DirtySock: HttpCallback Class Reference
HttpCallback Class Reference
Public Member Functions
HttpCallback ()
HttpCallback constructor.
virtual ~HttpCallback ()
HttpCallback destructor.
STDMETHODIMP OnRedirect (IXMLHTTPRequest2 *pXHR, const WCHAR *pwszRedirectUrl)
STDMETHODIMP OnHeadersAvailable (IXMLHTTPRequest2 *pXHR, DWORD dwStatus, const WCHAR *pwszStatus)
STDMETHODIMP OnDataAvailable (IXMLHTTPRequest2 *pXHR, ISequentialStream *pResponseStream)
Part of the HTTP Data payload is available, we can start processing it here or copy it off and wait for the whole request to finish loading.
STDMETHODIMP OnResponseReceived (IXMLHTTPRequest2 *pXHR, ISequentialStream *pResponseStream)
Called when the entire body has been received.
STDMETHODIMP OnError (IXMLHTTPRequest2 *pXHR, HRESULT hrError)
Handle errors that have occurred during the HTTP request.
ProtoHttpXmlHttpT * GetXmlHttp ()
Get XmlHttp object reference.
void SetXmlHttp (ProtoHttpXmlHttpT *pXmlHttp)
Set XmlHttp object reference.
Related Functions
(Note that these are not member functions.)
IFACEMETHODIMP OnRedirect (IXMLHTTPRequest2 *pXHR, const wchar_t *pRedirectUrl)
The requested URI was redirected by the HTTP server to a new URI.
IFACEMETHODIMP OnHeadersAvailable (IXMLHTTPRequest2 *pXHR, DWORD dwStatus, const wchar_t *pwszStatus)
The HTTP Headers have been downloaded and are ready for parsing. The string that is returned is owned by this function and should be copied or deleted before exit.
Constructor & Destructor Documentation
HttpCallback ()
HttpCallback constructor.
Version
11/01/2012 (akirchner)
~HttpCallback () virtual
HttpCallback destructor.
Version
11/01/2012 (akirchner)
Member Function Documentation
ProtoHttpXmlHttpT * GetXmlHttp ()
Get XmlHttp object reference.
Returns
ProtoHttpXmlHttpT * - Pointer to reference
Version
07/02/2013 (jbrookes)
Referenced by OnDataAvailable(), OnError(), OnHeadersAvailable(), OnRedirect(), and OnResponseReceived().
IFACEMETHODIMP OnDataAvailable (IXMLHTTPRequest2 * pXHR, ISequentialStream * pResponseStream)
Part of the HTTP Data payload is available, we can start processing it here or copy it off and wait for the whole request to finish loading.
Parameters
*pXHR - Pointer to the originating IXMLHTTPRequest2 object.
*pResponseStream - Pointer to the input stream, which may only be part of the whole stream.
Returns
IFACEMETHODIMP - S_OK = success
Version
07/12/2013 (jbrookes)
References ProtoHttpXmlHttpT::bDestroyed, ProtoHttpRefT::critical, DirtyMemAlloc(), DirtyMemFree(), ds_memcpy(), GetXmlHttp(), ProtoHttpBufferT::iInpLen, ProtoHttpBufferT::iInpMax, ProtoHttpBufferT::iInpTotal, ProtoHttpRefT::iMemGroup, ProtoHttpRefT::iOnDataThreshold, ProtoHttpXmlHttpT::iVerbose, ProtoHttpRefT::iVerbose, ProtoHttpCriticalT::Locker, NetCritEnter(), NetCritLeave(), NetPrintfVerbose, ProtoHttpBufferT::pInpBuf, ProtoHttpRefT::pMemGroupUserData, PROTOHTTP_MEMID, ProtoHttpXmlHttpT::pState, ProtoHttpRefT::RecvRate, ProtoHttpCriticalT::responseBuffer, SocketRateThrottle(), and SocketRateUpdate().
Referenced by OnResponseReceived().
IFACEMETHODIMP OnError (IXMLHTTPRequest2 * pXHR, HRESULT hError)
Handle errors that have occurred during the HTTP request.
Parameters
*pXHR - The interface pointer of IXMLHTTPRequest2 object
hError - The errorcode for the httprequest
Returns
IFACEMETHODIMP - S_OK = success
Version
07/12/2013 (jbrookes)
References ProtoHttpCriticalT::bAbortingRedirection, ProtoHttpCriticalT::bBodyReceived, ProtoHttpXmlHttpT::bComplete, ProtoHttpCriticalT::bHeaderReceived, ProtoHttpCriticalT::bRedirBugWorkaround, ProtoHttpRefT::critical, DirtyErrGetName(), ProtoHttpCriticalT::eRequestState, ProtoHttpRefT::eRequestType, GetXmlHttp(), ProtoHttpRefT::iMaxRedirect, NetPrintf, PROTOHTTP_REQUESTTYPE_POST, PROTOHTTP_REQUESTTYPE_PUT, ProtoHttpXmlHttpT::pState, ST_FAIL, ProtoHttpRefT::strLocation, and TRUE.
STDMETHODIMP HttpCallback::OnHeadersAvailable (IXMLHTTPRequest2 * pXHR, DWORD dwStatus, const WCHAR * pwszStatus)
STDMETHODIMP HttpCallback::OnRedirect (IXMLHTTPRequest2 * pXHR, const WCHAR * pwszRedirectUrl)
IFACEMETHODIMP OnResponseReceived (IXMLHTTPRequest2 * pXHR, ISequentialStream * pResponseStream)
Called when the entire body has been received.
Parameters
*pXHR - Pointer to the originating IXMLHTTPRequest2 object.
*pResponseStream - Pointer to the complete input stream.
Returns
IFACEMETHODIMP - S_OK = success
Version
07/12/2013 (jbrookes)
References ProtoHttpCriticalT::bBodyReceived, ProtoHttpXmlHttpT::bComplete, ProtoHttpRefT::critical, GetXmlHttp(), ProtoHttpXmlHttpT::iVerbose, ProtoHttpRefT::iVerbose, ProtoHttpCriticalT::Locker, NetCritEnter(), NetCritLeave(), NetPrintfVerbose, OnDataAvailable(), ProtoHttpXmlHttpT::pState, and TRUE.
void SetXmlHttp (ProtoHttpXmlHttpT * pXmlHttp)
Set XmlHttp object reference.
Parameters
pXmlHttp - xmlhttp object reference
Version
07/02/2013 (jbrookes)
Friends And Related Function Documentation
IFACEMETHODIMP OnHeadersAvailable (IXMLHTTPRequest2 * pXHR, DWORD dwStatus, const wchar_t * pwszStatus) related
The HTTP Headers have been downloaded and are ready for parsing. The string that is returned is owned by this function and should be copied or deleted before exit.
Parameters
*pXHR - The interface pointer of originating IXMLHTTPRequest2 object.
dwStatus - The value of HTTP status code, e.g. 200, 404
*pwszStatus - The description text of HTTP status code.
Returns
IFACEMETHODIMP - S_OK = success
Version
07/12/2013 (jbrookes)
References ProtoHttpXmlHttpT::bDestroyed, ProtoHttpCriticalT::bHeaderReceived, ProtoHttpRefT::critical, ProtoHttpCriticalT::eRequestState, GetXmlHttp(), ProtoHttpXmlHttpT::iVerbose, ProtoHttpCriticalT::Locker, NetCritEnter(), NetCritLeave(), NetPrintfVerbose, ProtoHttpXmlHttpT::pState, ST_FAIL, and TRUE.
IFACEMETHODIMP OnRedirect (IXMLHTTPRequest2 * pXHR, const wchar_t * pRedirectUrl) related
The requested URI was redirected by the HTTP server to a new URI.
Parameters
*pXHR - The interface pointer of originating IXMLHTTPRequest2 object.
*pRedirectUrl - The new URL to for the request.
Returns
IFACEMETHODIMP - S_OK = success
Version
07/12/2013 (jbrookes)
References ProtoHttpCriticalT::bAbortingRedirection, ProtoHttpXmlHttpT::bDestroyed, ProtoHttpRefT::critical, ds_snzprintf(), GetXmlHttp(), ProtoHttpBufferT::iInpLen, ProtoHttpBufferT::iInpMax, ProtoHttpRefT::iMaxRedirect, ProtoHttpCriticalT::iNumRedirect, ProtoHttpXmlHttpT::iVerbose, ProtoHttpCriticalT::Locker, NetCritEnter(), NetCritLeave(), NetPrintf, NetPrintfVerbose, ProtoHttpBufferT::pInpBuf, ProtoHttpXmlHttpT::pState, ProtoHttpCriticalT::responseBuffer, ProtoHttpRefT::strLocation, and TRUE.
The documentation for this class was generated from the following file:
protohttpxboxone.cpp
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:34:39