DirtySock: voipheadsetps4.c File Reference
voipheadsetps4.c File Reference
VoIP headset manager.
#include <string.h>
#include <scebase_common.h>
#include <voice.h>
#include <audioin.h>
#include <audioout.h>
#include <user_service.h>
#include "DirtySDK/platform.h"
#include "DirtySDK/dirtysock.h"
#include "DirtySDK/dirtysock/dirtymem.h"
#include "DirtySDK/dirtysock/dirtyerr.h"
#include "DirtySDK/dirtysock/netconn.h"
#include "DirtySDK/voip/voipdef.h"
#include "voippriv.h"
#include "voippacket.h"
#include "voipheadset.h"
Data Structures
struct PS4DecoderT
< decoder data space (used to wrap a lib voice IN_VOICE port)
struct PS4LocalVoipUserT
struct PS4RemoteVoipUserT
struct VoipHeadsetRefT
voipheadset module state data
Macros
#define VOIPHEADSET_INVALID_INDEX (-1)
#define VOIPHEADSET_DECODER_OWNERSHIP_AGING (1 * 1000)
#define VOIPHEADSET_DEBUG (DIRTYCODE_DEBUG && FALSE)
#define VOIPHEADSET_VOICELIB_DEFAULT_ENCODER_BITRATE (SCE_VOICE_BITRATE_16000)
Functions
VoipHeadsetRefT * VoipHeadsetCreate (int32_t iMaxChannels, VoipHeadsetMicDataCbT *pMicDataCb, VoipHeadsetStatusCbT *pStatusCb, void *pCbUserData, int32_t iAttr)
Create the headset manager.
void VoipHeadsetDestroy (VoipHeadsetRefT *pHeadset)
Destroy the headset manager.
void VoipHeadsetReceiveVoiceDataCb (VoipUserT *pRemoteUsers, VoipMicrInfoT *pMicrInfo, uint8_t *pPacketData, void *pUserData)
Connectionlist callback to handle receiving a voice packet from a remote peer.
void VoipHeadsetRegisterUserCb (VoipUserT *pRemoteUser, uint32_t bRegister, void *pUserData)
Connectionlist callback to register a new remote user with the 1st party voice system.
void VoipHeadsetProcess (VoipHeadsetRefT *pHeadset, uint32_t uFrameCount)
Headset process function.
void VoipHeadsetSetVolume (VoipHeadsetRefT *pHeadset, int32_t iPlayVol, uint32_t iRecVol)
Sets play and record volume.
int32_t VoipHeadsetControl (VoipHeadsetRefT *pHeadset, int32_t iControl, int32_t iValue, int32_t iValue2, void *pValue)
Control function.
int32_t VoipHeadsetStatus (VoipHeadsetRefT *pHeadset, int32_t iSelect, int32_t iValue, void *pBuf, int32_t iBufSize)
Status function.
void VoipHeadsetSpkrCallback (VoipHeadsetRefT *pHeadset, VoipSpkrCallbackT *pCallback, void *pUserData)
Set speaker output callback.
Detailed Description
VoIP headset manager.
Attention
Copyright (c) Electronic Arts 2013. ALL RIGHTS RESERVED.
Version
01/16/2013 (mclouatre) First Version
Macro Definition Documentation
#define VOIPHEADSET_DEBUG (DIRTYCODE_DEBUG && FALSE)
#define VOIPHEADSET_DECODER_OWNERSHIP_AGING (1 * 1000)
#define VOIPHEADSET_INVALID_INDEX (-1)
Referenced by VoipHeadsetReceiveVoiceDataCb(), and VoipHeadsetRegisterUserCb().
#define VOIPHEADSET_VOICELIB_DEFAULT_ENCODER_BITRATE (SCE_VOICE_BITRATE_16000)
Referenced by VoipHeadsetCreate().
Function Documentation
int32_t VoipHeadsetControl (VoipHeadsetRefT * pHeadset, int32_t iControl, int32_t iValue, int32_t iValue2, void * pValue)
Control function.
Parameters
*pHeadset - headset module state
iControl - control selector
iValue - control value
iValue2 - control value
*pValue - control value
Returns
int32_t - selector specific, or -1 if no such selector
Note
iControl can be one of the following:
        '+pbk' - enable voice playback for a given remote user (pValue is the remote user VoipUserT).
        '-pbk' - disable voice playback for a given remote user (pValue is the remote user VoipUserT).
        'aloc' - activate/deactivate local user (enter/exit "participating" state)
        'epbs' - modified encoding bps generation configuration
        'loop' - enable/disable loopback
        'rloc' - register/unregister local user
        'spam' - debug verbosity level
Version
16/01/2013 (mclouatre)
References VoipHeadsetRefT::aRemoteUsers, VoipHeadsetRefT::bDecoderConnUpdateNeeded, VoipHeadsetRefT::bLoopback, FALSE, VoipHeadsetRefT::iMaxRemoteUsers, NetPrintf, VoipUserT::strUserId, TRUE, PS4RemoteVoipUserT::uEnablePlayback, PS4RemoteVoipUserT::user, VOIP_MAXLOCALUSERS, and VOIP_SameUser.
Referenced by VoipCommonControl(), and VoipControl().
VoipHeadsetRefT* VoipHeadsetCreate (int32_t iMaxChannels, VoipHeadsetMicDataCbT * pMicDataCb, VoipHeadsetStatusCbT * pStatusCb, void * pCbUserData, int32_t iAttr)
Create the headset manager.
Parameters
iMaxChannels - max number of remote users
*pMicDataCb - pointer to user callback to trigger when mic data is ready
*pStatusCb - pointer to user callback to trigger when headset status changes
*pCbUserData - pointer to user callback data
iAttr - platform-specific - use to specify the voice lib thread attributes on PS4
Returns
VoipHeadsetRefT * - pointer to module state, or NULL if an error occured
Note
        Valid value for iAttr:
        The higher 16 bit is the CPU Affinity value. The lower 16 bits is the scheduling priority.
        For example iAttr = (SCE_KERNEL_CPUMASK_USER_ALL << 16) | SCE_KERNEL_PRIO_FIFO_HIGHEST.
Version
16/01/2013 (mclouatre)
References VoipHeadsetRefT::cpuAffinity, DirtyMemAlloc(), DirtyMemFree(), VoipHeadsetRefT::iDecoderPoolSize, VoipHeadsetRefT::iEncoderBps, VoipHeadsetRefT::iMaxChannels, VoipHeadsetRefT::iMaxRemoteUsers, VoipHeadsetRefT::iSchedPriority, NetConnStatus(), NetPrintf, NetPrintfVerbose, NetTick(), NetTickDiff, VoipHeadsetRefT::pCbUserData, VoipHeadsetRefT::pDecoders, VoipHeadsetRefT::pMicDataCb, VoipHeadsetRefT::pStatusCb, VOIP_MAX_LOW_LEVEL_CONNS, VOIP_MAXCONNECT, VOIP_MEMID, VOIPHEADSET_VOICELIB_DEFAULT_ENCODER_BITRATE, and VoipMemGroupQuery().
Referenced by VoipCommonStartup().
void VoipHeadsetDestroy (VoipHeadsetRefT * pHeadset)
Destroy the headset manager.
Parameters
*pHeadset - pointer to headset state
Version
16/01/2013 (mclouatre)
References VoipHeadsetRefT::aLocalUsers, PS4LocalVoipUserT::bParticipating, PS4DecoderT::bValid, DirtyMemFree(), VoipHeadsetRefT::iDecoderPoolSize, VoipHeadsetRefT::pDecoders, PS4DecoderT::uDecoderPortId, PS4LocalVoipUserT::user, VOIP_MAXLOCALUSERS, VOIP_MEMID, VOIP_NullUser, and VoipMemGroupQuery().
Referenced by VoipCommonShutdown().
void VoipHeadsetProcess (VoipHeadsetRefT * pHeadset, uint32_t uFrameCount)
Headset process function.
Parameters
*pHeadset - pointer to headset state
uFrameCount - current frame count
Version
16/01/2013 (mclouatre)
References VoipHeadsetRefT::bDecoderConnUpdateInProgress, VoipHeadsetRefT::bDecoderConnUpdateNeeded, FALSE, TRUE, and VoipHeadsetStatus().
void VoipHeadsetReceiveVoiceDataCb (VoipUserT * pRemoteUsers, VoipMicrInfoT * pMicrInfo, uint8_t * pPacketData, void * pUserData)
Connectionlist callback to handle receiving a voice packet from a remote peer.
Parameters
*pRemoteUsers - user we're receiving the voice data from
*pMicrInfo - micr info from inbound packet
*pPacketData - pointer to beginning of data in packet payload
*pUserData - VoipHeadsetT ref
Version
16/01/2013 (mclouatre)
References VoipHeadsetRefT::aRemoteUsers, PS4RemoteVoipUserT::iDecoderIndex, VoipHeadsetRefT::iMaxRemoteUsers, NetPrintf, NetPrintfVerbose, NetTick(), VoipHeadsetRefT::pDecoders, VoipUserT::strUserId, TRUE, PS4DecoderT::uConnectedSpkrPort, PS4DecoderT::uDecoderPortId, PS4DecoderT::uLastUsage, VoipMicrInfoT::uNumSubPackets, PS4RemoteVoipUserT::user, VoipMicrInfoT::uSubPacketSize, VoipMicrInfoT::uUserIndex, VOIP_SameUser, and VOIPHEADSET_INVALID_INDEX.
Referenced by VoipCommonStartup().
void VoipHeadsetRegisterUserCb (VoipUserT * pRemoteUser, uint32_t bRegister, void * pUserData)
Connectionlist callback to register a new remote user with the 1st party voice system.
Parameters
*pRemoteUser - user to register
bRegister - true=register, false=unregister
*pUserData - voipheadset module ref
Version
16/01/2013 (mclouatre)
References VoipHeadsetRefT::aRemoteUsers, VoipHeadsetRefT::bDecoderConnUpdateNeeded, PS4RemoteVoipUserT::iDecoderIndex, VoipHeadsetRefT::iMaxRemoteUsers, NetPrintf, VoipUserT::strUserId, TRUE, PS4RemoteVoipUserT::uEnablePlayback, PS4RemoteVoipUserT::user, VOIP_ClearUser, VOIP_CopyUser, VOIP_NullUser, VOIP_SameUser, and VOIPHEADSET_INVALID_INDEX.
Referenced by VoipCommonStartup().
void VoipHeadsetSetVolume (VoipHeadsetRefT * pHeadset, int32_t iPlayVol, uint32_t iRecVol)
Sets play and record volume.
Parameters
*pHeadset - pointer to headset state
iPlayVol - play volume to set
iRecVol - record volume to set
Note
To not set a value, specify it as -1.
Version
16/01/2013 (mclouatre)
void VoipHeadsetSpkrCallback (VoipHeadsetRefT * pHeadset, VoipSpkrCallbackT * pCallback, void * pUserData)
Set speaker output callback.
Parameters
*pHeadset - headset module state
*pCallback - what to call when output data is available
*pUserData - user data for callback
Version
16/01/2013 (mclouatre)
References VoipHeadsetRefT::pSpkrCbUserData, and VoipHeadsetRefT::pSpkrDataCb.
Referenced by VoipSpkrCallback().
int32_t VoipHeadsetStatus (VoipHeadsetRefT * pHeadset, int32_t iSelect, int32_t iValue, void * pBuf, int32_t iBufSize)
Status function.
Parameters
*pHeadset - headset module state
iSelect - control selector
iValue - selector specific
*pBuf - buffer pointer
iBufSize - buffer size
Returns
int32_t - selector specific, or -1 if no such selector
Note
iSelect can be one of the following:
        'camr' - return TRUE is the PS Camera Mic is in use.
        'ruid' - return TRUE if the given remote user (pBuf) is registered with voipheadset, FALSE if not.
        'sact' - return TRUE if shared device (PS Camera) is active
        'hpao' - return the audio device output flag for a given user index (iValue). IMPORTANT: value is not valid until something has been written to the outpout port
Version
16/01/2013 (mclouatre)
References VoipHeadsetRefT::aLocalUsers, VoipHeadsetRefT::aRemoteUsers, PS4LocalVoipUserT::bParticipating, DirtyErrGetName(), FALSE, VoipHeadsetRefT::iMaxRemoteUsers, NetPrintf, TRUE, VoipHeadsetRefT::uLastHeadsetStatus, PS4LocalVoipUserT::uMicPortId, PS4LocalVoipUserT::user, PS4RemoteVoipUserT::user, PS4LocalVoipUserT::uSpkrPortId, VOIP_MAXLOCALUSERS, VOIP_NullUser, and VOIP_SameUser.
Referenced by VoipCommonApplyChannelConfig(), VoipCommonStatus(), and VoipHeadsetProcess().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:15