DirtySock: Voip
Voip
The Voip module provides ...
Modules
VoipCodec
VoipDef
VoipGroup
VoipTunnel
Functions
DIRTYCODE_API VoipRefT * VoipStartup (int32_t iMaxPeers, int32_t iMaxLocal, int32_t iData)
Prepare VoIP for use.
DIRTYCODE_API VoipRefT * VoipGetRef (void)
Return current module reference.
DIRTYCODE_API void VoipShutdown (VoipRefT *pVoip, uint32_t uShutdownFlags)
Release all VoIP resources.
DIRTYCODE_API void VoipSetLocalUser (VoipRefT *pVoip, int32_t iLocalUserIndex, uint32_t bRegister)
Register/unregister specified local user with the voip sub-system.
DIRTYCODE_API void VoipActivateLocalUser (VoipRefT *pVoip, int32_t iLocalUserIndex, uint8_t bActivate)
Promote/demote specified local user to/from "participating" state.
DIRTYCODE_API void VoipSetEventCallback (VoipRefT *pVoip, VoipCallbackT *pCallback, void *pUserData)
Set Voip event callback notification handler.
DIRTYCODE_API int32_t VoipConnect (VoipRefT *pVoip, int32_t iConnID, uint32_t uAddress, uint32_t uManglePort, uint32_t uGamePort, uint32_t uClientId, uint32_t uSessionId)
Connect to a peer.
DIRTYCODE_API void VoipDisconnect (VoipRefT *pVoip, int32_t iConnID, uint32_t uAddress)
Disconnect from peer.
DIRTYCODE_API void VoipDisconnect2 (VoipRefT *pVoip, int32_t iConnID, uint32_t uAddress, int32_t bSendDiscMsg)
Disconnect from peer.
DIRTYCODE_API void VoipRemove (VoipRefT *pVoip, int32_t iConnID)
Remove connection from connectionlist (do not contract list).
DIRTYCODE_API int32_t VoipConnStatus (VoipRefT *pVoip, int32_t iConnID)
Return information about peer connection.
DIRTYCODE_API int32_t VoipRemoteUserStatus (VoipRefT *pVoip, int32_t iConnID, int32_t iRemoteUserIndex)
Return information about remote peer.
DIRTYCODE_API int32_t VoipLocalUserStatus (VoipRefT *pVoip, int32_t iLocalUserIndex)
Return information about local hardware state.
DIRTYCODE_API void VoipSpeaker (VoipRefT *pVoip, uint32_t uConnMask)
Select which peers to accept voice from.
DIRTYCODE_API void VoipMicrophone (VoipRefT *pVoip, uint32_t uConnMask)
Select which peers to send voice to.
DIRTYCODE_API int32_t VoipStatus (VoipRefT *pVoip, int32_t iSelect, int32_t iValue, void *pBuf, int32_t iBufSize)
Return status.
DIRTYCODE_API int32_t VoipControl (VoipRefT *pVoip, int32_t iControl, int32_t iValue, void *pValue)
Set control options.
DIRTYCODE_API int32_t VoipGetProfileStat (VoipRefT *pVoip, VoipProfStatE eProfStat)
Returns current profile data.
DIRTYCODE_API int32_t VoipGetProfileTime (VoipRefT *pVoip)
Returns current profile time from IOP.
DIRTYCODE_API void VoipSpkrCallback (VoipRefT *pVoip, VoipSpkrCallbackT *pCallback, void *pUserData)
Set speaker data callback (not supported on all platforms).
DIRTYCODE_API void VoipUpdate (VoipRefT *pVoip)
DIRTYCODE_API int32_t VoipSelectChannel (VoipRefT *pVoip, int32_t iUserIndex, int32_t iChannel, VoipChanModeE eMode)
Select the mode(send/recv) of a given channel.
DIRTYCODE_API void VoipResetChannels (VoipRefT *pVoip, int32_t iUserIndex)
Resets the channels selection to defaults. Sends and receives to all.
Detailed Description
The Voip module provides ...
Overview
Overview TBD
Function Documentation
DIRTYCODE_API void VoipActivateLocalUser (VoipRefT * pVoip, int32_t iLocalUserIndex, uint8_t bActivate)
Promote/demote specified local user to/from "participating" state.
Parameters
*pVoip - module state from VoipStartup
iLocalUserIndex - local user index
bActivate - TRUE to activate, FALSE to deactivate
Version
04/25/2013 (tcho)
References VoipConnectionlistT::aIsParticipating, VoipRefT::Common, VoipCommonRefT::Connectionlist, VoipConnectionlistT::LocalUsers, NETCONN_MAXLOCALUSERS, NetConnStatus(), NetCritEnter(), NetCritLeave(), NetPrintf, NULL, VoipCommonRefT::pHeadset, VoipCommonRefT::ThreadCrit, VOIP_NullUser, VoipCommonApplyChannelConfig(), VoipConnectionReliableBroadcastUser(), VoipHeadsetControl(), and VoipSerializeUser().
Referenced by VoipGroupActivateLocalUser(), and VoipSetLocalUser().
DIRTYCODE_API int32_t VoipConnect (VoipRefT * pVoip, int32_t iConnID, uint32_t uAddress, uint32_t uManglePort, uint32_t uGamePort, uint32_t uClientId, uint32_t uSessionId)
Connect to a peer.
Parameters
*pVoip - module state from VoipStartup
iConnID - [zero, iMaxPeers-1] for an explicit slot or VOIP_CONNID_NONE to auto-allocate
uAddress - remote peer address
uManglePort - port from demangler (should be identical to game port on Xenon)
uGamePort - port to connect on
uClientId - remote clientId to connect to (cannot be 0)
uSessionId - session identifier (optional)
Returns
int32_t - connection identifier (negative=error)
Version
1.0 03/02/2004 (jbrookes) first version
1.1 10/26/2009 (mclouatre) uClientId is no longer optional
References VoipCommonRefT::Connectionlist, NetCritEnter(), NetCritLeave(), VoipCommonRefT::ThreadCrit, and VoipConnectionStart().
Referenced by VoipGroupConnect(), and VoipGroupResume().
DIRTYCODE_API int32_t VoipConnStatus (VoipRefT * pVoip, int32_t iConnID)
Return information about peer connection.
Parameters
*pVoip - module state from VoipStartup
iConnID - which connection to get remote info for, or VOIP_CONNID_ALL
Returns
int32_t - VOIP_CONN* flags, or VOIP_FLAG_INVALID if iConnID is invalid
Version
05/06/2014 (amakoukji)
References VoipCommonRefT::Connectionlist, VoipConnectionlistT::iMaxConnections, NULL, VoipConnectionlistT::pConnections, VoipConnectionT::uRemoteConnStatus, VOIP_CONNID_ALL, and VOIP_FLAG_INVALID.
Referenced by VoipGroupConnStatus().
DIRTYCODE_API int32_t VoipControl (VoipRefT * pVoip, int32_t iControl, int32_t iValue, void * pValue)
Set control options.
Parameters
*pVoip - module state from VoipStartup
iControl - control selector
iValue - selector-specific input
*pValue - selector-specific input
Returns
int32_t - selector-specific output
Note
iControl can be one of the following:
        '+pbk' - enable voice playback for a given remote user (pValue is the remote user VoipUserT).
        '-pbk' - disable voice playback for a given remote user (pValue is the remote user VoipUserT).
        'pcsu' - takes iValue as a bool, TRUE suspend party chat, FALSE resume it.
            In order for VoipControl 'pcsu' to work you must add to the appxmanifest.xml:
            <mx:Extension Category="xbox.multiplayer">
                <mx:XboxMultiplayer CanSuppressPartyChat="true" />
            </mx:Extension>
Unhandled selectors are passed through to VoipCommonControl(), and further to VoipHeadsetControl() if unhandled there.
Version
05/24/2013 (mclouatre)
References VoipRefT::Common, NetPrintf, VoipCommonRefT::pHeadset, VoipCommonControl(), and VoipHeadsetControl().
Referenced by ConnApiControl(), VoipCommonApplyChannelConfig(), VoipCommonResetChannels(), VoipCommonSelectChannel(), VoipGroupConnect(), VoipGroupControl(), VoipGroupDisconnect(), VoipGroupResume(), VoipMicrophone(), and VoipSpeaker().
DIRTYCODE_API void VoipDisconnect (VoipRefT * pVoip, int32_t iConnID, uint32_t uAddress)
Disconnect from peer.
Parameters
*pVoip - module state from VoipStartup
iConnID - which connection to disconnect (VOIP_CONNID_ALL for all)
uAddress - remote peer address
Todo:
Remove VoipDisconnect() in favor of VoipDisconnect2()
Version
1.0 03/02/2004 (jbrookes) First Version
References TRUE, and VoipDisconnect2().
Referenced by VoipGroupDisconnect().
DIRTYCODE_API void VoipDisconnect2 (VoipRefT * pVoip, int32_t iConnID, uint32_t uAddress, int32_t bSendDiscMsg)
Disconnect from peer.
Parameters
*pVoip - module state from VoipStartup
iConnID - which connection to disconnect (VOIP_CONNID_ALL for all)
uAddress - remote peer address
bSendDiscMsg - TRUE if a voip disc pkt needs to be sent, FALSE otherwise
Todo:
Multiple connection support. Deprecate unused uAddress parameter Rename VoipDisconnect2() to VoipDisconnect() when current version of VoipDisconnect() is deprecated
Version
15/01/2014 (mclouatre)
References VoipCommonRefT::Connectionlist, NetCritEnter(), NetCritLeave(), VoipCommonRefT::ThreadCrit, and VoipConnectionStop().
Referenced by VoipDisconnect(), and VoipGroupSuspend().
DIRTYCODE_API int32_t VoipGetProfileStat (VoipRefT * pVoip, VoipProfStatE eProfStat)
Returns current profile data.
Parameters
*pVoip - module state from VoipStartup
eProfStat - type of profile data to get
Returns
int32_t - profile data
Version
1.0 03/02/2004 (jbrookes) First Version
DIRTYCODE_API int32_t VoipGetProfileTime (VoipRefT * pVoip)
Returns current profile time from IOP.
Parameters
*pVoip - module state from VoipStartup
Returns
int32_t - amount of time that elapsed during previous profiling cycle
Version
1.0 03/02/2004 (jbrookes) First Version
DIRTYCODE_API VoipRefT* VoipGetRef (void)
Return current module reference.
Returns
VoipRefT * - reference pointer, or NULL if the module is not active
Version
1.0 03/08/2004 (jbrookes) First Version
References VoipCommonGetRef().
Referenced by ConnApiOnline(), VoipCommonApplyChannelConfig(), VoipCommonResetChannels(), VoipCommonSelectChannel(), VoipConnectionSend(), VoipGroupActivateLocalUser(), VoipGroupConnect(), VoipGroupConnStatus(), VoipGroupControl(), VoipGroupDisconnect(), VoipGroupLocalUserStatus(), VoipGroupMuteByConnId(), VoipGroupRemoteUserStatus(), VoipGroupResume(), VoipGroupSetEventCallback(), VoipGroupStatus(), VoipGroupSuspend(), and VoipShutdown().
DIRTYCODE_API int32_t VoipLocalUserStatus (VoipRefT * pVoip, int32_t iLocalUserIndex)
Return information about local hardware state.
Parameters
*pVoip - module state from VoipStartup
iLocalUserIndex - local index of the user
Returns
int32_t - VOIP_LOCAL* flags
Version
1.0 03/02/2004 (jbrookes) First Version
2.0 04/25/2014 (amakoukji) Refactored for MLU
References VoipCommonRefT::Connectionlist, and VoipConnectionlistT::uLocalUserStatus.
Referenced by VoipGroupLocalUserStatus().
DIRTYCODE_API void VoipMicrophone (VoipRefT * pVoip, uint32_t uConnMask)
Select which peers to send voice to.
Parameters
*pVoip - module state from VoipStartup
uConnMask - bitmask indicating which connections to send to (or VOIP_CONNID_*)
Returns
None.
Note
On Xenon, user-specified recv masks take lower priority than muting and permissions managed by the HUD.
Version
1.0 03/02/2004 (jbrookes) First Version
References NULL, and VoipControl().
Referenced by VoipGroupConnect(), VoipGroupDisconnect(), VoipGroupMuteByConnId(), VoipGroupResume(), and VoipGroupSuspend().
DIRTYCODE_API int32_t VoipRemoteUserStatus (VoipRefT * pVoip, int32_t iConnID, int32_t iRemoteUserIndex)
Return information about remote peer.
Parameters
*pVoip - module state from VoipStartup
iConnID - which connection to get remote info for, or VOIP_CONNID_ALL
iRemoteUserIndex - user index at the connection iConnID
Returns
int32_t - VOIP_REMOTE* flags, or VOIP_FLAG_INVALID if iConnID is invalid
Version
05/06/2014 (amakoukji)
References VoipCommonRefT::Connectionlist, VoipConnectionlistT::iMaxConnections, NULL, VoipConnectionlistT::pConnections, VoipConnectionT::uRemoteUserStatus, VOIP_CONNID_ALL, and VOIP_FLAG_INVALID.
Referenced by VoipGroupRemoteUserStatus().
DIRTYCODE_API void VoipRemove (VoipRefT * pVoip, int32_t iConnID)
Remove connection from connectionlist (do not contract list).
Parameters
*pVoip - module state from VoipStartup
iConnID - which connection to remove from list
Version
1.0 06/14/2008 (jbrookes) First Version
References VoipCommonRefT::Connectionlist, NetCritEnter(), NetCritLeave(), VoipCommonRefT::ThreadCrit, and VoipConnectionRemove().
DIRTYCODE_API void VoipResetChannels (VoipRefT * pVoip, int32_t iUserIndex)
Resets the channels selection to defaults. Sends and receives to all.
Parameters
*pVoip - module ref
iUserIndex - local user index
Version
12/07/2009 (jrainy)
References VoipCommonResetChannels().
DIRTYCODE_API int32_t VoipSelectChannel (VoipRefT * pVoip, int32_t iUserIndex, int32_t iChannel, VoipChanModeE eMode)
Select the mode(send/recv) of a given channel.
Parameters
*pVoip - voip module state
iUserIndex - local user index
iChannel - Channel ID (valid range: [0,63])
eMode - The mode, combination of VOIP_CHANSEND, VOIP_CHANRECV
Returns
int32_t - number of channels remaining that this console could join
Version
01/31/2007 (jrainy)
References VoipCommonSelectChannel().
DIRTYCODE_API void VoipSetEventCallback (VoipRefT * pVoip, VoipCallbackT * pCallback, void * pUserData)
Set Voip event callback notification handler.
Parameters
*pVoip - module state from VoipStartup
*pCallback - event callback notification handler
*pUserData - user data for callback handler
Returns
None.
Version
02/10/2006 (jbrookes) first version
11/05/2009 (mclouatre) if pCallback is NULL, revert to default callback
References NULL, VoipCommonRefT::pCallback, and VoipCommonRefT::pUserData.
Referenced by VoipCommonStartup(), and VoipGroupSetEventCallback().
DIRTYCODE_API void VoipSetLocalUser (VoipRefT * pVoip, int32_t iLocalUserIndex, uint32_t bRegister)
Register/unregister specified local user with the voip sub-system.
Parameters
*pVoip - module state from VoipStartup
iLocalUserIndex - controller index of user
bRegister - TRUE to register, FALSE to unregister.
Version
05/24/2013 (mclouatre)
References VoipConnectionlistT::aIsParticipating, VoipRefT::Common, VoipCommonRefT::Connectionlist, ds_snzprintf(), FALSE, VoipConnectionlistT::LocalUsers, NetConnStatus(), NetCritEnter(), NetCritLeave(), NetPrintf, NULL, VoipUserT::strUserId, VoipCommonRefT::ThreadCrit, TRUE, VOIP_MAXLOCALUSERS, VOIP_NullUser, and VoipActivateLocalUser().
Referenced by VoipGroupControl().
DIRTYCODE_API void VoipShutdown (VoipRefT * pVoip, uint32_t uShutdownFlags)
Release all VoIP resources.
Parameters
*pVoip - module state from VoipStartup
uShutdownFlags - NET_SHUTDOWN_* flags
Version
05/24/2013 (mclouatre)
References VoipRefT::Common, FALSE, VoipRefT::hThread, VoipRefT::iThreadActive, NetPrintf, NULL, VoipCommonShutdown(), VoipGetRef(), and VoipSerializeTerm().
Referenced by ConnApiDestroy(), and VoipStartup().
DIRTYCODE_API void VoipSpeaker (VoipRefT * pVoip, uint32_t uConnMask)
Select which peers to accept voice from.
Parameters
*pVoip - module state from VoipStartup
uConnMask - bitmask indicating which connections to receive from (or VOIP_CONNID_*)
Returns
None.
Note
On Xenon, user-specified recv masks take lower priority than muting and permissions managed by the HUD.
Version
1.0 03/02/2004 (jbrookes) First Version
References NULL, and VoipControl().
Referenced by VoipGroupConnect(), VoipGroupDisconnect(), VoipGroupMuteByConnId(), VoipGroupResume(), and VoipGroupSuspend().
DIRTYCODE_API void VoipSpkrCallback (VoipRefT * pVoip, VoipSpkrCallbackT * pCallback, void * pUserData)
Set speaker data callback (not supported on all platforms).
Parameters
*pVoip - voip module state
*pCallback - data callback
*pUserData - user data
Version
12/12/2005 (jbrookes)
References VoipCommonRefT::pHeadset, and VoipHeadsetSpkrCallback().
DIRTYCODE_API VoipRefT* VoipStartup (int32_t iMaxPeers, int32_t iMaxLocal, int32_t iData)
Prepare VoIP for use.
Parameters
iMaxPeers - maximum number of peers supported (up to VOIP_MAXCONNECT)
iMaxLocal - maximum number of local users supported
iData - platform-specific - unused for xboxone
Returns
VoipRefT - state reference that is passed to all other functions
Version
05/24/2013 (mclouatre)
References VoipCommonRefT::bPrivileged, DirtyErrGetName(), VoipRefT::dwThreadId, VoipRefT::hThread, VoipRefT::iThreadActive, NetPrintf, NULL, TRUE, VoipCommonStartup(), VoipSerializeInit(), and VoipShutdown().
Referenced by ConnApiOnline().
DIRTYCODE_API int32_t VoipStatus (VoipRefT * pVoip, int32_t iSelect, int32_t iValue, void * pBuf, int32_t iBufSize)
Return status.
Parameters
*pVoip - module state from VoipStartup
iSelect - status selector
iValue - selector-specific
*pBuf - [out] storage for selector-specific output
iBufSize - size of output buffer
Returns
int32_t - selector-specific data
Note
iSelect can be one of the following:
        'hset' - bitfield indicating which ports have headsets
        'pcac' - returns true if party chat is active
        'pcsu' - returns true if party chat is currently suspended
        'thid' - returns handle of _VoipThread
Unhandled selectors are passed through to VoipCommonStatus(), and further to VoipHeadsetStatus() if unhandled there.
Version
05/24/2013 (mclouatre)
References VoipRefT::Common, VoipRefT::hThread, NetPrintf, and VoipCommonStatus().
Referenced by VoipCommonApplyChannelConfig(), VoipConnectionSend(), VoipGroupConnect(), VoipGroupResume(), and VoipGroupStatus().
DIRTYCODE_API void VoipUpdate (VoipRefT * pVoip)
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:21