DirtySock: voippriv.h File Reference
voippriv.h File Reference
Header for private VoIP functions.
Data Structures
struct VoipTimerT
struct VoipUserT
Macros
#define VOIP_CopyUser(_pUser1, _pUser2) (ds_memcpy_s(_pUser1, sizeof(*_pUser1), _pUser2, sizeof(*_pUser2)))
copy VoipUserTs
#define VOIP_ClearUser(_pUser1) (memset(_pUser1, 0, sizeof(*_pUser1)))
clear VoipUserT
#define VOIP_NullUser(_pUser1) ((_pUser1)->strUserId[0] == '\0')
return if VoipUserT is NULL or not
#define VOIP_SameUser(_pUser1, _pUser2) (!strcmp((_pUser1)->strUserId, (_pUser2)->strUserId))
compare VoipUserTs
Typedefs
typedef struct VoipTimerT VoipTimerT
typedef struct VoipUserT VoipUserT
Functions
uint32_t VoipTimer (VoipTimerT *pTimer)
Returns a high-resolution platform-dependent time value.
int32_t VoipTimerDiff (const VoipTimerT *pTimerA, const VoipTimerT *pTimerB)
Differences two timers (a-b).
void VoipMemGroupQuery (int32_t *pMemGroup, void **ppMemGroupUserData)
Get VoIP mem group data.
void VoipMemGroupSet (int32_t iMemGroup, void *pMemGroupUserData)
Set VoIP mem group data.
Detailed Description
Header for private VoIP functions.
Attention
Copyright (c) Electronic Arts 2004. ALL RIGHTS RESERVED.
Version
1.0 03/17/2004 (jbrookes) First Version
1.1 11/18/2008 (mclouatre) Adding user data concept to mem group support
Macro Definition Documentation
#define VOIP_ClearUser (_pUser1) (memset(_pUser1, 0, sizeof(*_pUser1)))
clear VoipUserT
Referenced by VoipConduitRegisterUser().
#define VOIP_CopyUser (_pUser1, _pUser2) (ds_memcpy_s(_pUser1, sizeof(*_pUser1), _pUser2, sizeof(*_pUser2)))
copy VoipUserTs
Referenced by VoipConduitRegisterUser(), and VoipSetLocalUser().
#define VOIP_NullUser (_pUser1) ((_pUser1)->strUserId[0] == '\0')
return if VoipUserT is NULL or not
Referenced by VoipActivateLocalUser(), VoipCommonStatus(), VoipConduitRegisterUser(), VoipConnectionRegisterRemoteTalkers(), and VoipSetLocalUser().
#define VOIP_SameUser (_pUser1, _pUser2) (!strcmp((_pUser1)->strUserId, (_pUser2)->strUserId))
compare VoipUserTs
Referenced by VoipConduitReceiveVoiceData(), and VoipConduitRegisterUser().
Typedef Documentation
typedef struct VoipTimerT VoipTimerT
typedef struct VoipUserT VoipUserT
Function Documentation
void VoipMemGroupQuery (int32_t * pMemGroup, void ** ppMemGroupUserData)
Get VoIP mem group data.
Parameters
*pMemGroup - [OUT param] pointer to variable to be filled with mem group id
**ppMemGroupUserData - [OUT param] pointer to variable to be filled with pointer to user data
Returns
None.
Version
1.0 11/11/2005 (jbrookes) First Version
1.1 11/18/2008 (mclouatre) returned values now passed in [OUT] parameters
Referenced by VoipCommonShutdown(), VoipCommonStatus(), VoipConduitCreate(), VoipConduitDestroy(), VoipConnectionShutdown(), VoipConnectionStartup(), VoipHeadsetCreate(), VoipHeadsetDestroy(), VoipMixerCreate(), and VoipMixerDestroy().
void VoipMemGroupSet (int32_t iMemGroup, void * pMemGroupUserData)
Set VoIP mem group data.
Parameters
iMemGroup - mem group to set
*pMemGroupUserData - user data associated with mem group
Returns
None.
Version
1.0 11/11/2005 (jbrookes) First Version
1.1 11/18/2008 (mclouatre) Adding second parameter (user data)
Referenced by VoipCommonStartup().
uint32_t VoipTimer (VoipTimerT * pTimer)
Returns a high-resolution platform-dependent time value.
Parameters
*pTimer - storage for timer value
Returns
None
Version
1.0 08/26/2004 (jbrookes) First Version
Referenced by VoipCodecDecode(), and VoipCodecEncode().
int32_t VoipTimerDiff (const VoipTimerT * pTimerA, const VoipTimerT * pTimerB)
Differences two timers (a-b).
Parameters
*pTimerA - pointer to first timer
*pTimerB - pointer to second timer
Returns
int32_t - TimerA - TimerB
Version
1.0 08/26/2004 (jbrookes) First Version
References VoipTimerT::uHi, and VoipTimerT::uLo.
Referenced by VoipCodecDecode(), and VoipCodecEncode().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:47