DirtySock: ProtoSSL
ProtoSSL
Proto
Data Structures
struct ProtoSSLCertIdentT
identity fields for X509 issuer/subject
struct ProtoSSLAlertDescT
alert info, returned by ProtoSSLStat() 'alrt' selector after an SSL alert has been received
struct ProtoSSLCertInfoT
cert info, returned by ProtoSSLStat() 'cert' selector after certificate failure
Macros
#define PROTOSSL_VERSION_SSLv3 (0x0300)
#define PROTOSSL_VERSION_TLS1_0 (0x0301)
#define PROTOSSL_VERSION_TLS1_1 (0x0302)
#define PROTOSSL_VERSION_TLS1_2 (0x0303)
#define PROTOSSL_ERROR_NONE (0)
no error
#define PROTOSSL_ERROR_DNS (-1)
DNS failure.
#define PROTOSSL_ERROR_CONN (-10)
TCP connection failure.
#define PROTOSSL_ERROR_CONN_SSL2 (-11)
connection attempt was using unsupported SSLv2 record format
#define PROTOSSL_ERROR_CONN_NOTSSL (-12)
connection attempt was not recognized as SSL
#define PROTOSSL_ERROR_CONN_MINVERS (-13)
request failed minimum protocol version restriction
#define PROTOSSL_ERROR_CONN_MAXVERS (-14)
request failed maximum protocol version restriction
#define PROTOSSL_ERROR_CONN_NOCIPHER (-15)
no supported cipher
#define PROTOSSL_ERROR_CERT_INVALID (-20)
certificate invalid
#define PROTOSSL_ERROR_CERT_HOST (-21)
certificate not issued to this host
#define PROTOSSL_ERROR_CERT_NOTRUST (-22)
certificate is not trusted (recognized)
#define PROTOSSL_ERROR_CERT_MISSING (-23)
certificate not provided in certificate message
#define PROTOSSL_ERROR_CERT_BADDATE (-24)
certificate date range validity check failed
#define PROTOSSL_ERROR_CERT_REQUEST (-25)
CA fetch request failed.
#define PROTOSSL_ERROR_SETUP (-30)
failure in secure setup
#define PROTOSSL_ERROR_SECURE (-31)
failure in secure connection after setup
#define PROTOSSL_ERROR_UNKNOWN (-32)
unknown failure
#define PROTOSSL_CIPHER_RSA_WITH_RC4_128_SHA (1)
#define PROTOSSL_CIPHER_RSA_WITH_RC4_128_MD5 (2)
#define PROTOSSL_CIPHER_RSA_WITH_AES_128_CBC_SHA (4)
#define PROTOSSL_CIPHER_RSA_WITH_AES_256_CBC_SHA (8)
#define PROTOSSL_CIPHER_RSA_WITH_AES_128_CBC_SHA256 (16)
#define PROTOSSL_CIPHER_RSA_WITH_AES_256_CBC_SHA256 (32)
#define PROTOSSL_CIPHER_RSA_WITH_AES_128_GCM_SHA256 (64)
#define PROTOSSL_CIPHER_RSA_WITH_AES_256_GCM_SHA384 (128)
#define PROTOSSL_CIPHER_ALL
all cipher suites
#define PROTOSSL_CLIENTCERT_NONE (0)
#define PROTOSSL_CLIENTCERT_OPTIONAL (1)
#define PROTOSSL_CLIENTCERT_REQUIRED (2)
#define PROTOSSL_HELLOEXTN_NONE (0)
#define PROTOSSL_HELLOEXTN_SERVERNAME (1)
#define PROTOSSL_HELLOEXTN_SIGALGS (2)
#define PROTOSSL_HELLOEXTN_ALPN (4)
#define PROTOSSL_HELLOEXTN_ALL
#define PROTOSSL_HELLOEXTN_DEFAULT (PROTOSSL_HELLOEXTN_ALL)
Typedefs
typedef struct ProtoSSLCertIdentT ProtoSSLCertIdentT
identity fields for X509 issuer/subject
typedef struct ProtoSSLAlertDescT ProtoSSLAlertDescT
alert info, returned by ProtoSSLStat() 'alrt' selector after an SSL alert has been received
typedef struct ProtoSSLCertInfoT ProtoSSLCertInfoT
cert info, returned by ProtoSSLStat() 'cert' selector after certificate failure
typedef struct ProtoSSLRefT ProtoSSLRefT
Functions
DIRTYCODE_API int32_t ProtoSSLStartup (void)
Start up ProtoSSL. Used to create global state shared across SSL refs.
DIRTYCODE_API void ProtoSSLShutdown (void)
Shut down ProtoSSL. Cleans up global state.
DIRTYCODE_API ProtoSSLRefT * ProtoSSLCreate (void)
Allocate an SSL connection and prepare for use.
DIRTYCODE_API void ProtoSSLReset (ProtoSSLRefT *pState)
Reset connection back to unconnected state (will disconnect from server).
DIRTYCODE_API void ProtoSSLDestroy (ProtoSSLRefT *pState)
Destroy the module and release its state. Will disconnect from the server if required.
DIRTYCODE_API void ProtoSSLUpdate (ProtoSSLRefT *pState)
Give time to module to do its thing (should be called periodically to allow module to perform work). Calling once per 100ms or so should be enough.
DIRTYCODE_API ProtoSSLRefT * ProtoSSLAccept (ProtoSSLRefT *pState, int32_t iSecure, struct sockaddr *pAddr, int32_t *pAddrlen)
Accept an incoming connection.
DIRTYCODE_API int32_t ProtoSSLBind (ProtoSSLRefT *pState, const struct sockaddr *pAddr, int32_t pAddrlen)
Create a socket bound to the given address.
DIRTYCODE_API int32_t ProtoSSLConnect (ProtoSSLRefT *pState, int32_t iSecure, const char *pAddr, uint32_t uAddr, int32_t iPort)
Make a secure connection to an SSL server.
DIRTYCODE_API int32_t ProtoSSLDisconnect (ProtoSSLRefT *pState)
Disconnect from the server.
DIRTYCODE_API int32_t ProtoSSLListen (ProtoSSLRefT *pState, int32_t iBacklog)
Start listening for an incoming connection.
DIRTYCODE_API int32_t ProtoSSLSend (ProtoSSLRefT *pState, const char *pBuffer, int32_t iLength)
Send data to the server over secure TCP connection (actually, whether the connection is secure or not is determined by the secure flag passed during the SSLConnect call).
DIRTYCODE_API int32_t ProtoSSLRecv (ProtoSSLRefT *pState, char *pBuffer, int32_t iLength)
Receive data from the server.
DIRTYCODE_API int32_t ProtoSSLStat (ProtoSSLRefT *pState, int32_t iSelect, void *pBuffer, int32_t iLength)
Return the current module status (according to selector)
DIRTYCODE_API int32_t ProtoSSLControl (ProtoSSLRefT *pState, int32_t iSelect, int32_t iValue, int32_t iValue2, void *pValue)
ProtoSSL control function. Different selectors control different behaviors.
DIRTYCODE_API int32_t ProtoSSLSetCACert (const uint8_t *pCACert, int32_t iCertSize)
Add one or more X.509 CA certificates to the trusted list. A certificate added will be available to all ProtoSSL instances for the lifetime of the application. This function can add one or more PEM certificates or a single DER certificate.
DIRTYCODE_API int32_t ProtoSSLSetCACert2 (const uint8_t *pCACert, int32_t iCertSize)
Add one or more X.509 CA certificates to the trusted list. A certificate added will be available to all ProtoSSL instances for the lifetime of the application. This function can add one or more PEM certificates or a single DER certificate.
DIRTYCODE_API int32_t ProtoSSLValidateAllCA (void)
Validate all CA that have been added but not yet been validated. Validation is a one-time process and disposes of the X509 certificate that is retained until validation.
DIRTYCODE_API void ProtoSSLClrCACerts (void)
Clears all dynamic CA certs from the list.
Detailed Description
Macro Definition Documentation
#define PROTOSSL_CIPHER_ALL
Value:
(\
    PROTOSSL_CIPHER_RSA_WITH_RC4_128_SHA|PROTOSSL_CIPHER_RSA_WITH_RC4_128_MD5|\
    PROTOSSL_CIPHER_RSA_WITH_AES_128_CBC_SHA|PROTOSSL_CIPHER_RSA_WITH_AES_256_CBC_SHA|\
    PROTOSSL_CIPHER_RSA_WITH_AES_128_CBC_SHA256|PROTOSSL_CIPHER_RSA_WITH_AES_256_CBC_SHA256|\
    PROTOSSL_CIPHER_RSA_WITH_AES_128_GCM_SHA256|PROTOSSL_CIPHER_RSA_WITH_AES_256_GCM_SHA384)
all cipher suites
Referenced by ProtoHttpServCreate2(), and ProtoSSLCreate().
#define PROTOSSL_CIPHER_RSA_WITH_AES_128_CBC_SHA (4)
#define PROTOSSL_CIPHER_RSA_WITH_AES_128_CBC_SHA256 (16)
#define PROTOSSL_CIPHER_RSA_WITH_AES_128_GCM_SHA256 (64)
#define PROTOSSL_CIPHER_RSA_WITH_AES_256_CBC_SHA (8)
#define PROTOSSL_CIPHER_RSA_WITH_AES_256_CBC_SHA256 (32)
#define PROTOSSL_CIPHER_RSA_WITH_AES_256_GCM_SHA384 (128)
#define PROTOSSL_CIPHER_RSA_WITH_RC4_128_MD5 (2)
Referenced by ProtoSSLControl(), and ProtoSSLCreate().
#define PROTOSSL_CIPHER_RSA_WITH_RC4_128_SHA (1)
Referenced by ProtoSSLControl(), and ProtoSSLCreate().
#define PROTOSSL_CLIENTCERT_NONE (0)
#define PROTOSSL_CLIENTCERT_OPTIONAL (1)
#define PROTOSSL_CLIENTCERT_REQUIRED (2)
#define PROTOSSL_ERROR_CERT_BADDATE (-24)
certificate date range validity check failed
Referenced by ProtoSSLStat().
#define PROTOSSL_ERROR_CERT_HOST (-21)
certificate not issued to this host
Referenced by ProtoSSLStat().
#define PROTOSSL_ERROR_CERT_INVALID (-20)
certificate invalid
Referenced by ProtoSSLStat().
#define PROTOSSL_ERROR_CERT_MISSING (-23)
certificate not provided in certificate message
Referenced by ProtoSSLStat().
#define PROTOSSL_ERROR_CERT_NOTRUST (-22)
certificate is not trusted (recognized)
Referenced by ProtoSSLStat().
#define PROTOSSL_ERROR_CERT_REQUEST (-25)
CA fetch request failed.
Referenced by ProtoSSLStat().
#define PROTOSSL_ERROR_CONN (-10)
TCP connection failure.
Referenced by ProtoSSLStat().
#define PROTOSSL_ERROR_CONN_MAXVERS (-14)
request failed maximum protocol version restriction
Referenced by ProtoSSLStat().
#define PROTOSSL_ERROR_CONN_MINVERS (-13)
request failed minimum protocol version restriction
Referenced by ProtoSSLStat().
#define PROTOSSL_ERROR_CONN_NOCIPHER (-15)
no supported cipher
Referenced by ProtoSSLStat().
#define PROTOSSL_ERROR_CONN_NOTSSL (-12)
connection attempt was not recognized as SSL
Referenced by ProtoSSLStat().
#define PROTOSSL_ERROR_CONN_SSL2 (-11)
connection attempt was using unsupported SSLv2 record format
Referenced by ProtoSSLStat().
#define PROTOSSL_ERROR_DNS (-1)
DNS failure.
Referenced by ProtoSSLStat().
#define PROTOSSL_ERROR_NONE (0)
no error
#define PROTOSSL_ERROR_SECURE (-31)
failure in secure connection after setup
Referenced by ProtoSSLStat().
#define PROTOSSL_ERROR_SETUP (-30)
failure in secure setup
Referenced by ProtoSSLStat().
#define PROTOSSL_ERROR_UNKNOWN (-32)
unknown failure
Referenced by ProtoSSLStat().
#define PROTOSSL_HELLOEXTN_ALL
Value:
(\
    PROTOSSL_HELLOEXTN_SERVERNAME|PROTOSSL_HELLOEXTN_SIGALGS|PROTOSSL_HELLOEXTN_ALPN)
#define PROTOSSL_HELLOEXTN_ALPN (4)
#define PROTOSSL_HELLOEXTN_DEFAULT (PROTOSSL_HELLOEXTN_ALL)
Referenced by ProtoSSLCreate().
#define PROTOSSL_HELLOEXTN_NONE (0)
#define PROTOSSL_HELLOEXTN_SERVERNAME (1)
#define PROTOSSL_HELLOEXTN_SIGALGS (2)
#define PROTOSSL_VERSION_SSLv3 (0x0300)
#define PROTOSSL_VERSION_TLS1_0 (0x0301)
#define PROTOSSL_VERSION_TLS1_1 (0x0302)
#define PROTOSSL_VERSION_TLS1_2 (0x0303)
Typedef Documentation
typedef struct ProtoSSLAlertDescT ProtoSSLAlertDescT
alert info, returned by ProtoSSLStat() 'alrt' selector after an SSL alert has been received
typedef struct ProtoSSLCertIdentT ProtoSSLCertIdentT
identity fields for X509 issuer/subject
typedef struct ProtoSSLCertInfoT ProtoSSLCertInfoT
cert info, returned by ProtoSSLStat() 'cert' selector after certificate failure
typedef struct ProtoSSLRefT ProtoSSLRefT
Function Documentation
DIRTYCODE_API ProtoSSLRefT* ProtoSSLAccept (ProtoSSLRefT * pState, int32_t iSecure, struct sockaddr * pAddr, int32_t * pAddrlen)
Accept an incoming connection.
Parameters
*pState - module state reference
iSecure - flag indicating use of secure connection: 1=secure, 0=unsecure
*pAddr - where the client's address should be written
*pAddrlen - the length of the client's address space
Returns
ProtoSSLRefT * - accepted connection or NULL if not available
Version
10/27/2013 (jbrookes)
References ProtoSSLRefT::bServer, DirtyMemGroupEnter(), DirtyMemGroupLeave(), ds_memcpy(), ProtoSSLRefT::iClosed, ProtoSSLRefT::iMemGroup, ProtoSSLRefT::iState, ProtoSSLRefT::PeerAddr, ProtoSSLRefT::pMemGroupUserData, ProtoSSLCreate(), ProtoSSLDestroy(), ProtoSSLRefT::pSecure, ProtoSSLRefT::pSock, SOCKERR_NONE, SocketAccept(), SocketClose(), SocketInfo(), ST3_RECV_HELLO, ST_UNSECURE, and TRUE.
DIRTYCODE_API int32_t ProtoSSLBind (ProtoSSLRefT * pState, const struct sockaddr * pAddr, int32_t iAddrlen)
Create a socket bound to the given address.
Parameters
*pState - module state reference
*pAddr - the IPv4 address
iAddrlen - the size of the IPv4 address.
Returns
int32_t - SOCKERR_xxx (zero=success, negative=failure)
Version
03/03/2004 (sbevan)
References ProtoSSLRefT::iLastSocketError, ProtoSSLRefT::pSock, SOCKERR_OTHER, SocketBind(), SocketClose(), SocketInfo(), and SocketOpen().
DIRTYCODE_API void ProtoSSLClrCACerts (void)
Clears all dynamic CA certs from the list.
Version
01/14/2009 (jbrookes)
References DirtyMemFree(), ProtoSSLCACertT::iMemGroup, ProtoSSLCACertT::pMemGroupUserData, ProtoSSLCACertT::pNext, PROTOSSL_MEMID, and ProtoSSLCACertT::pX509Cert.
Referenced by ProtoHttpClrCACerts().
DIRTYCODE_API int32_t ProtoSSLConnect (ProtoSSLRefT * pState, int32_t iSecure, const char * pAddr, uint32_t uAddr, int32_t iPort)
Make a secure connection to an SSL server.
Parameters
*pState - module state reference
iSecure - flag indicating use of secure connection (1=secure, 0=unsecure)
*pAddr - textual form of address (1.2.3.4 or www.ea.com)
uAddr - the IP address of the server (if not in textual form)
iPort - the TCP port of the server (if not in textual form)
Returns
int32_t - SOCKERR_xxx (zero=success, negative=failure)
Version
03/08/2002 (gschaefer)
References ProtoSSLRefT::bCertInfoSet, ProtoSSLRefT::CertInfo, DirtyCertStatus(), FALSE, ProtoSSLRefT::iState, NetPrintf, ProtoSSLRefT::PeerAddr, ProtoSSLRefT::pHost, ProtoSSLRefT::pSock, SockaddrInGetAddr, SockaddrInit, SockaddrInSetAddr, SockaddrInSetAddrText(), SockaddrInSetPort, SOCKERR_INVALID, SOCKERR_NONE, SOCKERR_NORSRC, SocketLookup(), SocketOpen(), ST_ADDR, ST_CONN, and ProtoSSLRefT::strHost.
Referenced by ProtoWebSocketConnect().
DIRTYCODE_API int32_t ProtoSSLControl (ProtoSSLRefT * pState, int32_t iSelect, int32_t iValue, int32_t iValue2, void * pValue)
ProtoSSL control function. Different selectors control different behaviors.
Parameters
*pState - module state reference
iSelect - control selector
iValue - selector specific
iValue2 - selector specific
*pValue - selector specific
Returns
int32_t - selector specific
Note
Selectors are:
        SELECTOR    DESCRIPTION
        'alpn'      Set the ALPN protocols (using IANA registerd named) as a comma delimited list
        'ccrt'      Set client certificate level (0=disabled, 1=requested, 2=required)
        'ciph'      Set enabled/disabled ciphers (PROTOSSL_CIPHER_*)
        'extn'      Set enabled ClientHello extensions (PROTOSSL_HELLOEXTN_*), (default=0=disabled)
        'host'      Set remote host
        'maxr'      Set max recv rate (0=uncapped, default)
        'maxs'      Set max send rate (0=uncapped, default)
        'ncrt'      Disable client certificate validation
        'rbuf'      Set socket recv buffer size (must be called before Connect())
        'resu'      Set whether session resume is enabled or disabled (default=1=enabled)
        'sbuf'      Set socket send buffer size (must be called before Connect())
        'scrt'      Set certificate (pValue=cert, iValue=len)
        'secu'      Start secure negotiation on an established unsecure connection
        'skey'      Set private key (pValue=key, iValue=len)
        'skep'      Set socket keep-alive settings (iValue=enable/disable, iValue2=keep-alive time/interval)
        'spam'      Set debug logging level (default=1)
        'vers'      Set client-requested SSL version (default=0x302, TLS1.1)
        'vmin'      Set minimum SSL version application will accept
Version
01/27/2009 (jbrookes)
References ProtoSSLRefT::aAlpnProtocols, ProtoSSLRefT::bAllowAnyCert, ProtoSSLRefT::bKeepAlive, ProtoSSLRefT::bReuseAddr, ProtoSSLRefT::bSessionResumeEnabled, DS_CLAMP, ds_strnzcpy(), FALSE, ProtoSSLRefT::iCertificateLen, ProtoSSLRefT::iClientCertLevel, ProtoSSLRefT::iMaxRecvRate, ProtoSSLRefT::iMaxSendRate, ProtoSSLRefT::iPrivateKeyKen, ProtoSSLRefT::iRecvBufSize, ProtoSSLRefT::iSendBufSize, ProtoSSLRefT::iState, ProtoSSLRefT::iVerbose, NetPrintf, NetPrintfVerbose, ProtoSSLRefT::pCertificate, ProtoSSLRefT::pPrivateKey, PROTOSSL_CIPHER_RSA_WITH_RC4_128_MD5, PROTOSSL_CIPHER_RSA_WITH_RC4_128_SHA, ProtoSSLRefT::pSock, SocketControl(), SSL3_VERSION_MAX, SSL3_VERSION_MIN, SSL_ALPN_MAX_PROTOCOLS, ST3_SEND_HELLO, ST_UNSECURE, ProtoSSLRefT::strHost, AlpnProtocolT::strName, TRUE, ProtoSSLRefT::uAlpnExtensionLength, ProtoSSLRefT::uEnabledCiphers, ProtoSSLRefT::uHelloExtn, ProtoSSLRefT::uKeepAliveTime, AlpnProtocolT::uLength, ProtoSSLRefT::uNumAlpnProtocols, ProtoSSLRefT::uSslVersion, and ProtoSSLRefT::uSslVersionMin.
Referenced by ProtoHttpControl(), and ProtoWebSocketControl().
DIRTYCODE_API ProtoSSLRefT* ProtoSSLCreate (void)
Allocate an SSL connection and prepare for use.
Returns
ProtoSSLRefT * - module state; NULL=failure
Version
03/08/2002 (gschaefer)
References ProtoSSLRefT::bSessionResumeEnabled, DirtyMemAlloc(), DirtyMemGroupQuery(), ProtoSSLRefT::iLastSocketError, ProtoSSLRefT::iMemGroup, ProtoSSLRefT::iVerbose, NetCritInit(), NetPrintf, ProtoSSLRefT::pMemGroupUserData, PROTOSSL_CIPHER_ALL, PROTOSSL_CIPHER_RSA_WITH_RC4_128_MD5, PROTOSSL_CIPHER_RSA_WITH_RC4_128_SHA, PROTOSSL_HELLOEXTN_DEFAULT, PROTOSSL_MEMID, ProtoSSLRefT::SecureCrit, SOCKERR_NONE, SSL3_VERSION, SSL3_VERSION_MIN, SSL_VERBOSE_DEFAULT, TRUE, ProtoSSLRefT::uEnabledCiphers, ProtoSSLRefT::uHelloExtn, ProtoSSLRefT::uSslVersion, and ProtoSSLRefT::uSslVersionMin.
Referenced by ProtoHttpCreate(), ProtoSSLAccept(), and ProtoWebSocketCreate().
DIRTYCODE_API void ProtoSSLDestroy (ProtoSSLRefT * pState)
Destroy the module and release its state. Will disconnect from the server if required.
Parameters
*pState - module state reference
Version
03/08/2002 (gschaefer)
References DirtyMemFree(), ProtoSSLRefT::iMemGroup, NetCritKill(), ProtoSSLRefT::pMemGroupUserData, PROTOSSL_MEMID, and ProtoSSLRefT::SecureCrit.
Referenced by ProtoHttpDestroy(), ProtoHttpServDestroy(), ProtoSSLAccept(), and ProtoWebSocketDestroy().
DIRTYCODE_API int32_t ProtoSSLDisconnect (ProtoSSLRefT * pState)
Disconnect from the server.
Parameters
*pState - module state reference
Returns
int32_t - SOCKERR_xxx (zero=success, negative=failure)
Version
03/08/2002 (gschaefer)
References ProtoSSLRefT::bServer, DirtyCertCARequestFree(), ProtoSSLRefT::iCARequestId, ProtoSSLRefT::iClosed, ProtoSSLRefT::iState, ProtoSSLRefT::pSecure, ProtoSSLRefT::pSock, SOCK_NOSEND, SOCKERR_NONE, SocketClose(), SocketShutdown(), SSL3_ALERT_DESC_CLOSE_NOTIFY, SSL3_ALERT_LEVEL_WARNING, ST3_SECURE, and ST_IDLE.
DIRTYCODE_API int32_t ProtoSSLListen (ProtoSSLRefT * pState, int32_t iBacklog)
Start listening for an incoming connection.
Parameters
*pState - module state reference
iBacklog - number of pending connections allowed
Returns
int32_t - SOCKERR_xxx (zero=success, negative=failure)
Version
03/03/2004 (sbevan)
References ProtoSSLRefT::pSock, and SocketListen().
Referenced by ProtoHttpServCreate2().
DIRTYCODE_API int32_t ProtoSSLRecv (ProtoSSLRefT * pState, char * pBuffer, int32_t iLength)
Receive data from the server.
Parameters
*pState - module state reference
*pBuffer - receiver data
iLength - maximum buffer length
Returns
int32_t - negative=error, zero=nothing available, positive=bytes received
Version
03/08/2002 (gschaefer)
References ds_memcpy(), ProtoSSLRefT::iClosed, SecureStateT::iRecvBase, SecureStateT::iRecvProg, SecureStateT::iRecvSize, ProtoSSLRefT::iState, NetCritEnter(), NetCritLeave(), ProtoSSLUpdate(), ProtoSSLRefT::pSecure, ProtoSSLRefT::pSock, SecureStateT::RecvData, ProtoSSLRefT::SecureCrit, SOCKERR_CLOSED, SocketRecv, SSL3_REC_APPLICATION, SSL_MIN_PACKET, ST3_SECURE, ST_FAIL, and ST_UNSECURE.
DIRTYCODE_API void ProtoSSLReset (ProtoSSLRefT * pState)
Reset connection back to unconnected state (will disconnect from server).
Parameters
*pState - module state reference
Version
03/08/2002 (gschaefer)
DIRTYCODE_API int32_t ProtoSSLSend (ProtoSSLRefT * pState, const char * pBuffer, int32_t iLength)
Send data to the server over secure TCP connection (actually, whether the connection is secure or not is determined by the secure flag passed during the SSLConnect call).
Parameters
*pState - module state reference
*pBuffer - data to send
iLength - length of data (if negative, input data is assumed to be null-terminated string)
Returns
int32_t - negative=error, otherwise number of bytes sent
Version
06/03/2002 (gschaefer)
References SecureStateT::iSendSize, ProtoSSLRefT::iState, NetCritEnter(), NetCritLeave(), ProtoSSLUpdate(), ProtoSSLRefT::pSecure, ProtoSSLRefT::pSock, ProtoSSLRefT::SecureCrit, SOCKERR_CLOSED, SocketSend, SSL3_REC_APPLICATION, SSL_SNDLIM_PACKET, ST3_SECURE, and ST_UNSECURE.
DIRTYCODE_API int32_t ProtoSSLSetCACert (const uint8_t * pCertData, int32_t iCertSize)
Add one or more X.509 CA certificates to the trusted list. A certificate added will be available to all ProtoSSL instances for the lifetime of the application. This function can add one or more PEM certificates or a single DER certificate.
Parameters
*pCertData - pointer to certificate data (PEM or DER)
iCertSize - size of certificate data
Returns
int32_t - negative=error, positive=count of CAs added
Note
The certificate must be in .DER (binary) or .PEM (base64-encoded) format.
Version
01/13/2009 (jbrookes)
References TRUE.
Referenced by ProtoHttpSetCACert().
DIRTYCODE_API int32_t ProtoSSLSetCACert2 (const uint8_t * pCertData, int32_t iCertSize)
Add one or more X.509 CA certificates to the trusted list. A certificate added will be available to all ProtoSSL instances for the lifetime of the application. This function can add one or more PEM certificates or a single DER certificate.
This version of the function does not validate the CA at load time.
The X509 certificate data will be copied and retained until the CA
is validated, either by use of ProtoSSLValidateAllCA() or by the CA
being used to validate a certificate.
Parameters
*pCertData - pointer to certificate data (PEM or DER)
iCertSize - size of certificate data
Returns
int32_t - negative=error, positive=count of CAs added
Note
The certificate must be in .DER (binary) or .PEM (base64-encoded) format.
Version
04/21/2011 (jbrookes)
References FALSE.
Referenced by ProtoHttpSetCACert2().
DIRTYCODE_API void ProtoSSLShutdown (void)
Shut down ProtoSSL. Cleans up global state.
Version
09/14/2012 (jbrookes)
References CryptRandShutdown(), DirtyMemFree(), ProtoSSLStateT::iMemGroup, NetCritKill(), NetPrintf, ProtoSSLStateT::pMemGroupUserData, PROTOSSL_MEMID, and ProtoSSLStateT::StateCrit.
Referenced by NetConnShutdown().
DIRTYCODE_API int32_t ProtoSSLStartup (void)
Start up ProtoSSL. Used to create global state shared across SSL refs.
Returns
int32_t - negative=failure, else success
Version
09/14/2012 (jbrookes)
References CryptRandInit(), DirtyMemAlloc(), DirtyMemGroupQuery(), ProtoSSLStateT::iMemGroup, NetCritInit(), NetPrintf, ProtoSSLStateT::pMemGroupUserData, PROTOSSL_MEMID, and ProtoSSLStateT::StateCrit.
Referenced by NetConnStartup().
DIRTYCODE_API int32_t ProtoSSLStat (ProtoSSLRefT * pState, int32_t iSelect, void * pBuffer, int32_t iLength)
Return the current module status (according to selector)
Parameters
*pState - module state reference
iSelect - status selector ('conn'=return "am i connected" flag)
pBuffer - buffer pointer
iLength - buffer size
Returns
int32_t - negative=error, zero=false, positive=true
Note
Selectors are:
        SELECTOR    DESCRIPTION
        'addr'      Address of peer we are connecting/connected to
        'alpn'      Get the negotiated protocol using the ALPN extension from the secure state
        'alrt'      Return alert status 0=no alert, 1=recv alert, 2=sent alert; alert desc copied to pBuffer
        'cert'      Return SSL cert info (valid after 'fail')
        'cfip'      TRUE/FALSE indication if a CA fetch is in progress
        'ciph'      Cipher suite negotiated (string name in output buffer)
        'fail'      Return PROTOSSL_ERROR_* or zero if no error
        'hres'      Return hResult containing either the socket error or ssl error
        'htim'      Return timing of most recent SSL handshake in milliseconds
        'maxr'      Return max recv rate (0=uncapped)
        'maxs'      Return max send rate (0=uncapped)
        'recv'      Return number of bytes in recv buffer (secure only)
        'resu'      Returns whether session was resumed or not
        'rsao'      Returns whether we are performing any RSA operations at this time
        'send'      Return number of bytes in send buffer (secure only)
        'serr'      Return socket error
        'sock'      Copy SocketT ref to output buffer
        'stat'      Return like SocketInfo('stat')
        'vers'      Return current SSL version
Version
03/08/2002 (gschaefer)
References ProtoSSLRefT::bAlertSent, SecureStateT::bSessionResume, ProtoSSLRefT::CertInfo, DIRTYAPI_PROTO_SSL, DIRTYAPI_SOCKET, DirtyErrGetHResult(), ds_memcpy(), ds_strnzcpy(), FALSE, ProtoSSLRefT::iLastSocketError, ProtoSSLRefT::iMaxRecvRate, ProtoSSLRefT::iMaxSendRate, SecureStateT::iRecvProg, SecureStateT::iRecvSize, SecureStateT::iSendProg, SecureStateT::iSendSize, ProtoSSLRefT::iState, SecureStateT::pCipher, ProtoSSLRefT::PeerAddr, PROTOSSL_ERROR_CERT_BADDATE, PROTOSSL_ERROR_CERT_HOST, PROTOSSL_ERROR_CERT_INVALID, PROTOSSL_ERROR_CERT_MISSING, PROTOSSL_ERROR_CERT_NOTRUST, PROTOSSL_ERROR_CERT_REQUEST, PROTOSSL_ERROR_CONN, PROTOSSL_ERROR_CONN_MAXVERS, PROTOSSL_ERROR_CONN_MINVERS, PROTOSSL_ERROR_CONN_NOCIPHER, PROTOSSL_ERROR_CONN_NOTSSL, PROTOSSL_ERROR_CONN_SSL2, PROTOSSL_ERROR_DNS, PROTOSSL_ERROR_SECURE, PROTOSSL_ERROR_SETUP, PROTOSSL_ERROR_UNKNOWN, ProtoSSLRefT::pSecure, ProtoSSLRefT::pSock, SockaddrInGetAddr, SOCKERR_CLOSED, SocketInfo(), ST3_SECURE, ST3_SEND_KEY, ST3_SEND_VERIFY, ST_FAIL, ST_FAIL_CERT_BADDATE, ST_FAIL_CERT_HOST, ST_FAIL_CERT_INVALID, ST_FAIL_CERT_NONE, ST_FAIL_CERT_NOTRUST, ST_FAIL_CERT_REQUEST, ST_FAIL_CONN, ST_FAIL_CONN_MAXVERS, ST_FAIL_CONN_MINVERS, ST_FAIL_CONN_NOCIPHER, ST_FAIL_CONN_NOTSSL, ST_FAIL_CONN_SSL2, ST_FAIL_DNS, ST_FAIL_SECURE, ST_FAIL_SETUP, ST_WAIT_CA, SecureStateT::strAlpnProtocol, CipherSuiteT::strName, TRUE, ProtoSSLRefT::uAlertLevel, ProtoSSLRefT::uAlertValue, CipherSuiteT::uId, SecureStateT::uSslVersion, and SecureStateT::uTimer.
Referenced by ProtoHttpCheckKeepAlive(), ProtoHttpStatus(), ProtoHttpUpdate(), ProtoWebSocketStatus(), and ProtoWebSocketUpdate().
DIRTYCODE_API void ProtoSSLUpdate (ProtoSSLRefT * pState)
Give time to module to do its thing (should be called periodically to allow module to perform work). Calling once per 100ms or so should be enough.
This is actually a collection of state functions plus
the overall update function. They are kept together for
ease of reading.
Parameters
*pState - module state reference
Version
11/10/2005 gschaefer
References HostentT::addr, HostentT::Done, HostentT::Free, ProtoSSLRefT::iClosed, ProtoSSLRefT::iState, NetCritEnter(), NetCritLeave(), ProtoSSLRefT::PeerAddr, ProtoSSLRefT::pHost, ProtoSSLRefT::pSecure, ProtoSSLRefT::pSock, ProtoSSLRefT::SecureCrit, SockaddrInSetAddr, SOCKERR_NONE, SocketConnect(), SocketInfo(), ST3_SECURE, ST3_SEND_HELLO, ST_ADDR, ST_CONN, ST_FAIL_CONN, ST_FAIL_DNS, ST_UNSECURE, ST_WAIT_CA, and ST_WAIT_CONN.
Referenced by ProtoHttpUpdate(), ProtoSSLRecv(), ProtoSSLSend(), and ProtoWebSocketUpdate().
DIRTYCODE_API int32_t ProtoSSLValidateAllCA (void)
Validate all CA that have been added but not yet been validated. Validation is a one-time process and disposes of the X509 certificate that is retained until validation.
Returns
int32_t - zero on success; else the number of certs that could not be validated
Version
04/21/2011 (jbrookes)
References _DebugFormatCertIdent, _DebugPrintCert, DirtyMemFree(), ProtoSSLCACertT::iMemGroup, X509CertificateT::Issuer, NetPrintf, ProtoSSLCACertT::pMemGroupUserData, ProtoSSLCACertT::pNext, PROTOSSL_MEMID, ProtoSSLCACertT::pX509Cert, X509CertificateT::Subject, and TRUE.
Referenced by ProtoHttpValidateAllCA().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:49