DirtySock: xmlformat.c File Reference
xmlformat.c File Reference
This module formats simple Xml, in a linear fashion, using a character buffer that the client provides. See header for more information.
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include "DirtySDK/platform.h"
#include "DirtySDK/dirtysock/dirtylib.h"
#include "DirtySDK/xml/xmlformat.h"
Macros
#define XML_HEADER_LEN 24
#define XML_MAX_TAG_LENGTH 128
#define XML_MAX_FLOAT_LENGTH 128
#define XML_MAX_DATE_LENGTH 32
Functions
void XmlInit (char *pBuffer, int32_t iBufLen, unsigned char uFlags)
Initialize the Xml Buffer. This MUST be called prior to any other calls. Client can allocate the buffer on stack, but should not access it directly. (see XmlData()).
void XmlBufSizeIncrease (char *pBuffer, int32_t iNewBufLen)
Notify the xmlformat API that the buffer size was increased.
char * XmlFinish (char *pBuffer)
Signal completion of output to this buffer. Clear the XML API hidden data.
int32_t XmlTagStart (char *pBuffer, const char *pName)
Start an xml element (node), to which you can add other elements or attributes. Must be ended with XmlTagEnd.
int32_t XmlTagEnd (char *pBuffer)
End the current element or tag – must have an outstanding open tag.
int32_t XmlElemAddString (char *pBuffer, const char *pElemName, const char *pValue)
Add a complete, contained text element. Builds start and end tag. Nothing can be appended to this tag.
int32_t XmlElemAddInt (char *pBuffer, const char *pElemName, int32_t iValue)
Add a complete, contained integer element. Builds start and end tag. Nothing can be appended to this tag.
int32_t XmlElemAddFloat (char *pBuffer, const char *pElemName, const char *pFormatSpec, float fValue)
Add a complete, contained decimal element. Builds start and end tag. Nothing can be appended to this tag. Format it using formatSpec.
int32_t XmlElemAddDate (char *pBuffer, const char *pElemName, uint32_t uEpochDate)
Add a complete, contained Date element, using epoch date. Builds start and end tag. Nothing can be appended to this tag.
int32_t XmlAttrSetString (char *pBuffer, const char *pAttrName, const char *pValue)
Set a text attribute for an open element (started tag). Must be called before Element text is set.
int32_t XmlAttrSetStringRaw (char *pBuffer, const char *pAttr)
Set a text attribute for an open element (started tag) with no text encoding being performed on the input string. Must be called before Element text is set.
int32_t XmlAttrSetInt (char *pBuffer, const char *pAttrName, int32_t iValue)
Set an integer attribute for an open element (started tag). Must be called before Element text is set.
int32_t XmlAttrSetFloat (char *pBuffer, const char *pAttrName, const char *pFormatSpec, float fValue)
Set a decimal attribute for an open element (started tag). Must be called before Element text is set. Format using formatSpec.
int32_t XmlAttrSetDate (char *pBuffer, const char *pAttrName, uint32_t uEpochDate)
Set a date attribute for an open element (started tag). Must be called before Element text is set.
int32_t XmlAttrSetAddr (char *pBuffer, const char *pAttrName, uint32_t uAddr)
Set an IP address attribute (in dot notation)
int32_t XmlElemSetString (char *pBuffer, const char *pValue)
Set text value for an open element (started tag). Must have an open or started tag, uses element from previous start tag call. To be used if element is simple text node with some attributes.
int32_t XmlElemSetStringRaw (char *pBuffer, const char *pValue)
Set text value for an open element (started tag), with no encoding being performed on the input string. Must have an open or started tag, uses element from previous start tag call. To be used if element is simple text node with some attributes.
int32_t XmlElemSetInt (char *pBuffer, int32_t iValue)
Set integer value for an open element (started tag). Must have an open or started tag, uses element from previous start tag call. To be used if element is a simple node with some attributes.
int32_t XmlElemSetAddr (char *pBuffer, uint32_t uAddr)
Set an IP address value (in dot notation) for an open element¸.
int32_t XmlElemSetDate (char *pBuffer, uint32_t uEpoch)
Set a date for an open element. Must have an open element (started tag).
int32_t XmlValidate (const char *pXmlBuff, char *pErrorsBuff, int32_t iErrorsBuffLen)
Debug only function that will do simple validation of the tags. Will return count of errors found, and, errorsBuff is a output string of the errors. Returns true on Production.
char * XmlFormatVPrintf (char *pXmlBuff, int32_t iBufLen, const char *pFormat, va_list pFmtArgs)
char * XmlFormatPrintf (char *pXmlBuff, int32_t iBufLen, const char *pFormat,...)
Detailed Description
This module formats simple Xml, in a linear fashion, using a character buffer that the client provides. See header for more information.
Attention
Copyright (c) Electronic Arts 2004-2008. ALL RIGHTS RESERVED.
Note
    When XmlInit() is called, a 24-bytes header is added at the beginning of the
    client-provided buffer. The header is an ascii string that looks like this:
        <AAAAAAAABBBBBBBBCCDD />
            where:
                AAAAAAAA is the offset field
                BBBBBBBB is the buffer size field
                CC is the indent field
                DD is the flag field
    Those first 24 bytes are replaced by whitespaces when XmlFinish() is called.
    Upon buffer overrun:
    1. _XmlIndent: negative is returned and buffer remain untouched;
    2. _XmlEncodeString: negative is returned and buffer[0] has been reset to '\0' (if length(buffer) > 0);
    3. snzprintf: zero/negative is returned and buffer[0] has been reset to '\0' (if length(buffer) > 0).
    Required buffer capacity for xml = length(xml) + 1.
    That means if length(buffer) <= length(xml), buffer-overrun occurs.
Version
01/30/2004 (jbertrand) First Version
Macro Definition Documentation
#define XML_HEADER_LEN 24
Referenced by XmlFinish(), XmlInit(), and XmlTagEnd().
#define XML_MAX_DATE_LENGTH 32
Referenced by XmlAttrSetDate(), XmlElemAddDate(), and XmlElemSetDate().
#define XML_MAX_FLOAT_LENGTH 128
Referenced by XmlAttrSetFloat(), and XmlElemAddFloat().
#define XML_MAX_TAG_LENGTH 128
Referenced by XmlTagEnd().
Function Documentation
char* XmlFormatVPrintf (char * pXmlBuff, int32_t iBufLen, const char * pFormat, va_list pFmtArgs)
    Takes a format string and variable parameter list and formats into syntax
    correct XML doing optimizations like removing empty tags (i.e., <x></x>
    becomes <x />). The "v" (variable args) version can be called by other
    functions that use "..." in the their prototype.
Parameters
*pXmlBuff - xml output buffer
iBufLen - length of Xml output buffer (negative=append to existing buffer)
*pFormat - printf style format string
pFmtArgs - variable argument list (use va_start / va_end to get)
Returns
char* - pointer to formatted buffer
References ds_timeinsecs(), XML_FL_WHITESPACE, XmlAttrSetAddr(), XmlAttrSetDate(), XmlAttrSetInt(), XmlAttrSetString(), XmlElemSetAddr(), XmlElemSetDate(), XmlElemSetInt(), XmlElemSetString(), XmlFinish(), XmlInit(), XmlTagEnd(), and XmlTagStart().
Referenced by XmlFormatPrintf().
void XmlInit (char * pBuffer, int32_t iBufLen, unsigned char uFlags)
Initialize the Xml Buffer. This MUST be called prior to any other calls. Client can allocate the buffer on stack, but should not access it directly. (see XmlData()).
Parameters
*pBuffer - buffer to which xml will be written.
iBufLen – size of buffer passed in.
uFlags - encoding flags (XMLFORMAT_FL_xxx)
References ds_snzprintf(), and XML_HEADER_LEN.
Referenced by XmlFormatVPrintf().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:47