DirtySock: DirtyGraph
DirtyGraph
Graph
Data Structures
struct DirtyGraphInfoT
structure representing parsed image info
Typedefs
typedef enum DirtyGraphImageTypeE DirtyGraphImageTypeE
supported image types
typedef struct DirtyGraphInfoT DirtyGraphInfoT
structure representing parsed image info
typedef struct DirtyGraphRefT DirtyGraphRefT
opaque module state
Enumerations
enum DirtyGraphImageTypeE {
DIRTYGRAPH_IMAGETYPE_UNKNOWN = 0,
DIRTYGRAPH_IMAGETYPE_GIF,
DIRTYGRAPH_IMAGETYPE_JPG,
DIRTYGRAPH_IMAGETYPE_PNG
}
supported image types
Functions
DIRTYCODE_API DirtyGraphRefT * DirtyGraphCreate (void)
Create the DirtyGraph module.
DIRTYCODE_API void DirtyGraphDestroy (DirtyGraphRefT *pRef)
Destroy the DirtyGraph module.
DIRTYCODE_API int32_t DirtyGraphDecodeHeader (DirtyGraphRefT *pRef, DirtyGraphInfoT *pInfo, const uint8_t *pImageData, uint32_t uImageLen)
Decode an image header.
DIRTYCODE_API int32_t DirtyGraphDecodeImage (DirtyGraphRefT *pRef, DirtyGraphInfoT *pInfo, uint8_t *pImageBuf, int32_t iBufWidth, int32_t iBufHeight)
Decode an image into the given output buffer.
Detailed Description
Typedef Documentation
typedef enum DirtyGraphImageTypeE DirtyGraphImageTypeE
supported image types
typedef struct DirtyGraphInfoT DirtyGraphInfoT
structure representing parsed image info
typedef struct DirtyGraphRefT DirtyGraphRefT
opaque module state
Enumeration Type Documentation
enum DirtyGraphImageTypeE
supported image types
Enumerator
DIRTYGRAPH_IMAGETYPE_UNKNOWN
DIRTYGRAPH_IMAGETYPE_GIF
DIRTYGRAPH_IMAGETYPE_JPG
DIRTYGRAPH_IMAGETYPE_PNG
Function Documentation
DIRTYCODE_API DirtyGraphRefT* DirtyGraphCreate (void)
Create the DirtyGraph module.
Returns
DirtyGraphStateT * - module state, or NULL if unable to create
Version
03/09/2006 (jbrookes) First Version
References DIRTYGRAPH_MEMID, DirtyJpgCreate(), DirtyMemAlloc(), DirtyMemGroupQuery(), DirtyPngCreate(), DirtyGraphRefT::iMemGroup, NetPrintf, NULL, DirtyGraphRefT::pJpg, DirtyGraphRefT::pMemGroupUserData, and DirtyGraphRefT::pPng.
DIRTYCODE_API int32_t DirtyGraphDecodeHeader (DirtyGraphRefT * pDirtyGraph, DirtyGraphInfoT * pInfo, const uint8_t * pImageData, uint32_t uImageLen)
Decode an image header.
Parameters
*pDirtyGraph - pointer to module state
*pInfo - [out] storage for image info
*pImageData - pointer to input image info
uImageLen - size of input image
Returns
int32_t - negative=error, else success
Version
03/09/2006 (jbrookes)
References DirtyGifIdentify(), DirtyGifParse(), DIRTYGRAPH_IMAGETYPE_GIF, DIRTYGRAPH_IMAGETYPE_JPG, DIRTYGRAPH_IMAGETYPE_PNG, DIRTYGRAPH_IMAGETYPE_UNKNOWN, DIRTYJPG_ERR_NONE, DirtyJpgDecodeHeader(), DirtyJpgIdentify(), DIRTYPNG_ERR_NONE, DirtyPngIdentify(), DirtyPngParse(), DirtyGraphRefT::GifHdr, DirtyGraphInfoT::iHeight, DirtyGraphInfoT::iWidth, DirtyGraphRefT::JpgHdr, NetPrintf, NULL, DirtyGraphInfoT::pImageData, DirtyGraphRefT::pJpg, DirtyGraphRefT::PngHdr, DirtyGraphRefT::pPng, DirtyGifHdrT::uHeight, DirtyJpgHdrT::uHeight, DirtyPngHdrT::uHeight, DirtyGraphInfoT::uLength, DirtyGraphInfoT::uType, DirtyGifHdrT::uWidth, DirtyJpgHdrT::uWidth, and DirtyPngHdrT::uWidth.
DIRTYCODE_API int32_t DirtyGraphDecodeImage (DirtyGraphRefT * pDirtyGraph, DirtyGraphInfoT * pInfo, uint8_t * pImageBuf, int32_t iBufWidth, int32_t iBufHeight)
Decode an image into the given output buffer.
Parameters
*pDirtyGraph - pointer to module state
*pInfo - image information (filled in by DirtyGraphDecodeHeader)
*pImageBuf - [out] pointer to buffer to store decoded image
iBufWidth - width of output buffer
iBufHeight - height of output buffer
Returns
int32_t - negative=error, else success
Version
03/09/2006 (jbrookes)
References DirtyGifDecodeImage32(), DIRTYGRAPH_IMAGETYPE_GIF, DIRTYGRAPH_IMAGETYPE_JPG, DIRTYGRAPH_IMAGETYPE_PNG, DirtyJpgDecodeImage(), DirtyPngDecodeImage(), DirtyGraphRefT::GifHdr, DirtyGraphRefT::JpgHdr, NetPrintf, DirtyGraphRefT::pJpg, DirtyGraphRefT::PngHdr, DirtyGraphRefT::pPng, TRUE, and DirtyGraphInfoT::uType.
DIRTYCODE_API void DirtyGraphDestroy (DirtyGraphRefT * pDirtyGraph)
Destroy the DirtyGraph module.
Parameters
*pDirtyGraph - pointer to module state
Returns
None.
Version
03/09/2006 (jbrookes)
References DIRTYGRAPH_MEMID, DirtyJpgDestroy(), DirtyMemFree(), DirtyPngDestroy(), DirtyGraphRefT::iMemGroup, NULL, DirtyGraphRefT::pJpg, DirtyGraphRefT::pMemGroupUserData, and DirtyGraphRefT::pPng.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:21