DirtySock: voipheadsetxboxone.cpp File Reference
voipheadsetxboxone.cpp File Reference
VoIP headset manager. Wraps Xbox One Game Chat api.
#include "DirtySDK/platform.h"
#include <collection.h>
#include <wrl.h>
#include <robuffer.h>
#include <xdk.h>
#include "DirtySDK/dirtysock.h"
#include "DirtySDK/dirtysock/dirtymem.h"
#include "DirtySDK/dirtysock/dirtyerr.h"
#include "DirtySDK/dirtysock/netconn.h"
#include "DirtySDK/voip/voipdef.h"
#include "DirtySDK/misc/userlistapi.h"
#include "voippriv.h"
#include "voippacket.h"
#include "voipheadset.h"
#include "voipserializationxboxone.h"
Data Structures
struct LocalVoipUserT
< local user data space
struct RemoteSharedUserT
struct VoipHeadsetRefT
voipheadset module state data
Macros
#define VOIPHEADSET_DEBUG (DIRTYCODE_DEBUG && FALSE)
#define VOIPHEADSET_GAMECHAT_DEFAULT_ENCODING_QUALITY (EncodingQuality::Normal)
#define VOIPHEADSET_INBOUND_QUEUE_MAX_CAPACITY (16)
#define VOIPHEADSET_INBOUND_QUEUE_LOW_WATERMARK (4)
#define VOIPHEADSET_USERLISTAPI_RESPONSE_SIZE (1000)
#define VOIPHEADSET_STATISTIC_SERVICE_SCID "7492baca-c1b4-440d-a391-b7ef364a8d40"
#define VOIPHEADSET_BADREP_CHECK_TIMEOUT (5000)
Typedefs
typedef struct LocalVoipUserT LocalVoipUserT
< local user data space
typedef struct RemoteSharedUserT RemoteSharedUserT
Functions
void VoipHeadsetIsFriendCallback (UserListApiRefT *pRef, UserListApiIfATypeE eResponseType, UserListApiIsADataT *pUserApiEventData, void *pUserData)
Set speaker output callback.
VoipHeadsetRefT * VoipHeadsetCreate (int32_t iMaxChannels, VoipHeadsetMicDataCbT *pMicDataCb, VoipHeadsetStatusCbT *pStatusCb, void *pCbUserData, int32_t iData)
Create the headset manager.
void VoipHeadsetDestroy (VoipHeadsetRefT *pHeadset)
Destroy the headset manager.
void VoipHeadsetReceiveVoiceDataCb (VoipUserT *pRemoteUsers, VoipMicrInfoT *pMicrInfo, uint8_t *pPacketData, void *pUserData)
Connectionlist callback to handle receiving a voice packet from a remote peer.
void VoipHeadsetRegisterUserCb (VoipUserT *pRemoteUser, uint32_t bRegister, void *pUserData)
Connectionlist callback to register a new remote user with the 1st party voice system It will also register remote shared users with voipheadset internally.
void VoipHeadsetProcess (VoipHeadsetRefT *pHeadset, uint32_t uFrameCount)
Headset process function.
void VoipHeadsetSetVolume (VoipHeadsetRefT *pHeadset, int32_t iPlayVol, uint32_t iRecVol)
Sets play and record volume.
int32_t VoipHeadsetControl (VoipHeadsetRefT *pHeadset, int32_t iControl, int32_t iValue, int32_t iValue2, void *pValue)
Control function.
int32_t VoipHeadsetStatus (VoipHeadsetRefT *pHeadset, int32_t iSelect, int32_t iValue, void *pBuf, int32_t iBufSize)
Status function.
void VoipHeadsetSpkrCallback (VoipHeadsetRefT *pHeadset, VoipSpkrCallbackT *pCallback, void *pUserData)
Set speaker output callback.
Detailed Description
VoIP headset manager. Wraps Xbox One Game Chat api.
Attention
Copyright (c) Electronic Arts 2013. ALL RIGHTS RESERVED.
Version
05/24/2013 (mclouatre) First Version
Macro Definition Documentation
#define VOIPHEADSET_BADREP_CHECK_TIMEOUT (5000)
#define VOIPHEADSET_DEBUG (DIRTYCODE_DEBUG && FALSE)
#define VOIPHEADSET_GAMECHAT_DEFAULT_ENCODING_QUALITY (EncodingQuality::Normal)
Referenced by VoipHeadsetCreate().
#define VOIPHEADSET_INBOUND_QUEUE_LOW_WATERMARK (4)
#define VOIPHEADSET_INBOUND_QUEUE_MAX_CAPACITY (16)
#define VOIPHEADSET_STATISTIC_SERVICE_SCID "7492baca-c1b4-440d-a391-b7ef364a8d40"
#define VOIPHEADSET_USERLISTAPI_RESPONSE_SIZE (1000)
Referenced by VoipHeadsetCreate().
Typedef Documentation
typedef struct LocalVoipUserT LocalVoipUserT
< local user data space
remote shared user
typedef struct RemoteSharedUserT RemoteSharedUserT
Function Documentation
int32_t VoipHeadsetControl (VoipHeadsetRefT * pHeadset, int32_t iControl, int32_t iValue, int32_t iValue2, void * pValue)
Control function.
Parameters
*pHeadset - headset module state
iControl - control selector
iValue - control value
iValue2 - control value
*pValue - control value
Returns
int32_t - selector specific, or -1 if no such selector
Note
iControl can be one of the following:
        'ambr' - enable or disable auto muting for bad rep users (default is enabled)
        '+pbk' - enable voice playback for a given remote user (pValue is the remote user VoipUserT).
        '-pbk' - disable voice playback for a given remote user (pValue is the remote user VoipUserT).
        'aloc' - set local user as participating / not participating
        'loop' - enable/disable loopback
        'qual' - set encoding quality
        'rloc' - register/unregister local talker
        'spam' - debug verbosity level
Version
05/24/2013 (mclouatre)
References VoipHeadsetRefT::bAutoMuteBadRep, VoipHeadsetRefT::bAutoMuteCheckCompleted, VoipHeadsetRefT::bLoopback, ds_stristr(), VoipHeadsetRefT::EncodingQual, FALSE, NetPrintf, VoipUserT::strUserId, TRUE, and VOIP_MAXLOCALUSERS_EXTENDED.
Referenced by VoipActivateLocalUser(), VoipCommonControl(), and VoipControl().
VoipHeadsetRefT* VoipHeadsetCreate (int32_t iMaxChannels, VoipHeadsetMicDataCbT * pMicDataCb, VoipHeadsetStatusCbT * pStatusCb, void * pCbUserData, int32_t iData)
Create the headset manager.
Parameters
iMaxChannels - max number of remote users
*pMicDataCb - pointer to user callback to trigger when mic data is ready
*pStatusCb - pointer to user callback to trigger when headset status changes
*pCbUserData - pointer to user callback data
iData - platform-specific - unused for xboxone
Returns
VoipHeadsetRefT * - pointer to module state, or NULL if an error occured
Version
05/24/2013 (mclouatre)
References VoipHeadsetRefT::aLocalUsers, VoipHeadsetRefT::AudioDeviceAddedToken, VoipHeadsetRefT::AudioDeviceChangedToken, VoipHeadsetRefT::AudioDeviceRemovedToken, VoipHeadsetRefT::bAutoMuteBadRep, VoipHeadsetRefT::bHeadsetChanged, VoipHeadsetRefT::crit, DirtyMemAlloc(), VoipHeadsetRefT::EncodingQual, VoipHeadsetRefT::iMaxChannels, NETCONN_MAXLOCALUSERS, NetConnMachineId(), NetConnStatus(), NetCritEnter(), NetCritInit(), NetCritLeave(), NetPrintf, NetTick(), VoipHeadsetRefT::pCbUserData, VoipHeadsetRefT::pMicDataCb, VoipHeadsetRefT::pStatusCb, VoipHeadsetRefT::pUserListApiRef, VoipHeadsetRefT::refAsyncOp, LocalVoipUserT::refAudioDevsVector, LocalVoipUserT::refChatParticipant, VoipHeadsetRefT::refChatSession, VoipHeadsetRefT::refCurrentChatSessionState, VoipHeadsetRefT::refDecodersMap, VoipHeadsetRefT::refEncodersMap, VoipHeadsetRefT::refInboundQueuesMap, VoipHeadsetRefT::refNewChatSessionState, VoipHeadsetRefT::refPreBufStateMap, TRUE, VoipHeadsetRefT::uLastBystanderUpdate, LocalVoipUserT::user, UserListApiCreate(), VOIP_MAXCONNECT, VOIP_MAXLOCALUSERS, VOIP_MEMID, VOIP_NullUser, VoipDeserializeAudioDevice(), VOIPHEADSET_GAMECHAT_DEFAULT_ENCODING_QUALITY, VOIPHEADSET_USERLISTAPI_RESPONSE_SIZE, VoipHeadsetDestroy(), VoipMemGroupQuery(), and VoipSerializeAudioDevice().
Referenced by VoipCommonStartup().
void VoipHeadsetDestroy (VoipHeadsetRefT * pHeadset)
Destroy the headset manager.
Parameters
*pHeadset - pointer to headset state
Version
05/24/2013 (mclouatre)
References VoipHeadsetRefT::bDestroy, NetConnControl(), NetPrintf, and TRUE.
Referenced by VoipCommonShutdown(), and VoipHeadsetCreate().
void VoipHeadsetIsFriendCallback (UserListApiRefT * pRef, UserListApiIfATypeE eResponseType, UserListApiIsADataT * pUserApiEventData, void * pUserData)
Set speaker output callback.
Parameters
*pRef - user list ref
eResponseType - user list response type
*pUserApiEventData - user list event data
*pUserData - customer user data (VoipHeadsetRef)
Version
10/26/2015 (tcho)
References UserListApiIsADataT::bIsFavorite, UserListApiIsADataT::bIsMutualFriend, UserListApiIsADataT::DirtyUser, DirtyUserToNativeUser(), FALSE, VoipHeadsetRefT::iCompletedFrdCheck, VoipHeadsetRefT::refChatSession, TRUE, and USERLISTAPI_IS_FRIENDS.
void VoipHeadsetProcess (VoipHeadsetRefT * pHeadset, uint32_t uFrameCount)
Headset process function.
Parameters
*pHeadset - pointer to headset state
uFrameCount - current frame count
Version
05/24/2013 (mclouatre)
References VoipHeadsetRefT::bHeadsetChanged, VoipHeadsetRefT::bKinectAvailabilityChanged, VoipHeadsetRefT::bSessionStateRefreshInProgress, FALSE, NetTick(), NetTickDiff, VoipHeadsetRefT::pUserListApiRef, VoipHeadsetRefT::refCurrentChatSessionState, VoipHeadsetRefT::uLastBystanderUpdate, and UserListApiUpdate().
void VoipHeadsetReceiveVoiceDataCb (VoipUserT * pRemoteUsers, VoipMicrInfoT * pMicrInfo, uint8_t * pPacketData, void * pUserData)
Connectionlist callback to handle receiving a voice packet from a remote peer.
Parameters
*pRemoteUsers - user we're receiving the voice data from
*pMicrInfo - micr info from inbound packet
*pPacketData - pointer to beginning of data in packet payload
*pUserData - VoipHeadsetT ref
Version
05/24/2013 (mclouatre)
References VoipHeadsetRefT::aRemoteSharedUsers, RemoteSharedUserT::CaptureSoureId, NetPrintf, NetPrintfVerbose, VoipMicrInfoT::uNumSubPackets, RemoteSharedUserT::user, VoipMicrInfoT::uUserIndex, VOIP_MAX_LOW_LEVEL_CONNS, VOIP_SameUser, VOIP_SHARED_USER_INDEX, and VoipDeserializeAudioDevice().
Referenced by VoipCommonStartup().
void VoipHeadsetRegisterUserCb (VoipUserT * pRemoteUser, uint32_t bRegister, void * pUserData)
Connectionlist callback to register a new remote user with the 1st party voice system It will also register remote shared users with voipheadset internally.
Parameters
*pRemoteUser - user to register
bRegister - true=register, false=unregister
*pUserData - voipheadset module ref
Version
05/24/2013 (mclouatre)
References VoipHeadsetRefT::aRemoteSharedUsers, VoipHeadsetRefT::bAutoMuteBadRep, RemoteSharedUserT::CaptureSoureId, ds_stristr(), NetHash(), NetPrintf, VoipUserT::strUserId, RemoteSharedUserT::uEnablePlaybackFlag, RemoteSharedUserT::user, VOIP_CopyUser, VOIP_MAX_LOW_LEVEL_CONNS, VOIP_NullUser, VOIP_SameUser, and VoipDeserializeUser().
Referenced by VoipCommonStartup().
void VoipHeadsetSetVolume (VoipHeadsetRefT * pHeadset, int32_t iPlayVol, uint32_t iRecVol)
Sets play and record volume.
Parameters
*pHeadset - pointer to headset state
iPlayVol - play volume to set
iRecVol - record volume to set
Note
To not set a value, specify it as -1.
Version
05/24/2013 (mclouatre)
void VoipHeadsetSpkrCallback (VoipHeadsetRefT * pHeadset, VoipSpkrCallbackT * pCallback, void * pUserData)
Set speaker output callback.
Parameters
*pHeadset - headset module state
*pCallback - what to call when output data is available
*pUserData - user data for callback
Version
05/24/2013 (mclouatre)
References VoipHeadsetRefT::pSpkrCbUserData, and VoipHeadsetRefT::pSpkrDataCb.
Referenced by VoipSpkrCallback().
int32_t VoipHeadsetStatus (VoipHeadsetRefT * pHeadset, int32_t iSelect, int32_t iValue, void * pBuf, int32_t iBufSize)
Status function.
Parameters
*pHeadset - headset module state
iSelect - control selector
iValue - selector specific
*pBuf - buffer pointer
iBufSize - buffer size
Returns
int32_t - selector specific, or -1 if no such selector
Note
iSelect can be one of the following:
        'ambr' - TRUE if auto mute bad reputation check is enabled
        'amcc' - TRUE if auto mute bad reputation check is completed
        'amuc' - TRUE if the given user should be muted because of bad reputation
        'kine' - TRUE if kinect is in set of active capture source, FALSE otherwise
        'ruid' - return TRUE if the given remote user (pBuf) is registered with voipheadset, FALSE if not.
        'supd' - TRUE if chat session update is in progress
        'sact' - TRUE if the shared device (kinect) is active
        'vlen' - TRUE if voice sub-packet have variable length, FALSE otherwise
Version
05/24/2013 (mclouatre)
References VoipHeadsetRefT::aRemoteSharedUsers, VoipHeadsetRefT::bAutoMuteBadRep, VoipHeadsetRefT::bAutoMuteCheckCompleted, VoipHeadsetRefT::bHeadsetFound, VoipHeadsetRefT::bIsKinectAvailable, VoipHeadsetRefT::bKinectIsCapturing, VoipHeadsetRefT::bSessionStateRefreshInProgress, ds_snzprintf(), FALSE, VoipHeadsetRefT::refChatSession, VoipUserT::strUserId, TRUE, RemoteSharedUserT::user, VOIP_MAX_LOW_LEVEL_CONNS, and VOIP_SameUser.
Referenced by VoipCommonApplyChannelConfig(), and VoipCommonStatus().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:34:35