DirtySock: DispList
DispList
Util
Typedefs
typedef struct DispListRef DispListRef
typedef struct DispListT DispListT
Functions
DIRTYCODE_API DispListRef * DispListCreate (int32_t basis, int32_t addcnt, int32_t addpct)
Create a new display list.
DIRTYCODE_API void DispListDestroy (DispListRef *ref)
Destroy a display list.
DIRTYCODE_API void DispListClear (DispListRef *ref)
Clear all items from existing list.
DIRTYCODE_API DispListT * DispListAdd (DispListRef *ref, void *recptr)
Add an item to the display list.
DIRTYCODE_API void DispListSet (DispListRef *ref, DispListT *item, void *recptr)
Change the data associated with a record.
DIRTYCODE_API void * DispListGet (DispListRef *ref, DispListT *item)
Return data pointer for a record.
DIRTYCODE_API void * DispListDel (DispListRef *ref, DispListT *item)
Delete an item from the list.
DIRTYCODE_API void * DispListDelByIndex (DispListRef *ref, int32_t index)
Delete an item given an index to it.
DIRTYCODE_API int32_t DispListChange (DispListRef *ref, int32_t set)
Get/set the list "changed" value.
DIRTYCODE_API int32_t DispListDirty (DispListRef *ref, int32_t set)
Get/set the list "dirty" value.
DIRTYCODE_API int32_t DispListCount (DispListRef *ref)
Return total number of records (visible+invisible)
DIRTYCODE_API int32_t DispListShown (DispListRef *ref)
Return total number of visible records.
DIRTYCODE_API void * DispListIndex (DispListRef *ref, int32_t index)
Return a record data pointer by its display index.
DIRTYCODE_API void DispListSort (DispListRef *ref, void *sortref, int32_t sortcon, int32_t(*sortptr)(void *sortref, int32_t sortcon, void *recptr1, void *recptr2))
Assign the sort routine for the list.
DIRTYCODE_API void DispListFilt (DispListRef *ref, void *filtref, int32_t filtcon, int32_t(*filtptr)(void *filtref, int32_t filtcon, void *recptr))
Assign the filter routine for the list.
DIRTYCODE_API int32_t DispListOrder (DispListRef *ref)
Order the list using the current filter/sort functions.
DIRTYCODE_API void DispListDataSet (DispListRef *ref, void *dataref)
Store data storage pointer (used by calling code)
DIRTYCODE_API void * DispListDataGet (DispListRef *ref)
Return data storage pointer (used by calling code)
Detailed Description
Typedef Documentation
typedef struct DispListRef DispListRef
typedef struct DispListT DispListT
Function Documentation
DIRTYCODE_API DispListT* DispListAdd (DispListRef * ref, void * recptr)
Add an item to the display list.
Parameters
*ref - reference pointer
*recptr - pointer to record to add
Returns
DispListT* - record refernce (NULL=unable to add)
Note
Caller must maintain storage for record
Version
1.0 03/15/00 (GWS) First Version
References DispListRef::avail, DispListRef::change, DispListRef::count, DispListT::data, DispListRef::filtcon, DispListRef::filtptr, DispListRef::filtref, DispListRef::free, NULL, and DispListRef::view.
DIRTYCODE_API int32_t DispListChange (DispListRef * ref, int32_t set)
Get/set the list "changed" value.
Parameters
*ref - reference pointer
set - indicates if the changed value should be set
Returns
int32_t - change value
Note
None.
Version
1.0 03/15/00 (GWS) First Version
References DispListRef::change.
Referenced by HLBListDisableSorting(), and HLBListSort().
DIRTYCODE_API void DispListClear (DispListRef * ref)
Clear all items from existing list.
Parameters
*ref - reference pointer
Returns
None.
Note
None.
Version
1.0 03/15/00 (GWS) First Version
References DispListRef::avail, DispListRef::change, DispListRef::count, DispListT::data, DispListRef::free, DispListRef::shown, and DispListRef::view.
DIRTYCODE_API int32_t DispListCount (DispListRef * ref)
Return total number of records (visible+invisible)
Parameters
*ref - reference pointer
Returns
int32_t - number of records
Note
None.
Version
1.0 03/15/00 (GWS) First Version
References DispListRef::count.
DIRTYCODE_API DispListRef* DispListCreate (int32_t basis, int32_t addcnt, int32_t addpct)
Create a new display list.
Parameters
basis - initial number of records
addcnt - number of record to add, when expansion needed
addpct - percent of records to add during expansion
Returns
DispListRef * - reference pointer (need for all other functions)
Version
1.0 03/15/00 (GWS) First Version
References DispListRef::addcnt, DispListRef::addpct, DirtyMemAlloc(), DirtyMemGroupQuery(), DISPLIST_MEMID, DispListRef::memgroup, and DispListRef::memgrpusrdata.
DIRTYCODE_API void* DispListDataGet (DispListRef * ref)
Return data storage pointer (used by calling code)
Parameters
*ref - reference pointer
Returns
void* - the data storage constant (used entirely by caller)
Version
1.0 12/19/2002 (GWS) First Version
References DispListRef::dataref.
DIRTYCODE_API void DispListDataSet (DispListRef * ref, void * dataref)
Store data storage pointer (used by calling code)
Parameters
*ref - reference pointer
*dataref - caller defined
Returns
None.
Version
1.0 12/19/2002 (GWS) First Version
References DispListRef::dataref.
DIRTYCODE_API void* DispListDel (DispListRef * ref, DispListT * item)
Delete an item from the list.
Parameters
*ref - reference pointer
*item - record reference (from add)
Returns
void * - record pointer
Note
None.
Version
1.0 03/15/00 (GWS) First Version
References DispListRef::count, DispListDelByIndex(), and DispListRef::view.
Referenced by BuddyApiFlush(), and BuddyApiUpdate().
DIRTYCODE_API void* DispListDelByIndex (DispListRef * ref, int32_t idx)
Delete an item given an index to it.
Parameters
*ref - reference pointer
*idx - record reference (from add)
Returns
void * - record pointer, the data held by item.
Note
None.
Version
1.0 03/15/00 (GWS) First Version
References DispListRef::avail, DispListRef::change, DispListRef::count, DispListT::data, data, DispListRef::free, NULL, DispListRef::shown, and DispListRef::view.
Referenced by DispListDel().
DIRTYCODE_API void DispListDestroy (DispListRef * ref)
Destroy a display list.
Parameters
*ref - reference pointer
Returns
None.
Note
None.
Version
1.0 03/15/00 (GWS) First Version
References DispListT::data, DirtyMemFree(), DISPLIST_MEMID, DispListRef::list, DispListRef::memgroup, DispListRef::memgrpusrdata, NULL, and DispListRef::view.
Referenced by BuddyApiFlush().
DIRTYCODE_API int32_t DispListDirty (DispListRef * ref, int32_t set)
Get/set the list "dirty" value.
Parameters
*ref - reference pointer
set - indicates if the dirty value should be set
Returns
int32_t - dirty value
Note
None.
Version
1.0 03/15/00 (GWS) First Version
References DispListRef::dirty.
Referenced by BuddyApiRoster(), and BuddyApiUpdate().
DIRTYCODE_API void DispListFilt (DispListRef * ref, void * filtref, int32_t filtcon, int32_t(*)(void *filtref, int32_t filtcon, void *recptr) filtptr)
Assign the filter routine for the list.
Parameters
*ref - reference pointer
*filtref - callback value
filtcon - callback value
*filtptr - user filter function
Returns
None.
Note
None.
Version
1.0 03/15/00 (GWS) First Version
References DispListRef::change, DispListRef::count, DispListRef::filtcon, DispListRef::filtptr, and DispListRef::filtref.
DIRTYCODE_API void* DispListGet (DispListRef * ref, DispListT * item)
Return data pointer for a record.
Parameters
*ref - reference pointer
*item - record reference
Returns
void * - record pointer
Note
None.
Version
1.0 03/15/00 (GWS) First Version
References DispListT::data, and NULL.
Referenced by BuddyApiFind().
DIRTYCODE_API void* DispListIndex (DispListRef * ref, int32_t index)
Return a record data pointer by its display index.
Parameters
*ref - reference pointer
index - record index
Returns
void * - record data pointer (NULL=invalid index)
Note
None.
Version
1.0 03/15/00 (GWS) First Version
References DispListRef::count, DispListT::data, NULL, and DispListRef::view.
Referenced by BuddyApiUpdate(), and HLBListGetBuddyByIndex().
DIRTYCODE_API int32_t DispListOrder (DispListRef * ref)
Order the list using the current filter/sort functions.
Parameters
*ref - reference pointer
Returns
int32_t - zero=no changes made, positive=list was resorted/refiltered
Note
None.
Version
1.0 03/15/00 (GWS) First Version
References DispListRef::change, DispListRef::count, DispListRef::dirty, DispListRef::filtcon, DispListRef::filtptr, DispListRef::filtref, LobbyMSort(), NULL, DispListRef::shown, DispListRef::sortptr, and DispListRef::view.
Referenced by BuddyApiUpdate(), HLBListDisableSorting(), and HLBListSort().
DIRTYCODE_API void DispListSet (DispListRef * ref, DispListT * item, void * recptr)
Change the data associated with a record.
Parameters
*ref - reference pointer
*item - record reference (from add)
*recptr - new record pointer
Returns
None.
Note
If item->data == recptr then record was changed and we cannot determine its prior visibility and thus must assume it changed
Version
1.0 03/15/00 (GWS) First Version
References DispListRef::change, DispListT::data, DispListRef::filtcon, DispListRef::filtptr, DispListRef::filtref, and NULL.
DIRTYCODE_API int32_t DispListShown (DispListRef * ref)
Return total number of visible records.
Parameters
*ref - reference pointer
Returns
int32_t - number of visible records
Note
None.
Version
1.0 03/15/00 (GWS) First Version
References DispListRef::shown.
DIRTYCODE_API void DispListSort (DispListRef * ref, void * sortref, int32_t sortcon, int32_t(*)(void *sortref, int32_t sortcon, void *recptr1, void *recptr2) sortptr)
Assign the sort routine for the list.
Parameters
*ref - reference pointer
*sortref - callback value
sortcon - callback value
sortptr - user sort function
Returns
None.
Note
None.
Version
1.0 03/15/00 (GWS) First Version
References DispListRef::change, DispListRef::count, DispListRef::sortcon, DispListRef::sortptr, and DispListRef::sortref.
Referenced by HLBListDisableSorting(), and HLBListSort().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:32