DirtySock: dirtynetxboxone.c File Reference
dirtynetxboxone.c File Reference
Provide a wrapper that translates the Winsock network interface into DirtySock calls. In the case of Winsock, little translation is needed since it is based off BSD sockets (as is DirtySock).
#include <windows.h>
#include <winsock2.h>
#include <ws2tcpip.h>
#include <mstcpip.h>
#include "DirtySDK/dirtysock/dirtylib.h"
#include "DirtySDK/dirtysock/dirtymem.h"
#include "DirtySDK/dirtysock/dirtynet.h"
#include "DirtySDK/dirtysock/dirtyerr.h"
#include "DirtySDK/dirtyvers.h"
#include "dirtynetpriv.h"
Data Structures
struct SocketT
dirtysock connection socket structure
struct SocketAddrMapEntryT
struct SocketAddrMapT
struct SocketStateT
local state
Macros
#define WIN32_LEAN_AND_MEAN 1
#define SOCKET_MAXEVENTS (64)
#define SockaddrIn6GetAddr4(addr) (((((((uint8_t)((addr)->sin6_addr.s6_addr[12])<<8)|(uint8_t)((addr)->sin6_addr.s6_addr[13]))<<8)|(uint8_t)((addr)->sin6_addr.s6_addr[14]))<<8)|(uint8_t)((addr)->sin6_addr.s6_addr[15]))
Typedefs
typedef struct SocketAddrMapEntryT SocketAddrMapEntryT
typedef struct SocketAddrMapT SocketAddrMapT
typedef struct SocketStateT SocketStateT
local state
Functions
int32_t _SocketAddrMapAlloc (SocketStateT *pState, int32_t iNumEntries)
Alloc (or re-alloc) address map entry list.
int32_t _SocketAddrMapAdd (SocketStateT *pState, const struct sockaddr_in6 *pAddr6, int32_t iAddrSize)
Add an IPv6 address to the address mapping table.
int32_t SocketCreate (int32_t iThreadPrio, int32_t iThreadStackSize, int32_t iThreadCpuAffinity)
Create new instance of socket interface module. Initializes all global resources and makes module ready for use.
int32_t SocketDestroy (uint32_t uShutdownFlags)
Release resources and destroy module.
SocketT * SocketOpen (int32_t af, int32_t type, int32_t proto)
Create a new transfer endpoint. A socket endpoint is required for any data transfer operation.
int32_t SocketClose (SocketT *pSocket)
Close a socket. Performs a graceful shutdown of connection oriented protocols.
SocketT * SocketImport (intptr_t uSockRef)
Import a socket. The given socket ref may be a SocketT, in which case a SocketT pointer to the ref is returned, or it can be an actual Sony socket ref, in which case a SocketT is created for the Sony socket ref.
void SocketRelease (SocketT *pSocket)
Release an imported socket.
int32_t SocketShutdown (SocketT *pSocket, int32_t iHow)
Perform partial/complete shutdown of socket indicating that either sending and/or receiving is complete.
int32_t SocketBind (SocketT *pSocket, const struct sockaddr *pName, int32_t iNameLen)
Bind a local address/port to a socket.
int32_t SocketConnect (SocketT *pSocket, struct sockaddr *pName, int32_t iNameLen)
Initiate a connection attempt to a remote host.
int32_t SocketListen (SocketT *pSocket, int32_t iBackLog)
Start listening for an incoming connection on the socket. The socket must already be bound and a stream oriented connection must be in use.
SocketT * SocketAccept (SocketT *pSocket, struct sockaddr *pAddr, int32_t *pAddrLen)
Accept an incoming connection attempt on a socket.
int32_t SocketSendto (SocketT *pSocket, const char *pBuf, int32_t iLen, int32_t iFlags, const struct sockaddr *pTo, int32_t iToLen)
Send data to a remote host. The destination address is supplied along with the data. Should only be used with datagram sockets as stream sockets always send to the connected peer.
int32_t SocketRecvfrom (SocketT *pSock, const char *pBuf, int32_t iLen, int32_t iFlags, struct sockaddr *pFrom, int32_t *pFromLen)
Receive data from a remote host. If socket is a connected stream, then data can only come from that source. A datagram socket can receive from any remote host.
int32_t SocketInfo (SocketT *pSocket, int32_t iInfo, int32_t iData, void *pBuf, int32_t iLen)
Return information about an existing socket.
int32_t SocketCallback (SocketT *pSocket, int32_t iMask, int32_t iIdle, void *pRef, int32_t(*pProc)(SocketT *pSocket, int32_t iFlags, void *pRef))
Register a callback routine for notification of socket events. Also includes timeout support.
int32_t SocketControl (SocketT *pSocket, int32_t iOption, int32_t iData1, void *pData2, void *pData3)
Process a control message (type specific operation)
uint32_t SocketGetLocalAddr (void)
Returns the "external" local address (ie, the address as a machine "out on the Internet" would see as the local machine's address).
HostentT * SocketLookup (const char *pText, int32_t iTimeout)
Lookup a host by name and return the corresponding Internet address. Uses a callback/polling system since the socket library does not allow blocking.
int32_t SocketHost (struct sockaddr *pHost, int32_t iHostLen, const struct sockaddr *pDest, int32_t iDestLen)
Return the host address that would be used in order to communicate with the given destination address.
Detailed Description
Provide a wrapper that translates the Winsock network interface into DirtySock calls. In the case of Winsock, little translation is needed since it is based off BSD sockets (as is DirtySock).
Attention
Copyright (c) Electronic Arts 1999-2013.
Version
1.0 03/22/2013 (jbrookes) Branched from dirtynetwin
Macro Definition Documentation
#define SockaddrIn6GetAddr4 (addr) (((((((uint8_t)((addr)->sin6_addr.s6_addr[12])<<8)|(uint8_t)((addr)->sin6_addr.s6_addr[13]))<<8)|(uint8_t)((addr)->sin6_addr.s6_addr[14]))<<8)|(uint8_t)((addr)->sin6_addr.s6_addr[15]))
#define SOCKET_MAXEVENTS (64)
#define WIN32_LEAN_AND_MEAN 1
Typedef Documentation
typedef struct SocketAddrMapEntryT SocketAddrMapEntryT
typedef struct SocketAddrMapT SocketAddrMapT
typedef struct SocketStateT SocketStateT
local state
Function Documentation
int32_t _SocketAddrMapAdd (SocketStateT * pState, const struct sockaddr_in6 * pAddr6, int32_t iAddrSize)
Add an IPv6 address to the address mapping table.
Parameters
*pState - module state
*pAddr6 - address to add to the mapping table
iAddrSize - size of address
Returns
int32_t - negative=error, else virtual IPv4 address for newly mapped IPv6 address
Version
04/17/2013 (jbrookes)
References _SocketAddrMapAlloc(), SocketStateT::AddrMap, SocketAddrMapT::iNumEntries, SocketAddrMapEntryT::iVirtualAddress, and SocketAddrMapT::pMapEntries.
int32_t _SocketAddrMapAlloc (SocketStateT * pState, int32_t iNumEntries)
Alloc (or re-alloc) address map entry list.
Parameters
*pState - module state
iNumEntries - new entry list size
Returns
int32_t - negative=error, zero=success
Version
04/17/2013 (jbrookes)
References SocketStateT::AddrMap, DirtyMemAlloc(), DirtyMemFree(), ds_memcpy(), SocketStateT::iMemGroup, SocketAddrMapT::iNumEntries, NULL, SocketAddrMapT::pMapEntries, SocketStateT::pMemGroupUserData, and SOCKET_MEMID.
Referenced by _SocketAddrMapAdd().
int32_t SocketCallback (SocketT * pSocket, int32_t iMask, int32_t iIdle, void * pRef, int32_t(*)(SocketT *pSocket, int32_t iFlags, void *pRef) pProc)
Register a callback routine for notification of socket events. Also includes timeout support.
Parameters
*pSocket - socket reference
iMask - valid callback events (CALLB_NONE, CALLB_SEND, CALLB_RECV)
iIdle - if nonzero, specifies the number of ticks between idle calls
*pRef - user data to be passed to proc
*pProc - user callback
Returns
int32_t - zero
Note
A callback will reset the idle timer, so when specifying a callback and an idle processing time, the idle processing time represents the maximum elapsed time between calls.
Version
03/22/2013 (jbrookes)
References SocketT::pCallback, SocketT::pCallRef, pProc, pRef, SocketT::uCallIdle, and SocketT::uCallMask.
int32_t SocketRecvfrom (SocketT * pSock, const char * pBuf, int32_t iLen, int32_t iFlags, struct sockaddr * pFrom, int32_t * pFromLen)
Receive data from a remote host. If socket is a connected stream, then data can only come from that source. A datagram socket can receive from any remote host.
Parameters
*pSock - socket reference
*pBuf - buffer to receive data
iLen - length of recv buffer
iFlags - unused
*pFrom - address data was received from (NULL=ignore)
*pFromLen - length of address
Returns
int32_t - positive=data bytes received, else standard error code
Version
03/22/2013 (jbrookes)
References SocketT::bAsyncRecv, ds_memcpy_s(), FALSE, SocketT::iLastError, SocketT::iType, NetCritEnter(), NetCritLeave(), NetTick(), NULL, SocketT::pCallback, SocketT::pRecvQueue, SocketT::RecvAddr, SocketT::RecvRate, SocketT::RemoteAddr, SockaddrInSetMisc, SOCKERR_CLOSED, SOCKERR_INVALID, SOCKERR_NONE, SocketPacketQueueRem(), SocketRateThrottle(), SocketRateUpdate(), and SocketT::uSocket.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:19