DirtySock: voipconnection.c File Reference
voipconnection.c File Reference
VoIP virtual connection manager.
#include <stdio.h>
#include <string.h>
#include "DirtySDK/platform.h"
#include "DirtySDK/dirtysock.h"
#include "DirtySDK/dirtysock/dirtymem.h"
#include "DirtySDK/voip/voipdef.h"
#include "voippriv.h"
#include "voipcommon.h"
#include "voipconnection.h"
Macros
#define VOIP_PACKET_VERSION ('g')
current packet version
#define VOIP_PING_RATE (500)
send ping packets twice a second
#define VOIP_TIMEOUT (15*1000)
default voip data timeout
#define VOIP_CONNTIMEOUT (10*1000)
connection timeout
#define VOIP_MSPERPACKET (100)
number of ms per network packet (100ms = 10hz)
#define VOIP_TALKTIMEOUT (100)
clear talking flag after 1/10th sec of no voice
#define VOIP_CONNECTION_DEBUG (DIRTYCODE_DEBUG && FALSE)
enable for verbose debugging
#define VOIP_RELIABLE_DEBUG (DIRTYCODE_DEBUG && TRUE)
#define VOIP_IPPROTO (IPPROTO_IP)
#define VOIP_SamePacketType(_packetHead1, _packetHead2) (!memcmp((_packetHead1)->aType, (_packetHead2)->aType, sizeof((_packetHead1)->aType)))
compare packet types
#define VOIP_ConnID(_pConnectionlist, _pConnection) ((uint32_t)((_pConnection)-(_pConnectionlist)->pConnections))
get connection ID
Functions
int32_t VoipConnectionStartup (VoipConnectionlistT *pConnectionlist, int32_t iMaxPeers)
Startup a connectionlist.
void VoipConnectionSetCallbacks (VoipConnectionlistT *pConnectionlist, VoipConnectRecvVoiceCbT *pVoiceCb, VoipConnectRegUserCbT *pRegUserCb, void *pUserData)
Set required recv voice and reg user callbacks.
void VoipConnectionShutdown (VoipConnectionlistT *pConnectionlist)
Shutdown a connectionlist.
uint8_t VoipConnectionCanAllocate (VoipConnectionlistT *pConnectionlist, int32_t iConnID)
Check whether a given Connection ID can be allocated in this Connection List.
int32_t VoipConnectionStart (VoipConnectionlistT *pConnectionlist, int32_t iConnID, uint32_t uAddr, uint32_t uConnPort, uint32_t uBindPort, uint32_t uClientId, uint32_t uSessionId)
Start a connection to a peer.
void VoipConnectionUpdate (VoipConnectionlistT *pConnectionlist)
Update all connections.
void VoipConnectionStop (VoipConnectionlistT *pConnectionlist, int32_t iConnID, int32_t bSendDiscMsg)
Stop a connection with a peer.
void VoipConnectionRemove (VoipConnectionlistT *pConnectionlist, int32_t iConnID)
Remove specified connection.
void VoipConnectionSend (VoipConnectionlistT *pConnectionlist, const uint8_t *pVoiceData, int32_t iDataSize, const uint8_t *pMetaData, int32_t iMetaDataSize, uint32_t uUserIndex, uint8_t uSendSeqn)
Send data to peer.
int32_t VoipConnectionFlush (VoipConnectionlistT *pConnectionlist, int32_t iConnID)
Send currently queued voice data, if any.
void VoipConnectionRegisterRemoteTalkers (VoipConnectionlistT *pConnectionlist, int32_t iConnID, uint32_t bRegister)
Register/unregister remote users associated with the given connection.
void VoipConnectionSetSendMask (VoipConnectionlistT *pConnectionlist, uint32_t uSendMask)
Set connections to send to.
void VoipConnectionSetRecvMask (VoipConnectionlistT *pConnectionlist, uint32_t uRecvMask)
Set connections to receive from.
int32_t VoipConnectionAddSessionId (VoipConnectionlistT *pConnectionlist, int32_t iConnId, uint32_t uSessionId)
Add a session ID the set of higher level sessions sharing the specified VoIP connection.
int32_t VoipConnectionDeleteSessionId (VoipConnectionlistT *pConnectionlist, int32_t iConnId, uint32_t uSessionId)
Delete a session ID from the set of sessions sharing this voip connection.
void VoipConnectionReliableBroadcastUser (VoipConnectionlistT *pConnectionlist, uint8_t uLocalUserIndex, uint32_t bParticipating)
Use this function to broadcast local user join-in-progress/leave-in-progress data that needs to be sent reliably on all active connections (or connections in ST_CONN state).
void VoipConnectionReliableBroadcastOpaque (VoipConnectionlistT *pConnectionlist, const uint8_t *pData, uint16_t uDataSize)
Use this function to broadcast opaque data that needs to be sent reliably on all active connections (or connections in ST_CONN state).
Detailed Description
VoIP virtual connection manager.
Attention
Copyright (c) Electronic Arts 2004. ALL RIGHTS RESERVED.
Note
None of the packet types used by DirtySDK's voip implementation is reliable, i.e. delivery to the other end of the connection is not guaranteed.
There exists some sort of reliability during the connection establishment handshaking: voip connect packets (VoipConnPacketT) are being re-sent
until packets are detected as received by the other end of the connection. This mechanism is specific to the connection establishment and is
not generic enough for re-use after connection establishment.
MLU VoIP join-in-progress (local user added to voip console-to-console connection after connection established) requires some
post-initial-handshaking reliability. For that purpose specifically, a reliability scheme was implemented with protocol components
piggy-backed on voip micr packets and voip ping packets. Those protocol components are:  DATA, ACK and ACKCNF.
    DATA   (producer->consumer): data to be delivered reliably (tagged with a sequence number)
    ACK    (consumer->producer): acked sequence number
    ACKCNF (producer->consumer): acked sequence number confirmation (can be leveraged by the consumer to stop “acking” and eliminate the associated “acking” overhead)
From the perspective of a game console producing reliable data, an "outbound reliable data flow" on a given connection looks like this:
    Reliable data producer (local)                  Reliable Data Consumer (remote)
                             ------    DATA    ----->
                            <------    ACK     -----
                             ------   ACKCNF   ----->
From the perspective of a game console consuming reliable data, an "inbound reliable data flow" on a given connection looks like this:
    Reliable data consumer (local)                  Reliable Data Producer (remote)
                            <------    DATA    -----
                             ------    ACK     ----->
                            <------   ACKCNF   -----
ACK and ACKCNF protocol components are added, when necessary, as a pair to the beginning of any ping or voip packet. When the packet
is flagged with VOIP_PACKET_RELIABLE_FLAG_ACK_ACKCNF, then it contains at least one such entry. The exact number of entries is
captured in the first byte of the packet payload. Then each entry consists of a 4-byte destination client id and a 1-byte field where:
    bit 7       = ACKCNF (1 means "continue acking", 0 means "you can stop acking")
    bits 0-6    = ACK (acked seq number in the 1 to 127 range - 0 means "unused" or "invalid")
DATA protocol component is also added at the beginning of the voip packet payload (after ACK+ACkNF if any). When the packet
is flagged with VOIP_PACKET_RELIABLE_FLAG_DATA, then it contains at least one such entry. The exact number of entries is
captured in the first byte of the packet payload (or in the first byte following the ACK+ACKCNF portion). When a DATA entry
is created, it is queued with the SAME sequence number in the outbound queue of all connections. The use of the SAME
sequence number is key in not having to specifiy what destination console the entry is for. For P2P connectivity this is not
really a concern as packets are exchanged directly between consoles. But for voipserver-based connectivity, the voip micr
packets are sent once to the voipserver and then rebroadcasted from there to all other peers. Consequently it is important that
the sequence number that the DATA entries are tagged with are meaningful to all remote peers.
For voipserver-based voip:
    Have a look at addition comments in _VoipReliableDataOutProcess() describing the logics used to add DATA entries
    to voip micr packets sent to the voipserver.
Version
1.0 03/17/2004 (jbrookes) First Version
1.1 01/06/2008 (mclouatre) Created VoipConnectionAddRef(), VoipConnectionRemoveRef(), VoipConnectionResetRef(), VoipConnectionGetFallbackAddr()
1.2 10/26/2009 (mclouatre) Renamed from xbox/voipconnection.c to xenon/voipconnectionxenon.c
1.3 11/13/2009 (jbrookes) Merged Xenon back into common version
1.4 09/29/2014 (mclouatre) Addes support for voip reliable data
Macro Definition Documentation
#define VOIP_CONNECTION_DEBUG (DIRTYCODE_DEBUG && FALSE)
enable for verbose debugging
#define VOIP_ConnID (_pConnectionlist, _pConnection) ((uint32_t)((_pConnection)-(_pConnectionlist)->pConnections))
get connection ID
Referenced by VoipConnectionSetRecvMask(), and VoipConnectionStart().
#define VOIP_CONNTIMEOUT (10*1000)
connection timeout
#define VOIP_IPPROTO (IPPROTO_IP)
Referenced by VoipConnectionStart().
#define VOIP_MSPERPACKET (100)
number of ms per network packet (100ms = 10hz)
Referenced by VoipConnectionSend().
#define VOIP_PACKET_VERSION ('g')
current packet version
#define VOIP_PING_RATE (500)
send ping packets twice a second
#define VOIP_RELIABLE_DEBUG (DIRTYCODE_DEBUG && TRUE)
#define VOIP_SamePacketType (_packetHead1, _packetHead2) (!memcmp((_packetHead1)->aType, (_packetHead2)->aType, sizeof((_packetHead1)->aType)))
compare packet types
#define VOIP_TALKTIMEOUT (100)
clear talking flag after 1/10th sec of no voice
Referenced by VoipConnectionUpdate().
#define VOIP_TIMEOUT (15*1000)
default voip data timeout
Referenced by VoipConnectionStartup().
Function Documentation
int32_t VoipConnectionAddSessionId (VoipConnectionlistT * pConnectionlist, int32_t iConnId, uint32_t uSessionId)
Add a session ID the set of higher level sessions sharing the specified VoIP connection.
Parameters
*pConnectionlist - connectionlist
iConnId - connection ID
uSessionId - session ID to be added
Returns
int32_t - 0 for success, negative for failure
Note
Maintaning a set of session IDs per voip connection is required to support cases where two consoles are involved in a P2P game and a pg simultaneously. Both of these constructs will have a different session ID over the same shared voip connection. Under some specific race conditions affecting the order at which Blaze messages are processed by each game client, it is very possible that the pg session id is setup first on one side and second on the other side thus leading to VOIP connectivity failures if the voip connection construct is not supporting multiple concurrent session IDs.
Version
08/30/2011 (mclouatre)
References VoipConnectionlistT::NetCrit, NetCritEnter(), NetCritLeave(), NetPrintf, VoipConnectionlistT::pConnections, VoipConnectionT::uSessionId, and VOIP_MAXSESSIONIDS.
Referenced by VoipCommonControl(), and VoipConnectionStart().
uint8_t VoipConnectionCanAllocate (VoipConnectionlistT * pConnectionlist, int32_t iConnID)
Check whether a given Connection ID can be allocated in this Connection List.
Parameters
*pConnectionlist - connection list ref
iConnID - connection index
Returns
uint8_t - Whether a connection can be allocated with given ConnID
Version
02/19/2008 (jrainy)
References VoipConnectionT::eState, VoipConnectionlistT::iMaxConnections, and VoipConnectionlistT::pConnections.
Referenced by VoipCommonStatus().
int32_t VoipConnectionDeleteSessionId (VoipConnectionlistT * pConnectionlist, int32_t iConnId, uint32_t uSessionId)
Delete a session ID from the set of sessions sharing this voip connection.
Parameters
*pConnectionlist - connectionlist
iConnId - connection id
uSessionId - session ID to be deleted
Returns
int32_t - 0 for success, negative for failure
Version
08/30/2011 (mclouatre)
References VoipConnectionlistT::NetCrit, NetCritEnter(), NetCritLeave(), NetPrintf, VoipConnectionlistT::pConnections, VoipConnectionT::uSessionId, and VOIP_MAXSESSIONIDS.
Referenced by VoipCommonControl().
int32_t VoipConnectionFlush (VoipConnectionlistT * pConnectionlist, int32_t iConnID)
Send currently queued voice data, if any.
Parameters
*pConnectionlist - connectionlist to send to
iConnID - connection ident of connection to flush
Returns
int32_t - number of voice packets flushed
Note
Currently only useful on Xenon
Version
01/04/2006 (jbrookes)
References VoipConnectionT::eState, VoipMicrPacketT::MicrInfo, NetTick(), VoipConnectionlistT::pConnections, TRUE, VoipMicrInfoT::uNumSubPackets, VoipConnectionlistT::uSendMask, VOIP_MAXLOCALUSERS_EXTENDED, and VoipConnectionT::VoipMicrPacket.
Referenced by VoipCommonControl().
void VoipConnectionRegisterRemoteTalkers (VoipConnectionlistT * pConnectionlist, int32_t iConnID, uint32_t bRegister)
Register/unregister remote users associated with the given connection.
Parameters
*pConnectionlist - connectionlist to send to
iConnID - connection ident of connection to flush
bRegister - if TRUE register talkers, else unregister them
Version
01/04/2006 (jbrookes)
References VoipConnectionlistT::bUpdateMute, VoipConnectionlistT::pCbUserData, VoipConnectionlistT::pConnections, VoipConnectionlistT::pRegUserCb, VoipConnectionT::RemoteUsers, TRUE, VOIP_MAXLOCALUSERS_EXTENDED, and VOIP_NullUser.
Referenced by VoipConnectionSetRecvMask().
void VoipConnectionReliableBroadcastOpaque (VoipConnectionlistT * pConnectionlist, const uint8_t * pData, uint16_t uDataSize)
Use this function to broadcast opaque data that needs to be sent reliably on all active connections (or connections in ST_CONN state).
Parameters
*pConnectionlist - connectionlist
*pData - pointer to buffer filled with reliable data to be broadcasted
uDataSize - reliable data size (in bytes)
Version
09/18/2014 (mclouatre)
References ReliableDataT::aData, ds_memcpy_s(), ReliableDataT::info, ReliableDataInfoT::uSize, ReliableDataInfoT::uType, VOIP_CONNID_ALL, and VOIP_RELIABLE_TYPE_OPAQUE.
void VoipConnectionReliableBroadcastUser (VoipConnectionlistT * pConnectionlist, uint8_t uLocalUserIndex, uint32_t bParticipating)
Use this function to broadcast local user join-in-progress/leave-in-progress data that needs to be sent reliably on all active connections (or connections in ST_CONN state).
Parameters
*pConnectionlist - connectionlist
uLocalUserIndex - local user index
bParticipating - TRUE if user joined-in-progress, FALSE if user left-in-progress
Version
09/18/2014 (mclouatre)
References ReliableDataT::aData, ds_memcpy_s(), ReliableDataT::info, VoipConnectionlistT::LocalUsers, ReliableDataInfoT::uSize, ReliableDataInfoT::uType, VOIP_CONNID_ALL, VOIP_RELIABLE_TYPE_USERADD, and VOIP_RELIABLE_TYPE_USERREM.
void VoipConnectionRemove (VoipConnectionlistT * pConnectionlist, int32_t iConnID)
Remove specified connection.
Parameters
*pConnectionlist - connection list ref
iConnID - connection to remove
Version
05/24/2007 (jbrookes)
References NetPrintf, VoipConnectionlistT::pConnections, VoipConnectionlistT::uRecvMask, VoipConnectionlistT::uRecvVoice, VoipConnectionlistT::uSendMask, VoipConnectionlistT::uUserRecvMask, VoipConnectionlistT::uUserSendMask, VoipCommonDelMask(), and VoipConnectionSetRecvMask().
Referenced by VoipRemove().
void VoipConnectionSend (VoipConnectionlistT * pConnectionlist, const uint8_t * pVoiceData, int32_t iDataSize, const uint8_t * pMetaData, int32_t iMetaDataSize, uint32_t uUserIndex, uint8_t uSendSeqn)
Send data to peer.
Parameters
*pConnectionlist - connectionlist to send to
*pVoiceData - pointer to data to send
iDataSize - size of data to send
*pMetaData - pointer to metadata to be added to voip packet
iMetaDataSize - size of metadata
uUserIndex - local user index
uSendSeqn - seq nb
Version
03/17/2004 (jbrookes)
References VoipMicrPacketT::aData, VoipConnectionlistT::aIsParticipating, VoipConnectionT::aVoiceSendTimer, ds_memcpy(), VoipConnectionT::eState, FALSE, VoipMicrPacketT::Head, VoipConnectionlistT::iMaxConnections, VoipConnectionT::iMaxSubPktSize, VoipConnectionT::iVoipServerConnId, VoipMicrPacketT::MicrInfo, NetPrintf, NetTick(), NetTickDiff, NULL, VoipConnectionlistT::pConnections, TRUE, VoipPacketHeadT::uFlags, VoipConnectionlistT::uLastVoiceTime, VoipConnectionlistT::uLocalUserStatus, VoipMicrInfoT::uNumSubPackets, VoipConnectionlistT::uSendMask, VoipMicrInfoT::uSubPacketSize, VoipMicrInfoT::uUserIndex, VOIP_CONNID_ALL, VOIP_CONNID_NONE, VOIP_LOCAL_USER_TALKING, VOIP_MAXLOCALUSERS, VOIP_MAXSUBPKTS_PER_PKT, VOIP_MSPERPACKET, VOIP_PACKET_STATUS_FLAG_METADATA, VOIP_SHARED_USER_INDEX, VoipGetRef(), VoipConnectionT::VoipMicrPacket, and VoipStatus().
void VoipConnectionSetCallbacks (VoipConnectionlistT * pConnectionlist, VoipConnectRecvVoiceCbT * pVoiceCb, VoipConnectRegUserCbT * pRegUserCb, void * pUserData)
Set required recv voice and reg user callbacks.
Parameters
*pConnectionlist - connectionlist to register callbacks for
*pVoiceCb - voice callback to register
*pRegUserCb - user reg callback to register
*pUserData - pointer to user data
Version
03/20/2004 (jbrookes)
References VoipConnectionlistT::pCbUserData, VoipConnectionlistT::pRegUserCb, and VoipConnectionlistT::pVoiceCb.
Referenced by VoipCommonStartup().
void VoipConnectionSetRecvMask (VoipConnectionlistT * pConnectionlist, uint32_t uRecvMask)
Set connections to receive from.
Parameters
*pConnectionlist - connectionlist to send to
uRecvMask - connection receive mask
Version
03/22/2004 (jbrookes)
References VoipConnectionT::eState, FALSE, VoipConnectionlistT::iMaxConnections, VoipConnectionlistT::NetCrit, NetCritEnter(), NetCritLeave(), NetPrintf, VoipConnectionlistT::pConnections, ST_CONN, TRUE, VoipConnectionlistT::uRecvMask, VOIP_ConnID, VoipCommonSetMask(), and VoipConnectionRegisterRemoteTalkers().
Referenced by VoipCommonUpdateRemoteStatus(), and VoipConnectionRemove().
void VoipConnectionSetSendMask (VoipConnectionlistT * pConnectionlist, uint32_t uSendMask)
Set connections to send to.
Parameters
*pConnectionlist - connectionlist to send to
uSendMask - connection send mask
Version
03/22/2004 (jbrookes)
References VoipConnectionlistT::uSendMask, and VoipCommonSetMask().
Referenced by VoipCommonUpdateRemoteStatus().
void VoipConnectionShutdown (VoipConnectionlistT * pConnectionlist)
Shutdown a connectionlist.
Parameters
*pConnectionlist - connectionlist to close
Version
03/20/2004 (jbrookes)
References DirtyMemFree(), VoipConnectionlistT::NetCrit, NetCritKill(), NetPrintf, NULL, VoipConnectionlistT::pConnections, VoipConnectionlistT::pSocket, SocketClose(), VOIP_MEMID, and VoipMemGroupQuery().
Referenced by VoipCommonShutdown().
int32_t VoipConnectionStart (VoipConnectionlistT * pConnectionlist, int32_t iConnID, uint32_t uAddr, uint32_t uConnPort, uint32_t uBindPort, uint32_t uClientId, uint32_t uSessionId)
Start a connection to a peer.
Parameters
*pConnectionlist - connection list ref
iConnID - connection index
uAddr - address to connect to
uConnPort - connection port
uBindPort - local bind port
uClientId - id of client to connect to (cannot be 0)
uSessionId - session id (optional)
Returns
int32_t - connection identifier on success, negative=failure
Version
03/18/2004 (jbrookes)
References CALLB_RECV, ds_memcpy_s(), VoipConnectionT::eState, VoipMicrPacketT::Head, VoipConnectionT::iVoipServerConnId, VoipConnectionlistT::NetCrit, NetCritEnter(), NetCritLeave(), NetPrintf, NetTick(), NULL, VoipConnectionlistT::pSocket, VoipConnectionT::SendAddr, SockaddrInGetPort, SockaddrInit, SockaddrInSetPort, SOCKERR_NONE, SocketBind(), SocketCallback(), SocketClose(), SocketHtonl(), SocketHtons(), SocketInfo(), SocketNtohl(), SocketNtohs(), SocketOpen(), ST_CONN, VoipConnectionlistT::uBindPort, VoipConnectionT::uClientId, VoipConnectionlistT::uClientId, VoipConnectionT::uLastRecv, VoipConnectionT::uRecvSeqn, VoipConnectionT::uRemoteConnStatus, VoipConnectionT::uRemoteUserStatus, VOIP_ConnID, VOIP_CONNID_NONE, VOIP_IPPROTO, VOIP_MAXLOCALUSERS, VOIP_MAXLOCALUSERS_EXTENDED, VoipConnectionAddSessionId(), and VoipConnectionT::VoipMicrPacket.
Referenced by VoipConnect().
int32_t VoipConnectionStartup (VoipConnectionlistT * pConnectionlist, int32_t iMaxPeers)
Startup a connectionlist.
Parameters
*pConnectionlist - connectionlist to init
iMaxPeers - max number of connections to support
Returns
int32_t - zero=success, negative=error
Version
03/20/2004 (jbrookes)
References DirtyMemAlloc(), VoipConnectionlistT::iDataTimeout, VoipConnectionlistT::iFriendConnId, VoipConnectionlistT::iMaxConnections, VoipConnectionT::iVoipServerConnId, VoipConnectionlistT::NetCrit, NetCritInit(), NetPrintf, NULL, VoipConnectionlistT::pConnections, VoipConnectionlistT::uOutSeqNb, VOIP_CONNID_NONE, VOIP_MAXCONNECT, VOIP_MEMID, VOIP_TIMEOUT, and VoipMemGroupQuery().
Referenced by VoipCommonStartup().
void VoipConnectionStop (VoipConnectionlistT * pConnectionlist, int32_t iConnID, int32_t bSendDiscMsg)
Stop a connection with a peer.
Parameters
*pConnectionlist - connection list ref
iConnID - connection to stop, or VOIP_CONNID_ALL to stop all connections
bSendDiscMsg - TRUE - send DISC msg to peer; FALSE - do not send DISC msg to peer
Version
03/18/2004 (jbrookes)
References VoipConnectionlistT::iMaxConnections, NetPrintf, VoipConnectionlistT::pConnections, and VOIP_CONNID_ALL.
Referenced by VoipDisconnect2().
void VoipConnectionUpdate (VoipConnectionlistT * pConnectionlist)
Update all connections.
Parameters
*pConnectionlist - connection list
Version
03/18/2004 (jbrookes)
References VoipConnectionlistT::NetCrit, NetCritEnter(), NetCritLeave(), NetTick(), NetTickDiff, VoipConnectionlistT::pConnections, VoipConnectionlistT::uLastVoiceTime, VoipConnectionlistT::uLocalUserStatus, VoipConnectionlistT::uRecvVoice, VOIP_LOCAL_USER_TALKING, VOIP_MAXLOCALUSERS, and VOIP_TALKTIMEOUT.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:41