DirtySock: friendapipriv.h File Reference
friendapipriv.h File Reference
Header for private friend api functions.
#include "DirtySDK/dirtysock/netconn.h"
Data Structures
struct FriendApiCallbackT
struct FriendApiCommonRefT
friend api common ref
Typedefs
typedef struct FriendApiCallbackT FriendApiCallbackT
typedef struct FriendApiCommonRefT FriendApiCommonRefT
friend api common ref
Functions
FriendApiRefT * FriendApiPrivCreate (void)
Create the ps3 friendapi object.
void FriendApiPrivUpdate (FriendApiRefT *pFriendApiRef)
Give module time to perform periodic processing.
int32_t FriendApiPrivGetFriendsList (FriendApiRefT *pFriendApiRef, uint32_t uUserIndex, FriendDataT *pFriendsList, void *pRawDataList1, int32_t *pFriendCount)
Returns the number of friends and list of friends in the user-provided buffers. Set pFriendsList to NULL to find out the number of friends that will be returned in the friendslist.
int32_t FriendApiPrivStatus (FriendApiRefT *pFriendApiRef, int32_t iSelect, void *pBuf, int32_t iBufSize)
Get status information.
int32_t FriendApiPrivControl (FriendApiRefT *pFriendApiRef, int32_t iControl, int32_t iValue, int32_t iValue2, void *pValue)
Control behavior of module.
void FriendApiPrivDestroy (FriendApiRefT *pFriendApiRef)
Destroy the ps3 friend api object.
uint32_t FriendApiPrivIsUserFriend (FriendApiRefT *pFriendApiRef, uint32_t uUserIndex, void *pUserId)
Returns whether a given user is friend.
uint32_t FriendApiPrivIsUserRealFriend (FriendApiRefT *pFriendApiRef, uint32_t uUserIndex, void *pUserId)
Returns whether a given user is a 'real' friend.
uint32_t FriendApiPrivIsUserBlocked (FriendApiRefT *pFriendApiRef, uint32_t uUserIndex, void *pUserId)
Returns whether a given user is blocked or not.
int32_t FriendApiPrivBlockUser (FriendApiRefT *pFriendApiRef, uint32_t uUserIndex, void *pUserId)
Initiates a block user operation. After calling this function, if the return code is "success", the caller needs to wait for the FRIENDAPI_EVENT_BLOCK_USER_RESULT completion event.
int32_t FriendApiPrivUnblockUser (FriendApiRefT *pFriendApiRef, uint32_t uUserIndex, void *pUserId)
Unblock user. Currently a NO-OP on PS3.
int32_t FriendApiPrivGetBlockList (FriendApiRefT *pFriendApiRef, uint32_t uUserIndex, BlockedUserDataT *pBlockList, int32_t *pUsersCount)
Returns the list of blocked users in the user-provided buffers.
int32_t FriendApiPrivGetBlockListVersion (FriendApiRefT *pFriendApiRef, uint32_t *pVersion)
Returns the current version of the list of blocked users.
void FriendApiPrivNotifyEvent (FriendApiRefT *pFriendApiRef, FriendEventDataT *pEventData)
Invokes the different callbacks registered by higher-level modules.
Detailed Description
Header for private friend api functions.
Attention
Copyright (c) Electronic Arts 2010.
Version
02/01/2010 (mclouatre)
Typedef Documentation
typedef struct FriendApiCallbackT FriendApiCallbackT
typedef struct FriendApiCommonRefT FriendApiCommonRefT
friend api common ref
Function Documentation
int32_t FriendApiPrivBlockUser (FriendApiRefT * pFriendApiRef, uint32_t uUserIndex, void * pUserId)
Initiates a block user operation. After calling this function, if the return code is "success", the caller needs to wait for the FRIENDAPI_EVENT_BLOCK_USER_RESULT completion event.
Parameters
*pFriendApiRef - module reference
uUserIndex - local user index
*pUserId - user to be blocked (pointer to SceNpId)
Returns
int32_t - 0 for success, negative for failure
Note
Experimentation showed that, in a scenario where the specified user is already a friend, sceNpBasicAddBlockListEntry() returns 0 for success, but later in time the NP Basic handler is invoked by the system with: iEvent=SCE_NP_BASIC_EVENT_ADD_BLOCKLIST_RESULT/11 iRetCode=SCE_NP_BASIC_ERROR_BLOCKLIST_ADD_FAILED/0x8002a675
Version
02/24/2011 (mclouatre)
References DirtyErrGetName(), and NetPrintf.
Referenced by FriendApiBlockUser().
int32_t FriendApiPrivControl (FriendApiRefT * pFriendApiRef, int32_t iControl, int32_t iValue, int32_t iValue2, void * pValue)
Control behavior of module.
Parameters
*pFriendApiRef - module reference
iControl - status selector
iValue - control value
iValue2 - control value
*pValue - control value
Returns
int32_t - selector specific
Note
iControl can be one of the following:
        'stop' - notifies the Friend API that it is time to unregister the handler to get PS3 friends events (if nobody else relies on it)
Version
05/19/2010 (mclouatre)
References FriendApiRefT::bNpBasicHandlerRegistered, FriendApiRefT::callbackCrit, DirtyErrGetName(), FALSE, Ps3CallbackCritT::locker, NetCritEnter(), NetCritLeave(), NetPrintf, and TRUE.
Referenced by FriendApiControl(), and FriendApiPrivDestroy().
FriendApiRefT* FriendApiPrivCreate (void)
Create the ps3 friendapi object.
Returns
FriendApiRefT* - module reference (NULL = failed)
Version
04/19/2010 (mclouatre)
References FriendApiRefT::callbackCrit, FriendApiRefT::common, DirtyMemAlloc(), DirtyMemGroupQuery(), FRIENDAPI_MEMID, FriendApiCommonRefT::iMemGroup, Ps3CallbackCritT::locker, NetCritInit(), NetPrintf, FriendApiCommonRefT::notifyCrit, NULL, and FriendApiCommonRefT::pMemGroupUserData.
Referenced by FriendApiCreate().
void FriendApiPrivDestroy (FriendApiRefT * pFriendApiRef)
Destroy the ps3 friend api object.
Parameters
*pFriendApiRef - module reference
Version
04/19/2010 (mclouatre)
References FriendApiRefT::callbackCrit, FriendApiRefT::common, DirtyMemFree(), FRIENDAPI_MEMID, FriendApiPrivControl(), FriendApiCommonRefT::iMemGroup, Ps3CallbackCritT::locker, NetCritKill(), NetPrintf, FriendApiCommonRefT::notifyCrit, NULL, and FriendApiCommonRefT::pMemGroupUserData.
Referenced by FriendApiDestroy().
int32_t FriendApiPrivGetBlockList (FriendApiRefT * pFriendApiRef, uint32_t uUserIndex, BlockedUserDataT * pBlockList, int32_t * pUsersCount)
Returns the list of blocked users in the user-provided buffers.
Parameters
*pFriendApiRef - module reference
uUserIndex - local user index
*pBlockList - [out] user-provided buffer to be filled with block list (can be NULL)
pUsersCount - [out] user-provided variable to be filled with number of entries in the block list.
Returns
int32_t - return negative in case of error, and 0 otherwise
Note
Set pBlockList to NULL to find out the number of entries that pBlockList will be filled-in with.
Version
05/10/2011 (mclouatre)
References Ps3BlockListT::aUsers, FriendApiRefT::blockList, Ps3BlockedUserT::bValid, FRIENDAPI_MAX_BLOCKED_USERS, Ps3BlockedUserT::npId, BlockedUserDataT::pRawData1, and BlockedUserDataT::strBlockedUserId.
Referenced by FriendApiGetBlockList().
int32_t FriendApiPrivGetBlockListVersion (FriendApiRefT * pFriendApiRef, uint32_t * pVersion)
Returns the current version of the list of blocked users.
Parameters
*pFriendApiRef - module reference
*pVersion - [out] pointer to buffer to be filled with version number
Returns
int32_t - return negative in case of error, and 0 otherwise
Version
05/10/2011 (mclouatre)
References FriendApiRefT::common, and FriendApiCommonRefT::uBlockListVersion.
Referenced by FriendApiGetBlockListVersion().
int32_t FriendApiPrivGetFriendsList (FriendApiRefT * pFriendApiRef, uint32_t uUserIndex, FriendDataT * pFriendsList, void * pRawDataList1, int32_t * pFriendsCount)
Returns the number of friends and list of friends in the user-provided buffers. Set pFriendsList to NULL to find out the number of friends that will be returned in the friendslist.
Parameters
*pFriendApiRef - module reference
uUserIndex - ignored on PS3
*pFriendsList - [out] user-provided buffer to be filled with the generic friends list (can be NULL)
*pRawDataList1 - [out] user-provided buffer to be filled with array of SceNpUserInfo structures (can be NULL; only used if pFriendsList is valid)
*pFriendsCount - [out] user-provided buffer to be filled with the number of friends in the list (can be NULL)
Returns
int32_t - return negative in case of error, and 0 otherwise
Version
04/19/2010 (mclouatre)
References Ps3FriendsListT::aFriends, Ps3FriendT::bValid, ds_memcpy(), FRIENDAPI_MAX_FRIENDS, FriendApiRefT::friendsList, FriendDataT::pRawData1, FriendDataT::strFriendName, and Ps3FriendT::userInfo.
Referenced by FriendApiGetFriendsList().
uint32_t FriendApiPrivIsUserBlocked (FriendApiRefT * pFriendApiRef, uint32_t uUserIndex, void * pUserId)
Returns whether a given user is blocked or not.
Parameters
*pFriendApiRef - module reference
uUserIndex - local user index (ignored)
*pUserId - user for which "blocked" status needs to be queried (pointer to SceNpId)
Returns
uint32_t - TRUE if user is blocked, FALSE otherwise
Version
02/24/2011 (mclouatre)
References Ps3BlockListT::aUsers, FriendApiRefT::blockList, Ps3BlockedUserT::bValid, FALSE, FRIENDAPI_MAX_BLOCKED_USERS, Ps3BlockedUserT::npId, and TRUE.
Referenced by FriendApiIsUserBlocked().
uint32_t FriendApiPrivIsUserFriend (FriendApiRefT * pFriendApiRef, uint32_t uUserIndex, void * pUserId)
Returns whether a given user is friend.
Parameters
*pFriendApiRef - module reference
uUserIndex - local user index
*pUserId - user for which "friend" status needs to be queried on PS3: pUserId needs to point to a SceNpId struct
Returns
uint32_t - TRUE if user is friend, FALSE otherwise
Version
09/13/2012 (akirchner)
References Ps3FriendsListT::aFriends, FALSE, FRIENDAPI_MAX_FRIENDS, FriendApiRefT::friendsList, TRUE, and Ps3FriendT::userInfo.
Referenced by FriendApiIsUserFriend(), and FriendApiPrivIsUserRealFriend().
uint32_t FriendApiPrivIsUserRealFriend (FriendApiRefT * pFriendApiRef, uint32_t uUserIndex, void * pUserId)
Returns whether a given user is a 'real' friend.
Parameters
*pFriendApiRef - module reference
uUserIndex - local user index
*pUserId - user for which "friend" status needs to be queried on PS3: pUserId needs to point to a SceNpId struct
Returns
uint32_t - TRUE if user is friend, FALSE otherwise
Version
07/17/2013 (jbrookes)
References FriendApiPrivIsUserFriend().
Referenced by FriendApiIsUserRealFriend().
void FriendApiPrivNotifyEvent (FriendApiRefT * pFriendApiRef, FriendEventDataT * pEventData)
Invokes the different callbacks registered by higher-level modules.
Parameters
pFriendApiRef - module reference
pEventData - pointer to event data to be passed to the callbacks
Version
06/15/2010 (mclouatre)
09/06/2012 (akirchner) - ignore FRIENDAPI_EVENT_FRIEND_UPDATED, FRIENDAPI_EVENT_FRIEND_REMOVED and FRIENDAPI_EVENT_BLOCKLIST_UPDATED events if bInitFinished is false
References FriendApiCallbackT::bInitFinished, FriendApiCommonRefT::callback, FriendEventDataT::eventType, FALSE, FRIENDAPI_EVENT_BLOCK_USER_RESULT, FRIENDAPI_EVENT_BLOCKLIST_UPDATED, FRIENDAPI_EVENT_FRIEND_REMOVED, FRIENDAPI_EVENT_FRIEND_UPDATED, FRIENDAPI_EVENT_INIT_COMPLETE, FRIENDAPI_EVENT_MAX, FRIENDAPI_EVENT_MSG_RCVED, FRIENDAPI_EVENT_UNKNOWN, FRIENDAPI_MAX_CALLBACKS, NetCritEnter(), NetCritLeave(), NetPrintf, FriendApiCommonRefT::notifyCrit, FriendApiCallbackT::pNotifyCb, FriendApiCallbackT::pNotifyCbUserData, TRUE, and FriendEventDataT::uUserIndex.
Referenced by FriendApiPrivUpdate().
int32_t FriendApiPrivStatus (FriendApiRefT * pFriendApiRef, int32_t iSelect, void * pBuf, int32_t iBufSize)
Get status information.
Parameters
*pFriendApiRef - module reference
iSelect - status selector
*pBuf - [out] storage for selector-specific output
iBufSize - size of output buffer
Returns
int32_t - selector specific
Note
iSelect can be one of the following:
        'eoip' - stands for "End Of Initial Presence"; returns TRUE if initial presence completed, FALSE otherwise
        'maxf' - returns maximum possible number of friends in the friendslist
        'nphr' - returns TRUE if sceNpBasicRegisterContextSensitiveHandler(), had been called successfully, FALSE otherwise
Version
04/19/2010 (mclouatre)
References Ps3CallbackCritT::bEndOfInitialPresence, FriendApiRefT::bNpBasicHandlerRegistered, FriendApiRefT::callbackCrit, Ps3CallbackCritT::locker, NetCritEnter(), NetCritLeave(), and NetPrintf.
Referenced by FriendApiStatus().
int32_t FriendApiPrivUnblockUser (FriendApiRefT * pFriendApiRef, uint32_t uUserIndex, void * pUserId)
Unblock user. Currently a NO-OP on PS3.
Parameters
*pFriendApiRef - module reference
uUserIndex - local user index
*pUserId - user to be unblocked (pointer to SceNpId)
Returns
int32_t - 0 for success, negative for failure
Note
The PS3 API does not provide any function to unblock a user, i.e remove a user from the blocklist. At the moment, the only way to do this is via the XMB: under the Friends menu, select "Block list",
Version
02/24/2011 (mclouatre)
References NetPrintf.
Referenced by FriendApiUnblockUser().
void FriendApiPrivUpdate (FriendApiRefT * pFriendApiRef)
Give module time to perform periodic processing.
Parameters
*pFriendApiRef - module reference
Version
04/21/2010 (mclouatre)
References Ps3BlockListT::aUsers, Ps3CallbackCritT::bGetBlockList, FriendApiRefT::blockList, FriendEventTypeDataT::BlockListUpdated, FriendEventDataBlocklistUpdatedT::bPresence, Ps3BlockedUserT::bValid, FriendApiRefT::callbackCrit, DirtyErrGetName(), FriendEventDataT::eventType, FriendEventDataT::eventTypeData, FALSE, FRIENDAPI_EVENT_BLOCKLIST_UPDATED, FriendApiPrivNotifyEvent(), Ps3CallbackCritT::iEventsInQueue, Ps3CallbackCritT::locker, NetConnStatus(), NetCritEnter(), NetCritLeave(), NetPrintf, Ps3BlockedUserT::npId, NULL, FriendEventDataT::pRawData1, FriendEventDataT::pRawData2, and TRUE.
Referenced by FriendApiUpdate().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:40