#!/usr/bin/python

import commands, os, sys, time

startnumber = 1
totalnumber = -1
numdigitsusername = 0
numdigitsfilename = 5
password = 'aaaa'
noexecute = 0 

for option in sys.argv[2:]:
	if option.find('-startnumber=') != -1:
		startnumber = int(option[13:])
	elif option.find('-totalnumber=') != -1:
		totalnumber = int(option[13:])
	else:
		print 'usage: qosmulti {start|stop} [ -startnumber -totalnumber ]'
		sys.exit()

if sys.argv[1] == 'start':
	i = 0
	if totalnumber == -1:
		totalnumber = 8
	while i < totalnumber:
		indexUser = str(startnumber + i)
		indexUser = '0' * (numdigitsusername - len(indexUser)) + indexUser
		indexfilename =  str(startnumber + i)
		indexfilename = '0' * (numdigitsfilename - len(indexfilename)) + indexfilename

        	sysstr = './qosstressf stress.cfg ' + indexUser + ' &> qosstress' + indexfilename + '.log'
        	print('executing ' + sysstr)
        	if noexecute == 0:
	        	os.system('(' + sysstr + ')&')
                        time.sleep(0.015)
		i = i + 1
elif sys.argv[1] == 'stop':
	files = commands.getoutput('ls').split()

	for file in files:
		if totalnumber == 0:
			break
		elif file.find('qosstress') != -1 and file.find('.pid') != -1:
			pidfile = open(file, 'r')
			pid = pidfile.readline()
			pidfile.close()
			os.system('kill -TERM ' + pid)
			totalnumber = totalnumber - 1
else:
	print 'usage: gsmulti {start|stop} [ -startnumber -totalnumber ]'
	sys.exit()
