DirtySock: TagField
TagField
Util
Data Structures
struct TagFieldStructPtrT
Macros
#define TagFieldClear(record, reclen) (record)[0] = (0)
#define TagFieldSetStruct(record, reclen, name, bin, pat) TagFieldSetStructure(record, reclen, name, bin, -1, pat)
#define TagFieldGetStruct(data, buf, pat) TagFieldGetStructure(data, buf, -1, pat)
#define TagFieldGetBinary7(data, buffer, buflen) TagFieldGetBinary(data, buffer, buflen)
#define TagFieldSetCopy(record, reclen, name, source) TagFieldSetRaw(record, reclen, name, TagFieldFind(source, name))
#define TagFieldSetUnsignedNumber(_pRecord, _iRecLen, _pName, _uValue) TagFieldSetNumber(_pRecord, _iRecLen, _pName, (signed)(_uValue))
#define TagFieldGetUnsignedNumber(_pData, _uDefVal) (unsigned)TagFieldGetNumber(_pData, (signed)(_uDefVal));
Typedefs
typedef struct TagFieldStructPtrT TagFieldStructPtrT
Enumerations
enum TagFieldPatternE {
TAGFIELD_PATTERN_INT8 = 'b',
TAGFIELD_PATTERN_INT16 = 'w',
TAGFIELD_PATTERN_INT32 = 'l',
TAGFIELD_PATTERN_STR = 's'
}
Functions
DIRTYCODE_API char TagFieldDivider (char iDivider)
Set the default field divider character.
DIRTYCODE_API void TagFieldFormat (char *record, unsigned char marker)
Convert a tag buffer to use specified marker char (also converts bulk data to use strictly newlines).
DIRTYCODE_API const char * TagFieldFind (const char *record, const char *name)
Search the buffer and locate the named field. Now optimized to only use = as field separator (old version allowed equals and colen).
DIRTYCODE_API const char * TagFieldFind2 (const char *record, const char *name1, const char *name2)
Search the buffer and locate the two-part named field (the names are catenated together).
DIRTYCODE_API const char * TagFieldFindIdx (const char *pRecord, const char *pName, int32_t iIdx)
Search the buffer and locate the indexed named field (the tag to find is a concatenation of "pName" and the provided index.
DIRTYCODE_API int32_t TagFieldDelete (char *record, const char *name)
Delete a field from the record.
DIRTYCODE_API int32_t TagFieldRename (char *record, int32_t reclen, const char *oldname, const char *newname)
Rename a field within the record.
DIRTYCODE_API int32_t TagFieldDupl (char *record, int32_t reclen, const char *data)
Duplicate an entire record.
DIRTYCODE_API int32_t TagFieldFirst (const char *record, char *nameptr, int32_t namelen)
Extract the first field name in record.
DIRTYCODE_API int32_t TagFieldSetNumber (char *record, int32_t reclen, const char *name, int32_t value)
Set a numeric field.
DIRTYCODE_API int32_t TagFieldSetNumber64 (char *record, int32_t reclen, const char *name, int64_t value)
Set a 64-bit numeric field.
DIRTYCODE_API int32_t TagFieldSetFlags (char *record, int32_t reclen, const char *name, int32_t value)
Set a flags field.
DIRTYCODE_API int32_t TagFieldSetAddress (char *record, int32_t reclen, const char *name, uint32_t addr)
Set an ip-address field.
DIRTYCODE_API int32_t TagFieldSetToken (char *record, int32_t reclen, const char *name, int32_t token)
Set a token field.
DIRTYCODE_API int32_t TagFieldSetString (char *record, int32_t reclen, const char *name, const char *value)
Set a string field.
DIRTYCODE_API int32_t TagFieldSetBinary (char *record, int32_t reclen, const char *name, const void *value, int32_t vallen)
Set a binary field.
DIRTYCODE_API int32_t TagFieldSetBinary7 (char *record, int32_t reclen, const char *name, const void *value, int32_t vallen)
Set a binary field using more efficient 7-bits-per-byte encoding.
DIRTYCODE_API int32_t TagFieldSetStructure (char *record, int32_t reclen, const char *name, const void *_bin, int32_t len, const char *pat)
Save an entire structure as a single field.
DIRTYCODE_API int32_t TagFieldSetEpoch (char *record, int32_t reclen, const char *name, uint32_t epoch)
Set a date from epoch time using std C time.h lib.
DIRTYCODE_API int32_t TagFieldSetDate (char *record, int32_t reclen, const char *name, int32_t year, int32_t month, int32_t day, int32_t hour, int32_t minute, int32_t second, int32_t gmt)
Set a date field from discrete date components.
DIRTYCODE_API int32_t TagFieldSetFloat (char *pRecord, int32_t iReclen, const char *pName, float fValue)
Set a floating point field.
DIRTYCODE_API int32_t TagFieldSetRaw (char *pRecord, int32_t iReclen, const char *pName, const char *pData_)
Set a raw field (must come from TagFieldGetRaw or TagFieldFind). If the field is encoded badly, it can mess up the tagfield record so don't use data not generated by tagfield functions.
DIRTYCODE_API int32_t TagFieldMerge (char *record, int32_t reclen, const char *merge)
Merge two records together (does not merge bulk data). As of 12/14/2004 rewrite, it no longer returns a merged field count (just that is merged something).
DIRTYCODE_API int32_t TagFieldPrintf (char *pRecord, int32_t iLength, const char *pFormat,...)
Create a tagfield record using printf style descriptor.
DIRTYCODE_API int32_t TagFieldGetNumber (const char *data, int32_t defval)
Get a numeric field.
DIRTYCODE_API int64_t TagFieldGetNumber64 (const char *data, int64_t defval)
Get a 64-bit numeric field.
DIRTYCODE_API int32_t TagFieldGetFlags (const char *data, int32_t defval)
Get a flags field.
DIRTYCODE_API uint32_t TagFieldGetAddress (const char *data, uint32_t defval)
Get an ip address field.
DIRTYCODE_API int32_t TagFieldGetToken (const char *data, int32_t deftok)
Get a token.
DIRTYCODE_API int32_t TagFieldGetDelim (const char *data, char *buffer, int32_t buflen, const char *defval, int32_t index, int32_t delim)
Get item from delimeter separated list.
DIRTYCODE_API int32_t TagFieldGetString (const char *data, char *buffer, int32_t buflen, const char *defval)
Get string field contents.
DIRTYCODE_API int32_t TagFieldGetBinary (const char *data, void *buffer, int32_t buflen)
Get binary field contents.
DIRTYCODE_API int32_t TagFieldGetStructure (const char *data, void *_buf, int32_t len, const char *pat)
Get packed structure field contents.
DIRTYCODE_API uint32_t TagFieldGetEpoch (const char *data, uint32_t defval)
Get date in epoch time.
DIRTYCODE_API int32_t TagFieldGetDate (const char *data, int32_t *pyear, int32_t *pmonth, int32_t *pday, int32_t *phour, int32_t *pminute, int32_t *psecond, int32_t gmt)
Get date.
DIRTYCODE_API float TagFieldGetFloat (const char *pData, float fDefval)
Get a floating point field.
DIRTYCODE_API int32_t TagFieldGetRaw (const char *pData, char *pBuffer, int32_t iBuflen, const char *pDefval)
Get the raw, undecoded value of a field returned as a string.
DIRTYCODE_API const char * TagFieldFindNext (const char *pRecord, char *pName, int32_t iNameSize)
Find next tag field record.
DIRTYCODE_API int32_t TagFieldGetStructureOffsets (const char *pPat, TagFieldStructPtrT *pPtrs, int32_t iNumPtrs)
Populate pPtrs with memory offsets to the individual fields of a structure as defined by the given pattern.
Detailed Description
Macro Definition Documentation
#define TagFieldClear (record, reclen) (record)[0] = (0)
Referenced by WebOfferSetup().
#define TagFieldGetBinary7 (data, buffer, buflen) TagFieldGetBinary(data, buffer, buflen)
#define TagFieldGetStruct (data, buf, pat) TagFieldGetStructure(data, buf, -1, pat)
#define TagFieldGetUnsignedNumber (_pData, _uDefVal) (unsigned)TagFieldGetNumber(_pData, (signed)(_uDefVal));
#define TagFieldSetCopy (record, reclen, name, source) TagFieldSetRaw(record, reclen, name, TagFieldFind(source, name))
#define TagFieldSetStruct (record, reclen, name, bin, pat) TagFieldSetStructure(record, reclen, name, bin, -1, pat)
#define TagFieldSetUnsignedNumber (_pRecord, _iRecLen, _pName, _uValue) TagFieldSetNumber(_pRecord, _iRecLen, _pName, (signed)(_uValue))
Typedef Documentation
typedef struct TagFieldStructPtrT TagFieldStructPtrT
Enumeration Type Documentation
enum TagFieldPatternE
Enumerator
TAGFIELD_PATTERN_INT8
TAGFIELD_PATTERN_INT16
TAGFIELD_PATTERN_INT32
TAGFIELD_PATTERN_STR
Function Documentation
DIRTYCODE_API int32_t TagFieldDelete (char * _record, const char * name)
Delete a field from the record.
Parameters
*_record - data record
*name - field name
Returns
int32_t - negative=no such field, zero=no error
Version
01/23/2000 (gschaefer)
References data, and TagFieldFind().
Referenced by TagFieldSetRaw(), and TagFieldSetString().
DIRTYCODE_API char TagFieldDivider (char iDivider)
Set the default field divider character.
Parameters
iDivider - new divider character
Returns
char - previous divider character
Version
01/23/2000 (gschaefer)
DIRTYCODE_API int32_t TagFieldDupl (char * pRecord, int32_t iReclen, const char * pData)
Duplicate an entire record.
Parameters
*pRecord - data record
iReclen - record length
*pData - data source
Returns
int32_t - number of bytes copied
Version
01/23/2000 (gschaefer)
Referenced by WebOfferResultData().
DIRTYCODE_API const char* TagFieldFind (const char * _pRecord, const char * _pName)
Search the buffer and locate the named field. Now optimized to only use = as field separator (old version allowed equals and colen).
Parameters
*_pRecord - data record
*_pName - field name
Returns
const char * - pointer to data start, or NULL if no such field exists
Version
12/13/2004 (gschaefer)
Referenced by TagFieldDelete(), TagFieldFind2(), TagFieldFindIdx(), TagFieldMerge(), TagFieldPrintf(), TagFieldRename(), WebOfferCommand(), WebOfferGetAlert(), WebOfferGetArticles(), WebOfferGetBusy2(), WebOfferGetCredit(), WebOfferGetForm(), WebOfferGetMarketplace(), WebOfferGetMedia(), WebOfferGetMenu(), WebOfferGetNews(), WebOfferGetPromo(), WebOfferGetStory(), WebOfferHttp(), WebOfferHttpComplete(), WebOfferResource(), and WebOfferUpdate().
DIRTYCODE_API const char* TagFieldFind2 (const char * pRecord, const char * pName1, const char * pName2)
Search the buffer and locate the two-part named field (the names are catenated together).
Parameters
*pRecord - data record
*pName1 - field name
*pName2 - field name 2
Returns
const char * - pointer to data start, or NULL if no such field exists
Version
01/23/2000 (gschaefer)
References ds_strnzcat(), ds_strnzcpy(), and TagFieldFind().
DIRTYCODE_API const char* TagFieldFindIdx (const char * pRecord, const char * pName, int32_t iIdx)
Search the buffer and locate the indexed named field (the tag to find is a concatenation of "pName" and the provided index.
Parameters
*pRecord - data record
*pName - field name
iIdx - index
Returns
const char * - pointer to data start, or NULL if no such field exists
Version
03/23/04 (doneill)
References ds_snzprintf(), and TagFieldFind().
Referenced by WebOfferGetArticles(), WebOfferGetForm(), and WebOfferHttp().
DIRTYCODE_API const char* TagFieldFindNext (const char * pRecord, char * pName, int32_t iNameSize)
Find next tag field record.
Parameters
*pRecord - Data record
*pName - Output buffer to place name of tag in
iNameSize - Size of pName
Returns
const unsigned char * - pointer to start of next record
DIRTYCODE_API int32_t TagFieldFirst (const char * _record, char * nameptr, int32_t namelen)
Extract the first field name in record.
Parameters
*_record - data record
*nameptr - name field return pointer
namelen - max length
Returns
int32_t - zero=empty record, positive=name length
Version
01/23/2000 (gschaefer)
DIRTYCODE_API void TagFieldFormat (char * _record, unsigned char marker)
Convert a tag buffer to use specified marker char (also converts bulk data to use strictly newlines).
Parameters
*_record - data record
marker - new marker
Version
01/23/2000 (gschaefer)
DIRTYCODE_API uint32_t TagFieldGetAddress (const char * pData, uint32_t iDefval)
Get an ip address field.
Parameters
*pData - data record
iDefval - default address
Returns
uint32_t - address from field, or default address if field does not exist
Version
01/23/2000 (gschaefer)
DIRTYCODE_API int32_t TagFieldGetBinary (const char * _pData, void * _pBuffer, int32_t iBuflen)
Get binary field contents.
Parameters
*_pData - data record
*_pBuffer - string target
iBuflen - length of target buffer
Returns
int32_t - field value copied to target buffer, returns data length
Note
This function does not support a default value.
Version
12/13/2004 (gschaefer)
References Binary7Decode().
DIRTYCODE_API int32_t TagFieldGetDate (const char * data, int32_t * pyear, int32_t * pmonth, int32_t * pday, int32_t * phour, int32_t * pminute, int32_t * psecond, int32_t gmt)
Get date.
Parameters
*data - data record
*pyear - (out) year component
*pmonth - (out) month component
*pday - (out) day component
*phour - (out) hour component
*pminute - (out) minute component
*psecond - (out) second component
gmt - GMT offset in seconds (zero=GMT time)
Returns
int32_t - date in psuedo epoch time
Version
01/23/2000 (gschaefer)
References ds_secstotime(), and TagFieldGetEpoch().
DIRTYCODE_API int32_t TagFieldGetDelim (const char * data, char * buffer, int32_t buflen, const char * defval, int32_t index, int32_t delim)
Get item from delimeter separated list.
Parameters
*data - data record
*buffer - string target
buflen - length of target buffer
*defval - default value
index - index of item within list
delim - list delimiter
Returns
int32_t - field value or defval copied to target buffer, returns string length
Version
01/23/2000 (gschaefer)
References data.
Referenced by WebOfferParamList().
DIRTYCODE_API uint32_t TagFieldGetEpoch (const char * pData, uint32_t uDefval)
Get date in epoch time.
Parameters
*pData - data record
uDefval - default value
Returns
uint32_t - date in psuedo epoch time, or default value if record does not exist
Version
01/23/2000 (gschaefer)
References ds_timeinsecs(), and ds_timetosecs().
Referenced by TagFieldGetDate().
DIRTYCODE_API int32_t TagFieldGetFlags (const char * pData, int32_t iDefault)
Get a flags field.
Parameters
*pData - data record
iDefault - default flags
Returns
int32_t - flags from field, or default flags if field does not exist
Version
12/12/2004 (gschaefer) Rewrite
DIRTYCODE_API float TagFieldGetFloat (const char * pData, float fDefval)
Get a floating point field.
Parameters
*pData - data pointer
fDefval - default number
Returns
float - float from field, or default number if field does not exist
Version
12/12/2004 (gschaefer)
DIRTYCODE_API int32_t TagFieldGetNumber (const char * pData, int32_t iDefval)
Get a numeric field.
Parameters
*pData - data pointer
iDefval - default number
Returns
int32_t - number from field, or default number if field does not exist
Version
01/23/2000 (gschaefer)
Referenced by WebOfferGetForm(), WebOfferGetMarketplace(), WebOfferGetNews(), WebOfferGetPromo(), WebOfferHttp(), and WebOfferUpdate().
DIRTYCODE_API int64_t TagFieldGetNumber64 (const char * pData, int64_t iDefval)
Get a 64-bit numeric field.
Parameters
*pData - data pointer
iDefval - default number
Returns
int64_t - number from field, or default number if field does not exist
Version
02/04/2005 (gschaefer)
DIRTYCODE_API int32_t TagFieldGetRaw (const char * pData, char * pBuffer, int32_t iBuflen, const char * pDefval)
Get the raw, undecoded value of a field returned as a string.
Parameters
*pData - data pointer
*pBuffer - buffer to store field data in
iBuflen - length of pBuffer
*pDefval - default value
Returns
int32_t - field value or pDefval copied to target buffer, returns string length
Version
12/13/2004 (gschaefer)
Referenced by WebOfferHttp().
DIRTYCODE_API int32_t TagFieldGetString (const char * data, char * buffer, int32_t buflen, const char * defval)
Get string field contents.
Parameters
*data - data record
*buffer - string target
buflen - length of target buffer
*defval - default value
Returns
int32_t - field value or defval copied to target buffer, returns string length
Version
01/23/2000 (gschaefer)
References data.
Referenced by WebOfferGetAlert(), WebOfferGetArticles(), WebOfferGetBusy2(), WebOfferGetCredit(), WebOfferGetForm(), WebOfferGetMedia(), WebOfferGetMenu(), WebOfferGetNews(), WebOfferGetPromo(), WebOfferGetStory(), WebOfferHttp(), WebOfferHttpComplete(), and WebOfferUpdate().
DIRTYCODE_API int32_t TagFieldGetStructure (const char * _pData, void * _pBuf, int32_t iLen, const char * pPat)
Get packed structure field contents.
Parameters
*_pData - data record
*_pBuf - struct target
iLen - length of target buffer
*pPat - structure pattern
Returns
int32_t - struct copied to target buffer, returns struct length
Note
This function does not support a default value. See TagFieldSetStructure() for a description of the pattern string.
Version
01/23/2000 (gschaefer)
DIRTYCODE_API int32_t TagFieldGetStructureOffsets (const char * pPat, TagFieldStructPtrT * pPtrs, int32_t iNumPtrs)
Populate pPtrs with memory offsets to the individual fields of a structure as defined by the given pattern.
Parameters
pPat - Pattern to build offsets for
pPtrs - Array to build offsets into
iNumPtrs - Size of pPtrs array
Returns
int32_t - Number of pointers populated.
Version
05/06/2005 (doneill)
References TagFieldStructPtrT::eType, TagFieldStructPtrT::iOffset, TAGFIELD_PATTERN_INT16, TAGFIELD_PATTERN_INT32, TAGFIELD_PATTERN_INT8, and TAGFIELD_PATTERN_STR.
DIRTYCODE_API int32_t TagFieldGetToken (const char * _pData, int32_t iDefault)
Get a token.
Parameters
*_pData - data record
iDefault - default token
Returns
int32_t - token from field, or default token if field does not exist
Version
12/13/2004 (gschaefer) Rewrite
Referenced by WebOfferCommand(), and WebOfferResource().
DIRTYCODE_API int32_t TagFieldMerge (char * _pRecord, int32_t iReclen, const char * _pMerge)
Merge two records together (does not merge bulk data). As of 12/14/2004 rewrite, it no longer returns a merged field count (just that is merged something).
Parameters
*_pRecord - data record
iReclen - record length
*_pMerge - source record to merge from
Returns
int32_t - negative=out of space, zero=nothing merged, positive=one or more fields merged
Version
01/23/2000 (gschaefer)
References TagFieldFind().
Referenced by WebOfferHttp().
DIRTYCODE_API int32_t TagFieldPrintf (char * _pRecord, int32_t iLength, const char * pFormat, ...)
Create a tagfield record using printf style descriptor.
Parameters
*_pRecord - data record
iLength - record length
*pFormat - format string
... - variable argument list
Returns
int32_t - field length (including terminator)
Note
Supported tokens include:
s: string
d: decimal
a: address
f: flags
e: epoch
r: record
#: replace part of tag name with number
,: allow multiple items in delim situation
Version
04/03/2002 (gschaefer)
References ds_snzprintf(), TagFieldFind(), TagFieldSetAddress(), TagFieldSetEpoch(), TagFieldSetFlags(), TagFieldSetNumber(), TagFieldSetRaw(), TagFieldSetString(), and TagFieldSetToken().
DIRTYCODE_API int32_t TagFieldRename (char * _record, int32_t reclen, const char * oldname, const char * newname)
Rename a field within the record.
Parameters
*_record - data record
reclen - record length
*oldname - old name
*newname - new name
Returns
int32_t - negative=no such field, zero=no error
Version
01/23/2000 (gschaefer)
References data, and TagFieldFind().
Referenced by WebOfferUpdate().
DIRTYCODE_API int32_t TagFieldSetAddress (char * pRecord, int32_t iReclen, const char * pName, uint32_t uAddr)
Set an ip-address field.
Parameters
*pRecord - data record
iReclen - record length
*pName - field name
uAddr - ip address
Returns
int32_t - negative=record too small, zero=no error
Version
12/10/2004 (gschaefer) Rewrite
Referenced by TagFieldPrintf().
DIRTYCODE_API int32_t TagFieldSetBinary (char * pRecord, int32_t iReclen, const char * pName, const void * _pValue, int32_t iVallen)
Set a binary field.
Parameters
*pRecord - data record
iReclen - record length
*pName - field name
*_pValue - start of binary data
iVallen - binary data length
Returns
int32_t - negative=record too small, zero=no error
Version
12/13/2004 (gschaefer)
DIRTYCODE_API int32_t TagFieldSetBinary7 (char * pRecord, int32_t iReclen, const char * pName, const void * _pValue, int32_t iVallen)
Set a binary field using more efficient 7-bits-per-byte encoding.
Parameters
*pRecord - data record
iReclen - record length
*pName - field name
*_pValue - start of binary data
iVallen - binary data length
Returns
int32_t - negative=record too small, zero=no error
Version
12/13/2004 (gschaefer)
References Binary7Encode(), and FALSE.
DIRTYCODE_API int32_t TagFieldSetDate (char * record, int32_t reclen, const char * name, int32_t year, int32_t month, int32_t day, int32_t hour, int32_t minute, int32_t second, int32_t gmt)
Set a date field from discrete date components.
Parameters
*record - data record
reclen - record length
*name - field name
year - year component
month - month component
day - day component
hour - hour component
minute - minute component
second - second component
gmt - GMT offset in seconds (zero=GMT time)
Returns
int32_t - negative=record too small, zero=no error
Version
01/23/2000 (gschaefer)
References ds_timetosecs(), and TagFieldSetEpoch().
DIRTYCODE_API int32_t TagFieldSetEpoch (char * pRecord, int32_t iReclen, const char * pName, uint32_t uEpoch)
Set a date from epoch time using std C time.h lib.
Parameters
*pRecord - data record
iReclen - record length
*pName - field name
uEpoch - date in psuedo epoch format
Returns
int32_t - negative=record too small, zero=no error
Version
12/13/2004 (gschaefer)
References ds_secstotime(), ds_snzprintf(), and ds_timeinsecs().
Referenced by TagFieldPrintf(), and TagFieldSetDate().
DIRTYCODE_API int32_t TagFieldSetFlags (char * pRecord, int32_t iReclen, const char * pName, int32_t iValue)
Set a flags field.
Parameters
*pRecord - data record
iReclen - record length
*pName - field name
iValue - flags value
Returns
int32_t - negative=record too small, zero=no error
Version
12/13/2004 (gschaefer)
Referenced by TagFieldPrintf().
DIRTYCODE_API int32_t TagFieldSetFloat (char * pRecord, int32_t iReclen, const char * pName, float fValue)
Set a floating point field.
Parameters
*pRecord - data record
iReclen - record length
*pName - field name
fValue - number
Returns
int32_t - negative=record too small, zero=no error
Version
12/12/2004 (gschaefer)
References ds_memcpy().
DIRTYCODE_API int32_t TagFieldSetNumber (char * pRecord, int32_t iReclen, const char * pName, int32_t iValue)
Set a numeric field.
Parameters
*pRecord - data record
iReclen - record length
*pName - field name
iValue - number
Returns
int32_t - negative=record too small, zero=no error
Version
12/12/2004 (gschaefer) Rewrite
Referenced by TagFieldPrintf(), TagFieldSetNumber64(), WebOfferAction(), WebOfferHttp(), WebOfferSetCredit(), and WebOfferSetup().
DIRTYCODE_API int32_t TagFieldSetNumber64 (char * pRecord, int32_t iReclen, const char * pName, int64_t iValue)
Set a 64-bit numeric field.
Parameters
*pRecord - data record
iReclen - record length
*pName - field name
iValue - number
Returns
int32_t - negative=record too small, zero=no error
Version
02/04/2005 (gschaefer) First version
References TagFieldSetNumber().
Referenced by WebOfferSetup().
DIRTYCODE_API int32_t TagFieldSetRaw (char * _pRecord, int32_t iReclen, const char * pName, const char * _pData)
Set a raw field (must come from TagFieldGetRaw or TagFieldFind). If the field is encoded badly, it can mess up the tagfield record so don't use data not generated by tagfield functions.
Parameters
*_pRecord - data record
iReclen - record length
*pName - field name
*_pData - source record to copy from
Returns
int32_t - negative=record too small, zero=no error
Version
12/13/2004 (gschaefer)
References TagFieldDelete().
Referenced by TagFieldPrintf().
DIRTYCODE_API int32_t TagFieldSetString (char * _pRecord, int32_t iReclen, const char * pName, const char * _pValue)
Set a string field.
Parameters
*_pRecord - data record
iReclen - record length
*pName - field name
*_pValue - text string
Returns
int32_t - negative = record too small, zero=no error
Version
01/23/2000 (gschaefer)
References CHAR_STRINGENC, and TagFieldDelete().
Referenced by TagFieldPrintf(), WebOfferHttp(), WebOfferSetCredit(), WebOfferSetForm(), WebOfferSetPromo(), and WebOfferSetup().
DIRTYCODE_API int32_t TagFieldSetStructure (char * pRecord, int32_t iReclen, const char * pName, const void * pStruct_, int32_t iLength, const char * pPattern)
Save an entire structure as a single field.
Parameters
*pRecord - data record
iReclen - record length
*pName - field name
*pStruct_ - binary structure data
iLength - length of binary data (-1=use pattern length)
*pPattern - structure pattern
Returns
int32_t - number of fields changed
Note
Structure pattern is a string that may consist of the following characters:
#: Field name (# name = count)
a: alignment skip ('count' bytes)
b: byte/character
w: word (four bytes)
l: int32_t (eight bytes)
s: string ('count' bytes)
Version
12/13/2004 (gschaefer)
References CHAR_STRUCTENC.
DIRTYCODE_API int32_t TagFieldSetToken (char * pRecord, int32_t iReclen, const char * pName, int32_t iToken)
Set a token field.
Parameters
*pRecord - data record
iReclen - record length
*pName - field name
iToken - token to set
Returns
int32_t - negative=record too small, zero=no error
Version
12/13/2004 (gschaefer) Rewrite
References CHAR_TOKENENC.
Referenced by TagFieldPrintf().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:50