DirtySock: Platform
Platform
DirtySock
Macros
#define DIRTYCODE_API
#define DIRTYCODE_64BITPTR (0)
#define FALSE (0)
#define TRUE (1)
#define DIRTYCODE_DEBUG (0)
#define DS_MIN(_x, _y) (((_x) < (_y)) ? (_x) : (_y))
min of _x and _y
#define DS_MAX(_x, _y) (((_x) > (_y)) ? (_x) : (_y))
max of _x and _y
#define DS_ABS(_x) (((_x) < 0) ? -(_x) : (_x))
abs of _x
#define DS_CLAMP(_x, _min, _max) (((_x) > (_max)) ? (_max) : (((_x) < (_min)) ? (_min) : (_x)))
clamp _x between _min and _max; if _low < _high result is undefined
#define ds_strtoll(_buf, _outp, _radix) strtoll(_buf, _outp, _radix)
#define ds_strtoull(_buf, _outp, _radix) strtoull(_buf, _outp, _radix)
Typedefs
typedef enum
TimeToStringConversionTypeE TimeToStringConversionTypeE
time-to-string conversion type
Enumerations
enum TimeToStringConversionTypeE {
TIMETOSTRING_CONVERSION_ISO_8601,
TIMETOSTRING_CONVERSION_RFC_0822,
TIMETOSTRING_CONVERSION_ASN1_UTCTIME,
TIMETOSTRING_CONVERSION_ASN1_GENTIME,
TIMETOSTRING_CONVERSION_UNKNOWN
}
time-to-string conversion type
Functions
DIRTYCODE_API uint64_t ds_timeinsecs (void)
This function replaces the standard library time() function. Main differences are the missing pointer parameter (not needed) and the uint32_t return value. The function returns 0 on unsupported platforms vs time which returns -1.
DIRTYCODE_API int32_t ds_timezone (void)
This function returns the current system timezone as its offset from GMT in seconds. There is no direct equivilent function in the standard C libraries.
DIRTYCODE_API struct tm * ds_localtime (struct tm *pTm, uint64_t elap)
This converts the input GMT time to the local time as specified by the system clock. This function follows the re-entrant localtime_r function signature.
DIRTYCODE_API struct tm * ds_secstotime (struct tm *pTm, uint64_t elap)
Convert elapsed seconds to discrete time components. This is essentially a ds_localtime() replacement with better syntax that is available on all platforms.
DIRTYCODE_API uint64_t ds_timetosecs (const struct tm *pTm)
Convert discrete components to elapsed time.
DIRTYCODE_API struct tm * ds_plattimetotime (struct tm *pTm, void *pPlatTime)
This converts the input platform-specific time data structure to the generic time data structure.
DIRTYCODE_API struct tm * ds_plattimetotimems (struct tm *pTm, int32_t *iMsec)
This function retrieves the current date time and fills in the generic time data structure prrovided. It has the option of returning millisecond which is not part of the generic time data structure.
DIRTYCODE_API char * ds_timetostr (const struct tm *pTm, TimeToStringConversionTypeE eConvType, uint8_t bLocalTime, char *pStr, int32_t iBufSize)
Converts a date formatted in a number of common Unix and Internet formats and convert to a struct tm.
DIRTYCODE_API char * ds_secstostr (uint64_t elap, TimeToStringConversionTypeE eConvType, uint8_t bLocalTime, char *pStr, int32_t iBufSize)
Converts a datetime in epoch format to string.
DIRTYCODE_API uint64_t ds_strtotime (const char *str)
Converts a date formatted in a number of common Unix and Internet formats and convert to a struct tm.
DIRTYCODE_API uint64_t ds_strtotime2 (const char *pStr, TimeToStringConversionTypeE eConvType)
Converts a date formatted in a number of common Unix and Internet formats and convert to a struct tm.
DIRTYCODE_API int32_t ds_strnlen (const char *pBuffer, int32_t iLength)
Replacement for strnlen.
DIRTYCODE_API int32_t ds_vsnprintf (char *pBuffer, int32_t iLength, const char *pFormat, va_list Args)
Replacement for vsnprintf, with some modifications.
DIRTYCODE_API int32_t ds_vsnzprintf (char *pBuffer, int32_t iLength, const char *pFormat, va_list Args)
Replacement for vsnprintf that always includes a terminator at the end of the string.
DIRTYCODE_API int32_t ds_snzprintf (char *pBuffer, int32_t iLength, const char *pFormat,...)
Replacement for snprintf that always includes a terminator at the end of the string.
DIRTYCODE_API char * ds_strnzcpy (char *pDest, const char *pSource, int32_t iCount)
Always terminated strncpy function.
DIRTYCODE_API int32_t ds_strnzcat (char *pDst, const char *pSrc, int32_t iDstLen)
Concatenate the string pointed to by pSrc to the string pointed to by pDst. A maximum of iDstLen-1 characters are copied, and the resulting string is guaranteed to be null-terminated.
DIRTYCODE_API int32_t ds_stricmp (const char *pString1, const char *pString2)
Case insensitive string compare.
DIRTYCODE_API int32_t ds_strnicmp (const char *pString1, const char *pString2, uint32_t uCount)
Case insensitive string compare of first N characters.
DIRTYCODE_API char * ds_stristr (const char *pHaystack, const char *pNeedle)
Case insensitive substring search.
DIRTYCODE_API int32_t ds_strsubzcpy (char *pDst, int32_t iDstLen, const char *pSrc, int32_t iSrcLen)
Copy a substring from pSrc into the output buffer. The output string is guaranteed to be null-terminated.
DIRTYCODE_API int32_t ds_strsubzcat (char *pDst, int32_t iDstLen, const char *pSrc, int32_t iSrcLen)
Concatenate the substring pointed to by pSrc and with a length of iSrcLen to the string pointed to by pDst. A maximum of iDstLen-1 or iSrcLen characters are copied, whichever is smaller, and the resulting string is guaranteed to be null-terminated.
DIRTYCODE_API int32_t ds_strcmpwc (const char *pString1, const char *pStrWild)
String compare with wildcard matching ('*' only).
DIRTYCODE_API int32_t ds_stricmpwc (const char *pString1, const char *pStrWild)
String compare with wildcard matching ('*' only).
DIRTYCODE_API void ds_memcpy (void *pDst, const void *pSrc, int32_t iDstLen)
Replacement for memcpy.
DIRTYCODE_API void ds_memcpy_s (void *pDst, int32_t iDstLen, const void *pSrc, int32_t iSrcLen)
Replacement for memcpy_s.
Detailed Description
Macro Definition Documentation
#define DIRTYCODE_64BITPTR (0)
#define DIRTYCODE_API
#define DIRTYCODE_DEBUG (0)
#define DS_ABS (_x) (((_x) < 0) ? -(_x) : (_x))
abs of _x
#define DS_CLAMP (_x, _min, _max) (((_x) > (_max)) ? (_max) : (((_x) < (_min)) ? (_min) : (_x)))
clamp _x between _min and _max; if _low < _high result is undefined
Referenced by ProtoSSLControl(), SocketPacketQueueCreate(), and SocketPacketQueueResize().
#define DS_MAX (_x, _y) (((_x) > (_y)) ? (_x) : (_y))
max of _x and _y
Referenced by SocketControl().
#define DS_MIN (_x, _y) (((_x) < (_y)) ? (_x) : (_y))
min of _x and _y
Referenced by ds_memcpy_s().
#define ds_strtoll (_buf, _outp, _radix) strtoll(_buf, _outp, _radix)
#define ds_strtoull (_buf, _outp, _radix) strtoull(_buf, _outp, _radix)
#define FALSE (0)
Referenced by _UserApiGetPriorityTitle(), _UserApiInitializeContext(), _UserListApiGetPriorityTitle(), Base64Decode(), ConnApiControl(), ConnApiCreate2(), ConnApiDisconnect(), ConnApiFindClient(), ConnApiOnline(), CryptArc4StringEncrypt(), CryptRandInit(), CryptRandShutdown(), DirtyAddrFromHostAddr(), DirtyAddrGetLocalAddr(), DirtyAddrSetInfoXboxOne(), DirtyAddrToHostAddr(), DirtyAuthGetToken2(), DirtyCertControl(), DirtyJpgDecodeHeader(), DirtyJpgDecodeImage(), DirtyJpgReset(), DirtyPngDecodeImage(), DirtyPngIdentify(), DirtyUserCompare(), DirtyUserGetLocalUser(), DirtyUserToNativeUser(), ds_strcmpwc(), HttpManagerControl(), JsonAddDate(), JsonAddInt(), JsonAddNum(), JsonGetBoolean(), JsonParse(), LobbyLanCreateGame(), LobbyLanStartGame(), NetConnConnect(), NetConnDisconnect(), NetConnIdle(), NetConnShutdown(), NetConnStartup(), NetConnStatus(), NetGameDistControl(), NetGameDistInputQueryMulti(), NetGameDistServHighWaterChanged(), NetGameDistServStopGame(), NetGameDistServUpdate(), NetGameDistSetServer(), NetGameLinkCreate(), NetGameLinkStatus(), NetLibCommonShutdown(), NetResourceCacheCheck(), PingManagerInvalidateAddress(), PrivilegeApiReleaseRequest(), ProtoHttpControl(), ProtoHttpRequestCb(), ProtoHttpStatus(), ProtoHttpUpdate(), ProtoHttpUrlParse2(), ProtoMangleCreate(), ProtoMangleStatus(), ProtoPingRequest(), ProtoPingResponse(), ProtoSSLConnect(), ProtoSSLControl(), ProtoSSLSetCACert2(), ProtoSSLStat(), ProtoTunnelCreate(), ProtoTunnelDestroy(), ProtoTunnelFree2(), ProtoTunnelValidatePacket(), ProtoUpnpControl(), ProtoUpnpCreate(), ProtoUpnpUpdate(), ProtoWebSocketStatus(), SocketControl(), SocketCreate(), SocketPacketQueueStatus(), SocketRelease(), TagFieldSetBinary7(), UserApiCreate(), UserApiDestroy(), UserApiPlatUpdate(), UserApiRegisterUpdateEvent(), UserApiUpdate(), UserListApiUpdate(), VoipConnectionSend(), VoipGroupActivateLocalUser(), VoipGroupConnect(), VoipGroupConnect2(), VoipGroupDisconnect(), VoipGroupIsMutedByClientId(), VoipGroupIsMutedByClientId2(), VoipGroupIsMutedByConnId(), VoipGroupResume(), VoipGroupSuspend(), VoipHeadsetControl(), VoipHeadsetIsFriendCallback(), VoipHeadsetProcess(), VoipHeadsetStatus(), VoipSetLocalUser(), VoipTunnelClientRefreshSendMask(), VoipUpdateSerializedUser(), WebLogStop(), WebLogUpdate(), WebOfferHttp(), and WebOfferUpdate().
#define TRUE (1)
Referenced by _UserApiGetPriorityTitle(), _UserApiInitializeContext(), _UserListApiGetPriorityTitle(), Base64Decode(), CommUDPConnect(), ConnApiAddClient(), ConnApiControl(), ConnApiCreate2(), ConnApiDestroy(), ConnApiDisconnect(), ConnApiFindClient(), ConnApiOnline(), CryptArc4StringEncrypt(), CryptRandInit(), CryptRSAInit(), DirtyAddrFromHostAddr(), DirtyAddrGetLocalAddr(), DirtyAddrSetInfoXboxOne(), DirtyAddrToHostAddr(), DirtyCertControl(), DirtyCertCreate(), DirtyGraphDecodeImage(), DirtyJpgIdentify(), DirtyPngDecodeImage(), DirtyPngIdentify(), DirtyUserCompare(), DirtyUserFromNativeUser(), DirtyUserToNativeUser(), ds_stricmpwc(), HttpManagerControl(), HttpManagerCreate(), HttpManagerFree(), JsonAddStr(), JsonGetBoolean(), JsonParse(), LobbyLanCreate2(), LobbyLanCreateGame(), LobbyLanRecvfrom(), LobbyLanSetPlyrNote(), NetConnConnect(), NetConnIdle(), NetConnStartup(), NetConnStatus(), NetGameDistControl(), NetGameDistInputQueryMulti(), NetGameDistServAddClient(), NetGameDistServDiscClient(), NetGameDistServStartGame(), NetGameDistServUpdate(), NetGameDistSetServer(), NetGameDistUpdate(), NetGameLinkControl(), NetGameLinkCreate(), NetGameLinkStatus(), NetLibCommonInit(), NetResourceFetch(), HttpCallback::OnError(), HttpCallback::OnHeadersAvailable(), HttpCallback::OnRedirect(), HttpCallback::OnResponseReceived(), PingManagerInvalidateAddress(), PingManagerUpdate(), ProtoHttpControl(), ProtoHttpCreate(), ProtoHttpServCreate2(), ProtoHttpStatus(), ProtoHttpUpdate(), ProtoHttpUrlParse2(), ProtoMangleCreate(), ProtoMangleStatus(), ProtoPingRequestServer(), ProtoPingResponse(), ProtoSSLAccept(), ProtoSSLControl(), ProtoSSLCreate(), ProtoSSLSetCACert(), ProtoSSLStat(), ProtoSSLValidateAllCA(), ProtoStreamPause(), ProtoStreamRead(), ProtoTunnelAlloc(), ProtoTunnelCreate(), ProtoTunnelFree2(), ProtoUpnpControl(), ProtoUpnpCreate(), ProtoUpnpUpdate(), QosApiServiceRequest(), SocketBind(), SocketClose(), SocketControl(), SocketCreate(), SocketHostnameAddRef(), SocketLookup(), SocketPacketQueueStatus(), UserApiControl(), UserApiCreate(), UserApiDestroy(), UserApiPlatRequestPostRichPresence(), UserApiPlatRequestPresence(), UserApiPlatRequestProfile(), UserApiPlatUpdate(), UserApiRegisterUpdateEvent(), UserApiUpdate(), UserListApiDestroy(), UserListApiGetListAsync(), UserListApiUpdate(), VoipActivateLocalUser(), VoipCommonControl(), VoipCommonResetChannels(), VoipCommonSelectChannel(), VoipCommonStartup(), VoipConnectionFlush(), VoipConnectionRegisterRemoteTalkers(), VoipConnectionSend(), VoipDisconnect(), VoipGroupActivateLocalUser(), VoipGroupConnect2(), VoipGroupCreate(), VoipGroupIsMutedByConnId(), VoipGroupResume2(), VoipHeadsetControl(), VoipHeadsetCreate(), VoipHeadsetDestroy(), VoipHeadsetIsFriendCallback(), VoipHeadsetStatus(), VoipSetLocalUser(), VoipStartup(), VoipTunnelClientListAdd2(), VoipTunnelClientRefreshSendMask(), VoipUpdateSerializedUser(), WebLogStart(), and WebLogUpdate().
Typedef Documentation
typedef enum TimeToStringConversionTypeE TimeToStringConversionTypeE
time-to-string conversion type
Enumeration Type Documentation
enum TimeToStringConversionTypeE
time-to-string conversion type
Enumerator
TIMETOSTRING_CONVERSION_ISO_8601
ISO 8601 standard: yyyy-MM-ddTHH:mmZ where Z means 0 UTC offset, and no Z means local time zone.
TIMETOSTRING_CONVERSION_RFC_0822
RFC 0822 format, updated by RFC1123: day, dd mon yyyy hh:mm:ss zzz.
TIMETOSTRING_CONVERSION_ASN1_UTCTIME
ASN.1 UTCTime format.
TIMETOSTRING_CONVERSION_ASN1_GENTIME
ASN.1 GeneralizedTime format.
TIMETOSTRING_CONVERSION_UNKNOWN
unknown source format type; try to auto-determine if possible
Function Documentation
DIRTYCODE_API struct tm* ds_localtime (struct tm * pTm, uint64_t elap)
This converts the input GMT time to the local time as specified by the system clock. This function follows the re-entrant localtime_r function signature.
Parameters
*pTm - storage for localtime output
elap - GMT time
Returns
struct tm * - pointer to localtime result
Version
04/23/2008 (jbrookes)
Referenced by ds_timezone().
DIRTYCODE_API void ds_memcpy (void * pDst, const void * pSrc, int32_t iDstLen)
Replacement for memcpy.
Parameters
*pDst - [out] output for new string
*pSrc - pointer to input string to copy from
iDstLen - size of substring pointed to by pSrc.
Version
07/15/2014 (amakoukji)
Referenced by _ProtoWebSocketRecv(), _UserApiTriggerCallback(), CommSRPPeek(), CommSRPSend(), CommTCPPeek(), CommTCPSend(), CommUDPPeek(), CommUDPSend(), ConnApiStatus2(), CryptHmacCalcMulti(), CryptMD2Final(), CryptMD2Update(), CryptMD5Update(), CryptRSAInit(), CryptRSAInitMaster(), CryptRSAInitPrivate(), CryptRSAInitSignature(), CryptSha1Update(), CryptSha2Update(), DirtyAddrToHostAddr(), HttpManagerStatus(), LobbyLanStatus(), LobbyMSort(), MurmurHash3Update(), NetConnStatus(), NetGameDistInputLocal(), NetGameDistInputLocalMulti(), NetGameDistInputPeek(), NetGameDistInputQueryMulti(), NetGameDistSendStats(), NetGameDistStatus(), NetGameDistUpdate(), NetGameLinkRecv2(), NetGameLinkStatus(), NetGameUtilStatus(), HttpCallback::OnDataAvailable(), PingManagerPingAddress(), PingManagerUpdate(), ProtoHttpRecv(), ProtoHttpStatus(), ProtoPingResponse(), ProtoSSLAccept(), ProtoSSLRecv(), ProtoSSLStat(), ProtoStreamRead(), ProtoTunnelStatus(), ProtoUdpRecvFrom(), ProtoWebSocketRecv(), ProtoWebSocketStatus(), QosApiStatus(), SequentialStream::Read(), SocketHost(), SocketHtonl(), SocketHtons(), SocketInfo(), SocketNtohl(), SocketNtohs(), SocketPacketQueueAdd(), SocketPacketQueueRem(), TagFieldSetFloat(), VoipCommonStatus(), VoipConnectionSend(), VoipGroupControl(), VoipTunnelStatus(), WebOfferAction(), and SequentialStream::Write().
DIRTYCODE_API void ds_memcpy_s (void * pDst, int32_t iDstLen, const void * pSrc, int32_t iSrcLen)
Replacement for memcpy_s.
Parameters
*pDst - [out] output for new string
iDstLen - size of output buffer
*pSrc - pointer to input string to copy from
iSrcLen - size of substring pointed to by pSrc.
Version
07/15/2014 (amakoukji)
References DS_MIN.
Referenced by CommUDPSend(), ConnApiFindClient(), DirtyCertCARequestCert(), LobbyLanSetPlyrNote(), MurmurHash3Update(), NetGameDistServUpdate(), ProtoAdvtConstruct(), ProtoTunnelAlloc(), ProtoTunnelValidatePacket(), ProtoUdpConnect(), ProtoUdpUpdate(), SocketAddrMapTranslate(), SocketBind(), SocketConnect(), SocketPacketQueueAdd(), UserListApiIsFriendAsync(), UserListApiUpdate(), VoipConnectionReliableBroadcastOpaque(), VoipConnectionReliableBroadcastUser(), VoipConnectionStart(), VoipTunnelClientListAdd2(), and WebOfferCommand().
DIRTYCODE_API struct tm* ds_plattimetotime (struct tm * pTm, void * pPlatTime)
This converts the input platform-specific time data structure to the generic time data structure.
Parameters
*pTm - generic time data structure to be filled by the function
*pPlatTime - pointer to the platform-specific data structure
Returns
struct tm * - NULL=failure; else pointer to user-provided generic time data structure
Note
    Data type to be used with plattime:
        On PS4:      SceKernelTimeval
        On PC:       __timeb64
        On Xbox One: SYSTEMTIME
        On WinRT:    SYSTEMTIME
        On Linux:    timespec
Version
05/08/2010 (mclouatre)
Referenced by ds_plattimetotimems().
DIRTYCODE_API struct tm* ds_plattimetotimems (struct tm * pTm, int32_t * imsec)
This function retrieves the current date time and fills in the generic time data structure prrovided. It has the option of returning millisecond which is not part of the generic time data structure.
Parameters
*pTm - generic time data structure to be filled by the function
*imsec - output param for milisecond to be filled by the function (optional can be NULL)
Returns
struct tm * - NULL=failure; else pointer to user-provided generic time data structure
Note
Version
09/16/2014 (tcho)
References ds_plattimetotime().
DIRTYCODE_API char* ds_secstostr (uint64_t elap, TimeToStringConversionTypeE eConvType, uint8_t bLocalTime, char * pStrBuf, int32_t iBufSize)
Converts a datetime in epoch format to string.
Parameters
elap - epoch time to convert to string
eConvType - user-selected conversion type
bLocalTime - whether input time is local time or UTC 0 offset time.
*pStrBuf - user-provided buffer to be filled with datetime string
iBufSize - size of output buffer (must be at least 18 bytes to receive null-terminated yyyy-MM-ddTHH:mm:ssZ
Returns
char * - zero=failure, else epoch time
Version
02/26/2014 (jbrookes)
References ds_secstotime(), and ds_timetostr().
DIRTYCODE_API struct tm* ds_secstotime (struct tm * pTm, uint64_t elap)
Convert elapsed seconds to discrete time components. This is essentially a ds_localtime() replacement with better syntax that is available on all platforms.
Parameters
*pTm - target component record
elap - epoch time input
Returns
struct tm * - returns tm if successful, NULL if failed
Version
01/23/2000 (gschaefer)
(can happen on dec 31 of non-leap year)
Referenced by ds_secstostr(), ds_timetosecs(), JsonAddDate(), TagFieldGetDate(), TagFieldSetEpoch(), XmlAttrSetDate(), XmlConvEpoch2Date(), XmlElemAddDate(), and XmlElemSetDate().
DIRTYCODE_API int32_t ds_snzprintf (char * pBuffer, int32_t iLength, const char * pFormat, ...)
Replacement for snprintf that always includes a terminator at the end of the string.
Parameters
*pBuffer - output buffer
iLength - size of output buffer
*pFormat - format string
... - variable argument list
Returns
int32_t - number of characters formatted; if > than the length, output is truncated and the buffer is null-terminated unless iLength<=0.
Version
02/15/2011 (jbrookes)
Referenced by ConnApiOnline(), DirtyErrNameList(), ds_timetostr(), JsonAddDate(), JsonAddInt(), JsonAddNum(), JsonArrayEnd(), JsonArrayStart(), JsonFinish(), JsonInit(), JsonObjectEnd(), JsonObjectStart(), NetGameDistControl(), NetGameDistInputLocalMulti(), NetGameDistInputPeek(), NetGameDistUpdate(), NetGameUtilComplete(), HttpCallback::OnRedirect(), PingManagerPingServer2(), ProtoHttpFindHeaderValue(), ProtoHttpGetLocationHeader(), ProtoHttpUrlEncodeIntParm(), ProtoMangleFindTemplate(), QosApiServiceRequest(), TagFieldFindIdx(), TagFieldPrintf(), TagFieldSetEpoch(), UserApiPlatRequestPresence(), UserListApiIsFriendAsync(), UserListApiUpdate(), VoipHeadsetStatus(), VoipSetLocalUser(), WebOfferSetForm(), XmlAttrSetAddr(), XmlAttrSetDate(), XmlAttrSetFloat(), XmlAttrSetInt(), XmlAttrSetString(), XmlAttrSetStringRaw(), XmlElemAddDate(), XmlElemAddFloat(), XmlElemAddInt(), XmlElemAddString(), XmlElemSetAddr(), XmlElemSetDate(), XmlElemSetInt(), XmlInit(), XmlTagEnd(), and XmlTagStart().
DIRTYCODE_API int32_t ds_strcmpwc (const char * pString1, const char * pStrWild)
String compare with wildcard matching ('*' only).
Parameters
*pString1 - see stricmp
*pStrWild - match string including wildcard(s)
Returns
see stricmp
Version
09/18/2012 (jbrookes)
References FALSE.
DIRTYCODE_API int32_t ds_stricmp (const char * pString1, const char * pString2)
Case insensitive string compare.
Parameters
*pString1 - see stricmp
*pString2 - see stricmp
Returns
see stricmp
Version
01/25/2005 (gschaefer)
Referenced by ProtoAdvtAnnounce(), ProtoAdvtCancel(), ProtoAdvtLocate(), ProtoAdvtQuery(), ProtoHttpCheckKeepAlive(), ProtoHttpGetHeaderValue(), ProtoHttpUrlParse2(), and ProtoWebSocketStatus().
DIRTYCODE_API int32_t ds_stricmpwc (const char * pString1, const char * pStrWild)
String compare with wildcard matching ('*' only).
Parameters
*pString1 - see stricmp
*pStrWild - match string including wildcard(s)
Returns
see stricmp
Version
09/18/2012 (jbrookes)
References TRUE.
DIRTYCODE_API char* ds_stristr (const char * pHaystack, const char * pNeedle)
Case insensitive substring search.
Parameters
pHaystack - see stristr
pNeedle - see stristr
Returns
see stristr
Version
01/25/2005 (gschaefer)
Referenced by ProtoHttpFindHeaderValue(), VoipHeadsetControl(), VoipHeadsetRegisterUserCb(), WebOfferExecute(), and WebOfferUpdate().
DIRTYCODE_API int32_t ds_strnicmp (const char * pString1, const char * pString2, uint32_t uCount)
Case insensitive string compare of first N characters.
Parameters
*pString1 - see strnicmp
*pString2 - see strnicmp
uCount - see strnicmp
Returns
see strnicmp
Version
01/25/2005 (gschaefer)
Referenced by NetConnQuery(), and ProtoHttpGetLocationHeader().
DIRTYCODE_API int32_t ds_strnlen (const char * pBuffer, int32_t iLength)
Replacement for strnlen.
Parameters
*pBuffer - buffer
iLength - size of buffer
Returns
int32_t - number of characters or iLength if no '\0' is present.
Version
10/28/2009 (jbrookes)
DIRTYCODE_API int32_t ds_strnzcat (char * pDst, const char * pSrc, int32_t iDstLen)
Concatenate the string pointed to by pSrc to the string pointed to by pDst. A maximum of iDstLen-1 characters are copied, and the resulting string is guaranteed to be null-terminated.
Parameters
*pDst - [out] output for new string
*pSrc - pointer to input string to copy from
iDstLen - size of output buffer
Returns
int32_t - number of characters in pDst, excluding null character
Version
09/27/2005 (jbrookes)
Referenced by ProtoHttpGetLocationHeader(), TagFieldFind2(), and WebLogPrintf().
DIRTYCODE_API char* ds_strnzcpy (char * pDest, const char * pSource, int32_t iCount)
Always terminated strncpy function.
Parameters
*pDest - see strncpy
*pSource - see strncpy
iCount - see strncpy
Returns
see strncpy
Version
01/25/2005 (gschaefer)
Referenced by ConnApiControl(), ConnApiCreate2(), ConnApiOnline(), ConnApiStatus2(), CryptArc4StringEncryptStaticCode(), DirtyCertCARequestCert(), DirtyCertStatus(), HttpManagerStatus(), LobbyLanCreate2(), LobbyLanCreateGame(), LobbyLanSetNote(), LobbyLanSetPlyrNote(), NetConnControl(), NetConnCopyParam(), NetConnStartup(), NetConnStatus(), NetGameDistServAddClient(), NetGameUtilAdvert(), NetGameUtilComplete(), NetGameUtilConnect(), NetResourceCreate(), ProtoAdvtAnnounce(), ProtoAdvtQuery(), ProtoHttpControl(), ProtoHttpGetLocationHeader(), ProtoHttpRequestCb(), ProtoHttpServCreate2(), ProtoHttpSetBaseUrl(), ProtoHttpStatus(), ProtoHttpUrlParse2(), ProtoSSLControl(), ProtoSSLStat(), ProtoStreamUpdate(), ProtoTunnelAlloc(), ProtoTunnelStatus(), ProtoUpnpControl(), ProtoUpnpStatus(), ProtoWebSocketConnect(), QosApiControl(), QosApiStatus(), SocketHostnameCacheAdd(), SocketLookup(), TagFieldFind2(), UserListApiIsFriendAsync(), VoipTunnelClientListAdd2(), WebLogConfigure(), and WebLogCreate().
DIRTYCODE_API int32_t ds_strsubzcat (char * pDst, int32_t iDstLen, const char * pSrc, int32_t iSrcLen)
Concatenate the substring pointed to by pSrc and with a length of iSrcLen to the string pointed to by pDst. A maximum of iDstLen-1 or iSrcLen characters are copied, whichever is smaller, and the resulting string is guaranteed to be null-terminated.
Parameters
*pDst - [out] output for new string
iDstLen - size of output buffer
*pSrc - pointer to input string to copy from
iSrcLen - size of substring pointed to by pSrc.
Returns
int32_t - number of characters in pDst, excluding null character
Version
09/27/2005 (jbrookes)
DIRTYCODE_API int32_t ds_strsubzcpy (char * pDst, int32_t iDstLen, const char * pSrc, int32_t iSrcLen)
Copy a substring from pSrc into the output buffer. The output string is guaranteed to be null-terminated.
Parameters
*pDst - [out] output for new string
iDstLen - length of output buffer
*pSrc - pointer to input string to copy from
iSrcLen - number of characters to copy from input string
Returns
int32_t - number of characters written, excluding null character
Version
09/27/2005 (jbrookes)
Referenced by ProtoHttpGetNextParam(), and ProtoHttpUrlParse2().
DIRTYCODE_API uint64_t ds_strtotime (const char * pStr)
Converts a date formatted in a number of common Unix and Internet formats and convert to a struct tm.
Parameters
*pStr - textual date string
Returns
uint32_t - zero=failure, else epoch time
Note
    The following time formats are supported:
        Sun, 06 Nov 1994 08:49:37 GMT  ; RFC 822, updated by RFC 1123
        Sun Nov  6 08:49:37 1994       ; ANSI C's asctime() format
    The following format is mentioned as needing to be readable by HTTP
    but is not currently supported by this function:
        Sunday, 06-Nov-94 08:49:37 GMT ; RFC 850, obsoleted by RFC 1036
Version
11/01/2002 (gschaefer)
References ds_timetosecs().
Referenced by ds_strtotime2().
DIRTYCODE_API uint64_t ds_strtotime2 (const char * pStr, TimeToStringConversionTypeE eConvType)
Converts a date formatted in a number of common Unix and Internet formats and convert to a struct tm.
Parameters
*pStr - textual date string
eConvType - time format to convert from
Returns
uint32_t - zero=failure, else epoch time
Note
For supported conversion types other than ISO_8601, see documentation for ds_strtotime().
Version
12/13/2012 (jbrookes)
References ds_strtotime(), ds_timetosecs(), TIMETOSTRING_CONVERSION_ASN1_GENTIME, TIMETOSTRING_CONVERSION_ASN1_UTCTIME, and TIMETOSTRING_CONVERSION_ISO_8601.
Referenced by JsonGetDate().
DIRTYCODE_API uint64_t ds_timeinsecs (void)
This function replaces the standard library time() function. Main differences are the missing pointer parameter (not needed) and the uint32_t return value. The function returns 0 on unsupported platforms vs time which returns -1.
Returns
uint32_t - number of elapsed seconds since Jan 1, 1970.
Version
01/12/2005 (gschaefer)
Referenced by JsonFormatVPrintf(), TagFieldGetEpoch(), TagFieldSetEpoch(), and XmlFormatVPrintf().
DIRTYCODE_API uint64_t ds_timetosecs (const struct tm * pTm)
Convert discrete components to elapsed time.
Parameters
*pTm - source component record
Returns
uint32_t - zero=failure, else epoch time
Version
01/23/2000 (gschaefer)
References ds_secstotime().
Referenced by ds_strtotime(), ds_strtotime2(), TagFieldGetEpoch(), TagFieldSetDate(), XmlAttribGetDate(), and XmlContentGetDate().
DIRTYCODE_API char* ds_timetostr (const struct tm * pTm, TimeToStringConversionTypeE eConvType, uint8_t bLocalTime, char * pStrBuf, int32_t iBufSize)
Converts a date formatted in a number of common Unix and Internet formats and convert to a struct tm.
Parameters
*pTm - input time stucture to be converted to string
eConvType - user-selected conversion type
bLocalTime - whether input time is local time or UTC 0 offset time.
*pStrBuf - user-provided buffer to be filled with datetime string
iBufSize - size of output buffer (must be at least 18 bytes to receive null-terminated yyyy-MM-ddTHH:mm:ssZ
Returns
char * - zero=failure, else epoch time
Version
07/12/2012 (jbrookes)
References ds_snzprintf(), TIMETOSTRING_CONVERSION_ISO_8601, and TIMETOSTRING_CONVERSION_RFC_0822.
Referenced by ds_secstostr().
DIRTYCODE_API int32_t ds_timezone (void)
This function returns the current system timezone as its offset from GMT in seconds. There is no direct equivilent function in the standard C libraries.
Returns
int32_t - local timezone offset from GMT in seconds
Version
11/06/2002 (jbrookes)
References ds_localtime().
DIRTYCODE_API int32_t ds_vsnprintf (char * pBuffer, int32_t iLength, const char * pFormat, va_list Args)
Replacement for vsnprintf, with some modifications.
Parameters
*pBuffer - output buffer
iLength - size of output buffer
*pFormat - format string
Args - variable argument list
Returns
int32_t - number of characters formatted; if > than the length, output is truncated and the buffer is null-terminated unless iLength<=0.
Note
Unlike standard vsnprintf, this version always null-terminates if the buffer is not zero-sized.
Version
10/28/2009 (jbrookes)
DIRTYCODE_API int32_t ds_vsnzprintf (char * pBuffer, int32_t iLength, const char * pFormat, va_list Args)
Replacement for vsnprintf that always includes a terminator at the end of the string.
Parameters
*pBuffer - output buffer
iLength - size of output buffer
*pFormat - format string
Args - variable argument list
Returns
int32_t - number of characters formatted; if > than the length, output is truncated and the buffer is null-terminated unless iLength<=0.
Version
02/15/2011 (jbrookes)
Referenced by WebLogPrintf().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:34:35