window.originTranslator = {
    fallbackStrings: {
    "ebisu_client_settings_language_restriction": "Active downloads and installs must be cancelled or completed before changing languages.", 
    "ebisu_client_default_tab": "Default Tab", 
    "application_name": "Origin", 
    "ebisu_client_lang_select_label": "%1 Client Language", 
    "ebisu_client_settings_autostart_mac": "Automatically start %1 when I log in", 
    "home_title": "Origin Now", 
    "ebisu_client_my_games_lowercase": "My Games", 
    "ebisu_client_store_system_tray": "Store", 
    "ebisu_client_let_origin_decide": "Let %1 decide", 
    "ebisu_client_language_german": "Deutsch (German)", 
    "ebisu_client_language_danish": "Dansk (Danish)", 
    "ebisu_client_settings_autoupdate": "Automatically keep %1 up to date", 
    "ebisu_client_lowest": "Lowest", 
    "ebisu_client_mid": "Mid", 
    "ebisu_client_highest": "Highest", 
    "ebisu_client_disconnect": "Disconnect", 
    "ebisu_client_connect": "Connect", 
    "ebisu_client_enable_in_game_dashboard_description": "%1 is not yet available for all games. If you are experiencing issues with a particular game, try disabling %1 before playing. You can re-enable %1 at any time. Please note that disabling %1 may disrupt some in-game features.", 
    "ebisu_client_igo_name": "Origin In Game", 
    "ebisu_client_enable_in_game_dashboard": "Enable %1", 
    "ebisu_client_dashboard_hotkeys": "%1 Hotkeys", 
    "ebisu_client_enable_igo_log": "Enable %1 log file (Not recommended)", 
    "ebisu_client_in_game_supported_tooltip": "Enable %1 for officially supported titles only.", 
    "ebisu_client_in_game_all_tooltip": "Enable %1 for all titles, even those that aren't officially supported.", 
    "ebisu_client_enable_igo_log_tooltip": "This feature is for troubleshooting only. Enabling it can significantly reduce performance.", 
    "ebisu_client_advanced": "Advanced", 
    "ebisu_client_experience_reporting_title": "%1 Experience Reporting", 
    "ebisu_client_experience_reporting_text": "Help improve %1 and enhance user experience by sharing your hardware specifications and usage data with EA. Please note, preferences selected here apply only to %1, and some critical usage data (such as game entitlements) will always be shared with %1. See our %2 for full details.", 
    "ebisu_client_faq" : "FAQ", 
    "ebisu_client_send_hardware_data" : "Share hardware specifications", 
    "ebisu_client_send_usage_data" : "Share system interaction data", 
    "ebisu_client_crash_reporting_title" : "%1 Crash Reporting", 
    "ebisu_client_beta_title" : "%1 Beta Participation", 
    "ebisu_client_general" : "General", 
    "ebisu_client_interface" : "Interface", 
    "ebisu_client_notifications" : "Notifications", 
    "ebisu_client_igo_logging_warning" : "Enabling this option allows for the creation of log files to help debug %1. We recommend keeping this unchecked unless you are given instructions by a customer service representative.", 
    "ebisu_client_cant_change_lang_oig" : "Cannot change language while in %1", 
    "ebisu_client_language_da_dk" : "Dansk (Dänisch)", 
    "ebisu_client_language_nl_nl" : "Nederlands (Niederländisch)", 
    "ebisu_client_language_en_gb" : "English GB (Englisch GB)", 
    "ebisu_client_language_en_us" : "English US (Englisch USA)", 
    "ebisu_client_language_fr_fr" : "Français (Französisch)", 
    "ebisu_client_language_de_de" : "Deutsch", 
    "ebisu_client_language_it_it" : "Italiano (Italienisch)", 
    "ebisu_client_language_ja_jp" : "??? (Japanisch)", 
    "ebisu_client_language_ko_kr" : "??? (Koreanisch)", 
    "ebisu_client_language_pl_pl" : "Polski (Polnisch)", 
    "ebisu_client_language_ru_ru" : "??????? (Russisch)", 
    "ebisu_client_language_spanish" : "Spanisch", 
    "ebisu_client_language_sv_se" : "Svenska (Schwedisch)", 
    "ebisu_client_language_th_th" : "??????? (Thai)", 
    "ebisu_client_language_traditional_chinese" : "Traditionelles Chinesisch", 
    "ebisu_client_language_fi_fi" : "Suomi (Finnisch)", 
    "ebisu_client_language_el_gr" : "???????? (Griechisch)", 
    "ebisu_client_language_hu_hu" : "Magyar (Ungarisch)", 
    "ebisu_client_language_no_no" : "Norsk (Norwegisch)", 
    "ebisu_client_language_pt_br" : "Português Brasil (Portugiesisch Brasilien)", 
    "ebisu_client_language_pt_pt" : "Português Portugal (Portugiesisch Portugal)", 
    "ebisu_client_language_es_mx" : "Español México (Spanisch Mexiko)", 
    "ebisu_client_language_es_es" : "Español España (Spanisch Spanien)", 
    "ebisu_client_language_cs_cz" : "Ceština (Tschechisch)", 
    "ebisu_client_settings_language_restriction_play" : "Please exit any games launched from %1 before changing languages.", 
    "ebisu_client_settings" : "Settings", 
    "ebisu_client_preferences" : "Preferences", 
    "ebisu_client_settings_autostart" : "Automatically launch %1 when I log on to Windows", 
    "ebisu_client_settings_autostart_mac" : "Automatically launch %1 when I log in", 
    "ebisu_client_cloud_settings_enable_tooltip" : "This feature syncs your saved games to the cloud so you can access them from other computers.", 
    "ebisu_client_beta_tooltip" : "Updating to the beta version will give you access to new features that are still in development. You can always go back to the official release by unmarking the checkbox and restarting %1.",
    "ebisu_client_oig_manual_disable_desc" : "Origin In Game lets you connect with friends, browse the web, and more during your game. Since not all games support Origin In Game, we recommend selecting \"supported games only\”. <p>If you experience issues, you can disable OIG (please note that disabling OIG could disrupt some in-game features in other titles). You can also disable OIG for individual games by right-clicking on the game in My Games and selecting \"Game Properties...\".</p>",
    "ebisu_client_action_group_chat": "Start Group Chat",
    "ebisu_client_action_invite_to_group_chat": "Invite to Group Chat",
    "ebisu_client_web_integration_title" : "%1 Helper",
    "ebisu_client_web_integration_description" : "This lets web programs use %1 as needed for smoother downloads, game launches, etc.",
    "ebisu_client_enable_web_integration" : "Enable %1 Helper",
    "ebisu_client_quiet_mode_heading" : "Quiet Mode",
    "ebisu_client_quiet_mode_description": "These settings relate to minimizing the presence of %1 so you can focus on playing your games.",
    "ebisu_client_disable_promomanager": "Hide featured today promotions when first opening %1",
    "ebisu_client_ignore_nonmandatory_game_patches": "Ignore non-mandatory game patches",
    "ebisu_client_exit_origin_after_closing_game": "Automatically exit %1 after closing a game",
    "ebisu_client_exit_origin_after_closing_game_tooltip" : "Warning tot user about enabling the setting that will automatically exit %1 when user closes a game",
    "ebisu_client_must_be_online_to_change_setting": "You'll need to be online to change this setting.",
    "ebisu_client_cloud_text": "%1 syncs your saved games to the cloud, allowing you to access and continue playing them from any %1-enabled computer.",
	"ebisu_client_voice_chat": "Voice Chat",
    "ebisu_client_settings_voice_test_button_start": "Test Microphone",
    "ebisu_client_settings_voice_test_button_stop": "Stop Microphone Test",
    "ebisu_client_voice_input_level": "Input Level:",
    "ebisu_client_voice_threshold": "Threshold:",
    "ebisu_client_voice_activation_description": "With voice activation, your microphone automatically starts transmitting after it reaches the threshold represented as a slider below",
    "ebisu_client_push_to_talk_description": "With push to talk, you start broadcasting when you press a hotkey",
    "ebisu_client_push_to_talk_shortcut": "Push to Talk Keyboard Shortcut",
    "ebisu_client_enable_voice_chat_indicator": "Show who's talking in your current voice channel directly in game",
    "ebisu_client_decline_voice_chat_requests": "Automatically decline all incoming voice chat requests",
    "ebisu_client_no_warn_voice_chat_conflict": "Don't warn me that starting a new voice chat will end my current voice chat (if applicable)"
    },

    translate: function(string_id) {
        var fallbackStrings = originTranslator.fallbackStrings;

        if (string_id in fallbackStrings) {
            return fallbackStrings[string_id];
        }

        return string_id;
    }
}

window.tr = function(string_id) {
    return originTranslator.translate(string_id)
}
