DirtySock: CommSRP
CommSRP
Comm
Typedefs
typedef struct CommSRPRef CommSRPRef
Functions
DIRTYCODE_API CommSRPRef * CommSRPConstruct (int32_t maxwid, int32_t maxinp, int32_t maxout)
Construct the class.
DIRTYCODE_API void CommSRPDestroy (CommSRPRef *what)
Destruct the class.
DIRTYCODE_API int32_t CommSRPResolve (CommSRPRef *what, const char *addr, char *buf, int32_t len, char div)
Resolve an address (unimplemented)
DIRTYCODE_API void CommSRPUnresolve (CommSRPRef *what)
Stop the resolver.
DIRTYCODE_API int32_t CommSRPListen (CommSRPRef *what, const char *addr)
Listen for a connection.
DIRTYCODE_API int32_t CommSRPUnlisten (CommSRPRef *what)
Stop listening.
DIRTYCODE_API int32_t CommSRPConnect (CommSRPRef *what, const char *addr)
Initiate a connection to a peer.
DIRTYCODE_API int32_t CommSRPUnconnect (CommSRPRef *what)
Terminate a connection.
DIRTYCODE_API void CommSRPCallback (CommSRPRef *what, void(*callback)(CommRef *ref, int32_t event))
Set upper layer callback.
DIRTYCODE_API int32_t CommSRPStatus (CommSRPRef *what)
Return current stream status.
DIRTYCODE_API uint32_t CommSRPTick (CommSRPRef *what)
Return current tick.
DIRTYCODE_API int32_t CommSRPSend (CommSRPRef *what, const void *buffer, int32_t length, uint32_t flags)
Send a packet.
DIRTYCODE_API int32_t CommSRPPeek (CommSRPRef *what, void *target, int32_t length, uint32_t *when)
Peek at waiting packet, and copy to target buffer if present.
DIRTYCODE_API int32_t CommSRPRecv (CommSRPRef *what, void *target, int32_t length, uint32_t *when)
Receive a packet from the buffer.
Detailed Description
Typedef Documentation
typedef struct CommSRPRef CommSRPRef
Function Documentation
DIRTYCODE_API void CommSRPCallback (CommSRPRef * ref, void(*)(CommRef *ref, int32_t event) callback)
Set upper layer callback.
Parameters
*ref - reference pointer
*callback - socket generating callback
Version
01/03/03 (JLB)
Referenced by CommSRPConstruct().
DIRTYCODE_API int32_t CommSRPConnect (CommSRPRef * ref, const char * pAddr)
Initiate a connection to a peer.
Parameters
*ref - reference pointer
*pAddr - address in ip-address:port form
Returns
int32_t - negative=error, zero=ok
Note
Does not perform dns translation
Version
01/03/03 (JLB)
References CALLB_RECV, COMM_BADADDRESS, COMM_BADSTATE, COMM_NORESOURCE, COMM_UNEXPECTED, NetPrintf, NULL, CommSRPRef::peeraddr, SockaddrInit, SockaddrInParse2(), SockaddrInSetAddr, SockaddrInSetPort, CommSRPRef::socket, SocketBind(), SocketCallback(), SocketOpen(), ST_CONN, ST_IDLE, and CommSRPRef::state.
Referenced by CommSRPConstruct().
DIRTYCODE_API CommSRPRef* CommSRPConstruct (int32_t maxwid, int32_t maxinp, int32_t maxout)
Construct the class.
Parameters
maxwid - max record width
maxinp - input packet buffer size
maxout - output packet buffer size
Returns
CommSRPRef - reference pointer
Note
Initialized winsock for first class. also creates linked list of all current instances of the class and worker thread to do most udp stuff.
Version
01/03/03 (JLB)
References CommRef::Callback, CommSRPRef::common, COMMSRP_MEMID, CommSRPCallback(), CommSRPConnect(), CommSRPDestroy(), CommSRPListen(), CommSRPPeek(), CommSRPRecv(), CommSRPResolve(), CommSRPSend(), CommSRPStatus(), CommSRPTick(), CommSRPUnconnect(), CommSRPUnlisten(), CommSRPUnresolve(), CommRef::Connect, CommSRPRef::connident, CommRef::Construct, CommSRPRef::crit, CommRef::Destroy, DirtyMemAlloc(), DirtyMemGroupQuery(), CommRef::Listen, CommRef::maxinp, CommRef::maxout, CommRef::maxwid, CommRef::memgroup, CommRef::memgrpusrdata, NetCritInit(), NULL, CommRef::Peek, CommSRPRef::rcvbuf, CommSRPRef::rcvlen, CommSRPRef::rcvrelresv, CommSRPRef::rcvwid, CommRef::Recv, RELIABLE_PCT_RESERVED, CommRef::Resolve, CommRef::Send, CommSRPRef::sndbuf, CommSRPRef::sndlen, CommSRPRef::sndwid, ST_IDLE, CommSRPRef::state, CommRef::Status, CommRef::Tick, CommRef::Unconnect, CommRef::Unlisten, and CommRef::Unresolve.
DIRTYCODE_API void CommSRPDestroy (CommSRPRef * ref)
Destruct the class.
Parameters
*ref - reference pointer
Version
01/03/03 (JLB)
References CommSRPRef::common, COMMSRP_MEMID, CommSRPRef::crit, DirtyMemFree(), CommRef::memgroup, CommRef::memgrpusrdata, NetCritKill(), NULL, CommSRPRef::rcvbuf, CommSRPRef::sndbuf, CommSRPRef::socket, SocketClose(), and CommSRPRef::state.
Referenced by CommSRPConstruct().
DIRTYCODE_API int32_t CommSRPListen (CommSRPRef * ref, const char * addr)
Listen for a connection.
Parameters
*ref - reference pointer
*addr - port to listen on (only :port portion used)
Returns
int32_t - negative=error, zero=ok
Version
01/03/03 (JLB)
References CALLB_RECV, COMM_BADADDRESS, COMM_BADSTATE, COMM_NORESOURCE, COMM_UNEXPECTED, NetPrintf, NULL, CommSRPRef::peeraddr, SockaddrInGetPort, SockaddrInit, SockaddrInParse2(), SockaddrInSetAddr, SockaddrInSetPort, CommSRPRef::socket, SocketBind(), SocketCallback(), SocketClose(), SocketOpen(), ST_IDLE, and CommSRPRef::state.
Referenced by CommSRPConstruct().
DIRTYCODE_API int32_t CommSRPPeek (CommSRPRef * ref, void * target, int32_t length, uint32_t * when)
Peek at waiting packet, and copy to target buffer if present.
Parameters
*ref - reference pointer
*target - target buffer
length - buffer length
*when - tick received at
Returns
int32_t - negative=nothing pending, else packet length
Version
01/03/03 (JLB)
References RawSRPPacketT::body, RawSRPPacketT::code, COMM_NODATA, RawSRPPacketT::data, ds_memcpy(), RawSRPPacketT::head, RawSRPPacketT::len, NetPrintf, NULL, CommSRPRef::rcvbuf, CommSRPRef::rcvinp, CommSRPRef::rcvout, and RawSRPPacketT::when.
Referenced by CommSRPConstruct(), and CommSRPRecv().
DIRTYCODE_API int32_t CommSRPRecv (CommSRPRef * ref, void * target, int32_t length, uint32_t * when)
Receive a packet from the buffer.
Parameters
*ref - reference pointer
*target - target buffer
length - buffer length
*when - tick received at
Returns
int32_t - negative=error, else packet length
Version
01/03/03 (JLB)
References CommSRPPeek(), CommSRPRef::rcvlen, CommSRPRef::rcvout, and CommSRPRef::rcvwid.
Referenced by CommSRPConstruct().
DIRTYCODE_API int32_t CommSRPResolve (CommSRPRef * ref, const char * addr, char * buf, int32_t len, char div)
Resolve an address (unimplemented)
Parameters
*ref - endpoint
*addr - resolve address
*buf - target buffer
len - target length (min 64 bytes)
div - divider char
Returns
int32_t - <0=error, 0=complete (COMM_NOERROR), >0=in progress (COMM_PENDING)
Note
Target list is always double null terminated allowing null to be used as the divider character if desired. when COMM_PENDING is returned, target buffer is set to "~" until completion
Version
01/03/03 (JLB)
References NetPrintf.
Referenced by CommSRPConstruct().
DIRTYCODE_API int32_t CommSRPSend (CommSRPRef * ref, const void * buffer, int32_t length, uint32_t flags)
Send a packet.
Parameters
*ref - reference pointer
*buffer - pointer to data
length - length of data
flags - COMM_FLAGS_*
Returns
int32_t - negative=error, zero=buffer full (temp fail), positive=queue position (ok)
Version
01/03/03 (JLB)
References RawSRPPacketT::body, RawSRPPacketT::code, COMM_BADSTATE, COMM_FLAGS_UNRELIABLE, COMM_MINBUFFER, COMMSRP_VERBOSE, RawSRPPacketT::data, ds_memcpy(), RawSRPPacketT::head, RawSRPPacketT::len, NetPrintf, CommSRPRef::relseqn, RELSEQN_BASE, SEQN_MASK, CommSRPRef::sndbuf, CommSRPRef::sndinp, CommSRPRef::sndlen, CommSRPRef::sndout, CommSRPRef::sndwid, CommSRPRef::state, CommSRPRef::unrelseqn, and UNRELSEQN_BASE.
Referenced by CommSRPConstruct().
DIRTYCODE_API int32_t CommSRPStatus (CommSRPRef * ref)
Return current stream status.
Parameters
*ref - reference pointer
Returns
int32_t - COMM_CONNECTING, COMM_OFFLINE, COMM_ONLINE or COMM_FAILURE
Version
01/03/03 (JLB)
References COMM_CONNECTING, COMM_FAILURE, COMM_OFFLINE, COMM_ONLINE, ST_CONN, ST_IDLE, and CommSRPRef::state.
Referenced by CommSRPConstruct().
DIRTYCODE_API uint32_t CommSRPTick (CommSRPRef * ref)
Return current tick.
Parameters
*ref - reference pointer
Returns
uint32_t - elapsed milliseconds
Version
01/03/03 (JLB)
References NetTick().
Referenced by CommSRPConstruct().
DIRTYCODE_API int32_t CommSRPUnconnect (CommSRPRef * ref)
Terminate a connection.
Parameters
*ref - reference pointer
Returns
int32_t - negative=error, zero=ok
Version
01/03/03 (JLB)
References NULL, CommSRPRef::socket, SocketClose(), ST_IDLE, and CommSRPRef::state.
Referenced by CommSRPConstruct().
DIRTYCODE_API int32_t CommSRPUnlisten (CommSRPRef * ref)
Stop listening.
Parameters
*ref - reference pointer
Returns
int32_t - negative=error, zero=ok
Version
01/03/03 (JLB)
References NULL, CommSRPRef::socket, SocketClose(), ST_IDLE, and CommSRPRef::state.
Referenced by CommSRPConstruct().
DIRTYCODE_API void CommSRPUnresolve (CommSRPRef * ref)
Stop the resolver.
Parameters
*ref - endpoint ref
Version
01/03/03 (JLB)
Referenced by CommSRPConstruct().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:31