DirtySock: ProtoAdvt
ProtoAdvt
Proto
Macros
#define ADVERT_BROADCAST_PORT_UDP 9999
define the ports used for service broadcasts
#define ADVERT_BROADCAST_PORT_IPX 9999
#define ADVERT_PACKET_IDENTIFIER "gEA"
define the static packet header identifier
Typedefs
typedef struct ProtoAdvtRef ProtoAdvtRef
module reference – passed as first arg to all module functions
Functions
DIRTYCODE_API ProtoAdvtRef * ProtoAdvtConstruct (int32_t buffer)
Construct an advertising agent.
DIRTYCODE_API void ProtoAdvtDestroy (ProtoAdvtRef *what)
Destruct an advertising agent.
DIRTYCODE_API int32_t ProtoAdvtQuery (ProtoAdvtRef *what, const char *kind, const char *proto, char *buffer, int32_t buflen, int32_t local)
Query for available services.
DIRTYCODE_API uint32_t ProtoAdvtLocate (ProtoAdvtRef *ref, const char *kind, const char *name, uint32_t *host, uint32_t defval)
Locate a specific advertisement and return advertisers address (UDP only)
DIRTYCODE_API int32_t ProtoAdvtAnnounce (ProtoAdvtRef *what, const char *kind, const char *name, const char *addr, const char *note, int32_t freq)
Advertise a service as available.
DIRTYCODE_API int32_t ProtoAdvtCancel (ProtoAdvtRef *what, const char *kind, const char *name)
Cancel server advertisement.
Detailed Description
Macro Definition Documentation
#define ADVERT_BROADCAST_PORT_IPX 9999
#define ADVERT_BROADCAST_PORT_UDP 9999
define the ports used for service broadcasts
Referenced by ProtoAdvtConstruct().
#define ADVERT_PACKET_IDENTIFIER "gEA"
define the static packet header identifier
Referenced by ProtoAdvtAnnounce().
Typedef Documentation
typedef struct ProtoAdvtRef ProtoAdvtRef
module reference – passed as first arg to all module functions
Function Documentation
DIRTYCODE_API int32_t ProtoAdvtAnnounce (ProtoAdvtRef * ref, const char * kind, const char * name, const char * note, const char * addr, int32_t freq)
Advertise a service as available.
Parameters
*ref - reference pointer
*kind - service class (max 32 characters including NUL)
*name - service name (usually game name, max 32 characters including NUL)
*note - service note (max 32 characters including NUL)
*addr - service address list (max 120 characters, including NUL)
freq - announcement frequency, in seconds (can be in the range [2...250])
Returns
int32_t - <0 = error, 0=ok
Version
11/01/02 (GWS)
References ProtoAdvtPacketT::addr, ADVERT_PACKET_IDENTIFIER, ProtoAdvtRef::announce, ProtoAdvtRef::crit, DirtyMemAlloc(), ds_stricmp(), ds_strnzcpy(), ProtoAdvtPacketT::freq, ProtoAdvtPacketT::ident, ProtoAdvtPacketT::kind, ProtoAdvtRef::memgroup, ProtoAdvtRef::memgrpusrdata, ProtoAdvtPacketT::name, NetCritEnter(), NetCritLeave(), NetPrintf, NetTick(), ServListT::next, ProtoAdvtPacketT::note, NULL, ServListT::packet, PROTOADVT_MEMID, ProtoAdvtPacketT::seqn, and ServListT::timeout.
Referenced by NetGameUtilAdvert(), and NetGameUtilConnect().
DIRTYCODE_API int32_t ProtoAdvtCancel (ProtoAdvtRef * ref, const char * kind, const char * name)
Cancel server advertisement.
Parameters
*ref - reference pointer
*kind - service kind
*name - service name (usually game name, NULL=wildcard)
Returns
int32_t - <0=error, 0=ok
Version
11/01/02 (GWS)
References ProtoAdvtRef::announce, ProtoAdvtRef::crit, ds_stricmp(), ProtoAdvtPacketT::kind, ProtoAdvtPacketT::name, NetCritEnter(), NetCritLeave(), ServListT::next, NULL, ServListT::packet, and ServListT::timeout.
Referenced by NetGameUtilWithdraw(), and ProtoAdvtDestroy().
DIRTYCODE_API ProtoAdvtRef* ProtoAdvtConstruct (int32_t limit)
Construct an advertising agent.
Parameters
limit - size of snoop buffer (min 4)
Returns
ProtoAdvtRef * - construct ref (passed to other routines)
Version
11/01/02 (GWS)
References ADVERT_BROADCAST_PORT_UDP, CALLB_RECV, DirtyMemAlloc(), DirtyMemFree(), DirtyMemGroupQuery(), ds_memcpy_s(), INADDR_BROADCAST, NetCritEnter(), NetCritInit(), NetCritLeave(), NULL, PROTOADVT_MEMID, SockaddrInit, SockaddrInSetAddr, SockaddrInSetPort, SocketBind(), SocketCallback(), and SocketOpen().
DIRTYCODE_API void ProtoAdvtDestroy (ProtoAdvtRef * ref)
Destruct an advertising agent.
Parameters
*ref - construct ref
Version
11/01/02 (GWS)
References ProtoAdvtRef::announce, ProtoAdvtRef::crit, DirtyMemFree(), ProtoAdvtPacketT::kind, ProtoAdvtRef::memgroup, ProtoAdvtRef::memgrpusrdata, ProtoAdvtPacketT::name, NetCritEnter(), NetCritKill(), NetCritLeave(), NULL, ServListT::packet, PROTOADVT_MEMID, ProtoAdvtCancel(), ProtoAdvtRef::snoopbuf, ProtoAdvtRef::sock, and SocketClose().
Referenced by NetGameUtilComplete(), and NetGameUtilReset().
DIRTYCODE_API uint32_t ProtoAdvtLocate (ProtoAdvtRef * ref, const char * kind, const char * name, uint32_t * host, uint32_t defval)
Locate a specific advertisement and return advertisers address (UDP only)
Parameters
*ref - reference pointer
*kind - service kind (NULL=any)
*name - service name (usually game name, NULL=wildcard)
*host - pointer to buffer for host (our) address, or NULL
defval - value returned if module is not set
Returns
uint32_t - defval if ref is NULL, else first matching internet address
Version
11/01/02 (GWS)
References ds_stricmp(), ServListT::hostval, ServListT::inetval, ProtoAdvtPacketT::kind, ServListT::local, ProtoAdvtPacketT::name, NULL, ServListT::packet, ProtoAdvtRef::snoopbuf, and ProtoAdvtRef::snoopend.
Referenced by NetGameUtilComplete(), and NetGameUtilLocate().
DIRTYCODE_API int32_t ProtoAdvtQuery (ProtoAdvtRef * ref, const char * kind, const char * proto, char * buffer, int32_t buflen, int32_t local)
Query for available services.
Parameters
*ref - reference pointer
*kind - service kind
*proto - protocol
*buffer - target buffer
buflen - target length
local - if zero, exclude local lists
Returns
int32_t - number of matches
Version
11/01/02 (GWS)
References ProtoAdvtPacketT::addr, ds_stricmp(), ds_strnzcpy(), ServListT::inetdot, ProtoAdvtPacketT::kind, ServListT::local, ProtoAdvtPacketT::name, ProtoAdvtPacketT::note, NULL, ServListT::packet, ProtoAdvtRef::snoopbuf, and ProtoAdvtRef::snoopend.
Referenced by NetGameUtilQuery().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:56