DirtySock: ProtoMangle
ProtoMangle
Proto
Macros
#define PROTOMANGLE_STRCOOKIE_MAX (64)
max cookie length, including terminator
#define PROTOMANGLE_STRGAMEID_MAX (32)
max gameFeatureID length, including terminator
#define PROTOMANGLE_STRLKEY_MAX (64)
max LKey length, including terminator
#define PROTOMANGLE_STRSERVER_MAX (32)
max server name length, including terminator
#define PROTOMANGLE_SERVER ("demangler.ea.com")
default server name
#define PROTOMANGLE_TEST_SERVER ("peach.online.ea.com")
development server
#define PROTOMANGLE_PORT (3658)
default server port
Typedefs
typedef enum ProtoMangleStatusE ProtoMangleStatusE
response codes
typedef struct ProtoMangleRefT ProtoMangleRefT
Enumerations
enum ProtoMangleStatusE {
PROTOMANGLE_STATUS_CONNECTED,
PROTOMANGLE_STATUS_FAILED,
PROTOMANGLE_NUMSTATUS
}
response codes
Functions
DIRTYCODE_API ProtoMangleRefT * ProtoMangleCreate (const char *pServer, int32_t iPort, const char *pGameID, const char *pLKey)
Allocate module state and prepare for use.
DIRTYCODE_API void ProtoMangleDestroy (ProtoMangleRefT *pRef)
Destroy the module and release its state.
DIRTYCODE_API void ProtoMangleUpdate (ProtoMangleRefT *pRef)
Update module state.
DIRTYCODE_API void ProtoMangleConnect (ProtoMangleRefT *pRef, int32_t iGamePort, const char *pSessID)
no-op on XboxOne
DIRTYCODE_API void ProtoMangleConnect2 (ProtoMangleRefT *pRef, int32_t iGamePort, const char *pSessID, int32_t iSessIDLen)
Initiate asynchronous resolution of secure address.
DIRTYCODE_API void ProtoMangleConnectSocket (ProtoMangleRefT *pRef, intptr_t uSocketRef, const char *pSessID)
no-op on XboxOne
DIRTYCODE_API int32_t ProtoMangleComplete (ProtoMangleRefT *pRef, int32_t *pAddr, int32_t *pPort)
Returns TRUE and fills in address and port if secure address resolution finished successfully.
DIRTYCODE_API int32_t ProtoMangleReport (ProtoMangleRefT *pRef, ProtoMangleStatusE eStatus, int32_t iLatency)
no-op on XboxOne
DIRTYCODE_API int32_t ProtoMangleControl (ProtoMangleRefT *pRef, int32_t iControl, int32_t iValue, int32_t iValue2, const void *pValue)
ProtoMangle control function.
DIRTYCODE_API int32_t ProtoMangleStatus (ProtoMangleRefT *pRef, int32_t iSelect, void *pBuf, int32_t iBufSize)
Return module status based on input selector.
Detailed Description
Macro Definition Documentation
#define PROTOMANGLE_PORT (3658)
default server port
Referenced by ConnApiOnline().
#define PROTOMANGLE_SERVER ("demangler.ea.com")
default server name
Referenced by ConnApiCreate2().
#define PROTOMANGLE_STRCOOKIE_MAX (64)
max cookie length, including terminator
#define PROTOMANGLE_STRGAMEID_MAX (32)
max gameFeatureID length, including terminator
#define PROTOMANGLE_STRLKEY_MAX (64)
max LKey length, including terminator
#define PROTOMANGLE_STRSERVER_MAX (32)
max server name length, including terminator
#define PROTOMANGLE_TEST_SERVER ("peach.online.ea.com")
development server
Typedef Documentation
typedef struct ProtoMangleRefT ProtoMangleRefT
typedef enum ProtoMangleStatusE ProtoMangleStatusE
response codes
Enumeration Type Documentation
enum ProtoMangleStatusE
response codes
Enumerator
PROTOMANGLE_STATUS_CONNECTED
PROTOMANGLE_STATUS_FAILED
PROTOMANGLE_NUMSTATUS
Function Documentation
DIRTYCODE_API int32_t ProtoMangleComplete (ProtoMangleRefT * pRef, int32_t * pAddr, int32_t * pPort)
Returns TRUE and fills in address and port if secure address resolution finished successfully.
Parameters
*pRef - module state
*pAddr - storage for address (result==TRUE)
*pPort - (ignored on XboxOne)
Returns
int32_t - >0=complete; 0=tryagain; <0=error
Version
04/05/2013 (mclouatre)
References ProtoMangleRefT::aClients, ProtoMangleSecurityAssocT::eMangleState, ProtoMangleSecurityAssocT::iIpv4Addr, ProtoMangleRefT::iVerbose, NetPrintf, NetPrintfVerbose, NULL, ProtoMangleClientT::pAssoc, PROTOMANGLE_STATE_CLEANING, PROTOMANGLE_STATE_CREATING, PROTOMANGLE_STATE_DONE, PROTOMANGLE_STATE_FAILED, PROTOMANGLE_STATE_INIT, PROTOMANGLE_STATE_LISTENING, PROTOMANGLE_STATE_MULTI_UNLOCK, PROTOMANGLE_STATE_TIMEDOUT, ProtoMangleSecurityAssocT::refRemoteCanonicalName, and ProtoMangleSecurityAssocT::refRemotePort.
DIRTYCODE_API void ProtoMangleConnect (ProtoMangleRefT * pRef, int32_t iMyPort, const char * pSessID)
no-op on XboxOne
Parameters
*pRef - module state
iMyPort - (ignored on XboxOne)
*pSessID - (ignored on XboxOne)
Version
04/05/2013 (mclouatre)
DIRTYCODE_API void ProtoMangleConnect2 (ProtoMangleRefT * pRef, int32_t iClientIndex, const char * pAddr, int32_t iAddrSize)
Initiate asynchronous resolution of secure address.
Parameters
*pRef - module state
iClientIndex - client index
*pAddr - pointer to SecureDeviceAddress of other xboxone device
iAddrSize - size of SecureDeviceAddress, or size of client certificate for dedicated server
Version
04/05/2013 (mclouatre)
References ProtoMangleRefT::aClients, DirtyMemAlloc(), ProtoMangleSecurityAssocT::iClientIndex, ProtoMangleRefT::iMemGroup, ProtoMangleRefT::iVerbose, NetPrintf, NetPrintfVerbose, NetPrintMem, NULL, ProtoMangleClientT::pAssoc, ProtoMangleRefT::pMemGroupUserData, PROTOMANGLE_MEMID, and ProtoMangleClientT::refPendingSecureDeviceAddr.
DIRTYCODE_API void ProtoMangleConnectSocket (ProtoMangleRefT * pRef, intptr_t uSockRef, const char * pSessID)
no-op on XboxOne
Parameters
*pRef - module state
uSockRef - (ignored on XboxOne)
*pSessID - (ignored on XboxOne)
Version
04/05/2013 (mclouatre)
DIRTYCODE_API int32_t ProtoMangleControl (ProtoMangleRefT * pRef, int32_t iControl, int32_t iValue, int32_t iValue2, const void * pValue)
ProtoMangle control function.
Parameters
*pRef - mangle ref
iControl - control selector
iValue - selector specific
iValue2 - selector specific
*pValue - selector specific
Note
iControl can be one of the following:
        abrt: abort currently ongoing secure address resolution
        cert: starts client certificate request async operation
        exsn: set the external session name for the MultiplayerSessionReference
        exst: set the external session template name for the MultiplayerSessionReference
        remv: remove specified client (release matching security association)
        scid: set the service configuration id for the MultiplayerSessionReference
        self: set local client index
        spam: sets debug output verbosity (0...n)
        time: set the maximum time waiting for locally-initiated async security association creation
Version
04/05/2013 (mclouatre)
References ProtoMangleRefT::aClients, ProtoMangleSecurityAssocT::eMangleState, ProtoMangleRefT::iAssocCreateTimeout, ProtoMangleRefT::iSelf, ProtoMangleRefT::iVerbose, NetPrintf, NetPrintfVerbose, NULL, ProtoMangleClientT::pAssoc, ProtoMangleRefT::refScid, ProtoMangleRefT::refSessionName, and ProtoMangleRefT::refSessionTemplateName.
Referenced by ConnApiConnect(), and ConnApiControl().
DIRTYCODE_API ProtoMangleRefT* ProtoMangleCreate (const char * pServer, int32_t iPort, const char * pGameID, const char * pLKey)
Allocate module state and prepare for use.
Parameters
*pServer - ignored
iPort - max number of clients
*pGameID - ignored
*pLKey - multiplayer session id
Returns
ProtoMangleRefT * - reference pointer (must be passed to all other functions)
Version
04/05/2013 (mclouatre)
References ProtoMangleRefT::bSecureBypass, DirtyMemAlloc(), FALSE, ProtoMangleRefT::iAssocCreateTimeout, ProtoMangleStateT::iMapRefCount, ProtoMangleRefT::iMaxClients, ProtoMangleRefT::iMemGroup, ProtoMangleRefT::iVerbose, ProtoMangleRefT::MangleCrit, NetConnStatus(), NetCritInit(), NetPrintf, NetPrintfVerbose, NULL, ProtoMangleRefT::pMemGroupUserData, pRef, PROTOMANGLE_MEMID, PROTOMANGLE_SECURITYASSOC_CREATION_TIMEOUT, ProtoMangleRefT::refIncomingSecurityAssocVect, ProtoMangleStateT::refRemoteHostRefCountMap, ProtoMangleRefT::refSecureDeviceAssociationTemplate, and TRUE.
Referenced by ConnApiOnline().
DIRTYCODE_API void ProtoMangleDestroy (ProtoMangleRefT * pRef)
Destroy the module and release its state.
Parameters
*pRef - reference pointer
Version
04/05/2013 (mclouatre)
References ProtoMangleRefT::iVerbose, NetConnControl(), and NetPrintfVerbose.
Referenced by ConnApiDestroy().
DIRTYCODE_API int32_t ProtoMangleReport (ProtoMangleRefT * pRef, ProtoMangleStatusE eStatus, int32_t iLatency)
no-op on XboxOne
Parameters
*pRef - mangle ref
eStatus - (ignored on XboxOne)
iLatency - (ignored on XboxOne)
Returns
int32_t - zero=success, negative=failure
Version
04/05/2013 (mclouatre)
DIRTYCODE_API int32_t ProtoMangleStatus (ProtoMangleRefT * pRef, int32_t iSelect, void * pBuf, int32_t iBufSize)
Return module status based on input selector.
Parameters
*pRef - mangle ref
iSelect - status selector
*pBuf - [out] storage for output data
iBufSize - size of output buffer
Note
iSelect can be one of the following:
        idle: true/false indication of whether module is idle or not
        secu: true/false indication of whether security is enabled (based on template settings) for this ref
        time: true/false indication of whether security assoc timed out
Version
04/05/2013 (mclouatre)
References ProtoMangleRefT::aClients, ProtoMangleRefT::bSecureBypass, ProtoMangleSecurityAssocT::eMangleState, FALSE, ProtoMangleRefT::iVerbose, NetPrintfVerbose, NULL, ProtoMangleClientT::pAssoc, PROTOMANGLE_STATE_TIMEDOUT, ProtoMangleClientT::refPendingSecureDeviceAddr, and TRUE.
DIRTYCODE_API void ProtoMangleUpdate (ProtoMangleRefT * pRef)
Update module state.
Parameters
*pRef - module reference
Version
04/05/2013 (mclouatre)
References _ProtoMangleProcessIncomingSAs(), ProtoMangleRefT::aClients, ProtoMangleRefT::iMaxClients, NULL, ProtoMangleClientT::pAssoc, ProtoMangleSecurityAssocT::pNext, and ProtoMangleRefT::pSecurityAssocKillList.
Referenced by ConnApiUpdate().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:21