DirtySock: commser.c File Reference
commser.c File Reference
Serial comm driver.
#include <windows.h>
#include "DirtySDK/dirtysock.h"
#include "DirtySDK/dirtysock/dirtymem.h"
#include "DirtySDK/comm/commall.h"
#include "DirtySDK/comm/pc/commser.h"
Data Structures
struct RawSerPacketT
raw protocol packet format
struct CommSerRef
private module storage
Typedefs
typedef struct CommSerRef CommSerRef
private module storage
Enumerations
enum {
RAW_PACKET_INIT = 1,
RAW_PACKET_CONN,
RAW_PACKET_DISC,
RAW_PACKET_NAK,
RAW_PACKET_DATA = 100
}
define error free protocol packet types
Functions
CommSerRef * CommSerConstruct (int32_t maxwid, int32_t maxinp, int32_t maxout)
Construct the class.
void CommSerDestroy (CommSerRef *ref)
Destruct the class.
void CommSerCallback (CommSerRef *ref, void(*callback)(CommRef *ref, int32_t event))
Set upper layer callback.
int32_t CommSerResolve (CommSerRef *ref, const char *addr, char *buf, int32_t len, char div)
Resolve an address.
void CommSerUnresolve (CommSerRef *ref)
Stop the resolver.
int32_t CommSerRecover (CommSerRef *ref, const char *addr)
Recover a broken connection.
int32_t CommSerListen (CommSerRef *ref, const char *addr)
Listen for a connection.
int32_t CommSerUnlisten (CommSerRef *ref)
Stop listening.
int32_t CommSerConnect (CommSerRef *ref, const char *addr)
Initiate a connection to a peer.
int32_t CommSerUnconnect (CommSerRef *ref)
Terminate a connection.
int32_t CommSerStatus (CommSerRef *ref)
Return current stream status.
uint32_t CommSerTick (CommSerRef *ref)
Return current tick.
int32_t CommSerSend (CommSerRef *ref, const void *buffer, int32_t length)
Send a packet.
int32_t CommSerPeek (CommSerRef *ref, void *target, int32_t length, uint32_t *when)
Peek at waiting packet.
int32_t CommSerRecv (CommSerRef *ref, void *target, int32_t length, uint32_t *when)
Receive a packet from the buffer.
Detailed Description
Serial comm driver.
Note
This is a simple serial transport class which incorporates the notions of virtual connections and error free transfer. The protocol is optimized for use in a real-time environment where latency is more important than bandwidth. Overhead is low with the protocol adding only 8 bytes per packet on top of that required by Ser itself.
Attention
Copyright (c) Tiburon Entertainment / Electronic Arts 1999-2003. ALL RIGHTS RESERVED.
Version
1.0 02/15/99 (GWS) First Version
1.1 02/25/99 (GWS) Alpha release
Typedef Documentation
typedef struct CommSerRef CommSerRef
private module storage
Enumeration Type Documentation
anonymous enum
define error free protocol packet types
Enumerator
RAW_PACKET_INIT
initiate a connection
RAW_PACKET_CONN
confirm a connection
RAW_PACKET_DISC
terminate a connection
RAW_PACKET_NAK
force resend of lost data
RAW_PACKET_DATA
initial data packet sequence number
Function Documentation
int32_t CommSerRecover (CommSerRef * ref, const char * addr)
Recover a broken connection.
Parameters
*ref - reference pointer
*addr - port to open on
Returns
int32_t - negative=error, zero=ok
Note
Not an advertised function; used internally and by tapi driver
Version
1.0 02/15/99 (GWS) First Version
References COMM_INPROGRESS, COMM_NOERROR, COMM_NORESOURCE, data, ds_strnzcpy(), FALSE, CommSerRef::handle, NULL, CommSerRef::rdover, CommSerRef::state, TRUE, CommSerRef::wrover, and CommSerRef::wtover.
Referenced by CommSerConnect(), and CommSerListen().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:41