DirtySock: DirtyWebApiPS4
DirtyWebApiPS4
DirtySock
Data Structures
struct DirtyWebApiCreateParamsT
Typedefs
typedef struct DirtyWebApiRefT DirtyWebApiRefT
typedef void(DirtyWebApiCallbackT)(int32_t iSceError, int32_t iUserIndex, int32_t iStatusCode, const char *pRespBody, int32_t iRespBodyLength, void *pUserData)
typedef void(DirtyWebApiPushEventCallbackT)(int32_t userCtxId, int32_t callbackId, const char *pNpServiceName, SceNpServiceLabel npServiceLabel, const SceNpPeerAddress *pTo, const SceNpPeerAddress *pFrom, const SceNpWebApiPushEventDataType *pDataType, const char *pData, size_t dataLen, void *pUserArg)
typedef struct
DirtyWebApiCreateParamsT DirtyWebApiCreateParamsT
Functions
DirtyWebApiRefT * DirtyWebApiCreate (const DirtyWebApiCreateParamsT *pCreateParams)
Allocate module state and prepare for use.
void DirtyWebApiDestroy (DirtyWebApiRefT *pRef)
Destroy the module and release its state.
int32_t DirtyWebApiRequest (DirtyWebApiRefT *pRef, int32_t iUserIndex, const char *pApiGroup, SceNpWebApiHttpMethod eHttpMethod, const char *pPath, const uint8_t *pContent, int32_t iContentLength, const char *pContentType, DirtyWebApiCallbackT *pCallback, void *pUserData)
Destroy the module and release its state.
int32_t DirtyWebApiAbortRequests (DirtyWebApiRefT *pRef, int32_t iUserIndex)
Stop any web requests for a given user, will NOT evoke completion callback. Not to be called from a completion callback.
int32_t DirtyWebApiAddPushEventListenerEx (DirtyWebApiRefT *pRef, const char *eventType, const char *pNpServiceName, SceNpServiceLabel npServiceLabel, DirtyWebApiPushEventCallbackT *callback, void *pUserData)
Adds a registration for push events, gives access to the "service" apis.
int32_t DirtyWebApiAddPushEventListener (DirtyWebApiRefT *pRef, const char *eventType, DirtyWebApiPushEventCallbackT *callback, void *pUserData)
Adds a registration for basic push events.
int32_t DirtyWebApiRemovePushEventListener (DirtyWebApiRefT *pRef, int32_t filterId, DirtyWebApiPushEventCallbackT *callback)
Removes a registration for basic push events.
int32_t DirtyWebApiControl (DirtyWebApiRefT *pRef, int32_t iControl, int32_t iValue, int32_t iValue2, void *pValue)
Destroy the module and release its state.
Detailed Description
Typedef Documentation
typedef void(DirtyWebApiCallbackT)(int32_t iSceError, int32_t iUserIndex, int32_t iStatusCode, const char *pRespBody, int32_t iRespBodyLength, void *pUserData)
typedef struct DirtyWebApiCreateParamsT DirtyWebApiCreateParamsT
typedef void(DirtyWebApiPushEventCallbackT)(int32_t userCtxId, int32_t callbackId, const char *pNpServiceName, SceNpServiceLabel npServiceLabel, const SceNpPeerAddress *pTo, const SceNpPeerAddress *pFrom, const SceNpWebApiPushEventDataType *pDataType, const char *pData, size_t dataLen, void *pUserArg)
typedef struct DirtyWebApiRefT DirtyWebApiRefT
Function Documentation
int32_t DirtyWebApiAbortRequests (DirtyWebApiRefT * pRef, int32_t iUserIndex)
Stop any web requests for a given user, will NOT evoke completion callback. Not to be called from a completion callback.
Parameters
*pRef - pointer to module state
iUserIndex - user index, if < 0 all users
Returns
int32_t - negative=error, else the number of requests aborted
Version
05/09/2013 (mcorcoran)
References NetPrintf, and NULL.
Referenced by _UserApiPlatAbortPostRequests(), DirtySessionManagerControl(), UserApiPlatAbortRequests(), and UserListApiCancelAll().
int32_t DirtyWebApiAddPushEventListener (DirtyWebApiRefT * pRef, const char * eventType, DirtyWebApiPushEventCallbackT * callback, void * pUserData)
Adds a registration for basic push events.
Parameters
pRef - module state
eventType - event type from sony ie "np:service:presence:onlineStatus"
callback - function to call when the event triggers
pUserData - data passed to the callback when it triggers
Version
07/20/2013 (cvienneau)
References NULL.
Referenced by UserApiPlatRegisterUpdateEvent(), and UserListApiRegisterUpdateEvent().
int32_t DirtyWebApiAddPushEventListenerEx (DirtyWebApiRefT * pRef, const char * eventType, const char * pNpServiceName, SceNpServiceLabel npServiceLabel, DirtyWebApiPushEventCallbackT * callback, void * pUserData)
Adds a registration for push events, gives access to the "service" apis.
Parameters
pRef - module state
eventType - event type from sony ie "np:service:invitation"
pNpServiceName - NP web service generating the event ie "sessionInvitation"
npServiceLabel - more detail on the web service, usually SCE_NP_DEFAULT_SERVICE_LABEL
callback - function to call when the event triggers
pUserData - data passed to the callback when it triggers
Version
07/20/2013 (cvienneau)
Referenced by DirtySessionManagerUpdate(), and UserApiPlatRegisterUpdateEvent().
int32_t DirtyWebApiControl (DirtyWebApiRefT * pRef, int32_t iControl, int32_t iValue, int32_t iValue2, void * pValue)
Destroy the module and release its state.
Parameters
*pRef - reference pointer
iControl - control selector
iValue - control value
iValue2 - control value
*pValue - [in/out] control value
Returns
int32_t - negative=error, else success
        qcal: TRUE to enable callback queuing else FALSE. All non push event callback if queue will be executed by the NetConnIdle thread
        rbuf: set the read buffer size.
Version
05/22/2013 (amakoukji)
References DirtyWebApiRefT::aReadBuffer, DirtyWebApiRefT::bQueueCallback, DirtyMemAlloc(), DirtyMemFree(), DIRTYSESSMGR_MEMID, DirtyWebApiRefT::iMemGroup, NetPrintf, NULL, DirtyWebApiRefT::pMemGroupUserData, and DirtyWebApiRefT::uReadBufferSize.
Referenced by DirtySessionManagerControl().
DirtyWebApiRefT* DirtyWebApiCreate (const DirtyWebApiCreateParamsT * pCreateParams)
Allocate module state and prepare for use.
Parameters
pCreateParams - creation parameters as per user preference
Returns
DirtyWebApiRefT * - reference pointer (must be passed to all other functions)
Version
09/06/2013 (abaldeva)
References DirtyWebApiRefT::abortCrit, DirtyWebApiRefT::aReadBuffer, DirtyWebApiRefT::bQueueCallback, DirtyWebApiRefT::crit, DIRTY_WEBAPI_HTTP_HEAP_SIZE, DIRTY_WEBAPI_NET_HEAP_NAME, DIRTY_WEBAPI_NET_HEAP_SIZE, DIRTY_WEBAPI_READ_BUFFER_SIZE, DIRTY_WEBAPI_SSL_HEAP_SIZE, DIRTY_WEBAPI_WEBAPI_HEAP_SIZE, DirtyErrGetName(), DirtyMemAlloc(), DirtyMemFree(), DirtyMemGroupQuery(), DIRTYSESSMGR_MEMID, DirtyWebApiDestroy(), FALSE, DirtyWebApiCreateParamsT::httpHeapSize, DirtyWebApiRefT::iMemGroup, NetConnIdleAdd(), NetCritInit(), DirtyWebApiCreateParamsT::netHeapSize, NetPrintf, NULL, DirtyWebApiRefT::pMemGroupUserData, pRef, DirtyWebApiCreateParamsT::readBufferSize, DirtyWebApiCreateParamsT::sslHeapSize, DirtyWebApiRefT::uReadBufferSize, DirtyWebApiCreateParamsT::webApiHeapSize, and DirtyWebApiRefT::WebApiThread.
Referenced by DirtySessionManagerCreate(), UserApiPlatCreateData(), and UserListApiCreate().
void DirtyWebApiDestroy (DirtyWebApiRefT * pRef)
Destroy the module and release its state.
Parameters
*pRef - reference pointer
Version
05/09/2013 (mcorcoran)
References DirtyWebApiRefT::abortCrit, DirtyWebApiRefT::aReadBuffer, DirtyWebApiRefT::crit, DirtyMemFree(), DIRTYSESSMGR_MEMID, DirtyWebApiRefT::dirtyWebApiThreadMutex, DirtyWebApiRefT::dirtyWepApiThreadCond, DirtyWebApiRefT::iMemGroup, DirtyWebApiRefT::iThreadLife, NetConnIdleDel(), NetCritKill(), NetPrintf, NULL, DirtyWebApiRefT::pMemGroupUserData, and DirtyWebApiRefT::WebApiThread.
Referenced by DirtyWebApiCreate(), UserApiPlatCreateData(), UserApiPlatDestroyData(), and UserListApiDestroy().
int32_t DirtyWebApiRemovePushEventListener (DirtyWebApiRefT * pRef, int32_t filterId, DirtyWebApiPushEventCallbackT * callback)
Removes a registration for basic push events.
Parameters
*pRef - module state
filterId - filter id
*callback - function to remove
Returns
int32_t - 0 for success; negative for error
Version
09/04/2013 (amakoukji)
References DirtyWebApPushEventT::aCallBackIds, DirtyWebApPushEventsT::aEvents, DirtyWebApPushEventT::bServicePushEvent, DirtyErrGetName(), DirtyWebApPushEventsT::iEventCount, DirtyWebApPushEventT::iFilterId, DirtyWebApiRefT::iWebApiCtxId, DirtyWebApiUserT::iWebapiUserCtxId, NETCONN_MAXLOCALUSERS, NetPrintf, DirtyWebApPushEventT::pPushEventCallback, DirtyWebApiRefT::PushEvents, and DirtyWebApiRefT::WebApiUsers.
int32_t DirtyWebApiRequest (DirtyWebApiRefT * pRef, int32_t iUserIndex, const char * pApiGroup, SceNpWebApiHttpMethod eHttpMethod, const char * pPath, const uint8_t * pContent, int32_t iContentLength, const char * pContentType, DirtyWebApiCallbackT * pCallback, void * pUserData)
Destroy the module and release its state.
Parameters
*pRef - reference pointer
iUserIndex - user index
*pApiGroup - SCE API group
eHttpMethod - SCE HTTP method
*pPath - the URI path to request
*pContent - body content to be sent along with the HTTP request (e.g. POST or PUT requests)
*iContentLength - context length
*pContentType - context type
*pCallback - callback pointer
*pUserData - user data
Returns
int32_t - 0 on success, else negative=error
Version
05/09/2013 (mcorcoran)
References DirtyMemAlloc(), DIRTYWEBAPI_MEMID, ds_memcpy(), DirtyWebApiWebRequestT::iContentLength, DirtyWebApiRefT::iMemGroup, DirtyWebApiWebRequestT::iUserIndex, DirtyWebApiCallbackEntryT::iUserIndex, DirtyWebApiUserT::iWebapiUserCtxId, DirtyWebApiWebRequestT::iWebRequestId, NetPrintf, NULL, DirtyWebApiWebRequestT::pCallback, DirtyWebApiCallbackEntryT::pCallback, DirtyWebApiWebRequestT::pContent, DirtyWebApiRefT::pMemGroupUserData, DirtyWebApiWebRequestT::pUserData, DirtyWebApiCallbackEntryT::pUserData, and DirtyWebApiRefT::WebApiUsers.
Referenced by UserApiPlatRequestPostRichPresence(), UserApiPlatRequestPresence(), UserApiPlatRequestRecentlyMet(), UserApiPlatRequestRichPresence(), and UserApiPlatUpdate().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:19