DirtySock: DirtyNet
DirtyNet
DirtySock
Data Structures
struct HostentT
struct SocketSendCallbackEntryT
socket send callback entry (internal use only - needs to be public for DirtyCast stress tester)
Macros
#define SOCK_NORECV 1
caller does not want to receive more data
#define SOCK_NOSEND 2
caller does not want to send more data
#define INADDR_BROADCAST 0xffffffff
#define CALLB_NONE 0
no callback
#define CALLB_SEND 1
call when we can send
#define CALLB_RECV 2
call when we can receive
#define SOCKLOOK_LOCALADDR "*"
#define SOCKLOOK_FLAGS_ALLOWXDNS (1)
#define SOCKET_MAXUDPRECV (1264)
maximum udp packet size we can receive (constrained by Xbox 360 max VDP packet size)
#define SOCKET_MAXVIRTUALPORTS (32)
maximum number of virtual ports that can be specified
#define SOCKERR_NONE 0
no error
#define SOCKERR_CLOSED -1
the socket is closed
#define SOCKERR_NOTCONN -2
the socket is not connected
#define SOCKERR_BLOCKED -3
operation would result in blocking
#define SOCKERR_ADDRESS -4
the address is invalid
#define SOCKERR_UNREACH -5
network cannot be accessed by this host
#define SOCKERR_REFUSED -6
connection refused by the recipient
#define SOCKERR_OTHER -7
unclassified error
#define SOCKERR_NOMEM -8
out of memory
#define SOCKERR_NORSRC -9
out of resources
#define SOCKERR_UNSUPPORT -10
unsupported operation
#define SOCKERR_INVALID -11
resource or operation is invalid
#define SOCKERR_ADDRINUSE -12
address already in use
#define SOCKERR_CONNRESET -13
connection has been reset
#define SOCKERR_BADPIPE -14
EBADF or EPIPE.
#define SOCKET_MAXSENDCALLBACKS (8)
maximum number of send callbacks supported (internal use only - needs to be public for DirtyCast stress tester)
#define SA_DATA_TYPE unsigned char
#define SockaddrInit(addr, fam) { (addr)->sa_family = (fam); *((uint16_t *)&(addr)->sa_data[0]) = 0; *((uint32_t *)&(addr)->sa_data[2]) = 0; *((uint32_t *)&(addr)->sa_data[6]) = 0; *((uint32_t *)&(addr)->sa_data[10]) = 0; }
init a sockaddr to zero and set its family type
#define SockaddrInGetPort(addr) ((((unsigned char)(addr)->sa_data[0])<<8)|(((unsigned char)(addr)->sa_data[1])<<0))
get the port in host format from sockaddr
#define SockaddrInSetPort(addr, val) { (addr)->sa_data[0] = (SA_DATA_TYPE)((val)>>8); (addr)->sa_data[1] = (SA_DATA_TYPE)(val); }
set the port in host format in a sockaddr
#define SockaddrInGetAddr(addr) (((((((unsigned char)((addr)->sa_data[2])<<8)|(unsigned char)((addr)->sa_data[3]))<<8)|(unsigned char)((addr)->sa_data[4]))<<8)|(unsigned char)((addr)->sa_data[5]))
get the address in host format from sockaddr
#define SockaddrInSetAddr(addr, val) { uint32_t val2 = (val); (addr)->sa_data[5] = (SA_DATA_TYPE)val2; val2 >>= 8; (addr)->sa_data[4] = (SA_DATA_TYPE)val2; val2 >>= 8; (addr)->sa_data[3] = (SA_DATA_TYPE)val2; val2 >>= 8; (addr)->sa_data[2] = (SA_DATA_TYPE)val2; }
set the address in host format in a sockaddr
#define SockaddrInGetMisc(addr) (((((((unsigned char)((addr)->sa_data[6])<<8)|(unsigned char)((addr)->sa_data[7]))<<8)|(unsigned char)((addr)->sa_data[8]))<<8)|(unsigned char)((addr)->sa_data[9]))
get the misc field in host format from sockaddr
#define SockaddrInSetMisc(addr, val) { uint32_t val2 = (val); (addr)->sa_data[9] = (SA_DATA_TYPE)val2; val2 >>= 8; (addr)->sa_data[8] = (SA_DATA_TYPE)val2; val2 >>= 8; (addr)->sa_data[7] = (SA_DATA_TYPE)val2; val2 >>= 8; (addr)->sa_data[6] = (SA_DATA_TYPE)val2; }
set the misc field in host format in a sockaddr
#define SockaddrIsLoopback(addr) ((((addr)->sa_family == AF_INET) && ((addr)->sa_data[0] == 127) && ((addr)->sa_data[1] == 0) && ((addr)->sa_data[2] == 0) && ((addr)->sa_data[3] == 1)))
detect loopback address (family independent)
#define SockaddrInit6(addr, fam) { memset(addr, 0, sizeof(*(addr))); (addr)->sin6_family = (fam); }
init a sockaddr6 to zero and set its family type
#define SockaddrIn6GetAddr4(addr) (((((((uint8_t)((addr)->sin6_addr.s6_addr[12])<<8)|(uint8_t)((addr)->sin6_addr.s6_addr[13]))<<8)|(uint8_t)((addr)->sin6_addr.s6_addr[14]))<<8)|(uint8_t)((addr)->sin6_addr.s6_addr[15]))
get IPv6 address from IPv4-mapped IPv6 address, also works for NAT64
#define SocketSend(_pSocket, _pBuf, iLen, iFlags) SocketSendto(_pSocket, _pBuf, iLen, iFlags, NULL, 0)
#define SocketRecv(_pSocket, pBuf, iLen, iFlags) SocketRecvfrom(_pSocket, pBuf, iLen, iFlags, NULL, 0)
#define SocketLookup2(_text, _timeout, _flags) SocketLookup(_text, _timeout)
Typedefs
typedef struct SocketT SocketT
typedef struct HostentT HostentT
typedef int32_t(SocketSendCallbackT)(SocketT *pSocket, int32_t iType, const uint8_t *pData, int32_t iDataSize, const struct sockaddr *pTo, void *pCallref)
global socket send callback
typedef struct
SocketSendCallbackEntryT SocketSendCallbackEntryT
socket send callback entry (internal use only - needs to be public for DirtyCast stress tester)
Functions
DIRTYCODE_API int32_t SockaddrCompare (struct sockaddr *addr1, struct sockaddr *addr2)
Compare two sockaddr structs and see if address is the same. This is different from simple binary compare because only relevent fields are checked.
DIRTYCODE_API int32_t SockaddrInSetAddrText (struct sockaddr *addr, const char *str)
Set Internet address component of sockaddr struct from textual address (a.b.c.d).
DIRTYCODE_API char * SockaddrInGetAddrText (struct sockaddr *addr, char *str, int32_t len)
Return Internet address component of sockaddr struct in textual form (a.b.c.d).
DIRTYCODE_API uint16_t SocketHtons (uint16_t addr)
Convert int16_t from host to network byte order.
DIRTYCODE_API uint32_t SocketHtonl (uint32_t addr)
Convert int32_t from host to network byte order.
DIRTYCODE_API uint16_t SocketNtohs (uint16_t addr)
Convert int16_t from network to host byte order.
DIRTYCODE_API uint32_t SocketNtohl (uint32_t addr)
Convert int32_t from network to host byte order.
DIRTYCODE_API char * SocketInAddrGetText (uint32_t addr, char *str, int32_t len)
Convert 32-bit internet address into textual form.
DIRTYCODE_API int32_t SocketInTextGetAddr (const char *addrtext)
Convert textual internet address into 32-bit integer form.
DIRTYCODE_API int32_t SockaddrInParse (struct sockaddr *addr, const char *parse)
Convert textual internet address:port into sockaddr structure.
DIRTYCODE_API int32_t SockaddrInParse2 (uint32_t *pAddr, int32_t *pPort, int32_t *pPort2, const char *parse)
Convert textual internet address:port into sockaddr structure.
DIRTYCODE_API uint8_t SockaddrIn6IsIPv4 (const struct sockaddr *pSockAddr)
Identify if specified sockaddr is an IPv4-mapped IPv6 address.
DIRTYCODE_API uint8_t SockaddrIn6IsNAT64 (const struct sockaddr *pSockAddr)
Identify if specified sockaddr is a NAT64 IPv6 address.
DIRTYCODE_API uint8_t SockaddrIn6IsZero (const struct sockaddr *pSockAddr)
Identify if specified sockaddr is zero (unspecified)
DIRTYCODE_API int32_t SocketCreate (int32_t iThreadPrio, int32_t iThreadStackSize, int32_t iThreadCpuAffinity)
Create new instance of socket interface module. Initializes all global resources and makes module ready for use.
DIRTYCODE_API int32_t SocketDestroy (uint32_t uShutdownFlags)
Release resources and destroy module.
DIRTYCODE_API SocketT * SocketOpen (int32_t af, int32_t type, int32_t protocol)
Create a new transfer endpoint. A socket endpoint is required for any data transfer operation.
DIRTYCODE_API int32_t SocketShutdown (SocketT *pSocket, int32_t how)
Perform partial/complete shutdown of socket indicating that either sending and/or receiving is complete.
DIRTYCODE_API int32_t SocketClose (SocketT *pSocket)
Close a socket. Performs a graceful shutdown of connection oriented protocols.
DIRTYCODE_API SocketT * SocketImport (intptr_t uSockRef)
Import a socket. The given socket ref may be a SocketT, in which case a SocketT pointer to the ref is returned, or it can be an actual Sony socket ref, in which case a SocketT is created for the Sony socket ref.
DIRTYCODE_API void SocketRelease (SocketT *pSocket)
Release an imported socket.
DIRTYCODE_API int32_t SocketBind (SocketT *pSocket, const struct sockaddr *name, int32_t namelen)
Bind a local address/port to a socket.
DIRTYCODE_API int32_t SocketInfo (SocketT *pSocket, int32_t iInfo, int32_t iData, void *pBuf, int32_t iLen)
Return information about an existing socket.
DIRTYCODE_API int32_t SocketControl (SocketT *pSocket, int32_t option, int32_t data1, void *data2, void *data3)
Process a control message (type specific operation)
DIRTYCODE_API int32_t SocketListen (SocketT *pSocket, int32_t backlog)
Start listening for an incoming connection on the socket. The socket must already be bound and a stream oriented connection must be in use.
DIRTYCODE_API SocketT * SocketAccept (SocketT *pSocket, struct sockaddr *addr, int32_t *addrlen)
Accept an incoming connection attempt on a socket.
DIRTYCODE_API int32_t SocketConnect (SocketT *pSocket, struct sockaddr *name, int32_t namelen)
Initiate a connection attempt to a remote host.
DIRTYCODE_API int32_t SocketSendto (SocketT *pSocket, const char *buf, int32_t len, int32_t flags, const struct sockaddr *to, int32_t tolen)
Send data to a remote host. The destination address is supplied along with the data. Should only be used with datagram sockets as stream sockets always send to the connected peer.
DIRTYCODE_API int32_t SocketRecvfrom (SocketT *pSocket, char *buf, int32_t len, int32_t flags, struct sockaddr *from, int32_t *fromlen)
Receive data from a remote host. If socket is a connected stream, then data can only come from that source. A datagram socket can receive from any remote host.
DIRTYCODE_API int32_t SocketCallback (SocketT *pSocket, int32_t flags, int32_t timeout, void *ref, int32_t(*proc)(SocketT *pSocket, int32_t flags, void *ref))
DIRTYCODE_API int32_t SocketHost (struct sockaddr *host, int32_t hostlen, const struct sockaddr *dest, int32_t destlen)
Return the host address that would be used in order to communicate with the given destination address.
DIRTYCODE_API HostentT * SocketLookup (const char *text, int32_t timeout)
Lookup a host by name and return the corresponding Internet address. Uses a callback/polling system since the socket library does not allow blocking.
int32_t SocketSendCallbackInvoke (SocketSendCallbackEntryT aCbEntries[], SocketT *pSocket, int32_t iType, const char *pBuf, int32_t iLen, const struct sockaddr *pTo)
Invoke all send callbacks in specified collection. Only one of the callback is supposed to return "handled"... warn if not the case.
DIRTYCODE_API uint32_t SocketGetLocalAddr (void)
Returns the "external" local address (ie, the address as a machine "out on the Internet" would see as the local machine's address).
Detailed Description
Macro Definition Documentation
#define CALLB_NONE 0
no callback
#define CALLB_RECV 2
call when we can receive
Referenced by CommSRPConnect(), CommSRPListen(), CommTCPConnect(), CommTCPListen(), ProtoAdvtConstruct(), SocketControl(), and VoipConnectionStart().
#define CALLB_SEND 1
call when we can send
#define INADDR_BROADCAST 0xffffffff
Referenced by ProtoAdvtConstruct().
#define SA_DATA_TYPE unsigned char
#define SOCK_NORECV 1
caller does not want to receive more data
Referenced by SocketShutdown().
#define SOCK_NOSEND 2
caller does not want to send more data
Referenced by ProtoSSLDisconnect(), SocketBind(), and SocketShutdown().
#define SockaddrIn6GetAddr4 (addr) (((((((uint8_t)((addr)->sin6_addr.s6_addr[12])<<8)|(uint8_t)((addr)->sin6_addr.s6_addr[13]))<<8)|(uint8_t)((addr)->sin6_addr.s6_addr[14]))<<8)|(uint8_t)((addr)->sin6_addr.s6_addr[15]))
get IPv6 address from IPv4-mapped IPv6 address, also works for NAT64
Referenced by SocketAddrMapAddress(), and SocketAddrMapTranslate().
#define SockaddrInGetAddr (addr) (((((((unsigned char)((addr)->sa_data[2])<<8)|(unsigned char)((addr)->sa_data[3]))<<8)|(unsigned char)((addr)->sa_data[4]))<<8)|(unsigned char)((addr)->sa_data[5]))
get the address in host format from sockaddr
Referenced by CommUDPConnect(), ConnApiStatus2(), ProtoSSLConnect(), ProtoSSLStat(), SocketAddrMapAddress(), SocketAddrMapTranslate(), SocketBind(), SocketGetLocalAddr(), SocketHost(), SocketInTextGetAddr(), SocketSendto(), and VoipTunnelClientListMatchSockaddr().
#define SockaddrInGetMisc (addr) (((((((unsigned char)((addr)->sa_data[6])<<8)|(unsigned char)((addr)->sa_data[7]))<<8)|(unsigned char)((addr)->sa_data[8]))<<8)|(unsigned char)((addr)->sa_data[9]))
get the misc field in host format from sockaddr
#define SockaddrInGetPort (addr) ((((unsigned char)(addr)->sa_data[0])<<8)|(((unsigned char)(addr)->sa_data[1])<<0))
get the port in host format from sockaddr
Referenced by CommSRPListen(), CommUDPConnect(), SocketAddrMapTranslate(), SocketBind(), SocketInfo(), SocketSendto(), VoipConnectionStart(), and VoipTunnelClientListMatchSockaddr().
#define SockaddrInit (addr, fam) { (addr)->sa_family = (fam); *((uint16_t *)&(addr)->sa_data[0]) = 0; *((uint32_t *)&(addr)->sa_data[2]) = 0; *((uint32_t *)&(addr)->sa_data[6]) = 0; *((uint32_t *)&(addr)->sa_data[10]) = 0; }
init a sockaddr to zero and set its family type
Referenced by CommSRPConnect(), CommSRPListen(), CommTCPConnect(), CommTCPListen(), CommUDPConnect(), CommUDPListen(), ProtoAdvtConstruct(), ProtoSSLConnect(), ProtoUdpBind(), ProtoUdpConnect(), ProtoUpnpCreate(), SockaddrInParse(), SocketAccept(), SocketAddrMapTranslate(), SocketInfo(), and VoipConnectionStart().
#define SockaddrInit6 (addr, fam) { memset(addr, 0, sizeof(*(addr))); (addr)->sin6_family = (fam); }
init a sockaddr6 to zero and set its family type
Referenced by SocketAccept(), SocketConnect(), and SocketSendto().
#define SockaddrInSetAddr (addr, val) { uint32_t val2 = (val); (addr)->sa_data[5] = (SA_DATA_TYPE)val2; val2 >>= 8; (addr)->sa_data[4] = (SA_DATA_TYPE)val2; val2 >>= 8; (addr)->sa_data[3] = (SA_DATA_TYPE)val2; val2 >>= 8; (addr)->sa_data[2] = (SA_DATA_TYPE)val2; }
set the address in host format in a sockaddr
Referenced by CommSRPConnect(), CommSRPListen(), CommUDPConnect(), CommUDPListen(), CommUDPSend(), ProtoAdvtConstruct(), ProtoSSLConnect(), ProtoSSLUpdate(), ProtoUpnpCreate(), SockaddrInParse(), SocketAddrMapTranslate(), SocketBind(), SocketGetLocalAddr(), SocketHost(), SocketInAddrGetText(), and SocketInfo().
#define SockaddrInSetMisc (addr, val) { uint32_t val2 = (val); (addr)->sa_data[9] = (SA_DATA_TYPE)val2; val2 >>= 8; (addr)->sa_data[8] = (SA_DATA_TYPE)val2; val2 >>= 8; (addr)->sa_data[7] = (SA_DATA_TYPE)val2; val2 >>= 8; (addr)->sa_data[6] = (SA_DATA_TYPE)val2; }
set the misc field in host format in a sockaddr
Referenced by SocketPacketQueueRem().
#define SockaddrInSetPort (addr, val) { (addr)->sa_data[0] = (SA_DATA_TYPE)((val)>>8); (addr)->sa_data[1] = (SA_DATA_TYPE)(val); }
set the port in host format in a sockaddr
Referenced by CommSRPConnect(), CommSRPListen(), CommUDPConnect(), CommUDPListen(), ProtoAdvtConstruct(), ProtoSSLConnect(), ProtoUdpBind(), ProtoUpnpCreate(), SockaddrInParse(), SocketAddrMapTranslate(), SocketGetLocalAddr(), SocketInfo(), and VoipConnectionStart().
#define SockaddrIsLoopback (addr) ((((addr)->sa_family == AF_INET) && ((addr)->sa_data[0] == 127) && ((addr)->sa_data[1] == 0) && ((addr)->sa_data[2] == 0) && ((addr)->sa_data[3] == 1)))
detect loopback address (family independent)
#define SOCKERR_ADDRESS -4
the address is invalid
#define SOCKERR_ADDRINUSE -12
address already in use
#define SOCKERR_BADPIPE -14
EBADF or EPIPE.
#define SOCKERR_BLOCKED -3
operation would result in blocking
#define SOCKERR_CLOSED -1
the socket is closed
Referenced by ProtoSSLRecv(), ProtoSSLSend(), ProtoSSLStat(), SocketInfo(), and SocketRecvfrom().
#define SOCKERR_CONNRESET -13
connection has been reset
#define SOCKERR_INVALID -11
resource or operation is invalid
Referenced by ProtoSSLConnect(), SocketAccept(), SocketConnect(), and SocketSendto().
#define SOCKERR_NOMEM -8
out of memory
#define SOCKERR_NONE 0
no error
Referenced by CommUDPSend(), ProtoHttpServCreate2(), ProtoSSLAccept(), ProtoSSLConnect(), ProtoSSLCreate(), ProtoSSLDisconnect(), ProtoSSLUpdate(), SocketAccept(), SocketBind(), SocketConnect(), SocketControl(), SocketRecvfrom(), and VoipConnectionStart().
#define SOCKERR_NORSRC -9
out of resources
Referenced by ProtoSSLConnect().
#define SOCKERR_NOTCONN -2
the socket is not connected
Referenced by _ProtoWebSocketRecv(), ProtoWebSocketRecv(), and ProtoWebSocketSend().
#define SOCKERR_OTHER -7
unclassified error
Referenced by ProtoSSLBind(), ProtoWebSocketSend(), and SocketInfo().
#define SOCKERR_REFUSED -6
connection refused by the recipient
#define SOCKERR_UNREACH -5
network cannot be accessed by this host
#define SOCKERR_UNSUPPORT -10
unsupported operation
#define SOCKET_MAXSENDCALLBACKS (8)
maximum number of send callbacks supported (internal use only - needs to be public for DirtyCast stress tester)
Referenced by SocketSendCallbackAdd(), SocketSendCallbackInvoke(), and SocketSendCallbackRem().
#define SOCKET_MAXUDPRECV (1264)
maximum udp packet size we can receive (constrained by Xbox 360 max VDP packet size)
Referenced by SocketControl(), SocketCreate(), SocketPacketQueueAdd(), and SocketPacketQueueResize().
#define SOCKET_MAXVIRTUALPORTS (32)
maximum number of virtual ports that can be specified
Referenced by SocketBind(), and SocketControl().
#define SocketLookup2 (_text, _timeout, _flags) SocketLookup(_text, _timeout)
#define SocketRecv (_pSocket, pBuf, iLen, iFlags) SocketRecvfrom(_pSocket, pBuf, iLen, iFlags, NULL, 0)
Referenced by ProtoSSLRecv().
#define SocketSend (_pSocket, _pBuf, iLen, iFlags) SocketSendto(_pSocket, _pBuf, iLen, iFlags, NULL, 0)
Referenced by ProtoSSLSend().
#define SOCKLOOK_FLAGS_ALLOWXDNS (1)
#define SOCKLOOK_LOCALADDR "*"
Typedef Documentation
typedef struct HostentT HostentT
a host lookup structure – uses a callback system to determine when lookup has finished
typedef struct SocketSendCallbackEntryT SocketSendCallbackEntryT
socket send callback entry (internal use only - needs to be public for DirtyCast stress tester)
typedef int32_t(SocketSendCallbackT)(SocketT *pSocket, int32_t iType, const uint8_t *pData, int32_t iDataSize, const struct sockaddr *pTo, void *pCallref)
global socket send callback
typedef struct SocketT SocketT
Function Documentation
DIRTYCODE_API int32_t SockaddrCompare (struct sockaddr * addr1, struct sockaddr * addr2)
Compare two sockaddr structs and see if address is the same. This is different from simple binary compare because only relevent fields are checked.
Parameters
*addr1 - address #1
*addr2 - address to compare with address #1
Returns
int32_t - zero=no error, negative=error
Version
10/04/99 (GWS) First Version
Referenced by CommUDPConnect().
DIRTYCODE_API uint8_t SockaddrIn6IsIPv4 (const struct sockaddr * pSockAddr)
Identify if specified sockaddr is an IPv4-mapped IPv6 address.
Parameters
*pSockAddr - address to identify
Returns
uint8_t - TRUE if the address is IPv4-mapped, else FALSE
Version
04/12/2016 (jbrookes)
Referenced by SocketAddrMapAddress(), and SocketAddrMapTranslate().
DIRTYCODE_API uint8_t SockaddrIn6IsNAT64 (const struct sockaddr * pSockAddr)
Identify if specified sockaddr is a NAT64 IPv6 address.
Parameters
*pSockAddr - address to identify
Returns
uint8_t - TRUE if the address is NAT64, else FALSE
Version
04/12/2016 (jbrookes)
DIRTYCODE_API uint8_t SockaddrIn6IsZero (const struct sockaddr * pSockAddr)
Identify if specified sockaddr is zero (unspecified)
Parameters
*pSockAddr - address to identify
Returns
uint8_t - TRUE if the address is zero, else FALSE
Version
04/22/2016 (jbrookes)
Referenced by SocketAddrMapAddress().
DIRTYCODE_API char* SockaddrInGetAddrText (struct sockaddr * addr, char * str, int32_t len)
Return Internet address component of sockaddr struct in textual form (a.b.c.d).
Parameters
*addr - sockaddr struct
*str - address buffer
len - address length
Returns
char * - returns str on success, NULL on failure
Version
10/04/99 (GWS) First Version
Referenced by SocketInAddrGetText().
DIRTYCODE_API int32_t SockaddrInParse (struct sockaddr * sa, const char * pParse)
Convert textual internet address:port into sockaddr structure.
If the textual internet address:port is followed by a second :port, the second port
is optionally parsed into pPort2, if not NULL.
Parameters
*sa - sockaddr to fill in
*pParse - textual address
Returns
int32_t - flags: 0=parsed nothing 1=parsed addr 2=parsed port 3=parsed addr+port
Version
11/23/02 (GWS) First Version
References SockaddrInit, SockaddrInParse2(), SockaddrInSetAddr, and SockaddrInSetPort.
Referenced by CommTCPConnect(), and CommTCPListen().
DIRTYCODE_API int32_t SockaddrInParse2 (uint32_t * pAddr, int32_t * pPort, int32_t * pPort2, const char * pParse)
Convert textual internet address:port into sockaddr structure.
If the textual internet address:port is followed by a second :port, the second port
is optionally parsed into pPort2, if not NULL.
Parameters
*pAddr - address to fill in
*pPort - port to fill in
*pPort2 - second port to fill in
*pParse - textual address
Returns
int32_t - flags: 0=parsed nothing 1=parsed addr 2=parsed port 3=parsed addr+port 4=parsed port2
Version
11/23/02 (GWS) First Version
Referenced by CommSRPConnect(), CommSRPListen(), CommUDPConnect(), CommUDPListen(), and SockaddrInParse().
DIRTYCODE_API int32_t SockaddrInSetAddrText (struct sockaddr * addr, const char * s)
Set Internet address component of sockaddr struct from textual address (a.b.c.d).
Parameters
*addr - sockaddr structure
*s - textual address
Returns
int32_t - zero=no error, negative=error
Version
10/04/99 (GWS) First Version
Referenced by ProtoSSLConnect(), and SocketInTextGetAddr().
DIRTYCODE_API SocketT* SocketAccept (SocketT * pSocket, struct sockaddr * pAddr, int32_t * pAddrLen)
Accept an incoming connection attempt on a socket.
Parameters
*pSocket - socket reference to socket in listening state (see SocketListen())
*pAddr - pointer to storage for address of the connecting entity, or NULL
*pAddrLen - pointer to storage for length of address, or NULL
Returns
SocketT * - the accepted socket, or NULL if not available
Note
The integer pointed to by addrlen should on input contain the number of characters in the buffer addr. On exit it will contain the number of characters in the output address.
Version
10/04/1999 (gschaefer)
References SocketStateT::AddrMap, SocketT::iFamily, SocketT::iLastError, SocketT::iProto, SocketT::iType, NetPrintf, SockaddrInit, SockaddrInit6, SOCKERR_INVALID, SOCKERR_NONE, SocketAddrMapAddress(), SocketAddrMapTranslate(), and SocketT::uSocket.
Referenced by ProtoSSLAccept().
DIRTYCODE_API int32_t SocketBind (SocketT * pSocket, const struct sockaddr * pName, int32_t iNameLen)
Bind a local address/port to a socket.
Parameters
*pSocket - socket reference
*pName - local address/port
iNameLen - length of name
Returns
int32_t - standard network error code (SOCKERR_xxx)
Note
If either address or port is zero, then they are filled in automatically.
Version
10/04/1999 (gschaefer)
References SocketStateT::AddrMap, SocketStateT::aVirtualPorts, SocketT::bAsyncRecv, SocketT::bVirtual, ds_memcpy_s(), SocketStateT::hEvent, SocketT::iLastError, SocketStateT::iMemGroup, SocketT::iType, NetCritEnter(), NetCritLeave(), NetPrintf, SocketStateT::pMemGroupUserData, SocketT::pRecvQueue, SocketT::RecvCrit, SOCK_NOSEND, SockaddrInGetAddr, SockaddrInGetPort, SockaddrInSetAddr, SOCKERR_NONE, SOCKET_MAXVIRTUALPORTS, SocketAddrMapTranslate(), SocketNtohs(), SocketPacketQueueResize(), TRUE, SocketStateT::uAdapterAddress, SocketT::uSocket, and SocketT::uVirtualPort.
Referenced by CommSRPConnect(), CommSRPListen(), CommTCPListen(), CommUDPConnect(), ProtoAdvtConstruct(), ProtoSSLBind(), ProtoUdpBind(), ProtoUdpConnect(), SocketConnect(), and VoipConnectionStart().
DIRTYCODE_API int32_t SocketCallback (SocketT * pSocket, int32_t flags, int32_t timeout, void * ref, int32_t(*)(SocketT *pSocket, int32_t flags, void *ref) proc)
Referenced by CommSRPConnect(), CommSRPListen(), CommTCPConnect(), CommTCPListen(), ProtoAdvtConstruct(), and VoipConnectionStart().
DIRTYCODE_API int32_t SocketClose (SocketT * pSocket)
Close a socket. Performs a graceful shutdown of connection oriented protocols.
Parameters
*pSocket - socket reference
Returns
int32_t - zero
Version
10/04/1999 (gschaefer)
References TRUE.
Referenced by CommSRPDestroy(), CommSRPListen(), CommSRPUnconnect(), CommSRPUnlisten(), CommTCPDestroy(), CommTCPListen(), CommTCPUnconnect(), CommTCPUnlisten(), CommUDPConnect(), CommUDPDestroy(), CommUDPUnconnect(), CommUDPUnlisten(), ProtoAdvtDestroy(), ProtoPingDestroy(), ProtoSSLAccept(), ProtoSSLBind(), ProtoSSLDisconnect(), ProtoTunnelControl(), ProtoTunnelDestroy(), ProtoUdpDisconnect(), QosApiDestroy(), SocketDestroy(), VoipConnectionShutdown(), VoipConnectionStart(), and VoipTunnelDestroy().
DIRTYCODE_API int32_t SocketConnect (SocketT * pSocket, struct sockaddr * pName, int32_t iNameLen)
Initiate a connection attempt to a remote host.
Parameters
*pSocket - socket reference
*pName - pointer to name of socket to connect to
iNameLen - length of name
Returns
int32_t - standard network error code (SOCKERR_xxx)
Note
Only has real meaning for stream protocols. For a datagram protocol, this just sets the default remote host.
Version
10/04/1999 (gschaefer)
References SocketStateT::AddrMap, SocketT::bAsyncRecv, ds_memcpy_s(), SocketStateT::hEvent, SocketT::iLastError, SocketT::iOpened, SocketT::iVerbose, NetPrintfVerbose, SocketT::RemoteAddr, SockaddrInit6, SOCKERR_INVALID, SOCKERR_NONE, SocketAddrMapTranslate(), SocketBind(), and SocketT::uSocket.
Referenced by CommTCPConnect(), and ProtoSSLUpdate().
DIRTYCODE_API int32_t SocketControl (SocketT * pSocket, int32_t iOption, int32_t iData1, void * pData2, void * pData3)
Process a control message (type specific operation)
Parameters
*pSocket - socket to control, or NULL for module-level option
iOption - the option to pass
iData1 - message specific parm
*pData2 - message specific parm
*pData3 - message specific parm
Returns
int32_t - message specific result (-1=unsupported message, -2=no such module)
Note
iOption can be one of the following:
        'arcv' - set async receive enable/disable (default enabled for DGRAM/RAW, disabled for TCP)
        'conn' - handle connect message
        'disc' - handle disconnect message
        '+ip6' - add an IPv6 address into the mapping table and return a virtual IPv4 address to reference it
        '-ip6' - del an IPv6 address from the mapping table
        '~ip6' - remap an existing IPv6 address in the mapping table
        'keep' - set TCP keep-alive settings on PC (iData1=enable/disable, iData2=keep-alive time, iData3=keep-alive interval)
        'ladr' - set local address for subsequent SocketBind() operations (pc only)
        'maxp' - set max udp packet size
        'maxr' - set max recv rate (bytes/sec; zero=uncapped)
        'maxs' - set max send rate (bytes/sec; zero=uncapped)
        'nbio' - set nonblocking/blocking mode (TCP only, iData1=TRUE (nonblocking) or FALSE (blocking))
        'ndly' - set TCP_NODELAY state for given stream socket (iData1=zero or one)
        'pdev' - set simulated packet deviation
        'plat' - set simulated packet latency
        'plos' - set simulated packet loss
        'poll' - execute blocking wait on given socket list (pData2) or all sockets (pData2=NULL), 64 max sockets
        'pque' - set socket packet queue depth
        'push' - push data into given socket (iData1=size, pData2=data ptr, pData3=sockaddr ptr)
        'rbuf' - set socket recv buffer size
        'sbuf' - set socket send buffer size
        'scbk' - enable/disable "send callbacks usage" on specified socket (defaults to enable)
        'sdcb' - set/unset send callback (iData1=TRUE for set - FALSE for unset, pData2=callback, pData3=callref)
        'spam' - set debug level for debug output
        'vadd' - add a port to virtual port list
        'vdel' - del a port from virtual port list
Version
10/04/1999 (gschaefer)
References SocketStateT::AddrMap, SocketStateT::aSendCbEntries, SocketStateT::aVirtualPorts, SocketT::bAsyncRecv, SocketT::bSendCbs, CALLB_RECV, DS_MAX, FALSE, SocketStateT::hEvent, SocketT::iLastError, SocketStateT::iMaxPacket, SocketStateT::iMemGroup, SocketT::iPacketQueueResizePending, SocketT::iType, SocketT::iVerbose, SocketStateT::iVerbose, NetCritEnter(), NetCritLeave(), NetPrintf, NetPrintfVerbose, SocketT::pCallback, SocketT::pCallRef, SocketStateT::pMemGroupUserData, SocketT::pNext, SocketT::pRecvQueue, SocketSendCallbackEntryT::pSendCallback, SocketSendCallbackEntryT::pSendCallref, SocketStateT::pSockList, SocketT::RecvCrit, SocketT::RecvRate, SocketT::SendRate, SOCKERR_NONE, SOCKET_MAXUDPRECV, SOCKET_MAXVIRTUALPORTS, SocketAddrMapAddress(), SocketAddrRemapAddress(), SocketAddrUnmapAddress(), SocketPacketQueueAdd(), SocketPacketQueueControl(), SocketPacketQueueResize(), SocketSendCallbackAdd(), SocketSendCallbackRem(), TRUE, SocketStateT::uAdapterAddress, SocketT::uCallMask, SocketRateT::uMaxRate, and SocketT::uSocket.
Referenced by CommUDPControl(), NetConnControl(), ProtoSSLControl(), ProtoTunnelControl(), ProtoTunnelCreate(), and ProtoTunnelDestroy().
DIRTYCODE_API int32_t SocketCreate (int32_t iThreadPrio, int32_t iThreadStackSize, int32_t iThreadCpuAffinity)
Create new instance of socket interface module. Initializes all global resources and makes module ready for use.
Parameters
iThreadPrio - priority to start threads with
iThreadStackSize - stack size to start threads with (in bytes)
iThreadCpuAffinity - cpu affinity to start threads with
Returns
int32_t - negative=error, zero=success
Version
10/04/1999 (gschaefer)
References SocketStateT::AddrMap, DirtyMemAlloc(), DirtyMemGroupQuery(), DIRTYSDK_VERSION_MAJOR, DIRTYSDK_VERSION_MINOR, DIRTYSDK_VERSION_PATCH, DIRTYSDK_VERSION_SEASON, DIRTYSDK_VERSION_YEAR, SocketStateT::EventCrit, FALSE, SocketStateT::hEvent, SocketStateT::hRecvThread, SocketStateT::iMaxPacket, SocketStateT::iMemGroup, SocketStateT::iRecvLife, SocketStateT::iVerbose, SocketStateT::iVersion, NetCritInit(), NetIdleAdd(), NetLibCreate(), NetPrintf, NetPrintfVerbose, SocketStateT::pHostnameCache, SocketStateT::pMemGroupUserData, SOCKET_MAXUDPRECV, SOCKET_MEMID, SocketAddrMapInit(), SocketDestroy(), SocketHostnameCacheCreate(), and TRUE.
Referenced by NetConnStartup().
DIRTYCODE_API int32_t SocketDestroy (uint32_t uShutdownFlags)
Release resources and destroy module.
Parameters
uShutdownFlags - shutdown flags
Returns
int32_t - negative=error, zero=success
Version
10/04/1999 (gschaefer)
References SocketStateT::AddrMap, DirtyMemFree(), SocketStateT::EventCrit, SocketStateT::hEvent, SocketStateT::hRecvThread, SocketStateT::iMemGroup, SocketStateT::iRecvLife, NetCritKill(), NetIdleDel(), NetIdleDone(), NetLibDestroy(), NetPrintf, SocketStateT::pHostList, SocketStateT::pHostnameCache, SocketStateT::pMemGroupUserData, HostentT::pNext, SocketStateT::pSockList, SOCKET_MEMID, SocketAddrMapShutdown(), SocketClose(), SocketHostnameCacheDestroy(), and HostentT::thread.
Referenced by NetConnShutdown(), and SocketCreate().
DIRTYCODE_API uint32_t SocketGetLocalAddr (void)
Returns the "external" local address (ie, the address as a machine "out on the Internet" would see as the local machine's address).
Returns
uint32_t - local address
Version
07/28/2003 (jbrookes)
References SockaddrInGetAddr, SockaddrInSetAddr, SockaddrInSetPort, and SocketHost().
Referenced by ProtoPingCreate(), and SocketInfo().
DIRTYCODE_API int32_t SocketHost (struct sockaddr * pHost, int32_t iHostLen, const struct sockaddr * pDest, int32_t iDestLen)
Return the host address that would be used in order to communicate with the given destination address.
Parameters
*pHost - local sockaddr struct
iHostLen - length of structure (sizeof(host))
*pDest - remote sockaddr struct
iDestLen - length of structure (sizeof(dest))
Returns
int32_t - zero=success, negative=error
Version
10/04/1999 (gschaefer)
References ds_memcpy(), SocketStateT::iVersion, NetPrintf, SockaddrInGetAddr, SockaddrInSetAddr, and SocketStateT::uAdapterAddress.
Referenced by ProtoUdpGetLocalAddr(), and SocketGetLocalAddr().
DIRTYCODE_API uint32_t SocketHtonl (uint32_t addr)
Convert int32_t from host to network byte order.
Parameters
addr - value to convert
Returns
uint32_t - converted value
Version
10/04/99 (GWS) First Version
References ds_memcpy().
Referenced by NetGameDistServUpdate(), and VoipConnectionStart().
DIRTYCODE_API uint16_t SocketHtons (uint16_t addr)
Convert int16_t from host to network byte order.
Parameters
addr - value to convert
Returns
uint16_t - converted value
Version
1.0 10/04/99 (GWS) First Version
References ds_memcpy().
Referenced by SocketAddrMapTranslate(), SocketInfo(), and VoipConnectionStart().
DIRTYCODE_API SocketT* SocketImport (intptr_t uSockRef)
Import a socket. The given socket ref may be a SocketT, in which case a SocketT pointer to the ref is returned, or it can be an actual Sony socket ref, in which case a SocketT is created for the Sony socket ref.
Parameters
uSockRef - socket reference
Returns
SocketT * - pointer to imported socket, or NULL
Version
01/14/2005 (jbrookes)
References SocketT::LocalAddr, NetCritEnter(), NetCritLeave(), SocketT::pNext, SocketStateT::pSockList, SocketT::RemoteAddr, SocketInfo(), and SocketT::uImported.
DIRTYCODE_API char* SocketInAddrGetText (uint32_t addr, char * str, int32_t len)
Convert 32-bit internet address into textual form.
Parameters
addr - address
*str - [out] address buffer
len - address length
Returns
char * - returns str on success, NULL on failure
Version
06/17/2009 (jbrookes)
References SockaddrInGetAddrText(), and SockaddrInSetAddr.
Referenced by ProtoUpnpControl().
DIRTYCODE_API int32_t SocketInfo (SocketT * pSocket, int32_t iInfo, int32_t iData, void * pBuf, int32_t iLen)
Return information about an existing socket.
Parameters
*pSocket - socket reference
iInfo - selector for desired information
iData - selector specific
*pBuf - [out] return buffer
iLen - buffer length
Returns
int32_t - size of returned data or error code (negative value)
Note
iInfo can be one of the following:
        'addr' - return local address
        'conn' - who we are connecting to
        'bind' - return bind data (if pSocket == NULL, get socket bound to given port)
        'bndu' - return bind data (only with pSocket=NULL, get SOCK_DGRAM socket bound to given port)
        'ladr' - get local address previously specified by user for subsequent SocketBind() operations (pc only)
        'maxp' - return configured max packet size
        'maxr' - return configured max recv rate (bytes/sec; zero=uncapped)
        'maxs' - return configured max send rate (bytes/sec; zero=uncapped)
        'pdrp' - return socket packet queue number of packets dropped
        'peer' - peer info (only valid if connected)
        'pmax' - return socket packet queue max depth
        'ratr' - return current recv rate estimation (bytes/sec)
        'rats' - return current send rate estimation (bytes/sec)
        'sdcf' - get installed send callback function pointer (iData specifies index in array)
        'sdcu' - get installed send callback userdata pointer (iData specifies index in array)
        'serr' - last socket error
        'size' - return socket packet queue max size
        'sock' - return windows socket associated with the specified DirtySock socket
        'spam' - return debug level for debug output
        'stat' - TRUE if connected, else FALSE
        'virt' - TRUE if socket is virtual, else FALSE
Version
10/04/1999 (gschaefer)
References SocketStateT::AddrMap, SocketStateT::aSendCbEntries, SocketT::bVirtual, ds_memcpy(), SocketT::iLastError, SocketStateT::iMaxPacket, SocketT::iOpened, SocketT::iProto, SocketT::iType, SocketT::iVerbose, SocketStateT::iVerbose, NetCritEnter(), NetCritLeave(), NetPrintf, NetPrintfVerbose, SocketT::pNext, SocketT::pRecvQueue, SocketSendCallbackEntryT::pSendCallback, SocketSendCallbackEntryT::pSendCallref, SocketStateT::pSockList, SocketT::RecvCrit, SocketT::RecvRate, SocketT::SendRate, SockaddrInGetPort, SockaddrInit, SockaddrInSetAddr, SockaddrInSetPort, SOCKERR_CLOSED, SOCKERR_OTHER, SocketAddrMapAddress(), SocketGetLocalAddr(), SocketHtons(), SocketPacketQueueStatus(), SocketStateT::uAdapterAddress, SocketRateT::uCurRate, SocketRateT::uMaxRate, SocketT::uSocket, and SocketT::uVirtualPort.
Referenced by CommUDPConnect(), NetConnStatus(), NetGameLinkStatus(), ProtoSSLAccept(), ProtoSSLBind(), ProtoSSLStat(), ProtoSSLUpdate(), ProtoUdpGetLocalAddr(), SocketAddrMapAddress(), SocketAddrMapTranslate(), SocketHostnameAddRef(), SocketImport(), and VoipConnectionStart().
DIRTYCODE_API int32_t SocketInTextGetAddr (const char * pAddrText)
Convert textual internet address into 32-bit integer form.
Parameters
*pAddrText - textual address
Returns
int32_t - integer form
Version
11/23/02 (JLB) First Version
References SockaddrInGetAddr, and SockaddrInSetAddrText().
Referenced by SocketLookup().
DIRTYCODE_API int32_t SocketListen (SocketT * pSocket, int32_t iBackLog)
Start listening for an incoming connection on the socket. The socket must already be bound and a stream oriented connection must be in use.
Parameters
*pSocket - socket reference to bound socket (see SocketBind())
iBackLog - number of pending connections allowed
Returns
int32_t - standard network error code (SOCKERR_xxx)
Version
10/04/1999 (gschaefer)
References SocketT::iLastError, and SocketT::uSocket.
Referenced by CommTCPListen(), and ProtoSSLListen().
DIRTYCODE_API HostentT* SocketLookup (const char * pText, int32_t iTimeout)
Lookup a host by name and return the corresponding Internet address. Uses a callback/polling system since the socket library does not allow blocking.
Parameters
*pText - pointer to null terminated address string
iTimeout - number of milliseconds to wait for completion
Returns
HostentT * - hostent struct that includes callback vectors
Version
10/04/1999 (gschaefer)
References HostentT::addr, DirtyMemAlloc(), DirtyMemFree(), HostentT::done, HostentT::Done, ds_strnzcpy(), HostentT::Free, SocketStateT::iMemGroup, SocketStateT::iVerbose, HostentT::name, NetConnStatus(), NetPrintf, SocketStateT::pHostList, SocketStateT::pHostnameCache, SocketStateT::pMemGroupUserData, HostentT::refcount, SOCKET_MEMID, SocketHostnameAddRef(), SocketHostnameCacheGet(), SocketInTextGetAddr(), HostentT::thread, and TRUE.
Referenced by ProtoNameAsync(), and ProtoSSLConnect().
DIRTYCODE_API uint32_t SocketNtohl (uint32_t addr)
Convert int32_t from network to host byte order.
Parameters
addr - value to convert
Returns
uint32_t - converted value
Version
1.0 10/04/99 (GWS) First Version
References ds_memcpy().
Referenced by NetGameDistUpdate(), and VoipConnectionStart().
DIRTYCODE_API uint16_t SocketNtohs (uint16_t addr)
Convert int16_t from network to host byte order.
Parameters
addr - value to convert
Returns
uint16_t - converted value
Version
10/0/99 (GWS) First Version
References ds_memcpy().
Referenced by SocketAddrMapTranslate(), SocketBind(), and VoipConnectionStart().
DIRTYCODE_API SocketT* SocketOpen (int32_t iFamily, int32_t iType, int32_t iProto)
Create a new transfer endpoint. A socket endpoint is required for any data transfer operation.
Parameters
iFamily - address family (AF_INET)
iType - socket type (SOCK_STREAM, SOCK_DGRAM, SOCK_RAW, ...)
iProto - protocol type for SOCK_RAW (unused by others)
Returns
SocketT - socket reference
Version
10/04/1999 (gschaefer)
Referenced by CommSRPConnect(), CommSRPListen(), CommTCPConnect(), CommTCPListen(), CommUDPConnect(), CommUDPListen(), ProtoAdvtConstruct(), ProtoSSLBind(), ProtoSSLConnect(), ProtoUdpBind(), ProtoUdpConnect(), and VoipConnectionStart().
DIRTYCODE_API int32_t SocketRecvfrom (SocketT * pSocket, char * pBuf, int32_t iLen, int32_t iFlags, struct sockaddr * pFrom, int32_t * pFromLen)
Receive data from a remote host. If socket is a connected stream, then data can only come from that source. A datagram socket can receive from any remote host.
Parameters
*pSocket - socket reference
*pBuf - buffer to receive data
iLen - length of recv buffer
iFlags - unused
*pFrom - address data was received from (NULL=ignore)
*pFromLen - length of address
Returns
int32_t - positive=data bytes received, else standard error code
Version
10/04/1999 (gschaefer)
References SocketT::bAsyncRecv, SocketT::bRecvInp, SocketT::bVirtual, SocketStateT::hEvent, SocketT::iLastError, SocketT::iType, NetCritEnter(), NetCritLeave(), SocketT::pRecvQueue, SocketT::RecvCrit, SocketT::RecvRate, SOCKERR_CLOSED, SOCKERR_NONE, SocketPacketQueueStatus(), SocketRateThrottle(), and SocketRateUpdate().
Referenced by ProtoUdpUpdate().
DIRTYCODE_API void SocketRelease (SocketT * pSocket)
Release an imported socket.
Parameters
*pSocket - pointer to socket
Version
01/14/2005 (jbrookes)
References FALSE, and SocketT::uImported.
int32_t SocketSendCallbackInvoke (SocketSendCallbackEntryT aCbEntries[], SocketT * pSocket, int32_t iType, const char * pBuf, int32_t iLen, const struct sockaddr * pTo)
Invoke all send callbacks in specified collection. Only one of the callback is supposed to return "handled"... warn if not the case.
Parameters
aCbEntries - collection of callbacks to be invoked
pSocket - socket reference
iType - socket type
*pBuf - the data to be sent
iLen - size of data
*pTo - the address to send to (NULL=use connection address)
Returns
int32_t - 0 = send not handled; >0 = send successfully handled (bytes sent); <0 = send handled but failed (SOCKERR_XXX)
Version
07/18/2014 (mclouatre)
References NetPrintf, and SOCKET_MAXSENDCALLBACKS.
Referenced by SocketSendto().
DIRTYCODE_API int32_t SocketSendto (SocketT * pSocket, const char * pBuf, int32_t iLen, int32_t iFlags, const struct sockaddr * pTo, int32_t iToLen)
Send data to a remote host. The destination address is supplied along with the data. Should only be used with datagram sockets as stream sockets always send to the connected peer.
Parameters
*pSocket - socket reference
*pBuf - the data to be sent
iLen - size of data
iFlags - unused
*pTo - the address to send to (NULL=use connection address)
iToLen - length of address
Returns
int32_t - standard network error code (SOCKERR_xxx)
Version
10/04/1999 (gschaefer)
References SocketStateT::AddrMap, SocketStateT::aSendCbEntries, SocketT::bSendCbs, SocketT::iLastError, SocketT::iType, NetPrintf, SocketT::RemoteAddr, SocketT::SendRate, SockaddrInGetAddr, SockaddrInGetPort, SockaddrInit6, SOCKERR_INVALID, SocketAddrMapTranslate(), SocketRateThrottle(), SocketRateUpdate(), SocketSendCallbackInvoke(), and SocketT::uSocket.
Referenced by ProtoUdpSend(), and ProtoUdpSendTo().
DIRTYCODE_API int32_t SocketShutdown (SocketT * pSocket, int32_t iHow)
Perform partial/complete shutdown of socket indicating that either sending and/or receiving is complete.
Parameters
*pSocket - socket reference
iHow - SOCK_NOSEND and/or SOCK_NORECV
Returns
int32_t - zero
Version
10/04/1999 (gschaefer)
References SOCK_NORECV, SOCK_NOSEND, SocketT::uShutdown, and SocketT::uSocket.
Referenced by ProtoSSLDisconnect().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:34:36