DirtySock: hlbudapixenon.c File Reference
hlbudapixenon.c File Reference
This module implements High Level Buddy, an application level interface to Friends for Xenon. This is LARGELY stubbed out, as Xenon does not expose many Friends functions, and expect clients to use HUD.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <assert.h>
#include <xtl.h>
#include <xonline.h>
#include "DirtySDK/dirtysock.h"
#include "DirtySDK/dirtysock/dirtymem.h"
#include "DirtySDK/dirtysock/netconn.h"
#include "DirtySDK/util/displist.h"
#include "DirtySDK/util/hasher.h"
#include "DirtySDK/buddy/hlbudapi.h"
#include "DirtySDK/friend/friendapi.h"
Data Structures
struct HLBApiRefT
current module state
struct HLBBudT
Macros
#define true 1
#define false 0
#define HLBPrintf(x)
Functions
void _HLBRosterCallback (BuddyApiRefT *pLLRef, BuddyApiMsgT *pMsg, void *pUserData)
int32_t _HLBListGetIndexByName (HLBApiRefT *pApiRef, const char *name)
Given a buddy name, find the index into the list.
void _reloadFriends (HLBApiRefT *pApiRef)
HLBBudT * _updateFriendInRoster (HLBApiRefT *pApiRef, PXONLINE_FRIEND pFriend)
update friend in internal "roster" disp list – add if not there etc and return new buddy.
int32_t _XlateState (int32_t XOnlineState)
void _signalBuddyListChanged (HLBApiRefT *pApiRef)
int32_t _rosterCount (HLBApiRefT *pApiRef)
return count of low level roster list.
int32_t _countBuddies (HLBApiRefT *pApiRef, uint32_t flag)
void _RosterDestroy (HLBApiRefT *pApiRef)
int32_t HLBListCancelAllInvites (HLBApiRefT *pApiRef, const char *pName)
void HLBListDisableSorting (HLBApiRefT *pApiRef)
void _HLBEnableSorting (HLBApiRefT *pApiRef)
int32_t _HLBRosterSort (void *pSortref, int32_t iSortcon, void *pRecptr1, void *pRecptr2)
HLBApiRefT * _HLBApiInit (HLBApiRefT *pApiRef)
HLBApiRefT * HLBApiCreate (const char *pProduct, const char *pRelease, int32_t iRefMemGroup, void *pRefMemGroupUserData)
Create an instance of the High Level Buddy API.
HLBApiRefT * HLBApiCreate2 (BuddyMemAllocT *pAlloc, BuddyMemFreeT *pFree, const char *pProduct, const char *pRelease, int32_t iRefMemGroup, void *pRefMemGroupUserData)
Create HL Buddy Api, overriding the default memory alloc/free functions.
void HLBApiSetDebugFunction (HLBApiRefT *pApiRef, void *pDebugData, void(*pDebugProc)(void *pData, const char *pText))
Set a callback to write out debug messages within API.
void HLBApiOverrideXblIsSameProductCheck (HLBApiRefT *pApiRef, int32_t bDontUseXBLSameTitleIdCheck)
Set to 1 if on XBL and NTSC cannot play each other, but, have same title id.
void HLBApiOverrideMaxMessagesPerBuddy (HLBApiRefT *pApiRef, int32_t max_msgs_per_perm_buddy)
Application may override default for max msg per permanent buddy.
void HLBApiOverrideConstants (HLBApiRefT *pApiRef, int32_t bNoTextSupport, int32_t connect_timeout, int32_t op_timeout, int32_t max_perm_buddies, int32_t max_temp_buddies, int32_t max_msgs_allowed, int32_t bTalk_to_xbox, int32_t max_msg_len, int32_t bTrackSendMsgInOpState, int32_t iGameInviteAccept_timeout)
Application may override default constants. -1 leaves it as default. Only valid before HLBApiConfig is called.
void HLBApiSetUtf8TransTbl (HLBApiRefT *pApiRef, Utf8TransTblT *pTransTbl)
Set if want api to translate utf8 chars to 8 bit characters in Presence, and Message Text.
int32_t HLBApiInitialize (HLBApiRefT *pApiRef, const char *prodPresence, uint32_t uLocality)
Configure and initialize any data structures in the API, and set some basic product and presence info.
int32_t HLBApiConnect (HLBApiRefT *pApiRef, const char *pServer, int32_t port, const char *key, const char *pRsrc)
Not needed for Xenon. Creating API connect to XDK as well.
int32_t HLBApiRegisterConnectCallback (HLBApiRefT *pApiRef, HLBOpCallbackT *cb, void *pContext)
int32_t HLBApiGetConnectState (HLBApiRefT *pApiRef)
Get state of connection to the server, returns int32_t, but see HLBConnectState_Enum.
void HLBApiDisconnect (HLBApiRefT *pApiRef)
Disconnect from buddy server.
void HLBApiDestroy (HLBApiRefT *pApiRef)
Destroy this API and any memory held by it. Also destroy lower level BuddyApi held by this.
void HLBApiUpdate (HLBApiRefT *pApiRef)
Give API and api below some time to process. Must be called periodically by client.
int32_t HLBApiSuspend (HLBApiRefT *pApiRef)
Free up buddy memory,and stop enumerating, while client goes in game.
void * HLBApiResume (HLBApiRefT *pApiRef)
Reconnect after being in game.
int32_t HLBApiGetLastOpStatus (HLBApiRefT *pApiRef)
State of last operation –implies only one operation at a time. NOT FOR XENON ***.
void HLBApiCancelOp (HLBApiRefT *pApiRef)
NOT FOR XENON.
int32_t HLBApiFindUsers (HLBApiRefT *pApiRef, const char *pName, HLBOpCallbackT *pOpCallback, void *context)
NOT FOR XENON ***.
BuddyApiUserT * HLBApiUserFound (HLBApiRefT *pApiRef, int32_t iItem)
NOT FOR XENON ***.
int32_t HLBApiRegisterNewMsgCallback (HLBApiRefT *pApiRef, HLBMsgCallbackT *pMsgCallback, void *pAppData)
Register callback for new (chat) messages. NOT FOR XENON ***.
int32_t HLBApiRegisterBuddyChangeCallback (HLBApiRefT *pApiRef, HLBOpCallbackT *pListCallback, void *pAppData)
Register callback for any buddy list (aka roster) change.
int32_t HLBApiRegisterGameInviteCallback (HLBApiRefT *pApiRef, HLBBudActionCallbackT *pActionCallback, void *pAppData)
Informs caller when Cross Game Invite activity happens. Not neeeded if polling. Local. NOT FOR XENON ***.
int32_t HLBApiRegisterBuddyPresenceCallback (HLBApiRefT *pApiRef, HLBPresenceCallbackT *pPresCallback, void *pAppData)
Register callback for when buddy presence changes–state or text can change.
char * HLBBudGetName (HLBBudT *pBuddy)
Return screen/persona name of this buddy.
uint64_t HLBBudGetXenonXUID (HLBBudT *pBuddy)
Return XUID of buddy –Xenon only!
int32_t HLBBudIsTemporary (HLBBudT *pBuddy)
NOT FOR XENON ***.
int32_t HLBBudIsBlocked (HLBBudT *pBuddy)
Indicates if messages from this 'buddy' is ignored NOT FOR XENON ***.
int32_t HLBBudIsWannaBeMyBuddy (HLBBudT *pBuddy)
int32_t HLBBudIsIWannaBeHisBuddy (HLBBudT *pBuddy)
char * HLBBudGetTitle (HLBBudT *pBuddy)
Return Title played name by this buddy, NOT FOR XENON ***.
int32_t HLBBudTempBuddyIs (HLBBudT *pBuddy, int32_t tempBuddyType)
Is this buddy one of these temp buddy kinds – can be true for permanent buddies too.
int32_t HLBBudIsRealBuddy (HLBBudT *pBuddy)
Indicates if the buddy is really a buddy – ie. not someone on the list due to being blocked, or added temporarily.
int32_t HLBBudIsInGroup (HLBBudT *pBuddy)
NOT FOR XENON ***.
int32_t HLBBudGetState (HLBBudT *pBuddy)
Return buddy's state, such as is online, disconnected, in game etc. – see HLB_Buddy_State_Enum.
int32_t HLBBudIsPassive (HLBBudT *pBuddy)
Indicate if buddy is passive i.e. is online but playing a game.
int32_t HLBBudIsAvailableForChat (HLBBudT *pBuddy)
Indicate if buddy is online and available for chat.
int32_t HLBBudIsSameProduct (HLBBudT *pBuddy)
NOT FOR XENON ***.
void HLBBudGetPresence (HLBBudT *pBuddy, char *strPresence)
NOT FOR XENON ***.
void HLBBudGetPresenceExtra (HLBBudT *pBuddy, char *strExtraPres, int32_t iStrSize)
NOT FOR XENON ***.
int32_t HLBBudIsNoReplyBud (HLBBudT *pBuddy)
NOT FOR XENON ***.
int32_t HLBBudIsJoinable (HLBBudT *pBuddy)
Indicates if buddy can be "joined" (aka found and gone to) in an Xbox game. Checks the Joinable bit in Xbox Presence.
int32_t HLBBudGetVOIPState (HLBBudT *pBuddy)
NOT FOR XENON ***.
int32_t HLBBudCanVoiceChat (HLBBudT *pBuddy)
Indicates if buddy is ready to be talked to. i.e. plugged in, and in same product etc.
int32_t HLBBudJoinGame (HLBBudT *pBuddy, HLBOpCallbackT *cb, void *pContext)
BuddyApiMsgT * HLBMsgListGetMsgByIndex (HLBBudT *pBuddy, int32_t index, int32_t read)
Get message at index position, if read is true, mark message as read.
BuddyApiMsgT * HLBMsgListGetFirstUnreadMsg (HLBBudT *pBuddy, int32_t startPos, int32_t read)
NOT FOR XENON ***.
void HLBMsgListGetMsgText (HLBApiRefT *pApiRef, BuddyApiMsgT *pMsg, char *strText, int32_t iLen)
NOT FOR XENON.
int32_t HLBMsgListGetUnreadCount (HLBBudT *pBuddy)
NOT FOR XENON.
int32_t HLBMsgListGetTotalCount (HLBBudT *pBuddy)
NOT FOR XENON.
void HLBMsgListDelete (HLBBudT *pBuddy, int32_t index)
NOT FOR XENON.
void HLBMsgListDeleteAll (HLBBudT *pBuddy, int32_t bZapReadOnly)
NOT FOR XENON.
HLBBudT * HLBListGetBuddyByName (HLBApiRefT *pApiRef, const char *name)
Get a buddy from the buddy list (roster) by name. Exact match.
HLBBudT * HLBListGetBuddyByIndex (HLBApiRefT *pApiRef, int32_t index)
Get a Buddy by index into the buddy list.
int32_t HLBListGetBuddyCount (HLBApiRefT *pApiRef)
Get count of all buddies in the Roster. Also see HLBListGetBuddyCountByFlags.
int32_t HLBListGetBuddyCountByFlags (HLBApiRefT *pApiRef, uint32_t uTypeFlag)
Get count of buddies that match **** NOT FOR XENON ***.
int32_t HLBListBlockBuddy (HLBApiRefT *pApiRef, const char *name, HLBOpCallbackT *cb, void *context)
NOT FOR XENON.
int32_t HLBListUnBlockBuddy (HLBApiRefT *pApiRef, const char *name, HLBOpCallbackT *cb, void *context)
No longer Ignore this buddy. NOT FOR XENON.
int32_t HLBListUnMakeBuddy (HLBApiRefT *pApiRef, const char *name, HLBOpCallbackT *cb, void *context)
Ensure user is no longer a buddy of mine. NOT FOR XENON.
int32_t HLBListInviteBuddy (HLBApiRefT *pApiRef, const char *name, HLBOpCallbackT *cb, void *pContext)
Ask this use to be my buddy. NOT FOR XENON.
int32_t HLBListAnswerInvite (HLBApiRefT *pApiRef, const char *name, int32_t eInviteAction, HLBOpCallbackT *cb, void *pContext)
Respond to an invite or change state- NOT FOR XENON.
int32_t HLBListAnswerGameInvite (HLBApiRefT *pApiRef, const char *name, int32_t eInviteAction, HLBOpCallbackT *cb, void *pContext)
Respond to an invite NOT FOR XENON.
int32_t HLBListCancelGameInvite (HLBApiRefT *pApiRef, HLBOpCallbackT *cb, void *pContext)
Cancel any game invites I sent - NOT FOR XENON.
int32_t HLBListGameInviteBuddy (HLBApiRefT *pApiRef, const char *name, const char *pGameInviteState, HLBOpCallbackT *cb, void *pContext)
int32_t HLBListFlagTempBuddy (HLBApiRefT *pApiRef, const char *name, int32_t buddyType)
Add as a tourney or other temp buddy for convenience. NOT FOR XENON.
int32_t HLBListUnFlagTempBuddy (HLBApiRefT *pApiRef, const char *name, int32_t tempBuddyType)
Clear the particular temp buddy flag if set. NOT FOR XENON.
int32_t HLBListDeleteTempBuddy (HLBApiRefT *pApiRef, const char *name)
NOT FOR XENON ***.
void HLBListSetSortFunction (HLBApiRefT *pApiRef, HLBRosterSortFunctionT *sortCallbackFunction)
Sort function to be set if client wants custom sort of buddy list – However API will have a reasonable default sort.
int32_t HLBListSort (HLBApiRefT *pApiRef)
Sort list of buddies. Once sorted, list will be frozen until re-sorted, or provide a freeze() call.
int32_t HLBListChanged (HLBApiRefT *pApiRef)
Has the list of buddies or their presence changed? Will clear the flag. Local.
int32_t HLBListBuddyWithMsg (HLBApiRefT *pApiRef)
Has messages from any buddies changed? NOT FOR XENON.
int32_t HLBListDeleteTempBuddies (HLBApiRefT *pApiRef)
On closing screen, need to clear temp buddies w/o messages. NOT FOR XENON.
int32_t HLBListAddToGroup (HLBApiRefT *pApiRef, const char *buddyName)
Add user to group to whom i will send a common msg.
int32_t HLBListRemoveFromGroup (HLBApiRefT *pApiRef, const char *buddyName)
Remove this buddy from the group Iam going to send messages to. NOT FOR XENON.
int32_t HLBListClearGroup (HLBApiRefT *pApiRef)
Clear group of users so I can re-use it. NOT FOR XENON.
int32_t HLBListSendMsgToGroup (HLBApiRefT *pApiRef, int32_t msgType, const char *msg, int32_t bClearGroup, HLBOpCallbackT *cb, void *pContext)
Send message to group of users I created earlier. NOT FOR XENON.
void HLBApiPresenceDiff (HLBApiRefT *pApiRef, const char *globalPres)
Set presence for other products, in appropriate language. NOT FOR XENON.
void HLBApiPresenceSame (HLBApiRefT *pApiRef, int32_t iPresState, const char *strSamePres)
Set presence my presence state and presence string for this product NOT FOR XENON.
int32_t HLBApiPresenceJoinable (HLBApiRefT *pApiRef, int32_t bOn, int32_t bSendImmediate)
NOT FOR XENON ***.
void HLBApiPresenceExtra (HLBApiRefT *pApiRef, const char *strExtraPres)
int32_t HLBApiPresenceOffline (HLBApiRefT *pApiRef, int32_t bOnOff)
Set presence as "Offline" if OnOff is true. NOT FOR XENON.
int32_t HLBApiPresenceSend (HLBApiRefT *pApiRef, int32_t iBuddyState, int32_t iVOIPState, const char *gamePres, int32_t waitMsecs)
Send presence msg. NOT FOR XENON.
int32_t HLBApiPresenceVOIPSend (HLBApiRefT *pApiRef, int32_t iVOIPState)
NOT FOR XENON ***.
int32_t HLBApiPresenceSendSetPresence (HLBApiRefT *pApiRef)
NOT FOR XENON ***.
int32_t HLBListSendChatMsg (HLBApiRefT *pApiRef, const char *name, const char *msg, HLBOpCallbackT *cb, void *pContext)
Send an actual chat message.
int32_t HLBApiSetEmailForwarding (HLBApiRefT *pApiRef, int32_t bEnable, const char *strEmail, HLBOpCallbackT *pOpCallback, void *pCalldata)
Turn email forwarding on or off **** NOT FOR XENON ***.
int32_t HLBApiGetEmailForwarding (HLBApiRefT *pApiRef, int32_t *bEnable, char *strEmail)
Get email forwarding state, **** NOT FOR XENON ***.
uint32_t HLBBudGetGameInviteFlags (HLBBudT *pBuddy)
int32_t HLBApiSetUserIndex (HLBApiRefT *pApiRef, int32_t iIndex)
int32_t HLBApiGetUserIndex (HLBApiRefT *pApiRef)
int32_t HLBApiGetTitleName (HLBApiRefT *pApiRef, const uint32_t uTitleId, const int32_t iBufSize, char *pTitleName)
Get the " Official" Xbox title name for a given title. XBOX ONLY. pLang ignored.
int32_t HLBApiGetMyTitleName (HLBApiRefT *pApiRef, const char *pLang, const int32_t iBufSize, char *pTitleName)
Get the " Official" Title name for this title. pLang ignored – defaults to English.
int32_t HLBListSetGameInviteSessionID (HLBApiRefT *pApiRef, const char *sSessionID)
int32_t HLBListGetGameSessionID (HLBApiRefT *pApiRef, const char *name, char *sSessionID, const int32_t iBufSize)
Detailed Description
This module implements High Level Buddy, an application level interface to Friends for Xenon. This is LARGELY stubbed out, as Xenon does not expose many Friends functions, and expect clients to use HUD.
Attention
Copyright (c) Electronic Arts 2005. ALL RIGHTS RESERVED.
Macro Definition Documentation
#define false 0
#define HLBPrintf (x)
Referenced by _reloadFriends(), _updateFriendInRoster(), HLBApiRegisterBuddyChangeCallback(), and HLBApiRegisterBuddyPresenceCallback().
#define true 1
Function Documentation
int32_t _countBuddies (HLBApiRefT * pApiRef, uint32_t flag)
References _rosterCount().
Referenced by HLBListGetBuddyCount(), and HLBListGetBuddyCountByFlags().
HLBApiRefT* _HLBApiInit (HLBApiRefT * pApiRef)
References _HLBRosterSort(), DirtyMemGroupEnter(), DirtyMemGroupLeave(), DispListCreate(), HasherCreate(), HLBApiConnect(), HLBUDAPI_MEMID, HLBApiRefT::iMemGroup, NetConnStatus(), NetPrintf, NULL, HLBApiRefT::pBuddyFree, HLBApiRefT::pBuddySortFunc, HLBApiRefT::pDisp, HLBApiRefT::pHash, and HLBApiRefT::pMemGroupUserData.
Referenced by HLBApiCreate(), HLBApiCreate2(), and HLBApiResume().
void _HLBEnableSorting (HLBApiRefT * pApiRef)
References DispListChange(), DispListOrder(), DispListSort(), NULL, HLBApiRefT::pBuddySortFunc, and HLBApiRefT::pDisp.
int32_t _HLBListGetIndexByName (HLBApiRefT * pApiRef, const char * name)
Given a buddy name, find the index into the list.
Parameters
*pApiRef - API reference pointer
*name - name
Returns
int32_t - index to buddy; negative value (HLB_ERROR_MISSING) if not there.
References ds_stricmp(), HLB_ERROR_MISSING, HLBListGetBuddyByIndex(), HLBListGetBuddyCount(), and NULL.
Referenced by HLBListGetBuddyByName().
void _HLBRosterCallback (BuddyApiRefT * pLLRef, BuddyApiMsgT * pMsg, void * pUserData)
int32_t _HLBRosterSort (void * pSortref, int32_t iSortcon, void * pRecptr1, void * pRecptr2)
References BUDDY_STAT_CHAT, ds_stricmp(), HLBBudGetState(), BuddyRosterT::pUserRef, and BuddyRosterT::strUser.
Referenced by _HLBApiInit().
void _reloadFriends (HLBApiRefT * pApiRef)
References _updateFriendInRoster(), BUDDYAPI_MEMID, DispListCount(), DispListDel(), FRIENDAPI_MAX_FRIENDS, HashStrDel(), HashStrFind(), HLBListGetBuddyByIndex(), HLBPrintf, HLBApiRefT::iMemGroup, HLBApiRefT::iUserIndex, NULL, HLBApiRefT::pBuddyFree, HLBApiRefT::pDisp, HLBApiRefT::pHash, and HLBApiRefT::pMemGroupUserData.
Referenced by HLBApiSetUserIndex().
int32_t _rosterCount (HLBApiRefT * pApiRef)
return count of low level roster list.
References DispListCount(), NULL, and HLBApiRefT::pDisp.
Referenced by _countBuddies().
void _RosterDestroy (HLBApiRefT * pApiRef)
References DispListDel(), DispListDestroy(), HasherDestroy(), HasherFlush(), HLBUDAPI_MEMID, HLBApiRefT::iMemGroup, NULL, HLBApiRefT::pBuddyFree, HLBApiRefT::pDisp, HLBApiRefT::pHash, and HLBApiRefT::pMemGroupUserData.
Referenced by HLBApiDestroy(), and HLBApiSuspend().
void _signalBuddyListChanged (HLBApiRefT * pApiRef)
References HLB_ERROR_NONE, HLB_OP_LOAD, HLBApiRefT::pListData, HLBApiRefT::pListProc, and HLBApiRefT::rosterDirty.
HLBBudT * _updateFriendInRoster (HLBApiRefT * pApiRef, PXONLINE_FRIEND pFriend)
update friend in internal "roster" disp list – add if not there etc and return new buddy.
References DispListAdd(), DispListGet(), ds_memcpy_s(), ds_strnzcpy(), HashStrAdd(), HashStrFind(), HLBPrintf, HLBUDAPI_MEMID, HLBApiRefT::iMemGroup, NULL, HLBApiRefT::pBuddyAlloc, HLBApiRefT::pDisp, HLBApiRefT::pHash, and HLBApiRefT::pMemGroupUserData.
Referenced by _reloadFriends().
int32_t _XlateState (int32_t XOnlineState)
References BUDDY_STAT_AWAY, BUDDY_STAT_CHAT, BUDDY_STAT_DISC, and BUDDY_STAT_PASS.
Referenced by HLBBudGetState().
int32_t HLBListDeleteTempBuddies (HLBApiRefT * pApiRef)
On closing screen, need to clear temp buddies w/o messages. NOT FOR XENON.
References HLB_ERROR_UNSUPPORTED.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:55