DirtySock: voipconduit.h File Reference
voipconduit.h File Reference
VoIP data packet definitions.
Typedefs
typedef struct VoipConduitRefT VoipConduitRefT
conduit manager module state
Functions
VoipConduitRefT * VoipConduitCreate (int32_t iMaxConduits)
Create voice conduit manager.
void VoipConduitSetMixer (VoipConduitRefT *pConduitRef, VoipMixerRefT *pMixerRef)
Assign a mixer to the conduit.
void VoipConduitDestroy (VoipConduitRefT *pConduitRef)
Destroy voice conduit manager.
void VoipConduitReceiveVoiceData (VoipConduitRefT *pConduitRef, VoipUserT *pRemoteUser, const uint8_t *pData, int32_t iDataSize)
Receive voice data, and send it to the mixer.
void VoipConduitRegisterUser (VoipConduitRefT *pConduitRef, VoipUserT *pRemoteUser, uint32_t bRegister)
Register/unregister a remote user with the conduit manager.
int32_t VoipConduitControl (VoipConduitRefT *pConduitRef, int32_t iControl, int32_t iValue, void *pValue)
Control function.
Detailed Description
VoIP data packet definitions.
Attention
Copyright (c) Electronic Arts 2004. ALL RIGHTS RESERVED.
Version
07/29/2004 (jbrookes) Split from voipheadset
12/01/2009 (jbrookes) voipchannel->voipconduit; avoid name clash with new API
Typedef Documentation
typedef struct VoipConduitRefT VoipConduitRefT
conduit manager module state
Function Documentation
int32_t VoipConduitControl (VoipConduitRefT * pConduitRef, int32_t iControl, int32_t iValue, void * pValue)
Control function.
Parameters
*pConduitRef - pointer to conduit manager
iControl - control selector
iValue - control value
*pValue - control value
Returns
int32_t - selector specific, or -1 if no such selector
Note
iControl can be one of the following:
    'spam' - set the debug level
Version
06/03/2016 (amakoukji)
References VoipConduitRefT::iVerbosity.
Referenced by VoipHeadsetControl().
VoipConduitRefT* VoipConduitCreate (int32_t iMaxConduits)
Create voice conduit manager.
Parameters
iMaxConduits - number of conduits to support
Returns
VoipConduitRefT * - pointer to module state, or NULL if an error occurred
Version
07/29/2004 (jbrookes) Split from voipheadset.c
References DirtyMemAlloc(), VoipConduitRefT::iNumConduits, VOIP_MEMID, and VoipMemGroupQuery().
Referenced by VoipHeadsetCreate().
void VoipConduitDestroy (VoipConduitRefT * pConduitRef)
Destroy voice conduit manager.
Parameters
*pConduitRef - pointer to conduit manager
Version
07/29/2004 (jbrookes)
References DirtyMemFree(), VOIP_MEMID, and VoipMemGroupQuery().
Referenced by VoipHeadsetDestroy().
void VoipConduitReceiveVoiceData (VoipConduitRefT * pConduitRef, VoipUserT * pRemoteUser, const uint8_t * pData, int32_t iDataSize)
Receive voice data, and send it to the mixer.
Parameters
*pConduitRef - pointer to conduit manager
*pRemoteUser - user data came from
*pData - incoming voice data packet
iDataSize - voice data size
Version
03/21/2004 (jbrookes)
References VoipConduitRefT::Conduits, VoipConduitRefT::iNumConduits, VoipConduitRefT::iVerbosity, NetPrintf, NetPrintfVerbose, VoipConduitT::PacketUser, VoipConduitRefT::pMixerRef, VoipUserT::strUserId, VOIP_ConduitName, VOIP_SameUser, and VoipMixerAccumulate().
Referenced by VoipHeadsetReceiveVoiceDataCb().
void VoipConduitRegisterUser (VoipConduitRefT * pConduitRef, VoipUserT * pRemoteUser, uint32_t bRegister)
Register/unregister a remote user with the conduit manager.
Parameters
*pConduitRef - pointer to conduit manager
*pRemoteUser - remote user
bRegister - if TRUE, register user, else unregister user.
Version
03/21/2004 (jbrookes)
References VoipConduitRefT::Conduits, VoipConduitRefT::iNumConduits, NetPrintf, VoipConduitT::PacketUser, VoipUserT::strUserId, VOIP_ClearUser, VOIP_ConduitName, VOIP_CopyUser, VOIP_NullUser, and VOIP_SameUser.
Referenced by VoipHeadsetRegisterUserCb().
void VoipConduitSetMixer (VoipConduitRefT * pConduitRef, VoipMixerRefT * pMixerRef)
Assign a mixer to the conduit.
Parameters
*pConduitRef - pointer to conduit manager
*pMixerRef - pointer to mixer to assign
Version
10/26/2011 (jbrookes)
References VoipConduitRefT::pMixerRef.
Referenced by VoipHeadsetCreate().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:47