DirtySock: ProtoTunnel
ProtoTunnel
Proto
Data Structures
struct ProtoTunnelInfoT
map description
struct ProtoTunnelStatT
tunnel statistics
Macros
#define PROTOTUNNEL_VERSION_1_0 (0x0100)
#define PROTOTUNNEL_VERSION_1_1 (0x0101)
#define PROTOTUNNEL_MAXPORTS (8)
maximum number of ports that can be mapped to a tunnel
#define PROTOTUNNEL_PORTFLAG_ENCRYPTED (1)
port flag indicating data is encrypted
#define PROTOTUNNEL_PORTFLAG_AUTOFLUSH (2)
#define PROTOTUNNEL_MAXKEYLEN (128)
max key length
Typedefs
typedef enum ProtoTunnelEventE ProtoTunnelEventE
tunnel event types
typedef enum ProtoTunnelModeE ProtoTunnelModeE
tunnel modes
typedef struct ProtoTunnelInfoT ProtoTunnelInfoT
map description
typedef struct ProtoTunnelStatT ProtoTunnelStatT
tunnel statistics
typedef struct ProtoTunnelRefT ProtoTunnelRefT
opaque module ref
typedef void(ProtoTunnelCallbackT)(ProtoTunnelRefT *pProtoTunnel, ProtoTunnelEventE eEvent, const char *pData, int32_t iDataSize, struct sockaddr *pRecvAddr, void *pUserData)
prototunnel event callback
typedef int32_t(RawRecvCallbackT)(SocketT *pSocket, uint8_t *pData, int32_t iRecvLen, const struct sockaddr *pFrom, int32_t iFromLen, void *pUserData)
raw inbound data receive callback (shall return 1 if it swallows the data, 0 otherwise)
Enumerations
enum ProtoTunnelEventE {
PROTOTUNNEL_EVENT_RECVNOMATCH,
PROTOTUNNEL_NUMEVENTS
}
tunnel event types
enum ProtoTunnelModeE {
PROTOTUNNEL_MODE_GENERIC,
PROTOTUNNEL_MODE_XENON,
PROTOTUNNEL_MODE_NOCRYPT
}
tunnel modes
Functions
DIRTYCODE_API ProtoTunnelRefT * ProtoTunnelCreate (int32_t iMaxTunnels, int32_t iTunnelPort)
Create the ProtoTunnel module.
DIRTYCODE_API void ProtoTunnelDestroy (ProtoTunnelRefT *pProtoTunnel)
Destroy the ProtoTunnel module.
DIRTYCODE_API void ProtoTunnelCallback (ProtoTunnelRefT *pProtoTunnel, ProtoTunnelCallbackT *pCallback, void *pUserData)
Set event callback.
DIRTYCODE_API int32_t ProtoTunnelAlloc (ProtoTunnelRefT *pProtoTunnel, ProtoTunnelInfoT *pInfo, const char *pKey)
Allocate a tunnel.
DIRTYCODE_API uint32_t ProtoTunnelFree (ProtoTunnelRefT *pProtoTunnel, uint32_t uTunnelId, const char *pKey)
Free a tunnel.
DIRTYCODE_API uint32_t ProtoTunnelFree2 (ProtoTunnelRefT *pProtoTunnel, uint32_t uTunnelId, const char *pKey, uint32_t uAddr)
Free a tunnel. Same as ProtoTunnelFree but takes an IP address. Used on 360 to allow ProtoTunnel to maintain a list of secure IP addresses for sending. When refcounting down a tunnel, the current secure IP address will be replaced by another valid one, reaching the same peer.
DIRTYCODE_API int32_t ProtoTunnelUpdatePortList (ProtoTunnelRefT *pProtoTunnel, uint32_t uTunnelId, ProtoTunnelInfoT *pInfo)
Updates the port list for the given tunnel. Port and port flag info is copied over from the specified info structure if the port value is non- zero.
DIRTYCODE_API int32_t ProtoTunnelStatus (ProtoTunnelRefT *pProtoTunnel, int32_t iSelect, int32_t iValue, void *pBuf, int32_t iBufSize)
Get module status.
DIRTYCODE_API int32_t ProtoTunnelControl (ProtoTunnelRefT *pProtoTunnel, int32_t iControl, int32_t iValue, int32_t iValue2, const void *pValue)
Control the module.
DIRTYCODE_API void ProtoTunnelUpdate (ProtoTunnelRefT *pProtoTunnel)
Update the module.
DIRTYCODE_API int32_t ProtoTunnelRawSendto (ProtoTunnelRefT *pProtoTunnel, const char *pBuf, int32_t iLen, const struct sockaddr *pTo, int32_t iToLen)
Send data to a remote host over the prototunnel socket. The destination address is supplied along with the data. Important: remote host shall not be expecting tunneled data because that function bypasses all the tunneling logic on the sending side.
Detailed Description
Macro Definition Documentation
#define PROTOTUNNEL_MAXKEYLEN (128)
max key length
#define PROTOTUNNEL_MAXPORTS (8)
maximum number of ports that can be mapped to a tunnel
Referenced by ProtoTunnelAlloc(), and ProtoTunnelUpdatePortList().
#define PROTOTUNNEL_PORTFLAG_AUTOFLUSH (2)
#define PROTOTUNNEL_PORTFLAG_ENCRYPTED (1)
port flag indicating data is encrypted
Referenced by ProtoTunnelAlloc().
#define PROTOTUNNEL_VERSION_1_0 (0x0100)
Referenced by ProtoTunnelAlloc().
#define PROTOTUNNEL_VERSION_1_1 (0x0101)
Typedef Documentation
typedef void(ProtoTunnelCallbackT)(ProtoTunnelRefT *pProtoTunnel, ProtoTunnelEventE eEvent, const char *pData, int32_t iDataSize, struct sockaddr *pRecvAddr, void *pUserData)
prototunnel event callback
typedef enum ProtoTunnelEventE ProtoTunnelEventE
tunnel event types
typedef struct ProtoTunnelInfoT ProtoTunnelInfoT
map description
typedef enum ProtoTunnelModeE ProtoTunnelModeE
tunnel modes
typedef struct ProtoTunnelRefT ProtoTunnelRefT
opaque module ref
typedef struct ProtoTunnelStatT ProtoTunnelStatT
tunnel statistics
typedef int32_t(RawRecvCallbackT)(SocketT *pSocket, uint8_t *pData, int32_t iRecvLen, const struct sockaddr *pFrom, int32_t iFromLen, void *pUserData)
raw inbound data receive callback (shall return 1 if it swallows the data, 0 otherwise)
Enumeration Type Documentation
enum ProtoTunnelEventE
tunnel event types
Enumerator
PROTOTUNNEL_EVENT_RECVNOMATCH
data received from source with no tunnel mapping
PROTOTUNNEL_NUMEVENTS
total number of events
enum ProtoTunnelModeE
tunnel modes
Enumerator
PROTOTUNNEL_MODE_GENERIC
generic implementation with encryption
PROTOTUNNEL_MODE_XENON
xenon-specific implementation, no encryption
PROTOTUNNEL_MODE_NOCRYPT
generic implementation with no encryption
Function Documentation
DIRTYCODE_API int32_t ProtoTunnelAlloc (ProtoTunnelRefT * pProtoTunnel, ProtoTunnelInfoT * pInfo, const char * pKey)
Allocate a tunnel.
Parameters
*pProtoTunnel - pointer to module state
*pInfo - tunnel info
*pKey - encryption key for tunnel
Returns
int32_t - negative=error, else allocated tunnel id
Version
12/07/2005 (jbrookes)
References ProtoTunnelT::aHmacKey, ProtoTunnelT::aKeyList, ProtoTunnelInfoT::aPortFlags, ProtoTunnelInfoT::aRemotePortList, ProtoTunnelT::bSendCtrlInfo, CryptArc4Apply(), CryptArc4Init(), ProtoTunnelT::CryptRecvState, ProtoTunnelT::CryptSendState, ds_memcpy_s(), ds_strnzcpy(), ProtoTunnelRefT::iMaxTunnels, ProtoTunnelT::Info, NetCritEnter(), NetCritInit(), NetCritLeave(), NetPrintf, NetTick(), ProtoTunnelT::PacketCrit, PROTOTUNNEL_CONTROL_PORTIDX, PROTOTUNNEL_CRYPTARC4_ITER, PROTOTUNNEL_MAXKEYS, PROTOTUNNEL_MAXPORTS, PROTOTUNNEL_MODE_XENON, PROTOTUNNEL_PORTFLAG_ENCRYPTED, PROTOTUNNEL_VERSION_1_0, TRUE, ProtoTunnelRefT::Tunnels, ProtoTunnelRefT::TunnelsCritR, ProtoTunnelRefT::TunnelsCritS, ProtoTunnelT::uRefCount, ProtoTunnelInfoT::uRemoteAddr, ProtoTunnelInfoT::uRemoteClientId, ProtoTunnelInfoT::uRemotePort, ProtoTunnelInfoT::uTunnelMode, ProtoTunnelRefT::uTunnelPort, ProtoTunnelRefT::uVersion, ProtoTunnelT::uVirtualAddr, and ProtoTunnelRefT::uVirtualAddr.
DIRTYCODE_API void ProtoTunnelCallback (ProtoTunnelRefT * pProtoTunnel, ProtoTunnelCallbackT * pCallback, void * pUserData)
Set event callback.
Parameters
*pProtoTunnel - pointer to module state
*pCallback - callback pointer
*pUserData - callback data
Version
03/24/2006 (jbrookes)
References ProtoTunnelRefT::pCallback, and ProtoTunnelRefT::pUserData.
DIRTYCODE_API int32_t ProtoTunnelControl (ProtoTunnelRefT * pProtoTunnel, int32_t iControl, int32_t iValue, int32_t iValue2, const void * pValue)
Control the module.
Parameters
*pProtoTunnel - pointer to module state
iControl - control selector
iValue - selector specific
iValue2 - selector specific
*pValue - selector specific
Returns
int32_t - selector result
Note
iControl can be one of the following:
        'bind' - recreate tunnel socket bound to specified port (iValue is port to bind to)
        'bnds' - recreate server tunnel socket bound to ephemeral port (iValue is ignored, iValue2 is remote server port)
        'clid' - set local clientId for all tunnels
        'drop' - drop next iValue packets (debug only; used to test crypt recovery)
        'flsh' - flush the specified tunnelId
        'hmac' - set hmac type (iValue) and size (iValue2)
        'rate' - set flush rate in milliseconds; defaults to 16ms
        'rprt' - set specified tunnel's remote port
        'rrcb' - set raw receive callback
        'rrud' - set raw receive user data
        'sock' - set socket ref
        'spam' - set verbosity level (debug only)
        'tcid' - set per-tunnel local clientId override for specific tunnel
Unrecognized selectors are passed through to SocketControl()
Version
12/02/2005 (jbrookes)
References CRYPTHASH_NULL, CRYPTHASH_NUMHASHES, CryptHashGetSize(), ProtoTunnelRefT::iMaxTunnels, ProtoTunnelT::Info, ProtoTunnelRefT::iVerbosity, NetCritEnter(), NetCritLeave(), NetPrintf, NetTick(), NULL, ProtoTunnelRefT::pRawRecvCallback, ProtoTunnelRefT::pRawRecvUserData, PROTOTUNNEL_HMAC_MAXSIZE, PROTOTUNNEL_VERSION_MIN, ProtoTunnelRefT::pServerSocket, ProtoTunnelRefT::pSocket, SocketClose(), SocketControl(), ProtoTunnelRefT::Tunnels, ProtoTunnelRefT::TunnelsCritR, ProtoTunnelRefT::TunnelsCritS, ProtoTunnelRefT::uFlushRate, ProtoTunnelRefT::uHmacSize, ProtoTunnelRefT::uHmacType, ProtoTunnelT::uLocalClientId, ProtoTunnelRefT::uLocalClientId, ProtoTunnelInfoT::uRemotePort, ProtoTunnelRefT::uServerRemotePort, ProtoTunnelRefT::uTunnelPort, ProtoTunnelRefT::uVersion, and ProtoTunnelT::uVirtualAddr.
Referenced by ConnApiControl().
DIRTYCODE_API ProtoTunnelRefT* ProtoTunnelCreate (int32_t iMaxTunnels, int32_t iTunnelPort)
Create the ProtoTunnel module.
Parameters
iMaxTunnels - maximum number of tunnels module can allocate
iTunnelPort - local port for socket all tunnels will use
Returns
ProtoTunnelRefT * - pointer to new module, or NULL
Version
12/02/2005 (jbrookes)
References CRYPTHASH_MURMUR3, DirtyMemAlloc(), DirtyMemFree(), DirtyMemGroupQuery(), FALSE, ProtoTunnelRefT::iMaxTunnels, ProtoTunnelRefT::iMemGroup, NetCritInit(), NetPrintf, NetTick(), NULL, ProtoTunnelRefT::pMemGroupUserData, PROTOTUNNEL_MAXPACKET, PROTOTUNNEL_MEMID, PROTOTUNNEL_VERSION, ProtoTunnelRefT::pSocket, SocketControl(), TRUE, ProtoTunnelRefT::TunnelsCritR, ProtoTunnelRefT::TunnelsCritS, ProtoTunnelRefT::uHmacSize, ProtoTunnelRefT::uHmacType, ProtoTunnelRefT::uLastFlush, ProtoTunnelRefT::uTunnelPort, and ProtoTunnelRefT::uVersion.
Referenced by ConnApiOnline().
DIRTYCODE_API void ProtoTunnelDestroy (ProtoTunnelRefT * pProtoTunnel)
Destroy the ProtoTunnel module.
Parameters
*pProtoTunnel - pointer to module state
Version
12/02/2005 (jbrookes)
References DirtyMemFree(), FALSE, ProtoTunnelRefT::iMemGroup, NetCritKill(), NULL, ProtoTunnelRefT::pMemGroupUserData, PROTOTUNNEL_MEMID, ProtoTunnelRefT::pServerSocket, ProtoTunnelRefT::pSocket, SocketClose(), SocketControl(), ProtoTunnelRefT::TunnelsCritR, and ProtoTunnelRefT::TunnelsCritS.
Referenced by ConnApiDestroy().
DIRTYCODE_API uint32_t ProtoTunnelFree (ProtoTunnelRefT * pProtoTunnel, uint32_t uTunnelId, const char * pKey)
Free a tunnel.
Parameters
*pProtoTunnel - pointer to module state
uTunnelId - id of tunnel to free
*pKey - key tunnel was allocated with
Note
pKey is only required when tunnel refcounting is used. Otherwise, pKey may be specified as NULL.
Version
12/07/2005 (jbrookes)
References ProtoTunnelFree2().
DIRTYCODE_API uint32_t ProtoTunnelFree2 (ProtoTunnelRefT * pProtoTunnel, uint32_t uTunnelId, const char * pKey, uint32_t uAddr)
Free a tunnel. Same as ProtoTunnelFree but takes an IP address. Used on 360 to allow ProtoTunnel to maintain a list of secure IP addresses for sending. When refcounting down a tunnel, the current secure IP address will be replaced by another valid one, reaching the same peer.
Parameters
*pProtoTunnel - pointer to module state
uTunnelId - id of tunnel to free
*pKey - key tunnel was allocated with
uAddr - address of peer that is being freed
Note
pKey is only required when tunnel refcounting is used. Otherwise, pKey may be specified as NULL.
Version
03/15/2010 (jrainy)
References ProtoTunnelT::aKeyList, CryptArc4Advance(), CryptArc4Init(), ProtoTunnelT::CryptSendState, FALSE, ProtoTunnelT::Info, NetCritEnter(), NetCritKill(), NetCritLeave(), NetPrintf, NetTick(), ProtoTunnelT::PacketCrit, PROTOTUNNEL_CRYPTARC4_ITER, PROTOTUNNEL_CRYPTBITS, PROTOTUNNEL_MAXKEYS, TRUE, ProtoTunnelRefT::Tunnels, ProtoTunnelRefT::TunnelsCritR, ProtoTunnelRefT::TunnelsCritS, ProtoTunnelT::uRefCount, ProtoTunnelInfoT::uRemoteAddr, ProtoTunnelInfoT::uRemoteClientId, ProtoTunnelT::uSendKey, ProtoTunnelT::uSendOffset, and ProtoTunnelT::uVirtualAddr.
Referenced by ProtoTunnelFree().
DIRTYCODE_API int32_t ProtoTunnelRawSendto (ProtoTunnelRefT * pProtoTunnel, const char * pBuf, int32_t iLen, const struct sockaddr * pTo, int32_t iToLen)
Send data to a remote host over the prototunnel socket. The destination address is supplied along with the data. Important: remote host shall not be expecting tunneled data because that function bypasses all the tunneling logic on the sending side.
Parameters
*pProtoTunnel - pointer to module state
*pBuf - the data to be sent
iLen - size of data
*pTo - the address to send to
iToLen - length of address
Returns
int32_t - number of bytes sent or standard network error code (SOCKERR_xxx)
Version
07/12/2011 (mclouatre)
DIRTYCODE_API int32_t ProtoTunnelStatus (ProtoTunnelRefT * pProtoTunnel, int32_t iSelect, int32_t iValue, void * pBuf, int32_t iBufSize)
Get module status.
Parameters
*pProtoTunnel - pointer to module state
iSelect - status selector
iValue - selector specific
*pBuf - [out] - selector specific
iBufSize - size of output buffer
Returns
int32_t - selector specific
Note
iControl can be one of the following:
        'dpkt' - return number of out-of-order packet discards
        'hmac' - return HMAC type/size
        'lprt' - return local socket port
        'maxp' - return maximum size of packet that can be tunneled (NOTE: pProtoTunnel can be NULL)
        'rcvs' - copy receive statistics to pBuf
        'rcal' - return number of recv calls
        'rprt' - remote game port for the specificed tunnel id
        'rsub' - return number of sub-packets received
        'rtot' - return number of packets received
        'snds' - copy send statistics to pBuf
        'sock' - copy socket ref to pBuf
        'vtop' - convert virtual address to physical address (pBuf == sockaddr, optional)
Version
12/02/2005 (jbrookes)
References ds_memcpy(), ProtoTunnelT::Info, NetPrintf, NULL, PROTOTUNNEL_MAXPACKET, ProtoTunnelRefT::pSocket, ProtoTunnelT::RecvStat, ProtoTunnelT::SendStat, ProtoTunnelRefT::Tunnels, ProtoTunnelRefT::uHmacSize, ProtoTunnelRefT::uHmacType, ProtoTunnelRefT::uNumPktsDiscard, ProtoTunnelRefT::uNumPktsRecvd, ProtoTunnelRefT::uNumRecvCalls, ProtoTunnelRefT::uNumSubPktsRecvd, ProtoTunnelInfoT::uRemotePort, and ProtoTunnelRefT::uTunnelPort.
Referenced by ConnApiStatus2().
DIRTYCODE_API void ProtoTunnelUpdate (ProtoTunnelRefT * pProtoTunnel)
Update the module.
Parameters
*pProtoTunnel - pointer to module state
Version
12/02/2005 (jbrookes)
References ProtoTunnelRefT::iMaxTunnels, NetCritEnter(), NetCritLeave(), NetTick(), NetTickDiff, ProtoTunnelRefT::pSocket, ProtoTunnelRefT::Tunnels, ProtoTunnelRefT::TunnelsCritR, ProtoTunnelRefT::TunnelsCritS, ProtoTunnelRefT::uFlushRate, ProtoTunnelRefT::uLastFlush, and ProtoTunnelT::uVirtualAddr.
DIRTYCODE_API int32_t ProtoTunnelUpdatePortList (ProtoTunnelRefT * pProtoTunnel, uint32_t uTunnelId, ProtoTunnelInfoT * pInfo)
Updates the port list for the given tunnel. Port and port flag info is copied over from the specified info structure if the port value is non- zero.
Parameters
*pProtoTunnel - pointer to module state
uTunnelId - id of tunnel to update port mapping for
*pInfo - structure containing updated port info
Returns
int32_t - zero=success, else could not find tunnel with given id
Version
06/12/2008 (jbrookes)
References ProtoTunnelInfoT::aPortFlags, ProtoTunnelInfoT::aRemotePortList, ProtoTunnelT::Info, NetCritEnter(), NetCritLeave(), NetPrintf, PROTOTUNNEL_MAXPORTS, ProtoTunnelRefT::Tunnels, ProtoTunnelRefT::TunnelsCritR, ProtoTunnelRefT::TunnelsCritS, and ProtoTunnelT::uVirtualAddr.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:42