DirtySock: DirtyJpg
DirtyJpg
Graph
Data Structures
struct DirtyJpgHdrT
structure to represent a parsed gif
Macros
#define DIRTYJPG_ERR_NONE (0)
#define DIRTYJPG_ERR_NOMAGIC (-1)
#define DIRTYJPG_ERR_TOOSHORT (-2)
#define DIRTYJPG_ERR_NOBUFFER (-3)
#define DIRTYJPG_ERR_BADSTATE (-4)
#define DIRTYJPG_ERR_BADFRAME (-5)
#define DIRTYJPG_ERR_BADVERS (-6)
#define DIRTYJPG_ERR_ENDOFDATA (-7)
#define DIRTYJPG_ERR_BADDQT (-8)
#define DIRTYJPG_ERR_BADDHT (-9)
#define DIRTYJPG_ERR_BADSOF0 (-10)
#define DIRTYJPG_ERR_BITDEPTH (-11)
#define DIRTYJPG_ERR_DECODER (-12)
#define DIRTYJPG_ERR_NOSUPPORT (-13)
Typedefs
typedef struct DirtyJpgStateT DirtyJpgStateT
typedef struct DirtyJpgHdrT DirtyJpgHdrT
structure to represent a parsed gif
Functions
DIRTYCODE_API DirtyJpgStateT * DirtyJpgCreate (void)
Create the DirtyJpg module state.
DIRTYCODE_API void DirtyJpgReset (DirtyJpgStateT *pState)
Reset the DirtyJpg module state.
DIRTYCODE_API void DirtyJpgDestroy (DirtyJpgStateT *pState)
Destroy the DirtyJpg module.
DIRTYCODE_API int32_t DirtyJpgIdentify (DirtyJpgStateT *pState, const uint8_t *pImageData, uint32_t uImageLen)
Identify if input image is a JPG (JFIF) image.
DIRTYCODE_API int32_t DirtyJpgDecodeHeader (DirtyJpgStateT *pState, DirtyJpgHdrT *pJpgHdr, const uint8_t *pImage, uint32_t uLength)
Parse JPG header.
DIRTYCODE_API int32_t DirtyJpgDecodeImage (DirtyJpgStateT *pState, DirtyJpgHdrT *pJpgHdr, uint8_t *pImageData, int32_t iBufWidth, int32_t iBufHeight)
Parse JPG image.
Detailed Description
Macro Definition Documentation
#define DIRTYJPG_ERR_BADDHT (-9)
#define DIRTYJPG_ERR_BADDQT (-8)
#define DIRTYJPG_ERR_BADFRAME (-5)
#define DIRTYJPG_ERR_BADSOF0 (-10)
#define DIRTYJPG_ERR_BADSTATE (-4)
Referenced by DirtyJpgDecodeImage().
#define DIRTYJPG_ERR_BADVERS (-6)
#define DIRTYJPG_ERR_BITDEPTH (-11)
#define DIRTYJPG_ERR_DECODER (-12)
#define DIRTYJPG_ERR_ENDOFDATA (-7)
#define DIRTYJPG_ERR_NOBUFFER (-3)
Referenced by DirtyJpgDecodeHeader(), DirtyJpgDecodeImage(), and DirtyJpgIdentify().
#define DIRTYJPG_ERR_NOMAGIC (-1)
Referenced by DirtyJpgDecodeHeader().
#define DIRTYJPG_ERR_NONE (0)
Referenced by DirtyGraphDecodeHeader(), and DirtyJpgIdentify().
#define DIRTYJPG_ERR_NOSUPPORT (-13)
#define DIRTYJPG_ERR_TOOSHORT (-2)
Referenced by DirtyJpgDecodeHeader().
Typedef Documentation
typedef struct DirtyJpgHdrT DirtyJpgHdrT
structure to represent a parsed gif
typedef struct DirtyJpgStateT DirtyJpgStateT
Function Documentation
DIRTYCODE_API DirtyJpgStateT* DirtyJpgCreate (void)
Create the DirtyJpg module state.
Returns
DirtyJpgStateT * - pointer to new ref, or NULL if error
Version
02/23/2006 (jbrookes)
References DIRTYJPG_MEMID, DirtyMemAlloc(), DirtyMemGroupQuery(), DirtyJpgStateT::iMemGroup, NetPrintf, and DirtyJpgStateT::pMemGroupUserData.
Referenced by DirtyGraphCreate().
DIRTYCODE_API int32_t DirtyJpgDecodeHeader (DirtyJpgStateT * pState, DirtyJpgHdrT * pJpgHdr, const uint8_t * pImage, uint32_t uLength)
Parse JPG header.
Parameters
*pState - pointer to module state
*pJpgHdr - pointer to jpg header
*pImage - pointer to image buf
uLength - size of input image
Returns
int32_t - DIRTYJPG_ERR_*
Version
02/23/2006 (jbrookes)
References DIRTYJPG_ERR_NOBUFFER, DIRTYJPG_ERR_NOMAGIC, DIRTYJPG_ERR_TOOSHORT, DirtyJpgReset(), FALSE, DirtyJpgHdrT::pImageData, DirtyJpgHdrT::uHeight, DirtyJpgStateT::uImageHeight, DirtyJpgStateT::uImageWidth, DirtyJpgHdrT::uLength, and DirtyJpgHdrT::uWidth.
Referenced by DirtyGraphDecodeHeader().
DIRTYCODE_API int32_t DirtyJpgDecodeImage (DirtyJpgStateT * pState, DirtyJpgHdrT * pJpgHdr, uint8_t * pImageBuf, int32_t iBufWidth, int32_t iBufHeight)
Parse JPG image.
Parameters
*pState - pointer to module state
*pJpgHdr - pointer to jpg header
*pImageBuf - pointer to image buf
iBufWidth - image buf width
iBufHeight - image buf height
Returns
int32_t - DIRTYJPG_ERR_*
Version
02/23/2006 (jbrookes)
References DIRTYJPG_ERR_BADSTATE, DIRTYJPG_ERR_NOBUFFER, FALSE, DirtyJpgStateT::iLastError, DirtyJpgStateT::pImageBuf, DirtyJpgHdrT::pImageData, DirtyJpgStateT::uBufHeight, DirtyJpgStateT::uBufWidth, DirtyJpgStateT::uLastOffset, and DirtyJpgHdrT::uLength.
Referenced by DirtyGraphDecodeImage().
DIRTYCODE_API void DirtyJpgDestroy (DirtyJpgStateT * pState)
Destroy the DirtyJpg module.
Parameters
*pState - pointer to module state
Version
02/23/2006 (jbrookes)
References DIRTYJPG_MEMID, DirtyMemFree(), DirtyJpgStateT::iMemGroup, and DirtyJpgStateT::pMemGroupUserData.
Referenced by DirtyGraphDestroy().
DIRTYCODE_API int32_t DirtyJpgIdentify (DirtyJpgStateT * pState, const uint8_t * pImageData, uint32_t uImageLen)
Identify if input image is a JPG (JFIF) image.
Parameters
*pState - jpg module state
*pImageData - pointer to image data
uImageLen - size of image data
Returns
int32_t - TRUE if a JPG, else FALSE
Version
03/09/2006 (jbrookes)
References DIRTYJPG_ERR_NOBUFFER, DIRTYJPG_ERR_NONE, and TRUE.
Referenced by DirtyGraphDecodeHeader().
DIRTYCODE_API void DirtyJpgReset (DirtyJpgStateT * pState)
Reset the DirtyJpg module state.
Parameters
*pState - pointer to module state
Version
02/23/2006 (jbrookes)
References DirtyJpgStateT::bRestart, DirtyJpgStateT::CompTable, FALSE, DirtyJpgStateT::HuffTable, DirtyJpgStateT::pImageBuf, DirtyJpgStateT::QuantTable, DirtyJpgStateT::uBitfield, DirtyJpgStateT::uBitsAvail, DirtyJpgStateT::uBitsConsumed, DirtyJpgStateT::uBytesRead, and DirtyJpgStateT::uLastOffset.
Referenced by DirtyJpgDecodeHeader().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:17