DirtySock: BuddyApi
BuddyApi
Friend
Data Structures
struct BuddyRosterT
roster entry
struct BuddyApiMsgT
info message (chat, extended info, etc)
struct BuddyApiUserT
Macros
#define BUDDY_MAX_USERS_FOUND 20
max number of users returned on "find user".
#define BUDDY_DOMAIN_LEN 4
#define BUDDY_PRODUCT_LEN 16
#define BUDDY_TITLE_LEN 40
#define BUDDY_NAME_LEN 32
#define BUDDY_SESSION_ID_LEN 16
#define BUDDY_FLAG_BUDDY (1<<('B'&31))
user is on buddy list
#define BUDDY_FLAG_IGNORE (1<<('I'&31))
user is on ignore list
#define BUDDY_FLAG_TEMP (1<<('T'&31))
user is temporary
#define BUDDY_FLAG_SAME (1<<('M'&31))
user is using same product
#define BUDDY_FLAG_PEND (1<<('P'&31))
user is pending (waiting for server)
#define BUDDY_FLAG_WATCH (1<<('W'&31))
watch this user (for temp buddies)
#define BUDDY_FLAG_TEXT (1<<('X'&31))
supports Text messaging i.e. EA user.
#define BUDDY_FLAG_NOREPLY (1<<('Y'&31))
bud who wont accept msgs or invites.
#define BUDDY_FLAG_BUD_REQ_SENT (1<<('S'&31))
I invited him to be my bud.
#define BUDDY_FLAG_BUD_REQ_RECEIVED (1<<('R'&31))
I recd invite to be his bud.
#define BUDDY_FLAG_JOINABLE (1<<('L'&31))
In a state where you can join me in lobby etc.
#define BUDDY_FLAG_GAME_INVITE_SENT (1<<('Q'&31))
I invited him to play game.
#define BUDDY_FLAG_GAME_INVITE_RECEIVED (1<<('V'&31))
I recd invite to play game.
#define BUDDY_FLAG_GAME_INVITE_ACCEPTED (1<<('C'&31))
game invite accepted
#define BUDDY_FLAG_GAME_INVITE_REJECTED (1<<('J'&31))
game invite rejected –wont be flagged
#define BUDDY_FLAG_GAME_INVITE_READY (1<<('O'&31))
invitee is now back online, in game.
#define BUDDY_FLAG_GAME_INVITE_TIMEOUT (1<<('Z'&31))
t.o. waiting for acceptor to get back in game
#define BUDDY_FLAG_GAME_INVITE_REVOKE (1<<('K'&31))
changed mind –wont be flagged
#define BUDDY_MASK_GAME_INVITE
Mask for clearing all game invite flags.
#define BUDDY_MASK_GAME_REVOKE_ONLY
Mask for clearing all game invite when i do revoke–Do not clear Received flag.
#define BUDDY_MASK_GAME_REJECT_ONLY
Mask for clearing all game invite when i do Reject–Do not clear Sent flag.
#define BUDDY_MASK_KEEP_BUDDY
If on a delete, any of these flags still set, keep the buddy, as this defines a bud.
#define BUDDY_STAT_UNDEFINED -1
#define BUDDY_STAT_DISC 0
#define BUDDY_STAT_CHAT 1
#define BUDDY_STAT_AWAY 2
#define BUDDY_STAT_XA 3
#define BUDDY_STAT_DND 4
#define BUDDY_STAT_PASS 5
#define BUDDY_STAT_GAME 6
#define BUDDY_FORWARD_FLAG_EMAIL (1<<0)
Treatment of my messages at server.
#define BUDDY_FORWARD_FLAG_SMS (1<<1)
Send to SMS.
#define BUDDY_FORWARD_FLAG_UNKNOWN (1<<8)
Not loaded from server yet.
#define BUDDY_EMAIL_SMS_ADDR_LEN 254
max length of email or sms address
#define BUDDY_MSG_CHAT 'chat'
#define BUDDY_MSG_ADMIN 'admn'
#define BUDDY_MSG_ROSTER 'rost'
#define BUDDY_MSG_CONNECT 'conn'
#define BUDDY_MSG_AUTHORIZE 'auth'
#define BUDDY_MSG_ADDUSER 'addu'
#define BUDDY_MSG_DELUSER 'delu'
#define BUDDY_MSG_ENDROSTER 'endr'
#define BUDDY_MSG_SEND 'send'
#define BUDDY_MSG_USERS 'user'
#define BUDDY_MSG_BROADCAST 'brdc'
#define BUDDY_MSG_SET_FORWARDING 'epst'
#define BUDDY_MSG_BUD_INVITE 'invt'
#define BUDDY_MSG_GAME_INVITE 'ginv'
#define BUDDY_MSG_PRESENCE 'pget'
#define BUDDY_EASO_BODYLEN (255)
#define BUDDY_EASO_SUBJLEN (0)
#define BUDDY_TYPE_APPL "A"
application message
#define BUDDY_TYPE_CHAT "C"
chat message
#define BUDDY_SERV_IDLE 0
idle state (no connection)
#define BUDDY_SERV_CONN 1
connecting to server
#define BUDDY_SERV_NAME 2
server name lookup failure
#define BUDDY_SERV_TIME 3
server timeout
#define BUDDY_SERV_FAIL 4
misc connection failure
#define BUDDY_SERV_ONLN 5
server is online
#define BUDDY_SERV_DISC 6
server has disconnected
#define BUDDY_SERV_RECN 7
waiting to reconnect to server
#define BUDDY_ERROR_NONE 0
no error
#define BUDDY_ERROR_PEND -1
command is still pending
#define BUDDY_ERROR_NOTUSER -2
not a user
#define BUDDY_ERROR_BADPARM -3
bad parameter
#define BUDDY_ERROR_OFFLINE -4
server is offline
#define BUDDY_ERROR_FULL -5
no more room to add
#define BUDDY_ERROR_UNSUPPORTED -6
feaure not supported on platform
#define BUDDY_ERROR_SELF -7
cannot add oneself
#define BUDDY_ERROR_MISSING -8
item not found etc.
#define BUDDY_ERROR_TIMEOUT -10
app level timeout.
#define BUDDY_ERROR_BLOCKED -11
user has blocked your invites.
#define BUDDY_ERROR_MEMORY -12
memory alloc failure – user alloc block is full?
#define BUDDY_ERROR_MAX -13
#define BUDDY_SYMBOL_C "\xc2\xa9"
#define BUDDY_SYMBOL_R "\xc2\xae"
#define BUDDY_SYMBOL_TM "\xe2\x84\xa2"
Typedefs
typedef enum
BuddyInviteResponseTypeE BuddyInviteResponseTypeE
Xbfriend response and action types for games and buddies.
typedef struct BuddyApiRefT BuddyApiRefT
typedef struct BuddyRosterT BuddyRosterT
roster entry
typedef struct BuddyApiMsgT BuddyApiMsgT
info message (chat, extended info, etc)
typedef struct BuddyApiUserT BuddyApiUserT
typedef void(BuddyApiCallbackT)(BuddyApiRefT *pRef, BuddyApiMsgT *pMsg, void *pUserData)
buddy msg or list callback function prototype
typedef void(BuddyApiDelCallbackT)(BuddyApiRefT *pRef, BuddyRosterT *pBuddy, void *pUserData)
callback for client to free any "user ref" ptr memory, prior to buddy being deleted.
typedef void(BuddyApiBuddyChangeCallbackT)(BuddyApiRefT *pRef, BuddyRosterT *pBuddy, int32_t iKind, int32_t iAction, void *pUserData)
buddy change callback function prototype –game invite or presence etc. changed
typedef void *(BuddyMemAllocT)(int32_t iSize, int32_t iMemModule, int32_t iMemGroup, void *pMemGroupUserData)
Function prototype for custom mem allocation function.
typedef void(BuddyMemFreeT)(void *pMem, int32_t iMemModule, int32_t iMemGroup, void *pMemGroupUserData)
Function prototype for custom mem free function.
Enumerations
enum BuddyInviteResponseTypeE {
BUDDY_INVITE_RESPONSE_ACCEPT =0,
BUDDY_INVITE_RESPONSE_REJECT,
BUDDY_INVITE_RESPONSE_REVOKE,
BUDDY_INVITE_RESPONSE_BLOCK,
BUDDY_INVITE_RESPONSE_REMOVE,
BUDDY_INVITE_RESPONSE_INVITE,
BUDDY_INVITE_RESPONSE_MUTE,
BUDDY_INVITE_RESPONSE_JOIN,
BUDDY_INVITE_RESPONSE_TIMEOUT,
BUDDY_INVITE_RESPONSE_UNKNOWN_MAX
}
Xbfriend response and action types for games and buddies.
Functions
DIRTYCODE_API BuddyApiRefT * BuddyApiCreate2 (BuddyMemAllocT *pAlloc, BuddyMemFreeT *pFree, const char *pProduct, const char *pRelease, int32_t iRefMemGroup, void *pRefMemGroupUserData)
Create a new buddy interface client.
DIRTYCODE_API void BuddyApiDestroy (BuddyApiRefT *pState)
Destroy an existing client.
DIRTYCODE_API void BuddyApiDebug (BuddyApiRefT *pState, void *pDebugData, void(*pDebugProc)(void *pData, const char *pText))
Assign the debug callback.
DIRTYCODE_API int32_t BuddyApiConfig (BuddyApiRefT *pState, const char *pSame, uint32_t uLocality)
Config the language, initial same product identifier and locale for translating title name.
DIRTYCODE_API int32_t BuddyApiConnect (BuddyApiRefT *pState, const char *pServer, int32_t iPort, int32_t iTimeout, const char *pLKey, const char *pRsrc, BuddyApiCallbackT *pCallback, void *pCalldata)
Connect to the buddy server.
DIRTYCODE_API int32_t BuddyApiDisconnect (BuddyApiRefT *pState)
Disconnect from the buddy server.
DIRTYCODE_API int32_t BuddyApiStatus (BuddyApiRefT *pState)
Return the current connection status.
DIRTYCODE_API char * BuddyApiResource (BuddyApiRefT *pState)
Return the resource name set in this api.
DIRTYCODE_API char * BuddyApiDomain (BuddyApiRefT *pState)
Return the current Domain, as set in this api. Domain is the resource minus extra stuff at end that distinguishes servers.
DIRTYCODE_API void BuddyApiFlush (BuddyApiRefT *pState)
Flush the roster from memory.
DIRTYCODE_API DispListRef * BuddyApiRoster (BuddyApiRefT *pState, BuddyApiCallbackT *pCallback, void *pCalldata)
Get the roster from the server.
DIRTYCODE_API DispListRef * BuddyApiRosterList (BuddyApiRefT *pState)
Return the current roster display list.
DIRTYCODE_API int32_t BuddyApiAdd (BuddyApiRefT *pState, BuddyRosterT *pBuddy, BuddyApiCallbackT *pCallback, void *pCalldata, int32_t iTimeout)
Add a user to the buddy roster.
DIRTYCODE_API int32_t BuddyApiBuddyInvite (BuddyApiRefT *pState, BuddyRosterT *pBuddy, BuddyApiCallbackT *pCallback, void *pCalldata, int32_t iTimeout)
Invite a user to be my buddy.
DIRTYCODE_API int32_t BuddyApiGameInvite (BuddyApiRefT *pState, BuddyRosterT *pBuddy, BuddyApiCallbackT *pCallback, void *pCalldata, int32_t iTimeout, int32_t iSessionId, const char *pGameInviteState)
Invite a user to play Cross Game –Xbox Only!
DIRTYCODE_API void BuddyApiRegisterBuddyChangeCallback (BuddyApiRefT *pState, BuddyApiBuddyChangeCallbackT *pCallback, void *pCalldata)
Register a callback when buddy changes state – this include presence change or game notifications.
DIRTYCODE_API void BuddyApiRegisterBuddyDelCallback (BuddyApiRefT *pState, BuddyApiDelCallbackT *pDelCallback, void *pCalldata)
Register optional callback for client to free user ref ptr, when buddy is being deleted from mem. BuddyApi will call this, just prior to freeing the buddy memory.
DIRTYCODE_API int32_t BuddyApiRespondBuddy (BuddyApiRefT *pState, BuddyRosterT *pBuddy, BuddyInviteResponseTypeE eResponse, BuddyApiCallbackT *pCallback, void *pCalldata, int32_t iTimeout)
DIRTYCODE_API int32_t BuddyApiRespondGame (BuddyApiRefT *pState, BuddyRosterT *pBuddy, BuddyInviteResponseTypeE eResponse, BuddyApiCallbackT *pCallback, void *pCalldata, int32_t iTimeout, int32_t iSessionId)
Respond to game invite requests. pBuddy is null for a cancel of ALL invites sent.
DIRTYCODE_API int32_t BuddyApiJoinGame (BuddyApiRefT *pState, BuddyRosterT *pBuddy, BuddyApiCallbackT *pCallback, void *pCalldata, int32_t iTimeout)
Join my buddy, wherever he is –he must be in another game and joinable.
DIRTYCODE_API int32_t BuddyApiDel (BuddyApiRefT *pState, BuddyRosterT *pBuddy, BuddyApiCallbackT *pCallback, void *pCalldata, int32_t iTimeout)
Add a user to the buddy roster.
DIRTYCODE_API BuddyRosterT * BuddyApiFind (BuddyApiRefT *pState, const char *pUser)
Find a user in the buddy roster.
DIRTYCODE_API int32_t BuddyApiSetForwarding (BuddyApiRefT *pState, unsigned uForwardingFlags, const char *strEmail, BuddyApiCallbackT *pCallback, void *pCalldata, int32_t iTimeout)
Turn email forwarding on or off, and set email address.
DIRTYCODE_API int32_t BuddyApiGetForwarding (BuddyApiRefT *pState, unsigned *puForwardingFlags, char *strEmail)
Get email and other forwarding states, if already loaded from server.
DIRTYCODE_API int32_t BuddyApiFindUsers (BuddyApiRefT *pState, const char *pUserPattern, BuddyApiCallbackT *pCallback, void *pCalldata, int32_t iTimeout)
Request a search of users, of names starting with the pUserPattern. Min 3 chars.
DIRTYCODE_API BuddyApiUserT * BuddyApiUserFound (BuddyApiRefT *pState, int32_t item)
Return users found from FindUser request. Allows client to iterate list of returned users. Should be called after callback from BuddyApiFindUsers has returned with a succes status.
DIRTYCODE_API void BuddyApiPresInit (BuddyApiRefT *pState)
Prepare to send our presence information to the server.
DIRTYCODE_API void BuddyApiPresSame (BuddyApiRefT *pState, const char *pSame)
Set the presence information intended for the same product.
DIRTYCODE_API void BuddyApiPresDiff (BuddyApiRefT *pState, const char *pDiff, const char *pLang)
Setup information for different products.
DIRTYCODE_API void BuddyApiPresJoinable (BuddyApiRefT *pState, int32_t bOn)
Set/Reset the I am joinable bit for Xbox –so other games can join/meet me.
DIRTYCODE_API void BuddyApiPresExFlags (BuddyApiRefT *pState, uint32_t uFlags)
Add extra, client specific, info to the Presence.
DIRTYCODE_API void BuddyApiPresNoText (BuddyApiRefT *pState)
Set flag to set no text capability to server -if dont support text messages. Will be sent to server on next send (e.g. BuddyApiPresSend).
DIRTYCODE_API void BuddyApiPresExtra (BuddyApiRefT *pState, const char *strExtraPres)
Set addition string to users presence, will be sent to buddies when BuddyApiPresSend is called.
DIRTYCODE_API int32_t BuddyApiPresSend (BuddyApiRefT *pState, const char *pRsrc, int32_t iShow, int32_t iDelay, int32_t bDontAutoRefreshRoster)
Prepare to send our presence information to the server.
DIRTYCODE_API void BuddyApiSuspendXDK (BuddyApiRefT *pState)
DIRTYCODE_API void BuddyApiResumeXDK (BuddyApiRefT *pState)
DIRTYCODE_API int32_t BuddyApiSend (BuddyApiRefT *pState, const char *pMesg, BuddyApiCallbackT *pCallback, void *pCalldata, int32_t iTimeout)
Send a message to a remote user.
DIRTYCODE_API int32_t BuddyApiBroadcast (BuddyApiRefT *pState, const char *pMesg, BuddyApiCallbackT *pCallback, void *pCalldata, int32_t iTimeout)
Send a message to a list of users, or to all in product or even domain.
DIRTYCODE_API void BuddyApiRecv (BuddyApiRefT *pState, BuddyApiCallbackT *pCallback, void *pCalldata)
Set the receive callback.
DIRTYCODE_API unsigned BuddyApiUpdate (BuddyApiRefT *pState)
Handle periodic update, and return the aries game tick.
DIRTYCODE_API int32_t BuddyApiGetTitleName (BuddyApiRefT *pState, const uint32_t uTitleId, const int32_t iBufSize, char *pTitleName)
Get the "Official" Xbox title name for a given title id, based on my locale-language.
DIRTYCODE_API int32_t BuddyApiGetMyTitleName (BuddyApiRefT *pState, const char *pLang, const int32_t iBufSize, char *pTitleName)
Get the "Official" title name for this game. pLang ignored for now–defaults to English.
DIRTYCODE_API void _BuddyApiSetTalkToXbox (BuddyApiRefT *pState, int32_t bOn)
temp test method prior to Server side Xbox integration..
DIRTYCODE_API void BuddyApiRefreshTitle (BuddyApiRefT *pBudRef, BuddyRosterT *pBuddy)
DIRTYCODE_API int32_t BuddyApiSetGameInviteSessionID (BuddyApiRefT *pState, const char *sSessionID)
Set my Session id, for an xbox game invite.
DIRTYCODE_API int32_t BuddyApiGetUserSessionID (BuddyApiRefT *pState, const char *strGamertag, char *sSessionID, const int32_t iBufSize)
Get this users game session id.
Detailed Description
Macro Definition Documentation
#define BUDDY_DOMAIN_LEN 4
#define BUDDY_EASO_BODYLEN (255)
Referenced by HLBMsgListMsgInject().
#define BUDDY_EASO_SUBJLEN (0)
#define BUDDY_EMAIL_SMS_ADDR_LEN 254
max length of email or sms address
#define BUDDY_ERROR_BADPARM -3
bad parameter
Referenced by BuddyApiAdd(), BuddyApiDel(), BuddyApiFindUsers(), BuddyApiRespondBuddy(), BuddyApiRespondGame(), and BuddyApiSetForwarding().
#define BUDDY_ERROR_BLOCKED -11
user has blocked your invites.
#define BUDDY_ERROR_FULL -5
no more room to add
Referenced by BuddyApiUpdate().
#define BUDDY_ERROR_MAX -13
#define BUDDY_ERROR_MEMORY -12
memory alloc failure – user alloc block is full?
Referenced by BuddyApiAdd().
#define BUDDY_ERROR_MISSING -8
item not found etc.
Referenced by BuddyApiGetMyTitleName(), BuddyApiGetTitleName(), and BuddyApiGetUserSessionID().
#define BUDDY_ERROR_NONE 0
no error
Referenced by BuddyApiAdd(), BuddyApiConfig(), BuddyApiConnect(), BuddyApiDel(), BuddyApiDisconnect(), BuddyApiGetForwarding(), BuddyApiGetUserSessionID(), BuddyApiPresSend(), BuddyApiRespondBuddy(), BuddyApiSetGameInviteSessionID(), BuddyApiUpdate(), and HLBListSort().
#define BUDDY_ERROR_NOTUSER -2
not a user
Referenced by BuddyApiDel(), and BuddyApiUpdate().
#define BUDDY_ERROR_OFFLINE -4
server is offline
Referenced by BuddyApiUpdate().
#define BUDDY_ERROR_PEND -1
command is still pending
Referenced by BuddyApiGetForwarding().
#define BUDDY_ERROR_SELF -7
cannot add oneself
#define BUDDY_ERROR_TIMEOUT -10
app level timeout.
#define BUDDY_ERROR_UNSUPPORTED -6
feaure not supported on platform
Referenced by BuddyApiJoinGame().
#define BUDDY_FLAG_BUD_REQ_RECEIVED (1<<('R'&31))
I recd invite to be his bud.
Referenced by BuddyApiRespondBuddy(), BuddyApiUpdate(), and HLBBudIsWannaBeMyBuddy().
#define BUDDY_FLAG_BUD_REQ_SENT (1<<('S'&31))
I invited him to be my bud.
Referenced by BuddyApiAdd(), BuddyApiBuddyInvite(), BuddyApiRespondBuddy(), BuddyApiUpdate(), and HLBBudIsIWannaBeHisBuddy().
#define BUDDY_FLAG_BUDDY (1<<('B'&31))
user is on buddy list
Referenced by BuddyApiAdd(), BuddyApiDel(), BuddyApiRespondBuddy(), BuddyApiUpdate(), HLBBudIsRealBuddy(), HLBListInviteBuddy(), and HLBListUnMakeBuddy().
#define BUDDY_FLAG_GAME_INVITE_ACCEPTED (1<<('C'&31))
game invite accepted
Referenced by BuddyApiRespondGame().
#define BUDDY_FLAG_GAME_INVITE_READY (1<<('O'&31))
invitee is now back online, in game.
#define BUDDY_FLAG_GAME_INVITE_RECEIVED (1<<('V'&31))
I recd invite to play game.
#define BUDDY_FLAG_GAME_INVITE_REJECTED (1<<('J'&31))
game invite rejected –wont be flagged
#define BUDDY_FLAG_GAME_INVITE_REVOKE (1<<('K'&31))
changed mind –wont be flagged
#define BUDDY_FLAG_GAME_INVITE_SENT (1<<('Q'&31))
I invited him to play game.
Referenced by BuddyApiGameInvite(), and HLBListCancelGameInvite().
#define BUDDY_FLAG_GAME_INVITE_TIMEOUT (1<<('Z'&31))
t.o. waiting for acceptor to get back in game
Referenced by HLBApiUpdate().
#define BUDDY_FLAG_IGNORE (1<<('I'&31))
user is on ignore list
Referenced by BuddyApiAdd(), BuddyApiDel(), BuddyApiRespondBuddy(), BuddyApiUpdate(), HLBBudIsBlocked(), HLBListAnswerInvite(), HLBListBlockBuddy(), and HLBListUnBlockBuddy().
#define BUDDY_FLAG_JOINABLE (1<<('L'&31))
In a state where you can join me in lobby etc.
Referenced by HLBBudIsJoinable().
#define BUDDY_FLAG_NOREPLY (1<<('Y'&31))
bud who wont accept msgs or invites.
Referenced by HLBBudIsNoReplyBud().
#define BUDDY_FLAG_PEND (1<<('P'&31))
user is pending (waiting for server)
Referenced by BuddyApiAdd(), and BuddyApiUpdate().
#define BUDDY_FLAG_SAME (1<<('M'&31))
user is using same product
Referenced by HLBBudIsSameProduct().
#define BUDDY_FLAG_TEMP (1<<('T'&31))
user is temporary
Referenced by BuddyApiAdd(), HLBListDeleteTempBuddy(), and HLBListFlagTempBuddy().
#define BUDDY_FLAG_TEXT (1<<('X'&31))
supports Text messaging i.e. EA user.
#define BUDDY_FLAG_WATCH (1<<('W'&31))
watch this user (for temp buddies)
Referenced by BuddyApiAdd(), BuddyApiDel(), and BuddyApiUpdate().
#define BUDDY_FORWARD_FLAG_EMAIL (1<<0)
Treatment of my messages at server.
Send to email
Referenced by BuddyApiSetForwarding(), BuddyApiUpdate(), HLBApiGetEmailForwarding(), and HLBApiSetEmailForwarding().
#define BUDDY_FORWARD_FLAG_SMS (1<<1)
Send to SMS.
#define BUDDY_FORWARD_FLAG_UNKNOWN (1<<8)
Not loaded from server yet.
Referenced by BuddyApiCreate2(), BuddyApiGetForwarding(), and BuddyApiUpdate().
#define BUDDY_MASK_GAME_INVITE
Value:
(BUDDY_FLAG_GAME_INVITE_SENT \
            | BUDDY_FLAG_GAME_INVITE_RECEIVED \
            | BUDDY_FLAG_GAME_INVITE_ACCEPTED \
            | BUDDY_FLAG_GAME_INVITE_REJECTED\
            | BUDDY_FLAG_GAME_INVITE_READY \
            | BUDDY_FLAG_GAME_INVITE_TIMEOUT\
            | BUDDY_FLAG_GAME_INVITE_REVOKE )
Mask for clearing all game invite flags.
Referenced by BuddyApiRespondGame(), and HLBBudGetGameInviteFlags().
#define BUDDY_MASK_GAME_REJECT_ONLY
Value:
(BUDDY_FLAG_GAME_INVITE_RECEIVED \
            | BUDDY_FLAG_GAME_INVITE_ACCEPTED \
            | BUDDY_FLAG_GAME_INVITE_REJECTED\
            | BUDDY_FLAG_GAME_INVITE_READY \
            | BUDDY_FLAG_GAME_INVITE_TIMEOUT\
            | BUDDY_FLAG_GAME_INVITE_REVOKE )
Mask for clearing all game invite when i do Reject–Do not clear Sent flag.
Referenced by BuddyApiRespondGame().
#define BUDDY_MASK_GAME_REVOKE_ONLY
Value:
(BUDDY_FLAG_GAME_INVITE_SENT \
            | BUDDY_FLAG_GAME_INVITE_ACCEPTED \
            | BUDDY_FLAG_GAME_INVITE_REJECTED\
            | BUDDY_FLAG_GAME_INVITE_READY \
            | BUDDY_FLAG_GAME_INVITE_TIMEOUT\
            | BUDDY_FLAG_GAME_INVITE_REVOKE )
Mask for clearing all game invite when i do revoke–Do not clear Received flag.
Referenced by BuddyApiRespondGame().
#define BUDDY_MASK_KEEP_BUDDY
Value:
(BUDDY_FLAG_BUDDY  \
            | BUDDY_FLAG_IGNORE \
            | BUDDY_FLAG_TEMP \
            | BUDDY_FLAG_BUD_REQ_SENT \
            | BUDDY_FLAG_BUD_REQ_RECEIVED )
If on a delete, any of these flags still set, keep the buddy, as this defines a bud.
#define BUDDY_MAX_USERS_FOUND 20
max number of users returned on "find user".
Referenced by BuddyApiFindUsers(), and BuddyApiUserFound().
#define BUDDY_MSG_ADDUSER 'addu'
Referenced by BuddyApiUpdate().
#define BUDDY_MSG_ADMIN 'admn'
Referenced by BuddyApiUpdate().
#define BUDDY_MSG_AUTHORIZE 'auth'
Referenced by BuddyApiUpdate().
#define BUDDY_MSG_BROADCAST 'brdc'
Referenced by BuddyApiUpdate().
#define BUDDY_MSG_BUD_INVITE 'invt'
Referenced by BuddyApiUpdate().
#define BUDDY_MSG_CHAT 'chat'
#define BUDDY_MSG_CONNECT 'conn'
#define BUDDY_MSG_DELUSER 'delu'
Referenced by BuddyApiUpdate().
#define BUDDY_MSG_ENDROSTER 'endr'
Referenced by BuddyApiUpdate().
#define BUDDY_MSG_GAME_INVITE 'ginv'
Referenced by BuddyApiUpdate(), and HLBApiUpdate().
#define BUDDY_MSG_PRESENCE 'pget'
#define BUDDY_MSG_ROSTER 'rost'
Referenced by BuddyApiFlush(), and BuddyApiUpdate().
#define BUDDY_MSG_SEND 'send'
Referenced by BuddyApiUpdate().
#define BUDDY_MSG_SET_FORWARDING 'epst'
Referenced by BuddyApiUpdate().
#define BUDDY_MSG_USERS 'user'
Referenced by BuddyApiUpdate().
#define BUDDY_NAME_LEN 32
#define BUDDY_PRODUCT_LEN 16
#define BUDDY_SERV_CONN 1
connecting to server
Referenced by BuddyApiConnect().
#define BUDDY_SERV_DISC 6
server has disconnected
Referenced by BuddyApiDisconnect(), and BuddyApiUpdate().
#define BUDDY_SERV_FAIL 4
misc connection failure
#define BUDDY_SERV_IDLE 0
idle state (no connection)
Referenced by BuddyApiDisconnect().
#define BUDDY_SERV_NAME 2
server name lookup failure
Referenced by BuddyApiUpdate().
#define BUDDY_SERV_ONLN 5
server is online
Referenced by BuddyApiDisconnect(), BuddyApiUpdate(), and HLBApiPresenceOffline().
#define BUDDY_SERV_RECN 7
waiting to reconnect to server
Referenced by _BuddyApiReconnect(), and BuddyApiUpdate().
#define BUDDY_SERV_TIME 3
server timeout
Referenced by BuddyApiUpdate().
#define BUDDY_SESSION_ID_LEN 16
#define BUDDY_STAT_AWAY 2
#define BUDDY_STAT_CHAT 1
Referenced by BuddyApiPresSend(), HLBApiResume(), and HLBBudIsAvailableForChat().
#define BUDDY_STAT_DISC 0
Referenced by HLBApiConnect(), HLBApiDisconnect(), and HLBApiPresenceOffline().
#define BUDDY_STAT_DND 4
#define BUDDY_STAT_GAME 6
Referenced by BuddyApiPresSend().
#define BUDDY_STAT_PASS 5
Referenced by BuddyApiPresSend(), HLBApiSuspend(), HLBBudIsPassive(), HLBListDeleteTempBuddy(), HLBListFlagTempBuddy(), HLBListGameInviteBuddy(), HLBListInviteBuddy(), HLBListUnFlagTempBuddy(), and HLBListUnMakeBuddy().
#define BUDDY_STAT_UNDEFINED -1
#define BUDDY_STAT_XA 3
#define BUDDY_SYMBOL_C "\xc2\xa9"
#define BUDDY_SYMBOL_R "\xc2\xae"
#define BUDDY_SYMBOL_TM "\xe2\x84\xa2"
#define BUDDY_TITLE_LEN 40
#define BUDDY_TYPE_APPL "A"
application message
#define BUDDY_TYPE_CHAT "C"
chat message
Typedef Documentation
typedef void(BuddyApiBuddyChangeCallbackT)(BuddyApiRefT *pRef, BuddyRosterT *pBuddy, int32_t iKind, int32_t iAction, void *pUserData)
buddy change callback function prototype –game invite or presence etc. changed
typedef void(BuddyApiCallbackT)(BuddyApiRefT *pRef, BuddyApiMsgT *pMsg, void *pUserData)
buddy msg or list callback function prototype
typedef void(BuddyApiDelCallbackT)(BuddyApiRefT *pRef, BuddyRosterT *pBuddy, void *pUserData)
callback for client to free any "user ref" ptr memory, prior to buddy being deleted.
typedef struct BuddyApiMsgT BuddyApiMsgT
info message (chat, extended info, etc)
typedef struct BuddyApiRefT BuddyApiRefT
typedef struct BuddyApiUserT BuddyApiUserT
typedef enum BuddyInviteResponseTypeE BuddyInviteResponseTypeE
Xbfriend response and action types for games and buddies.
typedef void*(BuddyMemAllocT)(int32_t iSize, int32_t iMemModule, int32_t iMemGroup, void *pMemGroupUserData)
Function prototype for custom mem allocation function.
typedef void(BuddyMemFreeT)(void *pMem, int32_t iMemModule, int32_t iMemGroup, void *pMemGroupUserData)
Function prototype for custom mem free function.
typedef struct BuddyRosterT BuddyRosterT
roster entry
Enumeration Type Documentation
enum BuddyInviteResponseTypeE
Xbfriend response and action types for games and buddies.
Enumerator
BUDDY_INVITE_RESPONSE_ACCEPT
BUDDY_INVITE_RESPONSE_REJECT
BUDDY_INVITE_RESPONSE_REVOKE
BUDDY_INVITE_RESPONSE_BLOCK
BUDDY_INVITE_RESPONSE_REMOVE
BUDDY_INVITE_RESPONSE_INVITE
BUDDY_INVITE_RESPONSE_MUTE
BUDDY_INVITE_RESPONSE_JOIN
BUDDY_INVITE_RESPONSE_TIMEOUT
BUDDY_INVITE_RESPONSE_UNKNOWN_MAX
Function Documentation
DIRTYCODE_API void _BuddyApiSetTalkToXbox (BuddyApiRefT * pState, int32_t bOn)
temp test method prior to Server side Xbox integration..
Referenced by HLBApiOverrideConstants().
DIRTYCODE_API int32_t BuddyApiAdd (BuddyApiRefT * pState, BuddyRosterT * pBuddy, BuddyApiCallbackT * pCallback, void * pCalldata, int32_t iTimeout)
Add a user to the buddy roster.
Parameters
*pState - reference pointer
*pBuddy - buddy record
*pCallback - callback
*pCalldata - callback data
iTimeout - time out
Returns
int32_t - zero=success, negative=error
Version
01/20/2002 (GWS)
References BUDDY_ERROR_BADPARM, BUDDY_ERROR_MEMORY, BUDDY_ERROR_NONE, BUDDY_FLAG_BUD_REQ_SENT, BUDDY_FLAG_BUDDY, BUDDY_FLAG_IGNORE, BUDDY_FLAG_PEND, BUDDY_FLAG_TEMP, BUDDY_FLAG_WATCH, CB_ADDUSER, BuddyRosterT::iPend, NULL, BuddyApiRefT::strDomain, BuddyRosterT::strUser, TagFieldClear, TagFieldSetNumber(), TagFieldSetString(), and BuddyRosterT::uFlags.
Referenced by BuddyApiBuddyInvite().
DIRTYCODE_API int32_t BuddyApiBroadcast (BuddyApiRefT * pState, const char * pMesg, BuddyApiCallbackT * pCallback, void * pCalldata, int32_t iTimeout)
Send a message to a list of users, or to all in product or even domain.
Parameters
*pState - reference pointer
*pMesg - message packet
*pCallback - callback
*pCalldata - callback data
iTimeout - time out
Returns
int32_t - error code (zero=success, negative=error)
Referenced by HLBListSendChatMsg().
DIRTYCODE_API int32_t BuddyApiBuddyInvite (BuddyApiRefT * pState, BuddyRosterT * pBuddy, BuddyApiCallbackT * pCallback, void * pCalldata, int32_t iTimeout)
Invite a user to be my buddy.
References BUDDY_FLAG_BUD_REQ_SENT, BuddyApiAdd(), and BuddyRosterT::uFlags.
Referenced by HLBListInviteBuddy().
DIRTYCODE_API int32_t BuddyApiConfig (BuddyApiRefT * pState, const char * pSame, uint32_t uLocality)
Config the language, initial same product identifier and locale for translating title name.
\param *pState      - reference pointer
\param *pSame       - "same product" identifier string
\param  uLocality   - This users locale, used for translating title names.
\return int32_t     - error code (zero=success, negative=error)
\version 01/20/2002 (GWS)
References BuddyApiRefT::bPeriod, BuddyApiRefT::bReconnect, BUDDY_ERROR_NONE, BuddyApiRefT::iProd, BuddyApiRefT::strSame, TagFieldDupl(), and BuddyApiRefT::uLocale.
Referenced by HLBApiInitialize().
DIRTYCODE_API int32_t BuddyApiConnect (BuddyApiRefT * pState, const char * pServer, int32_t iPort, int32_t iTimeout, const char * pLKey, const char * pRsrc, BuddyApiCallbackT * pCallback, void * pCalldata)
Connect to the buddy server.
Parameters
*pState - reference pointer
*pServer - buddy server hostname
iPort - buddy server port
iTimeout - connection timeout in seconds; cannot be zero if reconnect required.
*pLKey - session key (or username:password for dev)
*pRsrc - Resource (domain/sub-domain) uniquely identified product.
*pCallback - completion callback function
*pCalldata - callback data
Returns
int32_t - error code (zero=success, negative=error)
Version
01/20/2002 (GWS)
References BUDDY_ERROR_NONE, BUDDY_SERV_CONN, BuddyApiDisconnect(), BuddyApiPrintf, ds_strnzcpy(), BuddyApiRefT::iConnectTimeout, BuddyApiRefT::iPort, BuddyApiRefT::iShow, LOBBYAPI_LocalizerTokenCreateLocalityString, NULL, BuddyApiRefT::pAries, BuddyApiRefT::pConnData, BuddyApiRefT::pConnProc, BuddyApiRefT::pHost, BuddyApiRefT::pLKey, ProtoAriesTick(), ProtoNameAsync(), BuddyApiRefT::pRsrc, BuddyApiRefT::pServer, BuddyApiRefT::strDomain, BuddyApiRefT::strLogin, BuddyApiRefT::strProduct, BuddyApiRefT::strRelease, BuddyApiRefT::strSame, TagFieldClear, TagFieldDupl(), TagFieldSetString(), BuddyApiRefT::uLocale, BuddyApiRefT::uRandom, and BuddyApiRefT::uTimeout.
Referenced by _BuddyApiReconnect(), and HLBApiConnect().
DIRTYCODE_API BuddyApiRefT* BuddyApiCreate2 (BuddyMemAllocT * pAlloc, BuddyMemFreeT * pFree, const char * pProduct, const char * pRelease, int32_t iRefMemGroup, void * pRefMemGroupUserData)
Create a new buddy interface client.
Parameters
*pAlloc - alloc function to use (optional)
*pFree - free function to use (optional)
*pProduct - product id (product-platform-year)
*pRelease - product release (year4-month2-day2)
iRefMemGroup - mem group to use for ref (zero=default)
*pRefMemGroupUserData - pointer to user data associated with mem group
Returns
BuddyApiRefT * - state pointer (pass to other functions) (NULL=failed)
Version
01/20/2002 (GWS)
References BUDDY_FORWARD_FLAG_UNKNOWN, BUDDYAPI_MEMID, BuddyApiPrintf, DirtyMemAlloc(), DirtyMemFree(), DirtyMemGroupEnter(), DirtyMemGroupLeave(), DirtyMemGroupQuery(), BuddyApiRefT::iMemGroup, BuddyApiRefT::iRefMemGroup, BuddyApiRefT::iSeqn, NULL, BuddyApiRefT::pAries, BuddyApiRefT::pBuddyAlloc, BuddyApiRefT::pBuddyFree, BuddyApiRefT::pMemGroupUserData, BuddyApiRefT::pRefMemGroupUserData, ProtoAriesCreate(), ProtoAriesSecure(), pState, BuddyApiRefT::strProduct, BuddyApiRefT::strRelease, TagFieldDupl(), and BuddyApiRefT::uForwardFlags.
DIRTYCODE_API void BuddyApiDebug (BuddyApiRefT * pState, void * pDebugData, void(*)(void *pData, const char *pText) pDebugProc)
Assign the debug callback.
Parameters
*pState - reference pointer
*pDebugData - user data for callback
*pDebugProc - user callback
Version
01/20/2002 (GWS)
References BuddyApiRefT::pDebugData, and BuddyApiRefT::pDebugProc.
Referenced by HLBApiSetDebugFunction().
DIRTYCODE_API int32_t BuddyApiDel (BuddyApiRefT * pState, BuddyRosterT * pBuddy, BuddyApiCallbackT * pCallback, void * pCalldata, int32_t iTimeout)
Add a user to the buddy roster.
Parameters
*pState - reference pointer
*pBuddy - buddy record
*pCallback - callback
*pCalldata - callback data
iTimeout - time out
Returns
int32_t - zero=success, negative=error
Version
01/20/2002 (GWS)
References BUDDY_ERROR_BADPARM, BUDDY_ERROR_NONE, BUDDY_ERROR_NOTUSER, BUDDY_FLAG_BUDDY, BUDDY_FLAG_IGNORE, BUDDY_FLAG_WATCH, CB_DELUSER, NULL, BuddyApiRefT::pDisp, BuddyApiRefT::strDomain, BuddyRosterT::strUser, TagFieldClear, TagFieldSetNumber(), TagFieldSetString(), and BuddyRosterT::uFlags.
DIRTYCODE_API void BuddyApiDestroy (BuddyApiRefT * pState)
Destroy an existing client.
Parameters
*pState - reference pointer
Version
01/20/2002 (GWS)
References BUDDYAPI_MEMID, BuddyApiDisconnect(), BuddyApiFlush(), DirtyMemFree(), HostentT::Free, BuddyApiRefT::iRefMemGroup, NULL, BuddyApiRefT::pAries, BuddyApiRefT::pHost, BuddyApiRefT::pRefMemGroupUserData, and ProtoAriesDestroy().
Referenced by HLBApiDestroy().
DIRTYCODE_API int32_t BuddyApiDisconnect (BuddyApiRefT * pState)
Disconnect from the buddy server.
Parameters
*pState - reference pointer
Returns
int32_t - error code (zero=success, negative=error)
Version
01/20/2002 (GWS)
References BuddyApiRefT::bReconnect, BUDDY_ERROR_NONE, BUDDY_SERV_DISC, BUDDY_SERV_IDLE, BUDDY_SERV_ONLN, BuddyApiFlush(), HostentT::Free, BuddyApiRefT::iStat, NULL, BuddyApiRefT::pAries, BuddyApiRefT::pConnProc, BuddyApiRefT::pHost, and ProtoAriesUnconnect().
Referenced by BuddyApiConnect(), BuddyApiDestroy(), BuddyApiUpdate(), and HLBApiDisconnect().
DIRTYCODE_API char* BuddyApiDomain (BuddyApiRefT * pState)
Return the current Domain, as set in this api. Domain is the resource minus extra stuff at end that distinguishes servers.
Parameters
*pState - reference pointer
Returns
char * - Domain String .
References BuddyApiRefT::strDomain.
DIRTYCODE_API BuddyRosterT* BuddyApiFind (BuddyApiRefT * pState, const char * pUser)
Find a user in the buddy roster.
Parameters
*pState - reference pointer
*pUser - name of buddy
Returns
BuddyRosterT * - matching record (NULL=no match)
Version
01/20/2002 (GWS)
References DispListGet(), HashStrFind(), NULL, BuddyApiRefT::pDisp, and BuddyApiRefT::pHash.
Referenced by BuddyApiGetUserSessionID(), and HLBListGetBuddyByName().
DIRTYCODE_API int32_t BuddyApiFindUsers (BuddyApiRefT * pState, const char * pUserPattern, BuddyApiCallbackT * pCallback, void * pCalldata, int32_t iTimeout)
Request a search of users, of names starting with the pUserPattern. Min 3 chars.
Parameters
*pState - reference pointer
*pUserPattern - User name pattern to search. Min 3 characters, server add the wildcard.
*pCallback - Callback function to be called when search is completed.
*pCalldata - User data or context that will be passed back to caller in the callback.
iTimeout - timeout in seconds for command to completed. Ignored (no t/o) if 0.
Returns
int32_t - BUDDY_ERROR_NONE if request was sent to server.
References BUDDY_ERROR_BADPARM, BUDDY_MAX_USERS_FOUND, CB_FINDUSER, BuddyApiRefT::foundUsers, BuddyApiRefT::iFoundUsersCount, BuddyApiRefT::strDomain, TagFieldClear, TagFieldSetNumber(), TagFieldSetString(), and USCH_FIXED_ID.
Referenced by HLBApiFindUsers().
DIRTYCODE_API void BuddyApiFlush (BuddyApiRefT * pState)
Flush the roster from memory.
Parameters
*pState - reference pointer
Version
01/20/2002 (GWS)
References BUDDY_MSG_ROSTER, BUDDYAPI_MEMID, DispListDel(), DispListDestroy(), HasherDestroy(), HasherFlush(), BuddyApiMsgT::iCode, BuddyApiMsgT::iKind, BuddyApiRefT::iMemGroup, BuddyApiMsgT::iType, NULL, BuddyApiRefT::pBuddyDelData, BuddyApiRefT::pBuddyDelProc, BuddyApiRefT::pBuddyFree, BuddyApiMsgT::pData, BuddyApiRefT::pDisp, BuddyApiRefT::pHash, BuddyApiRefT::pListData, BuddyApiRefT::pListProc, BuddyApiRefT::pMemGroupUserData, and pState.
Referenced by BuddyApiDestroy(), and BuddyApiDisconnect().
DIRTYCODE_API int32_t BuddyApiGameInvite (BuddyApiRefT * pState, BuddyRosterT * pBuddy, BuddyApiCallbackT * pCallback, void * pCalldata, int32_t iTimeout, int32_t iSessionId, const char * pGameInviteState)
Invite a user to play Cross Game –Xbox Only!
References BUDDY_FLAG_GAME_INVITE_SENT, CB_GAMEINVITE, BuddyApiRefT::pRsrc, BuddyApiRefT::strSEID, BuddyApiRefT::strTitleName, BuddyRosterT::strUser, TagFieldClear, TagFieldSetNumber(), TagFieldSetString(), and BuddyRosterT::uFlags.
Referenced by HLBListGameInviteBuddy().
DIRTYCODE_API int32_t BuddyApiGetForwarding (BuddyApiRefT * pState, unsigned * puForwardingFlags, char * strEmail)
Get email and other forwarding states, if already loaded from server.
Parameters
*pState - ptr to API State.
*puForwardingFlags - Returned enable flags. Ignore if return code is "pending".
*strEmail - The email address will be copied to this string, if set.
Returns
- int32_t HLB_ERROR_NONE if ok, HLB_ERROR_PEND if not loaded yet.
References BUDDY_ERROR_NONE, BUDDY_ERROR_PEND, BUDDY_FORWARD_FLAG_UNKNOWN, ds_strnzcpy(), NULL, BuddyApiRefT::strEmail, and BuddyApiRefT::uForwardFlags.
Referenced by HLBApiGetEmailForwarding().
DIRTYCODE_API int32_t BuddyApiGetMyTitleName (BuddyApiRefT * pState, const char * pLang, const int32_t iBufSize, char * pTitleName)
Get the "Official" title name for this game. pLang ignored for now–defaults to English.
Get the "Official" title name for this game. pLang ignored for now–defaults to English.
References BUDDY_ERROR_MISSING, ds_strnzcpy(), and BuddyApiRefT::strTitleName.
Referenced by HLBApiGetMyTitleName().
DIRTYCODE_API int32_t BuddyApiGetTitleName (BuddyApiRefT * pState, const uint32_t uTitleId, const int32_t iBufSize, char * pTitleName)
Get the "Official" Xbox title name for a given title id, based on my locale-language.
Get the "Official" Xbox title name for a given title id, based on my locale-language.
References BUDDY_ERROR_MISSING.
Referenced by HLBApiGetTitleName().
DIRTYCODE_API int32_t BuddyApiGetUserSessionID (BuddyApiRefT * pState, const char * strGamertag, char * sSessionID, const int32_t iBufSize)
Get this users game session id.
References BUDDY_ERROR_MISSING, BUDDY_ERROR_NONE, BuddyApiFind(), ds_strnzcpy(), NULL, and BuddyRosterT::strSEID.
Referenced by HLBListGetGameSessionID().
int32_t BuddyApiJoinGame (BuddyApiRefT * pState, BuddyRosterT * pBuddy, BuddyApiCallbackT * pCallback, void * pCalldata, int32_t iTimeout)
Join my buddy, wherever he is –he must be in another game and joinable.
References BUDDY_ERROR_UNSUPPORTED.
Referenced by HLBBudJoinGame().
DIRTYCODE_API void BuddyApiPresDiff (BuddyApiRefT * pState, const char * pDiff, const char * pLang)
Setup information for different products.
Parameters
*pState - reference pointer
*pDiff - string intended for different products
*pLang - language of string
Version
03/10/2002 (GWS)
References BuddyApiRefT::strPresDiff, and TagFieldSetString().
Referenced by HLBApiPresenceDiff().
DIRTYCODE_API void BuddyApiPresExFlags (BuddyApiRefT * pState, uint32_t uFlags)
Add extra, client specific, info to the Presence.
Parameters
*pState - reference pointer
uFlags - Flags to set in presence. Will show up in Buddies presence.
Version
11/18/2003 (TE)
References BuddyApiRefT::uPresExFlags.
Referenced by HLBApiPresenceSend(), and HLBApiPresenceVOIPSend().
DIRTYCODE_API void BuddyApiPresExtra (BuddyApiRefT * pState, const char * strPresenceExtra)
Set addition string to users presence, will be sent to buddies when BuddyApiPresSend is called.
Parameters
*pState - reference pointer
strPresenceExtra - String to set in presence. Will show up in Buddies presence.
References BuddyApiRefT::strPresExtra, and TagFieldDupl().
Referenced by HLBApiPresenceExtra().
DIRTYCODE_API void BuddyApiPresInit (BuddyApiRefT * pState)
Prepare to send our presence information to the server.
Parameters
*pState - reference pointer
Version
03/10/2002 (GWS)
References BuddyApiRefT::strPresDiff, BuddyApiRefT::strPresSame, and BuddyApiRefT::uPresExFlags.
DIRTYCODE_API void BuddyApiPresJoinable (BuddyApiRefT * pState, int32_t bOn)
Set/Reset the I am joinable bit for Xbox –so other games can join/meet me.
Parameters
*pState - reference pointer
*bOn - 1 to set it on, 0 to turn it off.
References BuddyApiRefT::bPresJoinable.
Referenced by HLBApiPresenceJoinable().
DIRTYCODE_API void BuddyApiPresNoText (BuddyApiRefT * pState)
Set flag to set no text capability to server -if dont support text messages. Will be sent to server on next send (e.g. BuddyApiPresSend).
Parameters
*pState - reference pointer
References BuddyApiRefT::bPresNoText.
Referenced by HLBApiOverrideConstants().
DIRTYCODE_API void BuddyApiPresSame (BuddyApiRefT * pState, const char * pSame)
Set the presence information intended for the same product.
Parameters
*pState - reference pointer
*pSame - string indended for same product
Version
03/10/2002 (GWS)
References BuddyApiRefT::strPresSame, BuddyApiRefT::strSame, and TagFieldDupl().
Referenced by HLBApiPresenceSame(), and HLBApiPresenceSend().
DIRTYCODE_API int32_t BuddyApiPresSend (BuddyApiRefT * pState, const char * pRsrc, int32_t iShow, int32_t iDelay, int32_t bDontAutoRefreshRoster)
Prepare to send our presence information to the server.
Parameters
*pState - reference pointer
*pRsrc - (optional) resource
iShow - show state (BUDDY_STAT_CHAT ... BUDDY_STAT_PASS)
iDelay - milliseconds to delay before sending (0=send now)
bDontAutoRefreshRoster –Stop refresh of roster, even if going CHAT from PASSive.
Returns
int32_t - error code (zero=success, negative=error)
Version
01/20/2002 (GWS)
References BUDDY_ERROR_NONE, BUDDY_STAT_CHAT, BUDDY_STAT_GAME, BUDDY_STAT_PASS, BuddyApiRoster(), BuddyApiRefT::iShow, BuddyApiRefT::pAries, BuddyApiRefT::pListData, BuddyApiRefT::pListProc, ProtoAriesTick(), BuddyApiRefT::strPresSend, TagFieldClear, TagFieldSetString(), and BuddyApiRefT::uPresTick.
Referenced by HLBApiPresenceJoinable(), HLBApiPresenceOffline(), HLBApiPresenceSend(), HLBApiPresenceSendSetPresence(), HLBApiPresenceVOIPSend(), HLBApiResume(), and HLBApiSuspend().
DIRTYCODE_API void BuddyApiRecv (BuddyApiRefT * pState, BuddyApiCallbackT * pCallback, void * pCalldata)
Set the receive callback.
Parameters
*pState - reference pointer
*pCallback - receive callback
*pCalldata - callback user data
Version
01/20/2002 (GWS)
References BuddyApiRefT::pMesgData, and BuddyApiRefT::pMesgProc.
DIRTYCODE_API void BuddyApiRefreshTitle (BuddyApiRefT * pBudRef, BuddyRosterT * pBuddy)
Referenced by HLBBudGetTitle().
DIRTYCODE_API void BuddyApiRegisterBuddyChangeCallback (BuddyApiRefT * pState, BuddyApiBuddyChangeCallbackT * pCallback, void * pCalldata)
Register a callback when buddy changes state – this include presence change or game notifications.
Parameters
*pState - reference pointer
*pCallback - callback function for when change occur.
*pCalldata - callback user data
References BuddyApiRefT::pBuddyChangeData, and BuddyApiRefT::pBuddyChangeProc.
DIRTYCODE_API void BuddyApiRegisterBuddyDelCallback (BuddyApiRefT * pState, BuddyApiDelCallbackT * pDelCallback, void * pCalldata)
Register optional callback for client to free user ref ptr, when buddy is being deleted from mem. BuddyApi will call this, just prior to freeing the buddy memory.
Parameters
*pState - reference pointer
*pDelCallback - callback function for when change occur.
*pCalldata - callback user data
References BuddyApiRefT::pBuddyDelData, and BuddyApiRefT::pBuddyDelProc.
DIRTYCODE_API char* BuddyApiResource (BuddyApiRefT * pState)
Return the resource name set in this api.
Parameters
*pState - reference pointer
Returns
char * - Resource String .
References BuddyApiRefT::pRsrc.
Referenced by HLBListSendChatMsg(), HLBListSendMsgToGroup(), and HLBMsgListMsgInject().
DIRTYCODE_API int32_t BuddyApiRespondBuddy (BuddyApiRefT * pState, BuddyRosterT * pBuddy, BuddyInviteResponseTypeE eResponse, BuddyApiCallbackT * pCallback, void * pCalldata, int32_t iTimeout)
send the Invite Response.
References BUDDY_ERROR_BADPARM, BUDDY_ERROR_NONE, BUDDY_FLAG_BUD_REQ_RECEIVED, BUDDY_FLAG_BUD_REQ_SENT, BUDDY_FLAG_BUDDY, BUDDY_FLAG_IGNORE, BUDDY_INVITE_RESPONSE_ACCEPT, BUDDY_INVITE_RESPONSE_BLOCK, BUDDY_INVITE_RESPONSE_REJECT, BUDDY_INVITE_RESPONSE_REVOKE, BuddyApiPrintf, CB_BUDRESP, CB_DELUSER, BuddyRosterT::strUser, and BuddyRosterT::uFlags.
Referenced by HLBListAnswerInvite(), and HLBListCancelAllInvites().
DIRTYCODE_API int32_t BuddyApiRespondGame (BuddyApiRefT * pState, BuddyRosterT * pBuddy, BuddyInviteResponseTypeE eResponse, BuddyApiCallbackT * pCallback, void * pCalldata, int32_t iTimeout, int32_t iSessionId)
Respond to game invite requests. pBuddy is null for a cancel of ALL invites sent.
References BUDDY_ERROR_BADPARM, BUDDY_FLAG_GAME_INVITE_ACCEPTED, BUDDY_INVITE_RESPONSE_ACCEPT, BUDDY_INVITE_RESPONSE_REJECT, BUDDY_INVITE_RESPONSE_REMOVE, BUDDY_INVITE_RESPONSE_REVOKE, BUDDY_MASK_GAME_INVITE, BUDDY_MASK_GAME_REJECT_ONLY, BUDDY_MASK_GAME_REVOKE_ONLY, CB_GAMERESP, BuddyApiRefT::pRsrc, BuddyApiRefT::strTitleName, BuddyRosterT::strUser, TagFieldClear, TagFieldSetNumber(), TagFieldSetString(), and BuddyRosterT::uFlags.
Referenced by HLBListAnswerGameInvite(), and HLBListCancelAllInvites().
DIRTYCODE_API void BuddyApiResumeXDK (BuddyApiRefT * pState)
Referenced by HLBApiResume().
DIRTYCODE_API DispListRef* BuddyApiRoster (BuddyApiRefT * pState, BuddyApiCallbackT * pCallback, void * pCalldata)
Get the roster from the server.
Parameters
*pState - reference pointer
*pCallback - callback
*pCalldata - callback data
Returns
Returns a displist reference
Version
01/20/2002 (GWS)
References BuddyApiRefT::bEndRoster, DispListDirty(), BuddyApiRefT::pDisp, BuddyApiRefT::pListData, BuddyApiRefT::pListProc, ROSTER_BUDDY, ROSTER_IGNORE, BuddyApiRefT::strDomain, TagFieldClear, TagFieldSetNumber(), TagFieldSetString(), and USERFWD_FIXED_ID.
Referenced by BuddyApiPresSend(), and HLBApiResume().
DIRTYCODE_API DispListRef* BuddyApiRosterList (BuddyApiRefT * pState)
Return the current roster display list.
Parameters
*pState - reference pointer
Returns
Returns a displist reference (NULL=nothing allocated)
Version
01/20/2002 (GWS)
References BuddyApiRefT::pDisp.
DIRTYCODE_API int32_t BuddyApiSend (BuddyApiRefT * pState, const char * pMesg, BuddyApiCallbackT * pCallback, void * pCalldata, int32_t iTimeout)
Send a message to a remote user.
Parameters
*pState - reference pointer
*pMesg - message packet
*pCallback - callback
*pCalldata - callback data
iTimeout - time out
Returns
int32_t - error code (zero=success, negative=error)
Version
01/20/2002 (GWS)
Referenced by HLBListSendChatMsg().
DIRTYCODE_API int32_t BuddyApiSetForwarding (BuddyApiRefT * pState, unsigned uForwardingFlags, const char * strEmail, BuddyApiCallbackT * pCallback, void * pCalldata, int32_t iTimeout)
Turn email forwarding on or off, and set email address.
Parameters
*pState - pointer to API State.
uForwardingFlags - turn forwarding on or off by presence of bits in flag.
*strEmail - the email address to set it to. Will be set even if bEnable is off, due to server issue.
*pCallback * - callback to get status of operation.
*pCalldata - user context for callback.
iTimeout - time out
Returns
- int32_t - Return code– HLB_ERROR_NONE if ok, HLB_ERROR_BADPARAM if params not there.
References BUDDY_ERROR_BADPARM, BUDDY_FORWARD_FLAG_EMAIL, CB_SETFWD, ds_strnzcpy(), NULL, BuddyApiRefT::strDomain, BuddyApiRefT::strEmail, TagFieldClear, TagFieldSetNumber(), TagFieldSetString(), and BuddyApiRefT::uForwardFlags.
Referenced by HLBApiSetEmailForwarding().
DIRTYCODE_API int32_t BuddyApiSetGameInviteSessionID (BuddyApiRefT * pState, const char * sSessionID)
Set my Session id, for an xbox game invite.
References BUDDY_ERROR_NONE, ds_strnzcpy(), and BuddyApiRefT::strSEID.
Referenced by HLBListSetGameInviteSessionID().
DIRTYCODE_API int32_t BuddyApiStatus (BuddyApiRefT * pState)
Return the current connection status.
Parameters
*pState - reference pointer
Returns
BUDDY_SERV_xxxx
Version
03/20/2002 (GWS)
References BuddyApiRefT::iStat.
Referenced by HLBApiPresenceOffline().
DIRTYCODE_API void BuddyApiSuspendXDK (BuddyApiRefT * pState)
Referenced by HLBApiSuspend().
DIRTYCODE_API unsigned BuddyApiUpdate (BuddyApiRefT * pState)
Handle periodic update, and return the aries game tick.
Parameters
*pState - reference pointer
Returns
unsigned - aries game tick.
Version
01/20/2002 (GWS)
References _BuddyApiReconnect(), HostentT::addr, BuddyApiRefT::bEndRoster, BuddyApiRefT::bReconnect, BUDDY_ERROR_FULL, BUDDY_ERROR_NONE, BUDDY_ERROR_NOTUSER, BUDDY_ERROR_OFFLINE, BUDDY_FLAG_BUD_REQ_RECEIVED, BUDDY_FLAG_BUD_REQ_SENT, BUDDY_FLAG_BUDDY, BUDDY_FLAG_IGNORE, BUDDY_FLAG_PEND, BUDDY_FLAG_WATCH, BUDDY_FORWARD_FLAG_EMAIL, BUDDY_FORWARD_FLAG_UNKNOWN, BUDDY_MSG_ADDUSER, BUDDY_MSG_ADMIN, BUDDY_MSG_AUTHORIZE, BUDDY_MSG_BROADCAST, BUDDY_MSG_BUD_INVITE, BUDDY_MSG_DELUSER, BUDDY_MSG_ENDROSTER, BUDDY_MSG_GAME_INVITE, BUDDY_MSG_ROSTER, BUDDY_MSG_SEND, BUDDY_MSG_SET_FORWARDING, BUDDY_MSG_USERS, BUDDY_SERV_DISC, BUDDY_SERV_NAME, BUDDY_SERV_ONLN, BUDDY_SERV_RECN, BUDDY_SERV_TIME, BUDDYAPI_MEMID, BuddyApiDisconnect(), BuddyApiPrintf, BuddyApiRefT::Callback, CB_ADDUSER, CB_BROADCAST, CB_BUDRESP, CB_DELUSER, CB_FINDUSER, CB_GAMEINVITE, CB_GAMERESP, CB_MAX, CB_SEND, CB_SETFWD, DispListDel(), DispListDirty(), DispListIndex(), DispListOrder(), HostentT::Done, ds_stricmp(), HostentT::Free, HashStrAdd(), HashStrDel(), BuddyApiMsgT::iCode, BuddyApiRefT::iFoundUsersCount, BuddyApiMsgT::iKind, BuddyApiRefT::iMemGroup, BuddyRosterT::iPend, BuddyApiRefT::iPort, BuddyApiRefT::iRostListCount, BuddyApiRefT::iStat, BuddyApiRefT::iType, BuddyApiMsgT::iType, NULL, BuddyApiRefT::pAries, BuddyApiRefT::pBuddyDelData, BuddyApiRefT::pBuddyDelProc, BuddyApiRefT::pBuddyFree, BuddyApiRefT::pCallData, BuddyApiRefT::pCallProc, BuddyApiRefT::pConnData, BuddyApiRefT::pConnProc, BuddyApiMsgT::pData, BuddyApiRefT::pDebugProc, BuddyApiRefT::pDisp, BuddyApiRefT::pHash, BuddyApiRefT::pHost, BuddyApiRefT::pListData, BuddyApiRefT::pListProc, BuddyApiRefT::pMemGroupUserData, BuddyApiRefT::pMesgData, BuddyApiRefT::pMesgProc, PROTOARIES_SECURE_SSL, ProtoAriesConnect(), ProtoAriesPeek(), ProtoAriesRecv(), ProtoAriesSecure(), ProtoAriesSend(), ProtoAriesTick(), ProtoAriesUnconnect(), ProtoAriesUpdate(), BuddyApiRefT::pServer, pState, ROSTER_IGNORE, BuddyApiRefT::strEmail, BuddyApiRefT::strLogin, BuddyApiRefT::strTitleName, BuddyRosterT::strUser, TagFieldDupl(), TagFieldFind(), TagFieldGetNumber(), TagFieldGetString(), BuddyRosterT::uFlags, BuddyApiRefT::uForwardFlags, BuddyApiRefT::uPresTick, USCH_FIXED_ID, USERFWD_FIXED_ID, and BuddyApiRefT::uTimeout.
Referenced by HLBApiUpdate().
DIRTYCODE_API BuddyApiUserT* BuddyApiUserFound (BuddyApiRefT * pState, int32_t iItem)
Return users found from FindUser request. Allows client to iterate list of returned users. Should be called after callback from BuddyApiFindUsers has returned with a succes status.
Parameters
*pState - reference pointer
iItem -int32_t - Zero based item number in list.
Returns
return code – *BuddyApiUserT -user name and domain, null if not responed yet, or item not there.
References BUDDY_MAX_USERS_FOUND, BuddyApiRefT::foundUsers, BuddyApiUserT::name, and NULL.
Referenced by HLBApiUserFound().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:31