DirtySock: userlistapixboxone.cpp File Reference
userlistapixboxone.cpp File Reference
See userlistapi.h.
#include "DirtySDK/platform.h"
#include <xdk.h>
#include <collection.h>
#include "DirtySDK/misc/userlistapi.h"
#include "DirtySDK/misc/xboxone/userlistapixboxone.h"
#include "DirtySDK/dirtysock.h"
#include "DirtySDK/dirtysock/dirtyerr.h"
#include "DirtySDK/dirtysock/dirtylib.h"
#include "DirtySDK/dirtysock/dirtymem.h"
#include "DirtySDK/dirtysock/netconn.h"
#include "DirtySDK/proto/protohttp.h"
#include "DirtySDK/util/jsonparse.h"
#include "DirtySDK/util/utf8.h"
Data Structures
struct UserListApiPlatformRequestListT
flags for data synchronization
struct UserListApiResultT
result struct
struct UserListApiRequestT
structure to store in the queue of requests
struct UserListApiPlatformUserContextT
platform context and operation objects for MS queries
struct UserListApiIsFriendQueueT
struct UserListApiRefT
module state
Macros
#define USERLISTAPI_READ_BUFFER_SIZE (2*64)
#define USERLISTAPI_AUTH_TOKEN_SIZE (16 * 1024)
#define USERLISTAPI_REQUEST_PATH_SIZE (512)
#define USERLISTAPI_ISFRIEND_PATH "https://social.xboxlive.com/users/xuid(%llu)/people/xuid(%llu)"
#define USERLISTAPI_HTTP_READ_BUFFER_SIZE (2*1024)
#define USERLISTAPI_NOT_IN_PEOPLE_LIST_ERROR_CODE (1016)
#define USERLISTAPI_MYSELF_ERROR_CODE (1017)
#define USERLISTAPI_ASYNC_TIMOUT_MS (20000)
#define HOME_MENU_TITLE_ID (714681658)
Typedefs
typedef enum
UserListApiRequestTypeE UserListApiRequestTypeE
query types
typedef struct
UserListApiPlatformRequestListT UserListApiPlatformRequestListT
flags for data synchronization
typedef struct UserListApiRequestT UserListApiRequestT
structure to store in the queue of requests
typedef struct
UserListApiPlatformUserContextT UserApiPlatformUserContextT
platform context and operation objects for MS queries
typedef struct
UserListApiIsFriendQueueT UserListApiIsFriendQueueT
Enumerations
enum UserListApiRequestTypeE {
USERLISTAPI_REQUEST_TYPE_FRIENDS,
USERLISTAPI_REQUEST_TYPE_BLOCKED,
USERLISTAPI_REQUEST_TYPE_FRIENDS_OF_FRIEND,
USERLISTAPI_REQUEST_TYPE_MUTED,
USERLISTAPI_REQUEST_TYPE_ISFRIENDS,
USERLISTAPI_REQUEST_TYPE_ISBLOCKED
}
query types
Functions
void _UserListApiGetPriorityTitle (IVectorView< PresenceDeviceRecord^>^presenceDeviceRecordList, PresenceDeviceRecord^&refOutDeviceRecord, PresenceTitleRecord^&refOutTitleRecord)
Choose the most relevant title from the list provided. The logic should be identical to the equivalent method in userapi.
void _UserListApiProcessIsFriend (UserListApiRefT *pRef)
Process IsFriend requests by cleaning up previously completed operations and starting queued ones.
UserListApiRefT * UserListApiCreate (uint32_t uMaxResponseSize)
Startup UserListApi module.
void UserListApiDestroy (UserListApiRefT *pRef)
Shutdown UserListApi module.
int32_t UserListApiRegisterUpdateEvent (UserListApiRefT *pRef, uint32_t uUserIndex, UserListApiNotifyTypeE eType, UserListApiUpdateCallbackT *pNotifyCb, void *pUserData)
Set the callback used for registering userlist update event.
int32_t UserListApiIsFriendAsync (UserListApiRefT *pRef, uint32_t uUserIndex, DirtyUserT *pUser, UserListApiIsAQueryCallbackT *pNotifyCb, void *pUserData)
Updates UserListApiXboxOne module.
int32_t UserListApiIsBlockedAsync (UserListApiRefT *pRef, uint32_t uUserIndex, DirtyUserT *pUser, UserListApiIsAQueryCallbackT *pNotifyCb, void *pUserData)
Stub for UserListApiIsBlockedAsync()
void UserListApiUpdate (UserListApiRefT *pRef)
Updates UserListApi module.
int32_t UserListApiStatus (UserListApiRefT *pRef, int32_t iSelect, void *pBuf, int32_t iBufSize)
Query status of module.
int32_t UserListApiControl (UserListApiRefT *pRef, int32_t iControl, int32_t iValue, int32_t iValue2, void *pValue)
Control behavior of module.
int32_t UserListApiGetListAsync (UserListApiRefT *pRef, uint32_t uUserIndex, UserListApiTypeE eType, int32_t iLimit, int32_t iOffset, UserListApiFiltersT *filter, UserListApiCallbackT *pNotifyCb, uint32_t uTypeMask, void *pUserData)
Retrieve a list of friends or blocked users from PSN.
void UserListApiCancelAll (UserListApiRefT *pRef)
Cancels all active requests.
Detailed Description
See userlistapi.h.
Attention
Copyright (c) Electronic Arts 2013
Version
1.0 25/04/2013 (amakoukji) First Version
Macro Definition Documentation
#define HOME_MENU_TITLE_ID (714681658)
Referenced by _UserListApiGetPriorityTitle().
#define USERLISTAPI_ASYNC_TIMOUT_MS (20000)
Referenced by UserListApiUpdate().
#define USERLISTAPI_AUTH_TOKEN_SIZE (16 * 1024)
#define USERLISTAPI_HTTP_READ_BUFFER_SIZE (2*1024)
Referenced by UserListApiUpdate().
#define USERLISTAPI_ISFRIEND_PATH "https://social.xboxlive.com/users/xuid(%llu)/people/xuid(%llu)"
Referenced by UserListApiIsFriendAsync().
#define USERLISTAPI_MYSELF_ERROR_CODE (1017)
Referenced by UserListApiUpdate().
#define USERLISTAPI_NOT_IN_PEOPLE_LIST_ERROR_CODE (1016)
Referenced by UserListApiUpdate().
#define USERLISTAPI_READ_BUFFER_SIZE (2*64)
Referenced by UserListApiUpdate().
#define USERLISTAPI_REQUEST_PATH_SIZE (512)
Referenced by UserListApiIsFriendAsync().
Typedef Documentation
typedef struct UserListApiPlatformUserContextT UserApiPlatformUserContextT
platform context and operation objects for MS queries
typedef struct UserListApiIsFriendQueueT UserListApiIsFriendQueueT
typedef struct UserListApiPlatformRequestListT UserListApiPlatformRequestListT
flags for data synchronization
typedef struct UserListApiRequestT UserListApiRequestT
structure to store in the queue of requests
typedef enum UserListApiRequestTypeE UserListApiRequestTypeE
query types
Enumeration Type Documentation
enum UserListApiRequestTypeE
query types
Enumerator
USERLISTAPI_REQUEST_TYPE_FRIENDS
USERLISTAPI_REQUEST_TYPE_BLOCKED
USERLISTAPI_REQUEST_TYPE_FRIENDS_OF_FRIEND
USERLISTAPI_REQUEST_TYPE_MUTED
USERLISTAPI_REQUEST_TYPE_ISFRIENDS
USERLISTAPI_REQUEST_TYPE_ISBLOCKED
Function Documentation
void _UserListApiGetPriorityTitle (IVectorView< PresenceDeviceRecord^>^ presenceDeviceRecordList, PresenceDeviceRecord^& refOutDeviceRecord, PresenceTitleRecord^& refOutTitleRecord)
Choose the most relevant title from the list provided. The logic should be identical to the equivalent method in userapi.
Parameters
presenceDeviceRecordList - list of active title presence data
refOutTitleRecord - Highest priority title, or nullptr if failed
refOutDeviceRecord - The device presence record that contains the highest priority title
Version
04/24/2014 (amakoukji)
References FALSE, HOME_MENU_TITLE_ID, and TRUE.
Referenced by UserListApiUpdate().
void _UserListApiProcessIsFriend (UserListApiRefT * pRef)
Process IsFriend requests by cleaning up previously completed operations and starting queued ones.
Parameters
*pRef - pointer to the UserListApiRefT
Version
05/08/2015 (amakoukji)
References DirtyMemFree(), UserListApiIsADataT::eIsaType, UserListApiIsADataT::Error, UserListApiRefT::iMemGroup, NetPrintf, UserListApiIsFriendQueueT::pAssociatedResult, UserListApiRefT::pHttp, UserListApiResultT::pIsAQueryNotifyCb, UserListApiRefT::pIsFriendRequestQueue, UserListApiRefT::pMemGroupUserData, UserListApiResultT::pNext, UserListApiIsFriendQueueT::pNext, ProtoHttpControl(), ProtoHttpGet(), UserListApiResultT::pUserData, UserListApiResultT::refResultFriend, UserListApiResultT::refResultPresence, UserListApiResultT::refResultProfile, UserListApiRefT::ResultList, UserListApiIsFriendQueueT::strRequest, USERLISTAPI_ERROR_UNKNOWN, USERLISTAPI_IS_FRIENDS, USERLISTAPI_IS_TYPE_UNKNOWN, USERLISTAPI_MEMID, and UserListApiIsFriendQueueT::uUserIndex.
Referenced by UserListApiUpdate().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:34:34