DirtySock: jsonformat.c File Reference
jsonformat.c File Reference
This module formats simple JSON, in a linear fashion, using a character buffer that the client provides.
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include "DirtySDK/platform.h"
#include "DirtySDK/dirtysock/dirtylib.h"
#include "DirtySDK/util/jsonformat.h"
Macros
#define JSON_HEADER_LEN (22)
#define JSON_MAX_TAG_LENGTH (128)
#define JSON_MAX_FLOAT_LENGTH (128)
#define JSON_MAX_DATE_LENGTH (32)
Functions
void JsonInit (char *pBuffer, int32_t iBufLen, unsigned char uFlags)
Initialize the Json Buffer. This MUST be called prior to any other calls. Client can allocate the buffer on stack, but should not access it directly. (see JsonData()).
void JsonBufSizeIncrease (char *pBuffer, int32_t iNewBufLen)
Notify the jsonformat API that the buffer size was increased.
char * JsonFinish (char *pBuffer)
Signal completion of output to this buffer. Clear the JSON API hidden data.
int32_t JsonObjectStart (char *pBuffer, const char *pName)
Start a JSON object, to which you can add other objects or elements. Must be ended with JsonObjectEnd.
int32_t JsonObjectEnd (char *pBuffer)
End the current object – must have an outstanding open tag.
int32_t JsonArrayStart (char *pBuffer, const char *pName)
Start a JSON array, to which you can add other objects or elements. Must be ended with JsonArrayEnd.
int32_t JsonArrayEnd (char *pBuffer)
End the current array – must have an outstanding open array.
int32_t JsonAddStr (char *pBuffer, const char *pElemName, const char *pValue)
Adds a string element.
int32_t JsonAddInt (char *pBuffer, const char *pElemName, int64_t iValue)
Add an integer element.
int32_t JsonAddNum (char *pBuffer, const char *pElemName, const char *pFormatSpec, float fValue)
Add a complete, contained decimal element. Builds start and end tag. Nothing can be appended to this tag. Format it using formatSpec.
int32_t JsonAddDate (char *pBuffer, const char *pElemName, uint32_t uEpochDate)
Add a date (will be encoded as a string; use JsonAddInteger for integer encoding)
char * JsonFormatVPrintf (char *pJsonBuff, int32_t iBufLen, const char *pFormat, va_list pFmtArgs)
Takes a format string and variable parameter list and formats into syntax correct JSON. The "v" (variable args) version can be called by other functions that use "..." in the their prototype.
char * JsonFormatPrintf (char *pJsonBuff, int32_t iBufLen, const char *pFormat,...)
Takes a format string and variable parameter list and formats into syntax correct JSON.
Detailed Description
This module formats simple JSON, in a linear fashion, using a character buffer that the client provides.
Attention
Copyright (c) Electronic Arts 2012.
Note
    When JsonInit() is called, a 24-bytes header is added at the beginning of the
    client-provided buffer. The header is an ascii string that looks like this:
        <AAAAAAAABBBBBBBBCCDD />
            where:
                AAAAAAAA is the offset field
                BBBBBBBB is the buffer size field
                CC is the indent field
                DD is the flag field
    Those first 24 bytes are replaced by whitespaces when JsonFinish() is called.
    Required buffer capacity for json = ??? length(JSON) + 1.
    That means if length(buffer) <= length(JSON), buffer-overrun occurs.
Version
12/11/2012 (jbrookes) First Version, based on XmlFormat
Macro Definition Documentation
#define JSON_HEADER_LEN (22)
Referenced by JsonFinish(), and JsonInit().
#define JSON_MAX_DATE_LENGTH (32)
Referenced by JsonAddDate().
#define JSON_MAX_FLOAT_LENGTH (128)
Referenced by JsonAddNum().
#define JSON_MAX_TAG_LENGTH (128)
Function Documentation
char* JsonFormatVPrintf (char * pJsonBuff, int32_t iBufLen, const char * pFormat, va_list pFmtArgs)
Takes a format string and variable parameter list and formats into syntax correct JSON. The "v" (variable args) version can be called by other functions that use "..." in the their prototype.
Parameters
*pJsonBuff - JSON output buffer
iBufLen - length of Json output buffer (negative=append to existing buffer)
*pFormat - printf style format string
pFmtArgs - variable argument list (use va_start / va_end to get)
Returns
char * - pointer to formatted buffer
Version
12/11/2012 (jbrookes)
References ds_timeinsecs(), JSON_FL_WHITESPACE, JsonFinish(), and JsonInit().
Referenced by JsonFormatPrintf().
void JsonInit (char * pBuffer, int32_t iBufLen, unsigned char uFlags)
Initialize the Json Buffer. This MUST be called prior to any other calls. Client can allocate the buffer on stack, but should not access it directly. (see JsonData()).
Parameters
*pBuffer - buffer to which JSON will be written.
iBufLen – size of buffer passed in.
uFlags - encoding flags (JSONFORMAT_FL_xxx)
Version
12/11/2012 (jbrookes)
References ds_snzprintf(), and JSON_HEADER_LEN.
Referenced by JsonFormatVPrintf().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:45