DirtySock: DirtyMem
DirtyMem
DirtySock
Macros
#define BUDDYAPI_MEMID ('budd')
#define HLBUDAPI_MEMID ('hbud')
#define XNFRIENDS_MEMID ('xnfr')
#define PCISP_MEMID ('pcip')
#define COMMSER_MEMID ('cser')
#define COMMSRP_MEMID ('csrp')
#define COMMTCP_MEMID ('ctcp')
#define COMMUDP_MEMID ('cudp')
#define DIRTYAUTH_MEMID ('dath')
#define DIRTYCERT_MEMID ('dcrt')
#define DIRTYLSP_MEMID ('dlsp')
#define DIRTYSESSMGR_MEMID ('dsmg')
#define DIRTYWEBAPI_MEMID ('weba')
#define DIRTYEVENT_DISP_MEMID ('semd')
#define SOCKET_MEMID ('dsoc')
#define NETCONN_MEMID ('ncon')
#define FRIENDAPI_MEMID ('frnd')
#define CONNAPI_MEMID ('conn')
#define NETGAMEDIST_MEMID ('ngdt')
#define NETGAMEDISTSERV_MEMID ('ngds')
#define NETGAMELINK_MEMID ('nglk')
#define NETGAMEUTIL_MEMID ('ngut')
#define DIRTYGRAPH_MEMID ('dgph')
#define DIRTYJPG_MEMID ('djpg')
#define DIRTYPNG_MEMID ('dpng')
#define LOBBYLAN_MEMID ('llan')
#define USERAPI_MEMID ('uapi')
#define USERLISTAPI_MEMID ('ulst')
#define WEBLOG_MEMID ('wlog')
#define PRIVILEGEAPI_MEMID ('priv')
#define PROTOADVT_MEMID ('padv')
#define PROTOARIES_MEMID ('pari')
#define PROTOHTTP_MEMID ('phtp')
#define HTTPSERV_MEMID ('hsrv')
#define HTTPMGR_MEMID ('hmgr')
#define PROTOMANGLE_MEMID ('pmgl')
#define PROTONAME_MEMID ('pnam')
#define PROTOPING_MEMID ('ppng')
#define PINGMGR_MEMID ('lpmg')
#define PROTOSSL_MEMID ('pssl')
#define PROTOSTREAM_MEMID ('pstr')
#define PROTOTUNNEL_MEMID ('ptun')
#define PROTOUDP_MEMID ('pudp')
#define PROTOUPNP_MEMID ('pupp')
#define PROTOWEBSOCKET_MEMID ('webs')
#define DISPLIST_MEMID ('ldsp')
#define HASHER_MEMID ('lhsh')
#define SORT_MEMID ('lsor')
#define QOSAPI_MEMID ('dqos')
#define VOIP_MEMID ('voip')
#define VOIPTUNNEL_MEMID ('vtun')
#define NETRSRC_MEMID ('nrsc')
#define WEBOFFER_MEMID ('webo')
#define PLAYERSYNCSERVICE_MEMID ('plss')
#define TELEMETRYAPI_MEMID ('telm')
#define DirtyMemDebugAlloc(_pMem, _iSize, _iMemModule, _iMemGroup, _pMemGroupUserData) {;}
#define DirtyMemDebugFree(_pMem, _iSize, _iMemModule, _iMemGroup, _pMemGroupUserData) {;}
Functions
DIRTYCODE_API void DirtyMemGroupEnter (int32_t iGroup, void *pMemGroupUserData)
enter memory group
DIRTYCODE_API void DirtyMemGroupLeave (void)
leave memory group
DIRTYCODE_API void DirtyMemGroupQuery (int32_t *pMemGroup, void **ppMemGroupUserData)
get current memory group
DIRTYCODE_API void * DirtyMemAlloc (int32_t iSize, int32_t iMemModule, int32_t iMemGroup, void *pMemGroupUserData)
allocate memory
DIRTYCODE_API void DirtyMemFree (void *pMem, int32_t iMemModule, int32_t iMemGroup, void *pMemGroupUserData)
free memory
Detailed Description
Macro Definition Documentation
#define BUDDYAPI_MEMID ('budd')
All DirtySock modules have their memory identifiers defined here.
Referenced by BuddyApiCreate2(), BuddyApiDestroy(), BuddyApiFlush(), and BuddyApiUpdate().
#define COMMSER_MEMID ('cser')
#define COMMSRP_MEMID ('csrp')
Referenced by CommSRPConstruct(), and CommSRPDestroy().
#define COMMTCP_MEMID ('ctcp')
Referenced by CommTCPConstruct(), and CommTCPDestroy().
#define COMMUDP_MEMID ('cudp')
Referenced by CommUDPConstruct(), and CommUDPDestroy().
#define CONNAPI_MEMID ('conn')
Referenced by ConnApiCreate2(), and ConnApiDestroy().
#define DIRTYAUTH_MEMID ('dath')
Referenced by DirtyAuthCreate(), DirtyAuthDestroy(), and DirtyAuthGetToken().
#define DIRTYCERT_MEMID ('dcrt')
Referenced by DirtyCertCreate(), and DirtyCertDestroy().
#define DIRTYEVENT_DISP_MEMID ('semd')
#define DIRTYGRAPH_MEMID ('dgph')
Referenced by DirtyGraphCreate(), and DirtyGraphDestroy().
#define DIRTYJPG_MEMID ('djpg')
Referenced by DirtyJpgCreate(), and DirtyJpgDestroy().
#define DIRTYLSP_MEMID ('dlsp')
#define DirtyMemDebugAlloc (_pMem, _iSize, _iMemModule, _iMemGroup, _pMemGroupUserData) {;}
#define DirtyMemDebugFree (_pMem, _iSize, _iMemModule, _iMemGroup, _pMemGroupUserData) {;}
#define DIRTYPNG_MEMID ('dpng')
Referenced by DirtyPngCreate(), DirtyPngDecodeImage(), and DirtyPngDestroy().
#define DIRTYSESSMGR_MEMID ('dsmg')
#define DIRTYWEBAPI_MEMID ('weba')
#define DISPLIST_MEMID ('ldsp')
Referenced by DispListCreate(), and DispListDestroy().
#define FRIENDAPI_MEMID ('frnd')
Referenced by FriendApiCreate(), and FriendApiDestroy().
#define HASHER_MEMID ('lhsh')
Referenced by HasherCreate(), HasherDestroy(), and HasherExpand().
#define HLBUDAPI_MEMID ('hbud')
Referenced by HLBApiCreate(), HLBApiCreate2(), and HLBApiDestroy().
#define HTTPMGR_MEMID ('hmgr')
Referenced by HttpManagerCreate(), HttpManagerDestroy(), and HttpManagerFree().
#define HTTPSERV_MEMID ('hsrv')
Referenced by ProtoHttpServCreate(), and ProtoHttpServDestroy().
#define LOBBYLAN_MEMID ('llan')
Referenced by LobbyLanCreate2(), LobbyLanDestroy(), and LobbyLanLeaveGame().
#define NETCONN_MEMID ('ncon')
Referenced by NetConnCommonShutdown(), NetConnCommonStartup(), NetConnShutdown(), and NetConnStartup().
#define NETGAMEDIST_MEMID ('ngdt')
Referenced by NetGameDistCreate(), and NetGameDistDestroy().
#define NETGAMEDISTSERV_MEMID ('ngds')
Referenced by NetGameDistServCreate(), and NetGameDistServDestroy().
#define NETGAMELINK_MEMID ('nglk')
Referenced by NetGameLinkCreate(), NetGameLinkCreateStream(), NetGameLinkDestroy(), and NetGameLinkDestroyStream().
#define NETGAMEUTIL_MEMID ('ngut')
Referenced by NetGameUtilCreate(), and NetGameUtilDestroy().
#define NETRSRC_MEMID ('nrsc')
Referenced by NetResourceCache(), NetResourceCreate(), NetResourceDestroy(), and NetResourceFetch().
#define PCISP_MEMID ('pcip')
#define PINGMGR_MEMID ('lpmg')
Referenced by PingManagerCreate(), and PingManagerDestroy().
#define PLAYERSYNCSERVICE_MEMID ('plss')
#define PRIVILEGEAPI_MEMID ('priv')
Referenced by PrivilegeApiCheckPrivilegesAsyncWithUi(), PrivilegeApiCreate(), and PrivilegeApiDestroy().
#define PROTOADVT_MEMID ('padv')
Referenced by ProtoAdvtAnnounce(), ProtoAdvtConstruct(), and ProtoAdvtDestroy().
#define PROTOARIES_MEMID ('pari')
Referenced by ProtoAriesCreate(), and ProtoAriesDestroy().
#define PROTOHTTP_MEMID ('phtp')
Referenced by HttpCallback::OnDataAvailable(), ProtoHttpCreate(), SequentialStream::Write(), and SequentialStream::~SequentialStream().
#define PROTOMANGLE_MEMID ('pmgl')
Referenced by ProtoMangleConnect2(), and ProtoMangleCreate().
#define PROTONAME_MEMID ('pnam')
#define PROTOPING_MEMID ('ppng')
Referenced by ProtoPingCreate(), ProtoPingDestroy(), and ProtoPingResponse().
#define PROTOSSL_MEMID ('pssl')
Referenced by ProtoSSLClrCACerts(), ProtoSSLCreate(), ProtoSSLDestroy(), ProtoSSLShutdown(), ProtoSSLStartup(), and ProtoSSLValidateAllCA().
#define PROTOSTREAM_MEMID ('pstr')
Referenced by ProtoStreamCreate(), and ProtoStreamDestroy().
#define PROTOTUNNEL_MEMID ('ptun')
Referenced by ProtoTunnelCreate(), and ProtoTunnelDestroy().
#define PROTOUDP_MEMID ('pudp')
Referenced by ProtoUdpCreate(), and ProtoUdpDestroy().
#define PROTOUPNP_MEMID ('pupp')
Referenced by ProtoUpnpCreate(), and ProtoUpnpDestroy().
#define PROTOWEBSOCKET_MEMID ('webs')
Referenced by ProtoWebSocketCreate(), and ProtoWebSocketDestroy().
#define QOSAPI_MEMID ('dqos')
Referenced by QosApiCreate(), and QosApiDestroy().
#define SOCKET_MEMID ('dsoc')
Referenced by _SocketAddrMapAlloc(), SocketCreate(), SocketDestroy(), SocketHostnameCacheCreate(), SocketHostnameCacheDestroy(), SocketHostnameListProcess(), SocketLookup(), SocketPacketQueueCreate(), and SocketPacketQueueDestroy().
#define SORT_MEMID ('lsor')
Referenced by LobbyMSort().
#define TELEMETRYAPI_MEMID ('telm')
#define USERAPI_MEMID ('uapi')
Referenced by UserApiControl(), UserApiCreate(), UserApiPlatCreateData(), and UserApiPlatDestroyData().
#define USERLISTAPI_MEMID ('ulst')
Referenced by _UserListApiProcessIsFriend(), UserApiUpdate(), UserListApiCancelAll(), UserListApiCreate(), UserListApiGetListAsync(), UserListApiIsFriendAsync(), and UserListApiUpdate().
#define VOIP_MEMID ('voip')
Referenced by VoipCommonShutdown(), VoipCommonStartup(), VoipConnectionShutdown(), VoipConnectionStartup(), VoipHeadsetCreate(), and VoipHeadsetDestroy().
#define VOIPTUNNEL_MEMID ('vtun')
Referenced by VoipTunnelCreate(), and VoipTunnelDestroy().
#define WEBLOG_MEMID ('wlog')
Referenced by WebLogCreate(), and WebLogDestroy().
#define WEBOFFER_MEMID ('webo')
Referenced by WebOfferCreate(), and WebOfferDestroy().
#define XNFRIENDS_MEMID ('xnfr')
Function Documentation
DIRTYCODE_API void* DirtyMemAlloc (int32_t iSize, int32_t iMemModule, int32_t iMemGroup, void * pMemGroupUserData)
allocate memory
Referenced by _SocketAddrMapAlloc(), BuddyApiCreate2(), CommSRPConstruct(), CommTCPConstruct(), CommUDPConstruct(), ConnApiCreate2(), DirtyAuthCreate(), DirtyAuthGetToken(), DirtyCertCreate(), DirtyGraphCreate(), DirtyJpgCreate(), DirtyPngCreate(), DirtyPngDecodeImage(), DispListCreate(), FriendApiCreate(), HasherCreate(), HasherExpand(), HLBApiCreate(), HLBApiCreate2(), HttpManagerCreate(), LobbyLanCreate2(), LobbyMSort(), NetConnCommonStartup(), NetConnStartup(), NetGameDistCreate(), NetGameDistServCreate(), NetGameLinkCreate(), NetGameLinkCreateStream(), NetGameUtilCreate(), NetResourceCreate(), NetResourceFetch(), HttpCallback::OnDataAvailable(), PingManagerCreate(), PrivilegeApiCheckPrivilegesAsyncWithUi(), PrivilegeApiCreate(), ProtoAdvtAnnounce(), ProtoAdvtConstruct(), ProtoAriesCreate(), ProtoHttpCreate(), ProtoHttpServCreate(), ProtoMangleConnect2(), ProtoMangleCreate(), ProtoPingCreate(), ProtoSSLCreate(), ProtoSSLStartup(), ProtoStreamCreate(), ProtoTunnelCreate(), ProtoUdpCreate(), ProtoUpnpCreate(), ProtoWebSocketCreate(), QosApiCreate(), SocketCreate(), SocketHostnameCacheCreate(), SocketLookup(), SocketPacketQueueCreate(), UserApiCreate(), UserApiPlatCreateData(), UserListApiCreate(), UserListApiGetListAsync(), UserListApiIsFriendAsync(), VoipCommonStartup(), VoipConnectionStartup(), VoipHeadsetCreate(), VoipTunnelCreate(), WebLogCreate(), WebOfferCreate(), and SequentialStream::Write().
DIRTYCODE_API void DirtyMemFree (void * pMem, int32_t iMemModule, int32_t iMemGroup, void * pMemGroupUserData)
free memory
Referenced by _SocketAddrMapAlloc(), _UserListApiProcessIsFriend(), BuddyApiCreate2(), BuddyApiDestroy(), CommSRPDestroy(), CommTCPDestroy(), CommUDPDestroy(), ConnApiCreate2(), ConnApiDestroy(), DirtyAuthDestroy(), DirtyCertCreate(), DirtyCertDestroy(), DirtyGraphDestroy(), DirtyJpgDestroy(), DirtyPngDecodeImage(), DirtyPngDestroy(), DispListDestroy(), FriendApiDestroy(), HasherDestroy(), HLBApiCreate(), HLBApiDestroy(), HttpManagerDestroy(), HttpManagerFree(), LobbyLanCreate2(), LobbyLanDestroy(), LobbyLanLeaveGame(), LobbyMSort(), NetConnCommonShutdown(), NetConnShutdown(), NetGameDistDestroy(), NetGameDistServDestroy(), NetGameLinkDestroy(), NetGameLinkDestroyStream(), NetGameUtilDestroy(), NetResourceCache(), NetResourceCreate(), NetResourceDestroy(), NetResourceFetch(), HttpCallback::OnDataAvailable(), PingManagerCreate(), PingManagerDestroy(), PrivilegeApiCheckPrivilegesAsyncWithUi(), PrivilegeApiDestroy(), ProtoAdvtConstruct(), ProtoAdvtDestroy(), ProtoAriesDestroy(), ProtoHttpServDestroy(), ProtoPingDestroy(), ProtoPingResponse(), ProtoSSLClrCACerts(), ProtoSSLDestroy(), ProtoSSLShutdown(), ProtoSSLValidateAllCA(), ProtoStreamCreate(), ProtoStreamDestroy(), ProtoTunnelCreate(), ProtoTunnelDestroy(), ProtoUdpDestroy(), ProtoUpnpCreate(), ProtoUpnpDestroy(), ProtoWebSocketDestroy(), QosApiDestroy(), SocketDestroy(), SocketHostnameCacheDestroy(), SocketHostnameListProcess(), SocketLookup(), SocketPacketQueueDestroy(), UserApiControl(), UserApiPlatDestroyData(), UserApiUpdate(), UserListApiCancelAll(), UserListApiUpdate(), VoipCommonShutdown(), VoipCommonStartup(), VoipConnectionShutdown(), VoipHeadsetDestroy(), VoipTunnelDestroy(), WebLogDestroy(), WebOfferCreate(), WebOfferDestroy(), SequentialStream::Write(), and SequentialStream::~SequentialStream().
DIRTYCODE_API void DirtyMemGroupEnter (int32_t iMemGroup, void * pMemGroupUserData)
enter memory group
enter memory group
Parameters
iMemGroup - group id
*pMemGroupUserData - User-provided data pointer
Returns
None.
Version
10/13/2005 (jbrookes)
11/19/2008 (mclouatre) Adding pMemGroupUserData to mem groups
References DIRTYMEM_MAXGROUPS, DirtyMemInfoT::iMemGroup, NetPrintf, and DirtyMemInfoT::pMemGroupUserData.
Referenced by BuddyApiCreate2(), ConnApiOnline(), NetGameDistServAddClient(), NetGameUtilConnect(), ProtoAriesListen(), ProtoAriesUpdate(), ProtoPingControl(), and ProtoSSLAccept().
DIRTYCODE_API void DirtyMemGroupLeave (void)
leave memory group
leave memory group
Version
10/13/2005 (jbrookes)
References NetPrintf.
Referenced by BuddyApiCreate2(), ConnApiOnline(), NetGameDistServAddClient(), NetGameUtilConnect(), ProtoAriesListen(), ProtoAriesUpdate(), ProtoPingControl(), and ProtoSSLAccept().
DIRTYCODE_API void DirtyMemGroupQuery (int32_t * pMemGroup, void ** ppMemGroupUserData)
get current memory group
get current memory group
Parameters
*pMemGroup - [OUT param] pointer to variable to be filled with mem group id
**ppMemGroupUserData - [OUT param] pointer to variable to be filled with pointer to user data
Returns
None.
Version
10/13/2005 (jbrookes)
11/18/2008 (mclouatre) returned values now passed in [OUT] parameters
References DirtyMemInfoT::iMemGroup, NULL, and DirtyMemInfoT::pMemGroupUserData.
Referenced by BuddyApiCreate2(), CommSRPConstruct(), CommTCPConstruct(), CommUDPConstruct(), ConnApiCreate2(), DirtyAuthCreate(), DirtyCertCreate(), DirtyGraphCreate(), DirtyJpgCreate(), DirtyPngCreate(), DispListCreate(), FriendApiCreate(), HasherCreate(), HLBApiCreate(), HLBApiCreate2(), HttpManagerCreate(), LobbyLanCreate2(), LobbyMSort(), NetConnCommonStartup(), NetGameDistCreate(), NetGameDistServCreate(), NetGameLinkCreate(), NetGameUtilCreate(), NetResourceCreate(), PingManagerCreate(), PrivilegeApiCreate(), ProtoAdvtConstruct(), ProtoAriesCreate(), ProtoHttpCreate(), ProtoHttpServCreate(), ProtoPingCreate(), ProtoSSLCreate(), ProtoSSLStartup(), ProtoStreamCreate(), ProtoTunnelCreate(), ProtoUdpCreate(), ProtoUpnpCreate(), ProtoWebSocketCreate(), QosApiCreate(), SocketCreate(), UserApiCreate(), UserListApiCreate(), VoipCommonStartup(), VoipTunnelCreate(), WebLogCreate(), WebOfferCreate(), SequentialStream::Write(), and SequentialStream::~SequentialStream().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:21