DirtySock: ProtoWebSocket
ProtoWebSocket
Proto
Macros
#define PROTOWEBSOCKET_CLOSEREASON_BASE (1000)
#define PROTOWEBSOCKET_CLOSEREASON_NORMAL (PROTOWEBSOCKET_CLOSEREASON_BASE+0)
#define PROTOWEBSOCKET_CLOSEREASON_GOINGAWAY (PROTOWEBSOCKET_CLOSEREASON_BASE+1)
#define PROTOWEBSOCKET_CLOSEREASON_PROTOCOLERROR (PROTOWEBSOCKET_CLOSEREASON_BASE+2)
#define PROTOWEBSOCKET_CLOSEREASON_UNSUPPORTEDDATA (PROTOWEBSOCKET_CLOSEREASON_BASE+3)
#define PROTOWEBSOCKET_CLOSEREASON_NOSTATUSRECVD (PROTOWEBSOCKET_CLOSEREASON_BASE+5)
#define PROTOWEBSOCKET_CLOSEREASON_ABNORMALCLOSURE (PROTOWEBSOCKET_CLOSEREASON_BASE+6)
#define PROTOWEBSOCKET_CLOSEREASON_INVALIDFRAMEDATA (PROTOWEBSOCKET_CLOSEREASON_BASE+7)
#define PROTOWEBSOCKET_CLOSEREASON_POLICYVIOLATION (PROTOWEBSOCKET_CLOSEREASON_BASE+8)
#define PROTOWEBSOCKET_CLOSEREASON_MESSAGETOOBIG (PROTOWEBSOCKET_CLOSEREASON_BASE+9)
#define PROTOWEBSOCKET_CLOSEREASON_MANDATORYEXT (PROTOWEBSOCKET_CLOSEREASON_BASE+10)
#define PROTOWEBSOCKET_CLOSEREASON_INTERNALERR (PROTOWEBSOCKET_CLOSEREASON_BASE+11)
#define PROTOWEBSOCKET_CLOSEREASON_SERVICERESTART (PROTOWEBSOCKET_CLOSEREASON_BASE+12)
#define PROTOWEBSOCKET_CLOSEREASON_TRYAGAINLATER (PROTOWEBSOCKET_CLOSEREASON_BASE+13)
#define PROTOWEBSOCKET_CLOSEREASON_TLSHANDSHAKE (PROTOWEBSOCKET_CLOSEREASON_BASE+15)
#define PROTOWEBSOCKET_CLOSEREASON_MAX (PROTOWEBSOCKET_CLOSEREASON_TLSHANDSHAKE)
#define PROTOWEBSOCKET_CLOSEREASON_COUNT (PROTOWEBSOCKET_CLOSEREASON_MAX-PROTOWEBSOCKET_CLOSEREASON_BASE+1)
#define PROTOWEBSOCKET_CLOSEREASON_UNKNOWN (PROTOWEBSOCKET_CLOSEREASON_BASE+100)
Typedefs
typedef struct ProtoWebSocketRefT ProtoWebSocketRefT
opaque module state definition
Functions
DIRTYCODE_API ProtoWebSocketRefT * ProtoWebSocketCreate (int32_t iBufSize)
Allocate a WebSocket connection and prepare for use.
DIRTYCODE_API ProtoWebSocketRefT * ProtoWebSocketCreate2 (void)
Allocate a WebSocket connection and prepare for use: ProtoSSL function signature compatible version.
DIRTYCODE_API void ProtoWebSocketDestroy (ProtoWebSocketRefT *pWebSocket)
Destroy a connection and release state.
DIRTYCODE_API ProtoWebSocketRefT * ProtoWebSocketAccept (ProtoWebSocketRefT *pWebSocket)
Accept an incoming connection.
DIRTYCODE_API ProtoWebSocketRefT * ProtoWebSocketListen (ProtoWebSocketRefT *pWebSocket)
Start listening for an incoming connection.
DIRTYCODE_API int32_t ProtoWebSocketConnect (ProtoWebSocketRefT *pWebSocket, const char *pUrl)
Initiate a connection to a server.
DIRTYCODE_API int32_t ProtoWebSocketConnect2 (ProtoWebSocketRefT *pWebSocket, int32_t iUnused0, const char *pUrl, uint32_t uUnused1, int32_t iUnused2)
Initiate a connection to a server: ProtoSSL function signature compatible version.
DIRTYCODE_API int32_t ProtoWebSocketDisconnect (ProtoWebSocketRefT *pWebSocket)
Disconnect from the server. Note that this is an asynchronous operation. Connection status can be polled with the 'conn' status selector.
DIRTYCODE_API int32_t ProtoWebSocketSend (ProtoWebSocketRefT *pWebSocket, const char *pBuffer, int32_t iLength)
Send data to a server over a WebSocket connection. Stream-type send, TODO describe this better.
DIRTYCODE_API int32_t ProtoWebSocketRecv (ProtoWebSocketRefT *pWebSocket, char *pBuffer, int32_t iLength)
Receive data from a server over a WebSocket connection.
DIRTYCODE_API int32_t ProtoWebSocketStatus (ProtoWebSocketRefT *pWebSocket, int32_t iSelect, void *pBuffer, int32_t iBufSize)
Get module status.
DIRTYCODE_API int32_t ProtoWebSocketControl (ProtoWebSocketRefT *pWebSocket, int32_t iSelect, int32_t iValue, int32_t iValue2, void *pValue)
Control module behavior.
DIRTYCODE_API void ProtoWebSocketUpdate (ProtoWebSocketRefT *pWebSocket)
Give life to module (should be called periodically to allow module to perform work).
Detailed Description
Macro Definition Documentation
#define PROTOWEBSOCKET_CLOSEREASON_ABNORMALCLOSURE (PROTOWEBSOCKET_CLOSEREASON_BASE+6)
#define PROTOWEBSOCKET_CLOSEREASON_BASE (1000)
#define PROTOWEBSOCKET_CLOSEREASON_COUNT (PROTOWEBSOCKET_CLOSEREASON_MAX-PROTOWEBSOCKET_CLOSEREASON_BASE+1)
#define PROTOWEBSOCKET_CLOSEREASON_GOINGAWAY (PROTOWEBSOCKET_CLOSEREASON_BASE+1)
#define PROTOWEBSOCKET_CLOSEREASON_INTERNALERR (PROTOWEBSOCKET_CLOSEREASON_BASE+11)
#define PROTOWEBSOCKET_CLOSEREASON_INVALIDFRAMEDATA (PROTOWEBSOCKET_CLOSEREASON_BASE+7)
#define PROTOWEBSOCKET_CLOSEREASON_MANDATORYEXT (PROTOWEBSOCKET_CLOSEREASON_BASE+10)
#define PROTOWEBSOCKET_CLOSEREASON_MAX (PROTOWEBSOCKET_CLOSEREASON_TLSHANDSHAKE)
#define PROTOWEBSOCKET_CLOSEREASON_MESSAGETOOBIG (PROTOWEBSOCKET_CLOSEREASON_BASE+9)
#define PROTOWEBSOCKET_CLOSEREASON_NORMAL (PROTOWEBSOCKET_CLOSEREASON_BASE+0)
Referenced by ProtoWebSocketDisconnect().
#define PROTOWEBSOCKET_CLOSEREASON_NOSTATUSRECVD (PROTOWEBSOCKET_CLOSEREASON_BASE+5)
#define PROTOWEBSOCKET_CLOSEREASON_POLICYVIOLATION (PROTOWEBSOCKET_CLOSEREASON_BASE+8)
#define PROTOWEBSOCKET_CLOSEREASON_PROTOCOLERROR (PROTOWEBSOCKET_CLOSEREASON_BASE+2)
#define PROTOWEBSOCKET_CLOSEREASON_SERVICERESTART (PROTOWEBSOCKET_CLOSEREASON_BASE+12)
#define PROTOWEBSOCKET_CLOSEREASON_TLSHANDSHAKE (PROTOWEBSOCKET_CLOSEREASON_BASE+15)
#define PROTOWEBSOCKET_CLOSEREASON_TRYAGAINLATER (PROTOWEBSOCKET_CLOSEREASON_BASE+13)
#define PROTOWEBSOCKET_CLOSEREASON_UNKNOWN (PROTOWEBSOCKET_CLOSEREASON_BASE+100)
#define PROTOWEBSOCKET_CLOSEREASON_UNSUPPORTEDDATA (PROTOWEBSOCKET_CLOSEREASON_BASE+3)
Typedef Documentation
typedef struct ProtoWebSocketRefT ProtoWebSocketRefT
opaque module state definition
Function Documentation
DIRTYCODE_API ProtoWebSocketRefT* ProtoWebSocketAccept (ProtoWebSocketRefT * pWebSocket)
Accept an incoming connection.
Parameters
*pWebSocket - websocket module state
Returns
ProtoWebSocketRefT * - new connection, or NULL if no connection
Version
11/26/2012 (jbrookes)
References NULL.
DIRTYCODE_API int32_t ProtoWebSocketConnect (ProtoWebSocketRefT * pWebSocket, const char * pUrl)
Initiate a connection to a server.
Parameters
*pWebSocket - websocket module state
*pUrl - url containing host information; ws:// or wss://
Returns
int32_t - zero=success, else failure
Version
11/26/2012 (jbrookes)
References ds_stricmp(), ProtoWebSocketRefT::eState, ProtoWebSocketRefT::iPort, ProtoWebSocketRefT::iVerbose, NetPrintfVerbose, NetTick(), ProtoWebSocketRefT::pProtoSSL, ProtoHttpUrlParse(), ProtoSSLConnect(), SOCKERR_NONE, ST_CONN, ST_FAIL, ProtoWebSocketRefT::strHost, and ProtoWebSocketRefT::uTimer.
Referenced by ProtoWebSocketConnect2().
DIRTYCODE_API int32_t ProtoWebSocketConnect2 (ProtoWebSocketRefT * pWebSocket, int32_t iUnused0, const char * pUrl, uint32_t uUnused1, int32_t iUnused2)
Initiate a connection to a server: ProtoSSL function signature compatible version.
Parameters
*pWebSocket - websocket module state
iUnused0 - unused
*pUrl - url containing host information; ws:// or wss://
uUnused1 - unused
iUnused2 - unused
Returns
int32_t - zero=success, else failure
Version
03/08/2013 (jbrookes)
References ProtoWebSocketConnect().
DIRTYCODE_API int32_t ProtoWebSocketControl (ProtoWebSocketRefT * pWebSocket, int32_t iSelect, int32_t iValue, int32_t iValue2, void * pValue)
Control module behavior.
Parameters
*pWebSocket - websocket module state
iSelect - control selector
iValue - selector specific
iValue2 - selector specific
*pValue - selector specific
Returns
int32_t - selector specific
Note
Selectors are:
        SELECTOR    DESCRIPTION
        'apnd'      The given buffer will be appended to future headers sent by
                    ProtoWebSocket.  The Accept header in the default header will
                    be omitted.  If there is a User-Agent header included in the
                    append header, it will replace the default User-Agent header.
        'clse'      Send a close message with optional reason (iValue) and data
                    (string passed in pValue)
        'keep'      Set keep-alive timer, in seconds; client sends a 'pong' at this
                    rate to keep connection alive (0 disables; disabled by default)
        'ping'      Send a ping message with optional data (string passed in pValue)
        'pong'      Send a pong message with optional data (string passed in pValue)
        'spam'      Sets debug output verbosity (0...n)
        'time'      Sets ProtoWebSocket client timeout in seconds (default=300s)
Unhandled selectors are passed on to ProtoSSL.
Version
11/30/2012 (jbrookes)
References ProtoWebSocketRefT::iKeepAlive, ProtoWebSocketRefT::iTimeout, ProtoWebSocketRefT::iVerbose, ProtoWebSocketRefT::pProtoSSL, ProtoSSLControl(), PROTOWEBSOCKET_CTRL_PING, and PROTOWEBSOCKET_CTRL_PONG.
DIRTYCODE_API ProtoWebSocketRefT* ProtoWebSocketCreate (int32_t iBufSize)
Allocate a WebSocket connection and prepare for use.
Parameters
iBufSize - websocket buffer size (determines max message size)
Returns
ProtoWebSocketRefT * - module state, or NULL on failure
Version
11/26/2012 (jbrookes)
References DirtyMemAlloc(), DirtyMemGroupQuery(), ProtoWebSocketRefT::iMemGroup, ProtoWebSocketRefT::iOutMax, ProtoWebSocketRefT::iTimeout, ProtoWebSocketRefT::iVerbose, ProtoWebSocketRefT::iVersion, NetPrintf, NULL, ProtoWebSocketRefT::pMemGroupUserData, ProtoWebSocketRefT::pOutBuf, ProtoWebSocketRefT::pProtoSSL, ProtoSSLCreate(), PROTOWEBSOCKET_BUFSIZE_MIN, PROTOWEBSOCKET_MAXSENDHDR, PROTOWEBSOCKET_MEMID, PROTOWEBSOCKET_PROTOCOLVERS, PROTOWEBSOCKET_TIMEOUT, and ProtoWebSocketDestroy().
Referenced by ProtoWebSocketCreate2().
DIRTYCODE_API ProtoWebSocketRefT* ProtoWebSocketCreate2 (void)
Allocate a WebSocket connection and prepare for use: ProtoSSL function signature compatible version.
Returns
ProtoWebSocketRefT * - module state, or NULL on failure
Version
03/08/2013 (jbrookes)
References PROTOWEBSOCKET_BUFSIZE_MIN, and ProtoWebSocketCreate().
DIRTYCODE_API void ProtoWebSocketDestroy (ProtoWebSocketRefT * pWebSocket)
Destroy a connection and release state.
Parameters
*pWebSocket - websocket module state
Version
11/26/2012 (jbrookes)
References DirtyMemFree(), ProtoWebSocketRefT::iMemGroup, NULL, ProtoWebSocketRefT::pAppendHdr, ProtoWebSocketRefT::pMemGroupUserData, ProtoWebSocketRefT::pOutBuf, ProtoWebSocketRefT::pProtoSSL, ProtoSSLDestroy(), and PROTOWEBSOCKET_MEMID.
Referenced by ProtoWebSocketCreate().
DIRTYCODE_API int32_t ProtoWebSocketDisconnect (ProtoWebSocketRefT * pWebSocket)
Disconnect from the server. Note that this is an asynchronous operation. Connection status can be polled with the 'conn' status selector.
Parameters
*pWebSocket - websocket module state
Returns
int32_t - zero=success, else failure
Version
11/26/2012 (jbrookes)
References ProtoWebSocketRefT::eState, NULL, PROTOWEBSOCKET_CLOSEREASON_NORMAL, and ST_FAIL.
DIRTYCODE_API ProtoWebSocketRefT* ProtoWebSocketListen (ProtoWebSocketRefT * pWebSocket)
Start listening for an incoming connection.
Parameters
*pWebSocket - websocket module state
Returns
ProtoWebSocketRefT * - ?
Version
11/26/2012 (jbrookes)
References NULL.
DIRTYCODE_API int32_t ProtoWebSocketRecv (ProtoWebSocketRefT * pWebSocket, char * pBuffer, int32_t iLength)
Receive data from a server over a WebSocket connection.
Parameters
*pWebSocket - websocket module state
*pBuffer - [out] buffer to receive data
iLength - size of buffer
Returns
int32_t - negative=failure, else number of bytes of data received
Version
11/26/2012 (jbrookes)
References ProtoWebSocketRefT::eState, SOCKERR_NOTCONN, and ST_FAIL.
DIRTYCODE_API int32_t ProtoWebSocketSend (ProtoWebSocketRefT * pWebSocket, const char * pBuffer, int32_t iLength)
Send data to a server over a WebSocket connection. Stream-type send, TODO describe this better.
Parameters
*pWebSocket - websocket module state
*pBuffer - data to send
iLength - amount of data to send
Returns
int32_t - negative=failure, else number of bytes of data sent
Version
11/26/2012 (jbrookes)
References ProtoWebSocketRefT::eState, PROTOWEBSOCKET_OPCODE_BINA, SOCKERR_NOTCONN, and ST_FAIL.
DIRTYCODE_API int32_t ProtoWebSocketStatus (ProtoWebSocketRefT * pWebSocket, int32_t iSelect, void * pBuffer, int32_t iBufSize)
Get module status.
Parameters
*pWebSocket - websocket module state
iSelect - status selector
*pBuffer - [inp/out] buffer, selector specific
iBufSize - size of buffer
Returns
int32_t - selector specific
Note
Selectors are:
    SELECTOR    RETURN RESULT
    'crsn'      returns close reason (PROTOWEBSOCKET_CLOSEREASON_*)
    'essl'      returns protossl error state
    'host'      current host copied to output buffer
    'port'      current port
    'stat'      connection status (-1=not connected, 0=connection in progress, 1=connected)
    'time'      TRUE if the client timed out the connection, else FALSE
Version
11/26/2012 (jbrookes)
References ProtoWebSocketRefT::bTimeout, ds_memcpy(), ds_strnzcpy(), ProtoWebSocketRefT::eState, ProtoWebSocketRefT::iCloseReason, ProtoWebSocketRefT::iCtrlDataLen, ProtoWebSocketRefT::iPort, ProtoWebSocketRefT::iSSLFail, NULL, ProtoWebSocketRefT::pProtoSSL, ProtoSSLStat(), ST_FAIL, ProtoWebSocketRefT::strCtrlData, and ProtoWebSocketRefT::strHost.
DIRTYCODE_API void ProtoWebSocketUpdate (ProtoWebSocketRefT * pWebSocket)
Give life to module (should be called periodically to allow module to perform work).
Parameters
*pWebSocket - websocket module state
Version
11/26/2012 (jbrookes)
References ProtoWebSocketRefT::bDoPong, ProtoWebSocketRefT::bTimeout, ProtoWebSocketRefT::eState, ProtoWebSocketRefT::iCtrlDataLen, ProtoWebSocketRefT::iKeepAlive, ProtoWebSocketRefT::iOutLen, ProtoWebSocketRefT::iOutMax, ProtoWebSocketRefT::iTimeout, ProtoWebSocketRefT::iVerbose, NetPrintf, NetPrintfVerbose, NetPrintWrap, NetTick(), NetTickDiff, NULL, ProtoWebSocketRefT::pOutBuf, ProtoWebSocketRefT::pProtoSSL, ProtoSSLStat(), ProtoSSLUpdate(), ST_CONN, ST_FAIL, ProtoWebSocketRefT::strCtrlData, TRUE, and ProtoWebSocketRefT::uTimer.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:42