DirtySock: NetGameLink
NetGameLink
Game
Data Structures
struct NetGameLinkHistT
structure providing access to ping history
struct NetGameLinkStatT
structure providing access to game/comm stats (in the past, had to be a multiple of 16 bytes to support IOP/EE DMA!)
struct NetGameLinkStreamInpT
struct NetGameLinkStreamT
structure to access network stream with
Macros
#define PING_HISTORY 32
must be a power of 2
#define PING_LENGTH 250
sample every 250 ms
#define PING_DEFAULT 200
default value if no sample available
#define NETGAME_QOS_DURATION_MIN (0)
min/max values for NetGameLink QoS settings
#define NETGAME_QOS_DURATION_MAX (10000)
#define NETGAME_QOS_INTERVAL_MIN (10)
#define NETGAME_QOS_PACKETSIZE_MIN (50)
Typedefs
typedef struct NetGameLinkRefT NetGameLinkRefT
opaque module state
typedef struct NetGameLinkHistT NetGameLinkHistT
structure providing access to ping history
typedef struct NetGameLinkStatT NetGameLinkStatT
structure providing access to game/comm stats (in the past, had to be a multiple of 16 bytes to support IOP/EE DMA!)
typedef struct NetGameLinkStreamT NetGameLinkStreamT
typedef struct
NetGameLinkStreamInpT NetGameLinkStreamInpT
Functions
DIRTYCODE_API typedef int32_t() NetGameLinkStreamSendProc (NetGameLinkStreamT *pStream, int32_t iSubchan, int32_t iKind, void *pBuffer, int32_t iLen)
dist stream send proc
DIRTYCODE_API typedef void() NetGameLinkStreamRecvProc (NetGameLinkStreamT *pStream, int32_t iSubchan, int32_t iKind, void *pBuffer, int32_t iLen)
dist stream recv proc
DIRTYCODE_API NetGameLinkRefT * NetGameLinkCreate (void *comm, int32_t owner, int32_t buflen)
Construct the game client.
DIRTYCODE_API void NetGameLinkDestroy (NetGameLinkRefT *ref)
Destruct the game client.
DIRTYCODE_API void NetGameLinkCallback (NetGameLinkRefT *ref, void *calldata, void(*callproc)(void *calldata, int32_t kind))
Register a callback function.
DIRTYCODE_API int32_t NetGameLinkStatus (NetGameLinkRefT *pRef, int32_t iSelect, int32_t iValue, void *pBuf, int32_t iBufSize)
Return current link status.
DIRTYCODE_API int32_t NetGameLinkSend (NetGameLinkRefT *ref, NetGamePacketT *pkt, int32_t len)
Handle incoming packet stream from upper layer.
DIRTYCODE_API int32_t NetGameLinkPeek (NetGameLinkRefT *ref, NetGamePacketT **pkt)
Peek into the buffer.
DIRTYCODE_API int32_t NetGameLinkPeek2 (NetGameLinkRefT *ref, NetGamePacketT **pkt, uint32_t mask)
Peek into the buffer, for the first packet type matching mask.
DIRTYCODE_API int32_t NetGameLinkRecv (NetGameLinkRefT *ref, NetGamePacketT *buf, int32_t len, uint8_t bDist)
Outgoing packet stream to upper layer.
DIRTYCODE_API int32_t NetGameLinkRecv2 (NetGameLinkRefT *ref, NetGamePacketT *buf, int32_t len, uint32_t mask)
Outgoing packet stream to upper layer.
DIRTYCODE_API int32_t NetGameLinkControl (NetGameLinkRefT *ref, int32_t iSelect, int32_t iValue, void *pValue)
NetGameLink control function. Different selectors control different behaviors.
DIRTYCODE_API uint32_t NetGameLinkUpdate (NetGameLinkRefT *pRef)
Provides NetGameLink with time, at regular interval. Need for streams handling. Also handles QoS stage when during link startup.
DIRTYCODE_API NetGameLinkStreamT * NetGameLinkCreateStream (NetGameLinkRefT *pRef, int32_t iSubChan, int32_t iIdent, int32_t iInpLen, int32_t iOutLen, int32_t iSynLen)
Allocate a stream.
DIRTYCODE_API void NetGameLinkDestroyStream (NetGameLinkRefT *pRef, NetGameLinkStreamT *pStream)
Destroy a stream.
Detailed Description
Macro Definition Documentation
#define NETGAME_QOS_DURATION_MAX (10000)
Referenced by ConnApiControl(), and NetGameLinkControl().
#define NETGAME_QOS_DURATION_MIN (0)
min/max values for NetGameLink QoS settings
Referenced by ConnApiControl(), and NetGameLinkControl().
#define NETGAME_QOS_INTERVAL_MIN (10)
Referenced by ConnApiControl(), ConnApiCreate2(), NetGameLinkControl(), and NetGameLinkCreate().
#define NETGAME_QOS_PACKETSIZE_MIN (50)
Referenced by ConnApiControl(), ConnApiCreate2(), and NetGameLinkControl().
#define PING_DEFAULT 200
default value if no sample available
Referenced by NetGameLinkCreate().
#define PING_HISTORY 32
must be a power of 2
Referenced by NetGameLinkCreate().
#define PING_LENGTH 250
sample every 250 ms
Typedef Documentation
typedef struct NetGameLinkHistT NetGameLinkHistT
structure providing access to ping history
typedef struct NetGameLinkRefT NetGameLinkRefT
opaque module state
typedef struct NetGameLinkStatT NetGameLinkStatT
structure providing access to game/comm stats (in the past, had to be a multiple of 16 bytes to support IOP/EE DMA!)
typedef struct NetGameLinkStreamInpT NetGameLinkStreamInpT
typedef struct NetGameLinkStreamT NetGameLinkStreamT
Function Documentation
DIRTYCODE_API void NetGameLinkCallback (NetGameLinkRefT * ref, void * calldata, void(*)(void *calldata, int32_t kind) callproc)
Register a callback function.
Parameters
*ref - reference pointer
*calldata - caller reference data
*callproc - callback function
Version
12/19/00 (GWS)
References NetGameLinkRefT::m_calldata, and NetGameLinkRefT::m_callproc.
DIRTYCODE_API int32_t NetGameLinkControl (NetGameLinkRefT * ref, int32_t iSelect, int32_t iValue, void * pValue)
NetGameLink control function. Different selectors control different behaviors.
Parameters
*ref - reference pointer
iSelect - status selector (send, sdpt)
iValue - selector-specific value
pValue - selector-specific pointer
Returns
int32_t - selector specific, or negative if failure
Note
selector inputs:
        rlmt: redundant packet size limit
        send: iValue==TRUE to enable sending, iData==FALSE to disable
        slen: none
        sque: none
        sync: iValue==FALSE to disable sync packets, TRUE to enable (default)
selector outputs:
        rlim: 0
        send: TRUE
        slen: current length of send queue
        sque: TRUE if send queue is empty, else FALSE
        sync: zero
Unhandled selectors are passed through to the underlying comm module
Version
07/07/03 (jbrookes)
References COMM_FLAGS_RELIABLE, CommRef::Control, NetGameLinkRefT::m_port, NetGameLinkRefT::m_sendenabled, NetGameLinkRefT::m_syncenabled, CommRef::maxwid, NETGAME_DATAPKT_MAXSIZE, NETGAME_QOS_DURATION_MAX, NETGAME_QOS_DURATION_MIN, NETGAME_QOS_INTERVAL_MIN, NETGAME_QOS_PACKETSIZE_MIN, NetPrintf, NULL, CommRef::Send, TRUE, NetGameLinkRefT::uQosLastSendTime, NetGameLinkRefT::uQosPacketSize, NetGameLinkRefT::uQosPacketsToSend, and NetGameLinkRefT::uQosSendInterval.
Referenced by LobbyLanStatus().
DIRTYCODE_API NetGameLinkRefT* NetGameLinkCreate (void * pCommRef, int32_t owner, int32_t buflen)
Construct the game client.
Parameters
*pCommRef - the connection from NetGameUtilComplete()
owner - if TRUE, NetGameLink will assume ownership of the port (ie, delete it when done)
buflen - length of input buffer
Returns
NetGameLinkRefT * - pointer to new NetGameLinkRef
Version
12/19/00 (GWS)
References NetGameLinkHistT::avg, CommRef::Callback, NetGameLinkHistT::cnt, NetGameLinkStatT::conn, NetGameLinkRefT::crit, DirtyMemAlloc(), DirtyMemGroupQuery(), FALSE, NetGameLinkStatT::isconn, NetGameLinkStatT::isopen, NetGameLinkRefT::iStrmMaxPktSize, NetGameLinkRefT::m_buffer, NetGameLinkRefT::m_bufmax, NetGameLinkRefT::m_memgroup, NetGameLinkRefT::m_memgrpusrdata, NetGameLinkRefT::m_port, NetGameLinkRefT::m_portowner, NetGameLinkRefT::m_rttavg, NetGameLinkRefT::m_rttdev, NetGameLinkRefT::m_sendenabled, NetGameLinkRefT::m_stats, NetGameLinkRefT::m_syncenabled, NetGameLinkHistT::max, NetGameLinkHistT::min, NetCritInit(), NETGAME_DATAPKT_MAXSIZE, NETGAME_QOS_INTERVAL_MIN, NETGAME_STRMPKT_DEFSIZE, NETGAMELINK_MEMID, NetPrintf, NetTick(), NULL, PING_DEFAULT, PING_HISTORY, NetGameLinkStatT::pinghist, NetGameLinkStatT::rcvdhide, NetGameLinkStatT::rcvdlast, CommRef::refptr, CommRef::SendCallback, NetGameLinkStatT::senthide, NetGameLinkStatT::sentlast, NetGameLinkStatT::stattick, TRUE, NetGameLinkRefT::uQosPacketSize, and NetGameLinkRefT::uQosSendInterval.
DIRTYCODE_API NetGameLinkStreamT* NetGameLinkCreateStream (NetGameLinkRefT * pRef, int32_t iSubChan, int32_t iIdent, int32_t iInpLen, int32_t iOutLen, int32_t iSynLen)
Allocate a stream.
Parameters
*pRef - module state reference
iSubChan - number of subchannels (zero for a normal stream)
iIdent - unique stream iIdent
iInpLen - size of input buffer
iOutLen - size of output buffer
iSynLen - size of sync buffer
Returns
NetGameLinkStreamT * - new stream, or NULL if the iIdent was not unique
Version
12/20/00 (GWS)
References DirtyMemAlloc(), NetGameLinkStreamT::iIdent, NetGameLinkStreamT::iInpMaxm, NetGameLinkStreamT::iOutMaxm, NetGameLinkStreamT::iSubchan, NetGameLinkStreamT::iSynMaxm, NetGameLinkRefT::m_memgroup, NetGameLinkRefT::m_memgrpusrdata, NetGameLinkRefT::m_stream, NETGAMELINK_MEMID, NetPrintf, NULL, NetGameLinkStreamT::pClient, NetGameLinkStreamT::pInp, NetGameLinkStreamInpT::pInpData, NetGameLinkStreamT::pNext, NetGameLinkStreamT::pOutData, pRef, NetGameLinkStreamT::pSynData, NetGameLinkStreamT::Recv, and NetGameLinkStreamT::Send.
DIRTYCODE_API void NetGameLinkDestroy (NetGameLinkRefT * ref)
Destruct the game client.
Parameters
*ref - reference pointer
Version
12/19/00 (GWS)
References CommRef::Callback, NetGameLinkRefT::crit, CommRef::Destroy, DirtyMemFree(), NetGameLinkRefT::m_buffer, NetGameLinkRefT::m_memgroup, NetGameLinkRefT::m_memgrpusrdata, NetGameLinkRefT::m_port, NetGameLinkRefT::m_portowner, NetCritKill(), NETGAMELINK_MEMID, and NULL.
DIRTYCODE_API void NetGameLinkDestroyStream (NetGameLinkRefT * pRef, NetGameLinkStreamT * pStream)
Destroy a stream.
Parameters
*pRef - reference pointer
*pStream - pointer to stream to destroy
Version
12/20/00 (GWS)
References DirtyMemFree(), NetGameLinkRefT::m_memgroup, NetGameLinkRefT::m_memgrpusrdata, NetGameLinkRefT::m_stream, NETGAMELINK_MEMID, NULL, NetGameLinkStreamT::pClient, NetGameLinkStreamT::pInp, NetGameLinkStreamT::pNext, NetGameLinkStreamT::pOutData, and NetGameLinkStreamT::pSynData.
DIRTYCODE_API int32_t NetGameLinkPeek (NetGameLinkRefT * ref, NetGamePacketT ** pkt)
Peek into the buffer.
Parameters
*ref - reference pointer
**pkt - (optional) storage for pointer to current packet data
Returns
int32_t - buffer size
Version
12/19/00 (GWS)
References NetGameLinkPeek2().
Referenced by LobbyLanRecvfrom().
DIRTYCODE_API int32_t NetGameLinkPeek2 (NetGameLinkRefT * ref, NetGamePacketT ** pkt, uint32_t mask)
Peek into the buffer, for the first packet type matching mask.
Parameters
*ref - reference pointer
**pkt - (optional) storage for pointer to current packet data
mask - which packet types we want. bitmask, addressed by GAME_PACKET values
Returns
int32_t - buffer size
Version
08/08/11 (jrainy)
References GAME_PACKET_SYNC, NetGamePacketT::head, NetGamePacketHeadT::kind, NetGameLinkRefT::m_buffer, NetGameLinkRefT::m_buflen, NetGameLinkRefT::m_port, NULL, and NetGamePacketHeadT::size.
Referenced by NetGameLinkPeek().
DIRTYCODE_API int32_t NetGameLinkRecv (NetGameLinkRefT * ref, NetGamePacketT * buf, int32_t len, uint8_t bDist)
Outgoing packet stream to upper layer.
Parameters
*ref - reference pointer
*buf - storage for packet list (1 or more)
len - size packet list (1=one packet)
bDist - whether dist packets are to be received. Use FALSE.
Returns
int32_t - 0=no data available, else number of packets received
Version
01/11/10 (jrainy)
References GAME_PACKET_INPUT, GAME_PACKET_INPUT_FLOW, GAME_PACKET_INPUT_META, GAME_PACKET_INPUT_MULTI, GAME_PACKET_INPUT_MULTI_FAT, GAME_PACKET_LINK_STRM, GAME_PACKET_STATS, and NetGameLinkRecv2().
Referenced by NetGameDistServAddClient().
DIRTYCODE_API int32_t NetGameLinkRecv2 (NetGameLinkRefT * ref, NetGamePacketT * buf, int32_t len, uint32_t mask)
Outgoing packet stream to upper layer.
Parameters
*ref - reference pointer
*buf - storage for packet list (1 or more)
len - size packet list (1=one packet)
mask - which packet types we wanted. bitmask, addressed by GAME_PACKET values
Returns
int32_t - 0=no data available, else number of packets received
Version
01/11/10 (jrainy)
References NetGameLinkRefT::crit, ds_memcpy(), GAME_PACKET_SYNC, NetGamePacketT::head, NetGamePacketHeadT::kind, NetGameLinkRefT::m_buffer, NetGameLinkRefT::m_buflen, NetCritEnter(), NetCritLeave(), NetTick(), and NetGamePacketHeadT::size.
Referenced by NetGameLinkRecv().
DIRTYCODE_API int32_t NetGameLinkSend (NetGameLinkRefT * ref, NetGamePacketT * pkt, int32_t len)
Handle incoming packet stream from upper layer.
Parameters
*ref - reference pointer
*pkt - packet list (1 or more)
len - size packet list (1=one packet)
Returns
int32_t - negative=bad error, zero=unable to send now (overflow), positive=bytes sent
Version
12/19/00 (GWS)
References NetGameLinkRefT::crit, NetGamePacketT::head, NetGamePacketHeadT::len, NetGameLinkRefT::m_process, NetCritEnter(), NetCritLeave(), NetPrintf, NetTick(), and NetGamePacketHeadT::size.
Referenced by NetGameDistServAddClient().
DIRTYCODE_API int32_t NetGameLinkStatus (NetGameLinkRefT * pRef, int32_t iSelect, int32_t iValue, void * pBuf, int32_t iBufSize)
Return current link status.
Parameters
*pRef - reference pointer
iSelect - selector
iValue - input value
pBuf - output buffer
iBufSize - output buffer size
Returns
int32_t - selector specific return value
Note
iSelect can be one of the following:
        'qlat' - average latency calculated during the initial qos phase
        'stat' - Fills out a NetGameLinkStatT with QoS info. pBuf=&NetGameLinkStatT, iBufSize=sizeof(NetGameLinkStatT)
Version
12/19/00 (GWS)
References COMM_CONNECTING, COMM_ONLINE, ds_memcpy(), FALSE, NetGameLinkRefT::iQosAvgLate, NetGameLinkStatT::isopen, NetGameLinkStatT::lpacksent_now, NetGameLinkRefT::m_port, NetGameLinkRefT::m_stats, NetTick(), NULL, CommRef::packsent, CommRef::Status, NetGameLinkStatT::tick, NetGameLinkStatT::tickseqn, TRUE, NetGameLinkRefT::uQosPacketsToRecv, and NetGameLinkRefT::uQosPacketsToSend.
Referenced by LobbyLanStatus(), and NetGameDistServAddClient().
DIRTYCODE_API typedef void() NetGameLinkStreamRecvProc (NetGameLinkStreamT * pStream, int32_t iSubchan, int32_t iKind, void * pBuffer, int32_t iLen)
dist stream recv proc
DIRTYCODE_API typedef int32_t() NetGameLinkStreamSendProc (NetGameLinkStreamT * pStream, int32_t iSubchan, int32_t iKind, void * pBuffer, int32_t iLen)
dist stream send proc
DIRTYCODE_API uint32_t NetGameLinkUpdate (NetGameLinkRefT * pRef)
Provides NetGameLink with time, at regular interval. Need for streams handling. Also handles QoS stage when during link startup.
Parameters
*pRef - reference pointer
Returns
uint32_t - zero
Version
01/11/10 (jrainy)
References NetGameLinkRefT::uQosPacketsToRecv, and NetGameLinkRefT::uQosPacketsToSend.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:42