DirtySock: friendapiprivxenon.c File Reference
friendapiprivxenon.c File Reference
Xenon-specific portion of the friend api module.
#include <string.h>
#include <xtl.h>
#include <xonline.h>
#include "DirtySDK/platform.h"
#include "DirtySDK/dirtysock.h"
#include "DirtySDK/dirtysock/dirtymem.h"
#include "DirtySDK/dirtysock/dirtyerr.h"
#include "DirtySDK/dirtysock/netconn.h"
#include "DirtySDK/friend/friendapi.h"
#include "friendapipriv.h"
Data Structures
struct EnumerationT
struct FriendsUpdateT
struct FriendsCollectionT
struct FriendApiRefT
friend api module state
Macros
#define FRIEND_XENON_MIN_QUERY_RETRY_TIME 60000
Typedefs
typedef struct EnumerationT EnumerationT
typedef struct FriendsUpdateT FriendsUpdateT
typedef struct FriendsCollectionT FriendsCollectionT
Functions
FriendApiRefT * FriendApiPrivCreate ()
Create the xenon friendapi object.
void FriendApiPrivUpdate (FriendApiRefT *pFriendApiRef)
Give module time to perform periodic processing.
int32_t FriendApiPrivGetFriendsList (FriendApiRefT *pFriendApiRef, uint32_t uUserIndex, FriendDataT *pFriendsList, void *pRawDataList1, int32_t *pFriendsCount)
Returns the number of friends and the list of friends in the user-provided buffers. Set pFriend to NULL to only find out the number of friends.
int32_t FriendApiPrivStatus (FriendApiRefT *pFriendApiRef, int32_t iSelect, void *pBuf, int32_t iBufSize)
Get status information.
int32_t FriendApiPrivControl (FriendApiRefT *pFriendApiRef, int32_t iControl, int32_t iValue, int32_t iValue2, void *pValue)
Control behavior of module.
void FriendApiPrivDestroy (FriendApiRefT *pFriendApiRef)
Release friend api component if enumeration is done, otherwise queue release of the xenon friend api component.
uint32_t FriendApiPrivIsUserFriend (FriendApiRefT *pFriendApiRef, uint32_t uUserIndex, void *pUserId)
Returns whether a given user is friend.
uint32_t FriendApiPrivIsUserRealFriend (FriendApiRefT *pFriendApiRef, uint32_t uUserIndex, void *pUserId)
Returns whether a given user is a 'real' friend (not pending)
uint32_t FriendApiPrivIsUserBlocked (FriendApiRefT *pFriendApiRef, uint32_t uUserIndex, void *pUserId)
Returns whether a given user is blocked or not. On Xenon, a "blocked" user is a "muted" user.
int32_t FriendApiPrivBlockUser (FriendApiRefT *pFriendApiRef, uint32_t uUserIndex, void *pUserId)
Initiates a block user operation. After calling this function, if the return code is "success", the caller needs to wait for the FRIENDAPI_EVENT_BLOCK_USER_RESULT completion event.
int32_t FriendApiPrivUnblockUser (FriendApiRefT *pFriendApiRef, uint32_t uUserIndex, void *pUserId)
Unblock user.
int32_t FriendApiPrivGetBlockListVersion (FriendApiRefT *pFriendApiRef, uint32_t *pVersion)
Returns the current version of the list of blocked users. Unsupported on Xenon. Always returns 0.
int32_t FriendApiPrivGetBlockList (FriendApiRefT *pFriendApiRef, uint32_t uUserIndex, BlockedUserDataT *pBlockList, int32_t *pUsersCount)
Returns the list of blocked users in the user-provided buffers. Unsupported on Xenon. Always returns an empty list.
Detailed Description
Xenon-specific portion of the friend api module.
Attention
Copyright (c) 2010 Electronic Arts Inc.
Version
04/19/2010 (mclouatre)
Macro Definition Documentation
#define FRIEND_XENON_MIN_QUERY_RETRY_TIME 60000
Typedef Documentation
typedef struct EnumerationT EnumerationT
typedef struct FriendsCollectionT FriendsCollectionT
typedef struct FriendsUpdateT FriendsUpdateT
Function Documentation
int32_t FriendApiPrivBlockUser (FriendApiRefT * pFriendApiRef, uint32_t uUserIndex, void * pUserId)
Initiates a block user operation. After calling this function, if the return code is "success", the caller needs to wait for the FRIENDAPI_EVENT_BLOCK_USER_RESULT completion event.
Parameters
*pFriendApiRef - module reference
uUserIndex - local user index
*pUserId - user to be blocked (pointer to SceNpId)
Returns
int32_t - 0 for success, negative for failure
Version
02/24/2011 (mclouatre)
References FriendApiRefT::bNotifyBlockUserResult, DirtyErrGetName(), NetPrintf, and TRUE.
Referenced by FriendApiBlockUser().
int32_t FriendApiPrivControl (FriendApiRefT * pFriendApiRef, int32_t iControl, int32_t iValue, int32_t iValue2, void * pValue)
Control behavior of module.
Parameters
*pFriendApiRef - module reference
iControl - status selector
iValue - control value
iValue2 - control value
*pValue - control value
Returns
int32_t - selector specific
Note
iControl can be one of the following:
        'alfu' - if iValue=1 set the friend api to surface all MS events
Version
09/25/2014 (amakoukji)
References FriendApiRefT::bNotifyAllFriendUpdates, FALSE, NetPrintf, and TRUE.
Referenced by FriendApiControl().
FriendApiRefT* FriendApiPrivCreate (void)
Create the xenon friendapi object.
Returns
FriendApiRefT* - module reference (NULL = failed)
Version
04/19/2010 (mclouatre)
References FriendApiRefT::common, DirtyMemAlloc(), DirtyMemFree(), DirtyMemGroupQuery(), FriendApiRefT::enumeration, FRIENDAPI_MEMID, EnumerationT::hEventListener, FriendApiCommonRefT::iMemGroup, NetCritInit(), NetPrintf, FriendApiCommonRefT::notifyCrit, NULL, and FriendApiCommonRefT::pMemGroupUserData.
Referenced by FriendApiCreate().
void FriendApiPrivDestroy (FriendApiRefT * pFriendApiRef)
Release friend api component if enumeration is done, otherwise queue release of the xenon friend api component.
Parameters
*pFriendApiRef - module reference
Version
04/19/2010 (mclouatre) - Initial version
09/13/2012 (akirchner) - Queue release of friend api component if there is an enumeration going on
References EnumerationT::bEnumerating, FriendApiRefT::enumeration, NetConnControl(), NetPrintf, and TRUE.
Referenced by FriendApiDestroy().
int32_t FriendApiPrivGetBlockList (FriendApiRefT * pFriendApiRef, uint32_t uUserIndex, BlockedUserDataT * pBlockList, int32_t * pUsersCount)
Returns the list of blocked users in the user-provided buffers. Unsupported on Xenon. Always returns an empty list.
Parameters
*pFriendApiRef - module reference
uUserIndex - local user index
*pBlockList - [out] user-provided buffer to be filled with block list (can be NULL)
pUsersCount - [out] user-provided variable to be filled with number of entries in the block list.
Returns
int32_t - return negative in case of error, and 0 otherwise
Note
Set pBlockList to NULL to find out the number of entries that pBlockList will be filled-in with.
Version
05/10/2011 (mclouatre)
Referenced by FriendApiGetBlockList().
int32_t FriendApiPrivGetBlockListVersion (FriendApiRefT * pFriendApiRef, uint32_t * pVersion)
Returns the current version of the list of blocked users. Unsupported on Xenon. Always returns 0.
Parameters
*pFriendApiRef - module reference
*pVersion - [out] pointer to buffer to be filled with version number
Returns
int32_t - return negative in case of error, and 0 otherwise
Version
05/10/2011 (mclouatre)
Referenced by FriendApiGetBlockListVersion().
int32_t FriendApiPrivGetFriendsList (FriendApiRefT * pFriendApiRef, uint32_t uUserIndex, FriendDataT * pFriendsList, void * pRawDataList1, int32_t * pFriendsCount)
Returns the number of friends and the list of friends in the user-provided buffers. Set pFriend to NULL to only find out the number of friends.
Parameters
*pFriendApiRef - module reference
uUserIndex - user index
*pFriendsList - [out] user-provided buffer to be filled with the friends list (can be NULL)
*pRawDataList1 - [out] user-provided buffer to be filled with array of XONLINE_FRIEND data structures (can be NULL)
*pFriendsCount - [out] user-provided buffer to be filled with the number of friends in the list (can be NULL)
Returns
int32_t - return negative in case of error, and 0 otherwise
Version
04/19/2010 (mclouatre)
References FriendApiRefT::aFriendsCollection, FriendsCollectionT::aFriendsUpdate, FriendsCollectionT::aOnlineFriends, FriendsCollectionT::bOldFriendsCollectionIndex, ds_snzprintf(), FriendsUpdateT::iFriends, FriendDataT::pRawData1, and FriendDataT::strFriendName.
Referenced by FriendApiGetFriendsList().
uint32_t FriendApiPrivIsUserBlocked (FriendApiRefT * pFriendApiRef, uint32_t uUserIndex, void * pUserId)
Returns whether a given user is blocked or not. On Xenon, a "blocked" user is a "muted" user.
Parameters
*pFriendApiRef - module reference
uUserIndex - local user index
*pUserId - user for which "blocked" status needs to be queried (pointer to XUID)
Returns
uint32_t - TRUE if user is blocked, FALSE otherwise
Version
02/24/2011 (mclouatre)
References DirtyErrGetName(), FALSE, and NetPrintf.
Referenced by FriendApiIsUserBlocked().
uint32_t FriendApiPrivIsUserFriend (FriendApiRefT * pFriendApiRef, uint32_t uUserIndex, void * pUserId)
Returns whether a given user is friend.
Parameters
*pFriendApiRef - module reference
uUserIndex - local user index
*pUserId - user for which "friend" status needs to be queried on xenon: pUserId needs to point to a XUID
Returns
uint32_t - TRUE if user is friend, FALSE otherwise
Version
09/13/2012 (akirchner)
References FriendApiRefT::aFriendsCollection, FriendsCollectionT::aFriendsUpdate, FriendsCollectionT::aOnlineFriends, FriendsCollectionT::bOldFriendsCollectionIndex, FALSE, FriendsUpdateT::iFriends, and TRUE.
Referenced by FriendApiIsUserFriend().
uint32_t FriendApiPrivIsUserRealFriend (FriendApiRefT * pFriendApiRef, uint32_t uUserIndex, void * pUserId)
Returns whether a given user is a 'real' friend (not pending)
Parameters
*pFriendApiRef - module reference
uUserIndex - local user index
*pUserId - user for which "friend" status needs to be queried on xenon: pUserId needs to point to a XUID
Returns
uint32_t - TRUE if user is friend, FALSE otherwise
Version
07/17/2013 (jbrookes)
References FriendApiRefT::aFriendsCollection, FriendsCollectionT::aOnlineFriends, FALSE, FRIENDAPI_MAX_FRIENDS, and TRUE.
Referenced by FriendApiIsUserRealFriend().
int32_t FriendApiPrivStatus (FriendApiRefT * pFriendApiRef, int32_t iSelect, void * pBuf, int32_t iBufSize)
Get status information.
Parameters
*pFriendApiRef - module reference
iSelect - status selector
*pBuf - [out] storage for selector-specific output
iBufSize - size of output buffer
Returns
int32_t - selector specific
Note
iSelect can be one of the following:
        'maxf' - returns maximum possible number of friends in the friendslist
        'eoip' - stands for "End Of Initial Presence"; returns TRUE if initial presence completed, FALSE otherwise
Version
04/19/2010 (mclouatre)
References FriendApiRefT::aFriendsCollection, FriendsCollectionT::bEndOfInitialPresence, ds_memcpy_s(), and NetPrintf.
Referenced by FriendApiStatus().
int32_t FriendApiPrivUnblockUser (FriendApiRefT * pFriendApiRef, uint32_t uUserIndex, void * pUserId)
Unblock user.
Parameters
*pFriendApiRef - module reference
uUserIndex - local user index
*pUserId - user to be unblocked (pointer to SceNpId)
Returns
int32_t - 0 for success, negative for failure
Version
02/24/2011 (mclouatre)
References DirtyErrGetName(), FALSE, and NetPrintf.
Referenced by FriendApiUnblockUser().
void FriendApiPrivUpdate (FriendApiRefT * pFriendApiRef)
Give module time to perform periodic processing.
Parameters
*pFriendApiRef - module reference
Version
04/21/2010 (mclouatre)
References FriendApiRefT::aFriendsCollection, FriendsCollectionT::bEndOfInitialPresence, EnumerationT::bEnumerating, FriendEventTypeDataT::BlockUserResult, FriendApiRefT::bNotifyBlockUserResult, FriendEventDataBlockUserResultT::bSuccess, FriendApiRefT::enumeration, FriendEventDataT::eventType, FriendEventDataT::eventTypeData, FALSE, FRIENDAPI_EVENT_BLOCK_USER_RESULT, FriendApiPrivNotifyEvent(), NETCONN_MAXLOCALUSERS, NetConnStatus(), NULL, TRUE, and EnumerationT::xOverlapped.
Referenced by FriendApiUpdate().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:55