DirtySock: DirtyLSPXenon
DirtyLSPXenon
DirtySock
Data Structures
struct DirtyLSPQueryRecT
lsp query record
Macros
#define DIRTYLSP_USERDATA_MAXSIZE (64)
maximum length of UserData string
Typedefs
typedef enum DirtyLSPQueryStateE DirtyLSPQueryStateE
lsp query states
typedef enum DirtyLSPCacheEventE DirtyLSPCacheEventE
lsp notify types
typedef struct DirtyLSPQueryRecT DirtyLSPQueryRecT
lsp query record
typedef struct DirtyLSPRefT DirtyLSPRefT
module state ref
typedef void(DirtyLSPCacheCbT)(uint32_t uAddress, DirtyLSPCacheEventE eCacheEvent, void *pUserRef)
cache callback (internal use only)
typedef void(DirtyLSPNotifyCbT)(DirtyLSPRefT *pDirtyLSP, const DirtyLSPQueryRecT *pQueryRec, void *pUserRef)
optional notification callback
Enumerations
enum DirtyLSPQueryStateE {
DIRTYLSP_QUERYSTATE_FAIL = -1,
DIRTYLSP_QUERYSTATE_RSLV,
DIRTYLSP_QUERYSTATE_INIT,
DIRTYLSP_QUERYSTATE_CONN,
DIRTYLSP_QUERYSTATE_DONE
}
lsp query states
enum DirtyLSPCacheEventE {
DIRTYLSP_CACHEEVENT_NONE = 0,
DIRTYLSP_CACHEEVENT_EXPIRED
}
lsp notify types
Functions
DirtyLSPRefT * DirtyLSPCreate (uint32_t uMaxQueryCount)
Create the DirtyLSP module state.
void DirtyLSPCallback (DirtyLSPRefT *pDirtyLSP, DirtyLSPNotifyCbT *pNotifyCb, void *pUserRef)
Set optional notification callback.
void DirtyLSPDestroy (DirtyLSPRefT *pDirtyLSP)
Destroy the DirtyLSP module.
DirtyLSPQueryRecT * DirtyLSPQueryStart (DirtyLSPRefT *pDirtyLSP, const char *pQueryStr)
Start an LSP query.
DirtyLSPQueryRecT * DirtyLSPQueryStart2 (DirtyLSPRefT *pDirtyLSP, const char *pQueryStr, uint32_t uMaxResponses)
Start an LSP query.
void DirtyLSPQueryFree (DirtyLSPRefT *pDirtyLSP, DirtyLSPQueryRecT *pQueryRec)
Free an allocated query.
int32_t DirtyLSPQueryDone (DirtyLSPRefT *pDirtyLSP, DirtyLSPQueryRecT *pQueryRec)
Poll query for completion.
void DirtyLSPConnectionUpdate (uint32_t uAddress)
Update specified connection. Must be polled to prevent the security association from timing out.
int32_t DirtyLSPConnectionClose (DirtyLSPRefT *pDirtyLSP, uint32_t uAddress)
Close connection associated with given secure address, if it is an address that is managed by DirtyLSP.
int32_t DirtyLSPControl (DirtyLSPRefT *pDirtyLSP, int32_t iSelect, int32_t iValue, int32_t iValue2, void *pValue)
DirtyLSP control function. Different selectors control different behaviors.
int32_t DirtyLSPStatus (DirtyLSPRefT *pDirtyLSP, int32_t iSelect, void *pBuffer, int32_t iBufSize)
Return status of DirtyLSP module. Status type depends on selector.
Detailed Description
Macro Definition Documentation
#define DIRTYLSP_USERDATA_MAXSIZE (64)
maximum length of UserData string
Typedef Documentation
typedef void(DirtyLSPCacheCbT)(uint32_t uAddress, DirtyLSPCacheEventE eCacheEvent, void *pUserRef)
cache callback (internal use only)
typedef enum DirtyLSPCacheEventE DirtyLSPCacheEventE
lsp notify types
typedef void(DirtyLSPNotifyCbT)(DirtyLSPRefT *pDirtyLSP, const DirtyLSPQueryRecT *pQueryRec, void *pUserRef)
optional notification callback
typedef struct DirtyLSPQueryRecT DirtyLSPQueryRecT
lsp query record
typedef enum DirtyLSPQueryStateE DirtyLSPQueryStateE
lsp query states
typedef struct DirtyLSPRefT DirtyLSPRefT
module state ref
Enumeration Type Documentation
enum DirtyLSPCacheEventE
lsp notify types
Enumerator
DIRTYLSP_CACHEEVENT_NONE
placeholder
DIRTYLSP_CACHEEVENT_EXPIRED
cache entry has expired
enum DirtyLSPQueryStateE
lsp query states
Enumerator
DIRTYLSP_QUERYSTATE_FAIL
xlsp request failed
DIRTYLSP_QUERYSTATE_RSLV
xlsp resolve is in progress
DIRTYLSP_QUERYSTATE_INIT
connection to xlsp server is to be initiated
DIRTYLSP_QUERYSTATE_CONN
connection to xlsp server is in progress
DIRTYLSP_QUERYSTATE_DONE
connection to xlsp server has been established
Function Documentation
void DirtyLSPCallback (DirtyLSPRefT * pDirtyLSP, DirtyLSPNotifyCbT * pNotifyCb, void * pUserRef)
Set optional notification callback.
Parameters
*pDirtyLSP - pointer to module state
*pNotifyCb - pointer to notification callback
*pUserRef - user-supplied callback ref (may be NULL)
Version
11/17/2009 (jbrookes)
References DirtyLSPRefT::pNotifyCb, and DirtyLSPRefT::pUserRef.
int32_t DirtyLSPConnectionClose (DirtyLSPRefT * pDirtyLSP, uint32_t uAddress)
Close connection associated with given secure address, if it is an address that is managed by DirtyLSP.
[DEPRECATED]
Parameters
*pDirtyLSP - pointer to module state
uAddress - secure address of connection to close
Returns
int32_t - zero=connection closed, negative=not mapped, else refcount
Version
11/17/2009 (jbrookes)
void DirtyLSPConnectionUpdate (uint32_t uAddress)
Update specified connection. Must be polled to prevent the security association from timing out.
Parameters
uAddress - secure address of connection to update
Version
04/15/2010 (jbrookes)
Referenced by ConnApiUpdate(), SocketConnect(), SocketRecvfrom(), and SocketSendto().
int32_t DirtyLSPControl (DirtyLSPRefT * pDirtyLSP, int32_t iSelect, int32_t iValue, int32_t iValue2, void * pValue)
DirtyLSP control function. Different selectors control different behaviors.
Parameters
*pDirtyLSP - reference pointer
iSelect - control selector
iValue - selector specific
iValue2 - selector specific
*pValue - selector specific
Returns
int32_t - selector specific
Note
Selectors are:
        SELECTOR    DESCRIPTION
        'cbfp'      Sets cache notification callback (internal use only)
        'cbup'      Sets cache notification user ref (internal use only)
        'xtim'      Sets cache timeout
        'xclr'      Clears global cache
Version
02/24/2010 (jbrookes)
References NULL.
Referenced by SocketControl().
DirtyLSPRefT* DirtyLSPCreate (uint32_t uMaxQueryCount)
Create the DirtyLSP module state.
Parameters
uMaxQueryCount - max number of XLSPs that will be returned in a single query
Returns
DirtyLSPRefT * - pointer to module state, or NULL
Version
03/13/2006 (jbrookes)
References DIRTYLSP_MEMID, DIRTYLSP_MINQUERYCOUNT, DirtyLSPDestroy(), DirtyMemAlloc(), DirtyMemGroupQuery(), DirtyLSPRefT::iMemGroup, NetConnIdleAdd(), NetCritInit(), NetPrintf, NULL, DirtyLSPRefT::pMemGroupUserData, DirtyLSPRefT::pNotifyCb, DirtyLSPRefT::QueryCrit, and DirtyLSPRefT::uMaxQueryCount.
Referenced by NetConnStartup(), and SocketControl().
void DirtyLSPDestroy (DirtyLSPRefT * pDirtyLSP)
Destroy the DirtyLSP module.
Parameters
*pDirtyLSP - pointer to module state
Version
03/13/2006 (jbrookes)
References DIRTYLSP_MEMID, DIRTYLSP_QUERYSTATE_RSLV, DirtyMemFree(), DirtyLSPQueryRecT::eQueryState, DirtyLSPRefT::iMemGroup, NetConnControl(), NetConnIdleDel(), NetCritEnter(), NetCritKill(), NetCritLeave(), NetPrintf, NULL, DirtyLSPRefT::pMemGroupUserData, DirtyLSPQueryRecT::pNext, DirtyLSPRefT::pQueryList, and DirtyLSPRefT::QueryCrit.
Referenced by DirtyLSPCreate(), NetConnShutdown(), and SocketControl().
int32_t DirtyLSPQueryDone (DirtyLSPRefT * pDirtyLSP, DirtyLSPQueryRecT * pQueryRec)
Poll query for completion.
Parameters
*pDirtyLSP - pointer to module state
*pQueryRec - pointer to query record
Returns
int32_t - negative=error, zero=pending, positive=complete
Version
03/13/2006 (jbrookes)
References DIRTYLSP_QUERYSTATE_DONE, DIRTYLSP_QUERYSTATE_FAIL, and DirtyLSPQueryRecT::eQueryState.
void DirtyLSPQueryFree (DirtyLSPRefT * pDirtyLSP, DirtyLSPQueryRecT * pQueryRec)
Free an allocated query.
Parameters
*pDirtyLSP - pointer to module state
*pQueryRec - pointer to query record to free
Note
This function may be called from a user callback.
Version
03/13/2006 (jbrookes)
References DIRTYLSP_QUERYSTATE_RSLV, DirtyLSPQueryRecT::eQueryState, NetCritEnter(), NetCritLeave(), NetPrintf, NULL, DirtyLSPQueryRecT::pNext, DirtyLSPRefT::pQueryList, DirtyLSPRefT::QueryCrit, and TRUE.
DirtyLSPQueryRecT* DirtyLSPQueryStart (DirtyLSPRefT * pDirtyLSP, const char * pQueryStr)
Start an LSP query.
Parameters
*pDirtyLSP - pointer to module state
*pQueryStr - query string (may be empty for global query; not recommended)
Returns
DirtyLSPQueryRecT * - query record or NULL on failure
Version
03/13/2006 (jbrookes)
References DirtyLSPQueryStart2(), and DirtyLSPRefT::uMaxQueryCount.
Referenced by SocketLookup2().
DirtyLSPQueryRecT* DirtyLSPQueryStart2 (DirtyLSPRefT * pDirtyLSP, const char * pQueryStr, uint32_t uMaxResponses)
Start an LSP query.
Parameters
*pDirtyLSP - pointer to module state
*pQueryStr - query string (may be empty for global query; not recommended)
uMaxResponses - maximum number of responses to allow
Returns
DirtyLSPQueryRecT * - query record or NULL on failure
Version
03/13/2006 (jbrookes)
References DIRTYLSP_QUERYSTATE_INIT, DirtyLSPQueryRecT::eQueryState, DirtyLSPQueryRecT::InAddr, NetCritEnter(), NetCritLeave(), NULL, DirtyLSPQueryRecT::pNext, DirtyLSPRefT::pQueryList, DirtyLSPRefT::QueryCrit, SocketHtonl(), and DirtyLSPQueryRecT::uAddress.
Referenced by DirtyLSPQueryStart().
int32_t DirtyLSPStatus (DirtyLSPRefT * pDirtyLSP, int32_t iSelect, void * pBuffer, int32_t iBufSize)
Return status of DirtyLSP module. Status type depends on selector.
Parameters
*pDirtyLSP - reference pointer
iSelect - info selector (see Notes)
*pBuffer - [out] storage for selector-specific output
iBufSize - size of buffer
Returns
int32_t - selector specific
Note
Selectors are:
    SELECTOR    RETURN RESULT
Version
02/24/2010 (jbrookes)
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:56