DirtySock: ProtoPing
ProtoPing
Proto
Data Structures
struct ProtoPingResponseT
ping response structure
Macros
#define ICMP_ECHOREPLY (0)
#define ICMP_DESTUNREACH (3)
#define ICMP_ECHOREQ (8)
#define ICMP_TIMEEXCEEDED (11)
#define PROTOPING_MAXUSERDATA (256)
maximum user data size
Typedefs
typedef enum PingType ePingType
typedef struct ProtoPingRefT ProtoPingRefT
typedef struct ProtoPingResponseT ProtoPingResponseT
ping response structure
Enumerations
enum PingType {
PROTOPING_TYPE_ICMP = 0,
PROTOPING_TYPE_QOS,
PROTOPING_NUMTYPES
}
Functions
DIRTYCODE_API ProtoPingRefT * ProtoPingCreate (int32_t iMaxPings)
Create new ping module.
DIRTYCODE_API void ProtoPingDestroy (ProtoPingRefT *pProtoPing)
Destroy the module.
DIRTYCODE_API int32_t ProtoPingControl (ProtoPingRefT *pProtoPing, int32_t iControl, int32_t iValue, void *pValue)
Configure ProtoPing module.
DIRTYCODE_API int32_t ProtoPingRequest (ProtoPingRefT *pProtoPing, DirtyAddrT *pAddr, const unsigned char *pData, int32_t iDataLen, int32_t iTimeout, int32_t iTtl)
Send a ping request uSockAddrg opaque address form.
DIRTYCODE_API int32_t ProtoPingRequestServer (ProtoPingRefT *pProtoPing, uint32_t uServerAddress, const unsigned char *pData, int32_t iDataLen, int32_t iTimeout, int32_t iTtl)
Ping the given server address.
DIRTYCODE_API int32_t ProtoPingResponse (ProtoPingRefT *pProtoPing, unsigned char *pBuffer, int32_t *pBufLen, ProtoPingResponseT *pResponse)
Get ping response from queue.
Detailed Description
Macro Definition Documentation
#define ICMP_DESTUNREACH (3)
#define ICMP_ECHOREPLY (0)
#define ICMP_ECHOREQ (8)
#define ICMP_TIMEEXCEEDED (11)
#define PROTOPING_MAXUSERDATA (256)
maximum user data size
Typedef Documentation
typedef enum PingType ePingType
typedef struct ProtoPingRefT ProtoPingRefT
typedef struct ProtoPingResponseT ProtoPingResponseT
ping response structure
Enumeration Type Documentation
enum PingType
Enumerator
PROTOPING_TYPE_ICMP
PROTOPING_TYPE_QOS
PROTOPING_NUMTYPES
Function Documentation
DIRTYCODE_API int32_t ProtoPingControl (ProtoPingRefT * pProtoPing, int32_t iControl, int32_t iValue, void * pValue)
Configure ProtoPing module.
Parameters
*pProtoPing - module state ref
iControl - config selector
iValue - selector specific
*pValue - selector specific
Returns
int32_t - selector specific
Note
iControl can be:
        'spam' - set verbose debug output
        'type' - set the ping type to use
Version
11/18/2002 (jbrookes)
References ProtoPingRefT::bVerbose, DirtyMemGroupEnter(), DirtyMemGroupLeave(), ProtoPingRefT::eType, ProtoPingRefT::iMemGroup, NetPrintf, ProtoPingRefT::pMemGroupUserData, ProtoPingRefT::pQosApi, PROTOPING_TYPE_ICMP, PROTOPING_TYPE_QOS, QosApiControl(), and QosApiCreate().
Referenced by PingManagerCreate().
DIRTYCODE_API ProtoPingRefT* ProtoPingCreate (int32_t iMaxPings)
Create new ping module.
Parameters
iMaxPings - maximum number of ping requests that can be issued at one time
Returns
ProtoPingRefT * - reference pointer (needed for all other calls)
Version
04/03/2002 (gschaefer)
References DirtyMemAlloc(), DirtyMemGroupQuery(), FALSE, ProtoPingRefT::hIcmp, ProtoPingRefT::iMemGroup, ProtoPingRefT::iQueueSize, ProtoPingRefT::iRefCount, NetCritInit(), NetPrintf, ProtoPingRefT::pEvents, ProtoPingRefT::pMemGroupUserData, ProtoPingRefT::ppResponses, ProtoPingRefT::pResponses, PROTOPING_DEFAULT_MAXPINGS, PROTOPING_MEMID, ProtoPingDestroy(), SocketGetLocalAddr(), ProtoPingRefT::ThreadCrit, TRUE, and ProtoPingRefT::uLocalAddr.
Referenced by PingManagerCreate().
DIRTYCODE_API void ProtoPingDestroy (ProtoPingRefT * pProtoPing)
Destroy the module.
Parameters
*pProtoPing - reference pointer
Version
04/03/2002 (gschaefer)
References DirtyMemFree(), ProtoPingRefT::hIcmp, ProtoPingRefT::iMemGroup, ProtoPingRefT::iQueueSize, ProtoPingRefT::iQueueTail, ProtoPingRefT::iRefCount, NetCritKill(), ProtoPingQueueT::pData, ProtoPingRefT::pEvents, ProtoPingRefT::pMemGroupUserData, ProtoPingRefT::ppResponses, ProtoPingRefT::pQosApi, ProtoPingRefT::pResponses, PROTOPING_MEMID, QosApiDestroy(), ProtoPingRefT::RequestQueue, and ProtoPingRefT::ThreadCrit.
Referenced by PingManagerDestroy(), and ProtoPingCreate().
DIRTYCODE_API int32_t ProtoPingRequest (ProtoPingRefT * pRef, DirtyAddrT * pAddr, const unsigned char * pData, int32_t iDataLen, int32_t iTimeout, int32_t iTtl)
Send a ping request uSockAddrg opaque address form.
Parameters
*pRef - reference pointer
*pAddr - address to ping
*pData - pointer to user data
iDataLen - iLength of user data
iTimeout - timeout in ms, or zero for default
iTtl - time to live, or zero for default
Returns
int32_t - sequence number of packet (zero=failed)
Version
04/12/2004 (jbrookes)
References DirtyAddrToHostAddr(), and FALSE.
Referenced by PingManagerUpdate().
DIRTYCODE_API int32_t ProtoPingRequestServer (ProtoPingRefT * pRef, uint32_t uServerAddress, const unsigned char * pData, int32_t iDataLen, int32_t iTimeout, int32_t iTtl)
Ping the given server address.
Parameters
*pRef - reference pointer
uServerAddress - address of server to ping
*pData - pointer to user data
iDataLen - iLength of user data
iTimeout - timeout in ms, or zero for default
iTtl - time to live, or zero for default
Returns
int32_t - sequence number of packet (zero=failed)
Version
04/12/2004 (jbrookes)
References TRUE.
Referenced by PingManagerPingServer2().
DIRTYCODE_API int32_t ProtoPingResponse (ProtoPingRefT * pProtoPing, unsigned char * pBuffer, int32_t * pBufLen, ProtoPingResponseT * pResponse)
Get ping response from queue.
Parameters
*pProtoPing - reference pointer
*pBuffer - space for user data
*pBufLen - size of buffer on entry, actual data size on exit
*pResponse - pointer to ping response structure
Returns
int32_t - zero if nothing pending, else ping (negative=timeout)
Version
04/03/2002 (gschaefer)
References ProtoPingResponseT::Addr, ProtoPingResponseT::bServer, DirtyAddrFromHostAddr(), DirtyMemFree(), ds_memcpy(), ProtoPingRefT::eType, FALSE, ProtoPingRefT::iMemGroup, ProtoPingResponseT::iPing, ProtoPingRefT::iQueueTail, NetCritEnter(), NetCritLeave(), NetTick(), ProtoPingQueueT::pData, ProtoPingRefT::pEvents, ProtoPingRefT::pMemGroupUserData, ProtoPingRefT::ppResponses, PROTOPING_FLAG_RECEIVED, PROTOPING_FLAG_SERVER, PROTOPING_MEMID, PROTOPING_TYPE_QOS, QOSAPI_STATFL_FAILED, ProtoPingRefT::RequestQueue, ProtoPingRefT::ThreadCrit, TRUE, ProtoPingQueueT::uAddr, ProtoPingResponseT::uAddr, ProtoPingQueueT::uFlag, ProtoPingQueueT::uPing, ProtoPingQueueT::uSeqn, ProtoPingResponseT::uSeqn, ProtoPingQueueT::uSize, ProtoPingQueueT::uTick, ProtoPingQueueT::uTime, ProtoPingQueueT::uType, and ProtoPingResponseT::uType.
Referenced by PingManagerUpdate().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:49