DirtySock: CommUDP
CommUDP
Comm
Typedefs
typedef struct CommUDPRef CommUDPRef
Functions
DIRTYCODE_API CommUDPRef * CommUDPConstruct (int32_t maxwid, int32_t maxinp, int32_t maxout)
Construct the class.
DIRTYCODE_API void CommUDPDestroy (CommUDPRef *what)
Destruct the class.
DIRTYCODE_API int32_t CommUDPResolve (CommUDPRef *what, const char *addr, char *buf, int32_t len, char iDiv)
Resolve an address.
DIRTYCODE_API void CommUDPUnresolve (CommUDPRef *what)
Stop the resolver.
DIRTYCODE_API int32_t CommUDPListen (CommUDPRef *what, const char *addr)
Listen for a connection.
DIRTYCODE_API int32_t CommUDPUnlisten (CommUDPRef *what)
Stop listening.
DIRTYCODE_API int32_t CommUDPConnect (CommUDPRef *what, const char *addr)
Initiate a connection to a peer.
DIRTYCODE_API int32_t CommUDPUnconnect (CommUDPRef *what)
Terminate a connection.
DIRTYCODE_API void CommUDPCallback (CommUDPRef *what, void(*callback)(void *ref, int32_t event))
Set upper layer callback.
DIRTYCODE_API int32_t CommUDPStatus (CommUDPRef *what)
Return current stream status.
DIRTYCODE_API int32_t CommUDPControl (CommUDPRef *pRef, int32_t iControl, int32_t iValue, void *pValue)
Set connection behavior.
DIRTYCODE_API uint32_t CommUDPTick (CommUDPRef *what)
Return current tick.
DIRTYCODE_API int32_t CommUDPSend (CommUDPRef *what, const void *buffer, int32_t length, uint32_t flags)
Send a packet.
DIRTYCODE_API int32_t CommUDPPeek (CommUDPRef *what, void *target, int32_t length, uint32_t *when)
Peek at waiting packet.
DIRTYCODE_API int32_t CommUDPRecv (CommUDPRef *what, void *target, int32_t length, uint32_t *when)
Receive a packet from the buffer.
Detailed Description
Typedef Documentation
typedef struct CommUDPRef CommUDPRef
Function Documentation
DIRTYCODE_API void CommUDPCallback (CommUDPRef * ref, void(*)(void *ref, int32_t event) callback)
Set upper layer callback.
Parameters
*ref - reference pointer
*callback - socket generating callback
Version
12/04/00 (GWS)
References NetCritEnter(), and NetCritLeave().
Referenced by CommUDPConstruct().
DIRTYCODE_API int32_t CommUDPConnect (CommUDPRef * ref, const char * addr)
Initiate a connection to a peer.
Parameters
*ref - reference pointer
*addr - address in ip-address:port form
Returns
int32_t - negative=error, zero=ok
Note
Does not currently perform dns translation
Version
12/04/00 (GWS)
References COMM_BADADDRESS, COMM_NORESOURCE, COMM_UNEXPECTED, CommUDPRef::connident, CommUDPRef::link, NetPrintf, NULL, SockaddrCompare(), SockaddrInGetAddr, SockaddrInGetPort, SockaddrInit, SockaddrInParse2(), SockaddrInSetAddr, SockaddrInSetPort, CommUDPRef::socket, SocketBind(), SocketClose(), SocketInfo(), SocketOpen(), and TRUE.
Referenced by CommUDPConstruct().
DIRTYCODE_API CommUDPRef* CommUDPConstruct (int32_t maxwid, int32_t maxinp, int32_t maxout)
Construct the class.
Parameters
maxwid - max record width
maxinp - input packet buffer size
maxout - output packet buffer size
Returns
CommUDPRef - construct pointer
Note
Initialized winsock for first class. also creates linked list of all current instances of the class and worker thread to do most udp stuff.
Version
12/04/00 (GWS)
References CommRef::Callback, CommUDPRef::common, COMMUDP_MAX_METALEN, COMMUDP_MEMID, CommUDPCallback(), CommUDPConnect(), CommUDPControl(), CommUDPDestroy(), CommUDPListen(), CommUDPPeek(), CommUDPRecv(), CommUDPResolve(), CommUDPSend(), CommUDPStatus(), CommUDPTick(), CommUDPUnconnect(), CommUDPUnlisten(), CommUDPUnresolve(), CommRef::Connect, CommUDPRef::connident, CommRef::Construct, CommRef::Control, CommRef::Destroy, DirtyMemAlloc(), DirtyMemGroupQuery(), CommRef::Listen, CommRef::maxinp, CommRef::maxout, CommRef::maxwid, CommRef::memgroup, CommRef::memgrpusrdata, NULL, CommRef::Peek, CommUDPRef::peeraddr, CommUDPRef::rcvbuf, CommUDPRef::rcvlen, CommUDPRef::rcvwid, CommRef::Recv, REDUNDANT_LIMIT_DEFAULT, CommUDPRef::redundantlimit, CommRef::Resolve, CommRef::Send, CommUDPRef::sndbuf, CommUDPRef::sndlen, CommUDPRef::sndwid, CommUDPRef::state, CommRef::Status, CommRef::Tick, UNACK_LIMIT, CommUDPRef::unacklimit, CommRef::Unconnect, CommRef::Unlisten, and CommRef::Unresolve.
DIRTYCODE_API int32_t CommUDPControl (CommUDPRef * pRef, int32_t iControl, int32_t iValue, void * pValue)
Set connection behavior.
Parameters
*pRef - reference pointer
iControl - control selector
iValue - selector specfic
*pValue - selector specific
Returns
int32_t - negative=error, else selector result
Note
iControl can be one of the following:
        'clid' - client identifier
        'meta' - set metatype (default=0)
        'rcid' - remote client identifier
        'rlmt' - redundant packet size limit (default = REDUNDANT_LIMIT_DEFAULT)
        'ulmt' - unacknowledged packet limit (2k default)
Version
02/20/2007 (jbrookes)
References CommUDPRef::clientident, NetPrintf, NULL, CommUDPRef::rclientident, REDUNDANT_LIMIT_DEFAULT, CommUDPRef::redundantlimit, CommUDPRef::socket, SocketControl(), and CommUDPRef::unacklimit.
Referenced by CommUDPConstruct().
DIRTYCODE_API void CommUDPDestroy (CommUDPRef * ref)
Destruct the class.
Parameters
*ref - reference pointer
Version
12/04/00 (GWS)
References CommUDPRef::common, COMMUDP_MEMID, DirtyMemFree(), CommUDPRef::link, CommRef::memgroup, CommRef::memgrpusrdata, NetCritKill(), NetTick(), NULL, CommUDPRef::rcvbuf, CommUDPRef::sndbuf, CommUDPRef::socket, SocketClose(), and CommUDPRef::state.
Referenced by CommUDPConstruct().
DIRTYCODE_API int32_t CommUDPListen (CommUDPRef * ref, const char * addr)
Listen for a connection.
Parameters
*ref - reference pointer
*addr - port to listen on (only :port portion used)
Returns
int32_t - negative=error, zero=ok
Version
12/04/00 (GWS)
References COMM_BADADDRESS, COMM_NORESOURCE, CommUDPRef::connident, NetPrintf, NULL, SockaddrInit, SockaddrInParse2(), SockaddrInSetAddr, SockaddrInSetPort, and SocketOpen().
Referenced by CommUDPConstruct().
DIRTYCODE_API int32_t CommUDPPeek (CommUDPRef * ref, void * target, int32_t length, uint32_t * when)
Peek at waiting packet.
Parameters
*ref - reference pointer
*target - target buffer
length - buffer length
*when - tick received at
Returns
int32_t - negative=nothing pending, else packet length
Version
12/04/00 (GWS)
References RawUDPPacketT::body, COMM_MINBUFFER, COMM_NODATA, RawUDPPacketT::data, ds_memcpy(), RawUDPPacketT::head, RawUDPPacketT::len, NULL, CommUDPRef::rcvbuf, CommUDPRef::rcvinp, CommUDPRef::rcvout, and RawUDPPacketT::when.
Referenced by CommUDPConstruct(), and CommUDPRecv().
DIRTYCODE_API int32_t CommUDPRecv (CommUDPRef * ref, void * target, int32_t length, uint32_t * when)
Receive a packet from the buffer.
Parameters
*ref - reference pointer
*target - target buffer
length - buffer length
*when - tick received at
Returns
int32_t - negative=error, else packet length
Version
12/04/00 (GWS)
References CommUDPPeek(), CommUDPRef::rcvlen, CommUDPRef::rcvout, and CommUDPRef::rcvwid.
Referenced by CommUDPConstruct().
DIRTYCODE_API int32_t CommUDPResolve (CommUDPRef * ref, const char * addr, char * buf, int32_t len, char div)
Resolve an address.
Parameters
*ref - endpoint
*addr - resolve address
*buf - target buffer
len - target length (min 64 bytes)
div - divider char
Returns
int32_t - <0=error, 0=complete (COMM_NOERROR), >0=in progress (COMM_PENDING)
Note
Target list is always double null terminated allowing null to be used as the divider character if desired. when COMM_PENDING is returned, target buffer is set to "~" until completion.
Version
12/04/00 (GWS)
References NetPrintf.
Referenced by CommUDPConstruct().
DIRTYCODE_API int32_t CommUDPSend (CommUDPRef * ref, const void * buffer, int32_t length, uint32_t flags)
Send a packet.
Parameters
*ref - reference pointer
*buffer - pointer to data
length - length of data
flags - COMM_FLAGS_*
Returns
int32_t - negative=error, zero=buffer full (temp fail), positive=queue position (ok)
Note
Zero length packets may not be sent (they are used for buffer query)
Version
12/04/00 (GWS)
References RawUDPPacketT::ack, RawUDPPacketT::body, COMM_BADSTATE, COMM_FLAGS_BROADCAST, COMM_FLAGS_UNRELIABLE, COMM_MINBUFFER, CommUDPRef::connident, RawUDPPacketT::data, ds_memcpy(), ds_memcpy_s(), RawUDPPacketT::head, RawUDPPacketT::len, CommUDPRef::metatype, NetCritEnter(), NetCritLeave(), NetPrintf, NetTick(), CommUDPRef::peeraddr, RAW_METATYPE1_SIZE, RAW_PACKET_DATA, RAW_PACKET_UNREL, CommUDPRef::rcvseq, RawUDPPacketT::seq, CommUDPRef::sndbuf, CommUDPRef::snderr, CommUDPRef::sndinp, CommUDPRef::sndlen, CommUDPRef::sndout, CommUDPRef::sndseq, CommUDPRef::sndwid, SockaddrInSetAddr, SOCKERR_NONE, CommUDPRef::state, CommUDPRef::usndseq, and RawUDPPacketT::when.
Referenced by CommUDPConstruct().
DIRTYCODE_API int32_t CommUDPStatus (CommUDPRef * ref)
Return current stream status.
Parameters
*ref - reference pointer
Returns
int32_t - CONNECTING, OFFLINE, ONLINE or FAILURE
Version
12/04/00 (GWS)
References COMM_CONNECTING, COMM_FAILURE, COMM_OFFLINE, COMM_ONLINE, and CommUDPRef::state.
Referenced by CommUDPConstruct().
DIRTYCODE_API uint32_t CommUDPTick (CommUDPRef * ref)
Return current tick.
Parameters
*ref - reference pointer
Returns
uint32_t - elaped milliseconds
Version
12/04/00 (GWS)
References NetTick().
Referenced by CommUDPConstruct().
DIRTYCODE_API int32_t CommUDPUnconnect (CommUDPRef * ref)
Terminate a connection.
Parameters
*ref - reference pointer
Returns
int32_t - negative=error, zero=ok
Version
12/04/00 (GWS)
References NetTick(), NULL, CommUDPRef::socket, SocketClose(), and CommUDPRef::state.
Referenced by CommUDPConstruct().
DIRTYCODE_API int32_t CommUDPUnlisten (CommUDPRef * ref)
Stop listening.
Parameters
*ref - reference pointer
Returns
int32_t - negative=error, zero=ok
Version
12/04/00 (GWS)
References NetTick(), NULL, CommUDPRef::socket, SocketClose(), and CommUDPRef::state.
Referenced by CommUDPConstruct().
DIRTYCODE_API void CommUDPUnresolve (CommUDPRef * ref)
Stop the resolver.
Parameters
*ref - reference pointer
Version
12/04/00 (GWS)
Referenced by CommUDPConstruct().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:31