DirtySock: ProtoUpnp
ProtoUpnp
Proto
Data Structures
struct ProtoUpnpMacroT
protoupnp macro element definition
Macros
#define PROTOUPNP_STATUS_DISCOVERED (1)
discovered a upnp device
#define PROTOUPNP_STATUS_DESCRIBED (2)
described a upnp device
#define PROTOUPNP_STATUS_GOTEXTADDR (4)
got external address for device
#define PROTOUPNP_STATUS_ADDPORTMAP (8)
successfully added port mapping
#define PROTOUPNP_STATUS_DELPORTMAP (16)
successfully deleted port mapping
Typedefs
typedef struct ProtoUpnpMacroT ProtoUpnpMacroT
protoupnp macro element definition
typedef struct ProtoUpnpRefT ProtoUpnpRefT
opaque module ref
Functions
DIRTYCODE_API ProtoUpnpRefT * ProtoUpnpCreate (void)
Create the ProtoUpnp module state.
DIRTYCODE_API ProtoUpnpRefT * ProtoUpnpGetRef (void)
Get ProtoUpnp reference.
DIRTYCODE_API void ProtoUpnpDestroy (ProtoUpnpRefT *pProtoUpnp)
Destroy the ProtoUpnp module.
DIRTYCODE_API int32_t ProtoUpnpStatus (ProtoUpnpRefT *pProtoUpnp, int32_t iSelect, void *pBuf, int32_t iBufSize)
Get information from the ProtoUpnp module.
DIRTYCODE_API int32_t ProtoUpnpControl (ProtoUpnpRefT *pProtoUpnp, int32_t iControl, int32_t iValue, int32_t iValue2, const void *pValue)
Control ProtoUpnp behavior.
DIRTYCODE_API void ProtoUpnpUpdate (ProtoUpnpRefT *pProtoUpnp)
Update the ProtoUpnp module.
Detailed Description
Macro Definition Documentation
#define PROTOUPNP_STATUS_ADDPORTMAP (8)
successfully added port mapping
Referenced by NetConnStatus(), and ProtoUpnpUpdate().
#define PROTOUPNP_STATUS_DELPORTMAP (16)
successfully deleted port mapping
Referenced by ProtoUpnpUpdate().
#define PROTOUPNP_STATUS_DESCRIBED (2)
described a upnp device
Referenced by ProtoUpnpUpdate().
#define PROTOUPNP_STATUS_DISCOVERED (1)
discovered a upnp device
Referenced by ProtoUpnpControl(), and ProtoUpnpUpdate().
#define PROTOUPNP_STATUS_GOTEXTADDR (4)
got external address for device
Referenced by ProtoUpnpUpdate().
Typedef Documentation
typedef struct ProtoUpnpMacroT ProtoUpnpMacroT
protoupnp macro element definition
typedef struct ProtoUpnpRefT ProtoUpnpRefT
opaque module ref
Function Documentation
DIRTYCODE_API int32_t ProtoUpnpControl (ProtoUpnpRefT * pProtoUpnp, int32_t iControl, int32_t iValue, int32_t iValue2, const void * pValue)
Control ProtoUpnp behavior.
Parameters
*pProtoUpnp - pointer to module state
iControl - control selector
iValue - selector specifc
iValue2 - selector specific
*pValue - selector specific
Returns
int32_t - selector specific
Note
iControl can be one of the following:
        'abrt' - abort current operation
        'aprt' - start AddPortMapping request
        'desc' - initiate description
        'disc' - initiate discovery
        'dprt' - start DeletePortMapping request
        'extp' - set external port
        'gadr' - start GetExternalIPAddress request
        'gprt' - start GetSpecificPortMappingEntry request
        'host' - host address to allow traffic through firewall from
        'intp' - set internal port
        'ldur' - set lease duration
        'macr' - execute a macro.  iValue=macro id, or pValue=pointer to user macro
        'addp' - macro to add a new port mapping
        'port' - set internal and external ports
        'spam' - enable/disable verbose output
Version
05/24/2005 (jbrookes)
References _ProtoUpnpSoapRequestAddBln, _ProtoUpnpSoapRequestAddStr, _ProtoUpnpSoapRequestAddUI2, _ProtoUpnpSoapRequestAddUI4, ProtoUpnpDeviceT::bDiscovered, ProtoUpnpPortMapT::bEnabled, ProtoUpnpRefT::bEnableMapping, ProtoUpnpRefT::bPortIsMapped, ProtoUpnpRefT::bRequestInProgress, ProtoUpnpRefT::bVerbose, ProtoUpnpDeviceT::CurPortMap, ProtoUpnpRefT::Device, ds_strnzcpy(), ProtoUpnpRefT::eState, FALSE, ProtoUpnpPortMapT::iAddr, ProtoUpnpRefT::iClientAddr, ProtoUpnpMacroT::iControl, ProtoUpnpRefT::iLeaseDuration, ProtoUpnpDeviceT::iNumServices, ProtoUpnpPortMapT::iPort, ProtoUpnpRefT::iPortToMapExt, ProtoUpnpRefT::iPortToMapInt, ProtoUpnpRefT::iRemoteHost, ProtoUpnpRefT::iService, ProtoUpnpRefT::iStatus, ProtoUpnpMacroT::iValue, ProtoUpnpMacroT::iValue2, NetConnStatus(), NetPrintf, NULL, ProtoUpnpRefT::pCommandList, ProtoUpnpRefT::pProtoHttp, ProtoHttpControl(), ProtoHttpGet(), PROTOUPNP_STATUS_DISCOVERED, ProtoUpnpMacroT::pValue, ProtoUpnpDeviceT::Services, SocketInAddrGetText(), ST_IDLE, ProtoUpnpPortMapT::strDesc, ProtoUpnpServiceT::strDescriptionUrl, ProtoUpnpRefT::strRecvBuf, ProtoUpnpRefT::strRequestName, ProtoUpnpDeviceT::strUrl, and TRUE.
Referenced by ConnApiDestroy(), ConnApiOnline(), NetConnDisconnect(), and ProtoUpnpUpdate().
DIRTYCODE_API ProtoUpnpRefT* ProtoUpnpCreate (void)
Create the ProtoUpnp module state.
Returns
ProtoUpnpRefT * - pointer to module state, or NULL
Version
03/23/2005 (jbrookes)
References ProtoUpnpRefT::bEnableMapping, DirtyMemAlloc(), DirtyMemFree(), DirtyMemGroupQuery(), ProtoUpnpRefT::DiscoveryAddr, ProtoUpnpRefT::eState, FALSE, ProtoUpnpRefT::iLeaseDuration, ProtoUpnpRefT::iMemGroup, ProtoUpnpRefT::iPortToMapExt, ProtoUpnpRefT::iPortToMapInt, ProtoUpnpRefT::iRefCount, ProtoUpnpRefT::iRemoteHost, NetConnIdleAdd(), NetPrintf, NULL, ProtoUpnpRefT::pMemGroupUserData, ProtoUpnpRefT::pProtoHttp, ProtoUpnpRefT::pProtoUdp, ProtoHttpControl(), ProtoHttpCreate(), ProtoUdpCreate(), ProtoUdpDestroy(), PROTOUPNP_DEFAULTPORTMAP, PROTOUPNP_DISCOVERYADDR, PROTOUPNP_DISCOVERYPORT, PROTOUPNP_MEMID, SockaddrInit, SockaddrInSetAddr, SockaddrInSetPort, ST_IDLE, and TRUE.
Referenced by ConnApiOnline(), and NetConnStartup().
DIRTYCODE_API void ProtoUpnpDestroy (ProtoUpnpRefT * pProtoUpnp)
Destroy the ProtoUpnp module.
Parameters
*pProtoUpnp - pointer to module state
Version
03/23/2005 (jbrookes)
References DirtyMemFree(), ProtoUpnpRefT::iMemGroup, ProtoUpnpRefT::iRefCount, NetConnIdleDel(), NULL, ProtoUpnpRefT::pMemGroupUserData, ProtoUpnpRefT::pProtoHttp, ProtoUpnpRefT::pProtoUdp, ProtoHttpDestroy(), ProtoUdpDestroy(), and PROTOUPNP_MEMID.
Referenced by ConnApiDestroy(), and NetConnShutdown().
DIRTYCODE_API ProtoUpnpRefT* ProtoUpnpGetRef (void)
Get ProtoUpnp reference.
Version
03/23/2005 (jbrookes)
Referenced by ConnApiOnline().
DIRTYCODE_API int32_t ProtoUpnpStatus (ProtoUpnpRefT * pProtoUpnp, int32_t iSelect, void * pBuf, int32_t iBufSize)
Get information from the ProtoUpnp module.
Parameters
*pProtoUpnp - pointer to module state
iSelect - info selector
*pBuf - [out] pointer to output buffer
iBufSize - size of output buffer
Returns
int32_t - selector specific
Note
iSelect can be one of the following:
        'body' - get most recent http response body
        'ctrl' - return control ident for current operation
        'disc' - TRUE if a UPnP device has been discovered, else FALSE
        'dnam' - device name ("manufacturer modelName modelNumber")
        'done' - returns TRUE if in IDLE state and no macro is currently being processed
        'durn' - device URN
        'extn' - device external (WAN) IP address
        'extp' - returns external port used in mapping operations
        'idle' - return if module is idle or not
        'intp' - returns internal port used in mapping operations
        'lerr' - most recent error result (http or soap)
        'macr' - return current macro being executed, or zero if none, + name copied to pBuf
        'rbdy' - get most recent htto request body
        'stat' - module status (PROTOUPNP_STATUS_*)
Version
10/10/2005 (jbrookes)
References ProtoUpnpDeviceT::bDiscovered, ProtoUpnpRefT::Device, ds_strnzcpy(), ProtoUpnpRefT::eState, ProtoUpnpMacroT::iControl, ProtoUpnpRefT::iHttpError, ProtoUpnpRefT::iPortToMapExt, ProtoUpnpRefT::iPortToMapInt, ProtoUpnpRefT::iSoapError, ProtoUpnpRefT::iStatus, NULL, ProtoUpnpRefT::pCommandList, ProtoUpnpRefT::pProtoHttp, ProtoHttpStatus(), ST_IDLE, ProtoUpnpDeviceT::strModel, ProtoUpnpRefT::strRecvBuf, ProtoUpnpRefT::strRequestName, ProtoUpnpRefT::strSendBuf, ProtoUpnpDeviceT::strUdn, and ProtoUpnpDeviceT::uExternalAddress.
Referenced by NetConnStatus().
DIRTYCODE_API void ProtoUpnpUpdate (ProtoUpnpRefT * pProtoUpnp)
Update the ProtoUpnp module.
Parameters
*pProtoUpnp - pointer to module state
Version
03/23/2005 (jbrookes)
References ProtoUpnpRefT::bPortIsMapped, ProtoUpnpRefT::Device, ProtoUpnpRefT::eState, FALSE, ProtoUpnpMacroT::iControl, ProtoUpnpRefT::iDiscoveryTimer, ProtoUpnpRefT::iLeaseDuration, ProtoUpnpDeviceT::iNumServices, ProtoUpnpRefT::iRemoteHost, ProtoUpnpRefT::iService, ProtoUpnpRefT::iSoapError, ProtoUpnpRefT::iStatus, ProtoUpnpMacroT::iValue, ProtoUpnpMacroT::iValue2, NetPrintf, NetTick(), NetTickDiff, NULL, ProtoUpnpRefT::pCommandList, ProtoUpnpRefT::pProtoUdp, ProtoUdpRecvFrom(), ProtoUdpUpdate(), PROTOUPNP_DISCOVERYINTERVAL, PROTOUPNP_STATUS_ADDPORTMAP, PROTOUPNP_STATUS_DELPORTMAP, PROTOUPNP_STATUS_DESCRIBED, PROTOUPNP_STATUS_DISCOVERED, PROTOUPNP_STATUS_GOTEXTADDR, ProtoUpnpControl(), ProtoUpnpMacroT::pValue, ST_IDLE, ProtoUpnpRefT::strRecvBuf, and TRUE.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:32