DirtySock: XmlParse
XmlParse
Util
Macros
#define XmlPrintFmt(_x) { }
Functions
DIRTYCODE_API const char * XmlSkip (const char *strXml)
Skip to the next xml element (used to enumerate lists)
DIRTYCODE_API const char * XmlFind (const char *strXml, const char *strName)
Find an element within an xml document.
DIRTYCODE_API const char * XmlNext (const char *strXml)
Skip to next element with same name as current.
DIRTYCODE_API const char * XmlStep (const char *strXml)
Step over tag (regardless of the tab being a start tag or a end tag).
DIRTYCODE_API uint32_t XmlComplete (const char *pXml)
Determines if the xml element pointed to is complete.
DIRTYCODE_API int32_t XmlContentGetString (const char *strXml, char *strBuffer, int32_t iLength, const char *strDefault)
Return element contents as a string.
DIRTYCODE_API int32_t XmlContentGetInteger (const char *strXml, int32_t iDefault)
Return element contents as an integer.
DIRTYCODE_API int64_t XmlContentGetInteger64 (const char *strXml, int64_t iDefault)
Return element contents as an integer (64-bit)
DIRTYCODE_API int32_t XmlContentGetToken (const char *pXml, int32_t iDefault)
Return element contents as a token (a packed sequence of characters)
DIRTYCODE_API uint32_t XmlContentGetDate (const char *pXml, uint32_t uDefault)
Return epoch seconds for a date.
DIRTYCODE_API int32_t XmlContentGetAddress (const char *pXml, int32_t iDefault)
Parse element contents as an internet dot-notation address and return as an integer.
DIRTYCODE_API int32_t XmlContentGetBinary (const char *pXml, char *pBuffer, int32_t iLength)
Return binary encoded data.
DIRTYCODE_API int32_t XmlAttribGetString (const char *strXml, const char *strAttrib, char *strBuffer, int32_t iLength, const char *strDefault)
Return element attribute as a string.
DIRTYCODE_API int32_t XmlAttribGetInteger (const char *strXml, const char *strAttrib, int32_t iDefault)
Return element attribute as an integer.
DIRTYCODE_API int64_t XmlAttribGetInteger64 (const char *strXml, const char *strAttrib, int64_t iDefault)
Return element attribute as an integer (64-bit)
DIRTYCODE_API int32_t XmlAttribGetToken (const char *pXml, const char *pAttrib, int32_t iDefault)
Return element attribute as a token.
DIRTYCODE_API uint32_t XmlAttribGetDate (const char *pXml, const char *pAttrib, uint32_t uDefault)
Return epoch seconds for a date.
DIRTYCODE_API int32_t XmlConvEpoch2Date (uint32_t uEpoch, int32_t *pYear, int32_t *pMonth, int32_t *pDay, int32_t *pHour, int32_t *pMinute, int32_t *pSecond)
Convert epoch to date components.
Detailed Description
Macro Definition Documentation
#define XmlPrintFmt (_x) { }
Function Documentation
DIRTYCODE_API uint32_t XmlAttribGetDate (const char * pXml, const char * pAttrib, uint32_t uDefault)
Return epoch seconds for a date.
Parameters
pXml - pointer to xml element
pAttrib - name of attribute
uDefault - default value if (pXml == NULL || pAttrib not found)
Returns
uint32_t - attribute value as epoch seconds
Version
01/30/2002 (GWS)
References ds_timetosecs().
DIRTYCODE_API int32_t XmlAttribGetInteger (const char * pXml, const char * pAttrib, int32_t iDefault)
Return element attribute as an integer.
Parameters
pXml - pointer to xml element
pAttrib - name of attribute
iDefault - default value if (pXml == NULL || pAttrib not found)
Returns
int32_t - attibute value as integer
Version
01/30/2002 (GWS)
DIRTYCODE_API int64_t XmlAttribGetInteger64 (const char * pXml, const char * pAttrib, int64_t iDefault)
Return element attribute as an integer (64-bit)
Parameters
pXml - pointer to xml element
pAttrib - name of attribute
iDefault - default value if (pXml == NULL || pAttrib not found)
Returns
int64_t - attibute value as integer
DIRTYCODE_API int32_t XmlAttribGetString (const char * pXml, const char * pAttrib, char * pBuffer, int32_t iLength, const char * pDefault)
Return element attribute as a string.
Parameters
pXml - pointer to xml element
pAttrib - name of attribute
pBuffer - output string buffer
iLength - length of string buffer
pDefault - default string if (pXml == NULL || pAttrib not found)
Returns
int32_t - length of result string (-1=nothing copied)
Version
01/30/2002 (GWS)
DIRTYCODE_API int32_t XmlAttribGetToken (const char * pXml, const char * pAttrib, int32_t iDefault)
Return element attribute as a token.
Parameters
pXml - pointer to xml element
pAttrib - name of attribute
iDefault - default value if (pXml == NULL || pAttrib not found)
Returns
int32_t - attribute value as a token
Version
01/30/2002 (GWS)
DIRTYCODE_API uint32_t XmlComplete (const char * pXml)
Determines if the xml element pointed to is complete.
Parameters
*pXml - pointer to xml element (start tag)
Returns
uint32_t - TRUE if the element is complete, else FALSE
Version
09/24/2010 (jbrookes)
DIRTYCODE_API int32_t XmlContentGetAddress (const char * pXml, int32_t iDefault)
Parse element contents as an internet dot-notation address and return as an integer.
Parameters
pXml - pointer to xml document
iDefault - default value if (pXml == NULL)
Returns
int32_t - element contents as integer
Version
10/07/2005 (JLB)
DIRTYCODE_API int32_t XmlContentGetBinary (const char * pXml, char * pBuffer, int32_t iLength)
Return binary encoded data.
Parameters
pXml - pointer to xml document
pBuffer - pointer to buffer to copy binary data to
iLength - length of buffer pointed to by pBuffer
Returns
int32_t - negative if error, length otherwise
Version
01/30/2002 (GWS)
DIRTYCODE_API uint32_t XmlContentGetDate (const char * pXml, uint32_t uDefault)
Return epoch seconds for a date.
Parameters
pXml - pointer to xml document
uDefault - default value if (pXml == NULL)
Returns
uint32_t - element contents as epoch seconds
Version
01/30/2002 (GWS)
References ds_timetosecs().
DIRTYCODE_API int32_t XmlContentGetInteger (const char * pXml, int32_t iDefault)
Return element contents as an integer.
Parameters
pXml - pointer to xml document
iDefault - default value if (pXml == NULL)
Returns
int32_t - element contents as integer
Version
01/30/2002 (GWS)
References XmlContentGetInteger64().
DIRTYCODE_API int64_t XmlContentGetInteger64 (const char * pXml, int64_t iDefault)
Return element contents as an integer (64-bit)
Parameters
pXml - pointer to xml document
iDefault - default value if (pXml == NULL)
Returns
int64_t - element contents as integer
Referenced by XmlContentGetInteger().
DIRTYCODE_API int32_t XmlContentGetString (const char * pXml, char * _pBuffer, int32_t iLength, const char * pDefault)
Return element contents as a string.
Parameters
pXml - pointer to xml document
_pBuffer - string output buffer
iLength - length of output buffer
pDefault - default value if (pXml == NULL)
Returns
int32_t - length of string (-1=nothing copied)
Version
01/30/2002 (GWS)
DIRTYCODE_API int32_t XmlContentGetToken (const char * pXml, int32_t iDefault)
Return element contents as a token (a packed sequence of characters)
Parameters
pXml - pointer to xml document
iDefault - default value if (pXml == NULL)
Returns
int32_t - element contents as token
Version
01/30/2002 (GWS)
DIRTYCODE_API int32_t XmlConvEpoch2Date (uint32_t uEpoch, int32_t * pYear, int32_t * pMonth, int32_t * pDay, int32_t * pHour, int32_t * pMinute, int32_t * pSecond)
Convert epoch to date components.
Parameters
uEpoch - epoch to convert to date components
pYear - pointer to storage for year
pMonth - pointer to storage for month
pDay - pointer to storage for day
pHour - pointer to storage for hour
pMinute - pointer to storage for minute
pSecond - pointer to storage for second
Returns
int32_t - negative=error, zero=success
Version
01/30/2002 (GWS)
References ds_secstotime().
DIRTYCODE_API const char* XmlFind (const char * _pXml, const char * _pName)
Find an element within an xml document.
Parameters
_pXml - pointer to xml document
_pName - element name (x.y.z notation)
Returns
- Pointer to named element start
Version
01/30/2002 (GWS)
DIRTYCODE_API const char* XmlNext (const char * _pXml)
Skip to next element with same name as current.
Parameters
_pXml - pointer to element start
Returns
- Pointer to next element start
Version
01/30/2002 (GWS)
DIRTYCODE_API const char* XmlSkip (const char * pXml)
Skip to the next xml element (used to enumerate lists)
Parameters
*pXml - pointer to xml element (start tag)
Returns
- Pointer to next element at same level
Version
01/30/2002 (GWS)
DIRTYCODE_API const char* XmlStep (const char * _pXml)
Step over tag (regardless of the tab being a start tag or a end tag).
Parameters
*_pXml - pointer to tag opening character
Returns
const char * - pointer to byte following tag closing character or NULL if at end of document
Version
09/16/2010 (jbrookes)
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:50