DirtySock: CryptSSC2
CryptSSC2
Crypt
Data Structures
struct CryptSSC2T
all fields are PRIVATE
Macros
#define CRYPTSSC2_TEST (/*DIRTYCODE_DEBUG && */ TRUE)
Typedefs
typedef struct CryptSSC2T CryptSSC2T
Functions
DIRTYCODE_API void CryptSSC2Init (CryptSSC2T *pState, const unsigned char *pKey, int32_t iKey, int32_t iIter)
Init the cipher for use based on key/iter count.
DIRTYCODE_API void CryptSSC2Apply (CryptSSC2T *pState, unsigned char *pData, int32_t iData)
Apply the cipher to the target data. Uses xor so the process is reversible.
DIRTYCODE_API int32_t CryptSSC2StringEncrypt (char *pDst, int32_t iLen, const char *pSrc, const unsigned char *pKey, int32_t iKey, int32_t iIter)
Easy way to encode an asciiz string. The resulting string is iLen chars of visible ascii characters.
DIRTYCODE_API int32_t CryptSSC2StringDecrypt (char *pDst, int32_t iLen, const char *pSrc, const unsigned char *pKey, int32_t iKey, int32_t iIter)
Easy way to encode an asciiz string. The resulting string is iLen chars of visible ascii characters.
Detailed Description
Macro Definition Documentation
#define CRYPTSSC2_TEST (/*DIRTYCODE_DEBUG && */ TRUE)
Typedef Documentation
typedef struct CryptSSC2T CryptSSC2T
Function Documentation
DIRTYCODE_API void CryptSSC2Apply (CryptSSC2T * pState, unsigned char * pData, int32_t iData)
Apply the cipher to the target data. Uses xor so the process is reversible.
Parameters
*pState - cipher state from create
*pData - pointer to data to apply cipher to
iData - length of target data
Returns
None.
Note
None.
Version
1.0 03/15/02 (GWS) First Version
References CryptSSC2T::crc, CryptSSC2T::idx, and CryptSSC2T::sbox.
Referenced by CryptSSC2StringDecrypt(), and CryptSSC2StringEncrypt().
DIRTYCODE_API void CryptSSC2Init (CryptSSC2T * pState, const unsigned char * pKey, int32_t iKey, int32_t iIter)
Init the cipher for use based on key/iter count.
Parameters
*pState - cipher state from create
*pKey - key data pointer
iKey - length of key (-1=assume key is an asciiz string)
iIter - initialization iteration count (higher is slower but more secure)
Returns
None.
Note
None.
Version
1.0 03/15/02 (GWS) First Version
References CryptSSC2T::crc, CryptSSC2T::idx, and CryptSSC2T::sbox.
Referenced by CryptSSC2StringDecrypt(), and CryptSSC2StringEncrypt().
DIRTYCODE_API int32_t CryptSSC2StringDecrypt (char * pDst, int32_t iLen, const char * pSrc, const unsigned char * pKey, int32_t iKey, int32_t iIter)
Easy way to encode an asciiz string. The resulting string is iLen chars of visible ascii characters.
Parameters
*pDst - pointer to output string
iLen - length of output string
*pSrc - pointer to source string (asciiz)
*pKey - key to ecrypt with
iKey - length of key (-1=key is asciiz)
iIter - number of initialization iterations
Returns
int32_t - success
Note
None.
Version
1.0 03/15/02 (GWS) First Version
References CryptSSC2Apply(), and CryptSSC2Init().
DIRTYCODE_API int32_t CryptSSC2StringEncrypt (char * pDst, int32_t iLen, const char * pSrc, const unsigned char * pKey, int32_t iKey, int32_t iIter)
Easy way to encode an asciiz string. The resulting string is iLen chars of visible ascii characters.
Parameters
*pDst - pointer to output string
iLen - length of output string
*pSrc - pointer to source string (asciiz)
*pKey - key to ecrypt with
iKey - length of key (-1=key is asciiz)
iIter - number of initialization iterations
Returns
int32_t - success
Note
None.
Version
1.0 03/15/02 (GWS) First Version
References CryptSSC2Apply(), CryptSSC2Init(), and NULL.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:20