DirtySock: LobbyLan
LobbyLan
Misc
Data Structures
struct LobbyLanPlyrInfoT
player info
struct LobbyLanPlyrListT
player list
struct LobbyLanGameInfoT
game info
struct LobbyLanGameListT
list of games
Macros
#define LOBBYLAN_GAMENAME_LEN (32)
max game name length
#define LOBBYLAN_PLYRNAME_LEN (32)
max player name length
#define LOBBYLAN_PASSWORD_LEN (16)
max game password length
#define LOBBYLAN_GAMENOTE_LEN (116)
max game parameter length
#define LOBBYLAN_PLYRNOTE_LEN (116)
max player parameter length
#define LOBBYLAN_GAMEFLAG_NONE (0)
no game flags
#define LOBBYLAN_GAMEFLAG_AUTOSTART (1)
autostart when game is filled
#define LobbyLanCreate(_pSelfName, _pSelfAddr, _pKind, _uMaxGames) LobbyLanCreate2(_pSelfName, _pSelfAddr, _pKind, _uMaxGames, (CommAllConstructT *)CommUDPConstruct)
Typedefs
typedef enum LobbyLanCBTypeE LobbyLanCBTypeE
LobbyLan callback types.
typedef struct LobbyLanPlyrInfoT LobbyLanPlyrInfoT
player info
typedef struct LobbyLanPlyrListT LobbyLanPlyrListT
player list
typedef struct LobbyLanGameInfoT LobbyLanGameInfoT
game info
typedef struct LobbyLanGameListT LobbyLanGameListT
list of games
typedef struct LobbyLanRefT LobbyLanRefT
opaque LobbyLan ref
typedef int32_t(LobbyLanCallbackT)(LobbyLanRefT *pRef, LobbyLanCBTypeE eType, void *pCbData, void *pUserData)
LobbyLan callback function prototype.
Enumerations
enum LobbyLanCBTypeE {
LOBBYLAN_CBTYPE_GAMELIST,
LOBBYLAN_CBTYPE_GAMEJOIN,
LOBBYLAN_CBTYPE_GAMEFULL,
LOBBYLAN_CBTYPE_GAMEPASS,
LOBBYLAN_CBTYPE_GAMEREFU,
LOBBYLAN_CBTYPE_PLYRLIST,
LOBBYLAN_CBTYPE_GAMESTRT,
LOBBYLAN_CBTYPE_GAMEKILL,
LOBBYLAN_CBTYPE_PLYRKILL,
LOBBYLAN_CBTYPE_JOINREQU,
LOBBYLAN_NUMCBTYPES
}
LobbyLan callback types.
Functions
DIRTYCODE_API LobbyLanRefT * LobbyLanCreate2 (const char *pSelfName, const DirtyAddrT *pSelfAddr, const char *pKind, uint32_t uMaxGames, CommAllConstructT *pConstruct)
Create the LobbyLan module.
DIRTYCODE_API void LobbyLanDestroy (LobbyLanRefT *pRef)
Destroy the LobbyLan module.
DIRTYCODE_API void LobbyLanSetCallback (LobbyLanRefT *pRef, LobbyLanCallbackT *pCallback, void *pUserData)
Set LobbyLan callback function.
DIRTYCODE_API void LobbyLanReset (LobbyLanRefT *pRef)
Reset module state.
DIRTYCODE_API int32_t LobbyLanCreateGame (LobbyLanRefT *pRef, uint32_t uGameFlags, const char *pName, const char *pNote, const char *pPassword, uint32_t uMaxPlayers)
Create a new game as host and join it.
DIRTYCODE_API void LobbyLanSetNote (LobbyLanRefT *pRef, const char *pNote)
Set game note, if hosting a game.
DIRTYCODE_API void LobbyLanSetPlyrNote (LobbyLanRefT *pRef, const char *pNote)
Set our player note.
DIRTYCODE_API int32_t LobbyLanStartGame (LobbyLanRefT *pRef)
Start a game (game host only)
DIRTYCODE_API int32_t LobbyLanJoinGame (LobbyLanRefT *pRef, const char *pName, const char *pPassword)
Join a game.
DIRTYCODE_API int32_t LobbyLanJoinGameByIndex (LobbyLanRefT *pRef, int32_t iGameIndex, const char *pPassword)
Join a game by index.
DIRTYCODE_API int32_t LobbyLanSendto (LobbyLanRefT *pRef, NetGamePacketT *pPacket, int32_t iClientId)
Send a packet to a client using link interface.
DIRTYCODE_API int32_t LobbyLanRecvfrom (LobbyLanRefT *pRef, NetGamePacketT *pPacket, int32_t iClientId)
Receive a packet from a peer using link interface.
DIRTYCODE_API int32_t LobbyLanLeaveGame (LobbyLanRefT *pRef)
Leave current game.
DIRTYCODE_API const
LobbyLanGameListT * LobbyLanGetGameList (LobbyLanRefT *pRef)
Get game list.
DIRTYCODE_API const
LobbyLanGameInfoT * LobbyLanGetGameInfo (LobbyLanRefT *pRef, const char *pName)
Get current game info.
DIRTYCODE_API void LobbyLanGetPlyrList (LobbyLanRefT *pRef, LobbyLanPlyrListT *pPlyrList)
Get player list for local (hosted/joined) game.
DIRTYCODE_API int32_t LobbyLanStatus (LobbyLanRefT *pRef, int32_t iSelect, int32_t iData, void *pBuf, int32_t iBufSize)
Get status information.
DIRTYCODE_API int32_t LobbyLanControl (LobbyLanRefT *pRef, int32_t iControl, int32_t iValue, void *pValue)
Control behavior of module.
Detailed Description
Macro Definition Documentation
#define LOBBYLAN_GAMEFLAG_AUTOSTART (1)
autostart when game is filled
#define LOBBYLAN_GAMEFLAG_NONE (0)
no game flags
#define LOBBYLAN_GAMENAME_LEN (32)
max game name length
#define LOBBYLAN_GAMENOTE_LEN (116)
max game parameter length
#define LOBBYLAN_PASSWORD_LEN (16)
max game password length
#define LOBBYLAN_PLYRNAME_LEN (32)
max player name length
#define LOBBYLAN_PLYRNOTE_LEN (116)
max player parameter length
Referenced by LobbyLanSetPlyrNote().
#define LobbyLanCreate (_pSelfName, _pSelfAddr, _pKind, _uMaxGames) LobbyLanCreate2(_pSelfName, _pSelfAddr, _pKind, _uMaxGames, (CommAllConstructT *)CommUDPConstruct)
Typedef Documentation
typedef int32_t(LobbyLanCallbackT)(LobbyLanRefT *pRef, LobbyLanCBTypeE eType, void *pCbData, void *pUserData)
LobbyLan callback function prototype.
typedef enum LobbyLanCBTypeE LobbyLanCBTypeE
LobbyLan callback types.
typedef struct LobbyLanGameInfoT LobbyLanGameInfoT
game info
typedef struct LobbyLanGameListT LobbyLanGameListT
list of games
typedef struct LobbyLanPlyrInfoT LobbyLanPlyrInfoT
player info
player info
typedef struct LobbyLanPlyrListT LobbyLanPlyrListT
player list
player info
typedef struct LobbyLanRefT LobbyLanRefT
opaque LobbyLan ref
Enumeration Type Documentation
enum LobbyLanCBTypeE
LobbyLan callback types.
Enumerator
LOBBYLAN_CBTYPE_GAMELIST
the list of available games has changed
LOBBYLAN_CBTYPE_GAMEJOIN
indicates game has been successfully joined
LOBBYLAN_CBTYPE_GAMEFULL
indicates game is full
LOBBYLAN_CBTYPE_GAMEPASS
indicates password was rejected
LOBBYLAN_CBTYPE_GAMEREFU
host refused join
LOBBYLAN_CBTYPE_PLYRLIST
the list of players in game room has changed
LOBBYLAN_CBTYPE_GAMESTRT
the game has been started
LOBBYLAN_CBTYPE_GAMEKILL
the game has been withdrawn by the host
LOBBYLAN_CBTYPE_PLYRKILL
the connection to the given player has been terminated
LOBBYLAN_CBTYPE_JOINREQU
[host only] - client join request - return >0 to accept, <0 to reject, 0 to wait
LOBBYLAN_NUMCBTYPES
number of callback types
Function Documentation
DIRTYCODE_API int32_t LobbyLanControl (LobbyLanRefT * pRef, int32_t iControl, int32_t iValue, void * pValue)
Control behavior of module.
Parameters
*pRef - module state ref
iControl - control selector
iValue - selector-specific
*pValue - selector-specific
Returns
int32_t - selector-specific
Note
iControl can be one of the following:
        'advf' - set advert freq - iValue=frequency in seconds
        'dlat' - display latency - iValue=frequency in seconds [DEBUG ONLY]
        'gprt' - set port for game communications - iValue=port
        'kcon' - set keep-connection status - iValue=TRUE or FALSE
        'mwid' - set maximum packet width - iValue=size in bytes
        'time' - set peer connection timeout - iValue=timeout in ms (default 5000)
Unhandled selectors are passed through to NetGameUtilControl() if the ref is not NULL.
Version
02/16/2005 (jbrookes)
References LobbyLanRefT::bKeepConn, LobbyLanRefT::iAdvtFreq, LobbyLanRefT::iGamePort, LobbyLanRefT::iLinkBufSize, LobbyLanRefT::iLocalGames, LobbyLanRefT::iMaxInp, LobbyLanRefT::iMaxOut, LobbyLanRefT::iMaxPacket, LobbyLanRefT::iTimeout, NetGameUtilControl(), NetPrintf, and LobbyLanRefT::pGameUtilRef.
DIRTYCODE_API LobbyLanRefT* LobbyLanCreate2 (const char * pSelfName, const DirtyAddrT * pSelfAddr, const char * pKind, uint32_t uMaxGames, CommAllConstructT * pConstruct)
Create the LobbyLan module.
Parameters
*pSelfName - pointer to local client's name
*pSelfAddr - pointer to local client's address
*pKind - unique title identifier
uMaxGames - max number of games viewable
*pConstruct - comm construct function
Returns
LobbyLanRefT * - pointer to new module, or NULL if creation failed
Version
09/15/2004 (jbrookes)
References LobbyLanPlyrInfoT::Addr, LobbyLanRefT::bKeepConn, DirtyMemAlloc(), DirtyMemFree(), DirtyMemGroupQuery(), ds_strnzcpy(), LobbyLanRefT::iAdvtFreq, LobbyLanRefT::iGamePort, LobbyLanRefT::iHosting, LobbyLanRefT::iLinkBufSize, LobbyLanRefT::iMaxPacket, LobbyLanRefT::iMemGroup, LobbyLanRefT::iTimeout, LOBBYLAN_GAMECONN_TIMEOUT, LOBBYLAN_GameListSize, LOBBYLAN_MEMID, NetConnIdleAdd(), NETGAME_DATAPKT_DEFSIZE, NetPrintf, LobbyLanRefT::pCallback, LobbyLanRefT::pCommConstruct, LobbyLanRefT::pGameList, LobbyLanRefT::pMemGroupUserData, pRef, LobbyLanRefT::Self, LobbyLanRefT::strKind, DirtyAddrT::strMachineAddr, LobbyLanPlyrInfoT::strName, TRUE, LobbyLanGameListT::uMaxGames, and LobbyLanRefT::uMaxGames.
DIRTYCODE_API int32_t LobbyLanCreateGame (LobbyLanRefT * pRef, uint32_t uGameFlags, const char * pName, const char * pNote, const char * pPassword, uint32_t uMaxPlayers)
Create a new game as host and join it.
Parameters
*pRef - module state ref
uGameFlags - game flags (LOBBYLAN_GAMEFLAGS_*)
*pName - pointer to game name
*pNote - pointer to game-specific parameters
*pPassword - pointer to game password (optional)
uMaxPlayers - maximum number of players allowed in game
Returns
int32_t - zero=success, negative=failure
Version
09/15/2004 (jbrookes)
References LobbyLanGameInfoT::bPassword, ds_strnzcpy(), LobbyLanRefT::eState, FALSE, LobbyLanRefT::Game, LobbyLanGameT::GameInfo, LobbyLanRefT::iHosting, NetPrintf, LobbyLanRefT::Self, ST_IDLE, LobbyLanGameInfoT::strName, LobbyLanGameInfoT::strNote, LobbyLanGameT::strPass, TRUE, LobbyLanGameT::uFlags, and LobbyLanGameInfoT::uMaxPlayers.
DIRTYCODE_API void LobbyLanDestroy (LobbyLanRefT * pRef)
Destroy the LobbyLan module.
Parameters
*pRef - module state ref
Version
09/15/2004 (jbrookes)
References DirtyMemFree(), LobbyLanRefT::eState, LobbyLanRefT::iMemGroup, LOBBYLAN_MEMID, LobbyLanLeaveGame(), NetConnIdleDel(), LobbyLanRefT::pGameList, LobbyLanRefT::pMemGroupUserData, and ST_IDLE.
DIRTYCODE_API const LobbyLanGameInfoT* LobbyLanGetGameInfo (LobbyLanRefT * pRef, const char * pName)
Get current game info.
Parameters
*pRef - module state ref
*pName - name of game to get, or NULL for the local game
Returns
const LobbyLanGameInfoT * - pointer to current game info
Version
09/17/2004 (jbrookes)
References LobbyLanRefT::Game, and LobbyLanGameT::GameInfo.
DIRTYCODE_API const LobbyLanGameListT* LobbyLanGetGameList (LobbyLanRefT * pRef)
Get game list.
Parameters
*pRef - module state ref
Returns
const LobbyLanGameListT * - pointer to current game list
Version
09/16/2004 (jbrookes)
References LobbyLanRefT::pGameList.
DIRTYCODE_API void LobbyLanGetPlyrList (LobbyLanRefT * pRef, LobbyLanPlyrListT * pPlyrList)
Get player list for local (hosted/joined) game.
Parameters
*pRef - module state ref
*pPlyrList - [out] pointer to buffer to fill in with player list info
Version
09/21/2004 (jbrookes)
References LobbyLanRefT::Game, LobbyLanGameT::GameInfo, LobbyLanPlyrListT::pPlayers, LobbyLanGameT::pPlyrList, LobbyLanPlyrListT::uMaxPlayers, LobbyLanGameInfoT::uMaxPlayers, LobbyLanPlyrListT::uNumPlayers, and LobbyLanGameInfoT::uNumPlayers.
DIRTYCODE_API int32_t LobbyLanJoinGame (LobbyLanRefT * pRef, const char * pName, const char * pPassword)
Join a game.
Parameters
*pRef - module state ref
*pName - name of game to join
*pPassword - game password
Returns
int32_t - zero=success, negative=failure
Version
09/15/2004 (jbrookes)
References LobbyLanRefT::eState, NetPrintf, and ST_IDLE.
DIRTYCODE_API int32_t LobbyLanJoinGameByIndex (LobbyLanRefT * pRef, int32_t iGameIndex, const char * pPassword)
Join a game by index.
Parameters
*pRef - module state ref
iGameIndex - index of game
*pPassword - game password
Returns
int32_t - zero=success, negative=failure
Version
09/15/2004 (jbrookes)
References LobbyLanRefT::eState, LobbyLanGameListT::Games, NetPrintf, LobbyLanRefT::pGameList, ST_IDLE, and LobbyLanGameListT::uNumGames.
DIRTYCODE_API int32_t LobbyLanLeaveGame (LobbyLanRefT * pRef)
Leave current game.
Parameters
*pRef - module state ref
Returns
int32_t - negative=error, else success
Version
09/16/2004 (jbrookes)
References DirtyMemFree(), LobbyLanConnT::eState, LobbyLanRefT::eState, LobbyLanRefT::Game, GAME_PACKET_USER, LobbyLanGameT::GameInfo, NetGamePacketT::head, LobbyLanRefT::iHosting, LobbyLanRefT::iMemGroup, NetGamePacketHeadT::kind, NetGamePacketHeadT::len, LOBBYLAN_CLNTMESG_QUIT, LOBBYLAN_MEMID, NetPrintf, LobbyLanGameT::pConnList, LobbyLanConnT::pLinkRef, LobbyLanRefT::pMemGroupUserData, LobbyLanGameT::pPlyrList, LobbyLanConnT::pUtilRef, ST_IDLE, and LobbyLanGameInfoT::uNumPlayers.
Referenced by LobbyLanDestroy().
DIRTYCODE_API int32_t LobbyLanRecvfrom (LobbyLanRefT * pRef, NetGamePacketT * pPacket, int32_t iClientId)
Receive a packet from a peer using link interface.
Parameters
*pRef - module state ref
*pPacket - [out] pointer to storage for received packet data
iClientId - index of client to receive from
Returns
int32_t - positive=received data, else zero
Version
04/04/2005 (jbrookes)
References NetGamePacketT::body, NetGamePacketT::data, LobbyLanConnT::eState, LobbyLanRefT::Game, LobbyLanGameT::GameInfo, NetGamePacketT::head, NetGamePacketHeadT::len, LOBBYLAN_USERMESG_DATA, NetGameLinkPeek(), NetPrintf, LobbyLanGameT::pConnList, LobbyLanConnT::pLinkRef, TRUE, and LobbyLanGameInfoT::uNumPlayers.
DIRTYCODE_API void LobbyLanReset (LobbyLanRefT * pRef)
Reset module state.
Parameters
*pRef - module state ref
Version
05/15/2007 (jbrookes)
References NetGameUtilReset(), NetPrintf, LobbyLanRefT::pGameList, LobbyLanRefT::pGameUtilRef, LobbyLanRefT::strQueryBuf, and LobbyLanGameListT::uNumGames.
DIRTYCODE_API int32_t LobbyLanSendto (LobbyLanRefT * pRef, NetGamePacketT * pPacket, int32_t iClientId)
Send a packet to a client using link interface.
Parameters
*pRef - module state ref
*pPacket - pointer to packet data to send
iClientId - index of client to send to
Returns
int32_t - positive=bytes sent, else failure
Note
The input packet buffer should include at least one byte of space over the size of the data, for LobbyLan to append its kind byte to.
Version
04/04/2005 (jbrookes)
References LobbyLanConnT::eState, LobbyLanRefT::Game, LobbyLanGameT::GameInfo, LOBBYLAN_USERMESG_DATA, NetPrintf, LobbyLanGameT::pConnList, LobbyLanConnT::pLinkRef, and LobbyLanGameInfoT::uNumPlayers.
DIRTYCODE_API void LobbyLanSetCallback (LobbyLanRefT * pRef, LobbyLanCallbackT * pCallback, void * pUserData)
Set LobbyLan callback function.
Parameters
*pRef - module state ref
*pCallback - pointer to user callback
*pUserData - pointer to user callback data
Version
09/15/2004 (jbrookes)
References LobbyLanRefT::pCallback, and LobbyLanRefT::pUserData.
DIRTYCODE_API void LobbyLanSetNote (LobbyLanRefT * pRef, const char * pNote)
Set game note, if hosting a game.
Parameters
*pRef - module state ref
*pNote - pointer to new note to use
Version
04/12/2005 (jbrookes)
References ds_strnzcpy(), LobbyLanRefT::Game, LobbyLanGameT::GameInfo, LobbyLanRefT::iHosting, NetPrintf, LobbyLanRefT::pGameUtilRef, and LobbyLanGameInfoT::strNote.
DIRTYCODE_API void LobbyLanSetPlyrNote (LobbyLanRefT * pRef, const char * pNote)
Set our player note.
Parameters
*pRef - module state ref
*pNote - pointer to new note to use
Version
04/19/2005 (jbrookes)
References NetGamePacketT::body, LobbyLanConnT::bPlyrListDirty, NetGamePacketT::data, ds_memcpy_s(), ds_strnzcpy(), LobbyLanRefT::Game, GAME_PACKET_USER, LobbyLanGameT::GameInfo, NetGamePacketT::head, LobbyLanRefT::iHosting, NetGamePacketHeadT::kind, NetGamePacketHeadT::len, LOBBYLAN_CLNTMESG_INFO, LOBBYLAN_PLYRNOTE_LEN, NetPrintf, LobbyLanGameT::pConnList, LobbyLanConnT::pLinkRef, LobbyLanGameT::pPlyrList, LobbyLanRefT::Self, LobbyLanPlyrInfoT::strNote, TRUE, and LobbyLanGameInfoT::uNumPlayers.
DIRTYCODE_API int32_t LobbyLanStartGame (LobbyLanRefT * pRef)
Start a game (game host only)
Parameters
*pRef - module state ref
Returns
int32_t - zero=success, negative=failure
Version
09/15/2004 (jbrookes)
References LobbyLanRefT::bKeepConn, LobbyLanRefT::eState, FALSE, LobbyLanRefT::Game, GAME_PACKET_USER, LobbyLanGameT::GameInfo, NetGamePacketT::head, NetGamePacketHeadT::kind, NetGamePacketHeadT::len, LOBBYLAN_HOSTMESG_STRT, NetGameUtilReset(), NetPrintf, LobbyLanGameT::pConnList, LobbyLanRefT::pGameUtilRef, LobbyLanConnT::pLinkRef, and LobbyLanGameInfoT::uNumPlayers.
DIRTYCODE_API int32_t LobbyLanStatus (LobbyLanRefT * pRef, int32_t iSelect, int32_t iData, void * pBuf, int32_t iBufSize)
Get status information.
Parameters
*pRef - pointer to module state
iSelect - status selector
iData - selector-specific
*pBuf - [out] selector-specific
iBufSize - size of output buffer
Returns
int32_t - selector specific
Note
iSelect can be one of the following:
        'host' - returns true if hosting
        'ingm' - currently 'in game' (connecting to or connected to one or more peers)
        'self' - copies LobbyLanPlyrInfoT for self into output
        'slen' - length of send queue -
        'stat' - copies NetGameLinkStatT for client iData into output buffer
        'strt' - returns true if game has been started
Version
03/16/2005 (jbrookes)
References ds_memcpy(), LobbyLanRefT::eState, LobbyLanRefT::Game, LobbyLanGameT::GameInfo, LobbyLanRefT::iHosting, NetGameLinkControl(), NetGameLinkStatus(), LobbyLanGameT::pConnList, LobbyLanConnT::pLinkRef, LobbyLanRefT::Self, and LobbyLanGameInfoT::uNumPlayers.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:49