DirtySock: voipprivpc.c File Reference
voipprivpc.c File Reference
Private functions for VoIP module use.
#include <windows.h>
#include <stdio.h>
#include <stdarg.h>
#include <wtypes.h>
#include "DirtySDK/platform.h"
#include "DirtySDK/voip/voipdef.h"
#include "voippriv.h"
Functions
uint32_t VoipTimer (VoipTimerT *pTimer)
Returns a high-resolution platform-dependent time value.
int32_t VoipTimerDiff (const VoipTimerT *pTimerA, const VoipTimerT *pTimerB)
Differences two timers (a-b).
Detailed Description
Private functions for VoIP module use.
Attention
Copyright (c) Electronic Arts 2004. ALL RIGHTS RESERVED.
Version
1.0 03/17/2004 (jbrookes) First Version
1.1 11/18/2008 (mclouatre) Move mem group fcts to ../voippriv.c
Function Documentation
uint32_t VoipTimer (VoipTimerT * pTimer)
Returns a high-resolution platform-dependent time value.
Parameters
*pTimer - storage for timer value
Returns
None
Version
1.0 08/26/2004 (jbrookes) First Version
Referenced by VoipCodecDecode(), and VoipCodecEncode().
int32_t VoipTimerDiff (const VoipTimerT * pTimerA, const VoipTimerT * pTimerB)
Differences two timers (a-b).
Parameters
*pTimerA - pointer to first timer
*pTimerB - pointer to second timer
Returns
int32_t - TimerA - TimerB
Version
1.0 08/26/2004 (jbrookes) First Version
References VoipTimerT::uHi, and VoipTimerT::uLo.
Referenced by VoipCodecDecode(), and VoipCodecEncode().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:42