DirtySock: FriendApi
FriendApi
Friend
Data Structures
struct FriendDataT
generic friend data structure
struct BlockedUserDataT
generic blocked user data structure
struct FriendEventDataUnknownT
struct FriendEventDataFriendUpdatedT
struct FriendEventDataFriendRemovedT
struct FriendEventDataBlocklistUpdatedT
struct FriendEventDataBlockUserResultT
struct FriendEventDataMsgRcvedT
union FriendEventTypeDataT
struct FriendEventDataT
Macros
#define FRIENDAPI_FRIENDID_MAXLEN (20)
#define FRIENDAPI_FRIENDNAME_MAXLEN (16)
#define FRIENDAPI_EVENTMSG_MAXSIZE (512)
#define FRIENDAPI_MAX_FRIENDS (100)
#define FRIENDAPI_BLOCKEDUSERID_MAXLEN (16)
#define FRIENDAPI_MAX_BLOCKED_USERS (50)
#define FRIENDAPI_MAX_CALLBACKS (8)
Typedefs
typedef enum FriendApiEventsE FriendApiEventsE
FriendApi event types.
typedef struct FriendApiRefT FriendApiRefT
opaque module ref
typedef struct FriendDataT FriendDataT
generic friend data structure
typedef struct BlockedUserDataT BlockedUserDataT
generic blocked user data structure
typedef struct
FriendEventDataUnknownT FriendEventDataUnknownT
typedef struct
FriendEventDataFriendUpdatedT FriendEventDataFriendUpdatedT
typedef struct
FriendEventDataFriendRemovedT FriendEventDataFriendRemovedT
typedef struct
FriendEventDataBlocklistUpdatedT FriendEventDataBlocklistUpdatedT
typedef struct
FriendEventDataBlockUserResultT FriendEventDataBlockUserResultT
typedef struct
FriendEventDataMsgRcvedT FriendEventDataMsgRcvedT
typedef union FriendEventTypeDataT FriendEventTypeDataT
typedef struct FriendEventDataT FriendEventDataT
typedef void(FriendApiNotifyCbT)(FriendApiRefT *pFriendApiRef, FriendEventDataT *pEventData, void *pNotifyCbUserData)
Enumerations
enum FriendApiEventsE {
FRIENDAPI_EVENT_UNKNOWN,
FRIENDAPI_EVENT_FRIEND_UPDATED,
FRIENDAPI_EVENT_FRIEND_REMOVED,
FRIENDAPI_EVENT_BLOCKLIST_UPDATED,
FRIENDAPI_EVENT_BLOCK_USER_RESULT,
FRIENDAPI_EVENT_MSG_RCVED,
FRIENDAPI_EVENT_INIT_COMPLETE,
FRIENDAPI_EVENT_MAX
}
FriendApi event types.
Functions
DIRTYCODE_API FriendApiRefT * FriendApiCreate (void)
Create the friendapi object.
DIRTYCODE_API int32_t FriendApiAddCallback (FriendApiRefT *pFriendApiRef, FriendApiNotifyCbT *pNotifyCb, void *pNotifyCbUserData)
Register callback for friends notifications.
DIRTYCODE_API int32_t FriendApiRemoveCallback (FriendApiRefT *pFriendApiRef, FriendApiNotifyCbT *pNotifyCb, void *pNotifyCbUserData)
Unregister a callback.
DIRTYCODE_API void FriendApiUpdate (FriendApiRefT *pFriendApiRef)
Give module time to perform periodic processing.
DIRTYCODE_API int32_t FriendApiGetFriendsList (FriendApiRefT *pFriendApiRef, uint32_t uUserIndex, FriendDataT *pFriendsList, void *pRawDataList1, int32_t *pFriendsCount)
Returns the number of friends and list of friends in the user-provided buffers (also returns corresponding list of 1st-party friend data structures).
DIRTYCODE_API int32_t FriendApiGetFriendsListVersion (FriendApiRefT *pFriendApiRef, uint32_t *pVersion)
Returns the current version of friendslist.
DIRTYCODE_API int32_t FriendApiStatus (FriendApiRefT *pFriendApiRef, int32_t iSelect, void *pBuf, int32_t iBufSize)
Get status information.
DIRTYCODE_API int32_t FriendApiControl (FriendApiRefT *pFriendApiRef, int32_t iControl, int32_t iValue, int32_t iValue2, void *pValue)
Control behavior of module.
DIRTYCODE_API void FriendApiDestroy (FriendApiRefT *pFriendApiRef)
Destroy the friend api object.
DIRTYCODE_API uint32_t FriendApiIsUserFriend (FriendApiRefT *pFriendApiRef, uint32_t uUserIndex, void *pUserId)
DIRTYCODE_API uint32_t FriendApiIsUserRealFriend (FriendApiRefT *pFriendApiRef, uint32_t uUserIndex, void *pUserId)
DIRTYCODE_API uint32_t FriendApiIsUserBlocked (FriendApiRefT *pFriendApiRef, uint32_t uUserIndex, void *pUserId)
Returns whether a given user is blocked or not.
DIRTYCODE_API int32_t FriendApiBlockUser (FriendApiRefT *pFriendApiRef, uint32_t uUserIndex, void *pUserId)
Block user.
DIRTYCODE_API int32_t FriendApiUnblockUser (FriendApiRefT *pFriendApiRef, uint32_t uUserIndex, void *pUserId)
Unblock user.
DIRTYCODE_API int32_t FriendApiGetBlockListVersion (FriendApiRefT *pFriendApiRef, uint32_t *pVersion)
Returns the current version of the list of blocked users. PS3 only, returns 0 for other platforms.
DIRTYCODE_API int32_t FriendApiGetBlockList (FriendApiRefT *pFriendApiRef, uint32_t uUserIndex, BlockedUserDataT *pBlockList, int32_t *pUsersCount)
Returns the list of blocked users in the user-provided buffers PS3 only, always returns empty list on other platforms.
Detailed Description
Macro Definition Documentation
#define FRIENDAPI_BLOCKEDUSERID_MAXLEN (16)
#define FRIENDAPI_EVENTMSG_MAXSIZE (512)
#define FRIENDAPI_FRIENDID_MAXLEN (20)
#define FRIENDAPI_FRIENDNAME_MAXLEN (16)
#define FRIENDAPI_MAX_BLOCKED_USERS (50)
#define FRIENDAPI_MAX_CALLBACKS (8)
Referenced by FriendApiAddCallback(), and FriendApiRemoveCallback().
#define FRIENDAPI_MAX_FRIENDS (100)
Typedef Documentation
typedef struct BlockedUserDataT BlockedUserDataT
generic blocked user data structure
typedef enum FriendApiEventsE FriendApiEventsE
FriendApi event types.
typedef void(FriendApiNotifyCbT)(FriendApiRefT *pFriendApiRef, FriendEventDataT *pEventData, void *pNotifyCbUserData)
optional friend notification callback Note: for some event types, pEventData and pFriendData can be NULL!
typedef struct FriendApiRefT FriendApiRefT
opaque module ref
typedef struct FriendDataT FriendDataT
generic friend data structure
typedef struct FriendEventDataBlocklistUpdatedT FriendEventDataBlocklistUpdatedT
typedef struct FriendEventDataBlockUserResultT FriendEventDataBlockUserResultT
typedef struct FriendEventDataFriendRemovedT FriendEventDataFriendRemovedT
typedef struct FriendEventDataFriendUpdatedT FriendEventDataFriendUpdatedT
typedef struct FriendEventDataMsgRcvedT FriendEventDataMsgRcvedT
typedef struct FriendEventDataT FriendEventDataT
typedef struct FriendEventDataUnknownT FriendEventDataUnknownT
typedef union FriendEventTypeDataT FriendEventTypeDataT
Enumeration Type Documentation
enum FriendApiEventsE
FriendApi event types.
Enumerator
FRIENDAPI_EVENT_UNKNOWN
unknown friend event
FRIENDAPI_EVENT_FRIEND_UPDATED
a friend was added or modified
FRIENDAPI_EVENT_FRIEND_REMOVED
a friend was removed
FRIENDAPI_EVENT_BLOCKLIST_UPDATED
the list of blocked friends has changed
FRIENDAPI_EVENT_BLOCK_USER_RESULT
completion notification for FriendApiBlockUser()
FRIENDAPI_EVENT_MSG_RCVED
message received
FRIENDAPI_EVENT_INIT_COMPLETE
signal completion of the the first upload of friendlist and blocklist
FRIENDAPI_EVENT_MAX
number of events
Function Documentation
DIRTYCODE_API int32_t FriendApiAddCallback (FriendApiRefT * pFriendApiRef, FriendApiNotifyCbT * pNotifyCb, void * pNotifyCbUserData)
Register callback for friends notifications.
Parameters
*pFriendApiRef - module reference
*pNotifyCb - user-provided callback (cannot be NULL)
*pNotifyCbUserData - user data to be passed when invoking the callback (can be NULL)
Returns
int32_t - negative means error. 0 or greater: slot used
Version
04/19/2010 (mclouatre)
References FriendApiCommonRefT::callback, FriendApiRefT::common, FRIENDAPI_MAX_CALLBACKS, NetPrintf, NULL, FriendApiCallbackT::pNotifyCb, and FriendApiCallbackT::pNotifyCbUserData.
DIRTYCODE_API int32_t FriendApiBlockUser (FriendApiRefT * pFriendApiRef, uint32_t uUserIndex, void * pUserId)
Block user.
Parameters
*pFriendApiRef - module reference
uUserIndex - local user index
*pUserId - user to be blocked on xenon: pUserId needs to point to a XUID on PS3: pUserId needs to point to a SceNpId struct
Returns
uint32_t - 0 for success, negative for failure
Version
06/01/2011 (mclouatre)
DIRTYCODE_API int32_t FriendApiControl (FriendApiRefT * pFriendApiRef, int32_t iControl, int32_t iValue, int32_t iValue2, void * pValue)
Control behavior of module.
Parameters
*pFriendApiRef - module reference
iControl - status selector
iValue - control value
iValue2 - control value
*pValue - control value
Returns
int32_t - selector specific
Version
06/01/2011 (mclouatre)
References NetPrintf.
DIRTYCODE_API FriendApiRefT* FriendApiCreate (void)
Create the friendapi object.
Returns
FriendApiRefT* - module reference (NULL = failed)
Version
04/19/2010 (mclouatre)
References FriendApiRefT::common, DirtyMemAlloc(), DirtyMemGroupQuery(), FRIENDAPI_MEMID, FriendApiCommonRefT::iMemGroup, NetPrintf, NULL, and FriendApiCommonRefT::pMemGroupUserData.
DIRTYCODE_API void FriendApiDestroy (FriendApiRefT * pFriendApiRef)
Destroy the friend api object.
Parameters
*pFriendApiRef - module reference
Version
06/01/2011 (mclouatre)
References FriendApiRefT::common, DirtyMemFree(), FRIENDAPI_MEMID, FriendApiCommonRefT::iMemGroup, NetPrintf, and FriendApiCommonRefT::pMemGroupUserData.
DIRTYCODE_API int32_t FriendApiGetBlockList (FriendApiRefT * pFriendApiRef, uint32_t uUserIndex, BlockedUserDataT * pBlockList, int32_t * pUsersCount)
Returns the list of blocked users in the user-provided buffers PS3 only, always returns empty list on other platforms.
Parameters
*pFriendApiRef - module reference
uUserIndex - local user index
*pBlockList - [out] user-provided buffer to be filled with block list (can be NULL)
pUsersCount - [out] user-provided variable to be filled with number of entries in the block list.
Returns
int32_t - return negative in case of error, and 0 otherwise
Note
Set pBlockList to NULL to find out the number of entries that pBlockList will be filled-in with.
Version
06/01/2011 (mclouatre)
DIRTYCODE_API int32_t FriendApiGetBlockListVersion (FriendApiRefT * pFriendApiRef, uint32_t * pVersion)
Returns the current version of the list of blocked users. PS3 only, returns 0 for other platforms.
Parameters
*pFriendApiRef - module reference
*pVersion - pointer to version
Returns
int32_t - return negative in case of error, and 0 otherwise
Version
06/01/2011 (mclouatre)
DIRTYCODE_API int32_t FriendApiGetFriendsList (FriendApiRefT * pFriendApiRef, uint32_t uUserIndex, FriendDataT * pFriendsList, void * pRawDataList1, int32_t * pFriendsCount)
Returns the number of friends and list of friends in the user-provided buffers (also returns corresponding list of 1st-party friend data structures).
Parameters
*pFriendApiRef - module reference
uUserIndex - user index
*pFriendsList - [out] user-provided buffer to be filled with the friends list (can be NULL)
*pRawDataList1 - [out] user-provided buffer to be filled with array of 1st-party friend data structure 1 (can be NULL)
*pFriendsCount - [out] user-provided buffer to be filled with the number of friends in the list
Note
Set all pointers to NULL except pFriendsCount to find out the number of entries that each of the buffers you provide will be filled-in with.
Version
06/01/2011 (mclouatre)
DIRTYCODE_API int32_t FriendApiGetFriendsListVersion (FriendApiRefT * pFriendApiRef, uint32_t * pVersion)
Returns the current version of friendslist.
Parameters
*pFriendApiRef - module reference
*pVersion - pointer to version
Returns
int32_t - return negative in case of error, and 0 otherwise
Version
06/01/2011 (mclouatre)
DIRTYCODE_API uint32_t FriendApiIsUserBlocked (FriendApiRefT * pFriendApiRef, uint32_t uUserIndex, void * pUserId)
Returns whether a given user is blocked or not.
Parameters
*pFriendApiRef - module reference
uUserIndex - local user index
*pUserId - user for which "blocked" status needs to be queried on xenon: pUserId needs to point to a XUID on PS3: pUserId needs to point to a SceNpId struct
Returns
uint32_t - TRUE if user is blocked, FALSE otherwise
Version
06/01/2011 (mclouatre)
References FALSE.
DIRTYCODE_API uint32_t FriendApiIsUserFriend (FriendApiRefT * pFriendApiRef, uint32_t uUserIndex, void * pUserId)
DIRTYCODE_API uint32_t FriendApiIsUserRealFriend (FriendApiRefT * pFriendApiRef, uint32_t uUserIndex, void * pUserId)
DIRTYCODE_API int32_t FriendApiRemoveCallback (FriendApiRefT * pFriendApiRef, FriendApiNotifyCbT * pNotifyCb, void * pNotifyCbUserData)
Unregister a callback.
Parameters
*pFriendApiRef - module reference
*pNotifyCb - the callback to remove (cannot be NULL)
*pNotifyCbUserData - the user data that was originally passed in (can be NULL)
Returns
int32_t - negative means error. 0 or greater: slot freed
Version
06/15/2008 (mclouatre) First Version
References FriendApiCommonRefT::callback, FriendApiRefT::common, FRIENDAPI_MAX_CALLBACKS, NetPrintf, NULL, FriendApiCallbackT::pNotifyCb, and FriendApiCallbackT::pNotifyCbUserData.
DIRTYCODE_API int32_t FriendApiStatus (FriendApiRefT * pFriendApiRef, int32_t iSelect, void * pBuf, int32_t iBufSize)
Get status information.
Parameters
*pFriendApiRef - module reference
iSelect - status selector
*pBuf - [out] storage for selector-specific output
iBufSize - size of output buffer
Returns
int32_t - selector specific
Version
06/01/2011 (mclouatre)
References NetPrintf.
DIRTYCODE_API int32_t FriendApiUnblockUser (FriendApiRefT * pFriendApiRef, uint32_t uUserIndex, void * pUserId)
Unblock user.
Parameters
*pFriendApiRef - module reference
uUserIndex - local user index
*pUserId - user to be unblocked on xenon: pUserId needs to point to a XUID on PS3: pUserId needs to point to a SceNpId struct
Returns
uint32_t - 0 for success, negative for failure
Version
06/01/2011 (mclouatre)
DIRTYCODE_API void FriendApiUpdate (FriendApiRefT * pFriendApiRef)
Give module time to perform periodic processing.
Parameters
*pFriendApiRef - module reference
Version
04/21/2010 (mclouatre)
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:21