DirtySock: CommRef Struct Reference
CommRef Struct Reference
CommAll
common reference type
#include <commall.h>
Data Fields
CommRef *(* Construct)(int32_t maxwid, int32_t maxinp, int32_t maxout)
construct the class
void(* Destroy)(CommRef *what)
destruct the class
int32_t(* Resolve)(struct CommRef *what, const char *addr, char *buf, int32_t len, char iDiv)
resolve an address
void(* Unresolve)(CommRef *what)
stop the resolver
int32_t(* Listen)(CommRef *what, const char *addr)
listen for a connection
int32_t(* Unlisten)(CommRef *what)
stop listening
int32_t(* Connect)(CommRef *what, const char *addr)
initiate a connection to a peer
int32_t(* Unconnect)(CommRef *what)
terminate a connection
void(* Callback)(CommRef *what, void(*callback)(CommRef *ref, int32_t event))
set event callback hook
int32_t(* Status)(CommRef *what)
return current stream status
int32_t(* Control)(CommRef *what, int32_t iControl, int32_t iValue, void *pValue)
control connection behavior (optional)
uint32_t(* Tick)(CommRef *what)
return current clock tick
int32_t(* Send)(CommRef *what, const void *buffer, int32_t length, uint32_t flags)
send a packet
int32_t(* Peek)(CommRef *what, void *target, int32_t length, uint32_t *when)
peek at waiting packet
int32_t(* Recv)(CommRef *what, void *target, int32_t length, uint32_t *when)
receive a packet from the buffer
void(* SendCallback)(CommRef *what, void *buffer, int32_t length, uint32_t when)
send data callback hook
void(* RecvCallback)(CommRef *what, void *target, int32_t length, uint32_t when)
receive data callback hook
int32_t memgroup
module memory group
void * memgrpusrdata
int32_t refnum
user definable storage
void * refptr
user definable reference
SocketT * sockptr
socket ref
uint16_t maxwid
maximum packet width (read only)
uint8_t maxinp
maximum number of input packets buffered
uint8_t maxout
maximum number of output packets buffered
int32_t datasent
data transfer statistics (read only)
int32_t datarcvd
data transfer statistics (read only)
int32_t packsent
data transfer statistics (read only)
int32_t packrcvd
data transfer statistics (read only)
int32_t packlost
data transfer statistics (read only)
uint32_t packsaved
data tranfer statictics (read only)
int32_t naksent
data transfer statistics (read only)
int32_t overhead
data transfer statistics (read only)
int32_t rcvoverhead
data transfer statistics (read only)
uint32_t hostip
< host ip address (read only)
uint32_t peerip
host port (read only)
uint16_t hostport
peer port (read only)
uint16_t peerport
if packet was received (read on;y)
uint8_t bpackrcvd
uint8_t _pad [3]
Detailed Description
common reference type
Field Documentation
uint8_t CommRef::_pad[3]
uint8_t CommRef::bpackrcvd
Referenced by NetGameUtilStatus().
void(* CommRef::Callback)(CommRef *what, void(*callback)(CommRef *ref, int32_t event))
set event callback hook
Note1: this is an optional callback which is called after new data has been received and buffered or at other times where the protocol state has significantly changed. It is called by a private thread so the routines it uses must be thread safe. It can be used to provide "life" to servers or other modules which use comm services. The code must not take too long to execute since it will impact comm performance if it does.
Note2: By disabling and enabling this callback at specific times, it is possible to avoid threading concerns in the upper layer (i.e., if you disable the callback while the callback is executing, this call will block until the callback completes).
entry: comm reference exit: none
Referenced by CommSRPConstruct(), CommTCPConstruct(), CommUDPConstruct(), NetGameLinkCreate(), and NetGameLinkDestroy().
int32_t(* CommRef::Connect)(CommRef *what, const char *addr)
initiate a connection to a peer
note: does not currently perform dns translation
entry: addr=address in ip-address:port form exit: negative=error, zero=ok
Referenced by CommSRPConstruct(), CommTCPConstruct(), CommUDPConstruct(), and NetGameUtilConnect().
CommRef*(* CommRef::Construct)(int32_t maxwid, int32_t maxinp, int32_t maxout)
construct the class
note: initialized winsock for first class. also creates linked list of all current instances of the class and worker thread to do most udp stuff.
entry: maxwid=max record width, maxinp/maxout=input/output packet buffer size exit: none
Referenced by CommSRPConstruct(), CommTCPConstruct(), and CommUDPConstruct().
int32_t(* CommRef::Control)(CommRef *what, int32_t iControl, int32_t iValue, void *pValue)
control connection behavior (optional)
see specific implementation for entry and exit parameter descriptions
Referenced by CommUDPConstruct(), NetGameLinkControl(), NetGameUtilConnect(), and NetGameUtilControl().
int32_t CommRef::datarcvd
data transfer statistics (read only)
int32_t CommRef::datasent
data transfer statistics (read only)
void(* CommRef::Destroy)(CommRef *what)
destruct the class
entry: none exit: none
Referenced by CommSRPConstruct(), CommTCPConstruct(), CommUDPConstruct(), NetGameLinkDestroy(), NetGameUtilConnect(), and NetGameUtilReset().
uint32_t CommRef::hostip
< host ip address (read only)
peer ip address (read only)
Referenced by NetGameUtilConnect().
uint16_t CommRef::hostport
peer port (read only)
Referenced by NetGameUtilConnect().
int32_t(* CommRef::Listen)(CommRef *what, const char *addr)
listen for a connection
entry: addr=port to listen on (only :port portion used) exit: negative=error, zero=ok
Referenced by CommSRPConstruct(), CommTCPConstruct(), CommUDPConstruct(), and NetGameUtilConnect().
uint8_t CommRef::maxinp
maximum number of input packets buffered
Referenced by CommSRPConstruct(), CommTCPConstruct(), and CommUDPConstruct().
uint8_t CommRef::maxout
maximum number of output packets buffered
Referenced by CommSRPConstruct(), CommTCPConstruct(), and CommUDPConstruct().
uint16_t CommRef::maxwid
maximum packet width (read only)
Referenced by CommSRPConstruct(), CommTCPConstruct(), CommUDPConstruct(), and NetGameLinkControl().
int32_t CommRef::memgroup
module memory group
Referenced by CommSRPConstruct(), CommSRPDestroy(), CommTCPConstruct(), CommTCPDestroy(), CommUDPConstruct(), and CommUDPDestroy().
void* CommRef::memgrpusrdata
Referenced by CommSRPConstruct(), CommSRPDestroy(), CommTCPConstruct(), CommTCPDestroy(), CommUDPConstruct(), and CommUDPDestroy().
int32_t CommRef::naksent
data transfer statistics (read only)
int32_t CommRef::overhead
data transfer statistics (read only)
int32_t CommRef::packlost
data transfer statistics (read only)
int32_t CommRef::packrcvd
data transfer statistics (read only)
uint32_t CommRef::packsaved
data tranfer statictics (read only)
int32_t CommRef::packsent
data transfer statistics (read only)
Referenced by NetGameLinkStatus().
int32_t(* CommRef::Peek)(CommRef *what, void *target, int32_t length, uint32_t *when)
peek at waiting packet
entry: target=target buffer, length=buffer length, when=tick received at exit: negative=nothing pending, else packet length
Referenced by CommSRPConstruct(), CommTCPConstruct(), and CommUDPConstruct().
uint32_t CommRef::peerip
host port (read only)
Referenced by NetGameUtilComplete().
uint16_t CommRef::peerport
if packet was received (read on;y)
Referenced by NetGameUtilComplete().
int32_t CommRef::rcvoverhead
data transfer statistics (read only)
int32_t(* CommRef::Recv)(CommRef *what, void *target, int32_t length, uint32_t *when)
receive a packet from the buffer
entry: target=target buffer, length=buffer length, what=tick received at exit: negative=error, else packet length
Referenced by CommSRPConstruct(), CommTCPConstruct(), and CommUDPConstruct().
void(* CommRef::RecvCallback)(CommRef *what, void *target, int32_t length, uint32_t when)
receive data callback hook
Note: this is an optional callback which is called immediately after a packet is received. By the time this function is called, the packet is available for input via the Recv function.
entry: same as Recv exit: none
int32_t CommRef::refnum
user definable storage
void* CommRef::refptr
user definable reference
Referenced by NetGameLinkCreate().
int32_t(* CommRef::Resolve)(struct CommRef *what, const char *addr, char *buf, int32_t len, char iDiv)
resolve an address
entry: what=endpoint ref, addr=address, buffer=target buffer, buflen=length exit: <0=error, 0=in progress, >0=complete
Referenced by CommSRPConstruct(), CommTCPConstruct(), and CommUDPConstruct().
int32_t(* CommRef::Send)(CommRef *what, const void *buffer, int32_t length, uint32_t flags)
send a packet
note: zero length packets may not be sent (they are ignored)
entry: buffer=pointer to data, length=length of data, flags=COMM_FLAGS_* (see defines above) exit: negative=error, zero=ok
Referenced by CommSRPConstruct(), CommTCPConstruct(), CommUDPConstruct(), and NetGameLinkControl().
void(* CommRef::SendCallback)(CommRef *what, void *buffer, int32_t length, uint32_t when)
send data callback hook
Note: this is an optional callback which is called immediately before a packet is transmitted. Due to error handling, it may get called more than once for the same packet if the packet is sent more than once.
entry: same as Send exit: none
Referenced by NetGameLinkCreate().
SocketT* CommRef::sockptr
socket ref
Referenced by NetGameUtilConnect().
int32_t(* CommRef::Status)(CommRef *what)
return current stream status
entry: none exit: CONNECTING, OFFLINE, ONLINE or FAILURE
Referenced by CommSRPConstruct(), CommTCPConstruct(), CommUDPConstruct(), NetGameLinkStatus(), and NetGameUtilComplete().
uint32_t(* CommRef::Tick)(CommRef *what)
return current clock tick
entry: none exit: elapsed millisecs from some epoch
Referenced by CommSRPConstruct(), CommTCPConstruct(), and CommUDPConstruct().
int32_t(* CommRef::Unconnect)(CommRef *what)
terminate a connection
entry: none exit: negative=error, zero=ok
Referenced by CommSRPConstruct(), CommTCPConstruct(), and CommUDPConstruct().
int32_t(* CommRef::Unlisten)(CommRef *what)
stop listening
entry: none exit: negative=error, zero=ok
Referenced by CommSRPConstruct(), CommTCPConstruct(), and CommUDPConstruct().
void(* CommRef::Unresolve)(CommRef *what)
stop the resolver
entry: what=endpoint ref exit: none
Referenced by CommSRPConstruct(), CommTCPConstruct(), and CommUDPConstruct().
The documentation for this struct was generated from the following file:
commall.h
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:21