DirtySock: ProtoPingManager
ProtoPingManager
Proto
Macros
#define PINGMGR_PINGSTATUS_PINGING (-1)
this address is currently being pinged
#define PINGMGR_PINGSTATUS_TIMEOUT (-2)
ping of this address timed out
Typedefs
typedef struct PingManagerRefT PingManagerRefT
ping manager ref
Functions
DIRTYCODE_API typedef void() PingManagerCallbackT (DirtyAddrT *pAddr, uint32_t uPing, void *pUserData)
ping manager callback type
DIRTYCODE_API PingManagerRefT * PingManagerCreate (uint32_t uMaxRecords)
Create PingManager module.
DIRTYCODE_API void PingManagerDestroy (PingManagerRefT *pPingManager)
Shut down PingManager module.
DIRTYCODE_API void PingManagerUpdate (PingManagerRefT *pPingManager)
Give life to PingManager.
DIRTYCODE_API int32_t PingManagerPingAddress (PingManagerRefT *pPingManager, DirtyAddrT *pAddr, PingManagerCallbackT *pCallback, void *pCallbackData)
Ping an address.
DIRTYCODE_API int32_t PingManagerPingServer (PingManagerRefT *pPingManager, uint32_t uServerAddress, PingManagerCallbackT *pCallback, void *pCallbackData)
Ping server. This is a direct pass-through to ProtoPingRequestServer.
DIRTYCODE_API int32_t PingManagerPingServer2 (PingManagerRefT *pPingManager, uint32_t uServerAddress, PingManagerCallbackT *pCallback, void *pCallbackData)
Ping server. This is a direct pass-through to ProtoPingRequestServer.
DIRTYCODE_API int32_t PingManagerInvalidateAddress (PingManagerRefT *pPingManager, DirtyAddrT *pAddr)
Invalidate an address in the cache. This forces PingManager to issue a new ping the next time PingManagerPingAddress() is called with this address.
DIRTYCODE_API void PingManagerInvalidateCache (PingManagerRefT *pPingManager)
Invalidate all addresses in the cache.
DIRTYCODE_API void PingManagerCancelRequest (PingManagerRefT *pPingManager, DirtyAddrT *pAddr)
Cancel an outstanding ping request callback.
DIRTYCODE_API void PingManagerCancelServerRequest (PingManagerRefT *pPingManager, uint32_t uSeqn)
Cancel an outstanding server ping request callback.
Detailed Description
Macro Definition Documentation
#define PINGMGR_PINGSTATUS_PINGING (-1)
this address is currently being pinged
#define PINGMGR_PINGSTATUS_TIMEOUT (-2)
ping of this address timed out
Typedef Documentation
typedef struct PingManagerRefT PingManagerRefT
ping manager ref
Function Documentation
DIRTYCODE_API typedef void() PingManagerCallbackT (DirtyAddrT * pAddr, uint32_t uPing, void * pUserData)
ping manager callback type
DIRTYCODE_API void PingManagerCancelRequest (PingManagerRefT * pPingManager, DirtyAddrT * pAddr)
Cancel an outstanding ping request callback.
Parameters
*pPingManager - ping manager ref
*pAddr - address to cancel request for
Version
07/12/04 (JLB)
References PingRecT::Addr, DirtyAddrCompare(), NULL, PingRecT::pCallback, PingRecT::pCallbackData, PingManagerRefT::PingCache, and PingManagerRefT::uNumRecords.
DIRTYCODE_API void PingManagerCancelServerRequest (PingManagerRefT * pPingManager, uint32_t uSeqn)
Cancel an outstanding server ping request callback.
Parameters
*pPingManager - ping manager ref
uSeqn - sequence for request to cancel, or zero to cancell all requests
Version
06/12/07 (JLB)
References NetPrintf, PINGMGR_MAXSERVERPINGS, PingManagerRefT::ServerPings, and ServerPingRecT::uSeqn.
DIRTYCODE_API PingManagerRefT* PingManagerCreate (uint32_t uMaxRecords)
Create PingManager module.
Parameters
uMaxRecords - size of LRU ping history cache.
Returns
PingManagerRefT * - created PingManager ref, or NULL if failure.
Note
Only one copy is instantiated. All other Create calls increment a reference counter and return a copy to the first version. This means that the first Create call sets the cache size.
Version
08/21/03 (JLB)
References DirtyMemAlloc(), DirtyMemFree(), DirtyMemGroupQuery(), PingManagerRefT::iMemGroup, NetPrintf, NetTick(), NULL, PINGMGR_MEMID, PINGMGR_TIMEOUT, PingManagerRefT::pMemGroupUserData, PingManagerRefT::pPingRef, PingManagerRefT::pQosRef, ProtoPingControl(), ProtoPingCreate(), QosApiCreate(), PingManagerRefT::uLastPingTick, PingManagerRefT::uMaxRecords, and PingManagerRefT::uTickCount.
DIRTYCODE_API void PingManagerDestroy (PingManagerRefT * pPingManager)
Shut down PingManager module.
Parameters
*pPingManager - ping manager ref
Note
As only one copy of the Ping Manager is instantiated, this call only destroys the Ping Manager if the internal reference count is zero.
Version
08/21/03 (JLB)
References DirtyMemFree(), PingManagerRefT::iMemGroup, NULL, PINGMGR_MEMID, PingManagerRefT::pMemGroupUserData, PingManagerRefT::pPingRef, PingManagerRefT::pQosRef, ProtoPingDestroy(), and QosApiDestroy().
DIRTYCODE_API int32_t PingManagerInvalidateAddress (PingManagerRefT * pPingManager, DirtyAddrT * pAddr)
Invalidate an address in the cache. This forces PingManager to issue a new ping the next time PingManagerPingAddress() is called with this address.
Parameters
*pPingManager - ping manager ref
*pAddr - address to invalidate
Returns
uint32_t - TRUE if address was found in cache, else FALSE
Version
09/04/03 (JLB)
References PingRecT::Addr, FALSE, PingManagerRefT::PingCache, and TRUE.
DIRTYCODE_API void PingManagerInvalidateCache (PingManagerRefT * pPingManager)
Invalidate all addresses in the cache.
WARNING:
    This function should be used very sparingly if at all, as indescriminate
    use invalidates the purpose of the address cache, and will result in a
    very network-unfriendly title.  To get a fresh ping for a single user use
    PingManagerInvalidateAddress() on that user's address, and then re-ping that
    user with PingManagerPingAddress().
Parameters
*pPingManager - ping manager ref
Version
03/19/04 (JLB)
References PingManagerRefT::PingCache, and PingManagerRefT::uNumRecords.
DIRTYCODE_API int32_t PingManagerPingAddress (PingManagerRefT * pPingManager, DirtyAddrT * pAddr, PingManagerCallbackT * pCallback, void * pCallbackData)
Ping an address.
Parameters
*pPingManager - ping manager ref
*pAddr - address to ping
*pCallback - callback to call on ping response
*pCallbackData - user data for callback
Returns
int32_t - ping value for given address, can also be PINGMGR_INVALID or PINGMGR_PINGING
Version
08/21/03 (JLB)
References PingRecT::Addr, ds_memcpy(), NetPrintf, PingRecT::pCallback, PingRecT::pCallbackData, PingManagerRefT::PingCache, DirtyAddrT::strMachineAddr, PingManagerRefT::uMaxRecords, PingManagerRefT::uNumRecords, PingRecT::uPing, PingManagerRefT::uTime, and PingRecT::uTouchedTime.
DIRTYCODE_API int32_t PingManagerPingServer (PingManagerRefT * pPingManager, uint32_t uServerAddress, PingManagerCallbackT * pCallback, void * pCallbackData)
Ping server. This is a direct pass-through to ProtoPingRequestServer.
Parameters
*pPingManager - ping manager ref
uServerAddress - server address
*pCallback - callback to call on ping response
*pCallbackData - user data for callback
Returns
int32_t - response code from ProtoPingRequestServer
Version
04/11/04 (JLB)
References PingManagerPingServer2().
DIRTYCODE_API int32_t PingManagerPingServer2 (PingManagerRefT * pPingManager, uint32_t uServerAddress, PingManagerCallbackT * pCallback, void * pCallbackData)
Ping server. This is a direct pass-through to ProtoPingRequestServer.
Parameters
*pPingManager - ping manager ref
uServerAddress - server address
*pCallback - callback to call on ping response
*pCallbackData - user data for callback
Returns
int32_t - response code from ProtoPingRequestServer
Version
04/11/04 (JLB)
References ds_snzprintf(), NetPrintf, NULL, PINGMGR_MAXSERVERPINGS, PingManagerRefT::pPingRef, PingManagerRefT::pQosRef, ProtoPingRequestServer(), ServerPingRecT::pServCb, ServerPingRecT::pServCbData, QOSAPI_REQUESTFL_LATENCY, QosApiServiceRequest(), PingManagerRefT::ServerPings, PingManagerRefT::strServerAddress, ServerPingRecT::uAddr, and ServerPingRecT::uSeqn.
Referenced by PingManagerPingServer().
DIRTYCODE_API void PingManagerUpdate (PingManagerRefT * pPingManager)
Give life to PingManager.
Parameters
*pPingManager - ping manager ref
Version
08/21/03 (JLB)
References PingRecT::Addr, ProtoPingResponseT::Addr, ProtoPingResponseT::bServer, ds_memcpy(), ProtoPingResponseT::iPing, NetPrintf, NetTick(), NULL, PingRecT::pCallback, PingRecT::pCallbackData, PingManagerRefT::PingCache, PINGMGR_CalcTimeDiff, PINGMGR_MAXPINGVAL, PINGMGR_MAXSERVERPINGS, PINGMGR_PINGFLAG_NEWPING, PINGMGR_PINGFLAG_PINGING, PINGMGR_PINGFLAG_TIMEOUT, PINGMGR_SetFlag, PINGMGR_STALEEXPIRETIME, PINGMGR_TICKSPERPING, PingManagerRefT::pPingRef, ProtoPingRequest(), ProtoPingResponse(), ServerPingRecT::pServCb, ServerPingRecT::pServCbData, PingManagerRefT::ServerPings, DirtyAddrT::strMachineAddr, TRUE, ProtoPingResponseT::uAddr, PingRecT::uCreatedTime, PingManagerRefT::uLastPingTick, PingManagerRefT::uNumRecords, PingRecT::uPing, ServerPingRecT::uSeqn, ProtoPingResponseT::uSeqn, PingManagerRefT::uTime, and PingRecT::uTouchedTime.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:42