window.originTranslator = {
    fallbackStrings: {
        "ebisu_client_installed": "Installed",
        "ebisu_client_pause_ito_installation": "Pause Install",
        "ebisu_client_resume_game": "Resume %1",
        "ebisu_client_unfavorite": "Remove from Favorites",
        "ebisu_client_gamestatus_paused_install": "Paused Installation",
        "ebisu_client_game_update_check_for_verify": "Repair Game",
        "ebisu_client_download_noun": "Download",
        "ebisu_client_game_is_preloaded": "This game is preloaded",
        "ebisu_client_can_now_preload": "Now available for preload",
        "ebisu_client_view_in_store": "View in Store",
        "ebisu_client_percent_notation": "%1%",
        "ebisu_client_platform_available_only_on_other": "Game unavailable on this system",
        "ebisu_client_more_details": "More Details",
        "ebisu_client_interval_hour_singular": "%1 hour",
        "ebisu_client_expires_in": "Expires in %1",
        "ebisu_client_pause_repair": "Pause Repair",
        "ebisu_client_show_more": "Show More",
        "ebisu_client_kbyte_notation": "%1 KB",
        "ebisu_client_game_properties_ellipsis": "Game Properties\u2026",
        "ebisu_client_cancel_cloud_sync": "Cancel Cloud Sync",
        "ebisu_client_gamestatus_pausing_preload": "Pausing Pre-load",
        "ebisu_client_platform_available_only_on_windows": "Game only available on Windows",
        "ebisu_client_game_update_check_for_updates": "Check for Update",
        "ebisu_client_edit": "Edit",
        "ebisu_client_osx": "Mac OS X",
        "ebisu_client_achievements_view_achievements_button": "View Achievements",
        "ebisu_client_just_released": "Just released",
        "ebisu_client_download": "Download",
        "ebisu_client_gamestatus_paused_download": "Paused Download",
        "ebisu_client_owned": "Owned",
        "ebisu_client_added_to_my_library": "Added to My Library",
        "ebisu_client_gamestatus_canceling_preload": "Canceling Pre-load",
        "ebisu_client_update": "Update",
        "ebisu_client_update_now": "Update Now",
        "ebisu_client_gamestatus_resuming_preload": "Resuming Pre-load",
        "ebisu_client_windows": "Windows",
        "ebisu_client_preloaded": "Preloaded",
        "ebisu_client_cloud_game_card_status": "Syncing Cloud Data",
        "ebisu_client_play": "Play",
        "ebisu_client_gamestatus_canceling_unpack": "Canceling Unpack",
        "ebisu_client_not_yet_released_text": "You successfully pre-ordered %1.",
        "ebisu_client_gamestatus_preparing_cloud_sync": "Preparing Cloud Sync",
        "ebisu_client_mac_only": "Mac Only",
        "ebisu_client_cancel_ito_installation": "Cancel Install",
        "ebisu_client_installing": "Installing",
        "ebisu_client_gamestatus_pausing_cloud_sync": "Pausing Cloud Sync",
        "ebisu_client_resume_ito_installation": "Resume Installation",
        "ebisu_client_gamestatus_pausing_install": "Pausing Installation",
        "ebisu_client_last_played": "Last Played",
        "ebisu_client_product_code": "Product Code",
        "ebisu_client_repairing": "Repairing",
        "ebisu_client_last_played_date": "Last Played Date",
        "ebisu_client_gamestatus_finalizing_update": "Finalizing Update",
        "ebisu_client_unpacking": "Unpacking",
        "ebisu_client_PC": "PC",
        "ebisu_client_gamestatus_paused_preload": "Paused Pre-load",
        "ebisu_client_gamestatus_preparing_repair": "Preparing Repair",
        "ebisu_client_preload_noun": "Preload",
        "ebisu_client_unhide": "Unhide",
        "ebisu_client_game_update_available": "Game update available",
        "ebisu_client_unfavorite_tooltip": "Remove from Favorites",
        "ebisu_client_friends_who_play": "Friends Who Play",
        "ebisu_client_time_played": "Time Played",
        "cc_bytes_of_bytes": "of",
        "ebisu_client_gamestatus_preparing_preload": "Preparing Pre-load",
        "ebisu_client_free_games_download_client_button": "Get It Now",
        "ebisu_client_gamestatus_pausing_repair": "Pausing Repair",
        "ebisu_client_view_special_offer_ellipses": "View Special Offer\u2026",
        "ebisu_client_gamestatus_resuming_repair": "Resuming Repair",
        "ebisu_client_gamestatus_paused_unpack": "Paused Unpack",
        "ebisu_client_uninstall": "Uninstall",
        "ebisu_client_buy_now": "Buy Now",
        "ebisu_client_gamestatus_preparing_download": "Preparing Download",
        "ebisu_client_available": "Available",
        "ebisu_client_gamestatus_resuming_cloud_sync": "Resuming Cloud Sync",
        "ebisu_client_updating": "Updating",
        "ebisu_client_preloading": "Preloading",
        "ebisu_client_cloud_sync": "cloud sync",
        "ebisu_client_currently_playing": "Currently Playing",
        "ebisu_client_ellipsis": "\u2026",
        "ebisu_client_hovercard_dlc_available": "New content is available",
        "ebisu_client_64_only": "Game requires 64 bit version of %1",
        "ebisu_client_customize_boxart_ellipses": "Customize Box Art\u2026",
        "ebisu_free_trial_not_started": "Trial not started",
        "ebisu_client_not_yet_released": "Not yet released",
        "ebisu_client_new_dlc_notification": "New content available for purchase.",
        "ebisu_client_gamestatus_preparing_unpack": "Preparing Unpack",
        "ebisu_client_launch_options": "Launch Options",
        "ebisu_client_gamestatus_canceling_install": "Canceling Installation",
        "ebisu_client_game_update_pause_update": "Pause Update",
        "ebisu_client_cancel_repair": "Cancel Repair",
        "ebisu_client_cancel_game": "Cancel %1",
        "ebisu_client_cant_download_offline": "Unable to download while offline",
        "ebisu_client_view_special_offer": "View Special Offer",
        "ebisu_client_achievements_album_viewall": "View All",
        "ebisu_client_unhide_game": "Unhide Game in Library",
        "ebisu_client_non_origin_games": "Non-Origin Games",
        "ebisu_client_gamestatus_finalizing_preload": "Finalizing Pre-load",
        "ebisu_client_cloud_text": "%1 syncs your saved games to the cloud, allowing you to access and continue playing them from any %1-enabled computer.",
        "ebisu_client_all_platforms": "All Platforms",
        "ebisu_client_cloud_restore_last_modified": "Last Modified %1",
        "ebisu_client_achievements": "Achievements",
        "ebisu_client_resume_repair": "Resume Repair",
        "ebisu_client_gamestatus_finalizing_repair": "Finalizing Repair",
        "ebisu_client_gamestatus_pausing_unpack": "Pausing Unpack",
        "ebisu_client_hour_played": "%1 HOUR PLAYED",
        "ebisu_client_gamestatus_resuming_download": "Resuming Download",
        "ebisu_client_favorites": "Favorites",
        "ebisu_client_interval_hour_plural": "%1 hours",
        "ebisu_client_gamestatus_resuming_update": "Resuming Update",
        "ebisu_client_show_less": "Show Less",
        "ebisu_client_install": "Install",
        "ebisu_client_downloading": "Downloading",
        "ebisu_client_interval_less_than_hour_uppercase": "LESS THAN AN HOUR PLAYED",
        "ebisu_client_gamestatus_paused_repair": "Paused Repair",
        "ebisu_client_hours_played": "%1 HOURS PLAYED",
        "ebisu_client_pc_only": "PC Only",
        "ebisu_client_search": "Search",
        "ebisu_client_notranslate_debug_info": "Debug Info",
        "ebisu_client_hide_game_in_library": "Hide Game in Library",
        "ebisu_client_settings_default_prefix": "(Default)",
        "ebisu_client_hovercard_game_trashed": "This game is in the Trash. Please select Restore to play.",
        "ebisu_client_gamestatus_finalizing_cloud_sync": "Finalizing Cloud Sync",
        "ebisu_client_try_before_you_buy": "Try before you buy.",
        "ebisu_client_unreleased": "Unreleased",
        "ebisu_client_non_origin_shortcut": "This is a non-Origin shortcut.",
        "ebisu_client_gamestatus_preparing_install": "Preparing Installation",
        "ebisu_client_all": "All Games",
        "ebisu_client_gamestatus_resuming_install": "Resuming Installation",
        "ebisu_client_restore": "Restore",
        "ebisu_client_free_trial_purchase_game": "Purchase Game",
        "ebisu_client_gamestatus_canceling_repair": "Canceling Repair",
        "ebisu_client_hide": "Hide",
        "ebisu_client_byte_notation": "%1 B",
        "ebisu_client_gamestatus_canceling_cloud_sync": "Canceling Cloud Sync",
        "ebisu_client_gamestatus_pausing_download": "Pausing Download",
        "ebisu_client_remove_from_library": "Remove from Library",
        "ebisu_client_notranslate_internal_debug_info": "Internal Debug Info",
        "ebisu_client_favorite_tooltip": "Mark as Favorite",
        "ebisu_client_gamestatus_preparing_update": "Preparing Update",
        "ebisu_client_gamestatus_canceling_update": "Canceling Update",
        "ebisu_client_gamestatus_resuming_unpack": "Resuming Unpack",
        "ebisu_client_gamestatus_canceling_download": "Canceling Download",
        "ebisu_client_game_update_cancel_update": "Cancel Update",
        "ebisu_client_game_update_resume_update": "Resume Update",
        "ebisu_client_gamestatus_paused_cloud_sync": "Paused Cloud Sync",
        "ebisu_client_gamestatus_finalizing_download": "Finalizing Download",
        "ebisu_client_add_to_favorites": "Add to Favorites",
        "ebisu_client_mbyte_notation": "%1 MB",
        "ebisu_client_platforms_supported": "Supported Platforms",
        "ebisu_client_preload_now": "Preload Now",
        "ebisu_client_pause_game": "Pause %1",
        "ebisu_client_view_game_details": "View Game Details",
        "ebisu_client_preload": "Preload",
        "ebisu_client_gamestatus_finalizing_unpack": "Finalizing Unpack",
        "ebisu_client_gamestatus_pausing_update": "Pausing Update",
        "ebisu_client_played_this_week": "Played This Week",
        "ebisu_client_trial_expired": "Free Trial Expired",
        "ebisu_client_colon_placement": "%0: %1",
        "ebisu_client_trial_expires_in": "Trial ends in %1",
        "ebisu_client_installed_games": "Installed Games",
        "ebisu_client_mac": "Mac",
        "ebisu_client_gamestatus_paused_update": "Paused Update",
        "ebisu_client_hidden_games": "Hidden Games",
        "ebisu_client_gamestatus_finalizing_install": "Finalizing Installation",
        "ebisu_client_gbyte_notation": "%1 GB",
        "ebisu_client_platform_available_only_on_osx": "Game only available on OSX",
        "ebisu_client_expired": "Expired",
        "ebisu_client_must_be_online_to_change_setting": "You'll need to be online to change this setting.",
        "ebisu_client_verifying_game_files" : "Verifying game files",
        "ebisu_client_queued" : "Queued",
        "ebisu_client_add_to_downloads" : "Add to downloads",
        "ebisu_client_playable_marker" : "Playable",
        "ebisu_client_play_game_while_downloading_launch_at_X" : "Play while downloading: You can start playing at %1%.",
        "ebisu_client_play_game_while_downloading_play_now" : "Play while downloading: You can start playing now.",
        "ebisu_client_play_game_while_downloading" : "Play this game while it downloads.",
        "ebisu_client_download_now" : "Download Now",
        "ebisu_client_preview_content_description_downloadable" : "<b>This content is preloadable.</b> You may download this content before purchasing.",
        "ebisu_client_preview_content_description_installed" : "<b>Ready to Unlock.</b> This content has been preloaded.",
        "ebisu_client_game_details_release_date" : "Release Date",
        "ebisu_client_expansions_uppercase" : "EXPANSIONS",
        "ebisu_client_game_details_addons_and_bonuses_uppercase" : "ADD-ONS & BONUSES",
		"Subs_Library_Filter_Vault" : "Vault Games",
		"ebisu_client_purchased_games" : "Purchased Games",
		"Subs_Upgrade_Action" : "Upgrade Now",
		"Subs_Library_HoverCard_Renew" : "Renew Membership",
		"Subs_Library_HoverCard_Expires_Countdown" : "Expires with Thor in %1",
		"Subs_Membership_Expired" : "Your membership has expired",
		"Subs_Library_HoverCard_Buy" : "Buy in Store",
		"Subs_Library_HoverCard_VaultExpire_Countdown" : "This Vault title retires in %1.",
		"Subs_Library_HoverCard_VaultExpire_Notification" : "Retired from the Vault",
		"Subs_Library_HoverCard_Offline_Expired_Notification" : "Offline play expired. <button class=\"go-online\">Go online</button> to verify your Origin Access subscription to continue",
		"Subs_Library_HoverCard_Offline_Expires_Countdown" : "Online connection required in %1 days to verify Thor subscription",
		"Subs_Library_HoverCard_Upgrade_Notification" : "Thor subscriber benefit- Digital Deluxe version upgrade available",
		"ebisu_client_new_title" : "NEW",
		"ebisu_client_sims3_expansions_moved_title" : "YOUR SIMS 3 EXPANSIONS HAVE MOVED",
		"ebisu_client_sims3_expansions_moved_text" : "You can view your expansions by clicking the “I” button when hovering on Sims 3. <br><br>All of your installed expansions are still available by simply launching the game from here.",
		"ebisu_client_subs_upgrade_edition" : "Game edition upgrade available through Origin Access",
		"ebisu_client_subs_upgrade_expansions" : "Additional expansions ready to download through Origin Access",
		"ebisu_client_subs_upgrade_edition_expansions" : "New game edition and expansions are available with Origin Access",
        "ebisu_subs_windows_only_notification": "Available for Origin Access members on Windows only.",
        "ebisu_subs_windows_only_purchasable_notification": "Available for Origin Access members on Windows only. You may still purchase this separately to play on Mac.",
        "ebisu_subs_edition_windows_only_notification": "Origin Access edition only available on Windows."

    },

    translate: function(string_id) {
        var fallbackStrings = originTranslator.fallbackStrings;

        if (string_id in fallbackStrings) {
            return fallbackStrings[string_id];
        }

        return string_id;
    }
}

window.tr = function(string_id) {
    return originTranslator.translate(string_id)
}
