DirtySock: userapi.c File Reference
userapi.c File Reference
Expose first party players' information.
#include <string.h>
#include "DirtySDK/misc/userapi.h"
#include "userapipriv.h"
#include "DirtySDK/dirtysock/dirtyerr.h"
#include "DirtySDK/dirtysock/dirtymem.h"
Functions
void _UserApiTriggerCallback (UserApiRefT *pRef, uint32_t uUserIndex, UserApiEventErrorE eError, UserApiEventTypeE eType, UserApiUserDataT *pUserData)
Called by update function in the platform specific UserApi modules when a profile or error is ready.
UserApiRefT * UserApiCreate (void)
Starts UserApi.
int32_t UserApiDestroy (UserApiRefT *pRef)
Starts shutting down module. Module will not accept new requests, and will abort ongoing ones. Also, registered UserApiCallbackT callback will not be called even if there is data available for processing.
int32_t UserApiStatus (UserApiRefT *pRef, int32_t iSelect, void *pBuf, int32_t iBufSize)
Get status information.
int32_t UserApiControl (UserApiRefT *pRef, int32_t iControl, int32_t iValue, int32_t iValue2, void *pValue)
Control behavior of module.
int32_t UserApiRequestProfilesAsync (UserApiRefT *pRef, uint32_t uUserIndex, DirtyUserT *pLookupUsers, int32_t iLookupUsersLength, UserApiCallbackT *pCallback, void *pUserData)
Starts the process to retrieve user information of players. pLookupUsers is a pointer to the first DirtyUserT, and iLookupUsersLength is the number of DirtyUserTs.
int32_t UserApiRequestProfileAsync (UserApiRefT *pRef, uint32_t uUserIndex, DirtyUserT *pLookupUser, UserApiCallbackT *pCallback, uint32_t uUserDataMask, void *pUserData)
Starts the process to retrieve profile information of players. pLookupUser is a pointer to DirtyUserT.
int32_t UserApiRequestPresenceAsync (UserApiRefT *pRef, uint32_t uUserIndex, DirtyUserT *pLookupUser, UserApiCallbackT *pCallback, uint32_t uUserDataMask, void *pUserData)
Starts the process to retrieve profile information of players. pLookupUser is a pointer to DirtyUserT.
int32_t UserApiRequestRichPresenceAsync (UserApiRefT *pRef, uint32_t uUserIndex, DirtyUserT *pLookupUser, UserApiCallbackT *pCallback, uint32_t uUserDataMask, void *pUserData)
Starts the process to retrieve rich presence information of players.
int32_t UserApiPostRecentlyMetAsync (UserApiRefT *pRef, uint32_t uUserIndex, DirtyUserT *pPlayerMet, UserApiPostCallbackT *pCallback, void *pUserData)
Starts the process to post that a certain player was recently encountered.
int32_t UserApiPostRichPresenceAsync (UserApiRefT *pRef, uint32_t uUserIndex, UserApiRichPresenceT *pData, UserApiPostCallbackT *pCallback, void *pUserData)
Starts the process to post that a certain player was recently encountered.
int32_t UserApiRegisterUpdateEvent (UserApiRefT *pRef, uint32_t uUserIndex, UserApiNotifyTypeE eType, UserApiUpdateCallbackT *pNotifyCb, void *pUserData)
Register for notifications from first part.
int32_t UserApiCancel (UserApiRefT *pRef, uint32_t uUserIndex)
Cancel all queries to the 1st party.
void UserApiUpdate (UserApiRefT *pRef)
Update the internal state of the module, and call registered UserApiCallbackT callback if there are GamerCard/Profile responses available. This function should be called periodically.
Detailed Description
Expose first party players' information.
Attention
Copyright (c) Electronic Arts 2001-2013
Version
05/10/2013 (mcorcoran) First Version
Function Documentation
void _UserApiTriggerCallback (UserApiRefT * pRef, uint32_t uUserIndex, UserApiEventErrorE eError, UserApiEventTypeE eType, UserApiUserDataT * pUserData)
Called by update function in the platform specific UserApi modules when a profile or error is ready.
Parameters
*pRef - pointer to UserApiT module reference.
*uUserIndex - The index of the user associated with this profile request.
*eError - A UserApiEventErrorE indicating success for the failure reason.
eType - type of callback
*pUserData - pointer to a populated UserApiUserDataT
Returns
void
Version
05/10/2013 (mcorcoran) - First version
12/10/2013 (amakoukji) - Second version for UserApi second pass
References UserApiRefT::crit, ds_memcpy(), UserApiEventDataT::eError, UserApiEventDataT::eEventType, UserApiEventDetailsT::EndOfList, UserApiEventDataT::EventDetails, UserApiUserContextT::iTotalErrors, UserApiEndOfListT::iTotalErrors, UserApiUserContextT::iTotalReceived, UserApiEndOfListT::iTotalReceived, UserApiUserContextT::iTotalRequested, UserApiEndOfListT::iTotalRequested, NetCritEnter(), NetCritLeave(), pRef, UserApiRefT::pUserCallback, UserApiRefT::pUserData, USERAPI_ERROR_REQUEST_FAILED, USERAPI_EVENT_END_OF_LIST, UserApiRefT::UserContextList, UserApiEventDetailsT::UserData, UserApiRefT::UserPresenceList, UserApiRefT::UserRichPresenceList, and UserApiEventDataT::uUserIndex.
Referenced by _UserApiProcessProfileResponse(), and UserApiUpdate().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:14