DirtySock: Base64
Base64
Util
Macros
#define Base64EncodedSize(x) ((((x)+2)/3)*4)
#define Base64DecodedSize(x) (((x)/4)*3)
Functions
DIRTYCODE_API void Base64Encode (int32_t iInputLen, const char *pInput, char *pOutput)
Base-64 encode a string.
DIRTYCODE_API int32_t Base64Encode2 (const char *pInput, int32_t iInputLen, char *pOutput, int32_t iOutputLen)
Base-64 encode a string.
DIRTYCODE_API int32_t Base64Decode (int32_t iInputLen, const char *pInput, char *pOutput)
Decode a Base-64 encoded string.
DIRTYCODE_API int32_t Base64Decode2 (int32_t iInputLen, const char *pInput, char *pOutput)
Decode a Base-64 encoded string.
DIRTYCODE_API int32_t Base64Decode3 (const char *pInput, int32_t iInputLen, char *pOutput, int32_t iOutputLen)
Decode a Base-64 encoded string.
Detailed Description
Macro Definition Documentation
#define Base64DecodedSize (x) (((x)/4)*3)
The maximum number of bytes it takes to hold the decoded version of a Base-64 encoded string that is 'x' bytes long.
In this version of Base-64, 'x' is always a multiple of 4 and the result is always a multiple of 3 (i.e. there may be up to 2 padding bytes at the end of the decoded value). It is assumed that the exact length of the string (minus any padding) is either encoded in the string or is external to the string.
#define Base64EncodedSize (x) ((((x)+2)/3)*4)
The number of bytes it takes to Base-64 encode the given number of bytes. The result includes any required padding but not a '\0' terminator.
Referenced by Base64Encode2().
Function Documentation
DIRTYCODE_API int32_t Base64Decode (int32_t iInputLen, const char * pInput, char * pOutput)
Decode a Base-64 encoded string.
Deprecated:
The calling convention for Base64Decode will be replaced with that of Base64Decode3 in a future release.
Parameters
iInputLen - the length of the encoded input
*pInput - the Base-64 encoded string
*pOutput - [out] the decoded string, or NULL to calculate output size
Returns
int32_t - true on success, false on error.
Note
The only reasons for failure are if the input base64 sequence does not amount to a number of characters comprising an even multiple of four characters, or if the input contains a character not in the Base64 character set and not a whitespace character. This behavior is mentioned in the RFC:
"In base64 data, characters other than those in Table 1,
 line breaks, and other white space probably indicate a
 transmission error, about which a warning message or even
 a message rejection might be appropriate under some
 circumstances."
It is assumed that pOutput is large enough to hold Base64DecodedSize(iInputLen) bytes. If pOutput is NULL, the function will return the number of characters required to buffer the output or zero on error.
The following chart should help explain the various bit shifts that are in the code. On the top are the 6-bit bytes in the input and and on the bottom are the 8-bit bytes of the output :-
      |     0     |     1     |       2   |     3     |   in
      +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
      |               |               |               |
      +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
      |       0       |       1       |       2       |   out
As the above shows the out0 consists of all of in0 and the top 2 bits of in1, out1 is the bottom 4 bits of in1 and the top 4 bits of in2, ... etc.
Version
12/11/2002 (sbevan) First Version
01/29/2009 (jbrookes) Enhanced to skip whitespace, added decoded length functionality
References Base64Decode2(), FALSE, and TRUE.
DIRTYCODE_API int32_t Base64Decode2 (int32_t iInputLen, const char * pInput, char * pOutput)
Decode a Base-64 encoded string.
Deprecated:
The calling convention for Base64Decode2 will be replaced with that of Base64Decode3 in a future release.
Parameters
iInputLen - the length of the encoded input
*pInput - the Base-64 encoded string
*pOutput - [out[ the decoded string, or NULL to calculate output size
Returns
int32_t - decoded size on success, zero on error.
Note
The only reasons for failure are if the input base64 sequence does not amount to a number of characters comprising an even multiple of four characters, or if the input contains a character not in the Base64 character set and not a whitespace character. This behavior is mentioned in the RFC:
"In base64 data, characters other than those in Table 1,
 line breaks, and other white space probably indicate a
 transmission error, about which a warning message or even
 a message rejection might be appropriate under some
 circumstances."
It is assumed that pOutput is large enough to hold Base64DecodedSize(iInputLen) bytes. If pOutput is NULL, the function will return the number of characters required to buffer the output or zero on error.
The following chart should help explain the various bit shifts that are in the code. On the top are the 6-bit bytes in the input and and on the bottom are the 8-bit bytes of the output :-
      |     0     |     1     |       2   |     3     |   in
      +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
      |               |               |               |
      +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
      |       0       |       1       |       2       |   out
As the above shows the out0 consists of all of in0 and the top 2 bits of in1, out1 is the bottom 4 bits of in1 and the top 4 bits of in2, ... etc.
Version
12/11/2002 (sbevan) First Version
01/29/2009 (jbrookes) Enhanced to skip whitespace, added decoded length functionality
References Base64Decode3().
Referenced by Base64Decode().
DIRTYCODE_API int32_t Base64Decode3 (const char * pInput, int32_t iInputLen, char * pOutput, int32_t iOutputLen)
Decode a Base-64 encoded string.
Parameters
*pInput - the Base-64 encoded string
iInputLen - the length of the encoded input
*pOutput - [out] the decoded string, or NULL to calculate output size
iOutputLen - size of output buffer
Returns
int32_t - decoded size on success, zero on error.
Note
The only reasons for failure are if the input base64 sequence does not amount to a number of characters comprising an even multiple of four characters, or if the input contains a character not in the Base64 character set and not a whitespace character. This behavior is mentioned in the RFC:
"In base64 data, characters other than those in Table 1,
 line breaks, and other white space probably indicate a
 transmission error, about which a warning message or even
 a message rejection might be appropriate under some
 circumstances."
If pOutput is NULL, the function will return the number of characters required to buffer the output, or zero on error.
The following chart should help explain the various bit shifts that are in the code. On the top are the 6-bit bytes in the input and and on the bottom are the 8-bit bytes of the output :-
      |     0     |     1     |       2   |     3     |   in
      +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
      |               |               |               |
      +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
      |       0       |       1       |       2       |   out
As the above shows the out0 consists of all of in0 and the top 2 bits of in1, out1 is the bottom 4 bits of in1 and the top 4 bits of in2, ... etc.
Version
12/11/2002 (sbevan) First Version
01/29/2009 (jbrookes) Enhanced to skip whitespace, added decoded length functionality
Referenced by Base64Decode2().
DIRTYCODE_API void Base64Encode (int32_t iInputLen, const char * pInput, char * pOutput)
Base-64 encode a string.
Deprecated:
The calling convention for Base64Encode will be replaced with that of Base64Encode2 in a future release.
Parameters
iInputLen - the length of the input
*pInput - the input
*pOutput - the output
Note
pOutput is NUL terminated.
It is assumed that pOutput is large enough to hold Base64EncodedSize(iInputLen)+1 bytes.
The following chart should help explain the various bit shifts that are in the code. On the top are the 8-bit bytes of the input and on the bottom are the 6-bit bytes of the output :-
      |       0       |       1       |       2       |  in
      +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
      |               |               |               |
      +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
      |     0     |     1     |       2   |     3     |  out
As the above shows the out0 is the top 6 bits of in0, out1 is the bottom two bits of in0 along with the top 4 bits of in1, ... etc.
To speed things up the encoder tries to work on chunks of 3 input bytes at a time since that produces 4 output bytes without having to maintain any inter-byte processing state.
For any input that is not a multiple of 3 then 1 or 2 padding bytes are are added as appropriate as described in the RFC.
Version
1.0 12/11/2002 (SJB) First Version
References Base64Encode2().
DIRTYCODE_API int32_t Base64Encode2 (const char * pInput, int32_t iInputLen, char * pOutput, int32_t iOutputLen)
Base-64 encode a string.
Parameters
iInputLen - the length of the input
*pInput - the input
*pOutput - the output
iOutputLen - the output buffer size
Returns
int32_t - encoded length, or -1 on error
Note
pOutput is NUL terminated.
It is assumed that pOutput is large enough to hold Base64EncodedSize(iInputLen)+1 bytes.
The following chart should help explain the various bit shifts that are in the code. On the top are the 8-bit bytes of the input and on the bottom are the 6-bit bytes of the output :-
      |       0       |       1       |       2       |  in
      +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
      |               |               |               |
      +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
      |     0     |     1     |       2   |     3     |  out
As the above shows the out0 is the top 6 bits of in0, out1 is the bottom two bits of in0 along with the top 4 bits of in1, ... etc.
To speed things up the encoder tries to work on chunks of 3 input bytes at a time since that produces 4 output bytes without having to maintain any inter-byte processing state.
For any input that is not a multiple of 3 then 1 or 2 padding bytes are are added as appropriate as described in the RFC.
Version
12/11/2002 (sbevan) First Version
References Base64EncodedSize.
Referenced by Base64Encode().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:34:38