/**
 * @file store/storesearch.js
 */
(function () {
    'use strict';

    var NORMAL_FILTER = false;

    function StoreFacetFactory(ResultFilterFactory) {

        var sortBy = ResultFilterFactory.getInstance({
                'rank asc': {filterType: NORMAL_FILTER, value: false},
                'rank desc': {filterType: NORMAL_FILTER, value: false}, //default sort
                'dynamicPrice asc': {filterType: NORMAL_FILTER, value: false},
                'dynamicPrice desc': {filterType: NORMAL_FILTER, value: false},
                'releaseDate asc': {filterType: NORMAL_FILTER, value: false},
                'releaseDate desc': {filterType: NORMAL_FILTER, value: false},
                'title asc': {filterType: NORMAL_FILTER, value: false},
                'title desc': {filterType: NORMAL_FILTER, value: false}
            }),
            facets = {
                genre: ResultFilterFactory.getInstance({
                    shooter: {filterType: NORMAL_FILTER, value: false},
                    action: {filterType: NORMAL_FILTER, value: false},
                    adventure: {filterType: NORMAL_FILTER, value: false},
                    arcade: {filterType: NORMAL_FILTER, value: false},
                    casual: {filterType: NORMAL_FILTER, value: false},
                    family: {filterType: NORMAL_FILTER, value: false},
                    fighting: {filterType: NORMAL_FILTER, value: false},
                    mmo: {filterType: NORMAL_FILTER, value: false},
                    online: {filterType: NORMAL_FILTER, value: false},
                    puzzle: {filterType: NORMAL_FILTER, value: false},
                    racing: {filterType: NORMAL_FILTER, value: false},
                    'role-playing': {filterType: NORMAL_FILTER, value: false},
                    simulation: {filterType: NORMAL_FILTER, value: false},
                    sports: {filterType: NORMAL_FILTER, value: false},
                    strategy: {filterType: NORMAL_FILTER, value: false}
                }),

                price: ResultFilterFactory.getInstance({
                    'on-sale': {filterType: NORMAL_FILTER, value: false},
                    pricebargains: {filterType: NORMAL_FILTER, value: false},
                    pricetier1: {filterType: NORMAL_FILTER, value: false},
                    pricetier2: {filterType: NORMAL_FILTER, value: false},
                    pricetier3: {filterType: NORMAL_FILTER, value: false},
                    pricetier4: {filterType: NORMAL_FILTER, value: false},
                    pricetier5: {filterType: NORMAL_FILTER, value: false},
                    pricetier6: {filterType: NORMAL_FILTER, value: false},
                    pricetier7: {filterType: NORMAL_FILTER, value: false}
                }),

                franchise: ResultFilterFactory.getInstance({
                    'fifa': {filterType: NORMAL_FILTER, value: false},
                    'moh': {filterType: NORMAL_FILTER, value: false},
                    'mirrorsedge': {filterType: NORMAL_FILTER, value: false},
                    'masseffect': {filterType: NORMAL_FILTER, value: false},
                    'nfs': {filterType: NORMAL_FILTER, value: false},
                    'sims': {filterType: NORMAL_FILTER, value: false},
                    'battlefield': {filterType: NORMAL_FILTER, value: false},
                    'commandandconquer': {filterType: NORMAL_FILTER, value: false},
                    'deadspace': {filterType: NORMAL_FILTER, value: false},
                    'dragonage': {filterType: NORMAL_FILTER, value: false},
                    'none': {filterType: NORMAL_FILTER, value: false},
                    'battleforge': {filterType: NORMAL_FILTER, value: false},
                    'simcity': {filterType: NORMAL_FILTER, value: false},
                    'crysis': {filterType: NORMAL_FILTER, value: false},
                    'spore': {filterType: NORMAL_FILTER, value: false},
                    'madden': {filterType: NORMAL_FILTER, value: false},
                    'monopoly': {filterType: NORMAL_FILTER, value: false},
                    'nflheadcoach': {filterType: NORMAL_FILTER, value: false},
                    'nhl': {filterType: NORMAL_FILTER, value: false},
                    'armyoftwo': {filterType: NORMAL_FILTER, value: false},
                    'bejeweled': {filterType: NORMAL_FILTER, value: false},
                    'burnout': {filterType: NORMAL_FILTER, value: false},
                    'fightnight': {filterType: NORMAL_FILTER, value: false},
                    'skate': {filterType: NORMAL_FILTER, value: false},
                    'ssx': {filterType: NORMAL_FILTER, value: false},
                    'saboteur': {filterType: NORMAL_FILTER, value: false},
                    'tiger': {filterType: NORMAL_FILTER, value: false},
                    'war': {filterType: NORMAL_FILTER, value: false},
                    'railsimulator': {filterType: NORMAL_FILTER, value: false},
                    'batman': {filterType: NORMAL_FILTER, value: false},
                    'harrypotter': {filterType: NORMAL_FILTER, value: false},
                    'lotr': {filterType: NORMAL_FILTER, value: false},
                    'mercenaries': {filterType: NORMAL_FILTER, value: false},
                    'ultima': {filterType: NORMAL_FILTER, value: false},
                    'fifastreet': {filterType: NORMAL_FILTER, value: false},
                    'nba': {filterType: NORMAL_FILTER, value: false},
                    'hellgate': {filterType: NORMAL_FILTER, value: false},
                    'littlestpetshop': {filterType: NORMAL_FILTER, value: false},
                    'dead space': {filterType: NORMAL_FILTER, value: false},
                    'cricket': {filterType: NORMAL_FILTER, value: false},
                    'Ea Sports Active': {filterType: NORMAL_FILTER, value: false},
                    'titanfall': {filterType: NORMAL_FILTER, value: false},
                    'escape': {filterType: NORMAL_FILTER, value: false},
                    'star-wars': {filterType: NORMAL_FILTER, value: false},
                    'wingcommander': {filterType: NORMAL_FILTER, value: false},
                    'peggle': {filterType: NORMAL_FILTER, value: false},
                    'syndicate': {filterType: NORMAL_FILTER, value: false},
                    'pogo': {filterType: NORMAL_FILTER, value: false},
                    'amazingadventures': {filterType: NORMAL_FILTER, value: false},
                    'daoc': {filterType: NORMAL_FILTER, value: false},
                    'feedingfrenzy': {filterType: NORMAL_FILTER, value: false},
                    'insaniquarium': {filterType: NORMAL_FILTER, value: false},
                    'secretworld': {filterType: NORMAL_FILTER, value: false},
                    'pvz': {filterType: NORMAL_FILTER, value: false},
                    'koa': {filterType: NORMAL_FILTER, value: false},
                    'mysterypi': {filterType: NORMAL_FILTER, value: false},
                    'vacationquest': {filterType: NORMAL_FILTER, value: false},
                    'defiance': {filterType: NORMAL_FILTER, value: false},
                    'far-cry': {filterType: NORMAL_FILTER, value: false},
                    'alchemy': {filterType: NORMAL_FILTER, value: false},
                    'alice': {filterType: NORMAL_FILTER, value: false},
                    'landsoflore': {filterType: NORMAL_FILTER, value: false},
                    'starflight': {filterType: NORMAL_FILTER, value: false},
                    'themehospital': {filterType: NORMAL_FILTER, value: false},
                    'bigmoney': {filterType: NORMAL_FILTER, value: false},
                    'bookworm': {filterType: NORMAL_FILTER, value: false},
                    'dungeonkeeper': {filterType: NORMAL_FILTER, value: false},
                    'dynomite': {filterType: NORMAL_FILTER, value: false},
                    'magiccarpet': {filterType: NORMAL_FILTER, value: false},
                    'populous': {filterType: NORMAL_FILTER, value: false},
                    'sidmeiers': {filterType: NORMAL_FILTER, value: false},
                    'thegameeoflife': {filterType: NORMAL_FILTER, value: false},
                    'warp': {filterType: NORMAL_FILTER, value: false},
                    'zumasrevenge': {filterType: NORMAL_FILTER, value: false},
                    "assassin's-creed": {filterType: NORMAL_FILTER, value: false},
                    'tombraider': {filterType: NORMAL_FILTER, value: false},
                    'witcher': {filterType: NORMAL_FILTER, value: false},
                    'zubo': {filterType: NORMAL_FILTER, value: false},
                    'eve': {filterType: NORMAL_FILTER, value: false},
                    'thebookofunwrittentales': {filterType: NORMAL_FILTER, value: false},
                    'unravel': {filterType: NORMAL_FILTER, value: false}
                }),

                gameType: ResultFilterFactory.getInstance({
                    'basegame': {filterType: NORMAL_FILTER, value: false},
                    'basegame,bundles': {filterType: NORMAL_FILTER, value: false},
                    'beta': {filterType: NORMAL_FILTER, value: false},
                    'bundle': {filterType: NORMAL_FILTER, value: false},
                    'currency': {filterType: NORMAL_FILTER, value: false},
                    'demos': {filterType: NORMAL_FILTER, value: false},
                    'dlc': {filterType: NORMAL_FILTER, value: false},
                    'expansion': {filterType: NORMAL_FILTER, value: false},
                    'extra-content': {filterType: NORMAL_FILTER, value: false},
                    'freegames': {filterType: NORMAL_FILTER, value: false},
                    'onlinesubscription': {filterType: NORMAL_FILTER, value: false},
                    'subscription': {filterType: NORMAL_FILTER, value: false},
                    'trial': {filterType: NORMAL_FILTER, value: false},
                    'vault': {filterType: NORMAL_FILTER, value: false}

                }),

                platform: ResultFilterFactory.getInstance({
                    'mac-download': {filterType: NORMAL_FILTER, value: false},
                    'macpc-download': {filterType: NORMAL_FILTER, value: false},
                    'other': {filterType: NORMAL_FILTER, value: false},
                    'pc-download': {filterType: NORMAL_FILTER, value: false},
                    'browser': {filterType: NORMAL_FILTER, value: false}
                }),

                availability: ResultFilterFactory.getInstance({
                    'pre-order': {filterType: NORMAL_FILTER, value: false},
                    'coming-soon': {filterType: NORMAL_FILTER, value: false},
                    'new-releases': {filterType: NORMAL_FILTER, value: false},
                    'out-now': {filterType: NORMAL_FILTER, value: false},
                    'latest': {filterType: NORMAL_FILTER, value: false},
                    'past-year': {filterType: NORMAL_FILTER, value: false},
                    'catalog': {filterType: NORMAL_FILTER, value: false},
                    'legacy': {filterType: NORMAL_FILTER, value: false}
                }),

                players: ResultFilterFactory.getInstance({
                    '16ormore': {filterType: NORMAL_FILTER, value: false},
                    'multiplayer': {filterType: NORMAL_FILTER, value: false},
                    'multiplayer,singleplayer': {filterType: NORMAL_FILTER, value: false},
                    'singleplayer': {filterType: NORMAL_FILTER, value: false},
                    'upto16': {filterType: NORMAL_FILTER, value: false},
                    'upto2': {filterType: NORMAL_FILTER, value: false},
                }),

                rating: ResultFilterFactory.getInstance({
                    pegi3: {filterType: NORMAL_FILTER, value: false},
                    pegi7: {filterType: NORMAL_FILTER, value: false},
                    pegi12: {filterType: NORMAL_FILTER, value: false},
                    pegi16: {filterType: NORMAL_FILTER, value: false},
                    pegi16Provisional: {filterType: NORMAL_FILTER, value: false},
                    pegi18: {filterType: NORMAL_FILTER, value: false},
                    pegi18Provisional: {filterType: NORMAL_FILTER, value: false},
                    mature: {filterType: NORMAL_FILTER, value: false},
                    teen: {filterType: NORMAL_FILTER, value: false},
                    everyone: {filterType: NORMAL_FILTER, value: false},
                    'everyone-10+': {filterType: NORMAL_FILTER, value: false},
                    'rating-pending': {filterType: NORMAL_FILTER, value: false}
                }),

                developer: ResultFilterFactory.getInstance({
                    '38-studios': {filterType: NORMAL_FILTER, value: false},
                    '4a-games': {filterType: NORMAL_FILTER, value: false},
                    '5th-cell': {filterType: NORMAL_FILTER, value: false},
                    'big-huge-games38-studios': {filterType: NORMAL_FILTER, value: false},
                    'bioware': {filterType: NORMAL_FILTER, value: false},
                    'bright-future': {filterType: NORMAL_FILTER, value: false},
                    'bright-light': {filterType: NORMAL_FILTER, value: false},
                    'bullfrog-productions': {filterType: NORMAL_FILTER, value: false},
                    'cateia-games': {filterType: NORMAL_FILTER, value: false},
                    'ccp-games': {filterType: NORMAL_FILTER, value: false},
                    'cd-projekt-red': {filterType: NORMAL_FILTER, value: false},
                    'codemasters-birmingham': {filterType: NORMAL_FILTER, value: false},
                    'codemasters-southam': {filterType: NORMAL_FILTER, value: false},
                    'coldwood-interactive': {filterType: NORMAL_FILTER, value: false},
                    'core-design': {filterType: NORMAL_FILTER, value: false},
                    'criterion-games': {filterType: NORMAL_FILTER, value: false},
                    'crystal-dynamics': {filterType: NORMAL_FILTER, value: false},
                    'crytek': {filterType: NORMAL_FILTER, value: false},
                    'cyanide': {filterType: NORMAL_FILTER, value: false},
                    'danger-close-and-dice': {filterType: NORMAL_FILTER, value: false},
                    'danger-close-games': {filterType: NORMAL_FILTER, value: false},
                    'danger-close-games-and-DICE': {filterType: NORMAL_FILTER, value: false},
                    'dice': {filterType: NORMAL_FILTER, value: false},
                    'dontnod-entertainment': {filterType: NORMAL_FILTER, value: false},
                    'ea-black-box': {filterType: NORMAL_FILTER, value: false},
                    'ea-canada': {filterType: NORMAL_FILTER, value: false},
                    'ea-hasbro': {filterType: NORMAL_FILTER, value: false},
                    'ea-phenomic': {filterType: NORMAL_FILTER, value: false},
                    'ea-salt-lake': {filterType: NORMAL_FILTER, value: false},
                    'ea-tiburon': {filterType: NORMAL_FILTER, value: false},
                    'eala': {filterType: NORMAL_FILTER, value: false},
                    'ensemble-studios': {filterType: NORMAL_FILTER, value: false},
                    'eugen-systems': {filterType: NORMAL_FILTER, value: false},
                    'firaxis-games': {filterType: NORMAL_FILTER, value: false},
                    'firefly-studios': {filterType: NORMAL_FILTER, value: false},
                    'frontier-developments': {filterType: NORMAL_FILTER, value: false},
                    'funcom': {filterType: NORMAL_FILTER, value: false},
                    'ghost-games': {filterType: NORMAL_FILTER, value: false},
                    'giants-software': {filterType: NORMAL_FILTER, value: false},
                    'haeimont-games': {filterType: NORMAL_FILTER, value: false},
                    'inxile-entertainment': {filterType: NORMAL_FILTER, value: false},
                    'king-art': {filterType: NORMAL_FILTER, value: false},
                    'kuju-entertainment': {filterType: NORMAL_FILTER, value: false},
                    'maxis': {filterType: NORMAL_FILTER, value: false},
                    'monolith-productions': {filterType: NORMAL_FILTER, value: false},
                    'monte-cristo': {filterType: NORMAL_FILTER, value: false},
                    'mythic-entertainment': {filterType: NORMAL_FILTER, value: false},
                    'n-fusion-interactive': {filterType: NORMAL_FILTER, value: false},
                    'ninja-theory': {filterType: NORMAL_FILTER, value: false},
                    'nixxes-software': {filterType: NORMAL_FILTER, value: false},
                    'origin-systems': {filterType: NORMAL_FILTER, value: false},
                    'pandemic-studios': {filterType: NORMAL_FILTER, value: false},
                    'paradox-development-studio': {filterType: NORMAL_FILTER, value: false},
                    'people-can-fly,epic-games': {filterType: NORMAL_FILTER, value: false},
                    'piranha-bytes': {filterType: NORMAL_FILTER, value: false},
                    'platinumgames-inc.': {filterType: NORMAL_FILTER, value: false},
                    'popcap-games': {filterType: NORMAL_FILTER, value: false},
                    'realmforge-studios': {filterType: NORMAL_FILTER, value: false},
                    'rebellion-oxford': {filterType: NORMAL_FILTER, value: false},
                    'relic-entertainment': {filterType: NORMAL_FILTER, value: false},
                    'remedy-entertainment': {filterType: NORMAL_FILTER, value: false},
                    'respawn-entertainment': {filterType: NORMAL_FILTER, value: false},
                    'rocksteady-studios': {filterType: NORMAL_FILTER, value: false},
                    'slightly-mad-studios': {filterType: NORMAL_FILTER, value: false},
                    'snowblind-studios': {filterType: NORMAL_FILTER, value: false},
                    'spicy-horse': {filterType: NORMAL_FILTER, value: false},
                    'spiders-studios': {filterType: NORMAL_FILTER, value: false},
                    'starbreeze-studios': {filterType: NORMAL_FILTER, value: false},
                    'techland': {filterType: NORMAL_FILTER, value: false},
                    'telltale-games': {filterType: NORMAL_FILTER, value: false},
                    'the-creative-assembly': {filterType: NORMAL_FILTER, value: false},
                    'the-sims-studio': {filterType: NORMAL_FILTER, value: false},
                    'tilted-mill-entertainment': {filterType: NORMAL_FILTER, value: false},
                    'trapdoor': {filterType: NORMAL_FILTER, value: false},
                    'travellers-tales': {filterType: NORMAL_FILTER, value: false},
                    'trion-worlds': {filterType: NORMAL_FILTER, value: false},
                    'tt-games': {filterType: NORMAL_FILTER, value: false},
                    'uber-entertainment': {filterType: NORMAL_FILTER, value: false},
                    'ubisoft-montpellier': {filterType: NORMAL_FILTER, value: false},
                    'ubisoft-montreal': {filterType: NORMAL_FILTER, value: false},
                    'ubisoft-shanghai': {filterType: NORMAL_FILTER, value: false},
                    'united-front-games': {filterType: NORMAL_FILTER, value: false},
                    'victory-games': {filterType: NORMAL_FILTER, value: false},
                    'vigil-games': {filterType: NORMAL_FILTER, value: false},
                    'visceral': {filterType: NORMAL_FILTER, value: false},
                    'visceral-games': {filterType: NORMAL_FILTER, value: false},
                    'volition-inc.': {filterType: NORMAL_FILTER, value: false},
                    'westwood-studios': {filterType: NORMAL_FILTER, value: false}
                })
            };

        return {
            facets: facets,
            sortOrders: sortBy
        };

    }

    angular.module('origin-components')
        .factory('StoreFacetFactory', StoreFacetFactory);

}());
