DirtySock: netconncommon.cpp File Reference
netconncommon.cpp File Reference
Cross-platform netconn data types and functions.
#include <string.h>
#include "DirtySDK/dirtysock.h"
#include "DirtySDK/dirtysock/dirtymem.h"
#include "DirtySDK/dirtysock/netconn.h"
#include "netconncommon.h"
Functions
NetConnCommonRefT * NetConnCommonGetRef (void)
Return current module reference.
NetConnCommonRefT * NetConnCommonStartup (int32_t iNetConnRefSize)
Start up common functionality.
void NetConnCommonShutdown (NetConnCommonRefT *pCommonRef)
Shutdown common functionality.
Detailed Description
Cross-platform netconn data types and functions.
Attention
Copyright (c) 2014 Electronic Arts Inc.
Version
05/21/2014 (mclouatre) First Version
Function Documentation
NetConnCommonRefT* NetConnCommonGetRef (void)
Return current module reference.
Returns
NetConnCommonRefT * - reference pointer, or NULL if the module is not active
Version
05/21/2014 (mclouatre)
Referenced by NetConnConnect(), NetConnControl(), NetConnDisconnect(), NetConnQuery(), NetConnShutdown(), and NetConnStatus().
void NetConnCommonShutdown (NetConnCommonRefT * pCommonRef)
Shutdown common functionality.
Parameters
*pCommonRef - common module state
Version
05/21/2014 (mclouatre)
References NetConnCommonRefT::crit, DirtyMemFree(), NetConnCommonRefT::iMemGroup, NETCONN_MEMID, NetCritKill(), NULL, and NetConnCommonRefT::pMemGroupUserData.
Referenced by NetConnShutdown().
NetConnCommonRefT* NetConnCommonStartup (int32_t iNetConnRefSize)
Start up common functionality.
Parameters
iNetConnRefSize - size of netconn ref to allocate
Returns
NetConnCommonRefT * - netconn ref if successful; else NULL
Version
05/21/2014 (mclouatre)
References NetConnCommonRefT::crit, DirtyMemAlloc(), DirtyMemGroupQuery(), NetConnCommonRefT::iMemGroup, NETCONN_MEMID, NetCritInit(), NetPrintf, NULL, and NetConnCommonRefT::pMemGroupUserData.
Referenced by NetConnStartup().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:20