DirtySock: ConnApiXenonSessionManager
ConnApiXenonSessionManager
Game
Typedefs
typedef struct
ConnApiXenonSessionManagerRefT ConnApiXenonSessionManagerRefT
Functions
ConnApiXenonSessionManagerRefT * ConnApiXenonSessionManagerCreate (DirtyAddrT *pHostAddr, DirtyAddrT *pLocalAddr)
Allocate module state and prepare for use.
void ConnApiXenonSessionManagerDestroy (ConnApiXenonSessionManagerRefT *pRef)
Destroy the module and release its state.
void ConnApiXenonSessionManagerUpdate (ConnApiXenonSessionManagerRefT *pRef)
Update module state.
void ConnApiXenonSessionManagerConnect (ConnApiXenonSessionManagerRefT *pRef, const char **pSessID, uint32_t *uSlot, uint32_t uCount)
Initiate transaction with demangler service.
void ConnApiXenonSessionManagerConnect2 (ConnApiXenonSessionManagerRefT *pRef, const char **pSessID, uint32_t *uSlot, uint32_t uCount)
Adds the player to the secondary session manager only. Used for rematch.
int32_t ConnApiXenonSessionManagerGetSecureIp (ConnApiXenonSessionManagerRefT *pRef, int32_t *pAddr, const char *pMachineAddress)
Get secure address for specified host.
int32_t ConnApiXenonSessionManagerControl (ConnApiXenonSessionManagerRefT *pRef, int32_t iControl, int32_t iValue, int32_t iValue2, const void *pValue)
Pass-through to DirtySessionManager control function.
int32_t ConnApiXenonSessionManagerStatus (ConnApiXenonSessionManagerRefT *pRef, int32_t iSelect, void *pBuf, int32_t iBufSize)
Return module status based on input selector.
int32_t ConnApiXenonSessionManagerCreateSess (ConnApiXenonSessionManagerRefT *pRef, uint32_t bRanked, uint32_t *uUserFlags, const char *pSession, DirtyAddrT *pLocalAddrs)
Passes the request to create a session to the underlying DirtySessionManager.
Detailed Description
Typedef Documentation
typedef struct ConnApiXenonSessionManagerRefT ConnApiXenonSessionManagerRefT
Function Documentation
void ConnApiXenonSessionManagerConnect (ConnApiXenonSessionManagerRefT * pRef, const char ** pSessID, uint32_t * uSlot, uint32_t uCount)
Initiate transaction with demangler service.
Parameters
*pRef - module state
**pSessID - for Xbox, this is a pointer to the peer's DirtyAddrT
*uSlot - slot to use, i.e. DIRTYSESSIONMANAGER_FLAG_PUBLICSLOT
uCount - number of players to add to the session
Version
04/07/2009 (jrainy)
References DirtySessionManagerConnect(), ConnApiXenonSessionManagerRefT::pPrimarySessionManager, and ConnApiXenonSessionManagerRefT::pSecondarySessionManager.
void ConnApiXenonSessionManagerConnect2 (ConnApiXenonSessionManagerRefT * pRef, const char ** pSessID, uint32_t * uSlot, uint32_t uCount)
Adds the player to the secondary session manager only. Used for rematch.
Parameters
*pRef - module state
**pSessID - for Xbox, this is a pointer to the peer's DirtyAddrT
*uSlot - slot to use, i.e. DIRTYSESSIONMANAGER_FLAG_PUBLICSLOT
uCount - number of players to add to the session None.
Version
04/27/2009 (jrainy)
References DirtySessionManagerConnect(), and ConnApiXenonSessionManagerRefT::pSecondarySessionManager.
int32_t ConnApiXenonSessionManagerControl (ConnApiXenonSessionManagerRefT * pRef, int32_t iControl, int32_t iValue, int32_t iValue2, const void * pValue)
Pass-through to DirtySessionManager control function.
Parameters
*pRef - mangle ref
iControl - control selector
iValue - selector specific
iValue2 - selector specific
*pValue - selector specific
Returns
int32_t - selector specific
Note
iControl can be one of the following:
        'pres' - add/remove presence to/from secondary session creation flags
Version
04/07/2009 (jrainy)
References _ConnApiXenonSessionManagerDecodeLength(), ConnApiXenonSessionManagerRefT::aLocalAddrs, DirtySessionManagerControl(), DirtySessionManagerCreateSess(), DirtySessionManagerStatus(), ConnApiXenonSessionManagerRefT::iCombinedSessionFlags, ConnApiXenonSessionManagerRefT::iRanked, NULL, ConnApiXenonSessionManagerRefT::pPrimarySessionManager, ConnApiXenonSessionManagerRefT::pSecondarySessionManager, and ConnApiXenonSessionManagerRefT::uSlotType.
Referenced by ConnApiControl(), ConnApiDisconnect(), ConnApiMigratePlatformHost(), ConnApiRemoveUser(), ConnApiStart(), and ConnApiStop().
ConnApiXenonSessionManagerRefT* ConnApiXenonSessionManagerCreate (DirtyAddrT * pHostAddr, DirtyAddrT * pLocalAddr)
Allocate module state and prepare for use.
Parameters
*pHostAddr - host dirtyaddr, or NULL if not available
*pLocalAddr - local dirtyaddr, or NULL if not available
Returns
ConnApiXenonSessionManagerRefT * - reference pointer (must be passed to all other functions)
Version
04/07/2009 (jrainy)
References DirtyMemAlloc(), DirtyMemGroupQuery(), DirtySessionManagerControl(), DirtySessionManagerCreate(), DirtySessionManagerStatus(), DIRTYSESSMGR_MEMID, ConnApiXenonSessionManagerRefT::iCombinedSessionFlags, ConnApiXenonSessionManagerRefT::iMemGroup, NetPrintf, NULL, ConnApiXenonSessionManagerRefT::pMemGroupUserData, ConnApiXenonSessionManagerRefT::pPrimarySessionManager, pRef, and ConnApiXenonSessionManagerRefT::pSecondarySessionManager.
Referenced by ConnApiCreate2().
int32_t ConnApiXenonSessionManagerCreateSess (ConnApiXenonSessionManagerRefT * pRef, uint32_t bRanked, uint32_t * uUserFlags, const char * pSession, DirtyAddrT * pLocalAddrs)
Passes the request to create a session to the underlying DirtySessionManager.
Parameters
*pRef - module state
bRanked - whether the session is ranked
*uUserFlags - array of flags to pass to the DirtySessionManager
*pSession - encoded session string, for existing session or NULL for new session
*pLocalAddrs - array of local address of players to join in locally
Returns
int32_t - zero=success, negative=failure
Version
04/07/2009 (jrainy)
References _ConnApiXenonSessionManagerDecodeLength(), ConnApiXenonSessionManagerRefT::aLocalAddrs, DirtySessionManagerCreateSess(), ds_memcpy(), FALSE, ConnApiXenonSessionManagerRefT::iRanked, NetPrintf, NULL, ConnApiXenonSessionManagerRefT::pPrimarySessionManager, ConnApiXenonSessionManagerRefT::pSecondarySessionManager, and ConnApiXenonSessionManagerRefT::uSlotType.
void ConnApiXenonSessionManagerDestroy (ConnApiXenonSessionManagerRefT * pRef)
Destroy the module and release its state.
Parameters
*pRef - reference pointer
Returns
None.
Version
04/07/2009 (jrainy)
References DirtyMemFree(), DirtySessionManagerDestroy(), DIRTYSESSMGR_MEMID, ConnApiXenonSessionManagerRefT::iMemGroup, ConnApiXenonSessionManagerRefT::pMemGroupUserData, ConnApiXenonSessionManagerRefT::pPrimarySessionManager, and ConnApiXenonSessionManagerRefT::pSecondarySessionManager.
int32_t ConnApiXenonSessionManagerGetSecureIp (ConnApiXenonSessionManagerRefT * pRef, int32_t * pAddr, const char * pMachineAddress)
Get secure address for specified host.
Parameters
*pRef - module state
*pAddr - storage for secure address (if result code is positive)
*pMachineAddress - machine address
Returns
int32_t - positive=success, negative=failure
Version
04/07/2009 (jrainy)
References DirtySessionManagerGetSecureIp(), and ConnApiXenonSessionManagerRefT::pPrimarySessionManager.
int32_t ConnApiXenonSessionManagerStatus (ConnApiXenonSessionManagerRefT * pRef, int32_t iSelect, void * pBuf, int32_t iBufSize)
Return module status based on input selector.
Parameters
*pRef - mangle ref
iSelect - status selector
*pBuf - buffer pointer
iBufSize - buffer size
Returns
int32_t - selector specific
Note
iSelect can be one of the following:
        'pres' - returns whether sessions creation flags have the presence flag set
Version
04/07/2009 (jrainy)
References _ConnApiXenonSessionManagerEncodeLength(), DirtySessionManagerStatus(), ds_memcpy(), ConnApiXenonSessionManagerRefT::iCombinedSessionFlags, ConnApiXenonSessionManagerRefT::pPrimarySessionManager, and ConnApiXenonSessionManagerRefT::pSecondarySessionManager.
Referenced by ConnApiCreate2(), ConnApiStart(), ConnApiStatus2(), and ConnApiUpdate().
void ConnApiXenonSessionManagerUpdate (ConnApiXenonSessionManagerRefT * pRef)
Update module state.
Parameters
*pRef - module state
Returns
None.
Version
04/07/2009 (jrainy)
References DirtySessionManagerUpdate(), ConnApiXenonSessionManagerRefT::pPrimarySessionManager, and ConnApiXenonSessionManagerRefT::pSecondarySessionManager.
Referenced by ConnApiUpdate().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:56