DirtySock: CryptHash
CryptHash
Crypt
Data Structures
struct CryptHashT
crypthash function block
Macros
#define CRYPTHASH_MAXDIGEST (CRYPTSHA2_HASHSIZE_MAX)
SHA2 has the largest digest size.
#define CRYPTHASH_MAXSTATE (sizeof(CryptSha2T))
SHA2 has the largest state.
Typedefs
typedef enum CryptHashTypeE CryptHashTypeE
typedef void(CryptHashInitT)(void *pState, int32_t iHashSize)
crypthash init func
typedef void(CryptHashUpdateT)(void *pState, const uint8_t *pInput, uint32_t uInputLength)
crypthash update func
typedef void(CryptHashFinalT)(void *pState, void *pBuffer, uint32_t uLength)
crypthash final func
typedef struct CryptHashT CryptHashT
crypthash function block
Enumerations
enum CryptHashTypeE {
CRYPTHASH_NULL,
CRYPTHASH_MURMUR3,
CRYPTHASH_MD2,
CRYPTHASH_MD5,
CRYPTHASH_SHA1,
CRYPTHASH_SHA224,
CRYPTHASH_SHA256,
CRYPTHASH_SHA384,
CRYPTHASH_SHA512,
CRYPTHASH_NUMHASHES
}
Functions
DIRTYCODE_API const CryptHashT * CryptHashGet (CryptHashTypeE eHashType)
< get reference to hash function
DIRTYCODE_API int32_t CryptHashGetSize (CryptHashTypeE eHashType)
Get hash size for specified hash type.
Detailed Description
Macro Definition Documentation
#define CRYPTHASH_MAXDIGEST (CRYPTSHA2_HASHSIZE_MAX)
SHA2 has the largest digest size.
Referenced by CryptHmacCalcMulti().
#define CRYPTHASH_MAXSTATE (sizeof(CryptSha2T))
SHA2 has the largest state.
Referenced by CryptHmacCalcMulti().
Typedef Documentation
typedef void(CryptHashFinalT)(void *pState, void *pBuffer, uint32_t uLength)
crypthash final func
typedef void(CryptHashInitT)(void *pState, int32_t iHashSize)
crypthash init func
typedef struct CryptHashT CryptHashT
crypthash function block
typedef enum CryptHashTypeE CryptHashTypeE
typedef void(CryptHashUpdateT)(void *pState, const uint8_t *pInput, uint32_t uInputLength)
crypthash update func
Enumeration Type Documentation
enum CryptHashTypeE
Enumerator
CRYPTHASH_NULL
CRYPTHASH_MURMUR3
murmerhash3; NOT cryto grade but VERY fast, use with caution
CRYPTHASH_MD2
MD2; obsolete, use with caution.
CRYPTHASH_MD5
MD5; semi-obsolete, use with caution.
CRYPTHASH_SHA1
SHA1.
CRYPTHASH_SHA224
SHA2-224.
CRYPTHASH_SHA256
SHA2-256.
CRYPTHASH_SHA384
SHA2-384.
CRYPTHASH_SHA512
SHA2-512.
CRYPTHASH_NUMHASHES
Function Documentation
DIRTYCODE_API const CryptHashT* CryptHashGet (CryptHashTypeE eHashType)
< get reference to hash function
get hash size of specified hash function
< get reference to hash function
Parameters
eHashType - hash type to get size of
Returns
CryptHashT * - hash block pointer, or NULL if not found
Version
11/05/2013 (jbrookes)
References CRYPTHASH_NULL, CRYPTHASH_NUMHASHES, and NULL.
Referenced by CryptHashGetSize(), and CryptHmacCalcMulti().
DIRTYCODE_API int32_t CryptHashGetSize (CryptHashTypeE eHashType)
Get hash size for specified hash type.
Parameters
eHashType - hash type to get size of
Returns
int32_t - size of specified hash
Version
03/07/2014 (jbrookes)
References CryptHashGet(), CryptHashT::iHashSize, and NULL.
Referenced by ProtoTunnelControl().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:56