DirtySock: dirtyaddrxboxone.c File Reference
dirtyaddrxboxone.c File Reference
Platform-specific address functions.
#include "DirtySDK/dirtysock.h"
#include "DirtySDK/dirtysock/netconn.h"
#include "DirtySDK/dirtysock/dirtyaddr.h"
#include "DirtySDK/util/tagfield.h"
Functions
uint32_t DirtyAddrToHostAddr (void *pOutput, int32_t iBufLen, const DirtyAddrT *pAddr)
Convert from DirtyAddrT to native format.
uint32_t DirtyAddrFromHostAddr (DirtyAddrT *pAddr, const void *pInput)
Convert from native format to DirtyAddrT.
uint32_t DirtyAddrGetLocalAddr (DirtyAddrT *pAddr)
Get the local address in DirtyAddr form.
void DirtyAddrGetInfoXboxOne (const DirtyAddrT *pDirtyAddr, void *pXuid, void *pSecureDeviceAddressBlob, int32_t *pBlobSize)
Extract Xbox One-specific fields from the given DirtyAddr.
void DirtyAddrSetInfoXboxOne (DirtyAddrT *pDirtyAddr, const void *pXuid, const void *pSecureDeviceAddressBlob, int32_t iBlobSize)
Set Xbox One-specific fields into the given DirtyAddr.
Detailed Description
Platform-specific address functions.
Attention
Copyright (c) Electronic Arts 2013. ALL RIGHTS RESERVED.
Version
04/17/2013 (mclouatre)
Function Documentation
void DirtyAddrGetInfoXboxOne (const DirtyAddrT * pDirtyAddr, void * pXuid, void * pSecureDeviceAddressBlob, int32_t * pBlobSize)
Extract Xbox One-specific fields from the given DirtyAddr.
Parameters
*pDirtyAddr - dirtyaddr to decode
*pXuid - [out] storage for decoded XUID
*pSecureDeviceAddressBlob - [out] storage for decode SecureDeviceAddress blob
*pBlobSize - [out] size of decoded SecureDeviceAddress blob (in bytes)
Note
Any undesired outputs may be specified as NULL
Version
04/17/2013 (mclouatre)
References DirtyAddrToHostAddr(), DirtyAddrT::strMachineAddr, and TagFieldGetBinary().
void DirtyAddrSetInfoXboxOne (DirtyAddrT * pDirtyAddr, const void * pXuid, const void * pSecureDeviceAddressBlob, int32_t iBlobSize)
Set Xbox One-specific fields into the given DirtyAddr.
Parameters
*pDirtyAddr - [out] storage for dirtyaddr
*pXuid - XUID to encode
*pSecureDeviceAddressBlob - SecureDeviceAddress blob to encode
iBlobSize - size of Secure device address code (in bytes)
Version
04/17/2013 (mclouatre)
References DirtyAddrFromHostAddr(), FALSE, DirtyAddrT::strMachineAddr, and TRUE.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:34:32