DirtySock: ConnApi
ConnApi
Game
Data Structures
struct ConnApiConnInfoT
connection info
struct ConnApiClientInfoT
struct ConnApiClientT
connection type
struct ConnApiClientListT
connection list type
struct ConnApiCbInfoT
callback info
Macros
#define CONNAPI_CONNFLAG_GAMECONN (1)
maximum number of clients allowed
#define CONNAPI_CONNFLAG_VOIPCONN (2)
voip connection supported
#define CONNAPI_CONNFLAG_GAMEVOIP (3)
game and voip connections supported
#define CONNAPI_CONNFLAG_CONNECTED (4)
set if connection succeeded
#define CONNAPI_CONNFLAG_GAMESERVER (8)
set if a gameserver connection
#define CONNAPI_CONNFLAG_DEMANGLED (16)
set if demangler was attempted
#define CONNAPI_CONNFLAG_PKTRECEIVED (32)
set if packets are received (for game connection only)
#define CONNAPI_GAMEFLAG_RANKED (1)
game is a ranked game
#define CONNAPI_GAMEFLAG_PRIVATE (2)
game is a private game
#define CONNAPI_ERROR_INVALID_STATE (-1)
connapi is in an invalid state
#define CONNAPI_ERROR_CLIENTLIST_FULL (-2)
client list is full
#define CONNAPI_ERROR_SLOT_USED (-3)
selected slot already in use
#define CONNAPI_ERROR_SLOT_OUT_OF_RANGE (-4)
selected slot is not an valid index into the client array
#define CONNAPI_CALLBACKS_FULL (-5)
$$TODO DEPRECATE (unused) - maximum number of callbacks registered
#define CONNAPI_CALLBACK_NOT_FOUND (-6)
$$TODO DEPRECATE (unused) - callback not found
#define CONNAPI_FLAG_PUBLICSLOT (1)
#define CONNAPI_FLAG_PRIVATESLOT (2)
#define ConnApiCreate(_iGamePort, _iMaxClients, _pCallback, _pUserData) ConnApiCreate2(_iGamePort, _iMaxClients, _pCallback, _pUserData, (CommAllConstructT *)CommUDPConstruct)
Typedefs
typedef enum ConnApiGameServModeE ConnApiGameServModeE
typedef enum ConnApiCbTypeE ConnApiCbTypeE
ConnApi callback types.
typedef enum ConnApiConnStatusE ConnApiConnStatusE
typedef struct ConnApiConnInfoT ConnApiConnInfoT
connection info
typedef struct ConnApiClientInfoT ConnApiClientInfoT
typedef struct ConnApiClientT ConnApiClientT
connection type
typedef struct ConnApiClientListT ConnApiClientListT
connection list type
typedef struct ConnApiCbInfoT ConnApiCbInfoT
callback info
typedef struct ConnApiRefT ConnApiRefT
opaque module ref
typedef void(ConnApiCallbackT)(ConnApiRefT *pConnApi, ConnApiCbInfoT *pCbInfo, void *pUserData)
connection event callback function prototype
Enumerations
enum ConnApiGameServModeE {
CONNAPI_GAMESERV_BROADCAST,
CONNAPI_GAMESERV_PEERCONN
}
enum ConnApiCbTypeE {
CONNAPI_CBTYPE_GAMEEVENT,
CONNAPI_CBTYPE_DESTEVENT,
CONNAPI_CBTYPE_VOIPEVENT,
CONNAPI_CBTYPE_SESSEVENT,
CONNAPI_CBTYPE_RANKEVENT,
CONNAPI_NUMCBTYPES
}
ConnApi callback types.
enum ConnApiConnStatusE {
CONNAPI_STATUS_INIT,
CONNAPI_STATUS_CONN,
CONNAPI_STATUS_MNGL,
CONNAPI_STATUS_ACTV,
CONNAPI_STATUS_CLSE,
CONNAPI_STATUS_DISC,
CONNAPI_NUMSTATUSTYPES
}
Functions
DIRTYCODE_API ConnApiRefT * ConnApiCreate2 (int32_t iGamePort, int32_t iMaxClients, ConnApiCallbackT *pCallback, void *pUserData, CommAllConstructT *pConstruct)
Create the module state.
DIRTYCODE_API void ConnApiOnline (ConnApiRefT *pConnApi, const char *pGameName, uint32_t uSelfId)
This function should be called once the user has logged on and the input parameters are available.
DIRTYCODE_API void ConnApiDestroy (ConnApiRefT *pConnApi)
Destroy the module state.
DIRTYCODE_API void ConnApiConnect (ConnApiRefT *pConnApi, ConnApiClientInfoT *pClientList, int32_t iClientListSize, int32_t iTopologyHostIndex, int32_t iPlatformHostIndex, int32_t iSessId, uint32_t uGameFlags)
Connect to a game.
DIRTYCODE_API int32_t ConnApiAddClient (ConnApiRefT *pConnApi, ConnApiClientInfoT *pClientInfo, int32_t iClientIdx)
Add a new client to a pre-existing game at the specified index.
DIRTYCODE_API uint8_t ConnApiFindClient (ConnApiRefT *pConnApi, ConnApiClientInfoT *pClientInfo, ConnApiClientT *pOutClient)
Returns the ConnApiClientT of a given client, if found by id.
DIRTYCODE_API void ConnApiRemoveClient (ConnApiRefT *pConnApi, int32_t iClientIdx)
Remove a current client from a game.
DIRTYCODE_API void ConnApiMigrateTopologyHost (ConnApiRefT *pConnApi, int32_t iNewTopologyHostIndex)
Reopen all connections, using the host specified. This is for host migration to a different host in non-peerweb, needing new connections for everyone.
DIRTYCODE_API void ConnApiMigratePlatformHost (ConnApiRefT *pConnApi, int32_t iNewPlatformHostIndex, void *pPlatformData)
Specified client index becomes responsible for managing platform (session owner)
DIRTYCODE_API void ConnApiStart (ConnApiRefT *pConnApi, uint32_t uStartFlags)
Start game session.
DIRTYCODE_API void ConnApiStop (ConnApiRefT *pConnApi)
End game session.
DIRTYCODE_API void ConnApiRematch (ConnApiRefT *pConnApi)
End game session.
DIRTYCODE_API void ConnApiSetPresence (ConnApiRefT *pConnApi, uint8_t uPresenceEnabled)
Stub: would switch to a presence enabled(or disabled) session, if the platform had it.
DIRTYCODE_API void ConnApiDisconnect (ConnApiRefT *pConnApi)
Stop game, disconnect from clients, and reset client list.
DIRTYCODE_API const
ConnApiClientListT * ConnApiGetClientList (ConnApiRefT *pConnApi)
Get a list of current connections.
DIRTYCODE_API int32_t ConnApiStatus (ConnApiRefT *pConnApi, int32_t iSelect, void *pBuf, int32_t iBufSize)
Get status information.
DIRTYCODE_API int32_t ConnApiStatus2 (ConnApiRefT *pConnApi, int32_t iSelect, void *pData, void *pBuf, int32_t iBufSize)
Get status information.
DIRTYCODE_API int32_t ConnApiControl (ConnApiRefT *pConnApi, int32_t iControl, int32_t iValue, int32_t iValue2, void *pValue)
Control behavior of module.
DIRTYCODE_API void ConnApiUpdate (ConnApiRefT *pConnApi)
Update the ConnApi module (must be called directly if auto-update is disabled)
DIRTYCODE_API int32_t ConnApiAddCallback (ConnApiRefT *pConnApi, ConnApiCallbackT *pCallback, void *pUserData)
Register a new callback.
DIRTYCODE_API int32_t ConnApiRemoveCallback (ConnApiRefT *pConnApi, ConnApiCallbackT *pCallback, void *pUserData)
Unregister a callback.
DIRTYCODE_API char * ConnApiGetSessionPattern (const void *pFirstPartyStruct, int32_t *pFrom, int32_t *pLength)
Detailed Description
Macro Definition Documentation
#define CONNAPI_CALLBACK_NOT_FOUND (-6)
$$TODO DEPRECATE (unused) - callback not found
Referenced by ConnApiRemoveCallback().
#define CONNAPI_CALLBACKS_FULL (-5)
$$TODO DEPRECATE (unused) - maximum number of callbacks registered
Referenced by ConnApiAddCallback().
#define CONNAPI_CONNFLAG_CONNECTED (4)
set if connection succeeded
#define CONNAPI_CONNFLAG_DEMANGLED (16)
set if demangler was attempted
#define CONNAPI_CONNFLAG_GAMECONN (1)
maximum number of clients allowed
game connection supported
Referenced by ConnApiControl().
#define CONNAPI_CONNFLAG_GAMESERVER (8)
set if a gameserver connection
#define CONNAPI_CONNFLAG_GAMEVOIP (3)
game and voip connections supported
Referenced by ConnApiControl(), and ConnApiCreate2().
#define CONNAPI_CONNFLAG_PKTRECEIVED (32)
set if packets are received (for game connection only)
#define CONNAPI_CONNFLAG_VOIPCONN (2)
voip connection supported
Referenced by ConnApiControl().
#define CONNAPI_ERROR_CLIENTLIST_FULL (-2)
client list is full
Referenced by ConnApiAddClient().
#define CONNAPI_ERROR_INVALID_STATE (-1)
connapi is in an invalid state
Referenced by ConnApiAddClient().
#define CONNAPI_ERROR_SLOT_OUT_OF_RANGE (-4)
selected slot is not an valid index into the client array
Referenced by ConnApiAddClient().
#define CONNAPI_ERROR_SLOT_USED (-3)
selected slot already in use
Referenced by ConnApiAddClient().
#define CONNAPI_FLAG_PRIVATESLOT (2)
#define CONNAPI_FLAG_PUBLICSLOT (1)
#define CONNAPI_GAMEFLAG_PRIVATE (2)
game is a private game
#define CONNAPI_GAMEFLAG_RANKED (1)
game is a ranked game
#define ConnApiCreate (_iGamePort, _iMaxClients, _pCallback, _pUserData) ConnApiCreate2(_iGamePort, _iMaxClients, _pCallback, _pUserData, (CommAllConstructT *)CommUDPConstruct)
Typedef Documentation
typedef void(ConnApiCallbackT)(ConnApiRefT *pConnApi, ConnApiCbInfoT *pCbInfo, void *pUserData)
connection event callback function prototype
typedef struct ConnApiCbInfoT ConnApiCbInfoT
callback info
typedef enum ConnApiCbTypeE ConnApiCbTypeE
ConnApi callback types.
connection status
typedef struct ConnApiClientInfoT ConnApiClientInfoT
typedef struct ConnApiClientListT ConnApiClientListT
connection list type
typedef struct ConnApiClientT ConnApiClientT
connection type
typedef struct ConnApiConnInfoT ConnApiConnInfoT
connection info
typedef enum ConnApiConnStatusE ConnApiConnStatusE
typedef enum ConnApiGameServModeE ConnApiGameServModeE
typedef struct ConnApiRefT ConnApiRefT
opaque module ref
Enumeration Type Documentation
enum ConnApiCbTypeE
ConnApi callback types.
Enumerator
CONNAPI_CBTYPE_GAMEEVENT
a game event occurred
CONNAPI_CBTYPE_DESTEVENT
link/util ref destruction event
CONNAPI_CBTYPE_VOIPEVENT
a voip event occurred
CONNAPI_CBTYPE_SESSEVENT
a session event occurred (Xenon only)
CONNAPI_CBTYPE_RANKEVENT
game is ending, connapi requires ranking data (Xenon only)
CONNAPI_NUMCBTYPES
number of callback types
enum ConnApiConnStatusE
Enumerator
CONNAPI_STATUS_INIT
initialization state
CONNAPI_STATUS_CONN
connecting to peer
CONNAPI_STATUS_MNGL
demangling
CONNAPI_STATUS_ACTV
connection established
CONNAPI_STATUS_CLSE
connection closing
CONNAPI_STATUS_DISC
disconnected
CONNAPI_NUMSTATUSTYPES
max number of status types
enum ConnApiGameServModeE
Enumerator
CONNAPI_GAMESERV_BROADCAST
rebroadcast mode
CONNAPI_GAMESERV_PEERCONN
peer connection mode
Function Documentation
DIRTYCODE_API int32_t ConnApiAddCallback (ConnApiRefT * pConnApi, ConnApiCallbackT * pCallback, void * pUserData)
Register a new callback.
Parameters
*pConnApi - pointer to module state
*pCallback - the callback to add
*pUserData - the user data that will be passed back
Returns
int32_t - negative means error. 0 or greater: slot used
Version
09/18/2008 (jrainy)
References CONNAPI_CALLBACKS_FULL, CONNAPI_MAX_CALLBACKS, NULL, ConnApiRefT::pCallback, and ConnApiRefT::pUserData.
DIRTYCODE_API int32_t ConnApiAddClient (ConnApiRefT * pConnApi, ConnApiClientInfoT * pClientInfo, int32_t iClientIndex)
Add a new client to a pre-existing game at the specified index.
Parameters
*pConnApi - pointer to module state
*pClientInfo - info on joining user
iClientIndex - index to add client to
Returns
0 if successful, error code otherwise.
Note
This function should be called by all current members of a game while ConnApiConnect() is called by the joining client.
Version
06/16/2008 (jbrookes)
References ConnApiClientT::bAllocated, ConnApiRefT::ClientList, ConnApiClientListT::Clients, CONNAPI_ERROR_CLIENTLIST_FULL, CONNAPI_ERROR_INVALID_STATE, CONNAPI_ERROR_SLOT_OUT_OF_RANGE, CONNAPI_ERROR_SLOT_USED, ConnApiRefT::eState, ConnApiClientListT::iMaxClients, ConnApiClientListT::iNumClients, NetPrintf, NULL, ConnApiRefT::pGameUtilRef, ST_IDLE, and TRUE.
DIRTYCODE_API void ConnApiConnect (ConnApiRefT * pConnApi, ConnApiClientInfoT * pClientList, int32_t iClientListSize, int32_t iTopologyHostIndex, int32_t iPlatformHostIndex, int32_t iSessId, uint32_t uGameFlags)
Connect to a game.
Parameters
*pConnApi - pointer to module state
*pClientList - list of clients in game session
iClientListSize - number of clients in list
iTopologyHostIndex - index in the client list who will be serving as topology host
iPlatformHostIndex - (ignored)
iSessId - unique session identifier
uGameFlags - CONNAPI_GAMEFLAG_*
Note
ConnApi supports invalid entries in the client list. Invalid clients are detected with a DirtyAddr that is zeroed out
Version
09/29/2009 (cvienneau)
References ConnApiRefT::eState, ConnApiRefT::iHostIndex, ConnApiRefT::iSelf, ConnApiRefT::iSessId, NetPrintf, NULL, ConnApiRefT::pGameUtilRef, ConnApiRefT::pProtoMangle, ProtoMangleControl(), and ST_IDLE.
DIRTYCODE_API int32_t ConnApiControl (ConnApiRefT * pConnApi, int32_t iControl, int32_t iValue, int32_t iValue2, void * pValue)
Control behavior of module.
Parameters
*pConnApi - pointer to module state
iControl - status selector
iValue - control value
iValue2 - control value
*pValue - control value
Returns
int32_t - selector specific
Note
iControl can be one of the following:
        'adve' - set to enable ProtoAdvt advertising
        'auto' - set auto-update enable/disable - iValue=TRUE or FALSE (default TRUE)
        'cbfp' - set callback function pointer - pValue=pCallback
        'cbup' - set callback user data pointer - pValue=pUserData
        'ctim' - set connection timeout - iValue=timeout (minimum & default 10000 ms)
        'dist' - set dist ref - iValue=index of client or 'gsrv' for GameServer user, pValue=dist ref
        'dsrv' - set demangler server - pValue=pointer to demangler server name (default demangler.ea.com)
        'dtim' - set demangler timeout - iValue=timeout in milliseconds per max user
        'gprt' - set game port to use - iValue=port
        'gsid' - set gameserver id - iValue=id
        'gsrv' - set address of gameserver - iValue=address
        'gsv2' - set Game Server Connection Mode - iValue=mode
        'fbkp' - set fallback ports  iValue=fallback game port, iValu2=fallback remote tunnel port
        'lbuf' - set game link buffer size - iValue=size (default 1024)
        'meta' - enable/disable commudp metadata
        'minp' - set GameLink input buffer queue length - iValue=length (default 32)
        'mngl' - set demangler enable/disable - iValue=TRUE/FALSE (default TRUE)
        'mout' - set GameLink output buffer queue length - iValue=length (default 32)
        'mvtm' - set multiple virtual machine mode enable/disable - iValue=TRUE/FALSE (default FALSE)
        'mwid' - set GameLink max packet size - iValue=size (default 240, max 512)
        'nmsk' - set netmask used for external address comparisons - iValue=mask (default 0xffffffff)
        'peer' - set game conn peer-web enable/disable - iValue=TRUE/FALSE (default FALSE)
        'phcc' - enable/disable PcHostXboxOneClient mode
        'rcbk' - set enable of disc callback on removal - iValue=TRUE/FALSE (default FALSE)
        'stun' - set prototunnel ref
        'tctl' - set prototunnel control data
        'time' - set timeout - iValue=timeout in ms (default 15 seconds)
        'tgam' - enable the override of game tunnel flags - iValue=falgs, iValue2=boolean(overrides or not)
        'tunl' - set tunnel parms:
                     iValue = TRUE/FALSE to enable/disable or negative to ignore
                     iValue2 = tunnel port, or negative to ignore
                     pValue = tunnel crypto key, or NULL to ignore
        'type' - set connection type - iValue = CONNAPI_CONNFLAG_*
        'upnp' - set UPnP enable - iValue = TRUE to enable, FALSE to disable
        'vcon' - set the conapi to voip only with no game
        'voig' - pass-through to VoipGroupControl()
        'voip' - pass-through to VoipControl() - iValue=VoIP iControl, iValue2= VoIP iValue
        'vprt' - set voip port to use - iValue=port
        'vset' - set voip enable/disable (default=TRUE; call before ConnApiOnline())
        'exsn' - set the external session name for the MultiplayerSessionReference (xbox one only, not yet implemented)
        'exst' - set the external session template name for the MultiplayerSessionReference (xbox one only, not yet implemented)
        'scid' - set the service configuration id for the MultiplayerSessionReference (xbox one only, not yet implemented)
        'sqos' - set QoS settings used when creating NetGameLinks. iValue=QoS duration (0 disables QoS), iValue2=QoS packet interval
        'lqos' - set QoS packet size used when creating NetGameLinks. iValue=packet size in bytes
        '!res' - force secure address resolution to fail, to simulate p2p connection failure
Version
01/04/2005 (jbrookes)
References ConnApiRefT::bAutoUpdate, ConnApiRefT::bCommUdpMetadata, ConnApiRefT::bDemanglerEnabled, ConnApiRefT::bDoAdvertising, ConnApiRefT::bPeerWeb, ConnApiRefT::bRemoveCallback, ConnApiRefT::bTunnelEnabled, ConnApiRefT::bUpnpEnabled, ConnApiRefT::bVoipEnabled, ConnApiRefT::bVoipRedirectViaHost, ConnApiRefT::ClientList, ConnApiClientListT::Clients, CONNAPI_CONNFLAG_GAMECONN, CONNAPI_CONNFLAG_GAMEVOIP, CONNAPI_CONNFLAG_VOIPCONN, CONNAPI_CONNTIMEOUT_DEFAULT, CONNAPI_DEMANGLER_MAXTIMEOUT, ds_strnzcpy(), ConnApiRefT::eGameServMode, FALSE, ConnApiRefT::GameServer, ConnApiRefT::iConnTimeout, ConnApiRefT::iGameMinp, ConnApiRefT::iGameMout, ConnApiRefT::iGameMwid, ConnApiRefT::iGameUnackLimit, ConnApiRefT::iLinkBufSize, ConnApiClientListT::iMaxClients, ConnApiRefT::iMnglTimeout, ConnApiRefT::iQosDuration, ConnApiRefT::iQosInterval, ConnApiRefT::iQosPacketSize, ConnApiRefT::iTimeout, ConnApiRefT::iTunnelPort, NETGAME_DATAPKT_MAXSIZE, NETGAME_QOS_DURATION_MAX, NETGAME_QOS_DURATION_MIN, NETGAME_QOS_INTERVAL_MIN, NETGAME_QOS_PACKETSIZE_MIN, NetPrintf, NULL, ConnApiRefT::pCallback, ConnApiClientT::pGameDistRef, ConnApiRefT::pProtoMangle, ConnApiRefT::pProtoTunnel, ProtoMangleControl(), ProtoTunnelControl(), ConnApiRefT::pUserData, ConnApiRefT::pVoipGroupRef, ConnApiRefT::pVoipRef, ConnApiRefT::strDemanglerServer, ConnApiRefT::strGameServName, ConnApiRefT::strTunnelKey, ConnApiRefT::uConnFlags, ConnApiRefT::uFallbackGamePort, ConnApiRefT::uFallbackTunnelPort, ConnApiRefT::uGamePort, ConnApiRefT::uGameServAddr, ConnApiRefT::uGameServConnMode, ConnApiRefT::uGameServFallback, ConnApiRefT::uGameServId, ConnApiRefT::uGameTunnelFlag, ConnApiRefT::uGameTunnelFlagOverride, ConnApiRefT::uNetMask, ConnApiRefT::uVoipPort, VoipControl(), and VoipGroupControl().
Referenced by ConnApiOnline().
DIRTYCODE_API ConnApiRefT* ConnApiCreate2 (int32_t iGamePort, int32_t iMaxClients, ConnApiCallbackT * pCallback, void * pUserData, CommAllConstructT * pConstruct)
Create the module state.
Parameters
iGamePort - game connection port
iMaxClients - maximum number of clients allowed
*pCallback - pointer to user callback
*pUserData - pointer to user data
*pConstruct - comm construct function
Returns
ConnApiRefT * - pointer to module state, or NULL
Version
01/04/2005 (jbrookes)
References ConnApiRefT::bAutoUpdate, ConnApiRefT::bDemanglerEnabled, ConnApiRefT::bDoAdvertising, ConnApiRefT::bUpnpEnabled, ConnApiRefT::bVoipEnabled, ConnApiRefT::bVoipRedirectViaHost, ConnApiRefT::ClientList, CONNAPI_CONNFLAG_GAMEVOIP, CONNAPI_CONNTIMEOUT_DEFAULT, CONNAPI_DEMANGLER_TIMEOUT, CONNAPI_LINKBUFDEFAULT, CONNAPI_MEMID, CONNAPI_TIMEOUT_DEFAULT, DirtyMemAlloc(), DirtyMemFree(), DirtyMemGroupQuery(), ds_strnzcpy(), FALSE, ConnApiRefT::iConnTimeout, ConnApiRefT::iLinkBufSize, ConnApiClientListT::iMaxClients, ConnApiRefT::iMemGroup, ConnApiRefT::iMnglTimeout, ConnApiRefT::iQosDuration, ConnApiRefT::iQosInterval, ConnApiRefT::iQosPacketSize, iSize, ConnApiRefT::iTimeout, ConnApiRefT::iTunnelPort, NetConnIdleAdd(), NETGAME_QOS_INTERVAL_MIN, NETGAME_QOS_PACKETSIZE_MIN, NetPrintf, NULL, ConnApiRefT::pCallback, ConnApiRefT::pCommConstruct, ConnApiRefT::pMemGroupUserData, PROTOMANGLE_SERVER, ConnApiRefT::pUserData, ConnApiRefT::pVoipGroupRef, ConnApiRefT::strDemanglerServer, TRUE, ConnApiRefT::uConnFlags, ConnApiRefT::uGamePort, ConnApiRefT::uGameServConnMode, ConnApiRefT::uGameServFallback, ConnApiRefT::uNetMask, ConnApiRefT::uVoipPort, VOIP_PORT, VoipGroupCreate(), and VoipGroupSetConnSharingEventCallback().
DIRTYCODE_API void ConnApiDestroy (ConnApiRefT * pConnApi)
Destroy the module state.
Parameters
*pConnApi - pointer to module state
Version
01/04/2005 (jbrookes)
References ConnApiRefT::bTunnelOwner, ConnApiRefT::bVoipOwner, CONNAPI_MEMID, ConnApiDisconnect(), DirtyMemFree(), ConnApiRefT::iMemGroup, NetConnIdleDel(), NetGameUtilDestroy(), NULL, ConnApiRefT::pGameUtilRef, ConnApiRefT::pMemGroupUserData, ConnApiRefT::pProtoMangle, ConnApiRefT::pProtoTunnel, ConnApiRefT::pProtoUpnp, ProtoMangleDestroy(), ProtoTunnelDestroy(), ProtoUpnpControl(), ProtoUpnpDestroy(), ConnApiRefT::pVoipGroupRef, ConnApiRefT::pVoipRef, TRUE, VoipGroupDestroy(), and VoipShutdown().
DIRTYCODE_API void ConnApiDisconnect (ConnApiRefT * pConnApi)
Stop game, disconnect from clients, and reset client list.
Parameters
*pConnApi - pointer to module state
Note
Any NetGameDistRefs created by the application that references a NetGameUtil/ NeGameLink combination created by ConnApi must destroy the DistRef(s) before calling this function.
Version
01/04/2005 (jbrookes)
References ConnApiClientT::bAllocated, ConnApiRefT::bVoipOwner, ConnApiRefT::ClientList, ConnApiClientListT::Clients, CONNAPI_GAMESERV_BROADCAST, CONNAPI_GAMESERV_PEERCONN, ConnApiRefT::eGameServMode, ConnApiRefT::eState, FALSE, ConnApiRefT::GameServer, ConnApiClientListT::iMaxClients, ConnApiClientListT::iNumClients, ConnApiRefT::iSelf, NetPrintf, NULL, ConnApiRefT::pVoipGroupRef, ConnApiRefT::pVoipRef, ST_IDLE, TRUE, ConnApiRefT::uGameServAddr, ConnApiRefT::uGameSockRef, ConnApiRefT::uTunlSockRef, ConnApiRefT::uVoipSockRef, and VoipGroupControl().
Referenced by ConnApiDestroy().
DIRTYCODE_API uint8_t ConnApiFindClient (ConnApiRefT * pConnApi, ConnApiClientInfoT * pClientInfo, ConnApiClientT * pOutClient)
Returns the ConnApiClientT of a given client, if found by id.
Parameters
*pConnApi - pointer to module state
*pClientInfo - info on searched user
*pOutClient - used to return the ClientT structure of the client
Returns
uint8_t - TRUE if the client is found, FALSE otherwise
Version
06/05/2008 (jbrookes)
References ConnApiClientT::ClientInfo, ConnApiRefT::ClientList, ConnApiClientListT::Clients, ds_memcpy_s(), FALSE, ConnApiClientListT::iMaxClients, TRUE, and ConnApiClientInfoT::uId.
DIRTYCODE_API const ConnApiClientListT* ConnApiGetClientList (ConnApiRefT * pConnApi)
Get a list of current connections.
Parameters
*pConnApi - pointer to module state
Returns
ConnApiClientListT * - pointer to client list
Version
01/04/2005 (jbrookes)
References ConnApiRefT::ClientList.
DIRTYCODE_API char* ConnApiGetSessionPattern (const void * pFirstPartyStruct, int32_t * pFrom, int32_t * pLength)
DIRTYCODE_API void ConnApiMigratePlatformHost (ConnApiRefT * pConnApi, int32_t iNewPlatformHostIndex, void * pPlatformData)
Specified client index becomes responsible for managing platform (session owner)
Parameters
*pConnApi - pointer to module state
iNewPlatformHostIndex - index of new platform host
pPlatformData - platform data
Version
09/30/2009 (cvienneau)
DIRTYCODE_API void ConnApiMigrateTopologyHost (ConnApiRefT * pConnApi, int32_t newTopologyHostIndex)
Reopen all connections, using the host specified. This is for host migration to a different host in non-peerweb, needing new connections for everyone.
Parameters
*pConnApi - pointer to module state
newTopologyHostIndex - index of the new topology host
Version
09/21/2007 (jrainy)
References ConnApiClientT::bAllocated, ConnApiRefT::ClientList, ConnApiClientListT::Clients, CONNAPI_CBTYPE_GAMEEVENT, CONNAPI_STATUS_ACTV, CONNAPI_STATUS_INIT, ConnApiRefT::eState, ConnApiConnInfoT::eStatus, ConnApiClientT::GameInfo, ConnApiRefT::iHostIndex, and ConnApiClientListT::iMaxClients.
DIRTYCODE_API void ConnApiOnline (ConnApiRefT * pConnApi, const char * pGameName, uint32_t uSelfId)
This function should be called once the user has logged on and the input parameters are available.
Parameters
*pConnApi - pointer to module state
*pGameName - pointer to game resource string (eg cso/NCAA-2006/na)
uSelfId - unique identifier for the local connapi client
Version
01/06/2005 (jbrookes)
References ConnApiRefT::bDemanglerEnabled, ConnApiRefT::bDoAdvertising, ConnApiRefT::bTunnelEnabled, ConnApiRefT::bTunnelOwner, ConnApiRefT::bUpnpEnabled, ConnApiRefT::bVoipEnabled, ConnApiRefT::bVoipOwner, ConnApiRefT::ClientList, CONNAPI_CONNTIMEOUT_DEFAULT, ConnApiControl(), DirtyMemGroupEnter(), DirtyMemGroupLeave(), ds_snzprintf(), ds_strnzcpy(), FALSE, ConnApiClientListT::iMaxClients, ConnApiRefT::iMemGroup, ConnApiRefT::iMnglTimeout, ConnApiRefT::iTimeout, ConnApiRefT::iTunnelPort, NetGameUtilAdvert(), NetGameUtilCreate(), NetPrintf, NULL, ConnApiRefT::pGameUtilRef, ConnApiRefT::pMemGroupUserData, ConnApiRefT::pProtoMangle, ConnApiRefT::pProtoTunnel, ConnApiRefT::pProtoUpnp, PROTOMANGLE_PORT, ProtoMangleCreate(), ProtoTunnelCreate(), ProtoUpnpControl(), ProtoUpnpCreate(), ProtoUpnpGetRef(), ConnApiRefT::pVoipRef, ConnApiRefT::strDemanglerServer, ConnApiRefT::strGameName, TRUE, ConnApiRefT::uGamePort, ConnApiRefT::uGameServFallback, ConnApiRefT::uSelfId, VoipGetRef(), and VoipStartup().
DIRTYCODE_API void ConnApiRematch (ConnApiRefT * pConnApi)
End game session.
Parameters
*pConnApi - pointer to module state
Note
This function is a stub on non-Xenon platforms.
Version
04/17/2009 (jrainy)
DIRTYCODE_API int32_t ConnApiRemoveCallback (ConnApiRefT * pConnApi, ConnApiCallbackT * pCallback, void * pUserData)
Unregister a callback.
Parameters
*pConnApi - pointer to module state
*pCallback - the callback to remove
*pUserData - the user data that was originally passed in
Returns
int32_t - negative means error. 0 or greater: slot freed
Version
09/18/2008 (jrainy)
References CONNAPI_CALLBACK_NOT_FOUND, CONNAPI_MAX_CALLBACKS, NULL, ConnApiRefT::pCallback, and ConnApiRefT::pUserData.
DIRTYCODE_API void ConnApiRemoveClient (ConnApiRefT * pConnApi, int32_t iClientIndex)
Remove a current client from a game.
Parameters
*pConnApi - pointer to module state
iClientIndex - index of client to remove (used if pClientName is NULL)
Note
If this function is called inside of a ConnApi callback, the removal will be deferred until the next time NetConnIdle() is called. Otherwise, the removal will happen immediately.
Version
06/14/2008 (jbrookes)
References CONNAPI_CLIENTFLAG_REMOVE.
DIRTYCODE_API void ConnApiSetPresence (ConnApiRefT * pConnApi, uint8_t uPresenceEnabled)
Stub: would switch to a presence enabled(or disabled) session, if the platform had it.
Parameters
*pConnApi - pointer to module state
uPresenceEnabled - whether presence should be enabled or not
Version
05/17/2010 (jrainy)
DIRTYCODE_API void ConnApiStart (ConnApiRefT * pConnApi, uint32_t uStartFlags)
Start game session.
Parameters
*pConnApi - pointer to module state
uStartFlags - CONNAPI_STRTFLAG_*
Note
This function is a stub on non-Xenon platforms.
Version
06/20/2005 (jbrookes)
DIRTYCODE_API int32_t ConnApiStatus (ConnApiRefT * pConnApi, int32_t iSelect, void * pBuf, int32_t iBufSize)
Get status information.
Parameters
*pConnApi - pointer to module state
iSelect - status selector
*pBuf - [out] storage for selector-specific output
iBufSize - size of output buffer
Returns
int32_t - selector specific
Note
iSelect can be one of the following:
        'cbfp' - return current callback function pointer in output buffer
        'cbup' - return current callback data pointer in output buffer
        'dtim' - get demangler timeout (in milliseconds)
        'gprt' - return game port
        'gsmd' - return gameserver mode (ConnApiGameServModeE), or -1 if not using GameServer for game connections
        'gsrv' - return the game server ConnApiClientT
        'ingm' - currently 'in game' (connecting to or connected to one or more peers)
        'lbuf' - returns GameLink buffer allocation size
        'minp' - returns GameLink input buffer queue length (zero=default)
        'mngl' - returns whether demangler is enabled or not
        'mout' - returns GameLink output buffer queue length (zero=default)
        'mplr' - returns one past the index of the last allocated player
        'mwid' - returns GameLink max packet size (zero=default)
        'nmsk' - returns current netmask
        'peer' - returns game conn peer-web enable/disable status
        'self' - returns index of local user in client list
        'sock' - copy socket ref to pBuf
        'sess' - copies session information into output buffer
        'tprt' - returns port tunnel has been bound to (if available)
        'tref' - returns the prototunnel ref used
        'tunl' - returns whether tunnel is enabled or not
        'type' - returns current connection type (CONNAPI_CONNFLAG_*)
        'vprt' - return voip port
Version
01/04/2005 (jbrookes)
References ConnApiStatus2(), and NULL.
DIRTYCODE_API int32_t ConnApiStatus2 (ConnApiRefT * pConnApi, int32_t iSelect, void * pData, void * pBuf, int32_t iBufSize)
Get status information.
Parameters
*pConnApi - pointer to module state
iSelect - status selector
*pData - input data
*pBuf - [out] storage for selector-specific output
iBufSize - size of output buffer
Returns
int32_t - selector specific
Note
iSelect can be one of the following:
        'cadr' - stands for Connection Address, ip address used at the platform socket level to reach this client (regardless of tunneling being used or not)
        'cbfp' - return current callback function pointer in output buffer
        'cbup' - return current callback data pointer in output buffer
        'cprt' - stands for Connection Port, UDP port used at the platform socket level to reach this client
        'dtim' - get demangler timeout (in milliseconds)
        'gprt' - return game port
        'gsmd' - return gameserver mode (ConnApiGameServModeE), or -1 if not using GameServer for game connections
        'gsrv' - return the game server ConnApiClientT
        'host' - returns whether hosting or not, plus copies host name to buffer
        'ingm' - currently 'in game' (connecting to or connected to one or more peers)
        'lbuf' - returns GameLink buffer allocation size
        'minp' - returns GameLink input buffer queue length (zero=default)
        'mngl' - returns whether demangler is enabled or not
        'mout' - returns GameLink output buffer queue length (zero=default)
        'mplr' - returns one past the index of the last allocated player
        'mvtm' - return true if multiple virtual machine mode is active
        'mwid' - returns GameLink max packet size (zero=default)
        'nmsk' - returns current netmask
        'peer' - returns game conn peer-web enable/disable status
        'self' - returns index of local user in client list
        'sock' - copy socket ref to pBuf
        'sess' - copies session information into output buffer
        'tprt' - returns port tunnel has been bound to (if available)
        'tref' - returns the prototunnel ref used
        'tunl' - returns whether tunnel is enabled or not
        'tunr' - returns receive protunnel stats as a ProtoTunnelStatT in pBuf for a given client pData
        'tuns' - returns send prototunnel stats as a ProtoTunnelStatT in pBuf for a given client pData
        'type' - returns current connection type (CONNAPI_CONNFLAG_*)
        'vprt' - return voip port
Version
01/04/2005 (jbrookes)
References ConnApiClientT::bAllocated, ConnApiRefT::bDemanglerEnabled, ConnApiRefT::bPeerWeb, ConnApiRefT::bTunnelEnabled, ConnApiRefT::ClientList, ConnApiClientListT::Clients, CONNAPI_STATUS_ACTV, ds_memcpy(), ds_strnzcpy(), ConnApiRefT::eGameServMode, ConnApiRefT::eState, ConnApiConnInfoT::eStatus, ConnApiClientT::GameInfo, ConnApiRefT::GameServer, ConnApiRefT::iGameMinp, ConnApiRefT::iGameMout, ConnApiRefT::iGameMwid, ConnApiRefT::iGameUnackLimit, ConnApiRefT::iHostIndex, ConnApiRefT::iLinkBufSize, ConnApiClientListT::iMaxClients, ConnApiRefT::iMnglTimeout, ConnApiRefT::iSelf, ConnApiClientT::iTunnelId, NetGameUtilStatus(), NetPrintf, NULL, ConnApiRefT::pCallback, ConnApiClientT::pGameUtilRef, ConnApiRefT::pProtoTunnel, ProtoTunnelStatus(), ConnApiRefT::pUserData, ST_IDLE, ConnApiRefT::strSession, ConnApiRefT::uConnFlags, ConnApiRefT::uGamePort, ConnApiConnInfoT::uMnglPort, ConnApiRefT::uNetMask, and ConnApiRefT::uVoipPort.
Referenced by ConnApiStatus().
DIRTYCODE_API void ConnApiStop (ConnApiRefT * pConnApi)
End game session.
Parameters
*pConnApi - pointer to module state
Note
This function is a stub on non-Xenon platforms.
Version
01/30/2007 (jbrookes)
DIRTYCODE_API void ConnApiUpdate (ConnApiRefT * pConnApi)
Update the ConnApi module (must be called directly if auto-update is disabled)
Parameters
*pConnApi - pointer to module state
Note
By default, ConnApiUpdate() is called internally via a NetConnIdle() callback (auto-update). If auto-update is disabled via ConnApiControl('auto'), ConnApiUpdate must be polled by the application instead.
Version
01/06/2005 (jbrookes)
References CONNAPI_GAMESERV_BROADCAST, ConnApiRefT::eGameServMode, NULL, ConnApiRefT::pProtoMangle, and ProtoMangleUpdate().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:41