#!/bin/bash

if [ ! -d ./bin ]; then
  echo "ERROR: must be run from base Blaze Deploy directory.  bin dir not found when looking for pid files."
  exit 1
fi

top -b -p $(PIDS=;for FILE in $(find ./bin | grep pid | grep -v monitor); do if [ -n "$PIDS" ]; then PIDS="$PIDS,"; fi; PIDS=$PIDS$(cat $FILE); done; echo $PIDS)
