# Documentation - https://docs.docker.com/compose/compose-file/
# (make sure to read the documentation of the version number specified below - currently 3.8)
# We try and use the known versions of following containers currently to keep things stable.

version: "3.8"
services:

  redis-cluster:
    # https://github.com/Grokzen/docker-redis-cluster / https://registry.hub.docker.com/r/grokzen/redis-cluster
    image: grokzen/redis-cluster:5.0.0
    restart: "no"
    # Running the entire Redis Cluster within a single container via this custom container image
    # since it is the simplest way to setup a cluster using Docker Compose.
    ports:
      # Masters 1-3: 30000-30002
      - 30000-30002:30000-30002
    stdin_open: true
    tty: true
    healthcheck:
      test: redis-cli -p 30000 PING
    environment:
      INITIAL_PORT: 30000
      MASTERS: 3
      SLAVES_PER_MASTER: 0

  gen-blaze-redis-config:
    image: bash:latest
    restart: "no"
    volumes:
      - ./../../../init:/init
    command: [sh,-c,"echo 'main = { nodes = [ \"localhost:30000\", \"localhost:30001\", \"localhost:30002\" ] }' > /init/redis.cfg"]

