DirtySock: connapixenonsessionmanager.c File Reference
connapixenonsessionmanager.c File Reference
#include <xtl.h>
#include <xonline.h>
#include "DirtySDK/dirtysock.h"
#include "DirtySDK/dirtysock/dirtyaddr.h"
#include "DirtySDK/dirtysock/dirtymem.h"
#include "DirtySDK/dirtysock/dirtyerr.h"
#include "DirtySDK/dirtysock/dirtysessionmanager.h"
#include "DirtySDK/game/xenon/connapixenonsessionmanager.h"
#include "DirtySDK/dirtysock/netconn.h"
Data Structures
struct ConnApiXenonSessionManagerRefT
internal module state
Functions
void _ConnApiXenonSessionManagerEncodeLength (char *strSession, int16_t iLength1, int16_t iLength2)
void _ConnApiXenonSessionManagerDecodeLength (const char *strSession, int16_t *pLength1, int16_t *pLength2)
ConnApiXenonSessionManagerRefT * ConnApiXenonSessionManagerCreate (DirtyAddrT *pHostAddr, DirtyAddrT *pLocalAddr)
Allocate module state and prepare for use.
void ConnApiXenonSessionManagerDestroy (ConnApiXenonSessionManagerRefT *pRef)
Destroy the module and release its state.
void ConnApiXenonSessionManagerUpdate (ConnApiXenonSessionManagerRefT *pRef)
Update module state.
void ConnApiXenonSessionManagerConnect (ConnApiXenonSessionManagerRefT *pRef, const char **pSessID, uint32_t *uSlot, uint32_t uCount)
Initiate transaction with demangler service.
void ConnApiXenonSessionManagerConnect2 (ConnApiXenonSessionManagerRefT *pRef, const char **pSessID, uint32_t *uSlot, uint32_t uCount)
Adds the player to the secondary session manager only. Used for rematch.
int32_t ConnApiXenonSessionManagerGetSecureIp (ConnApiXenonSessionManagerRefT *pRef, int32_t *pAddr, const char *pMachineAddress)
Get secure address for specified host.
int32_t ConnApiXenonSessionManagerCreateSess (ConnApiXenonSessionManagerRefT *pRef, uint32_t bRanked, uint32_t *uUserFlags, const char *pSession, DirtyAddrT *pLocalAddrs)
Passes the request to create a session to the underlying DirtySessionManager.
int32_t ConnApiXenonSessionManagerControl (ConnApiXenonSessionManagerRefT *pRef, int32_t iControl, int32_t iValue, int32_t iValue2, const void *pValue)
Pass-through to DirtySessionManager control function.
int32_t ConnApiXenonSessionManagerStatus (ConnApiXenonSessionManagerRefT *pRef, int32_t iSelect, void *pBuf, int32_t iBufSize)
Return module status based on input selector.
Detailed Description
Note
Attention
Copyright (c) / Electronic Arts 2008-2009. ALL RIGHTS RESERVED.
Version
1.0 04/07/2009 (jrainy) First version
Function Documentation
void _ConnApiXenonSessionManagerDecodeLength (const char * strSession, int16_t * pLength1, int16_t * pLength2)
References NULL.
Referenced by ConnApiXenonSessionManagerControl(), and ConnApiXenonSessionManagerCreateSess().
void _ConnApiXenonSessionManagerEncodeLength (char * strSession, int16_t iLength1, int16_t iLength2)
Referenced by ConnApiXenonSessionManagerStatus().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:54