//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EA.PackageSystem.PackageCore.ServicesWCF
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://EATechNet.MOSS.Packages.Services/", ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://EATechNet.MOSS.Packages.Services/GetReleaseDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EA.PackageSystem.PackageCore.ServicesWCF.ArrayOfXElement> GetReleaseDetailsAsync(string name, string version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://EATechNet.MOSS.Packages.Services/GetPackageDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EA.PackageSystem.PackageCore.ServicesWCF.ArrayOfXElement> GetPackageDetailsAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://EATechNet.MOSS.Packages.Services/GetRelease", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EA.PackageSystem.PackageCore.Services.Release> GetReleaseAsync(string name, string version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://EATechNet.MOSS.Packages.Services/GetPackage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EA.PackageSystem.PackageCore.Services.Package> GetPackageAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://EATechNet.MOSS.Packages.Services/GetPackageReleases", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EA.PackageSystem.PackageCore.Services.Release[]> GetPackageReleasesAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://EATechNet.MOSS.Packages.Services/GetReleaseDependents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EA.PackageSystem.PackageCore.Services.Release[]> GetReleaseDependentsAsync(string name, string version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://EATechNet.MOSS.Packages.Services/GetAllPackages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EA.PackageSystem.PackageCore.Services.Package[]> GetAllPackagesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://EATechNet.MOSS.Packages.Services/GetAllReleases", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EA.PackageSystem.PackageCore.Services.Release[]> GetAllReleasesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://EATechNet.MOSS.Packages.Services/PostPackage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> PostPackageAsync(string fileName, string uncName, string changes, int statusId, string statusComment, string requiredReleases, string account);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface WebServiceSoapChannel : EA.PackageSystem.PackageCore.ServicesWCF.WebServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<EA.PackageSystem.PackageCore.ServicesWCF.WebServiceSoap>, EA.PackageSystem.PackageCore.ServicesWCF.WebServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), WebServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<EA.PackageSystem.PackageCore.ServicesWCF.ArrayOfXElement> GetReleaseDetailsAsync(string name, string version)
        {
            return base.Channel.GetReleaseDetailsAsync(name, version);
        }
        
        public System.Threading.Tasks.Task<EA.PackageSystem.PackageCore.ServicesWCF.ArrayOfXElement> GetPackageDetailsAsync(string name)
        {
            return base.Channel.GetPackageDetailsAsync(name);
        }
        
        public System.Threading.Tasks.Task<EA.PackageSystem.PackageCore.Services.Release> GetReleaseAsync(string name, string version)
        {
            return base.Channel.GetReleaseAsync(name, version);
        }
        
        public System.Threading.Tasks.Task<EA.PackageSystem.PackageCore.Services.Package> GetPackageAsync(string name)
        {
            return base.Channel.GetPackageAsync(name);
        }
        
        public System.Threading.Tasks.Task<EA.PackageSystem.PackageCore.Services.Release[]> GetPackageReleasesAsync(string name)
        {
            return base.Channel.GetPackageReleasesAsync(name);
        }
        
        public System.Threading.Tasks.Task<EA.PackageSystem.PackageCore.Services.Release[]> GetReleaseDependentsAsync(string name, string version)
        {
            return base.Channel.GetReleaseDependentsAsync(name, version);
        }
        
        public System.Threading.Tasks.Task<EA.PackageSystem.PackageCore.Services.Package[]> GetAllPackagesAsync()
        {
            return base.Channel.GetAllPackagesAsync();
        }
        
        public System.Threading.Tasks.Task<EA.PackageSystem.PackageCore.Services.Release[]> GetAllReleasesAsync()
        {
            return base.Channel.GetAllReleasesAsync();
        }
        
        public System.Threading.Tasks.Task<string> PostPackageAsync(string fileName, string uncName, string changes, int statusId, string statusComment, string requiredReleases, string account)
        {
            return base.Channel.PostPackageAsync(fileName, uncName, changes, statusId, statusComment, requiredReleases, account);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://packages.ea.com/webservice.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://packages.ea.com/webservice.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebServiceSoap,
            
            WebServiceSoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.0.0.2")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
