DirtySock: voipheadset.h File Reference
voipheadset.h File Reference
VoIP headset manager.
Typedefs
typedef enum
VoipHeadsetStatusUpdateE VoipHeadsetStatusUpdateE
voip headset update status
typedef struct VoipHeadsetRefT VoipHeadsetRefT
opaque headset module ref
typedef void(VoipHeadsetMicDataCbT)(const void *pVoiceData, int32_t iDataSize, const void *pMetaData, int32_t iMetaDataSize, uint32_t uLocalIdx, uint8_t uSendSeqn, void *pUserData)
mic data ready callback function prototype
typedef void(VoipHeadsetStatusCbT)(int32_t iLocalUserIndex, uint32_t bStatus, VoipHeadsetStatusUpdateE eUpdate, void *pUserData)
headset status change callback
Enumerations
enum VoipHeadsetStatusUpdateE {
VOIP_HEADSET_STATUS_INPUT = 1,
VOIP_HEADSET_STATUS_OUTPUT,
VOIP_HEADSET_STATUS_INOUT
}
voip headset update status
Functions
VoipHeadsetRefT * VoipHeadsetCreate (int32_t iMaxChannels, int32_t iMaxLocal, VoipHeadsetMicDataCbT *pMicDataCb, VoipHeadsetStatusCbT *pStatusCb, void *pCbUserData, int32_t iData)
Create the headset manager.
void VoipHeadsetDestroy (VoipHeadsetRefT *pHeadset)
Destroy the headset manager.
void VoipHeadsetReceiveVoiceDataCb (VoipUserT *pRemoteUsers, VoipMicrInfoT *pMicrInfo, uint8_t *pPacketData, void *pUserData)
Connectionlist callback to handle receiving a voice packet from a remote peer.
void VoipHeadsetRegisterUserCb (VoipUserT *pRemoteUser, uint32_t bRegister, void *pUserData)
Connectionlist callback to register a new remote user with the 1st party voice system It will also register remote shared users with voipheadset internally.
void VoipHeadsetProcess (VoipHeadsetRefT *pHeadset, uint32_t uFrameCount)
Headset process function.
void VoipHeadsetSetVolume (VoipHeadsetRefT *pHeadset, int32_t iPlayVol, uint32_t iRecVol)
Sets play and record volume.
int32_t VoipHeadsetControl (VoipHeadsetRefT *pHeadset, int32_t iControl, int32_t iValue, int32_t iValue2, void *pValue)
Control function.
int32_t VoipHeadsetStatus (VoipHeadsetRefT *pHeadset, int32_t iSelect, int32_t iData, void *pBuf, int32_t iBufSize)
Status function.
void VoipHeadsetSpkrCallback (VoipHeadsetRefT *pHeadset, VoipSpkrCallbackT *pCallback, void *pUserData)
Set speaker output callback.
Detailed Description
VoIP headset manager.
Attention
Copyright (c) Electronic Arts 2004. ALL RIGHTS RESERVED.
Version
1.0 03/31/2004 (jbrookes) First Version
Typedef Documentation
typedef void(VoipHeadsetMicDataCbT)(const void *pVoiceData, int32_t iDataSize, const void *pMetaData, int32_t iMetaDataSize, uint32_t uLocalIdx, uint8_t uSendSeqn, void *pUserData)
mic data ready callback function prototype
typedef struct VoipHeadsetRefT VoipHeadsetRefT
opaque headset module ref
typedef void(VoipHeadsetStatusCbT)(int32_t iLocalUserIndex, uint32_t bStatus, VoipHeadsetStatusUpdateE eUpdate, void *pUserData)
headset status change callback
typedef enum VoipHeadsetStatusUpdateE VoipHeadsetStatusUpdateE
voip headset update status
Enumeration Type Documentation
enum VoipHeadsetStatusUpdateE
voip headset update status
Enumerator
VOIP_HEADSET_STATUS_INPUT
VOIP_HEADSET_STATUS_OUTPUT
VOIP_HEADSET_STATUS_INOUT
Function Documentation
int32_t VoipHeadsetControl (VoipHeadsetRefT * pHeadset, int32_t iControl, int32_t iValue, int32_t iValue2, void * pValue)
Control function.
Parameters
*pHeadset - headset module state
iControl - control selector
iValue - control value
iValue2 - control value
*pValue - control value
Returns
int32_t - selector specific, or -1 if no such selector
Note
iControl can be one of the following:
        '+pbk' - enable voice playback for a given remote user (pValue is the remote user VoipUserT).
        '-pbk' - disable voice playback for a given remote user (pValue is the remote user VoipUserT).
        'aloc' - set local user as participating / not participating
        'loop' - enable/disable loopback
        'qual' - set encoding quality
        'rloc' - register/unregister local talker
        'spam' - debug verbosity level
Version
05/24/2013 (mclouatre)
References VoipHeadsetRefT::bLoopback, ds_stristr(), VoipHeadsetRefT::EncodingQual, FALSE, NetPrintf, NULL, VoipUserT::strUserId, TRUE, and VOIP_MAXLOCALUSERS_EXTENDED.
Referenced by VoipActivateLocalUser(), VoipCommonControl(), and VoipControl().
VoipHeadsetRefT* VoipHeadsetCreate (int32_t iMaxChannels, int32_t iMaxLocal, VoipHeadsetMicDataCbT * pMicDataCb, VoipHeadsetStatusCbT * pStatusCb, void * pCbUserData, int32_t iData)
Create the headset manager.
Parameters
iMaxChannels - max number of remote users
iMaxLocal - max number of local users
*pMicDataCb - pointer to user callback to trigger when mic data is ready
*pStatusCb - pointer to user callback to trigger when headset status changes
*pCbUserData - pointer to user callback data
iData - platform-specific - unused for xboxone
Returns
VoipHeadsetRefT * - pointer to module state, or NULL if an error occured
Version
05/24/2013 (mclouatre)
References VoipHeadsetRefT::aLocalUsers, VoipHeadsetRefT::AudioDeviceAddedToken, VoipHeadsetRefT::AudioDeviceChangedToken, VoipHeadsetRefT::AudioDeviceRemovedToken, VoipHeadsetRefT::bHeadsetChanged, VoipHeadsetRefT::crit, DirtyMemAlloc(), VoipHeadsetRefT::EncodingQual, VoipHeadsetRefT::iMaxChannels, NETCONN_MAXLOCALUSERS, NetConnMachineId(), NetConnStatus(), NetCritEnter(), NetCritInit(), NetCritLeave(), NetPrintf, NetTick(), NULL, VoipHeadsetRefT::pCbUserData, VoipHeadsetRefT::pMicDataCb, VoipHeadsetRefT::pStatusCb, VoipHeadsetRefT::refAsyncOp, LocalVoipUserT::refAudioDevsVector, LocalVoipUserT::refChatParticipant, VoipHeadsetRefT::refChatSession, VoipHeadsetRefT::refCurrentChatSessionState, VoipHeadsetRefT::refDecodersMap, VoipHeadsetRefT::refEncodersMap, VoipHeadsetRefT::refInboundQueuesMap, VoipHeadsetRefT::refNewChatSessionState, VoipHeadsetRefT::refPreBufStateMap, TRUE, VoipHeadsetRefT::uLastBystanderUpdate, LocalVoipUserT::user, VOIP_MAXCONNECT, VOIP_MAXLOCALUSERS, VOIP_MEMID, VOIP_NullUser, VoipDeserializeAudioDevice(), VOIPHEADSET_GAMECHAT_DEFAULT_ENCODING_QUALITY, VoipHeadsetDestroy(), VoipMemGroupQuery(), and VoipSerializeAudioDevice().
Referenced by VoipCommonStartup().
void VoipHeadsetDestroy (VoipHeadsetRefT * pHeadset)
Destroy the headset manager.
Parameters
*pHeadset - pointer to headset state
Version
05/24/2013 (mclouatre)
References VoipHeadsetRefT::AudioDeviceAddedToken, VoipHeadsetRefT::AudioDeviceChangedToken, VoipHeadsetRefT::AudioDeviceRemovedToken, VoipHeadsetRefT::bAsyncOpInProgress, VoipHeadsetRefT::crit, DirtyMemFree(), NetCritKill(), VoipHeadsetRefT::refAsyncOp, VoipHeadsetRefT::refCurrentChatSessionState, VoipHeadsetRefT::refDecodersMap, VoipHeadsetRefT::refEncodersMap, VoipHeadsetRefT::refInboundQueuesMap, VoipHeadsetRefT::refNewChatSessionState, VoipHeadsetRefT::refPreBufStateMap, VOIP_MEMID, and VoipMemGroupQuery().
Referenced by VoipCommonShutdown(), and VoipHeadsetCreate().
void VoipHeadsetProcess (VoipHeadsetRefT * pHeadset, uint32_t uFrameCount)
Headset process function.
Parameters
*pHeadset - pointer to headset state
uFrameCount - current frame count
Version
05/24/2013 (mclouatre)
References VoipHeadsetRefT::bHeadsetChanged, VoipHeadsetRefT::bKinectAvailabilityChanged, VoipHeadsetRefT::bSessionStateRefreshInProgress, FALSE, NetTick(), NetTickDiff, VoipHeadsetRefT::refCurrentChatSessionState, and VoipHeadsetRefT::uLastBystanderUpdate.
void VoipHeadsetReceiveVoiceDataCb (VoipUserT * pRemoteUsers, VoipMicrInfoT * pMicrInfo, uint8_t * pPacketData, void * pUserData)
Connectionlist callback to handle receiving a voice packet from a remote peer.
Parameters
*pRemoteUsers - user we're receiving the voice data from
*pMicrInfo - micr info from inbound packet
*pPacketData - pointer to beginning of data in packet payload
*pUserData - VoipHeadsetT ref
Version
05/24/2013 (mclouatre)
References VoipHeadsetRefT::aRemoteSharedUsers, RemoteSharedUserT::CaptureSoureId, NetPrintf, NetPrintfVerbose, VoipMicrInfoT::uNumSubPackets, RemoteSharedUserT::user, VoipMicrInfoT::uUserIndex, VOIP_MAX_LOW_LEVEL_CONNS, VOIP_SameUser, VOIP_SHARED_USER_INDEX, and VoipDeserializeAudioDevice().
Referenced by VoipCommonStartup().
void VoipHeadsetRegisterUserCb (VoipUserT * pRemoteUser, uint32_t bRegister, void * pUserData)
Connectionlist callback to register a new remote user with the 1st party voice system It will also register remote shared users with voipheadset internally.
Parameters
*pRemoteUser - user to register
bRegister - true=register, false=unregister
*pUserData - voipheadset module ref
Version
05/24/2013 (mclouatre)
References VoipHeadsetRefT::aRemoteSharedUsers, RemoteSharedUserT::CaptureSoureId, ds_stristr(), NetHash(), NetPrintf, NULL, VoipUserT::strUserId, RemoteSharedUserT::uEnablePlaybackFlag, RemoteSharedUserT::user, VOIP_CopyUser, VOIP_MAX_LOW_LEVEL_CONNS, VOIP_NullUser, VOIP_SameUser, and VoipDeserializeUser().
Referenced by VoipCommonStartup().
void VoipHeadsetSetVolume (VoipHeadsetRefT * pHeadset, int32_t iPlayVol, uint32_t iRecVol)
Sets play and record volume.
Parameters
*pHeadset - pointer to headset state
iPlayVol - play volume to set
iRecVol - record volume to set
Note
To not set a value, specify it as -1.
Version
05/24/2013 (mclouatre)
void VoipHeadsetSpkrCallback (VoipHeadsetRefT * pHeadset, VoipSpkrCallbackT * pCallback, void * pUserData)
Set speaker output callback.
Parameters
*pHeadset - headset module state
*pCallback - what to call when output data is available
*pUserData - user data for callback
Version
05/24/2013 (mclouatre)
References VoipHeadsetRefT::pSpkrCbUserData, and VoipHeadsetRefT::pSpkrDataCb.
Referenced by VoipSpkrCallback().
int32_t VoipHeadsetStatus (VoipHeadsetRefT * pHeadset, int32_t iSelect, int32_t iValue, void * pBuf, int32_t iBufSize)
Status function.
Parameters
*pHeadset - headset module state
iSelect - control selector
iValue - selector specific
*pBuf - buffer pointer
iBufSize - buffer size
Returns
int32_t - selector specific, or -1 if no such selector
Note
iSelect can be one of the following:
        'kine' - TRUE if kinect is in set of active capture source, FALSE otherwise
        'ruid' - return TRUE if the given remote user (pBuf) is registered with voipheadset, FALSE if not.
        'supd' - TRUE if chat session update is in progress
        'vlen' - TRUE if voice sub-packet have variable length, FALSE otherwise
Version
05/24/2013 (mclouatre)
References VoipHeadsetRefT::aRemoteSharedUsers, VoipHeadsetRefT::bKinectIsCapturing, VoipHeadsetRefT::bSessionStateRefreshInProgress, ds_snzprintf(), FALSE, VoipHeadsetRefT::refChatSession, VoipUserT::strUserId, TRUE, RemoteSharedUserT::user, VOIP_MAX_LOW_LEVEL_CONNS, and VOIP_SameUser.
Referenced by VoipCommonApplyChannelConfig(), and VoipCommonStatus().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:20