DirtySock: netconncommon.h File Reference
netconncommon.h File Reference
Cross-platform netconn data types and private functions.
#include "netconncommon.h"
Data Structures
struct NetConnIEAUserEventT
struct NetConnCommonRefT
Typedefs
typedef void(NetConnAddLocalUserCallbackT)(struct NetConnCommonRefT *pCommonRef, int32_t iLocalUserIndex, const EA::User::IEAUser *pIEAUser)
user event callback function prototype
typedef void(NetConnRemoveLocalUserCallbackT)(struct NetConnCommonRefT *pCommonRef, int32_t iLocalUserIndex, const EA::User::IEAUser *pIEAUser)
typedef enum
NetConnIEAUserEventTypeE NetConnIEAUserEventTypeE
typedef struct NetConnIEAUserEventT NetConnIEAUserEventT
typedef struct NetConnCommonRefT NetConnCommonRefT
Enumerations
enum NetConnIEAUserEventTypeE {
NETCONN_EVENT_IEAUSER_ADDED = 0,
NETCONN_EVENT_IEAUSER_REMOVED
}
Functions
NetConnCommonRefT * NetConnCommonGetRef (void)
Return current module reference.
void NetConnCommonShutdown (NetConnCommonRefT *pCommonRef)
Shutdown common functionality.
NetConnCommonRefT * NetConnCommonStartup (int32_t iNetConnRefSize, NetConnAddLocalUserCallbackT *pAddUserCb, NetConnRemoveLocalUserCallbackT *pRemoveUserCb)
Start up common functionality.
int32_t NetConnCommonAddLocalUser (int32_t iLocalUserIndex, const EA::User::IEAUser *pLocalUser)
Use this function to tell netconn about a newly detected local user on the local console.
int32_t NetConnCommonRemoveLocalUser (int32_t iLocalUserIndex, const EA::User::IEAUser *pLocalUser)
Use this function to tell netconn about a local user that no longer exists.
void NetConnCommonUpdateLocalUsers (NetConnCommonRefT *pCommonRef)
Update our internally maintained array of NetConnUsers from the array of IEAUsers.
Detailed Description
Cross-platform netconn data types and private functions.
Attention
Copyright (c) 2014 Electronic Arts Inc.
Version
05/21/2009 (mclouatre) First Version
Typedef Documentation
typedef void(NetConnAddLocalUserCallbackT)(struct NetConnCommonRefT *pCommonRef, int32_t iLocalUserIndex, const EA::User::IEAUser *pIEAUser)
user event callback function prototype
typedef struct NetConnCommonRefT NetConnCommonRefT
typedef struct NetConnIEAUserEventT NetConnIEAUserEventT
typedef enum NetConnIEAUserEventTypeE NetConnIEAUserEventTypeE
typedef void(NetConnRemoveLocalUserCallbackT)(struct NetConnCommonRefT *pCommonRef, int32_t iLocalUserIndex, const EA::User::IEAUser *pIEAUser)
Enumeration Type Documentation
enum NetConnIEAUserEventTypeE
Enumerator
NETCONN_EVENT_IEAUSER_ADDED
NETCONN_EVENT_IEAUSER_REMOVED
Function Documentation
int32_t NetConnCommonAddLocalUser (int32_t iLocalUserIndex, const EA::User::IEAUser * pLocalUser)
Use this function to tell netconn about a newly detected local user on the local console.
Parameters
iLocalUserIndex - index at which DirtySDK needs to insert this user it its internal user array
pLocalUser - pointer to associated IEAUser
Returns
int32_t - 0 for success; negative for error
Version
01/16/2014 (mclouatre)
References NETCONN_EVENT_IEAUSER_ADDED, NETCONN_MAXLOCALUSERS, and NetPrintf.
Referenced by NetConnAddLocalUser().
NetConnCommonRefT* NetConnCommonGetRef (void)
Return current module reference.
Returns
NetConnCommonRefT * - reference pointer, or NULL if the module is not active
Version
05/21/2014 (mclouatre)
Referenced by NetConnConnect(), NetConnControl(), NetConnDisconnect(), NetConnQuery(), NetConnRegisterNpStateCallback(), NetConnShutdown(), NetConnStartup(), and NetConnStatus().
int32_t NetConnCommonRemoveLocalUser (int32_t iLocalUserIndex, const EA::User::IEAUser * pLocalUser)
Use this function to tell netconn about a local user that no longer exists.
Parameters
iLocalUserIndex - index in the internal DirtySDK user array at which the user needs to be cleared pass -1 when the index is unknown and a lookup will be done
pLocalUser - pointer to associated IEAUser
Returns
int32_t - 0 for success; negative for error
Version
01/16/2014 (mclouatre)
References NetConnCommonRefT::crit, NETCONN_EVENT_IEAUSER_REMOVED, NETCONN_MAXLOCALUSERS, NetConnStatus(), NetCritEnter(), NetCritLeave(), and NetPrintf.
Referenced by NetConnRemoveLocalUser().
void NetConnCommonShutdown (NetConnCommonRefT * pCommonRef)
Shutdown common functionality.
Parameters
*pCommonRef - common module state
Version
05/21/2014 (mclouatre)
References NetConnCommonRefT::crit, DirtyMemFree(), NetConnCommonRefT::iMemGroup, NETCONN_MEMID, NetCritKill(), and NetConnCommonRefT::pMemGroupUserData.
Referenced by NetConnShutdown().
NetConnCommonRefT* NetConnCommonStartup (int32_t iNetConnRefSize, NetConnAddLocalUserCallbackT * pAddUserCb, NetConnRemoveLocalUserCallbackT * pRemoveUserCb)
Start up common functionality.
Parameters
iNetConnRefSize - size of netconn ref to allocate
*pAddUserCb - added user event handler
*pRemoveUserCb - removed user event handler
Returns
NetConnCommonRefT * - netconn ref if successful; else NULL
Version
05/21/2014 (mclouatre)
References NetConnCommonRefT::crit, DirtyMemAlloc(), DirtyMemGroupQuery(), NetConnCommonRefT::iMemGroup, NETCONN_MEMID, NetCritInit(), NetPrintf, NetConnCommonRefT::pAddUserCb, NetConnCommonRefT::pMemGroupUserData, and NetConnCommonRefT::pRemoveUserCb.
Referenced by NetConnStartup().
void NetConnCommonUpdateLocalUsers (NetConnCommonRefT * pCommonRef)
Update our internally maintained array of NetConnUsers from the array of IEAUsers.
Parameters
*pCommonRef - NetConnRefT reference
Version
01/18/2014 (mclouatre)
References NetConnCommonRefT::crit, NetConnIEAUserEventT::eEvent, NetConnCommonRefT::iDebugLevel, NetConnIEAUserEventT::iLocalUserIndex, NETCONN_EVENT_IEAUSER_ADDED, NetCritEnter(), NetCritLeave(), NetPrintfVerbose, NetConnCommonRefT::pAddUserCb, NetConnIEAUserEventT::pIEAUser, NetConnCommonRefT::pIEAUserEventList, NetConnCommonRefT::pIEAUserFreeEventList, and NetConnCommonRefT::pRemoveUserCb.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:13