DirtySock: HLBudApi
HLBudApi
Friend
Macros
#define HLB_MSGINJECT_PARMS_TAG "PARMS"
Tag used for secret parms message injection.
#define HLB_FLAG_GAME_INVITE_SENT BUDDY_FLAG_GAME_INVITE_SENT
Cross Game invite can have many states..
#define HLB_FLAG_GAME_INVITE_RECEIVED BUDDY_FLAG_GAME_INVITE_RECEIVED
#define HLB_FLAG_GAME_INVITE_ACCEPTED BUDDY_FLAG_GAME_INVITE_ACCEPTED
#define HLB_FLAG_GAME_INVITE_READY BUDDY_FLAG_GAME_INVITE_READY
#define HLB_FLAG_GAME_INVITE_TIMEOUT BUDDY_FLAG_GAME_INVITE_TIMEOUT
#define HLB_ERROR_NONE BUDDY_ERROR_NONE
status codes and last op status etc.
#define HLB_ERROR_PEND BUDDY_ERROR_PEND
command is still pending
#define HLB_ERROR_NOTUSER BUDDY_ERROR_NOTUSER
not a user
#define HLB_ERROR_BADPARM BUDDY_ERROR_BADPARM
bad parameter
#define HLB_ERROR_OFFLINE BUDDY_ERROR_OFFLINE
server is offline
#define HLB_ERROR_MISSING BUDDY_ERROR_MISSING
item not found etc.
#define HLB_ERROR_FULL BUDDY_ERROR_FULL
no space, hit max etc.
#define HLB_ERROR_MEMORY BUDDY_ERROR_MEMORY
out of memory, possibly user alloc space full?
#define HLB_ERROR_UNSUPPORTED BUDDY_ERROR_UNSUPPORTED
#define HLB_ERROR_SELF BUDDY_ERROR_SELF
cannot add yourself as buddy.
#define HLB_ERROR_BLOCKED BUDDY_ERROR_BLOCKED
cannot invite-he has blocked you.
#define HLB_ERROR_PASSWORD -101
#define HLB_ERROR_HACK -102
#define HLB_ERROR_INTERNAL -103
#define HLB_ERROR_BAD_RESOURCE -104
#define HLB_ERROR_NETWORK -105
#define HLB_ERROR_AUTH -106
#define HLB_ERROR_TIMEOUT -107
#define HLB_ERROR_CANCEL -108
operation was cancelled.
#define HLB_ERROR_NOOP -109
there is no operation –
#define HLB_ERROR_USER_STATE -110
some invite answers need right wannabe state.
#define HLB_ERROR_UNKNOWN -999
unexpected..
#define HLB_MAX_PERM_BUDDIES 100
max number of permanent buddies.
#define HLB_MAX_BLOCKED_BUDDIES 50
max number of buddies blocked.
#define HLB_MAX_TEMP_BUDDIES 10
max number of temporary buddies.
#define HLB_MAX_MESSAGES_ALLOWED 100
total max messages allowed – to keep memory constrained
#define HLB_CONNECT_TO 60
#define HLB_OP_TO 90
#define HLB_XGAME_READY_TO 600
seconds buddy has, after accept Xgame, to show up in this game.
#define HLB_GAME_STATE_LEN 32
X limit to size of game invite game state.
#define HLB_NO_CHANGES -1
tell if buddies or msg from buddy changed or not. -1 cause 0 is valid.
#define HLB_CHANGED 99
#define HLB_PRESENCE_LEN 100
how big a presence string
#define HLB_SESSION_ID_LEN BUDDY_SESSION_ID_LEN
how big game invite session id string
#define HLB_GROUP_ID 1
Only one group needed to send messages to.
#define HLB_MSG_TYPE_CHAT BUDDY_MSG_CHAT
How is Chat messages encoded in line protocol.
#define HLB_MSG_TYPE_INJECT 'injc'
#define HLB_CHAT_KIND_CHAT 'chat'
kind of chat message –just chat
#define HLB_CHAT_KIND_ADMIN 'admn'
chat message –a special from eaadmin..
#define HLB_ABSOLUTE_MAX_MSG_LEN 200
maximum message length.
#define HLB_BUDDY_NAME_LEN 32
maximum size of buddy name.
#define HLB_MSG_KEEP_SECS 259200
Number of seconds the server will wait to deliver the message.
Typedefs
typedef enum HLBStatE HLBStatE
State of a Buddy – same as BUDDY_STAT.
typedef enum HLBTempBuddyTypeE HLBTempBuddyTypeE
Kinds of Tempory Buddies. Any buddy can be many, or none of these..
typedef enum HLBInviteAnswerE HLBInviteAnswerE
Invite responses. Apply to buddy (wannabe) requests and to (cross) game invites.
typedef enum HLBMsgInjectE HLBMsgInjectE
Flags to control what features on injecting a msg –see HLBMsgListMsgInject.
typedef enum HLBConnectStateE HLBConnectStateE
State of connecting to server–.
typedef enum HLBVOIPE HLBVOIPE
Messages from Server –TBD.
typedef enum HLBOpE HLBOpE
Possible Async operations...
typedef struct HLBApiRefT HLBApiRefT
Reference to this API – private.
typedef struct HLBBudT HLBBudT
typedef void(HLBOpCallbackT)(HLBApiRefT *pRef, int32_t op, int32_t opStatus, void *pContext)
typedef void(HLBMsgCallbackT)(HLBApiRefT *pRef, BuddyApiMsgT *pMsg, void *pContext)
typedef void(HLBBudActionCallbackT)(HLBApiRefT *pRef, HLBBudT *pBuddy, int32_t eAction, void *pContext)
typedef void(HLBPresenceCallbackT)(HLBApiRefT *pRef, HLBBudT *pBuddy, HLBStatE eOldState, void *pContext)
Callback for when Buddy's presence changes–either state or text string can change.
typedef int32_t(HLBRosterSortFunctionT)(void *pSortref, int32_t iSortcon, void *pRecptr1, void *pRecptr2)
Function to register for custom sort. Use pRecptr1->pUserRef to get to the buddy.
Enumerations
enum HLBStatE {
HLB_STAT_UNDEFINED = BUDDY_STAT_UNDEFINED,
HLB_STAT_DISC = BUDDY_STAT_DISC,
HLB_STAT_CHAT = BUDDY_STAT_CHAT,
HLB_STAT_AWAY = BUDDY_STAT_AWAY,
HLB_STAT_XA = BUDDY_STAT_XA,
HLB_STAT_DND = BUDDY_STAT_DND,
HLB_STAT_PASSIVE = BUDDY_STAT_PASS
}
State of a Buddy – same as BUDDY_STAT.
enum HLBTempBuddyTypeE {
HLB_TEMPBUDDYTYPE_MESG = (1<<0),
HLB_TEMPBUDDYTYPE_CHAL = (1<<1),
HLB_TEMPBUDDYTYPE_TOUR = (1<<2),
HLB_TEMPBUDDYTYPE_VOIP = (1<<3),
HLB_TEMPBUDDYTYPE_CUST1 = (1<<4),
HLB_TEMPBUDDYTYPE_CUST2 = (1<<5),
HLB_TEMPBUDDYTYPE_SESSION = (1<<6),
HLB_TEMPBUDDYTYPE_MAX = (1<<7)
}
Kinds of Tempory Buddies. Any buddy can be many, or none of these..
enum HLBInviteAnswerE {
HLB_INVITEANSWER_ACCEPT =BUDDY_INVITE_RESPONSE_ACCEPT,
HLB_INVITEANSWER_REJECT =BUDDY_INVITE_RESPONSE_REJECT,
HLB_INVITEANSWER_REVOKE =BUDDY_INVITE_RESPONSE_REVOKE,
HLB_INVITEANSWER_BLOCK =BUDDY_INVITE_RESPONSE_BLOCK,
HLB_INVITEANSWER_REMOVE =BUDDY_INVITE_RESPONSE_REMOVE,
HLB_INVITEANSWER_TIMEOUT =BUDDY_INVITE_RESPONSE_TIMEOUT,
HLB_INVITEANSWER_UNKNOWN =BUDDY_INVITE_RESPONSE_UNKNOWN_MAX
}
Invite responses. Apply to buddy (wannabe) requests and to (cross) game invites.
enum HLBMsgInjectE { HLB_MSGINJECT_AS_ADMIN_MSG = 1 }
Flags to control what features on injecting a msg –see HLBMsgListMsgInject.
enum HLBConnectStateE {
HLB_CS_Disconnected,
HLB_CS_Connecting,
HLB_CS_Connected,
HLB_CS_ErrorAuth,
HLB_CS_ErrorUser,
HLB_CS_ErrorNetwork,
HLB_CS_ErrorServer,
HLB_CS_ErrorTimeout
}
State of connecting to server–.
enum HLBVOIPE {
HLB_VOIP_NONE = 0,
HLB_VOIP_PLUGGED,
HLB_VOIP_TALKING
}
Messages from Server –TBD.
enum HLBOpE {
HLB_OP_NONE =0,
HLB_OP_CONNECT =1,
HLB_OP_ADD_BUD,
HLB_OP_DELETE_BUD,
HLB_OP_BLOCK_BUD,
HLB_OP_LOAD,
HLB_OP_FIND_USERS,
HLB_OP_SEND_MSG,
HLB_OP_SET_FORWARDING,
HLB_OP_INVITE,
HLB_OP_ANY
}
Possible Async operations...
Functions
DIRTYCODE_API char * HLBBudGetName (HLBBudT *pBuddy)
Return screen/persona name of this buddy.
DIRTYCODE_API uint64_t HLBBudGetXenonXUID (HLBBudT *pBuddy)
DIRTYCODE_API uint32_t HLBBudGetGameInviteFlags (HLBBudT *pBuddy)
DIRTYCODE_API int32_t HLBBudGetVOIPState (HLBBudT *pBuddy)
Return the Voice Over IP state of the buddy – plugged in or not etc.
DIRTYCODE_API int32_t HLBBudCanVoiceChat (HLBBudT *pBuddy)
Indicates if buddy is ready to be talked to. i.e. plugged in, and in same product etc.
DIRTYCODE_API int32_t HLBBudIsTemporary (HLBBudT *pBuddy)
Indicates if the buddy is not persistent. Could be someone who sent me a message and is not on my buddy or ignore list.
DIRTYCODE_API int32_t HLBBudIsBlocked (HLBBudT *pBuddy)
Indicates if messages from this 'buddy' is ignored or blocked by the server.
DIRTYCODE_API int32_t HLBBudIsRealBuddy (HLBBudT *pBuddy)
Indicates if the buddy is really a buddy – ie. not someone on the list due to being blocked, or added temporarily.
DIRTYCODE_API int32_t HLBBudIsWannaBeMyBuddy (HLBBudT *pBuddy)
DIRTYCODE_API int32_t HLBBudIsIWannaBeHisBuddy (HLBBudT *pBuddy)
DIRTYCODE_API char * HLBBudGetTitle (HLBBudT *pBuddy)
Return Title played name by this buddy, based on language set in Presence.
DIRTYCODE_API int32_t HLBBudTempBuddyIs (HLBBudT *pBuddy, int32_t tempBuddyType)
Is this buddy one of these temp buddy kinds – can be true for permanent buddies too.
DIRTYCODE_API int32_t HLBBudIsInGroup (HLBBudT *pBuddy)
Indicates if this buddy a member of group that's been set up to send msg. See HLBListAddToGroup.
DIRTYCODE_API int32_t HLBBudGetState (HLBBudT *pBuddy)
Return buddy's state, such as is online, disconnected, in game etc. – see HLB_Buddy_State_Enum.
DIRTYCODE_API int32_t HLBBudIsPassive (HLBBudT *pBuddy)
Indicate if buddy is passive i.e. is online but playing a game.
DIRTYCODE_API int32_t HLBBudIsAvailableForChat (HLBBudT *pBuddy)
Indicate if buddy is online and available for chat.
DIRTYCODE_API int32_t HLBBudIsSameProduct (HLBBudT *pBuddy)
Indicate if buddy is logged into same game as I am. Buddy must be online.
DIRTYCODE_API int32_t HLBBudIsJoinable (HLBBudT *pBuddy)
Indicates if buddy can be "joined" (aka found and gone to) in an Xbox game. Checks the Joinable bit in Xbox Presence.
DIRTYCODE_API int32_t HLBBudJoinGame (HLBBudT *pBuddy, HLBOpCallbackT *cb, void *pContext)
DIRTYCODE_API int32_t HLBBudCanPlayMyGame (HLBBudT *pBuddy)
DIRTYCODE_API int32_t HLBBudIsNoReplyBud (HLBBudT *pBuddy)
Indicate if 'special' temp (i.e.admin) buddy who WONT accept messages or invites etc. Generally means I got a message from a "system" user, and it wont take replies.
DIRTYCODE_API void HLBBudGetPresence (HLBBudT *pBuddy, char *presence)
Get the buddy's product presence string, as set by the other client. Will be converted to 8 bit from utf8, if a translation table is registered.
DIRTYCODE_API void HLBBudGetPresenceExtra (HLBBudT *pBuddy, char *strExtraPres, int32_t iStrSize)
Get the buddy's extra presence string, as set by the other client. W Will be empty if product is not the same.
DIRTYCODE_API int32_t HLBApiPresenceJoinable (HLBApiRefT *pApiRef, int32_t bOn, int32_t bSendImmediate)
Set or reset joinable status in presence;.
DIRTYCODE_API BuddyApiMsgT * HLBMsgListGetMsgByIndex (HLBBudT *pBuddy, int32_t index, int32_t read)
Get message at index position, if read is true, mark message as read.
DIRTYCODE_API BuddyApiMsgT * HLBMsgListGetFirstUnreadMsg (HLBBudT *pBuddy, int32_t startPos, int32_t read)
Return unread message from buddy, starting from a start position.
DIRTYCODE_API int32_t HLBMsgListMsgInject (HLBApiRefT *pApiRef, int32_t iKind, const char *pSenderName, const char *pMsgBody, const char *pMsgParams, uint32_t uMsgInjectFlags, uint32_t uTime)
Inject a message, as if from some buddy. Message callbacks etc will be called. If user is not on buddy list, he will be added as "temp" buddy. Convenience function, so client can inject lobby control and other messages, and use same "buddy" UI to show such messages.
DIRTYCODE_API void HLBMsgListGetMsgText (HLBApiRefT *pApiRef, BuddyApiMsgT *pMsg, char *strText, int32_t iLen)
Return the BODY of message, text, converting to 8 bit chars from utf8 if needed.
DIRTYCODE_API int32_t HLBMsgListGetUnreadCount (HLBBudT *pBuddy)
Return count of unread messages from buddy.
DIRTYCODE_API int32_t HLBMsgListGetTotalCount (HLBBudT *pBuddy)
Return total count of messages, both read and unread, from buddy.
DIRTYCODE_API void HLBMsgListDelete (HLBBudT *pBuddy, int32_t index)
Delete message at (zero based) index position.
DIRTYCODE_API void HLBMsgListDeleteAll (HLBBudT *pBuddy, int32_t bZapReadOnly)
Delete all, or just read msgs from this buddy. Local. If bZapReadOnly is true will delete just read msgs.
DIRTYCODE_API HLBBudT * HLBListGetBuddyByName (HLBApiRefT *pApiRef, const char *name)
Get a buddy from the buddy list (roster) by name. Exact match.
DIRTYCODE_API HLBBudT * HLBListGetBuddyByIndex (HLBApiRefT *pApiRef, int32_t index)
Get a Buddy by index into the buddy list.
DIRTYCODE_API int32_t HLBListGetIndexByName (HLBApiRefT *pApiRef, const char *name)
Given a buddy name, find the index into the list.
DIRTYCODE_API int32_t HLBListGetBuddyCountByFlags (HLBApiRefT *pApiRef, uint32_t uTypeFlag)
Get count of buddies that match the buddy (type) flags, like BUDDY, INVITE_SENT etc. .e.g. To count all permanent, but not blocked, buddies, call with: flag=BUDDY_FLAG_BUDDY|BUDDY_FLAG_BUD_REQ_RECEIVED |BUDDY_FLAG_BUD_REQ_SENT.
DIRTYCODE_API int32_t HLBListGetBuddyCount (HLBApiRefT *pApiRef)
Get count of all buddies in the Roster. Also see HLBListGetBuddyCountByFlags.
DIRTYCODE_API int32_t HLBListBlockBuddy (HLBApiRefT *pApiRef, const char *name, HLBOpCallbackT *cb, void *pContext)
Ask that this buddy be ignored. Server will no longer send messages from this buddy.
DIRTYCODE_API int32_t HLBListUnBlockBuddy (HLBApiRefT *pApiRef, const char *name, HLBOpCallbackT *cb, void *pContext)
No longer Ignore this buddy. Server will no longer block messages from this buddy.
DIRTYCODE_API int32_t HLBListCancelAllInvites (HLBApiRefT *pApiRef, const char *pName)
add a message from a buddy.
DIRTYCODE_API int32_t HLBListInviteBuddy (HLBApiRefT *pApiRef, const char *name, HLBOpCallbackT *cb, void *pContext)
Ask this use to be my buddy. Async. Will be added to my IWannabeHisBuddy list.
DIRTYCODE_API int32_t HLBReceiveMsgAttachment (HLBApiRefT *pHLBApi, void *pContext)
DIRTYCODE_API int32_t HLBListAnswerInvite (HLBApiRefT *pApiRef, const char *name, int32_t iInviteAction, HLBOpCallbackT *cb, void *pContext)
Respond to an invite or change state of invite I sent, –applies to wannabe buddy invites.
DIRTYCODE_API int32_t HLBListAnswerGameInvite (HLBApiRefT *pApiRef, const char *name, int32_t iInviteAction, HLBOpCallbackT *cb, void *pContext)
Respond to an invite or change state of invite i sent, –applies to game invites.
DIRTYCODE_API int32_t HLBListCancelGameInvite (HLBApiRefT *pApiRef, HLBOpCallbackT *cb, void *pContext)
Cancel any game invites I sent – also see HLBListAnswerGameInvite.
DIRTYCODE_API int32_t HLBListGameInviteBuddy (HLBApiRefT *pApiRef, const char *name, const char *pGameInviteState, HLBOpCallbackT *cb, void *pContext)
DIRTYCODE_API int32_t HLBListUnMakeBuddy (HLBApiRefT *pApiRef, const char *name, HLBOpCallbackT *cb, void *pContext)
Ensure user is no longer a buddy of mine, by clearing "buddy" flag. Server operation. Will remain on buddy list if other (eg. temp or Ignore flags are set).
DIRTYCODE_API int32_t HLBListFlagTempBuddy (HLBApiRefT *pApiRef, const char *name, int32_t tempBuddyType)
Add as a tourney or other temp buddy for convenience. Sync, local call. If buddy already exists as a "permanent" buddy, then flag is set, Otherwise, buddy is added to the list as a "temp" buddy.
DIRTYCODE_API int32_t HLBListUnFlagTempBuddy (HLBApiRefT *pApiRef, const char *name, int32_t tempBuddyType)
Clear the particular temp buddy flag if set. Does not remove from list – client must explicitly deleteAdd as a tourney or other temp buddy for convenience. Sync, local call.
DIRTYCODE_API int32_t HLBListDeleteTempBuddy (HLBApiRefT *pApiRef, const char *name)
Explicitly delete this temp buddy. Will ignore request if buddy is permanent. local call.
DIRTYCODE_API void HLBListSetSortFunction (HLBApiRefT *pApiRef, HLBRosterSortFunctionT *sortCallbackFunction)
Sort function to be set if client wants custom sort of buddy list – However API will have a reasonable default sort.
DIRTYCODE_API int32_t HLBListSort (HLBApiRefT *pApiRef)
Sort list of buddies. Once sorted, list will be frozen until re-sorted, or provide a freeze() call.
DIRTYCODE_API void HLBListDisableSorting (HLBApiRefT *pApiRef)
DIRTYCODE_API int32_t HLBListChanged (HLBApiRefT *pApiRef)
Has the list of buddies or their presence changed? Will clear the flag. Local.
DIRTYCODE_API int32_t HLBListBuddyWithMsg (HLBApiRefT *pApiRef)
Has messages from any buddies changed? Returns buddy index, or HLB_NO_CHANGES.
DIRTYCODE_API int32_t HLBListDeleteNoMsgTempBuddies (HLBApiRefT *pApiRef)
DIRTYCODE_API int32_t HLBListAddToGroup (HLBApiRefT *pApiRef, const char *buddyName)
On closing screen, need to clear temp buddies w/o messages etc..
DIRTYCODE_API int32_t HLBListRemoveFromGroup (HLBApiRefT *pApiRef, const char *buddyName)
Remove this buddy from the group Iam going to send messages to.
DIRTYCODE_API int32_t HLBListClearGroup (HLBApiRefT *pApiRef)
Clear group of users so I can re-use it.
DIRTYCODE_API int32_t HLBListSendMsgToGroup (HLBApiRefT *pApiRef, int32_t msgType, const char *msg, int32_t bClearGroup, HLBOpCallbackT *cb, void *pContext)
Send message to group of users I created earlier. Reset group if clearGroup is set.
DIRTYCODE_API int32_t HLBListSendChatMsg (HLBApiRefT *pApiRef, const char *name, const char *body, HLBOpCallbackT *cb, void *pContext)
Send an actual chat message.
DIRTYCODE_API HLBApiRefT * HLBApiCreate (const char *pProduct, const char *pRelease, int32_t iRefMemGroup, void *pRefMemGroupUserData)
Create an instance of the High Level Buddy API.
DIRTYCODE_API HLBApiRefT * HLBApiCreate2 (BuddyMemAllocT *pAlloc, BuddyMemFreeT *pFree, const char *pProduct, const char *pRelease, int32_t iRefMemGroup, void *pRefMemGroupUserData)
Create HL Buddy Api, overriding the default memory alloc/free functions.
DIRTYCODE_API void HLBApiSetDebugFunction (HLBApiRefT *pApiRef, void *pDebugData, void(*pDebugProc)(void *pData, const char *pText))
Set a callback to write out debug messages within API.
DIRTYCODE_API void HLBApiOverrideConstants (HLBApiRefT *pApiRef, int32_t bNoTextSupport, int32_t connect_timeout, int32_t op_timeout, int32_t max_perm_buddies, int32_t max_temp_buddies, int32_t msgs_per_perm_buddy, int32_t msgs_per_temp_buddy, int32_t max_msg_len, int32_t bTrackSendMsgInOpState, int32_t iGameInviteAccept_timeout)
Application may override default constants. -1 leaves it as default. Only valid before HLBApiConfig is called.
DIRTYCODE_API void HLBApiOverrideMaxMessagesPerBuddy (HLBApiRefT *pApiRef, int32_t max_msgs_per_perm_buddy)
Application may override default for max msg per buddy – FIFA emergency.
DIRTYCODE_API void HLBApiOverrideXblIsSameProductCheck (HLBApiRefT *pApiRef, int32_t bDontUseXBLSameTitleIdCheck)
Set to 1 if on XBL and NTSC cannot play each other, but, have same title id.
DIRTYCODE_API int32_t HLBApiInitialize (HLBApiRefT *pApiRef, const char *prodid, uint32_t uLocality)
Configure and initialize any data structures in the API, and set some basic product and presence info.
DIRTYCODE_API int32_t HLBApiConnect (HLBApiRefT *pApiRef, const char *pServer, int32_t port, const char *key, const char *pRsrc)
Connect to buddy server. Note that if connect fails for network or server-unavailability, we will keep retrying connect within the connect timeout period.
DIRTYCODE_API int32_t HLBApiGetConnectState (HLBApiRefT *pApiRef)
Get state of connection to the server, returns int, but see HLBConnectState_Enum.
DIRTYCODE_API int32_t HLBApiRegisterConnectCallback (HLBApiRefT *pApiRef, HLBOpCallbackT *pMsgCallback, void *pAppData)
DIRTYCODE_API int32_t HLBApiRegisterMsgAttachmentCallback (HLBApiRefT *pApiRef, HLBBudActionCallbackT *pActionCallback, void *pAppData)
DIRTYCODE_API int32_t HLBApiRegisterGameInviteCallback (HLBApiRefT *pApiRef, HLBBudActionCallbackT *pActionCallback, void *pAppData)
Register callback for any game invite status change on buddies.
DIRTYCODE_API int32_t HLBApiRegisterBuddyPresenceCallback (HLBApiRefT *pApiRef, HLBPresenceCallbackT *pListCallback, void *pAppData)
Optional callback –Informe caller when buddy presence changes –state or text.
DIRTYCODE_API void HLBApiDisconnect (HLBApiRefT *pApiRef)
Disconnect from buddy server.
DIRTYCODE_API void HLBApiDestroy (HLBApiRefT *pState)
Destroy this API and any memory held by it. Also destroy lower level BuddyApi held by this.
DIRTYCODE_API void HLBApiUpdate (HLBApiRefT *pApiRef)
Give API and api below some time to process. Must be called periodically by client.
DIRTYCODE_API int32_t HLBApiSuspend (HLBApiRefT *pApiRef)
Suspend buddy api, cleanup and put buddy in passive state. Used when want to go into game ..
DIRTYCODE_API void * HLBApiResume (HLBApiRefT *pApiRef)
Refresh roster and put buddy in online state – used on return from game.
DIRTYCODE_API int32_t HLBApiGetLastOpStatus (HLBApiRefT *pApiRef)
State of last operation –implies only one operation at a time. If operation is done (i.e. not pending), this will CLEAR the state.
DIRTYCODE_API void HLBApiCancelOp (HLBApiRefT *pApiRef)
Cancel any pending operations –clear pending state unconditionally. Will call operation callbacks with state of HLB_ERROR_CANCEL.
DIRTYCODE_API int32_t HLBApiFindUsers (HLBApiRefT *pApiRef, const char *name, HLBOpCallbackT *pOpCallback, void *pAppData)
Request a search of users, of names starting with the pUserPattern. Min 3 chars.
DIRTYCODE_API BuddyApiUserT * HLBApiUserFound (HLBApiRefT *pApiRef, int32_t iItem)
Return users found from FindUser request. Allows client to iterate list of returned users. Should be called after callback from BuddyApiFindUsers has returned with a succes status.
DIRTYCODE_API int32_t HLBApiRegisterNewMsgCallback (HLBApiRefT *pApiRef, HLBMsgCallbackT *pMsgCallback, void *pAppData)
Register callback for new (chat) messages. Callback will be called whenever a chat message arrives. Note that clients can optionally use polling instead of this callback mechanism.
DIRTYCODE_API int32_t HLBApiRegisterBuddyChangeCallback (HLBApiRefT *pApiRef, HLBOpCallbackT *pMsgCallback, void *pAppData)
Register callback for any buddy list (aka roster) change.
DIRTYCODE_API int32_t HLBApiPresenceOffline (HLBApiRefT *pApiRef, int32_t bOnOff)
Set presence as "Offline" if OnOff is true.Reset if bOnOff false. Not Persistent.
DIRTYCODE_API void HLBApiPresenceDiff (HLBApiRefT *pApiRef, const char *globalPres)
Set presence string for other products.
DIRTYCODE_API void HLBApiPresenceSame (HLBApiRefT *pApiRef, int32_t iPresState, const char *strSamePres)
Set presence my presence state and presence string for this product.
DIRTYCODE_API void HLBApiPresenceExtra (HLBApiRefT *pApiRef, const char *strExtraPres)
DIRTYCODE_API int32_t HLBApiPresenceSend (HLBApiRefT *pApiRef, int32_t iBuddyState, int32_t VOIPState, const char *gamePres, int32_t waitMsecs)
Send presence msg, with string for this game and others.
DIRTYCODE_API int32_t HLBApiPresenceVOIPSend (HLBApiRefT *pApiRef, int32_t iVOIPState)
Set and send presence related to this user's voip (i.e. headset) status. Must be online.
DIRTYCODE_API int32_t HLBApiPresenceSendSetPresence (HLBApiRefT *pApiRef)
Send to server, previously set presence state and presence strings.
DIRTYCODE_API int32_t HLBApiSetEmailForwarding (HLBApiRefT *pApiRef, int32_t bEnable, const char *strEmail, HLBOpCallbackT *pOpCallback, void *pCalldata)
Turn email forwarding on or off, and set email address.
DIRTYCODE_API int32_t HLBApiGetEmailForwarding (HLBApiRefT *pApiRef, int32_t *bEnable, char *strEmail)
Get email forwarding state, if already loaded from server.
DIRTYCODE_API int32_t HLBApiGetForwarding (HLBApiRefT *pApiRef, unsigned *puForwardingFlags, char *strEmail)
DIRTYCODE_API void HLBApiSetUtf8TransTbl (HLBApiRefT *pApiRef, Utf8TransTblT *pTransTbl)
Set if want api to translate utf8 chars to 8 bit characters in Presence, and Message Text.
DIRTYCODE_API int32_t HLBApiGetMyTitleName (HLBApiRefT *pApiRef, const char *pLang, const int32_t iBufSize, char *pTitleName)
Get the "Official" title name for this game. pLang ignored for now–defaults to English.
DIRTYCODE_API int32_t HLBApiGetTitleName (HLBApiRefT *pApiRef, const uint32_t uTitleId, const int32_t iBufSize, char *pTitleName)
Get the " Official" Xbox title name for a given title, based on my locale-language.
DIRTYCODE_API int32_t HLBListSetGameInviteSessionID (HLBApiRefT *pApiRef, const char *sSessionID)
DIRTYCODE_API int32_t HLBListGetGameSessionID (HLBApiRefT *pApiRef, const char *name, char *sSessionID, const int32_t iBufSize)
DIRTYCODE_API int32_t HLBApiSetUserIndex (HLBApiRefT *pApiRef, int32_t iEnumeratorIndex)
DIRTYCODE_API int32_t HLBApiGetUserIndex (HLBApiRefT *pApiRef)
Detailed Description
Macro Definition Documentation
#define HLB_ABSOLUTE_MAX_MSG_LEN 200
maximum message length.
Referenced by HLBApiOverrideConstants(), and HLBListSendChatMsg().
#define HLB_BUDDY_NAME_LEN 32
maximum size of buddy name.
#define HLB_CHANGED 99
Referenced by HLBListChanged().
#define HLB_CHAT_KIND_ADMIN 'admn'
chat message –a special from eaadmin..
#define HLB_CHAT_KIND_CHAT 'chat'
kind of chat message –just chat
#define HLB_CONNECT_TO 60
#define HLB_ERROR_AUTH -106
#define HLB_ERROR_BAD_RESOURCE -104
#define HLB_ERROR_BADPARM BUDDY_ERROR_BADPARM
bad parameter
Referenced by HLBApiConnect(), and HLBApiRegisterConnectCallback().
#define HLB_ERROR_BLOCKED BUDDY_ERROR_BLOCKED
cannot invite-he has blocked you.
Referenced by HLBMsgListMsgInject().
#define HLB_ERROR_CANCEL -108
operation was cancelled.
Referenced by HLBApiCancelOp().
#define HLB_ERROR_FULL BUDDY_ERROR_FULL
no space, hit max etc.
Referenced by HLBApiRegisterBuddyChangeCallback(), HLBApiRegisterBuddyPresenceCallback(), HLBApiRegisterGameInviteCallback(), HLBApiRegisterNewMsgCallback(), HLBListAnswerInvite(), and HLBListInviteBuddy().
#define HLB_ERROR_HACK -102
#define HLB_ERROR_INTERNAL -103
#define HLB_ERROR_MEMORY BUDDY_ERROR_MEMORY
out of memory, possibly user alloc space full?
#define HLB_ERROR_MISSING BUDDY_ERROR_MISSING
item not found etc.
Referenced by HLBApiInitialize(), HLBBudJoinGame(), HLBListAddToGroup(), HLBListAnswerGameInvite(), HLBListAnswerInvite(), HLBListFlagTempBuddy(), HLBListGameInviteBuddy(), HLBListGetIndexByName(), HLBListRemoveFromGroup(), and HLBListSendMsgToGroup().
#define HLB_ERROR_NETWORK -105
#define HLB_ERROR_NONE BUDDY_ERROR_NONE
status codes and last op status etc.
no error
Referenced by HLBApiGetEmailForwarding(), HLBApiPresenceJoinable(), HLBApiPresenceSend(), HLBApiPresenceSendSetPresence(), HLBApiPresenceVOIPSend(), HLBApiRegisterBuddyChangeCallback(), HLBApiRegisterBuddyPresenceCallback(), HLBApiRegisterConnectCallback(), HLBApiRegisterGameInviteCallback(), HLBApiRegisterNewMsgCallback(), HLBApiResume(), HLBApiSuspend(), HLBApiUpdate(), HLBBudJoinGame(), HLBListAddToGroup(), HLBListClearGroup(), HLBListRemoveFromGroup(), HLBListUnFlagTempBuddy(), and HLBMsgListMsgInject().
#define HLB_ERROR_NOOP -109
there is no operation –
Referenced by HLBApiGetLastOpStatus().
#define HLB_ERROR_NOTUSER BUDDY_ERROR_NOTUSER
not a user
Referenced by HLBListBlockBuddy(), HLBListCancelAllInvites(), HLBListInviteBuddy(), and HLBListSendChatMsg().
#define HLB_ERROR_OFFLINE BUDDY_ERROR_OFFLINE
server is offline
Referenced by HLBApiPresenceSend(), HLBApiPresenceSendSetPresence(), HLBApiPresenceVOIPSend(), HLBApiSetEmailForwarding(), HLBListSendChatMsg(), and HLBListSendMsgToGroup().
#define HLB_ERROR_PASSWORD -101
#define HLB_ERROR_PEND BUDDY_ERROR_PEND
command is still pending
Referenced by HLBApiGetEmailForwarding(), HLBApiGetLastOpStatus(), HLBApiSetEmailForwarding(), and HLBListGameInviteBuddy().
#define HLB_ERROR_SELF BUDDY_ERROR_SELF
cannot add yourself as buddy.
#define HLB_ERROR_TIMEOUT -107
#define HLB_ERROR_UNKNOWN -999
unexpected..
#define HLB_ERROR_UNSUPPORTED BUDDY_ERROR_UNSUPPORTED
#define HLB_ERROR_USER_STATE -110
some invite answers need right wannabe state.
Referenced by HLBBudJoinGame(), HLBListDeleteTempBuddy(), HLBListFlagTempBuddy(), HLBListGameInviteBuddy(), HLBListInviteBuddy(), HLBListUnFlagTempBuddy(), and HLBListUnMakeBuddy().
#define HLB_FLAG_GAME_INVITE_ACCEPTED BUDDY_FLAG_GAME_INVITE_ACCEPTED
#define HLB_FLAG_GAME_INVITE_READY BUDDY_FLAG_GAME_INVITE_READY
#define HLB_FLAG_GAME_INVITE_RECEIVED BUDDY_FLAG_GAME_INVITE_RECEIVED
Referenced by HLBListCancelAllInvites().
#define HLB_FLAG_GAME_INVITE_SENT BUDDY_FLAG_GAME_INVITE_SENT
Cross Game invite can have many states..
Referenced by HLBListCancelAllInvites().
#define HLB_FLAG_GAME_INVITE_TIMEOUT BUDDY_FLAG_GAME_INVITE_TIMEOUT
Referenced by HLBBudGetGameInviteFlags().
#define HLB_GAME_STATE_LEN 32
X limit to size of game invite game state.
#define HLB_GROUP_ID 1
Only one group needed to send messages to.
Referenced by HLBBudIsInGroup(), HLBListAddToGroup(), and HLBListSendMsgToGroup().
#define HLB_MAX_BLOCKED_BUDDIES 50
max number of buddies blocked.
#define HLB_MAX_MESSAGES_ALLOWED 100
total max messages allowed – to keep memory constrained
#define HLB_MAX_PERM_BUDDIES 100
max number of permanent buddies.
#define HLB_MAX_TEMP_BUDDIES 10
max number of temporary buddies.
#define HLB_MSG_KEEP_SECS 259200
Number of seconds the server will wait to deliver the message.
Referenced by HLBListSendChatMsg().
#define HLB_MSG_TYPE_CHAT BUDDY_MSG_CHAT
How is Chat messages encoded in line protocol.
#define HLB_MSG_TYPE_INJECT 'injc'
Referenced by HLBMsgListMsgInject().
#define HLB_MSGINJECT_PARMS_TAG "PARMS"
Tag used for secret parms message injection.
Referenced by HLBMsgListMsgInject().
#define HLB_NO_CHANGES -1
tell if buddies or msg from buddy changed or not. -1 cause 0 is valid.
Referenced by HLBListBuddyWithMsg(), and HLBListChanged().
#define HLB_OP_TO 90
#define HLB_PRESENCE_LEN 100
how big a presence string
Referenced by HLBBudGetPresence().
#define HLB_SESSION_ID_LEN BUDDY_SESSION_ID_LEN
how big game invite session id string
#define HLB_XGAME_READY_TO 600
seconds buddy has, after accept Xgame, to show up in this game.
Typedef Documentation
typedef struct HLBApiRefT HLBApiRefT
Reference to this API – private.
typedef void(HLBBudActionCallbackT)(HLBApiRefT *pRef, HLBBudT *pBuddy, int32_t eAction, void *pContext)
typedef struct HLBBudT HLBBudT
typedef enum HLBConnectStateE HLBConnectStateE
State of connecting to server–.
typedef enum HLBInviteAnswerE HLBInviteAnswerE
Invite responses. Apply to buddy (wannabe) requests and to (cross) game invites.
typedef void(HLBMsgCallbackT)(HLBApiRefT *pRef, BuddyApiMsgT *pMsg, void *pContext)
typedef enum HLBMsgInjectE HLBMsgInjectE
Flags to control what features on injecting a msg –see HLBMsgListMsgInject.
typedef void(HLBOpCallbackT)(HLBApiRefT *pRef,int32_t op, int32_t opStatus, void *pContext)
typedef enum HLBOpE HLBOpE
Possible Async operations...
typedef void(HLBPresenceCallbackT)(HLBApiRefT *pRef, HLBBudT *pBuddy, HLBStatE eOldState, void *pContext)
Callback for when Buddy's presence changes–either state or text string can change.
typedef int32_t(HLBRosterSortFunctionT)(void *pSortref, int32_t iSortcon, void *pRecptr1, void *pRecptr2)
Function to register for custom sort. Use pRecptr1->pUserRef to get to the buddy.
typedef enum HLBStatE HLBStatE
State of a Buddy – same as BUDDY_STAT.
typedef enum HLBTempBuddyTypeE HLBTempBuddyTypeE
Kinds of Tempory Buddies. Any buddy can be many, or none of these..
typedef enum HLBVOIPE HLBVOIPE
Messages from Server –TBD.
Enumeration Type Documentation
enum HLBConnectStateE
State of connecting to server–.
Enumerator
HLB_CS_Disconnected
HLB_CS_Connecting
HLB_CS_Connected
HLB_CS_ErrorAuth
HLB_CS_ErrorUser
HLB_CS_ErrorNetwork
HLB_CS_ErrorServer
HLB_CS_ErrorTimeout
enum HLBInviteAnswerE
Invite responses. Apply to buddy (wannabe) requests and to (cross) game invites.
Enumerator
HLB_INVITEANSWER_ACCEPT
HLB_INVITEANSWER_REJECT
HLB_INVITEANSWER_REVOKE
HLB_INVITEANSWER_BLOCK
HLB_INVITEANSWER_REMOVE
HLB_INVITEANSWER_TIMEOUT
HLB_INVITEANSWER_UNKNOWN
enum HLBMsgInjectE
Flags to control what features on injecting a msg –see HLBMsgListMsgInject.
Enumerator
HLB_MSGINJECT_AS_ADMIN_MSG
enum HLBOpE
Possible Async operations...
Enumerator
HLB_OP_NONE
HLB_OP_CONNECT
HLB_OP_ADD_BUD
HLB_OP_DELETE_BUD
HLB_OP_BLOCK_BUD
HLB_OP_LOAD
HLB_OP_FIND_USERS
HLB_OP_SEND_MSG
HLB_OP_SET_FORWARDING
HLB_OP_INVITE
HLB_OP_ANY
enum HLBStatE
State of a Buddy – same as BUDDY_STAT.
Enumerator
HLB_STAT_UNDEFINED
HLB_STAT_DISC
HLB_STAT_CHAT
HLB_STAT_AWAY
HLB_STAT_XA
HLB_STAT_DND
HLB_STAT_PASSIVE
enum HLBTempBuddyTypeE
Kinds of Tempory Buddies. Any buddy can be many, or none of these..
Enumerator
HLB_TEMPBUDDYTYPE_MESG
HLB_TEMPBUDDYTYPE_CHAL
HLB_TEMPBUDDYTYPE_TOUR
HLB_TEMPBUDDYTYPE_VOIP
HLB_TEMPBUDDYTYPE_CUST1
HLB_TEMPBUDDYTYPE_CUST2
HLB_TEMPBUDDYTYPE_SESSION
HLB_TEMPBUDDYTYPE_MAX
enum HLBVOIPE
Messages from Server –TBD.
Enumerator
HLB_VOIP_NONE
not doing much
HLB_VOIP_PLUGGED
got headset plugged in.
HLB_VOIP_TALKING
plugged in and talking,
Function Documentation
DIRTYCODE_API void HLBApiCancelOp (HLBApiRefT * pApiRef)
Cancel any pending operations –clear pending state unconditionally. Will call operation callbacks with state of HLB_ERROR_CANCEL.
Parameters
*pApiRef - reference pointer
References HLB_ERROR_CANCEL, HLB_OP_ANY, HLBApiRefT::iLastOpState, NULL, HLBApiRefT::pOpData, and HLBApiRefT::pOpProc.
DIRTYCODE_API int32_t HLBApiConnect (HLBApiRefT * pApiRef, const char * pServer, int32_t port, const char * key, const char * pRsrc)
Connect to buddy server. Note that if connect fails for network or server-unavailability, we will keep retrying connect within the connect timeout period.
Parameters
*pApiRef - reference pointer
*pServer - buddy server hostname
port - buddy server port
*key - session key (or username:password for dev)
*pRsrc - Resource (domain/sub-domain) uniquely identified product.
Returns
int32_t - return status; HLB_ERROR_NONE if ok.
Note
    1. Will retry to connect if connect fails due to network or server unavailability.
    2. Will retry later too, if it noticed that server connection went down. Uses timeout specified in
       HLBApiOverrideConstants().
    3. If a callback is not specified, client checks for status of request using HLBApiGetConnectState().
    4. After connection is made, this api guarantees reconnect if server or network goes down. Client will know
       if server/came-up went down via  the callback or via  HLBGetConnectionStatus() poll.
References BUDDY_STAT_DISC, BuddyApiConnect(), HLBApiRefT::connect_timeout, HLBApiRefT::connectState, ds_strnzcpy(), HLB_CS_Connecting, HLB_ERROR_BADPARM, HLBApiRefT::iStat, HLBApiRefT::msgCount, NULL, and HLBApiRefT::pLLRef.
DIRTYCODE_API HLBApiRefT* HLBApiCreate (const char * pProduct, const char * pRelease, int32_t iRefMemGroup, void * pRefMemGroupUserData)
Create an instance of the High Level Buddy API.
Parameters
pProduct - Product name.
*pRelease - Release version
iRefMemGroup - mem group for hlbapiref (zero=default)
*pRefMemGroupUserData - pointer to user data associated with mem group
Returns
*HLBApiRefT - API reference pointer, to be used on subsequent calls.
References DirtyMemAlloc(), DirtyMemFree(), DirtyMemGroupQuery(), HLBUDAPI_MEMID, HLBApiRefT::iMemGroup, HLBApiRefT::iRefMemGroup, NULL, HLBApiRefT::pBuddyAlloc, HLBApiRefT::pBuddyFree, HLBApiRefT::pMemGroupUserData, and HLBApiRefT::pRefMemGroupUserData.
DIRTYCODE_API HLBApiRefT* HLBApiCreate2 (BuddyMemAllocT * pAlloc, BuddyMemFreeT * pFree, const char * pProduct, const char * pRelease, int32_t iRefMemGroup, void * pRefMemGroupUserData)
Create HL Buddy Api, overriding the default memory alloc/free functions.
Parameters
pAlloc - function to allocate memory.
pFree - function to free memory.
pProduct - Product name.
*pRelease - Release version
iRefMemGroup - mem group for hlbudapi ref (zero=default)
*pRefMemGroupUserData - pointer to user data associated with mem group
Returns
*HLBApiRefT - API reference pointer, to be used on subsequent calls.
References DirtyMemAlloc(), DirtyMemGroupQuery(), HLBUDAPI_MEMID, HLBApiRefT::iMemGroup, HLBApiRefT::iRefMemGroup, NULL, HLBApiRefT::pBuddyAlloc, HLBApiRefT::pBuddyFree, HLBApiRefT::pMemGroupUserData, and HLBApiRefT::pRefMemGroupUserData.
DIRTYCODE_API void HLBApiDestroy (HLBApiRefT * pState)
Destroy this API and any memory held by it. Also destroy lower level BuddyApi held by this.
Parameters
*pState - API reference pointer
References BuddyApiDestroy(), DirtyMemFree(), HLBUDAPI_MEMID, HLBApiRefT::iRefMemGroup, NULL, HLBApiRefT::pLLRef, and HLBApiRefT::pRefMemGroupUserData.
DIRTYCODE_API void HLBApiDisconnect (HLBApiRefT * pApiRef)
Disconnect from buddy server.
Parameters
*pApiRef - HL api reference pointer
References BUDDY_STAT_DISC, BuddyApiDisconnect(), HLBApiRefT::connectState, HLB_CS_Disconnected, HLBApiRefT::iStat, NULL, and HLBApiRefT::pLLRef.
DIRTYCODE_API int32_t HLBApiFindUsers (HLBApiRefT * pApiRef, const char * pName, HLBOpCallbackT * pOpCallback, void * context)
Request a search of users, of names starting with the pUserPattern. Min 3 chars.
Parameters
*pApiRef - reference pointer
*pName - User name pattern to search. Min 3 characters, server add the wildcard.
*pOpCallback - Callback function to be called when search is completed.
*context - User data or context that will be passed back to caller in the callback.
Returns
return code – BUDDY_ERROR_NONE if request was sent to server.
References BuddyApiFindUsers(), HLBApiRefT::op_timeout, and HLBApiRefT::pLLRef.
DIRTYCODE_API int32_t HLBApiGetConnectState (HLBApiRefT * pApiRef)
Get state of connection to the server, returns int, but see HLBConnectState_Enum.
Parameters
*pApiRef - HL api reference pointer
Returns
int32_t - connect state; int, but see HLBConnectState_Enum.
References HLBApiRefT::connectState, and HLB_CS_Disconnected.
Referenced by HLBApiPresenceSend(), HLBApiPresenceSendSetPresence(), HLBApiPresenceVOIPSend(), HLBApiSetEmailForwarding(), HLBListSendChatMsg(), and HLBListSendMsgToGroup().
DIRTYCODE_API int32_t HLBApiGetEmailForwarding (HLBApiRefT * pApiRef, int32_t * bEnable, char * strEmail)
Get email forwarding state, if already loaded from server.
Parameters
*pApiRef - ptr to API State.
*bEnable - Returned enable flag. Ignore if return code is "pending".
*strEmail - The email address.
Returns
int32_t - HLB_ERROR_NONE if ok, HLB_ERROR_PEND if not loaded yet.
References BUDDY_FORWARD_FLAG_EMAIL, BuddyApiGetForwarding(), HLB_ERROR_NONE, HLB_ERROR_PEND, and HLBApiRefT::pLLRef.
DIRTYCODE_API int32_t HLBApiGetForwarding (HLBApiRefT * pApiRef, unsigned * puForwardingFlags, char * strEmail)
DIRTYCODE_API int32_t HLBApiGetLastOpStatus (HLBApiRefT * pApiRef)
State of last operation –implies only one operation at a time. If operation is done (i.e. not pending), this will CLEAR the state.
Parameters
*pApiRef - reference pointer
Returns
int32_t - state of last operation. See HLB_ERROR_*. Returns HLB_ERROR_NOOP if nothing is outstanding.
References HLB_ERROR_NOOP, HLB_ERROR_PEND, and HLBApiRefT::iLastOpState.
DIRTYCODE_API int32_t HLBApiGetMyTitleName (HLBApiRefT * pApiRef, const char * pLang, const int32_t iBufSize, char * pTitleName)
Get the "Official" title name for this game. pLang ignored for now–defaults to English.
Get the "Official" title name for this game. pLang ignored for now–defaults to English.
References BuddyApiGetMyTitleName(), and HLBApiRefT::pLLRef.
DIRTYCODE_API int32_t HLBApiGetTitleName (HLBApiRefT * pApiRef, const uint32_t uTitleId, const int32_t iBufSize, char * pTitleName)
Get the " Official" Xbox title name for a given title, based on my locale-language.
Get the " Official" Xbox title name for a given title, based on my locale-language.
References BuddyApiGetTitleName(), and HLBApiRefT::pLLRef.
DIRTYCODE_API int32_t HLBApiGetUserIndex (HLBApiRefT * pApiRef)
DIRTYCODE_API int32_t HLBApiInitialize (HLBApiRefT * pApiRef, const char * prodPresence, uint32_t uLocality)
Configure and initialize any data structures in the API, and set some basic product and presence info.
Parameters
*pApiRef - HL api reference pointer
*prodPresence - identifies the product and used for init presence.
uLocality - The users locale -determines language to title etc.
Note
By server magic, the prodPresence field controls HLBBudIsSameProduct, so make sure this is unique for your product. This Might also be used to set initial presence, but use the Presence Api to set your presence on connecting, and all will be fine.
Returns
int32_t - HLB_ERROR_NONE if ok.
References BuddyApiConfig(), HLB_ERROR_MISSING, and HLBApiRefT::uLocale.
DIRTYCODE_API void HLBApiOverrideConstants (HLBApiRefT * pApiRef, int32_t bNoTextSupport, int32_t connect_timeout, int32_t op_timeout, int32_t max_perm_buddies, int32_t max_temp_buddies, int32_t msgs_per_perm_buddy, int32_t msgs_per_temp_buddy, int32_t max_msg_len, int32_t bTrackSendMsgInOpState, int32_t iGameInviteAccept_timeout)
Application may override default constants. -1 leaves it as default. Only valid before HLBApiConfig is called.
References _BuddyApiSetTalkToXbox(), HLBApiRefT::bTrackSendMsgInOpState, BuddyApiPresNoText(), HLBApiRefT::connect_timeout, HLB_ABSOLUTE_MAX_MSG_LEN, HLBApiRefT::iGIAccept_timeout_param, HLBApiRefT::max_msg_len, HLBApiRefT::max_msgs_allowed, HLBApiRefT::max_perm_buddies, HLBApiRefT::max_temp_buddies, HLBApiRefT::op_timeout, and HLBApiRefT::pLLRef.
DIRTYCODE_API void HLBApiOverrideMaxMessagesPerBuddy (HLBApiRefT * pApiRef, int32_t max_msgs_per_perm_buddy)
Application may override default for max msg per buddy – FIFA emergency.
Application may override default for max msg per buddy – FIFA emergency.
References HLBApiRefT::max_msgs_per_perm_buddy.
DIRTYCODE_API void HLBApiOverrideXblIsSameProductCheck (HLBApiRefT * pApiRef, int32_t bDontUseXBLSameTitleIdCheck)
Set to 1 if on XBL and NTSC cannot play each other, but, have same title id.
Application may override if XOnlineTitleIdIsSameTitle is also to be used to check for is same product. Usually use PROD field from server, and for Xbl, the XOnlineTitleIdIsSameTitle too to allow for "offline" users, who wont have a PROD field, in presence, when offline. Set to true(1), if say, NTSC and PAL cannot play each other, but, both have same XBL TitleId.
References HLBApiRefT::bDontUseXBLSameTitleIdCheck.
DIRTYCODE_API void HLBApiPresenceDiff (HLBApiRefT * pApiRef, const char * globalPres)
Set presence string for other products.
References BuddyApiPresDiff(), and HLBApiRefT::pLLRef.
DIRTYCODE_API void HLBApiPresenceExtra (HLBApiRefT * pApiRef, const char * strExtraPres)
References BuddyApiPresExtra(), and HLBApiRefT::pLLRef.
DIRTYCODE_API int32_t HLBApiPresenceJoinable (HLBApiRefT * pApiRef, int32_t bOn, int32_t bSendImmediate)
Set or reset joinable status in presence;.
Set or reset joinable status in presence;.
Parameters
pApiRef - Pointer to this api.
bOn - 1 if want joinable on, 0 if want it off.
bSendImmediate - 1 will send it now, 0 if client will call HLBApiPresenceSend later
Returns
int32_t - HLB_ERROR_NONE if ok, HLB_ERROR_OFFLINE in offline.
References BuddyApiPresJoinable(), BuddyApiPresSend(), HLB_ERROR_NONE, HLBApiRefT::iPresBuddyState, NULL, and HLBApiRefT::pLLRef.
DIRTYCODE_API int32_t HLBApiPresenceOffline (HLBApiRefT * pApiRef, int32_t bOnOff)
Set presence as "Offline" if OnOff is true.Reset if bOnOff false. Not Persistent.
References HLBApiRefT::bMakeOffline, BUDDY_SERV_ONLN, BUDDY_STAT_DISC, BuddyApiPresSend(), BuddyApiStatus(), HLBApiRefT::iPresBuddyState, NULL, and HLBApiRefT::pLLRef.
DIRTYCODE_API void HLBApiPresenceSame (HLBApiRefT * pApiRef, int32_t iPresState, const char * strSamePres)
Set presence my presence state and presence string for this product.
References BuddyApiPresSame(), HLBApiRefT::iPresBuddyState, and HLBApiRefT::pLLRef.
DIRTYCODE_API int32_t HLBApiPresenceSend (HLBApiRefT * pApiRef, int32_t iBuddyState, int32_t iVOIPState, const char * gamePres, int32_t waitMsecs)
Send presence msg, with string for this game and others.
Parameters
*pApiRef - the pointer to this API
iBuddyState - the chat state of this buddy. See HLBStatE.
iVOIPState - the headset status to send. Set to -1 if dont want to change it. VOIPState may be changed independantly, see HLBApiPresenceVOIPSend.
gamePres - the presence string for other in this (same) game to see.
waitMsecs - time to wait before sending, in msecs. 0 means send now.
Returns
int32_t - HLB_ERROR_NONE if ok, HLB_ERROR_OFFLINE regular presence not yet set.
References HLBApiRefT::bMakeOffline, BuddyApiPresExFlags(), BuddyApiPresSame(), BuddyApiPresSend(), HLB_CS_Connected, HLB_ERROR_NONE, HLB_ERROR_OFFLINE, HLBApiGetConnectState(), HLBApiRefT::iPresBuddyState, NULL, and HLBApiRefT::pLLRef.
DIRTYCODE_API int32_t HLBApiPresenceSendSetPresence (HLBApiRefT * pApiRef)
Send to server, previously set presence state and presence strings.
Parameters
*pApiRef - Pointer to this api.
Returns
int32_t - HLB_ERROR_NONE if ok, HLB_ERROR_OFFLINE in offline.
References HLBApiRefT::bMakeOffline, BuddyApiPresSend(), HLB_CS_Connected, HLB_ERROR_NONE, HLB_ERROR_OFFLINE, HLBApiGetConnectState(), HLBApiRefT::iPresBuddyState, NULL, and HLBApiRefT::pLLRef.
DIRTYCODE_API int32_t HLBApiPresenceVOIPSend (HLBApiRefT * pApiRef, int32_t iVOIPState)
Set and send presence related to this user's voip (i.e. headset) status. Must be online.
Parameters
*pApiRef - Pointer to this api.
iVOIPState - The headset status to send.
Returns
int32_t - HLB_ERROR_NONE if ok, HLB_ERROR_OFFLINE in offline.
References HLBApiRefT::bMakeOffline, BuddyApiPresExFlags(), BuddyApiPresSend(), HLB_CS_Connected, HLB_ERROR_NONE, HLB_ERROR_OFFLINE, HLBApiGetConnectState(), HLBApiRefT::iPresBuddyState, NULL, and HLBApiRefT::pLLRef.
DIRTYCODE_API int32_t HLBApiRegisterBuddyChangeCallback (HLBApiRefT * pApiRef, HLBOpCallbackT * pListCallback, void * pAppData)
Register callback for any buddy list (aka roster) change.
Parameters
*pApiRef - reference pointer
*pListCallback - Callback function to be called a chat message arrives.
*pAppData - User data or context that will be passed back to caller in the callback.
Returns
int32_t - HLB_ERROR_NONE if success. BUDDY_ERROR_FULL if try to register more than one callback.
References HLB_ERROR_FULL, HLB_ERROR_NONE, HLBPrintf, NULL, HLBApiRefT::pListData, and HLBApiRefT::pListProc.
DIRTYCODE_API int32_t HLBApiRegisterBuddyPresenceCallback (HLBApiRefT * pApiRef, HLBPresenceCallbackT * pPresCallback, void * pAppData)
Optional callback –Informe caller when buddy presence changes –state or text.
Optional callback –Informe caller when buddy presence changes –state or text.
Parameters
*pApiRef - reference pointer
*pPresCallback - function called when presence changes for a bud.
*pAppData - user data or context that will be passed back to caller in the callback.
Returns
int32_t - HLB_ERROR_NONE if success. BUDDY_ERROR_FULL if try to register more than one callback.
References HLB_ERROR_FULL, HLB_ERROR_NONE, HLBPrintf, NULL, HLBApiRefT::pBuddyPresData, and HLBApiRefT::pBuddyPresProc.
DIRTYCODE_API int32_t HLBApiRegisterConnectCallback (HLBApiRefT * pApiRef, HLBOpCallbackT * pMsgCallback, void * pAppData)
References HLB_ERROR_BADPARM, HLB_ERROR_NONE, NULL, HLBApiRefT::pConnectData, and HLBApiRefT::pConnectProc.
DIRTYCODE_API int32_t HLBApiRegisterGameInviteCallback (HLBApiRefT * pApiRef, HLBBudActionCallbackT * pActionCallback, void * pAppData)
Register callback for any game invite status change on buddies.
Parameters
*pApiRef - reference pointer
*pActionCallback - Function called when game invite changes for a bud.
*pAppData - User data or context that will be passed back to caller in the callback.
Returns
int32_t - HLB_ERROR_NONE if success. BUDDY_ERROR_FULL if try to register more than one callback.
References HLB_ERROR_FULL, HLB_ERROR_NONE, HLBPrintf, NULL, HLBApiRefT::pGameInviteData, and HLBApiRefT::pGameInviteProc.
DIRTYCODE_API int32_t HLBApiRegisterMsgAttachmentCallback (HLBApiRefT * pApiRef, HLBBudActionCallbackT * pActionCallback, void * pAppData)
DIRTYCODE_API int32_t HLBApiRegisterNewMsgCallback (HLBApiRefT * pApiRef, HLBMsgCallbackT * pMsgCallback, void * pAppData)
Register callback for new (chat) messages. Callback will be called whenever a chat message arrives. Note that clients can optionally use polling instead of this callback mechanism.
Parameters
*pApiRef - reference pointer
*pMsgCallback - Callback function to be called a chat message arrives.
*pAppData - User data or context that will be passed back to caller in the callback.
Returns
int32_t - HLB_ERROR_NONE if success. BUDDY_ERROR_FULL if try to register more than one callback.
Note
Register callback to inform caller on any new message waiting
References HLB_ERROR_FULL, HLB_ERROR_NONE, HLBPrintf, NULL, HLBApiRefT::pMesgData, and HLBApiRefT::pMesgProc.
DIRTYCODE_API void* HLBApiResume (HLBApiRefT * pApiRef)
Refresh roster and put buddy in online state – used on return from game.
Parameters
*pApiRef - reference pointer
Returns
void * - the Roster held onto by this API. NULL if errors.
References HLBApiRefT::bMakeOffline, HLBApiRefT::bRosterLoaded, BUDDY_STAT_CHAT, BuddyApiPresSend(), BuddyApiResumeXDK(), BuddyApiRoster(), HLB_ERROR_NONE, HLBApiRefT::iLastOpState, HLBApiRefT::iPresBuddyState, HLBApiRefT::iStat, NULL, and HLBApiRefT::pLLRef.
DIRTYCODE_API void HLBApiSetDebugFunction (HLBApiRefT * pApiRef, void * pDebugData, void(*)(void *pData, const char *pText) pDebugProc)
Set a callback to write out debug messages within API.
\param *pApiRef - API reference pointer
\param *pDebugData    -pointer to any caller data to be output with the prints.
\param *pDebugProc  - Function pointer that will write debug info.
Note
Caller sets this so debug info from buddy api will show up in whatever screen or log caller has.
References BuddyApiDebug(), NULL, HLBApiRefT::pDebugProc, and HLBApiRefT::pLLRef.
DIRTYCODE_API int32_t HLBApiSetEmailForwarding (HLBApiRefT * pApiRef, int32_t bEnable, const char * strEmail, HLBOpCallbackT * pOpCallback, void * pCalldata)
Turn email forwarding on or off, and set email address.
Parameters
*pApiRef - ptr to API State.
bEnable - turn forwarding on or off . 1 is on.
*strEmail - the email address to set it to. Will be set even if bEnable is off, due to server issue.
*pOpCallback - optional, callback to get status of operation. Can also poll LastOpStatus.
*pCalldata - optional, user context for callback.
Returns
int32_t - HLB_ERROR_NONE if ok, HLB_ERROR_PEND if some other operation is pending.
References BUDDY_FORWARD_FLAG_EMAIL, BuddyApiSetForwarding(), HLB_CS_Connected, HLB_ERROR_OFFLINE, HLB_ERROR_PEND, HLBApiGetConnectState(), HLBApiRefT::iLastOpState, HLBApiRefT::op_timeout, HLBApiRefT::pLLRef, HLBApiRefT::pOpData, and HLBApiRefT::pOpProc.
DIRTYCODE_API int32_t HLBApiSetUserIndex (HLBApiRefT * pApiRef, int32_t iEnumeratorIndex)
DIRTYCODE_API void HLBApiSetUtf8TransTbl (HLBApiRefT * pApiRef, Utf8TransTblT * pTransTbl)
Set if want api to translate utf8 chars to 8 bit characters in Presence, and Message Text.
References HLBApiRefT::pTransTbl.
DIRTYCODE_API int32_t HLBApiSuspend (HLBApiRefT * pApiRef)
Suspend buddy api, cleanup and put buddy in passive state. Used when want to go into game ..
Parameters
*pApiRef - reference pointer
References HLBApiRefT::bMakeOffline, BUDDY_STAT_PASS, BuddyApiPresSend(), BuddyApiSuspendXDK(), HLB_ERROR_NONE, HLBApiRefT::iPresBuddyState, HLBApiRefT::iStat, HLBApiRefT::pLLRef, and HLBApiRefT::uGIAcceptTimeout.
DIRTYCODE_API void HLBApiUpdate (HLBApiRefT * pApiRef)
Give API and api below some time to process. Must be called periodically by client.
Parameters
*pApiRef - reference pointer
References BUDDY_FLAG_GAME_INVITE_TIMEOUT, BUDDY_MSG_GAME_INVITE, BuddyApiUpdate(), HLBApiRefT::eFakeAsyncOp, HLB_ERROR_NONE, HLB_OP_NONE, HLBListGetBuddyByName(), HLBApiRefT::iFakeAsyncOpCode, HLBApiRefT::iLastOpState, NULL, HLBBudT::pLLBud, HLBApiRefT::pLLRef, HLBApiRefT::pOpData, HLBApiRefT::pOpProc, HLBApiRefT::strGIAcceptBuddy, HLBApiRefT::uGIAcceptTimeout, and HLBApiRefT::uTick.
DIRTYCODE_API BuddyApiUserT* HLBApiUserFound (HLBApiRefT * pApiRef, int32_t iItem)
Return users found from FindUser request. Allows client to iterate list of returned users. Should be called after callback from BuddyApiFindUsers has returned with a succes status.
Parameters
*pApiRef - reference pointer
iItem - Zero based item number in list.
Returns
BuddyApiUserT* - user name and domain, null if not responded yet, or item not there.
References BuddyApiUserFound(), and HLBApiRefT::pLLRef.
DIRTYCODE_API int32_t HLBBudCanPlayMyGame (HLBBudT * pBuddy)
DIRTYCODE_API int32_t HLBBudCanVoiceChat (HLBBudT * pBuddy)
Indicates if buddy is ready to be talked to. i.e. plugged in, and in same product etc.
Parameters
*pBuddy - pointer to the buddy.
Returns
int32_t - (boolean) -1- if plugged in and can be talked to.
References HLB_VOIP_PLUGGED, HLBBudGetVOIPState(), and HLBBudIsSameProduct().
DIRTYCODE_API uint32_t HLBBudGetGameInviteFlags (HLBBudT * pBuddy)
References BUDDY_MASK_GAME_INVITE, HLB_FLAG_GAME_INVITE_TIMEOUT, HLBBudT::pLLBud, and BuddyRosterT::uFlags.
Referenced by HLBListCancelAllInvites().
DIRTYCODE_API char* HLBBudGetName (HLBBudT * pBuddy)
Return screen/persona name of this buddy.
Parameters
*pBuddy - pointer to the buddy
Returns
char * - the name
References HLBBudT::pLLBud, and BuddyRosterT::strUser.
Referenced by HLBBudJoinGame(), and HLBListCancelGameInvite().
DIRTYCODE_API void HLBBudGetPresence (HLBBudT * pBuddy, char * strPresence)
Get the buddy's product presence string, as set by the other client. Will be converted to 8 bit from utf8, if a translation table is registered.
Parameters
*pBuddy - pointer to the buddy.
*strPresence - pointer to buffer to be filled with the buddy presence string
References ds_strnzcpy(), HLB_PRESENCE_LEN, NULL, HLBBudT::pHLBApi, HLBBudT::pLLBud, HLBApiRefT::pTransTbl, BuddyRosterT::strPres, and Utf8TranslateTo8Bit().
DIRTYCODE_API void HLBBudGetPresenceExtra (HLBBudT * pBuddy, char * strExtraPres, int32_t iStrSize)
Get the buddy's extra presence string, as set by the other client. W Will be empty if product is not the same.
Parameters
*pBuddy - pointer to the buddy.
*strExtraPres - pointer to the buffer to be filled with the buddy's extra presence string.
iStrSize - buffer size
References HLBBudT::pLLBud, BuddyRosterT::strPresExtra, and TagFieldDupl().
DIRTYCODE_API int32_t HLBBudGetState (HLBBudT * pBuddy)
Return buddy's state, such as is online, disconnected, in game etc. – see HLB_Buddy_State_Enum.
Parameters
*pBuddy - pointer to the buddy.
Returns
int32_t - Buddy's state – see HLB_Buddy_State_Enum.
References BuddyRosterT::iShow, and HLBBudT::pLLBud.
DIRTYCODE_API char* HLBBudGetTitle (HLBBudT * pBuddy)
Return Title played name by this buddy, based on language set in Presence.
Parameters
*pBuddy - pointer to the buddy.
Returns
char * - The utf-8 encoded title name.
Note
NOTE: Depends on server, and should be tied to language set in presence. NOTE: Not clear of server implementation for PS2. Simply may not be there. NOTE: If user is not online, title will be "empty".
References BuddyApiRefreshTitle(), NULL, HLBBudT::pHLBApi, HLBBudT::pLLBud, HLBApiRefT::pLLRef, and BuddyRosterT::strTitle.
DIRTYCODE_API int32_t HLBBudGetVOIPState (HLBBudT * pBuddy)
Return the Voice Over IP state of the buddy – plugged in or not etc.
Parameters
*pBuddy - pointer to the buddy.
Returns
int32_t - The buddy's presence voip state.
References HLBBudT::pLLBud, and BuddyRosterT::uPresExFlags.
Referenced by HLBBudCanVoiceChat().
DIRTYCODE_API uint64_t HLBBudGetXenonXUID (HLBBudT * pBuddy)
DIRTYCODE_API int32_t HLBBudIsAvailableForChat (HLBBudT * pBuddy)
Indicate if buddy is online and available for chat.
Parameters
*pBuddy - pointer to the buddy.
Returns
int32_t - (boolean) - 1 if buddy is online and available for chat.
References BUDDY_STAT_CHAT, BuddyRosterT::iShow, and HLBBudT::pLLBud.
DIRTYCODE_API int32_t HLBBudIsBlocked (HLBBudT * pBuddy)
Indicates if messages from this 'buddy' is ignored or blocked by the server.
Parameters
*pBuddy - pointer to the buddy.
Returns
int32_t -(boolean) 1 – if buddy is ignored or blocked.
References BUDDY_FLAG_IGNORE, HLBBudT::pLLBud, and BuddyRosterT::uFlags.
Referenced by HLBBudIsTemporary(), HLBListInviteBuddy(), and HLBMsgListMsgInject().
DIRTYCODE_API int32_t HLBBudIsInGroup (HLBBudT * pBuddy)
Indicates if this buddy a member of group that's been set up to send msg. See HLBListAddToGroup.
Parameters
*pBuddy - pointer to the buddy.
Returns
int32_t -(boolean) 1 – if buddy is in group.
References HLBBudT::groupId, and HLB_GROUP_ID.
DIRTYCODE_API int32_t HLBBudIsIWannaBeHisBuddy (HLBBudT * pBuddy)
References BUDDY_FLAG_BUD_REQ_SENT, HLBBudT::pLLBud, and BuddyRosterT::uFlags.
Referenced by HLBBudIsTemporary(), and HLBListCancelAllInvites().
DIRTYCODE_API int32_t HLBBudIsJoinable (HLBBudT * pBuddy)
Indicates if buddy can be "joined" (aka found and gone to) in an Xbox game. Checks the Joinable bit in Xbox Presence.
Parameters
*pBuddy - pointer to the buddy.
Returns
int32_t - (boolean) - 1 if buddy wont accept messages or invites.
References BUDDY_FLAG_JOINABLE, HLBBudT::pLLBud, and BuddyRosterT::uFlags.
Referenced by HLBBudJoinGame().
DIRTYCODE_API int32_t HLBBudIsNoReplyBud (HLBBudT * pBuddy)
Indicate if 'special' temp (i.e.admin) buddy who WONT accept messages or invites etc. Generally means I got a message from a "system" user, and it wont take replies.
Parameters
*pBuddy - pointer to the buddy.
Returns
int32_t - (boolean) - 1 if buddy wont accept messages or invites.
References BUDDY_FLAG_NOREPLY, HLBBudT::pLLBud, and BuddyRosterT::uFlags.
Referenced by HLBListBlockBuddy(), HLBListInviteBuddy(), and HLBListSendChatMsg().
DIRTYCODE_API int32_t HLBBudIsPassive (HLBBudT * pBuddy)
Indicate if buddy is passive i.e. is online but playing a game.
Parameters
*pBuddy - pointer to the buddy.
Returns
int32_t - (boolean) - 1 if buddy is in passive state, i.e. playing a game.
References BUDDY_STAT_PASS, BuddyRosterT::iShow, and HLBBudT::pLLBud.
DIRTYCODE_API int32_t HLBBudIsRealBuddy (HLBBudT * pBuddy)
Indicates if the buddy is really a buddy – ie. not someone on the list due to being blocked, or added temporarily.
Parameters
*pBuddy - pointer to the buddy.
Returns
int32_t -(boolean) 1 – if buddy is a real buddy of mine.
References BUDDY_FLAG_BUDDY, HLBBudT::pLLBud, and BuddyRosterT::uFlags.
Referenced by HLBBudIsTemporary(), HLBBudJoinGame(), and HLBListGameInviteBuddy().
DIRTYCODE_API int32_t HLBBudIsSameProduct (HLBBudT * pBuddy)
Indicate if buddy is logged into same game as I am. Buddy must be online.
Parameters
*pBuddy - pointer to the buddy.
Returns
int32_t - (boolean) - 1 if buddy is online and logged into same product.
References HLBApiRefT::bDontUseXBLSameTitleIdCheck, BUDDY_FLAG_SAME, HLBBudT::pHLBApi, HLBBudT::pLLBud, HLBApiRefT::pLLRef, and BuddyRosterT::uFlags.
Referenced by HLBBudCanVoiceChat(), and HLBBudJoinGame().
DIRTYCODE_API int32_t HLBBudIsTemporary (HLBBudT * pBuddy)
Indicates if the buddy is not persistent. Could be someone who sent me a message and is not on my buddy or ignore list.
Parameters
*pBuddy - pointer to the buddy.
Returns
int32_t -(boolean) 1 – if buddy is temporary and hence not persistent.
References HLBBudIsBlocked(), HLBBudIsIWannaBeHisBuddy(), HLBBudIsRealBuddy(), and HLBBudIsWannaBeMyBuddy().
Referenced by HLBListInviteBuddy().
DIRTYCODE_API int32_t HLBBudIsWannaBeMyBuddy (HLBBudT * pBuddy)
References BUDDY_FLAG_BUD_REQ_RECEIVED, HLBBudT::pLLBud, and BuddyRosterT::uFlags.
Referenced by HLBBudIsTemporary(), and HLBListCancelAllInvites().
DIRTYCODE_API int32_t HLBBudJoinGame (HLBBudT * pBuddy, HLBOpCallbackT * cb, void * pContext)
References BuddyApiJoinGame(), HLBApiRefT::eFakeAsyncOp, HLB_ERROR_MISSING, HLB_ERROR_NONE, HLB_ERROR_USER_STATE, HLB_OP_INVITE, HLBBudGetName(), HLBBudIsJoinable(), HLBBudIsRealBuddy(), HLBBudIsSameProduct(), HLBApiRefT::iFakeAsyncOpCode, NULL, HLBApiRefT::op_timeout, HLBBudT::pHLBApi, HLBBudT::pLLBud, and HLBApiRefT::pLLRef.
DIRTYCODE_API int32_t HLBBudTempBuddyIs (HLBBudT * pBuddy, int32_t tempBuddyType)
Is this buddy one of these temp buddy kinds – can be true for permanent buddies too.
References HLBBudT::uTempBuddyFlags.
DIRTYCODE_API int32_t HLBListAddToGroup (HLBApiRefT * pApiRef, const char * buddyName)
On closing screen, need to clear temp buddies w/o messages etc..
Add user to group to whom i will send a common msg.
References HLBBudT::groupId, HLB_ERROR_MISSING, HLB_ERROR_NONE, HLB_GROUP_ID, HLBListGetBuddyByName(), and NULL.
DIRTYCODE_API int32_t HLBListAnswerGameInvite (HLBApiRefT * pApiRef, const char * name, int32_t iInviteAction, HLBOpCallbackT * cb, void * pContext)
Respond to an invite or change state of invite i sent, –applies to game invites.
References BuddyApiRespondGame(), HLBApiRefT::eFakeAsyncOp, HLB_ERROR_MISSING, HLB_INVITEANSWER_REVOKE, HLB_OP_INVITE, HLBApiRefT::iFakeAsyncOpCode, NULL, HLBApiRefT::op_timeout, HLBApiRefT::pLLRef, HLBApiRefT::strGIAcceptBuddy, HLBApiRefT::uGIAcceptTimeout, and HLBApiRefT::uGISessionId.
Referenced by HLBListCancelGameInvite().
DIRTYCODE_API int32_t HLBListAnswerInvite (HLBApiRefT * pApiRef, const char * name, int32_t iInviteAction, HLBOpCallbackT * cb, void * pContext)
Respond to an invite or change state of invite I sent, –applies to wannabe buddy invites.
References BUDDY_FLAG_IGNORE, BuddyApiRespondBuddy(), HLB_ERROR_FULL, HLB_ERROR_MISSING, HLB_INVITEANSWER_BLOCK, HLBApiRefT::max_block_buddies, NULL, HLBApiRefT::op_timeout, and HLBApiRefT::pLLRef.
DIRTYCODE_API int32_t HLBListBlockBuddy (HLBApiRefT * pApiRef, const char * name, HLBOpCallbackT * cb, void * context)
Ask that this buddy be ignored. Server will no longer send messages from this buddy.
Parameters
*pApiRef - API Reference pointer.
*name - name pointer
*cb - pointer to optional completion callback function
*context - optional user context that will be passed to callback.
Returns
int32_t - HLB_ERROR_NONE if command was sent.
Note
Client can use callback, or, use polling to determine status of operation, as reported later by the server.
References BUDDY_FLAG_IGNORE, HLB_ERROR_NOTUSER, HLBBudIsNoReplyBud(), and HLBListGetBuddyByName().
DIRTYCODE_API int32_t HLBListBuddyWithMsg (HLBApiRefT * pApiRef)
Has messages from any buddies changed? Returns buddy index, or HLB_NO_CHANGES.
References HLB_NO_CHANGES, HLBListGetBuddyByIndex(), HLBListGetBuddyCount(), and HLBBudT::msgListDirty.
DIRTYCODE_API int32_t HLBListCancelAllInvites (HLBApiRefT * pApiRef, const char * pName)
add a message from a buddy.
Helper killer function to nuke all invites – NO Callbacks. To be used when blocking a buddy, and want all invites nuked.
References BuddyApiRespondBuddy(), BuddyApiRespondGame(), HLB_ERROR_NOTUSER, HLB_FLAG_GAME_INVITE_RECEIVED, HLB_FLAG_GAME_INVITE_SENT, HLB_INVITEANSWER_REJECT, HLB_INVITEANSWER_REVOKE, HLBBudGetGameInviteFlags(), HLBBudIsIWannaBeHisBuddy(), HLBBudIsWannaBeMyBuddy(), HLBListGetBuddyByName(), NULL, HLBApiRefT::op_timeout, HLBBudT::pLLBud, HLBApiRefT::pLLRef, and HLBApiRefT::uGISessionId.
DIRTYCODE_API int32_t HLBListCancelGameInvite (HLBApiRefT * pApiRef, HLBOpCallbackT * cb, void * pContext)
Cancel any game invites I sent – also see HLBListAnswerGameInvite.
References BUDDY_FLAG_GAME_INVITE_SENT, HLB_INVITEANSWER_REVOKE, HLBBudGetName(), HLBListAnswerGameInvite(), HLBListGetBuddyByIndex(), HLBListGetBuddyCount(), HLBBudT::pLLBud, and BuddyRosterT::uFlags.
DIRTYCODE_API int32_t HLBListChanged (HLBApiRefT * pApiRef)
Has the list of buddies or their presence changed? Will clear the flag. Local.
References HLB_CHANGED, HLB_NO_CHANGES, and HLBApiRefT::rosterDirty.
DIRTYCODE_API int32_t HLBListClearGroup (HLBApiRefT * pApiRef)
Clear group of users so I can re-use it.
References HLBBudT::groupId, HLB_ERROR_NONE, HLBListGetBuddyByIndex(), HLBListGetBuddyCount(), and NULL.
DIRTYCODE_API int32_t HLBListDeleteNoMsgTempBuddies (HLBApiRefT * pApiRef)
DIRTYCODE_API int32_t HLBListDeleteTempBuddy (HLBApiRefT * pApiRef, const char * name)
Explicitly delete this temp buddy. Will ignore request if buddy is permanent. local call.
Parameters
*pApiRef - module reference
*name - buddy name.
Returns
int32_t - HLB_ERROR_NONE if ok.
References BUDDY_FLAG_TEMP, BUDDY_STAT_PASS, HLB_ERROR_USER_STATE, HLBApiRefT::iStat, and NULL.
Referenced by HLBListUnMakeBuddy().
DIRTYCODE_API void HLBListDisableSorting (HLBApiRefT * pApiRef)
References DispListChange(), DispListOrder(), DispListSort(), and NULL.
DIRTYCODE_API int32_t HLBListFlagTempBuddy (HLBApiRefT * pApiRef, const char * name, int32_t buddyType)
Add as a tourney or other temp buddy for convenience. Sync, local call. If buddy already exists as a "permanent" buddy, then flag is set, Otherwise, buddy is added to the list as a "temp" buddy.
Parameters
*pApiRef - module reference
*name - Buddies name.
buddyType - the TempBuddyType (see enum)
Returns
int32_t - HLB_ERROR_NONE if ok.
References BUDDY_FLAG_TEMP, BUDDY_STAT_PASS, HLB_ERROR_MISSING, HLB_ERROR_USER_STATE, HLBApiRefT::iStat, and NULL.
DIRTYCODE_API int32_t HLBListGameInviteBuddy (HLBApiRefT * pApiRef, const char * name, const char * pGameInviteState, HLBOpCallbackT * cb, void * pContext)
References BUDDY_STAT_PASS, BuddyApiGameInvite(), HLBApiRefT::eFakeAsyncOp, HLB_ERROR_MISSING, HLB_ERROR_PEND, HLB_ERROR_USER_STATE, HLB_OP_INVITE, HLBBudIsRealBuddy(), HLBListGetBuddyByName(), HLBApiRefT::iFakeAsyncOpCode, HLBApiRefT::iStat, NULL, HLBApiRefT::op_timeout, HLBApiRefT::pLLRef, HLBApiRefT::uGIAcceptTimeout, and HLBApiRefT::uGISessionId.
DIRTYCODE_API HLBBudT* HLBListGetBuddyByIndex (HLBApiRefT * pApiRef, int32_t index)
Get a Buddy by index into the buddy list.
Parameters
*pApiRef - API Reference pointer.
index - zero based index.
Returns
HLBBudT* - pointer to Buddy structure. NULL if not there.
References DispListIndex(), NULL, and BuddyRosterT::pUserRef.
Referenced by HLBListBuddyWithMsg(), HLBListCancelGameInvite(), HLBListClearGroup(), HLBListGetIndexByName(), and HLBListSendMsgToGroup().
DIRTYCODE_API HLBBudT* HLBListGetBuddyByName (HLBApiRefT * pApiRef, const char * name)
Get a buddy from the buddy list (roster) by name. Exact match.
Parameters
*pApiRef - API Reference pointer.
*name - name string.
Returns
HLBBudT* - pointer to Buddy structure. NULL if not there.
References BuddyApiFind(), NULL, HLBApiRefT::pLLRef, and BuddyRosterT::pUserRef.
Referenced by HLBApiUpdate(), HLBListAddToGroup(), HLBListBlockBuddy(), HLBListCancelAllInvites(), HLBListGameInviteBuddy(), HLBListInviteBuddy(), HLBListRemoveFromGroup(), HLBListSendChatMsg(), HLBListUnFlagTempBuddy(), and HLBMsgListMsgInject().
DIRTYCODE_API int32_t HLBListGetBuddyCount (HLBApiRefT * pApiRef)
Get count of all buddies in the Roster. Also see HLBListGetBuddyCountByFlags.
Parameters
pApiRef - API Reference pointer.
Returns
int32_t - Total number of buddies.
Referenced by HLBListBuddyWithMsg(), HLBListCancelGameInvite(), HLBListClearGroup(), HLBListGetIndexByName(), and HLBListSendMsgToGroup().
DIRTYCODE_API int32_t HLBListGetBuddyCountByFlags (HLBApiRefT * pApiRef, uint32_t uTypeFlag)
Get count of buddies that match the buddy (type) flags, like BUDDY, INVITE_SENT etc. .e.g. To count all permanent, but not blocked, buddies, call with: flag=BUDDY_FLAG_BUDDY|BUDDY_FLAG_BUD_REQ_RECEIVED |BUDDY_FLAG_BUD_REQ_SENT.
Parameters
pApiRef - API Reference pointer.
uTypeFlag - bit mask of all buddy types to look for.
Returns
int32_t - total number of buddies that match any of the type flags specified.
DIRTYCODE_API int32_t HLBListGetGameSessionID (HLBApiRefT * pApiRef, const char * name, char * sSessionID, const int32_t iBufSize)
References BuddyApiGetUserSessionID(), and HLBApiRefT::pLLRef.
DIRTYCODE_API int32_t HLBListGetIndexByName (HLBApiRefT * pApiRef, const char * name)
Given a buddy name, find the index into the list.
Parameters
*pApiRef - API Reference pointer.
*name - name of the buddy to find from the local roster list.
Returns
int32_t - index to buddy; negative value (HLB_ERROR_MISSING) if not there.
References ds_stricmp(), HLB_ERROR_MISSING, HLBListGetBuddyByIndex(), HLBListGetBuddyCount(), NULL, HLBBudT::pLLBud, and BuddyRosterT::strUser.
DIRTYCODE_API int32_t HLBListInviteBuddy (HLBApiRefT * pApiRef, const char * name, HLBOpCallbackT * cb, void * pContext)
Ask this use to be my buddy. Async. Will be added to my IWannabeHisBuddy list.
References BUDDY_FLAG_BUDDY, BUDDY_STAT_PASS, BuddyApiBuddyInvite(), ds_strnzcpy(), HLB_ERROR_FULL, HLB_ERROR_NOTUSER, HLB_ERROR_USER_STATE, HLBBudIsBlocked(), HLBBudIsNoReplyBud(), HLBBudIsTemporary(), HLBListGetBuddyByName(), HLBApiRefT::iStat, NULL, HLBApiRefT::op_timeout, HLBApiRefT::pLLRef, and BuddyRosterT::strUser.
DIRTYCODE_API int32_t HLBListRemoveFromGroup (HLBApiRefT * pApiRef, const char * buddyName)
Remove this buddy from the group Iam going to send messages to.
References HLBBudT::groupId, HLB_ERROR_MISSING, HLB_ERROR_NONE, HLBListGetBuddyByName(), and NULL.
DIRTYCODE_API int32_t HLBListSendChatMsg (HLBApiRefT * pApiRef, const char * name, const char * body, HLBOpCallbackT * cb, void * pContext)
Send an actual chat message.
References HLBApiRefT::bTrackSendMsgInOpState, BuddyApiBroadcast(), BuddyApiResource(), BuddyApiSend(), ds_snzprintf(), ds_strnzcpy(), HLB_ABSOLUTE_MAX_MSG_LEN, HLB_CS_Connected, HLB_ERROR_NOTUSER, HLB_ERROR_OFFLINE, HLB_MSG_KEEP_SECS, HLBApiGetConnectState(), HLBBudIsNoReplyBud(), HLBListGetBuddyByName(), MAX_BRDC_USERS_LEN, HLBApiRefT::max_msg_len, NULL, HLBApiRefT::op_timeout, HLBApiRefT::pLLRef, TagFieldClear, TagFieldSetNumber(), and TagFieldSetString().
Referenced by HLBListSendMsgToGroup().
DIRTYCODE_API int32_t HLBListSendMsgToGroup (HLBApiRefT * pApiRef, int32_t msgType, const char * msg, int32_t bClearGroup, HLBOpCallbackT * cb, void * pContext)
Send message to group of users I created earlier. Reset group if clearGroup is set.
References BuddyApiResource(), ds_strnzcpy(), HLBBudT::groupId, HLB_CS_Connected, HLB_ERROR_MISSING, HLB_ERROR_OFFLINE, HLB_GROUP_ID, HLBApiGetConnectState(), HLBListGetBuddyByIndex(), HLBListGetBuddyCount(), HLBListSendChatMsg(), MAX_BRDC_USERS_LEN, NULL, HLBBudT::pLLBud, HLBApiRefT::pLLRef, and BuddyRosterT::strUser.
DIRTYCODE_API int32_t HLBListSetGameInviteSessionID (HLBApiRefT * pApiRef, const char * sSessionID)
References BuddyApiSetGameInviteSessionID(), and HLBApiRefT::pLLRef.
DIRTYCODE_API void HLBListSetSortFunction (HLBApiRefT * pApiRef, HLBRosterSortFunctionT * sortCallbackFunction)
Sort function to be set if client wants custom sort of buddy list – However API will have a reasonable default sort.
References HLBApiRefT::pBuddySortFunc.
DIRTYCODE_API int32_t HLBListSort (HLBApiRefT * pApiRef)
Sort list of buddies. Once sorted, list will be frozen until re-sorted, or provide a freeze() call.
References BUDDY_ERROR_NONE, DispListChange(), DispListOrder(), DispListSort(), NULL, and HLBApiRefT::pBuddySortFunc.
DIRTYCODE_API int32_t HLBListUnBlockBuddy (HLBApiRefT * pApiRef, const char * name, HLBOpCallbackT * cb, void * context)
No longer Ignore this buddy. Server will no longer block messages from this buddy.
Parameters
*pApiRef - API Reference pointer.
*name - name
*cb - Pointer to optional completion callback function
*context - Optional user context that will be passed to callback.
Returns
int32_t - HLB_ERROR_NONE if command was sent.
Note
Client can use callback, or, use polling to determine status of operation, as reported later by the server. If this "buddy" was only Blocked, it will now be removed from the local buddy list.
References BUDDY_FLAG_IGNORE.
DIRTYCODE_API int32_t HLBListUnFlagTempBuddy (HLBApiRefT * pApiRef, const char * name, int32_t tempBuddyType)
Clear the particular temp buddy flag if set. Does not remove from list – client must explicitly deleteAdd as a tourney or other temp buddy for convenience. Sync, local call.
Parameters
*pApiRef - module reference
*name - Buddies name
*tempBuddyType - the TempBuddyType flag to clear (see enum)
Returns
int32_t - HLB_ERROR_NONE if ok.
References BUDDY_STAT_PASS, HLB_ERROR_NONE, HLB_ERROR_USER_STATE, HLBListGetBuddyByName(), HLBApiRefT::iStat, and HLBBudT::uTempBuddyFlags.
DIRTYCODE_API int32_t HLBListUnMakeBuddy (HLBApiRefT * pApiRef, const char * name, HLBOpCallbackT * cb, void * context)
Ensure user is no longer a buddy of mine, by clearing "buddy" flag. Server operation. Will remain on buddy list if other (eg. temp or Ignore flags are set).
Parameters
*pApiRef - API Reference pointer.
*name - buddy name.
*cb - Pointer to optional completion callback function
*context - Optional user context that will be passed to callback.
Returns
int32_t - HLB_ERROR_NONE if command was sent.
Note
Client can use callback, or, use polling to determine status of operation, as reported later by the server.
References BUDDY_FLAG_BUDDY, BUDDY_STAT_PASS, HLB_ERROR_USER_STATE, HLBListDeleteTempBuddy(), and HLBApiRefT::iStat.
DIRTYCODE_API void HLBMsgListDelete (HLBBudT * pBuddy, int32_t index)
Delete message at (zero based) index position.
Parameters
*pBuddy - pointer to the buddy.
index - index
References HLBApiRefT::msgCount, HLBBudT::msgList, NULL, and HLBBudT::pHLBApi.
DIRTYCODE_API void HLBMsgListDeleteAll (HLBBudT * pBuddy, int32_t bZapReadOnly)
Delete all, or just read msgs from this buddy. Local. If bZapReadOnly is true will delete just read msgs.
Parameters
*pBuddy - pointer to the buddy.
bZapReadOnly - int32_t (boolean) - if 1, will delete Read messages.
References HLB_MSG_READ_FLAG, HLBApiRefT::msgCount, HLBBudT::msgList, NULL, HLBBudT::pHLBApi, and BuddyApiMsgT::uUserFlags.
DIRTYCODE_API BuddyApiMsgT* HLBMsgListGetFirstUnreadMsg (HLBBudT * pBuddy, int32_t startPos, int32_t read)
Return unread message from buddy, starting from a start position.
Parameters
*pBuddy - pointer to the buddy.
startPos - Zero based index position to start looking for unread messages.
read - (boolean) if true, message will be marked as read.
Returns
BuddyApiMsgT* - First unread Message from buddy. NULL if no more.
References HLB_MSG_READ_FLAG, HLBBudT::msgList, NULL, and BuddyApiMsgT::uUserFlags.
DIRTYCODE_API BuddyApiMsgT* HLBMsgListGetMsgByIndex (HLBBudT * pBuddy, int32_t index, int32_t read)
Get message at index position, if read is true, mark message as read.
HLBMsgList – Buddy's Message List – List of messages from a buddy Each buddy has a message list. Actual data structure used is TBD. This will contain all the messages from that buddy, as the list fills up (hits max msg per buddy) the earlier messages will be deleted. Assumes single threaded model and Update() not called while iterating through message list.
Return message from buddy, at index specified.
Parameters
*pBuddy - pointer to the buddy.
index - Sero based index position to read message from.
read - int32_t - (boolean) - if true, message will be marked as read.
Returns
BuddyApiMsgT* - Message from buddy at that index pos. NULL if not there.
References HLB_MSG_READ_FLAG, HLBBudT::msgList, NULL, and BuddyApiMsgT::uUserFlags.
DIRTYCODE_API void HLBMsgListGetMsgText (HLBApiRefT * pApiRef, BuddyApiMsgT * pMsg, char * strText, int32_t iLen)
Return the BODY of message, text, converting to 8 bit chars from utf8 if needed.
Parameters
*pApiRef - reference pointer
*pMsg - pointer to the msg.
strText - [out] Text buffer msg body will be written to.
iLen - Length of text buffer.
References ds_strnzcpy(), NULL, BuddyApiMsgT::pData, HLBApiRefT::pTransTbl, TagFieldFind(), TagFieldGetString(), and Utf8TranslateTo8Bit().
DIRTYCODE_API int32_t HLBMsgListGetTotalCount (HLBBudT * pBuddy)
Return total count of messages, both read and unread, from buddy.
Parameters
*pBuddy - pointer to the buddy.
Returns
int32_t - count of messages.
References HLBBudT::msgList.
DIRTYCODE_API int32_t HLBMsgListGetUnreadCount (HLBBudT * pBuddy)
Return count of unread messages from buddy.
Parameters
*pBuddy - pointer to the buddy.
Returns
int32_t - count of unread messages.
References HLB_MSG_READ_FLAG, HLBBudT::msgList, and BuddyApiMsgT::uUserFlags.
DIRTYCODE_API int32_t HLBMsgListMsgInject (HLBApiRefT * pApiRef, int32_t iKind, const char * pSenderName, const char * pMsgBody, const char * pMsgParms, uint32_t uMsgInjectFlags, uint32_t uTime)
Inject a message, as if from some buddy. Message callbacks etc will be called. If user is not on buddy list, he will be added as "temp" buddy. Convenience function, so client can inject lobby control and other messages, and use same "buddy" UI to show such messages.
Parameters
*pApiRef - reference pointer
iKind - Type of msg inject (client can set, see clubapi.h for CLUB_KINDs.)
*pSenderName - user, persona name of user on who's behalf msg is injected. Will appear as if "from" that user. May be null for admin message.
*pMsgBody - The text body of message to inject.
*pMsgParms - Any "secret" parameters to send, grab using tag field HLB_MSGINJECT_PARMS_TAG
uMsgInjectFlags - Flags to control features on msg, see HLBMsgInjectE.
uTime - time
Returns
int32_t - return status, 0 if sucess, BLOCKED,FULL etc based on error condition.
References ADMIN_USER, HLBApiRefT::bRosterLoaded, BUDDY_EASO_BODYLEN, BuddyApiResource(), HLB_ERROR_BLOCKED, HLB_ERROR_NONE, HLB_MSG_TYPE_INJECT, HLB_MSGINJECT_AS_ADMIN_MSG, HLB_MSGINJECT_PARMS_TAG, HLBBudIsBlocked(), HLBListGetBuddyByName(), BuddyApiMsgT::iKind, BuddyApiMsgT::iType, NULL, BuddyApiMsgT::pData, HLBApiRefT::pLLRef, TagFieldClear, TagFieldSetNumber(), and TagFieldSetString().
DIRTYCODE_API int32_t HLBReceiveMsgAttachment (HLBApiRefT * pHLBApi, void * pContext)
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:31