DirtySock: JsonParse
JsonParse
Util
Macros
#define JsonGetListItemEnd(__pObject) JsonSeekObjectEnd(__pObject)
alternate name for JsonSeekObjectEnd (DEPRECATED)
Functions
DIRTYCODE_API int32_t JsonParse (uint16_t *pDst, int32_t iMax, const char *pSrc, int32_t iLen)
Pre-parse a JSON buffer for fast parsing. Must be called on a buffer before any Find() or Get() functions are used. Pass pDst=NULL and iMax=0 to query the required table size.
DIRTYCODE_API const char * JsonFind (const uint16_t *pParse, const char *pName)
Locate a JSON element.
DIRTYCODE_API const char * JsonFind2 (const uint16_t *pParse, const char *pJson, const char *pName, int32_t iIndex)
Locate a JSON element, starting from an offset, with an optional array index.
DIRTYCODE_API int32_t JsonGetString (const char *pJson, char *pBuffer, int32_t iLength, const char *pDefault)
Extract a JSON string element. Pass pBuffer=NULL for length check.
DIRTYCODE_API int64_t JsonGetInteger (const char *pJson, int64_t iDefault)
Extract a JSON integer number element.
DIRTYCODE_API float JsonGetNumber (const char *pJson, float fDefault)
Extract a JSON number element (UNIMPLEMENTED)
DIRTYCODE_API uint32_t JsonGetDate (const char *pJson, uint32_t uDefault)
Extract a JSON date element.
DIRTYCODE_API uint8_t JsonGetBoolean (const char *pJson, uint8_t bDefault)
Extract a JSON boolean.
DIRTYCODE_API int32_t JsonGetEnum (const char *pJson, const char *pEnumArray[], int32_t iDefault)
Extract a JSON enumerated value. The source type is assumed to be a string, and pEnumArray contains a NULL-terminated list of strings that may be converted to an enum value.
DIRTYCODE_API const char * JsonSeekObjectEnd (const char *pObject)
Seek to the end of an object within the JSON text buffer.
DIRTYCODE_API const char * JsonSeekValue (const char *pKey)
Given a pointer to the beginning of a simple JSON key value pair, seeks the start of the value.
Detailed Description
Macro Definition Documentation
#define JsonGetListItemEnd (__pObject) JsonSeekObjectEnd(__pObject)
alternate name for JsonSeekObjectEnd (DEPRECATED)
Function Documentation
DIRTYCODE_API const char* JsonFind (const uint16_t * pParse, const char * pName)
Locate a JSON element.
Parameters
*pParse - pre-parsed lookup from JsonParse
*pName - name of element to locate
Returns
const char * - pointer to element, or NULL if not found
Note
A name can include a period character '.' which indicates an object reference, or an open bracket '[' which indicates an array reference. A bracket must be the last character in the name.
Version
12/13/2012 (jbrookes)
References JsonFind2().
Referenced by UserListApiUpdate().
DIRTYCODE_API const char* JsonFind2 (const uint16_t * pParse, const char * _pJsonOff, const char * pName, int32_t iIndex)
Locate a JSON element, starting from an offset, with an optional array index.
Parameters
*pParse - pre-parsed lookup from JsonParse
*_pJsonOff - offset into JSON buffer to begin search
*pName - name of element to locate
iIndex - [optional] index of array element to return
Returns
const uint8_t * - pointer to element, or NULL if not found
Note
This version of Find is useful for parsing arrays of scalars or objects, or for starting a parse at an offset within the JSON document.
Version
12/13/2012 (jbrookes)
Referenced by JsonFind().
DIRTYCODE_API uint8_t JsonGetBoolean (const char * pJson, uint8_t bDefault)
Extract a JSON boolean.
Parameters
*pJson - JSON buffer
bDefault - default boolean value to use
Returns
uint8_t - extracted bool, or default
Version
12/13/2012 (jbrookes)
References FALSE, and TRUE.
Referenced by UserListApiUpdate().
DIRTYCODE_API uint32_t JsonGetDate (const char * pJson, uint32_t uDefault)
Extract a JSON date element.
Parameters
*pJson - JSON buffer
uDefault - default date value to use
Returns
uint32_t - extracted date, or default
Note
Date is assumed to be in ISO_8601 format
Version
12/13/2012 (jbrookes)
References ds_strtotime2(), JsonGetString(), and TIMETOSTRING_CONVERSION_ISO_8601.
DIRTYCODE_API int32_t JsonGetEnum (const char * pJson, const char * pEnumArray[], int32_t iDefault)
Extract a JSON enumerated value. The source type is assumed to be a string, and pEnumArray contains a NULL-terminated list of strings that may be converted to an enum value.
Parameters
*pJson - JSON buffer
*pEnumArray - NULL-terminated list of enum strings
iDefault - default enum value to use if no match is found
Returns
int32_t - enum value; or default
Version
12/13/2012 (jbrookes)
References JsonGetString().
DIRTYCODE_API int64_t JsonGetInteger (const char * pJson, int64_t iDefault)
Extract a JSON integer number element.
Parameters
*pJson - JSON buffer
iDefault - default value to use, if number could not be extracted
Returns
int64_t - integer, or default value
Version
12/13/2012 (jbrookes)
Referenced by UserListApiUpdate().
DIRTYCODE_API float JsonGetNumber (const char * pJson, float fDefault)
Extract a JSON number element (UNIMPLEMENTED)
Parameters
*pJson - JSON buffer
fDefault - default value to use, if number could not be extracted
Returns
float - number, or default value
Version
12/13/2012 (jbrookes)
DIRTYCODE_API int32_t JsonGetString (const char * pJson, char * pBuffer, int32_t iLength, const char * pDefault)
Extract a JSON string element. Pass pBuffer=NULL for length check.
Parameters
*pJson - JSON buffer
*pBuffer - [out] storage for string (may be NULL for length query)
iLength - length of output buffer
*pDefault - default value to use, if string could not be extracted
Returns
int32_t - length of string, or negative on error
Version
12/13/2012 (jbrookes)
Referenced by JsonGetDate(), and JsonGetEnum().
DIRTYCODE_API int32_t JsonParse (uint16_t * pDst, int32_t iMax, const char * _pSrc, int32_t iLen)
Pre-parse a JSON buffer for fast parsing. Must be called on a buffer before any Find() or Get() functions are used. Pass pDst=NULL and iMax=0 to query the required table size.
Parameters
*pDst - [out] storage for lookup buffer, two elements per object
iMax - number of uint16_t elements in output buffer
*_pSrc - pointer to JSON buffer
iLen - length of JSON buffer; if -1 a strlen is performed
Returns
int32_t - zero=table too small, else size of table in bytes
Version
12/13/2012 (jbrookes)
References FALSE, and TRUE.
Referenced by UserListApiUpdate().
DIRTYCODE_API const char* JsonSeekObjectEnd (const char * pList)
Seek to the end of an object within the JSON text buffer.
Parameters
*pList - pointer to the beginning of object
Returns
const char * - pointer to the end of the object, NULL for error
Version
04/17/2013 (amakoukji)
DIRTYCODE_API const char* JsonSeekValue (const char * pKey)
Given a pointer to the beginning of a simple JSON key value pair, seeks the start of the value.
Parameters
*pKey - module ref
Returns
int32_t - pointer to the start of the value, NULL for error
Version
11/28/2013 (amakoukji)
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:34:38