DirtySock: NetResource
NetResource
Misc
Data Structures
struct NetResourceXferT
NetResource Transfer Descriptor Structure.
Macros
#define NETRSRC_STAT_IDLE (0)
not doing anything
#define NETRSRC_STAT_START (1)
start of transfer
#define NETRSRC_STAT_SIZE (2)
size of object known (allocate buffer)
#define NETRSRC_STAT_DATA (3)
append data to buffer
#define NETRSRC_STAT_DONE (4)
transfer is complete (hand off data)
#define NETRSRC_STAT_ERROR (5)
transfer failed
#define NETRSRC_STAT_CANCEL (6)
transfer was canceled (release buffer)
#define NETRSRC_STAT_TIMEOUT (7)
transfer timed out
#define NETRSRC_STAT_MISSING (8)
resource is not on the server
#define NETRSRC_STAT_FINISH (9)
finished – release resources
#define NETRSRC_PRIO_DONTCACHE (-1)
don't cache the incoming data whatsoever (one-time use data to download, like rosters etc.)
#define NETRSRC_PRIO_DEFAULT (0)
default - don't do anything special to keep or discard data in the cache
#define NETRSRC_PRIO_KEEPIFPOSSIBLE (1)
keep the data in the cache if at all possible (commonly used data)
#define NETRSRC_ERROR_NONE (0)
no error
#define NETRSRC_ERROR_BADNAME (-1)
bad resource string name passed to fetch function
#define NETRSRC_CACHESTATUS_LOADING (0x01)
#define NETRSRC_CACHESTATUS_SAVING (0x02)
#define NETRSRC_PRINTFTYPEIDENT(uType, uIdent)
Typedefs
typedef struct NetResourceT NetResourceT
typedef struct NetResourceXferT NetResourceXferT
typedef void(NetResourceCallbackT)(NetResourceT *pState, NetResourceXferT *pXfer, void *pDataBuf, int32_t iDataLen)
Functions
DIRTYCODE_API NetResourceT * NetResourceCreate (const char *pHome)
Create network resource manager instance.
DIRTYCODE_API void NetResourceDestroy (NetResourceT *pState)
Destroy the network resource manager instance.
DIRTYCODE_API int32_t NetResourceCache (NetResourceT *pState, void *pCacheBuf, const int32_t iCacheLen)
Sets the external cache buffer, which will be used for caching resources until a different buffer is selected. Pass NULL to disable caching.
DIRTYCODE_API int32_t NetResourceCacheCheck (NetResourceT *pState, const char *pResource, uint32_t uType, uint32_t uIdent)
Check to see if the cache contains the given resource.
DIRTYCODE_API int32_t NetResourceFetch (NetResourceT *pState, NetResourceXferT *pXfer, const uint32_t uType, const uint32_t uIdent, NetResourceCallbackT *pCallback, const int32_t iTimeout, const int32_t iPriority)
Start a network transfer from a resource type and id value.
DIRTYCODE_API int32_t NetResourceFetchString (NetResourceT *pState, NetResourceXferT *pXfer, const char *pResource, NetResourceCallbackT *pCallback, const int32_t iTimeout, const int32_t iPriority)
Start a network transfer from a resource string.
DIRTYCODE_API void NetResourceCancel (NetResourceT *pState, int32_t iSeqNum)
Cancel an in-progress network transfer.
Detailed Description
Macro Definition Documentation
#define NETRSRC_CACHESTATUS_LOADING (0x01)
#define NETRSRC_CACHESTATUS_SAVING (0x02)
#define NETRSRC_ERROR_BADNAME (-1)
bad resource string name passed to fetch function
#define NETRSRC_ERROR_NONE (0)
no error
Referenced by NetResourceCache().
#define NETRSRC_PRINTFTYPEIDENT (uType, uIdent)
Value:
((uType) >> 24) & 0xFF, \
    ((uType) >> 16) & 0xFF, \
    ((uType) >> 8) & 0xFF, \
    (uType) & 0xFF, (uIdent)
Referenced by NetResourceCancel().
#define NETRSRC_PRIO_DEFAULT (0)
default - don't do anything special to keep or discard data in the cache
#define NETRSRC_PRIO_DONTCACHE (-1)
don't cache the incoming data whatsoever (one-time use data to download, like rosters etc.)
#define NETRSRC_PRIO_KEEPIFPOSSIBLE (1)
keep the data in the cache if at all possible (commonly used data)
#define NETRSRC_STAT_CANCEL (6)
transfer was canceled (release buffer)
Referenced by NetResourceCancel().
#define NETRSRC_STAT_DATA (3)
append data to buffer
#define NETRSRC_STAT_DONE (4)
transfer is complete (hand off data)
#define NETRSRC_STAT_ERROR (5)
transfer failed
#define NETRSRC_STAT_FINISH (9)
finished – release resources
#define NETRSRC_STAT_IDLE (0)
not doing anything
Referenced by NetResourceFetch().
#define NETRSRC_STAT_MISSING (8)
resource is not on the server
#define NETRSRC_STAT_SIZE (2)
size of object known (allocate buffer)
#define NETRSRC_STAT_START (1)
start of transfer
#define NETRSRC_STAT_TIMEOUT (7)
transfer timed out
Typedef Documentation
typedef void(NetResourceCallbackT)(NetResourceT *pState, NetResourceXferT *pXfer, void *pDataBuf, int32_t iDataLen)
typedef struct NetResourceT NetResourceT
typedef struct NetResourceXferT NetResourceXferT
Function Documentation
DIRTYCODE_API int32_t NetResourceCache (NetResourceT * pState, void * pCacheBuf, const int32_t iCacheLen)
Sets the external cache buffer, which will be used for caching resources until a different buffer is selected. Pass NULL to disable caching.
Parameters
*pState - module state
*pCacheBuf - pointer to the user-supplied (and alloc'ed) memory block
iCacheLen - length of the user-supplied memory block
Returns
— TBD —
Note
This module does not allocate or free any memory. These operations are left up to the caller.
Version
12/15/2004 (jfrank)
References DirtyMemFree(), NetResourceT::iCacheLen, NetResourceT::iFreeCacheLen, NetResourceT::iMemGroup, NETRSRC_ERROR_NONE, NETRSRC_MEMID, NULL, NetResourceT::pCache, NetResourceT::pMemGroupUserData, NetResourceCacheUsedListT::pNext, and NetResourceT::pUsedList.
DIRTYCODE_API int32_t NetResourceCacheCheck (NetResourceT * pState, const char * pResource, uint32_t uType, uint32_t uIdent)
Check to see if the cache contains the given resource.
Parameters
*pState - module state
*pResource - resource name (NULL if using type and ident)
uType - type of resource to check if pResource is NULL; else unused
uIdent - identity of resource to check if pResource is NULL; else unused
Returns
int32_t - 0=cache miss, 1=cache hit
Version
05/12/2006 (jbrookes)
References FALSE, NULL, NetResourceControlT::uIdent, and NetResourceControlT::uType.
DIRTYCODE_API void NetResourceCancel (NetResourceT * pState, int32_t iSeqNum)
Cancel an in-progress network transfer.
Parameters
*pState - module state
iSeqNum - Sequence number of the transaction to cancel
Note
If pXfer is NULL, cancel ALL pending transfers. Otherwise, run through the list of pending transfers and cancel only the requested tranfer.
Version
12/15/2004 (jfrank)
References NetResourceControlT::iSeqNum, NetResourceControlT::iStatus, NetPrintf, NETRSRC_PRINTFTYPEIDENT, NETRSRC_STAT_CANCEL, NULL, NetResourceControlT::pCallback, NetResourceControlT::pNext, NetResourceT::pXferCBList, NetResourceControlT::uIdent, and NetResourceControlT::uType.
DIRTYCODE_API NetResourceT* NetResourceCreate (const char * pHome)
Create network resource manager instance.
Parameters
*pHome - address of home server (normally downloaded from lobby server)
Returns
NetResourceT - pass this return value as the first parameter to all other functions
Version
12/15/2004 (jfrank)
References DirtyMemAlloc(), DirtyMemFree(), DirtyMemGroupQuery(), ds_strnzcpy(), NetResourceT::iMemGroup, NetConnIdleAdd(), NetPrintf, NETRSRC_HTTPSPOOLSIZE, NETRSRC_MEMID, NULL, NetResourceT::pHttp, NetResourceT::pMemGroupUserData, ProtoHttpCreate(), and NetResourceT::strHomeURL.
DIRTYCODE_API void NetResourceDestroy (NetResourceT * pState)
Destroy the network resource manager instance.
Parameters
*pState - module state
Version
12/15/2004 (jfrank)
References DirtyMemFree(), NetResourceT::iMemGroup, NetConnIdleDel(), NETRSRC_MEMID, NetResourceT::pHttp, NetResourceT::pMemGroupUserData, and ProtoHttpDestroy().
DIRTYCODE_API int32_t NetResourceFetch (NetResourceT * pState, NetResourceXferT * pXfer, const uint32_t uType, const uint32_t uIdent, NetResourceCallbackT * pCallback, const int32_t iTimeout, const int32_t iPriority)
Start a network transfer from a resource type and id value.
Parameters
*pState - module state
*pXfer - transfer descriptor
uType - type of resource to download
uIdent - identity of resource to download
*pCallback - function to call with update progress
iTimeout - number of milliseconds allowed for transaction
iPriority - NETRSRC_PRIO_* priority of item, if cache enabled (send 0 if don't care)
Returns
int32_t - Sequence number for the transaction, changes for each update Returns 0 if the request was for a cached entry and there's no sequence number to remember.
Note
The type/ident fields are internally translated into URLs via a mapping from the server and the file downloaded from a web server. The user supplied callback function handles buffer management and appending the data into the buffer. The timeout field lets the application specify a maximum time for the transfer.
Version
12/15/2004 (jfrank)
References DirtyMemAlloc(), DirtyMemFree(), NetResourceT::iMemGroup, NetResourceControlT::iPriority, NetResourceControlT::iSeqNum, NetResourceControlT::iStatus, NetResourceControlT::iTimeout, NetResourceT::iTotalSeqNum, NETRSRC_MEMID, NETRSRC_STAT_IDLE, NULL, NetResourceControlT::pCallback, NetResourceT::pCurrentXferCB, NetResourceT::pMemGroupUserData, NetResourceControlT::pNext, NetResourceControlT::pPrev, NetResourceControlT::pUserXfer, NetResourceT::pXferCBList, TRUE, NetResourceControlT::uIdent, and NetResourceControlT::uType.
Referenced by NetResourceFetchString().
DIRTYCODE_API int32_t NetResourceFetchString (NetResourceT * pState, NetResourceXferT * pXfer, const char * pResource, NetResourceCallbackT * pCallback, const int32_t iTimeout, const int32_t iPriority)
Start a network transfer from a resource string.
Parameters
*pState - module state
*pXfer - transfer descriptor
*pResource - string for resource to download
*pCallback - function to call with update progress
iTimeout - number of milliseconds allowed for transaction
iPriority - NETRSRC_PRIO_* priority of item, if cache enabled (send 0 if don't care)
Returns
Result of NetReourceFetch - see return codes for that function
Note
This is an adapter for the NetResourceFetch which allows game code to request a resource in string format as opposed to type and ident. The string sent to this function should be in the format: "<4-character type>-<numeric ID value>" An optional prefix of "netres:" may be added if required, but will be ignored by NetResourceFetch. Example: "netres:imag-001"
Version
02/22/2005 (jfrank)
References NetResourceFetch().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:56