// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EA.Eaconfig.Backends.VisualStudio
{
    using System;
    
    
    #line 1 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class AppXManifestTemplate : AppXManifestTemplateBase
    {
        public virtual string TransformText()
        {
            this.Write("<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<Package xmlns=\"http://schemas.microsoft." +
                    "com/appx/2010/manifest\">\r\n\r\n  <Identity Name=\"");
            
            #line 5 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write("\"\r\n            Publisher=\"CN=");
            
            #line 6 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Publisher));
            
            #line default
            #line hidden
            this.Write("\"\r\n            Version=\"");
            
            #line 7 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Version));
            
            #line default
            #line hidden
            this.Write("\" />\r\n\r\n  <Properties>\r\n    <DisplayName>");
            
            #line 10 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PropertiesDisplayName));
            
            #line default
            #line hidden
            this.Write("</DisplayName>\r\n    <PublisherDisplayName>");
            
            #line 11 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PublisherDisplayName));
            
            #line default
            #line hidden
            this.Write("</PublisherDisplayName>\r\n    <Logo>");
            
            #line 12 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PropertiesLogo));
            
            #line default
            #line hidden
            this.Write("</Logo>\r\n    <Description>");
            
            #line 13 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PropertiesDescription));
            
            #line default
            #line hidden
            this.Write(@"</Description>
  </Properties>

  <Prerequisites>
    <OSMinVersion>6.2.0</OSMinVersion>
    <OSMaxVersionTested>6.2.0</OSMaxVersionTested>
  </Prerequisites>

  <Resources>
    <Resource Language=""x-generate""/>
  </Resources>

  <Applications>
    <Application Id=""");
            
            #line 26 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApplicationId));
            
            #line default
            #line hidden
            this.Write("\"\r\n        Executable=\"");
            
            #line 27 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Executable));
            
            #line default
            #line hidden
            this.Write("\"\r\n        EntryPoint=\"");
            
            #line 28 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntryPoint));
            
            #line default
            #line hidden
            this.Write("\">\r\n        <VisualElements\r\n            DisplayName=\"");
            
            #line 30 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(VisualElementsDisplayName));
            
            #line default
            #line hidden
            this.Write("\"\r\n            Logo=\"");
            
            #line 31 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(VisualElementsLogo));
            
            #line default
            #line hidden
            this.Write("\"\r\n            SmallLogo=\"");
            
            #line 32 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(VisualElementsSmallLogo));
            
            #line default
            #line hidden
            this.Write("\"\r\n            Description=\"");
            
            #line 33 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(VisualElementsDescription));
            
            #line default
            #line hidden
            this.Write("\"\r\n            ForegroundText=\"light\"\r\n            BackgroundColor=\"#464646\">\r\n  " +
                    "          <DefaultTile ShowName=\"allLogos\"\r\n");
            
            #line 37 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
          if (WideLogo != null)
            { 
            
            #line default
            #line hidden
            this.Write("                WideLogo=\"");
            
            #line 39 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WideLogo));
            
            #line default
            #line hidden
            this.Write("\"\r\n");
            
            #line 40 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
          } 
            
            #line default
            #line hidden
            this.Write("            />\r\n            <SplashScreen Image=\"");
            
            #line 42 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SplashScreen));
            
            #line default
            #line hidden
            this.Write("\" />\r\n        </VisualElements>\r\n");
            
            #line 44 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
      if(Extensions.Count > 0) 
        { 
            
            #line default
            #line hidden
            this.Write("          <Extensions>\r\n            ");
            
            #line 47 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
  foreach(var extension in Extensions)
            { 
            
            #line default
            #line hidden
            this.Write("               ");
            
            #line 49 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(extension));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 50 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
          } 
            
            #line default
            #line hidden
            this.Write("          </Extensions>\r\n");
            
            #line 52 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
      } 
            
            #line default
            #line hidden
            this.Write("    </Application>\r\n  </Applications>\r\n  <Capabilities>\r\n");
            
            #line 56 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
  foreach(var capability in Capabilities)
    { 
            
            #line default
            #line hidden
            this.Write("    <Capability Name=\"");
            
            #line 58 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(capability));
            
            #line default
            #line hidden
            this.Write("\" />\r\n");
            
            #line 59 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
  } 
            
            #line default
            #line hidden
            
            #line 60 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
  foreach(var deviceCapability in DeviceCapabilities)
    { 
            
            #line default
            #line hidden
            this.Write("    <DeviceCapability Name=\"");
            
            #line 62 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(deviceCapability));
            
            #line default
            #line hidden
            this.Write("\" />\r\n");
            
            #line 63 "D:\packages\Framework\dev\source\EA.Tasks\EA.Config\Backends\VisualStudio\sln\AppXManifestTemplate.tt"
  } 
            
            #line default
            #line hidden
            this.Write("  </Capabilities>\r\n</Package>\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public class AppXManifestTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
