DirtySock: ProtoStream
ProtoStream
Proto
Macros
#define PROTOSTREAM_FREQ_ONCE (-1)
one time play
#define PROTOSTREAM_FREQ_IMMED (0)
immediate restart
Typedefs
typedef enum ProtoStreamStatusE ProtoStreamStatusE
callback status indicating state of the stream
typedef struct ProtoStreamRefT ProtoStreamRefT
opaque module state
typedef int32_t(ProtoStreamCallbackT)(ProtoStreamRefT *pProtoStream, ProtoStreamStatusE eStatus, const uint8_t *pBuffer, int32_t iBufSize, void *pUserData)
data callback definition
Enumerations
enum ProtoStreamStatusE {
PROTOSTREAM_STATUS_BEGIN = 0,
PROTOSTREAM_STATUS_DATA,
PROTOSTREAM_STATUS_SYNC,
PROTOSTREAM_STATUS_DONE
}
callback status indicating state of the stream
Functions
DIRTYCODE_API ProtoStreamRefT * ProtoStreamCreate (int32_t iBufSize)
Create the stream module.
DIRTYCODE_API void ProtoStreamDestroy (ProtoStreamRefT *pProtoStream)
Destroy the ProtoStream module.
DIRTYCODE_API void ProtoStreamSetCallback (ProtoStreamRefT *pProtoStream, int32_t iRate, ProtoStreamCallbackT *pCallback, void *pUserData)
Set recurring ProtoStream callback.
DIRTYCODE_API void ProtoStreamSetHttpCallback (ProtoStreamRefT *pProtoStream, ProtoHttpCustomHeaderCbT *pCustomHeaderCb, ProtoHttpReceiveHeaderCbT *pReceiveHeaderCb, void *pUserData)
Set custom callbacks for ProtoHttp ref managed by ProtoStream.
DIRTYCODE_API int32_t ProtoStreamOpen (ProtoStreamRefT *pProtoStream, const char *pUrl, int32_t iFreq)
Begin streaming an Internet media source.
DIRTYCODE_API int32_t ProtoStreamRead (ProtoStreamRefT *pProtoStream, char *pBuffer, int32_t iBufLen, int32_t iMinLen)
Read at least iMinLen bytes from stream into user buffer.
DIRTYCODE_API void ProtoStreamPause (ProtoStreamRefT *pProtoStream, uint8_t bPause)
Pause/unpause stream.
DIRTYCODE_API void ProtoStreamClose (ProtoStreamRefT *pProtoStream)
Stop streaming.
DIRTYCODE_API int32_t ProtoStreamStatus (ProtoStreamRefT *pProtoStream, int32_t iStatus, void *pBuffer, int32_t iBufSize)
Get module status.
DIRTYCODE_API int32_t ProtoStreamControl (ProtoStreamRefT *pProtoStream, int32_t iControl, int32_t iValue, int32_t iValue2, void *pValue)
Set control options.
DIRTYCODE_API void ProtoStreamUpdate (ProtoStreamRefT *pProtoStream)
Update the ProtoStream module.
Detailed Description
Macro Definition Documentation
#define PROTOSTREAM_FREQ_IMMED (0)
immediate restart
#define PROTOSTREAM_FREQ_ONCE (-1)
one time play
Referenced by ProtoStreamUpdate().
Typedef Documentation
typedef int32_t(ProtoStreamCallbackT)(ProtoStreamRefT *pProtoStream, ProtoStreamStatusE eStatus, const uint8_t *pBuffer, int32_t iBufSize, void *pUserData)
data callback definition
typedef struct ProtoStreamRefT ProtoStreamRefT
opaque module state
typedef enum ProtoStreamStatusE ProtoStreamStatusE
callback status indicating state of the stream
Enumeration Type Documentation
enum ProtoStreamStatusE
callback status indicating state of the stream
Enumerator
PROTOSTREAM_STATUS_BEGIN
first buffer of data (start of stream)
PROTOSTREAM_STATUS_DATA
data has been received
PROTOSTREAM_STATUS_SYNC
data was dropped from the stream
PROTOSTREAM_STATUS_DONE
end of stream (no data)
Function Documentation
DIRTYCODE_API void ProtoStreamClose (ProtoStreamRefT * pProtoStream)
Stop streaming.
Parameters
*pProtoStream - pointer to module state
Version
11/16/2005 (jbrookes)
DIRTYCODE_API int32_t ProtoStreamControl (ProtoStreamRefT * pProtoStream, int32_t iControl, int32_t iValue, int32_t iValue2, void * pValue)
Set control options.
Parameters
*pProtoStream - pointer to module state
iControl - control selector
iValue - selector specific
iValue2 - selector specific
*pValue - selector specific
Returns
int32_t - selector specific
Note
iStatus can be one of the following:
        'play' - set whether playing or not (client timeout is disabled if not playing)
        'spam' - set verbose debug level (debug only)
        'strv' - set number of seconds to starve input (debug only)
        'xhtp' - Select XHTTP (TRUE) or ProtoHttp (FALSE) (default=FALSE) (xenon only)
Unhandled codes are passed through to ProtoHttpControl().
Version
11/16/2005 (jbrookes)
References ProtoStreamRefT::bVerbose, FALSE, ProtoStreamRefT::iTimeout, NetPrintf, NetTick(), NULL, ProtoStreamRefT::pProtoHttp, and ProtoHttpControl().
DIRTYCODE_API ProtoStreamRefT* ProtoStreamCreate (int32_t iBufSize)
Create the stream module.
Parameters
iBufSize - size of streaming buffer (at least PROTOSTREAM_MINBUFFER)
Returns
ProtoStreamRefT * - new module state, or NULL
Version
11/16/2005 (jbrookes)
References ProtoStreamRefT::aBuffer, DirtyMemAlloc(), DirtyMemFree(), DirtyMemGroupQuery(), ProtoStreamRefT::iBufSize, ProtoStreamRefT::iMemGroup, ProtoStreamRefT::iTimeout, NetPrintf, NULL, ProtoStreamRefT::pCallback, ProtoStreamRefT::pMemGroupUserData, ProtoStreamRefT::pProtoHttp, ProtoHttpControl(), ProtoHttpCreate(), PROTOSTREAM_MEMID, and PROTOSTREAM_MINBUFFER.
DIRTYCODE_API void ProtoStreamDestroy (ProtoStreamRefT * pProtoStream)
Destroy the ProtoStream module.
Parameters
*pProtoStream - pointer to module state
Returns
None.
Version
11/16/2005 (jbrookes)
References DirtyMemFree(), ProtoStreamRefT::iMemGroup, ProtoStreamRefT::pMemGroupUserData, ProtoStreamRefT::pProtoHttp, ProtoHttpDestroy(), and PROTOSTREAM_MEMID.
DIRTYCODE_API int32_t ProtoStreamOpen (ProtoStreamRefT * pProtoStream, const char * pUrl, int32_t iFreq)
Begin streaming an Internet media source.
Parameters
*pProtoStream - pointer to module state
*pUrl - resource to stream
iFreq - restart frequency in seconds, or PROTOSTREAM_FREQ_*
Returns
int32_t - negative=failure, else success
Version
11/16/2005 (jbrookes)
References ProtoStreamRefT::iBufSize, ProtoStreamRefT::iLastModified, ProtoStreamRefT::iLastSize, ProtoStreamRefT::iRestartIncr, and ProtoStreamRefT::iRestartThreshold.
DIRTYCODE_API void ProtoStreamPause (ProtoStreamRefT * pProtoStream, uint8_t bPause)
Pause/unpause stream.
Parameters
*pProtoStream - pointer to module state
bPause - TRUE to pause, else FALSE
Version
01/25/2012 (jbrookes)
References ProtoStreamRefT::bPaused, ProtoStreamRefT::iTimeout, NetPrintf, NULL, ProtoStreamRefT::pProtoHttp, ProtoHttpControl(), and TRUE.
DIRTYCODE_API int32_t ProtoStreamRead (ProtoStreamRefT * pProtoStream, char * pBuffer, int32_t iBufLen, int32_t iMinLen)
Read at least iMinLen bytes from stream into user buffer.
Parameters
*pProtoStream - pointer to module state
*pBuffer - [out] output buffer
iBufLen - size of output buffer
iMinLen - minimum amount of data to copy
Returns
int32_t - number of bytes copied; negative=stream not open
Version
11/21/2005 (jbrookes)
References ProtoStreamRefT::aBuffer, ProtoStreamRefT::bPaused, ProtoStreamRefT::bPrebuffering, ProtoStreamRefT::bVerbose, ds_memcpy(), ProtoStreamRefT::eState, ProtoStreamRefT::iBufLen, ProtoStreamRefT::iBufOut, ProtoStreamRefT::iBufSize, NetPrintf, NetPrintfVerbose, and TRUE.
DIRTYCODE_API void ProtoStreamSetCallback (ProtoStreamRefT * pProtoStream, int32_t iRate, ProtoStreamCallbackT * pCallback, void * pUserData)
Set recurring ProtoStream callback.
Parameters
*pProtoStream - pointer to module state
iRate - callback rate in ms
*pCallback - data callback
*pUserData - user data for callback
Version
11/16/2005 (jbrookes)
References ProtoStreamRefT::iCallbackRate, NULL, ProtoStreamRefT::pCallback, and ProtoStreamRefT::pUserData.
DIRTYCODE_API void ProtoStreamSetHttpCallback (ProtoStreamRefT * pProtoStream, ProtoHttpCustomHeaderCbT * pCustomHeaderCb, ProtoHttpReceiveHeaderCbT * pReceiveHeaderCb, void * pUserData)
Set custom callbacks for ProtoHttp ref managed by ProtoStream.
Parameters
*pProtoStream - pointer to module state
*pCustomHeaderCb - pointer to custom send header callback (may be NULL)
*pReceiveHeaderCb- pointer to recv header callback (may be NULL)
*pUserData - user-supplied callback ref (may be NULL)
Version
10/26/2011 (jbrookes)
References ProtoStreamRefT::pProtoHttp, and ProtoHttpCallback().
DIRTYCODE_API int32_t ProtoStreamStatus (ProtoStreamRefT * pProtoStream, int32_t iStatus, void * pBuffer, int32_t iBufSize)
Get module status.
Parameters
*pProtoStream - pointer to module state
iStatus - status selector
*pBuffer - selector specific
iBufSize - selector specific
Returns
int32_t - selector specific
Note
iStatus can be one of the following:
        'bufl' - amount of data currently buffered
        'bufs' - size of current stream buffer
        'code' - most recent http result code
        'done' - stream status: -1=error, 0=in progress, 1=complete
Unrecognized codes are passed through to ProtoHttpStatus().
Version
11/16/2005 (jbrookes)
References ProtoStreamRefT::iBufLen, ProtoStreamRefT::iBufSize, ProtoStreamRefT::iLastHttpCode, ProtoStreamRefT::iStreamStatus, ProtoStreamRefT::pProtoHttp, and ProtoHttpStatus().
DIRTYCODE_API void ProtoStreamUpdate (ProtoStreamRefT * pProtoStream)
Update the ProtoStream module.
Parameters
*pProtoStream - pointer to module state
Version
11/16/2005 (jbrookes)
References ds_strnzcpy(), ProtoStreamRefT::eState, ProtoStreamRefT::iBufLen, ProtoStreamRefT::iRestartFreq, ProtoStreamRefT::iRestartTime, ProtoStreamRefT::iStreamStatus, NetTick(), NetTickDiff, ProtoStreamRefT::pProtoHttp, ProtoHttpUpdate(), PROTOSTREAM_FREQ_ONCE, PROTOSTREAM_MAXURL, ST_IDLE, and ProtoStreamRefT::strUrl.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:32