DirtySock: CryptMD2
CryptMD2
Crypt
Data Structures
struct CryptMD2T
all fields are PRIVATE
Macros
#define MD2_BINARY_OUT 16
length of binary output
#define MD2_STRING_OUT 33
length of string output
Typedefs
typedef struct CryptMD2T CryptMD2T
Functions
DIRTYCODE_API void CryptMD2Init (CryptMD2T *pContext)
Init the MD2 context.
DIRTYCODE_API void CryptMD2Init2 (CryptMD2T *pContext, int32_t iHashSize)
Init the MD2 context, alternate version.
DIRTYCODE_API void CryptMD2Update (CryptMD2T *pContext, const void *pBuffer, int32_t iLength)
Add data to the MD2 context (hash the data).
DIRTYCODE_API void CryptMD2Final (CryptMD2T *pContext, void *pBuffer, int32_t iLength)
Convert MD2 state into final output form.
Detailed Description
Macro Definition Documentation
#define MD2_BINARY_OUT 16
length of binary output
Referenced by CryptMD2Final().
#define MD2_STRING_OUT 33
length of string output
Typedef Documentation
typedef struct CryptMD2T CryptMD2T
Function Documentation
DIRTYCODE_API void CryptMD2Final (CryptMD2T * pContext, void * _pBuffer, int32_t iLength)
Convert MD2 state into final output form.
Parameters
*pContext - the MD2 state (from create)
*_pBuffer - the digest output
iLength - length of output buffer
Returns
None.
Version
03/19/2009 (jbrookes)
References CryptMD2T::aChecksum, CryptMD2T::aState, CryptMD2Update(), ds_memcpy(), CryptMD2T::iCount, MD2_BINARY_OUT, and NetPrintf.
DIRTYCODE_API void CryptMD2Init (CryptMD2T * pContext)
Init the MD2 context.
Parameters
*pContext - target MD2 context
Returns
None.
Version
03/19/2009 (jbrookes)
Referenced by CryptMD2Init2().
DIRTYCODE_API void CryptMD2Init2 (CryptMD2T * pContext, int32_t iHashSize)
Init the MD2 context, alternate version.
Parameters
*pContext - target MD2 context
iHashSize - hash size (ignored)
Returns
None.
Version
03/07/2014 (jbrookes)
References CryptMD2Init().
DIRTYCODE_API void CryptMD2Update (CryptMD2T * pContext, const void * _pBuffer, int32_t iLength)
Add data to the MD2 context (hash the data).
Parameters
*pContext - target MD2 context
*_pBuffer - input data to hash
iLength - length of buffer (-1=treat pBuffer as asciiz)
Returns
None.
Version
03/19/2009 (jbrookes)
References CryptMD2T::aBuffer, ds_memcpy(), and CryptMD2T::iCount.
Referenced by CryptMD2Final().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:56