DirtySock: CryptStp1
CryptStp1
Crypt
Data Structures
struct CryptStp1StreamT
stream encryption state
struct CryptStp1SharedT
shared secret used to generate tickets
struct CryptStp1SecretT
private secret used to stream encryption
struct CryptStp1TicketT
ticket used to pass stream crypto keys
struct CryptStp1WalletT
wallet containing seret keys & ticket
Typedefs
typedef struct CryptStp1StreamT CryptStp1StreamT
stream encryption state
typedef struct CryptStp1SharedT CryptStp1SharedT
shared secret used to generate tickets
typedef struct CryptStp1SecretT CryptStp1SecretT
private secret used to stream encryption
typedef struct CryptStp1TicketT CryptStp1TicketT
ticket used to pass stream crypto keys
typedef struct CryptStp1WalletT CryptStp1WalletT
wallet containing seret keys & ticket
Functions
DIRTYCODE_API void CryptStp1SetShared (CryptStp1SharedT *pShared, const void *pData, uint32_t uDataSize)
Set the master shared secret that is used for encrypting tickets.
DIRTYCODE_API void CryptStp1MakeWallet (CryptStp1WalletT *pWallet, CryptStp1SharedT *pShared, uint32_t uTime, const char *pRandom)
Create new wallet containing secret keys and a ticket.
DIRTYCODE_API int32_t CryptStp1OpenWallet (CryptStp1WalletT *pWallet, CryptStp1SecretT *pSecret, CryptStp1TicketT *pTicket)
Open the wallet and remove the secret and ticket.
DIRTYCODE_API int32_t CryptStp1UseSecret (CryptStp1StreamT *pStream, CryptStp1SecretT *pSecret)
USe the secret keys to initialize the session stream.
DIRTYCODE_API int32_t CryptStp1UseTicket (CryptStp1StreamT *pStream, CryptStp1TicketT *pTicket, CryptStp1SharedT *pShared, uint32_t uTime)
USe the secret keys to initialize the session stream.
DIRTYCODE_API void CryptStp1DecryptData (CryptStp1StreamT *pStream, char *pData, int32_t iSize)
Decrypt data from a stream.
DIRTYCODE_API int32_t CryptStp1DecryptHash (CryptStp1StreamT *pStream, char *pData, int32_t iSize)
Decrypt data from a stream. Return code indicates error. You must check and obey this result.
DIRTYCODE_API int32_t CryptStp1DecryptSize (CryptStp1StreamT *pStream, int32_t iSize)
Return the updated packet size (will remove hash if present)
DIRTYCODE_API int32_t CryptStp1EncryptSize (CryptStp1StreamT *pStream, int32_t iSize)
Return the updated packet size (will remove hash if present)
DIRTYCODE_API int32_t CryptStp1EncryptHash (CryptStp1StreamT *pStream, char *pData, int32_t iSize)
Calculate and append the packet hash. Call after CryptStp1EncryptSize.
DIRTYCODE_API void CryptStp1EncryptData (CryptStp1StreamT *pStream, char *pData, int32_t iSize)
Encrypt the packet data.
DIRTYCODE_API int32_t CryptStp1Enabled (CryptStp1StreamT *pStream)
Determine if encryption is enabled for the given instance.
Detailed Description
Typedef Documentation
typedef struct CryptStp1SecretT CryptStp1SecretT
private secret used to stream encryption
typedef struct CryptStp1SharedT CryptStp1SharedT
shared secret used to generate tickets
typedef struct CryptStp1StreamT CryptStp1StreamT
stream encryption state
typedef struct CryptStp1TicketT CryptStp1TicketT
ticket used to pass stream crypto keys
typedef struct CryptStp1WalletT CryptStp1WalletT
wallet containing seret keys & ticket
Function Documentation
DIRTYCODE_API void CryptStp1DecryptData (CryptStp1StreamT * pStream, char * pData, int32_t iSize)
Decrypt data from a stream.
Parameters
*pStream - the session stream
*pData - the data to decrypt
iSize - size of the data
Returns
None
Version
1.0 03/28/2004 (gschaefer) First Version
References CryptStp1StreamT::bDecrypt, CryptStp1StreamT::bEncrypt, CryptArc4Apply(), and CryptStp1StreamT::RecvArc4.
Referenced by ProtoAriesUpdate().
DIRTYCODE_API int32_t CryptStp1DecryptHash (CryptStp1StreamT * pStream, char * pData, int32_t iSize)
Decrypt data from a stream. Return code indicates error. You must check and obey this result.
Parameters
*pStream - the session stream
*pData - the data to decrypt
iSize - size of the data
Returns
int32_t - negative=error, zero=success
Version
1.0 03/28/2004 (gschaefer) First Version
References CryptStp1StreamT::bDecrypt, CryptStp1StreamT::bEncrypt, CryptMD5Final(), CryptMD5Init(), CryptMD5Update(), and MD5_BINARY_OUT.
Referenced by ProtoAriesUpdate().
DIRTYCODE_API int32_t CryptStp1DecryptSize (CryptStp1StreamT * pStream, int32_t iSize)
Return the updated packet size (will remove hash if present)
Parameters
*pStream - the session stream
iSize - size of the data
Returns
int32_t - updated packet size
Version
1.0 03/28/2004 (gschaefer) First Version
References CryptStp1StreamT::bDecrypt, CryptStp1StreamT::bEncrypt, and MD5_BINARY_OUT.
Referenced by ProtoAriesUpdate().
DIRTYCODE_API int32_t CryptStp1Enabled (CryptStp1StreamT * pStream)
Determine if encryption is enabled for the given instance.
Parameters
pStream - Stream to check for encryption status.
Returns
int32_t - 0=disabled; else enabled
Version
05/31/2005 (doneill)
References CryptStp1StreamT::bDecrypt, and CryptStp1StreamT::bEncrypt.
DIRTYCODE_API void CryptStp1EncryptData (CryptStp1StreamT * pStream, char * pData, int32_t iSize)
Encrypt the packet data.
Parameters
*pStream - the session stream
*pData - the data contaning hash
iSize - size of the data
Returns
None
Version
1.0 03/28/2004 (gschaefer) First Version
References CryptStp1StreamT::bEncrypt, CryptArc4Apply(), and CryptStp1StreamT::SendArc4.
Referenced by ProtoAriesSend().
DIRTYCODE_API int32_t CryptStp1EncryptHash (CryptStp1StreamT * pStream, char * pData, int32_t iSize)
Calculate and append the packet hash. Call after CryptStp1EncryptSize.
Parameters
*pStream - the session stream
*pData - the data contaning hash
iSize - size of the data
Returns
int32_t - negative=error, zero=success
Version
1.0 03/28/2004 (gschaefer) First Version
References CryptStp1StreamT::bEncrypt, CryptMD5Final(), CryptMD5Init(), CryptMD5Update(), and MD5_BINARY_OUT.
Referenced by ProtoAriesSend().
DIRTYCODE_API int32_t CryptStp1EncryptSize (CryptStp1StreamT * pStream, int32_t iSize)
Return the updated packet size (will remove hash if present)
Parameters
*pStream - the session stream
iSize - size of the data
Returns
int32_t - updated packet size
Version
1.0 03/28/2004 (gschaefer) First Version
References CryptStp1StreamT::bEncrypt, and MD5_BINARY_OUT.
Referenced by ProtoAriesSend().
DIRTYCODE_API void CryptStp1MakeWallet (CryptStp1WalletT * pWallet, CryptStp1SharedT * pShared, uint32_t uTime, const char * pRandom)
Create new wallet containing secret keys and a ticket.
Parameters
*pWallet - pointer to wallet output record
*pShared - the shared secret (for encrypting ticket)
uTime - curent time (to expire tickets)
*pRandom - random data used in secret key generation
Returns
None
Version
1.0 03/28/2004 (gschaefer) First Version
1.1 05/05/2004 (sbevan) Now initialized ticket IV.
References CryptArc4Apply(), CryptArc4Init(), CryptMD5Final(), CryptMD5Init(), CryptMD5Update(), ds_memcpy_s(), ds_snzprintf(), CryptStp1TicketT::Encrypted, CryptStp1TicketT::IV, MD5_BINARY_OUT, CryptStp1TicketT::Plain, CryptStp1TicketT::Secret, CryptStp1WalletT::Secret, CryptStp1SecretT::strRecv, CryptStp1SecretT::strSend, CryptStp1WalletT::Ticket, and CryptStp1TicketT::uTime.
DIRTYCODE_API int32_t CryptStp1OpenWallet (CryptStp1WalletT * pWallet, CryptStp1SecretT * pSecret, CryptStp1TicketT * pTicket)
Open the wallet and remove the secret and ticket.
Parameters
*pWallet - pointer to wallet output record
*pSecret - where to store the secret
*pTicket - where to store the ticket
Returns
<0 - error, the wallet is is malformed >0 - wallet is is valid
Note
pSecret and pTicket are only updated if the return value > 0.
Version
1.0 03/28/2004 (gschaefer) First Version
References ds_memcpy_s(), NULL, CryptStp1WalletT::Secret, and CryptStp1WalletT::Ticket.
Referenced by ProtoAriesConnect().
DIRTYCODE_API void CryptStp1SetShared (CryptStp1SharedT * pShared, const void * pData, uint32_t uDataSize)
Set the master shared secret that is used for encrypting tickets.
Parameters
*pShared - the shared secret (CryptStp1SharedT)
*pData - the shared secret (in binary)
*uDataSize - the number of bytes in the secret
Returns
none
Note
If pData points to less than 32 bytes of cryptographically random data then it will result in a weak master key.
Version
1.0 03/28/2004 (gschaefer) First Version
2.0 05/05/2004 (sbevan) Changed to take uDataSize argument
References ds_memcpy(), and CryptStp1SharedT::strSecret.
DIRTYCODE_API int32_t CryptStp1UseSecret (CryptStp1StreamT * pStream, CryptStp1SecretT * pSecret)
USe the secret keys to initialize the session stream.
Parameters
*pStream - the session stream
*pSecret - the secret keys
Returns
<0 - error, =0 - don't encrypt, >0 - encrypt
Version
1.0 03/28/2004 (gschaefer) First Version
References CryptStp1StreamT::bDecrypt, CryptStp1StreamT::bEncrypt, CryptArc4Init(), NULL, CryptStp1StreamT::RecvArc4, CryptStp1StreamT::SendArc4, CryptStp1SecretT::strRecv, and CryptStp1SecretT::strSend.
Referenced by ProtoAriesConnect(), ProtoAriesSetKey(), and ProtoAriesUpdate().
DIRTYCODE_API int32_t CryptStp1UseTicket (CryptStp1StreamT * pStream, CryptStp1TicketT * pTicket, CryptStp1SharedT * pShared, uint32_t uTime)
USe the secret keys to initialize the session stream.
Parameters
*pStream - the session stream
*pTicket - the session ticket
*pShared - the shared secret (to decrypt the ticket)
uTime - current time (to expire the ticket)
Returns
<0 - error, =0 - don't encrypt, >0 - encrypt
Version
1.0 03/28/2004 (gschaefer) First Version
References CryptStp1StreamT::bDecrypt, CryptStp1StreamT::bEncrypt, CryptArc4Apply(), CryptArc4Init(), ds_memcpy_s(), CryptStp1TicketT::Encrypted, MAX_TICKET_AGE, NULL, CryptStp1StreamT::RecvArc4, CryptStp1TicketT::Secret, CryptStp1StreamT::SendArc4, CryptStp1SecretT::strRecv, CryptStp1SecretT::strSend, and CryptStp1TicketT::uTime.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:31