/*H********************************************************************************/
/*!
    \File dirtyerrpsp2.c

    \Description
        Dirtysock debug error routines.

    \Copyright
        Copyright (c) 2010 Electronic Arts Inc.

    \Version 11/02/2010 (jbrookes) Ported from PS3
*/
/********************************************************************************H*/

/*** Include files ****************************************************************/
#include <sdk_version.h>

// error includes
#include <sceerror.h>
#include <kernel/error.h>
#include <net/errno.h>
#include <np/np_error.h>
#include <libnetctl.h>

#include "dirtysock.h"
#include "dirtyerr.h"

/*** Defines **********************************************************************/

/*** Type Definitions *************************************************************/

/*** Variables ********************************************************************/

#if DIRTYSOCK_ERRORNAMES
static DirtyErrT _DirtyErr_List[] =
{
    /*
        errno.h error codes
    */
    DIRTYSOCK_ErrorName(SCE_NET_EPERM),                     // 1
    DIRTYSOCK_ErrorName(SCE_NET_ENOENT),                    // 2
    DIRTYSOCK_ErrorName(SCE_NET_ESRCH),                     // 3
    DIRTYSOCK_ErrorName(SCE_NET_EINTR),                     // 4
    DIRTYSOCK_ErrorName(SCE_NET_EIO),                       // 5
    DIRTYSOCK_ErrorName(SCE_NET_ENXIO),                     // 6
    DIRTYSOCK_ErrorName(SCE_NET_E2BIG),                     // 7
    DIRTYSOCK_ErrorName(SCE_NET_ENOEXEC),                   // 8
    DIRTYSOCK_ErrorName(SCE_NET_EBADF),                     // 9
    DIRTYSOCK_ErrorName(SCE_NET_ECHILD),                    // 10
    DIRTYSOCK_ErrorName(SCE_NET_EDEADLK),                   // 11
    DIRTYSOCK_ErrorName(SCE_NET_ENOMEM),                    // 12
    DIRTYSOCK_ErrorName(SCE_NET_EACCES),                    // 13
    DIRTYSOCK_ErrorName(SCE_NET_EFAULT),                    // 14
    DIRTYSOCK_ErrorName(SCE_NET_ENOTBLK),                   // 15
    DIRTYSOCK_ErrorName(SCE_NET_EBUSY),                     // 16
    DIRTYSOCK_ErrorName(SCE_NET_EEXIST),                    // 17
    DIRTYSOCK_ErrorName(SCE_NET_EXDEV),                     // 18
    DIRTYSOCK_ErrorName(SCE_NET_ENODEV),                    // 19
    DIRTYSOCK_ErrorName(SCE_NET_ENOTDIR),                   // 20
    DIRTYSOCK_ErrorName(SCE_NET_EISDIR),                    // 21
    DIRTYSOCK_ErrorName(SCE_NET_EINVAL),                    // 22
    DIRTYSOCK_ErrorName(SCE_NET_ENFILE),                    // 23
    DIRTYSOCK_ErrorName(SCE_NET_EMFILE),                    // 24
    DIRTYSOCK_ErrorName(SCE_NET_ENOTTY),                    // 25
    DIRTYSOCK_ErrorName(SCE_NET_ETXTBSY),                   // 26
    DIRTYSOCK_ErrorName(SCE_NET_EFBIG),                     // 27
    DIRTYSOCK_ErrorName(SCE_NET_ENOSPC),                    // 28
    DIRTYSOCK_ErrorName(SCE_NET_ESPIPE),                    // 29
    DIRTYSOCK_ErrorName(SCE_NET_EROFS),                     // 30
    DIRTYSOCK_ErrorName(SCE_NET_EMLINK),                    // 31
    DIRTYSOCK_ErrorName(SCE_NET_EPIPE),                     // 32
    DIRTYSOCK_ErrorName(SCE_NET_EDOM),                      // 33
    DIRTYSOCK_ErrorName(SCE_NET_ERANGE),                    // 34
    DIRTYSOCK_ErrorName(SCE_NET_EAGAIN),                    // 35
    DIRTYSOCK_ErrorName(SCE_NET_EWOULDBLOCK),               // SCE_NET_EAGAIN
    DIRTYSOCK_ErrorName(SCE_NET_EINPROGRESS),               // 36
    DIRTYSOCK_ErrorName(SCE_NET_EALREADY),                  // 37
    DIRTYSOCK_ErrorName(SCE_NET_ENOTSOCK),                  // 38
    DIRTYSOCK_ErrorName(SCE_NET_EDESTADDRREQ),              // 39
    DIRTYSOCK_ErrorName(SCE_NET_EMSGSIZE),                  // 40
    DIRTYSOCK_ErrorName(SCE_NET_EPROTOTYPE),                // 41
    DIRTYSOCK_ErrorName(SCE_NET_ENOPROTOOPT),               // 42
    DIRTYSOCK_ErrorName(SCE_NET_EPROTONOSUPPORT),           // 43
    DIRTYSOCK_ErrorName(SCE_NET_ESOCKTNOSUPPORT),           // 44
    DIRTYSOCK_ErrorName(SCE_NET_EOPNOTSUPP),                // 45
    DIRTYSOCK_ErrorName(SCE_NET_EPFNOSUPPORT),              // 46
    DIRTYSOCK_ErrorName(SCE_NET_EAFNOSUPPORT),              // 47
    DIRTYSOCK_ErrorName(SCE_NET_EADDRINUSE),                // 48
    DIRTYSOCK_ErrorName(SCE_NET_EADDRNOTAVAIL),             // 49
    DIRTYSOCK_ErrorName(SCE_NET_ENETDOWN),                  // 50
    DIRTYSOCK_ErrorName(SCE_NET_ENETUNREACH),               // 51
    DIRTYSOCK_ErrorName(SCE_NET_ENETRESET),                 // 52
    DIRTYSOCK_ErrorName(SCE_NET_ECONNABORTED),              // 53
    DIRTYSOCK_ErrorName(SCE_NET_ECONNRESET),                // 54
    DIRTYSOCK_ErrorName(SCE_NET_ENOBUFS),                   // 55
    DIRTYSOCK_ErrorName(SCE_NET_EISCONN),                   // 56
    DIRTYSOCK_ErrorName(SCE_NET_ENOTCONN),                  // 57
    DIRTYSOCK_ErrorName(SCE_NET_ESHUTDOWN),                 // 58
    DIRTYSOCK_ErrorName(SCE_NET_ETOOMANYREFS),              // 59
    DIRTYSOCK_ErrorName(SCE_NET_ETIMEDOUT),                 // 60
    DIRTYSOCK_ErrorName(SCE_NET_ECONNREFUSED),              // 61
    DIRTYSOCK_ErrorName(SCE_NET_ELOOP),                     // 62
    DIRTYSOCK_ErrorName(SCE_NET_ENAMETOOLONG),              // 63
    DIRTYSOCK_ErrorName(SCE_NET_EHOSTDOWN),                 // 64
    DIRTYSOCK_ErrorName(SCE_NET_EHOSTUNREACH),              // 65
    DIRTYSOCK_ErrorName(SCE_NET_ENOTEMPTY),                 // 66
    DIRTYSOCK_ErrorName(SCE_NET_EPROCLIM),                  // 67
    DIRTYSOCK_ErrorName(SCE_NET_EUSERS),                    // 68
    DIRTYSOCK_ErrorName(SCE_NET_EDQUOT),                    // 69
    DIRTYSOCK_ErrorName(SCE_NET_ESTALE),                    // 70
    DIRTYSOCK_ErrorName(SCE_NET_EREMOTE),                   // 71
    DIRTYSOCK_ErrorName(SCE_NET_EBADRPC),                   // 72
    DIRTYSOCK_ErrorName(SCE_NET_ERPCMISMATCH),              // 73
    DIRTYSOCK_ErrorName(SCE_NET_EPROGUNAVAIL),              // 74
    DIRTYSOCK_ErrorName(SCE_NET_EPROGMISMATCH),             // 75
    DIRTYSOCK_ErrorName(SCE_NET_EPROCUNAVAIL),              // 76
    DIRTYSOCK_ErrorName(SCE_NET_ENOLCK),                    // 77
    DIRTYSOCK_ErrorName(SCE_NET_ENOSYS),                    // 78
    DIRTYSOCK_ErrorName(SCE_NET_EFTYPE),                    // 79
    DIRTYSOCK_ErrorName(SCE_NET_EAUTH),                     // 80
    DIRTYSOCK_ErrorName(SCE_NET_ENEEDAUTH),                 // 81
    DIRTYSOCK_ErrorName(SCE_NET_EIDRM),                     // 82
    DIRTYSOCK_ErrorName(SCE_NET_ENOMSG),                    // 83
    DIRTYSOCK_ErrorName(SCE_NET_EOVERFLOW),                 // 84
    DIRTYSOCK_ErrorName(SCE_NET_EILSEQ),                    // 85
    DIRTYSOCK_ErrorName(SCE_NET_ENOTSUP),                   // 86
    DIRTYSOCK_ErrorName(SCE_NET_ECANCELED),                 // 87
    DIRTYSOCK_ErrorName(SCE_NET_EBADMSG),                   // 88
    DIRTYSOCK_ErrorName(SCE_NET_ENODATA),                   // 89
    DIRTYSOCK_ErrorName(SCE_NET_ENOSR),                     // 90
    DIRTYSOCK_ErrorName(SCE_NET_ENOSTR),                    // 91
    DIRTYSOCK_ErrorName(SCE_NET_ETIME),                     // 92
    DIRTYSOCK_ErrorName(SCE_NET_EADHOC),                    // 160
    DIRTYSOCK_ErrorName(SCE_NET_EDISABLEDIF),               // 161
    DIRTYSOCK_ErrorName(SCE_NET_ERESUME),                   // 162
    DIRTYSOCK_ErrorName(SCE_NET_EIPADDRCHANGED),            // 163
    DIRTYSOCK_ErrorName(SCE_NET_EINACTIVEDISABLED),         // SCE_NET_EIPADDRCHANGED

    // libnet
    DIRTYSOCK_ErrorName(SCE_NET_ENOTINIT),                  // 200
    DIRTYSOCK_ErrorName(SCE_NET_ENOLIBMEM),                 // 201
    DIRTYSOCK_ErrorName(SCE_NET_ETLS),                      // 202
    DIRTYSOCK_ErrorName(SCE_NET_ECALLBACK),                 // 203
    DIRTYSOCK_ErrorName(SCE_NET_EINTERNAL),                 // 204
    DIRTYSOCK_ErrorName(SCE_NET_ERETURN),                   // 205
    // resolver
    DIRTYSOCK_ErrorName(SCE_NET_RESOLVER_EINTERNAL),        // 220
    DIRTYSOCK_ErrorName(SCE_NET_RESOLVER_EBUSY),            // 221
    DIRTYSOCK_ErrorName(SCE_NET_RESOLVER_ENOSPACE),         // 222
    DIRTYSOCK_ErrorName(SCE_NET_RESOLVER_EPACKET),          // 223
    DIRTYSOCK_ErrorName(SCE_NET_RESOLVER_ERESERVED224),     // 224
    DIRTYSOCK_ErrorName(SCE_NET_RESOLVER_ENODNS),           // 225
    DIRTYSOCK_ErrorName(SCE_NET_RESOLVER_ETIMEDOUT),        // 226
    DIRTYSOCK_ErrorName(SCE_NET_RESOLVER_ENOSUPPORT),       // 227
    DIRTYSOCK_ErrorName(SCE_NET_RESOLVER_EFORMAT),          // 228
    DIRTYSOCK_ErrorName(SCE_NET_RESOLVER_ESERVERFAILURE),   // 229
    DIRTYSOCK_ErrorName(SCE_NET_RESOLVER_ENOHOST),          // 230
    DIRTYSOCK_ErrorName(SCE_NET_RESOLVER_ENOTIMPLEMENTED),  // 231
    DIRTYSOCK_ErrorName(SCE_NET_RESOLVER_ESERVERREFUSED),   // 232
    DIRTYSOCK_ErrorName(SCE_NET_RESOLVER_ENORECORD),        // 233
    DIRTYSOCK_ErrorName(SCE_NET_RESOLVER_EALIGNMENT),       // 234

    /*
        errors from sceerror.h
    */
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EPERM),             // 0x80010001
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENOENT),            // 0x80010002
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ESRCH),             // 0x80010003
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EINTR),             // 0x80010004
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EIO),               // 0x80010005
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENXIO),             // 0x80010006
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_E2BIG),             // 0x80010007
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENOEXEC),           // 0x80010008
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EBADF),             // 0x80010009
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ECHILD),            // 0x8001000A
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EAGAIN),            // 0x8001000B
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENOMEM),            // 0x8001000C
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EACCES),            // 0x8001000D
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EFAULT),            // 0x8001000E
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENOTBLK),           // 0x8001000F
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EBUSY),             // 0x80010010
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EEXIST),            // 0x80010011
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EXDEV),             // 0x80010012
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENODEV),            // 0x80010013
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENOTDIR),           // 0x80010014
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EISDIR),            // 0x80010015
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EINVAL),            // 0x80010016
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENFILE),            // 0x80010017
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EMFILE),            // 0x80010018
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENOTTY),            // 0x80010019
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ETXTBSY),           // 0x8001001A
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EFBIG),             // 0x8001001B
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENOSPC),            // 0x8001001C
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ESPIPE),            // 0x8001001D
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EROFS),             // 0x8001001E
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EMLINK),            // 0x8001001F
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EPIPE),             // 0x80010020
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EDOM),              // 0x80010021
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ERANGE),            // 0x80010022
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENOMSG),            // 0x80010023
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EIDRM),             // 0x80010024
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ECHRNG),            // 0x80010025
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EL2NSYNC),          // 0x80010026
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EL3HLT),            // 0x80010027
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EL3RST),            // 0x80010028
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ELNRNG),            // 0x80010029
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EUNATCH),           // 0x8001002A
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENOCSI),            // 0x8001002B
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EL2HLT),            // 0x8001002C
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EDEADLK),           // 0x8001002D
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENOLCK),            // 0x8001002E
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EFORMAT),           // 0x8001002F
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EUNSUP),            // 0x80010030
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EBADE),             // 0x80010032
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EBADR),             // 0x80010033
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EXFULL),            // 0x80010034
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENOANO),            // 0x80010035
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EBADRQC),           // 0x80010036
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EBADSLT),           // 0x80010037
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EDEADLOCK),         // 0x80010038
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EBFONT),            // 0x80010039
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENOSTR),            // 0x8001003C
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENODATA),           // 0x8001003D
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ETIME),             // 0x8001003E
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENOSR),             // 0x8001003F
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENONET),            // 0x80010040
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENOPKG),            // 0x80010041
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EREMOTE),           // 0x80010042
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENOLINK),           // 0x80010043
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EADV),              // 0x80010044
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ESRMNT),            // 0x80010045
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ECOMM),             // 0x80010046
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EPROTO),            // 0x80010047
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EMULTIHOP),         // 0x8001004A
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ELBIN),             // 0x8001004B
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EDOTDOT),           // 0x8001004C
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EBADMSG),           // 0x8001004D
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EFTYPE),            // 0x8001004F
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENOTUNIQ),          // 0x80010050
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EBADFD),            // 0x80010051
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EREMCHG),           // 0x80010052
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ELIBACC),           // 0x80010053
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ELIBBAD),           // 0x80010054
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ELIBSCN),           // 0x80010055
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ELIBMAX),           // 0x80010056
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ELIBEXEC),          // 0x80010057
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENOSYS),            // 0x80010058
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENMFILE),           // 0x80010059
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENOTEMPTY),         // 0x8001005A
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENAMETOOLONG),      // 0x8001005B
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ELOOP),             // 0x8001005C
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EOPNOTSUPP),        // 0x8001005F
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EPFNOSUPPORT),      // 0x80010060
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ECONNRESET),        // 0x80010068
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENOBUFS),           // 0x80010069
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EAFNOSUPPORT),      // 0x8001006A
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EPROTOTYPE),        // 0x8001006B
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENOTSOCK),          // 0x8001006C
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENOPROTOOPT),       // 0x8001006D
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ESHUTDOWN),         // 0x8001006E
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ECONNREFUSED),      // 0x8001006F
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EADDRINUSE),        // 0x80010070
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ECONNABORTED),      // 0x80010071
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENETUNREACH),       // 0x80010072
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENETDOWN),          // 0x80010073
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ETIMEDOUT),         // 0x80010074
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EHOSTDOWN),         // 0x80010075
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EHOSTUNREACH),      // 0x80010076
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EINPROGRESS),       // 0x80010077
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EALREADY),          // 0x80010078
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EDESTADDRREQ),      // 0x80010079
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EMSGSIZE),          // 0x8001007A
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EPROTONOSUPPORT),   // 0x8001007B
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ESOCKTNOSUPPORT),   // 0x8001007C
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EADDRNOTAVAIL),     // 0x8001007D
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENETRESET),         // 0x8001007E
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EISCONN),           // 0x8001007F
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENOTCONN),          // 0x80010080
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ETOOMANYREFS),      // 0x80010081
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EPROCLIM),          // 0x80010082
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EUSERS),            // 0x80010083
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EDQUOT),            // 0x80010084
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ESTALE),            // 0x80010085
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENOTSUP),           // 0x80010086
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENOMEDIUM),         // 0x80010087
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENOSHARE),          // 0x80010088
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ECASECLASH),        // 0x80010089
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EILSEQ),            // 0x8001008A
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EOVERFLOW),         // 0x8001008B
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ECANCELED),         // 0x8001008C
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_ENOTRECOVERABLE),   // 0x8001008D
    DIRTYSOCK_ErrorName(SCE_ERROR_ERRNO_EOWNERDEAD),        // 0x8001008E

    /*
        kernel\error.h
    */
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ERROR),                    // 0x80020001
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NOT_IMPLEMENTED),          // 0x80020002
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NOSYS),                    // 0x80020003
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_UNSUP),                    // 0x80020004
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_INVALID_ARGUMENT),         // 0x80020005
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_ADDR),             // 0x80020006
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_ALIGNMENT),        // 0x80020007
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_PERMISSION),       // 0x80020008
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_INVALID_ARGUMENT_SIZE),    // 0x80020009
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_INVALID_FLAGS),            // 0x8002000A
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_SIZE),             // 0x8002000B
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_TYPE),             // 0x8002000C
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_PATTERN),          // 0x8002000D
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_ATTR),             // 0x8002000E
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_COUNT),            // 0x8002000F
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_MODE),             // 0x80020010
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_OPEN_LIMIT),       // 0x80020011
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_DEBUG_ERROR),              // 0x80021000
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_DIPSW_NUMBER),     // 0x80021001
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_PA_ERROR),                 // 0x80021100
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_PA_NOT_AVAILABLE),         // 0x80021101
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_PA_INVALID_KEY),           // 0x80021102
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_PA_KEY_IS_NOT_SHARED),     // 0x80021103
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_PA_INVALID_SIGNATURE),     // 0x80021104
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_CPU_ERROR),                // 0x80022000
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MMU_ILLEGAL_L1_TYPE),      // 0x80022001
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MMU_L2_INDEX_OVERFLOW),    // 0x80022002
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MMU_L2_SIZE_OVERFLOW),     // 0x80022003
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_INVALID_CPU_AFFINITY),     // 0x80022004
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_INVALID_MEMORY_ACCESS),    // 0x80022005
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_INVALID_MEMORY_ACCESS_PERMISSION),// 0x80022006
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_VA2PA_FAULT),              // 0x80022007
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_VA2PA_MAPPED),             // 0x80022008
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_VALIDATION_CHECK_FAILED),  // 0x80022009
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_SYSMEM_ERROR),             // 0x80024000
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_INVALID_PROCESS_CONTEXT),  // 0x80024001
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_UID_NAME_TOO_LONG),        // 0x80024002
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_VARANGE_IS_NOT_PHYSICAL_CONTINUOUS),// 0x80024003
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_PHYADDR_ERROR),            // 0x80024100
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NO_PHYADDR),               // 0x80024101
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_PHYADDR_USED),             // 0x80024102
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_PHYADDR_NOT_USED),         // 0x80024103
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NO_IOADDR),                // 0x80024104
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_PHYMEM_ERROR),             // 0x80024300
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_PHYPAGE_STATUS),   // 0x80024301
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NO_FREE_PHYSICAL_PAGE),    // 0x80024302
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NO_FREE_PHYSICAL_PAGE_UNIT),// 0x80024303
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_PHYMEMPART_NOT_EMPTY),     // 0x80024304
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NO_PHYMEMPART_LPDDR2),     // 0x80024305
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NO_PHYMEMPART_CDRAM),      // 0x80024306
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_PHYMEMPART_OUT_OF_INDEX),  // 0x80024307
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_CANNOT_GROW_PHYMEMPART),   // 0x80024308
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NO_FREE_PHYSICAL_PAGE_CDRAM),// 0x80024309
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_FIXEDHEAP_ERROR),          // 0x80024400
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_FIXEDHEAP_ILLEGAL_SIZE),   // 0x80024401
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_FIXEDHEAP_ILLEGAL_INDEX),  // 0x80024402
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_FIXEDHEAP_INDEX_OVERFLOW), // 0x80024403
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_FIXEDHEAP_NO_CHUNK),       // 0x80024404
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_UID_ERROR),                // 0x80024500
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_INVALID_UID),              // 0x80024501
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_SYSMEM_UID_INVALID_ARGUMENT),// 0x80024502
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_SYSMEM_INVALID_UID_RANGE), // 0x80024503
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_SYSMEM_NO_VALID_UID),      // 0x80024504
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_SYSMEM_CANNOT_ALLOCATE_UIDENTRY),// 0x80024505 
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NOT_PROCESS_UID),          // 0x80024506
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NOT_KERNEL_UID),           // 0x80024507
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_INVALID_UID_CLASS),        // 0x80024508
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_INVALID_UID_SUBCLASS),     // 0x80024509
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_UID_CANNOT_FIND_BY_NAME),  // 0x8002450A
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_UID_NOT_VISIBLE),          // 0x8002450B
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_UID_MAX_OPEN),             // 0x8002450C
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_UID_RL_OVERFLOW),          // 0x8002450D
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_VIRPAGE_ERROR),            // 0x80024600
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_VIRPAGE_TYPE),     // 0x80024601
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_BLOCK_ERROR),              // 0x80024700
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_BLOCK_ID),         // 0x80024701
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_BLOCK_TYPE),       // 0x80024702
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_BLOCK_IN_USE),             // 0x80024703
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_PARTITION_ERROR),          // 0x80024800
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_PARTITION_ID),     // 0x80024801
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_PARTITION_INDEX),  // 0x80024802
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NO_L2PAGETABLE),           // 0x80024803
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_HEAPLIB_ERROR),            // 0x80024900
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_HEAP_ID),          // 0x80024901
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_OUT_OF_RANG),              // 0x80024902
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_HEAPLIB_NOMEM),            // 0x80024903
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_HEAPLIB_VERIFY_ERROR),     // 0x80024904
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_SYSMEM_ADDRESS_SPACE_ERROR),// 0x80024A00
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_INVALID_ADDRESS_SPACE_ID), // 0x80024A01
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_INVALID_PARTITION_INDEX),  // 0x80024A02
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ADDRESS_SPACE_CANNOT_FIND_PARTITION_BY_ADDR),// 0x80024A03
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_SYSMEM_MEMBLOCK_ERROR),    // 0x80024B00
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_MEMBLOCK_TYPE),    // 0x80024B01
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_MEMBLOCK_REMAP_TYPE),// 0x80024B02
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NOT_PHY_CONT_MEMBLOCK),    // 0x80024B03
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_MEMBLOCK_CODE),    // 0x80024B04
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_MEMBLOCK_SIZE),    // 0x80024B05
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_USERMAP_SIZE),     // 0x80024B06
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MEMBLOCK_TYPE_FOR_KERNEL_PROCESS),// 0x80024B07
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_PROCESS_CANNOT_REMAP_MEMBLOCK),// 0x80024B08
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MEMBLOCK_RANGE_ERROR),     // 0x80024B09
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MEMBLOCK_TYPE_FOR_UPDATER_OR_SAFEMODE),// 0x80024B0A
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MEMBLOCK_OVERFLOW),        // 0x80024B0B
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_SYSMEM_PHYMEMLOW_ERROR),   // 0x80024C00
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_CANNOT_ALLOC_PHYMEMLOW),   // 0x80024C01
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_UNKNOWN_PHYMEMLOW_TYPE),   // 0x80024C02
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_SYSMEM_BITHEAP_ERROR),     // 0x80024D00
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_CANNOT_ALLOC_BITHEAP),     // 0x80024D01
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_SYSMEM_NAMEHEAP_ERROR),    // 0x80024E00
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NO_SUCH_NAME),             // 0x80024E01
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_DUPLICATE_NAME),           // 0x80024E02
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_LOADCORE_ERROR),           // 0x80025000
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_ELF_HEADER),       // 0x80025001
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_SELF_HEADER),      // 0x80025002
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_EXCPMGR_ERROR),            // 0x80027000
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_EXCPCODE),         // 0x80027001
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_EXCPHANDLER),      // 0x80027002
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NOTFOUND_EXCPHANDLER),     // 0x80027003
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_CANNOT_RELEASE_EXCPHANDLER),// 0x80027004
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_INTRMGR_ERROR),            // 0x80027100
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_CONTEXT),          // 0x80027101
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_INTRCODE),         // 0x80027102
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_INTRPARAM),        // 0x80027103
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_INTRPRIORITY),     // 0x80027104
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_TARGET_CPU),       // 0x80027105
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_INTRFILTER),       // 0x80027106
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_INTRTYPE),         // 0x80027107
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_HANDLER),          // 0x80027108
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_FOUND_HANDLER),            // 0x80027109
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NOTFOUND_HANDLER),         // 0x8002710A
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NO_MEMORY),                // 0x8002710B
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_DMACMGR_ERROR),            // 0x80027200
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ALREADY_QUEUED),           // 0x80027201
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NOT_QUEUED),               // 0x80027202
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NOT_SETUP),                // 0x80027203
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ON_TRANSFERRING),          // 0x80027204
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NOT_INITIALIZED),          // 0x80027205
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_TRANSFERRED),              // 0x80027206
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NOT_UNDER_CONTROL),        // 0x80027207
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_CANCELING),                // 0x80027208
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_SYSTIMER_ERROR),           // 0x80027300
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NO_FREE_TIMER),            // 0x80027301
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_TIMER_NOT_ALLOCATED),      // 0x80027302
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_TIMER_COUNTING),           // 0x80027303
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_TIMER_STOPPED),            // 0x80027304
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_THREADMGR_ERROR),          // 0x80028000
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_UNKNOWN_UID),              // 0x80028001
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_DIFFERENT_UID_CLASS),      // 0x80028002
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ALREADY_REGISTERED),       // 0x80028003
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_CAN_NOT_WAIT),             // 0x80028004
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_WAIT_TIMEOUT),             // 0x80028005
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_WAIT_DELETE),              // 0x80028006
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_WAIT_CANCEL),              // 0x80028007
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_THREAD_ERROR),             // 0x80028020
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_UNKNOWN_THREAD_ID),        // 0x80028021
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_THREAD_ID),        // 0x80028022
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_PRIORITY),         // 0x80028023
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_STACK_SIZE),       // 0x80028024
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_CPU_AFFINITY_MASK),// 0x80028025
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_THREAD_PARAM_COMBINATION),// 0x80028026 
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_DORMANT),                  // 0x80028027
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NOT_DORMANT),              // 0x80028028
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_RUNNING),                  // 0x80028029
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_DELETED),                  // 0x8002802A
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_CAN_NOT_SUSPEND),          // 0x8002802B
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_THREAD_STOPPED),           // 0x8002802C
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_THREAD_SUSPENDED),         // 0x8002802D
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NOT_SUSPENDED),            // 0x8002802E
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ALREADY_DEBUG_SUSPENDED),  // 0x8002802F
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NOT_DEBUG_SUSPENDED),      // 0x80028030
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_CAN_NOT_USE_VFP),          // 0x80028031
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_THREAD_EVENT_ERROR),       // 0x80028060
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_UNKNOWN_THREAD_EVENT_ID),  // 0x80028061
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_KERNEL_TLS_ERROR),         // 0x80028080
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_KERNEL_TLS_FULL),          // 0x80028081
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ILLEGAL_KERNEL_TLS_INDEX), // 0x80028082
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_KERNEL_TLS_BUSY),          // 0x80028083
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_CALLBACK_ERROR),           // 0x800280A0
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_UNKNOWN_CALLBACK_ID),      // 0x800280A1
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NOTIFY_CALLBACK),          // 0x800280A2
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_CALLBACK_NOT_REGISTERED),  // 0x800280A3
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ALARM_ERROR),              // 0x800280C0
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_UNKNOWN_ALARM_ID),         // 0x800280C1
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ALARM_CAN_NOT_CANCEL),     // 0x800280C2
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_EVF_ERROR),                // 0x800280E0
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_UNKNOWN_EVF_ID),           // 0x800280E1
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_EVF_MULTI),                // 0x800280E2
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_EVF_COND),                 // 0x800280E3
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_SEMA_ERROR),               // 0x80028100
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_UNKNOWN_SEMA_ID),          // 0x80028101
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_SEMA_ZERO),                // 0x80028102
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_SEMA_OVF),                 // 0x80028103
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_SIGNAL_ERROR),             // 0x80028120
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_ALREADY_SENT),             // 0x80028121
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MUTEX_ERROR),              // 0x80028140
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_UNKNOWN_MUTEX_ID),         // 0x80028141
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MUTEX_RECURSIVE),          // 0x80028142
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MUTEX_LOCK_OVF),           // 0x80028143
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MUTEX_UNLOCK_UDF),         // 0x80028144
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MUTEX_FAILED_TO_OWN),      // 0x80028145
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MUTEX_NOT_OWNED),          // 0x80028146
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_FAST_MUTEX_ERROR),         // 0x80028160
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_UNKNOWN_FAST_MUTEX_ID),    // 0x80028161
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_FAST_MUTEX_RECURSIVE),     // 0x80028162
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_FAST_MUTEX_LOCK_OVF),      // 0x80028163
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_FAST_MUTEX_FAILED_TO_OWN -2147319452),// 0x80028164
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_FAST_MUTEX_NOT_OWNED),     // 0x80028165
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_FAST_MUTEX_OWNED),         // 0x80028166
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_FAST_MUTEX_ALREADY_INITIALIZED),// 0x80028167
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_FAST_MUTEX_NOT_INITIALIZED),// 0x80028168
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_LW_MUTEX_ERROR),           // 0x80028180
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_UNKNOWN_LW_MUTEX_ID),      // 0x80028181
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_LW_MUTEX_RECURSIVE),       // 0x80028182
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_LW_MUTEX_LOCK_OVF),        // 0x80028183
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_LW_MUTEX_UNLOCK_UDF),      // 0x80028184
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_LW_MUTEX_FAILED_TO_OWN),   // 0x80028185
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_LW_MUTEX_NOT_OWNED),       // 0x80028186
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_COND_ERROR),               // 0x800281A0
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_UNKNOWN_COND_ID),          // 0x800281A1
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_WAIT_DELETE_MUTEX),        // 0x800281A2
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_WAIT_CANCEL_MUTEX),        // 0x800281A3
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_WAIT_DELETE_COND),         // 0x800281A4
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_WAIT_CANCEL_COND),         // 0x800281A5
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_LW_COND_ERROR),            // 0x800281C0
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_UNKNOWN_LW_COND_ID),       // 0x800281C1
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_WAIT_DELETE_LW_MUTEX),     // 0x800281C2
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_RW_LOCK_ERROR),            // 0x800281E0
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_UNKNOWN_RW_LOCK_ID),       // 0x800281E1
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_RW_LOCK_RECURSIVE),        // 0x800281E2
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_RW_LOCK_LOCK_OVF),         // 0x800281E3
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_RW_LOCK_NOT_OWNED),        // 0x800281E4
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_RW_LOCK_UNLOCK_UDF),       // 0x800281E5
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_RW_LOCK_FAILED_TO_LOCK),   // 0x800281E6
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_RW_LOCK_FAILED_TO_UNLOCK), // 0x800281E7
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_EVENT_ERROR),              // 0x80028200
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_UNKNOWN_EVENT_ID),         // 0x80028201
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_EVENT_COND),               // 0x80028202
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MSG_PIPE_ERROR),           // 0x80028220
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_UNKNOWN_MSG_PIPE_ID),      // 0x80028221
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MSG_PIPE_FULL),            // 0x80028222
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MSG_PIPE_EMPTY),           // 0x80028223
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MSG_PIPE_DELETED),         // 0x80028224
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_TIMER_ERROR),              // 0x80028240
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_UNKNOWN_TIMER_ID),         // 0x80028241
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_EVENT_NOT_SET),            // 0x80028242
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_SIMPLE_EVENT_ERROR),       // 0x80028260
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_UNKNOWN_SIMPLE_EVENT_ID),  // 0x80028261
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_PMON_ERROR),               // 0x80028280
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_PMON_NOT_THREAD_MODE),     // 0x80028281
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_PMON_NOT_CPU_MODE),        // 0x80028282
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_WORK_QUEUE),               // 0x80028300
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_UNKNOWN_WORK_QUEUE_ID),    // 0x80028301
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_UNKNOWN_WORK_TASK_ID),     // 0x80028302
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_PROCESSMGR_ERROR),         // 0x80029000
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_INVALID_PID),              // 0x80029001
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_INVALID_PROCESS_TYPE),     // 0x80029002
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_PLS_FULL),                 // 0x80029003
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_INVALID_PROCESS_STATUS),   // 0x80029004
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_PROCESS_CALLBACK_NOTFOUND),// 0x80029005
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_INVALID_BUDGET_ID),        // 0x80029006
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_INVALID_BUDGET_SIZE),      // 0x80029007
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_CP14_DISABLED),            // 0x80029008
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_EXCEEDED_MAX_PROCESSES),   // 0x80029009
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_PROCESS_REMAINING),        // 0x8002900A
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NO_PROCESS_DATA),          // 0x8002900B
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_PROCESS_EVENT_INHIBITED),  // 0x8002900C
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_IOFILEMGR_ERROR),          // 0x8002A000
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_IO_NAME_TOO_LONG),         // 0x8002A001
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_IO_REG_DEV),               // 0x8002A002
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_IO_ALIAS_USED),            // 0x8002A003
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_IO_DEL_DEV),               // 0x8002A004
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_IO_WOULD_BLOCK),           // 0x8002A005
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_START_FAILED),   // 0x8002D000
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_STOP_FAIL),      // 0x8002D001
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_IN_USE),         // 0x8002D002
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_NO_LIB),         // 0x8002D003
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_SYSCALL_REG),    // 0x8002D004
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_NOMEM_LIB),      // 0x8002D005
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_NOMEM_STUB),     // 0x8002D006
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_NOMEM_SELF),     // 0x8002D007
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_NOMEM),          // 0x8002D008
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_INVALID_LIB),    // 0x8002D009
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_INVALID_STUB),   // 0x8002D00A
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_NO_FUNC_NID),    // 0x8002D00B
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_NO_VAR_NID),     // 0x8002D00C
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_INVALID_TYPE),   // 0x8002D00D
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_NO_MOD_ENTRY),   // 0x8002D00E
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_INVALID_PROC_PARAM),// 0x8002D00F
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_NO_MODOBJ),      //  0x8002D010
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_NO_MOD),         // 0x8002D011
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_NO_PROCESS),     // 0x8002D012
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_OLD_LIB),        // 0x8002D013
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_STARTED),        // 0x8002D014
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_NOT_STARTED),    // 0x8002D015
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_NOT_STOPPED),    //  0x8002D016
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_INVALID_PROCESS_UID),// 0x8002D017
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_CANNOT_EXPORT_LIB_TO_SHARED), // 0x8002D018
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_INVALID_REL_INFO),// 0x8002D019
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_INVALID_REF_INFO),// 0x8002D01A
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_ELINK),          // 0x8002D01B
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_NOENT),          // 0x8002D01C
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_BUSY),           // 0x8002D01D
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_NOEXEC),         // 0x8002D01E
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_MODULEMGR_NAMETOOLONG),    // 0x8002D01F
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_LIBRARYDB_NOENT),          // 0x8002D080
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_LIBRARYDB_NO_LIB),         // 0x8002D081
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_LIBRARYDB_NO_MOD),         // 0x8002D082
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_PRELOAD_FAILED),           // 0x8002D0F0
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_PRELOAD_LIBC_FAILED),      // 0x8002D0F1
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_PRELOAD_FIOS2_FAILED),     // 0x8002D0F2
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_AUTHFAIL),                 // 0x8002F000
    DIRTYSOCK_ErrorName(SCE_KERNEL_ERROR_NO_AUTH),                  // 0x8002F001

    /*
        errors from net/errno.h
    */
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EPERM),                           // 0x80410101
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENOENT),                          // 0x80410102
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ESRCH),                           // 0x80410103
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EINTR),                           // 0x80410104
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EIO),                             // 0x80410105
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENXIO),                           // 0x80410106
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_E2BIG),                           // 0x80410107
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENOEXEC),                         // 0x80410108
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EBADF),                           // 0x80410109
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ECHILD),                          // 0x8041010A
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EDEADLK),                         // 0x8041010B
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENOMEM),                          // 0x8041010C
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EACCES),                          // 0x8041010D
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EFAULT),                          // 0x8041010E
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENOTBLK),                         // 0x8041010F
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EBUSY),                           // 0x80410110
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EEXIST),                          // 0x80410111
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EXDEV),                           // 0x80410112
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENODEV),                          // 0x80410113
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENOTDIR),                         // 0x80410114
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EISDIR),                          // 0x80410115
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EINVAL),                          // 0x80410116
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENFILE),                          // 0x80410117
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EMFILE),                          // 0x80410118
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENOTTY),                          // 0x80410119
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ETXTBSY),                         // 0x8041011A
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EFBIG),                           // 0x8041011B
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENOSPC),                          // 0x8041011C
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ESPIPE),                          // 0x8041011D
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EROFS),                           // 0x8041011E
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EMLINK),                          // 0x8041011F
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EPIPE),                           // 0x80410120
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EDOM),                            // 0x80410121
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ERANGE),                          // 0x80410122
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EAGAIN),                          // 0x80410123
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EWOULDBLOCK),                     // 0x80410123
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EINPROGRESS),                     // 0x80410124
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EALREADY),                        // 0x80410125
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENOTSOCK),                        // 0x80410126
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EDESTADDRREQ),                    // 0x80410127
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EMSGSIZE),                        // 0x80410128
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EPROTOTYPE),                      // 0x80410129
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENOPROTOOPT),                     // 0x8041012A
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EPROTONOSUPPORT),                 // 0x8041012B
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ESOCKTNOSUPPORT),                 // 0x8041012C
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EOPNOTSUPP),                      // 0x8041012D
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EPFNOSUPPORT),                    // 0x8041012E
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EAFNOSUPPORT),                    // 0x8041012F
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EADDRINUSE),                      // 0x80410130
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EADDRNOTAVAIL),                   // 0x80410131
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENETDOWN),                        // 0x80410132
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENETUNREACH),                     // 0x80410133
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENETRESET),                       // 0x80410134
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ECONNABORTED),                    // 0x80410135
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ECONNRESET),                      // 0x80410136
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENOBUFS),                         // 0x80410137
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EISCONN),                         // 0x80410138
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENOTCONN),                        // 0x80410139
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ESHUTDOWN),                       // 0x8041013A
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ETOOMANYREFS),                    // 0x8041013B
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ETIMEDOUT),                       // 0x8041013C
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ECONNREFUSED),                    // 0x8041013D
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ELOOP),                           // 0x8041013E
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENAMETOOLONG),                    // 0x8041013F
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EHOSTDOWN),                       // 0x80410140
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EHOSTUNREACH),                    // 0x80410141
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENOTEMPTY),                       // 0x80410142
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EPROCLIM),                        // 0x80410143
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EUSERS),                          // 0x80410144
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EDQUOT),                          // 0x80410145
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ESTALE),                          // 0x80410146
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EREMOTE),                         // 0x80410147
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EBADRPC),                         // 0x80410148
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ERPCMISMATCH),                    // 0x80410149
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EPROGUNAVAIL),                    // 0x8041014A
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EPROGMISMATCH),                   // 0x8041014B
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EPROCUNAVAIL),                    // 0x8041014C
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENOLCK),                          // 0x8041014D
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENOSYS),                          // 0x8041014E
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EFTYPE),                          // 0x8041014F
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EAUTH),                           // 0x80410150
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENEEDAUTH),                       // 0x80410151
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EIDRM),                           // 0x80410152
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENOMS),                           // 0x80410153
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EOVERFLOW),                       // 0x80410154
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EILSEQ),                          // 0x80410155
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENOTSUP),                         // 0x80410156
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ECANCELED),                       // 0x80410157
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EBADMSG),                         // 0x80410158
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENODATA),                         // 0x80410159
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENOSR),                           // 0x8041015A
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENOSTR),                          // 0x8041015B
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ETIME),                           // 0x8041015C
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EADHOC),                          // 0x804101A0
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EDISABLEDIF),                     // 0x804101A1
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENOTINIT),                        // 0x804101C8
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ENOLIBMEM),                       // 0x804101C9
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ERESERVED202),                    // 0x804101CA
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ECALLBACK),                       // 0x804101CB
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_EINTERNAL),                       // 0x804101CC
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_ERETURN),                         // 0x804101CD
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_RESOLVER_EINTERNAL),              // 0x804101DC
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_RESOLVER_EBUSY),                  // 0x804101DD
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_RESOLVER_ENOSPACE),               // 0x804101DE
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_RESOLVER_EPACKET),                // 0x804101DF
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_RESOLVER_ERESERVED224),           // 0x804101E0
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_RESOLVER_ENODNS),                 // 0x804101E1
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_RESOLVER_ETIMEDOUT),              // 0x804101E2
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_RESOLVER_ENOSUPPORT),             // 0x804101E3
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_RESOLVER_EFORMAT),                // 0x804101E4
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_RESOLVER_ESERVERFAILURE),         // 0x804101E5
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_RESOLVER_ENOHOST),                // 0x804101E6
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_RESOLVER_ENOTIMPLEMENTED),        // 0x804101E7
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_RESOLVER_ESERVERREFUSED),         // 0x804101E8
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_RESOLVER_ENORECORD),              // 0x804101E9
    DIRTYSOCK_ErrorName(SCE_NET_ERROR_RESOLVER_EALIGNMENT),             // 0x804101EA

    /*
        errors from libnetctl.h
    */
    DIRTYSOCK_ErrorName(SCE_NET_CTL_ERROR_NOT_INITIALIZED),             // 0x80412101
    DIRTYSOCK_ErrorName(SCE_NET_CTL_ERROR_NOT_TERMINATED),              // 0x80412102
    DIRTYSOCK_ErrorName(SCE_NET_CTL_ERROR_CALLBACK_MAX),                // 0x80412103
    DIRTYSOCK_ErrorName(SCE_NET_CTL_ERROR_ID_NOT_FOUND),                // 0x80412104
    DIRTYSOCK_ErrorName(SCE_NET_CTL_ERROR_INVALID_ID),                  // 0x80412105
    DIRTYSOCK_ErrorName(SCE_NET_CTL_ERROR_INVALID_CODE),                // 0x80412106
    DIRTYSOCK_ErrorName(SCE_NET_CTL_ERROR_INVALID_ADDR),                // 0x80412107
    DIRTYSOCK_ErrorName(SCE_NET_CTL_ERROR_NOT_CONNECTED),               // 0x80412108
    DIRTYSOCK_ErrorName(SCE_NET_CTL_ERROR_NOT_AVAIL),                   // 0x80412109
    DIRTYSOCK_ErrorName(SCE_NET_CTL_ERROR_AUTO_CONNECT_DISABLED),       // 0x8041210a
    DIRTYSOCK_ErrorName(SCE_NET_CTL_ERROR_AUTO_CONNECT_FAILED),         // 0x8041210b
    DIRTYSOCK_ErrorName(SCE_NET_CTL_ERROR_NO_SUITABLE_SETTING_FOR_AUTO_CONNECT), // 0x8041210c
    DIRTYSOCK_ErrorName(SCE_NET_CTL_ERROR_DISCONNECTED_FOR_ADHOC_USE),  // 0x8041210d
    DIRTYSOCK_ErrorName(SCE_NET_CTL_ERROR_DISCONNECT_REQ),              // 0x8041210e
    DIRTYSOCK_ErrorName(SCE_NET_CTL_ERROR_INVALID_TYPE),                // 0x8041210f
    DIRTYSOCK_ErrorName(SCE_NET_CTL_ERROR_AUTO_DISCONNECT),             // 0x80412110
    DIRTYSOCK_ErrorName(SCE_NET_CTL_ERROR_INVALID_SIZE),                // 0x80412111
    DIRTYSOCK_ErrorName(SCE_NET_CTL_ERROR_FLIGHT_MODE_ENABLED),         // 0x80412112
    DIRTYSOCK_ErrorName(SCE_NET_CTL_ERROR_WIFI_DISABLED),               // 0x80412113
    DIRTYSOCK_ErrorName(SCE_NET_CTL_ERROR_WIFI_IN_ADHOC_USE),           // 0x80412114
    DIRTYSOCK_ErrorName(SCE_NET_CTL_ERROR_ETHERNET_PLUGOUT),            // 0x80412115
    DIRTYSOCK_ErrorName(SCE_NET_CTL_ERROR_WIFI_DEAUTHED),               // 0x80412116
    DIRTYSOCK_ErrorName(SCE_NET_CTL_ERROR_WIFI_BEACON_LOST),            // 0x80412117
    DIRTYSOCK_ErrorName(SCE_NET_CTL_ERROR_DISCONNECTED_FOR_SUSPEND),    // 0x80412118
    DIRTYSOCK_ErrorName(SCE_NET_CTL_ERROR_COMMUNICATION_ID_NOT_EXIST),  // 0x80412119
    DIRTYSOCK_ErrorName(SCE_NET_CTL_ERROR_ADHOC_ALREADY_CONNECTED),     // 0x8041211a

    /*
        errors from np/nperror.h
    */
    
    /* 0x00 common error */
    DIRTYSOCK_ErrorName(SCE_NP_ERROR_ALREADY_INITIALIZED),              // 0x80550001
    DIRTYSOCK_ErrorName(SCE_NP_ERROR_NOT_INITIALIZED),                  // 0x80550002
    DIRTYSOCK_ErrorName(SCE_NP_ERROR_INVALID_ARGUMENT),                 // 0x80550003

    /* 0x03 auth error */
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_ALREADY_INITIALIZED),         // 0x80550301
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_NOT_INITIALIZED),             // 0x80550302
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_EINVAL),                      // 0x80550303
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_ENOMEM),                      // 0x80550304
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_ESRCH),                       // 0x80550305
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_EBUSY),                       // 0x80550306
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_ABORTED),                     // 0x80550307
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_INVALID_SERVICE_ID),          // 0x80550308
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_INVALID_CREDENTIAL),          // 0x80550309
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_INVALID_ENTITLEMENT_ID),      // 0x8055030a
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_INVALID_DATA_LENGTH),         // 0x8055030b
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_UNSUPPORTED_TICKET_VERSION),  // 0x8055030c
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_STACKSIZE_TOO_SHORT),         // 0x8055030d
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_TICKET_STATUS_CODE_INVALID),  // 0x8055030e
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_TICKET_PARAM_NOT_FOUND),      // 0x8055030f
#if SCE_PSP2_SDK_VERSION < 0x01000071
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_INVALID_TICKET_VERSION),      // 0x80550310
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_INVALID_ARGUMENT),            // 0x80550311
#endif

    /* 0x04 auth server error */
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_SERVICE_END),                 // 0x80550400
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_SERVICE_DOWN),                // 0x80550401
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_SERVICE_BUSY),                // 0x80550402
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_SERVER_MAINTENANCE),          // 0x80550403
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_S_INVALID_DATA_LENGTH),       // 0x80550410
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_S_INVALID_USER_AGENT),        // 0x80550411
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_S_INVALID_VERSION),           // 0x80550412
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_S_INVALID_SERVICE_ID),        // 0x80550420
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_S_INVALID_CREDENTIAL),        // 0x80550421
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_S_INVALID_ENTITLEMENT_ID),    // 0x80550422
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_S_INVALID_CONSUMED_COUNT),    // 0x80550423
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_INVALID_CONSOLE_ID),          // 0x80550424
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_CONSOLE_ID_SUSPENDED),        // 0x80550427
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_ACCOUNT_CLOSED),              // 0x80550430
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_ACCOUNT_SUSPENDED),           // 0x80550431
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_ACCOUNT_RENEW_EULA),          // 0x80550432
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_ACCOUNT_RENEW_ACCOUNT1),      // 0x80550440
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_ACCOUNT_RENEW_ACCOUNT2),      // 0x80550441
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_ACCOUNT_RENEW_ACCOUNT3),      // 0x80550442
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_ACCOUNT_RENEW_ACCOUNT4),      // 0x80550443
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_ACCOUNT_RENEW_ACCOUNT5),      // 0x80550444
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_ACCOUNT_RENEW_ACCOUNT6),      // 0x80550445
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_ACCOUNT_RENEW_ACCOUNT7),      // 0x80550446
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_ACCOUNT_RENEW_ACCOUNT8),      // 0x80550447
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_ACCOUNT_RENEW_ACCOUNT9),      // 0x80550448
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_ACCOUNT_RENEW_ACCOUNT10),     // 0x80550449
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_ACCOUNT_RENEW_ACCOUNT11),     // 0x8055044a
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_ACCOUNT_RENEW_ACCOUNT12),     // 0x8055044b
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_ACCOUNT_RENEW_ACCOUNT13),     // 0x8055044c
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_ACCOUNT_RENEW_ACCOUNT14),     // 0x8055044d
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_ACCOUNT_RENEW_ACCOUNT15),     // 0x8055044e
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_ACCOUNT_RENEW_ACCOUNT16),     // 0x8055044f
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_SUB_ACCOUNT_RENEW_EULA),      // 0x8055044f
    DIRTYSOCK_ErrorName(SCE_NP_AUTH_ERROR_UNKNOWN),                     // 0x80550480

    /* 0x05 manager error */
    DIRTYSOCK_ErrorName(SCE_NP_MANAGER_ERROR_ALREADY_INITIALIZED),      // 0x80550501
    DIRTYSOCK_ErrorName(SCE_NP_MANAGER_ERROR_NOT_INITIALIZED),          // 0x80550502
    DIRTYSOCK_ErrorName(SCE_NP_MANAGER_ERROR_INVALID_ARGUMENT),         // 0x80550503
    DIRTYSOCK_ErrorName(SCE_NP_MANAGER_ERROR_OUT_OF_MEMORY),            // 0x80550504
    DIRTYSOCK_ErrorName(SCE_NP_MANAGER_ERROR_INVALID_TICKET_SIZE),      // 0x80550505
    DIRTYSOCK_ErrorName(SCE_NP_MANAGER_ERROR_INVALID_STATE),            // 0x80550506
    DIRTYSOCK_ErrorName(SCE_NP_MANAGER_ERROR_ABORTED),                  // 0x80550507
    DIRTYSOCK_ErrorName(SCE_NP_MANAGER_ERROR_VARIANT_ACCOUNT_ID),       // 0x80550508
    DIRTYSOCK_ErrorName(SCE_NP_MANAGER_ERROR_ID_NOT_AVAIL),             // 0x80550509
    DIRTYSOCK_ErrorName(SCE_NP_MANAGER_ERROR_SIGNOUT),                  // 0x8055050a
#if SCE_PSP2_SDK_VERSION >= 0x01000071
    DIRTYSOCK_ErrorName(SCE_NP_MANAGER_ERROR_NOT_SIGNIN),               // 0x8055050b
#endif

    /* 0x06 util error */
    DIRTYSOCK_ErrorName(SCE_NP_UTIL_ERROR_INVALID_ARGUMENT),            // 0x80550601
    DIRTYSOCK_ErrorName(SCE_NP_UTIL_ERROR_INSUFFICIENT),                // 0x80550602
    DIRTYSOCK_ErrorName(SCE_NP_UTIL_ERROR_PARSER_FAILED),               // 0x80550603
    DIRTYSOCK_ErrorName(SCE_NP_UTIL_ERROR_INVALID_PROTOCOL_ID),         // 0x80550604
    DIRTYSOCK_ErrorName(SCE_NP_UTIL_ERROR_INVALID_NP_ID),               // 0x80550605
    DIRTYSOCK_ErrorName(SCE_NP_UTIL_ERROR_INVALID_NP_ENV),              // 0x80550606
    DIRTYSOCK_ErrorName(SCE_NP_UTIL_ERROR_INVALID_NPCOMMID),            // 0x80550607
    DIRTYSOCK_ErrorName(SCE_NP_UTIL_ERROR_INVALID_CHARACTER),           // 0x80550608
    DIRTYSOCK_ErrorName(SCE_NP_UTIL_ERROR_NOT_MATCH),                   // 0x80550609
    DIRTYSOCK_ErrorName(SCE_NP_UTIL_ERROR_INVALID_TITLEID),             // 0x8055060a
    DIRTYSOCK_ErrorName(SCE_NP_UTIL_ERROR_INVALID_ESCAPE_STRING),       // 0x8055060c
    DIRTYSOCK_ErrorName(SCE_NP_UTIL_ERROR_UNKNOWN_TYPE),                // 0x8055060d
    DIRTYSOCK_ErrorName(SCE_NP_UTIL_ERROR_UNKNOWN),                     // 0x8055060e

    /* 0x07 community error */
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_ERROR_ALREADY_INITIALIZED),                // 0x80550701
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_ERROR_NOT_INITIALIZED),                    // 0x80550702
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_ERROR_OUT_OF_MEMORY),                      // 0x80550703
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_ERROR_INVALID_ARGUMENT),                   // 0x80550704
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_ERROR_NO_LOGIN),                           // 0x80550705
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_ERROR_TOO_MANY_OBJECTS),                   // 0x80550706
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_ERROR_ABORTED),                            // 0x80550707
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_ERROR_BAD_RESPONSE),                       // 0x80550708
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_ERROR_BODY_TOO_LARGE),                     // 0x80550709
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_ERROR_HTTP_SERVER),                        // 0x8055070a
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_ERROR_INVALID_SIGNATURE),                  // 0x8055070b
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_ERROR_INSUFFICIENT_ARGUMENT),              // 0x8055070c
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_ERROR_UNKNOWN_TYPE),                       // 0x8055070d
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_ERROR_INVALID_ID),                         // 0x8055070e
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_ERROR_INVALID_ONLINE_ID),                  // 0x8055070f
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_ERROR_CONNECTION_HANDLE_ALREADY_EXISTS),   // 0x80550710
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_ERROR_INVALID_TYPE),                       // 0x80550711
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_ERROR_TRANSACTION_ALREADY_END),            // 0x80550712
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_ERROR_INVALID_PARTITION),                  // 0x80550713
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_ERROR_INVALID_ALIGNMENT),                  // 0x80550714
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_ERROR_CLIENT_HANDLE_ALREADY_EXISTS),       // 0x80550715
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_ERROR_NO_RESOURCE),                        // 0x80550716
#if SCE_PSP2_SDK_VERSION >= 0x01000071
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_ERROR_REQUEST_BEFORE_END),                 // 0x80550717
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_ERROR_TOO_MANY_SLOTID),                    // 0x80550718
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_ERROR_TOO_MANY_NPID),                      // 0x80550719
#endif

    /* 0x08 community server error */
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_BAD_REQUEST),                         // 0x80550801
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_INVALID_TICKET),                      // 0x80550802
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_INVALID_SIGNATURE),                   // 0x80550803
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_INVALID_NPID),                        // 0x80550805
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_FORBIDDEN),                           // 0x80550806
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_INTERNAL_SERVER_ERROR),               // 0x80550807
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_VERSION_NOT_SUPPORTED),               // 0x80550808
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_SERVICE_UNAVAILABLE),                 // 0x80550809
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_PLAYER_BANNED),                       // 0x8055080a
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_CENSORED),                            // 0x8055080b
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_RANKING_RECORD_FORBIDDEN),            // 0x8055080c
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_USER_PROFILE_NOT_FOUND),              // 0x8055080d
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_UPLOADER_DATA_NOT_FOUND),             // 0x8055080e
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_QUOTA_MASTER_NOT_FOUND),              // 0x8055080f
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_RANKING_TITLE_NOT_FOUND),             // 0x80550810
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_BLACKLISTED_USER_ID),                 // 0x80550811
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_GAME_RANKING_NOT_FOUND),              // 0x80550812
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_RANKING_STORE_NOT_FOUND),             // 0x80550814
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_NOT_BEST_SCORE),                      // 0x80550815
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_LATEST_UPDATE_NOT_FOUND),             // 0x80550816
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_RANKING_BOARD_MASTER_NOT_FOUND),      // 0x80550817
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_RANKING_GAME_DATA_MASTER_NOT_FOUND),  // 0x80550818
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_INVALID_ANTICHEAT_DATA),              // 0x80550819
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_TOO_LARGE_DATA),                      // 0x8055081a
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_NO_SUCH_USER_NPID),                   // 0x8055081b
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_INVALID_ENVIRONMENT),                 // 0x8055081d
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_INVALID_ONLINE_NAME_CHARACTER),       // 0x8055081f
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_INVALID_ONLINE_NAME_LENGTH),          // 0x80550820
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_INVALID_ABOUT_ME_CHARACTER),          // 0x80550821
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_INVALID_ABOUT_ME_LENGTH),             // 0x80550822
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_INVALID_SCORE),                       // 0x80550823
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_OVER_THE_RANKING_LIMIT),              // 0x80550824
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_FAIL_TO_CREATE_SIGNATURE),            // 0x80550826
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_RANKING_MASTER_INFO_NOT_FOUND),       // 0x80550827
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_OVER_THE_GAME_DATA_LIMIT),            // 0x80550828
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_SELF_DATA_NOT_FOUND),                 // 0x8055082a
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_USER_NOT_ASSIGNED),                   // 0x8055082b
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_GAME_DATA_ALREADY_EXISTS),            // 0x8055082c
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_MATCHING_BEFORE_SERVICE),             // 0x805508a0
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_MATCHING_END_OF_SERVICE),             // 0x805508a1
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_MATCHING_MAINTENANCE),                // 0x805508a2
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_RANKING_BEFORE_SERVICE),              // 0x805508a3
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_RANKING_END_OF_SERVICE),              // 0x805508a4
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_RANKING_MAINTENANCE),                 // 0x805508a5
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_NO_SUCH_TITLE),                       // 0x805508a6
#if SCE_PSP2_SDK_VERSION >= 0x01000071
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_TITLE_USER_STORAGE_BEFORE_SERVICE),   // 0x805508aa
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_TITLE_USER_STORAGE_END_OF_SERVICE),   // 0x805508ab
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_TITLE_USER_STORAGE_MAINTENANCE),      // 0x805508ac
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_FSR_BEFORE_SERVICE),                  // 0x805508ad
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_FSR_END_OF_SERVICE),                  // 0x805508ae
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_FSR_MAINTENANCE),                     // 0x805508af
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_UBS_BEFORE_SERVICE),                  // 0x805508b1
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_UBS_END_OF_SERVICE),                  // 0x805508b2
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_UBS_MAINTENANCE),                     // 0x805508b3
#endif


    /* Unspecified Error */
    DIRTYSOCK_ErrorName(SCE_NP_COMMUNITY_SERVER_ERROR_UNSPECIFIED),                         // 0x805508ff

    // NULL terminate
    DIRTYSOCK_ListEnd()
};
#endif

/*** Private Functions ************************************************************/

/*** Public functions *************************************************************/

/*F********************************************************************************/
/*!
    \Function DirtyErrNameList

    \Description
        This function takes as input a system-specific error code, and either
        resolves it to its define name if it is recognized or formats it as a hex
        number if not.

    \Input *pBuffer - [out] pointer to output buffer to store result
    \Input iBufSize - size of output buffer
    \Input uError   - error code to format
    \Input *pList   - error list to use

    \Version 10/04/2005 (jbrookes)
*/
/********************************************************************************F*/
void DirtyErrNameList(char *pBuffer, int32_t iBufSize, uint32_t uError, const DirtyErrT *pList)
{
    #if DIRTYSOCK_ERRORNAMES
    int32_t iErr;
    
    for (iErr = 0; pList[iErr].uError != DIRTYSOCK_LISTTERM; iErr++)
    {
        if (pList[iErr].uError == uError)
        {
            snzprintf(pBuffer, iBufSize, "%s/%d", pList[iErr].pErrorName, (signed)uError);
            return;
        }
    }
    #endif

    snzprintf(pBuffer, iBufSize, "%d", uError);
}

/*F********************************************************************************/
/*!
    \Function DirtyErrName

    \Description
        This function takes as input a system-specific error code, and either
        resolves it to its define name if it is recognized or formats it as a hex
        number if not.

    \Input *pBuffer - [out] pointer to output buffer to store result
    \Input iBufSize - size of output buffer
    \Input uError   - error code to format

    \Version 10/04/2005 (jbrookes)
*/
/********************************************************************************F*/
void DirtyErrName(char *pBuffer, int32_t iBufSize, uint32_t uError)
{
    #if DIRTYSOCK_ERRORNAMES
    int32_t iErr;
    
    for (iErr = 0; _DirtyErr_List[iErr].uError != DIRTYSOCK_LISTTERM; iErr++)
    {
        if (_DirtyErr_List[iErr].uError == uError)
        {
            snzprintf(pBuffer, iBufSize, "%s/0x%08x", _DirtyErr_List[iErr].pErrorName, uError);
            return;
        }
    }
    #endif

    snzprintf(pBuffer, iBufSize, "0x%08x", uError);
}

/*F********************************************************************************/
/*!
    \Function DirtyErrGetNameList

    \Description
        This function takes as input a system-specific error code, and either
        resolves it to its define name if it is recognized or formats it as a hex
        number if not.

    \Input uError   - error code to format
    \Input *pList   - error list to use
    
    \Output
        const char *- pointer to error name or error formatted in hex

    \Version 10/04/2005 (jbrookes)
*/
/********************************************************************************F*/
const char *DirtyErrGetNameList(uint32_t uError, const DirtyErrT *pList)
{
    static char strName[8][64];
    static uint8_t uLast = 0;
    char *pName = strName[uLast++];
    if (uLast > 7) uLast = 0;
    DirtyErrNameList(pName, sizeof(strName[0]), uError, pList);
    return(pName);
}

/*F********************************************************************************/
/*!
    \Function DirtyErrGetName

    \Description
        This function takes as input a system-specific error code, and either
        resolves it to its define name if it is recognized or formats it as a hex
        number if not.

    \Input uError   - error code to format
    
    \Output
        const char *- pointer to error name or error formatted in hex

    \Version 10/04/2005 (jbrookes)
*/
/********************************************************************************F*/
const char *DirtyErrGetName(uint32_t uError)
{
    static char strName[64];
    DirtyErrName(strName, sizeof(strName), uError);
    return(strName);
}
