DirtySock: dirtycontextmanagerps4.c File Reference
dirtycontextmanagerps4.c File Reference
dirtycontextManagerPs4 handles thread synchornization for creating and freeing sceHttp, sceSsl and sceNetPool context creation and deletion. This functionality is necessary since the Sony library does not offer a thread safe implementation.
#include <net.h>
#include <libhttp.h>
#include <string.h>
#include "DirtySDK/dirtysock/dirtymem.h"
#include "DirtySDK/dirtysock/dirtylib.h"
#include "DirtySDK/dirtysock/ps4/dirtycontextmanagerps4.h"
Data Structures
struct DirtyContextManagerRefT
Macros
#define DIRTYCM_MAX_CONTEXTS (100)
#define DIRTYCM_MAX_NET_CONTEXTS (32)
#define DIRTYCM_EXTERNAL_NETPOOL (-1)
#define DIRTYCM_MIN_NETHEAP_SIZE (4096)
#define DIRTYCM_POOLSIZE_FACTOR (16384)
Typedefs
typedef struct
DirtyContextManagerRefT DirtyContextManagerRefT
Functions
int32_t DirtyContextManagerInit ()
void DirtyContextManagerShutdown ()
int32_t DirtyContextManagerCreateNetPoolContext (const char *strName, int32_t iNetPoolSize)
int32_t DirtyContextManagerCreateSslContext (int32_t iSslBufferSize)
int32_t DirtyContextManagerCreateHttpContext (int32_t iSceNetContextId, int32_t iSslContextId, int32_t iHttpBufferSize)
int32_t DirtyContextManagerFreeNetPoolContext (int32_t iSceNetContextId)
int32_t DirtyContextManagerFreeSslContext (int32_t iSslContextId)
int32_t DirtyContextManagerFreeHttpContext (int32_t iHttpContextId)
Detailed Description
dirtycontextManagerPs4 handles thread synchornization for creating and freeing sceHttp, sceSsl and sceNetPool context creation and deletion. This functionality is necessary since the Sony library does not offer a thread safe implementation.
Attention
Copyright (c) Electronic Arts 2016
Version
1.0 07/22/2016 (amakoukji) First Version
Macro Definition Documentation
#define DIRTYCM_EXTERNAL_NETPOOL (-1)
#define DIRTYCM_MAX_CONTEXTS (100)
Referenced by DirtyContextManagerCreateHttpContext(), DirtyContextManagerCreateSslContext(), DirtyContextManagerFreeHttpContext(), DirtyContextManagerFreeSslContext(), and DirtyContextManagerShutdown().
#define DIRTYCM_MAX_NET_CONTEXTS (32)
Referenced by DirtyContextManagerCreateNetPoolContext(), DirtyContextManagerFreeNetPoolContext(), and DirtyContextManagerShutdown().
#define DIRTYCM_MIN_NETHEAP_SIZE (4096)
Referenced by DirtyContextManagerCreateNetPoolContext().
#define DIRTYCM_POOLSIZE_FACTOR (16384)
Referenced by DirtyContextManagerCreateHttpContext().
Typedef Documentation
typedef struct DirtyContextManagerRefT DirtyContextManagerRefT
Function Documentation
int32_t DirtyContextManagerCreateHttpContext (int32_t iSceNetContextId, int32_t iSslContextId, int32_t iHttpBufferSize)
References DirtyContextManagerRefT::aHttpContextId, DirtyContextManagerRefT::crit, DIRTYCM_MAX_CONTEXTS, DIRTYCM_POOLSIZE_FACTOR, NetCritEnter(), NetCritLeave(), and NetPrintf.
Referenced by ProtoHttpCreate().
int32_t DirtyContextManagerCreateNetPoolContext (const char * strName, int32_t iNetPoolSize)
References DirtyContextManagerRefT::aNetContexts, DirtyContextManagerRefT::crit, DIRTYCM_MAX_NET_CONTEXTS, DIRTYCM_MIN_NETHEAP_SIZE, ds_snzprintf(), ds_strnlen(), NetCritEnter(), NetCritLeave(), and NetPrintf.
Referenced by ProtoHttpCreate().
int32_t DirtyContextManagerCreateSslContext (int32_t iSslBufferSize)
References DirtyContextManagerRefT::aSslContextId, DirtyContextManagerRefT::crit, DIRTYCM_MAX_CONTEXTS, NetCritEnter(), NetCritLeave(), and NetPrintf.
Referenced by ProtoHttpCreate().
int32_t DirtyContextManagerFreeHttpContext (int32_t iHttpContextId)
References DirtyContextManagerRefT::aHttpContextId, DirtyContextManagerRefT::crit, DIRTYCM_MAX_CONTEXTS, NetCritEnter(), and NetCritLeave().
Referenced by ProtoHttpCreate(), and ProtoHttpDestroy().
int32_t DirtyContextManagerFreeNetPoolContext (int32_t iSceNetContextId)
References DirtyContextManagerRefT::aNetContexts, DirtyContextManagerRefT::crit, DIRTYCM_MAX_NET_CONTEXTS, NetCritEnter(), and NetCritLeave().
Referenced by ProtoHttpCreate(), and ProtoHttpDestroy().
int32_t DirtyContextManagerFreeSslContext (int32_t iSslContextId)
References DirtyContextManagerRefT::aSslContextId, DirtyContextManagerRefT::crit, DIRTYCM_MAX_CONTEXTS, NetCritEnter(), and NetCritLeave().
Referenced by ProtoHttpCreate(), and ProtoHttpDestroy().
int32_t DirtyContextManagerInit ()
References DirtyContextManagerRefT::crit, DIRTYCM_MEMID, DirtyMemAlloc(), DirtyMemGroupQuery(), DirtyContextManagerRefT::iMemGroup, NetCritInit(), and DirtyContextManagerRefT::pMemGroupUserData.
Referenced by NetConnStartup().
void DirtyContextManagerShutdown ()
References DirtyContextManagerRefT::aHttpContextId, DirtyContextManagerRefT::aNetContexts, DirtyContextManagerRefT::aSslContextId, DirtyContextManagerRefT::crit, DIRTYCM_MAX_CONTEXTS, DIRTYCM_MAX_NET_CONTEXTS, DIRTYCM_MEMID, DirtyMemFree(), DirtyContextManagerRefT::iMemGroup, NetCritEnter(), NetCritKill(), NetCritLeave(), NetPrintf, and DirtyContextManagerRefT::pMemGroupUserData.
Referenced by NetConnShutdown().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:12