DirtySock: WebLog
WebLog
Misc
Typedefs
typedef struct WebLogRefT WebLogRefT
opaque module ref
Functions
DIRTYCODE_API WebLogRefT * WebLogCreate (int32_t iBufSize)
Create the WebLog module.
DIRTYCODE_API void WebLogConfigure (WebLogRefT *pWebLog, const char *pServer, const char *pUrl)
Configure weblog parameters.
DIRTYCODE_API void WebLogStart (WebLogRefT *pWebLog)
Starts logging.
DIRTYCODE_API void WebLogStop (WebLogRefT *pWebLog)
Stop logging and close close the current WebLog transaction (if any)
DIRTYCODE_API void WebLogDestroy (WebLogRefT *pWebLog)
Destroy the WebLog module.
DIRTYCODE_API int32_t WebLogDebugHook (void *pUserData, const char *pText)
WebLog NetPrintf debug hook.
DIRTYCODE_API void WebLogPrintf (WebLogRefT *pWebLog, const char *pFormat,...)
Print into the weblog buffer.
DIRTYCODE_API int32_t WebLogControl (WebLogRefT *pWebLog, int32_t iSelect, int32_t iValue, int32_t iValue2, void *pValue)
Control weblog behavior.
DIRTYCODE_API void WebLogUpdate (WebLogRefT *pWebLog)
Update the WebLog module.
Detailed Description
Typedef Documentation
typedef struct WebLogRefT WebLogRefT
opaque module ref
Function Documentation
DIRTYCODE_API void WebLogConfigure (WebLogRefT * pWebLog, const char * pServer, const char * pUrl)
Configure weblog parameters.
Parameters
*pWebLog - weblog module state
*pServer - server to post log to (NULL to retain current value)
*pUrl - url to post log to (NULL to retain current value)
Returns
None.
Version
05/14/2008 (jbrookes)
References ds_strnzcpy(), NULL, WebLogRefT::strWebHost, and WebLogRefT::strWebUrl.
DIRTYCODE_API int32_t WebLogControl (WebLogRefT * pWebLog, int32_t iSelect, int32_t iValue, int32_t iValue2, void * pValue)
Control weblog behavior.
Parameters
*pWebLog - weblog module state
iSelect - control selector
iValue - selector specific
iValue2 - selector specific
*pValue - selector specific
Returns
int32_t - selector specific
Note
Unhandled selectors are passed through to ProtoHttpControl()
Version
05/13/2008 (jbrookes)
References WebLogRefT::pProtoHttp, and ProtoHttpControl().
DIRTYCODE_API WebLogRefT* WebLogCreate (int32_t iBufSize)
Create the WebLog module.
Parameters
iBufSize - local text buffer size
Returns
WebLogRefT * - pointer to module state, or NULL
Version
05/06/2008 (jbrookes)
References DirtyMemAlloc(), DirtyMemGroupQuery(), ds_strnzcpy(), WebLogRefT::iBufLen, WebLogRefT::iMemGroup, NetCritInit(), NetPrintf, NULL, WebLogRefT::pMemGroupUserData, WebLogRefT::pProtoHttp, ProtoHttpCreate(), WebLogRefT::strWebHost, WebLogRefT::strWebUrl, WebLogRefT::WebCrit, WEBLOG_MEMID, and WebLogDestroy().
DIRTYCODE_API int32_t WebLogDebugHook (void * pUserData, const char * pText)
WebLog NetPrintf debug hook.
Parameters
*pUserData - user data
*pText - debug text
Returns
int32_t - zero to suppress debug output, else do not suppress
Version
05/06/2008 (jbrookes)
References WebLogPrintf().
DIRTYCODE_API void WebLogDestroy (WebLogRefT * pWebLog)
Destroy the WebLog module.
Parameters
*pWebLog - pointer to weblog module to destroy
Returns
None.
Version
05/06/2008 (jbrookes)
References DirtyMemFree(), WebLogRefT::iMemGroup, NetCritKill(), NULL, WebLogRefT::pMemGroupUserData, WebLogRefT::pProtoHttp, ProtoHttpDestroy(), WebLogRefT::WebCrit, and WEBLOG_MEMID.
Referenced by WebLogCreate().
DIRTYCODE_API void WebLogPrintf (WebLogRefT * pWebLog, const char * pFormat, ...)
Print into the weblog buffer.
Parameters
*pWebLog - weblog module state
*pFormat - format string
... - variable argument listing
Returns
None.
Version
05/06/2008 (jbrookes)
References WebLogRefT::bLogging, WebLogRefT::bUpdating, ds_strnzcat(), ds_vsnzprintf(), WebLogRefT::iBufLen, NetCritEnter(), NetCritLeave(), WebLogRefT::strText, and WebLogRefT::WebCrit.
Referenced by WebLogDebugHook().
DIRTYCODE_API void WebLogStart (WebLogRefT * pWebLog)
Starts logging.
Parameters
*pWebLog - weblog module state
Returns
None.
Version
05/06/2008 (jbrookes)
References WebLogRefT::bLogging, NetPrintf, and TRUE.
DIRTYCODE_API void WebLogStop (WebLogRefT * pWebLog)
Stop logging and close close the current WebLog transaction (if any)
Parameters
*pWebLog - weblog module state
Returns
None.
Version
05/06/2008 (jbrookes)
References WebLogRefT::bLogging, FALSE, and NetPrintf.
DIRTYCODE_API void WebLogUpdate (WebLogRefT * pWebLog)
Update the WebLog module.
Parameters
*pWebLog - weblog module state
Returns
None.
Version
05/06/2008 (jbrookes)
References WebLogRefT::bUpdating, FALSE, NetCritEnter(), NetCritLeave(), WebLogRefT::pProtoHttp, ProtoHttpUpdate(), TRUE, and WebLogRefT::WebCrit.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:32