DirtySock: DirtyUser
DirtyUser
DirtySock
Data Structures
struct DirtyUserT
opaque user type
Macros
#define DIRTYUSER_NATIVEUSER_MAXLEN (64)
#define DIRTYUSER_NATIVEUSER_MAXSIZE (DIRTYUSER_NATIVEUSER_MAXLEN + 1)
Typedefs
typedef struct DirtyUserT DirtyUserT
opaque user type
Functions
DIRTYCODE_API uint32_t DirtyUserToNativeUser (void *pOutput, int32_t iBufLen, const DirtyUserT *pUser)
convert a DirtyUserT to native format
DIRTYCODE_API uint32_t DirtyUserFromNativeUser (DirtyUserT *pUser, const void *pInput)
convert a native format to a DirtyUserT
DIRTYCODE_API uint32_t DirtyUserGetLocalUser (DirtyUserT *pUser, int32_t iUserIndex)
get DirtyUserT for local user at specific index
DIRTYCODE_API int32_t DirtyUserCompare (DirtyUserT *pUser1, DirtyUserT *pUser2)
compare two opaque users for equality (same=TRUE, different=FALSE)
Detailed Description
Macro Definition Documentation
#define DIRTYUSER_NATIVEUSER_MAXLEN (64)
#define DIRTYUSER_NATIVEUSER_MAXSIZE (DIRTYUSER_NATIVEUSER_MAXLEN + 1)
Referenced by _UserApiProcessPresenceResponse(), _UserApiProcessProfileResponse(), and _UserApiProcessRichPresenceResponse().
Typedef Documentation
typedef struct DirtyUserT DirtyUserT
opaque user type
Function Documentation
DIRTYCODE_API int32_t DirtyUserCompare (DirtyUserT * pUser1, DirtyUserT * pUser2)
compare two opaque users for equality (same=TRUE, different=FALSE)
compare two opaque users for equality (same=TRUE, different=FALSE)
Parameters
*pUser1 - user 1
*pUser2 - user 2
Returns
int32_t - TRUE if successful, else FALSE
Note
On PS4, a DirtyUserT is a string-encoded network-order sceNpId. To compare for equality certain portions of the sceNpId need to be ignored. Only the sceOnlineId's data portion is relevant.
Version
06/19/2013 (amakoukji)
References DirtyUserToNativeUser(), ds_strnicmp(), FALSE, and TRUE.
DIRTYCODE_API uint32_t DirtyUserFromNativeUser (DirtyUserT * pUser, const void * pInput)
convert a native format to a DirtyUserT
convert a native format to a DirtyUserT
Parameters
*pUser - [out] storage for output DirtyUserT
*pInput - pointer to native format user
Returns
uint32_t - TRUE if successful, else FALSE
Note
On PS4, a DirtyUserT is a string-encoded network-order sceNpId. This function converts a sceNpId into a DirtyUsertT.
Version
04/25/2013 (mclouatre)
References ds_memcpy(), DirtyUserT::strNativeUser, and TRUE.
Referenced by _UserApiProcessPresenceResponse(), _UserApiProcessProfileResponse(), _UserApiProcessRichPresenceResponse(), DirtySessionManagerStatus(), DirtySessionManagerStatus2(), and UserListApiUpdate().
DIRTYCODE_API uint32_t DirtyUserGetLocalUser (DirtyUserT * pUser, int32_t iUserIndex)
get DirtyUserT for local user at specific index
get DirtyUserT for local user at specific index
Parameters
*pUser - [out] storage for output DirtyUserT
*iUserIndex - local user index
Returns
uint32_t - TRUE if successful, else FALSE
Version
04/25/2013 (mclouatre)
References FALSE.
DIRTYCODE_API uint32_t DirtyUserToNativeUser (void * pOutput, int32_t iBufLen, const DirtyUserT * pUser)
convert a DirtyUserT to native format
convert a DirtyUserT to native format
Parameters
*pOutput - [out] storage for native format user
iBufLen - length of output buffer
*pUser - source user to convert
Returns
uint32_t - TRUE if successful, else FALSE
Note
On PS4, a DirtyUserT is a string-encoded network-order sceNpId. This function converts that input into a sceNpId.
Version
04/25/2013 (mclouatre)
References ds_memcpy(), FALSE, DirtyUserT::strNativeUser, and TRUE.
Referenced by DirtyUserCompare(), UserApiPlatRequestPresence(), UserApiPlatRequestRecentlyMet(), UserApiPlatRequestRichPresence(), UserApiPlatUpdate(), UserListApiIsBlockedAsync(), and UserListApiIsFriendAsync().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:32