DirtySock: connapixenon.c File Reference
connapixenon.c File Reference
ConnApi is a high-level connection manager, that packages the "connect to peer" process into a single module. Both game connections and voice connections can be managed. Multiple peers are supported in a host/client model for the game connection, and a peer/peer model for the voice connections.
#include <xtl.h>
#include <stdio.h>
#include <string.h>
#include "DirtySDK/dirtysock.h"
#include "DirtySDK/dirtysock/dirtymem.h"
#include "DirtySDK/dirtysock/dirtynames.h"
#include "DirtySDK/dirtysock/dirtysessionmanager.h"
#include "DirtySDK/dirtysock/xenon/dirtylspxenon.h"
#include "DirtySDK/game/xenon/connapixenonsessionmanager.h"
#include "DirtySDK/proto/prototunnel.h"
#include "DirtySDK/voip/voip.h"
#include "DirtySDK/voip/voipgroup.h"
#include "DirtySDK/game/connapi.h"
Data Structures
struct ConnApiRefT
Macros
#define CONNAPI_TIMEOUT_DEFAULT (15*1000)
default connapi timeout
#define CONNAPI_CONNTIMEOUT (10*1000)
connapi connection timeout
#define CONNAPI_LINKBUFDEFAULT (1024)
default GameLink buffer size
#define CONNAPI_MAX_CALLBACKS (8)
max number of registered callbacks
#define CONNAPI_CLIENTFLAG_REMOVE (1)
connapi client flags
Typedefs
typedef enum ConnApiStateE ConnApiStateE
connapi states
Enumerations
enum ConnApiStateE {
ST_IDLE,
ST_SESSION,
ST_MIGRATE,
ST_INGAME,
ST_DELETING,
ST_SESSION_UPDATE
}
connapi states
Functions
void _ConnApiSetStatus (ConnApiRefT *pConnApi, ConnApiClientT *pClient, ConnApiConnStatusE *pStatus, uint8_t uStatus)
Set status of a given game or voip connection.
ConnApiRefT * ConnApiCreate2 (int32_t iGamePort, int32_t iMaxClients, ConnApiCallbackT *pCallback, void *pUserData, CommAllConstructT *pConstruct)
Create the module state.
void ConnApiOnline (ConnApiRefT *pConnApi, const char *pGameName, uint32_t uSelfId)
This function should be called once the user has logged on and the input parameters are available.
void ConnApiDestroy (ConnApiRefT *pConnApi)
Destroy the module state.
void ConnApiConnect (ConnApiRefT *pConnApi, ConnApiClientInfoT *pClientList, int32_t iClientListSize, int32_t iTopologyHostIndex, int32_t iPlatformHostIndex, int32_t iSessId, uint32_t uGameFlags)
Connect to a game.
void ConnApiMigrateTopologyHost (ConnApiRefT *pConnApi, int32_t iNewTopologyHostIndex)
Reopen all connections, using the topology host index specified. This is for host migration to a different host in non-peerweb, needing new connections for everyone.
void ConnApiMigratePlatformHost (ConnApiRefT *pConnApi, int32_t iNewPlatformHostIndex, void *pPlatformData)
Specified client index becomes responsible for managing platform (session owner)
int32_t ConnApiAddClient (ConnApiRefT *pConnApi, ConnApiClientInfoT *pClientInfo, int32_t iClientIndex)
Add a new client to a pre-existing game.
int32_t ConnApiAddUser (ConnApiRefT *pConnApi, int32_t iClientIndex, ConnApiUserInfoT *pUserInfo)
Add a new user to a specific client in a pre-existing game.
uint8_t ConnApiFindClient (ConnApiRefT *pConnApi, ConnApiClientInfoT *pClientInfo, ConnApiClientT *pOutClient)
Returns the ConnApiClientT of a given client, if found by id.
void ConnApiRemoveClient (ConnApiRefT *pConnApi, int32_t iClientIndex)
Remove a current client from a game.
void ConnApiRemoveUser (ConnApiRefT *pConnApi, int32_t iClientIdx, int32_t iUserIndex)
Remove a user from a specific client in a game.
void ConnApiStart (ConnApiRefT *pConnApi, uint32_t uStartFlags)
Start game session.
void ConnApiStop (ConnApiRefT *pConnApi)
End game session.
void ConnApiRematch (ConnApiRefT *pConnApi)
Rematch the game session.
void ConnApiSetPresence (ConnApiRefT *pConnApi, uint8_t uPresenceEnabled)
Switch to a presence enabled(or disabled) session. Two steps: 1- Set/Reset presence flag to be used at 'next' secondary session creation, because the presence attribute cannot be changed after a session is created. 2- Force a rematch to destroy current secondary session and create a new one. Note: The secondary session is the one that is created with or without presence support enabled.
void ConnApiDisconnect (ConnApiRefT *pConnApi)
Stop game, disconnect from peers, reset client list, and disconnect from the game server. Added so that ConnApiDisconnectPartial could be called directly when connection to the game server was to be kept.
const ConnApiClientListT * ConnApiGetClientList (ConnApiRefT *pConnApi)
Get a list of current connections.
int32_t ConnApiStatus (ConnApiRefT *pConnApi, int32_t iSelect, void *pBuf, int32_t iBufSize)
Get status information.
int32_t ConnApiStatus2 (ConnApiRefT *pConnApi, int32_t iSelect, void *pData, void *pBuf, int32_t iBufSize)
Get status information.
int32_t ConnApiControl (ConnApiRefT *pConnApi, int32_t iControl, int32_t iValue, int32_t iValue2, void *pValue)
Control behavior of module.
void ConnApiUpdate (ConnApiRefT *pConnApi)
Update the ConnApi module (must be called directly if auto-update is disabled)
int32_t ConnApiAddCallback (ConnApiRefT *pConnApi, ConnApiCallbackT *pCallback, void *pUserData)
Register a new callback.
int32_t ConnApiRemoveCallback (ConnApiRefT *pConnApi, ConnApiCallbackT *pCallback, void *pUserData)
Unregister a callback.
char * ConnApiGetSessionPattern (const void *pFirstPartyStruct, int32_t *pFrom, int32_t *pLength)
Return a string and range showing what a session string, with a specific first-party session in it, would look like. This is to allow an invitee getting the invite from the system HUD to check if a given game session string matches it.
Detailed Description
ConnApi is a high-level connection manager, that packages the "connect to peer" process into a single module. Both game connections and voice connections can be managed. Multiple peers are supported in a host/client model for the game connection, and a peer/peer model for the voice connections.
Attention
Copyright (c) Electronic Arts 2005. ALL RIGHTS RESERVED.
Version
01/04/2005 (jbrookes) First Version
Macro Definition Documentation
#define CONNAPI_CLIENTFLAG_REMOVE (1)
connapi client flags
Referenced by ConnApiRemoveClient().
#define CONNAPI_CONNTIMEOUT (10*1000)
connapi connection timeout
#define CONNAPI_LINKBUFDEFAULT (1024)
default GameLink buffer size
Referenced by ConnApiCreate2().
#define CONNAPI_MAX_CALLBACKS (8)
max number of registered callbacks
Referenced by ConnApiAddCallback(), ConnApiRemoveCallback(), and ConnApiStop().
#define CONNAPI_TIMEOUT_DEFAULT (15*1000)
default connapi timeout
Referenced by ConnApiCreate2().
Typedef Documentation
typedef enum ConnApiStateE ConnApiStateE
connapi states
Enumeration Type Documentation
enum ConnApiStateE
connapi states
Enumerator
ST_IDLE
idle
ST_SESSION
waiting for session
ST_MIGRATE
waiting for platform host migration to complete
ST_INGAME
ST_DELETING
deleting session
ST_SESSION_UPDATE
waiting for the session update after a 'stop'
Function Documentation
void _ConnApiSetStatus (ConnApiRefT * pConnApi, ConnApiClientT * pClient, ConnApiConnStatusE * pStatus, uint8_t uStatus)
Set status of a given game or voip connection.
Parameters
*pConnApi - connection manager ref
*pClient - client being modified
*pStatus - pointer to the status field
uStatus - new status
Version
03/14/2011 (jrainy)
References ConnApiRefT::ClientList, ConnApiClientListT::Clients, ConnApiConnInfoT::eStatus, ConnApiClientT::GameInfo, NetPrintf, and ConnApiClientT::VoipInfo.
Referenced by ConnApiMigrateTopologyHost().
int32_t ConnApiAddUser (ConnApiRefT * pConnApi, int32_t iClientIndex, ConnApiUserInfoT * pUserInfo)
Add a new user to a specific client in a pre-existing game.
Parameters
*pConnApi - pointer to module state
iClientIndex - index of client to add user to
*pUserInfo - info on joining user
Returns
int32_t - 0 if successful, error code otherwise.
Version
04/07/2011 (jrainy)
References ConnApiClientT::ClientInfo, ConnApiRefT::ClientList, ConnApiClientListT::Clients, ConnApiClientInfoT::DirtyAddr, ds_memcpy(), FALSE, NETCONN_MAXLOCALUSERS, NetPrintf, DirtyAddrT::strMachineAddr, TRUE, and ConnApiRefT::uSessionJoinPending.
void ConnApiRemoveUser (ConnApiRefT * pConnApi, int32_t iClientIdx, int32_t iUserIndex)
Remove a user from a specific client in a game.
Parameters
*pConnApi - pointer to module state
iClientIdx - index of client to add user to
iUserIndex - index of the user to remove
Version
04/07/2011 (jrainy)
References ConnApiClientT::ClientInfo, ConnApiRefT::ClientList, ConnApiClientListT::Clients, ConnApiXenonSessionManagerControl(), ConnApiClientInfoT::DirtyAddr, FALSE, NETCONN_MAXLOCALUSERS, NetPrintf, ConnApiRefT::pSessionManager, and DirtyAddrT::strMachineAddr.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:54