DirtySock: ProtoHttpServ
ProtoHttpServ
Proto
Data Structures
struct ProtoHttpServRequestT
struct ProtoHttpServResponseT
Macros
#define PROTOHTTPSERV_FLAG_LOOPBACK (0x01)
when set, only traffic from the same host will be accepted on the listen port
Typedefs
typedef struct
ProtoHttpServRequestT ProtoHttpServRequestT
typedef struct
ProtoHttpServResponseT ProtoHttpServResponseT
typedef int32_t(ProtoHttpServRequestCbT)(ProtoHttpServRequestT *pRequest, ProtoHttpServResponseT *pResponse, void *pUserData)
Invoked when a request is ready for processing.
typedef int32_t(ProtoHttpServReceiveCbT)(ProtoHttpServRequestT *pRequest, const char *pBuffer, int32_t iBufSize, void *pUserData)
Invoked when new incoming data is received for a request.
typedef int32_t(ProtoHttpServSendCbT)(ProtoHttpServResponseT *pResponse, char *pBuffer, int32_t iBufSize, void *pUserData)
Invoked when outgoing data needs to be sent for the response.
typedef int32_t(ProtoHttpServHeaderCbT)(ProtoHttpServRequestT *pRequest, ProtoHttpServResponseT *pResponse, void *pUserData)
Invoked when a new request header is received.
typedef void(ProtoHttpServLogCbT)(const char *pText, void *pUserData)
logging function type
typedef struct ProtoHttpServRefT ProtoHttpServRefT
opaque module ref
Functions
DIRTYCODE_API ProtoHttpServRefT * ProtoHttpServCreate (int32_t iPort, int32_t iSecure, const char *pName)
create an httpserv module
DIRTYCODE_API ProtoHttpServRefT * ProtoHttpServCreate2 (int32_t iPort, int32_t iSecure, const char *pName, uint32_t uFlags)
create an httpserv module
DIRTYCODE_API void ProtoHttpServDestroy (ProtoHttpServRefT *pHttpServ)
destroy an httpserv module
DIRTYCODE_API void ProtoHttpServCallback (ProtoHttpServRefT *pHttpServ, ProtoHttpServRequestCbT *pRequestCb, ProtoHttpServReceiveCbT *pReceiveCb, ProtoHttpServSendCbT *pSendCb, ProtoHttpServHeaderCbT *pHeaderCb, ProtoHttpServLogCbT *pLogCb, void *pUserData)
set httpserv callback function handlers (required)
DIRTYCODE_API int32_t ProtoHttpServControl (ProtoHttpServRefT *pHttpServ, int32_t iSelect, int32_t iValue, int32_t iValue2, void *pValue)
control function; functionality based on input selector
DIRTYCODE_API int32_t ProtoHttpServStatus (ProtoHttpServRefT *pHttpServ, int32_t iSelect, void *pBuffer, int32_t iBufSize)
return module status based on input selector
DIRTYCODE_API void ProtoHttpServUpdate (ProtoHttpServRefT *pHttpServ)
update the module
Detailed Description
Macro Definition Documentation
#define PROTOHTTPSERV_FLAG_LOOPBACK (0x01)
when set, only traffic from the same host will be accepted on the listen port
Typedef Documentation
ProtoHttpServHeaderCbT
Invoked when a new request header is received.
Parameters
*pRequest - [in/out] Information about the request we are going to process
*pResponse - [out] Used for handling the response, this allows us to error if header is malformed
*pUserData - User Specific Data that was passed into ProtoHttpServCallback
Returns
int32_t - positive=success, negative=error
typedef void(ProtoHttpServLogCbT)(const char *pText, void *pUserData)
logging function type
ProtoHttpServReceiveCbT
Invoked when new incoming data is received for a request.
Parameters
*pRequest - [in/out] Information about the request
*pBuffer - The data that was received (NULL when complete)
iBufSize - The size of the data received (zero when complete)
*pUserData - User Specific Data that was passed into ProtoHttpServCallback
Returns
int32_t - zero=no data processed, positive=amount of data processed, negative=error
typedef struct ProtoHttpServRefT ProtoHttpServRefT
opaque module ref
ProtoHttpServRequestCbT
Invoked when a request is ready for processing.
Parameters
*pRequest - Information that allows for processing of request
*pResponse - [out] Information that ProtoHttpServ used in responding to the request
*pUserData - User Specific Data that was passed into ProtoHttpServCallback
Returns
int32_t - zero=complete, positive=in-progress, negative=error
typedef struct ProtoHttpServRequestT ProtoHttpServRequestT
typedef struct ProtoHttpServResponseT ProtoHttpServResponseT
ProtoHttpServSendCbT
Invoked when outgoing data needs to be sent for the response.
Parameters
*pResponse - Information about the response we are sending
*pBuffer - The data we are writting to for the response (NULL when complete)
iBufSize - The size of the outgoing buffer (zero when complete)
*pUserData - User Specific Data that was passed into ProtoHttpServCallback
Returns
int32_t - positive=amount of data written, other=error
Function Documentation
DIRTYCODE_API void ProtoHttpServCallback (ProtoHttpServRefT * pHttpServ, ProtoHttpServRequestCbT * pRequestCb, ProtoHttpServReceiveCbT * pReceiveCb, ProtoHttpServSendCbT * pSendCb, ProtoHttpServHeaderCbT * pHeaderCb, ProtoHttpServLogCbT * pLogCb, void * pUserData)
set httpserv callback function handlers (required)
set httpserv callback function handlers (required)
Parameters
*pHttpServ - module state
*pRequestCb - request handler callback
*pReceiveCb - inbound data handler callback
*pSendCb - outbound data handler callback
*pHeaderCb - inbound header callback
*pLogCb - logging function to use (optional)
*pUserData - user data for callbacks
Version
12/11/2013 (jbrookes)
References ProtoHttpServRefT::pHeaderCb, ProtoHttpServRefT::pLogCb, ProtoHttpServRefT::pReceiveCb, ProtoHttpServRefT::pRequestCb, ProtoHttpServRefT::pSendCb, and ProtoHttpServRefT::pUserData.
DIRTYCODE_API int32_t ProtoHttpServControl (ProtoHttpServRefT * pHttpServ, int32_t iSelect, int32_t iValue, int32_t iValue2, void * pValue)
control function; functionality based on input selector
control function; functionality based on input selector
Parameters
*pHttpServ - reference pointer
iSelect - control selector
iValue - selector specific
iValue2 - selector specific
*pValue - selector specific
Returns
int32_t - selector specific
Note
Selectors are:
        SELECTOR    DESCRIPTION
        'ccrt'      Set client certificate (pValue=cert, iValue=len)
        'ciph'      Set supported cipher suites (iValue=PROTOSSL_CIPHER_*; default=PROTOSSL_CIPHER_ALL)
        'idle'      Set idle timeout (iValue=timeout; default=5 minutes)
        'scrt'      Set certificate (pValue=cert, iValue=len)
        'skey'      Set private key (pValue=key, iValue=len)
        'time'      Set request timeout in milliseconds (iValue=timeout; default=30 seconds)
        'vers'      Set server-supported maximum SSL version (iValue=version; default=0x302, TLS1.1)
        'vmin'      Set server-required minimum SSL version (iValue=version; default=0x300, SSLv3)
Version
12/12/2013 (jbrookes)
References ProtoHttpServRefT::iClientCertLvl, ProtoHttpServRefT::iIdleTimeout, ProtoHttpServRefT::iRequestTimeout, ProtoHttpServRefT::iServerCertLen, ProtoHttpServRefT::iServerKeyLen, ProtoHttpServRefT::pServerCert, ProtoHttpServRefT::pServerKey, ProtoHttpServRefT::uDebugLevel, ProtoHttpServRefT::uSslCiphers, ProtoHttpServRefT::uSslVersion, and ProtoHttpServRefT::uSslVersionMin.
DIRTYCODE_API ProtoHttpServRefT* ProtoHttpServCreate (int32_t iPort, int32_t iSecure, const char * pName)
create an httpserv module
create an httpserv module
Parameters
iPort - port to listen on
iSecure - TRUE if secure, else FALSE
*pName - name of server, used in Server: header
Returns
ProtoHttpServRefT * - pointer to state, or null on failure
Version
12/11/2013 (jbrookes)
References ProtoHttpServCreate2().
DIRTYCODE_API ProtoHttpServRefT* ProtoHttpServCreate2 (int32_t iPort, int32_t iSecure, const char * pName, uint32_t uFlags)
create an httpserv module
create an httpserv module
Parameters
iPort - port to listen on
iSecure - TRUE if secure, else FALSE
*pName - name of server, used in Server: header
uFlags - flag field, use PROTOHTTPSERV_FLAG_*
Returns
ProtoHttpServRefT * - pointer to state, or null on failure
Version
02/22/2016 (amakoukji)
References DirtyMemAlloc(), DirtyMemGroupQuery(), ds_strnzcpy(), HTTPSERV_IDLETIMEOUT_DEFAULT, HTTPSERV_MEMID, HTTPSERV_REQUESTTIMEOUT_DEFAULT, ProtoHttpServRefT::iIdleTimeout, ProtoHttpServRefT::iMemGroup, ProtoHttpServRefT::iRequestTimeout, ProtoHttpServRefT::iSecure, ProtoHttpServRefT::pListenSSL, ProtoHttpServRefT::pMemGroupUserData, ProtoHttpServDestroy(), PROTOSSL_CIPHER_ALL, ProtoSSLListen(), SOCKERR_NONE, ProtoHttpServRefT::strServerName, TRUE, ProtoHttpServRefT::uCurrThreadId, ProtoHttpServRefT::uDebugLevel, and ProtoHttpServRefT::uSslCiphers.
Referenced by ProtoHttpServCreate().
DIRTYCODE_API void ProtoHttpServDestroy (ProtoHttpServRefT * pHttpServ)
destroy an httpserv module
destroy an httpserv module
Parameters
*pHttpServ - module state to destroy
Version
12/11/2013 (jbrookes)
References DirtyMemFree(), HTTPSERV_MEMID, ProtoHttpServRefT::iMemGroup, ProtoHttpServRefT::pListenSSL, ProtoHttpServRefT::pMemGroupUserData, ProtoHttpServThreadT::pNext, ProtoSSLDestroy(), and ProtoHttpServRefT::pThreadList.
Referenced by ProtoHttpServCreate2().
DIRTYCODE_API int32_t ProtoHttpServStatus (ProtoHttpServRefT * pHttpServ, int32_t iSelect, void * pBuffer, int32_t iBufSize)
return module status based on input selector
return module status based on input selector
Parameters
*pHttpServ - module state
iSelect - info selector (see Notes)
*pBuffer - [out] storage for selector-specific output
iBufSize - size of buffer
Returns
int32_t - selector specific
Note
Selectors are:
    SELECTOR    RETURN RESULT
Version
12/12/2013 (jbrookes)
DIRTYCODE_API void ProtoHttpServUpdate (ProtoHttpServRefT * pHttpServ)
update the module
update the module
Parameters
*pHttpServ - module state
Version
10/30/2013 (jbrookes)
References ProtoHttpServThreadT::bDisconnecting, HTTPSERV_DISCTIME, ProtoHttpServThreadT::iDisconnectTimer, NetTick(), NetTickDiff, ProtoHttpServRefT::pListenSSL, ProtoHttpServThreadT::pNext, and ProtoHttpServRefT::pThreadList.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:49