DirtySock: VoipTunnel
VoipTunnel
Voip
Data Structures
struct VoipTunnelClientT
voiptunnel client info
struct VoipTunnelGameT
game structure
struct VoipTunnelEventDataT
voiptunnel callback data
Macros
#define VOIPTUNNEL_MAXGROUPSIZE (32)
max number of clients that can appear in a group
#define VOIPTUNNEL_RECVVOICE_TIMEOUT_DEFAULT (1 * 1000)
default amount of time elapsed before incoming voice is assumed to be stopped, in milliseconds
#define VOIPTUNNEL_MAX_BROADCASTING_VOICES_DEFAULT 4
default maximum number of players can be talking at once in a single game
#define VOIPTUNNEL_CLIENTFLAG_RECVVOICE (1<<0)
voiptunnel is currently receiving voice from this client
#define VOIPTUNNEL_CLIENTFLAG_MAX_VOICES_REACHED (1<<1)
this client has reached its max simultaneous talkers
#define VOIPTUNNEL_CLIENTFLAG_BROADCASTING_VOICE (1<<1)
TODO: V9 Deprecate voiptunnel is broadcasting voice from this client.
#define VOIPTUNNEL_GAMEFLAG_MAX_VOICES_REACHED (1<<0)
TODO: V9 Deprecate this game has reached its max simultaneous talkers.
Typedefs
typedef enum VoipTunnelEventE VoipTunnelEventE
voiptunnel event types
typedef struct VoipTunnelClientT VoipTunnelClientT
voiptunnel client info
typedef struct VoipTunnelGameT VoipTunnelGameT
game structure
typedef struct VoipTunnelRefT VoipTunnelRefT
opaque module state
typedef struct VoipTunnelEventDataT VoipTunnelEventDataT
voiptunnel callback data
typedef void(VoipTunnelCallbackT)(VoipTunnelRefT *pVoipTunnel, const VoipTunnelEventDataT *pEventData, void *pUserData)
voiptunnel event callback
typedef int32_t(VoipTunnelMatchFuncT)(VoipTunnelClientT *pClient, void *pUserData)
voiptunnel match function
Enumerations
enum VoipTunnelEventE {
VOIPTUNNEL_EVENT_ADDCLIENT,
VOIPTUNNEL_EVENT_DELCLIENT,
VOIPTUNNEL_EVENT_MATCHADDR,
VOIPTUNNEL_EVENT_MATCHPORT,
VOIPTUNNEL_EVENT_RECVVOICE,
VOIPTUNNEL_EVENT_SENDVOICE,
VOIPTUNNEL_EVENT_DEADVOICE,
VOIPTUNNEL_EVENT_MAXDVOICE,
VOIPTUNNEL_EVENT_AVLBVOICE,
VOIPTUNNEL_NUMEVENTS
}
voiptunnel event types
Functions
DIRTYCODE_API VoipTunnelRefT * VoipTunnelCreate (uint32_t uVoipPort, int32_t iMaxClients, int32_t iMaxGames)
Create the VoipTunnel module.
DIRTYCODE_API void VoipTunnelCallback (VoipTunnelRefT *pVoipTunnel, VoipTunnelCallbackT *pCallback, void *pUserData)
Set optional voiptunnel event callback.
DIRTYCODE_API void VoipTunnelDestroy (VoipTunnelRefT *pVoipTunnel)
Shutdown this VoipTunnel.
DIRTYCODE_API int32_t VoipTunnelClientListAdd (VoipTunnelRefT *pVoipTunnel, const VoipTunnelClientT *pClientInfo, VoipTunnelClientT **ppNewClient)
Add a new client to the client list.
DIRTYCODE_API int32_t VoipTunnelClientListAdd2 (VoipTunnelRefT *pVoipTunnel, const VoipTunnelClientT *pClientInfo, VoipTunnelClientT **ppNewClient, int32_t iIndex)
Add a new client to the client list.
DIRTYCODE_API void VoipTunnelClientListDel (VoipTunnelRefT *pVoipTunnel, VoipTunnelClientT *pClient, int32_t iClient)
Remove client from the client list.
DIRTYCODE_API int32_t VoipTunnelGameListAdd (VoipTunnelRefT *pVoipTunnel, int32_t iGameIdx)
Add a new game.
DIRTYCODE_API int32_t VoipTunnelGameListDel (VoipTunnelRefT *pVoipTunnel, int32_t iGameIdx)
Remove all clients from the client list who have the given GameServer index.
DIRTYCODE_API VoipTunnelClientT * VoipTunnelClientListMatchAddr (VoipTunnelRefT *pVoipTunnel, uint32_t uRemoteAddr)
Return client matching given address.
DIRTYCODE_API VoipTunnelClientT * VoipTunnelClientListMatchId (VoipTunnelRefT *pVoipTunnel, uint32_t uClientId)
Return client matching given address.
DIRTYCODE_API VoipTunnelClientT * VoipTunnelClientListMatchIndex (VoipTunnelRefT *pVoipTunnel, uint32_t uClientIndex)
Return client at the given index.
DIRTYCODE_API VoipTunnelClientT * VoipTunnelClientListMatchSockaddr (VoipTunnelRefT *pVoipTunnel, struct sockaddr *pSockaddr)
Return client matching the address and port in the specified sockaddr.
DIRTYCODE_API VoipTunnelClientT * VoipTunnelClientListMatchFunc (VoipTunnelRefT *pVoipTunnel, VoipTunnelMatchFuncT *pMatchFunc, void *pUserData)
Return client matching criteria of matching function.
DIRTYCODE_API void VoipTunnelClientRefreshSendMask (VoipTunnelRefT *pVoipTunnel, VoipTunnelClientT *pClient)
Let api know client's send list has been updated.
DIRTYCODE_API int32_t VoipTunnelStatus (VoipTunnelRefT *pVoipTunnel, int32_t iSelect, int32_t iValue, void *pBuf, int32_t iBufSize)
Get module status.
DIRTYCODE_API int32_t VoipTunnelControl (VoipTunnelRefT *pVoipTunnel, int32_t iControl, int32_t iValue, int32_t iValue2, const void *pValue)
Control the module.
DIRTYCODE_API void VoipTunnelUpdate (VoipTunnelRefT *pVoipTunnel)
Update the module.
Detailed Description
Macro Definition Documentation
#define VOIPTUNNEL_CLIENTFLAG_BROADCASTING_VOICE (1<<1)
TODO: V9 Deprecate voiptunnel is broadcasting voice from this client.
#define VOIPTUNNEL_CLIENTFLAG_MAX_VOICES_REACHED (1<<1)
this client has reached its max simultaneous talkers
#define VOIPTUNNEL_CLIENTFLAG_RECVVOICE (1<<0)
voiptunnel is currently receiving voice from this client
#define VOIPTUNNEL_GAMEFLAG_MAX_VOICES_REACHED (1<<0)
TODO: V9 Deprecate this game has reached its max simultaneous talkers.
#define VOIPTUNNEL_MAX_BROADCASTING_VOICES_DEFAULT 4
default maximum number of players can be talking at once in a single game
Referenced by VoipTunnelCreate().
#define VOIPTUNNEL_MAXGROUPSIZE (32)
max number of clients that can appear in a group
Referenced by VoipTunnelClientListAdd2(), and VoipTunnelClientRefreshSendMask().
#define VOIPTUNNEL_RECVVOICE_TIMEOUT_DEFAULT (1 * 1000)
default amount of time elapsed before incoming voice is assumed to be stopped, in milliseconds
Referenced by VoipTunnelCreate().
Typedef Documentation
typedef void(VoipTunnelCallbackT)(VoipTunnelRefT *pVoipTunnel, const VoipTunnelEventDataT *pEventData, void *pUserData)
voiptunnel event callback
typedef struct VoipTunnelClientT VoipTunnelClientT
voiptunnel client info
typedef struct VoipTunnelEventDataT VoipTunnelEventDataT
voiptunnel callback data
typedef enum VoipTunnelEventE VoipTunnelEventE
voiptunnel event types
typedef struct VoipTunnelGameT VoipTunnelGameT
game structure
typedef int32_t(VoipTunnelMatchFuncT)(VoipTunnelClientT *pClient, void *pUserData)
voiptunnel match function
typedef struct VoipTunnelRefT VoipTunnelRefT
opaque module state
Enumeration Type Documentation
enum VoipTunnelEventE
voiptunnel event types
Enumerator
VOIPTUNNEL_EVENT_ADDCLIENT
client added to client list
VOIPTUNNEL_EVENT_DELCLIENT
client removed from client list
VOIPTUNNEL_EVENT_MATCHADDR
client matched addr
VOIPTUNNEL_EVENT_MATCHPORT
client matched port
VOIPTUNNEL_EVENT_RECVVOICE
received voice data from client
VOIPTUNNEL_EVENT_SENDVOICE
sending voice data to client
VOIPTUNNEL_EVENT_DEADVOICE
voice connection has gone dead
VOIPTUNNEL_EVENT_MAXDVOICE
additional clients attempting to send voice will not be rebroadcast
VOIPTUNNEL_EVENT_AVLBVOICE
additional clients may once again send voice
VOIPTUNNEL_NUMEVENTS
total number of events
Function Documentation
DIRTYCODE_API void VoipTunnelCallback (VoipTunnelRefT * pVoipTunnel, VoipTunnelCallbackT * pCallback, void * pUserData)
Set optional voiptunnel event callback.
Parameters
*pVoipTunnel - voiptunnel ref
*pCallback - callback pointer
*pUserData - callback user data
Version
03/24/2006 (jbrookes)
References VoipTunnelRefT::pCallback, and VoipTunnelRefT::pUserData.
DIRTYCODE_API int32_t VoipTunnelClientListAdd (VoipTunnelRefT * pVoipTunnel, const VoipTunnelClientT * pClientInfo, VoipTunnelClientT ** ppNewClient)
Add a new client to the client list.
Parameters
*pVoipTunnel - voiptunnel ref
*pClientInfo - new client info
**ppNewClient - [out] new client pointer (optional; can be NULL)
Returns
int32_t - negative=error, else success
Version
03/27/2006 (jbrookes)
References VoipTunnelClientListAdd2().
DIRTYCODE_API int32_t VoipTunnelClientListAdd2 (VoipTunnelRefT * pVoipTunnel, const VoipTunnelClientT * pClientInfo, VoipTunnelClientT ** ppNewClient, int32_t iStartIndex)
Add a new client to the client list.
Parameters
*pVoipTunnel - voiptunnel ref, at the first empty spot past a given index
*pClientInfo - new client info
**ppNewClient - [out] new client pointer (optional; can be NULL)
iStartIndex - index to add at
Returns
int32_t - negative=error, else success
Version
10/18/2011 (jrainy)
References VoipTunnelGameT::aClientList, VoipTunnelRefT::ClientList, ds_memcpy_s(), VoipTunnelClientT::iGameIdx, VoipTunnelRefT::iMaxClients, VoipTunnelRefT::iMaxGames, VoipTunnelRefT::iNumClients, VoipTunnelGameT::iNumClients, VoipTunnelClientT::iNumTalker, NetPrintf, NULL, VoipTunnelRefT::pGameList, VoipTunnelClientT::uClientId, VoipTunnelRefT::uDebugLevel, VoipTunnelClientT::uSendMask, VOIPTUNNEL_EVENT_ADDCLIENT, and VOIPTUNNEL_MAXGROUPSIZE.
Referenced by VoipTunnelClientListAdd().
DIRTYCODE_API void VoipTunnelClientListDel (VoipTunnelRefT * pVoipTunnel, VoipTunnelClientT * pClient, int32_t iClient)
Remove client from the client list.
Parameters
*pVoipTunnel - voiptunnel ref
*pClient - client to remove, or null
iClient - index of client to remove, if pClient is null
Version
04/10/2006 (jbrookes)
References VoipTunnelRefT::ClientList, VoipTunnelRefT::iMaxClients, NetPrintf, and NULL.
DIRTYCODE_API VoipTunnelClientT* VoipTunnelClientListMatchAddr (VoipTunnelRefT * pVoipTunnel, uint32_t uRemoteAddr)
Return client matching given address.
Parameters
*pVoipTunnel - voiptunnel ref
uRemoteAddr - address incoming packet originated from
Returns
VoipTunnelClientT * - pointer to new client, or NULL
Version
03/27/2006 (jbrookes)
References VoipTunnelRefT::ClientList, NULL, and VoipTunnelClientT::uRemoteAddr.
DIRTYCODE_API VoipTunnelClientT* VoipTunnelClientListMatchFunc (VoipTunnelRefT * pVoipTunnel, VoipTunnelMatchFuncT * pMatchFunc, void * pUserData)
Return client matching criteria of matching function.
Parameters
*pVoipTunnel - voiptunnel ref
*pMatchFunc - function to call to indicate if we have a match or not
*pUserData - user data to pass to match function
Returns
VoipTunnelClientT * - pointer to found client, or NULL
Version
04/10/2007 (jbrookes)
References VoipTunnelRefT::ClientList, and NULL.
DIRTYCODE_API VoipTunnelClientT* VoipTunnelClientListMatchId (VoipTunnelRefT * pVoipTunnel, uint32_t uClientId)
Return client matching given address.
Parameters
*pVoipTunnel - voiptunnel ref
uClientId - unique client identifier
Returns
VoipTunnelClientT * - pointer to matching client, or NULL
Version
03/27/2006 (jbrookes)
References VoipTunnelRefT::ClientList, VoipTunnelRefT::iNumClients, NULL, VoipTunnelRefT::pLookupTable, and VoipTunnelClientT::uClientId.
DIRTYCODE_API VoipTunnelClientT* VoipTunnelClientListMatchIndex (VoipTunnelRefT * pVoipTunnel, uint32_t uClientIndex)
Return client at the given index.
Parameters
*pVoipTunnel - voiptunnel ref
uClientIndex - index of client in client list
Returns
VoipTunnelClientT * - pointer to client, or NULL
Version
03/13/2007 (jbrookes)
References VoipTunnelRefT::ClientList, VoipTunnelRefT::iNumClients, and NULL.
DIRTYCODE_API VoipTunnelClientT* VoipTunnelClientListMatchSockaddr (VoipTunnelRefT * pVoipTunnel, struct sockaddr * pSockaddr)
Return client matching the address and port in the specified sockaddr.
Parameters
*pVoipTunnel - voiptunnel ref
*pSockaddr - sockaddr containing addr and port to match
Returns
VoipTunnelClientT * - pointer to matching client, or NULL
Version
03/13/2007 (jbrookes)
References VoipTunnelRefT::ClientList, NULL, SockaddrInGetAddr, SockaddrInGetPort, VoipTunnelClientT::uRemoteAddr, and VoipTunnelClientT::uRemoteGamePort.
DIRTYCODE_API void VoipTunnelClientRefreshSendMask (VoipTunnelRefT * pVoipTunnel, VoipTunnelClientT * pClient)
Let api know client's send list has been updated.
Parameters
*pVoipTunnel - voiptunnel ref
*pClient - client whose send list has been updated
Version
06/10/2007 (jbrookes)
References VoipTunnelClientT::aClientIds, VoipTunnelGameT::aClientList, FALSE, VoipTunnelClientT::iGameIdx, NetPrintf, VoipTunnelRefT::pGameList, TRUE, VoipTunnelClientT::uClientId, VoipTunnelClientT::uGameSendMask, and VOIPTUNNEL_MAXGROUPSIZE.
DIRTYCODE_API int32_t VoipTunnelControl (VoipTunnelRefT * pVoipTunnel, int32_t iControl, int32_t iValue, int32_t iValue2, const void * pValue)
Control the module.
Parameters
*pVoipTunnel - pointer to module state
iControl - control selector
iValue - selector specific
iValue2 - selector specific
*pValue - selector specific
Note
iControl can be one of the following:
        'bvma' - set the maximum number of simultaneous voice broadcasters per game
        'rtim' - set voice receive timeout value (iValue = timeout in ms)
        'spam' - set debug level (iValue = level)
        'xnat' - set port sniffing enable/disable (iValue = TRUE/FALSE, default FALSE)
Version
04/09/2006 (jbrookes)
References VoipTunnelRefT::bDirtyCastHack, VoipTunnelRefT::bPortSniff, VoipTunnelRefT::iMaxVoiceBroadcasters, NetPrintf, VoipTunnelRefT::uDebugLevel, and VoipTunnelRefT::uVoiceRecvTimeout.
DIRTYCODE_API VoipTunnelRefT* VoipTunnelCreate (uint32_t uVoipPort, int32_t iMaxClients, int32_t iMaxGames)
Create the VoipTunnel module.
Parameters
uVoipPort - local virtual voip port
iMaxClients - max number of clients allowed
iMaxGames - max number of games allowed
Returns
VoipTunnelRefT * - new module state pointer, or null
Version
04/06/2006 (jbrookes)
References VoipTunnelRefT::ClientList, DirtyMemAlloc(), DirtyMemGroupQuery(), VoipTunnelRefT::iMaxClients, VoipTunnelRefT::iMaxGames, VoipTunnelRefT::iMaxVoiceBroadcasters, VoipTunnelRefT::iMemGroup, NetPrintf, NULL, VoipTunnelRefT::pGameList, VoipTunnelRefT::pLookupTable, VoipTunnelRefT::pMemGroupUserData, VoipTunnelRefT::pVoipSocket, VoipTunnelRefT::uVoiceRecvTimeout, VoipTunnelRefT::uVoipPort, VOIPTUNNEL_MAX_BROADCASTING_VOICES_DEFAULT, VOIPTUNNEL_MEMID, VOIPTUNNEL_RECVVOICE_TIMEOUT_DEFAULT, and VoipTunnelDestroy().
DIRTYCODE_API void VoipTunnelDestroy (VoipTunnelRefT * pVoipTunnel)
Shutdown this VoipTunnel.
Parameters
*pVoipTunnel - voiptunnel ref
Version
03/24/2006 (jbrookes)
References DirtyMemFree(), VoipTunnelRefT::iMemGroup, NULL, VoipTunnelRefT::pGameList, VoipTunnelRefT::pLookupTable, VoipTunnelRefT::pMemGroupUserData, VoipTunnelRefT::pVoipSocket, SocketClose(), and VOIPTUNNEL_MEMID.
Referenced by VoipTunnelCreate().
DIRTYCODE_API int32_t VoipTunnelGameListAdd (VoipTunnelRefT * pVoipTunnel, int32_t iGameIdx)
Add a new game.
Parameters
*pVoipTunnel - voiptunnel ref
iGameIdx - index of game whose clients are to be removed
Returns
int32_t - negative=error, else success
Version
04/27/2006 (jbrookes)
References VoipTunnelRefT::iMaxGames, VoipTunnelGameT::iNumClients, VoipTunnelRefT::iNumGames, NetPrintf, and VoipTunnelRefT::pGameList.
DIRTYCODE_API int32_t VoipTunnelGameListDel (VoipTunnelRefT * pVoipTunnel, int32_t iGameIdx)
Remove all clients from the client list who have the given GameServer index.
Parameters
*pVoipTunnel - voiptunnel ref
iGameIdx - index of game whose clients are to be removed
Returns
int32_t - number of clients deleted
Version
04/27/2006 (jbrookes)
References VoipTunnelRefT::ClientList, VoipTunnelClientT::iGameIdx, VoipTunnelRefT::iNumClients, VoipTunnelGameT::iNumClients, VoipTunnelRefT::iNumGames, NetPrintf, and VoipTunnelRefT::pGameList.
DIRTYCODE_API int32_t VoipTunnelStatus (VoipTunnelRefT * pVoipTunnel, int32_t iSelect, int32_t iValue, void * pBuf, int32_t iBufSize)
Get module status.
Parameters
*pVoipTunnel - pointer to module state
iSelect - status selector
iValue - selector specific
*pBuf - [out] - selector specific
iBufSize - size of output buffer
Returns
int32_t - selector specific
Note
iControl can be one of the following:
        'game' - copies game info for game index=iValue into buffer; returns zero on success, negative on failure
        'vddm' - retuns the number of voip packets that were not rebroadcast due to limits on max number of senders per game
        'vmtm' - returns the voip max talker metric (number of times the limit on talkers was reached)
        'nusr' - if iValue==-1, returns total user count, else returns count of users w/ gameserver==iValue
        'sock' - returns voip socket ref (copied into buffer), if available
Version
04/10/2006 (jbrookes)
References VoipTunnelRefT::ClientList, ds_memcpy(), VoipTunnelClientT::iGameIdx, VoipTunnelRefT::iNumClients, NULL, VoipTunnelRefT::pGameList, VoipTunnelRefT::pVoipSocket, VoipTunnelRefT::uVoiceDataDropMetric, and VoipTunnelRefT::uVoiceMaxTalkersMetric.
DIRTYCODE_API void VoipTunnelUpdate (VoipTunnelRefT * pVoipTunnel)
Update the module.
Parameters
*pVoipTunnel - voiptunnel ref
Version
03/24/2006 (jbrookes)
References VoipTunnelRefT::pVoipSocket.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:43