DirtySock: friendapipriv.c File Reference
friendapipriv.c File Reference
This file contains private code comon to all platforms.
#include "DirtySDK/dirtysock.h"
#include "DirtySDK/friend/friendapi.h"
#include "DirtySDK/dirtysock/netconn.h"
#include "friendapipriv.h"
Functions
void FriendApiPrivNotifyEvent (FriendApiRefT *pFriendApiRef, FriendEventDataT *pEventData)
Invokes the different callbacks registered by higher-level modules.
Detailed Description
This file contains private code comon to all platforms.
Attention
Copyright (c) 2010 Electronic Arts Inc.
Version
09/05/2012 (akirchner)
Function Documentation
void FriendApiPrivNotifyEvent (FriendApiRefT * pFriendApiRef, FriendEventDataT * pEventData)
Invokes the different callbacks registered by higher-level modules.
Parameters
pFriendApiRef - module reference
pEventData - pointer to event data to be passed to the callbacks
Version
06/15/2010 (mclouatre)
09/06/2012 (akirchner) - ignore FRIENDAPI_EVENT_FRIEND_UPDATED, FRIENDAPI_EVENT_FRIEND_REMOVED and FRIENDAPI_EVENT_BLOCKLIST_UPDATED events if bInitFinished is false
References FriendApiCallbackT::bInitFinished, FriendApiCommonRefT::callback, FriendEventDataT::eventType, FALSE, FRIENDAPI_EVENT_BLOCK_USER_RESULT, FRIENDAPI_EVENT_BLOCKLIST_UPDATED, FRIENDAPI_EVENT_FRIEND_REMOVED, FRIENDAPI_EVENT_FRIEND_UPDATED, FRIENDAPI_EVENT_INIT_COMPLETE, FRIENDAPI_EVENT_MAX, FRIENDAPI_EVENT_MSG_RCVED, FRIENDAPI_EVENT_UNKNOWN, FRIENDAPI_MAX_CALLBACKS, NetCritEnter(), NetCritLeave(), NetPrintf, FriendApiCommonRefT::notifyCrit, FriendApiCallbackT::pNotifyCb, FriendApiCallbackT::pNotifyCbUserData, TRUE, and FriendEventDataT::uUserIndex.
Referenced by FriendApiPrivUpdate().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:55