DirtySock: DirtyEventManagerPS4
DirtyEventManagerPS4
DirtySock
Typedefs
typedef void(DirtyEventManagerUserServiceCallbackT)(void *pUserData, const SceUserServiceEvent *pEvent)
typedef void(DirtyEventManagerSystemServiceCallbackT)(void *pUserData, const SceSystemServiceEvent *pEvent)
typedef void(DirtyEventManagerCompanionHttpdCallbackT)(void *pUserData, const SceCompanionHttpdEvent *pEvent)
typedef void(DirtyEventManagerCompanionUtilCallbackT)(void *pUserData, const SceCompanionUtilEvent *pEvent)
Functions
int32_t DirtyEventManagerInit (void)
int32_t DirtyEventManagerUpdate (void)
int32_t DirtyEventManagerShutdown (void)
int32_t DirtyEventManagerRegisterUserService (DirtyEventManagerUserServiceCallbackT *pCallback, void *pUserData)
int32_t DirtyEventManagerRegisterSystemService (DirtyEventManagerSystemServiceCallbackT *pCallback, void *pUserData)
int32_t DirtyEventManagerRegisterCompanionHttpd (DirtyEventManagerCompanionHttpdCallbackT *pCallback, void *pUserData)
int32_t DirtyEventManagerRegisterCompanionUtil (DirtyEventManagerCompanionUtilCallbackT *pCallback, void *pUserData)
int32_t DirtyEventManagerUnregisterUserService (DirtyEventManagerUserServiceCallbackT *pCallback)
int32_t DirtyEventManagerUnregisterSystemService (DirtyEventManagerSystemServiceCallbackT *pCallback)
int32_t DirtyEventManagerUnregisterCompanionHttpd (DirtyEventManagerCompanionHttpdCallbackT *pCallback)
int32_t DirtyEventManagerUnregisterCompanionUtil (DirtyEventManagerCompanionUtilCallbackT *pCallback)
Detailed Description
Typedef Documentation
typedef void(DirtyEventManagerCompanionHttpdCallbackT)(void *pUserData, const SceCompanionHttpdEvent *pEvent)
typedef void(DirtyEventManagerCompanionUtilCallbackT)(void *pUserData, const SceCompanionUtilEvent *pEvent)
typedef void(DirtyEventManagerSystemServiceCallbackT)(void *pUserData, const SceSystemServiceEvent *pEvent)
typedef void(DirtyEventManagerUserServiceCallbackT)(void *pUserData, const SceUserServiceEvent *pEvent)
Function Documentation
int32_t DirtyEventManagerInit (void)
References _DirtyEventManagerInit().
Referenced by NetConnStartup().
int32_t DirtyEventManagerRegisterCompanionHttpd (DirtyEventManagerCompanionHttpdCallbackT * pCallback, void * pUserData)
References _DirtyEventManagerRegisterCompanionHttpd().
int32_t DirtyEventManagerRegisterCompanionUtil (DirtyEventManagerCompanionUtilCallbackT * pCallback, void * pUserData)
References _DirtyEventManagerRegisterCompanionUtil().
int32_t DirtyEventManagerRegisterSystemService (DirtyEventManagerSystemServiceCallbackT * pCallback, void * pUserData)
References _DirtyEventManagerRegisterSystemService().
Referenced by DirtySessionManagerCreate(), and NetConnStartup().
int32_t DirtyEventManagerRegisterUserService (DirtyEventManagerUserServiceCallbackT * pCallback, void * pUserData)
References _DirtyEventManagerRegisterUserService().
Referenced by NetConnStartup().
int32_t DirtyEventManagerShutdown (void)
References _DirtyEventManagerShutdown().
Referenced by NetConnShutdown().
int32_t DirtyEventManagerUnregisterCompanionHttpd (DirtyEventManagerCompanionHttpdCallbackT * pCallback)
References _DirtyEventManagerUnregisterCompanionHttpd().
int32_t DirtyEventManagerUnregisterCompanionUtil (DirtyEventManagerCompanionUtilCallbackT * pCallback)
References _DirtyEventManagerUnregisterCompanionUtil().
int32_t DirtyEventManagerUnregisterSystemService (DirtyEventManagerSystemServiceCallbackT * pCallback)
References _DirtyEventManagerUnregisterSystemService().
Referenced by NetConnShutdown().
int32_t DirtyEventManagerUnregisterUserService (DirtyEventManagerUserServiceCallbackT * pCallback)
References _DirtyEventManagerUnregisterUserService().
Referenced by NetConnShutdown().
int32_t DirtyEventManagerUpdate (void)
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:19