DirtySock: NetGameDist
NetGameDist
Game
Data Structures
struct NetGameDistStatT
Macros
#define GMDIST_DEFAULT_BUFFERSIZE_IN (16384)
#define GMDIST_DEFAULT_BUFFERSIZE_OUT (8192)
#define GMDIST_MAX_CLIENTS (32)
#define GMDIST_ERROR_SIZE (2048)
#define GMDIST_DATA_NONE (1)
#define GMDIST_DATA_INPUT (2)
#define GMDIST_DATA_INPUT_DROPPABLE (3)
#define GMDIST_DATA_DISCONNECT (4)
#define GMDIST_DATA_NODATA (5)
#define GMDIST_DATA_CRC_REQUEST (0x08)
Typedefs
typedef struct NetGameDistRefT NetGameDistRefT
typedef struct NetGameDistStatT NetGameDistStatT
Functions
DIRTYCODE_API typedef int32_t() NetGameDistStatProc (void *pLinkRef, int32_t iSelect, int32_t iValue, void *pBuf, int32_t iBufSize)
dist stat proc
DIRTYCODE_API typedef int32_t() NetGameDistSendProc (void *pLinkRef, NetGamePacketT *pPkt, int32_t iLen)
dist send proc
DIRTYCODE_API typedef int32_t() NetGameDistRecvProc (void *pLinkRef, NetGamePacketT *pPkt, int32_t iLen, uint8_t bDist)
dist recv proc
DIRTYCODE_API typedef int32_t() NetGameDistPeekProc (void *pLinkRef, NetGamePacketT **pPkt, uint32_t uMask)
dist peek proc
DIRTYCODE_API typedef int8_t() NetGameDistDropProc (void *pLinkRef, void *pExisting, void *pIncoming, uint8_t uTypeExisting, uint8_t uTypeIncoming)
dist drop proc
DIRTYCODE_API typedef int32_t() NetGameDistLinkCtrlProc (void *ref, int32_t iKind, int32_t iData)
DIRTYCODE_API NetGameDistRefT * NetGameDistCreate (void *pLinkRef, NetGameDistStatProc *pStatProc, NetGameDistSendProc *pSendProc, NetGameDistRecvProc *pRecvProc, uint32_t uInBufferSize, uint32_t uOutBufferSize)
Create the game pClient.
DIRTYCODE_API void NetGameDistDestroy (NetGameDistRefT *pRef)
Destroy the game pClient.
DIRTYCODE_API int32_t NetGameDistStatus (NetGameDistRefT *pRef, int32_t iSelect, int32_t iValue, void *pBuf, int32_t iBufSize)
Get pointer to status counters.
DIRTYCODE_API void NetGameDistSetServer (NetGameDistRefT *pRef, uint8_t uActAsServer)
Get pointer to status counters.
DIRTYCODE_API void NetGameDistMultiSetup (NetGameDistRefT *pRef, int32_t iOurIndex, int32_t iTotPlrs)
Tells NetGameDist how many players there are in the game, and which one we are. Will only affect the order packets are received from NetGameDistInputQueryMulti.
DIRTYCODE_API void NetGameDistMetaSetup (NetGameDistRefT *pRef, uint8_t uSparse, uint32_t uMask, uint32_t uVersion)
Tells NetGameDist whether to enable meta-information sending, and sets the mask & the version number for the meta-information.
DIRTYCODE_API int32_t NetGameDistInputPeek (NetGameDistRefT *pRef, uint8_t *pType, void *pPeer, int32_t *pPlen)
See if a completed packet is ready.
DIRTYCODE_API int32_t NetGameDistInputQuery (NetGameDistRefT *pRef, void *pOurs, int32_t *pOlen, void *pPeer, int32_t *pPlen)
See if a completed packet is ready.
DIRTYCODE_API int32_t NetGameDistInputQueryMulti (NetGameDistRefT *pRef, uint8_t *pDataTypes, void **pInputs, int32_t *pLen)
See if a completed packet is ready.
DIRTYCODE_API int32_t NetGameDistInputLocal (NetGameDistRefT *pRef, void *pBuffer, int32_t iLen)
Provide local input data.
DIRTYCODE_API int32_t NetGameDistInputLocalMulti (NetGameDistRefT *pRef, uint8_t *uTypes, void **pBuffer, int32_t *pLen, int32_t iDelta)
Provide local input data for all players, including ours, which will be discarded.
DIRTYCODE_API void NetGameDistInputCheck (NetGameDistRefT *pRef, int32_t *pSend, int32_t *pRecv)
Check input status (see how long till next)
DIRTYCODE_API void NetGameDistInputRate (NetGameDistRefT *pRef, int32_t iRate)
Set the input rate.
DIRTYCODE_API void NetGameDistInputClear (NetGameDistRefT *pRef)
Flush the input queue.
DIRTYCODE_API int32_t NetGameDistControl (NetGameDistRefT *pRef, int32_t iSelect, int32_t iValue, void *pValue)
Set NetGameDist operation parameters.
DIRTYCODE_API uint32_t NetGameDistUpdate (NetGameDistRefT *pRef)
Perform periodic tasks.
DIRTYCODE_API void NetGameDistSetProc (NetGameDistRefT *pRef, int32_t iKind, void *pProc)
Sets or override the various procedure pointers.
DIRTYCODE_API void NetGameDistSendStats (NetGameDistRefT *pRef, NetGameDistStatT *pStats)
Send stats. Meant to be used by the game server to send stats regarding all clients.
DIRTYCODE_API int32_t NetGameDistGetError (NetGameDistRefT *pRef)
return non-zero if there ever was an overflow
DIRTYCODE_API void NetGameDistGetErrorText (NetGameDistRefT *pRef, char *pErrorBuffer, int32_t iBufSize)
copies into the passed buffer the last error text.
DIRTYCODE_API void NetGameDistResetError (NetGameDistRefT *pRef)
reset the overflow error condition to 0.
Detailed Description
Macro Definition Documentation
#define GMDIST_DATA_CRC_REQUEST (0x08)
Referenced by NetGameDistInputLocalMulti(), NetGameDistInputQueryMulti(), and NetGameDistServUpdate().
#define GMDIST_DATA_DISCONNECT (4)
Referenced by NetGameDistInputLocalMulti().
#define GMDIST_DATA_INPUT (2)
Referenced by NetGameDistInputLocal(), and NetGameDistInputQueryMulti().
#define GMDIST_DATA_INPUT_DROPPABLE (3)
Referenced by NetGameDistInputQueryMulti().
#define GMDIST_DATA_NODATA (5)
Referenced by NetGameDistInputLocalMulti(), and NetGameDistInputQueryMulti().
#define GMDIST_DATA_NONE (1)
Referenced by NetGameDistInputLocalMulti(), and NetGameDistInputQueryMulti().
#define GMDIST_DEFAULT_BUFFERSIZE_IN (16384)
Referenced by NetGameDistServAddClient().
#define GMDIST_DEFAULT_BUFFERSIZE_OUT (8192)
Referenced by NetGameDistServAddClient().
#define GMDIST_ERROR_SIZE (2048)
#define GMDIST_MAX_CLIENTS (32)
Referenced by NetGameDistServUpdate().
Typedef Documentation
typedef struct NetGameDistRefT NetGameDistRefT
typedef struct NetGameDistStatT NetGameDistStatT
Function Documentation
DIRTYCODE_API int32_t NetGameDistControl (NetGameDistRefT * pRef, int32_t iSelect, int32_t iValue, void * pValue)
Set NetGameDist operation parameters.
Parameters
*pRef - reference pointer
iSelect - item to tweak
iValue - tweak value
pValue - pointer tweak value
Returns
int32_t - selector specific
Note
select can be one of the following:
-— basic setup and control -—
'clri' - clear the local queue of inputs
'mini' - min window size clamp
'maxi' - max window size clamp
'spam' - sets debug output verbosity (0...n)
— advanced setup
'crcs' - enable/disable the reception of CRC challenges
'lcrc' - to provide the current CRC as request by NetGameDist
'lrcv' - local recv flow control. Set whether we are ready to receive or not.
'lsnd' - local send flow control. Set whether we are ready to send or not.
-— provide information -—
'late' - overall latency of game
'plat' - get the end-to-end latency in number of packets
'rate' - current exchange rate
'rcrc' - get the remote CRC. if iValue==0, returns whether we have a value. Otherwise return the value itself.
'rrcv' - remote recv flow control. Tells whether remote is ready to receive or not.
'rsnd' - remote send flow control. Tells whether remote is ready to send or not.
'wind' - input exchange window
'?cmp' - offset of first packet to process in input buffer
'?cws' - can we send. FALSE if sending would overflow the send queue, iValue is length
'?inp' - offset of last packet to process in input buffer
'?out' - offset of last packet to send in output buffer
'?snd' - offset of first packet to send in output buffer
The count of [sndoff..outoff] is the number of packets ready to send. The min of [cmpoff..inpoff] and [cmpoff..outoff] is the number of packets ready to process (because you need a packet from each peer in order to perform processing).
Version
1.1 11/18/08 (jrainy) refactored from NetGameDistInputTweak
References ds_snzprintf(), FALSE, NetGameDistRefT::iVerbose, NetGameLinkStatT::late, GameBufferDataT::m_beg, GameBufferDataT::m_end, NetGameDistRefT::m_errortext, NetGameDistRefT::m_inp, NetGameDistRefT::m_inpmaxi, NetGameDistRefT::m_inpmini, NetGameDistRefT::m_inprate, NetGameDistRefT::m_inpwind, NetGameDistRefT::m_iooffset, NetGameDistRefT::m_localCRC, NetGameDistRefT::m_localCRCvalid, NetGameDistRefT::m_out, NetGameDistRefT::m_rdyrecv, NetGameDistRefT::m_rdyrecvremote, NetGameDistRefT::m_rdysend, NetGameDistRefT::m_rdysendremote, NetGameDistRefT::m_remoteCRC, NetGameDistRefT::m_remoteCRCvalid, NetGameDistRefT::m_sendmulti, NetGameDistRefT::m_stats, NetGameDistRefT::m_ucrcchallenges, NetGameDistRefT::m_updateflowctrl, NetGameDistInputClear(), PACKET_WINDOW, and TRUE.
Referenced by NetGameDistInputLocalMulti(), and NetGameDistServUpdate().
DIRTYCODE_API NetGameDistRefT* NetGameDistCreate (void * pLinkRef, NetGameDistStatProc * pStatProc, NetGameDistSendProc * pSendProc, NetGameDistRecvProc * pRecvProc, uint32_t uInBufferSize, uint32_t uOutBufferSize)
Create the game pClient.
Parameters
*pLinkRef - netgamelink module ref
*pStatProc - netgamelink stat callback
*pSendProc - game send func
*pRecvProc - game recv func
*uInBufferSize - input buffer size, plan around PACKET_WINDOW*n*packets
*uOutBufferSize - output buffer size, plan around PACKET_WINDOW*packets
Returns
NetGameDistRefT * - pointer to module state
Version
1.0 12/20/00 (GWS) First Version
1.1 02/08/07 (jrainy) modified from to include size params.
References DirtyMemAlloc(), DirtyMemGroupQuery(), NetGameDistRefT::iLastSentDelta, NetGameDistRefT::iVerbose, NetGameDistRefT::linkref, GameBufferDataT::m_buflen, GameBufferDataT::m_ctrlio, NetGameDistRefT::m_inp, NetGameDistRefT::m_inpmaxi, NetGameDistRefT::m_inpmini, NetGameDistRefT::m_inprate, NetGameDistRefT::m_memgroup, NetGameDistRefT::m_memgrpusrdata, NetGameDistRefT::m_ourindex, NetGameDistRefT::m_out, NetGameDistRefT::m_totplrs, NetGameDistRefT::m_uLastInputCheckLogTick, NETGAMEDIST_MEMID, NetPrintf, NetTick(), NULL, PACKET_WINDOW, pRef, NetGameDistRefT::recvproc, NetGameDistRefT::sendproc, and NetGameDistRefT::statproc.
Referenced by NetGameDistServAddClient().
DIRTYCODE_API void NetGameDistDestroy (NetGameDistRefT * pRef)
Destroy the game pClient.
Parameters
*pRef - reference pointer
Version
1.0 12/20/00 (GWS) First Version
References DirtyMemFree(), GameBufferDataT::m_ctrlio, NetGameDistRefT::m_inp, NetGameDistRefT::m_memgroup, NetGameDistRefT::m_memgrpusrdata, NetGameDistRefT::m_out, NETGAMEDIST_MEMID, and NULL.
DIRTYCODE_API typedef int8_t() NetGameDistDropProc (void * pLinkRef, void * pExisting, void * pIncoming, uint8_t uTypeExisting, uint8_t uTypeIncoming)
dist drop proc
Referenced by NetGameDistSetProc().
DIRTYCODE_API int32_t NetGameDistGetError (NetGameDistRefT * pRef)
return non-zero if there ever was an overflow
Parameters
*pRef - reference pointer
Returns
int32_t - 0 if there was no error, positive >0 otherwise.
Note
Version
1.0 03/23/07 (jrainy) First Version
References NetGameDistRefT::m_errcond.
Referenced by NetGameDistServUpdateClient().
DIRTYCODE_API void NetGameDistGetErrorText (NetGameDistRefT * pRef, char * pErrorBuffer, int32_t iBufSize)
copies into the passed buffer the last error text.
Parameters
*pRef - reference pointer
*pErrorBuffer - buffer to write into
iBufSize - buf size
Returns
none
Note
Version
1.0 08/15/08 (jrainy) First Version
References NetGameDistRefT::m_errortext.
DIRTYCODE_API void NetGameDistInputCheck (NetGameDistRefT * pRef, int32_t * pSend, int32_t * pRecv)
Check input status (see how long till next)
Parameters
*pRef - reference pointer
*pSend - (optional) stores time until next packet should be sent
*pRecv - (optional) stores whether data is available
Version
12/20/00 (GWS)
References NetGameLinkStatT::late, NetGameDistRefT::linkref, GameBufferDataT::m_beg, GameBufferDataT::m_end, NetGameDistRefT::m_inp, NetGameDistRefT::m_inpcalc, NetGameDistRefT::m_inpmaxi, NetGameDistRefT::m_inpmini, NetGameDistRefT::m_inpnext, NetGameDistRefT::m_inprate, NetGameDistRefT::m_inpwind, NetGameDistRefT::m_iooffset, NetGameDistRefT::m_out, NetGameDistRefT::m_rdyrecvremote, NetGameDistRefT::m_recvmulti, NetGameDistRefT::m_stats, NetGameDistUpdate(), NetPrintf, NetTick(), NULL, PACKET_WINDOW, and NetGameDistRefT::statproc.
DIRTYCODE_API void NetGameDistInputClear (NetGameDistRefT * pRef)
Flush the input queue.
Parameters
*pRef - reference pointer
Note
This must be done with independent synchronization before and after to avoid issues.
Version
12/20/00 (GWS)
References GameBufferDataT::m_beg, GameBufferDataT::m_end, NetGameDistRefT::m_globalseq, NetGameDistRefT::m_inp, NetGameDistRefT::m_inpnext, NetGameDistRefT::m_iooffset, NetGameDistRefT::m_localseq, NetGameDistRefT::m_out, and NetTick().
Referenced by NetGameDistControl().
DIRTYCODE_API int32_t NetGameDistInputLocal (NetGameDistRefT * pRef, void * pBuffer, int32_t iLength)
Provide local input data.
Parameters
*pRef - reference pointer
*pBuffer - controller data
iLength - data length
Returns
int32_t - negative=error (including GMDIST_OVERFLOW=overflow), positive=successfully sent or queued
Version
1.0 12/20/00 (GWS) First Version
References ds_memcpy(), GMDIST_DATA_INPUT, NetGameDistRefT::m_multibuf, and NULL.
Referenced by NetGameDistUpdate().
DIRTYCODE_API int32_t NetGameDistInputLocalMulti (NetGameDistRefT * pRef, uint8_t * uTypes, void ** pBuffer, int32_t * iLengths, int32_t iDelta)
Provide local input data for all players, including ours, which will be discarded.
Parameters
*pRef - reference pointer
*uTypes - array of data types (GMDIST_DATA_INPUT_DROPPABLE, GMDIST_DATA_INPUT)
*pBuffer - array of controller data
*iLengths - array of data length
*iDelta - game team should pass in 1, other values only usable on server
Returns
int32_t - negative=error (including GMDIST_OVERFLOW*=overflow), positive=successfully sent or queued
Version
1.0 02/08/07 (jrainy) First Version
1.1 12/03/09 (mclouatre) Added configurable run-time verbosity
References ds_memcpy(), ds_snzprintf(), GMDIST_DATA_CRC_REQUEST, GMDIST_DATA_DISCONNECT, GMDIST_DATA_NODATA, GMDIST_DATA_NONE, GMDIST_INVALID, GMDIST_META_ARRAY_SIZE, GMDIST_OVERFLOW, GMDIST_OVERFLOW_MULTI, GMDIST_OVERFLOW_WINDOW, NetGameDistRefT::iLastSentDelta, NetGameDistRefT::iVerbose, GameBufferDataT::m_beg, NetGameDistRefT::m_errortext, NetGameDistRefT::m_inp, NetGameDistRefT::m_iooffset, NetGameDistRefT::m_metaInfoToSend, NetGameDistRefT::m_multibuf, NetGameDistRefT::m_ourindex, NetGameDistRefT::m_packetid, NetGameDistRefT::m_sendmulti, NetGameDistRefT::m_totplrs, NetGameDistRefT::m_updatemetainfoend, NetGameDistRefT::m_uSparse, NETGAME_DATAPKT_MAXSIZE, NETGAMEDIST_VERBOSITY, NetGameDistControl(), NetPrintf, NetPrintfVerbose, NetTick(), NULL, PACKET_WINDOW, NetGameDistMetaInfoT::uMask, NetGameDistMetaInfoT::uPlayerCount, and NetGameDistMetaInfoT::uVer.
Referenced by NetGameDistServUpdate().
DIRTYCODE_API int32_t NetGameDistInputPeek (NetGameDistRefT * pRef, uint8_t * pType, void * pPeer, int32_t * pPlen)
See if a completed packet is ready.
Parameters
*pRef - reference pointer
*pType - will be filled with data type
*pPeer - buffer sent by peer
*pPlen - length of data in peer buffer. Must pass in the length of pPeer
Returns
int32_t - zero=no data pending, negative=error, positive=data returned
Version
1.0 02/05/2007 (JLB) First Version
References ds_memcpy(), ds_snzprintf(), GAME_PACKET_INPUT_MULTI_FAT, GMDIST_META_ARRAY_SIZE, GMDIST_OVERFLOW, NetGameDistRefT::iVerbose, GameBufferLookupB::len, GameBufferDataT::m_beg, GameBufferDataT::m_ctrlio, GameBufferDataT::m_end, NetGameDistRefT::m_errortext, NetGameDistRefT::m_gotMetaInfo, NetGameDistRefT::m_inp, GameBufferDataT::m_lkup, NetGameDistRefT::m_metaInfo, NetGameDistRefT::m_packetid, NetGameDistRefT::m_recvmulti, NetGameDistRefT::m_totplrs, NETGAMEDIST_VERBOSITY, NetGameDistUpdate(), NetPrintfVerbose, NULL, GameBufferLookupB::pos, NetGameDistRefT::uLastQueriedVersion, and NetGameDistMetaInfoT::uPlayerCount.
Referenced by NetGameDistServUpdate().
DIRTYCODE_API int32_t NetGameDistInputQuery (NetGameDistRefT * pRef, void * pOurs, int32_t * pOlen, void * pPeer, int32_t * pPlen)
See if a completed packet is ready.
Parameters
*pRef - reference pointer
*pOurs - buffer previously sent with NetGameDistInputLocal
*pOlen - length of data in ours buffer
*pPeer - buffer sent by peer
*pPlen - length of data in peer buffer
Returns
int32_t - zero=no data pending, negative=error, positive=data returned
Version
1.0 12/20/00 (GWS) First Version
1.1 02/08/07 (jrainy) cahnged to use the new multi version
References GMDIST_BADSETUP, NetGameDistRefT::m_ourindex, NetGameDistRefT::m_totplrs, and NetGameDistInputQueryMulti().
DIRTYCODE_API int32_t NetGameDistInputQueryMulti (NetGameDistRefT * pRef, uint8_t * pDataTypes, void ** pInputs, int32_t * pLen)
See if a completed packet is ready.
Parameters
*pRef - reference pointer
*pDataTypes - Array of data types (GMDIST_DATA_NONE, GMDIST_DATA_INPUT, GMDIST_DATA_INPUT_DROPPABLE, GMDIST_DATA_DISCONNECT)
**pInputs - Array of pointers to inputs to receive
*pLen - Array of lengths from the data received
Returns
int32_t - zero=no data pending, negative=error, positive=data returned
Version
1.0 12/20/00 (GWS) First Version
1.1 02/08/07 (jrainy) From the old non-multi version.
1.2 12/03/09 (mclouatre) Added configurable run-time verbosity
References ds_memcpy(), FALSE, GAME_PACKET_INPUT_MULTI_FAT, GMDIST_DATA_CRC_REQUEST, GMDIST_DATA_INPUT, GMDIST_DATA_INPUT_DROPPABLE, GMDIST_DATA_NODATA, GMDIST_DATA_NONE, GMDIST_META_ARRAY_SIZE, NetGameDistRefT::iVerbose, GameBufferLookupB::len, GameBufferDataT::m_beg, GameBufferDataT::m_ctrlio, GameBufferDataT::m_end, NetGameDistRefT::m_globalseq, NetGameDistRefT::m_gotMetaInfo, NetGameDistRefT::m_inp, NetGameDistRefT::m_iooffset, GameBufferDataT::m_lkup, NetGameDistRefT::m_metaInfo, NetGameDistRefT::m_ourindex, NetGameDistRefT::m_out, NetGameDistRefT::m_recvmulti, NetGameDistRefT::m_sendmulti, NetGameDistRefT::m_totplrs, NetGameDistRefT::m_ucrcchallenges, NETGAMEDIST_VERBOSITY, NetGameDistUpdate(), NetPrintfVerbose, NetTick(), PACKET_WINDOW, GameBufferLookupB::pos, TRUE, NetGameDistRefT::uLastQueriedVersion, NetGameDistMetaInfoT::uMask, and NetGameDistMetaInfoT::uPlayerCount.
Referenced by NetGameDistInputQuery(), and NetGameDistServUpdate().
DIRTYCODE_API void NetGameDistInputRate (NetGameDistRefT * pRef, int32_t iRate)
Set the input rate.
Parameters
*pRef - reference pointer
iRate - new input rate
Version
12/20/00 (GWS)
References NetGameDistRefT::m_inprate.
Referenced by NetGameDistUpdate().
DIRTYCODE_API typedef int32_t() NetGameDistLinkCtrlProc (void * ref, int32_t iKind, int32_t iData)
Referenced by NetGameDistSetProc().
DIRTYCODE_API void NetGameDistMetaSetup (NetGameDistRefT * pRef, uint8_t uSparse, uint32_t uMask, uint32_t uVersion)
Tells NetGameDist whether to enable meta-information sending, and sets the mask & the version number for the meta-information.
Parameters
*pRef - netgamelink module ref
uSparse - enable or disable meta-information sending (disabling after enabling is currently not-supported on the client)
uMask - set the mask for the meta-information
uVersion - set the version number for the meta-information.
Returns
Version
1.0 08/29/11 (szhu)
References GMDIST_META_ARRAY_SIZE, NetGameDistRefT::m_metaInfoToSend, NetGameDistRefT::m_updatemetainfoend, NetGameDistRefT::m_uSparse, NetPrintf, NetGameDistMetaInfoT::uMask, NetGameDistMetaInfoT::uPlayerCount, and NetGameDistMetaInfoT::uVer.
DIRTYCODE_API void NetGameDistMultiSetup (NetGameDistRefT * pRef, int32_t iOurIndex, int32_t iTotPlrs)
Tells NetGameDist how many players there are in the game, and which one we are. Will only affect the order packets are received from NetGameDistInputQueryMulti.
Parameters
*pRef - netgamelink module ref
iOurIndex - Which player we are
iTotPlrs - Total number of players
Returns
Version
1.0 02/08/07 (jrainy) (GWS) First Version
References NetGameDistRefT::m_ourindex, NetGameDistRefT::m_totplrs, and NetPrintf.
DIRTYCODE_API typedef int32_t() NetGameDistPeekProc (void * pLinkRef, NetGamePacketT ** pPkt, uint32_t uMask)
dist peek proc
Referenced by NetGameDistSetProc().
DIRTYCODE_API typedef int32_t() NetGameDistRecvProc (void * pLinkRef, NetGamePacketT * pPkt, int32_t iLen, uint8_t bDist)
dist recv proc
Referenced by NetGameDistServAddClient(), and NetGameDistSetProc().
DIRTYCODE_API void NetGameDistResetError (NetGameDistRefT * pRef)
reset the overflow error condition to 0.
Parameters
*pRef - reference pointer
Returns
Note
Version
1.0 03/23/07 (jrainy) First Version
References NetGameDistRefT::m_errcond.
DIRTYCODE_API typedef int32_t() NetGameDistSendProc (void * pLinkRef, NetGamePacketT * pPkt, int32_t iLen)
dist send proc
Referenced by NetGameDistServAddClient(), and NetGameDistSetProc().
DIRTYCODE_API void NetGameDistSendStats (NetGameDistRefT * pRef, NetGameDistStatT * pStats)
Send stats. Meant to be used by the game server to send stats regarding all clients.
Parameters
*pRef - reference pointer
*pStats - m_totplrs-sized array of stats
Returns
Note
Version
1.0 03/14/07 (jrainy) First Version
References NetGameMaxPacketT::body, NetGameMaxPacketT::data, ds_memcpy(), GAME_PACKET_STATS, NetGameMaxPacketT::head, NetGamePacketHeadT::kind, NetGamePacketHeadT::len, NetGameDistRefT::linkref, NetGameDistRefT::m_maxpkt, NetGameDistRefT::m_totplrs, and NetGameDistRefT::sendproc.
Referenced by NetGameDistServUpdate().
DIRTYCODE_API void NetGameDistSetProc (NetGameDistRefT * pRef, int32_t kind, void * proc)
Sets or override the various procedure pointers.
Parameters
*pRef - reference pointer
kind - kind
*proc - proc
Returns
kind - proc to override. ('send','recv','stat' or 'drop')
Note
'drop' should only be used on game servers
Version
1.0 02/27/07 (jrainy) First Version
References NetGameDistRefT::dropproc, NetGameDistRefT::linkctrlproc, NetGameDistDropProc(), NetGameDistLinkCtrlProc(), NetGameDistPeekProc(), NetGameDistRecvProc(), NetGameDistSendProc(), NetGameDistStatProc(), NetGameDistRefT::peekproc, NetGameDistRefT::recvproc, NetGameDistRefT::sendproc, and NetGameDistRefT::statproc.
Referenced by NetGameDistServAddClient().
DIRTYCODE_API void NetGameDistSetServer (NetGameDistRefT * pRef, uint8_t uActAsServer)
Get pointer to status counters.
Parameters
*pRef - reference pointer
uActAsServer - boolean, whether NetGameDist should send multi-packets
Returns
none
Note
Version
1.0 02/26/07 (jrainy) First Version
References FALSE, NetGameDistRefT::m_sendmulti, and TRUE.
Referenced by NetGameDistServAddClient().
DIRTYCODE_API typedef int32_t() NetGameDistStatProc (void * pLinkRef, int32_t iSelect, int32_t iValue, void * pBuf, int32_t iBufSize)
dist stat proc
Referenced by NetGameDistServAddClient(), and NetGameDistSetProc().
DIRTYCODE_API int32_t NetGameDistStatus (NetGameDistRefT * pRef, int32_t iSelect, int32_t iValue, void * pBuf, int32_t iBufSize)
Get pointer to status counters.
Parameters
*pRef - reference pointer
iSelect - selector
iValue - input value
pBuf - output buffer
iBufSize - output buffer size
Returns
int32_t - selector specific return value
Note
This is read-only data which can be read at any time. This reference becomes invalid when the module is destroyed.
Version
1.0 12/20/00 (GWS) First Version
References ds_memcpy(), NetGameDistRefT::linkref, NetGameDistRefT::m_recvstats, NetGameDistRefT::m_stats, NetGameDistRefT::m_totplrs, NULL, NetGameDistRefT::statproc, and NetGameDistRefT::uLastQueriedVersion.
Referenced by NetGameDistServUpdate(), and NetGameDistUpdate().
DIRTYCODE_API uint32_t NetGameDistUpdate (NetGameDistRefT * pRef)
Perform periodic tasks.
Parameters
*pRef - reference pointer
Returns
uint32_t - current sequence number
Note
Application must call this every 100ms or so.
Version
1.0 12/20/00 (GWS) First Version
References NetGamePacketT::body, NetGameMaxPacketT::body, NetGamePacketT::data, NetGameMaxPacketT::data, NetGameDistRefT::dropproc, ds_memcpy(), ds_snzprintf(), GAME_PACKET_INPUT, GAME_PACKET_INPUT_FLOW, GAME_PACKET_INPUT_META, GAME_PACKET_INPUT_MULTI, GAME_PACKET_INPUT_MULTI_FAT, GAME_PACKET_STATS, GMDIST_META_ARRAY_SIZE, GMDIST_QUEUE_FULL, GMDIST_QUEUE_MEMORY, NetGamePacketT::head, NetGameDistRefT::iCount, NetGameDistRefT::iVerbose, NetGamePacketHeadT::kind, GameBufferLookupB::len, NetGamePacketHeadT::len, GameBufferDataT::m_beg, GameBufferDataT::m_ctrlio, GameBufferDataT::m_end, NetGameDistRefT::m_errcond, NetGameDistRefT::m_errortext, NetGameDistRefT::m_globalseq, NetGameDistRefT::m_gotMetaInfo, NetGameDistRefT::m_inp, GameBufferDataT::m_lkup, NetGameDistRefT::m_maxpkt, NetGameDistRefT::m_metaInfo, NetGameDistRefT::m_packetid, NetGameDistRefT::m_rdyrecvremote, NetGameDistRefT::m_rdysendremote, NetGameDistRefT::m_recvmulti, NetGameDistRefT::m_recvstats, NetGameDistRefT::m_remoteCRC, NetGameDistRefT::m_remoteCRCvalid, NetGameDistRefT::m_sendmulti, NetGameDistRefT::m_stats, NetGameDistRefT::m_totplrs, NetGameDistRefT::m_updateflowctrl, NetGameDistRefT::m_updatemetainfobeg, NetGameDistRefT::m_updatemetainfoend, NETGAMEDIST_VERBOSITY, NetGameDistInputLocal(), NetGameDistInputRate(), NetGameDistStatus(), NetPrintf, NetPrintfVerbose, NULL, PACKET_WINDOW, NetGameDistStatT::ping, GameBufferLookupB::pos, SocketNtohl(), TRUE, NetGameDistMetaInfoT::uMask, NetGameDistMetaInfoT::uPlayerCount, and NetGameDistMetaInfoT::uVer.
Referenced by NetGameDistInputCheck(), NetGameDistInputPeek(), NetGameDistInputQueryMulti(), and NetGameDistServUpdateClient().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:56