DirtySock: CommSer
CommSer
Comm
Typedefs
typedef struct CommSerRef CommSerRef
basic reference returned/used by all routines
Functions
CommSerRef * CommSerConstruct (int32_t maxwid, int32_t maxinp, int32_t maxout)
Construct the class.
void CommSerDestroy (CommSerRef *what)
Destruct the class.
void CommSerCallback (CommSerRef *ref, void(*callback)(CommRef *ref, int32_t event))
Set upper layer callback.
int32_t CommSerResolve (CommSerRef *what, const char *addr, char *buf, int32_t len, char div)
Resolve an address.
void CommSerUnresolve (CommSerRef *what)
Stop the resolver.
int32_t CommSerListen (CommSerRef *what, const char *addr)
Listen for a connection.
int32_t CommSerUnlisten (CommSerRef *what)
Stop listening.
int32_t CommSerConnect (CommSerRef *what, const char *addr)
Initiate a connection to a peer.
int32_t CommSerUnconnect (CommSerRef *what)
Terminate a connection.
int32_t CommSerStatus (CommSerRef *what)
Return current stream status.
uint32_t CommSerTick (CommSerRef *ref)
Return current tick.
int32_t CommSerSend (CommSerRef *what, const void *buffer, int32_t length)
Send a packet.
int32_t CommSerPeek (CommSerRef *what, void *target, int32_t length, uint32_t *when)
Peek at waiting packet.
int32_t CommSerRecv (CommSerRef *what, void *target, int32_t length, uint32_t *when)
Receive a packet from the buffer.
Detailed Description
Typedef Documentation
typedef struct CommSerRef CommSerRef
basic reference returned/used by all routines
Function Documentation
void CommSerCallback (CommSerRef * ref, void(*)(CommRef *ref, int32_t event) callback)
Set upper layer callback.
Parameters
*ref - reference pointer
*callback - socket generating callback
Returns
None.
Version
1.0 03/10/03 (JLB) Copied from CommSRPCallback()
Referenced by CommSerConstruct().
int32_t CommSerConnect (CommSerRef * ref, const char * addr)
Initiate a connection to a peer.
Parameters
*ref - reference pointer
*addr - address in ip-address:port form
Returns
int32_t - negative=error, zero=ok
Note
Does not currently perform dns translation
Version
1.0 02/15/99 (GWS) First Version
References COMM_BADSTATE, CommSerRecover(), CommSerRef::crit, NULL, and CommSerRef::state.
Referenced by CommSerConstruct().
CommSerRef* CommSerConstruct (int32_t maxwid, int32_t maxinp, int32_t maxout)
Construct the class.
Parameters
maxwid - max record width
maxinp - input packet buffer size
maxout - output packet buffer size
Returns
CommSerRef * - pointer to class, or NULL
Note
Creates worker thread on construction.
Version
1.0 02/15/99 (GWS) First Version
References CommRef::Callback, CommSerRef::common, COMMSER_MEMID, CommSerCallback(), CommSerConnect(), CommSerDestroy(), CommSerListen(), CommSerPeek(), CommSerRecv(), CommSerResolve(), CommSerSend(), CommSerStatus(), CommSerTick(), CommSerUnconnect(), CommSerUnlisten(), CommSerUnresolve(), CommRef::Connect, CommSerRef::connident, CommRef::Construct, CommSerRef::crit, CommRef::Destroy, DirtyMemAlloc(), DirtyMemGroupQuery(), CommSerRef::handle, CommRef::Listen, CommRef::maxinp, CommRef::maxout, CommRef::maxwid, CommRef::memgroup, CommRef::memgrpusrdata, CommSerRef::notify, NULL, CommRef::Peek, CommSerRef::quebuf, CommSerRef::quelen, CommSerRef::quemax, CommSerRef::queref, CommSerRef::rawlen, CommSerRef::rcvbuf, CommSerRef::rcvlen, CommSerRef::rcvwid, CommSerRef::rdover, CommRef::Recv, CommRef::Resolve, CommRef::Send, CommSerRef::sndbuf, CommSerRef::sndlen, CommSerRef::sndwid, CommSerRef::state, CommRef::Status, CommRef::Tick, TRUE, CommRef::Unconnect, CommRef::Unlisten, CommRef::Unresolve, CommSerRef::wrover, and CommSerRef::wtover.
Referenced by CommTAPIConstruct().
void CommSerDestroy (CommSerRef * ref)
Destruct the class.
Parameters
*ref - module ref
Returns
None.
Version
1.0 02/15/99 (GWS) First Version
References CommSerRef::common, COMMSER_MEMID, DirtyMemFree(), CommSerRef::handle, CommRef::memgroup, CommRef::memgrpusrdata, CommSerRef::rcvbuf, CommSerRef::rdover, CommSerRef::sndbuf, CommSerRef::state, CommSerRef::wrover, and CommSerRef::wtover.
Referenced by CommSerConstruct(), and CommTAPIDestroy().
int32_t CommSerListen (CommSerRef * ref, const char * addr)
Listen for a connection.
Parameters
*ref - reference pointer
*addr - port to open on (only :port portion used)
Returns
int32_t - negative=error, zero=ok
Version
1.0 02/15/99 (GWS) First Version
References COMM_BADSTATE, CommSerRecover(), CommSerRef::crit, NULL, and CommSerRef::state.
Referenced by CommSerConstruct().
int32_t CommSerPeek (CommSerRef * ref, void * target, int32_t length, uint32_t * when)
Peek at waiting packet.
Parameters
*ref - reference pointer
target - target buffer
length - buffer length
*when - tick received at
Returns
int32_t - negative=nothing pending, else packet length
Version
1.0 02/15/99 (GWS) First Version
References RawSerPacketT::body, CommSerRef::callback, COMM_NODATA, RawSerPacketT::data, ds_memcpy(), RawSerPacketT::head, RawSerPacketT::len, NULL, CommSerRef::rcvbuf, CommSerRef::rcvinp, CommSerRef::rcvout, and RawSerPacketT::when.
Referenced by CommSerConstruct(), CommSerRecv(), and CommTAPIPeek().
int32_t CommSerRecv (CommSerRef * ref, void * target, int32_t length, uint32_t * when)
Receive a packet from the buffer.
Parameters
*ref - reference pointer
target - target buffer
length - buffer length
*when - tick received at
Returns
int32_t - negative=error, else packet length
Version
1.0 02/15/99 (GWS) First Version
References CommSerPeek(), CommSerRef::rcvlen, CommSerRef::rcvout, and CommSerRef::rcvwid.
Referenced by CommSerConstruct(), and CommTAPIRecv().
int32_t CommSerResolve (CommSerRef * ref, const char * addr, char * buf, int32_t len, char div)
Resolve an address.
Parameters
*ref - module ref
*addr - resolve address
*buf - target buffer
len - target length (min 64 bytes)
div - divider char
Returns
int32_t - <0=error, 0=complete (COMM_NOERROR), >0=in progress (COMM_PENDING)
Note
Target list is always double null terminated allowing null to be used as the divider character if desired. when COMM_PENDING is returned, target buffer is set to "~" until completion.
Version
1.0 02/15/99 (GWS) First Version
References COMM_BADPARM, COMM_MINBUFFER, and NULL.
Referenced by CommSerConstruct().
int32_t CommSerSend (CommSerRef * ref, const void * buffer, int32_t length)
Send a packet.
Parameters
*ref - reference pointer
buffer - pointer to data
length - length of data
Returns
int32_t - negative=error, zero=buffer full (temp fail), positive=queue position (ok)
Note
Zero length packets may not be sent (they are used for buffer query)
Version
1.0 02/15/99 (GWS) First Version
References RawSerPacketT::ack, RawSerPacketT::body, COMM_BADSTATE, COMM_MINBUFFER, CommSerRef::crit, RawSerPacketT::data, ds_memcpy(), RawSerPacketT::head, RawSerPacketT::len, CommSerRef::rcvseq, RawSerPacketT::seq, CommSerRef::sndbuf, CommSerRef::sndinp, CommSerRef::sndlen, CommSerRef::sndout, CommSerRef::sndseq, CommSerRef::sndwid, CommSerRef::state, and RawSerPacketT::when.
Referenced by CommSerConstruct(), and CommTAPISend().
int32_t CommSerStatus (CommSerRef * ref)
Return current stream status.
Parameters
*ref - reference pointer
Returns
int32_t - COMM_CONNECTING, COMM_OFFLINE, COMM_ONLINE or COMM_FAILURE
Version
1.0 02/15/99 (GWS) First Version
References COMM_CONNECTING, COMM_FAILURE, COMM_OFFLINE, COMM_ONLINE, and CommSerRef::state.
Referenced by CommSerConstruct(), and CommTAPIStatus().
uint32_t CommSerTick (CommSerRef * ref)
Return current tick.
Parameters
*ref - reference pointer
Returns
uint32_t - elapsed milliseconds
Version
1.0 03/10/03 (JLB) Copied from CommSRPTick
References NetTick().
Referenced by CommSerConstruct().
int32_t CommSerUnconnect (CommSerRef * ref)
Terminate a connection.
Parameters
*ref - reference pointer
Returns
int32_t - negative=error, zero=ok
Version
1.0 02/15/99 (GWS) First Version
References CommSerUnlisten().
Referenced by CommSerConstruct(), and CommTAPIUnconnect().
int32_t CommSerUnlisten (CommSerRef * ref)
Stop listening.
Parameters
*ref - reference pointer
Returns
int32_t - negative=error, zero=ok
Version
1.0 02/15/99 (GWS) First Version
References CommSerRef::handle, and CommSerRef::state.
Referenced by CommSerConstruct(), CommSerUnconnect(), and CommTAPIUnlisten().
void CommSerUnresolve (CommSerRef * ref)
Stop the resolver.
Parameters
*ref - reference pointer
Returns
None.
Version
1.0 02/15/99 (GWS) First Version
Referenced by CommSerConstruct().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:43