DirtySock: NetConnDefs
NetConnDefs
DirtySock
Data Structures
struct NetConnUserDataT
Macros
#define NETCONN_MAXLOCALUSERS (4)
maximum number of local users
#define NETCONN_IFTYPE_NONE (1)
indeterminate interface type
#define NETCONN_IFTYPE_MODEM (2)
interface is a modem
#define NETCONN_IFTYPE_ETHER (4)
interface is ethernet
#define NETCONN_IFTYPE_USB (8)
interface bus type is USB
#define NETCONN_IFTYPE_PPPOE (16)
interface is PPPoE
#define NETCONN_IFTYPE_WIRELESS (32)
interface is wireless (wifi)
#define NETCONN_IFTYPE_CELL (64)
interface is cellular
#define NETCONN_PLATENV_DEV (8)
Dev environment - Note (0) is used by the 'envi' NetConnStatus selector to indicate ~inp/try again.
#define NETCONN_PLATENV_TEST (1)
Test environment.
#define NETCONN_PLATENV_CERT (2)
Certification environment.
#define NETCONN_PLATENV_PROD (4)
Production environment.
#define NETCONN_SHUTDOWN_NETACTIVE (NET_SHUTDOWN_NETACTIVE)
leave network active in preparation for launching to account management (Xbox 360 only)
#define NETCONN_SHUTDOWN_THREADSTARVE (NET_SHUTDOWN_THREADSTARVE)
special shutdown mode for PS3 that starves threads, allowing for quick exit to XMB
#define NETCONN_ERROR_ISACTIVE (-1)
the module is currently active
#define NETCONN_ERROR_NOTACTIVE (-2)
the module isn't currently active
Typedefs
typedef struct DirtyCertRefT DirtyCertRefT
typedef struct NetConnUserDataT NetConnUserDataT
typedef void * NetConfigRecT
network configuration entry
Functions
DIRTYCODE_API int32_t DirtyCertCreate (void)
Startup DirtyCert module.
DIRTYCODE_API int32_t DirtyCertDestroy (void)
Destroy the module and release its state.
DIRTYCODE_API int32_t DirtyCertCARequestCert (const ProtoSSLCertInfoT *pCertInfo, const char *pHost, int32_t iPort)
Initialize a CA fetch request.
DIRTYCODE_API void DirtyCertCAPreloadCerts (const char *pServiceName)
Initialize a CA preload request.
DIRTYCODE_API int32_t DirtyCertCARequestDone (int32_t iRequestId)
Determine if a CA fetch request is complete.
DIRTYCODE_API int32_t DirtyCertCARequestFree (int32_t iRequestId)
Release resources used by a CA fetch request.
DIRTYCODE_API int32_t DirtyCertControl (int32_t iControl, int32_t iValue, int32_t iValue2, void *pValue)
Set module behavior based on input selector.
DIRTYCODE_API int32_t DirtyCertStatus (int32_t iStatus, void *pBuffer, int32_t iBufSize)
Get module status.
DIRTYCODE_API int32_t NetConnStartup (const char *pParams)
Bring the network connection module to life. Creates connection with IOP resources and gets things ready to go. Puts all device drivers into "probe" mode so they look for appropriate hardware. Does not actually start any network activity.
DIRTYCODE_API int32_t NetConnQuery (const char *pDevice, NetConfigRecT *pList, int32_t iSize)
Returns the index of the given gamertag. If the gamertag is not present, find the index of the SceUserServiceUserId in the pList. Otherwise return the index of the first logged in user.
DIRTYCODE_API int32_t NetConnConnect (const NetConfigRecT *pConfig, const char *pParms, int32_t iData)
Used to bring the networking online with a specific configuration. Uses a configuration returned by NetConnQuery.
DIRTYCODE_API int32_t NetConnControl (int32_t iControl, int32_t iValue, int32_t iValue2, void *pValue, void *pValue2)
Set module behavior based on input selector.
DIRTYCODE_API int32_t NetConnStatus (int32_t iKind, int32_t iData, void *pBuf, int32_t iBufSize)
Check general network connection status. Different selectors return different status attributes.
DIRTYCODE_API const char * NetConnMAC (void)
Return the network MAC address string to the caller.
DIRTYCODE_API int32_t NetConnDisconnect (void)
Used to bring down the network connection. After calling this, it would be necessary to call NetConnConnect to bring the connection back up or NetConnShutdown to completely shutdown all network support.
DIRTYCODE_API int32_t NetConnShutdown (uint32_t uShutdownFlags)
Shutdown the network code and return to idle state.
DIRTYCODE_API uint32_t NetConnElapsed (void)
Return elapsed time in milliseconds. The epoch (zero time) is not defined. This function should be used to determine elapsed time by calling once, saving the result, then later calling again and subtracting the original result from the new result. This will give the elapsed time in millisecs.
DIRTYCODE_API void NetConnSleep (int32_t iMilliSecs)
Sleep the application for some number of milliseconds.
DIRTYCODE_API int32_t NetConnIdleAdd (void(*proc)(void *data, uint32_t tick), void *data)
Add an idle handler that will get called periodically. The frequency of calls is not guarenteed, but should be 60Hz min.
DIRTYCODE_API int32_t NetConnIdleDel (void(*proc)(void *data, uint32_t tick), void *data)
Remove a previously added idle handler. The data parameter must match what was given when the function was added.
DIRTYCODE_API void NetConnIdle (void)
Provide "life" to the network code.
DIRTYCODE_API void NetConnIdleShutdown (void)
Shut down the NetConnIdle handler. This function is intended for internal use only. It should not be called by an application.
DIRTYCODE_API void NetConnTiming (uint8_t uEnableTiming)
Enable or disable the timing of netconnidles.
DIRTYCODE_API typedef void() UserInfoCallbackT (NetConnUserDataT *pUserDataT, void *pData)
DIRTYCODE_API uint32_t NetConnMachineId (void)
Gets a unique id for this machine.
DIRTYCODE_API void NetConnSetMachineId (uint32_t uMachineId)
Sets a unique id for this machine.
DIRTYCODE_API int32_t NetConnCopyParam (char *pDst, int32_t iDstLen, const char *pParamName, const char *pSrc, const char *pDefault)
Copy a command-line parameter.
DIRTYCODE_API int32_t NetConnDirtyCertCreate (const char *pParams)
Create DirtyCert, intitialize service name if provided.
DIRTYCODE_API const char * NetConnGetEnvStr (void)
Translate specified NETCONN_PLATENV_ define into an environment string.
Detailed Description
Macro Definition Documentation
#define NETCONN_ERROR_ISACTIVE (-1)
the module is currently active
Referenced by NetConnShutdown().
#define NETCONN_ERROR_NOTACTIVE (-2)
the module isn't currently active
#define NETCONN_IFTYPE_CELL (64)
interface is cellular
#define NETCONN_IFTYPE_ETHER (4)
interface is ethernet
#define NETCONN_IFTYPE_MODEM (2)
interface is a modem
#define NETCONN_IFTYPE_NONE (1)
indeterminate interface type
#define NETCONN_IFTYPE_PPPOE (16)
interface is PPPoE
#define NETCONN_IFTYPE_USB (8)
interface bus type is USB
#define NETCONN_IFTYPE_WIRELESS (32)
interface is wireless (wifi)
#define NETCONN_MAXLOCALUSERS (4)
maximum number of local users
Referenced by DirtySessionManagerControl(), DirtyWebApiRemovePushEventListener(), NetConnDisconnect(), NetConnQuery(), NetConnShutdown(), NetConnStartup(), NetConnStatus(), PrivilegeApiAbort(), PrivilegeApiCheckResult(), PrivilegeApiDestroy(), PrivilegeApiReleaseRequest(), UserApiControl(), UserApiCreate(), UserApiDestroy(), UserApiPlatCreateData(), UserApiPlatDestroyData(), UserApiPlatUpdate(), UserApiPostRecentlyMetAsync(), UserApiPostRichPresenceAsync(), UserApiUpdate(), UserListApiCancelAll(), and VoipActivateLocalUser().
#define NETCONN_PLATENV_CERT (2)
Certification environment.
Referenced by NetConnGetEnvStr().
#define NETCONN_PLATENV_DEV (8)
Dev environment - Note (0) is used by the 'envi' NetConnStatus selector to indicate ~inp/try again.
Referenced by NetConnGetEnvStr().
#define NETCONN_PLATENV_PROD (4)
Production environment.
Referenced by NetConnGetEnvStr().
#define NETCONN_PLATENV_TEST (1)
Test environment.
Referenced by NetConnGetEnvStr().
#define NETCONN_SHUTDOWN_NETACTIVE (NET_SHUTDOWN_NETACTIVE)
leave network active in preparation for launching to account management (Xbox 360 only)
#define NETCONN_SHUTDOWN_THREADSTARVE (NET_SHUTDOWN_THREADSTARVE)
special shutdown mode for PS3 that starves threads, allowing for quick exit to XMB
Typedef Documentation
typedef struct DirtyCertRefT DirtyCertRefT
typedef void* NetConfigRecT
network configuration entry
typedef struct NetConnUserDataT NetConnUserDataT
Function Documentation
DIRTYCODE_API void DirtyCertCAPreloadCerts (const char * pServiceName)
Initialize a CA preload request.
Parameters
*pServiceName - servicename to identify CA preload set ("gamename-gameyear-platform")
Note
Unlike the explicit CA load, a preload request is fire and forget, and will clean up after itself when complete.
Version
04/18/2012 (jbrookes)
References DirtyCertRefT::crit, DIRTYCERT_MAXREQUESTS, DirtyCertCARequestT::eStatus, DirtyCertCARequestT::eType, DirtyCertRefT::iCount, DirtyCertCARequestT::iRefCount, NetCritEnter(), NetCritLeave(), NetPrintf, NULL, DirtyCertRefT::requests, RS_NOT_STARTED, and RT_PREFETCH.
Referenced by DirtyCertCARequestCert().
DIRTYCODE_API int32_t DirtyCertCARequestCert (const ProtoSSLCertInfoT * pCertInfo, const char * pHost, int32_t iPort)
Initialize a CA fetch request.
Parameters
*pCertInfo - CA Cert Info
*pHost - host we are fetching CA for
iPort - port we are fetching CA for
Returns
int32_t - positive=id of request, negative=error
Version
01/23/2012 (szhu)
References DirtyCertRefT::bPreload, DirtyCertCARequestT::CertInfo, DirtyCertRefT::crit, DIRTYCERT_MAXREQUESTS, DirtyCertCAPreloadCerts(), ds_memcpy_s(), ds_strnzcpy(), DirtyCertCARequestT::eStatus, DirtyCertCARequestT::eType, DirtyCertRefT::iCount, DirtyCertCARequestT::iPort, DirtyCertCARequestT::iRefCount, NetCritEnter(), NetCritLeave(), NetPrintf, NULL, DirtyCertRefT::requests, RS_NOT_STARTED, RT_ONDEMAND, DirtyCertCARequestT::strHost, and DirtyCertRefT::strServiceName.
DIRTYCODE_API int32_t DirtyCertCARequestDone (int32_t iRequestId)
Determine if a CA fetch request is complete.
Parameters
iRequestId - id of CA request
Returns
int32_t - zero=in progess, neg=done w/error, pos=done w/success
Version
01/23/2012 (szhu)
References DirtyCertRefT::crit, DirtyCertCARequestT::eStatus, DirtyCertCARequestT::iRefCount, NetCritEnter(), NetCritLeave(), NetPrintf, NULL, DirtyCertRefT::requests, RS_DONE, and RS_FAILED.
DIRTYCODE_API int32_t DirtyCertCARequestFree (int32_t iRequestId)
Release resources used by a CA fetch request.
Parameters
iRequestId - id of CA request
Returns
int32_t - negative=error, else success
Version
01/23/2012 (szhu)
References DirtyCertRefT::crit, NetCritEnter(), NetCritLeave(), NetPrintf, NULL, and DirtyCertRefT::requests.
Referenced by ProtoSSLDisconnect().
DIRTYCODE_API int32_t DirtyCertControl (int32_t iControl, int32_t iValue, int32_t iValue2, void * pValue)
Set module behavior based on input selector.
Parameters
iControl - input selector
iValue - selector input
iValue2 - selector input
*pValue - selector input
Returns
int32_t - selector result
Note
iControl can be one of the following:
        SELECTOR    DESCRIPTION
        'prld'      Enables/disables preload
        'snam'      Sets service name to use for on-demand requests
        'time'      Sets CA request timeout in milliseconds (default=30s)
Version
01/24/2012 (szhu)
References DirtyCertRefT::bPreload, DirtyCertRefT::crit, FALSE, NetCritEnter(), NetCritLeave(), NetPrintf, NULL, TRUE, and DirtyCertRefT::uTimeout.
Referenced by NetConnControl(), and NetConnDirtyCertCreate().
DIRTYCODE_API int32_t DirtyCertCreate (void)
Startup DirtyCert module.
Returns
int32_t - 0 for success, negative for error
Version
01/23/2012 (szhu)
References DirtyCertRefT::bPreload, DirtyCertRefT::crit, DIRTYCERT_MAXRESPONSE, DIRTYCERT_MEMID, DIRTYCERT_REQUESTID_NONE, DIRTYCERT_TIMEOUT, DirtyMemAlloc(), DirtyMemFree(), DirtyMemGroupQuery(), DirtyCertRefT::iMemGroup, DirtyCertRefT::iRequestId, NetConnIdleAdd(), NetCritInit(), NetPrintf, NULL, DirtyCertRefT::pHttp, DirtyCertRefT::pMemGroupUserData, ProtoHttpCreate(), pState, TRUE, and DirtyCertRefT::uTimeout.
Referenced by NetConnDirtyCertCreate().
DIRTYCODE_API int32_t DirtyCertDestroy (void)
Destroy the module and release its state.
Returns
int32_t - 0 for success, negative for error
Version
01/23/2012 (szhu)
References DirtyCertRefT::crit, DIRTYCERT_MEMID, DirtyMemFree(), DirtyCertRefT::iMemGroup, NetConnIdleDel(), NetCritKill(), NetPrintf, NULL, DirtyCertRefT::pHttp, DirtyCertRefT::pMemGroupUserData, and ProtoHttpDestroy().
Referenced by NetConnShutdown().
DIRTYCODE_API int32_t DirtyCertStatus (int32_t iStatus, void * pBuffer, int32_t iBufSize)
Get module status.
Parameters
iStatus - info selector (see notes)
*pBuffer - [out] storage for selector-specific output
iBufSize - size of output buffer
Returns
int32_t - selector result
Note
iStatus can be one of the following:
        SELECTOR    DESCRIPTION
        'snam'      Stores service name in output buffer (if not NULL); returns validity
Version
03/25/2013 (jbrookes)
References DirtyCertRefT::crit, ds_strnzcpy(), NetCritEnter(), NetCritLeave(), NetPrintf, NULL, and DirtyCertRefT::strServiceName.
Referenced by ProtoSSLConnect().
DIRTYCODE_API int32_t NetConnConnect (const NetConfigRecT * pConfig, const char * pOption, int32_t iData)
Used to bring the networking online with a specific configuration. Uses a configuration returned by NetConnQuery.
Parameters
*pConfig - unused
*pOption - asciiz list of config parameters "peerport=<port>" to specify peer port to be opened by upnp.
iData - platform-specific
Returns
int32_t - negative=error, zero=success
Version
10/04/2005 (jbrookes)
References NetConnRefT::bConnectDelayed, NetConnRefT::eState, NetConnRefT::iPeerPort, NETCONN_DEFAULT_UPNP_PORT, NetConnCommonGetRef(), NetConnStatus(), NetPrintf, NULL, NetConnRefT::ST_EXT_CLEANUP, NetConnRefT::ST_INIT, TRUE, and NetConnRefT::uLastConnStatus.
DIRTYCODE_API int32_t NetConnControl (int32_t iControl, int32_t iValue, int32_t iValue2, void * pValue, void * pValue2)
Set module behavior based on input selector.
Parameters
iControl - input selector
iValue - selector input
iValue2 - selector input
*pValue - selector input
*pValue2 - selector input
Returns
int32_t - selector result
Note
iControl can be one of the following:
        cpaf: set cpu affinity for threads
        npsc: set up SceNpTitleSecret, pValue = data, iVlaue = sizeof data
        recu: stands for "register for external cleanup"; add a new entry to the external cleanup list
        tick: initiate a new auth code request for the user index specified in iValue; <0=error, 0=retry (a request is already pending), >0=request issued
        pctl: initiate a new parental control settings request for the user index specified in iValue; <0=error, 0=retry (a request is already pending), >0=request issued
        pspl: initiate a new PlayStation Plus membership check for user index iValue; iValue2=desired PS+ features to check; <0=error, 0=retry (a request is already pending), >0=request issued
        scid: set up SceNpClientId, pValue = data, iValue = sizeof data
        snam: set DirtyCert service name
        spam: set debug output verbosity (0...n)
        stat: feed user status events into DirtySock if NpToolKit is used by the customer
        ousr: one user mode, which determines whether all users must be old enough to go into an +onl state (iValue=0) or any one user must be old enough (iValue=1)
Unhandled selectors are passed through to SocketControl()
Version
1.0 04/27/2006 (jbrookes)
References NetConnUserT::aParentalControls, NetConnUserT::aPsPlus, NetConnRefT::aUserIndex, NetConnRefT::bNpToolKit, NetConnRefT::bSecretSet, NetConnRefT::Common, NetConnRefT::CpuAffinity, DirtyCertControl(), ds_memcpy(), ds_strnzcpy(), NetConnCommonRefT::iDebugLevel, NetConnCommonGetRef(), NetPrintf, NetPrintMem, NetConnRefT::NpClientId, NetConnRefT::NpTitleSecret, NetConnRefT::NpUsers, NULL, NetConnPsPlusDataT::Param, SocketControl(), TRUE, and NetConnRefT::uConnUserMode.
Referenced by DirtySessionManagerDestroy(), PrivilegeApiCheckPrivilegesAsyncWithUi(), and UserApiDestroy().
DIRTYCODE_API int32_t NetConnCopyParam (char * pDst, int32_t iDstLen, const char * pParamName, const char * pSrc, const char * pDefault)
Copy a command-line parameter.
Parameters
*pDst - output buffer
iDstLen - output buffer length
*pParamName - name of parameter to check for
*pSrc - input string to look for parameters in
*pDefault - default string to use if paramname not found
Returns
int32_t - number of bytes written
Version
07/18/2006 (jbrookes)
References ds_strnzcpy(), and NULL.
Referenced by NetConnDirtyCertCreate().
DIRTYCODE_API int32_t NetConnDirtyCertCreate (const char * pParams)
Create DirtyCert, intitialize service name if provided.
Parameters
*pParams - input params
Returns
int32_t - negative=failure, else success
Version
03/28/2013 (jbrookes)
References DirtyCertControl(), DirtyCertCreate(), NetConnCopyParam(), NetConnShutdown(), NetPrintf, and NULL.
Referenced by NetConnStartup().
DIRTYCODE_API int32_t NetConnDisconnect (void)
Used to bring down the network connection. After calling this, it would be necessary to call NetConnConnect to bring the connection back up or NetConnShutdown to completely shutdown all network support.
Returns
int32_t - negative=error, zero=success
Version
10/04/2005 (jbrookes)
References NetConnUserT::aNpAvailability, NetConnUserT::aParentalControls, NetConnUserT::aPsPlus, NetConnNpAvailabilityT::bDone, NetConnParentalControlsT::data, NetConnPsPlusDataT::data, NetConnAsyncRequestDataT::eRequestState, NetConnRefT::eState, FALSE, NetConnRefT::iExternalCleanupListCnt, NetConnAsyncRequestDataT::iRequestId, NetConnNpAvailabilityT::iRequestId, NetConnNpAvailabilityT::iResult, NETCONN_MAXLOCALUSERS, NETCONN_NP_REQUEST_STATE_INVALID, NetConnCommonGetRef(), NetPrintf, NetConnRefT::NpUsers, NULL, NetConnRefT::pProtoUpnp, ProtoUpnpControl(), SocketControl(), NetConnRefT::ST_EXT_CLEANUP, NetConnRefT::ST_INIT, NetConnRefT::uConnStatus, and NetConnRefT::uLastConnStatus.
Referenced by NetConnShutdown().
DIRTYCODE_API uint32_t NetConnElapsed (void)
Return elapsed time in milliseconds. The epoch (zero time) is not defined. This function should be used to determine elapsed time by calling once, saving the result, then later calling again and subtracting the original result from the new result. This will give the elapsed time in millisecs.
Returns
uint32_t - elapsed milliseconds
Version
1.0 03/10/01 (GWS) First Version
References NetTick().
DIRTYCODE_API const char* NetConnGetEnvStr (void)
Translate specified NETCONN_PLATENV_ define into an environment string.
Returns
const char * - pointer to env str
Version
07/09/2013 (jbrookes)
References NETCONN_PLATENV_CERT, NETCONN_PLATENV_DEV, NETCONN_PLATENV_PROD, NETCONN_PLATENV_TEST, NetConnStatus(), NetPrintf, and NULL.
DIRTYCODE_API void NetConnIdle (void)
Provide "life" to the network code.
This function needs to be called periodically for the network code to function
properly.  Internally it calls RpcDone(), followed by any idle functions that have been
installed.  It also limits RpcDone() and idle functions from executing more than once
every 5ms.
Version
1.0 03/10/01 (GWS) First Version
References FALSE, NetConnStatus(), NetTick(), NetTickDiff, NULL, and TRUE.
DIRTYCODE_API int32_t NetConnIdleAdd (void(*)(void *data, uint32_t tick) proc, void * data)
Add an idle handler that will get called periodically. The frequency of calls is not guarenteed, but should be 60Hz min.
Parameters
*proc - callback function
*data - reference data provided to callback function
Returns
int32_t - negative=error, zero=success
Version
1.0 03/10/01 (GWS) First Version
References data, NETCONN_MAXIDLEHANDLERS, NetPrintf, NULL, and proc.
Referenced by ConnApiCreate2(), DirtyCertCreate(), DirtySessionManagerCreate(), DirtyWebApiCreate(), HttpManagerCreate(), LobbyLanCreate2(), NetConnStartup(), NetResourceCreate(), ProtoUpnpCreate(), QosApiCreate(), and VoipCommonStartup().
DIRTYCODE_API int32_t NetConnIdleDel (void(*)(void *data, uint32_t tick) proc, void * data)
Remove a previously added idle handler. The data parameter must match what was given when the function was added.
Parameters
*proc - callback function
*data - same value given to NetConnIdleAdd
Returns
int32_t - negative=error, zero=success
Version
1.0 03/10/01 (GWS) First Version
References NETCONN_MAXIDLEHANDLERS, NetPrintf, NULL, and proc.
Referenced by ConnApiDestroy(), DirtyCertDestroy(), DirtyWebApiDestroy(), HttpManagerDestroy(), LobbyLanDestroy(), NetConnShutdown(), NetResourceDestroy(), ProtoUpnpDestroy(), QosApiDestroy(), and VoipCommonShutdown().
DIRTYCODE_API void NetConnIdleShutdown (void)
Shut down the NetConnIdle handler. This function is intended for internal use only. It should not be called by an application.
Version
1.0 06/16/04 (JLB) First Version
References NETCONN_MAXIDLEHANDLERS, NetPrintf, NULL, and proc.
Referenced by NetConnShutdown().
DIRTYCODE_API const char* NetConnMAC (void)
Return the network MAC address string to the caller.
Returns
const char * - textual MAC address string
Version
1.0 04/29/01 (GWS) First Version
References NetConnStatus().
DIRTYCODE_API uint32_t NetConnMachineId (void)
Gets a unique id for this machine.
Returns
uint32_t - machine id of this machine.
Version
01/31/2014 (cvienneau)
DIRTYCODE_API int32_t NetConnQuery (const char * pGamertag, NetConfigRecT * pList, int32_t iListSize)
Returns the index of the given gamertag. If the gamertag is not present, find the index of the SceUserServiceUserId in the pList. Otherwise return the index of the first logged in user.
Parameters
*pGamertag - gamer tag
*pList - SceUserServiceUserId to get index of
iListSize - when pGamerTag
Returns
int32_t - negative=gamertag not logged in, else index of user
Version
02/19/2013 (amakoukji)
References NetConnUserT::aSceNpid, NetConnUserT::aSceNpState, ds_strnicmp(), NETCONN_MAXLOCALUSERS, NetConnCommonGetRef(), NetConnStatus(), NetConnRefT::NpUsers, and NULL.
DIRTYCODE_API void NetConnSetMachineId (uint32_t uMachineId)
Sets a unique id for this machine.
Parameters
uMachineId - new value
Version
01/31/2014 (cvienneau)
References NetPrintf.
DIRTYCODE_API int32_t NetConnShutdown (uint32_t uShutdownFlags)
Shutdown the network code and return to idle state.
Parameters
uShutdownFlags - shutdown configuration flags
Returns
int32_t - negative=error, else zero
Version
10/04/2005 (jbrookes)
References NetConnUserT::aParentalControls, NetConnUserT::aPsPlus, NetConnRefT::bUserSessionPriorInitialization, NetConnRefT::Common, NetConnCommonRefT::crit, DirtyCertDestroy(), DirtyEventManagerShutdown(), DirtyEventManagerUnregisterSystemService(), DirtyEventManagerUnregisterUserService(), DirtyMemFree(), NetConnRefT::eState, NetConnRefT::iExternalCleanupListCnt, NetConnCommonRefT::iMemGroup, NETCONN_ERROR_ISACTIVE, NETCONN_MAXLOCALUSERS, NETCONN_MEMID, NetConnCommonGetRef(), NetConnCommonShutdown(), NetConnDisconnect(), NetConnIdleDel(), NetConnIdleShutdown(), NetCritEnter(), NetCritLeave(), NetPrintf, NetConnRefT::NpUsers, NULL, NetConnRefT::pExternalCleanupList, NetConnCommonRefT::pMemGroupUserData, NetConnNpStateCallbackDataT::pNext, NetConnRefT::pNpStateCallback, NetConnRefT::pNpStateCallbackDataQueue, NetConnRefT::pProtoUpnp, ProtoSSLShutdown(), ProtoUpnpDestroy(), SocketDestroy(), and NetConnRefT::ST_EXT_CLEANUP.
Referenced by NetConnDirtyCertCreate(), and NetConnStartup().
DIRTYCODE_API void NetConnSleep (int32_t iMilliSecs)
Sleep the application for some number of milliseconds.
Parameters
iMilliSecs - number of milliseconds to block for
Version
10/04/2005 (jbrookes)
Referenced by VoipShutdown().
DIRTYCODE_API int32_t NetConnStartup (const char * pParams)
Bring the network connection module to life. Creates connection with IOP resources and gets things ready to go. Puts all device drivers into "probe" mode so they look for appropriate hardware. Does not actually start any network activity.
Parameters
*pParams - startup parameters
Returns
int32_t - zero=success, negative=failure
Note
pParams can contain the following terms:
        -noupnp                     - disable upnp support
        -nptoolkit                  - enable nptoolkit-compliant mode
        -titleid=titleidstr         - specify title id (default "NPXX51027_00")
        -userserviceprio=priostr    - specify user service priority (default "SCE_KERNEL_PRIO_FIFO_DEFAULT")
Version
10/04/2005 (jbrookes)
References NetConnUserT::aSceUsers, NetConnRefT::aUserIndex, NetConnRefT::bEnviRequest, NetConnRefT::bNpToolKit, NetConnRefT::bSecretSet, NetConnRefT::bUserSessionPriorInitialization, NetConnRefT::Common, NetConnRefT::CpuAffinity, DirtyErrGetName(), DirtyEventManagerInit(), DirtyEventManagerRegisterSystemService(), DirtyEventManagerRegisterUserService(), DirtyMemAlloc(), ds_strnzcpy(), NetConnRefT::eState, FALSE, NetConnRefT::iExternalCleanupListMax, NetConnCommonRefT::iMemGroup, NetConnRefT::iPeerPort, NetConnRefT::iUserThreadPrio, NETCONN_DEFAULT_UPNP_PORT, NETCONN_EXTERNAL_CLEANUP_LIST_INITIAL_CAPACITY, NETCONN_MAXLOCALUSERS, NETCONN_MEMID, NetConnCommonStartup(), NetConnDirtyCertCreate(), NetConnIdleAdd(), NETCONNPS4_CLIENT_ID, NETCONNPS4_SAMPLE_TITLE_ID, NetConnShutdown(), NetPrintf, NetConnRefT::NpClientId, NetConnRefT::NpUsers, NULL, NetConnRefT::pExternalCleanupList, NetConnCommonRefT::pMemGroupUserData, NetConnRefT::pProtoUpnp, pRef, ProtoSSLStartup(), ProtoUpnpCreate(), SocketCreate(), NetConnRefT::ST_INIT, NetConnRefT::strTitleId, TRUE, and NetConnRefT::uPlatEnv.
DIRTYCODE_API int32_t NetConnStatus (int32_t iKind, int32_t iData, void * pBuf, int32_t iBufSize)
Check general network connection status. Different selectors return different status attributes.
Parameters
iKind - status selector ('open', 'conn', 'onln')
iData - (optional) selector specific
*pBuf - (optional) pointer to output buffer
iBufSize - (optional) size of output buffer
Returns
int32_t - selector specific
Note
iKind can be one of the following:
        acct: returns the account id (pBuf) given the user index (iData)
        addr: ip address of client
        bbnd: TRUE if broadband, else FALSE
        chat: TRUE if local user cannot chat, else FALSE
        chav: S_OK (0) for available user, -1 for invalid parameters, -2 if check is in progress, SCE_NP_ERROR code otherwise
        conn: connection status: +onl=online, ~<code>=in progress, -<err>=NETCONN_ERROR_*
        envi: EA back-end environment type in use (-1=not available, NETCONN_PLATENV_TEST, NETCONN_PLATENV_CERT, NETCONN_PLATENV_PROD)
        cuis: convert a user index (iData) to a system index, returns the index or a negative value for errors
        gust: unsupported
        csiu: convert a system index (iData) to a user index, returns the index or a negative value for errors
        gtag: zero=username of user at index [0-3] in iData returned in pBuf, negative=erro
        iind: returns the index of the user that launched the game
        indx: returns the index of the user with the specified Sony User ID
        iuid: return the SceUserServiceUserId for the user that launched the application
        lcon: (stands for Last CONNection status) connection status saved upon NetConnDisconnect()
        macx: MAC address of client (returned in pBuf)
        mask: returns the mask of users that are ONLINE, similar to the Xbox equivalent
        mgrp: returns memory group and user data pointer
        npid: Return the n'th users's SceNpId via pBuf, negative return=error
        npst: Return the n'th users's SceNpState, negative return=error
        onln: true/false indication of whether network is operational
        open: true/false indication of whether network code running
        soid: return the SceNpOnlineId via pBuf, for the user at index in iData [0-3], negative means no user
        suid: return the SceUserServiceUserId for the user at index in iData [0-3], negative means no user
        tick: fills pBuf with authcode for user index iData, if available. return value: 0:"try again"; <0:error; >0:number of bytes copied into pBuf. If pBuf is null it will return the ticket size
        titl: fills pBuf with the title id, pBuf must be at least 13 characters large
        pctl: fills pBuf with a SceNpParentalControlInfo structure containing the parental control settings for user index iData, if available. return value: 0:"try again"; <0:error; >0:number of bytes copied into pBuf
        pspl: fills pBuf with a bool containing the result of the PlayStation Plus membership check for user index iData, if available. return value: 0:"try again"; <0:error; >0:number of bytes copied into pBuf
        type: connection type: NETCONN_IFTYPE_* bitfield
        upnp: return protoupnp external port info, if available
        vers: return DirtySDK version
        lerr: return the last error that occurred as a result of an sceNp library call
        iusr: return the index to the IEAUser::GetUserId() passed via iData. Should be called from the thread that calls NetConnIdle(). negative=error
Version
10/04/2005 (jbrookes)
References NetConnUserT::aNpAvailability, NetConnUserT::aParentalControls, NetConnUserT::aPsPlus, NetConnUserT::aSceNpid, NetConnRefT::aSceNpOnlineIdCache, NetConnUserT::aSceNpState, NetConnRefT::aUserIndex, NetConnNpAvailabilityT::bDone, NetConnRefT::Common, NetConnCommonRefT::crit, DirtyErrGetName(), DIRTYSDK_VERSION, ds_memcpy(), ds_strnzcpy(), FALSE, NetConnRefT::iLastNpError, NetConnCommonRefT::iMemGroup, NetConnSceNpOnlineIdQueryT::invalid, NetConnNpAvailabilityT::iResult, NETCONN_MAXLOCALUSERS, NetConnCommonGetRef(), NetCritEnter(), NetCritLeave(), NetPrintf, NetConnRefT::NpUsers, NULL, NetConnSceNpOnlineIdQueryT::onlineId, NetConnCommonRefT::pMemGroupUserData, NetConnRefT::pProtoUpnp, PROTOUPNP_STATUS_ADDPORTMAP, ProtoUpnpStatus(), NetConnPsPlusDataT::Result, NetConnSceNpOnlineIdQueryT::result, SocketInfo(), NetConnRefT::strTitleId, TRUE, NetConnRefT::uConnStatus, NetConnRefT::uLastConnStatus, and NetConnRefT::uPlatEnv.
Referenced by _UserApiProcessPresenceResponse(), DirtyAddrGetLocalAddr(), DirtySessionManagerControl(), DirtySessionManagerCreate(), DirtySessionManagerUpdate(), NetConnConnect(), NetConnGetEnvStr(), NetConnIdle(), NetConnMAC(), NetConnQuery(), PrivilegeApiCheckPrivilegesAsyncWithUi(), PrivilegeApiCheckResult(), ProtoUpnpControl(), QosApiGetNatType(), UserApiPlatRequestPostRichPresence(), UserApiPlatRequestRecentlyMet(), and VoipSetLocalUser().
DIRTYCODE_API void NetConnTiming (uint8_t uEnableTiming)
Enable or disable the timing of netconnidles.
Parameters
uEnableTiming - on or off
Returns
None.
Version
1.0 11/06/09 (jrainy) First Version
DIRTYCODE_API typedef void() UserInfoCallbackT (NetConnUserDataT * pUserDataT, void * pData)
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:32