baseURL = "https://frostbite-ew.gitlab.ea.com/framework/fwdocs/"
languageCode = "en-us"
title = "Framework documentation"
theme = "docdock"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
googleAnalytics = "UA-139152355-1"

# [Languages]
# [Languages.en]
# title = "Documentation for Hugo docDock"
# weight = 1
# languageName = "English"
# 
# [Languages.fr]
# title = "Documentation du thème docDock"
# weight = 2
# languageName = "Français"




[params]
editURL = "https://gitlab.ea.com/frostbite-ew/framework/fwdocs/edit/master/content/"
showVisitedLinks = true # default is false
themeStyle = "flex" # "original" or "flex" # default "flex"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = true # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = true # set true to open shortcuts links to a new tab/window
enableGitInfo = true
custom_css = ["css/overrides.css"]

[[menu.shortcuts]]
pre = "<h3>Contact Us</h3>"
name = "<i class='fa fa-slack'></i> <label>Contact Us</label>"
identifier = "slack"
url = "https://electronic-arts.slack.com/messages/C94592ESJ"
weight = 10

[[menu.shortcuts]]
pre = "<h3>Documentation Source</h3>"
name = "<i class='fa fa-git'></i> <label>Documentation Source</label>"
url = "https://gitlab.ea.com/frostbite-ew/framework/fwdocs"
weight = 11

# [[menu.shortcuts]]
# name = "<i class='fa fa-bookmark'></i> <label>Hugo Documentation</label>"
# identifier = "hugodoc"
# url = "https://gohugo.io/"
# weight = 20

# [[menu.shortcuts]]
# name = "<i class='fa fa-bullhorn'></i> <label>Credits</label>"
# url = "/credits"
# weight = 30


# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

