DirtySock: UserList
UserList
User
Data Structures
struct UserListApiUserDataT
struct UserListApiEndDataT
struct UserListApiIsADataT
union UserListApiEventDataT
struct UserListApiNotifyPresenceUpdateData
struct UserListApiNotifyRichPresenceUpdateData
struct UserListApiNotifyFriendListUpdate
struct UserListApiNotifyBlockedListUpdate
union UserListApiNotifyDataT
Macros
#define USERLISTAPI_ERROR_UNSUPPORTED (-1)
#define USERLISTAPI_ERROR_INPROGRESS (-2)
#define USERLISTAPI_ERROR_BAD_PARAM (-3)
#define USERLISTAPI_ERROR_NO_USER (-4)
#define USERLISTAPI_ERROR_TIMEOUT (-5)
#define USERLISTAPI_ERROR_GUEST (-6)
#define USERLISTAPI_ERROR_INVALID_USER (-7)
#define USERLISTAPI_ERROR_USER_INDEX_RANGE (-8)
#define USERLISTAPI_ERROR_UNKNOWN (-99)
#define USERLISTAPI_USERID_MAXLEN (128)
#define USERLISTAPI_FRIENDNAME_MAXLEN (64)
#define USERLISTAPI_AVATAR_URL_MAXLEN (255)
#define USERLISTAPI_MASK_PROFILE (0x01)
#define USERLISTAPI_MASK_PRESENCE (0x02)
#define USERLISTAPI_MASK_RICH_PRESENCE (0x04)
#define USERLISTAPI_NOTIFY_LIST_MAX_SIZE (50)
Typedefs
typedef enum UserListApiTypeE UserListApiTypeE
typedef enum UserListApiIfATypeE UserListApiIfATypeE
typedef enum UserListApiReturnTypeE UserListApiReturnTypeE
typedef enum
UserListApiIsAReturnTypeE UserListApiIsAReturnTypeE
typedef enum UserListApiNotifyTypeE UserListApiNotifyTypeE
typedef enum UserListApiUpdateTypeE UserListApiUpdateTypeE
typedef struct UserListApiRefT UserListApiRefT
< opaque module ref
typedef struct UserListApiFiltersT UserListApiFiltersT
response structure for user data
typedef struct UserListApiUserDataT UserListApiUserDataT
response structure for metadata
typedef struct UserListApiEndDataT UserListApiEndDataT
IsA style request response.
typedef struct UserListApiIsADataT UserListApiIsADataT
container union for generic response
typedef union UserListApiEventDataT UserListApiEventDataT
presence update notification data
typedef struct
UserListApiNotifyPresenceUpdateData UserListApiNotifyPresenceUpdateData
rich presence update notification data
typedef struct
UserListApiNotifyRichPresenceUpdateData UserListApiNotifyRichPresenceUpdateData
friend list update notification data
typedef struct
UserListApiNotifyFriendListUpdate UserListApiNotifyFriendListUpdate
blocked list update notification data
typedef struct
UserListApiNotifyBlockedListUpdate UserListApiNotifyBlockedListUpdate
container union for notification results
typedef union
UserListApiNotifyDataT UserListApiNotifyDataT
typedef void(UserListApiCallbackT)(UserListApiRefT *pRef, UserListApiReturnTypeE eResponseType, UserListApiEventDataT *pUserApiEventData, void *pUserData)
typedef void(UserListApiIsAQueryCallbackT)(UserListApiRefT *pRef, UserListApiIfATypeE eResponseType, UserListApiIsADataT *pUserApiEventData, void *pUserData)
typedef void(UserListApiUpdateCallbackT)(UserListApiRefT *pRef, UserListApiNotifyTypeE eType, UserListApiNotifyDataT *pData, void *pUserData)
Enumerations
enum UserListApiTypeE {
USERLISTAPI_TYPE_FRIENDS,
USERLISTAPI_TYPE_BLOCKED,
USERLISTAPI_TYPE_FRIENDS_OF_FRIEND,
USERLISTAPI_TYPE_MUTED
}
enum UserListApiIfATypeE {
USERLISTAPI_IS_FRIENDS,
USERLISTAPI_IS_BLOCKED
}
enum UserListApiReturnTypeE {
TYPE_USER_DATA,
TYPE_LIST_END
}
enum UserListApiIsAReturnTypeE {
USERLISTAPI_IS_OF_TYPE,
USERLISTAPI_IS_NOT_OF_TYPE,
USERLISTAPI_IS_MYSELF,
USERLISTAPI_IS_TYPE_UNKNOWN
}
enum UserListApiNotifyTypeE {
USERLISTAPI_NOTIFY_FRIENDLIST_UPDATE = 0,
USERLISTAPI_NOTIFY_BLOCKEDLIST_UPDATE
}
enum UserListApiUpdateTypeE {
USERLISTAPI_UPDATE_TYPE_UNKNOWN = 0,
USERLISTAPI_UPDATE_TYPE_REMOVED,
USERLISTAPI_UPDATE_TYPE_ADD
}
Functions
DIRTYCODE_API UserListApiRefT * UserListApiCreate (uint32_t uMaxResponseSize)
< create the user list api object
DIRTYCODE_API int32_t UserListApiRegisterUpdateEvent (UserListApiRefT *pRef, uint32_t uUserIndex, UserListApiNotifyTypeE eType, UserListApiUpdateCallbackT *pNotifyCb, void *pUserData)
give module time to perform periodic processing
DIRTYCODE_API void UserListApiUpdate (UserListApiRefT *pRef)
get status information
DIRTYCODE_API int32_t UserListApiStatus (UserListApiRefT *pRef, int32_t iSelect, void *pBuf, int32_t iBufSize)
control function
DIRTYCODE_API int32_t UserListApiControl (UserListApiRefT *pRef, int32_t iControl, int32_t iValue, int32_t iValue2, void *pValue)
destroy the user list api object
DIRTYCODE_API void UserListApiDestroy (UserListApiRefT *pRef)
gets the list of users of the specified type
DIRTYCODE_API int32_t UserListApiGetListAsync (UserListApiRefT *pRef, uint32_t uUserIndex, UserListApiTypeE eType, int32_t iLimit, int32_t iOffset, UserListApiFiltersT *filter, UserListApiCallbackT *pNotifyCb, uint32_t uTypeMask, void *pUserData)
Is target user a friend.
DIRTYCODE_API int32_t UserListApiIsFriendAsync (UserListApiRefT *pRef, uint32_t uUserIndex, DirtyUserT *pUser, UserListApiIsAQueryCallbackT *pNotifyCb, void *pUserData)
Is target user blocked.
DIRTYCODE_API int32_t UserListApiIsBlockedAsync (UserListApiRefT *pRef, uint32_t uUserIndex, DirtyUserT *pUser, UserListApiIsAQueryCallbackT *pNotifyCb, void *pUserData)
cancels all pending transactions
DIRTYCODE_API void UserListApiCancelAll (UserListApiRefT *pRef)
Cancels all active requests.
Detailed Description
Macro Definition Documentation
#define USERLISTAPI_AVATAR_URL_MAXLEN (255)
#define USERLISTAPI_ERROR_BAD_PARAM (-3)
Referenced by UserListApiGetListAsync().
#define USERLISTAPI_ERROR_GUEST (-6)
Referenced by UserListApiGetListAsync(), and UserListApiIsFriendAsync().
#define USERLISTAPI_ERROR_INPROGRESS (-2)
Referenced by UserListApiGetListAsync().
#define USERLISTAPI_ERROR_INVALID_USER (-7)
Referenced by UserListApiGetListAsync(), and UserListApiIsFriendAsync().
#define USERLISTAPI_ERROR_NO_USER (-4)
Referenced by UserListApiGetListAsync().
#define USERLISTAPI_ERROR_TIMEOUT (-5)
Referenced by UserListApiUpdate().
#define USERLISTAPI_ERROR_UNKNOWN (-99)
Referenced by _UserListApiProcessIsFriend(), UserListApiGetListAsync(), and UserListApiUpdate().
#define USERLISTAPI_ERROR_UNSUPPORTED (-1)
Referenced by UserListApiGetListAsync(), UserListApiIsBlockedAsync(), and UserListApiRegisterUpdateEvent().
#define USERLISTAPI_ERROR_USER_INDEX_RANGE (-8)
Referenced by UserListApiGetListAsync(), and UserListApiIsFriendAsync().
#define USERLISTAPI_FRIENDNAME_MAXLEN (64)
#define USERLISTAPI_MASK_PRESENCE (0x02)
Referenced by UserListApiGetListAsync(), and UserListApiUpdate().
#define USERLISTAPI_MASK_PROFILE (0x01)
Referenced by UserListApiGetListAsync(), and UserListApiUpdate().
#define USERLISTAPI_MASK_RICH_PRESENCE (0x04)
Referenced by UserListApiGetListAsync(), and UserListApiUpdate().
#define USERLISTAPI_NOTIFY_LIST_MAX_SIZE (50)
#define USERLISTAPI_USERID_MAXLEN (128)
Typedef Documentation
typedef void(UserListApiCallbackT)(UserListApiRefT *pRef, UserListApiReturnTypeE eResponseType, UserListApiEventDataT *pUserApiEventData, void *pUserData)
typedef struct UserListApiEndDataT UserListApiEndDataT
IsA style request response.
typedef union UserListApiEventDataT UserListApiEventDataT
presence update notification data
typedef struct UserListApiFiltersT UserListApiFiltersT
response structure for user data
typedef enum UserListApiIfATypeE UserListApiIfATypeE
typedef struct UserListApiIsADataT UserListApiIsADataT
container union for generic response
typedef void(UserListApiIsAQueryCallbackT)(UserListApiRefT *pRef, UserListApiIfATypeE eResponseType, UserListApiIsADataT *pUserApiEventData, void *pUserData)
typedef enum UserListApiIsAReturnTypeE UserListApiIsAReturnTypeE
typedef struct UserListApiNotifyBlockedListUpdate UserListApiNotifyBlockedListUpdate
container union for notification results
typedef union UserListApiNotifyDataT UserListApiNotifyDataT
typedef struct UserListApiNotifyFriendListUpdate UserListApiNotifyFriendListUpdate
blocked list update notification data
typedef struct UserListApiNotifyPresenceUpdateData UserListApiNotifyPresenceUpdateData
rich presence update notification data
typedef struct UserListApiNotifyRichPresenceUpdateData UserListApiNotifyRichPresenceUpdateData
friend list update notification data
typedef enum UserListApiNotifyTypeE UserListApiNotifyTypeE
typedef struct UserListApiRefT UserListApiRefT
< opaque module ref
search filters ref, this will be further defined in platforms specific headers
typedef enum UserListApiReturnTypeE UserListApiReturnTypeE
typedef enum UserListApiTypeE UserListApiTypeE
typedef void(UserListApiUpdateCallbackT)(UserListApiRefT *pRef, UserListApiNotifyTypeE eType, UserListApiNotifyDataT *pData, void *pUserData)
typedef enum UserListApiUpdateTypeE UserListApiUpdateTypeE
typedef struct UserListApiUserDataT UserListApiUserDataT
response structure for metadata
Enumeration Type Documentation
enum UserListApiIfATypeE
Enumerator
USERLISTAPI_IS_FRIENDS
USERLISTAPI_IS_BLOCKED
enum UserListApiIsAReturnTypeE
Enumerator
USERLISTAPI_IS_OF_TYPE
USERLISTAPI_IS_NOT_OF_TYPE
USERLISTAPI_IS_MYSELF
USERLISTAPI_IS_TYPE_UNKNOWN
enum UserListApiNotifyTypeE
Enumerator
USERLISTAPI_NOTIFY_FRIENDLIST_UPDATE
USERLISTAPI_NOTIFY_BLOCKEDLIST_UPDATE
enum UserListApiReturnTypeE
Enumerator
TYPE_USER_DATA
TYPE_LIST_END
enum UserListApiTypeE
Enumerator
USERLISTAPI_TYPE_FRIENDS
USERLISTAPI_TYPE_BLOCKED
USERLISTAPI_TYPE_FRIENDS_OF_FRIEND
USERLISTAPI_TYPE_MUTED
enum UserListApiUpdateTypeE
Enumerator
USERLISTAPI_UPDATE_TYPE_UNKNOWN
USERLISTAPI_UPDATE_TYPE_REMOVED
USERLISTAPI_UPDATE_TYPE_ADD
Function Documentation
DIRTYCODE_API void UserListApiCancelAll (UserListApiRefT * pRef)
Cancels all active requests.
Parameters
*pRef - module ref
Version
04/17/2013 (amakoukji)
References UserListApiResultT::bNeedsMemFreed, UserListApiResultT::bResponseProcessed, UserListApiPlatformRequestListT::bWaitingForFriendsList, UserListApiPlatformRequestListT::bWaitingForPresenceList, UserListApiPlatformRequestListT::bWaitingForProfileList, UserListApiRefT::crit, DirtyMemFree(), UserListApiRefT::iMemGroup, NetCritEnter(), NetCritLeave(), UserListApiRefT::pIsFriendRequestQueue, UserListApiRefT::pMemGroupUserData, UserListApiResultT::pNext, UserListApiIsFriendQueueT::pNext, UserListApiResultT::refResultFriend, UserListApiResultT::refResultPresence, UserListApiResultT::refResultProfile, UserListApiRefT::ResultList, UserListApiResultT::SubQueryStatuses, and USERLISTAPI_MEMID.
DIRTYCODE_API int32_t UserListApiControl (UserListApiRefT * pRef, int32_t iControl, int32_t iValue, int32_t iValue2, void * pValue)
destroy the user list api object
destroy the user list api object
Parameters
*pRef - module ref
iControl - status selector
iValue - control value
iValue2 - control value
*pValue - [in/out] control value
Returns
int32_t - zero=success; negative=error
Version
04/17/2013 (amakoukji)
References NetPrintf.
DIRTYCODE_API UserListApiRefT* UserListApiCreate (uint32_t uMaxResponseSize)
< create the user list api object
set the callback used for registering userlist update event
< create the user list api object
Parameters
uMaxResponseSize - size of the ProtoHttpBuffer
Returns
UserListApiRefT* - pointer to reference
Version
04/17/2013 (amakoukji)
References UserListApiRefT::crit, DirtyMemAlloc(), DirtyMemGroupQuery(), UserListApiRefT::iMemGroup, NetCritInit(), NetPrintf, UserListApiRefT::pHttp, UserListApiRefT::pMemGroupUserData, ProtoHttpCreate(), and USERLISTAPI_MEMID.
Referenced by VoipHeadsetCreate().
DIRTYCODE_API void UserListApiDestroy (UserListApiRefT * pRef)
gets the list of users of the specified type
gets the list of users of the specified type
Parameters
*pRef - module ref
Version
04/17/2013 (amakoukji)
References UserListApiRefT::bShuttingDown, NetConnControl(), NetPrintf, and TRUE.
DIRTYCODE_API int32_t UserListApiGetListAsync (UserListApiRefT * pRef, uint32_t uUserIndex, UserListApiTypeE eType, int32_t iLimit, int32_t iOffset, UserListApiFiltersT * filter, UserListApiCallbackT * pNotifyCb, uint32_t uTypeMask, void * pUserData)
Is target user a friend.
Is target user a friend.
Parameters
*pRef - module ref
uUserIndex - local user index
eType - type of users to query
iLimit - maximum users to return per query
iOffset - start index of query
*filter - xboxone specific filter set
*pNotifyCb - callback function pointer
uTypeMask - mask
*pUserData - user data
Returns
int32_t - zero=success; negative=error
Version
04/17/2013 (amakoukji)
References UserListApiRefT::aXblContext, UserListApiResultT::bNeedsMemFreed, UserListApiResultT::bResponseProcessed, UserListApiPlatformRequestListT::bWaitingForFriendsList, UserListApiPlatformRequestListT::bWaitingForPresenceList, UserListApiPlatformRequestListT::bWaitingForProfileList, UserListApiRefT::crit, DirtyMemAlloc(), UserListApiResultT::eRequestType, UserListApiResultT::iErrorFriend, UserListApiResultT::iErrorPresence, UserListApiResultT::iErrorProfile, UserListApiResultT::iLimit, UserListApiRefT::iMemGroup, UserListApiResultT::iOffset, NetConnQuery(), NetConnStatus(), NetCritEnter(), NetCritLeave(), NetPrintf, NetTick(), UserListApiResultT::pIsAQueryNotifyCb, UserListApiRefT::pMemGroupUserData, UserListApiResultT::pNext, UserListApiResultT::pNotifyCb, pRef, UserListApiResultT::pUserData, UserListApiPlatformUserContextT::refAsyncOpFriend, UserListApiPlatformUserContextT::refAsyncOpPresence, UserListApiPlatformUserContextT::refAsyncOpProfile, UserListApiRefT::refUsers, UserListApiPlatformUserContextT::refXblUserContext, UserListApiRefT::ResultList, UserListApiResultT::SocialView, UserListApiResultT::SubQueryStatuses, TRUE, UserListApiPlatformUserContextT::uOpFriendTimer, UserListApiPlatformUserContextT::uOpPresenceTimer, UserListApiPlatformUserContextT::uOpProfileTimer, USERLISTAPI_ERROR_BAD_PARAM, USERLISTAPI_ERROR_GUEST, USERLISTAPI_ERROR_INPROGRESS, USERLISTAPI_ERROR_INVALID_USER, USERLISTAPI_ERROR_NO_USER, USERLISTAPI_ERROR_UNKNOWN, USERLISTAPI_ERROR_UNSUPPORTED, USERLISTAPI_ERROR_USER_INDEX_RANGE, USERLISTAPI_MASK_PRESENCE, USERLISTAPI_MASK_PROFILE, USERLISTAPI_MASK_RICH_PRESENCE, USERLISTAPI_MEMID, USERLISTAPI_REQUEST_TYPE_FRIENDS, USERLISTAPI_TYPE_BLOCKED, USERLISTAPI_TYPE_FRIENDS, USERLISTAPI_TYPE_FRIENDS_OF_FRIEND, USERLISTAPI_TYPE_MUTED, UserListApiResultT::uTypeMask, and UserListApiResultT::uUserIndex.
DIRTYCODE_API int32_t UserListApiIsBlockedAsync (UserListApiRefT * pRef, uint32_t uUserIndex, DirtyUserT * pUser, UserListApiIsAQueryCallbackT * pNotifyCb, void * pUserData)
cancels all pending transactions
cancels all pending transactions
Parameters
*pRef - module ref
uUserIndex - current user index
*pUser - target user id (XUID for xboxone)
*pNotifyCb - callback
*pUserData - user data
Returns
int32_t - 0 for success, negative for error
Version
07/09/2013 (tcho)
References USERLISTAPI_ERROR_UNSUPPORTED.
DIRTYCODE_API int32_t UserListApiIsFriendAsync (UserListApiRefT * pRef, uint32_t uUserIndex, DirtyUserT * pUser, UserListApiIsAQueryCallbackT * pNotifyCb, void * pUserData)
Is target user blocked.
Is target user blocked.
Parameters
*pRef - - module ref
uUserIndex - current user index
*pUser - target user id (XUID for xboxone)
*pNotifyCb - callback
*pUserData - user data
Returns
int32_t - 0 for success, negative for error
Version
07/09/2013 (tcho)
References UserListApiResultT::bNeedsMemFreed, UserListApiPlatformRequestListT::bWaitingForFriendsList, UserListApiPlatformRequestListT::bWaitingForPresenceList, UserListApiPlatformRequestListT::bWaitingForProfileList, UserListApiRefT::crit, DirtyMemAlloc(), DirtyUserToNativeUser(), ds_memcpy_s(), ds_snzprintf(), ds_strnzcpy(), UserListApiResultT::eRequestType, UserListApiRefT::iMemGroup, NetConnStatus(), NetCritEnter(), NetCritLeave(), NetPrintf, NetTick(), UserListApiIsFriendQueueT::pAssociatedResult, UserListApiRefT::pHttp, UserListApiResultT::pIsAQueryNotifyCb, UserListApiRefT::pIsFriendRequestQueue, UserListApiRefT::pMemGroupUserData, UserListApiResultT::pNext, UserListApiIsFriendQueueT::pNext, UserListApiResultT::pNotifyCb, ProtoHttpControl(), ProtoHttpGet(), UserListApiResultT::pTargetUserId, UserListApiResultT::pUserData, UserListApiRefT::ResultList, UserListApiIsFriendQueueT::strRequest, UserListApiResultT::SubQueryStatuses, UserListApiRefT::uHttpOpTimer, USERLISTAPI_ERROR_GUEST, USERLISTAPI_ERROR_INVALID_USER, USERLISTAPI_ERROR_USER_INDEX_RANGE, USERLISTAPI_ISFRIEND_PATH, USERLISTAPI_MEMID, USERLISTAPI_REQUEST_PATH_SIZE, USERLISTAPI_REQUEST_TYPE_ISFRIENDS, UserListApiResultT::uUserIndex, and UserListApiIsFriendQueueT::uUserIndex.
DIRTYCODE_API int32_t UserListApiRegisterUpdateEvent (UserListApiRefT * pRef, uint32_t uUserIndex, UserListApiNotifyTypeE eType, UserListApiUpdateCallbackT * pNotifyCb, void * pUserData)
give module time to perform periodic processing
give module time to perform periodic processing
Parameters
*pRef - module ref
uUserIndex - user index
*eType - type of callback requested
*pNotifyCb - the callback pointer
*pUserData - the user data pointer
Returns
int32_t - 0 for success, negative for error
Version
02/14/2014 (amakoukji)
References USERLISTAPI_ERROR_UNSUPPORTED.
DIRTYCODE_API int32_t UserListApiStatus (UserListApiRefT * pRef, int32_t iSelect, void * pBuf, int32_t iBufSize)
control function
control function
Parameters
*pRef - module ref
iSelect - status selector
*pBuf - [in/out] control value
iBufSize - size of pBuf
Returns
int32_t - zero=success; negative=error
Version
04/17/2013 (amakoukji)
References NetPrintf.
DIRTYCODE_API void UserListApiUpdate (UserListApiRefT * pRef)
get status information
get status information
Parameters
*pRef - module ref
Version
04/17/2013 (amakoukji)
References _UserListApiGetPriorityTitle(), _UserListApiProcessIsFriend(), UserListApiRefT::aXblContext, UserListApiUserDataT::bIsFavorite, UserListApiIsADataT::bIsFavorite, UserListApiUserDataT::bIsMutualFriend, UserListApiIsADataT::bIsMutualFriend, UserApiPresenceT::bIsPlayingSameTitle, UserListApiResultT::bResponseProcessed, UserListApiPlatformRequestListT::bWaitingForFriendsList, UserListApiPlatformRequestListT::bWaitingForPresenceList, UserListApiPlatformRequestListT::bWaitingForProfileList, UserListApiRefT::crit, data, DirtyMemFree(), UserListApiUserDataT::DirtyUser, UserApiUserDataT::DirtyUser, UserListApiIsADataT::DirtyUser, DirtyUserFromNativeUser(), ds_memcpy_s(), ds_snzprintf(), UserListApiIsADataT::eIsaType, UserApiPresenceT::ePresenceStatus, UserListApiResultT::eRequestType, UserListApiUserDataT::eRequestType, UserListApiEndDataT::eRequestType, UserListApiEndDataT::Error, UserListApiIsADataT::Error, UserListApiUserDataT::ExtendedUserData, FALSE, UserListApiResultT::iErrorFriend, UserListApiResultT::iErrorPresence, UserListApiResultT::iErrorProfile, UserListApiResultT::iLimit, UserListApiEndDataT::iLimit, UserListApiRefT::iMemGroup, UserListApiResultT::iOffset, UserListApiEndDataT::iOffset, UserListApiEndDataT::iTotalFriendCount, UserListApiUserDataT::iUserProfileError, JsonFind(), JsonGetBoolean(), JsonGetInteger(), JsonParse(), UserListApiEventDataT::ListEndData, NetCritEnter(), NetCritLeave(), NetPrintf, NetTick(), NetTickDiff, UserListApiRefT::pHttp, UserListApiResultT::pIsAQueryNotifyCb, UserListApiRefT::pMemGroupUserData, UserListApiResultT::pNext, UserListApiResultT::pNotifyCb, UserApiRichPresenceT::pRawData, UserApiPresenceT::pRawData, UserApiProfileT::pRawData, UserListApiUserDataT::pRawData, UserApiUserDataT::Presence, UserApiUserDataT::Profile, PROTOHTTP_MINBUFF, PROTOHTTP_RECVFAIL, ProtoHttpRecvAll(), ProtoHttpStatus(), ProtoHttpUpdate(), UserListApiResultT::pTargetUserId, UserListApiResultT::pUserData, UserListApiUserDataT::pUserListFilters, UserListApiEndDataT::pUserListFilters, UserListApiResultT::refResultFriend, UserListApiResultT::refResultPresence, UserListApiResultT::refResultProfile, UserListApiRefT::ResultList, UserApiUserDataT::RichPresence, UserListApiResultT::SocialView, UserApiProfileT::strAvatarUrl, UserApiRichPresenceT::strData, UserApiProfileT::strDisplayName, UserApiProfileT::strGamertag, UserApiPresenceT::strPlatform, UserApiPresenceT::strTitleId, UserApiPresenceT::strTitleName, UserListApiResultT::SubQueryStatuses, TRUE, TYPE_LIST_END, TYPE_USER_DATA, UserListApiRefT::uHttpOpTimer, UserApiProfileT::uLocale, UserListApiPlatformUserContextT::uOpFriendTimer, UserListApiPlatformUserContextT::uOpPresenceTimer, UserListApiPlatformUserContextT::uOpProfileTimer, USERAPI_MASK_PRESENCE, USERAPI_MASK_PROFILE, USERAPI_MASK_RICH_PRESENCE, USERAPI_PRESENCE_AWAY, USERAPI_PRESENCE_OFFLINE, USERAPI_PRESENCE_ONLINE, USERAPI_PRESENCE_UNKNOWN, UserListApiEventDataT::UserData, USERLISTAPI_ASYNC_TIMOUT_MS, USERLISTAPI_ERROR_TIMEOUT, USERLISTAPI_ERROR_UNKNOWN, USERLISTAPI_HTTP_READ_BUFFER_SIZE, USERLISTAPI_IS_FRIENDS, USERLISTAPI_IS_MYSELF, USERLISTAPI_IS_NOT_OF_TYPE, USERLISTAPI_IS_OF_TYPE, USERLISTAPI_IS_TYPE_UNKNOWN, USERLISTAPI_MASK_PRESENCE, USERLISTAPI_MASK_PROFILE, USERLISTAPI_MASK_RICH_PRESENCE, USERLISTAPI_MEMID, USERLISTAPI_MYSELF_ERROR_CODE, USERLISTAPI_NOT_IN_PEOPLE_LIST_ERROR_CODE, USERLISTAPI_READ_BUFFER_SIZE, USERLISTAPI_REQUEST_TYPE_FRIENDS, USERLISTAPI_REQUEST_TYPE_ISFRIENDS, USERLISTAPI_TYPE_FRIENDS, Utf8EncodeFromUCS2(), UserListApiResultT::uTypeMask, UserListApiEndDataT::uTypeMask, UserApiUserDataT::uUserDataMask, UserListApiResultT::uUserIndex, UserListApiUserDataT::uUserIndex, UserListApiEndDataT::uUserIndex, and UserListApiIsADataT::uUserIndex.
Referenced by VoipHeadsetProcess().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:34:37