DirtySock: DirtySessionManager
DirtySessionManager
DirtySock
Macros
#define DIRTYSESSIONMANAGER_FLAG_PUBLICSLOT (1)
#define DIRTYSESSIONMANAGER_FLAG_PRIVATESLOT (2)
Typedefs
typedef struct
DirtySessionManagerRefT DirtySessionManagerRefT
Functions
DirtySessionManagerRefT * DirtySessionManagerCreate (DirtyAddrT *pHostAddr, DirtyAddrT *pLocalAddr)
Allocate module state and prepare for use.
void DirtySessionManagerDestroy (DirtySessionManagerRefT *pRef)
Destroy the module and release its state.
void DirtySessionManagerUpdate (DirtySessionManagerRefT *pRef)
(Unused) Update module state
void DirtySessionManagerConnect (DirtySessionManagerRefT *pRef, const char **pSessID, uint32_t *pSlot, uint32_t uCount)
(Unused) Connects one or many player(s) to a given game
int32_t DirtySessionManagerControl (DirtySessionManagerRefT *pRef, int32_t iControl, int32_t iValue, int32_t iValue2, const void *pValue)
DirtySessionManager control function.
int32_t DirtySessionManagerStatus (DirtySessionManagerRefT *pRef, int32_t iSelect, void *pBuf, int32_t iBufSize)
Return module status based on input selector.
int32_t DirtySessionManagerStatus2 (DirtySessionManagerRefT *pRef, int32_t iSelect, int32_t iValue, int32_t iValue2, int32_t iValue3, void *pBuf, int32_t iBufSize)
Return module status based on input selector, passes through to DirtySessionManagerStatus.
void DirtySessionManagerEncodeSession (char *pBuffer, int32_t iBufSize, const void *pSessionInfo)
Encode the pending sessions binary header and data and write it to pBuff if there is sufficiet space.
void DirtySessionManagerDecodeSession (void *pSessionInfo, const char *pBuffer)
unused, requires buffer size param to be useful
int32_t DirtySessionManagerCreateSess (DirtySessionManagerRefT *pRef, uint32_t bRanked, uint32_t *uUserFlags, const char *pSession, DirtyAddrT *pLocalAddrs)
(Unused) Create a PS4 session.
Detailed Description
Macro Definition Documentation
#define DIRTYSESSIONMANAGER_FLAG_PRIVATESLOT (2)
#define DIRTYSESSIONMANAGER_FLAG_PUBLICSLOT (1)
Typedef Documentation
typedef struct DirtySessionManagerRefT DirtySessionManagerRefT
Function Documentation
void DirtySessionManagerConnect (DirtySessionManagerRefT * pRef, const char ** pSessID, uint32_t * pSlot, uint32_t uCount)
(Unused) Connects one or many player(s) to a given game
Parameters
*pRef - module state
**pSessID- for Xbox, this is an array of pointers to the peers DirtyAddrT
pSlot - slot type to use, i.e. DIRTYSESSIONMANAGER_FLAG_PUBLICSLOT, array: one per player
uCount - number of players to join
Version
04/03/2013 (cvienneau)
int32_t DirtySessionManagerControl (DirtySessionManagerRefT * pRef, int32_t iControl, int32_t iValue, int32_t iValue2, const void * pValue)
DirtySessionManager control function.
Parameters
*pRef - module ref
iControl - control selector
iValue - selector specific
iValue2 - selector specific
*pValue - selector specific
Returns
int32_t - 0=success; negative=error
Note
iControl can be one of the following:
        'abrt' - abort all active requests
        'decb' - decode the supplied buffer into the pending sessions binary header and data
        'csid' - force close the session invitation dialog
        'cssi' - clear the selected session id from the invite dialog, for after reading the session from 'gssi'
        'gdat' - queue getting the binary data into the pending session
        'ginv' - queue getting of session invitation list for player index iValue
        'gimd' - queue getting of meta data for invitation for player index iValue, invite index iValue2
        'gmse' - debug to print the sessions this player is a member of for player index iValue
        'gses' - queue getting the provided session (via pValue=sessionid) into the pending session
        'ianp' - add a user name to list of npids to invite (only usable when not editable); via pValue
        'icnp' - clear the list of invitation np ids.
        'imus' - set the number of users for the session invite, via iValue
        'imsg' - set the session invitation message; via pValue
        'iued' - set if the invited users are editable once dispalyed; iValue as a bool
        'osid' - open session invitation dialog (using data from 'ianp', 'imus', 'imsg', 'iued', 'inpi'); iValue inviters user index
        'osrd' - open session receive dialog for player index iValue
        'rbuf' - set the buffer size to receive data into, may need to be large for binary data or large invite lists (sony says 100 max), via iValue
        'rqbs' - set the buffer size to generate requests into (sendbuff), may need to be large for images or binary data, via iValue
        'lock' - locks or unlocks the pending session. Set iValue to TRUE to lock, FALSE to unlock
        'scre' - queue create a new session with the current settings, all users on the console will autoamatically join the same session
        'sdat' - set the pending session's binary data; pValue incomming data, iValue2 data size
        'sdel' - queue remove all players from the current active session
        'sidi' - call sceInvitationDialogInitialize, and take responsibility for calling 'sidt'
        'sidt' - call sceInvitationDialogTerminate, and relinquish responsibility for calling 'sidt'
        'sind' - send invitations without first party dialog
        'simg' - set the pending session's image; pValue incomming data, iValue2 data size
        'siud' - set the bool indicating that the invite list is up to date, in case you want to ignore this update but want to detect future ones, for player index iValue
        'sjoi' - queue to have the user at index (iValue) join the provided session id (pValue)
        'slid' - set the pending session lobby id; int64 via pValue, iValue2 sizeof(int64_t)
        'smau' - set the pending session's maximum number of users; iValue2 is new max 0-256
        'snam' - set the pending session's name; pValue incomming string, iValue2 local code ie 'enUS' 0 for unlocalized
        'spri' - set the pending session's privacy setting; iValue2 == 1 private (default public)
        'ssta' - set the pending session's status; pValue incomming string, iValue2 local code ie 'enUS' 0 for unlocalized
        'surm' - remove the user specified by the user index (iValue) from the session
        'uimg' - queue updating the active image data from the pending session
        'uinv' - queue updating the invite usedFlag to TRUE for player index iValue, invite index iValue2
        'umau' - queue updating the active session max user attribute from the pending session
        'uses' - queue updating the active session from pending session
Version
04/03/2013 (cvienneau)
References DirtySessionInvitationT::aNpOnlineIds, DirtySessionManagerRefT::aSessionUsers, DirtySessionInvitationT::bEditList, DirtySessionManagerSessionInfoT::binaryDataHeader, DirtySessionManagerRefT::bInvDialog, DirtySessionManagerRefT::bInvDialogUserManagedInit, DirtySessionRecievedInvitationListT::bListUpToDate, DirtySessionManagerSessionInfoT::bPrivate, DirtySessionManagerSessionInfoT::bSessionLock, DirtySessionManagerUserT::bSessionMember, DirtySessionManagerRefT::crit, DIRTY_SESSION_MAX_INVITATION_MEMBER_LIST_LENGTH, DirtyErrGetName(), DirtyWebApiAbortRequests(), DirtyWebApiControl(), ds_memcpy(), ds_stricmp(), ds_strnicmp(), ds_strnzcpy(), FALSE, DirtySessionManagerRefT::iActiveRequests, DirtySessionManagerBinaryHeaderT::iLobbyId, DirtySessionManagerSessionInfoT::iMaxUsers, DirtySessionInvitationT::iMaxUsers, DirtySessionManagerRefT::InvitationInfo, DirtySessionManagerRefT::iRequestBuffSize, NETCONN_MAXLOCALUSERS, NetConnStatus(), NetCritEnter(), NetCritLeave(), NetPrintf, NULL, DirtySessionManagerRefT::PendingSession, DirtySessionManagerRefT::pWebApi, DirtySessionManagerUserT::RecievedInvitations, DirtySessionInvitationT::strMessage, DirtySessionManagerRefT::strSelectedInviteID, DirtySessionManagerRefT::strSelectedSessionID, DirtySessionManagerSessionInfoT::strSessionID, and TRUE.
Referenced by DirtySessionManagerDestroy().
DirtySessionManagerRefT* DirtySessionManagerCreate (DirtyAddrT * pHostAddr, DirtyAddrT * pLocalAddrUnused)
Allocate module state and prepare for use.
Parameters
*pHostAddr - host dirtyaddr, or NULL if not available
*pLocalAddrUnused - DEPRECATED: local dirtyaddr, Not used
Returns
DirtySessionManagerRefT * - reference pointer (must be passed to all other functions)
Version
04/03/2013 (cvienneau)
References DirtySessionManagerRefT::crit, DIRTY_SESSION_DEFAULT_RECIEVE_BUFF_SIZE, DIRTY_SESSION_DEFAULT_REQUEST_BUFF_SIZE, DirtyEventManagerRegisterSystemService(), DirtyMemAlloc(), DIRTYSESSMGR_MEMID, DirtyWebApiCreate(), DirtySessionManagerRefT::iMemGroup, DirtySessionManagerRefT::iRequestBuffSize, NetConnIdleAdd(), NetConnStatus(), NetCritInit(), NetPrintf, NULL, DirtySessionManagerRefT::pMemGroupUserData, pRef, and DirtySessionManagerRefT::pWebApi.
int32_t DirtySessionManagerCreateSess (DirtySessionManagerRefT * pRef, uint32_t bRanked, uint32_t * uUserFlags, const char * pSession, DirtyAddrT * pLocalAddrs)
(Unused) Create a PS4 session.
Parameters
*pRef - pointer to module state
bRanked - TRUE if ranked, else FALSE
uUserFlags - User flags such as slot type, DIRTYSESSIONMANAGER_FLAG_PUBLICSLOT | DIRTYSESSIONMANAGER_FLAG_PRIVATESLOT
*pSession - NULL if creating new session, pointer to session string if joining
*pLocalAddrs - Array of local address to join-in. Controller-index based. 0 if player is not joining
Returns
int32_t - zero=success, negative=failure
Version
04/03/2013 (cvienneau)
void DirtySessionManagerDecodeSession (void * pSessionInfo0, const char * pBuffer)
unused, requires buffer size param to be useful
Parameters
*pSessionInfo0 - DirtySessionManagerRefT
*pBuffer - pointer to incomming data
Version
04/03/2013 (cvienneau)
void DirtySessionManagerDestroy (DirtySessionManagerRefT * pRef)
Destroy the module and release its state.
Parameters
*pRef - reference pointer
Version
04/03/2013 (cvienneau)
References DirtySessionManagerRefT::crit, DirtySessionManagerControl(), DirtySessionManagerRefT::iActiveRequests, NetConnControl(), NetCritEnter(), NetCritLeave(), NetPrintf, and NULL.
void DirtySessionManagerEncodeSession (char * pBuffer, int32_t iBufSize, const void * pSessionInfo0)
Encode the pending sessions binary header and data and write it to pBuff if there is sufficiet space.
Parameters
*pBuffer - [out] pointer to buffer for session string
iBufSize - size of output buffer
*pSessionInfo0 - DirtySessionManagerRefT
Version
04/03/2013 (cvienneau)
References DirtySessionManagerSessionInfoT::binaryDataHeader, ds_memcpy(), DirtySessionManagerSessionInfoT::iBinaryDataSize, DirtySessionManagerSessionInfoT::pBinaryData, and DirtySessionManagerRefT::PendingSession.
Referenced by DirtySessionManagerStatus().
int32_t DirtySessionManagerStatus (DirtySessionManagerRefT * pRef, int32_t iSelect, void * pBuf, int32_t iBufSize)
Return module status based on input selector.
Parameters
*pRef - module ref
iSelect - status selector
*pBuf - user-provided buffer
iBufSize - size of user-provided buffer
Returns
int32_t - depends on selector, see each code
Note
iSelect can be one of the following:
        'bnam' - returns True if pending session name is before
        'bsta' - returns True if pending session status is set before
        'encb' - encode the pending sessions binary header and data and write it to pBuff if there is sufficiet space, returns the number of bytes
        'gclo' - get the active session's closed flag; -1 error, 0 joinable, 1 closed
        'gcre' - checks to see if session creation/join has completed, returns -1 error, 0 in progress, 1 active; and session id if a buffer to receive it (46 bytes) has been provided
        'gprc' - gets the pending request count, will be 0 with the session manager is idel
        'gpda' - get the pending session's binary data size; returns -1 error, 0 in progress, > 0 size; pValue if large enough will have the data written to it
        'gdat' - get the active session's binary data size; returns -1 error, 0 in progress, > 0 size; pValue if large enough will have the data written to it
        'gali' - get the active binary data lobby id; int64 via pBuf, iBUfSize =  sizeof(int64_t)
        'gpli' - get the pending binary data lobby id; int64 via pValue, iValue2 sizeof(int64_t)
        'gmau' - get the active session's maximum number of users; -1 error, >=0 max users
        'gnam' - get the active session's name; -1 error, pBuf output string
        'gpid' - get the pending session id. -1 error, 1 success, pBuf output string
        'gpri' - get the active session's privacy setting; -1 error, 0 public, 1 private
        'gsdo' - get if the session dialog is open
        'gsii' - get the selected invite id from the invite dialog, via pBuf
        'gssi' - get the selected session id from the invite dialog, via pBuf
        'gsta' - get the active session's status; -1 error, pBuf output string
        'laid' - get the last user that accepted an invite and returns it via pBuf as a DirtyUserT
        'lock' - get the session lock status of the active session
Version
04/03/2013 (cvienneau)
References DirtySessionManagerRefT::ActiveSession, DirtySessionManagerRefT::aSessionUsers, DirtySessionManagerSessionInfoT::bClosed, DirtySessionManagerSessionInfoT::binaryDataHeader, DirtySessionManagerRefT::bInvDialog, DirtySessionManagerRefT::bPendingNameSet, DirtySessionManagerRefT::bPendingStatusSet, DirtySessionManagerSessionInfoT::bPrivate, DirtySessionManagerSessionInfoT::bSessionLock, DirtySessionManagerRefT::crit, DIRTY_SESSION_ACTIVE, DIRTY_SESSION_INVALID, DIRTY_SESSION_PENDING, DirtySessionManagerEncodeSession(), DirtyUserFromNativeUser(), ds_memcpy(), ds_strnzcpy(), DirtySessionManagerRefT::eSessionStatus, DirtySessionManagerRefT::iActiveRequests, DirtySessionManagerSessionInfoT::iBinaryDataSize, DirtySessionManagerBinaryHeaderT::iLobbyId, DirtySessionManagerSessionInfoT::iMaxUsers, DirtySessionRecievedInvitationListT::iNumInvitations, DirtySessionManagerRefT::lastAcceptOnlineId, NetCritEnter(), NetCritLeave(), NULL, DirtySessionManagerSessionInfoT::pBinaryData, DirtySessionManagerRefT::PendingSession, DirtySessionManagerUserT::RecievedInvitations, DirtySessionManagerRefT::strSelectedInviteID, DirtySessionManagerRefT::strSelectedSessionID, DirtySessionManagerSessionInfoT::strSessionID, DirtySessionManagerSessionInfoT::strSessionName, and DirtySessionManagerSessionInfoT::strSessionStatus.
Referenced by DirtySessionManagerStatus2().
int32_t DirtySessionManagerStatus2 (DirtySessionManagerRefT * pRef, int32_t iSelect, int32_t iValue, int32_t iValue2, int32_t iValue3, void * pBuf, int32_t iBufSize)
Return module status based on input selector, passes through to DirtySessionManagerStatus.
Parameters
*pRef - module ref
iSelect - status selector
iValue - selection argument
iValue2 - selection argument
iValue3 - selection argument
*pBuf - user-provided buffer
iBufSize - size of user-provided buffer
Returns
int32_t - depends on selector, see each code
Note
iSelect can be one of the following:
        'giex' - get the invitation expired flag as bool; for the player at iValue index
        'ginv' - get the current count of invitations; for the player at iValue index
        'gimd' - get the invitation meta data has been set as bool; iValue player index, iValue2 invitation index
        'gims' - get the invitation maessage for; iValue player index, iValue2 invitation index, via pbuff as a char[]
        'giii' - get the invitation invite id for; iValue player index, iValue2 invitation index, via pbuff as a char[]
        'gisi' - get the invitation session id for; iValue player index, iValue2 invitation index, via pbuff as a char[]
        'giud' - get the current invitation list is up to date, as a bool; for the player at iValue index
        'giun' - get the invitation user name for; iValue player index, iValue2 invitation index, via pbuff as a DirtyUserT
        'giuf' - get the invitation used flag as bool; for the player at iValue index
Version
04/03/2013 (cvienneau)
References DirtySessionRecievedInvitationListT::aInvitations, DirtySessionManagerRefT::aSessionUsers, DirtySessionRecievedInvitationT::bExpired, DirtySessionRecievedInvitationT::bHasMetaData, DirtySessionRecievedInvitationListT::bListUpToDate, DirtySessionRecievedInvitationT::bUsedFlag, DirtySessionManagerStatus(), DirtyUserFromNativeUser(), ds_memcpy(), ds_strnzcpy(), DirtySessionRecievedInvitationListT::iNumInvitations, NetPrintf, DirtySessionManagerUserT::RecievedInvitations, DirtySessionRecievedInvitationT::strFromUser, DirtySessionRecievedInvitationT::strInvitationID, DirtySessionRecievedInvitationT::strMessage, and DirtySessionRecievedInvitationT::strSessionID.
void DirtySessionManagerUpdate (DirtySessionManagerRefT * pRef)
(Unused) Update module state
Parameters
*pRef - module state
Version
04/03/2013 (cvienneau)
References DirtySessionManagerRefT::bInitEvents, DirtySessionManagerRefT::bInvDialog, DirtySessionManagerRefT::bInvDialogUserManagedInit, DirtySessionManagerRefT::crit, DirtyErrGetName(), DirtyWebApiAddPushEventListenerEx(), FALSE, DirtySessionManagerResponseT::iControlCode, DirtySessionManagerResponseT::iRespBodyLength, DirtySessionManagerResponseT::iStatusCode, DirtySessionManagerResponseT::iUserIndex, NetConnStatus(), NetCritEnter(), NetCritLeave(), NetPrintf, NULL, DirtySessionManagerResponseT::pRequestData, DirtySessionManagerResponseT::pRespBody, DirtySessionManagerRefT::pWebApi, DirtySessionManagerRefT::ResponseData, and TRUE.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:32