DirtySock: NetGameDistServ
NetGameDistServ
Game
Typedefs
typedef struct NetGameDistServT NetGameDistServT
opaque module state
Functions
DIRTYCODE_API NetGameDistServT * NetGameDistServCreate (int32_t iMaxClients, int32_t iVerbosity)
Create the NetGameDistServ module.
DIRTYCODE_API void NetGameDistServDestroy (NetGameDistServT *pDistServ)
Destroy the NetGameDistServ module.
DIRTYCODE_API int32_t NetGameDistServAddClient (NetGameDistServT *pDistServ, int32_t iClient, NetGameLinkRefT *pLinkRef, const char *pClientName)
Add a client to the client list.
DIRTYCODE_API int32_t NetGameDistServDelClient (NetGameDistServT *pDistServ, int32_t iClient)
Delete a client from the client list.
DIRTYCODE_API int32_t NetGameDistServDiscClient (NetGameDistServT *pDistServ, int32_t iClient)
Mark the specified client as disconnect. This will prevent sends and update.
DIRTYCODE_API int32_t NetGameDistServUpdateClient (NetGameDistServT *pDistServ, int32_t iClient)
Update the Dist ref for the specified client.
DIRTYCODE_API void NetGameDistServStartGame (NetGameDistServT *pDistServ)
Starts the game, enabling controller passing.
DIRTYCODE_API void NetGameDistServStopGame (NetGameDistServT *pDistServ)
Stops the game, halting controller passing.
DIRTYCODE_API void NetGameDistServUpdate (NetGameDistServT *pDistServ)
Update the DistServ module. This function is expected to be called at the desired output rate.
DIRTYCODE_API uint8_t NetGameDistServHighWaterChanged (NetGameDistServT *pDistServ, int32_t *pHighWaterInputQueue, int32_t *pHighWaterOutputQueue)
Return whether the highwater mark changed, and the current highwater values.
DIRTYCODE_API char * NetGameDistServExplainError (NetGameDistServT *pDistServ, int32_t iClient)
return the lastest error reported by netgamedist, for client iClient
DIRTYCODE_API int32_t NetGameDistServControl (NetGameDistServT *pDistServ, int32_t iControl, int32_t iValue, int32_t iValue2, void *pValue)
Control behavior of module.
DIRTYCODE_API int32_t NetGameDistServStatus (NetGameDistServT *pDistServ, int32_t iSelect, void *pBuf, int32_t iBufSize)
Get status information.
Detailed Description
Typedef Documentation
typedef struct NetGameDistServT NetGameDistServT
opaque module state
Function Documentation
DIRTYCODE_API int32_t NetGameDistServAddClient (NetGameDistServT * pDistServ, int32_t iClient, NetGameLinkRefT * pLinkRef, const char * pClientName)
Add a client to the client list.
Parameters
*pDistServ - module state
iClient - index of slot to add client to
*pLinkRef - link ref to create dist with
*pClientName - name of client
Returns
int32_t - negative=error, else success
Version
02/05/2007 (jbrookes)
References NetGameDistServClientT::bDisconnected, NetGameDistServClientT::bInitialized, NetGameDistServT::ClientList, NetGameDistServClientListT::Clients, DirtyMemGroupEnter(), DirtyMemGroupLeave(), ds_strnzcpy(), GMDIST_DEFAULT_BUFFERSIZE_IN, GMDIST_DEFAULT_BUFFERSIZE_OUT, NetGameDistServT::iMemGroup, NetGameDistServClientListT::iNumClients, NetGameDistServT::iVerbosity, NetGameDistCreate(), NetGameDistSetProc(), NetGameDistSetServer(), NetGameLinkRecv(), NetGameLinkSend(), NetGameLinkStatus(), NetPrintf, NetPrintfVerbose, NetGameDistServClientT::pGameDist, NetGameDistServT::pMemGroupUserData, NetGameDistServClientT::strName, and TRUE.
DIRTYCODE_API int32_t NetGameDistServControl (NetGameDistServT * pDistServ, int32_t iControl, int32_t iValue, int32_t iValue2, void * pValue)
Control behavior of module.
Parameters
*pDistServ - pointer to module state
iControl - status selector
iValue - control value
iValue2 - control value
*pValue - control value
Note
iControl can be one of the following:
        'mpty' - set the number(iValue) of empty frames needed to pause traffic
        'crcc' - set the CRC challenge send rate in number of frames (0 to disable)
        'crcr' - set the CRC max response times in number of frames (0 makes it infinite)
Version
03/17/2009 (jrainy)
References NetPrintf, NetGameDistServT::uCRCRate, NetGameDistServT::uCRCRemainingFrames, NetGameDistServT::uCRCResponseLimit, and NetGameDistServT::uSendThreshold.
DIRTYCODE_API NetGameDistServT* NetGameDistServCreate (int32_t iMaxClients, int32_t iVerbosity)
Create the NetGameDistServ module.
Parameters
iMaxClients - maximum number of clients supported
iVerbosity - debug verbose level
Returns
NetGameDistServT * - module state, or NULL if create failed
Version
02/01/2007 (jbrookes)
References NetGameDistServT::ClientList, NetGameDistServClientListT::Clients, DirtyMemAlloc(), DirtyMemGroupQuery(), NetGameDistServClientListT::iMaxClients, NetGameDistServT::iMemGroup, NetGameDistServT::iVerbosity, NETGAMEDISTSERV_MEMID, NetPrintf, NetGameDistServT::pMemGroupUserData, and NetGameDistServT::uSendThreshold.
DIRTYCODE_API int32_t NetGameDistServDelClient (NetGameDistServT * pDistServ, int32_t iClient)
Delete a client from the client list.
Parameters
*pDistServ - module state
iClient - index of slot to delete client from
Returns
int32_t - negative=error, else success
Version
02/05/2007 (jbrookes)
References NetGameDistServT::ClientList, NetGameDistServClientListT::Clients, GMDIST_DELETED, NetGameDistServClientListT::iMaxClients, NetGameDistServClientListT::iNumClients, and NetPrintf.
DIRTYCODE_API void NetGameDistServDestroy (NetGameDistServT * pDistServ)
Destroy the NetGameDistServ module.
Parameters
*pDistServ - module state
Version
02/01/2007 (jbrookes)
References DirtyMemFree(), NetGameDistServT::iMemGroup, NETGAMEDISTSERV_MEMID, and NetGameDistServT::pMemGroupUserData.
DIRTYCODE_API int32_t NetGameDistServDiscClient (NetGameDistServT * pDistServ, int32_t iClient)
Mark the specified client as disconnect. This will prevent sends and update.
Parameters
*pDistServ - module state
iClient - index of slot holding client to update
Returns
int32_t - negative=error, else success
Version
03/15/2007 (jrainy)
References NetGameDistServT::ClientList, NetGameDistServClientListT::Clients, GMDIST_DISCONNECTED, NetGameDistServClientListT::iMaxClients, NetPrintf, and TRUE.
DIRTYCODE_API char* NetGameDistServExplainError (NetGameDistServT * pDistServ, int32_t iClient)
return the lastest error reported by netgamedist, for client iClient
Parameters
*pDistServ - module state
iClient - client to get the error for.
Returns
char * - the latest netgamedist error
Version
08/15/2008 (jrainy)
References NetGameDistServT::ClientList, NetGameDistServClientListT::Clients, and NetGameDistServClientT::strDiscReason.
DIRTYCODE_API uint8_t NetGameDistServHighWaterChanged (NetGameDistServT * pDistServ, int32_t * pHighWaterInputQueue, int32_t * pHighWaterOutputQueue)
Return whether the highwater mark changed, and the current highwater values.
Parameters
*pDistServ - module state
pHighWaterInputQueue - input queue
pHighWaterOutputQueue - output queue
Returns
Whether the HighWater marks changed since last call.
Version
06/05/2008 (jrainy)
References FALSE.
DIRTYCODE_API void NetGameDistServStartGame (NetGameDistServT * pDistServ)
Starts the game, enabling controller passing.
Parameters
*pDistServ - module state
Version
03/05/2007 (jbrookes)
References NetGameDistServT::bGameStarted, NetPrintf, NetTick(), TRUE, NetGameDistServT::uCRCRate, NetGameDistServT::uCRCRemainingFrames, NetGameDistServT::uCRCResponseCountdown, and NetGameDistServT::uLastFlowUpdateTime.
DIRTYCODE_API int32_t NetGameDistServStatus (NetGameDistServT * pDistServ, int32_t iSelect, void * pBuf, int32_t iBufSize)
Get status information.
Parameters
*pDistServ - pointer to module state
iSelect - status selector
*pBuf - [out] storage for selector-specific output
iBufSize - size of output buffer
Returns
int32_t - selector specific
Note
iSelect can be one of the following:
        'ninp' - whether we are currently in the mode where no inputs are sent due to
                    stall in input arrival
        'ftim' - flow time. Time (ms) since the last flow control packet was received.
Version
24/09/2012 (jrainy) first version
References NetGameDistServT::bGameStarted, NetGameDistServT::bNoInputMode, NetTick(), NetTickDiff, and NetGameDistServT::uLastFlowUpdateTime.
DIRTYCODE_API void NetGameDistServStopGame (NetGameDistServT * pDistServ)
Stops the game, halting controller passing.
Parameters
*pDistServ - module state
Version
05/20/2008 (jbrookes)
References NetGameDistServT::bGameStarted, FALSE, and NetPrintf.
DIRTYCODE_API void NetGameDistServUpdate (NetGameDistServT * pDistServ)
Update the DistServ module. This function is expected to be called at the desired output rate.
Parameters
*pDistServ - module state
Version
02/12/2007 (jrainy)
References NetGameDistServClientT::aLocalInput, NetGameDistServClientT::bDisconnected, NetGameDistServT::bFlowEnabled, NetGameDistServT::bGameStarted, NetGameDistServClientT::bInitialized, NetGameDistServClientT::bLocalInput, NetGameDistServT::bNoInputMode, NetGameDistStatT::bps, NetGameDistServClientT::bReallyPeeked, NetGameDistServClientT::bRemoteRcv, NetGameDistServClientT::bRemoteSnd, NetGameDistServT::ClientList, NetGameDistServClientListT::Clients, ds_memcpy_s(), FALSE, GMDIST_DATA_CRC_REQUEST, GMDIST_INPUTLOCAL_FAILED, GMDIST_INPUTLOCAL_FAILED_INVALID, GMDIST_INPUTLOCAL_FAILED_MULTI, GMDIST_INPUTLOCAL_FAILED_WINDOW, GMDIST_INPUTQUERY_FAILED, GMDIST_INVALID, GMDIST_MAX_CLIENTS, GMDIST_OVERFLOW_MULTI, GMDIST_OVERFLOW_WINDOW, GMDIST_PEEK_ERROR, NetGameDistServClientT::iCRC, NetGameDistServT::iFirstClient, NetGameDistServClientT::iLocalInputSize, NetGameDistServClientT::iLocalInputType, NetGameDistServClientListT::iMaxClients, NetGameDistServClientT::iPeekKey, NetGameDistServT::iVerbosity, NetGameLinkStatT::late, NetGameDistStatT::late, NetGameDistControl(), NetGameDistInputLocalMulti(), NetGameDistInputPeek(), NetGameDistInputQueryMulti(), NetGameDistSendStats(), NetGameDistStatus(), NetPrintf, NetPrintfVerbose, NetTick(), NetTickDiff, NetGameLinkStatT::outbps, NetGameLinkStatT::outpps, PACKET_WINDOW, NetGameDistServClientT::pGameDist, NetGameLinkStatT::ping, NetGameDistStatT::ping, NetGameDistStatT::pps, SocketHtonl(), NetGameDistServClientT::strName, TRUE, NetGameDistServT::uCRCRate, NetGameDistServT::uCRCRemainingFrames, NetGameDistServT::uCRCResponseCountdown, NetGameDistServT::uCRCResponseLimit, NetGameDistServClientT::uCRCValid, NetGameDistServT::uLastFlowUpdateTime, NetGameDistServT::uLastStatsUpdate, NetGameDistServT::uNbFramesNoData, and NetGameDistServT::uSendThreshold.
DIRTYCODE_API int32_t NetGameDistServUpdateClient (NetGameDistServT * pDistServ, int32_t iClient)
Update the Dist ref for the specified client.
Parameters
*pDistServ - module state
iClient - index of slot holding client to update
Returns
int32_t - negative=disconnected, else zero
Version
02/05/2007 (jbrookes)
References NetGameDistServClientT::bDisconnected, NetGameDistServT::bGameStarted, NetGameDistServClientT::bInitialized, NetGameDistServT::ClientList, NetGameDistServClientListT::Clients, NetGameDistServClientT::iDisconnectReason, NetGameDistGetError(), NetGameDistUpdate(), NetPrintf, and NetGameDistServClientT::pGameDist.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:17