DirtySock: protomanglexboxone.cpp File Reference
protomanglexboxone.cpp File Reference
Wrapper around Xbox One Secure Networking functionality.
#include <xdk.h>
#include <wrl.h>
#include <robuffer.h>
#include "DirtySDK/dirtysock.h"
#include "DirtySDK/dirtysock/dirtyerr.h"
#include "DirtySDK/dirtysock/dirtymem.h"
#include "DirtySDK/dirtysock/dirtynet.h"
#include "DirtySDK/dirtysock/netconn.h"
#include "DirtySDK/proto/protomangle.h"
#include <collection.h>
Data Structures
struct ProtoMangleSecurityAssocT
security association data space
struct ProtoMangleClientT
struct ProtoMangleRefT
internal module state
struct ProtoMangleStateT
global protomangle state
Macros
#define PROTOMANGLE_SECURITYASSOC_CREATION_TIMEOUT (20 * 1000)
#define PROTOMANGLE_SECURITYASSOC_CHECK_FREQUENCY (2 * 1000)
Typedefs
typedef enum ProtoMangleAssocStateE ProtoMangleAssocStateE
state transitions for a single security association data space
typedef struct ProtoMangleStateT ProtoMangleStateT
global protomangle state
Enumerations
enum ProtoMangleAssocStateE {
PROTOMANGLE_STATE_INIT,
PROTOMANGLE_STATE_MULTI_UNLOCK,
PROTOMANGLE_STATE_CREATING,
PROTOMANGLE_STATE_LISTENING,
PROTOMANGLE_STATE_DONE,
PROTOMANGLE_STATE_FAILED,
PROTOMANGLE_STATE_TIMEDOUT,
PROTOMANGLE_STATE_CLEANING
}
state transitions for a single security association data space
Functions
void _ProtoMangleIncomingAssociationEventHandler (ProtoMangleRefT *pRef, SecureDeviceAssociation^refSecurityAssociation)
Event handler (delegate) registered for incoming association events.
void _ProtoMangleProcessIncomingSAs (ProtoMangleRefT *pRef)
Process the queue of incoming secure device associations.
ProtoMangleRefT * ProtoMangleCreate (const char *pServer, int32_t iPort, const char *pGameID, const char *pLKey)
Allocate module state and prepare for use.
void ProtoMangleDestroy (ProtoMangleRefT *pRef)
Destroy the module and release its state.
void ProtoMangleConnect2 (ProtoMangleRefT *pRef, int32_t iClientIndex, const char *pAddr, int32_t iAddrSize)
Initiate asynchronous resolution of secure address.
void ProtoMangleConnect (ProtoMangleRefT *pRef, int32_t iMyPort, const char *pSessID)
no-op on XboxOne
void ProtoMangleConnectSocket (ProtoMangleRefT *pRef, intptr_t uSockRef, const char *pSessID)
no-op on XboxOne
void ProtoMangleUpdate (ProtoMangleRefT *pRef)
Update module state.
int32_t ProtoMangleComplete (ProtoMangleRefT *pRef, int32_t *pAddr, int32_t *pPort)
Returns TRUE and fills in address and port if secure address resolution finished successfully.
int32_t ProtoMangleReport (ProtoMangleRefT *pRef, ProtoMangleStatusE eStatus, int32_t iLatency)
no-op on XboxOne
int32_t ProtoMangleControl (ProtoMangleRefT *pRef, int32_t iControl, int32_t iValue, int32_t iValue2, const void *pValue)
ProtoMangle control function.
int32_t ProtoMangleStatus (ProtoMangleRefT *pRef, int32_t iSelect, void *pBuf, int32_t iBufSize)
Return module status based on input selector.
const char * ProtoMangleFindTemplate (char *pStrTemplateName, int32_t iTemplateNameSize, int32_t iLocalPort, int32_t iRemotePort, uint8_t bTcp, int32_t iVerbose)
Find template suitable for given query, based on protocol, local port, and remote port.
Detailed Description
Wrapper around Xbox One Secure Networking functionality.
Attention
Copyright (c) Electronic Arts 2013. ALL RIGHTS RESERVED.
Version
04/05/2013 (mclouatre)
Note
 ProtoMangleXboxone supports parallel resolution of secure device addresses
 for different remote consoles.
 Each instance is tracked with this state machine:
     PROTOMANGLE_STATE_INIT      <----| still conflicts with entry in kill list
             |             \__________|
-------------|
|            |
|            | no conflict with an entry in the kill list
|            |
|           \/
|    PROTOMANGLE_STATE_UNLOCK    <----| waiting for unlock complete
|            |             \__________|
|            |
|            |------------------------------------------------------------
|            |                                                            |
|            | unlock is complete and we are                              | unlock is complete and we are
|            | the SA creation initiator                                  | the SA creation listener
|            |                                                            |
|           \/                                                           \/
|    PROTOMANGLE_STATE_CREATING     <-| waiting for outbound       PROTOMANGLE_STATE_LISTENING   <-| waiting for inbound
|            |             \__________| SA creation to complete           |             \__________| SA creation to complete
|            |                                                            |
|            |                                                            |
|            |------------------------------------------------------------
|            |
|            |
|            |------------------------------------------------------------
|            |                             |                              |
|            | success                     | fail                         | timed out
|            |                             |                              | (here the async security association creation is still on going)
|           \/                            \/                             \/
|    PROTOMANGLE_STATE_DONE     PROTOMANGLE_STATE_FAILED    PROTOMANGLE_STATE_TIMEDOUT
|            |                             |                              |
|            |                             |                              |
---------------------------------------------------------------------------
             |
             | entry was moved to kill list and no async op in progress
             |
            \/
     PROTOMANGLE_STATE_CLEANING     <-| if SA initiator: waiting for security association destruction to complete
             |             \__________|
             |
            \/
           free
 At any time during the life time of such an instance, the instance can be moved
 to a kill list where it sits as an invalid instance until it reaches the CLEANING
 state and eventually gets freed. This allows us to not perform any cancel of
 async operations which proved to not work properly.
Macro Definition Documentation
#define PROTOMANGLE_SECURITYASSOC_CHECK_FREQUENCY (2 * 1000)
#define PROTOMANGLE_SECURITYASSOC_CREATION_TIMEOUT (20 * 1000)
Referenced by ProtoMangleCreate().
Typedef Documentation
typedef enum ProtoMangleAssocStateE ProtoMangleAssocStateE
state transitions for a single security association data space
typedef struct ProtoMangleStateT ProtoMangleStateT
global protomangle state
Enumeration Type Documentation
enum ProtoMangleAssocStateE
state transitions for a single security association data space
Enumerator
PROTOMANGLE_STATE_INIT
created
PROTOMANGLE_STATE_MULTI_UNLOCK
unlocking multiplayer capability is in progress
PROTOMANGLE_STATE_CREATING
establishment of the security association is in progress (locally-initiated)
PROTOMANGLE_STATE_LISTENING
establishment of the security association is in progress (remotely-initiated)
PROTOMANGLE_STATE_DONE
successful secure address resolution completion
PROTOMANGLE_STATE_FAILED
secure address resolution failed
PROTOMANGLE_STATE_TIMEDOUT
secure address resolution timedout
PROTOMANGLE_STATE_CLEANING
releasing allocated resources (includes async destroy if needed) - this state can only be reached when entry is in kill list
Function Documentation
void _ProtoMangleIncomingAssociationEventHandler (ProtoMangleRefT * pRef, SecureDeviceAssociation^ refSecurityAssociation)
Event handler (delegate) registered for incoming association events.
Parameters
*pRef - pointer to module state
^refSecurityAssociation - winrt reference to security association being notified
Version
10/29/2013 (mclouatre)
References ProtoMangleRefT::iVerbose, NetPrintfVerbose, and ProtoMangleRefT::refIncomingSecurityAssocVect.
void _ProtoMangleProcessIncomingSAs (ProtoMangleRefT * pRef)
Process the queue of incoming secure device associations.
Parameters
*pRef - pointer to module state
Version
09/06/2014 (mclouatre)
References ProtoMangleRefT::aClients, ProtoMangleSecurityAssocT::eMangleState, ProtoMangleSecurityAssocT::iIpv4Addr, ProtoMangleRefT::iMaxClients, ProtoMangleRefT::iVerbose, NetPrintf, NetPrintfVerbose, ProtoMangleClientT::pAssoc, PROTOMANGLE_STATE_DONE, PROTOMANGLE_STATE_LISTENING, ProtoMangleRefT::refIncomingSecurityAssocVect, ProtoMangleSecurityAssocT::refSecureDeviceAddr, ProtoMangleSecurityAssocT::refSecurityAssociation, and ProtoMangleSecurityAssocT::remoteSocketAddress.
Referenced by ProtoMangleUpdate().
const char* ProtoMangleFindTemplate (char * pStrTemplateName, int32_t iTemplateNameSize, int32_t iLocalPort, int32_t iRemotePort, uint8_t bTcp, int32_t iVerbose)
Find template suitable for given query, based on protocol, local port, and remote port.
Parameters
*pStrTemplateName- [out] buffer to store template name in
iTemplateNameSize- size of template name buffer
iLocalPort - local (bound) port to check template for
iRemotePort - remote (connect) port to check template for
bTcp - TRUE if TCP, else UDP
iVerbose - debug level
Returns
const char * - template name, or NULL if not found
Version
09/12/2013 (jbrookes)
References DirtyErrGetName(), ds_snzprintf(), NetPrintf, and NetPrintfVerbose.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:34:34