DirtySock: voipheadsetxenon.cpp File Reference
voipheadsetxenon.cpp File Reference
VoIP headset manager.
#include <xtl.h>
#include <xonline.h>
#include <xaudio2.h>
#include <xhv2.h>
#include "DirtySDK/platform.h"
#include "DirtySDK/dirtysock.h"
#include "DirtySDK/dirtysock/dirtymem.h"
#include "DirtySDK/dirtysock/dirtyerr.h"
#include "DirtySDK/voip/voipdef.h"
#include "voippriv.h"
#include "voipconnection.h"
#include "voipheadset.h"
Data Structures
struct VoipHeadsetRefT
voip headset module state data
Macros
#define VOIP_XHV_DEBUG (DIRTYCODE_DEBUG && FALSE)
Functions
VoipHeadsetRefT * VoipHeadsetCreate (int32_t iMaxChannels, int32_t iMaxLocal, VoipHeadsetMicDataCbT *pMicDataCb, VoipHeadsetStatusCbT *pStatusCb, void *pCbUserData, int32_t iData)
Create the headset manager.
void VoipHeadsetDestroy (VoipHeadsetRefT *pHeadset)
Destroy the headset manager.
void VoipHeadsetReceiveVoiceDataCb (VoipUserT *pRemoteUsers, VoipMicrInfoT *pMicrInfo, uint8_t *pPacketData, void *pUserData)
Connectionlist callback to handle receiving a voice packet from a remote peer.
void VoipHeadsetRegisterUserCb (VoipUserT *pRemoteUser, uint32_t bRegister, void *pUserData)
Connectionlist callback to register/unregister a new user with the XHV Engine.
void VoipHeadsetProcess (VoipHeadsetRefT *pHeadset, uint32_t uFrameCount)
Headset process function.
void VoipHeadsetSetMicStatus (VoipHeadsetRefT *pHeadset, uint32_t bMicOn)
Enable or disable the mic.
int32_t VoipHeadsetControl (VoipHeadsetRefT *pHeadset, int32_t iControl, int32_t iValue, int32_t iValue2, void *pValue)
Control function.
int32_t VoipHeadsetStatus (VoipHeadsetRefT *pHeadset, int32_t iSelect, int32_t iValue, void *pBuf, int32_t iBufSize)
Status function.
void VoipHeadsetSpkrCallback (VoipHeadsetRefT *pHeadset, VoipSpkrCallbackT *pCallback, void *pUserData)
Set speaker output callback.
Detailed Description
VoIP headset manager.
Attention
Copyright (c) 2009 Electronic Arts Inc.
Version
11/10/2009 (jbrookes) Split from voipxenon.cpp
Macro Definition Documentation
#define VOIP_XHV_DEBUG (DIRTYCODE_DEBUG && FALSE)
Function Documentation
int32_t VoipHeadsetControl (VoipHeadsetRefT * pHeadset, int32_t iControl, int32_t iValue, int32_t iValue2, void * pValue)
Control function.
Parameters
*pHeadset - headset module state
iControl - control selector
iValue - control value
iValue2 - control value
*pValue - control value
Returns
int32_t - selector specific, or -1 if no such selector
Note
iControl can be one of the following:
        'mrdr' - set raw data ready callback (must be called before VoipStartup()) - iValue=pCallback
        'prio' - set playback priority for user; pValue=VoipUserT, iValue=port, iValue2=enable/disable
        'rloc' - un/register local talker; iValue=port, iValue2=enable/disable, pValue=VoipUserT (not required for unregistration)
Version
11/10/2009 (jbrookes)
References NetPrintf, VoipHeadsetRefT::pXHVEngine, and VoipXuidFromUser().
Referenced by VoipCommonControl(), and VoipControl().
VoipHeadsetRefT* VoipHeadsetCreate (int32_t iMaxChannels, int32_t iMaxLocal, VoipHeadsetMicDataCbT * pMicDataCb, VoipHeadsetStatusCbT * pStatusCb, void * pCbUserData, int32_t iData)
Create the headset manager.
Parameters
iMaxChannels - max number of remote users
iMaxLocal - max number of local users
*pMicDataCb - pointer to user callback to trigger when mic data is ready
*pStatusCb - pointer to user callback to trigger when headset status changes
*pCbUserData - pointer to user callback data
iData - platform-specific - Xbox360 hardware thread to pass to XAudio2Create() (user 0 for default)
Returns
VoipHeadsetRefT* - NULL=failure; else pointer to VoipHeadset ref
Note
        Valid value range for iProcessor:
        0                           - use default, i.e. XAUDIO2_DEFAULT_PROCESSOR
        XboxThread0                 - value 0x01
        XboxThread1                 - value 0x02
        XboxThread2                 - value 0x04
        XboxThread3                 - value 0x08
        XboxThread4                 - value 0x10
        XboxThread5                 - value 0x20
        XAUDIO2_ANY_PROCESSOR       - value 0x3f
        XAUDIO2_DEFAULT_PROCESSOR   - (XboxThread4|XboxThread5)
Version
11/10/2009 (jbrookes)
References DirtyMemAlloc(), VoipHeadsetRefT::iMaxChannels, NetPrintf, NULL, VoipHeadsetRefT::pCbUserData, VoipHeadsetRefT::pMicDataCb, VoipHeadsetRefT::pStatusCb, VOIP_MAXCONNECT, VOIP_MEMID, VoipHeadsetDestroy(), and VoipMemGroupQuery().
Referenced by VoipCommonStartup().
void VoipHeadsetDestroy (VoipHeadsetRefT * pHeadset)
Destroy the headset manager.
Parameters
*pHeadset - pointer to headset state
Version
11/10/2009 (jbrookes)
References DirtyMemFree(), VoipHeadsetRefT::LocalUsers, NULL, VoipHeadsetRefT::pXAudio2, VoipHeadsetRefT::pXHVEngine, VOIP_MEMID, and VoipMemGroupQuery().
Referenced by VoipCommonShutdown(), and VoipHeadsetCreate().
void VoipHeadsetProcess (VoipHeadsetRefT * pHeadset, uint32_t uFrameCount)
Headset process function.
Parameters
*pHeadset - pointer to headset state
uFrameCount - current frame count
Version
11/10/2009 (jbrookes)
void VoipHeadsetReceiveVoiceDataCb (VoipUserT * pRemoteUsers, VoipMicrInfoT * pMicrInfo, uint8_t * pPacketData, void * pUserData)
Connectionlist callback to handle receiving a voice packet from a remote peer.
Parameters
*pRemoteUsers - user we're receiving the voice data from
*pMicrInfo - micr info from inbound packet
*pPacketData - pointer to beginning of data in packet payload
*pUserData - VoipHeadsetT ref
Version
11/10/2009 (jbrookes)
References VoipMicrInfoT::uNumSubPackets, VoipMicrInfoT::uSubPacketSize, and VoipMicrInfoT::uUserIndex.
Referenced by VoipCommonStartup().
void VoipHeadsetRegisterUserCb (VoipUserT * pRemoteUser, uint32_t bRegister, void * pUserData)
Connectionlist callback to register/unregister a new user with the XHV Engine.
Parameters
*pRemoteUser - user to register
bRegister - true=register, false=unregister
*pUserData - voipheadset module ref
Version
11/10/2009 (jbrookes)
Referenced by VoipCommonStartup().
void VoipHeadsetSetMicStatus (VoipHeadsetRefT * pHeadset, uint32_t bMicOn)
Enable or disable the mic.
Parameters
*pHeadset - pointer to headset state
bMicOn - TRUE to enable mic, else FALSE to disable it.
Version
11/10/2009 (jbrookes)
void VoipHeadsetSpkrCallback (VoipHeadsetRefT * pHeadset, VoipSpkrCallbackT * pCallback, void * pUserData)
Set speaker output callback.
Parameters
*pHeadset - headset module state
*pCallback - what to call when output data is available
*pUserData - user data for callback
Version
11/10/2009 (jbrookes)
Referenced by VoipSpkrCallback().
int32_t VoipHeadsetStatus (VoipHeadsetRefT * pHeadset, int32_t iSelect, int32_t iValue, void * pBuf, int32_t iBufSize)
Status function.
Parameters
*pHeadset - headset module state
iSelect - control selector
iValue - selector specific
pBuf - buffer pointer
iBufSize - buffer size
Returns
int32_t - selector specific, or -1 if no such selector
Note
iSelect can be one of the following:
Version
11/10/2009 (jbrookes)
Referenced by VoipCommonStatus().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:55