DirtySock: NetGameUtil
NetGameUtil
Game
Macros
#define NETGAME_CONN_LISTEN (1)
listen for connect
#define NETGAME_CONN_CONNECT (2)
connect to peer
#define NETGAME_CONN_AUTO (NETGAME_CONN_LISTEN|NETGAME_CONN_CONNECT)
(debug only) autoconnect
Typedefs
typedef struct NetGameUtilRefT NetGameUtilRefT
Functions
DIRTYCODE_API NetGameUtilRefT * NetGameUtilCreate (void)
Construct the game setup module.
DIRTYCODE_API void NetGameUtilDestroy (NetGameUtilRefT *ref)
Destroy the game setup module.
DIRTYCODE_API void NetGameUtilReset (NetGameUtilRefT *ref)
Reset the game setup module.
DIRTYCODE_API void NetGameUtilControl (NetGameUtilRefT *pRef, int32_t iKind, int32_t iValue)
Set internal GameUtil parameters.
DIRTYCODE_API int32_t NetGameUtilConnect (NetGameUtilRefT *ref, int32_t conn, const char *addr, CommAllConstructT *pConstruct)
Establish a connection (connect/listen)
DIRTYCODE_API void * NetGameUtilComplete (NetGameUtilRefT *ref)
Check for connection complete.
DIRTYCODE_API int32_t NetGameUtilStatus (NetGameUtilRefT *ref, int32_t iSelect, void *pBuf, int32_t iBufSize)
Return status info.
DIRTYCODE_API void NetGameUtilAdvert (NetGameUtilRefT *ref, const char *kind, const char *name, const char *note)
Send out an advertisement.
DIRTYCODE_API void NetGameUtilWithdraw (NetGameUtilRefT *ref, const char *kind, const char *name)
Withdraw given advertisement.
DIRTYCODE_API uint32_t NetGameUtilLocate (NetGameUtilRefT *ref, const char *kind, const char *name)
Find ip address of a specific advertisement.
DIRTYCODE_API int32_t NetGameUtilQuery (NetGameUtilRefT *ref, const char *kind, char *buf, int32_t max)
Return a list of all advertisements.
Detailed Description
Macro Definition Documentation
#define NETGAME_CONN_AUTO (NETGAME_CONN_LISTEN|NETGAME_CONN_CONNECT)
(debug only) autoconnect
Referenced by NetGameUtilConnect().
#define NETGAME_CONN_CONNECT (2)
connect to peer
Referenced by NetGameUtilComplete(), and NetGameUtilConnect().
#define NETGAME_CONN_LISTEN (1)
listen for connect
Referenced by NetGameUtilComplete(), and NetGameUtilConnect().
Typedef Documentation
typedef struct NetGameUtilRefT NetGameUtilRefT
Function Documentation
DIRTYCODE_API void NetGameUtilAdvert (NetGameUtilRefT * ref, const char * kind, const char * name, const char * note)
Send out an advertisement.
Parameters
*ref - reference pointer
*kind - class (unique to app)
*name - name to broadcast
*note - notes
Version
01/09/01 (GWS)
References NetGameUtilRefT::advt, NetGameUtilRefT::advtfreq, ds_strnzcpy(), NetGameUtilRefT::kind, and ProtoAdvtAnnounce().
Referenced by ConnApiOnline().
DIRTYCODE_API void* NetGameUtilComplete (NetGameUtilRefT * ref)
Check for connection complete.
Parameters
*ref - reference pointer
Returns
void * - connection pointer (NULL is no connection)
Version
01/09/01 (GWS)
References NetGameUtilRefT::addr, NetGameUtilRefT::advt, NetGameUtilRefT::comm, COMM_ONLINE, ds_snzprintf(), ds_strnzcpy(), NetGameUtilRefT::find, NetGameUtilRefT::hostip, NETGAME_CONN_CONNECT, NETGAME_CONN_LISTEN, NetGameUtilConnect(), NetPrintf, NetGameUtilRefT::pConstruct, NetGameUtilRefT::peerip, CommRef::peerip, NetGameUtilRefT::peerport, CommRef::peerport, ProtoAdvtDestroy(), ProtoAdvtLocate(), and CommRef::Status.
DIRTYCODE_API int32_t NetGameUtilConnect (NetGameUtilRefT * ref, int32_t conn, const char * addr, CommAllConstructT * pConstruct)
Establish a connection (connect/listen)
Parameters
*ref - reference pointer
conn - connect mode (NETGAME_CONN_*) | comm type (NETGAME_CONN_*)
*addr - service address list
*pConstruct - comm construct function
Returns
int32_t - zero=success, negative=failure (COMM_* error code)
Version
01/09/01 (GWS)
References NetGameUtilRefT::addr, NetGameUtilRefT::clientid, NetGameUtilRefT::comm, CommRef::Connect, CommRef::Control, CommRef::Destroy, DirtyMemGroupEnter(), DirtyMemGroupLeave(), ds_strnzcpy(), NetGameUtilRefT::find, NetGameUtilRefT::hosting, NetGameUtilRefT::hostip, CommRef::hostip, NetGameUtilRefT::hostport, CommRef::hostport, CommRef::Listen, NetGameUtilRefT::maxinp, NetGameUtilRefT::maxout, NetGameUtilRefT::maxwid, NetGameUtilRefT::memgroup, NetGameUtilRefT::memgrpusrdata, NetGameUtilRefT::metatype, NETGAME_CONN_AUTO, NETGAME_CONN_CONNECT, NETGAME_CONN_LISTEN, NetPrintf, NetGameUtilRefT::pConstruct, ProtoAdvtAnnounce(), NetGameUtilRefT::pSocket, NetGameUtilRefT::rclientid, CommRef::sockptr, and NetGameUtilRefT::unacklimit.
Referenced by NetGameUtilComplete().
DIRTYCODE_API void NetGameUtilControl (NetGameUtilRefT * pRef, int32_t iKind, int32_t iValue)
Set internal GameUtil parameters.
Parameters
*pRef - reference pointer
iKind - selector
iValue - value to set
Note
Selectors:
        'advf': set advertising frequency, in seconds (call before calling NetGameUtilAdvert)
        'clid': set client identifier* (for use with gameservers)
        'locl': enable or disable query of local adverts
        'meta': set metatype (default=0)
        'minp': set receive buffer size, in packets*
        'mout': set send buffer size, in packets*
        'mwid': set maximum packet width (must be <= NETGAME_MAXPACKETSIZE)*
            * must be set before NetGameLinkConnect() is called to be effective.
Version
11/12/03 (JLB)
References NetGameUtilRefT::advtfreq, NetGameUtilRefT::clientid, NetGameUtilRefT::comm, CommRef::Control, NetGameUtilRefT::maxinp, NetGameUtilRefT::maxout, NetGameUtilRefT::maxwid, NetGameUtilRefT::metatype, NETGAME_DATAPKT_MAXSIZE, NETGAME_DATAPKT_MAXTAIL, NetPrintf, NetGameUtilRefT::rclientid, NetGameUtilRefT::uLocalAdvt, and NetGameUtilRefT::unacklimit.
Referenced by LobbyLanControl(), and NetGameUtilCreate().
DIRTYCODE_API NetGameUtilRefT* NetGameUtilCreate (void)
Construct the game setup module.
Returns
NetGameUtilRefT * - reference pointer
Version
01/09/01 (GWS)
References DirtyMemAlloc(), DirtyMemGroupQuery(), NetGameUtilRefT::memgroup, NetGameUtilRefT::memgrpusrdata, NETGAME_DATABUF_MAXSIZE, NETGAME_DATAPKT_DEFSIZE, NETGAMEUTIL_MEMID, NetGameUtilControl(), NetPrintf, and pRef.
Referenced by ConnApiOnline().
DIRTYCODE_API void NetGameUtilDestroy (NetGameUtilRefT * ref)
Destroy the game setup module.
Parameters
*ref - reference pointer
Version
01/09/01 (GWS)
References DirtyMemFree(), NetGameUtilRefT::memgroup, NetGameUtilRefT::memgrpusrdata, NETGAMEUTIL_MEMID, and NetGameUtilReset().
Referenced by ConnApiControl(), and ConnApiDestroy().
DIRTYCODE_API uint32_t NetGameUtilLocate (NetGameUtilRefT * ref, const char * kind, const char * name)
Find ip address of a specific advertisement.
Parameters
*ref - reference pointer
*kind - class (unique to app)
*name - advertisement to look for
Returns
uint32_t - ip address of advertiser or zero if no match
Version
01/09/01 (GWS)
References NetGameUtilRefT::advt, NetGameUtilRefT::kind, and ProtoAdvtLocate().
DIRTYCODE_API int32_t NetGameUtilQuery (NetGameUtilRefT * ref, const char * kind, char * buf, int32_t max)
Return a list of all advertisements.
Parameters
*ref - reference pointer
*kind - class (unique to app)
*buf - target buffer
max - target buffer length
Returns
int32_t - number of matching ads
Version
01/09/01 (GWS)
References NetGameUtilRefT::advt, NetGameUtilRefT::kind, ProtoAdvtQuery(), and NetGameUtilRefT::uLocalAdvt.
DIRTYCODE_API void NetGameUtilReset (NetGameUtilRefT * ref)
Reset the game setup module.
Parameters
*ref - reference pointer
Version
01/09/01 (GWS)
References NetGameUtilRefT::advt, NetGameUtilRefT::comm, CommRef::Destroy, NetGameUtilRefT::find, NetGameUtilRefT::pConstruct, and ProtoAdvtDestroy().
Referenced by LobbyLanReset(), LobbyLanStartGame(), and NetGameUtilDestroy().
DIRTYCODE_API int32_t NetGameUtilStatus (NetGameUtilRefT * ref, int32_t iSelect, void * pBuf, int32_t iBufSize)
Return status info.
Parameters
*ref - reference pointer
iSelect - info selector
*pBuf - [out] output buffer
iBufSize - size of output buffer
Returns
int32_t - status info
Note
iSelect can be one of the following:
        'host' - TRUE if hosting, else FALSE
        'join' - TRUE if joining, else FALSE
        'hoip' - host ip
        'hprt' - host port
        'peip' - peer ip
        'pprt' - peer port
        'pkrc' - packet received
        'sock' - SocketT socket pointer (in pBuf)
Version
01/09/01 (GWS)
References CommRef::bpackrcvd, NetGameUtilRefT::comm, ds_memcpy(), NetGameUtilRefT::hosting, NetGameUtilRefT::hostip, NetGameUtilRefT::hostport, NetGameUtilRefT::peerip, NetGameUtilRefT::peerport, and NetGameUtilRefT::pSocket.
Referenced by ConnApiStatus2().
DIRTYCODE_API void NetGameUtilWithdraw (NetGameUtilRefT * ref, const char * kind, const char * name)
Withdraw given advertisement.
Parameters
*ref - reference pointer
*kind - advert kind
*name - advert name
Version
01/09/01 (GWS)
References NetGameUtilRefT::advt, and ProtoAdvtCancel().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:49