//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 

namespace EA.PackageSystem.PackageCore.Services
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "WebServiceSoap", Namespace = "http://EATechNet.MOSS.Packages.Services/")]
    public partial class WebServices : System.Web.Services.Protocols.SoapHttpClientProtocol
    {
        private System.Threading.SendOrPostCallback GetReleaseOperationCompleted;

        private System.Threading.SendOrPostCallback GetPackageOperationCompleted;

        private System.Threading.SendOrPostCallback GetPackageReleasesOperationCompleted;

        private System.Threading.SendOrPostCallback GetReleaseDependentsOperationCompleted;

        private System.Threading.SendOrPostCallback GetAllPackagesOperationCompleted;

        private System.Threading.SendOrPostCallback GetAllReleasesOperationCompleted;

        private System.Threading.SendOrPostCallback PostPackageOperationCompleted;

        /// <remarks/>
        public WebServices()
        {
            string urlSetting = System.Configuration.ConfigurationManager.AppSettings["WebServiceURL"];
            if ((urlSetting != null))
            {
                this.Url = urlSetting;
            }
            else
            {
                this.Url = "http://packages.ea.com/webservice.asmx";
            }
        }

        /// <remarks/>
        public event GetReleaseCompletedEventHandler GetReleaseCompleted;

        /// <remarks/>
        public event GetPackageCompletedEventHandler GetPackageCompleted;

        /// <remarks/>
        public event GetPackageReleasesCompletedEventHandler GetPackageReleasesCompleted;

        /// <remarks/>
        public event GetReleaseDependentsCompletedEventHandler GetReleaseDependentsCompleted;

        /// <remarks/>
        public event GetAllPackagesCompletedEventHandler GetAllPackagesCompleted;

        /// <remarks/>
        public event GetAllReleasesCompletedEventHandler GetAllReleasesCompleted;

        /// <remarks/>
        public event PostPackageCompletedEventHandler PostPackageCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://EATechNet.MOSS.Packages.Services/GetRelease", RequestNamespace = "http://EATechNet.MOSS.Packages.Services/", ResponseNamespace = "http://EATechNet.MOSS.Packages.Services/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Release GetRelease(string name, string version)
        {
            object[] results = this.Invoke("GetRelease", new object[] {
                    name,
                    version});
            return ((Release)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetRelease(string name, string version, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetRelease", new object[] {
                    name,
                    version}, callback, asyncState);
        }

        /// <remarks/>
        public Release EndGetRelease(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((Release)(results[0]));
        }

        /// <remarks/>
        public void GetReleaseAsync(string name, string version)
        {
            this.GetReleaseAsync(name, version, null);
        }

        /// <remarks/>
        public void GetReleaseAsync(string name, string version, object userState)
        {
            if ((this.GetReleaseOperationCompleted == null))
            {
                this.GetReleaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReleaseOperationCompleted);
            }
            this.InvokeAsync("GetRelease", new object[] {
                    name,
                    version}, this.GetReleaseOperationCompleted, userState);
        }

        private void OnGetReleaseOperationCompleted(object arg)
        {
            if ((this.GetReleaseCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReleaseCompleted(this, new GetReleaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://EATechNet.MOSS.Packages.Services/GetPackage", RequestNamespace = "http://EATechNet.MOSS.Packages.Services/", ResponseNamespace = "http://EATechNet.MOSS.Packages.Services/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Package GetPackage(string name)
        {
            object[] results = this.Invoke("GetPackage", new object[] {
                    name});
            return ((Package)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetPackage(string name, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetPackage", new object[] {
                    name}, callback, asyncState);
        }

        /// <remarks/>
        public Package EndGetPackage(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((Package)(results[0]));
        }

        /// <remarks/>
        public void GetPackageAsync(string name)
        {
            this.GetPackageAsync(name, null);
        }

        /// <remarks/>
        public void GetPackageAsync(string name, object userState)
        {
            if ((this.GetPackageOperationCompleted == null))
            {
                this.GetPackageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPackageOperationCompleted);
            }
            this.InvokeAsync("GetPackage", new object[] {
                    name}, this.GetPackageOperationCompleted, userState);
        }

        private void OnGetPackageOperationCompleted(object arg)
        {
            if ((this.GetPackageCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPackageCompleted(this, new GetPackageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://EATechNet.MOSS.Packages.Services/GetPackageReleases", RequestNamespace = "http://EATechNet.MOSS.Packages.Services/", ResponseNamespace = "http://EATechNet.MOSS.Packages.Services/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Release[] GetPackageReleases(string name)
        {
            object[] results = this.Invoke("GetPackageReleases", new object[] {
                    name});
            return ((Release[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetPackageReleases(string name, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetPackageReleases", new object[] {
                    name}, callback, asyncState);
        }

        /// <remarks/>
        public Release[] EndGetPackageReleases(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((Release[])(results[0]));
        }

        /// <remarks/>
        public void GetPackageReleasesAsync(string name)
        {
            this.GetPackageReleasesAsync(name, null);
        }

        /// <remarks/>
        public void GetPackageReleasesAsync(string name, object userState)
        {
            if ((this.GetPackageReleasesOperationCompleted == null))
            {
                this.GetPackageReleasesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPackageReleasesOperationCompleted);
            }
            this.InvokeAsync("GetPackageReleases", new object[] {
                    name}, this.GetPackageReleasesOperationCompleted, userState);
        }

        private void OnGetPackageReleasesOperationCompleted(object arg)
        {
            if ((this.GetPackageReleasesCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPackageReleasesCompleted(this, new GetPackageReleasesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://EATechNet.MOSS.Packages.Services/GetReleaseDependents", RequestNamespace = "http://EATechNet.MOSS.Packages.Services/", ResponseNamespace = "http://EATechNet.MOSS.Packages.Services/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Release[] GetReleaseDependents(string name, string version)
        {
            object[] results = this.Invoke("GetReleaseDependents", new object[] {
                    name,
                    version});
            return ((Release[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetReleaseDependents(string name, string version, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetReleaseDependents", new object[] {
                    name,
                    version}, callback, asyncState);
        }

        /// <remarks/>
        public Release[] EndGetReleaseDependents(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((Release[])(results[0]));
        }

        /// <remarks/>
        public void GetReleaseDependentsAsync(string name, string version)
        {
            this.GetReleaseDependentsAsync(name, version, null);
        }

        /// <remarks/>
        public void GetReleaseDependentsAsync(string name, string version, object userState)
        {
            if ((this.GetReleaseDependentsOperationCompleted == null))
            {
                this.GetReleaseDependentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReleaseDependentsOperationCompleted);
            }
            this.InvokeAsync("GetReleaseDependents", new object[] {
                    name,
                    version}, this.GetReleaseDependentsOperationCompleted, userState);
        }

        private void OnGetReleaseDependentsOperationCompleted(object arg)
        {
            if ((this.GetReleaseDependentsCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReleaseDependentsCompleted(this, new GetReleaseDependentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://EATechNet.MOSS.Packages.Services/GetAllPackages", RequestNamespace = "http://EATechNet.MOSS.Packages.Services/", ResponseNamespace = "http://EATechNet.MOSS.Packages.Services/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Package[] GetAllPackages()
        {
            object[] results = this.Invoke("GetAllPackages", new object[0]);
            return ((Package[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetAllPackages(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetAllPackages", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public Package[] EndGetAllPackages(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((Package[])(results[0]));
        }

        /// <remarks/>
        public void GetAllPackagesAsync()
        {
            this.GetAllPackagesAsync(null);
        }

        /// <remarks/>
        public void GetAllPackagesAsync(object userState)
        {
            if ((this.GetAllPackagesOperationCompleted == null))
            {
                this.GetAllPackagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllPackagesOperationCompleted);
            }
            this.InvokeAsync("GetAllPackages", new object[0], this.GetAllPackagesOperationCompleted, userState);
        }

        private void OnGetAllPackagesOperationCompleted(object arg)
        {
            if ((this.GetAllPackagesCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllPackagesCompleted(this, new GetAllPackagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://EATechNet.MOSS.Packages.Services/GetAllReleases", RequestNamespace = "http://EATechNet.MOSS.Packages.Services/", ResponseNamespace = "http://EATechNet.MOSS.Packages.Services/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Release[] GetAllReleases()
        {
            object[] results = this.Invoke("GetAllReleases", new object[0]);
            return ((Release[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetAllReleases(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetAllReleases", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public Release[] EndGetAllReleases(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((Release[])(results[0]));
        }

        /// <remarks/>
        public void GetAllReleasesAsync()
        {
            this.GetAllReleasesAsync(null);
        }

        /// <remarks/>
        public void GetAllReleasesAsync(object userState)
        {
            if ((this.GetAllReleasesOperationCompleted == null))
            {
                this.GetAllReleasesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllReleasesOperationCompleted);
            }
            this.InvokeAsync("GetAllReleases", new object[0], this.GetAllReleasesOperationCompleted, userState);
        }

        private void OnGetAllReleasesOperationCompleted(object arg)
        {
            if ((this.GetAllReleasesCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllReleasesCompleted(this, new GetAllReleasesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://EATechNet.MOSS.Packages.Services/PostPackage", RequestNamespace = "http://EATechNet.MOSS.Packages.Services/", ResponseNamespace = "http://EATechNet.MOSS.Packages.Services/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PostPackage(string fileName, string uncName, string changes, int statusId, string statusComment, string requiredReleases)
        {
            object[] results = this.Invoke("PostPackage", new object[] {
                    fileName,
                    uncName,
                    changes,
                    statusId,
                    statusComment,
                    requiredReleases});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginPostPackage(string fileName, string uncName, string changes, int statusId, string statusComment, string requiredReleases, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("PostPackage", new object[] {
                    fileName,
                    uncName,
                    changes,
                    statusId,
                    statusComment,
                    requiredReleases}, callback, asyncState);
        }

        /// <remarks/>
        public string EndPostPackage(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void PostPackageAsync(string fileName, string uncName, string changes, int statusId, string statusComment, string requiredReleases)
        {
            this.PostPackageAsync(fileName, uncName, changes, statusId, statusComment, requiredReleases, null);
        }

        /// <remarks/>
        public void PostPackageAsync(string fileName, string uncName, string changes, int statusId, string statusComment, string requiredReleases, object userState)
        {
            if ((this.PostPackageOperationCompleted == null))
            {
                this.PostPackageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostPackageOperationCompleted);
            }
            this.InvokeAsync("PostPackage", new object[] {
                    fileName,
                    uncName,
                    changes,
                    statusId,
                    statusComment,
                    requiredReleases}, this.PostPackageOperationCompleted, userState);
        }

        private void OnPostPackageOperationCompleted(object arg)
        {
            if ((this.PostPackageCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostPackageCompleted(this, new PostPackageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://EATechNet.MOSS.Packages.Services/")]
    public partial class Release
    {

        private int releaseIdField;

        private int packageIdField;

        private int frameworkVersionField;

        private string versionField;

        private string changesField;

        private string fileNameExtensionField;

        private int statusIdField;

        private string statusCommentField;

        private System.DateTime dateCreatedField;

        private string documentationUrlField;

        private string postNameField;

        private string postEmailField;

        private string nameField;

        private string summaryField;

        private string descriptionField;

        private string contactNameField;

        private string contactEmailField;

        private string licenseNameField;

        private int licenseSortOrderField;

        private string licenseCommentField;

        private string statusNameField;

        private int statusSortOrderField;

        private string releaseUrlField;

        private string packageUrlField;

        private string installUrlField;

        /// <remarks/>
        public int ReleaseId
        {
            get
            {
                return this.releaseIdField;
            }
            set
            {
                this.releaseIdField = value;
            }
        }

        /// <remarks/>
        public int PackageId
        {
            get
            {
                return this.packageIdField;
            }
            set
            {
                this.packageIdField = value;
            }
        }

        /// <remarks/>
        public int FrameworkVersion
        {
            get
            {
                return this.frameworkVersionField;
            }
            set
            {
                this.frameworkVersionField = value;
            }
        }

        /// <remarks/>
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        public string Changes
        {
            get
            {
                return this.changesField;
            }
            set
            {
                this.changesField = value;
            }
        }

        /// <remarks/>
        public string FileNameExtension
        {
            get
            {
                return this.fileNameExtensionField;
            }
            set
            {
                this.fileNameExtensionField = value;
            }
        }

        /// <remarks/>
        public int StatusId
        {
            get
            {
                return this.statusIdField;
            }
            set
            {
                this.statusIdField = value;
            }
        }

        /// <remarks/>
        public string StatusComment
        {
            get
            {
                return this.statusCommentField;
            }
            set
            {
                this.statusCommentField = value;
            }
        }

        /// <remarks/>
        public System.DateTime DateCreated
        {
            get
            {
                return this.dateCreatedField;
            }
            set
            {
                this.dateCreatedField = value;
            }
        }

        /// <remarks/>
        public string DocumentationUrl
        {
            get
            {
                return this.documentationUrlField;
            }
            set
            {
                this.documentationUrlField = value;
            }
        }

        /// <remarks/>
        public string PostName
        {
            get
            {
                return this.postNameField;
            }
            set
            {
                this.postNameField = value;
            }
        }

        /// <remarks/>
        public string PostEmail
        {
            get
            {
                return this.postEmailField;
            }
            set
            {
                this.postEmailField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Summary
        {
            get
            {
                return this.summaryField;
            }
            set
            {
                this.summaryField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string ContactName
        {
            get
            {
                return this.contactNameField;
            }
            set
            {
                this.contactNameField = value;
            }
        }

        /// <remarks/>
        public string ContactEmail
        {
            get
            {
                return this.contactEmailField;
            }
            set
            {
                this.contactEmailField = value;
            }
        }

        /// <remarks/>
        public string LicenseName
        {
            get
            {
                return this.licenseNameField;
            }
            set
            {
                this.licenseNameField = value;
            }
        }

        /// <remarks/>
        public int LicenseSortOrder
        {
            get
            {
                return this.licenseSortOrderField;
            }
            set
            {
                this.licenseSortOrderField = value;
            }
        }

        /// <remarks/>
        public string LicenseComment
        {
            get
            {
                return this.licenseCommentField;
            }
            set
            {
                this.licenseCommentField = value;
            }
        }

        /// <remarks/>
        public string StatusName
        {
            get
            {
                return this.statusNameField;
            }
            set
            {
                this.statusNameField = value;
            }
        }

        /// <remarks/>
        public int StatusSortOrder
        {
            get
            {
                return this.statusSortOrderField;
            }
            set
            {
                this.statusSortOrderField = value;
            }
        }

        /// <remarks/>
        public string ReleaseUrl
        {
            get
            {
                return this.releaseUrlField;
            }
            set
            {
                this.releaseUrlField = value;
            }
        }

        /// <remarks/>
        public string PackageUrl
        {
            get
            {
                return this.packageUrlField;
            }
            set
            {
                this.packageUrlField = value;
            }
        }

        /// <remarks/>
        public string InstallUrl
        {
            get
            {
                return this.installUrlField;
            }
            set
            {
                this.installUrlField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://EATechNet.MOSS.Packages.Services/")]
    public partial class Package
    {

        private int packageIdField;

        private string summaryField;

        private string nameField;

        private string descriptionField;

        private string contactNameField;

        private string contactEmailField;

        private int licenseIdField;

        private string licenseCommentField;

        private string homePageUrlField;

        private string packageUrlField;

        private System.DateTime dateCreatedField;

        private int licenseSortOrderField;

        private string licenseNameField;

        /// <remarks/>
        public int PackageId
        {
            get
            {
                return this.packageIdField;
            }
            set
            {
                this.packageIdField = value;
            }
        }

        /// <remarks/>
        public string Summary
        {
            get
            {
                return this.summaryField;
            }
            set
            {
                this.summaryField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string ContactName
        {
            get
            {
                return this.contactNameField;
            }
            set
            {
                this.contactNameField = value;
            }
        }

        /// <remarks/>
        public string ContactEmail
        {
            get
            {
                return this.contactEmailField;
            }
            set
            {
                this.contactEmailField = value;
            }
        }

        /// <remarks/>
        public int LicenseId
        {
            get
            {
                return this.licenseIdField;
            }
            set
            {
                this.licenseIdField = value;
            }
        }

        /// <remarks/>
        public string LicenseComment
        {
            get
            {
                return this.licenseCommentField;
            }
            set
            {
                this.licenseCommentField = value;
            }
        }

        /// <remarks/>
        public string HomePageUrl
        {
            get
            {
                return this.homePageUrlField;
            }
            set
            {
                this.homePageUrlField = value;
            }
        }

        /// <remarks/>
        public string PackageUrl
        {
            get
            {
                return this.packageUrlField;
            }
            set
            {
                this.packageUrlField = value;
            }
        }

        /// <remarks/>
        public System.DateTime DateCreated
        {
            get
            {
                return this.dateCreatedField;
            }
            set
            {
                this.dateCreatedField = value;
            }
        }

        /// <remarks/>
        public int LicenseSortOrder
        {
            get
            {
                return this.licenseSortOrderField;
            }
            set
            {
                this.licenseSortOrderField = value;
            }
        }

        /// <remarks/>
        public string LicenseName
        {
            get
            {
                return this.licenseNameField;
            }
            set
            {
                this.licenseNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetReleaseCompletedEventHandler(object sender, GetReleaseCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReleaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetReleaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Release Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Release)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetPackageCompletedEventHandler(object sender, GetPackageCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPackageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetPackageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Package Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Package)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetPackageReleasesCompletedEventHandler(object sender, GetPackageReleasesCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPackageReleasesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetPackageReleasesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Release[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Release[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetReleaseDependentsCompletedEventHandler(object sender, GetReleaseDependentsCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReleaseDependentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetReleaseDependentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Release[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Release[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetAllPackagesCompletedEventHandler(object sender, GetAllPackagesCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllPackagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetAllPackagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Package[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Package[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetAllReleasesCompletedEventHandler(object sender, GetAllReleasesCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllReleasesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetAllReleasesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Release[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Release[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void PostPackageCompletedEventHandler(object sender, PostPackageCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostPackageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal PostPackageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

}
