#
# Database migration script.  End each sql statement with a ;
[MIGRATION]

# Upgrade your schema
COMMON:

	CREATE TABLE `clubscustom_TeamSettings` (
		`clubId` BIGINT(20) UNSIGNED NOT NULL,
		`customkit1` INT(10) NOT NULL DEFAULT -1,
		`customkit1PrimaryColour` INT(10) NOT NULL DEFAULT -1,
		`customkit1SecondaryColour` INT(10) NOT NULL DEFAULT -1,
		`customkit1TertiaryColour` INT(10) NOT NULL DEFAULT -1,
		`customkit2` INT(10) NOT NULL DEFAULT -1,
		`customkit2PrimaryColour` INT(10) NOT NULL DEFAULT -1,
		`customkit2SecondaryColour` INT(10) NOT NULL DEFAULT -1,
		`customkit2TertiaryColour` INT(10) NOT NULL DEFAULT -1,
		`crestId` INT(10) NOT NULL DEFAULT -1,
		`crowdChantId` INT(10) NOT NULL DEFAULT -1,
		`commentaryId` INT(10) NOT NULL DEFAULT -1,
		`goalMusicId` INT(10) NOT NULL DEFAULT -1,
		`homeStadiumId` INT(10) NOT NULL DEFAULT -1,
		`teamBannerId` INT(10) NOT NULL DEFAULT -1,
		`pitchPatternId` INT(10) NOT NULL DEFAULT -1,
		`pitchLineColour` INT(10) NOT NULL DEFAULT -1,
		`netTensionType` INT(10) NOT NULL DEFAULT -1,
		`netShapeType` INT(10) NOT NULL DEFAULT -1,
		`netStyleType` INT(10) NOT NULL DEFAULT -1,
		`netMeshType` INT(10) NOT NULL DEFAULT -1,
		`flameThrower` INT(10) NOT NULL DEFAULT -1, 
		`extra1` INT(10) NOT NULL DEFAULT -1, 
		`extra2` INT(10) NOT NULL DEFAULT -1, 
		`extra3` INT(10) NOT NULL DEFAULT -1, 
		`extra4` INT(10) NOT NULL DEFAULT -1, 
		`extra5` INT(10) NOT NULL DEFAULT -1, 
		PRIMARY KEY (`clubId`), 
		UNIQUE (`clubId`)
	) ENGINE=InnoDB COMMENT='TeamCustomizations';

	CREATE TABLE `clubscustom_AIPlayerCustomization` (
		`clubId` BIGINT(20) UNSIGNED NOT NULL,
		`avatarId` INT(10) NOT NULL,			
		`firstname` varchar(100) DEFAULT NULL,
		`lastname` varchar(100) DEFAULT NULL,
		`commonname` varchar(100) DEFAULT NULL,
		`priority` INT(10) NOT NULL DEFAULT 0,
		`kitnumber` INT(10) NOT NULL DEFAULT 0,
		`hairtypecode` INT(10) NOT NULL DEFAULT 0,
		`haircolorcode` INT(10) NOT NULL DEFAULT 0,
		`facialhairtypecode` INT(10) NOT NULL DEFAULT 0,
		`facialhaircolorcode` INT(10) NOT NULL DEFAULT 0,
		`eyebrowcode` INT(10) NOT NULL DEFAULT 0,
		`eyecolorcode` INT(10) NOT NULL DEFAULT 0,
		`skintonecode` INT(10) NOT NULL DEFAULT 0,
		`shoetypecode` INT(10) NOT NULL DEFAULT 0,
		`shoecolorcode1` INT(10) NOT NULL DEFAULT 0,
		`shoecolorcode2` INT(10) NOT NULL DEFAULT 0,
		`shoedesigncode` INT(10) NOT NULL DEFAULT 0,
		`gkglovetypecode` INT(10) NOT NULL DEFAULT 0,
		`socklengthcode` INT(10) NOT NULL DEFAULT 0,
		`animfreekickstartposcode` INT(10) NOT NULL DEFAULT 0,
		`animpenaltiesstartposcode` INT(10) NOT NULL DEFAULT 0,
		`runstylecode` INT(10) NOT NULL DEFAULT 0,
		`runningcode1` INT(10) NOT NULL DEFAULT 0,
		`finishingcode1` INT(10) NOT NULL DEFAULT 0,
		`jerseyfit` INT(10) NOT NULL DEFAULT 0,
		`hasseasonaljersey` INT(10) NOT NULL DEFAULT 0,
		`jerseystylecode` INT(10) NOT NULL DEFAULT 0,
		`jerseysleevelengthcode` INT(10) NOT NULL DEFAULT 0,
		`year` INT(10) NOT NULL DEFAULT 1984,
		`month` INT(10) NOT NULL DEFAULT 1,
        `day` INT(10) NOT NULL DEFAULT 1,
		`accessories_code_0`INT(10) NOT NULL DEFAULT 0,	 
		`accessories_code_1`INT(10) NOT NULL DEFAULT 0,
		`accessories_code_2`INT(10) NOT NULL DEFAULT 0,
		`accessories_code_3`INT(10) NOT NULL DEFAULT 0,
		`accessories_color_0`INT(10) NOT NULL DEFAULT 0,	 
		`accessories_color_1`INT(10) NOT NULL DEFAULT 0,
		`accessories_color_2`INT(10) NOT NULL DEFAULT 0,
		`accessories_color_3`INT(10) NOT NULL DEFAULT 0,
		`tweak_preset_0` INT(10) NOT NULL DEFAULT 0,
		`tweak_a_0` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_b_0` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_c_0` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_d_0` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_e_0` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_preset_1` INT(10) NOT NULL DEFAULT 0,
		`tweak_a_1` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_b_1` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_c_1` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_d_1` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_e_1` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_preset_2` INT(10) NOT NULL DEFAULT 0,
		`tweak_a_2` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_b_2` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_c_2` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_d_2` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_e_2` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_preset_3` INT(10) NOT NULL DEFAULT 0,
		`tweak_a_3` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_b_3` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_c_3` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_d_3` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_e_3` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_preset_4` INT(10) NOT NULL DEFAULT 0,
		`tweak_a_4` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_b_4` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_c_4` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_d_4` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_e_4` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_preset_5` INT(10) NOT NULL DEFAULT 0,
		`tweak_a_5` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_b_5` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_c_5` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_d_5` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_e_5` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_preset_6` INT(10) NOT NULL DEFAULT 0,
		`tweak_a_6` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_b_6` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_c_6` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_d_6` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_e_6` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_preset_7` INT(10) NOT NULL DEFAULT 0,
		`tweak_a_7` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_b_7` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_c_7` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_d_7` FLOAT(53) NOT NULL DEFAULT 0,
		`tweak_e_7` FLOAT(53) NOT NULL DEFAULT 0,
		
		 PRIMARY KEY (`clubId`, `avatarId`)
	) ENGINE=InnoDB COMMENT='clubs AIPlayers Customization list';

	CREATE TABLE `clubscustom_Tactics` (
		`clubId` BIGINT(20) UNSIGNED NOT NULL,
		`slotId` INT(10) NOT NULL,
		`tacticsSlotData` varbinary(3072) NOT NULL,	 
		 PRIMARY KEY (`clubId`, `slotId`)
	) ENGINE=InnoDB COMMENT='clubs Tactics';
