DirtySock: XmlFormat
XmlFormat
Util
Macros
#define XML_ERR_NONE 0
#define XML_ERR_FULL -1
#define XML_ERR_UNINIT -2
#define XML_ERR_NOT_OPEN -3
#define XML_ERR_ATTR_POSITION -4
#define XML_ERR_INVALID_PARAM -5
#define XML_FL_WHITESPACE 1
Include formatting whitespace.
Functions
DIRTYCODE_API void XmlInit (char *pBuffer, int32_t iBufLen, uint8_t uFlags)
DIRTYCODE_API void XmlBufSizeIncrease (char *pBuffer, int32_t iNewBufLen)
Notify the xmlformat API that the buffer size was increased.
DIRTYCODE_API char * XmlFinish (char *pBuffer)
Signal completion of output to this buffer. Clear the XML API hidden data.
DIRTYCODE_API int32_t XmlTagStart (char *pBuffer, const char *pName)
Start an xml element (node), to which you can add other elements or attributes. Must be ended with XmlTagEnd.
DIRTYCODE_API int32_t XmlTagEnd (char *pBuffer)
End the current element or tag – must have an outstanding open tag.
DIRTYCODE_API int32_t XmlElemAddString (char *pBuffer, const char *pElemName, const char *pValue)
Add a complete, contained text element. Builds start and end tag. Nothing can be appended to this tag.
DIRTYCODE_API int32_t XmlElemAddInt (char *pBuffer, const char *pElemName, int32_t iValue)
Add a complete, contained integer element. Builds start and end tag. Nothing can be appended to this tag.
DIRTYCODE_API int32_t XmlElemAddFloat (char *pBuffer, const char *pElemName, const char *pFormatSpec, float fValue)
Add a complete, contained decimal element. Builds start and end tag. Nothing can be appended to this tag. Format it using formatSpec.
DIRTYCODE_API int32_t XmlElemAddDate (char *pBuffer, const char *pElemName, uint32_t uEpochDate)
Add a complete, contained Date element, using epoch date. Builds start and end tag. Nothing can be appended to this tag.
DIRTYCODE_API int32_t XmlAttrSetString (char *pBuffer, const char *pAttrName, const char *pValue)
Set a text attribute for an open element (started tag). Must be called before Element text is set.
DIRTYCODE_API int32_t XmlAttrSetStringRaw (char *pBuffer, const char *pAttr)
Set a text attribute for an open element (started tag) with no text encoding being performed on the input string. Must be called before Element text is set.
DIRTYCODE_API int32_t XmlAttrSetInt (char *pBuffer, const char *pAttrName, int32_t iValue)
Set an integer attribute for an open element (started tag). Must be called before Element text is set.
DIRTYCODE_API int32_t XmlAttrSetAddr (char *pBuffer, const char *pAttrName, uint32_t uAddr)
Set an IP address attribute (in dot notation)
DIRTYCODE_API int32_t XmlAttrSetFloat (char *pBuffer, const char *pAttrName, const char *pFormatSpec, float fValue)
Set a decimal attribute for an open element (started tag). Must be called before Element text is set. Format using formatSpec.
DIRTYCODE_API int32_t XmlAttrSetDate (char *pBuffer, const char *pAttrName, uint32_t uEpochDate)
Set a date attribute for an open element (started tag). Must be called before Element text is set.
DIRTYCODE_API int32_t XmlElemSetString (char *pBuffer, const char *pValue)
Set text value for an open element (started tag). Must have an open or started tag, uses element from previous start tag call. To be used if element is simple text node with some attributes.
DIRTYCODE_API int32_t XmlElemSetStringRaw (char *pBuffer, const char *pValue)
Set text value for an open element (started tag), with no encoding being performed on the input string. Must have an open or started tag, uses element from previous start tag call. To be used if element is simple text node with some attributes.
DIRTYCODE_API int32_t XmlElemSetInt (char *pBuffer, int32_t iValue)
Set integer value for an open element (started tag). Must have an open or started tag, uses element from previous start tag call. To be used if element is a simple node with some attributes.
DIRTYCODE_API int32_t XmlElemSetAddr (char *pBuffer, uint32_t uAddr)
Set an IP address value (in dot notation) for an open element¸.
DIRTYCODE_API int32_t XmlElemSetDate (char *pBuffer, uint32_t uEpoch)
Set a date for an open element. Must have an open element (started tag).
DIRTYCODE_API int32_t XmlValidate (const char *pXmlBuff, char *pErrorsBuff, int32_t iErrorsBuffLen)
Debug only function that will do simple validation of the tags. Will return count of errors found, and, errorsBuff is a output string of the errors. Returns true on Production.
DIRTYCODE_API char * XmlFormatPrintf (char *pXmlBuff, int32_t iBufLen, const char *pFormat,...)
Detailed Description
Macro Definition Documentation
#define XML_ERR_ATTR_POSITION -4
Referenced by XmlAttrSetString().
#define XML_ERR_FULL -1
Referenced by XmlAttrSetString(), XmlElemAddString(), XmlElemSetString(), XmlTagEnd(), and XmlTagStart().
#define XML_ERR_INVALID_PARAM -5
Referenced by XmlAttrSetDate(), XmlAttrSetFloat(), XmlAttrSetStringRaw(), XmlElemAddDate(), XmlElemAddFloat(), and XmlElemSetDate().
#define XML_ERR_NONE 0
#define XML_ERR_NOT_OPEN -3
Referenced by XmlAttrSetString(), XmlElemAddString(), and XmlElemSetString().
#define XML_ERR_UNINIT -2
Referenced by XmlAttrSetString(), XmlElemAddString(), XmlElemSetString(), XmlTagEnd(), and XmlTagStart().
#define XML_FL_WHITESPACE 1
Include formatting whitespace.
Referenced by XmlFormatVPrintf().
Function Documentation
DIRTYCODE_API int32_t XmlAttrSetAddr (char * pBuffer, const char * pAttrName, uint32_t uAddr)
Set an IP address attribute (in dot notation)
Parameters
*pBuffer - xml buffer.
*pAttrName - name of the attribute to be added.
uAddr - address value to be set.
Returns
int32_t - return code.
References ds_snzprintf(), and XmlAttrSetString().
Referenced by XmlFormatVPrintf().
DIRTYCODE_API int32_t XmlAttrSetDate (char * pBuffer, const char * pAttrName, uint32_t uEpochDate)
Set a date attribute for an open element (started tag). Must be called before Element text is set.
Parameters
*pBuffer - xml buffer.
*pAttrName - name of the attribute to be added.
uEpochDate - date value to be set.
Returns
int32_t - return code.
References ds_secstotime(), ds_snzprintf(), NULL, XML_ERR_INVALID_PARAM, XML_MAX_DATE_LENGTH, and XmlAttrSetString().
Referenced by XmlFormatVPrintf().
DIRTYCODE_API int32_t XmlAttrSetFloat (char * pBuffer, const char * pAttrName, const char * pFormatSpec, float fValue)
Set a decimal attribute for an open element (started tag). Must be called before Element text is set. Format using formatSpec.
Parameters
*pBuffer - xml buffer.
*pAttrName - name of the attribute (tag).
*pFormatSpec - Spec for formatting the float (see sprintf).
fValue - float value of the attribute.
Returns
int32_t - return code.
References ds_snzprintf(), XML_ERR_INVALID_PARAM, XML_MAX_FLOAT_LENGTH, and XmlAttrSetString().
DIRTYCODE_API int32_t XmlAttrSetInt (char * pBuffer, const char * pAttrName, int32_t iValue)
Set an integer attribute for an open element (started tag). Must be called before Element text is set.
Parameters
*pBuffer - xml buffer.
*pAttrName - name of the attribute to be added.
iValue - integer value to be set.
Returns
int32_t - return code.
References ds_snzprintf(), and XmlAttrSetString().
Referenced by XmlFormatVPrintf().
DIRTYCODE_API int32_t XmlAttrSetString (char * pBuffer, const char * pAttrName, const char * pValue)
Set a text attribute for an open element (started tag). Must be called before Element text is set.
Parameters
*pBuffer - xml buffer.
*pAttrName - name of the attribute to be added.
*pValue - string value of the element.
Returns
int32_t - return code.
References ds_snzprintf(), XML_ERR_ATTR_POSITION, XML_ERR_FULL, XML_ERR_NOT_OPEN, and XML_ERR_UNINIT.
Referenced by XmlAttrSetAddr(), XmlAttrSetDate(), XmlAttrSetFloat(), XmlAttrSetInt(), and XmlFormatVPrintf().
DIRTYCODE_API int32_t XmlAttrSetStringRaw (char * pBuffer, const char * pAttr)
Set a text attribute for an open element (started tag) with no text encoding being performed on the input string. Must be called before Element text is set.
Parameters
*pBuffer - xml buffer.
*pAttr - attribute to be added (expected format: attrName="attrValue").
Returns
int32_t - return code.
References ds_snzprintf(), and XML_ERR_INVALID_PARAM.
DIRTYCODE_API void XmlBufSizeIncrease (char * pBuffer, int32_t iNewBufLen)
Notify the xmlformat API that the buffer size was increased.
Parameters
*pBuffer - buffer to which xml is being written.
iNewBufLen – new size for that buffer
Version
03/30/2010 (mclouatre)
DIRTYCODE_API int32_t XmlElemAddDate (char * pBuffer, const char * pElemName, uint32_t uEpochDate)
Add a complete, contained Date element, using epoch date. Builds start and end tag. Nothing can be appended to this tag.
Parameters
*pBuffer - xml buffer.
*pElemName - name of the element (tag).
uEpochDate - date/time since epoch.
Returns
int32_t - return code.
References ds_secstotime(), ds_snzprintf(), NULL, XML_ERR_INVALID_PARAM, XML_MAX_DATE_LENGTH, and XmlElemAddString().
DIRTYCODE_API int32_t XmlElemAddFloat (char * pBuffer, const char * pElemName, const char * pFormatSpec, float fValue)
Add a complete, contained decimal element. Builds start and end tag. Nothing can be appended to this tag. Format it using formatSpec.
Parameters
*pBuffer - xml buffer.
*pElemName - name of the element (tag).
*pFormatSpec - Spec for formatting the float (see sprintf).
fValue - float value of the element.
Returns
int32_t - return code.
References ds_snzprintf(), XML_ERR_INVALID_PARAM, XML_MAX_FLOAT_LENGTH, and XmlElemAddString().
DIRTYCODE_API int32_t XmlElemAddInt (char * pBuffer, const char * pElemName, int32_t iValue)
Add a complete, contained integer element. Builds start and end tag. Nothing can be appended to this tag.
Parameters
*pBuffer - xml buffer.
*pElemName - name of the element (tag).
iValue - integer value of the element.
Returns
int32_t - return code.
References ds_snzprintf(), and XmlElemAddString().
DIRTYCODE_API int32_t XmlElemAddString (char * pBuffer, const char * pElemName, const char * pValue)
Add a complete, contained text element. Builds start and end tag. Nothing can be appended to this tag.
Parameters
*pBuffer - xml buffer.
*pElemName - name of the element (tag).
*pValue - value of the element.
Returns
int32_t - return code.
References ds_snzprintf(), XML_ERR_FULL, XML_ERR_NOT_OPEN, and XML_ERR_UNINIT.
Referenced by XmlElemAddDate(), XmlElemAddFloat(), and XmlElemAddInt().
DIRTYCODE_API int32_t XmlElemSetAddr (char * pBuffer, uint32_t uAddr)
Set an IP address value (in dot notation) for an open element¸.
Parameters
*pBuffer - xml buffer.
uAddr - address to set
Returns
int32_t - return code.
References ds_snzprintf(), and XmlElemSetString().
Referenced by XmlFormatVPrintf().
DIRTYCODE_API int32_t XmlElemSetDate (char * pBuffer, uint32_t uEpoch)
Set a date for an open element. Must have an open element (started tag).
Parameters
*pBuffer - xml buffer.
uEpoch - date to set
Returns
int32_t - return code.
References ds_secstotime(), ds_snzprintf(), NULL, XML_ERR_INVALID_PARAM, XML_MAX_DATE_LENGTH, and XmlElemSetString().
Referenced by XmlFormatVPrintf().
DIRTYCODE_API int32_t XmlElemSetInt (char * pBuffer, int32_t iValue)
Set integer value for an open element (started tag). Must have an open or started tag, uses element from previous start tag call. To be used if element is a simple node with some attributes.
Parameters
*pBuffer - xml buffer.
iValue - integer value of the element.
Returns
int32_t - return code.
References ds_snzprintf(), and XmlElemSetString().
Referenced by XmlFormatVPrintf().
DIRTYCODE_API int32_t XmlElemSetString (char * pBuffer, const char * pValue)
Set text value for an open element (started tag). Must have an open or started tag, uses element from previous start tag call. To be used if element is simple text node with some attributes.
Parameters
*pBuffer - xml buffer.
*pValue - value of the element.
Returns
int32_t - return code.
References XML_ERR_FULL, XML_ERR_NOT_OPEN, and XML_ERR_UNINIT.
Referenced by XmlElemSetAddr(), XmlElemSetDate(), XmlElemSetInt(), and XmlFormatVPrintf().
DIRTYCODE_API int32_t XmlElemSetStringRaw (char * pBuffer, const char * pValue)
Set text value for an open element (started tag), with no encoding being performed on the input string. Must have an open or started tag, uses element from previous start tag call. To be used if element is simple text node with some attributes.
Parameters
*pBuffer - xml buffer.
*pValue - value of the element.
Returns
int32_t - return code.
DIRTYCODE_API char* XmlFinish (char * pBuffer)
Signal completion of output to this buffer. Clear the XML API hidden data.
Parameters
*pBuffer – buffer to which xml was written.
Returns
char* - pointer to real XML data (skipping past header)
References XML_HEADER_LEN.
Referenced by XmlFormatVPrintf().
DIRTYCODE_API char* XmlFormatPrintf (char * pXmlBuff, int32_t iBufLen, const char * pFormat, ...)
    Takes a format string and variable parameter list and formats into syntax
    correct XML doing optimizations like removing empty tags (i.e., <x></x>
    becomes <x />).
Parameters
*pXmlBuff - xml output buffer
iBufLen - length of Xml output buffer (negative=append to existing buffer)
*pFormat - printf style format string
Returns
char* - pointer to formatted buffer
References XmlFormatVPrintf().
DIRTYCODE_API void XmlInit (char * pBuffer, int32_t iBufLen, uint8_t uFlags)
DIRTYCODE_API int32_t XmlTagEnd (char * pBuffer)
End the current element or tag – must have an outstanding open tag.
Parameters
*pBuffer - xml buffer.
Returns
int32_t - return code.
References ds_snzprintf(), XML_ERR_FULL, XML_ERR_UNINIT, XML_HEADER_LEN, and XML_MAX_TAG_LENGTH.
Referenced by XmlFormatVPrintf().
DIRTYCODE_API int32_t XmlTagStart (char * pBuffer, const char * pName)
Start an xml element (node), to which you can add other elements or attributes. Must be ended with XmlTagEnd.
Parameters
*pBuffer - xml buffer.
*pName - Name of the tag.
Returns
int32_t - return code.
Todo:
Consider using var-args for attributes?
References ds_snzprintf(), XML_ERR_FULL, and XML_ERR_UNINIT.
Referenced by XmlFormatVPrintf().
DIRTYCODE_API int32_t XmlValidate (const char * pXmlBuff, char * pErrorsBuff, int32_t iErrorsBuffLen)
Debug only function that will do simple validation of the tags. Will return count of errors found, and, errorsBuff is a output string of the errors. Returns true on Production.
Parameters
*pXmlBuff - xml buffer to validate.
*pErrorsBuff - Buffer for any errors returned.
iErrorsBuffLen - Length of error buff; will stop writing if full.
Returns
int32_t - Number of errors found. Returns 0 if OK, or in Production.
Todo:
No decision made on any validation that needed to occur.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:32