DirtySock: cryptarc4.c File Reference
cryptarc4.c File Reference
This module is a from-scratch ARC4 implementation designed to avoid any intellectual property complications. The ARC4 stream cipher is known to produce output that is compatible with the RC4 stream cipher.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "DirtySDK/platform.h"
#include "DirtySDK/dirtysock/dirtylib.h"
#include "DirtySDK/crypt/cryptarc4.h"
#include "DirtySDK/crypt/cryptrand.h"
Functions
void CryptArc4Init (CryptArc4T *pState, const uint8_t *pKeyBuf, int32_t iKeyLen, int32_t iIter)
Initialize state for ARC4 encryption/decryption module.
void CryptArc4Apply (CryptArc4T *pState, uint8_t *pBuffer, int32_t iLength)
Apply the cipher to the data. Uses reversible XOR so calling twice undoes the uncryption (assuming the key state has been reset).
void CryptArc4Advance (CryptArc4T *pState, int32_t iLength)
Advance the cipher state with by iLength bytes.
void CryptArc4StringEncrypt (char *pDst, int32_t iLen, const char *pSrc, const uint8_t *pKey, int32_t iKey, int32_t iIter)
Easy way to encode an asciiz string. The resulting string is iLen chars of visible ascii characters. String characters must fall in the range of 32 to 127 to be considered valid.
void CryptArc4StringDecrypt (char *pDst, int32_t iLen, const char *pSrc, const uint8_t *pKey, int32_t iKey, int32_t iIter)
Decode an asciiz string encoded with CryptArc4StringEncrypt.
int32_t CryptArc4StringEncryptStaticCode (char *pStr, int32_t iStrSize, const uint8_t *pKey, int32_t iKeySize, const char *pStrSrc)
This function decrypts an encrypted key/encoded string pair into the source plaintext string. It also accepts the plaintext string as an argument to verify that the source plaintext string matches the resulting decrypted string. If there is a mismatch updated key and encoded string data is printed in c-style array form and an error is returned. The source plaintext string parameter is only referenced in debug builds to prevent the plaintext string from leaking into the release binary. The CryptArc4StringEncryptStatic() macro wrapper should always be used to call this function, and the plaintext string itself should be defined via the preprocessor, to prevent the plaintext string from leaking into the release binary.
Detailed Description
This module is a from-scratch ARC4 implementation designed to avoid any intellectual property complications. The ARC4 stream cipher is known to produce output that is compatible with the RC4 stream cipher.
Note
This algorithm from this cypher was taken from the web site: ciphersaber.gurus.com. It is based on the RC4 compatible algorithm that was published in the 2nd ed of the book Applied Cryptography by Bruce Schneier. This is a private-key stream cipher which means that some other secure way of exchanging cipher keys prior to algorithm use is required. Its strength is directly related to the key exchange algorithm strength. In operation, each individual stream message must use a unique key. This is handled by appending on 10 byte random value onto the private key. This 10-byte data can be sent by public means to the receptor (or included at the start of a file or whatever). When the private key is combined with this public key, it essentially puts the cypher into a random starting state (it is like using a message digest routine to generate a random hash for password comparison). The code below was written from scratch using only a textual algorithm description.
Attention
Copyright (c) 2000-2005 Electronic Arts Inc.
Version
1.0 02/25/2000 (gschaefer) First Version
1.1 11/06/2002 (jbrookes) Removed Create()/Destroy() to eliminate mem alloc dependencies.
Function Documentation
void CryptArc4Apply (CryptArc4T * pState, uint8_t * pBuffer, int32_t iLength)
Apply the cipher to the data. Uses reversible XOR so calling twice undoes the uncryption (assuming the key state has been reset).
Parameters
*pState - module state
*pBuffer - buffer to encrypt/decrypt
iLength - length of buffer
Version
02/26/2000 (gschaefer)
References CryptArc4T::state, CryptArc4T::swap, and CryptArc4T::walk.
Referenced by CryptArc4StringDecrypt(), CryptArc4StringEncrypt(), and CryptArc4StringEncryptStaticCode().
void CryptArc4Init (CryptArc4T * pState, const uint8_t * pKeyBuf, int32_t iKeyLen, int32_t iIter)
Initialize state for ARC4 encryption/decryption module.
Parameters
*pState - module state
*pKeyBuf - pointer to crypt key
iKeyLen - length of crypt key (sixteen for RC4-128)
iIter - internal iterator (1=RC4 compat, larger for slightly improved security
Version
02/26/2000 (gschaefer)
References CryptArc4Advance(), CryptArc4T::state, CryptArc4T::swap, and CryptArc4T::walk.
Referenced by CryptArc4StringDecrypt(), CryptArc4StringEncrypt(), and CryptArc4StringEncryptStaticCode().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:44