DirtySock: SequentialStream Class Reference
SequentialStream Class Reference
Public Member Functions
SequentialStream ()
SequentialStream constructor.
virtual ~SequentialStream ()
SequentialStream destructor.
HRESULT STDMETHODCALLTYPE Read (void *pBuffer, ULONG uMaxBytes, ULONG *uBytesRead)
Reads from the uBufferPositionRead position.
HRESULT STDMETHODCALLTYPE Write (const void *pBuffer, ULONG uMaxBytes, ULONG *uBytesWritten)
Writes to the end of the buffer, and increases the buffer size if needed.
ProtoHttpRefT * GetProtoHttpRef ()
void SetProtoHttpRef (ProtoHttpRefT *pState)
int32_t GetDataSize ()
char * GetData ()
Protected Attributes
NetCritT m_StreamCrit
char * m_pBuffer
ULONG m_uBufferSize
ULONG m_uBufferPositionWrite
ULONG m_uBufferPositionRead
Constructor & Destructor Documentation
SequentialStream ()
SequentialStream constructor.
Version
11/01/2012 (akirchner)
References m_StreamCrit, and NetCritInit().
~SequentialStream () virtual
SequentialStream destructor.
Version
11/01/2012 (akirchner)
References DirtyMemFree(), DirtyMemGroupQuery(), m_pBuffer, m_StreamCrit, NetCritKill(), and PROTOHTTP_MEMID.
Member Function Documentation
char* SequentialStream::GetData () inline
References m_pBuffer.
int32_t SequentialStream::GetDataSize () inline
References m_uBufferPositionRead, and m_uBufferPositionWrite.
ProtoHttpRefT* SequentialStream::GetProtoHttpRef () inline
Referenced by Read(), and Write().
HRESULT Read (void * pData, ULONG uMaxBytes, ULONG * uBytesRead)
Reads from the uBufferPositionRead position.
Parameters
*pData - [OUT] A pointer to the buffer which the stream data is read into
uMaxBytes - The number of bytes of data to read from the stream object
uBytesRead - [OUT] A pointer to a ULONG variable that receives the actual number of bytes read from the stream object
Returns
HRESULT - S_OK if succeed
Version
07/02/2013 (jbrookes)
References ds_memcpy(), GetProtoHttpRef(), ProtoHttpRefT::iVerbose, m_pBuffer, m_StreamCrit, m_uBufferPositionRead, m_uBufferPositionWrite, NetCritEnter(), NetCritLeave(), NetPrintfVerbose, ProtoHttpRefT::SendRate, SocketRateThrottle(), and SocketRateUpdate().
void SequentialStream::SetProtoHttpRef (ProtoHttpRefT * pState) inline
HRESULT Write (const void * pData, ULONG uMaxBytes, ULONG * pBytesWritten)
Writes to the end of the buffer, and increases the buffer size if needed.
Parameters
*pData - input data to be written into the stream
uMaxBytes - size of data to be written into the stream
*pBytesWritten - [OUT] storage for actual number of bytes that were written
Returns
HRESULT - S_OK if succeed
Version
07/02/2013 (jbrookes)
References DirtyMemAlloc(), DirtyMemFree(), DirtyMemGroupQuery(), ds_memcpy(), GetProtoHttpRef(), ProtoHttpRefT::iVerbose, m_pBuffer, m_StreamCrit, m_uBufferPositionWrite, m_uBufferSize, NetCritEnter(), NetCritLeave(), NetPrintf, NetPrintfVerbose, and PROTOHTTP_MEMID.
Field Documentation
char* SequentialStream::m_pBuffer protected
Referenced by GetData(), Read(), Write(), and ~SequentialStream().
NetCritT SequentialStream::m_StreamCrit protected
Referenced by Read(), SequentialStream(), Write(), and ~SequentialStream().
ULONG SequentialStream::m_uBufferPositionRead protected
Referenced by GetDataSize(), and Read().
ULONG SequentialStream::m_uBufferPositionWrite protected
Referenced by GetDataSize(), Read(), and Write().
ULONG SequentialStream::m_uBufferSize protected
Referenced by Write().
The documentation for this class was generated from the following file:
protohttpxboxone.cpp
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:34:41