DirtySock: WebOffer
WebOffer
Misc
Data Structures
struct WebOfferSetupT
struct WebOfferCommandT
struct WebOfferColorT
struct WebOfferResourceT
struct WebOfferButtonT
struct WebOfferFixedImageT
struct WebOfferBusyT
struct WebOfferAlertT
struct WebOfferCreditT
struct WebOfferPromoT
struct WebOfferNewsT
struct WebOfferMenuT
struct WebOfferArticlesT
struct WebOfferStoryT
struct WebOfferMediaT
struct WebOfferFormT
struct WebOfferMarketplaceT
Macros
#define WEBOFFER_SUGGESTED_MEM (150*1024)
suggested script size (allow for localized TOS)
#define WEBOFFER_CMD_ALERT ('alrt')
show an alert
#define WEBOFFER_CMD_PROMO ('prom')
show promo screen
#define WEBOFFER_CMD_CREDIT ('card')
show credit card screen
#define WEBOFFER_CMD_HTTP ('http')
do http transfer
#define WEBOFFER_CMD_NEWS ('news')
show news screen
#define WEBOFFER_CMD_MENU ('menu')
show a menu of options
#define WEBOFFER_CMD_ARTICLES ('arti')
list of articles
#define WEBOFFER_CMD_STORY ('stor')
show a text based story
#define WEBOFFER_CMD_MEDIA ('medi')
show a media based story
#define WEBOFFER_CMD_FORM ('form')
show a web offer form
#define WEBOFFER_CMD_MARKET ('mplc')
show the platform marketplace UI
#define WEBOFFER_ALERT_NUMBUTTONS (4)
number of alert buttons
#define WEBOFFER_NEWS_NUMBUTTONS (4)
number of news buttons
#define WEBOFFER_BUSY_NUMBUTTONS (1)
number of busy buttons
#define WEBOFFER_CREDIT_NUMBUTTONS (4)
number of credit buttons
#define WEBOFFER_PROMO_NUMBUTTONS (4)
number of promo buttons
#define WEBOFFER_MENU_NUMBUTTONS (8)
number of menu buttons
#define WEBOFFER_ARTICLES_NUMBUTTONS (4)
number of article buttons
#define WEBOFFER_FORM_NUMBUTTONS (4)
number of form buttons
#define WEBOFFER_FORM_NUMFIELDS (16)
number of fields allowed on a web offer form
#define WEBOFFER_ARTICLES_NUMARTICLES (16)
number of articles in a WebOfferArticlesT
#define WEB_OFFER_FORM_STRING (0)
Form Style input string.
#define WEB_OFFER_FORM_LIST (1)
Form Style List of possible values.
#define WEB_OFFER_FORM_STATIC_STRING (2)
Form Style Static String.
#define WEB_OFFER_FORM_NUMERIC (3)
Form Style Numeric Value.
#define WEB_OFFER_FORM_FLOAT (4)
Form Style Float Value.
#define WEBOFFER_NEWS_NUM_FIXED_IMAGE (4)
number of auxillary pictures allowed for the news screen
#define WEBOFFER_CREDIT_NUM_FIXED_IMAGE (4)
number of auxillary pictures allowed for the credit card screen
#define WEBOFFER_PROMO_NUM_FIXED_IMAGE (4)
number of auxillary pictures allowed for the promotions screen
#define WEBOFFER_ARTICLES_NUM_FIXED_IMAGE (4)
number of auxillary pictures allowed for the article list screen
#define WEBOFFER_FORM_NUM_FIXED_IMAGE (4)
number of auxillary pictures allowed for a web offer form screen
#define WEBOFFER_TYPE_NORMAL (' ')
button type is normal
#define WEBOFFER_TYPE_SUBMIT ('^')
button type is submit
#define WEBOFFER_BUTTON_DISPMAX (20)
Display sizes (how many characters to show on the screen)
#define WEBOFFER_TITLE_DISPMAX (64)
display chars for title
#define WEBOFFER_BUSYMSG_DISPMAX (512)
display chars for busy message
#define WEBOFFER_ALERTMSG_DISPMAX (512)
display chars for alert message
#define WEBOFFER_CCMSG_DISPMAX (512)
display chars for credit card message
#define WEBOFFER_CCNAME_DISPMAX (50)
display chars for first/last name
#define WEBOFFER_CCADDR_DISPMAX (50)
display chars per address line
#define WEBOFFER_CCCITY_DISPMAX (50)
display character for city
#define WEBOFFER_CCSTATE_DISPMAX (20)
display chars for state
#define WEBOFFER_CCPOST_DISPMAX (20)
display chars for post/zip
#define WEBOFFER_CCCOUNTRY_DISPMAX (25)
display chars for country
#define WEBOFFER_CCEMAIL_DISPMAX (50)
display chars for email
#define WEBOFFER_CCCARDTYPE_DISPMAX (40)
display chars for credit card type
#define WEBOFFER_CCCARDNUM_DISPMAX (20)
display chars for credit card number
#define WEBOFFER_PROMOMSG_DISPMAX (512)
display chars for promotion message
#define WEBOFFER_PROMOENTRY_DISPMAX (100)
display chars for promotion entry
#define WEBOFFER_SUMMARY_DISPMAX (2048)
display chars for summary in Articles
#define WEBOFFER_FORMMSG_DISPMAX (512)
display chars for form message
#define WEBOFFER_FORMVALUE_DISPMAX (64)
display chars for form values
#define WEBOFFER_BUTTON_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_BUTTON_DISPMAX))
#define WEBOFFER_TITLE_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_TITLE_DISPMAX))
#define WEBOFFER_BUSYMSG_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_BUSYMSG_DISPMAX))
#define WEBOFFER_ALERTMSG_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_ALERTMSG_DISPMAX))
#define WEBOFFER_CCMSG_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_CCMSG_DISPMAX))
#define WEBOFFER_CCNAME_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_CCNAME_DISPMAX))
#define WEBOFFER_CCADDR_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_CCADDR_DISPMAX))
#define WEBOFFER_CCCITY_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_CCCITY_DISPMAX))
#define WEBOFFER_CCSTATE_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_CCSTATE_DISPMAX))
#define WEBOFFER_CCPOST_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_CCPOST_DISPMAX))
#define WEBOFFER_CCCOUNTRY_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_CCCOUNTRY_DISPMAX))
#define WEBOFFER_CCEMAIL_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_CCEMAIL_DISPMAX))
#define WEBOFFER_CCCARDTYPE_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_CCCARDTYPE_DISPMAX))
#define WEBOFFER_CCCARDNUM_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_CCCARDNUM_DISPMAX))
#define WEBOFFER_PROMOMSG_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_PROMOMSG_DISPMAX))
#define WEBOFFER_PROMOENTRY_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_PROMOENTRY_DISPMAX))
#define WEBOFFER_SUMMARY_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_SUMMARY_DISPMAX))
#define WEBOFFER_FORMMSG_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_FORMMSG_DISPMAX))
#define WEBOFFER_FORMVALUE_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_FORMVALUE_DISPMAX))
#define WEBOFFER_IMAGE_MEMSIZE 32
fixed size size not a display name
#define WEBOFFER_DispToMemSize(nDispChars) ((nDispChars * 100) / 50)
#define WebOfferResult(pOffer) WebOfferResultData(pOffer, NULL, 0)
Typedefs
typedef struct WebOfferT WebOfferT
typedef struct WebOfferSetupT WebOfferSetupT
typedef struct WebOfferCommandT WebOfferCommandT
typedef struct WebOfferColorT WebOfferColorT
typedef struct WebOfferResourceT WebOfferResourceT
typedef struct WebOfferButtonT WebOfferButtonT
typedef struct WebOfferFixedImageT WebOfferFixedImageT
typedef struct WebOfferBusyT WebOfferBusyT
typedef struct WebOfferAlertT WebOfferAlertT
typedef struct WebOfferCreditT WebOfferCreditT
typedef struct WebOfferPromoT WebOfferPromoT
typedef struct WebOfferNewsT WebOfferNewsT
typedef struct WebOfferMenuT WebOfferMenuT
typedef struct WebOfferArticlesT WebOfferArticlesT
typedef struct WebOfferStoryT WebOfferStoryT
typedef struct WebOfferMediaT WebOfferMediaT
typedef struct WebOfferFormT WebOfferFormT
typedef struct WebOfferMarketplaceT WebOfferMarketplaceT
Enumerations
enum WEB_OFFER_ACTION {
WEBOFFER_ACTION_ABORT = 0,
WEBOFFER_ACTION_BTN1,
WEBOFFER_ACTION_BTN2,
WEBOFFER_ACTION_BTN3,
WEBOFFER_ACTION_BTN4,
WEBOFFER_ACTION_BTN5,
WEBOFFER_ACTION_BTN6,
WEBOFFER_ACTION_BTN7,
WEBOFFER_ACTION_BTN8,
WEBOFFER_ACTION_ARTICLE1,
WEBOFFER_ACTION_ARTICLE2,
WEBOFFER_ACTION_ARTICLE3,
WEBOFFER_ACTION_ARTICLE4,
WEBOFFER_ACTION_ARTICLE5,
WEBOFFER_ACTION_ARTICLE6,
WEBOFFER_ACTION_ARTICLE7,
WEBOFFER_ACTION_ARTICLE8,
WEBOFFER_ACTION_ARTICLE9,
WEBOFFER_ACTION_ARTICLE10,
WEBOFFER_ACTION_ARTICLE11,
WEBOFFER_ACTION_ARTICLE12,
WEBOFFER_ACTION_ARTICLE13,
WEBOFFER_ACTION_ARTICLE14,
WEBOFFER_ACTION_ARTICLE15,
WEBOFFER_ACTION_ARTICLE16,
WEBOFFER_ACTION_LAST
}
weboffer actions
Functions
DIRTYCODE_API WebOfferT * WebOfferCreate (char *pBuffer, int32_t iLength)
Create a new web-offer module instance using passed in memory. Note that caller must make sure the buffer is valid until WebOfferDestroy is called. Recommand buffer is at least WEBOFFER_SUGGESTED_MEM bytes (based on typical usage).
DIRTYCODE_API WebOfferT * WebOfferDestroy (WebOfferT *pOffer)
Destroy the web-offer module.
DIRTYCODE_API void WebOfferUpdate (WebOfferT *pOffer)
Do period update – called by HttpResult automaticallt so most applications don't need to call direct.
DIRTYCODE_API void WebOfferClear (WebOfferT *pOffer)
Clear the script and reset to idle.
DIRTYCODE_API void WebOfferSetup (WebOfferT *pOffer, WebOfferSetupT *pSetup)
Setup information about the user/product.
DIRTYCODE_API void WebOfferExecute (WebOfferT *pOffer, const char *pScript)
Execute an offer script.
DIRTYCODE_API int32_t WebOfferResultData (WebOfferT *pOffer, char *pBuffer, int32_t iLength)
Return the result of an offer script.
DIRTYCODE_API WebOfferCommandT * WebOfferCommand (WebOfferT *pOffer)
Return the next command from the script.
DIRTYCODE_API int32_t WebOfferParamList (WebOfferT *pOffer, char *pBuffer, int32_t iLength, const char *pParam, int32_t iIndex)
Extract an item from a parameter list.
DIRTYCODE_API void WebOfferAction (WebOfferT *pOffer, int32_t iAction)
Report user input from last command.
DIRTYCODE_API void WebOfferHttp (WebOfferT *pOffer)
Transfer data to web server.
DIRTYCODE_API int32_t WebOfferHttpComplete (WebOfferT *pOffer)
Check on completion status of transfer.
DIRTYCODE_API int32_t WebOfferResource (WebOfferT *pOffer, WebOfferResourceT *pRsrc, const char *pName)
Return named resource type field.
DIRTYCODE_API void WebOfferGetAlert (WebOfferT *pOffer, WebOfferAlertT *pAlert)
Extract the alert data from the current command packet.
DIRTYCODE_API void WebOfferGetBusy (WebOfferT *pOffer, WebOfferBusyT *pBusy)
Extract the busy message for a web transfer.
DIRTYCODE_API void WebOfferGetBusy2 (WebOfferT *pOffer, WebOfferBusyT *pBusy, const char *strDefaultMessage)
Extract the busy message for a web transfer.
DIRTYCODE_API void WebOfferGetCredit (WebOfferT *pOffer, WebOfferCreditT *pInfo)
Extract credit card parms.
DIRTYCODE_API void WebOfferSetCredit (WebOfferT *pOffer, WebOfferCreditT *pInfo)
Store updated credit card data form user.
DIRTYCODE_API void WebOfferGetPromo (WebOfferT *pOffer, WebOfferPromoT *pInfo)
Extract promo screen parms.
DIRTYCODE_API void WebOfferSetPromo (WebOfferT *pOffer, WebOfferPromoT *pInfo)
Store updated promo data form user.
DIRTYCODE_API void WebOfferGetMenu (WebOfferT *pOffer, WebOfferMenuT *pInfo)
Extract menu screen parms.
DIRTYCODE_API const char * WebOfferGetNews (WebOfferT *pOffer, WebOfferNewsT *pInfo)
Extract news screen parms.
DIRTYCODE_API void WebOfferGetArticles (WebOfferT *pOffer, WebOfferArticlesT *pInfo)
Extract article list structure.
DIRTYCODE_API const char * WebOfferGetStory (WebOfferT *pOffer, WebOfferStoryT *pInfo)
Extract text story screen info.
DIRTYCODE_API const char * WebOfferGetMedia (WebOfferT *pOffer, WebOfferMediaT *pInfo)
Extract media player screen info.
DIRTYCODE_API void WebOfferGetForm (WebOfferT *pOffer, WebOfferFormT *pInfo)
Extract web offer form parms.
DIRTYCODE_API void WebOfferGetMarketplace (WebOfferT *pOffer, WebOfferMarketplaceT *pInfo)
Extract web offer marketplace parms.
DIRTYCODE_API void WebOfferSetForm (WebOfferT *pOffer, WebOfferFormT *pInfo)
Store updated web offer form data from user.
Detailed Description
Macro Definition Documentation
#define WEB_OFFER_FORM_FLOAT (4)
Form Style Float Value.
#define WEB_OFFER_FORM_LIST (1)
Form Style List of possible values.
#define WEB_OFFER_FORM_NUMERIC (3)
Form Style Numeric Value.
#define WEB_OFFER_FORM_STATIC_STRING (2)
Form Style Static String.
#define WEB_OFFER_FORM_STRING (0)
Form Style input string.
#define WEBOFFER_ALERT_NUMBUTTONS (4)
number of alert buttons
#define WEBOFFER_ALERTMSG_DISPMAX (512)
display chars for alert message
#define WEBOFFER_ALERTMSG_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_ALERTMSG_DISPMAX))
#define WEBOFFER_ARTICLES_NUM_FIXED_IMAGE (4)
number of auxillary pictures allowed for the article list screen
Referenced by WebOfferGetArticles().
#define WEBOFFER_ARTICLES_NUMARTICLES (16)
number of articles in a WebOfferArticlesT
#define WEBOFFER_ARTICLES_NUMBUTTONS (4)
number of article buttons
#define WEBOFFER_BUSY_NUMBUTTONS (1)
number of busy buttons
#define WEBOFFER_BUSYMSG_DISPMAX (512)
display chars for busy message
#define WEBOFFER_BUSYMSG_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_BUSYMSG_DISPMAX))
#define WEBOFFER_BUTTON_DISPMAX (20)
Display sizes (how many characters to show on the screen)
display chars for button name
#define WEBOFFER_BUTTON_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_BUTTON_DISPMAX))
Memory storage sizes (number of bytes used to store the above displayed strings) based on display size (above defines) and storage size conversion macro (above)
#define WEBOFFER_CCADDR_DISPMAX (50)
display chars per address line
#define WEBOFFER_CCADDR_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_CCADDR_DISPMAX))
#define WEBOFFER_CCCARDNUM_DISPMAX (20)
display chars for credit card number
#define WEBOFFER_CCCARDNUM_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_CCCARDNUM_DISPMAX))
#define WEBOFFER_CCCARDTYPE_DISPMAX (40)
display chars for credit card type
#define WEBOFFER_CCCARDTYPE_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_CCCARDTYPE_DISPMAX))
#define WEBOFFER_CCCITY_DISPMAX (50)
display character for city
#define WEBOFFER_CCCITY_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_CCCITY_DISPMAX))
#define WEBOFFER_CCCOUNTRY_DISPMAX (25)
display chars for country
#define WEBOFFER_CCCOUNTRY_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_CCCOUNTRY_DISPMAX))
#define WEBOFFER_CCEMAIL_DISPMAX (50)
display chars for email
#define WEBOFFER_CCEMAIL_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_CCEMAIL_DISPMAX))
#define WEBOFFER_CCMSG_DISPMAX (512)
display chars for credit card message
#define WEBOFFER_CCMSG_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_CCMSG_DISPMAX))
#define WEBOFFER_CCNAME_DISPMAX (50)
display chars for first/last name
#define WEBOFFER_CCNAME_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_CCNAME_DISPMAX))
#define WEBOFFER_CCPOST_DISPMAX (20)
display chars for post/zip
#define WEBOFFER_CCPOST_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_CCPOST_DISPMAX))
#define WEBOFFER_CCSTATE_DISPMAX (20)
display chars for state
#define WEBOFFER_CCSTATE_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_CCSTATE_DISPMAX))
#define WEBOFFER_CMD_ALERT ('alrt')
show an alert
#define WEBOFFER_CMD_ARTICLES ('arti')
list of articles
#define WEBOFFER_CMD_CREDIT ('card')
show credit card screen
#define WEBOFFER_CMD_FORM ('form')
show a web offer form
#define WEBOFFER_CMD_HTTP ('http')
do http transfer
Referenced by WebOfferHttp().
#define WEBOFFER_CMD_MARKET ('mplc')
show the platform marketplace UI
#define WEBOFFER_CMD_MEDIA ('medi')
show a media based story
#define WEBOFFER_CMD_MENU ('menu')
show a menu of options
#define WEBOFFER_CMD_NEWS ('news')
show news screen
#define WEBOFFER_CMD_PROMO ('prom')
show promo screen
#define WEBOFFER_CMD_STORY ('stor')
show a text based story
#define WEBOFFER_CREDIT_NUM_FIXED_IMAGE (4)
number of auxillary pictures allowed for the credit card screen
Referenced by WebOfferGetCredit().
#define WEBOFFER_CREDIT_NUMBUTTONS (4)
number of credit buttons
Referenced by WebOfferGetCredit().
#define WEBOFFER_DispToMemSize (nDispChars) ((nDispChars * 100) / 50)
Games that support Greek and/or Asian languages encode each user-visible character using UTF-8 which results in a single character being represented by 1-4 bytes. These games therefore need larger buffers to hold strings.
The following macro is used to convert the suggested display length to a storage size. If space is at a premium and the game is English only, the calculation can be reduced to simply equate the two sizes. Otherwise, this formula should be adjusted to take into account the average display size and average storage size of the strings to be used.
#define WEBOFFER_FORM_NUM_FIXED_IMAGE (4)
number of auxillary pictures allowed for a web offer form screen
Referenced by WebOfferGetForm().
#define WEBOFFER_FORM_NUMBUTTONS (4)
number of form buttons
Referenced by WebOfferGetForm().
#define WEBOFFER_FORM_NUMFIELDS (16)
number of fields allowed on a web offer form
Referenced by WebOfferGetForm().
#define WEBOFFER_FORMMSG_DISPMAX (512)
display chars for form message
#define WEBOFFER_FORMMSG_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_FORMMSG_DISPMAX))
#define WEBOFFER_FORMVALUE_DISPMAX (64)
display chars for form values
#define WEBOFFER_FORMVALUE_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_FORMVALUE_DISPMAX))
#define WEBOFFER_IMAGE_MEMSIZE 32
fixed size size not a display name
#define WEBOFFER_MENU_NUMBUTTONS (8)
number of menu buttons
#define WEBOFFER_NEWS_NUM_FIXED_IMAGE (4)
number of auxillary pictures allowed for the news screen
Referenced by WebOfferGetNews().
#define WEBOFFER_NEWS_NUMBUTTONS (4)
number of news buttons
Referenced by WebOfferGetNews().
#define WEBOFFER_PROMO_NUM_FIXED_IMAGE (4)
number of auxillary pictures allowed for the promotions screen
Referenced by WebOfferGetPromo().
#define WEBOFFER_PROMO_NUMBUTTONS (4)
number of promo buttons
Referenced by WebOfferGetPromo().
#define WEBOFFER_PROMOENTRY_DISPMAX (100)
display chars for promotion entry
#define WEBOFFER_PROMOENTRY_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_PROMOENTRY_DISPMAX))
#define WEBOFFER_PROMOMSG_DISPMAX (512)
display chars for promotion message
#define WEBOFFER_PROMOMSG_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_PROMOMSG_DISPMAX))
#define WEBOFFER_SUGGESTED_MEM (150*1024)
suggested script size (allow for localized TOS)
#define WEBOFFER_SUMMARY_DISPMAX (2048)
display chars for summary in Articles
#define WEBOFFER_SUMMARY_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_SUMMARY_DISPMAX))
#define WEBOFFER_TITLE_DISPMAX (64)
display chars for title
#define WEBOFFER_TITLE_MEMSIZE (WEBOFFER_DispToMemSize(WEBOFFER_TITLE_DISPMAX))
#define WEBOFFER_TYPE_NORMAL (' ')
button type is normal
Referenced by WebOfferGetAlert().
#define WEBOFFER_TYPE_SUBMIT ('^')
button type is submit
#define WebOfferResult (pOffer) WebOfferResultData(pOffer, NULL, 0)
Typedef Documentation
typedef struct WebOfferAlertT WebOfferAlertT
typedef struct WebOfferArticlesT WebOfferArticlesT
typedef struct WebOfferBusyT WebOfferBusyT
typedef struct WebOfferButtonT WebOfferButtonT
typedef struct WebOfferColorT WebOfferColorT
typedef struct WebOfferCommandT WebOfferCommandT
typedef struct WebOfferCreditT WebOfferCreditT
typedef struct WebOfferFixedImageT WebOfferFixedImageT
typedef struct WebOfferFormT WebOfferFormT
typedef struct WebOfferMarketplaceT WebOfferMarketplaceT
typedef struct WebOfferMediaT WebOfferMediaT
typedef struct WebOfferMenuT WebOfferMenuT
typedef struct WebOfferNewsT WebOfferNewsT
typedef struct WebOfferPromoT WebOfferPromoT
typedef struct WebOfferResourceT WebOfferResourceT
typedef struct WebOfferSetupT WebOfferSetupT
typedef struct WebOfferStoryT WebOfferStoryT
typedef struct WebOfferT WebOfferT
Enumeration Type Documentation
enum WEB_OFFER_ACTION
weboffer actions
Enumerator
WEBOFFER_ACTION_ABORT
WEBOFFER_ACTION_BTN1
WEBOFFER_ACTION_BTN2
WEBOFFER_ACTION_BTN3
WEBOFFER_ACTION_BTN4
WEBOFFER_ACTION_BTN5
WEBOFFER_ACTION_BTN6
WEBOFFER_ACTION_BTN7
WEBOFFER_ACTION_BTN8
WEBOFFER_ACTION_ARTICLE1
WEBOFFER_ACTION_ARTICLE2
WEBOFFER_ACTION_ARTICLE3
WEBOFFER_ACTION_ARTICLE4
WEBOFFER_ACTION_ARTICLE5
WEBOFFER_ACTION_ARTICLE6
WEBOFFER_ACTION_ARTICLE7
WEBOFFER_ACTION_ARTICLE8
WEBOFFER_ACTION_ARTICLE9
WEBOFFER_ACTION_ARTICLE10
WEBOFFER_ACTION_ARTICLE11
WEBOFFER_ACTION_ARTICLE12
WEBOFFER_ACTION_ARTICLE13
WEBOFFER_ACTION_ARTICLE14
WEBOFFER_ACTION_ARTICLE15
WEBOFFER_ACTION_ARTICLE16
WEBOFFER_ACTION_LAST
Function Documentation
DIRTYCODE_API void WebOfferAction (WebOfferT * pOffer, int32_t iAction)
Report user input from last command.
Parameters
*pOffer - module state from WebOfferCreate
iAction - action
Version
03/13/2004 gschaefer
References _WebOffer_ActionGoto1, WebOfferT::Command, ds_memcpy(), WebOfferT::iScript, WebOfferT::pCmdHead, WebOfferT::pCmdTail, WebOfferT::pNewsHead, WebOfferT::pNewsTail, WebOfferT::pScript, WebOfferCommandT::strParms, TagFieldSetNumber(), WEBOFFER_ACTION_ABORT, WEBOFFER_ACTION_LAST, and WebOfferClear().
DIRTYCODE_API void WebOfferClear (WebOfferT * pOffer)
Clear the script and reset to idle.
Parameters
*pOffer - module state from WebOfferCreate
Version
03/13/2004 gschaefer
References WebOfferT::pExec, and WebOfferT::pScript.
Referenced by WebOfferAction(), WebOfferExecute(), and WebOfferHttp().
DIRTYCODE_API WebOfferCommandT* WebOfferCommand (WebOfferT * pOffer)
Return the next command from the script.
Parameters
*pOffer - module state from WebOfferCreate
Version
03/13/2004 gschaefer
References WebOfferT::Command, ds_memcpy_s(), WebOfferCommandT::iCommand, WebOfferT::pCmdHead, WebOfferT::pCmdTail, WebOfferT::pExec, WebOfferT::pNewsHead, WebOfferT::pNewsTail, WebOfferCommandT::strParms, TagFieldFind(), TagFieldGetToken(), WEBOFFER_CMD_GOTO, and WEBOFFER_GOTO_LIMIT.
DIRTYCODE_API WebOfferT* WebOfferCreate (char * pBuffer, int32_t iLength)
Create a new web-offer module instance using passed in memory. Note that caller must make sure the buffer is valid until WebOfferDestroy is called. Recommand buffer is at least WEBOFFER_SUGGESTED_MEM bytes (based on typical usage).
Parameters
*pBuffer - pointer to caller supplied buffer, or NULL
iLength - length of caller supplied buffer, or size of buffer to allocate if pBuffer==NULL
Returns
WebOfferT reference pointer – pass as input to all other functions
Version
03/13/2004 gschaefer
References DirtyMemAlloc(), DirtyMemFree(), DirtyMemGroupQuery(), ProtoHttpCreate(), WebOfferT::pScript, ST_IDLE, WEBOFFER_MEMID, and WebOfferDestroy().
DIRTYCODE_API WebOfferT* WebOfferDestroy (WebOfferT * pOffer)
Destroy the web-offer module.
Parameters
*pOffer - the module state from WebOfferCreation
Returns
NULL - to allow inline destroy/variable clear
Version
03/13/2004 gschaefer
References DirtyMemFree(), WebOfferT::iMemGroup, WebOfferT::pHttps, WebOfferT::pMemGroupUserData, WebOfferT::pOwner, ProtoHttpDestroy(), and WEBOFFER_MEMID.
Referenced by WebOfferCreate().
DIRTYCODE_API void WebOfferExecute (WebOfferT * pOffer, const char * pScript)
Execute an offer script.
Parameters
*pOffer - module state from WebOfferCreate
*pScript - script to execute
Version
03/13/2004 gschaefer
References ds_stristr(), WebOfferT::iScript, WebOfferT::pExec, WebOfferT::pScript, WebOfferT::strResult, and WebOfferClear().
DIRTYCODE_API void WebOfferGetAlert (WebOfferT * pOffer, WebOfferAlertT * pInfo)
Extract the alert data from the current command packet.
Parameters
pOffer - module state from WebOfferCreate
pInfo - return structure for alert data
Version
03/13/2004 gschaefer
References WebOfferAlertT::Button, WebOfferT::Command, WebOfferAlertT::MsgColor, WebOfferAlertT::strImage, WebOfferAlertT::strMessage, WebOfferCommandT::strParms, WebOfferButtonT::strText, WebOfferAlertT::strTitle, WebOfferButtonT::strType, TagFieldFind(), TagFieldGetString(), WEBOFFER_TAGNAME_BUTTON, and WEBOFFER_TYPE_NORMAL.
DIRTYCODE_API void WebOfferGetArticles (WebOfferT * pOffer, WebOfferArticlesT * pInfo)
Extract article list structure.
Parameters
pOffer - module state from WebOfferCreate
pInfo - return structure with article list data
Version
11/03/2005 gschaefer
References WebOfferArticlesT::Article, WebOfferArticlesT::Button, WebOfferT::Command, WebOfferArticlesT::FixedImage, WebOfferArticlesT::strArticle, WebOfferArticlesT::strDesc, WebOfferArticlesT::strImage, WebOfferCommandT::strParms, WebOfferArticlesT::strTitle, WebOfferArticlesT::strType, TagFieldFind(), TagFieldFindIdx(), TagFieldGetString(), WEBOFFER_ARTICLES_NUM_FIXED_IMAGE, WEBOFFER_TAGNAME_ARTICLE, WEBOFFER_TAGNAME_BUTTON, and WEBOFFER_TAGNAME_FIXED_IMAGE.
DIRTYCODE_API void WebOfferGetBusy (WebOfferT * pOffer, WebOfferBusyT * pInfo)
Extract the busy message for a web transfer.
Parameters
pOffer - module state from WebOfferCreate
pInfo - return structure for busy screen data
Note
$$todo v9: deprecate WebOfferGetBusy rename WebOfferGetBusy2 –> WebOfferGetBusy
Version
03/13/2004 gschaefer
References WebOfferGetBusy2().
DIRTYCODE_API void WebOfferGetBusy2 (WebOfferT * pOffer, WebOfferBusyT * pInfo, const char * strDefaultMessage)
Extract the busy message for a web transfer.
Parameters
pOffer - module state from WebOfferCreate
pInfo - return structure for busy screen data
strDefaultMessage - The default message to use
Version
02/07/2012 jchen
References WebOfferBusyT::Button, WebOfferT::Command, WebOfferBusyT::MsgColor, WebOfferBusyT::strMessage, WebOfferCommandT::strParms, WebOfferBusyT::strTitle, TagFieldFind(), TagFieldGetString(), and WEBOFFER_TAGNAME_BUTTON.
Referenced by WebOfferGetBusy().
DIRTYCODE_API void WebOfferGetCredit (WebOfferT * pOffer, WebOfferCreditT * pInfo)
Extract credit card parms.
Parameters
pOffer - module state from WebOfferCreate
pInfo - return structure for credit card data
Version
03/13/2004 gschaefer
References WebOfferCreditT::Button, WebOfferT::Command, WebOfferCreditT::FixedImage, WebOfferCreditT::iExpiryMonth, WebOfferCreditT::iExpiryYear, WebOfferCreditT::iYearEndExpiry, WebOfferCreditT::iYearStartExpiry, WebOfferCreditT::MsgColor, WebOfferCreditT::pCardList, WebOfferCreditT::pCountryList, WebOfferCreditT::strAddress, WebOfferCreditT::strCardNumber, WebOfferCreditT::strCardType, WebOfferCreditT::strCity, WebOfferCreditT::strCountry, WebOfferCreditT::strEmail, WebOfferCreditT::strFirstName, WebOfferCreditT::strLastName, WebOfferCreditT::strMessage, WebOfferCommandT::strParms, WebOfferCreditT::strPostCode, WebOfferCreditT::strState, WebOfferCreditT::strTitle, TagFieldFind(), TagFieldGetString(), WEBOFFER_CREDIT_NUM_FIXED_IMAGE, WEBOFFER_CREDIT_NUMBUTTONS, WEBOFFER_TAGNAME_BUTTON, and WEBOFFER_TAGNAME_FIXED_IMAGE.
DIRTYCODE_API void WebOfferGetForm (WebOfferT * pOffer, WebOfferFormT * pInfo)
Extract web offer form parms.
Parameters
pOffer - module state from WebOfferCreate
pInfo - return structure for web form data
Version
05/23/2006 (ozietman)
References WebOfferFormT::bMandatory, WebOfferFormT::Button, WebOfferT::Command, WebOfferFormT::Fields, WebOfferFormT::FixedImage, WebOfferFormT::iLabelWidth, WebOfferFormT::iMaxWidth, WebOfferFormT::iNumFields, WebOfferFormT::iNumRows, WebOfferFormT::iStyle, WebOfferFormT::pValues, WebOfferFormT::strMessage, WebOfferFormT::strName, WebOfferCommandT::strParms, WebOfferFormT::strTitle, WebOfferFormT::strValue, TagFieldFind(), TagFieldFindIdx(), TagFieldGetNumber(), TagFieldGetString(), WEBOFFER_FORM_NUM_FIXED_IMAGE, WEBOFFER_FORM_NUMBUTTONS, WEBOFFER_FORM_NUMFIELDS, WEBOFFER_TAGNAME_BUTTON, and WEBOFFER_TAGNAME_FIXED_IMAGE.
DIRTYCODE_API void WebOfferGetMarketplace (WebOfferT * pOffer, WebOfferMarketplaceT * pInfo)
Extract web offer marketplace parms.
Parameters
pOffer - module state from WebOfferCreate
pInfo - return structure for web form data
Version
06/13/2005 (tdills)
References WebOfferT::Command, WebOfferCommandT::strParms, TagFieldFind(), TagFieldGetNumber(), and WebOfferMarketplaceT::uOfferId.
DIRTYCODE_API const char* WebOfferGetMedia (WebOfferT * pOffer, WebOfferMediaT * pInfo)
Extract media player screen info.
Parameters
pOffer - module state from WebOfferCreate
pInfo - return structure with media data
Returns
Pointer to media list
Version
11/03/2005 gschaefer
References WebOfferT::Command, WebOfferMediaT::pMedia, WebOfferT::pNewsHead, WebOfferMediaT::strImage, WebOfferCommandT::strParms, WebOfferMediaT::strTitle, TagFieldFind(), and TagFieldGetString().
DIRTYCODE_API void WebOfferGetMenu (WebOfferT * pOffer, WebOfferMenuT * pInfo)
Extract menu screen parms.
Parameters
pOffer - module state from WebOfferCreate
pInfo - return structure with menu data
Version
01/07/2005 jfrank
References WebOfferMenuT::Button, WebOfferT::Command, WebOfferCommandT::strParms, WebOfferMenuT::strTitle, TagFieldFind(), TagFieldGetString(), and WEBOFFER_TAGNAME_BUTTON.
DIRTYCODE_API const char* WebOfferGetNews (WebOfferT * pOffer, WebOfferNewsT * pInfo)
Extract news screen parms.
Parameters
pOffer - module state from WebOfferCreate
pInfo - return structure with news data
Returns
Pointer to news blob
Version
03/17/2004 gschaefer
References WebOfferNewsT::Button, WebOfferT::Command, WebOfferNewsT::FixedImage, WebOfferNewsT::iStyle, WebOfferNewsT::NewsColor, WebOfferNewsT::pNews, WebOfferT::pNewsHead, WebOfferNewsT::strImage, WebOfferCommandT::strParms, WebOfferNewsT::strTitle, TagFieldFind(), TagFieldGetNumber(), TagFieldGetString(), WEBOFFER_NEWS_NUM_FIXED_IMAGE, WEBOFFER_NEWS_NUMBUTTONS, WEBOFFER_TAGNAME_BUTTON, and WEBOFFER_TAGNAME_FIXED_IMAGE.
DIRTYCODE_API void WebOfferGetPromo (WebOfferT * pOffer, WebOfferPromoT * pInfo)
Extract promo screen parms.
Parameters
pOffer - module state from WebOfferCreate
pInfo - return structure with promo data
Version
03/13/2004 gschaefer
References WebOfferPromoT::Button, WebOfferT::Command, WebOfferPromoT::FixedImage, WebOfferPromoT::iStyle, WebOfferPromoT::MsgColor, WebOfferPromoT::strMessage, WebOfferCommandT::strParms, WebOfferPromoT::strPromo, WebOfferPromoT::strPromoKPopTitle, WebOfferPromoT::strTitle, TagFieldFind(), TagFieldGetNumber(), TagFieldGetString(), WEBOFFER_PROMO_NUM_FIXED_IMAGE, WEBOFFER_PROMO_NUMBUTTONS, WEBOFFER_TAGNAME_BUTTON, and WEBOFFER_TAGNAME_FIXED_IMAGE.
DIRTYCODE_API const char* WebOfferGetStory (WebOfferT * pOffer, WebOfferStoryT * pInfo)
Extract text story screen info.
Parameters
pOffer - module state from WebOfferCreate
pInfo - return structure with story data
Returns
Pointer to story text
Version
11/03/2005 gschaefer
References WebOfferT::Command, WebOfferT::pNewsHead, WebOfferStoryT::pText, WebOfferStoryT::strImage, WebOfferCommandT::strParms, WebOfferStoryT::strTitle, TagFieldFind(), and TagFieldGetString().
DIRTYCODE_API void WebOfferHttp (WebOfferT * pOffer)
Transfer data to web server.
Parameters
*pOffer - module state from WebOfferCreate
Version
03/13/2004 gschaefer
References WebOfferT::Command, WebOfferT::eState, FALSE, WebOfferCommandT::iCommand, WebOfferT::iHttpSize, WebOfferT::iScript, NetTick(), WebOfferT::pHttpData, WebOfferT::pHttpIncl, WebOfferT::pHttps, ProtoHttpGet(), ProtoHttpPost(), WebOfferT::pScript, ST_FAIL, WebOfferCommandT::strParms, WebOfferT::strSetup, TagFieldFind(), TagFieldFindIdx(), TagFieldGetNumber(), TagFieldGetRaw(), TagFieldGetString(), TagFieldMerge(), TagFieldSetNumber(), TagFieldSetString(), WebOfferT::uDispTime, WebOfferT::uHttpTime, WEBOFFER_CMD_HTTP, and WebOfferClear().
DIRTYCODE_API int32_t WebOfferHttpComplete (WebOfferT * pOffer)
Check on completion status of transfer.
Parameters
*pOffer - module state from WebOfferCreate
Returns
positive=complete w/success, zero=in progress, negative=complete w/unhandled failure
Version
03/13/2004 gschaefer
References WebOfferT::eState, WebOfferT::iHttpSize, WebOfferT::iScript, NetTick(), WebOfferT::pExec, WebOfferT::pHttpData, WebOfferT::pHttpIncl, WebOfferT::pHttpRsrc, WebOfferT::pScript, ST_FAIL, ST_IDLE, WebOfferT::strResult, TagFieldFind(), TagFieldGetString(), WebOfferT::uDispTime, WebOfferT::uHttpTime, and WebOfferUpdate().
DIRTYCODE_API int32_t WebOfferParamList (WebOfferT * pOffer, char * pBuffer, int32_t iLength, const char * pParam, int32_t iIndex)
Extract an item from a parameter list.
Parameters
*pOffer - module state from WebOfferCreate
*pBuffer - pointer to return buffer
iLength - length of string buffer
pParam - param list pointer from command structure
iIndex - index into list
Returns
negative=invalid index, 0=success
Version
03/25/2005 gschaefer
References TagFieldGetDelim().
DIRTYCODE_API int32_t WebOfferResource (WebOfferT * pOffer, WebOfferResourceT * pRsrc, const char * pName)
Return named resource type field.
Parameters
pOffer - module state from WebOfferCreate
pRsrc - resource header to populate
pName - name of resource
Returns
resource type or zero
Version
04/11/2005 gschaefer
References WebOfferResourceT::iSize, WebOfferResourceT::iType, WebOfferResourceT::pData, WebOfferT::pNewsHead, WebOfferT::pNewsTail, WebOfferResourceT::pParm, WebOfferT::pScript, TagFieldFind(), and TagFieldGetToken().
DIRTYCODE_API int32_t WebOfferResultData (WebOfferT * pOffer, char * pBuffer, int32_t iLength)
Return the result of an offer script.
Parameters
*pOffer - module state from WebOfferCreate
*pBuffer - pointer to return buffer for string values (NULL=ignore)
iLength - length of string buffer if supplied
Returns
Script dependent value (0 if not set by script, else atoi of exit string)
Version
01/13/2004 gschaefer
References WebOfferT::strResult, and TagFieldDupl().
DIRTYCODE_API void WebOfferSetCredit (WebOfferT * pOffer, WebOfferCreditT * pInfo)
Store updated credit card data form user.
Parameters
pOffer - module state from WebOfferCreate
pInfo - updated information from user
Version
03/13/2004 gschaefer
References WebOfferT::Command, WebOfferCreditT::iExpiryMonth, WebOfferCreditT::iExpiryYear, WebOfferCreditT::strAddress, WebOfferCreditT::strCardNumber, WebOfferCreditT::strCardType, WebOfferCreditT::strCity, WebOfferCreditT::strCountry, WebOfferCreditT::strEmail, WebOfferCreditT::strFirstName, WebOfferCreditT::strLastName, WebOfferCommandT::strParms, WebOfferCreditT::strPostCode, WebOfferCreditT::strState, TagFieldSetNumber(), and TagFieldSetString().
DIRTYCODE_API void WebOfferSetForm (WebOfferT * pOffer, WebOfferFormT * pInfo)
Store updated web offer form data from user.
Parameters
pOffer - module state from WebOfferCreate
pInfo - updated information from user
Version
05/23/2006 (ozietman)
References WebOfferT::Command, ds_snzprintf(), WebOfferFormT::Fields, WebOfferFormT::iNumFields, WebOfferCommandT::strParms, WebOfferFormT::strValue, and TagFieldSetString().
DIRTYCODE_API void WebOfferSetPromo (WebOfferT * pOffer, WebOfferPromoT * pInfo)
Store updated promo data form user.
Parameters
pOffer - module state from WebOfferCreate
pInfo - updated information from user
Version
03/13/2004 gschaefer
References WebOfferT::Command, WebOfferCommandT::strParms, WebOfferPromoT::strPromo, and TagFieldSetString().
DIRTYCODE_API void WebOfferSetup (WebOfferT * pOffer, WebOfferSetupT * pSetup)
Setup information about the user/product.
Parameters
*pOffer - module state from WebOfferCreate
*pSetup - script to execute
Version
03/13/2004 gschaefer
References WebOfferSetupT::strCountry, WebOfferSetupT::strFavPlyr, WebOfferSetupT::strFavTeam, WebOfferSetupT::strGameRegion, WebOfferSetupT::strLanguage, WebOfferSetupT::strLKey, WebOfferSetupT::strPersona, WebOfferSetupT::strPlatform, WebOfferSetupT::strPrivileges, WebOfferSetupT::strProduct, WebOfferT::strSetup, WebOfferSetupT::strSkuCode, WebOfferSetupT::strSlusCode, WebOfferSetupT::strUID, TagFieldClear, TagFieldSetNumber(), TagFieldSetNumber64(), TagFieldSetString(), WebOfferSetupT::uColor, and WebOfferSetupT::uMemSize.
DIRTYCODE_API void WebOfferUpdate (WebOfferT * pOffer)
Do period update – called by HttpResult automaticallt so most applications don't need to call direct.
Parameters
*pOffer - module state from WebOfferCreate
Version
03/13/2004 gschaefer
References ds_stristr(), WebOfferT::eState, FALSE, WebOfferT::iHttpSize, NetPrintf, WebOfferT::pHttpData, WebOfferT::pHttpIncl, WebOfferT::pHttpRsrc, WebOfferT::pHttps, PROTOHTTP_RECVDONE, ProtoHttpGet(), ProtoHttpRecv(), ProtoHttpStatus(), ProtoHttpUpdate(), WebOfferT::pScript, ST_FAIL, WebOfferT::strSetup, TagFieldFind(), TagFieldGetNumber(), TagFieldGetString(), TagFieldRename(), and WebOfferT::uHttpTime.
Referenced by WebOfferHttpComplete().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:18