DirtySock: CryptMD5
CryptMD5
Crypt
Data Structures
struct CryptMD5T
all fields are PRIVATE
Macros
#define MD5_BINARY_OUT 16
length of binary output
#define MD5_STRING_OUT 33
length of string output
Typedefs
typedef struct CryptMD5T CryptMD5T
Functions
DIRTYCODE_API void CryptMD5Init (CryptMD5T *pContext)
Init the MD5 context.
DIRTYCODE_API void CryptMD5Init2 (CryptMD5T *pContext, int32_t iHashSize)
Init the MD5 context (alternate form)
DIRTYCODE_API void CryptMD5Update (CryptMD5T *pContext, const void *pBuffer, int32_t iLength)
Add data to the MD5 context (hash the data).
DIRTYCODE_API void CryptMD5Final (CryptMD5T *pContext, void *pBuffer, int32_t iLength)
Convert MD5 state into final output form.
Detailed Description
Macro Definition Documentation
#define MD5_BINARY_OUT 16
length of binary output
Referenced by CryptMD5Final(), CryptStp1DecryptHash(), CryptStp1DecryptSize(), CryptStp1EncryptHash(), CryptStp1EncryptSize(), and CryptStp1MakeWallet().
#define MD5_STRING_OUT 33
length of string output
Referenced by CryptMD5Final().
Typedef Documentation
typedef struct CryptMD5T CryptMD5T
Function Documentation
DIRTYCODE_API void CryptMD5Final (CryptMD5T * pContext, void * _pBuffer, int32_t iLength)
Convert MD5 state into final output form.
Parameters
*pContext - the MD5 state (from create)
*_pBuffer - the digest output
iLength - length of output buffer
Version
03/16/02 (GWS)
References MD5_BINARY_OUT, MD5_STRING_OUT, CryptMD5T::strData, CryptMD5T::uCount, and CryptMD5T::uRegs.
Referenced by CryptStp1DecryptHash(), CryptStp1EncryptHash(), and CryptStp1MakeWallet().
DIRTYCODE_API void CryptMD5Init (CryptMD5T * pContext)
Init the MD5 context.
Parameters
*pContext - target MD5 context
Version
03/16/02 (GWS)
References CryptMD5T::uCount, and CryptMD5T::uRegs.
Referenced by CryptMD5Init2(), CryptStp1DecryptHash(), CryptStp1EncryptHash(), and CryptStp1MakeWallet().
DIRTYCODE_API void CryptMD5Init2 (CryptMD5T * pContext, int32_t iHashSize)
Init the MD5 context (alternate form)
Parameters
*pContext - target MD5 context
iHashSize - hash size (unused)
Version
11/05/13 (jbrookes)
References CryptMD5Init().
DIRTYCODE_API void CryptMD5Update (CryptMD5T * pContext, const void * _pBuffer, int32_t iLength)
Add data to the MD5 context (hash the data).
Parameters
*pContext - target MD5 context
*_pBuffer - input data to hash
iLength - length of buffer (-1=treat pBuffer as asciiz)
Version
03/16/02 (GWS)
References ds_memcpy(), CryptMD5T::strData, and CryptMD5T::uCount.
Referenced by CryptStp1DecryptHash(), CryptStp1EncryptHash(), and CryptStp1MakeWallet().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:20