DirtySock: netconnps4.cpp File Reference
netconnps4.cpp File Reference
Provides network setup and teardown support. Does not actually create any kind of network connections.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <libnetctl.h>
#include <libsysmodule.h>
#include <np.h>
#include <np/np_common.h>
#include <user_service.h>
#include <kernel.h>
#include <app_content.h>
#include "DirtySDK/dirtysock.h"
#include "DirtySDK/dirtyvers.h"
#include "DirtySDK/dirtysock/dirtyerr.h"
#include "DirtySDK/dirtysock/dirtymem.h"
#include "DirtySDK/dirtysock/dirtycert.h"
#include "DirtySDK/dirtysock/ps4/netconnps4.h"
#include "DirtySDK/dirtysock/ps4/dirtyeventmanagerps4.h"
#include "DirtySDK/dirtysock/ps4/dirtycontextmanagerps4.h"
#include "DirtySDK/dirtysock/netconn.h"
#include "DirtySDK/proto/protoupnp.h"
#include "netconncommon.h"
#include "IEAUser/IEAUser.h"
Data Structures
struct NetConnExternalCleanupEntryT
struct NetConnUserAuthCodeT
struct NetConnAsyncRequestDataT
struct NetConnParentalControlsT
struct NetConnPsPlusDataT
struct NetConnNpAvailabilityT
struct NetConnUserT
struct NetConnSceNpOnlineIdQueryT
struct NetConnNpStateCallbackDataT
struct NetConnRefT
private module state
Macros
#define NETCONNPS4_SAMPLE_TITLE_ID "NPXX51027_00"
#define NETCONNPS4_CLIENT_ID "33f3a6af-0a39-4c98-9870-bee66f2cbc57"
#define NETCONNPS4_SCOPE_FOR_AUTH_CODE "psn:s2s"
#define NETCONN_EXTERNAL_CLEANUP_LIST_INITIAL_CAPACITY (12)
#define NETCONN_DEFAULT_UPNP_PORT (3659)
UPNP port.
Typedefs
typedef int32_t(* NetConnExternalCleanupCallbackT)(void *pNetConnExternalCleanupData)
typedef struct
NetConnExternalCleanupEntryT NetConnExternalCleanupEntryT
typedef enum NetConnNpRequestStateE NetConnNpRequestStateE
typedef struct NetConnUserAuthCodeT NetConnUserAuthCodeT
typedef struct NetConnRefT NetConnRefT
typedef struct
NetConnAsyncRequestDataT NetConnAsyncRequestDataT
typedef int32_t(* NetConnAsyncRequestT)(NetConnRefT *pRef, int32_t iUserIndex, SceNpOnlineId onlineId, NetConnAsyncRequestDataT *pRequestData)
typedef int32_t(* NetConnAsyncResponseT)(NetConnRefT *pRef, int32_t iUserIndex, void *pBuf, int32_t iBufSize)
typedef struct
NetConnParentalControlsT NetConnParentalControlsT
typedef struct NetConnPsPlusDataT NetConnPsPlusDataT
typedef struct
NetConnNpAvailabilityT NetConnNpAvailabilityT
typedef struct NetConnUserT NetConnUserT
typedef struct
NetConnSceNpOnlineIdQueryT NetConnSceNpOnlineIdQueryT
typedef struct
NetConnNpStateCallbackDataT NetConnNpStateCallbackDataT
Enumerations
enum NetConnNpRequestStateE {
NETCONN_NP_REQUEST_STATE_INVALID = 0,
NETCONN_NP_REQUEST_STATE_FAILED,
NETCONN_NP_REQUEST_STATE_INPROG,
NETCONN_NP_REQUEST_STATE_VALID,
NETCONN_NP_REQUEST_STATE_UNDERAGE
}
Functions
int32_t NetConnStartup (const char *pParams)
Bring the network connection module to life. Creates connection with IOP resources and gets things ready to go. Puts all device drivers into "probe" mode so they look for appropriate hardware. Does not actually start any network activity.
int32_t NetConnQuery (const char *pGamertag, NetConfigRecT *pList, int32_t iListSize)
Returns the index of the given gamertag. If the gamertag is not present, find the index of the SceUserServiceUserId in the pList. Otherwise return the index of the first logged in user.
int32_t NetConnConnect (const NetConfigRecT *pConfig, const char *pOption, int32_t iData)
Used to bring the networking online with a specific configuration. Uses a configuration returned by NetConnQuery.
int32_t NetConnDisconnect (void)
Used to bring down the network connection. After calling this, it would be necessary to call NetConnConnect to bring the connection back up or NetConnShutdown to completely shutdown all network support.
int32_t NetConnControl (int32_t iControl, int32_t iValue, int32_t iValue2, void *pValue, void *pValue2)
Set module behavior based on input selector.
int32_t NetConnStatus (int32_t iKind, int32_t iData, void *pBuf, int32_t iBufSize)
Check general network connection status. Different selectors return different status attributes.
int32_t NetConnShutdown (uint32_t uShutdownFlags)
Shutdown the network code and return to idle state.
void NetConnSleep (int32_t iMilliSecs)
Sleep the application for some number of milliseconds.
void NetConnRegisterNpStateCallback (NetConnNpStateCallbackT *pCallback, void *pUserData)
Use this function to tell netconn about a local user that no longer exists.
int32_t NetConnAddLocalUser (int32_t iLocalUserIndex, const EA::User::IEAUser *pLocalUser)
Use this function to tell netconn about a newly detected local user on the local console.
int32_t NetConnRemoveLocalUser (int32_t iLocalUserIndex, const EA::User::IEAUser *pLocalUser)
Use this function to tell netconn about a local user that no longer exists.
Detailed Description
Provides network setup and teardown support. Does not actually create any kind of network connections.
Attention
Copyright (c) 2012 Electronic Arts Inc.
Version
10/24/2012 (jbrookes) First version; a vanilla port from the Unix version
Macro Definition Documentation
#define NETCONN_DEFAULT_UPNP_PORT (3659)
UPNP port.
Referenced by NetConnConnect(), and NetConnStartup().
#define NETCONN_EXTERNAL_CLEANUP_LIST_INITIAL_CAPACITY (12)
Referenced by NetConnStartup().
#define NETCONNPS4_CLIENT_ID "33f3a6af-0a39-4c98-9870-bee66f2cbc57"
Referenced by NetConnStartup().
#define NETCONNPS4_SAMPLE_TITLE_ID "NPXX51027_00"
Referenced by NetConnStartup().
#define NETCONNPS4_SCOPE_FOR_AUTH_CODE "psn:s2s"
Typedef Documentation
typedef struct NetConnAsyncRequestDataT NetConnAsyncRequestDataT
typedef int32_t(* NetConnAsyncRequestT)(NetConnRefT *pRef, int32_t iUserIndex, SceNpOnlineId onlineId, NetConnAsyncRequestDataT *pRequestData)
typedef int32_t(* NetConnAsyncResponseT)(NetConnRefT *pRef, int32_t iUserIndex, void *pBuf, int32_t iBufSize)
typedef int32_t(* NetConnExternalCleanupCallbackT)(void *pNetConnExternalCleanupData)
typedef struct NetConnExternalCleanupEntryT NetConnExternalCleanupEntryT
typedef struct NetConnNpAvailabilityT NetConnNpAvailabilityT
typedef enum NetConnNpRequestStateE NetConnNpRequestStateE
typedef struct NetConnNpStateCallbackDataT NetConnNpStateCallbackDataT
typedef struct NetConnParentalControlsT NetConnParentalControlsT
typedef struct NetConnPsPlusDataT NetConnPsPlusDataT
typedef struct NetConnRefT NetConnRefT
typedef struct NetConnSceNpOnlineIdQueryT NetConnSceNpOnlineIdQueryT
typedef struct NetConnUserAuthCodeT NetConnUserAuthCodeT
typedef struct NetConnUserT NetConnUserT
Enumeration Type Documentation
enum NetConnNpRequestStateE
Enumerator
NETCONN_NP_REQUEST_STATE_INVALID
NETCONN_NP_REQUEST_STATE_FAILED
NETCONN_NP_REQUEST_STATE_INPROG
NETCONN_NP_REQUEST_STATE_VALID
NETCONN_NP_REQUEST_STATE_UNDERAGE
Function Documentation
int32_t NetConnAddLocalUser (int32_t iLocalUserIndex, const EA::User::IEAUser * pLocalUser)
Use this function to tell netconn about a newly detected local user on the local console.
Parameters
iLocalUserIndex - index at which DirtySDK needs to insert this user it its internal user array
pLocalUser - pointer to associated IEAUser
Returns
int32_t - 0 for success; negative for error
Version
01/16/2014 (mclouatre)
References NetConnCommonAddLocalUser().
void NetConnRegisterNpStateCallback (NetConnNpStateCallbackT * pCallback, void * pUserData)
Use this function to tell netconn about a local user that no longer exists.
Parameters
pCallback - pointer to the function to call
pUserData - user data to pass to the callback
Version
05/11/2015 (amakoukji)
References NetConnCommonGetRef(), NetConnRefT::pNpStateCallback, and NetConnRefT::pNpStateCallbackUserData.
int32_t NetConnRemoveLocalUser (int32_t iLocalUserIndex, const EA::User::IEAUser * pLocalUser)
Use this function to tell netconn about a local user that no longer exists.
Parameters
iLocalUserIndex - index in the internal DirtySDK user array at which the user needs to be cleared
pLocalUser - pointer to associated IEAUser
Returns
int32_t - 0 for success; negative for error
Version
01/16/2014 (mclouatre)
References NetConnCommonRemoveLocalUser().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:13