DirtySock: CommTAPI
CommTAPI
Comm
Typedefs
typedef struct CommTAPIRef CommTAPIRef
basic reference returned/used by all routines
Functions
DIRTYCODE_API CommTAPIRef * CommTAPIConstruct (int32_t maxwid, int32_t maxinp, int32_t maxout)
Construct the class.
DIRTYCODE_API void CommTAPIDestroy (CommTAPIRef *what)
Destruct the class.
DIRTYCODE_API void CommTAPICallback (CommTAPIRef *ref, void(*callback)(CommRef *ref, int32_t event))
Set upper layer callback.
DIRTYCODE_API int32_t CommTAPIResolve (CommTAPIRef *what, const char *addr, char *buf, int32_t len, char div)
Resolve an address.
DIRTYCODE_API void CommTAPIUnresolve (CommTAPIRef *what)
Stop the resolver.
DIRTYCODE_API int32_t CommTAPIListen (CommTAPIRef *what, const char *addr)
Listen for a connection.
DIRTYCODE_API int32_t CommTAPIUnlisten (CommTAPIRef *what)
Stop listening.
DIRTYCODE_API int32_t CommTAPIConnect (CommTAPIRef *what, const char *addr)
Initiate a connection to a peer.
DIRTYCODE_API int32_t CommTAPIUnconnect (CommTAPIRef *what)
Terminate a connection.
DIRTYCODE_API int32_t CommTAPIStatus (CommTAPIRef *what)
Return current stream status.
DIRTYCODE_API uint32_t CommTAPITick (CommTAPIRef *ref)
Return current tick.
DIRTYCODE_API int32_t CommTAPISend (CommTAPIRef *what, const void *buffer, int32_t length)
Send a packet.
DIRTYCODE_API int32_t CommTAPIPeek (CommTAPIRef *what, void *target, int32_t length, uint32_t *when)
Peek at waiting packet.
DIRTYCODE_API int32_t CommTAPIRecv (CommTAPIRef *what, void *target, int32_t length, uint32_t *when)
Receive a packet from the buffer.
Detailed Description
Typedef Documentation
typedef struct CommTAPIRef CommTAPIRef
basic reference returned/used by all routines
Function Documentation
DIRTYCODE_API void CommTAPICallback (CommTAPIRef * ref, void(*)(CommRef *ref, int32_t event) callback)
Set upper layer callback.
Parameters
*ref - reference pointer
*callback - socket generating callback
Returns
None.
Version
1.0 03/10/03 (JLB) Copied from CommSrpCallback()
Referenced by CommTAPIConstruct().
DIRTYCODE_API int32_t CommTAPIConnect (CommTAPIRef * ref, const char * addr)
Initiate a connection to a peer.
Parameters
*ref - module ref
*addr - address in ip-address:port form
Returns
int32_t - negative=error, zero=ok
Note
Does not currently perform dns translation
Version
1.0 02/19/99 (GWS) First Version
References CommTAPIRef::address, COMM_BADADDRESS, COMM_BADSTATE, CommTAPIRef::device, NULL, and CommTAPIRef::state.
Referenced by CommTAPIConstruct().
DIRTYCODE_API CommTAPIRef* CommTAPIConstruct (int32_t maxwid, int32_t maxinp, int32_t maxout)
Construct the class.
Parameters
maxwid - max record width
maxinp - input packet buffer size
maxout - output packet buffer size
Returns
int32_t - zero
Version
1.0 02/19/99 (GWS) First Version
References CommRef::Callback, CommTAPIRef::common, CommSerConstruct(), CommTAPICallback(), CommTAPIConnect(), CommTAPIDestroy(), CommTAPIListen(), CommTAPIPeek(), CommTAPIRecv(), CommTAPIResolve(), CommTAPISend(), CommTAPIStatus(), CommTAPITick(), CommTAPIUnconnect(), CommTAPIUnlisten(), CommTAPIUnresolve(), CommRef::Connect, CommRef::Construct, CommRef::Destroy, CommRef::Listen, CommRef::maxinp, CommRef::maxout, CommRef::maxwid, NULL, CommRef::Peek, CommRef::Recv, CommRef::Resolve, CommRef::Send, CommTAPIRef::state, CommRef::Status, CommTAPIRef::threadid, CommRef::Tick, CommRef::Unconnect, CommRef::Unlisten, and CommRef::Unresolve.
DIRTYCODE_API void CommTAPIDestroy (CommTAPIRef * ref)
Destruct the class.
Parameters
*ref - module ref
Returns
None.
Version
1.0 02/19/99 (GWS) First Version
References CommSerDestroy(), CommTAPIRef::serial, CommTAPIRef::state, CommTAPIRef::tapiref, and CommTAPIRef::threadid.
Referenced by CommTAPIConstruct().
DIRTYCODE_API int32_t CommTAPIListen (CommTAPIRef * ref, const char * addr)
Listen for a connection.
Parameters
*ref - module ref
*addr - port to listen on (only :port portion used)
Returns
int32_t - negative=error, zero=ok
Version
1.0 02/19/99 (GWS) First Version
References CommTAPIRef::address, COMM_BADSTATE, CommTAPIResolve(), CommTAPIRef::device, and CommTAPIRef::state.
Referenced by CommTAPIConstruct().
DIRTYCODE_API int32_t CommTAPIPeek (CommTAPIRef * ref, void * target, int32_t length, uint32_t * when)
Peek at waiting packet.
Parameters
*ref - module ref
*target - target buffer
*length - buffer length
*when - tick received at
Returns
int32_t - negative=nothing pending, else packet length
Version
1.0 02/19/99 (GWS) First Version
References CommSerPeek(), and CommTAPIRef::serial.
Referenced by CommTAPIConstruct().
DIRTYCODE_API int32_t CommTAPIRecv (CommTAPIRef * ref, void * target, int32_t length, uint32_t * when)
Receive a packet from the buffer.
Parameters
*ref - module ref
*target - target buffer
*length - buffer length
*when - tick received at
Returns
int32_t - negative=error, else packet length
Version
1.0 02/19/99 (GWS) First Version
References CommSerRecv(), and CommTAPIRef::serial.
Referenced by CommTAPIConstruct().
DIRTYCODE_API int32_t CommTAPIResolve (CommTAPIRef * ref, const char * addr, char * buf, int32_t len, char div)
Resolve an address.
Parameters
*ref - module ref
*addr - resolve address
*buf - target buffer
len - target length (min 64 bytes)
div - divider char
Returns
int32_t - <0=error, 0=complete (COMM_NOERROR), >0=in progress (COMM_PENDING)
Note
Target list is always double null terminated allowing null to be used as the divider character if desired. when COMM_PENDING is returned, target buffer is set to "~" until completion.
Version
1.0 02/19/99 (GWS) First Version
References COMM_BADPARM, COMM_MINBUFFER, data, CommTAPIRef::devcount, ds_stricmp(), NULL, TAPI_CURRENT_VERSION, and CommTAPIRef::tapiref.
Referenced by CommTAPIConstruct(), and CommTAPIListen().
DIRTYCODE_API int32_t CommTAPISend (CommTAPIRef * ref, const void * buffer, int32_t length)
Send a packet.
Parameters
*ref - module ref
*buffer - pointer to data
*length - length of data
Returns
int32_t - negative=error, zero=ok
Note
Zero length packets may not be sent (they are ignored)
Version
1.0 02/19/99 (GWS) First Version
References CommSerSend(), and CommTAPIRef::serial.
Referenced by CommTAPIConstruct().
DIRTYCODE_API int32_t CommTAPIStatus (CommTAPIRef * ref)
Return current stream status.
Parameters
*ref - module ref
Returns
int32_t - COMM_CONNECTING, COMM_OFFLINE, COMM_ONLINE or COMM_FAILURE
Version
1.0 02/19/99 (GWS) First Version
References COMM_CONNECTING, COMM_FAILURE, COMM_OFFLINE, COMM_ONLINE, CommSerStatus(), CommTAPIRef::serial, and CommTAPIRef::state.
Referenced by CommTAPIConstruct().
DIRTYCODE_API uint32_t CommTAPITick (CommTAPIRef * ref)
Return current tick.
Parameters
*ref - reference pointer
Returns
uint32_t - elapsed milliseconds
Version
1.0 03/10/03 (JLB) Copied from CommSRPTick
References NetTick().
Referenced by CommTAPIConstruct().
DIRTYCODE_API int32_t CommTAPIUnconnect (CommTAPIRef * ref)
Terminate a connection.
Parameters
*ref - module ref
Returns
int32_t - negative=error, zero=ok
Version
1.0 02/19/99 (GWS) First Version
References CommSerUnconnect(), CommTAPIRef::lineref, CommTAPIRef::serial, and CommTAPIRef::state.
Referenced by CommTAPIConstruct().
DIRTYCODE_API int32_t CommTAPIUnlisten (CommTAPIRef * ref)
Stop listening.
Parameters
*ref - module ref
Returns
int32_t - negative=error, zero=ok
Version
1.0 02/19/99 (GWS) First Version
References CommSerUnlisten(), and CommTAPIRef::serial.
Referenced by CommTAPIConstruct().
DIRTYCODE_API void CommTAPIUnresolve (CommTAPIRef * ref)
Stop the resolver.
Parameters
*ref - module ref
Returns
None
Note
Target list is always double null terminated allowing null to be used as the divider character if desired. when COMM_PENDING is returned, target buffer is set to "~" until completion.
Version
1.0 02/19/99 (GWS) First Version
Referenced by CommTAPIConstruct().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:43