DirtySock: PrivilegeApi
PrivilegeApi
User
Macros
#define PRIVILEGEAPI_STATUS_NONE (0x0000)
#define PRIVILEGEAPI_STATUS_IN_PROGRESS (0x0001)
#define PRIVILEGEAPI_STATUS_GRANTED (0x0002)
#define PRIVILEGEAPI_STATUS_GRANTED_FRIENDS_ONLY (0x0004)
#define PRIVILEGEAPI_STATUS_RESTRICTED (0x0008)
#define PRIVILEGEAPI_STATUS_BANNED (0x0010)
#define PRIVILEGEAPI_STATUS_PURCHASE_REQUIRED (0x0020)
#define PRIVILEGEAPI_STATUS_ABORTED (0x0040)
#define PRIVILEGEAPI_STATUS_ERROR (0x0080)
#define PRIVILEGEAPI_STATUS_ADDITIONAL_CHECKS_REQUIRED (0x0100)
#define PRIVILEGEAPI_STATUS_UNDERAGE (0x0200)
Typedefs
typedef struct PrivilegeApiRefT PrivilegeApiRefT
typedef enum PrivilegeApiPrivT PrivilegeApiPrivT
Enumerations
enum PrivilegeApiPrivT {
PRIVILEGEAPI_PRIV_INVALID = (0),
PRIVILEGEAPI_PRIV_COMMUNICATION_VOICE_INGAME = (-1),
PRIVILEGEAPI_PRIV_COMMUNICATION_VOICE_SKYPE = (-2),
PRIVILEGEAPI_PRIV_VIDEO_COMMUNICATIONS = (-3),
PRIVILEGEAPI_PRIV_COMMUNICATIONS = (-4),
PRIVILEGEAPI_PRIV_USER_CREATED_CONTENT = (-5),
PRIVILEGEAPI_PRIV_MULTIPLAYER_SESSIONS_REALTIME = (-6),
PRIVILEGEAPI_PRIV_DOWNLOAD_FREE_CONTENT = (-7),
PRIVILEGEAPI_PRIV_FITNESS_UPLOAD = (-8),
PRIVILEGEAPI_PRIV_VIEW_FRIENDS_LIST = (-9),
PRIVILEGEAPI_PRIV_SHARE_KINECT_CONTENT = (-10),
PRIVILEGEAPI_PRIV_MULTIPLAYER_PARTIES = (-11),
PRIVILEGEAPI_PRIV_CLOUD_GAMING_MANAGE_SESSION = (-12),
PRIVILEGEAPI_PRIV_CLOUD_GAMING_JOIN_SESSION = (-13),
PRIVILEGEAPI_PRIV_CLOUD_SAVED_GAMES = (-14),
PRIVILEGEAPI_PRIV_PREMIUM_CONTENT = (-15),
PRIVILEGEAPI_PRIV_INTERNET_BROWSER = (-16),
PRIVILEGEAPI_PRIV_SUBSCRIPTION_CONTENT = (-17),
PRIVILEGEAPI_PRIV_PREMIUM_VIDEO = (-18),
PRIVILEGEAPI_PRIV_GAME_DVR = (-19),
PRIVILEGEAPI_PRIV_SOCIAL_NETWORK_SHARING = (-20),
PRIVILEGEAPI_PRIV_PURCHASE_CONTENT = (-21),
PRIVILEGEAPI_PRIV_PROFILE_VIEWING = (-22),
PRIVILEGEAPI_PRIV_PRESENCE = (-23),
PRIVILEGEAPI_PRIV_CONTENT_AUTHOR = (-24),
PRIVILEGEAPI_PRIV_UNSAFE_PROGRAMMING = (-25),
PRIVILEGEAPI_PRIV_MULTIPLAYER_SESSIONS_ASYNC = (-26),
PRIVILEGEAPI_PRIV_ONLINE_ACCESS = (-27),
PRIVILEGEAPI_PRIV_EA_ACCESS = (256)
}
Functions
DIRTYCODE_API PrivilegeApiRefT * PrivilegeApiCreate (void)
Create the PrivilegeApi.
DIRTYCODE_API int32_t PrivilegeApiDestroy (PrivilegeApiRefT *pRef)
Destroy the PrivilegeApi.
DIRTYCODE_API int32_t PrivilegeApiCheckPrivilegesAsync (PrivilegeApiRefT *pRef, int32_t iUserIndex, const PrivilegeApiPrivT *pPrivileges, int32_t iPrivilegeCount, int32_t *pHint)
Check one or more privileges against the system or the first party service for an authorotative determination of the current privilege status. No UI is shown when using this function.
DIRTYCODE_API int32_t PrivilegeApiCheckPrivilegesAsyncWithUi (PrivilegeApiRefT *pRef, int32_t iUserIndex, const PrivilegeApiPrivT *pPrivileges, int32_t iPrivilegeCount, int32_t *pHint, const char *pUiMessage)
Check one or more privileges against the system or the first party service for an authorotative determination of the current privilege status. This function will show appropriate error messages or commerce dialog to upsell product/privileges to the user.
DIRTYCODE_API int32_t PrivilegeApiCheckResult (PrivilegeApiRefT *pRef, int32_t iRequestId)
Gets the current status of an active privilege check started with one of the PrivilegeApiCheckPrivilegesAsync() functions.
DIRTYCODE_API int32_t PrivilegeApiReleaseRequest (PrivilegeApiRefT *pRef, int32_t iRequestId)
Must be called after you are done with a request id returned from PrivilegeApiCheckPrivilegesAsync() or PrivilegeApiCheckPrivilegesAsyncWithUi().
DIRTYCODE_API int32_t PrivilegeApiAbort (PrivilegeApiRefT *pRef, int32_t iRequestId)
Aborts and releases a request.
Detailed Description
Macro Definition Documentation
#define PRIVILEGEAPI_STATUS_ABORTED (0x0040)
Referenced by PrivilegeApiCheckResult().
#define PRIVILEGEAPI_STATUS_ADDITIONAL_CHECKS_REQUIRED (0x0100)
Referenced by PrivilegeApiCheckPrivilegesAsyncWithUi(), and PrivilegeApiCheckResult().
#define PRIVILEGEAPI_STATUS_BANNED (0x0010)
Referenced by PrivilegeApiCheckResult().
#define PRIVILEGEAPI_STATUS_ERROR (0x0080)
Referenced by PrivilegeApiCheckResult().
#define PRIVILEGEAPI_STATUS_GRANTED (0x0002)
Referenced by PrivilegeApiCheckPrivilegesAsyncWithUi(), and PrivilegeApiCheckResult().
#define PRIVILEGEAPI_STATUS_GRANTED_FRIENDS_ONLY (0x0004)
#define PRIVILEGEAPI_STATUS_IN_PROGRESS (0x0001)
Referenced by PrivilegeApiReleaseRequest().
#define PRIVILEGEAPI_STATUS_NONE (0x0000)
Referenced by PrivilegeApiAbort(), PrivilegeApiCheckResult(), PrivilegeApiDestroy(), and PrivilegeApiReleaseRequest().
#define PRIVILEGEAPI_STATUS_PURCHASE_REQUIRED (0x0020)
Referenced by PrivilegeApiCheckResult().
#define PRIVILEGEAPI_STATUS_RESTRICTED (0x0008)
Referenced by PrivilegeApiCheckPrivilegesAsyncWithUi(), and PrivilegeApiCheckResult().
#define PRIVILEGEAPI_STATUS_UNDERAGE (0x0200)
Typedef Documentation
typedef enum PrivilegeApiPrivT PrivilegeApiPrivT
typedef struct PrivilegeApiRefT PrivilegeApiRefT
Enumeration Type Documentation
enum PrivilegeApiPrivT
Enumerator
PRIVILEGEAPI_PRIV_INVALID
PRIVILEGEAPI_PRIV_COMMUNICATION_VOICE_INGAME
PRIVILEGEAPI_PRIV_COMMUNICATION_VOICE_SKYPE
PRIVILEGEAPI_PRIV_VIDEO_COMMUNICATIONS
PRIVILEGEAPI_PRIV_COMMUNICATIONS
PRIVILEGEAPI_PRIV_USER_CREATED_CONTENT
PRIVILEGEAPI_PRIV_MULTIPLAYER_SESSIONS_REALTIME
PRIVILEGEAPI_PRIV_DOWNLOAD_FREE_CONTENT
PRIVILEGEAPI_PRIV_FITNESS_UPLOAD
PRIVILEGEAPI_PRIV_VIEW_FRIENDS_LIST
PRIVILEGEAPI_PRIV_SHARE_KINECT_CONTENT
PRIVILEGEAPI_PRIV_MULTIPLAYER_PARTIES
PRIVILEGEAPI_PRIV_CLOUD_GAMING_MANAGE_SESSION
PRIVILEGEAPI_PRIV_CLOUD_GAMING_JOIN_SESSION
PRIVILEGEAPI_PRIV_CLOUD_SAVED_GAMES
PRIVILEGEAPI_PRIV_PREMIUM_CONTENT
PRIVILEGEAPI_PRIV_INTERNET_BROWSER
PRIVILEGEAPI_PRIV_SUBSCRIPTION_CONTENT
PRIVILEGEAPI_PRIV_PREMIUM_VIDEO
PRIVILEGEAPI_PRIV_GAME_DVR
PRIVILEGEAPI_PRIV_SOCIAL_NETWORK_SHARING
PRIVILEGEAPI_PRIV_PURCHASE_CONTENT
PRIVILEGEAPI_PRIV_PROFILE_VIEWING
PRIVILEGEAPI_PRIV_PRESENCE
PRIVILEGEAPI_PRIV_CONTENT_AUTHOR
PRIVILEGEAPI_PRIV_UNSAFE_PROGRAMMING
PRIVILEGEAPI_PRIV_MULTIPLAYER_SESSIONS_ASYNC
PRIVILEGEAPI_PRIV_ONLINE_ACCESS
PRIVILEGEAPI_PRIV_EA_ACCESS
Function Documentation
DIRTYCODE_API int32_t PrivilegeApiAbort (PrivilegeApiRefT * pRef, int32_t iRequestId)
Aborts and releases a request.
Parameters
*pRef - the module reference
iRequestId - the request id
Returns
int32_t - >=0 = success, <0 = error
Version
09/02/2013 (mcorcoran)
References PrivilegeApiRefT::aAsyncRequests, PrivilegeApiAsyncRequestT::iStatus, NetPrintf, PRIVILEGEAPI_STATUS_NONE, PrivilegeApiCheckResult(), PrivilegeApiReleaseRequest(), and PrivilegeApiAsyncRequestT::refAsyncOp.
Referenced by PrivilegeApiCheckPrivilegesAsyncWithUi(), and PrivilegeApiDestroy().
DIRTYCODE_API int32_t PrivilegeApiCheckPrivilegesAsync (PrivilegeApiRefT * pRef, int32_t iUserIndex, const PrivilegeApiPrivT * pPrivileges, int32_t iPrivilegeCount, int32_t * pHint)
Check one or more privileges against the system or the first party service for an authorotative determination of the current privilege status. No UI is shown when using this function.
Parameters
*pRef - the module reference
iUserIndex - user index
*pPrivileges - array of privileges
iPrivilegeCount - the numnber of privileges pointed to by pPrivileges
*pHint - (optional, out) if provided, pHint will be filled with a non-authoratative result for the privilege check. Unless the return value is zero (0), in which case, this value can be considered autorotative.
Returns
int32_t - <0 = error, 0 = success, use *pHint for the result, >0 = the request id to pass into PrivilegeApiCheckResult()
Version
09/02/2013 (mcorcoran)
References PrivilegeApiCheckPrivilegesAsyncWithUi().
DIRTYCODE_API int32_t PrivilegeApiCheckPrivilegesAsyncWithUi (PrivilegeApiRefT * pRef, int32_t iUserIndex, const PrivilegeApiPrivT * pPrivileges, int32_t iPrivilegeCount, int32_t * pHint, const char * pUiMessage)
Check one or more privileges against the system or the first party service for an authorotative determination of the current privilege status. This function will show appropriate error messages or commerce dialog to upsell product/privileges to the user.
Parameters
*pRef - the module reference
iUserIndex - user index
*pPrivileges - array of privileges
iPrivilegeCount - the numnber of privileges pointed to by pPrivileges
*pHint - (optional, out) if provided, pHint will be filled with a non-authoratative result for the privilege check. Unless the return value is zero (0), in which case, this value can be considered autorotative.
*pUiMessage - this parameter should be non-NULL for the UI functionality to be enabled, otherwise, no UI is displayed. However, the value of the string is not used on PS4.
Returns
int32_t - <0 = error, 0 = success, use *pHint for the result, >0 = the request id to pass into PrivilegeApiCheckResult()
Version
09/02/2013 (mcorcoran)
References PrivilegeApiRefT::aAsyncRequests, PrivilegeApiAsyncRequestT::bAdditionalChecks, DirtyMemAlloc(), DirtyMemFree(), PrivilegeApiRefT::iMemGroup, PrivilegeApiAsyncRequestT::iStatus, NetConnStatus(), NetPrintf, PrivilegeApiRefT::pMemGroupUserData, PRIVILEGEAPI_MEMID, PRIVILEGEAPI_PRIV_INVALID, PRIVILEGEAPI_STATUS_ADDITIONAL_CHECKS_REQUIRED, PRIVILEGEAPI_STATUS_GRANTED, PRIVILEGEAPI_STATUS_RESTRICTED, PrivilegeApiAbort(), and PrivilegeApiAsyncRequestT::refAsyncOp.
Referenced by PrivilegeApiCheckPrivilegesAsync().
DIRTYCODE_API int32_t PrivilegeApiCheckResult (PrivilegeApiRefT * pRef, int32_t iRequestId)
Gets the current status of an active privilege check started with one of the PrivilegeApiCheckPrivilegesAsync() functions.
Parameters
*pRef - the module reference
iRequestId - the request id returned from PrivilegeApiCheckPrivilegesAsync() or PrivilegeApiCheckPrivilegesAsyncWithUi()
Returns
int32_t - <0 = error, >=0 = one or more of the PRIVILEGEAPI_STATUS_* flags
Version
09/02/2013 (mcorcoran)
References PrivilegeApiRefT::aAsyncRequests, PrivilegeApiAsyncRequestT::bAdditionalChecks, PrivilegeApiAsyncRequestT::iStatus, NetPrintf, PRIVILEGEAPI_STATUS_ABORTED, PRIVILEGEAPI_STATUS_ADDITIONAL_CHECKS_REQUIRED, PRIVILEGEAPI_STATUS_BANNED, PRIVILEGEAPI_STATUS_ERROR, PRIVILEGEAPI_STATUS_GRANTED, PRIVILEGEAPI_STATUS_NONE, PRIVILEGEAPI_STATUS_PURCHASE_REQUIRED, PRIVILEGEAPI_STATUS_RESTRICTED, and PrivilegeApiAsyncRequestT::refAsyncOp.
Referenced by PrivilegeApiAbort().
DIRTYCODE_API PrivilegeApiRefT* PrivilegeApiCreate (void)
Create the PrivilegeApi.
Returns
PrivilegeApiRefT - the module reference, or NULL on error
Version
09/02/2013 (mcorcoran)
References DirtyMemAlloc(), DirtyMemGroupQuery(), PrivilegeApiRefT::iMemGroup, NetPrintf, PrivilegeApiRefT::pMemGroupUserData, pRef, and PRIVILEGEAPI_MEMID.
DIRTYCODE_API int32_t PrivilegeApiDestroy (PrivilegeApiRefT * pRef)
Destroy the PrivilegeApi.
Parameters
*pRef - the module reference
Returns
int32_t - <0 = error, >=0 = success
Version
09/02/2013 (mcorcoran)
References PrivilegeApiRefT::aAsyncRequests, DirtyMemFree(), PrivilegeApiRefT::iMemGroup, PrivilegeApiAsyncRequestT::iStatus, PrivilegeApiRefT::pMemGroupUserData, PRIVILEGEAPI_MAX_ASYNC_REQUESTS, PRIVILEGEAPI_MEMID, PRIVILEGEAPI_STATUS_NONE, and PrivilegeApiAbort().
DIRTYCODE_API int32_t PrivilegeApiReleaseRequest (PrivilegeApiRefT * pRef, int32_t iRequestId)
Must be called after you are done with a request id returned from PrivilegeApiCheckPrivilegesAsync() or PrivilegeApiCheckPrivilegesAsyncWithUi().
Parameters
*pRef - the module reference
iRequestId - the request id
Returns
int32_t - >=0 = success, <0 = error
Version
09/02/2013 (mcorcoran)
References PrivilegeApiRefT::aAsyncRequests, PrivilegeApiAsyncRequestT::bAdditionalChecks, FALSE, PrivilegeApiAsyncRequestT::iStatus, NetPrintf, PRIVILEGEAPI_STATUS_IN_PROGRESS, PRIVILEGEAPI_STATUS_NONE, and PrivilegeApiAsyncRequestT::refAsyncOp.
Referenced by PrivilegeApiAbort().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:34:37