DirtySock: DirtyLib
DirtyLib
DirtySock
Data Structures
struct NetCritT
critical section definition
Macros
#define DIRTYCODE_LOGGING (0)
#define NetPrintf(_x) { }
#define NetPrintfVerbose(_x) { }
#define NetPrintArray(_pMem, _iSize, _pTitle) { }
#define NetPrintMem(_pMem, _iSize, _pTitle) { }
#define NetPrintWrap(_pString, _iWrapCol) { }
#define NetTimeStampEnable(_bEnableTimeStamp) { }
#define NET_SHUTDOWN_NETACTIVE (1)
leave network active in preparation for launching to account management (Xbox 360 only)
#define NET_SHUTDOWN_THREADSTARVE (2)
special shutdown mode for PS3 that starves threads, allowing for quick exit to XMB
#define DIRTY_TOKEN_PASTE(a, b) a ## b
#define DIRTY_CONCATENATE_HELPER(a, b) DIRTY_TOKEN_PASTE(a,b)
#define NetTickDiff(_uNewTime, _uOldTime) ((signed)((_uNewTime) - (_uOldTime)))
Typedefs
typedef struct NetCritT NetCritT
critical section definition
Functions
DIRTYCODE_API void NetLibCommonInit (void)
NetLib platform-common initialization.
DIRTYCODE_API void NetLibCommonShutdown (void)
NetLib platform-common shutdown.
DIRTYCODE_API void NetIdleReset (void)
Reset idle function count.
DIRTYCODE_API void NetIdleAdd (void(*proc)(void *ref), void *ref)
DIRTYCODE_API void NetIdleDel (void(*proc)(void *ref), void *ref)
DIRTYCODE_API void NetIdleDone (void)
Make sure all idle calls have completed.
DIRTYCODE_API void NetIdleCall (void)
Call all of the functions in the idle list.
DIRTYCODE_API int32_t NetHash (const char *pString)
Calculate a unique 32-bit hash based on the given input string.
DIRTYCODE_API int32_t NetHashBin (const void *pBuffer, uint32_t uLength)
Calculate a unique 32-bit hash based on the given buffer.
DIRTYCODE_API uint32_t NetRand (uint32_t uLimit)
A simple pseudo-random sequence generator. The sequence is implicitly seeded in the first call with the millisecond tick count at the time of the call.
DIRTYCODE_API void NetTimeStampEnableCode (uint8_t bEnableTimeStamp)
DIRTYCODE_API void NetPrintfHook (int32_t(*pPrintfDebugHook)(void *pParm, const char *pText), void *pParm)
DIRTYCODE_API int32_t NetPrintfCode (const char *fmt,...)
DIRTYCODE_API void NetPrintfVerboseCode (int32_t iVerbosityLevel, int32_t iCheckLevel, const char *pFormat,...)
DIRTYCODE_API void NetPrintWrapCode (const char *pData, int32_t iWrapCol)
DIRTYCODE_API void NetPrintMemCode (const void *pMem, int32_t iSize, const char *pTitle)
DIRTYCODE_API void NetPrintArrayCode (const void *pMem, int32_t iSize, const char *pTitle)
DIRTYCODE_API void NetLibCreate (int32_t iThreadPrio, int32_t iThreadStackSize, int32_t iThreadCpuAffinity)
Initialize the network library functions.
DIRTYCODE_API void NetLibDestroy (uint32_t uShutdownFlags)
Destroy the network lib.
DIRTYCODE_API uint32_t NetTick (void)
Return some kind of increasing tick count with millisecond scale (does not need to have millisecond precision, but higher precision is better).
DIRTYCODE_API uint64_t NetTickUsec (void)
Return increasing tick count in microseconds. Used for performance timing purposes.
DIRTYCODE_API void NetCritInit (NetCritT *pCrit, const char *pCritName)
Initialize a critical section for use. Call must have persistant storage defined for lifetime of critical section.
DIRTYCODE_API void NetCritKill (NetCritT *pCrit)
Release resources and destroy critical section. Not currently used (no resources to release)
DIRTYCODE_API int32_t NetCritTry (NetCritT *pCrit)
Attempt to gain access to critical section. Always returns immediately regadless of access status. A thread that already has access to a critical section can always receive repeated access to it.
DIRTYCODE_API void NetCritEnter (NetCritT *pCrit)
Enter a critical section, blocking if needed. If implemented under a non-threaded O/S, then there should never be a reason for this routine to want to block.
DIRTYCODE_API void NetCritLeave (NetCritT *pCrit)
Leave a critical section. Must be called once for every NetCritEnter (or successful NetCritTry).
Detailed Description
Macro Definition Documentation
#define DIRTY_CONCATENATE_HELPER (a, b) DIRTY_TOKEN_PASTE(a,b)
#define DIRTY_TOKEN_PASTE (a, b) a ## b
#define DIRTYCODE_LOGGING (0)
#define NET_SHUTDOWN_NETACTIVE (1)
leave network active in preparation for launching to account management (Xbox 360 only)
#define NET_SHUTDOWN_THREADSTARVE (2)
special shutdown mode for PS3 that starves threads, allowing for quick exit to XMB
#define NetPrintArray (_pMem, _iSize, _pTitle) { }
Referenced by CryptArc4StringEncryptStaticCode().
#define NetPrintf (_x) { }
Referenced by CommSRPConnect(), CommSRPListen(), CommSRPPeek(), CommSRPResolve(), CommSRPSend(), CommTCPConnect(), CommTCPListen(), CommTCPResolve(), CommTCPSend(), CommUDPConnect(), CommUDPControl(), CommUDPListen(), CommUDPResolve(), CommUDPSend(), ConnApiAddClient(), ConnApiConnect(), ConnApiControl(), ConnApiCreate2(), ConnApiDisconnect(), ConnApiOnline(), ConnApiStatus2(), CryptAesInitKeySchedule(), CryptArc4StringEncryptStaticCode(), CryptGcmDecrypt(), CryptGcmEncrypt(), CryptHmacCalcMulti(), CryptMD2Final(), CryptRandGet(), CryptRandInit(), CryptRSAInit(), CryptSha2Init(), DirtyAddrToHostAddr(), DirtyCertCAPreloadCerts(), DirtyCertCARequestCert(), DirtyCertCARequestDone(), DirtyCertCARequestFree(), DirtyCertControl(), DirtyCertCreate(), DirtyCertDestroy(), DirtyCertStatus(), DirtyGraphCreate(), DirtyGraphDecodeHeader(), DirtyGraphDecodeImage(), DirtyJpgCreate(), DirtyMemGroupEnter(), DirtyMemGroupLeave(), DirtyPngCreate(), DirtyPngDecodeImage(), HttpManagerAlloc(), HttpManagerControl(), HttpManagerCreate(), HttpManagerFree(), HttpManagerRecv(), HttpManagerRecvAll(), HttpManagerSend(), HttpManagerSetBaseUrl(), HttpManagerStatus(), LobbyLanControl(), LobbyLanCreate2(), LobbyLanCreateGame(), LobbyLanJoinGame(), LobbyLanJoinGameByIndex(), LobbyLanLeaveGame(), LobbyLanRecvfrom(), LobbyLanReset(), LobbyLanSendto(), LobbyLanSetNote(), LobbyLanSetPlyrNote(), LobbyLanStartGame(), NetConnConnect(), NetConnControl(), NetConnDirtyCertCreate(), NetConnGetEnvStr(), NetConnIdleAdd(), NetConnIdleDel(), NetConnIdleShutdown(), NetConnSetMachineId(), NetConnStartup(), NetConnStatus(), NetGameDistCreate(), NetGameDistInputLocalMulti(), NetGameDistInputQueryMulti(), NetGameDistMetaSetup(), NetGameDistMultiSetup(), NetGameDistServAddClient(), NetGameDistServControl(), NetGameDistServCreate(), NetGameDistServDelClient(), NetGameDistServDiscClient(), NetGameDistServStartGame(), NetGameDistServStopGame(), NetGameDistServUpdate(), NetGameDistServUpdateClient(), NetGameDistUpdate(), NetGameLinkControl(), NetGameLinkCreate(), NetGameLinkCreateStream(), NetGameLinkSend(), NetGameUtilComplete(), NetGameUtilConnect(), NetGameUtilControl(), NetGameUtilCreate(), NetIdleAdd(), NetIdleDel(), NetLibCreate(), NetResourceCancel(), NetResourceCreate(), PingManagerCancelServerRequest(), PingManagerCreate(), PingManagerPingAddress(), PingManagerPingServer2(), PingManagerUpdate(), ProtoAdvtAnnounce(), ProtoHttpCreate(), ProtoHttpRecvAll(), ProtoHttpRequestCb(), ProtoHttpUpdate(), ProtoMangleConnectSocket(), ProtoMangleCreate(), ProtoMangleDestroy(), ProtoMangleUpdate(), ProtoPingControl(), ProtoPingCreate(), ProtoSSLConnect(), ProtoSSLControl(), ProtoSSLCreate(), ProtoSSLShutdown(), ProtoSSLStartup(), ProtoSSLValidateAllCA(), ProtoStreamControl(), ProtoStreamCreate(), ProtoStreamPause(), ProtoStreamRead(), ProtoTunnelAlloc(), ProtoTunnelControl(), ProtoTunnelCreate(), ProtoTunnelFree2(), ProtoTunnelStatus(), ProtoTunnelUpdatePortList(), ProtoUdpCreate(), ProtoUpnpControl(), ProtoUpnpCreate(), ProtoUpnpUpdate(), ProtoWebSocketCreate(), ProtoWebSocketUpdate(), QosApiCreate(), QosApiGetNatType(), QosApiServiceRequest(), SocketAccept(), SocketAddrMapAddress(), SocketAddrMapTranslate(), SocketAddrRemapAddress(), SocketAddrUnmapAddress(), SocketBind(), SocketControl(), SocketCreate(), SocketDestroy(), SocketHost(), SocketHostnameCacheCreate(), SocketInfo(), SocketLookup(), SocketPacketQueueAdd(), SocketPacketQueueAlloc(), SocketPacketQueueControl(), SocketPacketQueueCreate(), SocketPacketQueueRem(), SocketPacketQueueResize(), SocketRateUpdate(), SocketSendCallbackAdd(), SocketSendCallbackInvoke(), SocketSendCallbackRem(), SocketSendto(), VoipActivateLocalUser(), VoipCodecControl(), VoipCodecCreate(), VoipCodecDecode(), VoipCodecEncode(), VoipCodecRegister(), VoipCodecStatus(), VoipCommonApplyChannelConfig(), VoipCommonControl(), VoipCommonProcessChannelChange(), VoipCommonResetChannels(), VoipCommonSelectChannel(), VoipCommonSetMask(), VoipCommonStartup(), VoipCommonStatus(), VoipConduitReceiveVoiceData(), VoipConduitRegisterUser(), VoipConnectionAddSessionId(), VoipConnectionDeleteSessionId(), VoipConnectionRemove(), VoipConnectionSend(), VoipConnectionShutdown(), VoipConnectionStart(), VoipConnectionStartup(), VoipConnectionStop(), VoipControl(), VoipGroupActivateLocalUser(), VoipGroupConnect2(), VoipGroupControl(), VoipGroupDisconnect(), VoipGroupResume2(), VoipGroupSuspend(), VoipHeadsetControl(), VoipHeadsetCreate(), VoipHeadsetReceiveVoiceDataCb(), VoipMixerAccumulate(), VoipMixerCreate(), VoipSetLocalUser(), VoipShutdown(), VoipStartup(), VoipTunnelClientListAdd2(), VoipTunnelClientListDel(), VoipTunnelClientRefreshSendMask(), VoipTunnelControl(), VoipTunnelCreate(), VoipTunnelGameListAdd2(), VoipTunnelGameListDel(), VoipTunnelStatus(), WebLogCreate(), WebLogStart(), WebLogStop(), and WebOfferUpdate().
#define NetPrintfVerbose (_x) { }
Referenced by HttpManagerAlloc(), HttpManagerControl(), HttpManagerDestroy(), HttpManagerFree(), HttpManagerRecv(), HttpManagerUpdate(), NetGameDistInputLocalMulti(), NetGameDistInputPeek(), NetGameDistInputQueryMulti(), NetGameDistServAddClient(), NetGameDistServUpdate(), NetGameDistUpdate(), ProtoHttpCheckKeepAlive(), ProtoHttpControl(), ProtoHttpSetBaseUrl(), ProtoHttpUpdate(), ProtoSSLControl(), ProtoStreamRead(), ProtoWebSocketConnect(), ProtoWebSocketUpdate(), QosApiCancelRequest(), QosApiControl(), QosApiStatus(), SocketAddrMapAddress(), SocketAddrMapTranslate(), SocketConnect(), SocketControl(), SocketCreate(), SocketHostnameAddRef(), SocketHostnameCacheAdd(), SocketHostnameCacheDel(), SocketHostnameCacheGet(), SocketInfo(), SocketPacketQueueAdd(), SocketPacketQueueAlloc(), SocketPacketQueueRem(), SocketRateThrottle(), VoipConduitReceiveVoiceData(), and VoipHeadsetReceiveVoiceDataCb().
#define NetPrintMem (_pMem, _iSize, _pTitle) { }
Referenced by CryptGcmDecrypt(), CryptGcmEncrypt(), and CryptRandGet().
#define NetPrintWrap (_pString, _iWrapCol) { }
Referenced by ProtoMangleUpdate(), and ProtoWebSocketUpdate().
#define NetTickDiff (_uNewTime, _uOldTime) ((signed)((_uNewTime) - (_uOldTime)))
Referenced by HttpManagerRecv(), HttpManagerUpdate(), NetConnIdle(), NetGameDistServStatus(), NetGameDistServUpdate(), ProtoHttpServUpdate(), ProtoHttpUpdate(), ProtoStreamUpdate(), ProtoTunnelUpdate(), ProtoUpnpUpdate(), ProtoWebSocketUpdate(), SocketHostnameCacheGet(), SocketPacketQueueRem(), SocketRateUpdate(), VoipConnectionSend(), and VoipConnectionUpdate().
#define NetTimeStampEnable (_bEnableTimeStamp) { }
Typedef Documentation
typedef struct NetCritT NetCritT
critical section definition
Function Documentation
DIRTYCODE_API void NetCritEnter (NetCritT * pCrit)
Enter a critical section, blocking if needed. If implemented under a non-threaded O/S, then there should never be a reason for this routine to want to block.
Parameters
*pCrit - critical section marker
Version
11/15/1999 (gschaefer)
References NetCritPrivT::access, NetCritPrivT::csect, NetCritPrivT::locked, NetCritTry(), and NetCritPrivT::thread.
Referenced by CommUDPCallback(), CommUDPSend(), DirtyCertCAPreloadCerts(), DirtyCertCARequestCert(), DirtyCertCARequestDone(), DirtyCertCARequestFree(), DirtyCertControl(), DirtyCertStatus(), NetGameLinkRecv2(), NetGameLinkSend(), NetIdleDone(), ProtoAdvtAnnounce(), ProtoAdvtCancel(), ProtoAdvtConstruct(), ProtoAdvtDestroy(), ProtoHttpAbort(), ProtoHttpRecv(), ProtoHttpSend(), ProtoHttpUpdate(), ProtoPingResponse(), ProtoSSLRecv(), ProtoSSLSend(), ProtoSSLUpdate(), ProtoTunnelAlloc(), ProtoTunnelControl(), ProtoTunnelFree2(), ProtoTunnelStatus(), ProtoTunnelUpdate(), ProtoTunnelUpdatePortList(), ProtoUdpRecvFrom(), QosApiCancelRequest(), QosApiControl(), QosApiDestroy(), QosApiServiceRequest(), QosApiStatus(), SocketBind(), SocketControl(), SocketHostnameAddRef(), SocketHostnameCacheAdd(), SocketHostnameCacheDel(), SocketHostnameCacheGet(), SocketImport(), SocketInfo(), SocketRecvfrom(), VoipActivateLocalUser(), VoipCommonControl(), VoipConnect(), VoipConnectionAddSessionId(), VoipConnectionDeleteSessionId(), VoipConnectionStart(), VoipConnectionUpdate(), VoipControl(), VoipDisconnect2(), VoipGroupMuteByConnId2(), VoipHeadsetControl(), VoipRemove(), VoipSetLocalUser(), WebLogPrintf(), and WebLogUpdate().
DIRTYCODE_API void NetCritInit (NetCritT * pCrit, const char * pCritName)
Initialize a critical section for use. Call must have persistant storage defined for lifetime of critical section.
Parameters
*pCrit - critical section marker
*pCritName - unused
Version
11/15/1999 (gschaefer)
References NetCritPrivT::access, NetCritPrivT::csect, NetCritPrivT::locked, and NetCritPrivT::thread.
Referenced by CommSRPConstruct(), CommTCPConstruct(), DirtyCertCreate(), NetGameLinkCreate(), NetLibCommonInit(), ProtoAdvtConstruct(), ProtoHttpCreate(), ProtoPingCreate(), ProtoSSLCreate(), ProtoSSLStartup(), ProtoTunnelAlloc(), ProtoTunnelCreate(), ProtoUdpCreate(), QosApiCreate(), SocketCreate(), VoipCommonStartup(), VoipConnectionStartup(), VoipHeadsetCreate(), and WebLogCreate().
DIRTYCODE_API void NetCritKill (NetCritT * pCrit)
Release resources and destroy critical section. Not currently used (no resources to release)
Parameters
*pCrit - critical section marker
Version
11/15/1999 (gschaefer)
References NetCritPrivT::csect, and NetCritPrivT::locked.
Referenced by CommSRPDestroy(), CommTCPDestroy(), CommUDPDestroy(), DirtyCertDestroy(), NetGameLinkDestroy(), NetLibCommonShutdown(), ProtoAdvtDestroy(), ProtoHttpDestroy(), ProtoPingDestroy(), ProtoSSLDestroy(), ProtoSSLShutdown(), ProtoTunnelDestroy(), ProtoTunnelFree2(), ProtoUdpDestroy(), QosApiDestroy(), SocketDestroy(), VoipCommonShutdown(), VoipCommonStartup(), VoipConnectionShutdown(), VoipHeadsetDestroy(), and WebLogDestroy().
DIRTYCODE_API void NetCritLeave (NetCritT * pCrit)
Leave a critical section. Must be called once for every NetCritEnter (or successful NetCritTry).
Parameters
*pCrit - critical section marker
Version
11/15/1999 (gschaefer)
References NetCritPrivT::access, NetCritPrivT::csect, NetCritPrivT::locked, and NetCritPrivT::thread.
Referenced by CommUDPCallback(), CommUDPSend(), DirtyCertCAPreloadCerts(), DirtyCertCARequestCert(), DirtyCertCARequestDone(), DirtyCertCARequestFree(), DirtyCertControl(), DirtyCertStatus(), NetGameLinkRecv2(), NetGameLinkSend(), NetIdleCall(), NetIdleDone(), ProtoAdvtAnnounce(), ProtoAdvtCancel(), ProtoAdvtConstruct(), ProtoAdvtDestroy(), ProtoHttpAbort(), ProtoHttpRecv(), ProtoHttpSend(), ProtoHttpUpdate(), ProtoPingResponse(), ProtoSSLRecv(), ProtoSSLSend(), ProtoSSLUpdate(), ProtoTunnelAlloc(), ProtoTunnelControl(), ProtoTunnelFree2(), ProtoTunnelStatus(), ProtoTunnelUpdate(), ProtoTunnelUpdatePortList(), ProtoUdpRecvFrom(), ProtoUdpUpdate(), QosApiCancelRequest(), QosApiControl(), QosApiDestroy(), QosApiServiceRequest(), QosApiStatus(), SocketBind(), SocketControl(), SocketHostnameAddRef(), SocketHostnameCacheAdd(), SocketHostnameCacheDel(), SocketHostnameCacheGet(), SocketImport(), SocketInfo(), SocketRecvfrom(), VoipActivateLocalUser(), VoipCommonControl(), VoipConnect(), VoipConnectionAddSessionId(), VoipConnectionDeleteSessionId(), VoipConnectionStart(), VoipConnectionUpdate(), VoipControl(), VoipDisconnect2(), VoipGroupMuteByConnId2(), VoipHeadsetControl(), VoipRemove(), VoipSetLocalUser(), WebLogPrintf(), and WebLogUpdate().
DIRTYCODE_API int32_t NetCritTry (NetCritT * pCrit)
Attempt to gain access to critical section. Always returns immediately regadless of access status. A thread that already has access to a critical section can always receive repeated access to it.
Parameters
*pCrit - critical section marker
Returns
int32_t - zero=unable to get access, non-zero=access granted
Version
11/15/1999 (gschaefer)
References NetCritPrivT::access, NetCritPrivT::csect, NetCritPrivT::locked, and NetCritPrivT::thread.
Referenced by NetCritEnter(), NetIdleCall(), and ProtoUdpUpdate().
DIRTYCODE_API int32_t NetHash (const char * pString)
Calculate a unique 32-bit hash based on the given input string.
Parameters
*pString - pointer to string to calc hash of
Returns
int32_t - resultant 32bit hash
Version
2.0 07/26/2011 (jrainy) rewrite to lower collision rate
References NetHashBin().
DIRTYCODE_API int32_t NetHashBin (const void * pBuffer, uint32_t uLength)
Calculate a unique 32-bit hash based on the given buffer.
Parameters
*pBuffer - pointer to buffer to calc hash of
*uLength - length of buffer to calc hash of
Returns
int32_t - resultant 32bit hash
Version
1.0 02/14/2011 (jrainy) First Version
Referenced by NetHash().
DIRTYCODE_API void NetIdleAdd (void(*)(void *ref) proc, void * ref)
Referenced by DirtyCertCreate(), and SocketCreate().
DIRTYCODE_API void NetIdleCall (void)
Call all of the functions in the idle list.
Version
09/15/1999 (gschaefer)
References NetCritLeave(), NetCritTry(), pProc, and pRef.
DIRTYCODE_API void NetIdleDel (void(*)(void *ref) proc, void * ref)
Referenced by DirtyCertDestroy(), and SocketDestroy().
DIRTYCODE_API void NetIdleDone (void)
Make sure all idle calls have completed.
Version
09/15/1999 (gschaefer)
References NetCritEnter(), and NetCritLeave().
Referenced by SocketDestroy().
DIRTYCODE_API void NetIdleReset (void)
Reset idle function count.
Version
06/21/2006 (jbrookes)
Referenced by NetLibCommonInit().
DIRTYCODE_API void NetLibCommonInit (void)
NetLib platform-common initialization.
Version
04/05/2016 (jbrookes)
References NetCritInit(), NetIdleReset(), NetPrintRateLimitT::RateCrit, and TRUE.
Referenced by NetLibCreate().
DIRTYCODE_API void NetLibCommonShutdown (void)
NetLib platform-common shutdown.
Version
04/05/2016 (jbrookes)
References FALSE, NetCritKill(), and NetPrintRateLimitT::RateCrit.
Referenced by NetLibDestroy().
DIRTYCODE_API void NetLibCreate (int32_t iThreadPrio, int32_t iThreadStackSize, int32_t iThreadCpuAffinity)
Initialize the network library functions.
Parameters
iThreadPrio - priority to start the _NetLibThread with
iThreadStackSize - stack size to start the _NetLibThread with (in bytes)
iThreadCpuAffinity - cpu affinity to start the _NetLibThread with
Version
01/02/2002 (gschaefer)
References _NetLib_bUseHighResTimer, NetLibCommonInit(), and NetPrintf.
Referenced by SocketCreate().
DIRTYCODE_API void NetLibDestroy (uint32_t uShutdownFlags)
Destroy the network lib.
Parameters
uShutdownFlags - NET_SHUTDOWN_* flags
Version
01/02/02 (gschaefer)
References NetLibCommonShutdown().
Referenced by SocketDestroy().
DIRTYCODE_API void NetPrintArrayCode (const void * pMem, int32_t iSize, const char * pTitle)
DIRTYCODE_API int32_t NetPrintfCode (const char * fmt, ...)
DIRTYCODE_API void NetPrintfHook (int32_t(*)(void *pParm, const char *pText) pPrintfDebugHook, void * pParm)
DIRTYCODE_API void NetPrintfVerboseCode (int32_t iVerbosityLevel, int32_t iCheckLevel, const char * pFormat, ...)
DIRTYCODE_API void NetPrintMemCode (const void * pMem, int32_t iSize, const char * pTitle)
DIRTYCODE_API void NetPrintWrapCode (const char * pData, int32_t iWrapCol)
DIRTYCODE_API uint32_t NetRand (uint32_t uLimit)
A simple pseudo-random sequence generator. The sequence is implicitly seeded in the first call with the millisecond tick count at the time of the call.
Parameters
uLimit - upper bound of pseudo-random number output
Returns
uint32_t - pseudo-random number from [0...(uLimit - 1)]
Version
06/25/2009 (jbrookes)
References NetTick().
Referenced by SocketPacketQueueRem().
DIRTYCODE_API uint32_t NetTick (void)
Return some kind of increasing tick count with millisecond scale (does not need to have millisecond precision, but higher precision is better).
Returns
uint32_t - millisecond tick count
Version
09/15/1999 (gschaefer)
Referenced by CommSRPTick(), CommTCPSend(), CommTCPTick(), CommUDPDestroy(), CommUDPSend(), CommUDPTick(), CommUDPUnconnect(), CommUDPUnlisten(), HttpManagerCreate(), HttpManagerRecv(), HttpManagerUpdate(), NetConnElapsed(), NetConnIdle(), NetGameDistCreate(), NetGameDistInputCheck(), NetGameDistInputClear(), NetGameDistInputLocalMulti(), NetGameDistInputQueryMulti(), NetGameDistServStartGame(), NetGameDistServStatus(), NetGameDistServUpdate(), NetGameLinkCreate(), NetGameLinkRecv2(), NetGameLinkSend(), NetGameLinkStatus(), NetRand(), PingManagerCreate(), PingManagerUpdate(), ProtoAdvtAnnounce(), ProtoHttpServUpdate(), ProtoHttpUpdate(), ProtoMangleCreate(), ProtoPingResponse(), ProtoStreamControl(), ProtoStreamUpdate(), ProtoTunnelAlloc(), ProtoTunnelControl(), ProtoTunnelCreate(), ProtoTunnelFree2(), ProtoTunnelUpdate(), ProtoUpnpUpdate(), ProtoWebSocketConnect(), ProtoWebSocketUpdate(), SocketAddrMapInit(), SocketHostnameCacheAdd(), SocketHostnameCacheGet(), SocketPacketQueueAdd(), SocketPacketQueueCreate(), SocketPacketQueueRem(), SocketRateUpdate(), VoipConnectionFlush(), VoipConnectionSend(), VoipConnectionStart(), VoipConnectionUpdate(), WebOfferHttp(), and WebOfferHttpComplete().
DIRTYCODE_API uint64_t NetTickUsec (void)
Return increasing tick count in microseconds. Used for performance timing purposes.
Returns
uint64_t - microsecond tick count
Version
01/30/2015 (jbrookes)
DIRTYCODE_API void NetTimeStampEnableCode (uint8_t bEnableTimeStamp)
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:48