DirtySock: dirtyauthxboxone.cpp File Reference
dirtyauthxboxone.cpp File Reference
Xbox One Auth wrapper module.
#include <xdk.h>
#include <string.h>
#include <stdlib.h>
#include "DirtySDK/dirtysock/dirtyerr.h"
#include "DirtySDK/dirtysock/dirtylib.h"
#include "DirtySDK/dirtysock/dirtymem.h"
#include "DirtySDK/dirtysock/netconn.h"
#include "DirtySDK/dirtysock/xboxone/dirtyauthxboxone.h"
Data Structures
struct DirtyAuthTokenT
token request structure
struct DirtyAuthRefT
Typedefs
typedef struct DirtyAuthTokenT DirtyAuthTokenT
token request structure
Functions
DirtyAuthRefT * DirtyAuthCreate (uint8_t bSecureBypass)
Create the DirtyAuth module state.
void DirtyAuthDestroy (DirtyAuthRefT *pDirtyAuth)
Destroy the DirtyAuth module.
int32_t DirtyAuthGetToken (int32_t iUserIndex, const char *pHost, uint8_t bForceNew)
Get an XAuth token.
int32_t DirtyAuthCheckToken (int32_t iUserIndex, const char *pHost, int32_t *pTokenLen, char *pToken)
Check to see if an auth token is available.
Detailed Description
Xbox One Auth wrapper module.
Attention
Copyright 2012 Electronic Arts Inc.
Version
09/04/2013 (amakoukji) First Version ported from Xenon
Typedef Documentation
typedef struct DirtyAuthTokenT DirtyAuthTokenT
token request structure
Function Documentation
int32_t DirtyAuthCheckToken (int32_t iUserIndex, const char * pHost, int32_t * pTokenLen, char * pToken)
Check to see if an auth token is available.
Parameters
iUserIndex - User Index when -1 this will return the first valid ticket
*pHost - pointer to host to check token availability for
*pTokenLen - filled with token length when return code is DIRTYAUTH_SUCCESS (caller can pass NULL here)
*pToken - filled with token when return code is DIRTYAUTH_SUCCESS (caller can pass NULL here)
Returns
int32_t - DIRTYAUTH_* response code
Version
04/10/2012 (jbrookes)
09/04/2013 (amakoukji) Adapted for Xbox One
References NetCritEnter(), NetCritLeave(), NetPrintf, NULL, and DirtyAuthRefT::TokenCrit.
Referenced by NetConnStatus(), and ProtoHttpUpdate().
DirtyAuthRefT* DirtyAuthCreate (uint8_t bSecureBypass)
Create the DirtyAuth module state.
Parameters
bSecureBypass - ignored, this is present to keep the same Api as Xenon
Returns
DirtyAuthRefT * - pointer to module state, or NULL
Version
04/05/2012 (jbrookes)
References DIRTYAUTH_MEMID, DirtyMemAlloc(), DirtyMemGroupQuery(), DirtyAuthRefT::iMemGroup, NetCritInit(), NetPrintf, NULL, DirtyAuthRefT::pMemGroupUserData, and DirtyAuthRefT::TokenCrit.
void DirtyAuthDestroy (DirtyAuthRefT * pDirtyAuth)
Destroy the DirtyAuth module.
Parameters
*pDirtyAuth - pointer to module state
Version
04/05/2012 (jbrookes)
References DIRTYAUTH_MEMID, DirtyMemFree(), DirtyAuthRefT::iMemGroup, NetConnControl(), NetCritKill(), NetPrintf, NULL, DirtyAuthRefT::pMemGroupUserData, DirtyAuthTokenT::pNext, DirtyAuthRefT::pTokenList, and DirtyAuthRefT::TokenCrit.
Referenced by NetConnDisconnect().
int32_t DirtyAuthGetToken (int32_t iUserIndex, const char * pHost, uint8_t bForceNew)
Get an XAuth token.
Parameters
iUserIndex - user index
*pHost - pointer to hostname to get token for
bForceNew - TRUE=force acquisition of new token
Returns
int32_t - DIRTYAUTH_* response code
Version
04/10/2012 (jbrookes)
References DirtyAuthTokenT::asyncOperation, DIRTYAUTH_MEMID, DirtyMemAlloc(), FALSE, NetConnQuery(), NetConnStatus(), NetCritEnter(), NetCritLeave(), NetPrintf, NULL, and DirtyAuthRefT::TokenCrit.
Referenced by ProtoHttpRequestCb().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:19