DirtySock: userapips4.c File Reference
userapips4.c File Reference
Implements the ps4 specific code to request UserProfiles, and parse the responses.
#include <string.h>
#include <np.h>
#include <np/np_npid.h>
#include <scetypes.h>
#include "userapipriv.h"
#include "DirtySDK/dirtysock/ps4/dirtywebapips4.h"
#include "DirtySDK/dirtylang.h"
#include "DirtySDK/dirtysock/dirtymem.h"
#include "DirtySDK/util/jsonparse.h"
Data Structures
struct UserApiPlatResponseT
struct UserApiPlatformDataT
Macros
#define USERAPI_MAX_LOOKUPS_PER_REQUEST (50)
#define USERAPI_WEBAPI_GROUP "userProfile"
#define USERAPI_WEBAPI_RECENTLY_MET_GROUP "activityFeed"
#define USERAPI_PATH_PROFILE_FORMAT "/v1/profiles?onlineId=%s&fields=@default,personalDetail&avatarSize=%c"
#define USERAPI_PATH_PRESENCE_FORMAT "/v1/users/%s/presence?type=primary&presenceDetail=true"
#define USERAPI_PATH_RECENTLY_MET_FORMAT "/v1/users/%s/feed"
#define USERAPI_PATH_RECENTLY_MET_POST_FORMAT "{\"source\": {\"meta\": \"%s\", \"type\": \"ONLINE_ID\" }, \"storyType\": \"PLAYED_WITH\",\"targets\": [ {\"meta\": \"%s\", \"type\": \"TITLE_ID\" },{\"meta\": \"%s\", \"type\": \"ONLINE_ID\" }]}"
#define USERAPI_PATH_RICH_PRESENCE_FORMAT1 "/v1/users/%s/presence/gameStatus"
#define USERAPI_PATH_RICH_PRESENCE_FORMAT2 "/v1/users/%s/presence/gameData"
#define USERAPI_PATH_RICH_PRESENCE_POST_FORMAT1 "{\"gameStatus\": \"%s\"}"
#define USERAPI_PATH_RICH_PRESENCE_POST_FORMAT2 "{\"gameData\": \"%s\"}"
#define USERAPI_PATH_PROFILE_FORMAT_LEN_MAX (128 + ((SCE_NP_ONLINEID_MAX_LENGTH+1) * USERAPI_MAX_LOOKUPS_PER_REQUEST))
#define USERAPI_PATH_RECENTLY_MET_LEN_MAX (256)
#define USERAPI_HTTP_RESP_BODY_JSON_MAX_LEN (1024)
Functions
void _UserApiTriggerPostCallback (UserApiRefT *pRef, uint32_t uUserIndex)
Called by update function in the platform specific UserApi modules when a profile or error is ready.
int32_t _UserApiProcessProfileResponse (UserApiRefT *pRef, int32_t uUserIndex, uint8_t bBatch, UserApiProfileT *ProfileData, UserApiUserDataT *pUserData)
Initiates the recently met player request to PSN Services.
int32_t _UserApiProcessPresenceResponse (UserApiRefT *pRef, int32_t uUserIndex, UserApiPresenceT *pPresenceData, UserApiUserDataT *pUserData)
Initiates the recently met player request to PSN Services.
int32_t _UserApiProcessRichPresenceResponse (UserApiRefT *pRef, int32_t uUserIndex, UserApiRichPresenceT *pRichPresenceData, UserApiUserDataT *pUserData)
Initiates the recently met player request to PSN Services.
int32_t _UserApiProcessRmpResponse (UserApiRefT *pRef, uint32_t uUserIndex)
Initiates the recently met player request to PSN Services.
int32_t UserApiPlatUpdate (UserApiRefT *pRef)
Control behavior of module.
UserApiPlatformDataT * UserApiPlatCreateData (UserApiRefT *pRef)
Allocates and initializes resources needed for the UserApi on PS4.
int32_t UserApiPlatDestroyData (UserApiRefT *pRef, UserApiPlatformDataT *pPlatformData)
Destroys the ps4 specific resources used by the UserApi module.
int32_t UserApiPlatRequestProfile (UserApiRefT *pRef, uint32_t uUserIndex, DirtyUserT *pLookupUsers, int32_t iLookupUsersLength)
Initiates the profile request to PSN.
int32_t UserApiPlatRequestPresence (UserApiRefT *pRef, uint32_t uUserIndex, DirtyUserT *pLookupUser)
Initiates the presence request to PSN.
int32_t UserApiPlatRequestRichPresence (UserApiRefT *pRef, uint32_t uUserIndex, DirtyUserT *pLookupUser)
Initiates the rich presence request to PSN.
int32_t UserApiPlatRequestRecentlyMet (UserApiRefT *pRef, uint32_t uUserIndex, DirtyUserT *pPlayerMet)
Initiates the recently met player request to PSN Services.
int32_t UserApiPlatRequestPostRichPresence (UserApiRefT *pRef, uint32_t uUserIndex, UserApiRichPresenceT *pData)
Initiates the recently met player request to PSN Services.
int32_t UserApiPlatAbortRequests (UserApiRefT *pRef, uint32_t uUserIndex)
Abort all web requests for a user.
int32_t _UserApiPlatAbortPostRequests (UserApiRefT *pRef, uint32_t uUserIndex)
Aborts the recently met player request to PSN Services.
int32_t UserApiPlatControl (UserApiRefT *pRef, int32_t iControl, int32_t iValue, int32_t iValue2, void *pValue)
Control behavior of module.
int32_t UserApiPlatRegisterUpdateEvent (UserApiRefT *pRef, uint32_t uUserIndex, UserApiNotifyTypeE eType)
Control behavior of module.
Detailed Description
Implements the ps4 specific code to request UserProfiles, and parse the responses.
Note
None.
Attention
Copyright (c) Tiburon Entertainment / Electronic Arts 2001-2013. ALL RIGHTS RESERVED.
Version
04/11/13 (akirchner) First Version
Macro Definition Documentation
#define USERAPI_HTTP_RESP_BODY_JSON_MAX_LEN (1024)
Referenced by _UserApiProcessPresenceResponse(), _UserApiProcessProfileResponse(), and _UserApiProcessRichPresenceResponse().
#define USERAPI_MAX_LOOKUPS_PER_REQUEST (50)
Referenced by UserApiPlatUpdate().
#define USERAPI_PATH_PRESENCE_FORMAT "/v1/users/%s/presence?type=primary&presenceDetail=true"
Referenced by UserApiPlatRequestPresence(), and UserApiPlatRequestRichPresence().
#define USERAPI_PATH_PROFILE_FORMAT "/v1/profiles?onlineId=%s&fields=@default,personalDetail&avatarSize=%c"
Referenced by UserApiPlatUpdate().
#define USERAPI_PATH_PROFILE_FORMAT_LEN_MAX (128 + ((SCE_NP_ONLINEID_MAX_LENGTH+1) * USERAPI_MAX_LOOKUPS_PER_REQUEST))
Referenced by UserApiPlatUpdate().
#define USERAPI_PATH_RECENTLY_MET_FORMAT "/v1/users/%s/feed"
Referenced by UserApiPlatRequestRecentlyMet().
#define USERAPI_PATH_RECENTLY_MET_LEN_MAX (256)
Referenced by UserApiPlatRequestPostRichPresence(), UserApiPlatRequestPresence(), UserApiPlatRequestRecentlyMet(), and UserApiPlatRequestRichPresence().
#define USERAPI_PATH_RECENTLY_MET_POST_FORMAT "{\"source\": {\"meta\": \"%s\", \"type\": \"ONLINE_ID\" }, \"storyType\": \"PLAYED_WITH\",\"targets\": [ {\"meta\": \"%s\", \"type\": \"TITLE_ID\" },{\"meta\": \"%s\", \"type\": \"ONLINE_ID\" }]}"
Referenced by UserApiPlatRequestRecentlyMet().
#define USERAPI_PATH_RICH_PRESENCE_FORMAT1 "/v1/users/%s/presence/gameStatus"
Referenced by UserApiPlatRequestPostRichPresence().
#define USERAPI_PATH_RICH_PRESENCE_FORMAT2 "/v1/users/%s/presence/gameData"
#define USERAPI_PATH_RICH_PRESENCE_POST_FORMAT1 "{\"gameStatus\": \"%s\"}"
Referenced by UserApiPlatRequestPostRichPresence().
#define USERAPI_PATH_RICH_PRESENCE_POST_FORMAT2 "{\"gameData\": \"%s\"}"
#define USERAPI_WEBAPI_GROUP "userProfile"
Referenced by UserApiPlatRequestPostRichPresence(), UserApiPlatRequestPresence(), UserApiPlatRequestRichPresence(), and UserApiPlatUpdate().
#define USERAPI_WEBAPI_RECENTLY_MET_GROUP "activityFeed"
Referenced by UserApiPlatRequestRecentlyMet().
Function Documentation
int32_t _UserApiPlatAbortPostRequests (UserApiRefT * pRef, uint32_t uUserIndex)
Aborts the recently met player request to PSN Services.
Parameters
*pRef - module ref
uUserIndex - The index of the user making the request
Returns
int32_t - 0 for success, negative for error
Version
06/14/2013 (amakoukji)
References DirtyWebApiAbortRequests(), UserApiRefT::pPlatformData, and UserApiPlatformDataT::pWebApiRMP.
Referenced by UserApiPlatAbortRequests(), and UserApiPlatControl().
int32_t _UserApiProcessPresenceResponse (UserApiRefT * pRef, int32_t uUserIndex, UserApiPresenceT * pPresenceData, UserApiUserDataT * pUserData)
Initiates the recently met player request to PSN Services.
Parameters
*pRef - module ref
uUserIndex - The index of the user making the request
*pPresenceData - response data
*pUserData - user data for callback
Returns
int32_t - 0 for success, negative for error
Version
06/14/2013 (amakoukji)
References UserApiPresenceT::bIsPlayingSameTitle, UserApiUserDataT::DirtyUser, DIRTYUSER_NATIVEUSER_MAXSIZE, DirtyUserFromNativeUser(), ds_stricmp(), UserApiPresenceT::ePresenceStatus, FALSE, UserApiPlatResponseT::iStatusCode, UserApiUserContextT::iTotalErrors, UserApiUserContextT::iTotalReceived, JsonFind(), JsonGetString(), JsonParse(), NetConnStatus(), NetPrintf, UserApiPlatResponseT::pData, UserApiRefT::pPlatformData, UserApiPresenceT::pRawData, UserApiPlatformDataT::PresencePlatResponse, UserApiPresenceT::strPlatform, UserApiPresenceT::strTitleId, UserApiPresenceT::strTitleName, TRUE, USERAPI_ERROR_REQUEST_FAILED, USERAPI_ERROR_REQUEST_PARSE_FAILED, USERAPI_HTTP_RESP_BODY_JSON_MAX_LEN, USERAPI_PRESENCE_OFFLINE, USERAPI_PRESENCE_ONLINE, USERAPI_PRESENCE_UNKNOWN, and UserApiRefT::UserPresenceList.
Referenced by UserApiUpdate().
int32_t _UserApiProcessProfileResponse (UserApiRefT * pRef, int32_t uUserIndex, uint8_t bBatch, UserApiProfileT * ProfileData, UserApiUserDataT * pUserData)
Initiates the recently met player request to PSN Services.
Parameters
*pRef - module ref
uUserIndex - The index of the user making the request
bBatch - batch flag
*ProfileData - response data
*pUserData - user data for callback
Returns
int32_t - 0 for success, negative for error
Version
06/14/2013 (amakoukji)
References _UserApiTriggerCallback(), UserApiUserDataT::DirtyUser, DIRTYUSER_NATIVEUSER_MAXSIZE, DirtyUserFromNativeUser(), ds_strnzcat(), ds_strnzcpy(), UserApiRefT::iLookupsSent, UserApiPlatResponseT::iStatusCode, UserApiUserContextT::iTotalErrors, UserApiUserContextT::iTotalReceived, JsonFind(), JsonGetInteger(), JsonGetListItemEnd, JsonGetString(), JsonParse(), JsonSeekValue(), LOBBYAPI_LocalizerTokenCreate, NetPrintf, UserApiPlatResponseT::pData, UserApiRefT::pPlatformData, UserApiProfileT::pRawData, UserApiPlatformDataT::ProfilePlatResponse, UserApiProfileT::strAvatarUrl, UserApiProfileT::strDisplayName, UserApiProfileT::strGamertag, UserApiProfileT::uLocale, USERAPI_ERROR_OK, USERAPI_ERROR_REQUEST_FAILED, USERAPI_ERROR_REQUEST_PARSE_FAILED, USERAPI_EVENT_DATA, USERAPI_HTTP_RESP_BODY_JSON_MAX_LEN, and UserApiRefT::UserContextList.
Referenced by UserApiUpdate().
int32_t _UserApiProcessRichPresenceResponse (UserApiRefT * pRef, int32_t uUserIndex, UserApiRichPresenceT * pRichPresenceData, UserApiUserDataT * pUserData)
Initiates the recently met player request to PSN Services.
Parameters
*pRef - module ref
uUserIndex - The index of the user making the request
*pRichPresenceData - response data
*pUserData - user data for callback
Returns
int32_t - 0 for success, negative for error
Version
06/14/2013 (amakoukji)
References UserApiUserDataT::DirtyUser, DIRTYUSER_NATIVEUSER_MAXSIZE, DirtyUserFromNativeUser(), UserApiPlatResponseT::iStatusCode, UserApiUserContextT::iTotalErrors, UserApiUserContextT::iTotalReceived, JsonFind(), JsonGetString(), JsonParse(), NetPrintf, UserApiPlatResponseT::pData, UserApiRefT::pPlatformData, UserApiRichPresenceT::pRawData, UserApiPlatformDataT::PresencePlatResponse, UserApiRichPresenceT::strData, UserApiRichPresenceT::strGameData, USERAPI_ERROR_REQUEST_FAILED, USERAPI_ERROR_REQUEST_PARSE_FAILED, USERAPI_HTTP_RESP_BODY_JSON_MAX_LEN, and UserApiRefT::UserRichPresenceList.
Referenced by UserApiUpdate().
int32_t _UserApiProcessRmpResponse (UserApiRefT * pRef, uint32_t uUserIndex)
Initiates the recently met player request to PSN Services.
Parameters
*pRef - module ref
uUserIndex - The index of the user making the request
Returns
int32_t - 0 for success, negative for error
Version
06/14/2013 (amakoukji)
void _UserApiTriggerPostCallback (UserApiRefT * pRef, uint32_t uUserIndex)
Called by update function in the platform specific UserApi modules when a profile or error is ready.
Parameters
*pRef - pointer to UserApiT module reference.
*uUserIndex - The index of the user associated with this profile request.
Version
12/10/2013 (amakoukji) - First version
References UserApiPostResponseT::eError, UserApiPlatResponseT::iStatusCode, NetCritEnter(), NetCritLeave(), UserApiPlatResponseT::pData, UserApiPostResponseT::pMessage, UserApiRefT::postCrit, UserApiRefT::pPlatformData, UserApiRefT::pPostCallback, pRef, UserApiRefT::pUserDataPost, UserApiPlatformDataT::RmpPlatResponse, USERAPI_ERROR_OK, USERAPI_ERROR_REQUEST_FAILED, and UserApiPostResponseT::uUserIndex.
Referenced by UserApiUpdate().
int32_t UserApiPlatAbortRequests (UserApiRefT * pRef, uint32_t uUserIndex)
Abort all web requests for a user.
Parameters
*pRef - pointer to module state
uUserIndex - user index
Returns
int32_t - Return 0 if successful. Otherwise a selector specific error
Version
09/26/2013 (amakoukji) - First documentation
References _UserApiPlatAbortPostRequests(), DirtyWebApiAbortRequests(), UserApiRefT::pPlatformData, UserApiPlatformDataT::pWebApi, and UserApiPlatformDataT::pWebApiPresence.
Referenced by UserApiCancel(), and UserApiControl().
int32_t UserApiPlatControl (UserApiRefT * pRef, int32_t iControl, int32_t iValue, int32_t iValue2, void * pValue)
Control behavior of module.
Parameters
*pRef - pointer to module state
iControl - status selector
iValue - control value
iValue2 - control value
*pValue - control value
Returns
int32_t - Return 0 if successful. Otherwise a selector specific error
Note
iControl can be one of the following:
        'avsz' - Set which avatar size will be retrieved. iValue = 's' for small, 'm' for medium and 'l' for big. 's' is the default value, and this is just functional for PS4.
Version
05/10/2013 (mcorcoran) - First version
References _UserApiPlatAbortPostRequests(), UserApiUserContextT::iTotalErrors, UserApiUserContextT::iTotalReceived, UserApiUserContextT::iTotalRequested, NetPrintf, UserApiPlatformDataT::pAvatarSize, UserApiRefT::pPlatformData, UserApiRefT::pPostCallback, UserApiRefT::pUserDataPost, and UserApiRefT::UserRmpList.
Referenced by UserApiControl().
UserApiPlatformDataT* UserApiPlatCreateData (UserApiRefT * pRef)
Allocates and initializes resources needed for the UserApi on PS4.
Parameters
*pRef - pointer to UserApiT module reference.
Returns
UserApiPlatformDataT* - pointer to reference
Version
04/17/2013 (mcorcoran) - First version
References DirtyMemAlloc(), DirtyWebApiCreate(), DirtyWebApiDestroy(), UserApiPlatResponseT::iDataLen, UserApiRefT::iMemGroup, UserApiPlatResponseT::iStatusCode, NETCONN_MAXLOCALUSERS, NetPrintf, UserApiPlatformDataT::pAvatarSize, UserApiPlatResponseT::pData, UserApiRefT::pMemGroupUserData, UserApiPlatformDataT::PresencePlatResponse, UserApiPlatformDataT::ProfilePlatResponse, UserApiPlatResponseT::pUserData, UserApiPlatformDataT::pWebApi, UserApiPlatformDataT::pWebApiPresence, UserApiPlatformDataT::pWebApiRMP, UserApiPlatformDataT::RmpPlatResponse, USERAPI_MEMID, and UserApiPlatDestroyData().
Referenced by UserApiCreate().
int32_t UserApiPlatDestroyData (UserApiRefT * pRef, UserApiPlatformDataT * pPlatformData)
Destroys the ps4 specific resources used by the UserApi module.
Parameters
*pRef - pointer to UserApiT module reference.
*pPlatformData - pointer to the UserApiPlatformDataT struct to be destroyed.
Returns
int32_t - Return 0 if successful. Otherwise -1.
Version
04/17/2013 (akirchner) - First version
References UserApiRefT::aLookupUsers, DirtyMemFree(), DirtyWebApiDestroy(), UserApiRefT::iMemGroup, NETCONN_MAXLOCALUSERS, UserApiPlatResponseT::pData, UserApiRefT::pMemGroupUserData, UserApiPlatformDataT::PresencePlatResponse, UserApiPlatformDataT::ProfilePlatResponse, UserApiPlatformDataT::pWebApi, UserApiPlatformDataT::pWebApiPresence, UserApiPlatformDataT::pWebApiRMP, UserApiPlatformDataT::RmpPlatResponse, USERAPI_MEMID, and UserApiCancel().
Referenced by UserApiPlatCreateData().
int32_t UserApiPlatRegisterUpdateEvent (UserApiRefT * pRef, uint32_t uUserIndex, UserApiNotifyTypeE eType)
Control behavior of module.
Parameters
*pRef - pointer to module state
uUserIndex - user index
eType - type of callback to register
Returns
int32_t - Return 0 if successful. Otherwise a selector specific error
Version
08/08/2013 (amakoukji) - First version
References DirtyWebApiAddPushEventListener(), DirtyWebApiAddPushEventListenerEx(), NetPrintf, UserApiRefT::pPlatformData, UserApiPlatformDataT::pWebApi, USERAPI_ERROR_UNSUPPORTED, USERAPI_NOTIFY_PRESENCE_UPDATE, USERAPI_NOTIFY_RICH_PRESENCE_UPDATE, and USERAPI_NOTIFY_TITLE_UPDATE.
Referenced by UserApiRegisterUpdateEvent().
int32_t UserApiPlatRequestPostRichPresence (UserApiRefT * pRef, uint32_t uUserIndex, UserApiRichPresenceT * pData)
Initiates the recently met player request to PSN Services.
Parameters
*pRef - module ref
uUserIndex - The index of the user making the request
pData - Rich presence data
Returns
int32_t - 0 for success, negative for error
Version
06/14/2013 (amakoukji)
References DirtyWebApiRequest(), ds_snzprintf(), UserApiUserContextT::iTotalErrors, UserApiUserContextT::iTotalReceived, UserApiUserContextT::iTotalRequested, NetConnStatus(), NetCritEnter(), NetCritLeave(), NetPrintf, UserApiRefT::postCrit, UserApiRefT::pPlatformData, UserApiPlatformDataT::pWebApiRMP, UserApiRichPresenceT::strData, USERAPI_PATH_RECENTLY_MET_LEN_MAX, USERAPI_PATH_RICH_PRESENCE_FORMAT1, USERAPI_PATH_RICH_PRESENCE_POST_FORMAT1, USERAPI_WEBAPI_GROUP, and UserApiRefT::UserRmpList.
Referenced by UserApiPostRichPresenceAsync().
int32_t UserApiPlatRequestPresence (UserApiRefT * pRef, uint32_t uUserIndex, DirtyUserT * pLookupUser)
Initiates the presence request to PSN.
Parameters
*pRef - module ref
uUserIndex - The index of the user making the request
pLookupUser - Array of DirtyUserT struct containing the users to lookup
Returns
int32_t - 0 for success, negative for error
Version
12/10/2013 (amakoukji)
References UserApiRefT::crit, DirtyUserToNativeUser(), DirtyWebApiRequest(), ds_snzprintf(), UserApiUserContextT::iTotalErrors, UserApiUserContextT::iTotalReceived, UserApiUserContextT::iTotalRequested, NetCritEnter(), NetCritLeave(), UserApiRefT::pPlatformData, UserApiPlatformDataT::pWebApiPresence, USERAPI_PATH_PRESENCE_FORMAT, USERAPI_PATH_RECENTLY_MET_LEN_MAX, USERAPI_WEBAPI_GROUP, and UserApiRefT::UserPresenceList.
Referenced by UserApiRequestPresenceAsync().
int32_t UserApiPlatRequestProfile (UserApiRefT * pRef, uint32_t uUserIndex, DirtyUserT * pLookupUsers, int32_t iLookupUsersLength)
Initiates the profile request to PSN.
Parameters
*pRef - module ref
uUserIndex - The index of the user making the request
pLookupUsers - Array of DirtyUserT struct containing the users to lookup
iLookupUsersLength - maximum users to return per query
Returns
int32_t - 0 for success, negative for error
Version
04/17/2013 (mcorcoran)
References UserApiRefT::aLookupUsers, UserApiRefT::bLookupUserAvailable, UserApiRefT::crit, DirtyMemAlloc(), ds_memcpy(), UserApiRefT::iLookupsSent, UserApiRefT::iLookupUserIndex, UserApiRefT::iLookupUsersLength, UserApiRefT::iMemGroup, NetCritEnter(), NetCritLeave(), NetPrintf, UserApiRefT::pMemGroupUserData, TRUE, and USERAPI_MEMID.
Referenced by UserApiRequestPresenceAsync(), and UserApiRequestProfilesAsync().
int32_t UserApiPlatRequestRecentlyMet (UserApiRefT * pRef, uint32_t uUserIndex, DirtyUserT * pPlayerMet)
Initiates the recently met player request to PSN Services.
Parameters
*pRef - module ref
uUserIndex - The index of the user making the request
pPlayerMet - DirtyUserT struct containing the users to lookup
Returns
int32_t - 0 for success, negative for error
Version
06/14/2013 (amakoukji)
References DirtyUserToNativeUser(), DirtyWebApiRequest(), ds_snzprintf(), UserApiUserContextT::iTotalErrors, UserApiUserContextT::iTotalReceived, UserApiUserContextT::iTotalRequested, NetConnStatus(), NetCritEnter(), NetCritLeave(), NetPrintf, UserApiRefT::postCrit, UserApiRefT::pPlatformData, UserApiPlatformDataT::pWebApiRMP, USERAPI_PATH_RECENTLY_MET_FORMAT, USERAPI_PATH_RECENTLY_MET_LEN_MAX, USERAPI_PATH_RECENTLY_MET_POST_FORMAT, USERAPI_WEBAPI_RECENTLY_MET_GROUP, and UserApiRefT::UserRmpList.
Referenced by UserApiPostRecentlyMetAsync().
int32_t UserApiPlatRequestRichPresence (UserApiRefT * pRef, uint32_t uUserIndex, DirtyUserT * pLookupUser)
Initiates the rich presence request to PSN.
Parameters
*pRef - module ref
uUserIndex - The index of the user making the request
pLookupUser - Array of DirtyUserT struct containing the users to lookup
Returns
int32_t - 0 for success, negative for error
Version
12/10/2013 (amakoukji)
References UserApiRefT::crit, DirtyUserToNativeUser(), DirtyWebApiRequest(), ds_snzprintf(), UserApiUserContextT::iTotalErrors, UserApiUserContextT::iTotalReceived, UserApiUserContextT::iTotalRequested, NetCritEnter(), NetCritLeave(), UserApiRefT::pPlatformData, UserApiPlatformDataT::pWebApiPresence, USERAPI_PATH_PRESENCE_FORMAT, USERAPI_PATH_RECENTLY_MET_LEN_MAX, USERAPI_WEBAPI_GROUP, UserApiRefT::UserPresenceList, and UserApiRefT::UserRichPresenceList.
Referenced by UserApiRequestPresenceAsync().
int32_t UserApiPlatUpdate (UserApiRefT * pRef)
Control behavior of module.
Parameters
*pRef - pointer to module state
Returns
int32_t - Return 0 if successful. Otherwise a selector specific error
Version
08/08/2013 (amakoukji) - First version
References UserApiRefT::aLookupUsers, UserApiRefT::bLookupUserAvailable, UserApiRefT::crit, DirtyUserToNativeUser(), DirtyWebApiRequest(), ds_snzprintf(), FALSE, UserApiRefT::iLookupsSent, UserApiRefT::iLookupUserIndex, UserApiRefT::iLookupUsersLength, UserApiUserContextT::iTotalErrors, NETCONN_MAXLOCALUSERS, NetCritEnter(), NetCritLeave(), NetPrintf, UserApiPlatformDataT::pAvatarSize, UserApiRefT::pPlatformData, UserApiPlatformDataT::pWebApi, USERAPI_MAX_LOOKUPS_PER_REQUEST, USERAPI_PATH_PROFILE_FORMAT, USERAPI_PATH_PROFILE_FORMAT_LEN_MAX, USERAPI_WEBAPI_GROUP, and UserApiRefT::UserContextList.
Referenced by UserApiUpdate().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:14