DirtySock: ProtoAries
ProtoAries
Proto
Data Structures
struct ProtoAriesMsgHdrT
aries message header
Macros
#define ARIES_KIND_STAT ((signed)0xffffffff)
#define ARIES_CODE_CONN ((signed)0xffffffff)
#define ARIES_CODE_DISC ((signed)0xfefefefe)
Typedefs
typedef enum ProtoAriesStateE ProtoAriesStateE
aries module state
typedef enum ProtoAriesSecureE ProtoAriesSecureE
aries security types
typedef struct ProtoAriesMsgHdrT ProtoAriesMsgHdrT
aries message header
typedef struct ProtoAriesRefT ProtoAriesRefT
module state reference
Enumerations
enum {
PROTOARIES_SECRET_SIZE = 32,
PROTOARIES_TICKET_SIZE = PROTOARIES_SECRET_SIZE+sizeof(int32_t)
}
enum ProtoAriesStateE {
PROTOARIES_STATE_IDLE,
PROTOARIES_STATE_LIST,
PROTOARIES_STATE_CONN,
PROTOARIES_STATE_ONLN,
PROTOARIES_STATE_DISC
}
aries module state
enum ProtoAriesSecureE {
PROTOARIES_SECURE_NONE,
PROTOARIES_SECURE_SSL,
PROTOARIES_SECURE_TICKET
}
aries security types
Functions
DIRTYCODE_API ProtoAriesRefT * ProtoAriesCreate (int32_t iMaxBuf)
Create new virtual network session.
DIRTYCODE_API void ProtoAriesDestroy (ProtoAriesRefT *pProtoAries)
Destroy existing session.
DIRTYCODE_API int32_t ProtoAriesStatus (ProtoAriesRefT *pProtoAries, int32_t iSelect, void *pBuf, int32_t iBufLen)
Return session status info.
DIRTYCODE_API int32_t ProtoAriesConnect (ProtoAriesRefT *pProtoAries, const char *pServer, uint32_t uAddr, int32_t iPort)
Initiate an Aries protocol connection to a server. This is a non blocking call and sessions completion is detected by ProtoAriesStatus('stat') or by "receiving" a special packet where code/kind are both 0xffffffff.
DIRTYCODE_API int32_t ProtoAriesUnconnect (ProtoAriesRefT *pProtoAries)
Terminate Aries connection to server.
DIRTYCODE_API int32_t ProtoAriesListen (ProtoAriesRefT *pProtoAries, uint32_t uAddr, int32_t iPort)
Listen from an incoming Aries connection. This is a non blocking call and sessions completion is detected by ProtoAriesStatus('stat') or by "receiving" a special packet where code/kind are both 0xffffffff.
DIRTYCODE_API int32_t ProtoAriesUnlisten (ProtoAriesRefT *pProtoAries)
Terminate Aries server listening.
DIRTYCODE_API void ProtoAriesUpdate (ProtoAriesRefT *pProtoAries)
Perform actual "work" for protocol. This function should be called at least every 100ms to allow packets to be processed at a reasonable speed.
DIRTYCODE_API int32_t ProtoAriesSend (ProtoAriesRefT *pProtoAries, int32_t iKind, int32_t iCode, const char *pBody, int32_t iSize)
Send an Aries packet to the server.
DIRTYCODE_API int32_t ProtoAriesPeek (ProtoAriesRefT *pProtoAries, int32_t *pKind, int32_t *pCode, char **ppBody)
See if an incoming packet is waiting (but do not remove from queue).
DIRTYCODE_API int32_t ProtoAriesRecv (ProtoAriesRefT *pProtoAries, int32_t *pKind, int32_t *pCode, char *pBody, int32_t iSize)
Get a packet from the server (will copy packet to private buffer).
DIRTYCODE_API void ProtoAriesSecure (ProtoAriesRefT *pProtoAries, ProtoAriesSecureE eSecure)
Define whether the Aries connection should be secure or insecure.
DIRTYCODE_API void ProtoAriesSetKey (ProtoAriesRefT *pProtoAries, const void *pKey, uint32_t uKeySize)
Initialize the session key for this connection.
DIRTYCODE_API uint32_t ProtoAriesTick (ProtoAriesRefT *pProtoAries)
Return timebase for easy client calculations. Returns number of elapsed milliseconds from some point in time (typically system startup). Overflow occurs in approximately 46 days.
Detailed Description
Macro Definition Documentation
#define ARIES_CODE_CONN ((signed)0xffffffff)
#define ARIES_CODE_DISC ((signed)0xfefefefe)
#define ARIES_KIND_STAT ((signed)0xffffffff)
Typedef Documentation
typedef struct ProtoAriesMsgHdrT ProtoAriesMsgHdrT
aries message header
typedef struct ProtoAriesRefT ProtoAriesRefT
module state reference
typedef enum ProtoAriesSecureE ProtoAriesSecureE
aries security types
typedef enum ProtoAriesStateE ProtoAriesStateE
aries module state
Enumeration Type Documentation
anonymous enum
Enumerator
PROTOARIES_SECRET_SIZE
PROTOARIES_TICKET_SIZE
enum ProtoAriesSecureE
aries security types
Enumerator
PROTOARIES_SECURE_NONE
no security
PROTOARIES_SECURE_SSL
encryption via SSL
PROTOARIES_SECURE_TICKET
encryption using key server ticket
enum ProtoAriesStateE
aries module state
Enumerator
PROTOARIES_STATE_IDLE
PROTOARIES_STATE_LIST
PROTOARIES_STATE_CONN
PROTOARIES_STATE_ONLN
PROTOARIES_STATE_DISC
Function Documentation
DIRTYCODE_API int32_t ProtoAriesConnect (ProtoAriesRefT * pProtoAries, const char * pServer, uint32_t uAddr, int32_t iPort)
Initiate an Aries protocol connection to a server. This is a non blocking call and sessions completion is detected by ProtoAriesStatus('stat') or by "receiving" a special packet where code/kind are both 0xffffffff.
Parameters
*pProtoAries - reference pointer
*pServer - server name
uAddr - server address
iPort - server port
Returns
int32_t - -1=error, zero=no error
Version
11/01/2002 (gschaefer)
References ProtoAriesRefT::bHaveWallet, CryptStp1OpenWallet(), CryptStp1UseSecret(), ProtoAriesRefT::DestAddr, ds_strnzcpy(), ProtoAriesRefT::eState, ProtoAriesRefT::iInpProg, ProtoAriesRefT::iInpSize, NULL, ProtoAriesRefT::pProtoSsl, PROTOARIES_STATE_CONN, ProtoAriesSend(), SocketHtonl(), SocketHtons(), ProtoAriesRefT::Stream, ProtoAriesRefT::strServerName, ProtoAriesRefT::uTimeout, and ProtoAriesRefT::Wallet.
Referenced by BuddyApiUpdate().
DIRTYCODE_API ProtoAriesRefT* ProtoAriesCreate (int32_t iMaxBuf)
Create new virtual network session.
Parameters
iMaxBuf - size of internal buffer to use
Returns
ProtoAriesRefT * - reference pointer (NULL=failed)
Version
11/01/2002 (gschaefer)
References ProtoAriesRefT::aBufferData, ProtoAriesRefT::bHaveWallet, DirtyMemAlloc(), DirtyMemGroupQuery(), ProtoAriesRefT::eState, FALSE, ProtoAriesRefT::iBufSize, ProtoAriesRefT::iMemGroup, ProtoAriesRefT::iOutMaxm, NetPrintf, NULL, ProtoAriesRefT::pInpData, ProtoAriesRefT::pMemGroupUserData, ProtoAriesRefT::pOutData, ProtoAriesRefT::pProtoSsl, PROTOARIES_MEMID, and PROTOARIES_STATE_IDLE.
Referenced by BuddyApiCreate2().
DIRTYCODE_API void ProtoAriesDestroy (ProtoAriesRefT * pProtoAries)
Destroy existing session.
Parameters
*pProtoAries - reference pointer
Returns
None.
Version
11/01/2002 (gschaefer)
References DirtyMemFree(), ProtoAriesRefT::iMemGroup, NULL, ProtoAriesRefT::pMemGroupUserData, ProtoAriesRefT::pProtoSsl, PROTOARIES_MEMID, and ProtoSSLDestroy().
Referenced by BuddyApiDestroy().
DIRTYCODE_API int32_t ProtoAriesListen (ProtoAriesRefT * pProtoAries, uint32_t uAddr, int32_t iPort)
Listen from an incoming Aries connection. This is a non blocking call and sessions completion is detected by ProtoAriesStatus('stat') or by "receiving" a special packet where code/kind are both 0xffffffff.
Parameters
*pProtoAries - reference pointer
uAddr - ip address
iPort - tcp port
Returns
int32_t - -1=error, zero=no error
Version
11/01/2002 (gschaefer)
References ProtoAriesRefT::bHaveWallet, ProtoAriesRefT::DestAddr, DirtyMemGroupEnter(), DirtyMemGroupLeave(), ProtoAriesRefT::eState, ProtoAriesRefT::iInpProg, ProtoAriesRefT::iInpSize, ProtoAriesRefT::iMemGroup, NULL, ProtoAriesRefT::pMemGroupUserData, ProtoAriesRefT::pProtoSsl, PROTOARIES_STATE_LIST, ProtoSSLBind(), ProtoSSLCreate(), ProtoSSLListen(), SocketHtonl(), SocketHtons(), and ProtoAriesRefT::uTimeout.
DIRTYCODE_API int32_t ProtoAriesPeek (ProtoAriesRefT * pProtoAries, int32_t * pKind, int32_t * pCode, char ** ppBody)
See if an incoming packet is waiting (but do not remove from queue).
Parameters
*pProtoAries - reference pointer
*pKind - [out] packet kind (from packet)
*pCode - [out] packet subtype (from packet)
**ppBody - [out] packet data pointer
Returns
int32_t - <0=nothing pending, else size of data
Note
Pointer to data remains valid until call to ProtoAriesRecv
Version
11/01/2002 (gschaefer)
References ProtoAriesMsgHdrT::code, ProtoAriesRefT::iInpProg, ProtoAriesRefT::iInpSize, ProtoAriesMsgHdrT::kind, NULL, ProtoAriesRefT::pInpData, and ProtoAriesUpdate().
Referenced by BuddyApiUpdate(), and ProtoAriesRecv().
DIRTYCODE_API int32_t ProtoAriesRecv (ProtoAriesRefT * pProtoAries, int32_t * pKind, int32_t * pCode, char * pBody, int32_t iSize)
Get a packet from the server (will copy packet to private buffer).
Parameters
*pProtoAries - reference pointer
*pKind - [out] packet kind
*pCode - [out] packet subtype
*pBody - [out] packet data buffer
iSize - size of packet data buffer
Returns
int32_t - <0=error, 0=no error
Note
Can call with body=NULL to remove packet seen with ProtoAriesPeek().
Version
11/01/2002 (gschaefer)
References ds_memcpy(), ProtoAriesRefT::iInpProg, ProtoAriesRefT::iInpSize, NULL, ProtoAriesRefT::pInpData, and ProtoAriesPeek().
Referenced by BuddyApiUpdate().
DIRTYCODE_API void ProtoAriesSecure (ProtoAriesRefT * pProtoAries, ProtoAriesSecureE eSecure)
Define whether the Aries connection should be secure or insecure.
Parameters
*pProtoAries - reference pointer
eSecure - the type of security the connection should use.
Returns
None.
Note
If this is not called then the default is to use PROTOARIES_SECURE_NONE.
Version
03/03/2004 (sbevan)
References ProtoAriesRefT::bUseSSL, and PROTOARIES_SECURE_SSL.
Referenced by BuddyApiCreate2(), and BuddyApiUpdate().
DIRTYCODE_API int32_t ProtoAriesSend (ProtoAriesRefT * pProtoAries, int32_t iKind, int32_t iCode, const char * pBody, int32_t iBodyLen)
Send an Aries packet to the server.
Parameters
*pProtoAries - reference pointer
iKind - packet kind
iCode - packet subtype
*pBody - packet data pointer
iBodyLen - data length
Returns
int32_t - <0=error, 0=no error
Version
11/01/2002 (gschaefer)
References ProtoAriesRefT::bHaveWallet, ProtoAriesMsgHdrT::code, CryptStp1EncryptData(), CryptStp1EncryptHash(), CryptStp1EncryptSize(), ds_memcpy(), FALSE, ProtoAriesRefT::iOutSize, ProtoAriesMsgHdrT::kind, NetPrintf, ProtoAriesRefT::pOutData, ProtoAriesUpdate(), ProtoAriesMsgHdrT::size, and ProtoAriesRefT::Stream.
Referenced by BuddyApiUpdate(), and ProtoAriesConnect().
DIRTYCODE_API void ProtoAriesSetKey (ProtoAriesRefT * pProtoAries, const void * pKey, uint32_t uKeySize)
Initialize the session key for this connection.
Parameters
*pProtoAries - Aries object
*pKey - the session key information
uKeySize - the size of the key in bytes
Returns
None.
Note
A NULL pKey or uKeySize of 0 mean don't use any encryption.
Version
03/03/2004 (sbevan)
05/05/2004 (sbevan) changed to take key&length
References ProtoAriesRefT::bHaveWallet, CryptStp1UseSecret(), ds_memcpy_s(), FALSE, NULL, ProtoAriesRefT::Stream, TRUE, and ProtoAriesRefT::Wallet.
DIRTYCODE_API int32_t ProtoAriesStatus (ProtoAriesRefT * pProtoAries, int32_t iSelect, void * pBuf, int32_t iBufLen)
Return session status info.
Parameters
*pProtoAries - reference pointer
iSelect - status selector
*pBuf - output buffer
iBufLen - output buffer length
Returns
int32_t - selector specific
Note
iSelect can be one of the following:
        'addr' - server ip address
        'cryp' - session crypt status
        'ibuf' - number of bytes queued in the input buffer
        'ladr' - local ip address
        'lptr' - local port number
        'obuf' - number of bytes queued in the output buffer
        'port' - server port number
        'secu' - security status (ProtoAriesSecureE)
        'sock' - aries socket ref
        'stat' - module state
Version
11/01/2002 (gschaefer)
References CryptStp1StreamT::bEncrypt, ProtoAriesRefT::bUseSSL, ProtoAriesRefT::DestAddr, ProtoAriesRefT::eState, ProtoAriesRefT::iInpProg, ProtoAriesRefT::iInpSize, ProtoAriesRefT::iOutProg, ProtoAriesRefT::iOutSize, NULL, ProtoAriesRefT::pInpData, ProtoAriesRefT::pProtoSsl, ProtoSSLStat(), SocketNtohl(), SocketNtohs(), ProtoAriesRefT::Stream, ProtoAriesRefT::uLocalAddr, and ProtoAriesRefT::uLocalPort.
DIRTYCODE_API uint32_t ProtoAriesTick (ProtoAriesRefT * pProtoAries)
Return timebase for easy client calculations. Returns number of elapsed milliseconds from some point in time (typically system startup). Overflow occurs in approximately 46 days.
Parameters
*pProtoAries - reference pointer
Returns
uint32_t - epoch tick in milliseconds
Version
11/01/2002 (gschaefer)
References NetTick().
Referenced by _BuddyApiReconnect(), BuddyApiConnect(), BuddyApiPresSend(), and BuddyApiUpdate().
DIRTYCODE_API int32_t ProtoAriesUnconnect (ProtoAriesRefT * pProtoAries)
Terminate Aries connection to server.
Parameters
*pProtoAries - reference pointer
Returns
int32_t - zero=success, negative=error
Version
11/01/2002 (gschaefer)
References ProtoAriesRefT::eState, ProtoAriesRefT::iOutProg, ProtoAriesRefT::iOutSize, NULL, ProtoAriesRefT::pProtoSsl, PROTOARIES_STATE_DISC, and ProtoSSLDestroy().
Referenced by BuddyApiDisconnect(), BuddyApiUpdate(), and ProtoAriesUpdate().
DIRTYCODE_API int32_t ProtoAriesUnlisten (ProtoAriesRefT * pProtoAries)
Terminate Aries server listening.
Parameters
*pProtoAries - reference pointer
Returns
int32_t - zero=success, negative=error
Version
11/01/2002 (gschaefer)
References ProtoAriesRefT::eState, ProtoAriesRefT::iOutProg, ProtoAriesRefT::iOutSize, NULL, ProtoAriesRefT::pProtoSsl, PROTOARIES_STATE_DISC, and ProtoSSLDestroy().
DIRTYCODE_API void ProtoAriesUpdate (ProtoAriesRefT * pProtoAries)
Perform actual "work" for protocol. This function should be called at least every 100ms to allow packets to be processed at a reasonable speed.
Parameters
*pProtoAries - reference pointer
Returns
None.
Version
11/01/2002 (gschaefer)
References ProtoAriesRefT::aInpHead, ProtoAriesRefT::bUseSSL, ProtoAriesMsgHdrT::code, CryptStp1DecryptData(), CryptStp1DecryptHash(), CryptStp1DecryptSize(), CryptStp1UseSecret(), ProtoAriesRefT::DestAddr, DirtyMemGroupEnter(), DirtyMemGroupLeave(), ds_memcpy(), ProtoAriesRefT::eState, ProtoAriesRefT::iBufSize, ProtoAriesRefT::iInpProg, ProtoAriesRefT::iInpSize, ProtoAriesRefT::iMemGroup, ProtoAriesRefT::iOutProg, ProtoAriesRefT::iOutSize, iStat, ProtoAriesMsgHdrT::kind, NetPrintf, NetTick(), NULL, ProtoAriesRefT::pInpData, ProtoAriesRefT::pMemGroupUserData, ProtoAriesRefT::pOutData, ProtoAriesRefT::pProtoSsl, PROTOARIES_STATE_CONN, PROTOARIES_STATE_DISC, PROTOARIES_STATE_LIST, PROTOARIES_STATE_ONLN, ProtoAriesUnconnect(), ProtoSSLAccept(), ProtoSSLConnect(), ProtoSSLCreate(), ProtoSSLDestroy(), ProtoSSLRecv(), ProtoSSLSend(), ProtoSSLStat(), ProtoSSLUpdate(), ProtoAriesMsgHdrT::size, SocketNtohl(), SocketNtohs(), ProtoAriesRefT::Stream, ProtoAriesRefT::strServerName, ProtoAriesRefT::uLocalAddr, ProtoAriesRefT::uLocalPort, and ProtoAriesRefT::uTimeout.
Referenced by BuddyApiUpdate(), ProtoAriesPeek(), and ProtoAriesSend().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:21