#!/usr/bin/python

import os, commands, sys

total = 60

if len(sys.argv) == 2:
	total = sys.argv[1]

ls = commands.getoutput('ls')

lates = ['-1'] * total
files = ls.split()

datafile = open('data.txt', 'w')
current = 0
for filename in files:
	if filename.find('gsrvstress') != -1 and filename.find('.log') != -1:
		file = open(filename)

		for line in file.readlines():
			if line.find('stressgameplay:') != -1:
				latepos = line.find('late=')
				if latepos != -1:
					lates[current] = line[latepos+5:latepos+8].strip()
					current = current + 1
					if current == total:
						current = 0

		tab = ''
		for late in lates:
			datafile.write(tab + late)
			tab = '\t'
		datafile.write('\n')

datafile.close()
