DirtySock: UserApi
UserApi
User
Data Structures
struct UserApiRichPresenceT
struct UserApiPresenceT
struct UserApiProfileT
struct UserApiUserDataT
struct UserApiEndOfListT
union UserApiEventDetailsT
struct UserApiEventDataT
struct UserApiPostResponseT
struct UserApiNotifyTitleDataT
struct UserApiNotifyPresenceDataT
struct UserApiNotifyRichPresenceDataT
struct UserApiNotifyProfileUpdateDataT
union UserApiNotifyDataT
Macros
#define USERAPI_NOTIFY_LIST_MAX_SIZE (50)
< Maximum sizes of various strings
#define USERAPI_GAMERTAG_MAXLEN (16)
#define USERAPI_AVATAR_URL_MAXLEN (256)
#define USERAPI_DISPLAYNAME_MAXLEN (256)
#define USERAPI_PLATFORM_NAME_MAXLEN (64)
#define USERAPI_TITLE_NAME_MAXLEN (128)
#define USERAPI_TITLE_ID_MAXLEN (64)
#define USERAPI_RICH_PRES_MAXLEN (512)
#define USERAPI_GAME_DATA_MAXLEN (172)
#define USERAPI_MASK_PROFILE (0x01)
#define USERAPI_MASK_PRESENCE (0x02)
#define USERAPI_MASK_RICH_PRESENCE (0x04)
#define USERAPI_MASK_PROFILES (0x08)
Typedefs
typedef enum UserApiEventErrorE UserApiEventErrorE
< UserApi Error types
typedef enum UserApiNotifyTypeE UserApiNotifyTypeE
Categories of data for UserApi callbacks.
typedef enum UserApiEventTypeE UserApiEventTypeE
List of possible online statuses.
typedef enum UserApiOnlineStatusE UserApiOnlineStatusE
Rich presence response data structure.
typedef struct UserApiRichPresenceT UserApiRichPresenceT
Presence data response structure.
typedef struct UserApiPresenceT UserApiPresenceT
Profile data response structure.
typedef struct UserApiProfileT UserApiProfileT
General response structure.
typedef struct UserApiUserDataT UserApiUserDataT
Request metadata response structure.
typedef struct UserApiEndOfListT UserApiEndOfListT
Container union for responses.
typedef union UserApiEventDetailsT UserApiEventDetailsT
User metadata fpr USERAPI_EVENT_DATA.
typedef struct UserApiEventDataT UserApiEventDataT
Response from data post style request.
typedef struct UserApiPostResponseT UserApiPostResponseT
opaque module ref
typedef struct UserApiRefT UserApiRefT
Title change notification data.
typedef struct
UserApiNotifyTitleDataT UserApiNotifyTitleDataT
Presence change notification data, note that this remains incomplete since minimal data is provided by first parties.
typedef struct
UserApiNotifyPresenceDataT UserApiNotifyPresenceDataT
Rich presence change notification data, note that this remains incomplete since minimal data is provided by first parties.
typedef struct
UserApiNotifyRichPresenceDataT UserApiNotifyRichPresenceDataT
Rich presence change notification data, note that this remains incomplete since minimal data is provided by first parties.
typedef struct
UserApiNotifyProfileUpdateDataT UserApiNotifyProfileUpdateDataT
container union for notification data
typedef union UserApiNotifyDataT UserApiNotifyDataT
callback types
typedef void(UserApiCallbackT)(UserApiRefT *pRef, UserApiEventDataT *pUserApiEventData, void *pUserData)
typedef void(UserApiPostCallbackT)(UserApiRefT *pRef, UserApiPostResponseT *pResponse, void *pUserData)
typedef void(UserApiUpdateCallbackT)(UserApiRefT *pRef, UserApiNotifyTypeE eNotifyType, UserApiNotifyDataT *pData, void *pUserData)
Enumerations
enum UserApiEventErrorE {
USERAPI_ERROR_OK = 0,
USERAPI_ERROR_REQUEST_FAILED = -100,
USERAPI_ERROR_REQUEST_NOT_FOUND,
USERAPI_ERROR_REQUEST_FORBIDDEN,
USERAPI_ERROR_REQUEST_SERVER_ERROR,
USERAPI_ERROR_REQUEST_UNAVAILABLE,
USERAPI_ERROR_REQUEST_TIMEOUT,
USERAPI_ERROR_UNSUPPORTED,
USERAPI_ERROR_INPROGRESS,
USERAPI_ERROR_REQUEST_PARSE_FAILED,
USERAPI_ERROR_NO_USER,
USERAPI_ERROR_FULL
}
< UserApi Error types
enum UserApiNotifyTypeE {
USERAPI_NOTIFY_PRESENCE_UPDATE = 0,
USERAPI_NOTIFY_TITLE_UPDATE,
USERAPI_NOTIFY_RICH_PRESENCE_UPDATE,
USERAPI_NOTIFY_PROFILE_UPDATE
}
enum UserApiEventTypeE {
USERAPI_EVENT_DATA = 0,
USERAPI_EVENT_END_OF_LIST
}
enum UserApiOnlineStatusE {
USERAPI_PRESENCE_UNKNOWN = 0,
USERAPI_PRESENCE_OFFLINE,
USERAPI_PRESENCE_ONLINE,
USERAPI_PRESENCE_AWAY
}
Functions
DIRTYCODE_API UserApiRefT * UserApiCreate (void)
Starts UserApi.
DIRTYCODE_API int32_t UserApiDestroy (UserApiRefT *pRef)
Starts shutting down module. Module will not accept new requests, and will abort ongoing ones. Also, registered UserApiCallbackT callback will not be called even if there is data available for processing.
DIRTYCODE_API int32_t UserApiStatus (UserApiRefT *pRef, int32_t iSelect, void *pBuf, int32_t iBufSize)
Get status information.
DIRTYCODE_API int32_t UserApiControl (UserApiRefT *pRef, int32_t iControl, int32_t iValue, int32_t iValue2, void *pValue)
Control behavior of module.
DIRTYCODE_API int32_t UserApiRequestProfilesAsync (UserApiRefT *pRef, uint32_t uUserIndex, DirtyUserT *pLookupUsers, int32_t iLookupUsersLength, UserApiCallbackT *pCallback, void *pUserData)
Starts the process to retrieve user information of players. pLookupUsers is a pointer to the first DirtyUserT, and iLookupUsersLength is the number of DirtyUserTs.
DIRTYCODE_API int32_t UserApiRequestProfileAsync (UserApiRefT *pRef, uint32_t uUserIndex, DirtyUserT *pLookupUser, UserApiCallbackT *pCallback, uint32_t uUserDataMask, void *pUserData)
Starts the process to retrieve profile information of players. pLookupUser is a pointer to DirtyUserT.
DIRTYCODE_API int32_t UserApiRequestPresenceAsync (UserApiRefT *pRef, uint32_t uUserIndex, DirtyUserT *pLookupUser, UserApiCallbackT *pCallback, uint32_t uUserDataMask, void *pUserData)
Starts the process to retrieve profile information of players. pLookupUser is a pointer to DirtyUserT.
DIRTYCODE_API int32_t UserApiRequestRichPresenceAsync (UserApiRefT *pRef, uint32_t uUserIndex, DirtyUserT *pLookupUser, UserApiCallbackT *pCallback, uint32_t uUserDataMask, void *pUserData)
Starts the process to retrieve rich presence information of players.
DIRTYCODE_API int32_t UserApiPostRecentlyMetAsync (UserApiRefT *pRef, uint32_t uUserIndex, DirtyUserT *pPlayerMet, UserApiPostCallbackT *pCallback, void *pUserData)
Starts the process to post that a certain player was recently encountered.
DIRTYCODE_API int32_t UserApiPostRichPresenceAsync (UserApiRefT *pRef, uint32_t uUserIndex, UserApiRichPresenceT *pData, UserApiPostCallbackT *pCallback, void *pUserData)
Starts the process to post that a certain player was recently encountered.
DIRTYCODE_API int32_t UserApiRegisterUpdateEvent (UserApiRefT *pRef, uint32_t uUserIndex, UserApiNotifyTypeE eType, UserApiUpdateCallbackT *pNotifyCb, void *pUserData)
Register for notifications from first part.
DIRTYCODE_API void UserApiUpdate (UserApiRefT *pRef)
Update the internal state of the module, and call registered UserApiCallbackT callback if there are GamerCard/Profile responses available. This function should be called periodically.
DIRTYCODE_API int32_t UserApiCancel (UserApiRefT *pRef, uint32_t uUserIndex)
Cancel all queries to the 1st party.
Detailed Description
Macro Definition Documentation
#define USERAPI_AVATAR_URL_MAXLEN (256)
#define USERAPI_DISPLAYNAME_MAXLEN (256)
#define USERAPI_GAME_DATA_MAXLEN (172)
#define USERAPI_GAMERTAG_MAXLEN (16)
#define USERAPI_MASK_PRESENCE (0x02)
Referenced by UserApiPlatRequestRichPresence(), UserApiRequestPresenceAsync(), UserApiUpdate(), and UserListApiUpdate().
#define USERAPI_MASK_PROFILE (0x01)
Referenced by UserApiRequestPresenceAsync(), UserApiUpdate(), and UserListApiUpdate().
#define USERAPI_MASK_PROFILES (0x08)
Referenced by UserApiRequestProfilesAsync(), and UserApiUpdate().
#define USERAPI_MASK_RICH_PRESENCE (0x04)
Referenced by UserApiRequestPresenceAsync(), UserApiUpdate(), and UserListApiUpdate().
#define USERAPI_NOTIFY_LIST_MAX_SIZE (50)
< Maximum sizes of various strings
Referenced by UserApiCreate(), UserApiPlatUpdate(), UserApiRegisterUpdateEvent(), and UserApiUpdate().
#define USERAPI_PLATFORM_NAME_MAXLEN (64)
#define USERAPI_RICH_PRES_MAXLEN (512)
Referenced by UserApiPlatRequestPostRichPresence().
#define USERAPI_TITLE_ID_MAXLEN (64)
#define USERAPI_TITLE_NAME_MAXLEN (128)
Typedef Documentation
typedef void(UserApiCallbackT)(UserApiRefT *pRef, UserApiEventDataT *pUserApiEventData, void *pUserData)
typedef struct UserApiEndOfListT UserApiEndOfListT
Container union for responses.
typedef struct UserApiEventDataT UserApiEventDataT
Response from data post style request.
typedef union UserApiEventDetailsT UserApiEventDetailsT
User metadata fpr USERAPI_EVENT_DATA.
typedef enum UserApiEventErrorE UserApiEventErrorE
< UserApi Error types
Type of first party notifications
typedef enum UserApiEventTypeE UserApiEventTypeE
List of possible online statuses.
typedef union UserApiNotifyDataT UserApiNotifyDataT
callback types
typedef struct UserApiNotifyPresenceDataT UserApiNotifyPresenceDataT
Rich presence change notification data, note that this remains incomplete since minimal data is provided by first parties.
typedef struct UserApiNotifyProfileUpdateDataT UserApiNotifyProfileUpdateDataT
container union for notification data
typedef struct UserApiNotifyRichPresenceDataT UserApiNotifyRichPresenceDataT
Rich presence change notification data, note that this remains incomplete since minimal data is provided by first parties.
typedef struct UserApiNotifyTitleDataT UserApiNotifyTitleDataT
Presence change notification data, note that this remains incomplete since minimal data is provided by first parties.
typedef enum UserApiNotifyTypeE UserApiNotifyTypeE
Categories of data for UserApi callbacks.
typedef enum UserApiOnlineStatusE UserApiOnlineStatusE
Rich presence response data structure.
typedef void(UserApiPostCallbackT)(UserApiRefT *pRef, UserApiPostResponseT *pResponse, void *pUserData)
typedef struct UserApiPostResponseT UserApiPostResponseT
opaque module ref
typedef struct UserApiPresenceT UserApiPresenceT
Profile data response structure.
typedef struct UserApiProfileT UserApiProfileT
General response structure.
typedef struct UserApiRefT UserApiRefT
Title change notification data.
typedef struct UserApiRichPresenceT UserApiRichPresenceT
Presence data response structure.
typedef void(UserApiUpdateCallbackT)(UserApiRefT *pRef, UserApiNotifyTypeE eNotifyType, UserApiNotifyDataT *pData, void *pUserData)
typedef struct UserApiUserDataT UserApiUserDataT
Request metadata response structure.
Enumeration Type Documentation
enum UserApiEventErrorE
< UserApi Error types
Enumerator
USERAPI_ERROR_OK
USERAPI_ERROR_REQUEST_FAILED
USERAPI_ERROR_REQUEST_NOT_FOUND
USERAPI_ERROR_REQUEST_FORBIDDEN
USERAPI_ERROR_REQUEST_SERVER_ERROR
USERAPI_ERROR_REQUEST_UNAVAILABLE
USERAPI_ERROR_REQUEST_TIMEOUT
USERAPI_ERROR_UNSUPPORTED
USERAPI_ERROR_INPROGRESS
USERAPI_ERROR_REQUEST_PARSE_FAILED
USERAPI_ERROR_NO_USER
USERAPI_ERROR_FULL
enum UserApiEventTypeE
Enumerator
USERAPI_EVENT_DATA
USERAPI_EVENT_END_OF_LIST
enum UserApiNotifyTypeE
Enumerator
USERAPI_NOTIFY_PRESENCE_UPDATE
USERAPI_NOTIFY_TITLE_UPDATE
USERAPI_NOTIFY_RICH_PRESENCE_UPDATE
USERAPI_NOTIFY_PROFILE_UPDATE
enum UserApiOnlineStatusE
Enumerator
USERAPI_PRESENCE_UNKNOWN
USERAPI_PRESENCE_OFFLINE
USERAPI_PRESENCE_ONLINE
USERAPI_PRESENCE_AWAY
Function Documentation
DIRTYCODE_API int32_t UserApiCancel (UserApiRefT * pRef, uint32_t uUserIndex)
Cancel all queries to the 1st party.
Parameters
*pRef - pointer to UserApiT module reference
uUserIndex - index of user associated with this request
Returns
int32_t - result of abort request; see UserApiPlatAbortRequests()
Version
05/10/2013 (mcorcoran) - First version
References UserApiRefT::pPostCallback, UserApiRefT::pUserCallback, UserApiRefT::pUserDataPost, and UserApiPlatAbortRequests().
DIRTYCODE_API int32_t UserApiControl (UserApiRefT * pRef, int32_t iControl, int32_t iValue, int32_t iValue2, void * pValue)
Control behavior of module.
Parameters
*pRef - pointer to module state
iControl - status selector
iValue - control value
iValue2 - control value
*pValue - control value
Returns
int32_t - Return 0 if successful. Otherwise a selector specific error
Note
iControl can be one of the following:
        'abrt' - Abort the current request associated with the user at index iValue
        'avsz' - (PS4 only) Set which avatar size will be retrieved. iValue = 's' for small, 'm' for medium and 'l' for big. 's' is the default value, and this is just functional for PS4.
Version
05/10/2013 (mcorcoran) - First version
References UserApiRefT::aLookupUsers, UserApiRefT::bLookupUserAvailable, DirtyMemFree(), UserApiRefT::iLookupUserIndex, UserApiRefT::iLookupUsersLength, UserApiRefT::iMemGroup, UserApiUserContextT::iTotalErrors, UserApiUserContextT::iTotalReceived, UserApiUserContextT::iTotalRequested, NETCONN_MAXLOCALUSERS, NetPrintf, UserApiRefT::pMemGroupUserData, UserApiRefT::pUserCallback, UserApiRefT::pUserData, TRUE, USERAPI_MEMID, UserApiPlatAbortRequests(), UserApiPlatControl(), and UserApiRefT::UserContextList.
DIRTYCODE_API UserApiRefT* UserApiCreate (void)
Starts UserApi.
Returns
UserApiRefT* - pointer to module ref if successful, NULL otherwise.
Version
05/10/2013 (mcorcoran) - First version
References UserApiRefT::aLookupUsers, UserApiRefT::bAvailableDataIndex, UserApiRefT::bAvailableDataIndexPresence, UserApiRefT::bAvailableDataIndexRichPresence, UserApiRefT::bAvailableDataIndexRMP, UserApiRefT::bLookupUserAvailable, UserApiRefT::bPresenceNotificationStarted, UserApiRefT::bProfileUpdateNotificationStarted, UserApiRefT::bRichPresenceNotificationStarted, UserApiRefT::bShuttingDown, UserApiRefT::bTitleNotificationStarted, UserApiRefT::crit, DirtyMemAlloc(), DirtyMemGroupQuery(), FALSE, UserApiRefT::iLookupUserIndex, UserApiRefT::iLookupUsersLength, UserApiRefT::iMemGroup, NETCONN_MAXLOCALUSERS, NetCritInit(), NetPrintf, UserApiNotificationT::pCallback, UserApiRefT::pMemGroupUserData, UserApiRefT::postCrit, UserApiRefT::pPlatformData, UserApiRefT::pPostCallback, pRef, UserApiRefT::PresenceNotification, UserApiRefT::ProfileUpdateNotification, UserApiRefT::pUserCallback, UserApiNotificationT::pUserData, UserApiRefT::pUserData, UserApiRefT::pUserDataPost, UserApiRefT::RichPresenceNotification, UserApiRefT::TitleNotification, TRUE, USERAPI_MEMID, USERAPI_NOTIFY_LIST_MAX_SIZE, UserApiDestroy(), UserApiPlatCreateData(), and UserApiRefT::uUserDataMask.
DIRTYCODE_API int32_t UserApiDestroy (UserApiRefT * pRef)
Starts shutting down module. Module will not accept new requests, and will abort ongoing ones. Also, registered UserApiCallbackT callback will not be called even if there is data available for processing.
Parameters
*pRef - pointer to UserApiT module reference
Returns
int32_t - 0 if successful. Otherwise -1
Version
05/10/2013 (mcorcoran) - First version
References UserApiRefT::bAvailableDataIndex, UserApiRefT::bAvailableDataIndexPresence, UserApiRefT::bAvailableDataIndexRichPresence, UserApiRefT::bAvailableDataIndexRMP, UserApiRefT::bShuttingDown, UserApiRefT::crit, FALSE, NETCONN_MAXLOCALUSERS, NetConnControl(), NetCritEnter(), NetCritLeave(), NetPrintf, and TRUE.
Referenced by UserApiCreate().
DIRTYCODE_API int32_t UserApiPostRecentlyMetAsync (UserApiRefT * pRef, uint32_t uUserIndex, DirtyUserT * pPlayerMet, UserApiPostCallbackT * pCallback, void * pUserData)
Starts the process to post that a certain player was recently encountered.
Parameters
*pRef - pointer to UserApiT module reference
uUserIndex - Index used to specify which local user owns the request
*pPlayerMet - Pointer to the DityUserT to add to the recently met players list
*pCallback - Callback that is going to be called when responses for these requests are received
*pUserData - This pointer is going to be passed to the callback when it is called. This parameter can be NULL
Returns
int32_t - Return 0 if successful, -1 otherwise.
Version
06/16/2013 (amakoukji) - First version
References UserApiUserContextT::iTotalErrors, UserApiUserContextT::iTotalReceived, UserApiUserContextT::iTotalRequested, NETCONN_MAXLOCALUSERS, NetCritEnter(), NetCritLeave(), NetPrintf, UserApiRefT::postCrit, UserApiRefT::pPostCallback, UserApiRefT::pUserDataPost, UserApiPlatRequestRecentlyMet(), and UserApiRefT::UserRmpList.
DIRTYCODE_API int32_t UserApiPostRichPresenceAsync (UserApiRefT * pRef, uint32_t uUserIndex, UserApiRichPresenceT * pData, UserApiPostCallbackT * pCallback, void * pUserData)
Starts the process to post that a certain player was recently encountered.
Parameters
*pRef - pointer to UserApiT module reference
uUserIndex - Index used to specify which local user owns the request
*pData - Rich Presence to post
*pCallback - Callback that is going to be called when responses for these requests are received
*pUserData - This pointer is going to be passed to the callback when it is called. This parameter can be NULL
Returns
int32_t - Return 0 if successful, -1 otherwise.
Version
06/16/2013 (amakoukji) - First version
References UserApiUserContextT::iTotalErrors, UserApiUserContextT::iTotalReceived, UserApiUserContextT::iTotalRequested, NETCONN_MAXLOCALUSERS, NetCritEnter(), NetCritLeave(), NetPrintf, UserApiRefT::postCrit, UserApiRefT::pPostCallback, UserApiRefT::pUserDataPost, UserApiPlatRequestPostRichPresence(), and UserApiRefT::UserRmpList.
DIRTYCODE_API int32_t UserApiRegisterUpdateEvent (UserApiRefT * pRef, uint32_t uUserIndex, UserApiNotifyTypeE eType, UserApiUpdateCallbackT * pNotifyCb, void * pUserData)
Register for notifications from first part.
Parameters
*pRef - pointer to UserApiT module reference
uUserIndex - Index used to specify which local user owns the request
eType - type of event to register for
*pNotifyCb - Callback that is going to be called when responses for these requests are received
*pUserData - This pointer is going to be passed to the callback when it is called. This parameter can be NULL
Returns
int32_t - Return 0 if successful, -1 otherwise.
Version
06/16/2013 (amakoukji) - First version
References UserApiRefT::bPresenceNotificationStarted, UserApiRefT::bProfileUpdateNotificationStarted, UserApiRefT::bRichPresenceNotificationStarted, UserApiRefT::bTitleNotificationStarted, FALSE, UserApiRefT::PresenceNotification, UserApiRefT::ProfileUpdateNotification, UserApiRefT::RichPresenceNotification, UserApiRefT::TitleNotification, TRUE, USERAPI_ERROR_FULL, USERAPI_ERROR_OK, USERAPI_ERROR_UNSUPPORTED, USERAPI_NOTIFY_LIST_MAX_SIZE, USERAPI_NOTIFY_PRESENCE_UPDATE, USERAPI_NOTIFY_PROFILE_UPDATE, USERAPI_NOTIFY_RICH_PRESENCE_UPDATE, USERAPI_NOTIFY_TITLE_UPDATE, and UserApiPlatRegisterUpdateEvent().
DIRTYCODE_API int32_t UserApiRequestPresenceAsync (UserApiRefT * pRef, uint32_t uUserIndex, DirtyUserT * pLookupUser, UserApiCallbackT * pCallback, uint32_t uUserDataMask, void * pUserData)
Starts the process to retrieve profile information of players. pLookupUser is a pointer to DirtyUserT.
Parameters
*pRef - pointer to UserApiT module reference
uUserIndex - Index used to specify which local user owns the request
*pLookupUser - Pointer to DityUserT
*pCallback - Callback that is going to be called when responses for these requests are received
uUserDataMask - A mask value defining which elements are needed; USERAPI_MASK_*
*pUserData - This pointer is going to be passed to the callback when it is called. This parameter can be NULL
Returns
int32_t - Return 0 if successful, -1 otherwise.
Version
09/12/2013 (amakoukji) - First version
References UserApiRefT::crit, UserApiUserContextT::iTotalErrors, UserApiUserContextT::iTotalReceived, UserApiUserContextT::iTotalRequested, NetCritEnter(), NetCritLeave(), NetPrintf, UserApiRefT::pPostCallback, UserApiRefT::pUserCallback, UserApiRefT::pUserData, USERAPI_MASK_PRESENCE, USERAPI_MASK_PROFILE, USERAPI_MASK_RICH_PRESENCE, UserApiPlatRequestPresence(), UserApiPlatRequestProfile(), UserApiPlatRequestRichPresence(), UserApiRefT::UserContextList, UserApiRefT::UserPresenceList, UserApiRefT::UserRichPresenceList, and UserApiRefT::uUserDataMask.
Referenced by UserApiRequestProfileAsync().
DIRTYCODE_API int32_t UserApiRequestProfileAsync (UserApiRefT * pRef, uint32_t uUserIndex, DirtyUserT * pLookupUser, UserApiCallbackT * pCallback, uint32_t uUserDataMask, void * pUserData)
Starts the process to retrieve profile information of players. pLookupUser is a pointer to DirtyUserT.
Parameters
*pRef - pointer to UserApiT module reference
uUserIndex - Index used to specify which local user owns the request
*pLookupUser - Pointer to DityUserT
*pCallback - Callback that is going to be called when responses for these requests are received
uUserDataMask - A mask value defining which elements are needed; USERAPI_MASK_*
*pUserData - This pointer is going to be passed to the callback when it is called. This parameter can be NULL
Returns
int32_t - Return 0 if successful, -1 otherwise.
Version
09/12/2013 (amakoukji) - First version
References UserApiRequestPresenceAsync().
Referenced by UserApiRequestRichPresenceAsync().
DIRTYCODE_API int32_t UserApiRequestProfilesAsync (UserApiRefT * pRef, uint32_t uUserIndex, DirtyUserT * pLookupUsers, int32_t iLookupUsersLength, UserApiCallbackT * pCallback, void * pUserData)
Starts the process to retrieve user information of players. pLookupUsers is a pointer to the first DirtyUserT, and iLookupUsersLength is the number of DirtyUserTs.
Parameters
*pRef - pointer to UserApiT module reference
uUserIndex - Index used to specify which local user owns the request
*pLookupUsers - Pointer to first DityUserT in an array of iLookupUsersLength elements
iLookupUsersLength - Number of elements in the pLookupUsers array
*pCallback - Callback that is going to be called when responses for these requests are received
*pUserData - This pointer is going to be passed to the callback when it is called. This parameter can be NULL
Returns
int32_t - Return 0 if successful, -1 otherwise.
Version
05/10/2013 (mcorcoran) - First version
09/12/2013 (amakoukji) - Second pass with presence
References UserApiRefT::crit, UserApiUserContextT::iTotalErrors, UserApiUserContextT::iTotalReceived, UserApiUserContextT::iTotalRequested, NetCritEnter(), NetCritLeave(), NetPrintf, UserApiRefT::pPostCallback, UserApiRefT::pUserCallback, UserApiRefT::pUserData, USERAPI_MASK_PROFILES, UserApiPlatRequestProfile(), UserApiRefT::UserContextList, UserApiRefT::UserPresenceList, and UserApiRefT::uUserDataMask.
DIRTYCODE_API int32_t UserApiRequestRichPresenceAsync (UserApiRefT * pRef, uint32_t uUserIndex, DirtyUserT * pLookupUser, UserApiCallbackT * pCallback, uint32_t uUserDataMask, void * pUserData)
Starts the process to retrieve rich presence information of players.
Parameters
*pRef - pointer to UserApiT module reference
uUserIndex - Index used to specify which local user owns the request
*pLookupUser - Pointer to DirtyUserT
*pCallback - Callback that is going to be called when responses for these requests are received
uUserDataMask - A mask value defining which elements are needed; USERAPI_MASK_*
*pUserData - This pointer is going to be passed to the callback when it is called. This parameter can be NULL
Returns
int32_t - Return 0 if successful, -1 otherwise.
Note
For PS4: strData contains GameStatus pData == NULL means delete the rich presence For XB1: strData contains the Rich Presence String as defined in your Service Config Workbook More complex rich presence requests for XB1 will need to be set through their API directly
Version
09/12/2013 (amakoukji) - First version
References UserApiRequestProfileAsync().
DIRTYCODE_API int32_t UserApiStatus (UserApiRefT * pRef, int32_t iSelect, void * pBuf, int32_t iBufSize)
Get status information.
Parameters
*pRef - pointer to module state
iSelect - status selector
*pBuf - [out] storage for selector-specific output
iBufSize - size of output buffer
Returns
int32_t - Return 0 if successful. Otherwise a selector specific error
Note
There is currently nothing to query with this module. This is a placeholder for future implementations.
Version
05/10/2013 (mcorcoran) - First version
References NetPrintf.
DIRTYCODE_API void UserApiUpdate (UserApiRefT * pRef)
Update the internal state of the module, and call registered UserApiCallbackT callback if there are GamerCard/Profile responses available. This function should be called periodically.
Parameters
*pRef - pointer to UserApiT module reference
Version
05/10/2013 (mcorcoran) - First version
References _UserApiProcessPresenceResponse(), _UserApiProcessProfileResponse(), _UserApiProcessRichPresenceResponse(), _UserApiTriggerCallback(), _UserApiTriggerPostCallback(), UserApiRefT::bAvailableDataIndex, UserApiRefT::bAvailableDataIndexPresence, UserApiRefT::bAvailableDataIndexRichPresence, UserApiRefT::bAvailableDataIndexRMP, UserApiRefT::bLookupUserAvailable, UserApiRefT::crit, DirtyMemFree(), FALSE, UserApiRefT::iMemGroup, UserApiUserContextT::iTotalErrors, UserApiUserContextT::iTotalReceived, UserApiUserContextT::iTotalRequested, NETCONN_MAXLOCALUSERS, NetCritEnter(), NetCritLeave(), NetPrintf, UserApiRefT::pMemGroupUserData, UserApiNotifyEventT::pNotificationData, UserApiNotifyEventT::pNotificationList, UserApiNotifyEventT::pNotificationType, UserApiRefT::postCrit, UserApiUserDataT::Presence, UserApiUserDataT::Profile, UserApiUserDataT::RichPresence, TRUE, USERAPI_ERROR_OK, USERAPI_EVENT_DATA, USERAPI_EVENT_END_OF_LIST, USERAPI_MASK_PRESENCE, USERAPI_MASK_PROFILE, USERAPI_MASK_PROFILES, USERAPI_MASK_RICH_PRESENCE, USERAPI_MAX_QUEUED_NOTIFICATIONS, USERAPI_NOTIFY_LIST_MAX_SIZE, UserApiRefT::UserApiNotifyEvent, UserApiPlatUpdate(), UserApiRefT::UserContextList, USERLISTAPI_MEMID, UserApiRefT::UserRmpList, UserApiRefT::uUserDataMask, UserApiUserDataT::uUserDataMask, and UserApiNotifyEventT::uUserIndex.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:34:37