tasks:
    - path: Reference\Tasks\Structured XML Tasks
      includes:
        - EA.Eaconfig.Structured.*
      excludes:
        - EA.Eaconfig.Structured.Documentation.GenerateStructuredDocs
        - EA.Eaconfig.Structured.SPUProgramTask
        - EA.Eaconfig.Structured.SPULibraryTask
        - EA.Eaconfig.Structured.SpuSubsystemGroupPublicData
        - EA.Eaconfig.Structured.GenerateStructuredDocs
    - path: Reference\Tasks\NAnt Core Tasks\General Tasks
      includes:
        - NAnt.Core.Tasks.*
        - NAnt.ZipTasks.*
      excludes:
        - NAnt.Core.Tasks.SysInfoTask
        - NAnt.Core.Tasks.MetricTask
    - path: Reference\Tasks\NAnt Core Tasks\Perforce Tasks
      includes:
        - NAnt.PerforceTasks.*
    - path: Reference\Tasks\NAnt Core Tasks\Build Tasks\Native Tasks
      includes:
        - EA.CPlusPlusTasks.*
    - path: Reference\Tasks\NAnt Core Tasks\Build Tasks\DotNet Tasks
      includes:
        - NAnt.DotNetTasks.*
    - path: Reference\Tasks\Framework Tasks
      includes:
        - EA.CallTargetIfOutOfDate.*
        - EA.FrameworkTasks.*
        - EA.Eaconfig.GetModuleBaseType
        - EA.Eaconfig.RepeatExecifTask
      excludes:
        - EA.FrameworkTasks.VerifyPackageSignatureTask
        - EA.FrameworkTasks.SignPackageTask
    - path: Reference\Tasks\Framework Internal Tasks
      includes:
        - EA.Config.Backends.VisualStudio.sln_taskdef.*
        - EA.Eaconfig.*
        - EA.GenerateBulkBuildFiles.*
      excludes:
        - EA.Eaconfig.Structured.*
        - EA.Eaconfig.GenerateBuildOptionset
        - EA.Eaconfig.ScriptInitTask
        - EA.Eaconfig.CommaSeparatedListTask
        - EA.Eaconfig.GetModuleBaseType
        - EA.Eaconfig.RepeatExecifTask
    - path: Reference\Tasks\Deprecated Tasks
      includes:
        - NAnt.Core.Tasks.SysInfoTask
        - EA.Eaconfig.GenerateBuildOptionset
        - EA.Eaconfig.Structured.SPUProgramTask
        - EA.Eaconfig.Structured.SPULibraryTask
        - EA.Eaconfig.Structured.SpuSubsystemGroupPublicData
        - EA.Eaconfig.ScriptInitTask
        - EA.Eaconfig.CommaSeparatedListTask
        - NAnt.Core.Tasks.MetricTask
        - EA.FrameworkTasks.VerifyPackageSignatureTask
        - EA.FrameworkTasks.SignPackageTask
functions:
    - path: Reference\Functions
      includes:
        - EA.Eaconfig.*
        - NAnt.Core.Functions.*
        - NAnt.Win32Tasks.Functions.*
    