DirtySock: sort.c File Reference
sort.c File Reference
High performance memory based merge-sort routine. Does temporarily require twice the memory of the sort array (though this is not usually a problem as long as the sort array is small objects such as pointers or small structures). Performance is O(n log n) which allows it to provide very consistant and fast performance for even extremely large data sets. This version is optimized so that mostly-sorted data gets completely sorted in very few steps.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "DirtySDK/dirtysock/dirtymem.h"
#include "DirtySDK/platform.h"
#include "DirtySDK/util/sort.h"
Macros
#define STACK_ELEM 512
#define STACK_SWAP 1024
Functions
void LobbyMSort (void *refptr, void *base, int32_t nmemb, int32_t size, int32_t(*compare)(void *refptr, const void *, const void *))
Perform mergesort on fixed width array.
Detailed Description
High performance memory based merge-sort routine. Does temporarily require twice the memory of the sort array (though this is not usually a problem as long as the sort array is small objects such as pointers or small structures). Performance is O(n log n) which allows it to provide very consistant and fast performance for even extremely large data sets. This version is optimized so that mostly-sorted data gets completely sorted in very few steps.
Note
None.
Attention
Copyright (c) Tiburon Entertainment / Electronic Arts 2003. ALL RIGHTS RESERVED.
Version
1.0 ??/\98 (GWS) First Version
Macro Definition Documentation
#define STACK_ELEM 512
Referenced by LobbyMSort().
#define STACK_SWAP 1024
Referenced by LobbyMSort().
Function Documentation
void LobbyMSort (void * refptr, void * base, int32_t nmemb, int32_t size, int32_t(*)(void *refptr, const void *, const void *) compare)
Perform mergesort on fixed width array.
Parameters
*refptr - ref value to pass to compare
*base - array base
nmemb - array members
size - array width
*compare - compare function
Returns
None.
Note
Preserves ordering between identical keys. May allow up to (12*nmemb)+size bytes
Version
1.0 ??/\98 (GWS) First Version
References DirtyMemAlloc(), DirtyMemFree(), DirtyMemGroupQuery(), ds_memcpy(), QosApiRefT::iMemGroup, QosApiRefT::pMemGroupUserData, SORT_MEMID, STACK_ELEM, and STACK_SWAP.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:14