DirtySock: VoipCodec
VoipCodec
Voip
Data Structures
struct VoipCodecDefT
codec function block
struct VoipCodecRefT
codec state structure
Macros
#define VOIP_CODEC_OUTPUT_FRACTIONAL (12)
used by some of the fractional integer codes
#define VOIP_CODEC_ACTIVE (-1)
operate on active codec (passed for ident, valid for VoipDestroy, VoipControl)
Typedefs
typedef struct VoipCodecRefT VoipCodecRefT
opaque module ref
typedef VoipCodecRefT *(VoipCodecCreateT)(int32_t iNumDecoders)
create function type
typedef void(VoipCodecDestroyT)(VoipCodecRefT *pState)
destroy function type
typedef int32_t(VoipCodecEncodeT)(VoipCodecRefT *pState, uint8_t *pOutput, const int16_t *pInput, int32_t iNumSamples)
encode function type
typedef int32_t(VoipCodecDecodeT)(VoipCodecRefT *pState, int32_t *pOutput, const uint8_t *pInput, int32_t iInputBytes, int32_t iChannel)
decode function type
typedef void(VoipCodecResetT)(VoipCodecRefT *pState)
reset function type
typedef int32_t(VoipCodecControlT)(VoipCodecRefT *pState, int32_t iSelect, int32_t iValue, int32_t iValue2, void *pValue)
control function type
typedef int32_t(VoipCodecStatusT)(VoipCodecRefT *pState, int32_t iSelect, int32_t iValue, void *pBuffer, int32_t iBufSize)
status function type
typedef struct VoipCodecDefT VoipCodecDefT
codec function block
Functions
DIRTYCODE_API void VoipCodecRegister (int32_t iCodecIdent, const VoipCodecDefT *pCodecDef)
Register a codec in the table.
DIRTYCODE_API int32_t VoipCodecCreate (int32_t iCodecIdent, int32_t iDecodeChannels)
Create a codec module of the given type.
DIRTYCODE_API int32_t VoipCodecControl (int32_t iCodecIdent, int32_t iControl, int32_t iValue, int32_t iValue2, void *pValue)
Control codec.
DIRTYCODE_API int32_t VoipCodecStatus (int32_t iCodecIdent, int32_t iSelect, int32_t iValue, void *pBuffer, int32_t iBufSize)
Get codec status.
DIRTYCODE_API void VoipCodecDestroy (void)
Destroy the active codec.
DIRTYCODE_API void VoipCodecReset (void)
Resets codec state of active codec.
DIRTYCODE_API int32_t VoipCodecEncode (uint8_t *pOutput, const int16_t *pInput, int32_t iNumSamples)
Encode input data with the active codec.
DIRTYCODE_API int32_t VoipCodecDecode (int32_t *pOutput, const uint8_t *pInput, int32_t iInputBytes, int32_t iChannel)
Decode input data with the active codec.
Detailed Description
Macro Definition Documentation
#define VOIP_CODEC_ACTIVE (-1)
operate on active codec (passed for ident, valid for VoipDestroy, VoipControl)
Referenced by VoipCodecDecode(), VoipCodecDestroy(), VoipCodecEncode(), VoipCodecReset(), VoipControl(), and VoipHeadsetControl().
#define VOIP_CODEC_OUTPUT_FRACTIONAL (12)
used by some of the fractional integer codes
Referenced by VoipControl().
Typedef Documentation
typedef int32_t(VoipCodecControlT)(VoipCodecRefT *pState, int32_t iSelect, int32_t iValue, int32_t iValue2, void *pValue)
control function type
typedef VoipCodecRefT*(VoipCodecCreateT)(int32_t iNumDecoders)
create function type
typedef int32_t(VoipCodecDecodeT)(VoipCodecRefT *pState, int32_t *pOutput, const uint8_t *pInput, int32_t iInputBytes, int32_t iChannel)
decode function type
typedef struct VoipCodecDefT VoipCodecDefT
codec function block
typedef void(VoipCodecDestroyT)(VoipCodecRefT *pState)
destroy function type
typedef int32_t(VoipCodecEncodeT)(VoipCodecRefT *pState, uint8_t *pOutput, const int16_t *pInput, int32_t iNumSamples)
encode function type
typedef struct VoipCodecRefT VoipCodecRefT
opaque module ref
typedef void(VoipCodecResetT)(VoipCodecRefT *pState)
reset function type
typedef int32_t(VoipCodecStatusT)(VoipCodecRefT *pState, int32_t iSelect, int32_t iValue, void *pBuffer, int32_t iBufSize)
status function type
Function Documentation
DIRTYCODE_API int32_t VoipCodecControl (int32_t iCodecIdent, int32_t iControl, int32_t iValue, int32_t iValue2, void * pValue)
Control codec.
Parameters
iCodecIdent - codec identifier, or VOIP_CODEC_ACTIVE
iControl - control selector
iValue - selector specific
iValue2 - selector specific
*pValue - selector specific
Returns
int32_t - selector specific
Note
iControl can be one of the following:
        '+vad' - enable/disable vad
        'vada' - signal level threshold used to detect silence in a single frame (in millionths)
        'vadf' - number of silence frames required for silence detection to kick in
Version
08/09/2004 (jbrookes)
References VoipCodecRefT::bVadEnabled, FALSE, VoipCodecRefT::fVadPowerThreshold, VoipCodecRefT::iVadSilenceFramesThreshold, NetPrintf, VoipCodecRegT::pCodecDef, VoipCodecRegT::pCodecRef, VoipCodecDefT::pControl, and TRUE.
Referenced by VoipControl(), and VoipHeadsetControl().
DIRTYCODE_API int32_t VoipCodecCreate (int32_t iCodecIdent, int32_t iDecodeChannels)
Create a codec module of the given type.
Parameters
iCodecIdent - identifier with which the codec will be tagged
iDecodeChannels - number of decoder channels
Returns
int32_t - zero=success, negative=failure
Version
08/04/2004 (jbrookes)
References VoipCodecRefT::fVadPowerThreshold, VoipCodecRefT::iVadSilenceFramesThreshold, NetPrintf, VoipCodecRegT::pCodecDef, VoipCodecRegT::pCodecRef, VoipCodecDefT::pCreate, VOIPCODEC_DEFAULT_VAD_AMPLITUDE_THRESHOLD, VOIPCODEC_DEFAULT_VAD_FRAMES_THRESHOLD, and VoipCodecDestroy().
DIRTYCODE_API int32_t VoipCodecDecode (int32_t * pOutput, const uint8_t * pInput, int32_t iInputBytes, int32_t iChannel)
Decode input data with the active codec.
Parameters
*pOutput - pointer to output buffer
*pInput - pointer to input compressed data
iInputBytes - size in bytes of input data
iChannel - the input channel whose data we are decoding
Returns
int32_t - number of output samples
Version
08/04/2004 (jbrookes)
References NetPrintf, VoipCodecRegT::pCodecDef, VoipCodecRegT::pCodecRef, VoipCodecDefT::pDecode, VOIP_CODEC_ACTIVE, VoipTimer(), and VoipTimerDiff().
Referenced by VoipMixerAccumulate().
DIRTYCODE_API void VoipCodecDestroy (void)
Destroy the active codec.
Version
08/04/2004 (jbrookes)
References VoipCodecRefT::pCodecDef, VoipCodecRegT::pCodecRef, VoipCodecDefT::pDestroy, and VOIP_CODEC_ACTIVE.
Referenced by VoipCodecCreate(), and VoipHeadsetDestroy().
DIRTYCODE_API int32_t VoipCodecEncode (uint8_t * pOutput, const int16_t * pInput, int32_t iNumSamples)
Encode input data with the active codec.
Parameters
*pOutput - pointer to output buffer
*pInput - pointer to input sample data
iNumSamples - number of input samples
Returns
int32_t - size of output data
Version
08/04/2004 (jbrookes)
References VoipCodecRefT::bVadEnabled, NetPrintf, VoipCodecRegT::pCodecDef, VoipCodecRegT::pCodecRef, VoipCodecDefT::pEncode, VOIP_CODEC_ACTIVE, VoipTimer(), and VoipTimerDiff().
DIRTYCODE_API void VoipCodecRegister (int32_t iCodecIdent, const VoipCodecDefT * pCodecDef)
Register a codec in the table.
Parameters
iCodecIdent - identifier with which the codec will be tagged
*pCodecDef - pointer to codec definition table
Version
08/04/2004 (jbrookes)
References VoipCodecRegT::iCodecIdent, NetPrintf, VoipCodecRegT::pCodecDef, and VOIPCODEC_MAXENTRIES.
Referenced by VoipControl(), and VoipHeadsetCreate().
DIRTYCODE_API void VoipCodecReset (void)
Resets codec state of active codec.
Version
08/04/2004 (jbrookes)
References VoipCodecRegT::pCodecDef, VoipCodecRegT::pCodecRef, VoipCodecDefT::pReset, and VOIP_CODEC_ACTIVE.
DIRTYCODE_API int32_t VoipCodecStatus (int32_t iCodecIdent, int32_t iSelect, int32_t iValue, void * pBuffer, int32_t iBufSize)
Get codec status.
Parameters
iCodecIdent - codec identifier, or VOIP_CODEC_ACTIVE
iSelect - status selector
iValue - selector-specific
*pBuffer - [out] selector-specific buffer space
iBufSize - size of output buffer
Version
08/09/2004 (jbrookes)
References NetPrintf, VoipCodecRegT::pCodecDef, VoipCodecRegT::pCodecRef, and VoipCodecDefT::pStatus.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:50