DirtySock: DirtyNames
DirtyNames
DirtySock
Functions
DIRTYCODE_API int32_t DirtyUsernameCompare (const char *pName1, const char *pName2)
Compare two master account names. Ignore case and non-printable ascii characters.
DIRTYCODE_API int32_t DirtyUsernameSubstr (const char *pSrc, const char *pMatch)
Determine if pMatch is a substring of pSrc. Ignore case and non-printable ascii characters.
DIRTYCODE_API int32_t DirtyUsernameCreateCanonical (const char *pName, char *pCanonical, size_t uLen)
DIRTYCODE_API uint32_t DirtyUsernameHash (const char *pName)
Generate the hash code for the given persona name. This hashing function will hash the canonical form of the name rather than the raw bytes to ensure that equivalent names always hash to the same value, as per the xlat table.
DIRTYCODE_API int32_t DirtyNameCreateCanonical (const char *pName, char *pCanonical, size_t uLen)
Create the canonical form of the given name. This essentially lowercases the name and strips non-printable ascii characters as per the xlat table.
int32_t toXlatIndex (const char str)
Converts a char to xlat table index using its ascii char representation. Characters outside the range [0, 255] are treated as 255.
Detailed Description
Function Documentation
DIRTYCODE_API int32_t DirtyNameCreateCanonical (const char * pName, char * pCanonical, size_t uLen)
Create the canonical form of the given name. This essentially lowercases the name and strips non-printable ascii characters as per the xlat table.
Parameters
pName - The input name to create the canonical name from.
pCanonical - The buffer to output the canonical name into
uLen - The length of pCanonical
Returns
int32_t - 0 on success; -1 if the output buffer is too small
References toXlatIndex().
DIRTYCODE_API int32_t DirtyUsernameCompare (const char * pName1, const char * pName2)
Compare two master account names. Ignore case and non-printable ascii characters.
Parameters
pName1 - Input account name 1
pName2 - Input account name 2
Returns
int32_t - < 0 = pName1 < pName2 = 0 = pName1 = pName2 > 0 = pName1 > pName2
Version
1.0 05/01/2003 (DBO) Taken from LobbyHasher (HashStrCmp)
References toXlatIndex().
Referenced by HasherCreate(), and NetConnQuery().
DIRTYCODE_API int32_t DirtyUsernameCreateCanonical (const char * pName, char * pCanonical, size_t uLen)
DIRTYCODE_API uint32_t DirtyUsernameHash (const char * pName)
Generate the hash code for the given persona name. This hashing function will hash the canonical form of the name rather than the raw bytes to ensure that equivalent names always hash to the same value, as per the xlat table.
Parameters
pName - The input name to generate a hash code.
Returns
uint32_t - The generated hash code.
References toXlatIndex().
DIRTYCODE_API int32_t DirtyUsernameSubstr (const char * pSrc, const char * pMatch)
Determine if pMatch is a substring of pSrc. Ignore case and non-printable ascii characters.
Parameters
pSrc - Location to store converted name
pMatch - Input account name
Returns
int32_t - TRUE if pMatch is a substring of pSrc; FALSE otherwise
Version
1.0 05/02/2003 (DBO) Initial version.
References FALSE, NULL, toXlatIndex(), and TRUE.
int32_t toXlatIndex (const char str)
Converts a char to xlat table index using its ascii char representation. Characters outside the range [0, 255] are treated as 255.
Parameters
str - Input char
Returns
xlat index - int32_t (0 to 255)
Referenced by DirtyNameCreateCanonical(), DirtyUsernameCompare(), DirtyUsernameHash(), and DirtyUsernameSubstr().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:56