DirtySock: voipmixer.c File Reference
voipmixer.c File Reference
VoIP audio mixer.
#include <string.h>
#include "DirtySDK/platform.h"
#include "DirtySDK/dirtysock/dirtylib.h"
#include "DirtySDK/dirtysock/dirtymem.h"
#include "DirtySDK/voip/voipdef.h"
#include "voippriv.h"
#include "voipmixer.h"
Data Structures
struct VoipMixBufferT
struct VoipMixerRefT
VOIP module state data.
Macros
#define VOIP_MAXMIXBUFFERS (16)
max number of supported mixbuffers
#define VOIP_PowerOf2(_val) (((_val) & -(_val)) == (_val))
TRUE if value is a power of two, else FALSE.
#define VOIP_NextMixBuffer(_pRef, _iCur) (((_iCur) + 1) % ((_pRef)->iNumMixBuffers))
index the next mixbuffer
#define VOIP_Abs32(_val) (((_val) ^ ((_val) >> 31)) - ((_val) >> 31))
absolute value of an 32bit integer
Typedefs
typedef struct VoipMixBufferT VoipMixBufferT
Functions
VoipMixerRefT * VoipMixerCreate (uint32_t uMixBuffers, uint32_t uFrameSamples)
Create the mixer module.
void VoipMixerDestroy (VoipMixerRefT *pMixerRef)
Destroy the mixer module.
int32_t VoipMixerAccumulate (VoipMixerRefT *pMixerRef, uint8_t *pInputData, int32_t iDataSize, int32_t iMixBufferUnused, int32_t iMixMask, int32_t iChannel)
Decodes and accumulates incoming data into mixbuffer.
int32_t VoipMixerProcess (VoipMixerRefT *pMixerRef, uint8_t *pFrameData)
Mixes queued data into one output buffer suitable for playback.
Detailed Description
VoIP audio mixer.
Attention
Copyright (c) Electronic Arts 2004. ALL RIGHTS RESERVED.
Version
1.0 07/29/2004 (jbrookes) Split from voipheadset.c
Macro Definition Documentation
#define VOIP_Abs32 (_val) (((_val) ^ ((_val) >> 31)) - ((_val) >> 31))
absolute value of an 32bit integer
Referenced by VoipMixerProcess().
#define VOIP_MAXMIXBUFFERS (16)
max number of supported mixbuffers
Referenced by VoipMixerCreate().
#define VOIP_NextMixBuffer (_pRef, _iCur) (((_iCur) + 1) % ((_pRef)->iNumMixBuffers))
index the next mixbuffer
Referenced by VoipMixerAccumulate(), and VoipMixerProcess().
#define VOIP_PowerOf2 (_val) (((_val) & -(_val)) == (_val))
TRUE if value is a power of two, else FALSE.
Typedef Documentation
typedef struct VoipMixBufferT VoipMixBufferT
Function Documentation
int32_t VoipMixerAccumulate (VoipMixerRefT * pMixerRef, uint8_t * pInputData, int32_t iDataSize, int32_t iMixBufferUnused, int32_t iMixMask, int32_t iChannel)
Decodes and accumulates incoming data into mixbuffer.
Parameters
*pMixerRef - pointer to mixer module
*pInputData - pointer to input voice data
iDataSize - size of incoming voice data
iMixBufferUnused - Unused. Deprecated. TODO: remove in V9.
iMixMask - bitmask uniquely representing who is doing the writing
iChannel - input channel number
Returns
int32_t - negative=error, else next mixbuffer to write into
Version
07/29/2004 (jbrookes)
References VoipMixerRefT::iCurMixBuffer, VoipMixerRefT::iMixBufferSize, VoipMixBufferT::iMixCount, VoipMixBufferT::iMixMask, VoipMixerRefT::iNumMixBuffers, VoipMixerRefT::MixBuffers, NetPrintf, VoipMixBufferT::pMixBuffer, VOIP_NextMixBuffer, and VoipCodecDecode().
VoipMixerRefT* VoipMixerCreate (uint32_t uMixBuffers, uint32_t uFrameSamples)
Create the mixer module.
Parameters
uMixBuffers - number of mixbuffers to implement
uFrameSamples - size of a frame in samples
Returns
VoipMixerRefT * - pointer to mixer module, or NULL if an error occurred
Version
07/29/2004 (jbrookes)
References DirtyMemAlloc(), DirtyMemFree(), VoipMixerRefT::iMixBufferSize, VoipMixerRefT::iNumMixBuffers, VoipMixerRefT::MixBuffers, NetPrintf, NULL, VoipMixBufferT::pMixBuffer, VOIP_MAXMIXBUFFERS, VOIP_MEMID, and VoipMemGroupQuery().
void VoipMixerDestroy (VoipMixerRefT * pMixerRef)
Destroy the mixer module.
Parameters
*pMixerRef - pointer to mixer module
Returns
None.
Version
07/29/2004 (jbrookes)
References DirtyMemFree(), VoipMixerRefT::MixBuffers, VoipMixBufferT::pMixBuffer, VOIP_MEMID, and VoipMemGroupQuery().
Referenced by VoipHeadsetDestroy().
int32_t VoipMixerProcess (VoipMixerRefT * pMixerRef, uint8_t * pFrameData)
Mixes queued data into one output buffer suitable for playback.
Parameters
*pMixerRef - pointer to mixer
*pFrameData - pointer to output
Returns
int32_t - number of bytes written to output buffer
Version
04/02/2004 (jbrookes)
References VoipMixerRefT::iCurMixBuffer, VoipMixerRefT::iMixBufferSize, VoipMixBufferT::iMixCount, VoipMixBufferT::iMixMask, VoipMixerRefT::MixBuffers, VoipMixBufferT::pMixBuffer, VOIP_Abs32, and VOIP_NextMixBuffer.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:41