#!/bin/bash

if [[ $1 == COMMAND ]]
then
    echo "no COMMAND"
fi

if [[ $1 == INFO ]]
then
    cat servulatorInfo.xml
    echo "completed INFO"
fi

if [[ $1 == CRASH ]]
then
    echo "no CRASH"
fi

if [[ $1 == DRAIN ]]
then
    kill -9 $2
    echo "completed DRAIN"
fi

if [[ $1 == STOP ]]
then
    kill -9 $2
    echo "completed STOP"
fi