DirtySock: Utf8
Utf8
Util
Data Structures
struct Utf8TransTblT
UTF-8 to 8bit translation table.
struct Utf8EncodeTblT
8bit to UTF-8 translation table
Typedefs
typedef struct Utf8TransTblT Utf8TransTblT
UTF-8 to 8bit translation table.
typedef struct Utf8EncodeTblT Utf8EncodeTblT
8bit to UTF-8 translation table
Functions
DIRTYCODE_API int32_t Utf8Strip (char *pOutStr, int32_t iBufSize, const char *pInStr)
Strip non-ASCII UTF-8 encoded data.
DIRTYCODE_API int32_t Utf8Replace (char *pOutStr, int32_t iBufSize, const char *pInStr, char cReplace)
Replace non-ASCII UTF-8 encoded data with the given character.
DIRTYCODE_API int32_t Utf8StrLen (const char *pStr)
Returns the number of code points in a UTF-8 encoded string.
DIRTYCODE_API int32_t Utf8EncodeFromUCS2 (char *pOutStr, int32_t iBufLen, const uint16_t *pInStr)
Convert a UCS-2 code point sequence into a UTF-8 code point sequence.
DIRTYCODE_API int32_t Utf8EncodeFromUCS2CodePt (char *pOutPtr, uint16_t uCodePt)
Encode a single UCS-2 code point ("char") into a UTF-8 sequence.
DIRTYCODE_API int32_t Utf8DecodeToUCS2 (uint16_t *pOutStr, int32_t iBufLen, const char *pInStr)
Convert a UTF-8 code point sequence into a UCS-2 code point sequence.
DIRTYCODE_API int32_t Utf8EncodeFrom8Bit (char *pOutStr, int32_t iBufLen, const char *pInStr, const Utf8EncodeTblT *pEncodeTbl)
Encode the given 8bit input string to UTF-8, based on the input translation table.
DIRTYCODE_API int32_t Utf8TranslateTo8Bit (char *pOutStr, int32_t iBufLen, const char *pInStr, char cReplace, const Utf8TransTblT *pTransTbl)
Translates the given UTF-8 sequence based on the input translation table.
Detailed Description
Typedef Documentation
typedef struct Utf8EncodeTblT Utf8EncodeTblT
8bit to UTF-8 translation table
typedef struct Utf8TransTblT Utf8TransTblT
UTF-8 to 8bit translation table.
Function Documentation
DIRTYCODE_API int32_t Utf8DecodeToUCS2 (uint16_t * pOutStr, int32_t iBufLen, const char * pInStr)
Convert a UTF-8 code point sequence into a UCS-2 code point sequence.
Parameters
*pOutStr - pointer to buffer to decode string to
iBufLen - length of output buffer, in UCS-2 units (int16_t)
*pInStr - pointer to string to decode
Returns
int32_t - output string length, in code points
Version
03/26/03 (JLB)
DIRTYCODE_API int32_t Utf8EncodeFrom8Bit (char * pOutStr, int32_t iBufLen, const char * pInStr, const Utf8EncodeTblT * pEncodeTbl)
Encode the given 8bit input string to UTF-8, based on the input translation table.
Parameters
*pOutStr - pointer to output UTF-8 string buffer
iBufLen - length of buffer
*pInStr - pointer to input 8bit string
*pEncodeTbl - pointer to translation table to map 8bit string to UCS-2
Returns
int32_t - length of output UCS-8 string
Version
03/28/03 (JLB)
References Utf8EncodeTblT::uCodeTbl, and Utf8EncodeFromUCS2CodePt().
DIRTYCODE_API int32_t Utf8EncodeFromUCS2 (char * pOutStr, int32_t iBufLen, const uint16_t * pInStr)
Convert a UCS-2 code point sequence into a UTF-8 code point sequence.
Parameters
*pOutStr - pointer to buffer to encode string to
iBufLen - length of output buffer, in char units
*pInStr - pointer to string to encode
Returns
int32_t - output string length, in char units
Version
03/27/03 (JLB)
References Utf8EncodeFromUCS2CodePt().
DIRTYCODE_API int32_t Utf8EncodeFromUCS2CodePt (char * pOutPtr, uint16_t uCodePt)
Encode a single UCS-2 code point ("char") into a UTF-8 sequence.
Parameters
uCodePt - input UCS-2 code point
*pOutPtr - pointer to output for encoded UTF-8 sequence.
Returns
int32_t - number of 8bit characters output
Note
See notes for _Utf8DecodeToUCS2()
Version
03/26/03 (JLB)
Referenced by Utf8EncodeFrom8Bit(), and Utf8EncodeFromUCS2().
DIRTYCODE_API int32_t Utf8Replace (char * pOutStr, int32_t iBufSize, const char * pInStr, char cReplace)
Replace non-ASCII UTF-8 encoded data with the given character.
Parameters
*pOutStr - pointer to output buffer (may be same as input buffer)
iBufSize - size of output buffer in ASCII units (char)
*pInStr - pointer to source string
cReplace - character to replace non-ASCII UTF-8 characters with
Returns
int32_t - number of characters in new string, or zero if no UTF-8 data was replaced
Version
03/25/03 (JLB)
Referenced by Utf8Strip().
DIRTYCODE_API int32_t Utf8Strip (char * pOutStr, int32_t iBufSize, const char * pInStr)
Strip non-ASCII UTF-8 encoded data.
Parameters
*pOutStr - pointer to output buffer (may be same as input buffer)
iBufSize - size of output buffer in ASCII units (char)
*pInStr - pointer to source string
Returns
int32_t - number of characters in new string, or zero if no utf8 data was stripped
Version
03/25/03 (JLB)
References Utf8Replace().
DIRTYCODE_API int32_t Utf8StrLen (const char * pStr)
Returns the number of code points in a UTF-8 encoded string.
Parameters
*pStr - pointer to string to get string length of
Returns
int32_t - number of code points in string
Version
03/26/03 (JLB)
DIRTYCODE_API int32_t Utf8TranslateTo8Bit (char * pOutStr, int32_t iBufLen, const char * pInStr, char cReplace, const Utf8TransTblT * pTransTbl)
Translates the given UTF-8 sequence based on the input translation table.
Parameters
*pOutStr - pointer to buffer to decode string to
iBufLen - length of output buffer, in ASCII units (char)
*pInStr - pointer to string to decode
cReplace -
character to replace code point with if untranslateable ('\0' to strip)
*pTransTbl - pointer to NULL-terminated translation table array
Returns
int32_t - length of output string in ASCII characters (8bit)
Note
'pTransTbl' is expected to be a NULL-terminated array of Utf8TransTblT structures that represent a sparse translation table from 16bit UCS-2 space to 8bit game font space.
Version
03/26/03 (JLB)
Referenced by HLBBudGetPresence(), and HLBMsgListGetMsgText().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:32