DirtySock: voipmixer.h File Reference
voipmixer.h File Reference
VoIP data packet definitions.
#include "DirtySDK/voip/voipcodec.h"
Typedefs
typedef struct VoipMixerRefT VoipMixerRefT
opaque module state ref
Functions
VoipMixerRefT * VoipMixerCreate (uint32_t uMixBuffers, uint32_t uFrameSamples)
Create the mixer module.
void VoipMixerDestroy (VoipMixerRefT *pMixerRef)
Destroy the mixer module.
int32_t VoipMixerAccumulate (VoipMixerRefT *pMixerRef, unsigned char *pInputData, int32_t iDataSize, int32_t iMixBuffer, int32_t iMixMask, int32_t iChannel)
int32_t VoipMixerProcess (VoipMixerRefT *pMixerRef, unsigned char *pFrameData)
Detailed Description
VoIP data packet definitions.
Attention
Copyright (c) Electronic Arts 2004. ALL RIGHTS RESERVED.
Version
1.0 07/29/2004 (jbrookes) Split from voipheadset
Typedef Documentation
typedef struct VoipMixerRefT VoipMixerRefT
opaque module state ref
Function Documentation
int32_t VoipMixerAccumulate (VoipMixerRefT * pMixerRef, unsigned char * pInputData, int32_t iDataSize, int32_t iMixBuffer, int32_t iMixMask, int32_t iChannel)
Referenced by VoipConduitReceiveVoiceData().
VoipMixerRefT* VoipMixerCreate (uint32_t uMixBuffers, uint32_t uFrameSamples)
Create the mixer module.
Parameters
uMixBuffers - number of mixbuffers to implement
uFrameSamples - size of a frame in samples
Returns
VoipMixerRefT * - pointer to mixer module, or NULL if an error occurred
Version
07/29/2004 (jbrookes)
References DirtyMemAlloc(), DirtyMemFree(), VoipMixerRefT::iMixBufferSize, VoipMixerRefT::iNumMixBuffers, VoipMixerRefT::MixBuffers, NetPrintf, NULL, VoipMixBufferT::pMixBuffer, VOIP_MAXMIXBUFFERS, VOIP_MEMID, and VoipMemGroupQuery().
void VoipMixerDestroy (VoipMixerRefT * pMixerRef)
Destroy the mixer module.
Parameters
*pMixerRef - pointer to mixer module
Returns
None.
Version
07/29/2004 (jbrookes)
References DirtyMemFree(), VoipMixerRefT::MixBuffers, VoipMixBufferT::pMixBuffer, VOIP_MEMID, and VoipMemGroupQuery().
Referenced by VoipHeadsetDestroy().
int32_t VoipMixerProcess (VoipMixerRefT * pMixerRef, unsigned char * pFrameData)
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:41