#!/usr/bin/python

import commands, os, sys, time

username = 'gsstressbot'
startnumber = 1
totalnumber = -1
build = 'final'
numdigits = 5
password = 'aaaa'
noexecute = 0

for option in sys.argv[2:]:
	if option.find('-startnumber=') != -1:
		startnumber = int(option[13:])
	elif option.find('-totalnumber=') != -1:
		totalnumber = int(option[13:])
	elif option.find('-build=') != -1:
		build = option[7:]
	else:
		print 'usage: gsmulti {start|stop} [ -startnumber -totalnumber -build ]'
		sys.exit()

if sys.argv[1] == 'start':
	i = 0
	if totalnumber == -1:
		totalnumber = 8
	while i < totalnumber:
		index = str(startnumber + i)
		index = '0' * (numdigits - len(index)) + index
        	sysstr = './gsrvstress' + build[0] + ' stress.cfg ' + index + ' &> gsrvstress' + index + '.log'
        	print('executing ' + sysstr)
        	if noexecute == 0:
	        	os.system('(' + sysstr + ')&')
			time.sleep(0.2)
		i = i + 1
elif sys.argv[1] == 'stop':
	files = commands.getoutput('ls').split()

	for file in files:
		if totalnumber == 0:
			break
		elif file.find('gsrvstress') != -1 and file.find('.pid') != -1:
			pidfile = open(file, 'r')
			pid = pidfile.readline()
			pidfile.close()
			os.system('kill -TERM ' + pid)
			totalnumber = totalnumber - 1
else:
	print 'usage: gsmulti {startup|shutdown} [ -startnumber -totalnumber -build ]'
	sys.exit()
