DirtySock: dirtyaddrps3.c File Reference
dirtyaddrps3.c File Reference
Opaque address functions.
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include "DirtySDK/dirtysock.h"
#include "DirtySDK/dirtysock/dirtyaddr.h"
#include "DirtySDK/dirtysock/netconn.h"
#include "DirtySDK/util/tagfield.h"
Functions
uint32_t DirtyAddrToHostAddr (void *pOutput, int32_t iBufLen, const DirtyAddrT *pAddr)
A PSN DirtyAddrT contains the internal and external addresses, as well as the NpID (optional). This function can be used to extract the external IP address from the DirtyAddr.
uint32_t DirtyAddrFromHostAddr (DirtyAddrT *pAddr, const void *pInput)
Convert from native format to DirtyAddrT.
uint32_t DirtyAddrGetLocalAddr (DirtyAddrT *pAddr)
Get the local address in DirtyAddr form.
void DirtyAddrGetInfoPS3 (const DirtyAddrT *pDirtyAddr, SceNpId *pId, uint32_t *pIntAddr, uint32_t *pExtAddr)
Extract PS3-specific fields from the given DirtyAddr.
void DirtyAddrSetInfoPS3 (DirtyAddrT *pDirtyAddr, const SceNpId *pId, uint32_t uIntAddr, uint32_t uExtAddr)
Set PS3-specific fields into the given DirtyAddr.
int32_t DirtyAddrCompare (DirtyAddrT *pAddr1, DirtyAddrT *pAddr2)
Compare two DirtyAddrTs (external address component only)
Detailed Description
Opaque address functions.
Attention
Copyright (c) Electronic Arts 2004. ALL RIGHTS RESERVED.
Note
A PS3 DirtyAddrT contains the internal and external addresses, as well as the NpID.
NpID-internal-external-opt-reserved
Version
09/01/2006 (jbrookes) First Version
Function Documentation
int32_t DirtyAddrCompare (DirtyAddrT * pAddr1, DirtyAddrT * pAddr2)
Compare two DirtyAddrTs (external address component only)
Parameters
*pAddr1 - first address
*pAddr2 - second address
Returns
int32_t - one=same, zero=different
Version
09/05/2006 (jbrookes)
References DirtyAddrGetInfoPS3(), and NULL.
Referenced by PingManagerCancelRequest().
void DirtyAddrGetInfoPS3 (const DirtyAddrT * pDirtyAddr, SceNpId * pId, uint32_t * pIntAddr, uint32_t * pExtAddr)
Extract PS3-specific fields from the given DirtyAddr.
Parameters
*pDirtyAddr - dirtyaddr to decode
*pId - [out] storage for decoded NpId
*pIntAddr - [out] storage for decoded internal address
*pExtAddr - [out] storage for decoded external address
Note
Any undesired outputs may be specified as NULL
Version
09/01/2006 (jbrookes)
References NULL, DirtyAddrT::strMachineAddr, and TagFieldGetBinary().
Referenced by DirtyAddrCompare(), DirtyAddrToHostAddr(), and HLBAddPlayersToHistory().
void DirtyAddrSetInfoPS3 (DirtyAddrT * pDirtyAddr, const SceNpId * pId, uint32_t uIntAddr, uint32_t uExtAddr)
Set PS3-specific fields into the given DirtyAddr.
Parameters
*pDirtyAddr - [out] storage for dirtyaddr
*pId - NpId to encode (can be NULL)
uIntAddr - internal address to encode
uExtAddr - external address to encode
Version
09/01/2006 (jbrookes)
References ds_strnzcpy(), FALSE, NULL, DirtyAddrT::strMachineAddr, and TRUE.
Referenced by DirtyAddrFromHostAddr(), and DirtyAddrGetLocalAddr().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:40