DirtySock: JsonFormat
JsonFormat
Util
Macros
#define JSON_ERR_NONE (0)
no error
#define JSON_ERR_FULL (-1)
buffer is full, no space to add attribute or element.
#define JSON_ERR_UNINIT (-2)
did not call JsonInit() prior to writing.
#define JSON_ERR_NOT_OPEN (-3)
attempt to set elem or attrib, but, no tag opened.
#define JSON_ERR_ATTR_POSITION (-4)
attempt to set an attrib, but, child element already added to tag.
#define JSON_ERR_INVALID_PARAM (-5)
invalid parameter passed to function
#define JSON_FL_WHITESPACE (1)
include formatting whitespace
Functions
DIRTYCODE_API void JsonInit (char *pBuffer, int32_t iBufLen, uint8_t uFlags)
DIRTYCODE_API void JsonBufSizeIncrease (char *pBuffer, int32_t iNewBufLen)
Notify the jsonformat API that the buffer size was increased.
DIRTYCODE_API char * JsonFinish (char *pBuffer)
Signal completion of output to this buffer. Clear the JSON API hidden data.
DIRTYCODE_API int32_t JsonObjectStart (char *pBuffer, const char *pName)
Start a JSON object, to which you can add other objects or elements. Must be ended with JsonObjectEnd.
DIRTYCODE_API int32_t JsonObjectEnd (char *pBuffer)
End the current object – must have an outstanding open tag.
DIRTYCODE_API int32_t JsonArrayStart (char *pBuffer, const char *pName)
Start a JSON array, to which you can add other objects or elements. Must be ended with JsonArrayEnd.
DIRTYCODE_API int32_t JsonArrayEnd (char *pBuffer)
End the current array – must have an outstanding open array.
DIRTYCODE_API int32_t JsonAddStr (char *pBuffer, const char *pElemName, const char *pValue)
Adds a string element.
DIRTYCODE_API int32_t JsonAddNum (char *pBuffer, const char *pElemName, const char *pFormatSpec, float fValue)
Add a complete, contained decimal element. Builds start and end tag. Nothing can be appended to this tag. Format it using formatSpec.
DIRTYCODE_API int32_t JsonAddInt (char *pBuffer, const char *pElemName, int64_t iValue)
Add an integer element.
DIRTYCODE_API int32_t JsonAddDate (char *pBuffer, const char *pElemName, uint32_t uEpochDate)
Add a date (will be encoded as a string; use JsonAddInteger for integer encoding)
DIRTYCODE_API char * JsonFormatPrintf (char *pJsonBuff, int32_t iBufLen, const char *pFormat,...)
Takes a format string and variable parameter list and formats into syntax correct JSON.
Detailed Description
Macro Definition Documentation
#define JSON_ERR_ATTR_POSITION (-4)
attempt to set an attrib, but, child element already added to tag.
#define JSON_ERR_FULL (-1)
buffer is full, no space to add attribute or element.
Referenced by JsonArrayEnd(), JsonArrayStart(), JsonObjectEnd(), and JsonObjectStart().
#define JSON_ERR_INVALID_PARAM (-5)
invalid parameter passed to function
Referenced by JsonAddDate(), and JsonAddNum().
#define JSON_ERR_NONE (0)
no error
#define JSON_ERR_NOT_OPEN (-3)
attempt to set elem or attrib, but, no tag opened.
#define JSON_ERR_UNINIT (-2)
did not call JsonInit() prior to writing.
Referenced by JsonArrayEnd(), JsonArrayStart(), JsonObjectEnd(), and JsonObjectStart().
#define JSON_FL_WHITESPACE (1)
include formatting whitespace
Referenced by JsonFormatVPrintf().
Function Documentation
DIRTYCODE_API int32_t JsonAddDate (char * pBuffer, const char * pElemName, uint32_t uEpochDate)
Add a date (will be encoded as a string; use JsonAddInteger for integer encoding)
Parameters
*pBuffer - JSON buffer
*pElemName - name of the element
uEpochDate - date/time since epoch
Returns
int32_t - JSON_ERR_*
Version
12/11/2012 (jbrookes)
References ds_secstotime(), ds_snzprintf(), FALSE, JSON_ERR_INVALID_PARAM, JSON_MAX_DATE_LENGTH, and NULL.
DIRTYCODE_API int32_t JsonAddInt (char * pBuffer, const char * pElemName, int64_t iValue)
Add an integer element.
Parameters
*pBuffer - JSON buffer
*pElemName - name of the element
iValue - integer value of the element
Returns
int32_t - JSON_ERR_*
Version
12/11/2012 (jbrookes)
References ds_snzprintf(), and FALSE.
DIRTYCODE_API int32_t JsonAddNum (char * pBuffer, const char * pElemName, const char * pFormatSpec, float fValue)
Add a complete, contained decimal element. Builds start and end tag. Nothing can be appended to this tag. Format it using formatSpec.
Parameters
*pBuffer - JSON buffer
*pElemName - name of the element
*pFormatSpec - format spec for formatting the float (see printf)
fValue - float value of the element
Returns
int32_t - JSON_ERR_*
Version
12/11/2012 (jbrookes)
References ds_snzprintf(), FALSE, JSON_ERR_INVALID_PARAM, and JSON_MAX_FLOAT_LENGTH.
DIRTYCODE_API int32_t JsonAddStr (char * pBuffer, const char * pElemName, const char * pValue)
Adds a string element.
Parameters
*pBuffer - JSON buffer
*pElemName - name of the element (may be null)
*pValue - value of the element
Returns
int32_t - JSON_ERR_*
Version
12/11/2012 (jbrookes)
References TRUE.
DIRTYCODE_API int32_t JsonArrayEnd (char * pBuffer)
End the current array – must have an outstanding open array.
Parameters
*pBuffer - JSON buffer
Returns
int32_t - JSON_ERR_*
Version
12/11/2012 (jbrookes)
References ds_snzprintf(), JSON_ERR_FULL, and JSON_ERR_UNINIT.
DIRTYCODE_API int32_t JsonArrayStart (char * pBuffer, const char * pName)
Start a JSON array, to which you can add other objects or elements. Must be ended with JsonArrayEnd.
Parameters
*pBuffer - JSON buffer
*pName - name of the array (may be null)
Returns
int32_t - JSON_ERR_*
Version
12/11/2012 (jbrookes)
References ds_snzprintf(), JSON_ERR_FULL, JSON_ERR_UNINIT, and NULL.
DIRTYCODE_API void JsonBufSizeIncrease (char * pBuffer, int32_t iNewBufLen)
Notify the jsonformat API that the buffer size was increased.
Parameters
*pBuffer - buffer to which JSON is being written.
iNewBufLen – new size for that buffer
Version
12/11/2012 (jbrookes)
DIRTYCODE_API char* JsonFinish (char * pBuffer)
Signal completion of output to this buffer. Clear the JSON API hidden data.
Parameters
*pBuffer – buffer to which JSON was written.
Returns
char* - pointer to real JSON data (skipping past header)
Version
12/11/2012 (jbrookes)
References ds_snzprintf(), and JSON_HEADER_LEN.
Referenced by JsonFormatVPrintf().
DIRTYCODE_API char* JsonFormatPrintf (char * pJsonBuff, int32_t iBufLen, const char * pFormat, ...)
Takes a format string and variable parameter list and formats into syntax correct JSON.
Parameters
*pJsonBuff - JSON output buffer
iBufLen - length of Json output buffer (negative=append to existing buffer)
*pFormat - printf style format string
Returns
char * - pointer to formatted buffer
Version
12/11/2012 (jbrookes)
References JsonFormatVPrintf().
DIRTYCODE_API void JsonInit (char * pBuffer, int32_t iBufLen, uint8_t uFlags)
DIRTYCODE_API int32_t JsonObjectEnd (char * pBuffer)
End the current object – must have an outstanding open tag.
Parameters
*pBuffer - JSON buffer.
Returns
int32_t - JSON_ERR_*
Version
12/11/2012 (jbrookes)
References ds_snzprintf(), JSON_ERR_FULL, and JSON_ERR_UNINIT.
DIRTYCODE_API int32_t JsonObjectStart (char * pBuffer, const char * pName)
Start a JSON object, to which you can add other objects or elements. Must be ended with JsonObjectEnd.
Parameters
*pBuffer - JSON buffer
*pName - name of the object (may be null)
Returns
int32_t - JSON_ERR_*
Version
12/11/2012 (jbrookes)
References ds_snzprintf(), JSON_ERR_FULL, JSON_ERR_UNINIT, and NULL.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:56