DirtySock: voipserializationxboxone.cpp File Reference
voipserializationxboxone.cpp File Reference
Xbox user and device serialization/deserialization code.
#include "DirtySDK/platform.h"
#include <collection.h>
#include "DirtySDK/dirtysock.h"
#include "DirtySDK/dirtysock/netconn.h"
#include "voipserializationxboxone.h"
Functions
void VoipSerializeAudioDevice (IAudioDeviceInfo^refAudioDeviceInfo, VoipSerializedDeviceT *pSerializedDevice)
Populate specified buffer with a serialized blob (ready for transmission over the network) of the local audio device.
void VoipDeserializeAudioDevice (VoipSerializedDeviceT *pSerializedDevice, uint32_t uConsoleId, AudioDevInfo^refRemoteAudioDeviceInfo, uint8_t *pDeviceId)
Initialized the RemoteAudioDevice object from the serialized remote audio device data blob.
int32_t VoipSerializeUser (IUser^refLocalUser, VoipUserExT *pRemoteUser)
Populate a VoipUserT with a serialized blob (ready for transmission over the network)
void VoipDeserializeUser (uint8 *pRemoteUser, RemoteUser^refRemoteUser)
Initialized the RemoteUser object from the serialized remote user data blob.
uint32_t VoipUpdateSerializedUser (VoipUserExT *pRemoteUser, VoipSerializedDeviceT *pSerializedDevice)
Update the remote user blob with a new capture source if necessary.
void VoipDumpUser (IUser^refUser)
Display user data.
void VoipSerializeInit ()
void VoipSerializeTerm ()
Variables
Platform::Collections::Map
< String^, int > g_refDeviceIdMap = nullptr
Detailed Description
Xbox user and device serialization/deserialization code.
Attention
Copyright (c) Electronic Arts 2014. ALL RIGHTS RESERVED.
Version
03/04/2014 (mclouatre) First Version
Function Documentation
void VoipDeserializeAudioDevice (VoipSerializedDeviceT * pSerializedDevice, uint32_t uConsoleId, AudioDevInfo^ refRemoteAudioDeviceInfo, uint8_t * pDeviceId)
Initialized the RemoteAudioDevice object from the serialized remote audio device data blob.
Parameters
*pSerializedDevice - remote audio device pointer
uConsoleId - id of the console to which the device belongs
^refRemoteAudioDeviceInfo - [in, out] remote audio device winrt ref
*pDeviceId - [out] to be filled with numerical device id associate with device
Version
07/12/2013 (mclouatre)
Referenced by VoipDeserializeUser(), VoipHeadsetCreate(), and VoipHeadsetReceiveVoiceDataCb().
void VoipDeserializeUser (uint8 * pRemoteUser, RemoteUser^ refRemoteUser)
Initialized the RemoteUser object from the serialized remote user data blob.
Parameters
*pRemoteUser - remote user pointer
^refRemoteUser - [in, out] remote user winrt ref
Version
07/12/2013 (mclouatre)
References VoipDeserializeAudioDevice().
Referenced by VoipHeadsetRegisterUserCb().
void VoipDumpUser (IUser^ refUser)
Display user data.
Parameters
^refUser - user winrt ref
Version
07/12/2013 (mclouatre)
References NetPrintf.
void VoipSerializeAudioDevice (IAudioDeviceInfo^ refAudioDeviceInfo, VoipSerializedDeviceT * pSerializedDevice)
Populate specified buffer with a serialized blob (ready for transmission over the network) of the local audio device.
Parameters
^refAudioDeviceInfo - local device winrt ref
*pSerializedDevice - [out] pointer to serialized device buffer
Version
07/12/2013 (mclouatre)
Referenced by VoipHeadsetCreate(), and VoipSerializeUser().
void VoipSerializeInit ()
References g_refDeviceIdMap.
Referenced by VoipStartup().
void VoipSerializeTerm ()
References g_refDeviceIdMap.
Referenced by VoipShutdown().
int32_t VoipSerializeUser (IUser^ refLocalUser, VoipUserExT * pRemoteUser)
Populate a VoipUserT with a serialized blob (ready for transmission over the network)
Parameters
^refLocalUser - local user winrt ref
*pRemoteUser - [out] remote user pointer
Returns
int32_t - size of serialized data
Version
07/12/2013 (mclouatre)
References NetConnMachineId(), NetPrintf, and VoipSerializeAudioDevice().
Referenced by VoipActivateLocalUser().
uint32_t VoipUpdateSerializedUser (VoipUserExT * pRemoteUser, VoipSerializedDeviceT * pSerializedDevice)
Update the remote user blob with a new capture source if necessary.
Parameters
*pRemoteUser - remote user pointer
*pSerializedDevice - originating capture source (serialized blob)
Returns
uint32_t - TRUE if remote user's collection of devices changed, FALSE otherwise
Version
07/12/2013 (mclouatre)
References FALSE, NetPrintf, and TRUE.
Variable Documentation
Platform::Collections::Map<String ^, int> g_refDeviceIdMap = nullptr
Referenced by VoipSerializeInit(), and VoipSerializeTerm().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:20