DirtySock: dirtyeventmanagerps4.cpp File Reference
dirtyeventmanagerps4.cpp File Reference
DirtyEventManagerps4 wraps the EASystemEventMessageDispatcher functionality for delegating callbacks from Sony's UserService.
#include "EASystemEventMessageDispatcher/SystemEventMessageDispatcher.h"
#include "DirtySDK/dirtysock/ps4/dirtyeventmanagerps4.h"
#include "DirtySDK/dirtysock/dirtylib.h"
#include "coreallocator/icoreallocator_interface.h"
#include <new>
Data Structures
struct DirtyEventHandler
Macros
#define DIRTYEVENTMANAGER_MAX_DELEGATES 100
Functions
int32_t _DirtyEventManagerInit (bool bCheckTick)
int32_t _DirtyEventManagerShutdown (void)
int32_t _DirtyEventManagerRegisterUserService (DirtyEventManagerUserServiceCallbackT *pCallback, void *pUserData)
int32_t _DirtyEventManagerRegisterSystemService (DirtyEventManagerSystemServiceCallbackT *pCallback, void *pUserData)
int32_t _DirtyEventManagerRegisterCompanionHttpd (DirtyEventManagerCompanionHttpdCallbackT *pCallback, void *pUserData)
int32_t _DirtyEventManagerRegisterCompanionUtil (DirtyEventManagerCompanionUtilCallbackT *pCallback, void *pUserData)
int32_t _DirtyEventManagerUnregisterUserService (DirtyEventManagerUserServiceCallbackT *pCallback)
int32_t _DirtyEventManagerUnregisterSystemService (DirtyEventManagerSystemServiceCallbackT *pCallback)
int32_t _DirtyEventManagerUnregisterCompanionHttpd (DirtyEventManagerCompanionHttpdCallbackT *pCallback)
int32_t _DirtyEventManagerUnregisterCompanionUtil (DirtyEventManagerCompanionUtilCallbackT *pCallback)
int32_t DirtyEventManagerInit (uint8_t bCheckTick)
int32_t DirtyEventManagerShutdown (void)
int32_t DirtyEventManagerRegisterUserService (DirtyEventManagerUserServiceCallbackT *pCallback, void *pUserData)
int32_t DirtyEventManagerRegisterSystemService (DirtyEventManagerSystemServiceCallbackT *pCallback, void *pUserData)
int32_t DirtyEventManagerRegisterCompanionHttpd (DirtyEventManagerCompanionHttpdCallbackT *pCallback, void *pUserData)
int32_t DirtyEventManagerRegisterCompanionUtil (DirtyEventManagerCompanionUtilCallbackT *pCallback, void *pUserData)
int32_t DirtyEventManagerUnregisterUserService (DirtyEventManagerUserServiceCallbackT *pCallback)
int32_t DirtyEventManagerUnregisterSystemService (DirtyEventManagerSystemServiceCallbackT *pCallback)
int32_t DirtyEventManagerUnregisterCompanionHttpd (DirtyEventManagerCompanionHttpdCallbackT *pCallback)
int32_t DirtyEventManagerUnregisterCompanionUtil (DirtyEventManagerCompanionUtilCallbackT *pCallback)
Detailed Description
DirtyEventManagerps4 wraps the EASystemEventMessageDispatcher functionality for delegating callbacks from Sony's UserService.
Attention
Copyright (c) / Electronic Arts 2013. ALL RIGHTS RESERVED.
Version
1.0 07/11/2013 (amakoukji) First Version
Macro Definition Documentation
#define DIRTYEVENTMANAGER_MAX_DELEGATES 100
Referenced by _DirtyEventManagerInit(), _DirtyEventManagerRegisterCompanionHttpd(), _DirtyEventManagerRegisterCompanionUtil(), _DirtyEventManagerRegisterSystemService(), _DirtyEventManagerRegisterUserService(), _DirtyEventManagerShutdown(), _DirtyEventManagerUnregisterCompanionHttpd(), _DirtyEventManagerUnregisterCompanionUtil(), _DirtyEventManagerUnregisterSystemService(), _DirtyEventManagerUnregisterUserService(), and DirtyEventHandler::HandleMessage().
Function Documentation
int32_t _DirtyEventManagerInit (bool bCheckTick)
References DIRTYEVENTMANAGER_MAX_DELEGATES, and NetPrintf.
Referenced by DirtyEventManagerInit().
int32_t _DirtyEventManagerRegisterCompanionHttpd (DirtyEventManagerCompanionHttpdCallbackT * pCallback, void * pUserData)
References DIRTYEVENTMANAGER_MAX_DELEGATES, and NetPrintf.
Referenced by DirtyEventManagerRegisterCompanionHttpd().
int32_t _DirtyEventManagerRegisterCompanionUtil (DirtyEventManagerCompanionUtilCallbackT * pCallback, void * pUserData)
References DIRTYEVENTMANAGER_MAX_DELEGATES, and NetPrintf.
Referenced by DirtyEventManagerRegisterCompanionUtil().
int32_t _DirtyEventManagerRegisterSystemService (DirtyEventManagerSystemServiceCallbackT * pCallback, void * pUserData)
References DIRTYEVENTMANAGER_MAX_DELEGATES, and NetPrintf.
Referenced by DirtyEventManagerRegisterSystemService().
int32_t _DirtyEventManagerRegisterUserService (DirtyEventManagerUserServiceCallbackT * pCallback, void * pUserData)
References DIRTYEVENTMANAGER_MAX_DELEGATES, and NetPrintf.
Referenced by DirtyEventManagerRegisterUserService().
int32_t _DirtyEventManagerShutdown (void)
References DIRTYEVENTMANAGER_MAX_DELEGATES, and NetPrintf.
Referenced by DirtyEventManagerShutdown().
int32_t _DirtyEventManagerUnregisterCompanionHttpd (DirtyEventManagerCompanionHttpdCallbackT * pCallback)
References DIRTYEVENTMANAGER_MAX_DELEGATES, and NetPrintf.
Referenced by DirtyEventManagerUnregisterCompanionHttpd().
int32_t _DirtyEventManagerUnregisterCompanionUtil (DirtyEventManagerCompanionUtilCallbackT * pCallback)
References DIRTYEVENTMANAGER_MAX_DELEGATES, and NetPrintf.
Referenced by DirtyEventManagerUnregisterCompanionUtil().
int32_t _DirtyEventManagerUnregisterSystemService (DirtyEventManagerSystemServiceCallbackT * pCallback)
References DIRTYEVENTMANAGER_MAX_DELEGATES, and NetPrintf.
Referenced by DirtyEventManagerUnregisterSystemService().
int32_t _DirtyEventManagerUnregisterUserService (DirtyEventManagerUserServiceCallbackT * pCallback)
References DIRTYEVENTMANAGER_MAX_DELEGATES, and NetPrintf.
Referenced by DirtyEventManagerUnregisterUserService().
int32_t DirtyEventManagerInit (uint8_t bCheckTick)
References _DirtyEventManagerInit().
Referenced by NetConnStartup().
int32_t DirtyEventManagerRegisterCompanionHttpd (DirtyEventManagerCompanionHttpdCallbackT * pCallback, void * pUserData)
References _DirtyEventManagerRegisterCompanionHttpd().
int32_t DirtyEventManagerRegisterCompanionUtil (DirtyEventManagerCompanionUtilCallbackT * pCallback, void * pUserData)
References _DirtyEventManagerRegisterCompanionUtil().
int32_t DirtyEventManagerRegisterSystemService (DirtyEventManagerSystemServiceCallbackT * pCallback, void * pUserData)
References _DirtyEventManagerRegisterSystemService().
Referenced by DirtySessionManagerCreate(), and NetConnStartup().
int32_t DirtyEventManagerRegisterUserService (DirtyEventManagerUserServiceCallbackT * pCallback, void * pUserData)
References _DirtyEventManagerRegisterUserService().
int32_t DirtyEventManagerShutdown (void)
References _DirtyEventManagerShutdown().
Referenced by NetConnShutdown(), and NetConnStartup().
int32_t DirtyEventManagerUnregisterCompanionHttpd (DirtyEventManagerCompanionHttpdCallbackT * pCallback)
References _DirtyEventManagerUnregisterCompanionHttpd().
int32_t DirtyEventManagerUnregisterCompanionUtil (DirtyEventManagerCompanionUtilCallbackT * pCallback)
References _DirtyEventManagerUnregisterCompanionUtil().
int32_t DirtyEventManagerUnregisterSystemService (DirtyEventManagerSystemServiceCallbackT * pCallback)
References _DirtyEventManagerUnregisterSystemService().
Referenced by NetConnShutdown().
int32_t DirtyEventManagerUnregisterUserService (DirtyEventManagerUserServiceCallbackT * pCallback)
References _DirtyEventManagerUnregisterUserService().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:12