DirtySock: DirtyErr
DirtyErr
DirtySock
Data Structures
struct DirtyErrT
Macros
#define DIRTYSOCK_ERRORNAMES (DIRTYCODE_LOGGING && TRUE)
#define DIRTYSOCK_LISTTERM (0x45454545)
Typedefs
typedef struct DirtyErrT DirtyErrT
Functions
DIRTYCODE_API void DirtyErrName (char *pBuffer, int32_t iBufSize, uint32_t uError)
This function takes as input a system-specific error code, and either resolves it to its define name if it is recognized or formats it as a hex number if not.
DIRTYCODE_API void DirtyErrNameList (char *pBuffer, int32_t iBufSize, uint32_t uError, const DirtyErrT *pList)
This function takes as input a system-specific error code, and either resolves it to its define name if it is recognized or formats it as a hex number if not.
DIRTYCODE_API const char * DirtyErrGetName (uint32_t uError)
This function takes as input a system-specific error code, and either resolves it to its define name if it is recognized or formats it as a hex number if not.
DIRTYCODE_API const char * DirtyErrGetNameList (uint32_t uError, const DirtyErrT *pList)
This function takes as input a system-specific error code, and either resolves it to its define name if it is recognized or formats it as a hex number if not.
DIRTYCODE_API uint32_t DirtyErrGetHResult (uint32_t uFacility, int32_t iCode, uint8_t bFailure)
create a unique error code for use across DirtySDK
Detailed Description
Macro Definition Documentation
#define DIRTYSOCK_ERRORNAMES (DIRTYCODE_LOGGING && TRUE)
#define DIRTYSOCK_LISTTERM (0x45454545)
Referenced by DirtyErrName(), and DirtyErrNameList().
Typedef Documentation
typedef struct DirtyErrT DirtyErrT
Function Documentation
DIRTYCODE_API uint32_t DirtyErrGetHResult (uint32_t uFacility, int32_t iCode, uint8_t bFailure)
create a unique error code for use across DirtySDK
Parameters
uFacility - the module id the hResult is being generated for (only bottom 11 bits)
iCode - the error code (only bottom 16 bits)
bFailure - true if the code represents a failure
Returns
uint32_t - hResult value
Note
    Description of HRESULT:
     http://msdn.microsoft.com/en-us/library/cc231198.aspx
     Bit  [ 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 09, 08, 07 06, 05, 04, 03, 02, 01, 00]
     Field[  S,  R,  C,  N,  X,  - - - - - - - - - - - FACILITY - - - - - , - - - - - - - - - - - - - - - - CODE - - - - - - - - - - - - ]
     S - Severity - indicates success/fail;  0 - Success, 1 - Failure
     R - Reserved portion of the facility code, corresponds to NT's second severity bit; 1 - Severe Failure
     C - Customer. This bit specifies if the value is customer-defined or Microsoft-defined; 0 - Microsoft-defined, 1 - Customer-defined
     N - Reserved portion of the facility code. Used to indicate a mapped NT status value.
     X - Reserved portion of the facility code. Reserved for internal use. Used to indicate HRESULT values that are not status values, but are instead message ids for display strings.
     FACILITY - indicates the system service that is responsible for the error.
     CODE - is the facility's status code
Version
09/16/2014 (cvienneau)
Referenced by ProtoSSLStat().
DIRTYCODE_API const char* DirtyErrGetName (uint32_t uError)
This function takes as input a system-specific error code, and either resolves it to its define name if it is recognized or formats it as a hex number if not.
Parameters
uError - error code to format
Returns
const char *- pointer to error name or error formatted in hex
Version
10/04/2005 (jbrookes)
References DirtyErrName().
Referenced by CryptRandGet(), CryptRandInit(), FriendApiPrivBlockUser(), FriendApiPrivControl(), FriendApiPrivUpdate(), HLBAddPlayersToHistory(), HLBApiUpdate(), HLBListGameInviteBuddy(), HLBListSendChatMsg(), HLBReceiveMsgAttachment(), NetConnControl(), NetConnShutdown(), NetConnStatus(), NetCritEnter(), NetCritInit(), NetCritKill(), NetCritLeave(), NetCritTry(), NetLibCreate(), SocketAccept(), SocketBind(), SocketClose(), SocketConnect(), SocketControl(), SocketCreate(), SocketDestroy(), SocketImport(), SocketInfo(), SocketListen(), SocketLookup(), SocketRecvfrom(), SocketSendto(), SocketShutdown(), and VoipStartup().
DIRTYCODE_API const char* DirtyErrGetNameList (uint32_t uError, const DirtyErrT * pList)
This function takes as input a system-specific error code, and either resolves it to its define name if it is recognized or formats it as a hex number if not.
Parameters
uError - error code to format
*pList - error list to use
Returns
const char *- pointer to error name or error formatted in hex
Version
10/04/2005 (jbrookes)
References DirtyErrNameList().
DIRTYCODE_API void DirtyErrName (char * pBuffer, int32_t iBufSize, uint32_t uError)
This function takes as input a system-specific error code, and either resolves it to its define name if it is recognized or formats it as a hex number if not.
Parameters
*pBuffer - [out] pointer to output buffer to store result
iBufSize - size of output buffer
uError - error code to format
Returns
None.
Version
10/04/2005 (jbrookes)
References DIRTYSOCK_LISTTERM, ds_snzprintf(), and DirtyErrT::uError.
Referenced by DirtyErrGetName().
DIRTYCODE_API void DirtyErrNameList (char * pBuffer, int32_t iBufSize, uint32_t uError, const DirtyErrT * pList)
This function takes as input a system-specific error code, and either resolves it to its define name if it is recognized or formats it as a hex number if not.
Parameters
*pBuffer - [out] pointer to output buffer to store result
iBufSize - size of output buffer
uError - error code to format
*pList - error list to use
Returns
None.
Version
10/04/2005 (jbrookes)
References DIRTYSOCK_LISTTERM, ds_snzprintf(), and DirtyErrT::uError.
Referenced by DirtyErrGetNameList().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:41