DirtySock: ProtoHttpUtil
ProtoHttpUtil
Proto
Macros
#define PROTOHTTPUTIL_SCHEME_MAX (32)
max supported protocol scheme length
#define PROTOHTTP_GetResponseClass(_eError) (((_eError)/100) * 100)
get class of response code
Typedefs
typedef enum ProtoHttpRequestTypeE ProtoHttpRequestTypeE
request types
typedef enum ProtoHttpResponseE ProtoHttpResponseE
Enumerations
enum ProtoHttpRequestTypeE {
PROTOHTTP_REQUESTTYPE_HEAD = 0,
PROTOHTTP_REQUESTTYPE_GET,
PROTOHTTP_REQUESTTYPE_POST,
PROTOHTTP_REQUESTTYPE_PUT,
PROTOHTTP_REQUESTTYPE_DELETE,
PROTOHTTP_REQUESTTYPE_OPTIONS,
PROTOHTTP_NUMREQUESTTYPES
}
request types
enum ProtoHttpResponseE {
PROTOHTTP_RESPONSE_PENDING = -1,
PROTOHTTP_RESPONSE_INFORMATIONAL = 100,
PROTOHTTP_RESPONSE_CONTINUE = 100,
PROTOHTTP_RESPONSE_SWITCHPROTO,
PROTOHTTP_RESPONSE_SUCCESSFUL = 200,
PROTOHTTP_RESPONSE_OK = 200,
PROTOHTTP_RESPONSE_CREATED,
PROTOHTTP_RESPONSE_ACCEPTED,
PROTOHTTP_RESPONSE_NONAUTH,
PROTOHTTP_RESPONSE_NOCONTENT,
PROTOHTTP_RESPONSE_RESETCONTENT,
PROTOHTTP_RESPONSE_PARTIALCONTENT,
PROTOHTTP_RESPONSE_REDIRECTION = 300,
PROTOHTTP_RESPONSE_MULTIPLECHOICES = 300,
PROTOHTTP_RESPONSE_MOVEDPERMANENTLY,
PROTOHTTP_RESPONSE_FOUND,
PROTOHTTP_RESPONSE_SEEOTHER,
PROTOHTTP_RESPONSE_NOTMODIFIED,
PROTOHTTP_RESPONSE_USEPROXY,
PROTOHTTP_RESPONSE_RESERVED,
PROTOHTTP_RESPONSE_TEMPREDIRECT,
PROTOHTTP_RESPONSE_CLIENTERROR = 400,
PROTOHTTP_RESPONSE_BADREQUEST = 400,
PROTOHTTP_RESPONSE_UNAUTHORIZED,
PROTOHTTP_RESPONSE_PAYMENTREQUIRED,
PROTOHTTP_RESPONSE_FORBIDDEN,
PROTOHTTP_RESPONSE_NOTFOUND,
PROTOHTTP_RESPONSE_METHODNOTALLOWED,
PROTOHTTP_RESPONSE_NOTACCEPTABLE,
PROTOHTTP_RESPONSE_PROXYAUTHREQ,
PROTOHTTP_RESPONSE_REQUESTTIMEOUT,
PROTOHTTP_RESPONSE_CONFLICT,
PROTOHTTP_RESPONSE_GONE,
PROTOHTTP_RESPONSE_LENGTHREQUIRED,
PROTOHTTP_RESPONSE_PRECONFAILED,
PROTOHTTP_RESPONSE_REQENTITYTOOLARGE,
PROTOHTTP_RESPONSE_REQURITOOLONG,
PROTOHTTP_RESPONSE_UNSUPPORTEDMEDIA,
PROTOHTTP_RESPONSE_REQUESTRANGE,
PROTOHTTP_RESPONSE_EXPECTATIONFAILED,
PROTOHTTP_RESPONSE_SERVERERROR = 500,
PROTOHTTP_RESPONSE_INTERNALSERVERERROR = 500,
PROTOHTTP_RESPONSE_NOTIMPLEMENTED,
PROTOHTTP_RESPONSE_BADGATEWAY,
PROTOHTTP_RESPONSE_SERVICEUNAVAILABLE,
PROTOHTTP_RESPONSE_GATEWAYTIMEOUT,
PROTOHTTP_RESPONSE_HTTPVERSUNSUPPORTED
}
Functions
DIRTYCODE_API const char * ProtoHttpFindHeaderValue (const char *pHdrBuf, const char *pHeaderText)
Finds the header field value for the designated header field. The input header text to find should not include formatting (leading
or trailing colon).
DIRTYCODE_API int32_t ProtoHttpExtractHeaderValue (const char *pHdrField, char *pOutBuf, int32_t iOutLen, const char **ppHdrEnd)
Extract header value from the designated header field. Passing pOutBuf=null and iOutLen=0 results in returning the size required to store the field, null-inclusive.
DIRTYCODE_API int32_t ProtoHttpParseHeaderCode (const char *pHdrBuf)
Parse header response code from HTTP header.
DIRTYCODE_API int32_t ProtoHttpGetHeaderValue (void *pState, const char *pHdrBuf, const char *pName, char *pBuffer, int32_t iBufSize, const char **pHdrEnd)
Extract header value for the header field specified by pName from pHdrBuf. Passing pOutBuf=null and iOutLen=0 results in returning the size required to store the field, null-inclusive.
DIRTYCODE_API int32_t ProtoHttpGetNextHeader (void *pState, const char *pHdrBuf, char *pName, int32_t iNameSize, char *pValue, int32_t iValSize, const char **pHdrEnd)
Get the next header name/value pair from the header buffer. pHdrBuf should initially be pointing to the start of the header text buffer ("HTTP...") and this function can then be iteratively called to extract the individual header fields from the header one by one. pHdrBuf could also start as the result of a call to ProtoHttpGetHeaderValue() if desired. If the start of the buffer is not the end of line marker, it is assumed to be the header to retrieve.
DIRTYCODE_API int32_t ProtoHttpUrlEncodeIntParm (char *pBuffer, int32_t iLength, const char *pParm, int32_t iValue)
Url-encode an integer parameter.
DIRTYCODE_API int32_t ProtoHttpUrlEncodeStrParm (char *pBuffer, int32_t iLength, const char *pParm, const char *pData)
Url-encode a string parameter.
DIRTYCODE_API int32_t ProtoHttpUrlEncodeStrParm2 (char *pBuffer, int32_t iLength, const char *pParm, const char *pData, const char *pStrSafe)
Url-encode a string parameter.
DIRTYCODE_API int32_t ProtoHttpUrlDecodeStrParm (const char *pBuffer, char *pData, int32_t iDataSize)
Url-decode a string parameter.
DIRTYCODE_API const char * ProtoHttpUrlParse (const char *pUrl, char *pKind, int32_t iKindSize, char *pHost, int32_t iHostSize, int32_t *pPort, int32_t *pSecure)
Parses a Url into component parts.
DIRTYCODE_API const char * ProtoHttpUrlParse2 (const char *pUrl, char *pKind, int32_t iKindSize, char *pHost, int32_t iHostSize, int32_t *pPort, int32_t *pSecure, uint8_t *bPortSpecified)
Parse information from given URL.
DIRTYCODE_API int32_t ProtoHttpGetNextParam (void *pState, const char *pUriBuf, char *pName, int32_t iNameSize, char *pValue, int32_t iValSize, const char **pUriEnd)
Get the next query param name/value pair from the uri buffer. This function can be iteratively called to extra the individual params one by one.
Detailed Description
Macro Definition Documentation
#define PROTOHTTP_GetResponseClass (_eError) (((_eError)/100) * 100)
get class of response code
#define PROTOHTTPUTIL_SCHEME_MAX (32)
max supported protocol scheme length
Referenced by ProtoHttpUrlParse2().
Typedef Documentation
typedef enum ProtoHttpRequestTypeE ProtoHttpRequestTypeE
request types
typedef enum ProtoHttpResponseE ProtoHttpResponseE
HTTP response codes - see http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10 for more detailed information. These response codes may be retrieved from ProtoHttp by calling ProtoHttpStatus('code'). Note that response codes are not available until a response has been received from the server and parsed by ProtoHttp. If a response code is not yet available, -1 will be returned.
Enumeration Type Documentation
enum ProtoHttpRequestTypeE
request types
Enumerator
PROTOHTTP_REQUESTTYPE_HEAD
HEAD request - does not return any data.
PROTOHTTP_REQUESTTYPE_GET
GET request - get data from a server.
PROTOHTTP_REQUESTTYPE_POST
POST request - post data to a server.
PROTOHTTP_REQUESTTYPE_PUT
PUT request - put data on a server.
PROTOHTTP_REQUESTTYPE_DELETE
DELETE request - delete resource from a server.
PROTOHTTP_REQUESTTYPE_OPTIONS
OPTIONS request - get server options for specified resource.
PROTOHTTP_NUMREQUESTTYPES
enum ProtoHttpResponseE
HTTP response codes - see http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10 for more detailed information. These response codes may be retrieved from ProtoHttp by calling ProtoHttpStatus('code'). Note that response codes are not available until a response has been received from the server and parsed by ProtoHttp. If a response code is not yet available, -1 will be returned.
Enumerator
PROTOHTTP_RESPONSE_PENDING
response has not yet been received
PROTOHTTP_RESPONSE_INFORMATIONAL
generic name for a 1xx class response
PROTOHTTP_RESPONSE_CONTINUE
continue with request, generally ignored
PROTOHTTP_RESPONSE_SWITCHPROTO
101 - OK response to client switch protocol request
PROTOHTTP_RESPONSE_SUCCESSFUL
generic name for a 2xx class response
PROTOHTTP_RESPONSE_OK
client's request was successfully received, understood, and accepted
PROTOHTTP_RESPONSE_CREATED
new resource has been created
PROTOHTTP_RESPONSE_ACCEPTED
request accepted but not complete
PROTOHTTP_RESPONSE_NONAUTH
non-authoritative info (ok)
PROTOHTTP_RESPONSE_NOCONTENT
request fulfilled, no message body
PROTOHTTP_RESPONSE_RESETCONTENT
request success, reset document view
PROTOHTTP_RESPONSE_PARTIALCONTENT
server has fulfilled partial GET request
PROTOHTTP_RESPONSE_REDIRECTION
generic name for a 3xx class response
PROTOHTTP_RESPONSE_MULTIPLECHOICES
requested resource corresponds to a set of representations
PROTOHTTP_RESPONSE_MOVEDPERMANENTLY
requested resource has been moved permanently to new URI
PROTOHTTP_RESPONSE_FOUND
requested resources has been moved temporarily to a new URI
PROTOHTTP_RESPONSE_SEEOTHER
response can be found under a different URI
PROTOHTTP_RESPONSE_NOTMODIFIED
response to conditional get when document has not changed
PROTOHTTP_RESPONSE_USEPROXY
requested resource must be accessed through proxy
PROTOHTTP_RESPONSE_RESERVED
old response code - reserved
PROTOHTTP_RESPONSE_TEMPREDIRECT
requested resource resides temporarily under a different URI
PROTOHTTP_RESPONSE_CLIENTERROR
generic name for a 4xx class response
PROTOHTTP_RESPONSE_BADREQUEST
request could not be understood by server due to malformed syntax
PROTOHTTP_RESPONSE_UNAUTHORIZED
request requires user authorization
PROTOHTTP_RESPONSE_PAYMENTREQUIRED
reserved for future user
PROTOHTTP_RESPONSE_FORBIDDEN
request understood, but server will not fulfill it
PROTOHTTP_RESPONSE_NOTFOUND
Request-URI not found.
PROTOHTTP_RESPONSE_METHODNOTALLOWED
method specified in the Request-Line is not allowed
PROTOHTTP_RESPONSE_NOTACCEPTABLE
resource incapable of generating content acceptable according to accept headers in request
PROTOHTTP_RESPONSE_PROXYAUTHREQ
client must first authenticate with proxy
PROTOHTTP_RESPONSE_REQUESTTIMEOUT
client did not produce response within server timeout
PROTOHTTP_RESPONSE_CONFLICT
request could not be completed due to a conflict with current state of the resource
PROTOHTTP_RESPONSE_GONE
requested resource is no longer available and no forwarding address is known
PROTOHTTP_RESPONSE_LENGTHREQUIRED
a Content-Length header was not specified and is required
PROTOHTTP_RESPONSE_PRECONFAILED
precondition given in request-header field(s) failed
PROTOHTTP_RESPONSE_REQENTITYTOOLARGE
request entity is larger than the server is able or willing to process
PROTOHTTP_RESPONSE_REQURITOOLONG
Request-URI is longer than the server is willing to interpret.
PROTOHTTP_RESPONSE_UNSUPPORTEDMEDIA
request entity is in unsupported format
PROTOHTTP_RESPONSE_REQUESTRANGE
invalid range in Range request header
PROTOHTTP_RESPONSE_EXPECTATIONFAILED
expectation in Expect request-header field could not be met by server
PROTOHTTP_RESPONSE_SERVERERROR
generic name for a 5xx class response
PROTOHTTP_RESPONSE_INTERNALSERVERERROR
an unexpected condition prevented the server from fulfilling the request
PROTOHTTP_RESPONSE_NOTIMPLEMENTED
the server does not support the functionality required to fulfill the request
PROTOHTTP_RESPONSE_BADGATEWAY
invalid response from gateway server
PROTOHTTP_RESPONSE_SERVICEUNAVAILABLE
unable to handle request due to a temporary overloading or maintainance
PROTOHTTP_RESPONSE_GATEWAYTIMEOUT
gateway or DNS server timeout
PROTOHTTP_RESPONSE_HTTPVERSUNSUPPORTED
the server does not support the HTTP protocol version that was used in the request
Function Documentation
DIRTYCODE_API int32_t ProtoHttpExtractHeaderValue (const char * pInpBuf, char * pOutBuf, int32_t iOutLen, const char ** ppHdrEnd)
Extract header value from the designated header field. Passing pOutBuf=null and iOutLen=0 results in returning the size required to store the field, null-inclusive.
Parameters
*pInpBuf - pointer to header text
*pOutBuf - [out] output for header field value, null for size query
iOutLen - size of output buffer or zero for size query
**ppHdrEnd- [out] pointer past end of parsed header (optional)
Returns
int32_t - negative=not found or not enough space, zero=success, positive=size query result
Version
03/17/2009 (jbrookes)
Referenced by ProtoHttpGetHeaderValue(), ProtoHttpGetLocationHeader(), and ProtoHttpGetNextHeader().
DIRTYCODE_API const char* ProtoHttpFindHeaderValue (const char * pHdrBuf, const char * pHeaderText)
Finds the header field value for the designated header field. The input header text to find should not include formatting (leading
or trailing colon).
Parameters
*pHdrBuf - input buffer
*pHeaderText - header field to find
Returns
char * - pointer to header value text or null if not found
Version
03/17/2009 (jbrookes)
References ds_snzprintf(), and ds_stristr().
Referenced by ProtoHttpGetHeaderValue(), and ProtoHttpGetLocationHeader().
DIRTYCODE_API int32_t ProtoHttpGetHeaderValue (void * pState, const char * pHdrBuf, const char * pName, char * pBuffer, int32_t iBufSize, const char ** pHdrEnd)
Extract header value for the header field specified by pName from pHdrBuf. Passing pOutBuf=null and iOutLen=0 results in returning the size required to store the field, null-inclusive.
Parameters
*pState - module state
*pHdrBuf - header text
*pName - header field name (case-insensitive)
*pBuffer - [out] pointer to buffer to store extracted header value (null for size query)
iBufSize - size of output buffer (zero for size query)
**pHdrEnd- [out] pointer past end of parsed header (optional)
Returns
int32_t - negative=not found or not enough space, zero=success, positive=size query result
Version
03/24/2009 (jbrookes)
References ds_stricmp(), ProtoHttpExtractHeaderValue(), ProtoHttpFindHeaderValue(), and ProtoHttpGetLocationHeader().
DIRTYCODE_API int32_t ProtoHttpGetNextHeader (void * pState, const char * pHdrBuf, char * pName, int32_t iNameSize, char * pValue, int32_t iValSize, const char ** pHdrEnd)
Get the next header name/value pair from the header buffer. pHdrBuf should initially be pointing to the start of the header text buffer ("HTTP...") and this function can then be iteratively called to extract the individual header fields from the header one by one. pHdrBuf could also start as the result of a call to ProtoHttpGetHeaderValue() if desired. If the start of the buffer is not the end of line marker, it is assumed to be the header to retrieve.
Parameters
*pState - module state
*pHdrBuf - header text
*pName - [out] header field name
iNameSize- size of header field name buffer
*pValue - [out] pointer to buffer to store extracted header value (null for size query)
iValSize - size of output buffer (zero for size query)
**pHdrEnd- [out] pointer past end of parsed header
Returns
int32_t - negative=not found or not enough space, zero=success, positive=size query result
Version
03/24/2009 (jbrookes)
References ProtoHttpExtractHeaderValue().
Referenced by _ProtoWebSocketAppendHeader().
DIRTYCODE_API int32_t ProtoHttpGetNextParam (void * pState, const char * pUriBuf, char * pName, int32_t iNameSize, char * pValue, int32_t iValSize, const char ** pUriEnd)
Get the next query param name/value pair from the uri buffer. This function can be iteratively called to extra the individual params one by one.
Parameters
*pState - module state
*pUriBuf - path text
*pName - [out] query key name
iNameSize- size of query key name buffer
*pValue - [out] pointer to buffer to store extracted query value
iValSize - size of output buffer
**pUriEnd- [out] pointer past end of parsed query
Returns
int32_t - negative=not found or not enough space, zero=success
References ds_strsubzcpy().
DIRTYCODE_API int32_t ProtoHttpParseHeaderCode (const char * pHdrBuf)
Parse header response code from HTTP header.
Parameters
*pHdrBuf - pointer to first line of HTTP header
Returns
int32_t - parsed header code
Version
01/12/2010 (jbrookes)
DIRTYCODE_API int32_t ProtoHttpUrlDecodeStrParm (const char * pBuffer, char * pData, int32_t iDataSize)
Url-decode a string parameter.
Parameters
*pBuffer - pointer to the buffer with the url-encoded string
*pData - [out] location to write the url-decoded string
iDataSize- length of pData
Returns
int32_t - negative=failure, zero=success
< 2 character + null term
DIRTYCODE_API int32_t ProtoHttpUrlEncodeIntParm (char * pBuffer, int32_t iLength, const char * pParm, int32_t iValue)
Url-encode an integer parameter.
Parameters
*pBuffer - [out] pointer to buffer to append parameter to
iLength - length of buffer
*pParm - pointer to parameter (not encoded)
iValue - integer to encode
Returns
int32_t - negative=failure, zero=success
Version
11/30/2004 (jbrookes) First Version
References ds_snzprintf().
DIRTYCODE_API int32_t ProtoHttpUrlEncodeStrParm (char * pBuffer, int32_t iLength, const char * pParm, const char * pData)
Url-encode a string parameter.
Parameters
*pBuffer - [out] pointer to buffer to append parameter to
iLength - length of buffer
*pParm - pointer to url parameter (not encoded)
*pData - string to encode
Returns
int32_t - negative=failure, zero=success
Version
11/30/2004 (jbrookes) First Version
References ProtoHttpUrlEncodeStrParm2().
DIRTYCODE_API int32_t ProtoHttpUrlEncodeStrParm2 (char * pBuffer, int32_t iLength, const char * pParm, const char * pData, const char * pStrSafe)
Url-encode a string parameter.
Parameters
*pBuffer - [out] pointer to buffer to append parameter to
iLength - length of buffer
*pParm - pointer to url parameter (not encoded)
*pData - string to encode
*pStrSafe- safe string table
Returns
int32_t - negative=failure, zero=success
Version
11/30/2004 (jbrookes) First Version
Referenced by ProtoHttpUrlEncodeStrParm().
DIRTYCODE_API const char* ProtoHttpUrlParse (const char * pUrl, char * pKind, int32_t iKindSize, char * pHost, int32_t iHostSize, int32_t * pPort, int32_t * pSecure)
Parses a Url into component parts.
Parameters
*pUrl - Url to parse
*pKind - [out] http request kind
iKindSize - size of kind output buffer
*pHost - [out] host name
iHostSize - size of host output buffer
*pPort - [out] request port
*pSecure - [out] request security
Returns
const char * - pointer past end of parsed Url
Version
07/01/2009 (jbrookes) First Version
References ProtoHttpUrlParse2().
DIRTYCODE_API const char* ProtoHttpUrlParse2 (const char * pUrl, char * pKind, int32_t iKindSize, char * pHost, int32_t iHostSize, int32_t * pPort, int32_t * pSecure, uint8_t * pPortSpecified)
Parse information from given URL.
Parameters
*pUrl - pointer to input URL to parse
*pKind - [out] storage for parsed URL kind (eg "http", "https")
iKindSize - size of pKind buffer
*pHost - [out] storage for parsed URL host
iHostSize - size of pHost buffer
*pPort - [out] storage for parsed port
*pSecure - [out] storage for parsed security (0 or 1)
*pPortSpecified - [out] storage for whether port was specified
Returns
const char * - pointer to URL arguments
Note
URI RFC http://www.ietf.org/rfc/rfc2396.txt
Version
11/10/2004 (jbrookes) Split/combined from ProtoHttpGet() and ProtoHttpPost()
References ds_stricmp(), ds_strnzcpy(), ds_strsubzcpy(), FALSE, PROTOHTTPUTIL_SCHEME_MAX, and TRUE.
Referenced by ProtoHttpCheckKeepAlive(), ProtoHttpSetBaseUrl(), ProtoHttpUrlParse(), and ProtoWebSocketStatus().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:34:37