DirtySock: voipheadsetps3.c File Reference
voipheadsetps3.c File Reference
VoIP headset manager.
#include <stdio.h>
#include <string.h>
#include <sdk_version.h>
#include <cell/audio.h>
#include <cell/mic.h>
#include <cell/sysmodule.h>
#include "DirtySDK/platform.h"
#include "DirtySDK/dirtysock.h"
#include "DirtySDK/dirtysock/dirtymem.h"
#include "DirtySDK/dirtysock/dirtyerr.h"
#include "DirtySDK/dirtysock/netconn.h"
#include "DirtySDK/voip/voipdef.h"
#include "voippriv.h"
#include "voipconnection.h"
#include "voippacket.h"
#include "voipmixer.h"
#include "voipconduit.h"
#include "DirtySDK/voip/voipcodec.h"
#include "voipheadset.h"
#include "voipdvi.h"
#include "voippcm.h"
#include "voipcelp.h"
Data Structures
struct VoipHeadsetParamT
headset sampling parameters
struct VoipHeadsetRefT
VOIP module state data.
Macros
#define VOIP_HEADSET_DEFAULTSAMPLERATE (16000)
default sample rate in hz
#define VOIP_HEADSET_DEFAULTFRAMESAMPLES (160)
default number of samples/frame (20ms at 8khz)
#define VOIP_HEADSET_MAX_READ_SAMPLES (16000/10)
100ms worth of samples data at 16khz
#define VOIP_HEADSET_BLOCK_SIZE (CELL_AUDIO_PORT_2CH * sizeof(float) * CELL_AUDIO_BLOCK_SAMPLES)
block size (in bytes) used to empty mix buffer and feed headset
#define VOIP_HEADSET_OUTBUFFER_BLOCKS (CELL_AUDIO_BLOCK_32)
port size in blocks
#define VOIP_HEADSET_MAX_BLOCKS (9)
max number of blocks that may be written out to audio at one time
#define VOIP_HEADSET_SOUND_TRIGGER_DECIBEL (50.0f)
min volume to not trigger VAD
#define VOIP_HEADSET_TALKING_MIN_DURATION (200)
min duration to not trigger VAD
Typedefs
typedef struct VoipHeadsetParamT VoipHeadsetParamT
headset sampling parameters
Functions
VoipHeadsetRefT * VoipHeadsetCreate (int32_t iMaxConduits, int32_t iMaxLocal, VoipHeadsetMicDataCbT *pMicDataCb, VoipHeadsetStatusCbT *pStatusCb, void *pCbUserData, int32_t iData)
Create the headset manager.
void VoipHeadsetDestroy (VoipHeadsetRefT *pHeadset)
Destroy the headset manager.
void VoipHeadsetReceiveVoiceDataCb (VoipUserT *pRemoteUsers, VoipMicrInfoT *pMicrInfo, uint8_t *pPacketData, void *pUserData)
Connectionlist callback to handle receiving a voice packet from a remote peer.
void VoipHeadsetRegisterUserCb (VoipUserT *pRemoteUser, uint32_t bRegister, void *pUserData)
Connectionlist callback to register/unregister a new user with the VoipConduit module.
void VoipHeadsetProcess (VoipHeadsetRefT *pHeadset, uint32_t uFrameCount)
Headset process function.
void VoipHeadsetSetVolume (VoipHeadsetRefT *pHeadset, int32_t iPlayVol, uint32_t iRecVol)
Sets play and record volume.
int32_t VoipHeadsetControl (VoipHeadsetRefT *pHeadset, int32_t iControl, int32_t iValue, int32_t iValue2, void *pValue)
Control function.
int32_t VoipHeadsetStatus (VoipHeadsetRefT *pHeadset, int32_t iSelect, int32_t iValue, void *pBuf, int32_t iBufSize)
Status function.
void VoipHeadsetSpkrCallback (VoipHeadsetRefT *pHeadset, VoipSpkrCallbackT *pCallback, void *pUserData)
Set speaker output callback.
Variables
int32_t _VoipHeadsetPS3_iDefaultCodecIdent = 'celp'
int32_t _VoipHeadsetPS3_iDefaultSampleRate = VOIP_HEADSET_DEFAULTSAMPLERATE
Detailed Description
VoIP headset manager.
Attention
Copyright (c) Electronic Arts 2006. ALL RIGHTS RESERVED.
Note
Summary of PS3 voice/voip operations:
Voip producer: voice data samples (floats) are obtained from the mic with calls to cellMicRead() voice data samples are grouped into "voice data bundles" in place, i.e. in the buffer being filled by cellMicRead() voice data bundles get encoded/compressed with VoipCodecEncode() the resulting data buffer is then passed to the voip transmission code for sending over the network the voip transmission code packs the compresssed voice data bundle as a sub-packet of a given voip packet (a voip packet can contain several sub-packets)
Voip consumer: the voip reception code unpacks sub-packets found in incoming voip packets each sub-packet is passed to the matching voip conduit (one conduit per local user) voip data is then decoded and mixed in the mix buffer mixed data is copied out of the mix buffer and fed into the audio device in chunks of size VOIP_HEADSET_BLOCK_SIZE bytes left-over mixed data (codec frame sizes tend to not match block output frame sizes) is retained for the next iteration
NOTE - we make the assumption that any left-over data that remains in the FrameData buffer and has not been written out to the audio output buffer when VAD kicks in can be disposed of; this data will be close to the VAD threshold and therefore it should not be easy to detect its absence.
Current configuration: voice bundles are set to capture from 20-40ms of samples, depending on input rate and codec codec input frame size and output data size depend on the codec; input frames range from 80 to 320 samples LPCM is supported only in loopback mode
Version
1.0 08/10/2006 (tdills) Port from PSP to PS3
2.0 10/20/2011 (jbrookes) Major rewrite to fix issues and support more codecs/sample rates
Macro Definition Documentation
#define VOIP_HEADSET_BLOCK_SIZE (CELL_AUDIO_PORT_2CH * sizeof(float) * CELL_AUDIO_BLOCK_SAMPLES)
block size (in bytes) used to empty mix buffer and feed headset
#define VOIP_HEADSET_DEFAULTFRAMESAMPLES (160)
default number of samples/frame (20ms at 8khz)
#define VOIP_HEADSET_DEFAULTSAMPLERATE (16000)
default sample rate in hz
#define VOIP_HEADSET_MAX_BLOCKS (9)
max number of blocks that may be written out to audio at one time
#define VOIP_HEADSET_MAX_READ_SAMPLES (16000/10)
100ms worth of samples data at 16khz
#define VOIP_HEADSET_OUTBUFFER_BLOCKS (CELL_AUDIO_BLOCK_32)
port size in blocks
#define VOIP_HEADSET_SOUND_TRIGGER_DECIBEL (50.0f)
min volume to not trigger VAD
#define VOIP_HEADSET_TALKING_MIN_DURATION (200)
min duration to not trigger VAD
Typedef Documentation
typedef struct VoipHeadsetParamT VoipHeadsetParamT
headset sampling parameters
Function Documentation
int32_t VoipHeadsetControl (VoipHeadsetRefT * pHeadset, int32_t iControl, int32_t iValue, int32_t iValue2, void * pValue)
Control function.
Parameters
*pHeadset - headset module state
iControl - control selector
iValue - control value
iValue2 - control value
*pValue - control value
Returns
int32_t - selector specific, or -1 if no such selector
Note
iControl can be one of the following:
        'aloc' - activate/deactivate local user (enter/exit "participating" state)
        'agcl' - set automatic gain control target value
        'bkgn' - set background noise level
        'cdec' - create a new codec
        'dcde' - change default codec (shall be used prior to module creation)
        'drat' - change default sample rate (shall be used prior to module creation)
        'loop' - enable/disable loopback
        'mrat' - set mic input sample rate (8000hz or 16000hz)
        'rvrb' - set avg reverb time
Version
07/28/2004 (jbrookes)
References _VoipHeadsetPS3_iDefaultCodecIdent, _VoipHeadsetPS3_iDefaultSampleRate, VoipHeadsetRefT::bLoopback, VoipHeadsetRefT::bParticipating, FALSE, VoipHeadsetRefT::fBkgndNoiseGain, VoipHeadsetRefT::iAGCLevel, VoipHeadsetRefT::iReverb, NetPrintf, and TRUE.
Referenced by VoipActivateLocalUser(), VoipCommonControl(), and VoipControl().
VoipHeadsetRefT* VoipHeadsetCreate (int32_t iMaxConduits, int32_t iMaxLocal, VoipHeadsetMicDataCbT * pMicDataCb, VoipHeadsetStatusCbT * pStatusCb, void * pCbUserData, int32_t iData)
Create the headset manager.
Parameters
iMaxConduits - max number of conduits
iMaxLocal - max number of local users (ignored because only primary user can do voip on PS3)
*pMicDataCb - pointer to user callback to trigger when mic data is ready
*pStatusCb - pointer to user callback to trigger when headset status changes
*pCbUserData - pointer to user callback data
iData - platform-specific - unused for PS3
Returns
VoipHeadsetRefT * - pointer to module state, or NULL if an error occured
Version
03/30/2004 (jbrookes)
References _VoipHeadsetPS3_iDefaultCodecIdent, _VoipHeadsetPS3_iDefaultSampleRate, DirtyMemAlloc(), DirtyMemFree(), VoipHeadsetRefT::fBkgndNoiseGain, VoipHeadsetRefT::iAGCLevel, VoipHeadsetRefT::iMaxConduits, VoipHeadsetRefT::iReverb, VoipHeadsetParamT::iSampleRate, NetPrintf, NULL, VoipHeadsetRefT::Param, VoipHeadsetRefT::pCbUserData, VoipHeadsetRefT::pConduitRef, VoipHeadsetRefT::pMicDataCb, VoipHeadsetRefT::pMixerRef, VoipHeadsetRefT::pStatusCb, VOIP_MAXCONNECT, VOIP_MEMID, VoipCelp8_CodecDef, VoipCelp_CodecDef, VoipCodecRegister(), VoipConduitCreate(), VoipDVI_CodecDef, VoipMemGroupQuery(), and VoipPCM_CodecDef.
Referenced by VoipCommonStartup().
void VoipHeadsetDestroy (VoipHeadsetRefT * pHeadset)
Destroy the headset manager.
Parameters
*pHeadset - pointer to headset state
Version
03/31/2004 (jbrookes)
References DirtyMemFree(), NetPrintf, VoipHeadsetRefT::pConduitRef, VoipHeadsetRefT::pMixerRef, VOIP_MEMID, VoipCodecDestroy(), VoipConduitDestroy(), VoipMemGroupQuery(), and VoipMixerDestroy().
Referenced by VoipCommonShutdown().
void VoipHeadsetProcess (VoipHeadsetRefT * pHeadset, uint32_t uFrameCount)
Headset process function.
Parameters
*pHeadset - pointer to headset state
uFrameCount - current frame count
Version
03/31/2004 (jbrookes)
void VoipHeadsetReceiveVoiceDataCb (VoipUserT * pRemoteUsers, VoipMicrInfoT * pMicrInfo, uint8_t * pPacketData, void * pUserData)
Connectionlist callback to handle receiving a voice packet from a remote peer.
Parameters
*pRemoteUsers - user we're receiving the voice data from
*pMicrInfo - micr info from inbound packet
*pPacketData - pointer to beginning of data in packet payload
*pUserData - VoipHeadsetT ref
Version
03/21/2004 (jbrookes)
References VoipHeadsetRefT::bPlaying, FALSE, VoipHeadsetParamT::iCmpFrameSize, NetPrintf, NetPrintfVerbose, VoipHeadsetRefT::Param, VoipHeadsetRefT::pConduitRef, VoipMicrInfoT::uNumSubPackets, VoipMicrInfoT::uSeqn, VoipMicrInfoT::uSubPacketSize, VoipMicrInfoT::uUserIndex, and VoipConduitReceiveVoiceData().
Referenced by VoipCommonStartup().
void VoipHeadsetRegisterUserCb (VoipUserT * pRemoteUser, uint32_t bRegister, void * pUserData)
Connectionlist callback to register/unregister a new user with the VoipConduit module.
Parameters
*pRemoteUser - user to register
bRegister - true=register, false=unregister
*pUserData - voipheadset module ref
Version
03/21/2004 (jbrookes)
References VoipHeadsetRefT::pConduitRef, and VoipConduitRegisterUser().
Referenced by VoipCommonStartup().
void VoipHeadsetSetVolume (VoipHeadsetRefT * pHeadset, int32_t iPlayVol, uint32_t iRecVol)
Sets play and record volume.
Parameters
*pHeadset - pointer to headset state
iPlayVol - play volume to set
iRecVol - record volume to set
Note
To not set a value, specify it as -1.
Version
03/31/2004 (jbrookes)
void VoipHeadsetSpkrCallback (VoipHeadsetRefT * pHeadset, VoipSpkrCallbackT * pCallback, void * pUserData)
Set speaker output callback.
Parameters
*pHeadset - headset module state
*pCallback - what to call when output data is available
*pUserData - user data for callback
Version
10/31/2011 (jbrookes)
References VoipHeadsetRefT::pSpkrCbUserData, and VoipHeadsetRefT::pSpkrDataCb.
Referenced by VoipSpkrCallback().
int32_t VoipHeadsetStatus (VoipHeadsetRefT * pHeadset, int32_t iSelect, int32_t iValue, void * pBuf, int32_t iBufSize)
Status function.
Parameters
*pHeadset - headset module state
iSelect - control selector
iValue - selector specific
*pBuf - buffer pointer
iBufSize - buffer size
Returns
int32_t - selector specific, or -1 if no such selector
Note
iSelect can be one of the following:
Version
07/28/2004 (jbrookes)
Referenced by VoipCommonStatus().
Variable Documentation
int32_t _VoipHeadsetPS3_iDefaultCodecIdent = 'celp'
Referenced by VoipHeadsetControl(), and VoipHeadsetCreate().
int32_t _VoipHeadsetPS3_iDefaultSampleRate = VOIP_HEADSET_DEFAULTSAMPLERATE
Referenced by VoipHeadsetControl(), and VoipHeadsetCreate().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:41