DirtySock: dirtynetxenon.c File Reference
dirtynetxenon.c File Reference
Provide a wrapper that translates the Winsock network interface into DirtySock calls, as well as handling Xenon-specific functionality. In the case of Winsock, little translation is needed since it is based off BSD sockets (as is DirtySock).
#include <xtl.h>
#include <winsockx.h>
#include "DirtySDK/dirtysock/dirtylib.h"
#include "DirtySDK/dirtysock/dirtymem.h"
#include "DirtySDK/dirtysock/dirtynet.h"
#include "DirtySDK/dirtysock/xenon/dirtylspxenon.h"
#include "DirtySDK/dirtyvers.h"
#include "dirtynetpriv.h"
Data Structures
struct SocketT
dirtysock connection socket structure
struct SocketStateT
local state
Macros
#define SOCKET_MAXEVENTS (64)
Typedefs
typedef struct SocketStateT SocketStateT
local state
Functions
int32_t SocketCreate (int32_t iThreadPrio, int32_t iThreadStackSize, int32_t iThreadCpuAffinity)
Create new instance of socket interface module. Initializes all global resources and makes module ready for use.
int32_t SocketDestroy (uint32_t uShutdownFlags)
Release resources and destroy module.
SocketT * SocketOpen (int32_t af, int32_t type, int32_t proto)
Create a new transfer endpoint. A socket endpoint is required for any data transfer operation.
int32_t SocketClose (SocketT *pSocket)
Close a socket. Performs a graceful shutdown of connection oriented protocols.
SocketT * SocketImport (intptr_t uSockRef)
Import a socket. The given socket ref may be a SocketT, in which case a SocketT pointer to the ref is returned, or it can be an actual Sony socket ref, in which case a SocketT is created for the Sony socket ref.
void SocketRelease (SocketT *pSock)
Release an imported socket.
int32_t SocketShutdown (SocketT *pSocket, int32_t iHow)
Perform partial/complete shutdown of socket indicating that either sending and/or receiving is complete.
int32_t SocketBind (SocketT *pSocket, const struct sockaddr *name, int32_t namelen)
Bind a local address/port to a socket.
int32_t SocketConnect (SocketT *pSocket, struct sockaddr *name, int32_t namelen)
Initiate a connection attempt to a remote host.
int32_t SocketListen (SocketT *pSocket, int32_t backlog)
Start listening for an incoming connection on the socket. The socket must already be bound and a stream oriented connection must be in use.
SocketT * SocketAccept (SocketT *pSocket, struct sockaddr *addr, int32_t *addrlen)
Accept an incoming connection attempt on a socket.
int32_t SocketSendto (SocketT *pSocket, const char *buf, int32_t len, int32_t flags, const struct sockaddr *to, int32_t tolen)
Send data to a remote host. The destination address is supplied along with the data. Should only be used with datagram sockets as stream sockets always send to the connected peer.
int32_t SocketRecvfrom (SocketT *pSock, char *pBuf, int32_t iLen, int32_t iFlags, struct sockaddr *pFrom, int32_t *pFromLen)
Receive data from a remote host. If socket is a connected stream, then data can only come from that source. A datagram socket can receive from any remote host.
int32_t SocketInfo (SocketT *pSocket, int32_t iInfo, int32_t iData, void *pBuf, int32_t iLen)
Return information about an existing socket.
int32_t SocketCallback (SocketT *pSocket, int32_t mask, int32_t idle, void *ref, int32_t(*proc)(SocketT *sock, int32_t flags, void *ref))
Register a callback routine for notification of socket events. Also includes timeout support.
int32_t SocketControl (SocketT *pSocket, int32_t iOption, int32_t iData1, void *pData2, void *pData3)
Process a control message (type specific operation)
uint32_t SocketGetLocalAddr (void)
Returns the "external" local address (ie, the address as a machine "out on the Internet" would see as the local machine's address).
HostentT * SocketLookup (const char *text, int32_t timeout)
Lookup a host by name and return the corresponding Internet address. Uses a callback/polling system since the socket library does not allow blocking.
HostentT * SocketLookup2 (const char *text, int32_t timeout, uint32_t flags)
Lookup a host by name and return the corresponding Internet address. Uses a callback/polling system since the socket library does not allow blocking.
int32_t SocketHost (struct sockaddr *host, int32_t hostlen, const struct sockaddr *dest, int32_t destlen)
Return the host address that would be used in order to communicate with the given destination address.
Detailed Description
Provide a wrapper that translates the Winsock network interface into DirtySock calls, as well as handling Xenon-specific functionality. In the case of Winsock, little translation is needed since it is based off BSD sockets (as is DirtySock).
Attention
Copyright (c) Electronic Arts 2004-2013.
Version
1.0 01/02/2004 (jbrookes) First Version
Macro Definition Documentation
#define SOCKET_MAXEVENTS (64)
Typedef Documentation
typedef struct SocketStateT SocketStateT
local state
Function Documentation
int32_t SocketCallback (SocketT * pSocket, int32_t mask, int32_t idle, void * ref, int32_t(*)(SocketT *sock, int32_t flags, void *ref) proc)
Register a callback routine for notification of socket events. Also includes timeout support.
Parameters
*pSocket - socket reference
mask - valid callback events (CALLB_NONE, CALLB_SEND, CALLB_RECV)
idle - if nonzero, specifies the number of ticks between idle calls
*ref - user data to be passed to proc
*proc - user callback
Returns
int32_t - zero
Note
A callback will reset the idle timer, so when specifying a callback and an idle processing time, the idle processing time represents the maximum elapsed time between calls.
Version
10/04/1999 (gschaefer)
References SocketT::callback, SocketT::callidle, SocketT::callmask, SocketT::callref, and proc.
HostentT* SocketLookup2 (const char * text, int32_t timeout, uint32_t flags)
Lookup a host by name and return the corresponding Internet address. Uses a callback/polling system since the socket library does not allow blocking.
Parameters
*text - pointer to null terminated address string
timeout - number of milliseconds to wait for completion
flags - SOCKLOOK_FLAGS_*
Returns
HostentT * - hostent struct that includes callback vectors
Version
10/04/1999 (gschaefer)
References HostentT::addr, DirtyLSPQueryStart(), DirtyMemAlloc(), HostentT::done, HostentT::Done, ds_strnzcpy(), HostentT::Free, SocketStateT::iDnsRemap, SocketStateT::iMemGroup, HostentT::name, NetPrintf, NULL, HostentT::pData, SocketStateT::pDirtyLSP, SocketStateT::pMemGroupUserData, HostentT::sema, SOCKET_MEMID, SocketInTextGetAddr(), SOCKLOOK_FLAGS_ALLOWXDNS, and HostentT::thread.
Referenced by ProtoSSLConnect(), and SocketLookup().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:55