#!/bin/bash
# ** NOTE **
# In your MacOS / Unix client spec, make sure that this file has "text" file type (not binary) and your client spec has
# "Line ending characters for text files" set to "Local: defaults to the current operating system".  If you modify this
# file in Windows OS, this file will have "carriage return" + "newline" characters in line ending. This "carriage return"
# character will mess up the script if Mac OS sees it.  The above perforce setting will properly remove this unwanted 
# character on MacOS / Unix environment.
exec mono $(dirname $0)/bin/nant.exe "$@"