DirtySock: CryptHmac
CryptHmac
Crypt
Data Structures
struct CryptHmacMsgT
Typedefs
typedef struct CryptHmacMsgT CryptHmacMsgT
Functions
DIRTYCODE_API int32_t CryptHmacCalc (uint8_t *pBuffer, int32_t iBufLen, const uint8_t *pMessage, int32_t iMessageLen, const uint8_t *pKey, int32_t iKeyLen, CryptHashTypeE eHashType)
Implements HMAC as defined in http://tools.ietf.org/html/rfc4346#section-5.
DIRTYCODE_API int32_t CryptHmacCalcMulti (uint8_t *pBuffer, int32_t iBufLen, const CryptHmacMsgT *pMessageList, int32_t iNumMessages, const uint8_t *pKey, int32_t iKeyLen, CryptHashTypeE eHashType)
Implements HMAC as defined in http://tools.ietf.org/html/rfc4346#section-5. This version allows multiple buffers to be specified in one call, which is useful when the input to be hashed is not in a single contiguous buffer.
Detailed Description
Typedef Documentation
typedef struct CryptHmacMsgT CryptHmacMsgT
Function Documentation
DIRTYCODE_API int32_t CryptHmacCalc (uint8_t * pBuffer, int32_t iBufLen, const uint8_t * pMessage, int32_t iMessageLen, const uint8_t * pKey, int32_t iKeyLen, CryptHashTypeE eHashType)
Implements HMAC as defined in http://tools.ietf.org/html/rfc4346#section-5.
Parameters
*pBuffer - [out] storage for generated digest
iBufLen - size of output buffer
*pMessage - input data to hash
iMessageLen - size of input data
*pKey - seed
iKeyLen - seed length
eHashType - hash type
Returns
int32_t - negative=error, else success
Version
01/14/2013 (jbrookes)
References CryptHmacCalcMulti(), CryptHmacMsgT::iMessageLen, and CryptHmacMsgT::pMessage.
DIRTYCODE_API int32_t CryptHmacCalcMulti (uint8_t * pBuffer, int32_t iBufLen, const CryptHmacMsgT * pMessageList, int32_t iNumMessages, const uint8_t * pKey, int32_t iKeyLen, CryptHashTypeE eHashType)
Implements HMAC as defined in http://tools.ietf.org/html/rfc4346#section-5. This version allows multiple buffers to be specified in one call, which is useful when the input to be hashed is not in a single contiguous buffer.
Parameters
*pBuffer - [out] storage for generated MAC
iBufLen - size of output buffer (may be smaller than hash size for truncated HMAC)
*pMessageList- list of messages to hash
iNumMessages - number of messages to hash
*pKey - seed
iKeyLen - seed length
eHashType - hash type
Returns
int32_t - negative=error, else success
Version
01/14/2013 (jbrookes)
References CRYPTHASH_MAXDIGEST, CRYPTHASH_MAXSTATE, CryptHashGet(), CRYPTSHA384_HASHSIZE, ds_memcpy(), CryptHashT::Final, CryptHashT::iHashSize, CryptHashT::Init, NetPrintf, NULL, and CryptHashT::Update.
Referenced by CryptHmacCalc().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:31