DirtySock: DirtyPng
DirtyPng
Graph
Data Structures
struct DirtyPngHdrT
structure to represent a parsed png
Macros
#define DIRTYPNG_ERR_NONE (0)
#define DIRTYPNG_ERR_TOOSHORT (-1)
#define DIRTYPNG_ERR_BADCRC (-2)
#define DIRTYPNG_ERR_BADTYPE (-3)
#define DIRTYPNG_ERR_BADCOLOR (-4)
#define DIRTYPNG_ERR_BADDEPTH (-5)
#define DIRTYPNG_ERR_BADCOMPR (-6)
#define DIRTYPNG_ERR_BADFILTR (-7)
#define DIRTYPNG_ERR_BADINTRL (-8)
#define DIRTYPNG_ERR_ALLOCFAIL (-9)
#define DIRTYPNG_ERR_TYPEMISS (-10)
#define DIRTYPNG_ERR_BADORDER (-11)
#define DIRTYPNG_ERR_TYPEDUPL (-12)
#define DIRTYPNG_ERR_UNKNCRIT (-13)
#define DIRTYPNG_ERR_BADCM (-14)
#define DIRTYPNG_ERR_BADCI (-15)
#define DIRTYPNG_ERR_BADFLG (-16)
#define DIRTYPNG_ERR_FDICTSET (-17)
#define DIRTYPNG_ERR_BADBTYPE (-18)
#define DIRTYPNG_ERR_NOBLKEND (-19)
#define DIRTYPNG_ERR_BADBLKLEN (-20)
#define DIRTYPNG_ERR_MAXCODES (-21)
#define DIRTYPNG_ERR_NOCODES (-22)
#define DIRTYPNG_ERR_BADCODE (-23)
#define DIRTYPNG_ERR_INVFILE (-24)
#define DIRTYPNG_ERR_UNKNOWN (-25)
Typedefs
typedef struct DirtyPngStateT DirtyPngStateT
typedef struct DirtyPngHdrT DirtyPngHdrT
structure to represent a parsed png
Functions
DIRTYCODE_API DirtyPngStateT * DirtyPngCreate (void)
Create the DirtyPng module state.
DIRTYCODE_API void DirtyPngDestroy (DirtyPngStateT *pState)
Destroy the DirtyPng module.
DIRTYCODE_API int32_t DirtyPngIdentify (const uint8_t *pImageData, uint32_t uImageLen)
Identify if input image is a PNG image.
DIRTYCODE_API int32_t DirtyPngParse (DirtyPngStateT *pState, DirtyPngHdrT *pPngHdr, const uint8_t *pImageData, const uint8_t *pImageEnd)
Parse PNG header.
DIRTYCODE_API int32_t DirtyPngDecodeImage (DirtyPngStateT *pState, DirtyPngHdrT *pPngHdr, uint8_t *pImageData, int32_t iBufWidth, int32_t iBufHeight)
Decode a PNG image into an 8bit paletteized bitmap.
Detailed Description
Macro Definition Documentation
#define DIRTYPNG_ERR_ALLOCFAIL (-9)
Referenced by DirtyPngDecodeImage().
#define DIRTYPNG_ERR_BADBLKLEN (-20)
#define DIRTYPNG_ERR_BADBTYPE (-18)
#define DIRTYPNG_ERR_BADCI (-15)
#define DIRTYPNG_ERR_BADCM (-14)
#define DIRTYPNG_ERR_BADCODE (-23)
#define DIRTYPNG_ERR_BADCOLOR (-4)
#define DIRTYPNG_ERR_BADCOMPR (-6)
#define DIRTYPNG_ERR_BADCRC (-2)
#define DIRTYPNG_ERR_BADDEPTH (-5)
#define DIRTYPNG_ERR_BADFILTR (-7)
#define DIRTYPNG_ERR_BADFLG (-16)
#define DIRTYPNG_ERR_BADINTRL (-8)
#define DIRTYPNG_ERR_BADORDER (-11)
#define DIRTYPNG_ERR_BADTYPE (-3)
#define DIRTYPNG_ERR_FDICTSET (-17)
#define DIRTYPNG_ERR_INVFILE (-24)
#define DIRTYPNG_ERR_MAXCODES (-21)
#define DIRTYPNG_ERR_NOBLKEND (-19)
#define DIRTYPNG_ERR_NOCODES (-22)
#define DIRTYPNG_ERR_NONE (0)
Referenced by DirtyGraphDecodeHeader(), and DirtyPngDecodeImage().
#define DIRTYPNG_ERR_TOOSHORT (-1)
#define DIRTYPNG_ERR_TYPEDUPL (-12)
#define DIRTYPNG_ERR_TYPEMISS (-10)
#define DIRTYPNG_ERR_UNKNCRIT (-13)
#define DIRTYPNG_ERR_UNKNOWN (-25)
Typedef Documentation
typedef struct DirtyPngHdrT DirtyPngHdrT
structure to represent a parsed png
typedef struct DirtyPngStateT DirtyPngStateT
Function Documentation
DIRTYCODE_API DirtyPngStateT* DirtyPngCreate (void)
Create the DirtyPng module state.
Returns
DirtyPngStateT * - pointer to new ref, or NULL if error
Version
02/07/2007 (cadam)
References DirtyMemAlloc(), DirtyMemGroupQuery(), DIRTYPNG_MEMID, DirtyPngStateT::iMemGroup, NetPrintf, and DirtyPngStateT::pMemGroupUserData.
Referenced by DirtyGraphCreate().
DIRTYCODE_API int32_t DirtyPngDecodeImage (DirtyPngStateT * pState, DirtyPngHdrT * pPngHdr, uint8_t * pImageData, int32_t iBufWidth, int32_t iBufHeight)
Decode a PNG image into an 8bit paletteized bitmap.
Parameters
*pState - pointer to the module state
*pPngHdr - pointer to header describing png to decode
*pImageData - [out] pointer to buffer to write decoded image data to
iBufWidth - width of output buffer
iBufHeight - height of output buffer
Returns
int32_t - positive=number of bytes decoded, negative=error
Version
05/01/2007 (cadam)
References DirtyMemAlloc(), DirtyMemFree(), DIRTYPNG_ERR_ALLOCFAIL, DIRTYPNG_ERR_NONE, DIRTYPNG_MEMID, FALSE, DirtyPngHdrT::iBitDepth, DirtyPngStateT::iMemGroup, NetPrintf, DirtyPngStateT::pCurrScanline, DirtyPngStateT::pImageBuf, DirtyPngStateT::pMemGroupUserData, DirtyPngStateT::pPrevScanline, DirtyPngStateT::pScanlines, TRUE, DirtyPngStateT::uBType, DirtyPngStateT::uBufHeight, DirtyPngStateT::uBufWidth, DirtyPngStateT::uPixelWidth, DirtyPngStateT::uScanlineWidth, and DirtyPngHdrT::uWidth.
Referenced by DirtyGraphDecodeImage().
DIRTYCODE_API void DirtyPngDestroy (DirtyPngStateT * pState)
Destroy the DirtyPng module.
Parameters
*pState - pointer to module state
Version
05/01/2007 (cadam)
References DirtyMemFree(), DIRTYPNG_MEMID, DirtyPngStateT::iMemGroup, and DirtyPngStateT::pMemGroupUserData.
Referenced by DirtyGraphDestroy().
DIRTYCODE_API int32_t DirtyPngIdentify (const uint8_t * pImageData, uint32_t uImageLen)
Identify if input image is a PNG image.
Parameters
*pImageData - pointer to image data
uImageLen - size of image data
Returns
int32_t - TRUE if a PNG, else FALSE
Version
02/05/2007 (cadam)
References FALSE, SIGNATURE_LEN, and TRUE.
Referenced by DirtyGraphDecodeHeader().
DIRTYCODE_API int32_t DirtyPngParse (DirtyPngStateT * pState, DirtyPngHdrT * pPngHdr, const uint8_t * pPngData, const uint8_t * pPngEnd)
Parse PNG header.
Parameters
*pState - pointer to the module state
*pPngHdr - [out] pointer to PNG header to fill in
*pPngData - pointer to PNG data
*pPngEnd - pointer past the end of PNG data
Version
02/06/2007 (cadam)
Referenced by DirtyGraphDecodeHeader().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:49