DirtySock: CryptArc4
CryptArc4
Crypt
Data Structures
struct CryptArc4T
all fields are PRIVATE
Macros
#define CryptArc4StringEncryptStatic(_pStr, _iStrSize, _pKey, _iKeySize, _pStrSrc) CryptArc4StringEncryptStaticCode(_pStr, _iStrSize, _pKey, _iKeySize, NULL)
Typedefs
typedef struct CryptArc4T CryptArc4T
Functions
DIRTYCODE_API void CryptArc4Init (CryptArc4T *pState, const unsigned char *pKeyBuf, int32_t iKeyLen, int32_t iIter)
DIRTYCODE_API void CryptArc4Apply (CryptArc4T *pState, unsigned char *pBuffer, int32_t iLength)
DIRTYCODE_API void CryptArc4Advance (CryptArc4T *pState, int32_t iLength)
Advance the cipher state with by iLength bytes.
DIRTYCODE_API void CryptArc4StringEncrypt (char *pDst, int32_t iLen, const char *pSrc, const uint8_t *pKey, int32_t iKey, int32_t iIter)
Easy way to encode an asciiz string. The resulting string is iLen chars of visible ascii characters. String characters must fall in the range of 32 to 127 to be considered valid.
DIRTYCODE_API void CryptArc4StringDecrypt (char *pDst, int32_t iLen, const char *pSrc, const uint8_t *pKey, int32_t iKey, int32_t iIter)
Decode an asciiz string encoded with CryptArc4StringEncrypt.
DIRTYCODE_API int32_t CryptArc4StringEncryptStaticCode (char *pStr, int32_t iStrSize, const uint8_t *pKey, int32_t iKeySize, const char *pStrSrc)
This function decrypts an encrypted key/encoded string pair into the source plaintext string. It also accepts the plaintext string as an argument to verify that the source plaintext string matches the resulting decrypted string. If there is a mismatch updated key and encoded string data is printed in c-style array form and an error is returned. The source plaintext string parameter is only referenced in debug builds to prevent the plaintext string from leaking into the release binary. The CryptArc4StringEncryptStatic() macro wrapper should always be used to call this function, and the plaintext string itself should be defined via the preprocessor, to prevent the plaintext string from leaking into the release binary.
Detailed Description
Macro Definition Documentation
#define CryptArc4StringEncryptStatic (_pStr, _iStrSize, _pKey, _iKeySize, _pStrSrc) CryptArc4StringEncryptStaticCode(_pStr, _iStrSize, _pKey, _iKeySize, NULL)
Typedef Documentation
typedef struct CryptArc4T CryptArc4T
Function Documentation
DIRTYCODE_API void CryptArc4Advance (CryptArc4T * pState, int32_t iLength)
Advance the cipher state with by iLength bytes.
Parameters
*pState - module state
iLength - length to advance
Version
12/06/2005 (jbrookes)
References CryptArc4T::state, CryptArc4T::swap, and CryptArc4T::walk.
Referenced by CryptArc4Init(), and ProtoTunnelFree2().
DIRTYCODE_API void CryptArc4Apply (CryptArc4T * pState, unsigned char * pBuffer, int32_t iLength)
Referenced by CryptStp1DecryptData(), CryptStp1EncryptData(), CryptStp1MakeWallet(), CryptStp1UseTicket(), and ProtoTunnelAlloc().
DIRTYCODE_API void CryptArc4Init (CryptArc4T * pState, const unsigned char * pKeyBuf, int32_t iKeyLen, int32_t iIter)
Referenced by CryptStp1MakeWallet(), CryptStp1UseSecret(), CryptStp1UseTicket(), ProtoTunnelAlloc(), and ProtoTunnelFree2().
DIRTYCODE_API void CryptArc4StringDecrypt (char * pDst, int32_t iLen, const char * pSrc, const uint8_t * pKey, int32_t iKey, int32_t iIter)
Decode an asciiz string encoded with CryptArc4StringEncrypt.
Parameters
*pDst - pointer to output string
iLen - length of output string
*pSrc - pointer to source string (asciiz)
*pKey - key to decrypt with
iKey - length of key (-1=key is asciiz)
iIter - number of initialization iterations
Version
01/10/2013 (jbrookes) Based on CryptSSC2 by GWS
References CryptArc4Apply(), and CryptArc4Init().
DIRTYCODE_API void CryptArc4StringEncrypt (char * pDst, int32_t iLen, const char * pSrc, const uint8_t * pKey, int32_t iKey, int32_t iIter)
Easy way to encode an asciiz string. The resulting string is iLen chars of visible ascii characters. String characters must fall in the range of 32 to 127 to be considered valid.
Parameters
*pDst - pointer to output string
iLen - length of output string
*pSrc - pointer to source string (asciiz)
*pKey - key to encrypt with
iKey - length of key (-1=key is asciiz)
iIter - number of initialization iterations
Version
01/10/2013 (jbrookes) Based on CryptSSC2 by GWS
References CryptArc4Apply(), CryptArc4Init(), CryptRandGet(), FALSE, NULL, and TRUE.
DIRTYCODE_API int32_t CryptArc4StringEncryptStaticCode (char * pStr, int32_t iStrSize, const uint8_t * pKey, int32_t iKeySize, const char * pStrSrc)
This function decrypts an encrypted key/encoded string pair into the source plaintext string. It also accepts the plaintext string as an argument to verify that the source plaintext string matches the resulting decrypted string. If there is a mismatch updated key and encoded string data is printed in c-style array form and an error is returned. The source plaintext string parameter is only referenced in debug builds to prevent the plaintext string from leaking into the release binary. The CryptArc4StringEncryptStatic() macro wrapper should always be used to call this function, and the plaintext string itself should be defined via the preprocessor, to prevent the plaintext string from leaking into the release binary.
Parameters
*pStr - [in/out] pointer to encrypted string, and output buffer for decrypted string
iStrSize - length of string buffer
*pKey - key to decrypt with
iKeySize - length of key
*pStrSrc - decrypted key (debug only)
Returns
int32_t - zero=success, negative means the decrypted string does not match the plaintext string (debug only)
Version
06/05/2014 (jbrookes)
References CryptArc4Apply(), CryptArc4Init(), CryptRandGet(), ds_strnzcpy(), NetPrintArray, NetPrintf, and NULL.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:20