DirtySock: MurmurHash3
MurmurHash3
Util
Data Structures
struct MurmurHash3T
Macros
#define MURMURHASH_HASHSIZE (16)
Typedefs
typedef struct MurmurHash3T MurmurHash3T
Functions
DIRTYCODE_API void MurmurHash3Init (MurmurHash3T *pContext)
Init the MurmurHash3 context.
DIRTYCODE_API void MurmurHash3Init2 (MurmurHash3T *pContext, int32_t iHashSize)
Init the MurmurHash3 context, with hash size.
DIRTYCODE_API void MurmurHash3Update (MurmurHash3T *pContext, const void *pBuffer, int32_t iLength)
Add data to the MurmurHash3 context (hash the data)
DIRTYCODE_API void MurmurHash3Final (MurmurHash3T *pContext, void *pBuffer, int32_t iLength)
Convert MurmurHash3 state into final output form.
DIRTYCODE_API void MurmurHash3 (void *_pOutput, int32_t iOutLen, const void *_pInput, int32_t iInpLen, const void *pKey, int32_t iKeyLen)
Generate 128-bit MurmurHash3 of specified input data.
Detailed Description
Macro Definition Documentation
#define MURMURHASH_HASHSIZE (16)
Typedef Documentation
typedef struct MurmurHash3T MurmurHash3T
Function Documentation
DIRTYCODE_API void MurmurHash3 (void * _pOutput, int32_t iOutLen, const void * _pInput, int32_t iInpLen, const void * pKey, int32_t iKeyLen)
Generate 128-bit MurmurHash3 of specified input data.
Parameters
*_pOutput - [out] buffer to hold output
iOutLen - length of output buffer
*_pInput - input data to be hashed
iInpLen - length of input
*pKey - key to init hash
iKeyLen - length of key (must be 16)
Todo:
Support key lengths other than 16
Version
03/07/2014 (jbrookes)
References MURMURHASH3_C1, MURMURHASH3_C2, and ROTL64.
DIRTYCODE_API void MurmurHash3Final (MurmurHash3T * pContext, void * pBuffer, int32_t iLength)
Convert MurmurHash3 state into final output form.
Parameters
*pContext - hash context
*pBuffer - [out] buffer to hold output
iLength - length of output buffer
Version
03/07/2014 (jbrookes)
References MurmurHash3T::aData, MurmurHash3T::aState, and MurmurHash3T::iCount.
DIRTYCODE_API void MurmurHash3Init (MurmurHash3T * pContext)
Init the MurmurHash3 context.
Parameters
*pContext - hash context
Version
03/07/2014 (jbrookes)
References MurmurHash3T::aState.
Referenced by MurmurHash3Init2().
DIRTYCODE_API void MurmurHash3Init2 (MurmurHash3T * pContext, int32_t iHashSize)
Init the MurmurHash3 context, with hash size.
Parameters
*pContext - hash context
iHashSize - hash size (may be 32 or 128)
Version
03/07/2014 (jbrookes)
References MurmurHash3Init().
DIRTYCODE_API void MurmurHash3Update (MurmurHash3T * pContext, const void * pBuffer, int32_t iLength)
Add data to the MurmurHash3 context (hash the data)
Parameters
*pContext - hash context
*pBuffer - input data to hash
iLength - length of data to hash
Version
03/07/2014 (jbrookes)
References MurmurHash3T::aData, MurmurHash3T::aState, ds_memcpy(), ds_memcpy_s(), MurmurHash3T::iCount, MURMURHASH3_C1, MURMURHASH3_C2, and ROTL64.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:21