DirtySock: voippriv.c File Reference
voippriv.c File Reference
Private functions for VoIP module use.
#include "DirtySDK/platform.h"
#include "DirtySDK/voip/voipdef.h"
#include "voippriv.h"
Functions
void VoipMemGroupQuery (int32_t *pMemGroup, void **ppMemGroupUserData)
Get VoIP mem group data.
void VoipMemGroupSet (int32_t iMemGroup, void *pMemGroupUserData)
Set VoIP mem group data.
Detailed Description
Private functions for VoIP module use.
Attention
Copyright (c) Electronic Arts 2008. ALL RIGHTS RESERVED.
Version
1.0 11/26/2008 (mclouatre) First Version
Function Documentation
void VoipMemGroupQuery (int32_t * pMemGroup, void ** ppMemGroupUserData)
Get VoIP mem group data.
Parameters
*pMemGroup - [OUT param] pointer to variable to be filled with mem group id
**ppMemGroupUserData - [OUT param] pointer to variable to be filled with pointer to user data
Returns
None.
Version
1.0 11/11/2005 (jbrookes) First Version
1.1 11/18/2008 (mclouatre) returned values now passed in [OUT] parameters
Referenced by VoipCommonShutdown(), VoipCommonStatus(), VoipConnectionShutdown(), VoipConnectionStartup(), VoipHeadsetCreate(), and VoipHeadsetDestroy().
void VoipMemGroupSet (int32_t iMemGroup, void * pMemGroupUserData)
Set VoIP mem group data.
Parameters
iMemGroup - mem group to set
*pMemGroupUserData - user data associated with mem group
Returns
None.
Version
1.0 11/11/2005 (jbrookes) First Version
1.1 11/18/2008 (mclouatre) Adding second parameter (user data)
Referenced by VoipCommonStartup().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:20