DirtySock: CryptRand
CryptRand
Crypt
Functions
DIRTYCODE_API void CryptRandInit (void)
Initialize CryptRand module.
DIRTYCODE_API void CryptRandShutdown (void)
Shut down the CryptRand module.
DIRTYCODE_API void CryptRandGet (uint8_t *pBuffer, int32_t iBufSize)
Get random data.
Detailed Description
Function Documentation
DIRTYCODE_API void CryptRandGet (uint8_t * pBuffer, int32_t iBufSize)
Get random data.
Version
12/05/2012 (jbrookes)
References DirtyErrGetName(), NetPrintf, and NetPrintMem.
Referenced by CryptArc4StringEncrypt(), CryptArc4StringEncryptStaticCode(), and CryptRSAInitMaster().
DIRTYCODE_API void CryptRandInit (void)
Initialize CryptRand module.
Version
12/05/2012 (jbrookes)
References DirtyErrGetName(), FALSE, NetPrintf, NULL, and TRUE.
Referenced by ProtoSSLStartup().
DIRTYCODE_API void CryptRandShutdown (void)
Shut down the CryptRand module.
Version
12/05/2012 (jbrookes)
References FALSE.
Referenced by ProtoSSLShutdown().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:20