DirtySock: dirtysessionmanagerxenon.c File Reference
dirtysessionmanagerxenon.c File Reference
This module encapsulates the Xenon functions required to resolve an XUID into a registered secure address, to enable a secure connection to be established between two Xenons. Like the Xbox implementations of DirtySessionManager, use of this module (or something performing the same functionality) is required to be able to connect two or more Xenons in secure mode.
#include <xtl.h>
#include <xonline.h>
#include <stdio.h>
#include "DirtySDK/dirtysock.h"
#include "DirtySDK/dirtysock/dirtyaddr.h"
#include "DirtySDK/dirtysock/dirtymem.h"
#include "DirtySDK/dirtysock/dirtyerr.h"
#include "DirtySDK/dirtysock/netconn.h"
#include "DirtySDK/util/binary7.h"
#include "DirtySDK/util/utf8.h"
#include "DirtySDK/dirtysock/dirtysessionmanager.h"
Data Structures
struct DirtySessionManagerOperation
struct DirtySessionManagerRefT
internal module state
Macros
#define DIRTYSESSIONMANAGER_SESSIONFLAGS_DEFAULT
#define DIRTYSESSIONMANAGER_MAXPUBLIC_DEFAULT (2)
#define DIRTYSESSIONMANAGER_MAXPRIVATE_DEFAULT (0)
#define DIRTYSESSIONMANAGER_MAX_GAMER_COUNT (4)
#define DIRTYSESSIONMANAGER_ARBITRATIONTIMER (1000)
#define DIRTYSESSIONMANAGER_MAX_OPERATIONS (64)
Typedefs
typedef struct
DirtySessionManagerOperation DirtySessionManagerOperation
Enumerations
enum SessMgrStateE {
ST_SESSMGR_CREA,
ST_SESSMGR_MODI,
ST_SESSMGR_JOIN_REM,
ST_SESSMGR_LEAV_REM,
ST_SESSMGR_INVT,
ST_SESSMGR_ARBI_SIZE,
ST_SESSMGR_ARBI,
ST_SESSMGR_STRT,
ST_SESSMGR_STAT,
ST_SESSMGR_MIGR_HOSTING,
ST_SESSMGR_MIGR_NOTHOSTING,
ST_SESSMGR_STOP,
ST_SESSMGR_DELE,
ST_SESSMGR_MAX
}
Functions
int32_t DirtySessionManagerCreateSess (DirtySessionManagerRefT *pRef, uint32_t bRanked, uint32_t *uUserFlags, const char *pSession, DirtyAddrT *pLocalAddrs)
Create a Xenon Live game session.
void DirtySessionManagerEncodeSession (char *pBuffer, int32_t iBufSize, const void *pSessionInfo0)
Encode session variables (host address, session key, and session ID) into a binary7 string.
void DirtySessionManagerDecodeSession (void *pSessionInfo0, const char *pBuffer)
Decode session variables (host address, session key, and session ID) from a binary7 string.
void DirtySessionManagerUpdate (DirtySessionManagerRefT *pRef)
Update module state.
int32_t DirtySessionManagerControl (DirtySessionManagerRefT *pRef, int32_t iControl, int32_t iValue, int32_t iValue2, void *pValue)
DirtySessionManager control function.
int32_t DirtySessionManagerStatus2 (DirtySessionManagerRefT *pRef, int32_t iSelect, int32_t iValue, int32_t iValue2, int32_t iValue3, void *pBuf, int32_t iBufSize)
Return module status based on input selector, passes through to DirtySessionManagerStatus.
int32_t DirtySessionManagerStatus (DirtySessionManagerRefT *pRef, int32_t iSelect, void *pBuf, int32_t iBufSize)
Return module status based on input selector.
int32_t DirtySessionManagerGetSecureIp (DirtySessionManagerRefT *pRef, int32_t *pAddr, const char *pMachineAddr)
Returns TRUE and fills in secure address address if session manager has finished operation successfully.
void DirtySessionManagerConnect (DirtySessionManagerRefT *pRef, const char **pSessID, uint32_t *uSlot, uint32_t uCount)
Connects one or many player(s) to a given game.
DirtySessionManagerRefT * DirtySessionManagerCreate (DirtyAddrT *pHostAddr, DirtyAddrT *pLocalAddrUnused)
Allocate module state and prepare for use.
void DirtySessionManagerDestroy (DirtySessionManagerRefT *pRef)
Destroy the module and release its state.
Detailed Description
This module encapsulates the Xenon functions required to resolve an XUID into a registered secure address, to enable a secure connection to be established between two Xenons. Like the Xbox implementations of DirtySessionManager, use of this module (or something performing the same functionality) is required to be able to connect two or more Xenons in secure mode.
In addition, DirtySessionManager encapsulates use of the XSession API for setting up Xenon sessions with peers.
Attention
Copyright (c) / Electronic Arts 2005-2007. ALL RIGHTS RESERVED.
Version
1.0 05/03/2005 (jbrookes) First Xenon Version
2.0 11/04/2007 (jbrookes) Removed from ProtoMangle namespace, cleanup
2.1 07/06/2009 (mclouatre) Corrected implementation of cancellation of overlapped operations
2.2 29/09/2009 (mclouatre) Refactored to have all XSession calls perform from a dedicated thread
3.0 29/01/2011 (jrainy) Rewritten
Macro Definition Documentation
#define DIRTYSESSIONMANAGER_ARBITRATIONTIMER (1000)
Referenced by DirtySessionManagerUpdate().
#define DIRTYSESSIONMANAGER_MAX_GAMER_COUNT (4)
Referenced by DirtySessionManagerUpdate().
#define DIRTYSESSIONMANAGER_MAX_OPERATIONS (64)
#define DIRTYSESSIONMANAGER_MAXPRIVATE_DEFAULT (0)
Referenced by DirtySessionManagerCreate().
#define DIRTYSESSIONMANAGER_MAXPUBLIC_DEFAULT (2)
Referenced by DirtySessionManagerCreate().
#define DIRTYSESSIONMANAGER_SESSIONFLAGS_DEFAULT
Value:
(XSESSION_CREATE_USES_PRESENCE |                 \
    XSESSION_CREATE_USES_STATS |                    \
    XSESSION_CREATE_USES_MATCHMAKING |              \
    XSESSION_CREATE_USES_PEER_NETWORK |             \
    XSESSION_CREATE_JOIN_IN_PROGRESS_DISABLED)
Referenced by DirtySessionManagerCreate().
Typedef Documentation
typedef struct DirtySessionManagerOperation DirtySessionManagerOperation
Enumeration Type Documentation
enum SessMgrStateE
Enumerator
ST_SESSMGR_CREA
waiting for session creation completion
ST_SESSMGR_MODI
modify session flags
ST_SESSMGR_JOIN_REM
waiting for session join remote completion
ST_SESSMGR_LEAV_REM
waiting for session leave remote completion
ST_SESSMGR_INVT
inviting someone
ST_SESSMGR_ARBI_SIZE
waiting for completion of arbitration register
ST_SESSMGR_ARBI
waiting for completion of arbitration register
ST_SESSMGR_STRT
starting session
ST_SESSMGR_STAT
writing stats
ST_SESSMGR_MIGR_HOSTING
migrate the local user to become the new xsession host
ST_SESSMGR_MIGR_NOTHOSTING
migrate to the new xsession host (not hosting locally)
ST_SESSMGR_STOP
ending session
ST_SESSMGR_DELE
deleting session
ST_SESSMGR_MAX
Function Documentation
int32_t DirtySessionManagerControl (DirtySessionManagerRefT * pRef, int32_t iControl, int32_t iValue, int32_t iValue2, void * pValue)
DirtySessionManager control function.
Parameters
*pRef - module ref
iControl - control selector
iValue - selector specific
iValue2 - selector specific
*pValue - selector specific
Returns
int32_t - 0=success; negative=error
Note
iControl can be one of the following:
        'dele' - iValue of 1 means terminal.
        'pres' - add/remove presence to/from session creation flags
Version
01/17/2011 (jrainy)
References Binary7Decode(), DirtyAddrToHostAddr(), ds_snzprintf(), FALSE, NETCONN_MAXLOCALUSERS, NetPrintf, NetPrintMem, TRUE, and Utf8DecodeToUCS2().
int32_t DirtySessionManagerGetSecureIp (DirtySessionManagerRefT * pRef, int32_t * pAddr, const char * pMachineAddr)
Returns TRUE and fills in secure address address if session manager has finished operation successfully.
Parameters
*pRef - module state
*pAddr - storage for secure address (if result code is positive)
*pMachineAddr - machine address
Returns
int32_t - positive=success, negative=failure
Version
01/17/2011 (jrainy)
References DirtyAddrGetInfoXenon(), DirtySessionManagerRefT::iSessionCreationFlags, NetPrintf, NULL, DirtySessionManagerRefT::SessionInfo, and SocketHtonl().
Referenced by ConnApiXenonSessionManagerGetSecureIp().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:55