DirtySock: QosApi
QosApi
Misc
Data Structures
struct _QosInfoT
QoS probe result information.
struct _QosApiCBInfoT
Qos callback information.
Macros
#define QOSAPI_STATFL_NONE (0x0000)
QoS Status flags.
#define QOSAPI_STATFL_COMPLETE (0x0001)
operation complete
#define QOSAPI_STATFL_PART_COMPLETE (0x0002)
half responses received
#define QOSAPI_STATFL_DATA_RECEIVED (0x0004)
title data received
#define QOSAPI_STATFL_DISABLED (0x0008)
"go away" received
#define QOSAPI_STATFL_CONTACTED (0x0010)
target contacted
#define QOSAPI_STATFL_TIMEDOUT (0x0020)
request timed out
#define QOSAPI_STATFL_FAILED (0x0040)
request failed
#define QOSAPI_STATUS_SUCCESS (1)
Qos Status Code.
#define QOSAPI_STATUS_UNSET (0)
un-initialized value
#define QOSAPI_STATUS_INIT (-1)
initialized, not no qos action was taken
#define QOSAPI_STATUS_USER_INIT (-2)
initialized, outside of qosapi, likely blaze
#define QOSAPI_STATUS_PENDING (-3)
qos operations were in progress
#define QOSAPI_STATUS_HTTP_PARSE_RESPONSE_FAILED (-4)
received http response but failed to parse it
#define QOSAPI_STATUS_NAME_RESOLUTION_FAILED (-5)
failed resolving dns
#define QOSAPI_STATUS_OPERATION_TIMEOUT (-6)
operation timed out
Typedefs
typedef enum QosApiRequestTypeE QosApiRequestTypeE
QOS services can provide the following tests.
typedef enum _QosApiNatTypeE QosApiNatTypeE
known NAT types
typedef enum _QosApiCBTypeE QosApiCBTypeE
callback types
typedef struct _QosInfoT QosInfoT
QoS probe result information.
typedef struct _QosApiCBInfoT QosApiCBInfoT
Qos callback information.
typedef struct QosApiRefT QosApiRefT
opaque module ref
typedef void(QosApiCallbackT)(QosApiRefT *pQosApi, QosApiCBInfoT *pCBInfo, QosApiCBTypeE eCBType, void *pUserData)
event callback function prototype
Enumerations
enum QosApiRequestTypeE {
QOSAPI_REQUEST_LATENCY = 1,
QOSAPI_REQUEST_BANDWIDTH = 2,
QOSAPI_REQUEST_FIREWALL = 3
}
QOS services can provide the following tests.
enum _QosApiNatTypeE {
QOSAPI_NAT_UNKNOWN,
QOSAPI_NAT_OPEN,
QOSAPI_NAT_MODERATE,
QOSAPI_NAT_STRICT_SEQUENTIAL,
QOSAPI_NAT_STRICT,
QOSAPI_NAT_PENDING,
QOSAPI_NUMNATTYPES
}
known NAT types
enum _QosApiCBTypeE {
QOSAPI_CBTYPE_LATENCY,
QOSAPI_CBTYPE_BANDWIDTH,
QOSAPI_CBTYPE_NAT,
QOSAPI_CBTYPE_X360_STATUS,
QOSAPI_NUMCBTYPES
}
callback types
Functions
DIRTYCODE_API QosApiRefT * QosApiCreate (QosApiCallbackT *pCallback, void *pUserData, uint16_t uListenPort)
Create the QosApi module.
DIRTYCODE_API uint32_t QosApiServiceRequest (QosApiRefT *pQosApi, const char *pServerAddress, uint16_t uServerPort, QosApiRequestTypeE eRequestType)
Send a QoS request to the QoS service provider.
DIRTYCODE_API int32_t QosApiCancelRequest (QosApiRefT *pQosApi, uint32_t uRequestId)
Cancel the specified QoS request.
DIRTYCODE_API int32_t QosApiControl (QosApiRefT *pQosApi, int32_t iControl, int32_t iValue, void *pValue)
QosApi control function. Different selectors control different behaviors.
DIRTYCODE_API int32_t QosApiStatus (QosApiRefT *pQosApi, int32_t iSelect, int32_t iData, void *pBuf, int32_t iBufSize)
Return quality of service information.
DIRTYCODE_API QosApiNatTypeE QosApiGetNatType (QosApiRefT *pQosApi)
Returns the current NAT information of the client.
DIRTYCODE_API void QosApiDestroy (QosApiRefT *pQosApi)
Destroy the QosApi module.
Detailed Description
Macro Definition Documentation
#define QOSAPI_STATFL_COMPLETE (0x0001)
operation complete
#define QOSAPI_STATFL_CONTACTED (0x0010)
target contacted
#define QOSAPI_STATFL_DATA_RECEIVED (0x0004)
title data received
#define QOSAPI_STATFL_DISABLED (0x0008)
"go away" received
#define QOSAPI_STATFL_FAILED (0x0040)
request failed
Referenced by ProtoPingResponse().
#define QOSAPI_STATFL_NONE (0x0000)
QoS Status flags.
no change in status
#define QOSAPI_STATFL_PART_COMPLETE (0x0002)
half responses received
#define QOSAPI_STATFL_TIMEDOUT (0x0020)
request timed out
#define QOSAPI_STATUS_HTTP_PARSE_RESPONSE_FAILED (-4)
received http response but failed to parse it
#define QOSAPI_STATUS_INIT (-1)
initialized, not no qos action was taken
#define QOSAPI_STATUS_NAME_RESOLUTION_FAILED (-5)
failed resolving dns
#define QOSAPI_STATUS_OPERATION_TIMEOUT (-6)
operation timed out
#define QOSAPI_STATUS_PENDING (-3)
qos operations were in progress
#define QOSAPI_STATUS_SUCCESS (1)
Qos Status Code.
operation complete successfully
#define QOSAPI_STATUS_UNSET (0)
un-initialized value
#define QOSAPI_STATUS_USER_INIT (-2)
initialized, outside of qosapi, likely blaze
Typedef Documentation
typedef void(QosApiCallbackT)(QosApiRefT *pQosApi, QosApiCBInfoT *pCBInfo, QosApiCBTypeE eCBType, void *pUserData)
event callback function prototype
typedef struct _QosApiCBInfoT QosApiCBInfoT
Qos callback information.
typedef enum _QosApiCBTypeE QosApiCBTypeE
callback types
typedef enum _QosApiNatTypeE QosApiNatTypeE
known NAT types
typedef struct QosApiRefT QosApiRefT
opaque module ref
typedef enum QosApiRequestTypeE QosApiRequestTypeE
QOS services can provide the following tests.
typedef struct _QosInfoT QosInfoT
QoS probe result information.
Enumeration Type Documentation
enum _QosApiCBTypeE
callback types
Enumerator
QOSAPI_CBTYPE_LATENCY
QOSAPI_CBTYPE_BANDWIDTH
QOSAPI_CBTYPE_NAT
QOSAPI_CBTYPE_X360_STATUS
QOSAPI_NUMCBTYPES
max number of callback types
enum _QosApiNatTypeE
known NAT types
Enumerator
QOSAPI_NAT_UNKNOWN
QOSAPI_NAT_OPEN
QOSAPI_NAT_MODERATE
QOSAPI_NAT_STRICT_SEQUENTIAL
QOSAPI_NAT_STRICT
QOSAPI_NAT_PENDING
This value does not exist in the server enum, the server should never have this value.
QOSAPI_NUMNATTYPES
max number of nat types
enum QosApiRequestTypeE
QOS services can provide the following tests.
Enumerator
QOSAPI_REQUEST_LATENCY
ping for latency to server
QOSAPI_REQUEST_BANDWIDTH
measure throughput to server
QOSAPI_REQUEST_FIREWALL
calculate firewall/NAT type with server
Function Documentation
DIRTYCODE_API int32_t QosApiCancelRequest (QosApiRefT * pQosApi, uint32_t uRequestId)
Cancel the specified QoS request.
Parameters
*pQosApi - module state
uRequestId - request to cancel
Returns
int32_t - 0 if successful, negative if failure.
Version
04/07/2008 (cadam)
References QosApiRefT::iSpamValue, NetCritEnter(), NetCritLeave(), NetPrintfVerbose, and QosApiRefT::ThreadCrit.
DIRTYCODE_API int32_t QosApiControl (QosApiRefT * pQosApi, int32_t iControl, int32_t iValue, void * pValue)
QosApi control function. Different selectors control different behaviors.
Parameters
*pQosApi - module state
iControl - control selector
iValue - selector specific data
pValue - selector specific data
Returns
int32_t - control specific
Note
iControl can be one of the following:
        'bpco' - if used overrides config from server, this will be the number of bandwidth probes used for tests
        'bpso' - if used overrides config from server, this will be the size of bandwidth probes used for tests
        'cbfp' - set callback function pointer - pValue=pCallback
        'isyt' - sets the maximum number of ms to wait to initially synchronize all latency requests
        'lpco' - if used overrides config from server, this will be the number of latency probes used for tests
        'lprt' - set the port to use for the QoS listen port (must be set before calling listen/request), same as the value passed to QosApiCreate
        'pque' - passed to SocketControl 'pque' if not 0, otherwise the numpackets will be passed to SocketControl 'pque'
        'rbuf' - passed to SocketControl 'rbuf'
        'repc' - sets the number of extra probes sent (in addition to those which received no response) on a re-issue
        'rira' - sets the new re-issue rate of latency requests in ms.
        'sado' - set the override address to send the http requests to when issuing a service request, overrides parameter passed to QosApiServiceRequest
        'salp' - if TRUE use old logic of sending all latency probes at once (default FALSE)
        'sbuf' - passed to SocketControl 'sbuf'
        'spam' - set the verbosity of the module, default 1 (0 errors, 1 debug info, 2 extended debug info, 3 per probe info)
        'sprt' - set the override port to send the http requests to when issuing a service request, overrides parameter passed to QosApiServiceRequest
        'time' - set the current timeout for new requests (milliseconds)
        'tgbp' - sets the minimum number of ms between sending latency probes to the same site.
        'ussl' - if TRUE use https else http for setup communication (defaults TRUE)
Version
04/07/2008 (cadam)
References QosApiRefT::bSendAllLatencyProbesAtOnce, QosApiRefT::bUseHttps, ds_strnzcpy(), QosApiRefT::iBandwidthProbeCountOverride, QosApiRefT::iBandwidthProbeSizeOverride, QosApiRefT::iLatencyProbeCountOverride, QosApiRefT::iServicePortOverride, QosApiRefT::iSpamValue, NetCritEnter(), NetCritLeave(), NetPrintfVerbose, QosApiRefT::pCallback, QOSAPI_MINIMUM_REISSUE_RATE, QOSAPI_MINIMUM_TIMEOUT, QosApiRefT::strTargetAddressOverride, QosApiRefT::ThreadCrit, QosApiRefT::uInitSyncTimeout, QosApiRefT::uListenPort, QosApiRefT::uPacketQueueLengthOverride, QosApiRefT::uReceiveBuffSize, QosApiRefT::uReissueExtraProbeCount, QosApiRefT::uReissueRate, QosApiRefT::uRequestTimeout, QosApiRefT::uSendBuffSize, and QosApiRefT::uTimeGapBetweenProbes.
Referenced by PingManagerCreate(), and ProtoPingControl().
DIRTYCODE_API QosApiRefT* QosApiCreate (QosApiCallbackT * pCallback, void * pUserData, uint16_t uListenPort)
Create the QosApi module.
Parameters
*pCallback - callback function to use when a status change is detected
*pUserData - use data to be set for the callback
uListenPort - set the port incoming probes will go to, pass 0 to use defaults
Returns
QosApiRefT * - state pointer
Version
04/07/2008 (cadam)
References QosApiRefT::bUseHttps, DirtyMemAlloc(), DirtyMemGroupQuery(), QosApiRefT::eQosApiNatType, QosApiRefT::iBandwidthProbeCountOverride, QosApiRefT::iBandwidthProbeSizeOverride, QosApiRefT::iLatencyProbeCountOverride, QosApiRefT::iMemGroup, QosApiRefT::iServicePortOverride, QosApiRefT::iSpamValue, NetConnIdleAdd(), NetCritInit(), NetPrintf, QosApiRefT::pCallback, QosApiRefT::pMemGroupUserData, QosApiRefT::pUserData, QOSAPI_DEFAULT_INIT_SYNC_TIME, QOSAPI_DEFAULT_RECEIVE_BUFF_SIZE, QOSAPI_DEFAULT_REISSUE_EXTRA_PROBES, QOSAPI_DEFAULT_REISSUE_RATE, QOSAPI_DEFAULT_SEND_BUFF_SIZE, QOSAPI_DEFAULT_TIME_GAP_BETWEEN_PROBES, QOSAPI_DEFAULT_TIMEOUT, QOSAPI_DEFAULT_USE_HTTPS, QOSAPI_MEMID, QOSAPI_NAT_PENDING, QosApiRefT::ThreadCrit, QosApiRefT::uCurrentId, QosApiRefT::uInitSyncTimeout, QosApiRefT::uListenPort, QosApiRefT::uReceiveBuffSize, QosApiRefT::uReissueExtraProbeCount, QosApiRefT::uReissueRate, QosApiRefT::uRequestTimeout, QosApiRefT::uSendBuffSize, and QosApiRefT::uTimeGapBetweenProbes.
Referenced by PingManagerCreate(), and ProtoPingControl().
DIRTYCODE_API void QosApiDestroy (QosApiRefT * pQosApi)
Destroy the QosApi module.
Parameters
*pQosApi - module state
Version
04/07/2008 (cadam)
References DirtyMemFree(), QosApiRefT::iMemGroup, NetConnIdleDel(), NetCritEnter(), NetCritKill(), NetCritLeave(), QosApiRefT::pMemGroupUserData, QosApiRefT::pRequestQueue, QosApiRefT::pSocket, QOSAPI_MEMID, SocketClose(), QosApiRefT::ThreadCrit, and QosApiRequestT::uRequestId.
Referenced by PingManagerDestroy(), and ProtoPingDestroy().
DIRTYCODE_API QosApiNatTypeE QosApiGetNatType (QosApiRefT * pQosApi)
Returns the current NAT information of the client.
Parameters
*pQosApi - module state
Returns
QosApiNatTypeE - nat type.
Version
04/07/2008 (cadam)
References QosApiRefT::eQosApiNatType, NetConnStatus(), NetPrintf, QOSAPI_NAT_MODERATE, QOSAPI_NAT_OPEN, QOSAPI_NAT_STRICT, and QOSAPI_NAT_UNKNOWN.
DIRTYCODE_API uint32_t QosApiServiceRequest (QosApiRefT * pQosApi, const char * pServerAddress, uint16_t uServerPort, QosApiRequestTypeE eRequestType)
Send a QoS request to the QoS service provider.
Parameters
*pQosApi - module state
*pServerAddress - address of the server to send http config query to
uServerPort - port to match pServerAddress
eRequestType - Type of request being made
Returns
uint32_t - request id, 0 if failure.
Version
04/07/2008 (cadam)
References QosApiRefT::bUseHttps, ds_snzprintf(), QosApiRefT::iServicePortOverride, NetCritEnter(), NetCritLeave(), NetPrintf, QosApiRequestT::pHttpHandler, QOSAPI_HTTP_MAX_URL_LENGTH, QOSAPI_REQUEST_BANDWIDTH, QOSAPI_REQUEST_FIREWALL, QOSAPI_REQUEST_LATENCY, QosApiRefT::strTargetAddressOverride, QosApiHttpHandlerT::strUrlBasePath, QosApiRefT::ThreadCrit, TRUE, and QosApiRequestT::uRequestId.
Referenced by PingManagerPingServer2().
DIRTYCODE_API int32_t QosApiStatus (QosApiRefT * pQosApi, int32_t iSelect, int32_t iData, void * pBuf, int32_t iBufSize)
Return quality of service information.
Parameters
*pQosApi - module state
iSelect - output selector
iData - selector specific
*pBuf - [out] pointer to output buffer
iBufSize - size of output buffer
Returns
int32_t - selector specific
Note
iSelect can be one of the following:
        'bpco' - get the override value for number of bandwidth probes used in tests (-1 if not used)
        'bpso' - get the override value for size of bandwidth probes used for tests (-1 if not used)
        'clpt' - get the current listen port of the QoS socket
        'extn' - get the external address information of the client for the specified request
        'isyt' - get the maximum number of ms to wait to initially synchronize all latency requests
        'lpco' - get the override used for number of latency probes used for tests (-1 if not used)
        'lprt' - get the port to use for the QoS listen port
        'pque' - get the value passed to SocketControl 'pque' (0 if not used)
        'rbuf' - get the value passed to SocketControl 'rbuf'
        'repc' - get the number of extra probes sent (in addition to those which received no response) on a re-issue
        'requ' - get the information for the specified request
        'rira' - get the new re-issue rate of latency requests in ms.
        'sado' - get the override address to send the http requests to when issuing a service request, overrides parameter passed to QosApiServiceRequest
        'salp' - get if send all latency probes at once is set
        'sbuf' - get the value passed to SocketControl 'sbuf'
        'spam' - get the verbosity of the module
        'sprt' - get the override port to send the http requests to when issuing a service request, overrides parameter passed to QosApiServiceRequest
        'time' - get the current timeout value for QoS requests
        'tgbp' - get the minimum number of ms between sending latency probes to the same site.
        'ussl' - if TRUE use https else http for setup communication
Version
04/07/2008 (cadam)
References QosApiRefT::bSendAllLatencyProbesAtOnce, QosApiRefT::bUseHttps, QosApiRequestT::data, ds_memcpy(), ds_strnzcpy(), QosApiRequestT::eType, QosApiRequestLatencyT::ExternalAddr, QosApiRefT::iBandwidthProbeCountOverride, QosApiRefT::iBandwidthProbeSizeOverride, QosApiRefT::iLatencyProbeCountOverride, QosApiRefT::iServicePortOverride, QosApiRefT::iSpamValue, QosApiRequestT::Latency, NetCritEnter(), NetCritLeave(), NetPrintfVerbose, QOSAPI_REQUEST_LATENCY, QosApiRefT::strTargetAddressOverride, QosApiRefT::ThreadCrit, QosApiRefT::uCurrentListenPort, QosApiRefT::uInitSyncTimeout, QosApiRefT::uListenPort, QosApiRefT::uPacketQueueLengthOverride, QosApiRefT::uReceiveBuffSize, QosApiRefT::uReissueExtraProbeCount, QosApiRefT::uReissueRate, QosApiRefT::uRequestTimeout, QosApiRefT::uSendBuffSize, and QosApiRefT::uTimeGapBetweenProbes.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:49