DirtySock: CryptRSA
CryptRSA
Crypt
Data Structures
struct CryptRSAT
cryptrsa state
Macros
#define UCRYPT_SIZE (4)
#define UCRYPT_BITSHIFT 5
#define UCRYPT_BITSIZE (UCRYPT_SIZE*8)
Typedefs
typedef uint32_t ucrypt_t
typedef uint64_t ucrypt2_t
typedef struct CryptRSAT CryptRSAT
cryptrsa state
Functions
DIRTYCODE_API int32_t CryptRSAInit (CryptRSAT *pState, const uint8_t *pModulus, int32_t iModSize, const uint8_t *pExponent, int32_t iExpSize)
Init RSA state.
DIRTYCODE_API void CryptRSAInitMaster (CryptRSAT *pState, const uint8_t *pMaster, int32_t iMasterLen)
Setup the master shared secret for encryption.
DIRTYCODE_API void CryptRSAInitPrivate (CryptRSAT *pState, const uint8_t *pMaster, int32_t iMasterLen)
Setup the master shared secret for encryption using PKCS1.5.
DIRTYCODE_API void CryptRSAInitSignature (CryptRSAT *pState, const uint8_t *pSig, int32_t iSigLen)
Setup the encrypted signature for decryption.
DIRTYCODE_API int32_t CryptRSAEncrypt (CryptRSAT *pState, int32_t iIter)
Encrypt data.
Detailed Description
Macro Definition Documentation
#define UCRYPT_BITSHIFT 5
#define UCRYPT_BITSIZE (UCRYPT_SIZE*8)
#define UCRYPT_SIZE (4)
Typedef Documentation
typedef struct CryptRSAT CryptRSAT
cryptrsa state
typedef uint64_t ucrypt2_t
typedef uint32_t ucrypt_t
Function Documentation
DIRTYCODE_API int32_t CryptRSAEncrypt (CryptRSAT * pState, int32_t iIter)
Encrypt data.
Parameters
*pState - module state
iIter - number of iterations to execute (zero=do all)
Returns
int32_t - zero=operation complete, else call again
Version
03/05/2003 (jbrookes) Split from protossl
DIRTYCODE_API int32_t CryptRSAInit (CryptRSAT * pState, const uint8_t * pModulus, int32_t iModSize, const uint8_t * pExponent, int32_t iExpSize)
Init RSA state.
Parameters
*pState - module state
*pModulus - crypto modulus
iModSize - size of modulus
*pExponent - crypto exponent
iExpSize - size of exponent
Returns
int32_t - zero for success, negative for error
Note
This module supports a max modulus size of 4096 (iModSize=512) and requires a minimum size of 1024 (iModSize=64). The exponent must be between 1 and 512 bytes in size, inclusive.
Version
03/05/03 (jbrookes) Split from protossl
References CryptRSAT::Accumul, CryptRSAT::bAccumulOne, ds_memcpy(), CryptRSAT::iExpByteIndex, CryptRSAT::iKeyExpSize, CryptRSAT::iKeyModSize, CryptRSAT::iWidth, CryptRSAT::KeyExpData, CryptRSAT::KeyModData, CryptRSAT::Modulus, NetPrintf, and TRUE.
DIRTYCODE_API void CryptRSAInitMaster (CryptRSAT * pState, const uint8_t * pMaster, int32_t iMasterLen)
Setup the master shared secret for encryption.
Parameters
*pState - module state
*pMaster - the master shared secret to encrypt
iMasterLen - the length of the master shared secret
Version
02/07/2014 (jbrookes) Rewritten to use CryptRand
References CryptRandGet(), ds_memcpy(), CryptRSAT::EncryptBlock, CryptRSAT::iKeyModSize, and CryptRSAT::Powerof.
DIRTYCODE_API void CryptRSAInitPrivate (CryptRSAT * pState, const uint8_t * pMaster, int32_t iMasterLen)
Setup the master shared secret for encryption using PKCS1.5.
Parameters
*pState - module state
*pMaster - the master shared secret to encrypt
iMasterLen - the length of the master shared secret
Version
11/03/2013 (jbrookes)
References ds_memcpy(), CryptRSAT::EncryptBlock, CryptRSAT::iKeyModSize, and CryptRSAT::Powerof.
DIRTYCODE_API void CryptRSAInitSignature (CryptRSAT * pState, const uint8_t * pSig, int32_t iSigLen)
Setup the encrypted signature for decryption.
Parameters
*pState - module state
*pSig - the encrypted signature
*iSigLen - the length of the encrypted signature.
Version
03/03/2004 (sbevan)
References ds_memcpy(), CryptRSAT::EncryptBlock, CryptRSAT::iKeyModSize, and CryptRSAT::Powerof.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:42