DirtySock: voipconnection.h File Reference
voipconnection.h File Reference
VoIP virtual connection manager.
#include "voippacket.h"
Data Structures
struct SendAddrFallbackT
struct LinkedReliableDataT
type used to create linked list of reliable data entries
struct VoipConnectionT
connection structure
struct VoipConnectionlistT
connection list
Macros
#define VOIP_MAXSESSIONIDS (8)
maximum number of session IDs per VOIP connection
Typedefs
typedef void(VoipConnectRecvVoiceCbT)(VoipUserT *pRemoteUsers, VoipMicrInfoT *pMicrInfo, uint8_t *pPacketData, void *pUserData)
voice receive callback
typedef void(VoipConnectRegUserCbT)(VoipUserT *pRemoteUser, uint32_t bRegister, void *pUserData)
new remote user register callback
typedef struct SendAddrFallbackT SendAddrFallbackT
typedef struct LinkedReliableDataT LinkedReliableDataT
type used to create linked list of reliable data entries
typedef struct VoipConnectionT VoipConnectionT
connection structure
typedef struct VoipConnectionlistT VoipConnectionlistT
connection list
Functions
int32_t VoipConnectionStartup (VoipConnectionlistT *pConnectionlist, int32_t iMaxPeers)
Startup a connectionlist.
void VoipConnectionSetCallbacks (VoipConnectionlistT *pConnectionlist, VoipConnectRecvVoiceCbT *pVoiceCb, VoipConnectRegUserCbT *pRegUserCb, void *pUserData)
Set required recv voice and reg user callbacks.
void VoipConnectionShutdown (VoipConnectionlistT *pConnectionlist)
Shutdown a connectionlist.
uint8_t VoipConnectionCanAllocate (VoipConnectionlistT *pConnectionlist, int32_t iConnID)
Check whether a given Connection ID can be allocated in this Connection List.
int32_t VoipConnectionStart (VoipConnectionlistT *pConnectionlist, int32_t iConnID, uint32_t uAddr, uint32_t uConnPort, uint32_t uBindPort, uint32_t uClientId, uint32_t uSessionId)
Start a connection to a peer.
void VoipConnectionUpdate (VoipConnectionlistT *pConnectionlist)
Update all connections.
void VoipConnectionStop (VoipConnectionlistT *pConnectionlist, int32_t iConnID, int32_t bSendDiscMsg)
Stop a connection with a peer.
void VoipConnectionRemove (VoipConnectionlistT *pConnectionlist, int32_t iConnID)
Remove specified connection.
int32_t VoipConnectionFlush (VoipConnectionlistT *pConnectionlist, int32_t iConnID)
Send currently queued voice data, if any.
void VoipConnectionSend (VoipConnectionlistT *pConnectionlist, const uint8_t *pVoiceData, int32_t iDataSize, const uint8_t *pMetaData, int32_t iMetaDataSize, uint32_t uLocalIndex, uint8_t uSendSeqn)
Send data to peer.
void VoipConnectionSetSendMask (VoipConnectionlistT *pConnectionlist, uint32_t uConnMask)
Set connections to send to.
void VoipConnectionSetRecvMask (VoipConnectionlistT *pConnectionlist, uint32_t uRecvMask)
Set connections to receive from.
void VoipConnectionRegisterRemoteTalkers (VoipConnectionlistT *pConnectionlist, int32_t iConnID, uint32_t bRegister)
Register/unregister remote users associated with the given connection.
int32_t VoipConnectionAddSessionId (VoipConnectionlistT *pConnectionlist, int32_t iConnId, uint32_t uSessionId)
Add a session ID the set of higher level sessions sharing the specified VoIP connection.
int32_t VoipConnectionDeleteSessionId (VoipConnectionlistT *pConnectionlist, int32_t iConnId, uint32_t uSessionId)
Delete a session ID from the set of sessions sharing this voip connection.
void VoipConnectionReliableBroadcastUser (VoipConnectionlistT *pConnectionlist, uint8_t uLocalUserIndex, uint32_t bParticipating)
Use this function to broadcast local user join-in-progress/leave-in-progress data that needs to be sent reliably on all active connections (or connections in ST_CONN state).
void VoipConnectionReliableBroadcastOpaque (VoipConnectionlistT *pConnectionlist, const uint8_t *pData, uint16_t uDataSize)
Use this function to broadcast opaque data that needs to be sent reliably on all active connections (or connections in ST_CONN state).
Detailed Description
VoIP virtual connection manager.
Attention
Copyright (c) Electronic Arts 2004. ALL RIGHTS RESERVED.
Version
1.0 03/17/2004 (jbrookes) First Version
1.1 12/10/2008 (mclouatre) Added ref count to VOIP connections.
1.2 01/06/2009 (mclouatre) Added field RemoteAddrFallbacks to VoipConnectionT structure. Create related functions
1.3 10/26/2009 (mclouatre) Renamed from xbox/voipconnection.h to xenon/voipconnectionxenon.h
Macro Definition Documentation
#define VOIP_MAXSESSIONIDS (8)
maximum number of session IDs per VOIP connection
Referenced by VoipConnectionAddSessionId(), and VoipConnectionDeleteSessionId().
Typedef Documentation
typedef struct LinkedReliableDataT LinkedReliableDataT
type used to create linked list of reliable data entries
typedef struct SendAddrFallbackT SendAddrFallbackT
typedef struct VoipConnectionlistT VoipConnectionlistT
connection list
typedef struct VoipConnectionT VoipConnectionT
connection structure
typedef void(VoipConnectRecvVoiceCbT)(VoipUserT *pRemoteUsers, VoipMicrInfoT *pMicrInfo, uint8_t *pPacketData, void *pUserData)
voice receive callback
typedef void(VoipConnectRegUserCbT)(VoipUserT *pRemoteUser, uint32_t bRegister, void *pUserData)
new remote user register callback
Function Documentation
int32_t VoipConnectionAddSessionId (VoipConnectionlistT * pConnectionlist, int32_t iConnId, uint32_t uSessionId)
Add a session ID the set of higher level sessions sharing the specified VoIP connection.
Parameters
*pConnectionlist - connectionlist
iConnId - connection ID
uSessionId - session ID to be added
Returns
int32_t - 0 for success, negative for failure
Note
Maintaning a set of session IDs per voip connection is required to support cases where two consoles are involved in a P2P game and a pg simultaneously. Both of these constructs will have a different session ID over the same shared voip connection. Under some specific race conditions affecting the order at which Blaze messages are processed by each game client, it is very possible that the pg session id is setup first on one side and second on the other side thus leading to VOIP connectivity failures if the voip connection construct is not supporting multiple concurrent session IDs.
Version
08/30/2011 (mclouatre)
References VoipConnectionlistT::NetCrit, NetCritEnter(), NetCritLeave(), NetPrintf, VoipConnectionlistT::pConnections, VoipConnectionT::uSessionId, and VOIP_MAXSESSIONIDS.
Referenced by VoipCommonControl(), and VoipConnectionStart().
uint8_t VoipConnectionCanAllocate (VoipConnectionlistT * pConnectionlist, int32_t iConnID)
Check whether a given Connection ID can be allocated in this Connection List.
Parameters
*pConnectionlist - connection list ref
iConnID - connection index
Returns
uint8_t - Whether a connection can be allocated with given ConnID
Version
02/19/2008 (jrainy)
References VoipConnectionT::eState, VoipConnectionlistT::iMaxConnections, and VoipConnectionlistT::pConnections.
Referenced by VoipCommonStatus().
int32_t VoipConnectionDeleteSessionId (VoipConnectionlistT * pConnectionlist, int32_t iConnId, uint32_t uSessionId)
Delete a session ID from the set of sessions sharing this voip connection.
Parameters
*pConnectionlist - connectionlist
iConnId - connection id
uSessionId - session ID to be deleted
Returns
int32_t - 0 for success, negative for failure
Version
08/30/2011 (mclouatre)
References VoipConnectionlistT::NetCrit, NetCritEnter(), NetCritLeave(), NetPrintf, VoipConnectionlistT::pConnections, VoipConnectionT::uSessionId, and VOIP_MAXSESSIONIDS.
Referenced by VoipCommonControl().
int32_t VoipConnectionFlush (VoipConnectionlistT * pConnectionlist, int32_t iConnID)
Send currently queued voice data, if any.
Parameters
*pConnectionlist - connectionlist to send to
iConnID - connection ident of connection to flush
Returns
int32_t - number of voice packets flushed
Note
Currently only useful on Xenon
Version
01/04/2006 (jbrookes)
References VoipConnectionT::eState, VoipMicrPacketT::MicrInfo, NetTick(), VoipConnectionlistT::pConnections, TRUE, VoipMicrInfoT::uNumSubPackets, VoipConnectionlistT::uSendMask, VOIP_MAXLOCALUSERS_EXTENDED, and VoipConnectionT::VoipMicrPacket.
Referenced by VoipCommonControl().
void VoipConnectionRegisterRemoteTalkers (VoipConnectionlistT * pConnectionlist, int32_t iConnID, uint32_t bRegister)
Register/unregister remote users associated with the given connection.
Parameters
*pConnectionlist - connectionlist to send to
iConnID - connection ident of connection to flush
bRegister - if TRUE register talkers, else unregister them
Version
01/04/2006 (jbrookes)
References VoipConnectionlistT::bUpdateMute, VoipConnectionlistT::pCbUserData, VoipConnectionlistT::pConnections, VoipConnectionlistT::pRegUserCb, VoipConnectionT::RemoteUsers, TRUE, VOIP_MAXLOCALUSERS_EXTENDED, and VOIP_NullUser.
Referenced by VoipConnectionRemove().
void VoipConnectionReliableBroadcastOpaque (VoipConnectionlistT * pConnectionlist, const uint8_t * pData, uint16_t uDataSize)
Use this function to broadcast opaque data that needs to be sent reliably on all active connections (or connections in ST_CONN state).
Parameters
*pConnectionlist - connectionlist
*pData - pointer to buffer filled with reliable data to be broadcasted
uDataSize - reliable data size (in bytes)
Version
09/18/2014 (mclouatre)
References ReliableDataT::aData, ds_memcpy_s(), ReliableDataT::info, ReliableDataInfoT::uSize, ReliableDataInfoT::uType, VOIP_CONNID_ALL, and VOIP_RELIABLE_TYPE_OPAQUE.
void VoipConnectionReliableBroadcastUser (VoipConnectionlistT * pConnectionlist, uint8_t uLocalUserIndex, uint32_t bParticipating)
Use this function to broadcast local user join-in-progress/leave-in-progress data that needs to be sent reliably on all active connections (or connections in ST_CONN state).
Parameters
*pConnectionlist - connectionlist
uLocalUserIndex - local user index
bParticipating - TRUE if user joined-in-progress, FALSE if user left-in-progress
Version
09/18/2014 (mclouatre)
References ReliableDataT::aData, ds_memcpy_s(), ReliableDataT::info, VoipConnectionlistT::LocalUsers, ReliableDataInfoT::uSize, ReliableDataInfoT::uType, VOIP_CONNID_ALL, VOIP_RELIABLE_TYPE_USERADD, and VOIP_RELIABLE_TYPE_USERREM.
Referenced by VoipActivateLocalUser().
void VoipConnectionRemove (VoipConnectionlistT * pConnectionlist, int32_t iConnID)
Remove specified connection.
Parameters
*pConnectionlist - connection list ref
iConnID - connection to remove
Version
05/24/2007 (jbrookes)
References NetPrintf, VoipConnectionlistT::uRecvMask, VoipConnectionlistT::uRecvVoice, VoipConnectionlistT::uSendMask, VoipConnectionlistT::uUserRecvMask, VoipConnectionlistT::uUserSendMask, VoipCommonDelMask(), and VoipConnectionRegisterRemoteTalkers().
Referenced by VoipRemove().
void VoipConnectionSend (VoipConnectionlistT * pConnectionlist, const uint8_t * pVoiceData, int32_t iDataSize, const uint8_t * pMetaData, int32_t iMetaDataSize, uint32_t uUserIndex, uint8_t uSendSeqn)
Send data to peer.
Parameters
*pConnectionlist - connectionlist to send to
*pVoiceData - pointer to data to send
iDataSize - size of data to send
*pMetaData - pointer to metadata to be added to voip packet
iMetaDataSize - size of metadata
uUserIndex - local user index
uSendSeqn - seq nb
Version
03/17/2004 (jbrookes)
References VoipMicrPacketT::aData, VoipConnectionlistT::aIsParticipating, VoipConnectionT::aVoiceSendTimer, ds_memcpy(), VoipConnectionT::eState, FALSE, VoipMicrPacketT::Head, VoipConnectionlistT::iMaxConnections, VoipConnectionT::iMaxSubPktSize, VoipConnectionT::iVoipServerConnId, VoipMicrPacketT::MicrInfo, NetPrintf, NetTick(), NetTickDiff, VoipConnectionlistT::pConnections, TRUE, VoipPacketHeadT::uFlags, VoipConnectionlistT::uLastVoiceTime, VoipConnectionlistT::uLocalUserStatus, VoipMicrInfoT::uNumSubPackets, VoipConnectionlistT::uSendMask, VoipMicrInfoT::uSubPacketSize, VoipMicrInfoT::uUserIndex, VOIP_CONNID_ALL, VOIP_CONNID_NONE, VOIP_LOCAL_USER_TALKING, VOIP_MAXLOCALUSERS, VOIP_MAXSUBPKTS_PER_PKT, VOIP_MSPERPACKET, VOIP_PACKET_STATUS_FLAG_METADATA, VOIP_SHARED_USER_INDEX, VoipGetRef(), VoipConnectionT::VoipMicrPacket, and VoipStatus().
void VoipConnectionSetCallbacks (VoipConnectionlistT * pConnectionlist, VoipConnectRecvVoiceCbT * pVoiceCb, VoipConnectRegUserCbT * pRegUserCb, void * pUserData)
Set required recv voice and reg user callbacks.
Parameters
*pConnectionlist - connectionlist to register callbacks for
*pVoiceCb - voice callback to register
*pRegUserCb - user reg callback to register
*pUserData - pointer to user data
Version
03/20/2004 (jbrookes)
References VoipConnectionlistT::pCbUserData, VoipConnectionlistT::pRegUserCb, and VoipConnectionlistT::pVoiceCb.
Referenced by VoipCommonStartup().
void VoipConnectionSetRecvMask (VoipConnectionlistT * pConnectionlist, uint32_t uRecvMask)
Set connections to receive from.
Parameters
*pConnectionlist - connectionlist to send to
uRecvMask - connection receive mask
Version
03/22/2004 (jbrookes)
References VoipConnectionlistT::uRecvMask, and VoipCommonSetMask().
Referenced by VoipCommonUpdateRemoteStatus().
void VoipConnectionSetSendMask (VoipConnectionlistT * pConnectionlist, uint32_t uSendMask)
Set connections to send to.
Parameters
*pConnectionlist - connectionlist to send to
uSendMask - connection send mask
Version
03/22/2004 (jbrookes)
References VoipConnectionlistT::uSendMask, and VoipCommonSetMask().
Referenced by VoipCommonUpdateRemoteStatus().
void VoipConnectionShutdown (VoipConnectionlistT * pConnectionlist)
Shutdown a connectionlist.
Parameters
*pConnectionlist - connectionlist to close
Version
03/20/2004 (jbrookes)
References DirtyMemFree(), VoipConnectionlistT::NetCrit, NetCritKill(), NetPrintf, VoipConnectionlistT::pConnections, VoipConnectionlistT::pSocket, SocketClose(), VOIP_MEMID, and VoipMemGroupQuery().
Referenced by VoipCommonShutdown().
int32_t VoipConnectionStart (VoipConnectionlistT * pConnectionlist, int32_t iConnID, uint32_t uAddr, uint32_t uConnPort, uint32_t uBindPort, uint32_t uClientId, uint32_t uSessionId)
Start a connection to a peer.
Parameters
*pConnectionlist - connection list ref
iConnID - connection index
uAddr - address to connect to
uConnPort - connection port
uBindPort - local bind port
uClientId - id of client to connect to (cannot be 0)
uSessionId - session id (optional)
Returns
int32_t - connection identifier on success, negative=failure
Version
03/18/2004 (jbrookes)
References CALLB_RECV, ds_memcpy_s(), VoipConnectionT::eState, VoipMicrPacketT::Head, VoipConnectionT::iVoipServerConnId, VoipConnectionlistT::NetCrit, NetCritEnter(), NetCritLeave(), NetPrintf, NetTick(), VoipConnectionlistT::pSocket, VoipConnectionT::SendAddr, SockaddrInGetPort, SockaddrInit, SockaddrInSetPort, SOCKERR_NONE, SocketBind(), SocketCallback(), SocketClose(), SocketHtonl(), SocketHtons(), SocketInfo(), SocketNtohl(), SocketNtohs(), SocketOpen(), ST_CONN, VoipConnectionlistT::uBindPort, VoipConnectionlistT::uClientId, VoipConnectionT::uLastRecv, VoipConnectionT::uLocalClientId, VoipConnectionT::uRecvSeqn, VoipConnectionT::uRemoteClientId, VoipConnectionT::uRemoteConnStatus, VoipConnectionT::uRemoteUserStatus, VOIP_ConnID, VOIP_CONNID_NONE, VOIP_IPPROTO, VOIP_MAXLOCALUSERS, VOIP_MAXLOCALUSERS_EXTENDED, VoipConnectionAddSessionId(), and VoipConnectionT::VoipMicrPacket.
Referenced by VoipConnect().
int32_t VoipConnectionStartup (VoipConnectionlistT * pConnectionlist, int32_t iMaxPeers)
Startup a connectionlist.
Parameters
*pConnectionlist - connectionlist to init
iMaxPeers - max number of connections to support
Returns
int32_t - zero=success, negative=error
Version
03/20/2004 (jbrookes)
References DirtyMemAlloc(), VoipConnectionlistT::iDataTimeout, VoipConnectionlistT::iFriendConnId, VoipConnectionlistT::iMaxConnections, VoipConnectionT::iVoipServerConnId, VoipConnectionlistT::NetCrit, NetCritInit(), NetPrintf, VoipConnectionlistT::pConnections, VoipConnectionlistT::uOutSeqNb, VOIP_CONNID_NONE, VOIP_MAXCONNECT, VOIP_MEMID, VOIP_TIMEOUT, and VoipMemGroupQuery().
Referenced by VoipCommonStartup().
void VoipConnectionStop (VoipConnectionlistT * pConnectionlist, int32_t iConnID, int32_t bSendDiscMsg)
Stop a connection with a peer.
Parameters
*pConnectionlist - connection list ref
iConnID - connection to stop, or VOIP_CONNID_ALL to stop all connections
bSendDiscMsg - TRUE - send DISC msg to peer; FALSE - do not send DISC msg to peer
Version
03/18/2004 (jbrookes)
References VoipConnectionlistT::iMaxConnections, NetPrintf, VoipConnectionlistT::pConnections, and VOIP_CONNID_ALL.
Referenced by VoipDisconnect2().
void VoipConnectionUpdate (VoipConnectionlistT * pConnectionlist)
Update all connections.
Parameters
*pConnectionlist - connection list
Version
03/18/2004 (jbrookes)
References VoipConnectionlistT::NetCrit, NetCritEnter(), NetCritLeave(), NetTick(), NetTickDiff, VoipConnectionlistT::pConnections, VoipConnectionlistT::uLastVoiceTime, VoipConnectionlistT::uLocalUserStatus, VoipConnectionlistT::uRecvVoice, VOIP_LOCAL_USER_TALKING, VOIP_MAXLOCALUSERS, and VOIP_TALKTIMEOUT.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:15