DirtySock: VoipGroup
VoipGroup
Voip
Typedefs
typedef enum ConnSharingCbTypeE ConnSharingCbTypeE
callback event types
typedef struct VoipGroupRefT VoipGroupRefT
opaque module ref
typedef void(ConnSharingCallbackT)(VoipGroupRefT *pVoip, ConnSharingCbTypeE eCbType, int32_t iConnId, void *pUserData)
event callback function prototype
Enumerations
enum ConnSharingCbTypeE {
VOIPGROUP_CBTYPE_CONNSUSPEND,
VOIPGROUP_CBTYPE_CONNRESUME
}
callback event types
Functions
DIRTYCODE_API VoipGroupRefT * VoipGroupCreate (void)
allocates a VoipGroup
DIRTYCODE_API void VoipGroupDestroy (VoipGroupRefT *pRef)
Deallocates a VoipGroup.
DIRTYCODE_API void VoipGroupSetEventCallback (VoipGroupRefT *pVoipGroup, VoipCallbackT *pCallback, void *pUserData)
Sets the callback and userdata for the specified group.
DIRTYCODE_API void VoipGroupSetConnSharingEventCallback (VoipGroupRefT *pVoipGroup, ConnSharingCallbackT *pCallback, void *pUserData)
Sets the connection sharing callback and userdata for the specified group.
DIRTYCODE_API int32_t VoipGroupConnect (VoipGroupRefT *pVoipGroup, int32_t iConnID, uint32_t uAddress, uint32_t uManglePort, uint32_t uGamePort, uint32_t uClientID, uint32_t uSessionID)
Set up a connection, using VoipGroup.
DIRTYCODE_API void VoipGroupResume (VoipGroupRefT *pVoipGroup, int32_t iConnId, uint32_t uAddress, uint32_t uManglePort, uint32_t uGamePort, uint32_t uClientId, uint32_t uSessionID)
resume a connection
DIRTYCODE_API void VoipGroupDisconnect (VoipGroupRefT *pVoipGroup, int32_t iConnID)
Teardown a connection, using VoipGroups.
DIRTYCODE_API void VoipGroupSuspend (VoipGroupRefT *pVoipGroup, int32_t iConnId)
suspend a connection
DIRTYCODE_API int32_t VoipGroupMuteByConnId (VoipGroupRefT *pVoipGroup, uint32_t iConnId, uint8_t uMute)
DIRTYCODE_API int32_t VoipGroupMuteByClientId (VoipGroupRefT *pVoipGroup, uint32_t iClientId, uint8_t uMute)
DIRTYCODE_API uint8_t VoipGroupIsMutedByConnId (VoipGroupRefT *pVoipGroup, uint32_t iConnId)
whether a client is muted, by ConnId
DIRTYCODE_API uint8_t VoipGroupIsMutedByClientId (VoipGroupRefT *pVoipGroup, uint32_t iClientId)
whether a client is muted, by ClientId
DIRTYCODE_API int32_t VoipGroupConnStatus (VoipGroupRefT *pVoipGroup, int32_t iConnID)
Passes through to VoipConnRemote, afer adjusting connection ID.
DIRTYCODE_API int32_t VoipGroupRemoteUserStatus (VoipGroupRefT *pVoipGroup, int32_t iConnID, int32_t iRemoteUserIndex)
Passes through to VoipUserRemote, afer adjusting connection ID.
DIRTYCODE_API int32_t VoipGroupLocalUserStatus (VoipGroupRefT *pVoipGroup, int32_t iLocalUserIndex)
return information about local hardware state
DIRTYCODE_API int32_t VoipGroupStatus (VoipGroupRefT *pVoipGroup, int32_t iSelect, int32_t iValue, void *pBuf, int32_t iBufSize)
Passes through to VoipStatus, for historical reasons.
DIRTYCODE_API int32_t VoipGroupControl (VoipGroupRefT *pVoipGroup, int32_t iControl, int32_t iValue, int32_t iValue2, void *pValue)
Passes through to VoipControl, afer adjusting connection ID and flags.
DIRTYCODE_API void VoipGroupActivateLocalUser (VoipGroupRefT *pVoipGroup, int32_t iLocalUserIndex, uint8_t bActivate)
Refcounted access to VoipActivateLocalUser()
Detailed Description
Typedef Documentation
typedef void(ConnSharingCallbackT)(VoipGroupRefT *pVoip, ConnSharingCbTypeE eCbType, int32_t iConnId, void *pUserData)
event callback function prototype
typedef enum ConnSharingCbTypeE ConnSharingCbTypeE
callback event types
typedef struct VoipGroupRefT VoipGroupRefT
opaque module ref
Enumeration Type Documentation
enum ConnSharingCbTypeE
callback event types
Enumerator
VOIPGROUP_CBTYPE_CONNSUSPEND
VOIPGROUP_CBTYPE_CONNRESUME
Function Documentation
DIRTYCODE_API void VoipGroupActivateLocalUser (VoipGroupRefT * pVoipGroup, int32_t iLocalUserIndex, uint8_t bActivate)
Refcounted access to VoipActivateLocalUser()
Parameters
*pVoipGroup - The VoipGroup (if voipgroup is null and bActivate is false we will deactivate the user from all the voipgroup)
iLocalUserIndex - local user index
bActivate - TRUE to activate, FALSE to deactivate
Version
05/12/2014 (mclouatre)
References VoipGroupManagerT::aActiveRefCount, VoipGroupRefT::aParticipatingUser, FALSE, VoipGroupManagerT::groups, MAX_GROUPS, NetPrintf, NULL, TRUE, VoipActivateLocalUser(), and VoipGetRef().
DIRTYCODE_API int32_t VoipGroupConnect (VoipGroupRefT * pVoipGroup, int32_t iConnId, uint32_t uAddress, uint32_t uManglePort, uint32_t uGamePort, uint32_t uClientId, uint32_t uSessionId)
Set up a connection, using VoipGroup.
Parameters
*pVoipGroup - The VoipGroup the flags apply to
iConnId - connection index
uAddress - address to connect to
uManglePort - port to connect on
uGamePort - port to connect on
uClientId - client identifier
uSessionId - session identifier (optional)
Returns
int32_t - the VoipGroup connid the connection was made with
Version
01/31/2007 (jrainy)
References VoipGroupRefT::bServer, VoipGroupRefT::bTunnel, VoipGroupRefT::connections, VoipGroupConnT::eConnState, VoipGroupConnT::iMappedLowLevelConnId, NetPrintf, NULL, VoipGroupRefT::pConnSharingCallback, VoipGroupRefT::pConnSharingCallbackData, TRUE, VoipGroupConnT::uClientId, VoipGroupConnT::uSessionId, VoipGroupManagerT::uUserRecvMask, VoipGroupManagerT::uUserSendMask, VOIP_CONNID_NONE, VoipConnect(), VoipControl(), VoipGetRef(), VOIPGROUP_CBTYPE_CONNSUSPEND, VOIPGROUP_CONNSTATE_ACTIVE, VOIPGROUP_CONNSTATE_SUSPENDED, VoipGroupDisconnect(), VoipMicrophone(), VoipSpeaker(), and VoipStatus().
DIRTYCODE_API int32_t VoipGroupConnStatus (VoipGroupRefT * pVoipGroup, int32_t iConnId)
Passes through to VoipConnRemote, afer adjusting connection ID.
Parameters
*pVoipGroup - The VoipGroup
iConnId - The connection ID
Returns
int32_t - VOIP_REMOTE_* flags, or VOIP_FLAG_INVALID if iConnId is invalid
Version
01/31/2007 (jrainy)
References VoipGroupRefT::connections, VoipGroupConnT::eConnState, VOIP_CONN_CONNECTED, VOIP_CONNID_NONE, VOIP_FLAG_INVALID, VoipConnStatus(), VoipGetRef(), and VOIPGROUP_CONNSTATE_SUSPENDED.
DIRTYCODE_API int32_t VoipGroupControl (VoipGroupRefT * pVoipGroup, int32_t iControl, int32_t iValue, int32_t iValue2, void * pValue)
Passes through to VoipControl, afer adjusting connection ID and flags.
Parameters
*pVoipGroup - The VoipGroup
iControl - status selector
iValue - selector-specific
iValue2 - selector-specific
*pValue - selector-specific
Returns
int32_t - selector-specific data
Version
01/31/2007 (jrainy)
References VoipGroupRefT::bServer, VoipGroupRefT::bTunnel, ds_memcpy(), NetPrintf, NULL, VoipGroupManagerT::uGroupsAvailable, VoipGroupManagerT::uUserRecvMask, VoipGroupManagerT::uUserSendMask, VoipControl(), VoipGetRef(), and VoipSetLocalUser().
Referenced by ConnApiControl(), and ConnApiDisconnect().
DIRTYCODE_API VoipGroupRefT* VoipGroupCreate (void)
allocates a VoipGroup
Returns
VoipGroupRefT* - Allocated VoipGroup
Version
01/31/2007 (jrainy)
References VoipGroupRefT::bUsed, NULL, TRUE, and VoipGroupManagerT::uGroupsAvailable.
Referenced by ConnApiCreate2().
DIRTYCODE_API void VoipGroupDestroy (VoipGroupRefT * pVoipGroup)
Deallocates a VoipGroup.
Parameters
*pVoipGroup - VoipGroup to Deallocate
Version
01/31/2007 (jrainy)
Referenced by ConnApiDestroy().
DIRTYCODE_API void VoipGroupDisconnect (VoipGroupRefT * pVoipGroup, int32_t iConnId)
Teardown a connection, using VoipGroups.
Parameters
*pVoipGroup - The VoipGroup the flags apply to
iConnId - connection index
Version
01/31/2007 (jrainy)
References VoipGroupRefT::connections, VoipGroupConnT::eConnState, VoipGroupConnT::iMappedLowLevelConnId, NetPrintf, NULL, VoipGroupRefT::pConnSharingCallback, VoipGroupRefT::pConnSharingCallbackData, VoipGroupConnT::uClientId, VoipGroupConnT::uSessionId, VoipGroupManagerT::uUserRecvMask, VoipGroupManagerT::uUserSendMask, VOIP_CONNID_NONE, VoipControl(), VoipDisconnect(), VoipGetRef(), VOIPGROUP_CBTYPE_CONNRESUME, VOIPGROUP_CONNSTATE_ACTIVE, VOIPGROUP_CONNSTATE_SUSPENDED, VoipMicrophone(), and VoipSpeaker().
Referenced by VoipGroupConnect().
DIRTYCODE_API uint8_t VoipGroupIsMutedByClientId (VoipGroupRefT * pVoipGroup, uint32_t iClientId)
whether a client is muted, by ClientId
References VoipGroupRefT::connections, FALSE, MAX_CLIENTS_PER_GROUP, VoipGroupConnT::uClientId, and VoipGroupIsMutedByConnId().
DIRTYCODE_API uint8_t VoipGroupIsMutedByConnId (VoipGroupRefT * pVoipGroup, uint32_t iConnId)
whether a client is muted, by ConnId
References FALSE, VoipGroupManagerT::uUserSendMask, and VOIP_CONNID_NONE.
Referenced by VoipGroupIsMutedByClientId().
DIRTYCODE_API int32_t VoipGroupLocalUserStatus (VoipGroupRefT * pVoipGroup, int32_t iLocalUserIndex)
return information about local hardware state
Parameters
*pVoipGroup - The VoipGroup
iLocalUserIndex - User index
Returns
int32_t - VOIP_LOCAL_* flags
Version
01/31/2007 (jrainy)
References VoipGetRef(), and VoipLocalUserStatus().
DIRTYCODE_API int32_t VoipGroupMuteByClientId (VoipGroupRefT * pVoipGroup, uint32_t iClientId, uint8_t uMute)
References VoipGroupRefT::connections, MAX_CLIENTS_PER_GROUP, VoipGroupConnT::uClientId, and VoipGroupMuteByConnId().
DIRTYCODE_API int32_t VoipGroupMuteByConnId (VoipGroupRefT * pVoipGroup, uint32_t iConnId, uint8_t uMute)
References VoipGroupManagerT::uUserRecvMask, VoipGroupManagerT::uUserSendMask, VOIP_CONNID_NONE, VoipGetRef(), VoipMicrophone(), and VoipSpeaker().
Referenced by VoipGroupMuteByClientId().
DIRTYCODE_API int32_t VoipGroupRemoteUserStatus (VoipGroupRefT * pVoipGroup, int32_t iConnId, int32_t iRemoteUserIndex)
Passes through to VoipUserRemote, afer adjusting connection ID.
Parameters
*pVoipGroup - The VoipGroup
iConnId - The connection ID
iRemoteUserIndex - User index
Returns
int32_t - VOIP_REMOTE_* flags, or VOIP_FLAG_INVALID if iConnId is invalid
Version
01/31/2007 (jrainy)
References VoipGroupRefT::connections, VoipGroupConnT::eConnState, VOIP_CONN_CONNECTED, VOIP_CONNID_NONE, VOIP_FLAG_INVALID, VoipGetRef(), VOIPGROUP_CONNSTATE_SUSPENDED, and VoipRemoteUserStatus().
DIRTYCODE_API void VoipGroupResume (VoipGroupRefT * pVoipGroup, int32_t iConnId, uint32_t uAddress, uint32_t uManglePort, uint32_t uGamePort, uint32_t uClientId, uint32_t uSessionId)
resume a connection
Parameters
*pVoipGroup - voipgroup ref
iConnId - connection index
uAddress - address to connect to
uManglePort - port to connect on
uGamePort - port to connect on
uClientId - client identifier
uSessionId - session identifier (optional)
Version
11/11/2009 (mclouatre)
References VoipGroupRefT::bServer, VoipGroupRefT::connections, VoipGroupConnT::eConnState, VoipGroupConnT::iMappedLowLevelConnId, NetPrintf, NULL, TRUE, VoipGroupConnT::uClientId, VoipGroupConnT::uSessionId, VoipGroupManagerT::uUserRecvMask, VoipGroupManagerT::uUserSendMask, VOIP_CONNID_NONE, VoipConnect(), VoipControl(), VoipGetRef(), VOIPGROUP_CONNSTATE_ACTIVE, VoipMicrophone(), VoipSpeaker(), and VoipStatus().
DIRTYCODE_API void VoipGroupSetConnSharingEventCallback (VoipGroupRefT * pVoipGroup, ConnSharingCallbackT * pCallback, void * pUserData)
Sets the connection sharing callback and userdata for the specified group.
Parameters
*pVoipGroup - voipgroup ref
*pCallback - pointer to the callback to use
*pUserData - pointer to the user specified data
Note
The callback registered with this function must invoke VoipGroupSuspend() when eCbType=VOIPGROUP_CBTYPE_CONNSUSPEND, and it must call VoipGroupResume() when eCbType=VOIPGROUP_CBTYPE_CONNRESUME.
Version
11/11/2009 (mclouatre)
References VoipGroupRefT::pConnSharingCallback, and VoipGroupRefT::pConnSharingCallbackData.
Referenced by ConnApiCreate2().
DIRTYCODE_API void VoipGroupSetEventCallback (VoipGroupRefT * pVoipGroup, VoipCallbackT * pCallback, void * pUserData)
Sets the callback and userdata for the specified group.
Parameters
*pVoipGroup - VoipGroup to use
*pCallback - pointer to the callback to use
*pUserData - pointer to the user specified data
Version
01/31/2007 (jrainy)
References VoipGroupRefT::pGroupCallback, VoipGroupRefT::pGroupCallbackData, VoipGetRef(), and VoipSetEventCallback().
DIRTYCODE_API int32_t VoipGroupStatus (VoipGroupRefT * pVoipGroup, int32_t iSelect, int32_t iValue, void * pBuf, int32_t iBufSize)
Passes through to VoipStatus, for historical reasons.
Parameters
*pVoipGroup - The VoipGroup
iSelect - status selector
iValue - selector-specific
*pBuf - selector-specific
iBufSize - size of the pBuf input
Returns
int32_t - selector-specific data
Version
01/31/2007 (jrainy)
References VOIP_CONNID_NONE, VoipGetRef(), and VoipStatus().
DIRTYCODE_API void VoipGroupSuspend (VoipGroupRefT * pVoipGroup, int32_t iConnId)
suspend a connection
Parameters
*pVoipGroup - voipgroup ref
iConnId - connection index
Version
11/11/2009 (mclouatre)
References VoipGroupRefT::connections, VoipGroupConnT::eConnState, FALSE, VoipGroupConnT::iMappedLowLevelConnId, NetPrintf, VoipGroupConnT::uSessionId, VoipGroupManagerT::uUserRecvMask, VoipGroupManagerT::uUserSendMask, VOIP_CONNID_NONE, VoipDisconnect2(), VoipGetRef(), VOIPGROUP_CONNSTATE_SUSPENDED, VoipMicrophone(), and VoipSpeaker().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:43