#!/bin/bash

if [ ! -n "$1" ]
then
  echo "Usage: confighack DSVERSION"
  exit 1
fi

if [[ $1 == *IPHONE* ]]
then
   sed -e "s/<package name=\"DirtySDK\" [ ]*version=\"dev.*\"/<package name=\"DirtySDK\" version=\"$1\"/" < iphone-masterconfig.xml > temp.xml
   sed -e "s/<package name=\"DirtySDK\" [ ]*version=\".*\.x\"/<package name=\"DirtySDK\" version=\"$1\"/" < temp.xml > build-masterconfig.xml
   
   sed -e "s/<package name=\"PyroSDK\" [ ]*version=\"dev.*\"/<package name=\"PyroSDK\" version=\"$1\"/" < build-masterconfig.xml > temp.xml
   sed -e "s/<package name=\"PyroSDK\" [ ]*version=\".*\.x\"/<package name=\"PyroSDK\" version=\"$1\"/" < temp.xml > build-masterconfig.xml
   
   sed -e "s/<package name=\"TelemetrySDK\" [ ]*version=\"dev.*\"/<package name=\"TelemetrySDK\" version=\"$1\"/" < build-masterconfig.xml > temp.xml
   sed -e "s/<package name=\"TelemetrySDK\" [ ]*version=\".*\.x\"/<package name=\"TelemetrySDK\" version=\"$1\"/" < temp.xml > build-masterconfig.xml

   sed -e "s/iphone-masterconfig.xml/build-masterconfig.xml/" < nant-iphone > nant-iphone.custom
   chmod ugo+x nant-iphone.custom
else
   sed -e "s/<package name=\"DirtySDK\" [ ]*version=\"dev.*\"/<package name=\"DirtySDK\" version=\"$1\"/" < unix-masterconfig.xml > temp.xml
   sed -e "s/<package name=\"DirtySDK\" [ ]*version=\".*\.x\"/<package name=\"DirtySDK\" version=\"$1\"/" < temp.xml > build-masterconfig.xml
   
   sed -e "s/<package name=\"PyroSDK\" [ ]*version=\"dev.*\"/<package name=\"PyroSDK\" version=\"$1\"/" < build-masterconfig.xml > temp.xml
   sed -e "s/<package name=\"PyroSDK\" [ ]*version=\".*\.x\"/<package name=\"PyroSDK\" version=\"$1\"/" < temp.xml > build-masterconfig.xml
   
   sed -e "s/<package name=\"TelemetrySDK\" [ ]*version=\"dev.*\"/<package name=\"TelemetrySDK\" version=\"$1\"/" < build-masterconfig.xml > temp.xml
   sed -e "s/<package name=\"TelemetrySDK\" [ ]*version=\".*\.x\"/<package name=\"TelemetrySDK\" version=\"$1\"/" < temp.xml > build-masterconfig.xml

   sed -e "s/unix-masterconfig.xml/build-masterconfig.xml/" < nant > nant.custom
   chmod ugo+x nant.custom
fi

rm -f temp.xml
