DirtySock: CommTCP
CommTCP
Comm
Typedefs
typedef struct CommTCPRef CommTCPRef
Functions
DIRTYCODE_API CommTCPRef * CommTCPConstruct (int32_t maxwid, int32_t maxinp, int32_t maxout)
Construct the class.
DIRTYCODE_API void CommTCPDestroy (CommTCPRef *what)
Destruct the class.
DIRTYCODE_API int32_t CommTCPResolve (CommTCPRef *what, const char *addr, char *buf, int32_t len, char div)
Resolve an address.
DIRTYCODE_API void CommTCPUnresolve (CommTCPRef *what)
Stop the resolver.
DIRTYCODE_API int32_t CommTCPListen (CommTCPRef *what, const char *addr)
Listen for a connection.
DIRTYCODE_API int32_t CommTCPUnlisten (CommTCPRef *what)
Stop listening.
DIRTYCODE_API int32_t CommTCPConnect (CommTCPRef *what, const char *addr)
Initiate a connection to a peer.
DIRTYCODE_API int32_t CommTCPUnconnect (CommTCPRef *what)
Terminate a connection.
DIRTYCODE_API void CommTCPCallback (CommTCPRef *what, void(*callback)(CommRef *ref, int32_t event))
Set upper layer callback.
DIRTYCODE_API int32_t CommTCPStatus (CommTCPRef *what)
Return current stream status.
DIRTYCODE_API uint32_t CommTCPTick (CommTCPRef *what)
Return current tick.
DIRTYCODE_API int32_t CommTCPSend (CommTCPRef *what, const void *buffer, int32_t length, uint32_t flags)
Send a packet.
DIRTYCODE_API int32_t CommTCPPeek (CommTCPRef *what, void *target, int32_t length, uint32_t *when)
Peek at waiting packet.
DIRTYCODE_API int32_t CommTCPRecv (CommTCPRef *what, void *target, int32_t length, uint32_t *when)
Receive a packet from the buffer.
Detailed Description
Typedef Documentation
typedef struct CommTCPRef CommTCPRef
Function Documentation
DIRTYCODE_API void CommTCPCallback (CommTCPRef * ref, void(*)(CommRef *ref, int32_t event) callback)
Set upper layer callback.
Parameters
*ref - reference pointer
*callback - socket generating callback
Returns
None.
Version
1.0 02/19/99 (GWS) First Version
Referenced by CommTCPConstruct().
DIRTYCODE_API int32_t CommTCPConnect (CommTCPRef * ref, const char * addr)
Initiate a connection to a peer.
Parameters
*ref - reference pointer
*addr - address in ip-address:port form
Returns
int32_t - negative=error, zero=ok
Note
Does not currently perform dns translation
Version
1.0 02/19/99 (GWS) First Version
References CALLB_RECV, COMM_BADADDRESS, COMM_BADSTATE, COMM_NORESOURCE, NetPrintf, CommTCPRef::peeraddr, SockaddrInit, SockaddrInParse(), CommTCPRef::socket, SocketCallback(), SocketConnect(), SocketOpen(), and CommTCPRef::state.
Referenced by CommTCPConstruct().
DIRTYCODE_API CommTCPRef* CommTCPConstruct (int32_t maxwid, int32_t maxinp, int32_t maxout)
Construct the class.
Parameters
maxwid - max record width
maxinp - input packet buffer size
maxout - output packet buffer size
Returns
CommTCPRef - reference pointer
Version
1.0 02/19/99 (GWS) First Version
References CommRef::Callback, CommTCPRef::common, COMMTCP_MEMID, CommTCPCallback(), CommTCPConnect(), CommTCPDestroy(), CommTCPListen(), CommTCPPeek(), CommTCPRecv(), CommTCPResolve(), CommTCPSend(), CommTCPStatus(), CommTCPTick(), CommTCPUnconnect(), CommTCPUnlisten(), CommTCPUnresolve(), CommRef::Connect, CommTCPRef::connident, CommRef::Construct, CommTCPRef::crit, CommRef::Destroy, DirtyMemAlloc(), DirtyMemGroupQuery(), CommRef::Listen, CommRef::maxinp, CommRef::maxout, CommRef::maxwid, CommRef::memgroup, CommRef::memgrpusrdata, NetCritInit(), CommRef::Peek, CommTCPRef::rcvbuf, CommTCPRef::rcvlen, CommTCPRef::rcvwid, CommRef::Recv, CommRef::Resolve, CommRef::Send, CommTCPRef::sndbuf, CommTCPRef::sndlen, CommTCPRef::sndwid, CommTCPRef::state, CommRef::Status, CommRef::Tick, CommRef::Unconnect, CommRef::Unlisten, and CommRef::Unresolve.
DIRTYCODE_API void CommTCPDestroy (CommTCPRef * ref)
Destruct the class.
Parameters
*ref - reference pointer
Returns
None.
Version
1.0 02/19/99 (GWS) First Version
References CommTCPRef::common, COMMTCP_MEMID, CommTCPRef::crit, DirtyMemFree(), CommRef::memgroup, CommRef::memgrpusrdata, NetCritKill(), CommTCPRef::rcvbuf, CommTCPRef::sndbuf, CommTCPRef::socket, SocketClose(), and CommTCPRef::state.
Referenced by CommTCPConstruct().
DIRTYCODE_API int32_t CommTCPListen (CommTCPRef * ref, const char * addr)
Listen for a connection.
Parameters
*ref - reference pointer
*addr - port to listen on (only :port portion used)
Returns
int32_t - negative=error, zero=ok
Version
1.0 02/19/99 (GWS) First Version
References CALLB_RECV, COMM_BADADDRESS, COMM_BADSTATE, COMM_NORESOURCE, COMM_UNEXPECTED, NetPrintf, SockaddrInit, SockaddrInParse(), CommTCPRef::socket, SocketBind(), SocketCallback(), SocketClose(), SocketListen(), SocketOpen(), and CommTCPRef::state.
Referenced by CommTCPConstruct().
DIRTYCODE_API int32_t CommTCPPeek (CommTCPRef * ref, void * target, int32_t length, uint32_t * when)
Peek at waiting packet.
Parameters
*ref - reference pointer
*target - target buffer
length - buffer length
*when - tick received at
Returns
int32_t - negative=nothing pending, else packet length
Version
1.0 02/19/99 (GWS) First Version
References RawTCPPacketT::body, COMM_NODATA, RawTCPPacketT::data, ds_memcpy(), RawTCPPacketT::head, RawTCPPacketT::len, CommTCPRef::rcvbuf, CommTCPRef::rcvinp, CommTCPRef::rcvout, and RawTCPPacketT::when.
Referenced by CommTCPConstruct(), and CommTCPRecv().
DIRTYCODE_API int32_t CommTCPRecv (CommTCPRef * ref, void * target, int32_t length, uint32_t * when)
Receive a packet from the buffer.
Parameters
*ref - reference pointer
*target - target buffer
length - buffer length
*when - tick received at
Returns
int32_t - negative=error, else packet length
Version
1.0 02/19/99 (GWS) First Version
References CommTCPPeek(), CommTCPRef::rcvlen, CommTCPRef::rcvout, and CommTCPRef::rcvwid.
Referenced by CommTCPConstruct().
DIRTYCODE_API int32_t CommTCPResolve (CommTCPRef * ref, const char * addr, char * buf, int32_t len, char div)
Resolve an address.
Parameters
*ref - endpoint
*addr - resolve address
*buf - target buffer
len - target length (min 64 bytes)
div - divider char
Returns
int32_t - <0=error, 0=complete (COMM_NOERROR), >0=in progress (COMM_PENDING)
Note
Target list is always double null terminated allowing null to be used as the divider character if desired. when COMM_PENDING is returned, target buffer is set to "~" until completion
Version
1.0 02/19/99 (GWS) First Version
References NetPrintf.
Referenced by CommTCPConstruct().
DIRTYCODE_API int32_t CommTCPSend (CommTCPRef * ref, const void * buffer, int32_t length, uint32_t flags)
Send a packet.
Parameters
*ref - reference pointer
*buffer - pointer to data
length - length of data
flags - COMM_FLAGS_*
Returns
int32_t - negative=error, zero=buffer full (temp fail), positive=queue position (ok)
Note
Zero length packets may not be sent (they are used for buffer query)
Version
1.0 02/19/99 (GWS) First Version
References RawTCPPacketT::body, COMM_BADSTATE, COMM_MINBUFFER, RawTCPPacketT::data, ds_memcpy(), RawTCPPacketT::head, RawTCPPacketT::len, NetPrintf, NetTick(), CommTCPRef::sndbuf, CommTCPRef::sndinp, CommTCPRef::sndlen, CommTCPRef::sndout, CommTCPRef::sndwid, CommTCPRef::socket, CommTCPRef::state, and RawTCPPacketT::when.
Referenced by CommTCPConstruct().
DIRTYCODE_API int32_t CommTCPStatus (CommTCPRef * ref)
Return current stream status.
Parameters
*ref - reference pointer
Returns
int32_t - CONNECTING, OFFLINE, ONLINE or FAILURE
Version
1.0 02/19/99 (GWS) First Version
References COMM_CONNECTING, COMM_FAILURE, COMM_OFFLINE, COMM_ONLINE, and CommTCPRef::state.
Referenced by CommTCPConstruct().
DIRTYCODE_API uint32_t CommTCPTick (CommTCPRef * ref)
Return current tick.
Parameters
*ref - reference pointer
Returns
uint32_t - elapsed milliseconds
Version
1.0 02/19/99 (GWS) First Version
References NetTick().
Referenced by CommTCPConstruct().
DIRTYCODE_API int32_t CommTCPUnconnect (CommTCPRef * ref)
Terminate a connection.
Parameters
*ref - reference pointer
Returns
int32_t - negative=error, zero=ok
Version
1.0 02/19/99 (GWS) First Version
References CommTCPRef::socket, SocketClose(), and CommTCPRef::state.
Referenced by CommTCPConstruct().
DIRTYCODE_API int32_t CommTCPUnlisten (CommTCPRef * ref)
Stop listening.
Parameters
*ref - reference pointer
Returns
int32_t - negative=error, zero=ok
Version
1.0 02/19/99 (GWS) First Version
References CommTCPRef::socket, SocketClose(), and CommTCPRef::state.
Referenced by CommTCPConstruct().
DIRTYCODE_API void CommTCPUnresolve (CommTCPRef * ref)
Stop the resolver.
Parameters
*ref - endpoint ref
Returns
None.
Version
1.0 02/19/99 (GWS) First Version
Referenced by CommTCPConstruct().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:48