DirtySock: Hasher
Hasher
Util
Macros
#define LobbyNameCmp DirtyUsernameCompare
alias for DirtyUsernameCompare
Typedefs
typedef struct HasherRef HasherRef
typedef int32_t HasherCompareF (const unsigned char *key1, const unsigned char *key2)
Functions
DIRTYCODE_API HasherRef * HasherCreate (int32_t initial, int32_t hashlen)
Create new hash table.
DIRTYCODE_API void HasherDestroy (HasherRef *ref)
Destroy the hash table.
DIRTYCODE_API void HasherSetStrCompareFunc (HasherRef *ref, HasherCompareF *compare)
Override the default string compare function for the given hash table.
DIRTYCODE_API void HasherClear (HasherRef *ref)
Clear an existing hash table.
DIRTYCODE_API void * HasherFlush (HasherRef *ref)
Flush the hash records one at a time.
DIRTYCODE_API int32_t HasherExpand (HasherRef *ref, int32_t expand)
Add additional records to a hash table.
DIRTYCODE_API int32_t HasherCount (HasherRef *ref)
Return count of items in hash table.
DIRTYCODE_API int32_t HashStrAdd (HasherRef *ref, const char *key, void *data)
Add new record to hash table.
DIRTYCODE_API void * HashStrReplace (HasherRef *ref, const char *key, void *data)
Replace an existing record in the hash table.
DIRTYCODE_API void * HashStrFind (HasherRef *ref, const char *key)
Find existing item within hash table.
DIRTYCODE_API void * HashStrDel (HasherRef *ref, const char *key)
Delete existing record from hash table.
DIRTYCODE_API int32_t HashNumAdd (HasherRef *ref, int32_t key, void *data)
Add new record to hash table.
DIRTYCODE_API void * HashNumReplace (HasherRef *ref, int32_t key, void *data)
Replace an existing record in the hash table.
DIRTYCODE_API void * HashNumFind (HasherRef *ref, int32_t key)
Find existing item within hash table.
DIRTYCODE_API void * HashNumDel (HasherRef *ref, int32_t key)
Delete existing record from hash table.
DIRTYCODE_API void HasherEnumInit (HasherRef *ref)
Initialize enumeration structure prior to calls to HasherEnum.
DIRTYCODE_API void * HasherEnum (HasherRef *ref, void **key)
Enumerate the hash records one at a time.
Detailed Description
Macro Definition Documentation
#define LobbyNameCmp DirtyUsernameCompare
alias for DirtyUsernameCompare
Typedef Documentation
typedef int32_t HasherCompareF(const unsigned char *key1, const unsigned char *key2)
typedef struct HasherRef HasherRef
Function Documentation
DIRTYCODE_API void HasherClear (HasherRef * ref)
Clear an existing hash table.
Parameters
*ref - reference pointer
Returns
None.
Version
1.0 03/12/00 (GWS) First Version
References HasherRef::avail, HasherRef::hashbuf, HasherRef::hashlen, HasherRef::items, HasherT::next, and NULL.
DIRTYCODE_API int32_t HasherCount (HasherRef * ref)
Return count of items in hash table.
Parameters
*ref - reference pointer
Returns
Number of items in hash table
Version
1.0 07/29/03 (GWS) First Version
References HasherRef::items.
DIRTYCODE_API HasherRef* HasherCreate (int32_t initial, int32_t hashlen)
Create new hash table.
Parameters
initial - initial number of records
hashlen - size of hash table
Returns
HasherRef * - reference pointer (needed for all other functions)
Version
1.0 03/12/00 (GWS) First Version
References HasherRef::compare, DirtyMemAlloc(), DirtyMemGroupQuery(), DirtyUsernameCompare(), HasherRef::hashbuf, HASHER_MEMID, HasherExpand(), HasherRef::hashlen, HasherRef::memgroup, and HasherRef::memgrpusrdata.
Referenced by _HLBApiInit().
DIRTYCODE_API void HasherDestroy (HasherRef * ref)
Destroy the hash table.
Parameters
*ref - reference pointer
Returns
None.
Version
1.0 03/12/00 (GWS) First Version
References DirtyMemFree(), HasherRef::hashbuf, HASHER_MEMID, HasherRef::list, HasherRef::memgroup, HasherRef::memgrpusrdata, HasherT::next, and NULL.
Referenced by _RosterDestroy().
DIRTYCODE_API void* HasherEnum (HasherRef * ref, void ** key)
Enumerate the hash records one at a time.
Parameters
*ref - reference pointer
*key - if not NULL, return pointer to entry key
Returns
void * - record pointer (NULL=no such record)
Version
1.0 01/15/2003 (DO) First Version
References HashEnumT::curr, HasherT::data, HasherRef::hashbuf, HasherRef::hashlen, HashEnumT::idx, HasherRef::iter, HasherT::key, HasherT::next, NULL, and HasherT::ptr.
DIRTYCODE_API void HasherEnumInit (HasherRef * ref)
Initialize enumeration structure prior to calls to HasherEnum.
Parameters
*ref - reference pointer
Returns
None
Version
1.0 01/15/2003 (DO) First Version
References HashEnumT::curr, HashEnumT::idx, HasherRef::iter, and NULL.
DIRTYCODE_API int32_t HasherExpand (HasherRef * ref, int32_t expand)
Add additional records to a hash table.
Parameters
*ref - reference pointer
expand - number of records to add
Returns
int32_t - number of free records
Note
Not normally called by user (table is auto-expanded)
Version
1.0 03/12/00 (GWS) First Version
References HasherRef::avail, DirtyMemAlloc(), HASHER_MEMID, HasherRef::list, HasherRef::memgroup, HasherRef::memgrpusrdata, HasherT::next, and NULL.
Referenced by HasherCreate(), HashNumAdd(), and HashStrAdd().
DIRTYCODE_API void* HasherFlush (HasherRef * ref)
Flush the hash records one at a time.
Parameters
*ref - reference pointer
Returns
void * - record pointer (NULL=no more records, table cleared)
Note
Similar to clear, but allows caller to get back records
Version
1.0 03/12/00 (GWS) First Version
References HasherRef::avail, HasherT::data, HasherRef::flush, HasherRef::hashbuf, HasherRef::hashlen, HasherRef::items, HasherT::next, and NULL.
Referenced by _RosterDestroy().
DIRTYCODE_API void HasherSetStrCompareFunc (HasherRef * ref, HasherCompareF * compare)
Override the default string compare function for the given hash table.
Parameters
*ref - reference pointer
*compare - pointer to new compare function
Returns
None.
Version
1.0 04/30/03 (DBO) First Version
References HasherRef::compare.
DIRTYCODE_API int32_t HashNumAdd (HasherRef * ref, int32_t key, void * data)
Add new record to hash table.
Parameters
*ref - reference pointer
key - record key
*data - record data
Returns
int32_t - negative=failed, positive=success
Version
1.0 03/12/00 (GWS) First Version
References HasherRef::avail, HasherT::data, data, HasherRef::hashbuf, HasherExpand(), HasherRef::hashlen, HasherRef::items, HasherT::key, HasherT::next, NULL, and HasherT::val.
DIRTYCODE_API void* HashNumDel (HasherRef * ref, int32_t key)
Delete existing record from hash table.
Parameters
*ref - reference pointer
key - item to delete
Returns
void * - pointer to record data (NULL=no such record)
Version
1.0 03/12/00 (GWS) First Version
References HasherRef::avail, HashEnumT::curr, HasherT::data, HasherRef::hashbuf, HasherRef::hashlen, HasherRef::items, HasherRef::iter, HasherT::next, and NULL.
DIRTYCODE_API void* HashNumFind (HasherRef * ref, int32_t key)
Find existing item within hash table.
Parameters
*ref - reference pointer
key - record key
Returns
void * - record pointer (NULL=no such record)
Version
1.0 03/12/00 (GWS) First Version
References HasherT::data, HasherRef::hashbuf, HasherRef::hashlen, HasherT::key, HasherT::next, NULL, and HasherT::val.
DIRTYCODE_API void* HashNumReplace (HasherRef * ref, int32_t key, void * data)
Replace an existing record in the hash table.
Parameters
*ref - reference pointer
*key - record key
*data - record data
Returns
void * - old record pointer (NULL=no match)
Version
1.0 01/15/2003 (DO) First Version
References HasherT::data, data, HasherRef::hashbuf, HasherRef::hashlen, HasherT::key, HasherT::next, NULL, and HasherT::val.
DIRTYCODE_API int32_t HashStrAdd (HasherRef * ref, const char * key, void * data)
Add new record to hash table.
Parameters
*ref - reference pointer
*key - record key
*data - record data
Returns
int32_t - negative=failed, positive=success
Version
1.0 03/12/00 (GWS) First Version
References HasherRef::avail, HasherT::data, data, HasherRef::hashbuf, HasherExpand(), HasherRef::items, HasherT::key, HasherT::next, NULL, and HasherT::ptr.
Referenced by _updateFriendInRoster().
DIRTYCODE_API void* HashStrDel (HasherRef * ref, const char * key)
Delete existing record from hash table.
Parameters
*ref - reference pointer
*key - item to delete
Returns
void * - pointer to record data (NULL=no such record)
Version
1.0 03/12/00 (GWS) First Version
References HasherRef::avail, HasherRef::compare, HashEnumT::curr, HasherT::data, HasherRef::hashbuf, HasherRef::items, HasherRef::iter, HasherT::next, and NULL.
Referenced by _reloadFriends().
DIRTYCODE_API void* HashStrFind (HasherRef * ref, const char * key)
Find existing item within hash table.
Parameters
*ref - reference pointer
*key - record key
Returns
void * - record pointer (NULL=no such record)
Version
1.0 03/12/00 (GWS) First Version
References HasherRef::compare, HasherT::data, HasherRef::hashbuf, HasherT::key, HasherT::next, NULL, and HasherT::ptr.
Referenced by _reloadFriends(), and _updateFriendInRoster().
DIRTYCODE_API void* HashStrReplace (HasherRef * ref, const char * key, void * data)
Replace an existing record in the hash table.
Parameters
*ref - reference pointer
*key - record key
*data - record data
Returns
void * - old record pointer (NULL=no match)
Version
1.0 01/15/2003 (DO) First Version
References HasherRef::compare, HasherT::data, data, HasherRef::hashbuf, HasherT::key, HasherT::next, NULL, and HasherT::ptr.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:56