DirtySock: DirtyNetPriv
DirtyNetPriv
DirtySock
Data Structures
struct SocketPacketQueueEntryT
socket packet queue entry
struct SocketRateT
socket rate estimation
struct SocketAddrMapT
socket address map
Typedefs
typedef struct SocketHostnameCacheT SocketHostnameCacheT
socket hostname cache
typedef struct SocketPacketQueueT SocketPacketQueueT
socket packet queue
typedef struct
SocketPacketQueueEntryT SocketPacketQueueEntryT
socket packet queue entry
typedef struct SocketRateT SocketRateT
socket rate estimation
typedef struct SocketAddrMapEntryT SocketAddrMapEntryT
typedef struct SocketAddrMapT SocketAddrMapT
socket address map
Functions
SocketHostnameCacheT * SocketHostnameCacheCreate (int32_t iMemGroup, void *pMemGroupUserData)
Create short-term hostname (DNS) cache.
void SocketHostnameCacheDestroy (SocketHostnameCacheT *pCache)
Destroy short-term hostname (DNS) cache.
void SocketHostnameCacheAdd (SocketHostnameCacheT *pCache, const char *pStrHost, uint32_t uAddress, int32_t iVerbose)
Add hostname and address to hostname cache.
uint32_t SocketHostnameCacheGet (SocketHostnameCacheT *pCache, const char *pStrHost, int32_t iVerbose)
Get address for hostname from cache, if available. Also expires cache entry if applicable.
void SocketHostnameCacheDel (SocketHostnameCacheT *pCache, const char *pStrHost, uint32_t uAddress, int32_t iVerbose)
Remove hostname cache entry from the cache, if it exists. pStrHost is checked if non-NULL and uAddress is checked if non-zero (note that both can be checked if desired).
HostentT * SocketHostnameAddRef (HostentT **ppHostList, HostentT *pHost, uint8_t bUseRef)
Check for in-progress DNS requests we can piggyback on, instead of issuing a new request.
void SocketHostnameListProcess (HostentT **ppHostList, int32_t iMemGroup, void *pMemGroupUserData)
Process list of in-progress DNS requests, disposing of those that are completed and no longer referenced.
SocketPacketQueueT * SocketPacketQueueCreate (int32_t iMaxPackets, int32_t iMemGroup, void *pMemGroupUserData)
Create a packet queue.
void SocketPacketQueueDestroy (SocketPacketQueueT *pPacketQueue)
Destroy packet queue.
SocketPacketQueueT * SocketPacketQueueResize (SocketPacketQueueT *pPacketQueue, int32_t iMaxPackets, int32_t iMemGroup, void *pMemGroupUserData)
Resize a packet queue, if the max packet size is different.
int32_t SocketPacketQueueControl (SocketPacketQueueT *pPacketQueue, int32_t iControl, int32_t iValue)
Control socket packet queue options.
int32_t SocketPacketQueueStatus (SocketPacketQueueT *pPacketQueue, int32_t iStatus)
Get status of socket packet queue.
int32_t SocketPacketQueueAdd (SocketPacketQueueT *pPacketQueue, const uint8_t *pPacketData, int32_t iPacketSize, struct sockaddr *pPacketAddr)
Add a packet to packet queue.
SocketPacketQueueEntryT * SocketPacketQueueAlloc (SocketPacketQueueT *pPacketQueue)
Alloc a packet queue entry. This is used when receiving data directly into the packet queue data buffer.
int32_t SocketPacketQueueRem (SocketPacketQueueT *pPacketQueue, uint8_t *pPacketData, int32_t iPacketSize, struct sockaddr *pPacketAddr)
Remove a packet from packet queue.
void SocketRateUpdate (SocketRateT *pRate, int32_t iData, const char *pOpName)
Update socket data rate estimation.
int32_t SocketRateThrottle (SocketRateT *pRate, int32_t iSockType, int32_t iData, const char *pOpName)
Throttles data size to send or recv based on calculated data rate and configured max rate.
int32_t SocketSendCallbackAdd (SocketSendCallbackEntryT aCbList[], SocketSendCallbackEntryT *pCbEntry)
Register a new socket send callback.
int32_t SocketSendCallbackRem (SocketSendCallbackEntryT aCbList[], SocketSendCallbackEntryT *pCbEntry)
Unregister a socket send callback that was already registered.
void SocketAddrMapInit (SocketAddrMapT *pAddrMap, int32_t iMemGroup, void *pMemGroupUserData)
Initialize a Socket Address Map.
void SocketAddrMapShutdown (SocketAddrMapT *pAddrMap)
Clean up a Socket Address Map.
struct sockaddr * SocketAddrMapTranslate (SocketAddrMapT *pAddrMap, struct sockaddr *pResult, const struct sockaddr *pSource, int32_t *pNameLen)
Translate the following:
int32_t SocketAddrMapAddress (SocketAddrMapT *pAddrMap, const struct sockaddr *pAddr, int32_t iAddrSize)
Map an IPv6 address and return a virtual IPv4 address that can be used to reference it.
int32_t SocketAddrRemapAddress (SocketAddrMapT *pAddrMap, const struct sockaddr *pOldAddr, const struct sockaddr *pNewAddr, int32_t iAddrSize)
Remap an existing IPv6 address and return a virtual IPv4 address that can be used to reference it.
int32_t SocketAddrUnmapAddress (SocketAddrMapT *pAddrMap, const struct sockaddr *pAddr, int32_t iAddrSize)
Removes an address mapping from the mapping table.
Detailed Description
Typedef Documentation
typedef struct SocketAddrMapEntryT SocketAddrMapEntryT
typedef struct SocketAddrMapT SocketAddrMapT
socket address map
typedef struct SocketHostnameCacheT SocketHostnameCacheT
socket hostname cache
typedef struct SocketPacketQueueEntryT SocketPacketQueueEntryT
socket packet queue entry
typedef struct SocketPacketQueueT SocketPacketQueueT
socket packet queue
typedef struct SocketRateT SocketRateT
socket rate estimation
Function Documentation
int32_t SocketAddrMapAddress (SocketAddrMapT * pAddrMap, const struct sockaddr * pAddr, int32_t iAddrSize)
Map an IPv6 address and return a virtual IPv4 address that can be used to reference it.
Parameters
*pAddrMap - address map
*pAddr - address to add to the mapping table
iAddrSize - size of address
Returns
int32_t - negative=error, else virtual IPv4 address for newly mapped IPv6 address
Version
04/17/2013 (jbrookes)
References SocketAddrMapEntryT::iRefCount, SocketAddrMapEntryT::iVirtualAddress, NetPrintf, NetPrintfVerbose, SocketAddrMapT::pMapEntries, SocketAddrMapEntryT::SockAddr6, SockaddrIn6GetAddr4, SockaddrIn6IsIPv4(), SockaddrIn6IsZero(), SockaddrInGetAddr, and SocketInfo().
Referenced by SocketAccept(), SocketAddrRemapAddress(), SocketControl(), and SocketInfo().
void SocketAddrMapInit (SocketAddrMapT * pAddrMap, int32_t iMemGroup, void * pMemGroupUserData)
Initialize a Socket Address Map.
Parameters
*pAddrMap - address map
iMemGroup - memory group
*pMemGroupUserData - memory group user data
Version
03/03/2016 (jbrookes)
References SocketAddrMapT::iMemGroup, SocketAddrMapT::iNextVirtAddr, NetTick(), and SocketAddrMapT::pMemGroupUserData.
Referenced by SocketCreate().
void SocketAddrMapShutdown (SocketAddrMapT * pAddrMap)
Clean up a Socket Address Map.
Parameters
*pAddrMap - address map
Version
03/03/2016 (jbrookes)
References DirtyMemFree(), SocketAddrMapT::iMemGroup, SocketAddrMapT::pMapEntries, SocketAddrMapT::pMemGroupUserData, and SOCKET_MEMID.
Referenced by SocketDestroy().
struct sockaddr* SocketAddrMapTranslate (SocketAddrMapT * pAddrMap, struct sockaddr * pResult, const struct sockaddr * pSource, int32_t * pNameLen)
Translate the following:
- IPv4 real address to IPV4-mapped IPv6 address
- IPv4 virtual address to IPv6 address
- IPv6 address to IPv4 address
Parameters
*pAddrMap - address map
*pResult - [out] storage for translated result
*pSource - source address
*pNameLen - [out] storage for result length
Returns
struct sockaddr * - pointer to resulting IPv6 address
Version
04/15/2013 (jbrookes)
References ds_memcpy_s(), SocketAddrMapEntryT::iVirtualAddress, NetPrintf, NetPrintfVerbose, SocketAddrMapEntryT::SockAddr6, SockaddrIn6GetAddr4, SockaddrIn6IsIPv4(), SockaddrInGetAddr, SockaddrInGetPort, SockaddrInit, SockaddrInSetAddr, SockaddrInSetPort, SocketHtons(), SocketInfo(), and SocketNtohs().
Referenced by SocketAccept(), SocketBind(), SocketConnect(), and SocketSendto().
int32_t SocketAddrRemapAddress (SocketAddrMapT * pAddrMap, const struct sockaddr * pOldAddr, const struct sockaddr * pNewAddr, int32_t iAddrSize)
Remap an existing IPv6 address and return a virtual IPv4 address that can be used to reference it.
Parameters
*pAddrMap - address map
*pOldAddr - address that should be in mapping table
*pNewAddr - address to update to the mapping table
iAddrSize - size of address
Returns
int32_t - negative=error, else virtual IPv4 address for remapped IPv6 address
Version
12/03/2015 (amakoukji)
References SocketAddrMapEntryT::iVirtualAddress, NetPrintf, and SocketAddrMapAddress().
Referenced by SocketControl().
int32_t SocketAddrUnmapAddress (SocketAddrMapT * pAddrMap, const struct sockaddr * pAddr, int32_t iAddrSize)
Removes an address mapping from the mapping table.
Parameters
*pAddrMap - address map
*pAddr - address to remove from the mapping table
iAddrSize - size of address
Returns
int32_t - negative=error, else virtual IPv4 address for newly mapped IPv6 address
Version
04/18/2013 (jbrookes)
References NetPrintf.
Referenced by SocketControl().
HostentT* SocketHostnameAddRef (HostentT ** ppHostList, HostentT * pHost, uint8_t bUseRef)
Check for in-progress DNS requests we can piggyback on, instead of issuing a new request.
Parameters
**ppHostList - list of active lookups
*pHost - current lookup
bUseRef - force using a new entry if bUseRef=FALSE (should normally be TRUE)
Returns
HostentT * - Pre-existing DNS request we have refcounted, or NULL
Version
01/16/2014 (jbrookes)
References HostentT::done, HostentT::name, NetCritEnter(), NetCritLeave(), NetPrintfVerbose, HostentT::pNext, HostentT::refcount, SocketInfo(), and TRUE.
Referenced by SocketLookup().
void SocketHostnameCacheAdd (SocketHostnameCacheT * pCache, const char * pStrHost, uint32_t uAddress, int32_t iVerbose)
Add hostname and address to hostname cache.
Parameters
*pCache - hostname cache
*pStrHost - hostname to add
uAddress - address of hostname
iVerbose - debug level
Version
10/09/2013 (jbrookes)
References SocketHostnameCacheT::CacheEntries, ds_strnzcpy(), SocketHostnameCacheT::iMaxEntries, NetCritEnter(), NetCritLeave(), NetPrintfVerbose, NetTick(), SocketHostnameCacheGet(), SocketHostnameCacheEntryT::strDnsName, SocketHostnameCacheEntryT::uAddress, and SocketHostnameCacheEntryT::uTimer.
SocketHostnameCacheT* SocketHostnameCacheCreate (int32_t iMemGroup, void * pMemGroupUserData)
Create short-term hostname (DNS) cache.
Parameters
iMemGroup - memgroup to alloc/free with
*pMemGroupUserData - memgroup user data to alloc/free with
Returns
SocketHostnameCacheT * - hostname cache or NULL on failure
Version
10/09/2013 (jbrookes)
References DirtyMemAlloc(), SocketHostnameCacheT::iMaxEntries, SocketHostnameCacheT::iMemGroup, NetPrintf, SocketHostnameCacheT::pMemGroupUserData, and SOCKET_MEMID.
Referenced by SocketCreate().
void SocketHostnameCacheDel (SocketHostnameCacheT * pCache, const char * pStrHost, uint32_t uAddress, int32_t iVerbose)
Remove hostname cache entry from the cache, if it exists. pStrHost is checked if non-NULL and uAddress is checked if non-zero (note that both can be checked if desired).
Parameters
*pCache - hostname cache
*pStrHost - hostname of cache entry to delete, or NULL
uAddress - address of cache entry to delete, or zero
iVerbose - debug level
Version
09/23/2016 (jbrookes)
References SocketHostnameCacheT::CacheEntries, SocketHostnameCacheT::iMaxEntries, NetCritEnter(), NetCritLeave(), NetPrintfVerbose, SocketHostnameCacheEntryT::strDnsName, and SocketHostnameCacheEntryT::uAddress.
void SocketHostnameCacheDestroy (SocketHostnameCacheT * pCache)
Destroy short-term hostname (DNS) cache.
Parameters
*pCache - hostname cache
Version
10/09/2013 (jbrookes)
References DirtyMemFree(), SocketHostnameCacheT::iMemGroup, SocketHostnameCacheT::pMemGroupUserData, and SOCKET_MEMID.
Referenced by SocketDestroy().
uint32_t SocketHostnameCacheGet (SocketHostnameCacheT * pCache, const char * pStrHost, int32_t iVerbose)
Get address for hostname from cache, if available. Also expires cache entry if applicable.
Parameters
*pCache - hostname cache
*pStrHost - hostname to add
iVerbose - debug level
Returns
uint32_t - address for hostname, or zero if not in cache
Version
10/09/2013 (jbrookes)
References SocketHostnameCacheT::CacheEntries, DIRTYNET_HOSTNAMECACHELIFETIME, SocketHostnameCacheT::iMaxEntries, NetCritEnter(), NetCritLeave(), NetPrintfVerbose, NetTick(), NetTickDiff, SocketHostnameCacheEntryT::strDnsName, SocketHostnameCacheEntryT::uAddress, and SocketHostnameCacheEntryT::uTimer.
Referenced by SocketHostnameCacheAdd(), and SocketLookup().
void SocketHostnameListProcess (HostentT ** ppHostList, int32_t iMemGroup, void * pMemGroupUserData)
Process list of in-progress DNS requests, disposing of those that are completed and no longer referenced.
Parameters
**ppHostList - list of active lookups
iMemGroup - memgroup hostname lookup records are allocated with
*pMemGroupUserData - memgroup userdata hostname lookup records are allocated with
Note
This function is called from the SocketIdle thread, which is already guarded by the global critical section. It is therefore assumed that it does not need to be explicitly guarded here.
Version
01/16/2014 (jbrookes)
References DirtyMemFree(), HostentT::pNext, and SOCKET_MEMID.
int32_t SocketPacketQueueAdd (SocketPacketQueueT * pPacketQueue, const uint8_t * pPacketData, int32_t iPacketSize, struct sockaddr * pPacketAddr)
Add a packet to packet queue.
Parameters
*pPacketQueue - packet queue to add to
*pPacketData - packet data to add to queue
iPacketSize - size of packet data
*pPacketAddr - remote address associated with packet
Returns
int32_t - zero=success, negative=failure
Version
02/21/2014 (jbrookes)
References SocketPacketQueueEntryT::aPacketData, SocketPacketQueueT::aPacketQueue, DIRTYNET_PACKETQUEUEDEBUG, ds_memcpy(), ds_memcpy_s(), SocketPacketQueueT::iMaxPackets, SocketPacketQueueT::iNumPackets, SocketPacketQueueT::iPacketHead, SocketPacketQueueEntryT::iPacketSize, SocketPacketQueueT::iPacketTail, NetPrintf, NetPrintfVerbose, NetTick(), SocketPacketQueueEntryT::PacketAddr, SOCKET_MAXUDPRECV, SocketPacketQueueT::uPacketDrop, SocketPacketQueueT::uPacketMax, and SocketPacketQueueEntryT::uPacketTick.
Referenced by SocketControl(), and SocketPacketQueueResize().
SocketPacketQueueEntryT* SocketPacketQueueAlloc (SocketPacketQueueT * pPacketQueue)
Alloc a packet queue entry. This is used when receiving data directly into the packet queue data buffer.
Parameters
*pPacketQueue - packet queue to alloc entry from
Returns
SocketPacketQueueEntryT * - packet queue entry
Version
02/24/2014 (jbrookes)
References SocketPacketQueueT::aPacketQueue, DIRTYNET_PACKETQUEUEDEBUG, SocketPacketQueueT::iMaxPackets, SocketPacketQueueT::iNumPackets, SocketPacketQueueT::iPacketHead, SocketPacketQueueEntryT::iPacketSize, SocketPacketQueueT::iPacketTail, NetPrintf, and NetPrintfVerbose.
int32_t SocketPacketQueueControl (SocketPacketQueueT * pPacketQueue, int32_t iControl, int32_t iValue)
Control socket packet queue options.
Parameters
*pPacketQueue - packet queue control function; different selectors control different behaviors
iControl - control selector
iValue - selector specific
Returns
int32_t - selector result
Note
iControl can be one of the following:
        'pdev' - set simulated packet deviation
        'plat' - set simulated packet latency
        'plos' - set simulated packet loss
Version
10/07/2014 (jbrookes)
References NetPrintf, SocketPacketQueueT::uDeviation, SocketPacketQueueT::uLatency, and SocketPacketQueueT::uPacketLoss.
Referenced by SocketControl().
SocketPacketQueueT* SocketPacketQueueCreate (int32_t iMaxPackets, int32_t iMemGroup, void * pMemGroupUserData)
Create a packet queue.
Parameters
iMaxPackets - size of queue, in packets (max 127)
iMemGroup - memgroup to alloc/free with
*pMemGroupUserData - memgroup user data to alloc/free with
Returns
SocketPacketQueueT * - packet queue, or NULL on failure
Version
02/21/2014 (jbrookes)
References SocketPacketQueueT::aPacketQueue, DirtyMemAlloc(), DIRTYNET_PACKETQUEUEMAX, DS_CLAMP, SocketPacketQueueT::iMaxPackets, SocketPacketQueueT::iMemGroup, SocketPacketQueueT::iNumPackets, NetPrintf, NetTick(), SocketPacketQueueT::pMemGroupUserData, SOCKET_MEMID, and SocketPacketQueueT::uLatencyTime.
Referenced by SocketPacketQueueResize().
void SocketPacketQueueDestroy (SocketPacketQueueT * pPacketQueue)
Destroy packet queue.
Parameters
*pPacketQueue - packet queue to destroy
Version
02/21/2014 (jbrookes)
References DirtyMemFree(), SocketPacketQueueT::iMemGroup, SocketPacketQueueT::pMemGroupUserData, and SOCKET_MEMID.
Referenced by SocketPacketQueueResize().
int32_t SocketPacketQueueRem (SocketPacketQueueT * pPacketQueue, uint8_t * pPacketData, int32_t iPacketSize, struct sockaddr * pPacketAddr)
Remove a packet from packet queue.
Parameters
*pPacketQueue - packet queue to add to
*pPacketData - [out] storage for packet data
iPacketSize - size of packet output data buffer
*pPacketAddr - [out] storage for packet addr
Returns
int32_t - positive=size of packet, zero=no packet, negative=failure
Version
02/21/2014 (jbrookes)
References SocketPacketQueueEntryT::aPacketData, SocketPacketQueueT::aPacketQueue, DIRTYNET_PACKETQUEUEDEBUG, ds_memcpy(), SocketPacketQueueT::iDeviationTime, SocketPacketQueueT::iMaxPackets, SocketPacketQueueT::iNumPackets, SocketPacketQueueT::iPacketHead, SocketPacketQueueEntryT::iPacketSize, SocketPacketQueueT::iPacketTail, NetPrintf, NetPrintfVerbose, NetRand(), NetTick(), NetTickDiff, SocketPacketQueueEntryT::PacketAddr, SockaddrInSetMisc, SocketPacketQueueT::uDeviation, SocketPacketQueueT::uLatency, SocketPacketQueueT::uLatencyTime, SocketPacketQueueT::uPacketLoss, and SocketPacketQueueEntryT::uPacketTick.
Referenced by SocketPacketQueueResize().
SocketPacketQueueT* SocketPacketQueueResize (SocketPacketQueueT * pPacketQueue, int32_t iMaxPackets, int32_t iMemGroup, void * pMemGroupUserData)
Resize a packet queue, if the max packet size is different.
Parameters
*pPacketQueue - packet queue to resize (may be null)
iMaxPackets - new size of queue, in packets (max 127)
iMemGroup - memgroup to alloc/free with
*pMemGroupUserData - memgroup user data to alloc/free with
Returns
SocketPacketQueueT * - pointer to resized packet queue
Note
If the new max queue size is less than the number of packets in the current queue, packets will be overwritten in the usual manner (older discarded in favor of newer).
Version
05/30/2014 (jbrookes)
References DIRTYNET_PACKETQUEUEMAX, DS_CLAMP, SocketPacketQueueT::iMaxPackets, NetPrintf, SOCKET_MAXUDPRECV, SocketPacketQueueAdd(), SocketPacketQueueCreate(), SocketPacketQueueDestroy(), and SocketPacketQueueRem().
Referenced by SocketBind(), and SocketControl().
int32_t SocketPacketQueueStatus (SocketPacketQueueT * pPacketQueue, int32_t iStatus)
Get status of socket packet queue.
Parameters
*pPacketQueue - packet queue to get status of
iStatus - status selector
Returns
int32_t - selector result
Note
iStatus can be one of the following:
        'full' - TRUE if queue is full, FALSE otherwise
        'pdrp' - number of packets overwritten due to queue overflow
        'pmax' - maximum number of packets in queue (high water)
        'size' - queue size (in packets)
Version
10/20/2015 (jbrookes)
References FALSE, SocketPacketQueueT::iMaxPackets, SocketPacketQueueT::iNumPackets, TRUE, SocketPacketQueueT::uPacketDrop, and SocketPacketQueueT::uPacketMax.
Referenced by SocketInfo(), and SocketRecvfrom().
int32_t SocketRateThrottle (SocketRateT * pRate, int32_t iSockType, int32_t iData, const char * pOpName)
Throttles data size to send or recv based on calculated data rate and configured max rate.
Parameters
*pRate - state used to calculate rate
iSockType - socket type (SOCK_DGRAM, SOCK_STREAM, etc)
iData - amount of data being sent/recv
*pOpName - indicates send or recv (for debug use only)
Returns
int32_t - amount of data to send/recv
Version
08/20/2014 (jbrookes)
References DIRTYNET_RATEDEBUG, NetPrintfVerbose, SocketRateUpdate(), SocketRateT::uMaxRate, and SocketRateT::uNextRate.
Referenced by HttpCallback::OnDataAvailable(), SequentialStream::Read(), SocketRecvfrom(), and SocketSendto().
void SocketRateUpdate (SocketRateT * pRate, int32_t iData, const char * pOpName)
Update socket data rate estimation.
Parameters
*pRate - state used to store rate estimation data
iData - amount of data being sent/recv
*pOpName - indicates send or recv (for debug use only)
Note
Rate estimation is based on a rolling 16-deep history of ~100ms samples of data rate (the actual period may vary slightly based on update rate and tick resolution) covering a total of ~1600-1700ms. We also keep track of the rate we are called at (excluding multiple calls within the same tick) so we can estimate how much data we need to have sent by the next time we are called. This is important because we will always be shooting lower than our cap if we don't consider this factor, and the amount we are shooting lower by increases the slower the update rate.
Version
08/20/2014 (jbrookes)
References SocketRateT::aCallHist, SocketRateT::aDataHist, SocketRateT::aTickHist, NetPrintf, NetTick(), NetTickDiff, SocketRateT::uCurRate, SocketRateT::uDataIndex, SocketRateT::uLastRateTick, SocketRateT::uLastTick, SocketRateT::uMaxRate, and SocketRateT::uNextRate.
Referenced by HttpCallback::OnDataAvailable(), SequentialStream::Read(), SocketRateThrottle(), SocketRecvfrom(), and SocketSendto().
int32_t SocketSendCallbackAdd (SocketSendCallbackEntryT aCbEntries[], SocketSendCallbackEntryT * pCbEntry)
Register a new socket send callback.
Parameters
aCbEntries - collection of callbacks to add to
*pCbEntry - entry to be added
Returns
int32_t - zero=success; negative=failure
Version
07/18/2014 (mclouatre)
References NetPrintf, SocketSendCallbackEntryT::pSendCallback, SocketSendCallbackEntryT::pSendCallref, and SOCKET_MAXSENDCALLBACKS.
Referenced by SocketControl().
int32_t SocketSendCallbackRem (SocketSendCallbackEntryT aCbEntries[], SocketSendCallbackEntryT * pCbEntry)
Unregister a socket send callback that was already registered.
Parameters
aCbEntries - collection of callbacks to remove from
*pCbEntry - entry to be removed
Returns
int32_t - zero=success; negative=failure
Version
07/18/2014 (mclouatre)
References NetPrintf, SocketSendCallbackEntryT::pSendCallback, SocketSendCallbackEntryT::pSendCallref, and SOCKET_MAXSENDCALLBACKS.
Referenced by SocketControl().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:34:39