DirtySock: commtapi.c File Reference
commtapi.c File Reference
Modem comm driver.
#include <windows.h>
#include <tapi.h>
#include "DirtySDK/dirtysock.h"
#include "DirtySDK/dirtysock/dirtylib.h"
#include "DirtySDK/comm/commall.h"
#include "DirtySDK/comm/pc/commser.h"
#include "DirtySDK/comm/pc/commtapi.h"
Data Structures
struct CommTAPIRef
private module storage
Macros
#define TAPI_CURRENT_VERSION 0x00010004
Typedefs
typedef struct CommTAPIRef CommTAPIRef
private module storage
Functions
int32_t CommSerRecover (CommSerRef *ref, const char *addr)
Recover a broken connection.
CommTAPIRef * CommTAPIConstruct (int32_t maxwid, int32_t maxinp, int32_t maxout)
Construct the class.
void CommTAPIDestroy (CommTAPIRef *ref)
Destruct the class.
void CommTAPICallback (CommTAPIRef *ref, void(*callback)(CommRef *ref, int32_t event))
Set upper layer callback.
int32_t CommTAPIResolve (CommTAPIRef *ref, const char *addr, char *buf, int32_t len, char div)
Resolve an address.
void CommTAPIUnresolve (CommTAPIRef *ref)
Stop the resolver.
int32_t CommTAPIListen (CommTAPIRef *ref, const char *addr)
Listen for a connection.
int32_t CommTAPIUnlisten (CommTAPIRef *ref)
Stop listening.
int32_t CommTAPIConnect (CommTAPIRef *ref, const char *addr)
Initiate a connection to a peer.
int32_t CommTAPIUnconnect (CommTAPIRef *ref)
Terminate a connection.
int32_t CommTAPIStatus (CommTAPIRef *ref)
Return current stream status.
uint32_t CommTAPITick (CommTAPIRef *ref)
Return current tick.
int32_t CommTAPISend (CommTAPIRef *ref, const void *buffer, int32_t length)
Send a packet.
int32_t CommTAPIPeek (CommTAPIRef *ref, void *target, int32_t length, uint32_t *when)
Peek at waiting packet.
int32_t CommTAPIRecv (CommTAPIRef *ref, void *target, int32_t length, uint32_t *when)
Receive a packet from the buffer.
Detailed Description
Modem comm driver.
Note
The TAPI module relies on the serial module for all of its actual packet communication needs. This code uses TAPI to establish the connection, but passes send/peek/recv calls through.
Attention
Copyright (c) Tiburon Entertainment / Electronic Arts 1999-2003. ALL RIGHTS RESERVED.
Version
1.0 02/19/99 (GWS) First Version
1.1 02/25/99 (GWS) Alpha Release
Macro Definition Documentation
#define TAPI_CURRENT_VERSION 0x00010004
Referenced by CommTAPIResolve().
Typedef Documentation
typedef struct CommTAPIRef CommTAPIRef
private module storage
Function Documentation
int32_t CommSerRecover (CommSerRef * ref, const char * addr)
Recover a broken connection.
Parameters
*ref - reference pointer
*addr - port to open on
Returns
int32_t - negative=error, zero=ok
Note
Not an advertised function; used internally and by tapi driver
Version
1.0 02/15/99 (GWS) First Version
References COMM_INPROGRESS, COMM_NOERROR, COMM_NORESOURCE, data, ds_strnzcpy(), FALSE, CommSerRef::handle, NULL, CommSerRef::rdover, CommSerRef::state, TRUE, CommSerRef::wrover, and CommSerRef::wtover.
Referenced by CommSerConnect(), and CommSerListen().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:41