DirtySock: protowebsocketxboxone.cpp File Reference
protowebsocketxboxone.cpp File Reference
This class wraps Microsoft's WebSocket class provided for Xbox One.
#include <stdlib.h>
#include <string.h>
#include <wrl.h>
#include "DirtySDK/dirtysock.h"
#include "DirtySDK/dirtyvers.h"
#include "DirtySDK/dirtysock/dirtymem.h"
#include "DirtySDK/proto/protowebsocket.h"
#include "DirtySDK/proto/protohttputil.h"
#include "DirtySDK/util/utf8.h"
Data Structures
struct ProtoWebSocketRefT
Macros
#define PROTOWEBSOCKET_BUFSIZE_MIN (4*1024)
default protowebsocket buffer size
#define PROTO_WEBSOCKET_XBOXONE_MAX_URL_SIZE (256)
#define PROTO_WEBSOCKET_XBOXONE_MAX_CLOSE_REASON_SIZE (256)
Functions
int32_t _ProtoWebSocketAppendHeader (ProtoWebSocketRefT *pWebSocket, const char *pStrReason)
Add headers in supplied buffer to connect handshake headers.
int32_t _ProtoWebSocketClose (ProtoWebSocketRefT *pWebSocket, int32_t iReason, const char *pStrReason)
Close connection to server.
int _ProtoWebSocketRecv (ProtoWebSocketRefT *pWebSocket)
Receive any pending data and place it in our modules buffer.
bool _ProtoWebSocketInit (ProtoWebSocketRefT *pWebSocket)
Initialize MS's websocket class in the module state.
ProtoWebSocketRefT * ProtoWebSocketCreate (int32_t iBufSize)
Allocate a WebSocket connection and prepare for use.
ProtoWebSocketRefT * ProtoWebSocketCreate2 (void)
Allocate a WebSocket connection and prepare for use: ProtoSSL function signature compatible version.
void ProtoWebSocketDestroy (ProtoWebSocketRefT *pWebSocket)
Destroy a connection and release state.
ProtoWebSocketRefT * ProtoWebSocketAccept (ProtoWebSocketRefT *pWebSocket)
Accept an incoming connection.
ProtoWebSocketRefT * ProtoWebSocketListen (ProtoWebSocketRefT *pWebSocket)
Start listening for an incoming connection.
int32_t ProtoWebSocketConnect (ProtoWebSocketRefT *pWebSocket, const char *pUrl)
Initiate a connection to a server.
int32_t ProtoWebSocketConnect2 (ProtoWebSocketRefT *pWebSocket, int32_t iUnused0, const char *pUrl, uint32_t uUnused1, int32_t iUnused2)
Initiate a connection to a server: ProtoSSL function signature compatible version.
int32_t ProtoWebSocketDisconnect (ProtoWebSocketRefT *pWebSocket)
Disconnect from the server.
int32_t ProtoWebSocketSend (ProtoWebSocketRefT *pWebSocket, const char *pBuffer, int32_t iLength)
Send data to a server over a WebSocket connection. Stream-type send.
int32_t ProtoWebSocketRecv (ProtoWebSocketRefT *pWebSocket, char *pBuffer, int32_t iLength)
Receive data from a server over a WebSocket connection.
int32_t ProtoWebSocketStatus (ProtoWebSocketRefT *pWebSocket, int32_t iSelect, void *pBuffer, int32_t iBufSize)
Get module status.
int32_t ProtoWebSocketControl (ProtoWebSocketRefT *pWebSocket, int32_t iSelect, int32_t iValue, int32_t iValue2, void *pValue)
Control module behavior.
void ProtoWebSocketUpdate (ProtoWebSocketRefT *pWebSocket)
Give life to module (should be called periodically to allow module to perform work).
Detailed Description
This class wraps Microsoft's WebSocket class provided for Xbox One.
Attention
Copyright (c) 2013 Electronic Arts Inc.
Version
02/23/2013 (cvienneau) First Version
Macro Definition Documentation
#define PROTO_WEBSOCKET_XBOXONE_MAX_CLOSE_REASON_SIZE (256)
Referenced by _ProtoWebSocketClose(), _ProtoWebSocketInit(), and ProtoWebSocketStatus().
#define PROTO_WEBSOCKET_XBOXONE_MAX_URL_SIZE (256)
Referenced by ProtoWebSocketConnect(), and ProtoWebSocketStatus().
#define PROTOWEBSOCKET_BUFSIZE_MIN (4*1024)
default protowebsocket buffer size
Referenced by ProtoWebSocketCreate(), and ProtoWebSocketCreate2().
Function Documentation
int32_t _ProtoWebSocketAppendHeader (ProtoWebSocketRefT * pWebSocket, const char * pStrReason)
Add headers in supplied buffer to connect handshake headers.
Parameters
*pWebSocket - module state
*pStrReason - headers
Returns
int32_t - 0 success, negative failure.
Version
03/04/2013 (cvienneau)
References ProtoWebSocketRefT::eState, NetPrintf, ProtoHttpGetNextHeader(), ProtoWebSocketRefT::pWebSocket, and ProtoWebSocketRefT::ST_DISC.
Referenced by ProtoWebSocketControl().
int32_t _ProtoWebSocketClose (ProtoWebSocketRefT * pWebSocket, int32_t iReason, const char * pStrReason)
Close connection to server.
Parameters
*pWebSocket - module state
iReason - (optional) close reason (PROTOWEBSOCKET_CLOSEREASON_*)
*pStrReason - (optional) string close reason
Returns
int32_t - 0 success
Version
03/04/2013 (cvienneau)
References ProtoWebSocketRefT::eState, ProtoWebSocketRefT::iVerbose, NetPrintf, NetPrintfVerbose, NULL, PROTO_WEBSOCKET_XBOXONE_MAX_CLOSE_REASON_SIZE, PROTOWEBSOCKET_CLOSEREASON_BASE, PROTOWEBSOCKET_CLOSEREASON_MAX, PROTOWEBSOCKET_CLOSEREASON_NORMAL, ProtoWebSocketRefT::pWebSocket, ProtoWebSocketRefT::ST_DISC, ProtoWebSocketRefT::ST_FAIL, and ProtoWebSocketRefT::strUrl.
Referenced by ProtoWebSocketControl(), and ProtoWebSocketDisconnect().
bool _ProtoWebSocketInit (ProtoWebSocketRefT * pWebSocket)
Initialize MS's websocket class in the module state.
Parameters
*pWebSocket - module state
Returns
int32_t - true for success
Version
03/04/2013 (cvienneau)
References ProtoWebSocketRefT::iBuffMax, ProtoWebSocketRefT::iCloseReason, NetPrintf, ProtoWebSocketRefT::pOutputDataWriter, PROTO_WEBSOCKET_XBOXONE_MAX_CLOSE_REASON_SIZE, ProtoWebSocketDestroy(), ProtoWebSocketRefT::pWebSocket, ProtoWebSocketRefT::strReason, and Utf8EncodeFromUCS2().
Referenced by ProtoWebSocketCreate(), and ProtoWebSocketUpdate().
int _ProtoWebSocketRecv (ProtoWebSocketRefT * pWebSocket)
Receive any pending data and place it in our modules buffer.
Parameters
*pWebSocket - module state
Returns
int32_t - negative for an error, 0 recv skipped, 1 recv started
Version
03/04/2013 (cvienneau)
References ProtoWebSocketRefT::bPendingRecv, ds_memcpy(), ProtoWebSocketRefT::eState, ProtoWebSocketRefT::iBuffMax, ProtoWebSocketRefT::iRecvLen, ProtoWebSocketRefT::iVerbose, NetCritEnter(), NetCritLeave(), NetPrintf, NetPrintfVerbose, ProtoWebSocketRefT::pRecvBuf, ProtoWebSocketRefT::pWebSocket, ProtoWebSocketRefT::recvcrit, SOCKERR_NOTCONN, ProtoWebSocketRefT::ST_CONN, ProtoWebSocketRefT::ST_DISC, and ProtoWebSocketRefT::ST_FAIL.
Referenced by ProtoWebSocketUpdate().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:20