DirtySock: DirtyAuthXboxOne
DirtyAuthXboxOne
DirtySock
Macros
#define DIRTYAUTH_SUCCESS (0)
success result
#define DIRTYAUTH_AVAILABLE (0)
alternative name for SUCCESS
#define DIRTYAUTH_PENDING (-1)
operation pending
#define DIRTYAUTH_ERROR (-2)
error
#define DIRTYAUTH_MEMORY (-3)
memory error
#define DIRTYAUTH_NOTSTARTED (-4)
not started
#define DIRTYAUTH_NOTFOUND (-5)
not found
#define DIRTYAUTH_AUTHERR (-6)
xauth error code
Typedefs
typedef struct DirtyAuthRefT DirtyAuthRefT
module state ref
Functions
DirtyAuthRefT * DirtyAuthCreate (uint8_t bSecureBypass)
Create the DirtyAuth module state.
void DirtyAuthDestroy (DirtyAuthRefT *pDirtyAuth)
Destroy the DirtyAuth module.
int32_t DirtyAuthGetToken (int32_t iUserIndex, const char *pHost, uint8_t bForceNew)
Get an XAuth token.
int32_t DirtyAuthCheckToken (int32_t iUserIndex, const char *pHost, int32_t *pTokenLen, char *pToken)
Check to see if an auth token is available.
Detailed Description
Macro Definition Documentation
#define DIRTYAUTH_AUTHERR (-6)
xauth error code
#define DIRTYAUTH_AVAILABLE (0)
alternative name for SUCCESS
#define DIRTYAUTH_ERROR (-2)
error
Referenced by DirtyAuthGetToken().
#define DIRTYAUTH_MEMORY (-3)
memory error
Referenced by DirtyAuthGetToken().
#define DIRTYAUTH_NOTFOUND (-5)
not found
Referenced by DirtyAuthCheckToken().
#define DIRTYAUTH_NOTSTARTED (-4)
not started
Referenced by DirtyAuthCheckToken(), and DirtyAuthGetToken().
#define DIRTYAUTH_PENDING (-1)
operation pending
Referenced by DirtyAuthDestroy(), DirtyAuthGetToken(), ProtoHttpRequestCb(), and ProtoHttpUpdate().
#define DIRTYAUTH_SUCCESS (0)
success result
Referenced by NetConnStatus(), ProtoHttpRequestCb(), and ProtoHttpUpdate().
Typedef Documentation
typedef struct DirtyAuthRefT DirtyAuthRefT
module state ref
Function Documentation
int32_t DirtyAuthCheckToken (int32_t iUserIndex, const char * pHost, int32_t * pTokenLen, char * pToken)
Check to see if an auth token is available.
Parameters
iUserIndex - User Index when -1 this will return the first valid ticket
*pHost - pointer to host to check token availability for
*pTokenLen - filled with token length when return code is DIRTYAUTH_SUCCESS (caller can pass NULL here)
*pToken - filled with token when return code is DIRTYAUTH_SUCCESS (caller can pass NULL here)
Returns
int32_t - DIRTYAUTH_* response code
Version
04/10/2012 (jbrookes)
09/04/2013 (amakoukji) Adapted for Xbox One
References DIRTYAUTH_NOTFOUND, DIRTYAUTH_NOTSTARTED, NetCritEnter(), NetCritLeave(), NetPrintf, NULL, and DirtyAuthRefT::TokenCrit.
Referenced by NetConnStatus(), and ProtoHttpUpdate().
DirtyAuthRefT* DirtyAuthCreate (uint8_t bSecureBypass)
Create the DirtyAuth module state.
Parameters
bSecureBypass - ignored, this is present to keep the same Api as Xenon
Returns
DirtyAuthRefT * - pointer to module state, or NULL
Version
04/05/2012 (jbrookes)
References DIRTYAUTH_MEMID, DirtyMemAlloc(), DirtyMemGroupQuery(), DirtyAuthRefT::iMemGroup, NetCritInit(), NetPrintf, NULL, DirtyAuthRefT::pMemGroupUserData, and DirtyAuthRefT::TokenCrit.
void DirtyAuthDestroy (DirtyAuthRefT * pDirtyAuth)
Destroy the DirtyAuth module.
Parameters
*pDirtyAuth - pointer to module state
Version
04/05/2012 (jbrookes)
References DIRTYAUTH_MEMID, DIRTYAUTH_PENDING, DirtyMemFree(), DirtyAuthRefT::iMemGroup, NetConnControl(), NetCritKill(), NetPrintf, NULL, DirtyAuthRefT::pMemGroupUserData, DirtyAuthTokenT::pNext, DirtyAuthRefT::pTokenList, and DirtyAuthRefT::TokenCrit.
Referenced by NetConnDisconnect().
int32_t DirtyAuthGetToken (int32_t iUserIndex, const char * pHost, uint8_t bForceNew)
Get an XAuth token.
Parameters
iUserIndex - user index
*pHost - pointer to hostname to get token for
bForceNew - TRUE=force acquisition of new token
Returns
int32_t - DIRTYAUTH_* response code
Version
04/10/2012 (jbrookes)
References DirtyAuthTokenT::asyncOperation, DIRTYAUTH_ERROR, DIRTYAUTH_MEMID, DIRTYAUTH_MEMORY, DIRTYAUTH_NOTSTARTED, DIRTYAUTH_PENDING, DirtyMemAlloc(), FALSE, NetConnQuery(), NetConnStatus(), NetCritEnter(), NetCritLeave(), NetPrintf, NULL, and DirtyAuthRefT::TokenCrit.
Referenced by ProtoHttpRequestCb().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Jun 5 2015 16:26:00