DirtySock: userapixboxone.cpp File Reference
userapixboxone.cpp File Reference
Implements the xboxone specific code to request UserProfiles, and parse the responses.
#include "DirtySDK/platform.h"
#include <xdk.h>
#include <collection.h>
#include "DirtySDK/dirtysock/dirtymem.h"
#include "DirtySDK/util/utf8.h"
#include "userapipriv.h"
Data Structures
struct UserApiPlatformUserContextT
struct UserApiPlatformDataT
Macros
#define USERAPI_MASK_NOTIFY_PRESENCE (0x10)
#define USERAPI_MASK_NOTIFY_TITLE (0x20)
#define USERAPI_MASK_FRIENDS (0x40)
#define USERAPI_MASK_POST (0x80)
#define USERAPI_ASYNC_TIMOUT_MS (20000)
#define USERAPI_DISPLAY_PIC_SIZE_SMALL "&w=64&h=64"
#define USERAPI_DISPLAY_PIC_SIZE_MEDIUM "&w=208&h=208"
#define USERAPI_DISPLAY_PIC_SIZE_LARGE "&w=424&h=424"
#define HOME_MENU_TITLE_ID (714681658)
Typedefs
typedef enum
UserApiLevelXb1NotificationState UserListApiLevelPS4E
typedef struct
UserApiPlatformUserContextT UserApiPlatformUserContextT
Enumerations
enum UserApiLevelXb1NotificationState {
NOTIFICATION_STATE_ERROR = -1,
NOTIFICATION_STATE_IDLE = 0,
NOTIFICATION_STATE_CONNECTING_TO_RTA,
NOTIFICATION_STATE_CONNECTED_TO_RTA,
NOTIFICATION_STATE_QUERY_FRIENDS,
NOTIFICATION_STATE_FRIEND_RECEIVED,
NOTIFICATION_STATE_SIGNUP,
NOTIFICATION_STATE_SIGNUP_COMPLETE
}
Functions
uint8_t _UserApiInitializeContext (UserApiRefT *pRef, uint32_t uUserIndex)
Initialize a user context.
PresenceTitleRecord _UserApiGetPriorityTitle (IVectorView< PresenceTitleRecord^>^presenceTitleRecordList)
Choose the most relevant title from the list provided.
UserApiPlatformDataT * UserApiPlatCreateData (UserApiRefT *pRef)
Allocates and initializes resources needed for the UserApi on Xbox One.
int32_t UserApiPlatDestroyData (UserApiRefT *pRef, UserApiPlatformDataT *pPlatformData)
Destroys the xboxone specific resources used by the UserApi module.
int32_t UserApiPlatRequestProfile (UserApiRefT *pRef, uint32_t uUserIndex, DirtyUserT *pLookupUsers, int32_t iLookupUsersLength)
Initiates the profile request to Xbox LIVE Services.
int32_t UserApiPlatAbortRequests (UserApiRefT *pRef, uint32_t uUserIndex)
Aborts all request to Xbox LIVE Services for a user.
int32_t UserApiPlatRequestPresence (UserApiRefT *pRef, uint32_t uUserIndex, DirtyUserT *pLookupUsers)
Requests presence information from Microsoft.
int32_t UserApiPlatRequestRichPresence (UserApiRefT *pRef, uint32_t uUserIndex, DirtyUserT *pLookupUser)
Requests rich presence information from Microsoft.
int32_t UserApiPlatRequestRecentlyMet (UserApiRefT *pRef, uint32_t uUserIndex, DirtyUserT *pPlayerMet)
Unused for XB1.
int32_t UserApiPlatRequestPostRichPresence (UserApiRefT *pRef, uint32_t uUserIndex, UserApiRichPresenceT *pData)
Submit rich presence data to Microsoft for a local player.
int32_t UserApiPlatControl (UserApiRefT *pRef, int32_t iControl, int32_t iValue, int32_t iValue2, void *pValue)
Control behavior of module.
int32_t UserApiPlatUpdate (UserApiRefT *pRef)
Control behavior of module.
Detailed Description
Implements the xboxone specific code to request UserProfiles, and parse the responses.
Attention
Copyright (c) Electronic Arts 2012
Version
1.0 25/04/2013 (amakoukji) First Version
Macro Definition Documentation
#define HOME_MENU_TITLE_ID (714681658)
Referenced by _UserApiGetPriorityTitle().
#define USERAPI_ASYNC_TIMOUT_MS (20000)
Referenced by UserApiPlatUpdate().
#define USERAPI_DISPLAY_PIC_SIZE_LARGE "&w=424&h=424"
#define USERAPI_DISPLAY_PIC_SIZE_MEDIUM "&w=208&h=208"
#define USERAPI_DISPLAY_PIC_SIZE_SMALL "&w=64&h=64"
#define USERAPI_MASK_FRIENDS (0x40)
#define USERAPI_MASK_NOTIFY_PRESENCE (0x10)
#define USERAPI_MASK_NOTIFY_TITLE (0x20)
#define USERAPI_MASK_POST (0x80)
Referenced by UserApiPlatRequestPostRichPresence(), and UserApiPlatUpdate().
Typedef Documentation
typedef struct UserApiPlatformUserContextT UserApiPlatformUserContextT
typedef enum UserApiLevelXb1NotificationState UserListApiLevelPS4E
Enumeration Type Documentation
enum UserApiLevelXb1NotificationState
Enumerator
NOTIFICATION_STATE_ERROR
NOTIFICATION_STATE_IDLE
NOTIFICATION_STATE_CONNECTING_TO_RTA
NOTIFICATION_STATE_CONNECTED_TO_RTA
NOTIFICATION_STATE_QUERY_FRIENDS
NOTIFICATION_STATE_FRIEND_RECEIVED
NOTIFICATION_STATE_SIGNUP
NOTIFICATION_STATE_SIGNUP_COMPLETE
Function Documentation
PresenceTitleRecord _UserApiGetPriorityTitle (IVectorView< PresenceTitleRecord^>^ presenceTitleRecordList)
Choose the most relevant title from the list provided.
Parameters
presenceTitleRecordList - list of active title presence data
Returns
PresenceTitleRecord^ - Highest priority title, or nullptr if failed
Version
04/24/2014 (amakoukji)
References HOME_MENU_TITLE_ID, and NULL.
uint8_t _UserApiInitializeContext (UserApiRefT * pRef, uint32_t uUserIndex)
Initialize a user context.
Parameters
pRef - pointer to the UserApiRefT module
uUserIndex - The index of the user making the request
Returns
uint8_t - TRUE for success, FALSE otherwise.
Version
02/14/2014 (amakoukji)
References UserApiPlatformDataT::aUserContext, FALSE, NetConnStatus(), NetPrintf, UserApiRefT::pPlatformData, UserApiPlatformUserContextT::refXblUserContext, and TRUE.
Referenced by UserApiPlatCreateData(), UserApiPlatRequestPostRichPresence(), UserApiPlatRequestPresence(), and UserApiPlatRequestProfile().
int32_t UserApiPlatAbortRequests (UserApiRefT * pRef, uint32_t uUserIndex)
Aborts all request to Xbox LIVE Services for a user.
Parameters
*pRef - module ref
uUserIndex - The index of the user making the request
Returns
int32_t - 0 for success, negative for error
Version
04/17/2013 (mcorcoran)
Referenced by UserApiCancel(), and UserApiControl().
int32_t UserApiPlatControl (UserApiRefT * pRef, int32_t iControl, int32_t iValue, int32_t iValue2, void * pValue)
Control behavior of module.
Parameters
*pRef - pointer to module state
iControl - status selector
iValue - control value
iValue2 - control value
*pValue - control value
Returns
int32_t - Return 0 if successful. Otherwise a selector specific error
Note
iControl can be one of the following:
        'avsz' - Set which avatar size will be retrieved. iValue = 's' for small (64x64), 'm' for medium (208x208) and 'l' for big (424x424). The default value is 'l' on xboxone
Version
05/10/2013 (mcorcoran) - First version
References NetPrintf, UserApiPlatformDataT::pAvatarSize, UserApiRefT::pPlatformData, and UserApiPlatformDataT::uNotificationTitle.
Referenced by UserApiControl().
UserApiPlatformDataT* UserApiPlatCreateData (UserApiRefT * pRef)
Allocates and initializes resources needed for the UserApi on Xbox One.
Parameters
pRef - pointer to the UserApiRefT module
Returns
UserApiPlatformDataT* - pointer to the Xbox One specific UserApiPlatformDataT, or NULL on failure.
Version
04/17/2013 (mcorcoran)
References _UserApiInitializeContext(), DirtyMemAlloc(), UserApiRefT::iMemGroup, NETCONN_MAXLOCALUSERS, NetConnStatus(), NetPrintf, NULL, UserApiPlatformDataT::pAvatarSize, UserApiRefT::pMemGroupUserData, UserApiRefT::pPlatformData, and USERAPI_MEMID.
Referenced by UserApiCreate().
int32_t UserApiPlatDestroyData (UserApiRefT * pRef, UserApiPlatformDataT * pPlatformData)
Destroys the xboxone specific resources used by the UserApi module.
Parameters
*pRef - pointer to UserApiT module reference.
*pPlatformData - pointer to the UserApiPlatformDataT struct to be destroyed.
Returns
int32_t - 0 for success, negative for error
Version
04/17/2013 (amakoukji)
References UserApiPlatformDataT::aUserContext, UserApiPlatformDataT::bAsyncInProgress, DirtyMemFree(), UserApiRefT::iMemGroup, NETCONN_MAXLOCALUSERS, NetPrintf, NULL, UserApiRefT::pMemGroupUserData, UserApiRefT::pPlatformData, UserApiPlatformUserContextT::refAsyncOpFriend, UserApiPlatformUserContextT::refAsyncOpNotifyPresence, UserApiPlatformUserContextT::refAsyncOpNotifyTitle, UserApiPlatformUserContextT::refAsyncOpPostRichPresence, UserApiPlatformUserContextT::refAsyncOpPresence, UserApiPlatformUserContextT::refAsyncOpProfile, UserApiPlatformUserContextT::refFriendResult, UserApiPlatformUserContextT::refResultsPresence, UserApiPlatformUserContextT::refResultsProfiles, UserApiPlatformUserContextT::refXblUserContext, and USERAPI_MEMID.
int32_t UserApiPlatRequestPostRichPresence (UserApiRefT * pRef, uint32_t uUserIndex, UserApiRichPresenceT * pData)
Submit rich presence data to Microsoft for a local player.
Parameters
*pRef - module ref
uUserIndex - The index of the user making the request
*pData - Rich presence data
Returns
int32_t - 0 for success, negative for error
Version
01/21/2013 (amakoukji)
References _UserApiInitializeContext(), UserApiPlatformDataT::aUserContext, UserApiPlatformDataT::bAsyncInProgress, UserApiRefT::bAvailableDataIndexRMP, UserApiRefT::bShuttingDown, UserApiPlatformUserContextT::eResultRichPresencePost, UserApiUserContextT::iTotalErrors, UserApiUserContextT::iTotalReceived, NetConnStatus(), NetPrintf, NetTick(), UserApiRefT::pPlatformData, UserApiPlatformUserContextT::refAsyncOpPostRichPresence, UserApiPlatformUserContextT::refXblUserContext, UserApiRichPresenceT::strData, TRUE, UserApiPlatformUserContextT::uOpPostRichPresenceTimer, USERAPI_ERROR_OK, USERAPI_ERROR_REQUEST_FAILED, USERAPI_MASK_POST, USERAPI_RICH_PRES_MAXLEN, and UserApiRefT::UserRmpList.
Referenced by UserApiPostRichPresenceAsync().
int32_t UserApiPlatRequestPresence (UserApiRefT * pRef, uint32_t uUserIndex, DirtyUserT * pLookupUsers)
Requests presence information from Microsoft.
Parameters
*pRef - module ref
uUserIndex - The index of the user making the request
*pLookupUsers - User to lookup
Returns
int32_t - 0 for success, negative for error
Version
01/21/2013 (amakoukji)
References _UserApiInitializeContext(), UserApiPlatformDataT::aUserContext, UserApiPlatformDataT::bAsyncInProgress, DirtyUserToNativeUser(), ds_snzprintf(), UserApiRefT::iLookupsSent, NetConnStatus(), NetPrintf, NetTick(), UserApiRefT::pPlatformData, pRef, UserApiPlatformUserContextT::refAsyncOpPresence, UserApiPlatformUserContextT::refXblUserContext, TRUE, UserApiPlatformUserContextT::uOpPresenceTimer, and USERAPI_MASK_PRESENCE.
Referenced by UserApiPlatRequestRichPresence(), and UserApiRequestPresenceAsync().
int32_t UserApiPlatRequestProfile (UserApiRefT * pRef, uint32_t uUserIndex, DirtyUserT * pLookupUsers, int32_t iLookupUsersLength)
Initiates the profile request to Xbox LIVE Services.
Parameters
*pRef - module ref
uUserIndex - The index of the user making the request
pLookupUsers - Array of DirtyUserT struct containing the users to lookup
iLookupUsersLength - maximum users to return per query
Returns
int32_t - 0 for success, negative for error
Version
04/17/2013 (mcorcoran)
References _UserApiInitializeContext(), UserApiPlatformDataT::aUserContext, UserApiPlatformDataT::bAsyncInProgress, DirtyUserToNativeUser(), UserApiRefT::iLookupsSent, NetConnStatus(), NetPrintf, NetTick(), UserApiRefT::pPlatformData, pRef, UserApiPlatformUserContextT::refAsyncOpProfile, UserApiPlatformUserContextT::refXblUserContext, TRUE, UserApiPlatformUserContextT::uOpProfileTimer, and USERAPI_MASK_PROFILE.
Referenced by UserApiRequestPresenceAsync(), and UserApiRequestProfilesAsync().
int32_t UserApiPlatRequestRecentlyMet (UserApiRefT * pRef, uint32_t uUserIndex, DirtyUserT * pPlayerMet)
Unused for XB1.
Parameters
*pRef - module ref
uUserIndex - The index of the user making the request
*pPlayerMet - User to match
Returns
int32_t - 0 for success, negative for error
Version
01/21/2013 (amakoukji)
References USERAPI_ERROR_UNSUPPORTED.
Referenced by UserApiPostRecentlyMetAsync().
int32_t UserApiPlatRequestRichPresence (UserApiRefT * pRef, uint32_t uUserIndex, DirtyUserT * pLookupUser)
Requests rich presence information from Microsoft.
Parameters
*pRef - module ref
uUserIndex - The index of the user making the request
*pLookupUser - User to lookup
Returns
int32_t - 0 for success, negative for error
Version
01/21/2013 (amakoukji)
References USERAPI_MASK_PRESENCE, UserApiPlatRequestPresence(), and UserApiRefT::uUserDataMask.
Referenced by UserApiRequestPresenceAsync().
int32_t UserApiPlatUpdate (UserApiRefT * pRef)
Control behavior of module.
Parameters
*pRef - pointer to module state
Returns
int32_t - Return 0 if successful. Otherwise a selector specific error
Version
08/08/2013 (amakoukji) - First version
References UserApiPlatformDataT::aUserContext, UserApiPlatformDataT::bAsyncInProgress, UserApiRefT::bAvailableDataIndex, UserApiRefT::bAvailableDataIndexRMP, UserApiRefT::bPresenceNotificationStarted, UserApiRefT::bRichPresenceNotificationStarted, UserApiRefT::bTitleNotificationStarted, UserApiPlatformUserContextT::eType, FALSE, UserApiUserContextT::iTotalErrors, NETCONN_MAXLOCALUSERS, NetPrintf, NetTick(), NetTickDiff, NOTIFICATION_STATE_CONNECTED_TO_RTA, NOTIFICATION_STATE_CONNECTING_TO_RTA, NOTIFICATION_STATE_ERROR, NOTIFICATION_STATE_FRIEND_RECEIVED, NOTIFICATION_STATE_IDLE, NOTIFICATION_STATE_QUERY_FRIENDS, NOTIFICATION_STATE_SIGNUP, NOTIFICATION_STATE_SIGNUP_COMPLETE, UserApiPlatformUserContextT::NotificationSignUpState, NULL, UserApiRefT::pPlatformData, UserApiRefT::PresenceNotification, UserApiPlatformUserContextT::refResultsPresence, UserApiPlatformUserContextT::refResultsProfiles, UserApiRefT::RichPresenceNotification, UserApiRefT::TitleNotification, TRUE, UserApiPlatformUserContextT::uOpFriendTimer, UserApiPlatformUserContextT::uOpNotifyPresenceTimer, UserApiPlatformUserContextT::uOpNotifyTitleTimer, UserApiPlatformUserContextT::uOpPostRichPresenceTimer, UserApiPlatformUserContextT::uOpPresenceTimer, UserApiPlatformUserContextT::uOpProfileTimer, UserApiPlatformUserContextT::uRtaConnectionTimer, USERAPI_ASYNC_TIMOUT_MS, USERAPI_MASK_POST, USERAPI_MASK_PRESENCE, USERAPI_MASK_PROFILE, USERAPI_MASK_RICH_PRESENCE, USERAPI_NOTIFY_LIST_MAX_SIZE, USERAPI_NOTIFY_PRESENCE_UPDATE, USERAPI_NOTIFY_RICH_PRESENCE_UPDATE, USERAPI_NOTIFY_TITLE_UPDATE, and UserApiRefT::UserRmpList.
Referenced by UserApiUpdate().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:20