DirtySock: ProtoHttp
ProtoHttp
Proto
Data Structures
struct ProtoHttpWriteCbInfoT
write callback info
Macros
#define PROTOHTTP_POST (0)
execute a POST when calling ProtoHttpPost
#define PROTOHTTP_PUT (1)
execute a PUT when calling ProtoHttpPost
#define PROTOHTTP_STREAM_BEGIN (-1)
start streaming upload (size unknown)
#define PROTOHTTP_STREAM_END (0)
streaming upload operation is complete
#define PROTOHTTP_HEADBODY (0)
get head and body when calling ProtoHttpGet
#define PROTOHTTP_HEADONLY (1)
only get head, not body, when calling ProtoHttpGet
#define PROTOHTTP_RECVDONE (-1)
receive operation complete, and all data has been read
#define PROTOHTTP_RECVFAIL (-2)
receive operation failed
#define PROTOHTTP_RECVWAIT (-3)
waiting for body data
#define PROTOHTTP_RECVHEAD (-4)
in headonly mode and header has been received
#define PROTOHTTP_RECVBUFF (-5)
recvall did not have enough space in the provided buffer
#define PROTOHTTP_MINBUFF (-6)
not enough input buffer space for operation
#define _PROTOHTTP_WRITECBINFO_DEFINED
#define ProtoHttpRequest(_pState, _pUrl, _pData, _iDataSize, _eRequestType) ProtoHttpRequestCb(_pState, _pUrl, _pData, _iDataSize, _eRequestType, NULL, NULL)
Typedefs
typedef struct ProtoHttpRefT ProtoHttpRefT
opaque module ref
typedef struct
ProtoHttpWriteCbInfoT ProtoHttpWriteCbInfoT
write callback info
typedef int32_t(ProtoHttpWriteCbT)(ProtoHttpRefT *pState, const ProtoHttpWriteCbInfoT *pCbInfo, const char *pData, int32_t iDataSize, void *pUserData)
write data callback
typedef int32_t(ProtoHttpCustomHeaderCbT)(ProtoHttpRefT *pState, char *pHeader, uint32_t uHeaderSize, const char *pData, int64_t iDataLen, void *pUserRef)
callback that may be used to customize request header before sending
typedef int32_t(ProtoHttpReceiveHeaderCbT)(ProtoHttpRefT *pState, const char *pHeader, uint32_t uHeaderSize, void *pUserRef)
callback that may be used to implement custom header parsing on header receipt
Functions
DIRTYCODE_API ProtoHttpRefT * ProtoHttpCreate (int32_t iRcvBuf)
Allocate module state and prepare for use.
DIRTYCODE_API void ProtoHttpCallback (ProtoHttpRefT *pState, ProtoHttpCustomHeaderCbT *pCustomHeaderCb, ProtoHttpReceiveHeaderCbT *pReceiveHeaderCb, void *pUserRef)
Set header callbacks.
DIRTYCODE_API void ProtoHttpDestroy (ProtoHttpRefT *pState)
Destroy the module and release its state.
DIRTYCODE_API int32_t ProtoHttpGet (ProtoHttpRefT *pState, const char *pUrl, uint32_t bHeadOnly)
Initiate an HTTP transfer. Pass in a URL and the module starts a getting data from the appropriate server.
DIRTYCODE_API int32_t ProtoHttpRecv (ProtoHttpRefT *pState, char *pBuffer, int32_t iBufMin, int32_t iBufMax)
Return the actual url data.
DIRTYCODE_API int32_t ProtoHttpRecvAll (ProtoHttpRefT *pState, char *pBuffer, int32_t iBufSize)
Return all of the url data.
DIRTYCODE_API int32_t ProtoHttpPost (ProtoHttpRefT *pState, const char *pUrl, const char *pData, int64_t iDataSize, uint32_t bDoPut)
Initiate transfer of data to to the server via a HTTP POST command.
DIRTYCODE_API int32_t ProtoHttpSend (ProtoHttpRefT *pState, const char *pData, int32_t iDataSize)
Send data during an ongoing Post transaction.
DIRTYCODE_API int32_t ProtoHttpDelete (ProtoHttpRefT *pState, const char *pUrl)
Request deletion of a server-based resource.
DIRTYCODE_API int32_t ProtoHttpOptions (ProtoHttpRefT *pState, const char *pUrl)
Request options from a server.
DIRTYCODE_API int32_t ProtoHttpRequestCb (ProtoHttpRefT *pState, const char *pUrl, const char *pData, int64_t iDataSize, ProtoHttpRequestTypeE eRequestType, ProtoHttpWriteCbT *pWriteCb, void *pWriteCbUserData)
Initiate an HTTP transfer. Pass in a URL and the module starts a transfer from the appropriate server. Use ProtoHttpRequest() macro wrapper if write callback is not required.
DIRTYCODE_API void ProtoHttpAbort (ProtoHttpRefT *pState)
Abort current operation, if any.
DIRTYCODE_API void ProtoHttpSetBaseUrl (ProtoHttpRefT *pState, const char *pUrl)
Set base url that will be used for any relative url references.
DIRTYCODE_API int32_t ProtoHttpGetLocationHeader (ProtoHttpRefT *pState, const char *pInpBuf, char *pBuffer, int32_t iBufSize, const char **pHdrEnd)
Get location header from the input buffer. The Location header requires some special processing.
DIRTYCODE_API int32_t ProtoHttpControl (ProtoHttpRefT *pState, int32_t iSelect, int32_t iValue, int32_t iValue2, void *pValue)
ProtoHttp control function. Different selectors control different behaviors.
DIRTYCODE_API int32_t ProtoHttpStatus (ProtoHttpRefT *pState, int32_t iSelect, void *pBuffer, int32_t iBufSize)
Return status of current HTTP transfer. Status type depends on selector.
DIRTYCODE_API int32_t ProtoHttpCheckKeepAlive (ProtoHttpRefT *pState, const char *pUrl)
Checks whether a request for the given Url would be a keep-alive transaction. Unlike the 'generic' version, this version is not aware of the current connection status, only whether the previous request was made to the same host/port/security setting.
DIRTYCODE_API void ProtoHttpUpdate (ProtoHttpRefT *pState)
Give time to module to do its thing (should be called periodically to allow module to perform work)
DIRTYCODE_API int32_t ProtoHttpSetCACert (const uint8_t *pCACert, int32_t iCertSize)
Add one or more X.509 CA certificates to the trusted list. A certificate added will be available to all HTTP instances for the lifetime of the application. This function can add one or more PEM certificates or a single DER certificate.
DIRTYCODE_API int32_t ProtoHttpSetCACert2 (const uint8_t *pCACert, int32_t iCertSize)
Add one or more X.509 CA certificates to the trusted list. A certificate added will be available to all HTTP instances for the lifetime of the application. This function can add one or more PEM certificates or a single DER certificate.
DIRTYCODE_API int32_t ProtoHttpValidateAllCA (void)
Validate all CA that have been added but not yet been validated. Validation is a one-time process and disposes of the X509 certificate that is retained until validation.
DIRTYCODE_API void ProtoHttpClrCACerts (void)
Clears all dynamic CA certs from the list.
Detailed Description
Macro Definition Documentation
#define _PROTOHTTP_WRITECBINFO_DEFINED
#define PROTOHTTP_HEADBODY (0)
get head and body when calling ProtoHttpGet
#define PROTOHTTP_HEADONLY (1)
only get head, not body, when calling ProtoHttpGet
#define PROTOHTTP_MINBUFF (-6)
not enough input buffer space for operation
Referenced by HttpManagerRecv(), HttpManagerRecvAll(), and UserListApiUpdate().
#define PROTOHTTP_POST (0)
execute a POST when calling ProtoHttpPost
#define PROTOHTTP_PUT (1)
execute a PUT when calling ProtoHttpPost
#define PROTOHTTP_RECVBUFF (-5)
recvall did not have enough space in the provided buffer
Referenced by ProtoHttpRecvAll().
#define PROTOHTTP_RECVDONE (-1)
receive operation complete, and all data has been read
Referenced by ProtoHttpRecv(), ProtoHttpRecvAll(), and WebOfferUpdate().
#define PROTOHTTP_RECVFAIL (-2)
receive operation failed
Referenced by HttpManagerRecv(), ProtoHttpRecv(), and UserListApiUpdate().
#define PROTOHTTP_RECVHEAD (-4)
in headonly mode and header has been received
#define PROTOHTTP_RECVWAIT (-3)
waiting for body data
Referenced by ProtoHttpRecv(), and ProtoHttpRecvAll().
#define PROTOHTTP_STREAM_BEGIN (-1)
start streaming upload (size unknown)
#define PROTOHTTP_STREAM_END (0)
streaming upload operation is complete
#define ProtoHttpRequest (_pState, _pUrl, _pData, _iDataSize, _eRequestType) ProtoHttpRequestCb(_pState, _pUrl, _pData, _iDataSize, _eRequestType, NULL, NULL)
Referenced by ProtoHttpDelete(), ProtoHttpGet(), ProtoHttpOptions(), and ProtoHttpPost().
Typedef Documentation
typedef int32_t(ProtoHttpCustomHeaderCbT)(ProtoHttpRefT *pState, char *pHeader, uint32_t uHeaderSize, const char *pData, int64_t iDataLen, void *pUserRef)
callback that may be used to customize request header before sending
typedef int32_t(ProtoHttpReceiveHeaderCbT)(ProtoHttpRefT *pState, const char *pHeader, uint32_t uHeaderSize, void *pUserRef)
callback that may be used to implement custom header parsing on header receipt
typedef struct ProtoHttpRefT ProtoHttpRefT
opaque module ref
typedef struct ProtoHttpWriteCbInfoT ProtoHttpWriteCbInfoT
write callback info
typedef int32_t(ProtoHttpWriteCbT)(ProtoHttpRefT *pState, const ProtoHttpWriteCbInfoT *pCbInfo, const char *pData, int32_t iDataSize, void *pUserData)
write data callback
Function Documentation
DIRTYCODE_API void ProtoHttpAbort (ProtoHttpRefT * pState)
Abort current operation, if any.
Parameters
*pState - reference pointer
Version
11/01/2012 (akirchner)
References ProtoHttpRefT::critical, ProtoHttpCriticalT::Locker, NetCritEnter(), and NetCritLeave().
DIRTYCODE_API void ProtoHttpCallback (ProtoHttpRefT * pState, ProtoHttpCustomHeaderCbT * pCustomHeaderCb, ProtoHttpReceiveHeaderCbT * pReceiveHeaderCb, void * pCallbackRef)
Set header callbacks.
Parameters
*pState - module state
*pCustomHeaderCb - pointer to custom send header callback (may be NULL)
*pReceiveHeaderCb- pointer to recv header callback (may be NULL)
*pCallbackRef - user-supplied callback ref (may be NULL)
Note
The ProtHttpCustomHeaderCbt callback is used to allow customization of the HTTP header before sending. It is more powerful than the append header functionality, allowing to make changes to any part of the header before it is sent. The callback should return a negative code if an error occurred, zero can be returned if the application wants ProtoHttp to calculate the header size, or the size of the header can be returned if the application has already calculated it. The header should not be terminated with the double \r\n that indicates the end of the entire header, as protohttp appends itself.
The ProtoHttpReceiveHeaderCbT callback is used to view the header immediately on reception. It can be used when the built-in header cache (retrieved with ProtoHttpStatus('htxt') is too small to hold the entire header received. It is also possible with this method to view redirection response headers that cannot be retrieved normally. This can be important if, for example, the application wishes to attach new cookies to a redirection response. The custom response header and custom header callback can be used in conjunction to implement this type of functionality.
Version
1.0 02/16/2007 (jbrookes)
References ProtoHttpRefT::pCallbackRef, ProtoHttpRefT::pCustomHeaderCb, and ProtoHttpRefT::pReceiveHeaderCb.
Referenced by HttpManagerCallback(), and ProtoStreamSetHttpCallback().
DIRTYCODE_API int32_t ProtoHttpCheckKeepAlive (ProtoHttpRefT * pState, const char * pUrl)
Checks whether a request for the given Url would be a keep-alive transaction. Unlike the 'generic' version, this version is not aware of the current connection status, only whether the previous request was made to the same host/port/security setting.
Parameters
*pState - reference pointer
*pUrl - Url to check
Returns
int32_t - TRUE if a request to this Url would use keep-alive, else FALSE
Version
07/18/2013 (jbrookes)
References ds_stricmp(), ProtoHttpRefT::iKeepAlive, ProtoHttpRefT::iPort, ProtoHttpRefT::iSecure, ProtoHttpUrlParse2(), and ProtoHttpRefT::strHost.
DIRTYCODE_API void ProtoHttpClrCACerts (void)
Clears all dynamic CA certs from the list.
Version
11/01/2012 (akirchner)
DIRTYCODE_API int32_t ProtoHttpControl (ProtoHttpRefT * pState, int32_t iSelect, int32_t iValue, int32_t iValue2, void * pValue)
ProtoHttp control function. Different selectors control different behaviors.
Parameters
*pState - reference pointer
iSelect - control selector ('time')
iValue - selector specific
iValue2 - selector specific
*pValue - selector specific
Returns
int32_t - selector specific
Note
Selectors are:
        SELECTOR    DESCRIPTION'
        'apnd'      The given buffer will be appended to future headers sent
                    by ProtoHttp.  Note that the User-Agent and Accept lines
                    in the default header will be replaced, so if these lines
                    are desired, they should be supplied in the append header.
        'auth'      Enables/disables authentication (default=enabled)
        'ires'      Resize input buffer
        'keep'      Sets keep-alive; zero=disabled, else enabled
        'maxr'      Sets max recv rate (bytes/sec; zero=uncapped)
        'maxs'      Sets max send rate (bytes/sec; zero=uncapped)
        'odth'      Sets ONDATA_THRESHOLD property (default=64k)
        'prxy'      Sets proxy server
        'rmax'      Sets maximum number of redirections (default=3)
        'spam'      Sets debug output verbosity (0...n)
        'time'      Sets ProtoHttp client timeout in milliseconds (default=30s)
        'xtok'      Sets XSTS token enable/disable (default=disabled; iValue=
                    enabled true/false, iValue2=user index, pValue=
                    token URN, only required if different from URL)
Version
07/02/2013 (jbrookes)
References ProtoHttpRefT::bAuthenticate, ProtoHttpRefT::bGetAuthToken, ProtoHttpRefT::critical, ds_strnzcpy(), FALSE, ProtoHttpRefT::iAuthTokenIdx, ProtoHttpBufferT::iInpMaxIdeal, ProtoHttpRefT::iKeepAlive, ProtoHttpRefT::iKeepAliveDflt, ProtoHttpRefT::iMaxRedirect, ProtoHttpRefT::iOnDataThreshold, ProtoHttpRefT::iVerbose, NetPrintf, NetPrintfVerbose, ProtoHttpRefT::RecvRate, ProtoHttpCriticalT::responseBuffer, ProtoHttpRefT::SendRate, ProtoHttpRefT::strProxy, ProtoHttpRefT::strTokenUrl, TRUE, SocketRateT::uMaxRate, and ProtoHttpRefT::uTimeout.
Referenced by _UserListApiProcessIsFriend(), HttpManagerControl(), ProtoStreamControl(), ProtoStreamCreate(), ProtoStreamPause(), ProtoUpnpControl(), ProtoUpnpCreate(), UserListApiIsFriendAsync(), and WebLogControl().
DIRTYCODE_API ProtoHttpRefT* ProtoHttpCreate (int32_t iBufSize)
Allocate module state and prepare for use.
Parameters
iBufSize - length of receive buffer
Returns
ProtoHttpRefT * - pointer to module state, or NULL
Version
07/02/2013 (jbrookes)
References ProtoHttpRefT::bAuthenticate, ProtoHttpRefT::critical, DirtyMemAlloc(), DirtyMemGroupQuery(), ProtoHttpHeaderT::iHdrCode, ProtoHttpBufferT::iInpMax, ProtoHttpBufferT::iInpMaxIdeal, ProtoHttpRefT::iMaxRedirect, ProtoHttpRefT::iMemGroup, ProtoHttpRefT::iOnDataThreshold, ProtoHttpRefT::iVerbose, ProtoHttpCriticalT::Locker, NetCritInit(), NetPrintf, ProtoHttpBufferT::pInpBuf, ProtoHttpRefT::pMemGroupUserData, PROTOHTTP_MAXREDIRECT, PROTOHTTP_MEMID, PROTOHTTP_TIMEOUT, ProtoHttpDestroy(), pState, ProtoHttpCriticalT::responseBuffer, ProtoHttpRefT::responseHeader, TRUE, and ProtoHttpRefT::uTimeout.
Referenced by DirtyCertCreate(), NetResourceCreate(), ProtoStreamCreate(), ProtoUpnpCreate(), UserListApiCreate(), WebLogCreate(), and WebOfferCreate().
DIRTYCODE_API int32_t ProtoHttpDelete (ProtoHttpRefT * pState, const char * pUrl)
Request deletion of a server-based resource.
Parameters
*pState - reference pointer
*pUrl - Url describing reference to delete
Returns
int32_t - negative=failure, zero=success
Version
11/01/2012 (akirchner)
References PROTOHTTP_REQUESTTYPE_DELETE, and ProtoHttpRequest.
DIRTYCODE_API void ProtoHttpDestroy (ProtoHttpRefT * pState)
Destroy the module and release its state.
Parameters
*pState - reference pointer
Version
07/12/2013 (jbrookes)
References ProtoHttpRefT::critical, ProtoHttpCriticalT::Locker, NetConnControl(), NetCritEnter(), NetCritLeave(), NetPrintf, and ProtoHttpCriticalT::pXmlHttp.
Referenced by DirtyCertDestroy(), NetResourceDestroy(), ProtoHttpCreate(), ProtoStreamDestroy(), ProtoUpnpDestroy(), WebLogDestroy(), and WebOfferDestroy().
DIRTYCODE_API int32_t ProtoHttpGet (ProtoHttpRefT * pState, const char * pUrl, uint32_t bHeadOnly)
Initiate an HTTP transfer. Pass in a URL and the module starts a getting data from the appropriate server.
Parameters
*pState - reference pointer
*pUrl - the url to retrieve
bHeadOnly - if TRUE only get header
Returns
int32_t - negative=failure, else success
Version
11/01/2012 (akirchner)
References PROTOHTTP_REQUESTTYPE_GET, PROTOHTTP_REQUESTTYPE_HEAD, and ProtoHttpRequest.
Referenced by _UserListApiProcessIsFriend(), ProtoUpnpControl(), UserListApiIsFriendAsync(), WebOfferHttp(), and WebOfferUpdate().
DIRTYCODE_API int32_t ProtoHttpGetLocationHeader (ProtoHttpRefT * pState, const char * pInpBuf, char * pBuffer, int32_t iBufSize, const char ** pHdrEnd)
Get location header from the input buffer. The Location header requires some special processing.
Parameters
*pState - reference pointer
*pInpBuf - buffer holding header text
*pBuffer - [out] output buffer for parsed location header, null for size request
iBufSize - size of output buffer, zero for size request
**pHdrEnd- [out] pointer past end of parsed header (optional)
Returns
int32_t - negative=header not received, not found or not enough space, zero=success, positive=size query result
Version
03/24/2009 (jbrookes)
References ds_snzprintf(), ds_strnicmp(), ds_strnzcat(), ds_strnzcpy(), ProtoHttpRefT::iPort, ProtoHttpRefT::iSecure, ProtoHttpExtractHeaderValue(), ProtoHttpFindHeaderValue(), ProtoHttpRefT::responseHeader, ProtoHttpHeaderT::strHdr, and ProtoHttpRefT::strHost.
DIRTYCODE_API int32_t ProtoHttpOptions (ProtoHttpRefT * pState, const char * pUrl)
Request options from a server.
Parameters
*pState - reference pointer
*pUrl - Url describing reference to get options on
Returns
int32_t - negative=failure, zero=success
Version
11/01/2012 (akirchner)
References PROTOHTTP_REQUESTTYPE_OPTIONS, and ProtoHttpRequest.
DIRTYCODE_API int32_t ProtoHttpPost (ProtoHttpRefT * pState, const char * pUrl, const char * pData, int64_t iDataSize, uint32_t bDoPut)
Initiate transfer of data to to the server via a HTTP POST command.
Parameters
*pState - reference pointer
*pUrl - the URL that identifies the POST action.
*pData - pointer to URL data (optional, may be NULL)
iDataSize - size of data being uploaded (see Notes below)
bDoPut - meanless on xboxone
Returns
int32_t - negative=failure, else number of data bytes sent
Note
Any data that is not sent as part of the Post transaction should be sent with ProtoHttpSend(). ProtoHttpSend() should be called at poll rate (i.e. similar to how often ProtoHttpUpdate() is called) until all of the data has been sent. The amount of data bytes actually sent is returned by the function.
If pData is not NULL and iDataSize is less than or equal to zero, iDataSize will be recalculated as the string length of pData, to allow for easy string sending.
Version
11/01/2012 (akirchner)
References PROTOHTTP_REQUESTTYPE_POST, PROTOHTTP_REQUESTTYPE_PUT, and ProtoHttpRequest.
Referenced by WebOfferHttp().
DIRTYCODE_API int32_t ProtoHttpRecv (ProtoHttpRefT * pState, char * pBuffer, int32_t iBufMin, int32_t iBufMax)
Return the actual url data.
Parameters
*pState - reference pointer
*pBuffer - buffer to store data in
iBufMin - minimum number of bytes to return (returns zero if this number is not available)
iBufMax - maximum number of bytes to return (buffer size)
Returns
int32_t - negative=error, zero=no data available or bufmax <= 0, positive=number of bytes read
Version
07/02/2013 (jbrookes)
References ProtoHttpRefT::critical, ds_memcpy(), ProtoHttpCriticalT::eRequestState, ProtoHttpBufferT::iInpLen, ProtoHttpBufferT::iInpMax, ProtoHttpRefT::iVerbose, ProtoHttpCriticalT::Locker, NetCritLeave(), NetCritTry(), NetPrintf, NetPrintMem, ProtoHttpBufferT::pInpBuf, PROTOHTTP_RECVDONE, PROTOHTTP_RECVFAIL, PROTOHTTP_RECVWAIT, ProtoHttpCriticalT::responseBuffer, ST_BODY, ST_DONE, and ST_FAIL.
Referenced by HttpManagerRecv(), ProtoHttpRecvAll(), and WebOfferUpdate().
DIRTYCODE_API int32_t ProtoHttpRecvAll (ProtoHttpRefT * pState, char * pBuffer, int32_t iBufSize)
Return all of the url data.
Parameters
*pState - reference pointer
*pBuffer - buffer to store data in
iBufSize - size of buffer
Returns
int32_t - PROTOHTTP_RECV*, or positive=bytes in response
Version
12/14/2005 (jbrookes)
References ProtoHttpRefT::iRecvSize, NetPrintf, PROTOHTTP_RECVBUFF, PROTOHTTP_RECVDONE, PROTOHTTP_RECVWAIT, and ProtoHttpRecv().
Referenced by HttpManagerRecvAll(), and UserListApiUpdate().
DIRTYCODE_API int32_t ProtoHttpRequestCb (ProtoHttpRefT * pState, const char * pUrl, const char * pData, int64_t iDataSize, ProtoHttpRequestTypeE eRequestType, ProtoHttpWriteCbT * pWriteCb, void * pWriteCbUserData)
Initiate an HTTP transfer. Pass in a URL and the module starts a transfer from the appropriate server. Use ProtoHttpRequest() macro wrapper if write callback is not required.
Parameters
*pState - reference pointer
*pUrl - the url to retrieve
*pData - user data to send to server (PUT and POST only)
iDataSize - size of user data to send to server (PUT and POST only)
eRequestType - request type to make
*pWriteCb - write callback (optional)
*pWriteCbUserData - write callback user data (optional)
Returns
int32_t - negative=failure, zero=success, >0=number of data bytes sent (PUT and POST only)
Version
07/12/2013 (jbrookes)
References ProtoHttpRefT::bGetAuthToken, ProtoHttpRefT::critical, DirtyAuthGetToken(), ds_strnzcpy(), ProtoHttpCriticalT::eRequestState, ProtoHttpRefT::eRequestType, FALSE, ProtoHttpRefT::iAuthTokenIdx, ProtoHttpBufferT::iInpMaxIdeal, ProtoHttpCriticalT::iRequestSize, ProtoHttpCriticalT::Locker, NetCritEnter(), NetCritLeave(), NetPrintf, NetTick(), PROTOHTTP_NUMREQUESTTYPES, ProtoHttpRefT::pWriteCb, ProtoHttpRefT::pWriteCbUserData, ProtoHttpCriticalT::pXmlHttp, ProtoHttpCriticalT::responseBuffer, ST_AUTH, ST_CONN, ST_FAIL, ProtoHttpRefT::strHost, ProtoHttpRefT::strTokenUrl, ProtoHttpRefT::uTimeout, and ProtoHttpRefT::uTimer.
DIRTYCODE_API int32_t ProtoHttpSend (ProtoHttpRefT * pState, const char * pData, int32_t iDataSize)
Send data during an ongoing Post transaction.
Parameters
*pState - reference pointer
*pData - pointer to data to send
iDataSize - size of data being sent
Returns
int32_t - negative=failure, else number of data bytes sent
Version
07/15/2013 (jbrookes)
References ProtoHttpRefT::critical, ProtoHttpCriticalT::eRequestState, ProtoHttpCriticalT::Locker, NetCritLeave(), NetCritTry(), NetPrintf, and ST_RESP.
Referenced by HttpManagerSend().
DIRTYCODE_API void ProtoHttpSetBaseUrl (ProtoHttpRefT * pState, const char * pUrl)
Set base url that will be used for any relative url references.
Parameters
*pState - module state
*pUrl - base url
Version
02/03/2010 (jbrookes)
References ds_strnzcpy(), ProtoHttpRefT::iBasePort, ProtoHttpRefT::iBaseSecure, NetPrintf, ProtoHttpUrlParse2(), ProtoHttpRefT::strBaseHost, and ProtoHttpRefT::strHost.
Referenced by HttpManagerSetBaseUrl().
DIRTYCODE_API int32_t ProtoHttpSetCACert (const uint8_t * pCACert, int32_t iCertSize)
Add one or more X.509 CA certificates to the trusted list. A certificate added will be available to all HTTP instances for the lifetime of the application. This function can add one or more PEM certificates or a single DER certificate.
Parameters
*pCACert - pointer to certificate data
iCertSize- certificate size in bytes
Returns
int32_t - negative=failure, zero=success
Version
11/01/2012 (akirchner)
DIRTYCODE_API int32_t ProtoHttpSetCACert2 (const uint8_t * pCACert, int32_t iCertSize)
Add one or more X.509 CA certificates to the trusted list. A certificate added will be available to all HTTP instances for the lifetime of the application. This function can add one or more PEM certificates or a single DER certificate.
This version of the function does not validate the CA at load time.
The X509 certificate data will be copied and retained until the CA
is validated, either by use of ProtoHttpValidateAllCA() or by the CA
being used to validate a certificate.
Parameters
*pCACert - pointer to certificate data
iCertSize- certificate size in bytes
Returns
int32_t - negative=failure, zero=success
Version
11/01/2012 (akirchner)
DIRTYCODE_API int32_t ProtoHttpStatus (ProtoHttpRefT * pState, int32_t iSelect, void * pBuffer, int32_t iBufSize)
Return status of current HTTP transfer. Status type depends on selector.
Parameters
*pState - reference pointer
iSelect - info selector (see Notes)
*pBuffer - [out] storage for selector-specific output
iBufSize - size of buffer
Returns
int32_t - selector specific
Note
Selectors are:
    SELECTOR    RETURN RESULT
    'body'      negative=failed or pending, else size of body (for 64bit size, get via pBuffer)
    'code'      negative=no response, else server response code (ProtoHttpResponseE)
    'data'      negative=failed, zero=pending, positive=amnt of data ready
    'date'      last-modified date, if available
    'done'      negative=failed, zero=pending, positive=done
    'head'      returns size of header
    'host'      current host copied to output buffer
    'hres'      return hResult containing either the socket error or ssl error or the http status code
    'htxt'      current received http header text copied to output buffer
    'info'      copies most recent info header received, if any, to output buffer (one time only)
    'imax'      size of input buffer
    'iovr'      returns input buffer overflow size (valid on PROTOHTTP_MINBUFF result code)
    'maxr'      returns configured max recv rate (bytes/sec; zero=uncapped)
    'maxs'      returns configured max send rate (bytes/sec; zero=uncapped)
    'port'      current port
    'rmax'      returns currently configured max redirection count
    'rtxt'      most recent http request header text copied to output buffer
    'time'      TRUE if the client timed out the connection, else FALSE
Version
07/02/2013 (jbrookes)
References ProtoHttpCriticalT::bTimeout, ProtoHttpRefT::critical, DIRTYAPI_PROTO_HTTP, DirtyErrGetHResult(), ds_memcpy(), ds_strnzcpy(), ProtoHttpCriticalT::eRequestState, FALSE, ProtoHttpHeaderT::iBodySize, ProtoHttpHeaderT::iHdrCode, ProtoHttpHeaderT::iHdrDate, ProtoHttpHeaderT::iHeadSize, ProtoHttpBufferT::iInpLen, ProtoHttpBufferT::iInpMax, ProtoHttpBufferT::iInpOvr, ProtoHttpRefT::iMaxRedirect, ProtoHttpRefT::iPort, ProtoHttpRefT::iVerbose, ProtoHttpCriticalT::Locker, NetCritEnter(), NetCritLeave(), NetPrintfVerbose, PROTOHTTP_RESPONSE_CLIENTERROR, ProtoHttpRefT::RecvRate, ProtoHttpCriticalT::responseBuffer, ProtoHttpRefT::responseHeader, ProtoHttpRefT::SendRate, ST_DONE, ST_FAIL, ST_IDLE, ProtoHttpHeaderT::strHdr, ProtoHttpRefT::strHost, ProtoHttpRefT::strRequestHdr, TRUE, and SocketRateT::uMaxRate.
Referenced by HttpManagerStatus(), ProtoStreamStatus(), ProtoUpnpStatus(), UserListApiUpdate(), and WebOfferUpdate().
DIRTYCODE_API void ProtoHttpUpdate (ProtoHttpRefT * pState)
Give time to module to do its thing (should be called periodically to allow module to perform work)
Parameters
*pState - reference pointer
Version
11/01/2012 (akirchner)
References ProtoHttpCriticalT::bBodyReceived, ProtoHttpCriticalT::bHeaderReceived, ProtoHttpCriticalT::bRedirBugWorkaround, ProtoHttpCriticalT::bTimeout, ProtoHttpRefT::critical, DirtyAuthCheckToken(), ProtoHttpCriticalT::eRequestState, ProtoHttpRefT::eRequestType, FALSE, ProtoHttpHeaderT::iBodySize, ProtoHttpBufferT::iInpTotal, ProtoHttpCriticalT::iRequestSize, ProtoHttpRefT::iVerbose, ProtoHttpCriticalT::Locker, NetCritLeave(), NetCritTry(), NetPrintf, NetPrintfVerbose, NetTick(), NetTickDiff, NULL, PROTOHTTP_REQUESTTYPE_GET, ProtoHttpRefT::pWriteCb, ProtoHttpCriticalT::pXmlHttp, ProtoHttpCriticalT::responseBuffer, ProtoHttpRefT::responseHeader, ST_AUTH, ST_BODY, ST_CONN, ST_DONE, ST_FAIL, ST_HEAD, ST_IDLE, ST_RESP, ProtoHttpRefT::strLocation, ProtoHttpRefT::strTokenUrl, TRUE, and ProtoHttpRefT::uTimer.
Referenced by HttpManagerRecv(), HttpManagerUpdate(), ProtoStreamUpdate(), UserListApiUpdate(), WebLogUpdate(), and WebOfferUpdate().
DIRTYCODE_API int32_t ProtoHttpValidateAllCA (void)
Validate all CA that have been added but not yet been validated. Validation is a one-time process and disposes of the X509 certificate that is retained until validation.
Returns
int32_t - negative=failure, zero=success
Version
11/01/2012 (akirchner)
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:21