DirtySock: ProtoHttpManager
ProtoHttpManager
Proto
Data Structures
struct HttpManagerStatT
httpmanager stats
Macros
#define HttpManagerRequest(_pHttpManager, _iHandle, _pUrl, _pData, _iDataSize, _eRequestType) HttpManagerRequestCb(_pHttpManager, _iHandle, _pUrl, _pData, _iDataSize, _eRequestType, NULL, NULL)
Typedefs
typedef struct HttpManagerStatT HttpManagerStatT
httpmanager stats
typedef struct HttpManagerRefT HttpManagerRefT
opaque module ref
Functions
DIRTYCODE_API HttpManagerRefT * HttpManagerCreate (int32_t iHttpBufSize, int32_t iHttpNumRefs)
Allocate module state and prepare for use.
DIRTYCODE_API void HttpManagerCallback (HttpManagerRefT *pHttpManager, ProtoHttpCustomHeaderCbT *pCustomHeaderCb, ProtoHttpReceiveHeaderCbT *pReceiveHeaderCb)
Set header callbacks.
DIRTYCODE_API void HttpManagerDestroy (HttpManagerRefT *pHttpManager)
Destroy the module and release its state.
DIRTYCODE_API int32_t HttpManagerAlloc (HttpManagerRefT *pHttpManager)
Allocate a new transaction handle.
DIRTYCODE_API void HttpManagerFree (HttpManagerRefT *pHttpManager, int32_t iHandle)
Release a new transaction handle.
DIRTYCODE_API int32_t HttpManagerGet (HttpManagerRefT *pHttpManager, int32_t iHandle, const char *pUrl, uint32_t bHeadOnly)
Initiate an HTTP transaction. Pass in a URL and the module starts a transfer from the appropriate server.
DIRTYCODE_API int32_t HttpManagerRecv (HttpManagerRefT *pHttpManager, int32_t iHandle, char *pBuffer, int32_t iBufMin, int32_t iBufMax)
Return the actual url data.
DIRTYCODE_API int32_t HttpManagerRecvAll (HttpManagerRefT *pHttpManager, int32_t iHandle, char *pBuffer, int32_t iBufSize)
Return all of the url data.
DIRTYCODE_API int32_t HttpManagerPost (HttpManagerRefT *pHttpManager, int32_t iHandle, const char *pUrl, const char *pData, int64_t iDataSize, uint32_t bDoPut)
Initiate transfer of data to to the server via a HTTP POST command.
DIRTYCODE_API int32_t HttpManagerSend (HttpManagerRefT *pHttpManager, int32_t iHandle, const char *pData, int32_t iDataSize)
Send data during an ongoing Post transaction.
DIRTYCODE_API int32_t HttpManagerRequestCb (HttpManagerRefT *pHttpManager, int32_t iHandle, const char *pUrl, const char *pData, int64_t iDataSize, ProtoHttpRequestTypeE eRequestType, ProtoHttpWriteCbT *pWriteCb, void *pWriteCbUserData)
Make an HTTP request.
DIRTYCODE_API void HttpManagerSetBaseUrl (HttpManagerRefT *pHttpManager, int32_t iHandle, const char *pUrl)
Set base url that will be used for any relative url references.
DIRTYCODE_API int32_t HttpManagerControl (HttpManagerRefT *pHttpManager, int32_t iHandle, int32_t iSelect, int32_t iValue, int32_t iValue2, void *pValue)
HttpManager control function. Different selectors control different behaviors.
DIRTYCODE_API int32_t HttpManagerStatus (HttpManagerRefT *pHttpManager, int32_t iHandle, int32_t iSelect, void *pBuffer, int32_t iBufSize)
Return status of current HTTP transfer. Status type depends on selector.
DIRTYCODE_API void HttpManagerUpdate (HttpManagerRefT *pHttpManager)
Give time to module to do its thing (should be called periodically to allow module to perform work)
Detailed Description
Macro Definition Documentation
#define HttpManagerRequest (_pHttpManager, _iHandle, _pUrl, _pData, _iDataSize, _eRequestType) HttpManagerRequestCb(_pHttpManager, _iHandle, _pUrl, _pData, _iDataSize, _eRequestType, NULL, NULL)
Typedef Documentation
typedef struct HttpManagerRefT HttpManagerRefT
opaque module ref
typedef struct HttpManagerStatT HttpManagerStatT
httpmanager stats
Function Documentation
DIRTYCODE_API int32_t HttpManagerAlloc (HttpManagerRefT * pHttpManager)
Allocate a new transaction handle.
Parameters
*pHttpManager - reference pointer
Returns
int32_t - negative=failure, else transaction handle
Version
05/20/2009 (jbrookes)
References HttpManagerHttpCmdT::iHttpHandle, HttpManagerRefT::iVerbose, NetPrintf, and NetPrintfVerbose.
DIRTYCODE_API void HttpManagerCallback (HttpManagerRefT * pHttpManager, ProtoHttpCustomHeaderCbT * pCustomHeaderCb, ProtoHttpReceiveHeaderCbT * pReceiveHeaderCb)
Set header callbacks.
Parameters
*pHttpManager - module state
*pCustomHeaderCb - pointer to custom send header callback
*pReceiveHeaderCb- pointer to recv header callback
Note
See ProtoHttpCallback documentation for a description of the callbacks specified here.
Version
05/20/2009 (jbrookes)
References HttpManagerRefT::HttpRefs, HttpManagerRefT::iHttpNumRefs, HttpManagerRefT::pCustomHeaderCb, HttpManagerHttpRefT::pProtoHttp, HttpManagerRefT::pReceiveHeaderCb, and ProtoHttpCallback().
DIRTYCODE_API int32_t HttpManagerControl (HttpManagerRefT * pHttpManager, int32_t iHandle, int32_t iSelect, int32_t iValue, int32_t iValue2, void * pValue)
HttpManager control function. Different selectors control different behaviors.
Parameters
*pHttpManager - reference pointer
iHandle - transaction handle
iSelect - control selector
iValue - selector specific
iValue2 - selector specific
*pValue - selector specific
Returns
int32_t - selector specific
Note
If a handle is specified (iHandle > 0), HttpManagerControl() will forward the call to ProtoHttpControl() for the appropriate ref. HttpManager control selectors are as follows:
        SELECTOR    DESCRIPTION
        'apnd'      Header append feature (see ProtoHttp doc for details).  If a
                    handle is specified the scope is command-specific, otherwise
                    it is global.  A command-specific append header takes
                    precedence over a global append header.
        'auto'      enable/disable auto-update (polling of HttpManagerUpdate by
                    NetConnIdle(); default enabled)
        'cbup'      sets callback user data pointer (pValue=callback)
        'copy'      sets if urls are copied internally or not (default=true)
        'maxp'      sets max pipeline depth (default 4)
        'pipe'      pipelining enable/disable
        'pwka'      pipelining without keep-alive enable/disable
        'spam'      manager-level debug verbosity
        'stcl'      clear httpmanager stats.
        'xhtp'      enable xhttp (xbox 360 only, global only) (default=disabled)
Version
05/20/2009 (jbrookes)
References HttpManagerRefT::bAutoUpdate, HttpManagerRefT::bCopyUrl, HttpManagerRefT::bPipelining, HttpManagerRefT::bPipeWithoutKeepAlive, FALSE, HTTPMANAGER_CMDSTATE_IDLE, HttpManagerRefT::HttpRefs, HttpManagerRefT::iHttpNumRefs, HttpManagerRefT::iMaxPipedUrls, HttpManagerHttpCmdT::iTimeout, HttpManagerRefT::iVerbose, NetPrintf, NetPrintfVerbose, HttpManagerHttpCmdT::pCallbackRef, HttpManagerHttpCmdT::pHttpRef, HttpManagerHttpRefT::pProtoHttp, ProtoHttpControl(), TRUE, and HttpManagerHttpCmdT::uState.
DIRTYCODE_API HttpManagerRefT* HttpManagerCreate (int32_t iHttpBufSize, int32_t iHttpNumRefs)
Allocate module state and prepare for use.
Parameters
iHttpBufSize - length of receive buffer for each protohttp ref
iHttpNumRefs - number of protohttp modules to allocate
Returns
HttpManagerRefT * - pointer to module state, or NULL
Version
05/20/2009 (jbrookes)
References HttpManagerRefT::bAutoUpdate, HttpManagerRefT::bCopyUrl, HttpManagerRefT::bKeepalive, HttpManagerRefT::bPipelining, HttpManagerRefT::bPipeWithoutKeepAlive, DirtyMemAlloc(), DirtyMemGroupQuery(), HTTPMANAGER_MAXREFS, HttpManagerDestroy(), HTTPMGR_MEMID, HttpManagerRefT::iHttpBufSize, HttpManagerRefT::iHttpHandle, HttpManagerRefT::iMaxPipedUrls, HttpManagerRefT::iMemGroup, HttpManagerRefT::iVerbose, NetConnIdleAdd(), NetPrintf, NetTick(), HttpManagerRefT::pMemGroupUserData, and TRUE.
DIRTYCODE_API void HttpManagerDestroy (HttpManagerRefT * pHttpManager)
Destroy the module and release its state.
Parameters
*pHttpManager - reference pointer
Version
05/20/2009 (jbrookes)
References DirtyMemFree(), HttpManagerRefT::HttpCmds, HTTPMANAGER_MAXCMDS, HttpManagerFree(), HTTPMGR_MEMID, HttpManagerHttpCmdT::iHttpHandle, HttpManagerRefT::iHttpNumRefs, HttpManagerRefT::iMemGroup, HttpManagerRefT::iVerbose, NetConnIdleDel(), NetPrintfVerbose, HttpManagerRefT::pAppendHdr, and HttpManagerRefT::pMemGroupUserData.
Referenced by HttpManagerCreate().
DIRTYCODE_API void HttpManagerFree (HttpManagerRefT * pHttpManager, int32_t iHandle)
Release a new transaction handle.
Parameters
*pHttpManager - reference pointer
iHandle - transaction handle
Version
05/20/2009 (jbrookes)
References HttpManagerHttpCmdT::bCopiedUrl, DirtyMemFree(), HTTPMGR_MEMID, HttpManagerRefT::iMemGroup, HttpManagerRefT::iVerbose, NetPrintf, NetPrintfVerbose, HttpManagerHttpCmdT::pAppendHdr, HttpManagerRefT::pMemGroupUserData, HttpManagerHttpCmdT::pUrl, and TRUE.
Referenced by HttpManagerDestroy().
DIRTYCODE_API int32_t HttpManagerGet (HttpManagerRefT * pHttpManager, int32_t iHandle, const char * pUrl, uint32_t bHeadOnly)
Initiate an HTTP transaction. Pass in a URL and the module starts a transfer from the appropriate server.
Parameters
*pHttpManager - module state
iHandle - transaction handle
*pUrl - the url to retrieve
bHeadOnly - if TRUE only get header
Returns
int32_t - negative=failure, else success
Version
05/20/2009 (jbrookes)
References PROTOHTTP_REQUESTTYPE_GET, and PROTOHTTP_REQUESTTYPE_HEAD.
DIRTYCODE_API int32_t HttpManagerPost (HttpManagerRefT * pHttpManager, int32_t iHandle, const char * pUrl, const char * pData, int64_t iDataSize, uint32_t bDoPut)
Initiate transfer of data to to the server via a HTTP POST command.
Parameters
*pHttpManager - reference pointer
iHandle - transaction handle
*pUrl - the URL that identifies the POST action.
*pData - pointer to URL data (optional, may be NULL)
iDataSize - size of data being uploaded (see Notes)
bDoPut - if TRUE, do a PUT instead of a POST
Returns
int32_t - negative=failure, else number of data bytes sent
Note
See ProtoHttpPost() documentation.
Version
05/20/2009 (jbrookes)
References PROTOHTTP_REQUESTTYPE_POST, and PROTOHTTP_REQUESTTYPE_PUT.
DIRTYCODE_API int32_t HttpManagerRecv (HttpManagerRefT * pHttpManager, int32_t iHandle, char * pBuffer, int32_t iBufMin, int32_t iBufMax)
Return the actual url data.
Parameters
*pHttpManager - reference pointer
iHandle - transaction handle (returned by HttpManagerGet())
*pBuffer - buffer to store data in
iBufMin - minimum number of bytes to return (returns zero if this number is not available)
iBufMax - maximum number of bytes to return (buffer size)
Returns
int32_t - negative=error, zero=no data available or bufmax <= 0, positive=number of bytes read
Version
05/20/2009 (jbrookes)
References HTTPMANAGER_CMDSTATE_ACTV, HTTPMANAGER_CMDSTATE_FAIL, HttpManagerRefT::HttpRefs, HttpManagerHttpCmdT::iResult, HttpManagerRefT::iVerbose, NetPrintf, NetPrintfVerbose, NetTick(), NetTickDiff, HttpManagerHttpCmdT::pHttpRef, HttpManagerHttpRefT::pProtoHttp, PROTOHTTP_MINBUFF, PROTOHTTP_RECVFAIL, ProtoHttpRecv(), ProtoHttpUpdate(), HttpManagerHttpCmdT::uBytesXfer, HttpManagerHttpRefT::uLastTick, and HttpManagerHttpCmdT::uState.
DIRTYCODE_API int32_t HttpManagerRecvAll (HttpManagerRefT * pHttpManager, int32_t iHandle, char * pBuffer, int32_t iBufSize)
Return all of the url data.
Parameters
*pHttpManager - reference pointer
iHandle - transaction handle (returned by HttpManagerGet())
*pBuffer - buffer to store data in
iBufSize - size of buffer
Returns
int32_t - PROTOHTTP_RECV*, or positive=bytes in response
Version
05/20/2009 (jbrookes)
References HTTPMANAGER_CMDSTATE_ACTV, HttpManagerHttpCmdT::iResult, NetPrintf, HttpManagerHttpCmdT::pHttpRef, HttpManagerHttpRefT::pProtoHttp, PROTOHTTP_MINBUFF, ProtoHttpRecvAll(), and HttpManagerHttpCmdT::uState.
DIRTYCODE_API int32_t HttpManagerRequestCb (HttpManagerRefT * pHttpManager, int32_t iHandle, const char * pUrl, const char * pData, int64_t iDataSize, ProtoHttpRequestTypeE eRequestType, ProtoHttpWriteCbT * pWriteCb, void * pWriteCbUserData)
Make an HTTP request.
Parameters
*pHttpManager - reference pointer
iHandle - transaction handle
*pUrl - the URL that identifies the POST action.
*pData - pointer to URL data (optional, may be NULL)
iDataSize - size of data being uploaded
eRequestType - http request type
*pWriteCb - write callback (optional)
*pWriteCbUserData- user data for write callback
Returns
int32_t - $$todo$$
Version
05/20/2009 (jbrookes)
DIRTYCODE_API int32_t HttpManagerSend (HttpManagerRefT * pHttpManager, int32_t iHandle, const char * pData, int32_t iDataSize)
Send data during an ongoing Post transaction.
Parameters
*pHttpManager - reference pointer
iHandle - transaction handle
*pData - pointer to data to send
iDataSize - size of data being sent
Returns
int32_t - negative=failure, else number of data bytes sent
Version
05/20/2009 (jbrookes)
References HTTPMANAGER_CMDSTATE_ACTV, NetPrintf, HttpManagerHttpCmdT::pHttpRef, HttpManagerHttpRefT::pProtoHttp, ProtoHttpSend(), and HttpManagerHttpCmdT::uState.
DIRTYCODE_API void HttpManagerSetBaseUrl (HttpManagerRefT * pHttpManager, int32_t iHandle, const char * pUrl)
Set base url that will be used for any relative url references.
Parameters
*pHttpManager - reference pointer
iHandle - handle to set base url for
*pUrl - base url
Version
02/03/2010 (jbrookes)
References NetPrintf, HttpManagerHttpCmdT::pHttpRef, HttpManagerHttpRefT::pProtoHttp, and ProtoHttpSetBaseUrl().
DIRTYCODE_API int32_t HttpManagerStatus (HttpManagerRefT * pHttpManager, int32_t iHandle, int32_t iSelect, void * pBuffer, int32_t iBufSize)
Return status of current HTTP transfer. Status type depends on selector.
Parameters
*pHttpManager - reference pointer
iHandle - transaction handle
iSelect - info selector (see Notes)
*pBuffer - [in/out] input and/or storage for selector-specific output
iBufSize - size of buffer
Returns
int32_t - selector specific
Note
If a handle is specified, HttpManagerStatus() will call ProtoHttpStatus() for the appropriate ref. HttpManager status selectors are as follows:
        SELECTOR    DESCRIPTION
        'busy'      Returns number of busy refs
        'hndl'      Get HttpManager handle from ProtoHttp ref (passed in pBuffer)
        'href'      Get ProtoHttp ref from HttpManager handle (returned in pBuffer, if specified)
        'stat'      If pBuffer is NULL, display httpmanager stats (debug only); else copy stats to output buffer
        'urls'      Copies url from specified command into output buffer
Version
05/20/2009 (jbrookes)
References ds_memcpy(), ds_strnzcpy(), HttpManagerHttpRefT::HttpCmdQueue, HTTPMANAGER_CMDSTATE_ACTV, HTTPMANAGER_REFSTATE_BUSY, HttpManagerRefT::HttpManagerStats, HttpManagerRefT::HttpRefs, HttpManagerHttpRefT::iCurTransaction, HttpManagerHttpCmdT::iHttpHandle, HttpManagerRefT::iHttpNumRefs, NetPrintf, HttpManagerHttpCmdT::pHttpRef, HttpManagerHttpRefT::pProtoHttp, ProtoHttpStatus(), HttpManagerHttpCmdT::pUrl, HttpManagerHttpRefT::uHttpState, and HttpManagerHttpCmdT::uState.
DIRTYCODE_API void HttpManagerUpdate (HttpManagerRefT * pHttpManager)
Give time to module to do its thing (should be called periodically to allow module to perform work)
Parameters
*pHttpManager - reference pointer
Version
05/20/2009 (jbrookes)
References HttpManagerHttpRefT::HttpCmdQueue, HttpManagerRefT::HttpCmds, HTTPMANAGER_CMDSTATE_ACTV, HTTPMANAGER_CMDSTATE_IDLE, HTTPMANAGER_CMDSTATE_WAIT, HTTPMANAGER_MAXCMDS, HTTPMANAGER_REFSTATE_BUSY, HTTPMANAGER_REFSTATE_IDLE, HttpManagerRefT::HttpRefs, HttpManagerHttpCmdT::iHttpHandle, HttpManagerRefT::iHttpNumRefs, HttpManagerHttpRefT::iTransactions, HttpManagerRefT::iVerbose, NetPrintfVerbose, NetTick(), NetTickDiff, HttpManagerHttpCmdT::pHttpRef, HttpManagerHttpRefT::pProtoHttp, ProtoHttpUpdate(), HttpManagerHttpCmdT::pUrl, HttpManagerHttpCmdT::pWriteCb, HttpManagerHttpRefT::uHttpState, HttpManagerHttpRefT::uLastTick, and HttpManagerHttpCmdT::uState.
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:17