DirtySock: DirtyAddr
DirtyAddr
DirtySock
Data Structures
struct DirtyAddrT
opaque address type
Macros
#define DIRTYADDR_MACHINEADDR_MAXLEN (127)
#define DIRTYADDR_MACHINEADDR_MAXSIZE (DIRTYADDR_MACHINEADDR_MAXLEN + 1)
#define DirtyAddrCompare(_pAddr1, _pAddr2) (!strcmp((_pAddr1)->strMachineAddr, (_pAddr2)->strMachineAddr))
compare two opaque addresses for equality (same=TRUE, different=FALSE)
Typedefs
typedef struct DirtyAddrT DirtyAddrT
opaque address type
Functions
DIRTYCODE_API uint32_t DirtyAddrToHostAddr (void *pOutput, int32_t iBufLen, const DirtyAddrT *pAddr)
convert a DirtyAddrT to native format
DIRTYCODE_API uint32_t DirtyAddrFromHostAddr (DirtyAddrT *pAddr, const void *pInput)
convert a host-format address to native format
DIRTYCODE_API uint32_t DirtyAddrGetLocalAddr (DirtyAddrT *pAddr)
get local address in DirtyAddr form
Detailed Description
Macro Definition Documentation
#define DIRTYADDR_MACHINEADDR_MAXLEN (127)
#define DIRTYADDR_MACHINEADDR_MAXSIZE (DIRTYADDR_MACHINEADDR_MAXLEN + 1)
#define DirtyAddrCompare (_pAddr1, _pAddr2) (!strcmp((_pAddr1)->strMachineAddr, (_pAddr2)->strMachineAddr))
compare two opaque addresses for equality (same=TRUE, different=FALSE)
Referenced by PingManagerCancelRequest().
Typedef Documentation
typedef struct DirtyAddrT DirtyAddrT
opaque address type
Function Documentation
DIRTYCODE_API uint32_t DirtyAddrFromHostAddr (DirtyAddrT * pAddr, const void * pInput)
convert a host-format address to native format
convert a host-format address to native format
Parameters
*pAddr - [out] storage for output DirtyAddrT
*pInput - pointer to native format address
Returns
uint32_t - TRUE if successful, else FALSE
Note
On Xbox One, a DirtyAddrT is a string-encoded network-order XUID.qwUserID field. This function converts that abinary-encoded host-order XUID.qwUserID to a DirtyAddrT.
Version
04/09/2004 (jbrookes)
References FALSE, NULL, DirtyAddrT::strMachineAddr, and TRUE.
Referenced by DirtyAddrGetLocalAddr(), DirtyAddrSetInfoXboxOne(), and ProtoPingResponse().
DIRTYCODE_API uint32_t DirtyAddrGetLocalAddr (DirtyAddrT * pAddr)
get local address in DirtyAddr form
get local address in DirtyAddr form
Parameters
*pAddr - [out] storage for output DirtyAddrT
Returns
uint32_t - TRUE if successful, else FALSE
Version
09/29/2004 (jbrookes)
References DirtyAddrFromHostAddr(), FALSE, NetConnStatus(), and TRUE.
DIRTYCODE_API uint32_t DirtyAddrToHostAddr (void * pOutput, int32_t iBufLen, const DirtyAddrT * pAddr)
convert a DirtyAddrT to native format
convert a DirtyAddrT to native format
Parameters
*pOutput - [out] storage for native format address
iBufLen - length of output buffer
*pAddr - source address to convert
Returns
uint32_t - TRUE if successful, else FALSE
Note
On Xbox One, a DirtyAddrT is a string-encoded network-order XUID.qwUserID field. This function converts that input to a binary-encoded host-order XUID.qwUserID.
Version
04/09/2004 (jbrookes)
References ds_memcpy(), FALSE, NetPrintf, DirtyAddrT::strMachineAddr, and TRUE.
Referenced by DirtyAddrGetInfoXboxOne(), and ProtoPingRequest().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:20