DirtySock: ProtoUdp
ProtoUdp
Proto
Macros
#define ProtoUdpRecv(_pUdp, _pData, _uSize) ProtoUdpRecvFrom(_pUdp, _pData, _uSize, NULL);
wrapper for ProtoUdpRecvFrom
Typedefs
typedef struct ProtoUdpT ProtoUdpT
Functions
DIRTYCODE_API ProtoUdpT * ProtoUdpCreate (int32_t iMaxPacketSize, int32_t iMaxPackets)
Create a proto udp instance.
DIRTYCODE_API int32_t ProtoUdpBind (ProtoUdpT *pUdp, int32_t iLocalPort)
Bind the source port for all outbound packets.
DIRTYCODE_API int32_t ProtoUdpConnect (ProtoUdpT *pUdp, struct sockaddr *pRemoteAddress)
Bind the remote address of the socket.
DIRTYCODE_API void ProtoUdpDestroy (ProtoUdpT *pUdp)
Destroy the UDP instance.
DIRTYCODE_API void ProtoUdpDisconnect (ProtoUdpT *pUdp)
Undo the effect of any previous ProtoUdpConnect.
DIRTYCODE_API void ProtoUdpGetLocalAddr (ProtoUdpT *pUdp, struct sockaddr_in *pLocalAddr)
Return the local IPv4 address and port that is on all outbound packets. Only works if ProtoUdpConnect has been called to bind the remote address.
DIRTYCODE_API int32_t ProtoUdpRecvFrom (ProtoUdpT *pUdp, char *pData, uint32_t uSize, struct sockaddr *pRemoteAddr)
Checks if there is a udp packet available and if so returns it.
DIRTYCODE_API int32_t ProtoUdpSend (ProtoUdpT *pUdp, const char *pData, int32_t iSize)
Send data to the host that was connected to via ProtoUdpConnect.
DIRTYCODE_API int32_t ProtoUdpSendTo (ProtoUdpT *pUdp, const char *pData, int32_t iSize, struct sockaddr *pRemoteAddr)
Send data to the specified address.
DIRTYCODE_API void ProtoUdpUpdate (ProtoUdpT *pUdp)
Do any necessary internal processing.
Detailed Description
Macro Definition Documentation
#define ProtoUdpRecv (_pUdp, _pData, _uSize) ProtoUdpRecvFrom(_pUdp, _pData, _uSize, NULL);
wrapper for ProtoUdpRecvFrom
Typedef Documentation
typedef struct ProtoUdpT ProtoUdpT
Function Documentation
DIRTYCODE_API int32_t ProtoUdpBind (ProtoUdpT * pUdp, int32_t iPort)
Bind the source port for all outbound packets.
Parameters
*pUdp - the UDP object
iPort - port
Returns
0 if the connection is successful.
Note
Should not be mixed with ProtoUdpConnect()
Version
1.0 12/11/2003 (sbevan) First Version
References NULL, ProtoUdpDisconnect(), ProtoUdpT::pSocket, SockaddrInit, SockaddrInSetPort, SocketBind(), and SocketOpen().
DIRTYCODE_API int32_t ProtoUdpConnect (ProtoUdpT * pUdp, struct sockaddr * pRemoteAddr)
Bind the remote address of the socket.
Parameters
*pUdp - the UDP object
*pRemoteAddr - the IPv4 address of the remote peer.
Returns
0 if the address can be bound, non-zero if there is an error.
Version
1.0 12/11/2003 (sbevan) First Version
References ds_memcpy_s(), NULL, ProtoUdpDisconnect(), ProtoUdpT::pSocket, ProtoUdpT::RemoteAddr, SockaddrInit, SocketBind(), and SocketOpen().
DIRTYCODE_API ProtoUdpT* ProtoUdpCreate (int32_t iMaxPacketSize, int32_t iMaxPackets)
Create a proto udp instance.
Parameters
iMaxPacketSize - max size in bytes of any packet that will received.
iMaxPackets - max number of packets that should be buffered.
Returns
0 if the UDP object cannot be created.
Note
To avoid creating lots of separate packet buffers, one large object is requested that can hold the sum of the size of the ProtoUdpT object and all the packets. For reasons to do with alignment and how the packet buffers are defined iMaxPacketSize is rounded up to the nearest multiple of 4 so this should be taken into account in any space calculations. More details on the packet format can be found in the file description.
Version
1.0 12/11/2003 (sbevan) First Version
References ProtoUdpT::crit, DirtyMemAlloc(), DirtyMemGroupQuery(), ProtoUdpT::iMemGroup, NetCritInit(), NetPrintf, NULL, ProtoUdpT::pMemGroupUserData, ProtoUdpT::pPackets, PROTOUDP_MEMID, PROTOUDP_PKTPREFIXSIZE, ProtoUdpT::pSocket, ProtoUdpT::RemoteAddr, ProtoUdpT::uMaxPacketSize, ProtoUdpT::uPacketsHead, ProtoUdpT::uPacketsTail, and ProtoUdpT::uTotalPacketSpace.
Referenced by ProtoUpnpCreate().
DIRTYCODE_API void ProtoUdpDestroy (ProtoUdpT * pUdp)
Destroy the UDP instance.
Parameters
*pUdp - the UDP object
Returns
None
Version
1.0 12/11/2003 (sbevan) First Version
References ProtoUdpT::crit, DirtyMemFree(), ProtoUdpT::iMemGroup, NetCritKill(), ProtoUdpT::pMemGroupUserData, PROTOUDP_MEMID, and ProtoUdpDisconnect().
Referenced by ProtoUpnpCreate(), and ProtoUpnpDestroy().
DIRTYCODE_API void ProtoUdpDisconnect (ProtoUdpT * pUdp)
Undo the effect of any previous ProtoUdpConnect.
Parameters
*pUdp - the UDP object
Returns
None
Note
This is here in the unlikely event that you call ProtoUdpConnect send some packets and then later decide to re-use the same ProtoUdpT for traffic destined for multiple targets and so you do not want the remote address bound or the implicit address checking that occurs on inbound packets when ProtoUdpConnect has been called.
Version
1.0 12/11/2003 (sbevan) First Version
References NULL, ProtoUdpT::pSocket, ProtoUdpT::RemoteAddr, and SocketClose().
Referenced by ProtoUdpBind(), ProtoUdpConnect(), and ProtoUdpDestroy().
DIRTYCODE_API void ProtoUdpGetLocalAddr (ProtoUdpT * pUdp, struct sockaddr_in * pLocalAddr)
Return the local IPv4 address and port that is on all outbound packets. Only works if ProtoUdpConnect has been called to bind the remote address.
Parameters
*pUdp - the UDP object
*pLocalAddr - the local IPv4 address that the socket is bound to.
Returns
None
Note
Logically the SocketInfo 'bind' call is all that should be required and that does work on Linux and Windows. However, on PS2 the SocketInfo call always returns 0 as the address for a UDP socket (works correctly for TCP). So, as a backup, SocketHost is called if the returned address is 0 and on PS2 that does determine the correct address. In the process it gets the port wrong which the SocketInfo got right so the port is saved and then restored around the SocketHost call. Perhaps should fix up PS2 SocketHost?
Version
1.0 12/11/2003 (sbevan) First Version
References NULL, ProtoUdpT::pSocket, ProtoUdpT::RemoteAddr, SocketHost(), and SocketInfo().
DIRTYCODE_API int32_t ProtoUdpRecvFrom (ProtoUdpT * pUdp, char * pBuffer, uint32_t uBufferLen, struct sockaddr * pRemoteAddr)
Checks if there is a udp packet available and if so returns it.
Parameters
*pUdp - the UDP object
*pBuffer - buffer where the received message should be written
uBufferLen - the length of the buffer
pRemoteAddr - remote address
Returns
negative on error, zero if nothing read, otherwise the length of the data read.
Version
1.0 12/11/2003 (sbevan) First Version
References ProtoUdpT::crit, ds_memcpy(), NetCritEnter(), NetCritLeave(), NULL, ProtoUdpT::pPackets, PROTOUDP_PKTPREFIXSIZE, ProtoUdpT::pSocket, ProtoUdpT::uPacketsHead, and ProtoUdpT::uPacketsTail.
Referenced by ProtoUpnpUpdate().
DIRTYCODE_API int32_t ProtoUdpSend (ProtoUdpT * pUdp, const char * pData, int32_t iSize)
Send data to the host that was connected to via ProtoUdpConnect.
Parameters
*pUdp - the UDP object
*pData - the data to send.
iSize - the length of the data.
Returns
negative if an error occurred otherwise number of bytes sent.
Version
1.0 12/11/2003 (sbevan) First Version
References NULL, ProtoUdpT::pSocket, ProtoUdpT::RemoteAddr, and SocketSendto().
DIRTYCODE_API int32_t ProtoUdpSendTo (ProtoUdpT * pUdp, const char * pData, int32_t iSize, struct sockaddr * pRemoteAddr)
Send data to the specified address.
Parameters
*pUdp - the UDP object
*pData - the data to send.
iSize - the length of the data.
pRemoteAddr - the (IPv4) address to send the data to.
Returns
negative if an error occurred otherwise number of bytes sent.
Version
1.0 12/11/2003 (sbevan) First Version
References NULL, ProtoUdpT::pSocket, and SocketSendto().
DIRTYCODE_API void ProtoUdpUpdate (ProtoUdpT * pUdp)
Do any necessary internal processing.
Parameters
*pUdp - the UDP object
Returns
None
Note
This takes care of reading a packet from the network and storing it in the packet queue. If ProtoUdpConnect was called to bind the remote address then address filtering is done and the packet is thrown away if it does not have the correct source address and port. This is a pretty weak sort of filtering and could arguably be left out.
Version
1.0 12/11/2003 (sbevan) First Version
References ProtoUdpT::crit, ds_memcpy_s(), NetCritLeave(), NetCritTry(), NULL, ProtoUdpT::pPackets, ProtoUdpT::pSocket, ProtoUdpT::RemoteAddr, SocketRecvfrom(), ProtoUdpT::uMaxPacketSize, ProtoUdpT::uPacketsHead, and ProtoUdpT::uPacketsTail.
Referenced by ProtoUpnpUpdate().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Thu Jul 9 2015 16:31:32