///////////////////////////////////////////////////////////////////////////////
// OGLFunctions.h
// 
// Copyright (c) 2012 Electronic Arts. All rights reserved.
///////////////////////////////////////////////////////////////////////////////

OGLFN(void, glAccum, (GLenum op, GLfloat value));
OGLFN(void, glAlphaFunc, (GLenum func, GLclampf ref));
OGLFN(GLboolean, glAreTexturesResident, (GLsizei n, const GLuint *textures, GLboolean *residences));
OGLFN(void, glArrayElement, (GLint i));
OGLFN(void, glBegin, (GLenum mode));
OGLFN(void, glBindTexture, (GLenum target, GLuint texture));
OGLFN(void, glBitmap, (GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap));
OGLFN(void, glBlendFunc, (GLenum sfactor, GLenum dfactor));
OGLFN(void, glCallList, (GLuint list));
OGLFN(void, glCallLists, (GLsizei n, GLenum type, const GLvoid *lists));
OGLFN(void, glClear, (GLbitfield mask));
OGLFN(void, glClearAccum, (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha));
OGLFN(void, glClearColor, (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha));
OGLFN(void, glClearDepth, (GLclampd depth));
OGLFN(void, glClearIndex, (GLfloat c));
OGLFN(void, glClearStencil, (GLint s));
OGLFN(void, glClipPlane, (GLenum plane, const GLdouble *equation));
OGLFN(void, glColor3b, (GLbyte red, GLbyte green, GLbyte blue));
OGLFN(void, glColor3bv, (const GLbyte *v));
OGLFN(void, glColor3d, (GLdouble red, GLdouble green, GLdouble blue));
OGLFN(void, glColor3dv, (const GLdouble *v));
OGLFN(void, glColor3f, (GLfloat red, GLfloat green, GLfloat blue));
OGLFN(void, glColor3fv, (const GLfloat *v));
OGLFN(void, glColor3i, (GLint red, GLint green, GLint blue));
OGLFN(void, glColor3iv, (const GLint *v));
OGLFN(void, glColor3s, (GLshort red, GLshort green, GLshort blue));
OGLFN(void, glColor3sv, (const GLshort *v));
OGLFN(void, glColor3ub, (GLubyte red, GLubyte green, GLubyte blue));
OGLFN(void, glColor3ubv, (const GLubyte *v));
OGLFN(void, glColor3ui, (GLuint red, GLuint green, GLuint blue));
OGLFN(void, glColor3uiv, (const GLuint *v));
OGLFN(void, glColor3us, (GLushort red, GLushort green, GLushort blue));
OGLFN(void, glColor3usv, (const GLushort *v));
OGLFN(void, glColor4b, (GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha));
OGLFN(void, glColor4bv, (const GLbyte *v));
OGLFN(void, glColor4d, (GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha));
OGLFN(void, glColor4dv, (const GLdouble *v));
OGLFN(void, glColor4f, (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha));
OGLFN(void, glColor4fv, (const GLfloat *v));
OGLFN(void, glColor4i, (GLint red, GLint green, GLint blue, GLint alpha));
OGLFN(void, glColor4iv, (const GLint *v));
OGLFN(void, glColor4s, (GLshort red, GLshort green, GLshort blue, GLshort alpha));
OGLFN(void, glColor4sv, (const GLshort *v));
OGLFN(void, glColor4ub, (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha));
OGLFN(void, glColor4ubv, (const GLubyte *v));
OGLFN(void, glColor4ui, (GLuint red, GLuint green, GLuint blue, GLuint alpha));
OGLFN(void, glColor4uiv, (const GLuint *v));
OGLFN(void, glColor4us, (GLushort red, GLushort green, GLushort blue, GLushort alpha));
OGLFN(void, glColor4usv, (const GLushort *v));
OGLFN(void, glColorMask, (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha));
OGLFN(void, glColorMaterial, (GLenum face, GLenum mode));
OGLFN(void, glColorPointer, (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer));
OGLFN(void, glCopyPixels, (GLint x, GLint y, GLsizei width, GLsizei height, GLenum type));
OGLFN(void, glCopyTexImage1D, (GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLint border));
OGLFN(void, glCopyTexImage2D, (GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border));
OGLFN(void, glCopyTexSubImage1D, (GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width));
OGLFN(void, glCopyTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height));
OGLFN(void, glCullFace, (GLenum mode));
OGLFN(void, glDeleteLists, (GLuint list, GLsizei range));
OGLFN(void, glDeleteTextures, (GLsizei n, const GLuint *textures));
OGLFN(void, glDepthFunc, (GLenum func));
OGLFN(void, glDepthMask, (GLboolean flag));
OGLFN(void, glDepthRange, (GLclampd zNear, GLclampd zFar));
OGLFN(void, glDisable, (GLenum cap));
OGLFN(void, glDisableClientState, (GLenum array));
OGLFN(void, glDrawArrays, (GLenum mode, GLint first, GLsizei count));
OGLFN(void, glDrawBuffer, (GLenum mode));
OGLFN(void, glDrawElements, (GLenum mode, GLsizei count, GLenum type, const GLvoid *indices));
OGLFN(void, glDrawPixels, (GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels));
OGLFN(void, glEdgeFlag, (GLboolean flag));
OGLFN(void, glEdgeFlagPointer, (GLsizei stride, const GLvoid *pointer));
OGLFN(void, glEdgeFlagv, (const GLboolean *flag));
OGLFN(void, glEnable, (GLenum cap));
OGLFN(void, glEnableClientState, (GLenum array));
OGLFN(void, glEnd, (void));
OGLFN(void, glEndList, (void));
OGLFN(void, glEvalCoord1d, (GLdouble u));
OGLFN(void, glEvalCoord1dv, (const GLdouble *u));
OGLFN(void, glEvalCoord1f, (GLfloat u));
OGLFN(void, glEvalCoord1fv, (const GLfloat *u));
OGLFN(void, glEvalCoord2d, (GLdouble u, GLdouble v));
OGLFN(void, glEvalCoord2dv, (const GLdouble *u));
OGLFN(void, glEvalCoord2f, (GLfloat u, GLfloat v));
OGLFN(void, glEvalCoord2fv, (const GLfloat *u));
OGLFN(void, glEvalMesh1, (GLenum mode, GLint i1, GLint i2));
OGLFN(void, glEvalMesh2, (GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2));
OGLFN(void, glEvalPoint1, (GLint i));
OGLFN(void, glEvalPoint2, (GLint i, GLint j));
OGLFN(void, glFeedbackBuffer, (GLsizei size, GLenum type, GLfloat *buffer));
OGLFN(void, glFinish, (void));
OGLFN(void, glFlush, (void));
OGLFN(void, glFogf, (GLenum pname, GLfloat param));
OGLFN(void, glFogfv, (GLenum pname, const GLfloat *params));
OGLFN(void, glFogi, (GLenum pname, GLint param));
OGLFN(void, glFogiv, (GLenum pname, const GLint *params));
OGLFN(void, glFrontFace, (GLenum mode));
OGLFN(void, glFrustum, (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar));
OGLFN(GLuint, glGenLists, (GLsizei range));
OGLFN(void, glGenTextures, (GLsizei n, GLuint *textures));
OGLFN(void, glGetBooleanv, (GLenum pname, GLboolean *params));
OGLFN(void, glGetClipPlane, (GLenum plane, GLdouble *equation));
OGLFN(void, glGetDoublev, (GLenum pname, GLdouble *params));
OGLFN(GLenum, glGetError, (void));
OGLFN(void, glGetFloatv, (GLenum pname, GLfloat *params));
OGLFN(void, glGetIntegerv, (GLenum pname, GLint *params));
OGLFN(void, glGetLightfv, (GLenum light, GLenum pname, GLfloat *params));
OGLFN(void, glGetLightiv, (GLenum light, GLenum pname, GLint *params));
OGLFN(void, glGetMapdv, (GLenum target, GLenum query, GLdouble *v));
OGLFN(void, glGetMapfv, (GLenum target, GLenum query, GLfloat *v));
OGLFN(void, glGetMapiv, (GLenum target, GLenum query, GLint *v));
OGLFN(void, glGetMaterialfv, (GLenum face, GLenum pname, GLfloat *params));
OGLFN(void, glGetMaterialiv, (GLenum face, GLenum pname, GLint *params));
OGLFN(void, glGetPixelMapfv, (GLenum map, GLfloat *values));
OGLFN(void, glGetPixelMapuiv, (GLenum map, GLuint *values));
OGLFN(void, glGetPixelMapusv, (GLenum map, GLushort *values));
OGLFN(void, glGetPointerv, (GLenum pname, GLvoid* *params));
OGLFN(void, glGetPolygonStipple, (GLubyte *mask));
OGLFN(const GLubyte *, glGetString, (GLenum name));
OGLFN(void, glGetTexEnvfv, (GLenum target, GLenum pname, GLfloat *params));
OGLFN(void, glGetTexEnviv, (GLenum target, GLenum pname, GLint *params));
OGLFN(void, glGetTexGendv, (GLenum coord, GLenum pname, GLdouble *params));
OGLFN(void, glGetTexGenfv, (GLenum coord, GLenum pname, GLfloat *params));
OGLFN(void, glGetTexGeniv, (GLenum coord, GLenum pname, GLint *params));
OGLFN(void, glGetTexImage, (GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels));
OGLFN(void, glGetTexLevelParameterfv, (GLenum target, GLint level, GLenum pname, GLfloat *params));
OGLFN(void, glGetTexLevelParameteriv, (GLenum target, GLint level, GLenum pname, GLint *params));
OGLFN(void, glGetTexParameterfv, (GLenum target, GLenum pname, GLfloat *params));
OGLFN(void, glGetTexParameteriv, (GLenum target, GLenum pname, GLint *params));
OGLFN(void, glHint, (GLenum target, GLenum mode));
OGLFN(void, glIndexMask, (GLuint mask));
OGLFN(void, glIndexPointer, (GLenum type, GLsizei stride, const GLvoid *pointer));
OGLFN(void, glIndexd, (GLdouble c));
OGLFN(void, glIndexdv, (const GLdouble *c));
OGLFN(void, glIndexf, (GLfloat c));
OGLFN(void, glIndexfv, (const GLfloat *c));
OGLFN(void, glIndexi, (GLint c));
OGLFN(void, glIndexiv, (const GLint *c));
OGLFN(void, glIndexs, (GLshort c));
OGLFN(void, glIndexsv, (const GLshort *c));
OGLFN(void, glIndexub, (GLubyte c));
OGLFN(void, glIndexubv, (const GLubyte *c));
OGLFN(void, glInitNames, (void));
OGLFN(void, glInterleavedArrays, (GLenum format, GLsizei stride, const GLvoid *pointer));
OGLFN(GLboolean, glIsEnabled, (GLenum cap));
OGLFN(GLboolean, glIsList, (GLuint list));
OGLFN(GLboolean, glIsTexture, (GLuint texture));
OGLFN(void, glLightModelf, (GLenum pname, GLfloat param));
OGLFN(void, glLightModelfv, (GLenum pname, const GLfloat *params));
OGLFN(void, glLightModeli, (GLenum pname, GLint param));
OGLFN(void, glLightModeliv, (GLenum pname, const GLint *params));
OGLFN(void, glLightf, (GLenum light, GLenum pname, GLfloat param));
OGLFN(void, glLightfv, (GLenum light, GLenum pname, const GLfloat *params));
OGLFN(void, glLighti, (GLenum light, GLenum pname, GLint param));
OGLFN(void, glLightiv, (GLenum light, GLenum pname, const GLint *params));
OGLFN(void, glLineStipple, (GLint factor, GLushort pattern));
OGLFN(void, glLineWidth, (GLfloat width));
OGLFN(void, glListBase, (GLuint base));
OGLFN(void, glLoadIdentity, (void));
OGLFN(void, glLoadMatrixd, (const GLdouble *m));
OGLFN(void, glLoadMatrixf, (const GLfloat *m));
OGLFN(void, glLoadName, (GLuint name));
OGLFN(void, glLogicOp, (GLenum opcode));
OGLFN(void, glMap1d, (GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points));
OGLFN(void, glMap1f, (GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points));
OGLFN(void, glMap2d, (GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points));
OGLFN(void, glMap2f, (GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points));
OGLFN(void, glMapGrid1d, (GLint un, GLdouble u1, GLdouble u2));
OGLFN(void, glMapGrid1f, (GLint un, GLfloat u1, GLfloat u2));
OGLFN(void, glMapGrid2d, (GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2));
OGLFN(void, glMapGrid2f, (GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2));
OGLFN(void, glMaterialf, (GLenum face, GLenum pname, GLfloat param));
OGLFN(void, glMaterialfv, (GLenum face, GLenum pname, const GLfloat *params));
OGLFN(void, glMateriali, (GLenum face, GLenum pname, GLint param));
OGLFN(void, glMaterialiv, (GLenum face, GLenum pname, const GLint *params));
OGLFN(void, glMatrixMode, (GLenum mode));
OGLFN(void, glMultMatrixd, (const GLdouble *m));
OGLFN(void, glMultMatrixf, (const GLfloat *m));
OGLFN(void, glNewList, (GLuint list, GLenum mode));
OGLFN(void, glNormal3b, (GLbyte nx, GLbyte ny, GLbyte nz));
OGLFN(void, glNormal3bv, (const GLbyte *v));
OGLFN(void, glNormal3d, (GLdouble nx, GLdouble ny, GLdouble nz));
OGLFN(void, glNormal3dv, (const GLdouble *v));
OGLFN(void, glNormal3f, (GLfloat nx, GLfloat ny, GLfloat nz));
OGLFN(void, glNormal3fv, (const GLfloat *v));
OGLFN(void, glNormal3i, (GLint nx, GLint ny, GLint nz));
OGLFN(void, glNormal3iv, (const GLint *v));
OGLFN(void, glNormal3s, (GLshort nx, GLshort ny, GLshort nz));
OGLFN(void, glNormal3sv, (const GLshort *v));
OGLFN(void, glNormalPointer, (GLenum type, GLsizei stride, const GLvoid *pointer));
OGLFN(void, glOrtho, (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar));
OGLFN(void, glPassThrough, (GLfloat token));
OGLFN(void, glPixelMapfv, (GLenum map, GLsizei mapsize, const GLfloat *values));
OGLFN(void, glPixelMapuiv, (GLenum map, GLsizei mapsize, const GLuint *values));
OGLFN(void, glPixelMapusv, (GLenum map, GLsizei mapsize, const GLushort *values));
OGLFN(void, glPixelStoref, (GLenum pname, GLfloat param));
OGLFN(void, glPixelStorei, (GLenum pname, GLint param));
OGLFN(void, glPixelTransferf, (GLenum pname, GLfloat param));
OGLFN(void, glPixelTransferi, (GLenum pname, GLint param));
OGLFN(void, glPixelZoom, (GLfloat xfactor, GLfloat yfactor));
OGLFN(void, glPointSize, (GLfloat size));
OGLFN(void, glPolygonMode, (GLenum face, GLenum mode));
OGLFN(void, glPolygonOffset, (GLfloat factor, GLfloat units));
OGLFN(void, glPolygonStipple, (const GLubyte *mask));
OGLFN(void, glPopAttrib, (void));
OGLFN(void, glPopClientAttrib, (void));
OGLFN(void, glPopMatrix, (void));
OGLFN(void, glPopName, (void));
OGLFN(void, glPrioritizeTextures, (GLsizei n, const GLuint *textures, const GLclampf *priorities));
OGLFN(void, glPushAttrib, (GLbitfield mask));
OGLFN(void, glPushClientAttrib, (GLbitfield mask));
OGLFN(void, glPushMatrix, (void));
OGLFN(void, glPushName, (GLuint name));
OGLFN(void, glRasterPos2d, (GLdouble x, GLdouble y));
OGLFN(void, glRasterPos2dv, (const GLdouble *v));
OGLFN(void, glRasterPos2f, (GLfloat x, GLfloat y));
OGLFN(void, glRasterPos2fv, (const GLfloat *v));
OGLFN(void, glRasterPos2i, (GLint x, GLint y));
OGLFN(void, glRasterPos2iv, (const GLint *v));
OGLFN(void, glRasterPos2s, (GLshort x, GLshort y));
OGLFN(void, glRasterPos2sv, (const GLshort *v));
OGLFN(void, glRasterPos3d, (GLdouble x, GLdouble y, GLdouble z));
OGLFN(void, glRasterPos3dv, (const GLdouble *v));
OGLFN(void, glRasterPos3f, (GLfloat x, GLfloat y, GLfloat z));
OGLFN(void, glRasterPos3fv, (const GLfloat *v));
OGLFN(void, glRasterPos3i, (GLint x, GLint y, GLint z));
OGLFN(void, glRasterPos3iv, (const GLint *v));
OGLFN(void, glRasterPos3s, (GLshort x, GLshort y, GLshort z));
OGLFN(void, glRasterPos3sv, (const GLshort *v));
OGLFN(void, glRasterPos4d, (GLdouble x, GLdouble y, GLdouble z, GLdouble w));
OGLFN(void, glRasterPos4dv, (const GLdouble *v));
OGLFN(void, glRasterPos4f, (GLfloat x, GLfloat y, GLfloat z, GLfloat w));
OGLFN(void, glRasterPos4fv, (const GLfloat *v));
OGLFN(void, glRasterPos4i, (GLint x, GLint y, GLint z, GLint w));
OGLFN(void, glRasterPos4iv, (const GLint *v));
OGLFN(void, glRasterPos4s, (GLshort x, GLshort y, GLshort z, GLshort w));
OGLFN(void, glRasterPos4sv, (const GLshort *v));
OGLFN(void, glReadBuffer, (GLenum mode));
OGLFN(void, glReadPixels, (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels));
OGLFN(void, glRectd, (GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2));
OGLFN(void, glRectdv, (const GLdouble *v1, const GLdouble *v2));
OGLFN(void, glRectf, (GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2));
OGLFN(void, glRectfv, (const GLfloat *v1, const GLfloat *v2));
OGLFN(void, glRecti, (GLint x1, GLint y1, GLint x2, GLint y2));
OGLFN(void, glRectiv, (const GLint *v1, const GLint *v2));
OGLFN(void, glRects, (GLshort x1, GLshort y1, GLshort x2, GLshort y2));
OGLFN(void, glRectsv, (const GLshort *v1, const GLshort *v2));
OGLFN(GLint, glRenderMode, (GLenum mode));
OGLFN(void, glRotated, (GLdouble angle, GLdouble x, GLdouble y, GLdouble z));
OGLFN(void, glRotatef, (GLfloat angle, GLfloat x, GLfloat y, GLfloat z));
OGLFN(void, glScaled, (GLdouble x, GLdouble y, GLdouble z));
OGLFN(void, glScalef, (GLfloat x, GLfloat y, GLfloat z));
OGLFN(void, glScissor, (GLint x, GLint y, GLsizei width, GLsizei height));
OGLFN(void, glSelectBuffer, (GLsizei size, GLuint *buffer));
OGLFN(void, glShadeModel, (GLenum mode));
OGLFN(void, glStencilFunc, (GLenum func, GLint ref, GLuint mask));
OGLFN(void, glStencilMask, (GLuint mask));
OGLFN(void, glStencilOp, (GLenum fail, GLenum zfail, GLenum zpass));
OGLFN(void, glTexCoord1d, (GLdouble s));
OGLFN(void, glTexCoord1dv, (const GLdouble *v));
OGLFN(void, glTexCoord1f, (GLfloat s));
OGLFN(void, glTexCoord1fv, (const GLfloat *v));
OGLFN(void, glTexCoord1i, (GLint s));
OGLFN(void, glTexCoord1iv, (const GLint *v));
OGLFN(void, glTexCoord1s, (GLshort s));
OGLFN(void, glTexCoord1sv, (const GLshort *v));
OGLFN(void, glTexCoord2d, (GLdouble s, GLdouble t));
OGLFN(void, glTexCoord2dv, (const GLdouble *v));
OGLFN(void, glTexCoord2f, (GLfloat s, GLfloat t));
OGLFN(void, glTexCoord2fv, (const GLfloat *v));
OGLFN(void, glTexCoord2i, (GLint s, GLint t));
OGLFN(void, glTexCoord2iv, (const GLint *v));
OGLFN(void, glTexCoord2s, (GLshort s, GLshort t));
OGLFN(void, glTexCoord2sv, (const GLshort *v));
OGLFN(void, glTexCoord3d, (GLdouble s, GLdouble t, GLdouble r));
OGLFN(void, glTexCoord3dv, (const GLdouble *v));
OGLFN(void, glTexCoord3f, (GLfloat s, GLfloat t, GLfloat r));
OGLFN(void, glTexCoord3fv, (const GLfloat *v));
OGLFN(void, glTexCoord3i, (GLint s, GLint t, GLint r));
OGLFN(void, glTexCoord3iv, (const GLint *v));
OGLFN(void, glTexCoord3s, (GLshort s, GLshort t, GLshort r));
OGLFN(void, glTexCoord3sv, (const GLshort *v));
OGLFN(void, glTexCoord4d, (GLdouble s, GLdouble t, GLdouble r, GLdouble q));
OGLFN(void, glTexCoord4dv, (const GLdouble *v));
OGLFN(void, glTexCoord4f, (GLfloat s, GLfloat t, GLfloat r, GLfloat q));
OGLFN(void, glTexCoord4fv, (const GLfloat *v));
OGLFN(void, glTexCoord4i, (GLint s, GLint t, GLint r, GLint q));
OGLFN(void, glTexCoord4iv, (const GLint *v));
OGLFN(void, glTexCoord4s, (GLshort s, GLshort t, GLshort r, GLshort q));
OGLFN(void, glTexCoord4sv, (const GLshort *v));
OGLFN(void, glTexCoordPointer, (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer));
OGLFN(void, glTexEnvf, (GLenum target, GLenum pname, GLfloat param));
OGLFN(void, glTexEnvfv, (GLenum target, GLenum pname, const GLfloat *params));
OGLFN(void, glTexEnvi, (GLenum target, GLenum pname, GLint param));
OGLFN(void, glTexEnviv, (GLenum target, GLenum pname, const GLint *params));
OGLFN(void, glTexGend, (GLenum coord, GLenum pname, GLdouble param));
OGLFN(void, glTexGendv, (GLenum coord, GLenum pname, const GLdouble *params));
OGLFN(void, glTexGenf, (GLenum coord, GLenum pname, GLfloat param));
OGLFN(void, glTexGenfv, (GLenum coord, GLenum pname, const GLfloat *params));
OGLFN(void, glTexGeni, (GLenum coord, GLenum pname, GLint param));
OGLFN(void, glTexGeniv, (GLenum coord, GLenum pname, const GLint *params));
OGLFN(void, glTexImage1D, (GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels));
OGLFN(void, glTexImage2D, (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels));
OGLFN(void, glTexParameterf, (GLenum target, GLenum pname, GLfloat param));
OGLFN(void, glTexParameterfv, (GLenum target, GLenum pname, const GLfloat *params));
OGLFN(void, glTexParameteri, (GLenum target, GLenum pname, GLint param));
OGLFN(void, glTexParameteriv, (GLenum target, GLenum pname, const GLint *params));
OGLFN(void, glTexSubImage1D, (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels));
OGLFN(void, glTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels));
OGLFN(void, glTranslated, (GLdouble x, GLdouble y, GLdouble z));
OGLFN(void, glTranslatef, (GLfloat x, GLfloat y, GLfloat z));
OGLFN(void, glVertex2d, (GLdouble x, GLdouble y));
OGLFN(void, glVertex2dv, (const GLdouble *v));
OGLFN(void, glVertex2f, (GLfloat x, GLfloat y));
OGLFN(void, glVertex2fv, (const GLfloat *v));
OGLFN(void, glVertex2i, (GLint x, GLint y));
OGLFN(void, glVertex2iv, (const GLint *v));
OGLFN(void, glVertex2s, (GLshort x, GLshort y));
OGLFN(void, glVertex2sv, (const GLshort *v));
OGLFN(void, glVertex3d, (GLdouble x, GLdouble y, GLdouble z));
OGLFN(void, glVertex3dv, (const GLdouble *v));
OGLFN(void, glVertex3f, (GLfloat x, GLfloat y, GLfloat z));
OGLFN(void, glVertex3fv, (const GLfloat *v));
OGLFN(void, glVertex3i, (GLint x, GLint y, GLint z));
OGLFN(void, glVertex3iv, (const GLint *v));
OGLFN(void, glVertex3s, (GLshort x, GLshort y, GLshort z));
OGLFN(void, glVertex3sv, (const GLshort *v));
OGLFN(void, glVertex4d, (GLdouble x, GLdouble y, GLdouble z, GLdouble w));
OGLFN(void, glVertex4dv, (const GLdouble *v));
OGLFN(void, glVertex4f, (GLfloat x, GLfloat y, GLfloat z, GLfloat w));
OGLFN(void, glVertex4fv, (const GLfloat *v));
OGLFN(void, glVertex4i, (GLint x, GLint y, GLint z, GLint w));
OGLFN(void, glVertex4iv, (const GLint *v));
OGLFN(void, glVertex4s, (GLshort x, GLshort y, GLshort z, GLshort w));
OGLFN(void, glVertex4sv, (const GLshort *v));
OGLFN(void, glVertexPointer, (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer));
OGLFN(void, glViewport, (GLint x, GLint y, GLsizei width, GLsizei height));

OGLFN(BOOL, wglCopyContext, (HGLRC, HGLRC, UINT));
OGLFN(HGLRC, wglCreateContext, (HDC));
OGLFN(HGLRC, wglCreateLayerContext, (HDC, int));
OGLFN(BOOL, wglDeleteContext, (HGLRC));
OGLFN(HGLRC, wglGetCurrentContext, (VOID));
OGLFN(HDC, wglGetCurrentDC, (VOID));
OGLFN(PROC, wglGetProcAddress, (LPCSTR));
OGLFN(BOOL, wglMakeCurrent, (HDC, HGLRC));
OGLFN(BOOL, wglShareLists, (HGLRC, HGLRC));
OGLFN(BOOL, wglUseFontBitmapsA, (HDC, DWORD, DWORD, DWORD));
OGLFN(BOOL, wglUseFontBitmapsW, (HDC, DWORD, DWORD, DWORD));
OGLFN(BOOL, wglSwapBuffers, (HDC));
OGLFN(BOOL, wglSwapLayerBuffers, (HDC, UINT));
