DirtySock: voipcommon.h File Reference
voipcommon.h File Reference
Cross-platform voip data types and private functions.
#include "voipconnection.h"
#include "voipheadset.h"
#include "DirtySDK/voip/voip.h"
Data Structures
struct VoipCommonRefT
Typedefs
typedef struct VoipCommonRefT VoipCommonRefT
Functions
VoipRefT * VoipCommonGetRef (void)
Return current module reference.
VoipRefT * VoipCommonStartup (int32_t iMaxPeers, int32_t iVoipRefSize, VoipHeadsetMicDataCbT *pMicDataCb, VoipHeadsetStatusCbT *pStatusCb, int32_t iData)
Start up common functionality.
void VoipCommonShutdown (VoipCommonRefT *pVoipCommon)
Shutdown common functionality.
void VoipCommonUpdateRemoteStatus (VoipCommonRefT *pVoipCommon)
Process mute list, and set appropriate flags/priority for each remote user.
int32_t VoipCommonStatus (VoipCommonRefT *pVoipCommon, int32_t iSelect, int32_t iValue, void *pBuf, int32_t iBufSize)
Return status.
int32_t VoipCommonControl (VoipCommonRefT *pVoipCommon, int32_t iControl, int32_t iValue, void *pValue)
Set control options.
void VoipCommonAddMask (uint32_t *pMask, uint32_t uAddMask, const char *pMaskName)
Add (OR) uAddMask into *pMask.
void VoipCommonDelMask (uint32_t *pMask, uint32_t uDelMask, const char *pMaskName)
Del (&~) uDelMask from *pMask.
void VoipCommonSetMask (uint32_t *pMask, uint32_t uNewMask, const char *pMaskName)
Set value of mask (with logging).
int32_t VoipCommonSelectChannel (VoipCommonRefT *pVoip, int32_t iUserIndex, int32_t iChannel, VoipChanModeE eMode)
Select the mode(send/recv) of a given channel.
void VoipCommonResetChannels (VoipCommonRefT *pVoip, int32_t iUserIndex)
Resets the channels selection to defaults. Sends and receives to all.
void VoipCommonApplyChannelConfig (VoipCommonRefT *pVoip)
Setup user muting flags based on channel config.
void VoipCommonProcessChannelChange (VoipCommonRefT *pVoipCommon, int32_t iConnID)
Unpacks the channel selection received by a remote machine.
Detailed Description
Cross-platform voip data types and private functions.
Attention
Copyright (c) 2009 Electronic Arts Inc.
Version
12/02/2009 (jbrookes) First Version
Typedef Documentation
typedef struct VoipCommonRefT VoipCommonRefT
Function Documentation
void VoipCommonAddMask (uint32_t * pMask, uint32_t uAddMask, const char * pMaskName)
Add (OR) uAddMask into *pMask.
Parameters
*pMask - mask to add into
uAddMask - mask to add (OR)
*pMaskName - name of mask (for debug logging)
Version
12/03/2009 (jbrookes)
References VoipCommonSetMask().
void VoipCommonApplyChannelConfig (VoipCommonRefT * pVoipCommon)
Setup user muting flags based on channel config.
Parameters
*pVoipCommon - voip module state
Version
12/02/2009 (jrainy)
References VoipCommonRefT::Connectionlist, VoipConnectionT::eState, NetPrintf, VoipConnectionlistT::pConnections, VoipCommonRefT::pHeadset, VoipCommonRefT::uChanRecvMask, VoipCommonRefT::uChanSendMask, VoipCommonRefT::uRemoteChannelSelection, VOIP_CHANRECV, VOIP_CHANSEND, VOIP_MAXLOCALUSERS_EXTENDED, VoipControl(), VoipGetRef(), VoipHeadsetStatus(), and VoipStatus().
Referenced by VoipCommonProcessChannelChange().
int32_t VoipCommonControl (VoipCommonRefT * pVoipCommon, int32_t iControl, int32_t iValue, void * pValue)
Set control options.
Parameters
*pVoipCommon - voip common state
iControl - control selector
iValue - selector-specific input
*pValue - selector-specific input
Returns
int32_t - selector-specific output
Note
iControl can be one of the following:
        'ases' - add session id to the set of sessions sharing this connnection
        'chan' - set the active voip channel (coded value of channels and modes)
        'clid' - set local client id
        'conm' - for voip via voip server, maps a local conn id to a voip server conn id
        'dses' - delete session id from the set of sessions sharing this connnection
        'flsh' - send currently queued voice data immediately (iValue=connection id)
        'shch' - turn on or the of the default shared channel config. iValue = TRUE to turn, FALSE to turn off
        'time' - set data timeout in milliseconds
        'umic' - select which peers to send voice to
        'uspk' - Select which peers to accept voice from
Unhandled selectors are passed through to VoipHeadsetControl()
Version
03/02/2004 (jbrookes)
References VoipConnectionlistT::aChannels, VoipCommonRefT::bApplyChannelConfig, VoipCommonRefT::bUseDefaultSharedChannelConfig, VoipCommonRefT::Connectionlist, VoipConnectionT::eState, VoipConnectionlistT::iDataTimeout, VoipConnectionT::iVoipServerConnId, NetCritEnter(), NetCritLeave(), NetPrintf, VoipConnectionlistT::pConnections, VoipCommonRefT::pHeadset, VoipCommonRefT::ThreadCrit, TRUE, VoipConnectionlistT::uClientId, VoipConnectionT::uLocalClientId, VoipCommonRefT::uUserMicrValue, VoipCommonRefT::uUserSpkrValue, VOIP_SHARED_USER_INDEX, VoipConnectionAddSessionId(), VoipConnectionDeleteSessionId(), VoipConnectionFlush(), and VoipHeadsetControl().
Referenced by VoipControl().
void VoipCommonDelMask (uint32_t * pMask, uint32_t uDelMask, const char * pMaskName)
Del (&~) uDelMask from *pMask.
Parameters
*pMask - mask to del from
uDelMask - mask to del (&~)
*pMaskName - name of mask (for debug logging)
Version
12/03/2009 (jbrookes)
References VoipCommonSetMask().
Referenced by VoipConnectionRemove().
VoipRefT* VoipCommonGetRef (void)
Return current module reference.
Returns
VoipRefT * - reference pointer, or NULL if the module is not active
Version
03/08/2004 (jbrookes)
Referenced by VoipGetRef().
void VoipCommonProcessChannelChange (VoipCommonRefT * pVoipCommon, int32_t iConnId)
Unpacks the channel selection received by a remote machine.
Parameters
pVoipCommon - voip common state
iConnId - connection id
Version
12/07/2009 (jrainy)
References NetPrintf, VoipCommonRefT::uRemoteChannelSelection, VOIP_MAXLOCALUSERS_EXTENDED, VoipCommonApplyChannelConfig(), VoipGetRef(), and VoipStatus().
void VoipCommonResetChannels (VoipCommonRefT * pVoipCommon, int32_t iUserIndex)
Resets the channels selection to defaults. Sends and receives to all.
Parameters
*pVoipCommon - voip common state
iUserIndex - local user index
Version
12/07/2009 (jrainy)
References VoipCommonRefT::bApplyChannelConfig, VoipCommonRefT::bUseDefaultSharedChannelConfig, VoipCommonRefT::iLocalChannels, NetPrintf, TRUE, VoipCommonRefT::uLocalChannelSelection, VoipCommonRefT::uLocalModes, VOIP_MAX_CONCURRENT_CHANNEL, VOIP_SHARED_USER_INDEX, VoipControl(), and VoipGetRef().
Referenced by VoipResetChannels().
int32_t VoipCommonSelectChannel (VoipCommonRefT * pVoipCommon, int32_t iUserIndex, int32_t iChannel, VoipChanModeE eMode)
Select the mode(send/recv) of a given channel.
Parameters
*pVoipCommon - common module state
iUserIndex - local user index
iChannel - Channel ID (valid range: [0,63])
eMode - The mode, combination of VOIP_CHANSEND, VOIP_CHANRECV
Returns
int32_t - number of channels remaining that this console could join
Version
01/31/2007 (jrainy)
References VoipCommonRefT::bApplyChannelConfig, VoipCommonRefT::iCustomSharedChannels, VoipCommonRefT::iLocalChannels, NetPrintf, TRUE, VoipCommonRefT::uCustomSharedModes, VoipCommonRefT::uLocalChannelSelection, VoipCommonRefT::uLocalModes, VOIP_CHANNONE, VOIP_CHANSENDRECV, VOIP_MAX_CONCURRENT_CHANNEL, VOIP_SHARED_USER_INDEX, VoipControl(), and VoipGetRef().
Referenced by VoipSelectChannel().
void VoipCommonSetMask (uint32_t * pMask, uint32_t uNewMask, const char * pMaskName)
Set value of mask (with logging).
Parameters
*pMask - mask to write to
uNewMask - new mask value
*pMaskName - name of mask (for debug logging)
Version
12/03/2009 (jbrookes)
References NetPrintf.
Referenced by VoipCommonAddMask(), VoipCommonDelMask(), VoipConnectionSetRecvMask(), and VoipConnectionSetSendMask().
void VoipCommonShutdown (VoipCommonRefT * pVoipCommon)
Shutdown common functionality.
Parameters
*pVoipCommon - common module state
Version
12/02/2009 (jbrookes)
References VoipCommonRefT::Connectionlist, DirtyMemFree(), NetConnIdleDel(), NetCritKill(), VoipCommonRefT::pHeadset, VoipCommonRefT::ThreadCrit, VOIP_MEMID, VoipConnectionShutdown(), VoipHeadsetDestroy(), and VoipMemGroupQuery().
Referenced by VoipShutdown().
VoipRefT* VoipCommonStartup (int32_t iMaxPeers, int32_t iVoipRefSize, VoipHeadsetMicDataCbT * pMicDataCb, VoipHeadsetStatusCbT * pStatusCb, int32_t iData)
Start up common functionality.
Parameters
iMaxPeers - maximum number of peers supported (up to VOIP_MAXCONNECT)
iVoipRefSize - size of voip ref to allocate
*pMicDataCb - mic data ready callback
*pStatusCb - headset status callback
iData - platform-specific
Returns
VoipRefT * - voip ref if successful; else NULL
Version
12/02/2009 (jbrookes)
References VoipCommonRefT::bUseDefaultSharedChannelConfig, VoipCommonRefT::Connectionlist, DirtyMemAlloc(), DirtyMemFree(), DirtyMemGroupQuery(), NetConnIdleAdd(), NetCritInit(), NetCritKill(), NetPrintf, VoipCommonRefT::pHeadset, VoipCommonRefT::ThreadCrit, TRUE, VoipCommonRefT::uLastFrom, VoipCommonRefT::uLastLocalStatus, VoipConnectionlistT::uLocalUserStatus, VoipConnectionlistT::uRecvVoice, VoipCommonRefT::uUserMicrValue, VoipCommonRefT::uUserSpkrValue, VOIP_MAXLOCALUSERS, VOIP_MEMID, VoipConnectionSetCallbacks(), VoipConnectionStartup(), VoipHeadsetCreate(), VoipHeadsetReceiveVoiceDataCb(), VoipHeadsetRegisterUserCb(), VoipMemGroupSet(), and VoipSetEventCallback().
Referenced by VoipStartup().
int32_t VoipCommonStatus (VoipCommonRefT * pVoipCommon, int32_t iSelect, int32_t iValue, void * pBuf, int32_t iBufSize)
Return status.
Parameters
*pVoipCommon - voip common state
iSelect - status selector
iValue - selector-specific
*pBuf - [out] storage for selector-specific output
iBufSize - size of output buffer
Returns
int32_t - selector-specific data
Note
Allowed selectors:
        'avlb' - whether a given ConnID is available
        'chan' - retrieve the active voip channel (coded value of channels and modes)
        'chnc' - return the count of channel slots used by the voip group manager
        'chnl' - return the channel id and channel mode associated with specified channel slot
        'from' - bitfield indicating which peers are talking
        'hset' - bitfield indicating which ports have headsets
        'lprt' - return local socket port
        'luid' - return user id of specified local user
        'maxc' - return max connections
        'mgrp' - voip memgroup user id
        'mgud' - voip memgroup user data
        'micr' - who we're sending voice to
        'rchn' - retrieve the active voip channel of a remote peer (coded value of channels and modes)
        'ruid' - return user id of specified remote user index for specified connection
        'shch' - return bUseDefaultSharedChannelConfig which indicates if the default shared channel config is used
        'sock' - voip socket ref
        'spkr' - who we're accepting voice from
        'umic' - user-specified microphone send list
        'uspk' - user-specified microphone recv list
Version
12/02/2009 (jbrookes)
References VoipConnectionlistT::aChannels, VoipConnectionT::aRecvChannels, VoipCommonRefT::bUseDefaultSharedChannelConfig, VoipCommonRefT::Connectionlist, ds_memcpy(), VoipConnectionT::eState, VoipCommonRefT::iLocalChannels, VoipConnectionlistT::iMaxConnections, VoipConnectionlistT::LocalUsers, NetPrintf, VoipConnectionlistT::pConnections, VoipCommonRefT::pHeadset, VoipConnectionlistT::pSocket, VoipConnectionT::RemoteUsers, VoipConnectionlistT::uBindPort, VoipCommonRefT::uLocalModes, VoipCommonRefT::uPortHeadsetStatus, VoipConnectionlistT::uRecvMask, VoipConnectionlistT::uRecvVoice, VoipConnectionlistT::uSendMask, VoipCommonRefT::uUserMicrValue, VoipCommonRefT::uUserSpkrValue, VOIP_NullUser, VoipConnectionCanAllocate(), VoipHeadsetStatus(), and VoipMemGroupQuery().
Referenced by VoipStatus().
void VoipCommonUpdateRemoteStatus (VoipCommonRefT * pVoipCommon)
Process mute list, and set appropriate flags/priority for each remote user.
Parameters
*pVoipCommon - pointer to module state
Version
08/23/2005 (jbrookes)
References VoipCommonRefT::bPrivileged, VoipCommonRefT::Connectionlist, VoipConnectionT::eState, VoipConnectionlistT::iMaxConnections, VoipConnectionlistT::pConnections, VoipConnectionlistT::uRecvMask, VoipConnectionlistT::uSendMask, VoipConnectionlistT::uUserRecvMask, VoipConnectionlistT::uUserSendMask, VoipConnectionSetRecvMask(), and VoipConnectionSetSendMask().
EA Digital Platform © 2014 Electronic Arts Inc.
Generated on: Fri Oct 21 2016 13:35:47